### ISSUE TITLE
Certain machines aren't assembling?

### ISSUE THREAD

**Issue by HyperMan19680** [zmaster587/AdvancedRocketry#1]
I tried the Arc Furnace, and assembled it all properly, but nothing is happening.
I noticed the same with the Observatory, with no sign of where to place the Observatory block afterwards. Perhaps a mod is replacing the air block?

**Comment by zmaster587** [comment]
can you post an image of the machine from several angles please?

**Comment by zerotheliger** [comment]
could i please have a list of mods? as well as a few pictures?

**Comment by HyperMan19680** [comment]
![2015-09-30_01 09 07](https://cloud.githubusercontent.com/assets/4326246/10185889/08409bc0-6712-11e5-994e-a839a24e9c78.png)
![2015-09-30_01 09 19](https://cloud.githubusercontent.com/assets/4326246/10185888/083f6a5c-6712-11e5-9170-17083ea9bf02.png)
![2015-09-30_01 09 29](https://cloud.githubusercontent.com/assets/4326246/10185890/0843c1a6-6712-11e5-8bf6-d56e659698c6.png)

As far as mods, I removed quite a lot of them to try and fix the problem with the Furnace. It didn't work. The problem with the Observatory was a bit embrassing as I noticed the problem after reconstruction on my test world.

Mods List (from NEIIntegrations Data Dump)

ID,Name,Version,Custom Container,Disableable,Dependencies
mcp,Minecraft Coder Pack,9.05,true,YES,[]
FML,Forge Mod Loader,7.10.99.99,true,NEVER,[]
Forge,Minecraft Forge,10.13.4.1492,true,NEVER,[]
CodeChickenCore,CodeChicken Core,1.0.7.47,true,NEVER,[]
NotEnoughItems,Not Enough Items,1.0.5.111,true,NEVER,"[CodeChickenCore@[1.0.7,)]"
OpenEye,OpenEye,0.6,true,NEVER,[]
OpenModsCore,OpenModsCore,0.8,true,NEVER,[]
<CoFH ASM>,CoFH ASM,000,true,NEVER,[]
CoFHCore,CoFH Core,1.7.10R3.0.3,false,DEPENDENCIES,"[Forge@[10.13.3.1448,10.14)]"
libVulpes,Vulpes library,0.0.2,false,DEPENDENCIES,"[CoFHCore, RotaryCraft, GalacticraftCore, tconstruct]"
advancedRocketry,Advanced Rocketry,0.0.1b,false,RESTART,[libVulpes]
antiidconflict,Anti Id Conflict,1.1,false,RESTART,[]
BuildCraft|Core,BuildCraft,7.0.25,false,DEPENDENCIES,"[Forge@[10.13.2.1236,)]"
BuildCraft|Builders,BC Builders,7.0.25,false,RESTART,[BuildCraft|Core@7.0.25]
BuildCraft|Transport,BC Transport,7.0.25,false,RESTART,[BuildCraft|Core@7.0.25]
BuildCraft|Energy,BC Energy,7.0.25,false,RESTART,[BuildCraft|Core@7.0.25]
BuildCraft|Silicon,BC Silicon,7.0.25,false,RESTART,[BuildCraft|Core@7.0.25]
BuildCraft|Robotics,BC Robotics,7.0.25,false,RESTART,[BuildCraft|Core@7.0.25]
BuildCraft|Factory,BC Factory,7.0.25,false,RESTART,[BuildCraft|Core@7.0.25]
BuildCraft|Compat,BuildCraft Compat,7.0.12,false,RESTART,"[Forge@[10.13.0.1179,), BuildCraft|Core, Forestry, BuildCraft|Transport, BuildCraft|Builders]"
endercore,EnderCore,1.7.10-0.1.0.24_beta,false,DEPENDENCIES,[ttCore]
ForgeMultipart,Forge Multipart,1.1.0.309,false,DEPENDENCIES,[]
McMultipart,Minecraft Multipart Plugin,1.1.0.309,false,RESTART,[]
HelpFixer,HelpFixer,1.0.7,false,RESTART,[]
NEIAddons,NEI Addons,1.12.11.36,false,RESTART,[NotEnoughItems]
NEIAddons|Developer,NEI Addons: Developer Tools,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|AppEng,NEI Addons: Applied Energistics 2,1.12.11.36,false,RESTART,"[NEIAddons, appliedenergistics2]"
NEIAddons|Botany,NEI Addons: Botany,1.12.11.36,false,RESTART,"[NEIAddons, Botany]"
NEIAddons|Forestry,NEI Addons: Forestry,1.12.11.36,false,RESTART,"[NEIAddons, Forestry]"
NEIAddons|CraftingTables,NEI Addons: Crafting Tables,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|ExNihilo,NEI Addons: Ex Nihilo,1.12.11.36,false,RESTART,[exnihilo]
neiintegration,NEI Integration,1.0.12,false,RESTART,"[Forestry@[3.6.0,)]"
NEIPlugins,NEI Plugins Unofficial,1.1.0.8-unofficial,false,RESTART,"[NotEnoughItems@[1.0.2,)]"
OpenMods,OpenMods,0.8,false,RESTART,[OpenModsCore]
quickhotbar,Quick Hotbar,1.04,false,RESTART,[]
ThermalFoundation,Thermal Foundation,1.7.10R1.2.0,false,DEPENDENCIES,"[CoFHCore@[1.7.10R3.0.3,)]"
ThermalExpansion,Thermal Expansion,1.7.10R4.0.3B1,false,DEPENDENCIES,"[CoFHCore@[1.7.10R3.0.3,), ThermalFoundation@[1.7.10R1.2.0,)]"
RedstoneArsenal,Redstone Arsenal,1.7.10R1.1.1,false,DEPENDENCIES,"[CoFHCore@[1.7.10R3.0.3,), ThermalExpansion]"
RArm,Redstone Armory,1.7.10-1.2.0-40,false,RESTART,"[RedstoneArsenal, endercore, ThermalFoundation, ThermalExpansion, Baubles]"
RedstonePasteMod,Redstone Paste,1.6.2,false,RESTART,[]
simplyjetpacks,Simply Jetpacks,1.5.1,false,RESTART,"[Forge@[10.13.2.1291,), ThermalExpansion, RedstoneArsenal, RArm, EnderIO@[1.7.10-2.1.3.243,), BuildCraft|Core@[6.4.15,7.0.0),[7.0.4,)]"
VersionChecker,Version Checker,1.1.9,false,RESTART,[]
wsync,World Sync,1.0,false,RESTART,"[Forge@[v10.13.2.1231,)]"
WR-CBE|Core,WR-CBE Core,1.4.1.9,false,DEPENDENCIES,"[CodeChickenCore@[1.0.4,), ForgeMultipart]"
WR-CBE|Addons,WR-CBE Addons,1.4.1.9,false,RESTART,[WR-CBE|Core]
WR-CBE|Logic,WR-CBE Logic,1.4.1.9,false,RESTART,"[WR-CBE|Core, ForgeMultipart]"
ForgeMicroblock,Forge Microblocks,1.1.0.309,false,RESTART,"[ForgeMultipart, *]"

**Comment by zmaster587** [comment]
The top of the arc furnace needs to be rotated counter-clockwise 90 degrees and make sure the gold blocks are moved to be under the new location for the power supplies

**Comment by HyperMan19680** [comment]
Okay then. New problem. Is the Cutting Machine not supposed to use RF power? Cause I see no spot in the Holo projector for a RF Storage block.

**Comment by zmaster587** [comment]
Yeah, I caught that about an hour ago, you can replace one of the motors in the back with a power block and it should work.  Fixing that now.

**Comment by HyperMan19680** [comment]
Done and fixed. Now I got a question. How does the Planet Analyzer gather data on, say, Luna? I have the Observatory up and running (albiet at a snail's place), but I dunno how the Planet Analyzer gathers data.

**Comment by zmaster587** [comment]
you need to either launch a satellite with a sensor corresponding to the type of data you want to collect then dump it into a data chip for transfer or you can use the observatory, which should be(but i making random data atm) limited to distance data at this point in time.  The data chip can then be put into the planet analyser where you can load the data from the chip

**Comment by KisameSan2** [comment]
for thhe cutting machine im trying to build it but everytime i place the output hatch it says that it is an invalid block

**Comment by zmaster587** [comment]
Can you upload an image of what you have built?
