### ISSUE TITLE
getRocketPadBounds() Throwing NPE on completed connection

### ISSUE THREAD

**Issue by xenoswift** [zmaster587/AdvancedRocketry#1000]
Minecraft Version:
- 1.7.10
Forge Version:
- 10.13.4.1614
Advanced Rocketry Version:
- AdvancedRocketry-1.7.10-1.2.5-49
LibVulpes Version:
- LibVulpes-1.7.10-0.2.7-26-universal
**is this the latest curseforge build?**
Sure is, in fact I manage to get it on several builds.
#Please Pastebin crash
---------------------
Crash Report: https://gist.github.com/xenoswift/c23d13bba69ce01dbabf6046616ff126
----------
Explain issue in detail: After creating a small space station out of entirely ordinary blocks and launching, disconnect from server occurs on dimension load.

**Comment by zmaster587** [comment]
Do you have any other mods installed?  If so, can this be replicated with only advanced rocketry, libvulpes and forge?

**Comment by xenoswift** [comment]
I do, and I can't reproduce with only AR/LibVulpes.
Modlist included here; https://gist.github.com/xenoswift/626b06cd5ae204a74b09b7868028f1d5
When trying to reload the world I get this crash, which was the precursor to that modlist output: https://gist.github.com/xenoswift/6dd98899e1a5c334f8707ba6e9c227bc

**Comment by zmaster587** [comment]
Alright, can you figure out the minimum set of mods required to reproduce the original crash?
For the most recent crash, can you send a copy of the planet list xml file?

**Comment by xenoswift** [comment]
I'm assuming this was the right file in the world save's directory.
https://gist.github.com/xenoswift/0643369cb329d5c156fe723fed55b4f0
I tried to set up a dev environment to just debug it but that was a waste of time. I guess I'll see what changes going down the list by hand.

**Comment by xenoswift** [comment]
So after disabled/enabling a ton of mods everything points to BuildcraftCompat causing some kind of interaction that leads to the crash, because with BC+Compat alone works just fine with AdvancedRocketry. I'll look into it some more tomorrow.

**Comment by xenoswift** [comment]
So I have gone back and narrowed down the realm of possibilities. Running with only BC+Compat works fine, so I had to go through the one-by-one process again.
Going through it I found that Immibis Microblocks and Buildcraft Compat being present in the modlist causes the exception. I cut the modlist down to only;
LibVulpes, AdvancedRocketry, Buildcraft, BC Compat, ImmibisCore, ImmibisMicroblocks.
As long as BC Compat and Immibis Microblocks are both enabled the NPE is thrown when a rocket generates the landing event. The entire modlist runs fine with one or the other, but not both.
Honestly, I have no expectation that you'll try to fix or make a hack around this very bizarre interaction. My fix is don't use Immibis Microblocks AND BCCompat with AdvancedRocketry. I'm not sure if Immibis is even around anymore to provide support. You might be able to ask the Buildcraft team for pointers.
But, I'm considering this a case of programming black magic and I'm going to just leave out the microblocks.

**Comment by zmaster587** [comment]
I wasn't expecting a valid list with the sun color crash, that's really bizzare, does that one keep happening?

The issue with the rocket pad bounds  is incredibly strange because the only thing that can cause this to be an issue is the reference to the world being null in the rocket builder.  I've seen this before with thermos installed, but I cannot imagine what could possibly be making the world instance null unless something is trying to spawn in the tile into some kind of fake world and malfunctioning.  I'll keep looking

**Comment by zmaster587** [comment]
I think I have an idea, the issue is occuring on the client, if the space station is not loaded on the client, the world will not exist.

**Comment by zmaster587** [comment]
Gonna give this a shot.
