### ISSUE TITLE
[Question] Item Inventories for Mining Missions

### ISSUE THREAD

**Issue by greenking13** [zmaster587/AdvancedRocketry#1001]
Hello Zmaster587,

I was wondering what forms of item inventories is accepted by Advanced Rocketry. I'm aware that normal chests work, and I have to assume shulker boxes do as well (I haven't tested it yet since I've not gotten to the end just yet.), but Stone Storages from Multi-Storage don't seem to work. Or are the only accepted inventories vanilla?

Also, as a side note, I can see the chests when I shift-right click the rocket entity, but when I try and open them, I'm immediately booted out. For my specs, they are written in https://github.com/zmaster587/AdvancedRocketry/issues/998

Thank you,
greenking13

**Comment by zmaster587** [comment]
In theory, any block that implements IInventory should work.  If you're running 1.12 it's possible that they switched to the item capability system and removed IInventory as an implemented interface.

As for opening the chests in the rocket that sound like a failure of the ASM code that overrides the distance check.   how big is the rocket and how far from it are you standing when you try to open the chests.  Also are you running anything like sponge?

**Comment by greenking13** [comment]
We are not running sponge or the likes. The rocket is...
![2017-12-22_05 41 38](https://user-images.githubusercontent.com/9355993/34296941-cfdb6a58-e6da-11e7-9bad-65033eec8cdb.png)

that. So, quite small and fat. I am also standing about the same distance away as I am currently. (It is not currently built, I disassembled it due to mining mission issues. We seem to have borked the asteroids such that they only have air of 0+-0 as their contents, even if it says it has XYZ of ores. I'm waiting until the pack dev pops on later today to discuss this more in depth with him.)

**Comment by Jummit** [comment]
Every block from computercraft isn't working too. I think it is because every peripheral uses the same block id(computercraft:peripheral), but different metadata.

**Comment by zmaster587** [comment]
Alright, thanks, I'll take a look

**Comment by zmaster587** [comment]
Added support for itemCapability handlers, should work next build.
