### ISSUE TITLE
Missing textures and incorrect lootbag texture

### ISSUE THREAD

**Issue by pixzi** [zmaster587/AdvancedRocketry#1002]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.1.2581
Advanced Rocketry Version:
- 1.12.2- 1.2.6-38
LibVulpes Version:
- 1.12.2 - 0.2.7.22
**is this the latest curseforge build?**
yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Missing textures from AR and LibVupe's.  Also advanced rocketry and/or LibVupe's messing up the common lootbag texture from the lootbags mod. 
<a href="http://tinypic.com?ref=2zp2g6b" target="_blank"><img src="http://i65.tinypic.com/2zp2g6b.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://tinypic.com?ref=20sg11x" target="_blank"><img src="http://i67.tinypic.com/20sg11x.png" border="0" alt="Image and video hosting by TinyPic"></a>

I've tested with and without a texturepack and i've ruled out any other mod.
As soon as i load these 3 together i get no textures and the incorrect one for the bag.
 I tried lootbags on its own and they worked perfectly also, so not a issue on that end, just when i add AR and libVupe's.

**Comment by Jummit** [comment]
Every block from computercraft isn't working too. I think it is because every peripheral uses the same block id(computercraft:peripheral), but different metadata.

**Comment by zmaster587** [comment]
Can you post the fml-client-latest?

**Comment by pixzi** [comment]
[fml-client-latest.log](https://github.com/zmaster587/AdvancedRocketry/files/1592981/fml-client-latest.log)

**Comment by 4karion** [comment]
I've the same problem, i think is the same than this one:
https://github.com/Malorolam/LootBags/issues/101

[fml-client-latest.log](https://github.com/zmaster587/AdvancedRocketry/files/1597317/fml-client-latest.log)

**Comment by zmaster587** [comment]
Appears to be the same as #987

**Comment by nmarshall23** [comment]
Try removing sonarcore. I'm basing this guess on the bug I had with another mod's custom state mapper.

**Comment by pixzi** [comment]
When i tested it to make sure it still did it. I only had AR and lootbags installed so sonarcore had no effect on what causes this.

**Comment by zmaster587** [comment]
fixed in build 79 and corresponding libvulpes
