### ISSUE TITLE
[issue] solar generator crazy ticking

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#1003]
Minecraft Version:1.7.10
-
Forge Version:1.7.10-10.13.4.1614-1.7.10
-
Advanced Rocketry Version:1.2.4
-
LibVulpes Version:0.2.6
-

Explain issue in detail:
After some hours the solar generator get crazy high ticking near 480 000 us each. (checked in OPIS)
Server restart fix it for some hours, remove them solve the issue.

Thanks

**Comment by zmaster587** [comment]
Can you run a VisualVM profile and upload the results of that?

**Comment by choum33** [comment]
Hello,
My server is an unbuntu with no GUI. Htop show 1 vCPU at 100% when i have this issue. Then Opis helped me to find the entities that generate this. My dedicated server has 6 vCPU and 16Gb of ram and is not very loaded .
After removing solar generators no more issue.

**Comment by dmodoomsirius** [comment]
@choum33 Can you open a port on your ubuntu and give yourself the ability to run a Visual VM profile from your server. As zmaster asked above.

**Comment by choum33** [comment]
Ok JDE installed on server and ports open. I'll try it this WE.
another info that can be usefull. When i place a coal generator (libvulpes) next to the station builder and start a ascan it goes crazy and get very huge ticking like solar generator.
As the scan process was crazy long i added 2 coal generators and the game becan badle laggy. On OPIS it went from 20-50ms to 950ms-1000ms. Only the coal generators feeding the station builder had this issue.
The scan itself took more than 1 hours (16x16 and 22 high blocks for my station).

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
