### ISSUE TITLE
Cannot Change/Remove Recipes for Machines

### ISSUE THREAD

**Issue by votex09** [zmaster587/AdvancedRocketry#1005]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.1.2560
Advanced Rocketry Version:
- 1.12.2-1.2.6-39
LibVulpes Version:
- 1.12.2-0.2.7-22
**is this the latest curseforge build?**
Yes

Explain issue in detail:
[pastebin](https://pastebin.com/6AYcfw0k)

This is an example of my ElectricArcFurnace.xml located in ./config/advRocketry

Using this I do not see these recipes in game. Only the default recipes that ship with the mod.

Things I've tried:
-Renaming advRocketry folder to advancedRocketry (Following continuity on site)
-Removing/Enabling/Disabling useDefault (<Recipes useDefault="<T/F>">)
-Using non-oreDict versions of items (as shown in pastebin)

Is it possible that the code is not looking in these locations for recipe changes, or is it just me?

**Comment by zmaster587** [comment]
Can you include a copy of the startup log with the modified XML?

**Comment by votex09** [comment]
Started Minecraft, waited until main menu and exited the game.
https://gist.github.com/76d68b891290b65d0619d0447948722f

**Comment by zmaster587** [comment]
Sorry, I should have been more specific, I had forgotten that latest.log existed, can you get the fml-client-latest.log and ./config/advRocketry/ElectricArcFurnace.xml?

**Comment by votex09** [comment]
fml-client-latest.log does not exist for me.  I am using the Twitch/Curse launcher if that makes a difference.
the only things that exist in my logs folder are latest.log and archives of old logs from other sessions.

**Comment by dmodoomsirius** [comment]
There should be a file starting with fml. I use the twitch/curse app all the time. 

Thanks,
Dmodoomsirius

**Comment by votex09** [comment]
Strangely enough, there is not:
[https://puu.sh/yPjdL/4add16f806.png](url)

**Comment by votex09** [comment]
Also.... I noticed that the mod is supposed to generate XMLs for the machines on startup correct?  It does not do that either.

**Comment by dmodoomsirius** [comment]
Does this only happen with Forge, LibVulpes and Advanced Rocketry?

**Comment by votex09** [comment]
I just tried with AdvRocketry, CodeChicken Lib, CraftTweaker, Jei, NEI and LibVulp on forge-14.23.1.2560

**Comment by votex09** [comment]
Well, I got fml-client-latest to show up.  I had to use the jar launcher option on curse rather than native.
https://gist.github.com/fa696dea469bb72a84d9f1a24b59987f

This is with just AdvRocketry, JEI and LibVulpes

**Comment by zmaster587** [comment]
the xml is not generating in the config/advRocketry folder when there's no XML files there?

**Comment by zmaster587** [comment]
I think XML loading somehow got missed when porting to 1.12, should work in the next build.  Can you confirm?

**Comment by votex09** [comment]
Sure.  When it pops up on curse, i'll report back here.

**Comment by votex09** [comment]
![image](https://user-images.githubusercontent.com/10671494/34443864-b12f3b88-ec8f-11e7-87bf-5ffe4bc43abd.png)
Looks good to me.  +karma
