### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by ProxyPlayerHD** [zmaster587/AdvancedRocketry#1006]
[LOG](https://pastebin.com/x4zguEsi)

The Log contains the Forge, Mod and MC version and all other information needed

i wanted to continue my Resourcepack so i got the newest version because if i learned anything from texturing Nuclearcraft then that is that Devs like to change texture file names a lot.

**Comment by zmaster587** [comment]
Does this occur with the non-obfuscated version of Advanced Rocketry?

**Comment by ProxyPlayerHD** [comment]
AR Version 1.2.6 29 with libV Version 0.2.7 22 works.

**Comment by zmaster587** [comment]
can you post a crash log with the latest build that isn't a -deobf version?

**Comment by ProxyPlayerHD** [comment]
Honestly i have no idea where i got the deobf version from, i couldn't find it on curse anymore.

AR version 1.2.6 41 plus libV version 1.2.6 24 works again.

did i just pick a broken version by accident?

**Comment by zmaster587** [comment]
No idea, they should be in something like "other files" on curse
