### ISSUE TITLE
Oxygen Vent Oxygen/Seal is Broken When SpongeForge is Installed

### ISSUE THREAD

**Issue by HorizonsMC** [zmaster587/AdvancedRocketry#1009]
Minecraft Version:
1.12.2
Forge Version:
2582
Advanced Rocketry Version:
1.12.2-1.2.6-41
LibVulpes Version:
1.12.2-0.2.7-23
**is this the latest curseforge build?**
Yes.

I am also using SpongeForge 1.12.2-2555-7.0.0-BETA-2800

Explain issue in detail:
Breaking the seal doesn't update the oxygen bubble. This happens when using any of the modes and does not happen when not using SpongeForge.

https://youtu.be/hqAu4H3M110

First part shows behavior in single player working as expected, 2nd part is on a server with identical settings and mods to the client, only difference being SpongeForge + it's on an actual Server.

**Comment by zmaster587** [comment]
Likely related to the ASM handler for AR's O2 system.  I was unable to find a forge event that was fired for every block event possible.  Of particular concern are explosions, door opening/closing/pistons.  To be fair last I checked for such a system was in 1.7

**Comment by HorizonsMC** [comment]
Alright, I saw this issue seemed to also be posted on the sponge issue tracker too.

**Comment by JoeSGT** [comment]
I'm still having this issue and i am on versions
Advanced Rocketry: 1.12.2-1.3.0-61
LibVulpes: 1.12.2-0.2.8-27
SpongeForge: 1.12.2-2611-7.1.0-BETA-2952

@zmaster587  If this a sponge issue have it been report to them ? or @HorizonsMC  did you do it? 
cause i am looking to fix this issue.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
