### ISSUE TITLE
[Suggestion] Option to Disable the Oxygen Vent From Requiring RF

### ISSUE THREAD

**Issue by HorizonsMC** [zmaster587/AdvancedRocketry#1010]
Currently making a modpack that spawns the player inside a dimension that has unbreathable air so they must use an oxygen vent or suit. In the current state you must give them a way to power it, it would be great if there was a way to disable it requiring RF so they don't spawn with something that gens power.

**Comment by zmaster587** [comment]
I've added a multiplier, setting the multiplier to 0 should disable power consumption.

**Comment by HorizonsMC** [comment]
Thank you :D
