### ISSUE TITLE
Elevator still crashing

### ISSUE THREAD

**Issue by Danickar** [zmaster587/AdvancedRocketry#1011]
I just downloaded the newest versions of both AR and the Lib and tried to use my space elevator again, this time going from the planet to the station.

As the dimension change was going to happen the server crashed to the desktop.

Here is the latest crash: https://pastebin.com/ZQApxRTy

I am posting this because I believe the commit you put in for the last issue is in the the latest build. If that fix isn't in then feel free to ignore this issue if it was already dealt with.

**Comment by zmaster587** [comment]
I copied and pasted the changedimension command from the rocket since the rockets appear to be working, but upon further inspection it's expected to fail, the real question is: why don't the rockets crash?

**Comment by zmaster587** [comment]
I copied space elevator code over the rocket code.  Instead of fixing one, I broke the other.

**Comment by zmaster587** [comment]
I need to stop writing code at 3am

**Comment by talonos2** [comment]
Sorry you're writing code at 3:00 am, but thanks for being willing to use some of your Christmas break working on this wonderful mod! Those of us relying on it for Modpacks really appreciate it, and we're patient. :)
