### ISSUE TITLE
Possible Warp Core/Controller issue

### ISSUE THREAD

**Issue by Danickar** [zmaster587/AdvancedRocketry#1013]
Minecraft Version:
- 1.12.2
Forge Version:
- 2566
Advanced Rocketry Version:
- 1.2.6-42
LibVulpes Version:
- 0.2.7-24
**is this the latest curseforge build?**

Not a crash

Explain issue in detail:
When I first click on the warp controller it says No Where To Go in the status as expected. When I selected a destination the status changes to Not Ready. The Fuel is listed as 0 in the warp core.  I have put 4 stacks of dilithium crystals into the warp core input hatch, and they have all disappeared I assume into the core, but yet it registers 0 for its current fuel.

**Comment by zmaster587** [comment]
What happens if you build a new warp core or replace the existing one?

**Comment by Danickar** [comment]
Completely destroying the original warp core and rebuilding it seemed to work.

I built the original one on Earth and had it packaged along with the everything else in the Space Station assembler and sent up with the original core of the station. Although it looked functional something must have been wrong in the unpackaging.

**Comment by Danickar** [comment]
I was warping around the universe testing things out, and the warp core stopped having fuel again. I broke it apart (and all of the crystals came flying out) and put it back together and it was happy. It seems that when it changes dimensions it sometimes breaks, sometimes it doesn't.

**Comment by zmaster587** [comment]
That's really bizzare.  Changing dimensions only should be updating the skybox and an internal "here's where I am" number.  What i suspect is happening is that the warp core location list is somehow being reset.  I had a friend run into that issue the other day and confirmed it.  Still no idea how it's went missing for him though.

However, I'm fairly sure I know why it's not working when built on earth and packaged, I'll look into a fix for that, but once rebuilt..

**Comment by Danickar** [comment]
this could be a totally random coincidence, but it has happened twice when the warp core ran out of fuel. I'll go put more in, but it doesn't register it has having more until I break it apart and put it back together.

**Comment by zmaster587** [comment]
I can't think of any mechanism that would cause that to happen but I'll try it and see if I can replicate it.

As a side note, it may be related to chunk loading, keep track of whether or not you let it unload and this issue occuring and see if there's a relation?

**Comment by eaanon01** [comment]
For #1079 it worked just crating a new space ID chip with a station. I did not need to go there to fix the problem. Neded to pick up and replace the warp core and controller but my dimension was immediately back.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by io-craft** [comment]
Still happens. On 1.7.10 at least.

**Comment by MrEyeballs29** [comment]
Only 1.12 is supported
