### ISSUE TITLE
Space Elevator Capsule crashes server while swiching between dimentions (Aparently)

### ISSUE THREAD

**Issue by Pabby-rubenzo** [zmaster587/AdvancedRocketry#1015]
Minecraft Version:
- 1.12.2
Forge Version:
- forge-1.12.2-14.23.1.2555
Advanced Rocketry Version:
- 1.2.5
LibVulpes Version:
- 0.2.6
**is this the latest curseforge build?**
yes (for 1.12.2)

Crash Report: https://pastebin.com/nbmTn0xW

Explain issue in detail:
i enter the space elevator and it flies up like usual then when it switches between dimensions the server crashes, i don't have this issue on single player and the world was imported from single player.

**Comment by zmaster587** [comment]
should be fixed  in 1.12.2-1.2.6-42
