### ISSUE TITLE
Rolling machine seems to always operate at x4.77 speed, regardless of make.

### ISSUE THREAD

**Issue by talonos2** [zmaster587/AdvancedRocketry#1016]
**Minecraft Version:**
1.11.2
**Forge Version:**
13.20.1.2388
**Advanced Rocketry Version:**
1.2.5a
**LibVulpes Version:**
0.2.6
**is this the latest curseforge build?**
Not quite: There is a more recent "Unstable Alpha" build.
**Pastebin crash**
None

To reproduce:

Tested in a modpack with LibVulpes, Adv. Rocketry, NEI, JEI, CodeChickenCore.
Create a new creative mode world.
Use Holoprojector to create an illusory rolling machine.
Use the pick block command to create a rolling machine with two copper coils and a normal motor.
Right click the rolling machine block to form the rolling machine.
Right click it again to view the machine's stats. Note it has a x4.77 speed modifier.
Break the coil blocks and motor blocks.
Replace the coils with iridium coils, and replace the motor with an elite motor.
Right click the rolling machine block to form the new rolling machine.
Right click it again to view the machine's stats. Note it still has a x4.77 speed modifier.

I would expect the first rolling machine to have a x1 speed, because it has no multipliers on its speed. I would expect the second to have a x16 speed (2 x 2 x 4). I honestly have no idea where x4.77 comes from; I can't figure out how to factor that into multiples of 1, 1.11, 1.25, 1.33, 1.5, 2, and 4.

The above issue isn't all; there's more weirdness involved, but the above repro steps will probably reveal the rest of the issues.

For instance, in the vid below, I *try* to replicate those steps I listed above, but accidentally use an advanced motor instead of an elite motor. Then the speed turns into x8.48. I then upgrade to an elite motor, and it stays at x8.48. I swap back to a normal motor, and the speed *still* stays at x8.48.

Hoping you can make sense of this. Thanks for your mod!

Download Vid of error: https://imgur.com/download/L2NmkIS

**Comment by talonos2** [comment]
A copper-coiled Electrolyzer seems to give me a x1.56 speed rate. The electric arc furnace seems to work normally, though.

Is there some sort of config option I set months ago and have since forgotten about?

**Comment by zmaster587** [comment]
titanium works fine, im wondering if it's just the iridium blocks, I mispelled it at one point a while back, I thought I got em all, but maybe not

**Comment by zmaster587** [comment]
Problem appears to be 1.11 specific, crystallizer is also affected

**Comment by talonos2** [comment]
Thanks!

Where do I get a copy of this build to test? That fix seems... odd. I'd love to mess around with it on my end to make sure it fixes the whole issue. (You've got better things to do than stress-test something you're pretty sure will work, but for my own comfort, I'd love to double-check it.)

**Comment by zmaster587** [comment]
Should be coming out on curse later today as unstable
