### ISSUE TITLE
Railgun crash

### ISSUE THREAD

**Issue by pwncc** [zmaster587/AdvancedRocketry#1017]
Minecraft Version:
1.11.2
Forge Version:
13.20.1.2386
Advanced Rocketry Version:
125a-61
LibVulpes Version:
-0.2.6-32
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
https://pastebin.com/qEHYMRrY
Crash Report:
----------
Explain issue in detail:
I put down a railgun block and it immediately crashed my game.

**Comment by dmodoomsirius** [comment]
Does this happen with only advanced rocketry and LibVulpes?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
