### ISSUE TITLE
Docking Pads on Planets. (Questionish)

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#1019]
Minecraft Version:1.12.2
-
Forge Version: 2555
-
Advanced Rocketry Version: 1.2.6-42
-
LibVulpes Version:  0.2.7-20
-
**is this the latest curseforge build?**  I think so.

Explain issue in detail:

I thought I got this to work in 1.10, but I could be wrong.  Or it may require a space station in the middle to setup.
I built a rocket on a planet with a warp core.  
I place a docking pad, linked coords with a linker.
I fly it to another planet, it lands at the same coords as the rocket took off from.
I place a docking pad under the rocket.
I put the linker in it.
I remove the planet id chip.
I launch.

Expected Result:
I land on the pad I linked to if it is in the same solar system.

(I also think it would be handy if I could just stick the linker into the guidance computer so I can move the rocket around.)

Actual Result:
I land in the same coords as I took off from on the Overworld/Earth.

What am I doing wrong, or am I assuming the functionality works differently than it really does?

Thanks,
IMarv

**Comment by zmaster587** [comment]
Your setup sounds like it's correct.  Can you verify that the coords and dimid on the linker are correct?

Also I agree with you on putting the linker in the guidance computer.  I'd actually toyed around with the idea for a while, but I fear weird things happening with space elevators and linking of blocks in general.  I suppose what I could do is create a seperate landing beacon item and that would allieviate the issue.  The landing beacon could contain a set of coords for each world and with the UI in the rocket you could pick the world to go to.  (the previous world would be set as the destination by default).

**Comment by zmaster587** [comment]
What version of 1.10 were you using before?

**Comment by zmaster587** [comment]
Should be fixed now.  The destination display on the rocket should also now properly update

**Comment by IMarvinTPA** [comment]
Did changes for this happen to fix https://github.com/zmaster587/AdvancedRocketry/issues/744 ?

**Comment by zmaster587** [comment]
The issue appears to be 1.12 specific, so likely not, rockets going to 1000 and staying there is likely something entirely different from what is described in #744 anyway.  AFAIK you cannot design a rocket with a full hour of fuel and the designs he had definatly would not run for a full hour.  If you could open a seperate ticket for the rockets stopping at 1k I'd appriciate it.

Could you also include the destination, contents of the guidance computer, does this happen if you create a new launch pad and test with that?

**Comment by zmaster587** [comment]
I have confirmed rockets not going to other pads in same dimension is also an issue and will have that resolved for the next build

**Comment by IMarvinTPA** [comment]
Cool.  I just was making a series of screenshots to document the problem in the latest Curse version.  My rocket went poof and then I was on it again after I teleported out of the dimension and back.

Thanks,
IMarv
