### ISSUE TITLE
Jetpack not working in FTB Revelation

### ISSUE THREAD

**Issue by jmaccini** [zmaster587/AdvancedRocketry#1022]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.1.2575 
Advanced Rocketry Version:
- 1.2.6-37
LibVulpes Version:
- 0.2.7-21
**is this the latest curseforge build?**
part of [FTB revelation pack](https://www.feed-the-beast.com/projects/ftb-revelation)
Explain issue in detail:
This is probably a me problem, but figured I'd reach out in case it's more complex.  I can't get the jetpack to turn on.  I built it, the full space suit, added 4 pressure tanks, filled with oxygen and hydrogen, and the icon stays red.   Tried changing the control to a different key and made sure there were no conflicts with that key, but nothing ever happened when I pressed the toggle jetpack key.

**Comment by zmaster587** [comment]
This should have been fixed in Libvulpes 0.2.7-24, can you give that build a try and report back?  See https://github.com/zmaster587/libVulpes/issues/26

**Comment by jmaccini** [comment]
Yep. That fixes it.  I think I saw #776 and didn't think it was the same issue, but I didn't look that closely.  Definitely the same, thanks!
