### ISSUE TITLE
remove System.out.println cause spamming 

### ISSUE THREAD

**Issue by JoeSGT** [zmaster587/AdvancedRocketry#1023]
Minecraft Version:
- 1.12.2
Forge Version:
- forge-1.12.2-14.23.1.2581-universal
Advanced Rocketry Version:
- AdvancedRocketry-1.12.2-1.2.6-42
LibVulpes Version:
- LibVulpes-1.12.2-0.2.7-24-universal
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/tile/cables/TilePipe.java#L213
please remove this because whenever players place 3 data cables connected to each other and break one of them they spam in console

**Comment by zmaster587** [comment]
Oops... left some debug output in...

**Comment by JoeSGT** [comment]
xD thanks buddy
