### ISSUE TITLE
Chemical Reactor Fluid Input Crash & World Corruption

### ISSUE THREAD

**Issue by Alex-Irwin** [zmaster587/AdvancedRocketry#1026]
Minecraft Version:
-1.12.2
Forge Version:
-2575
Advanced Rocketry Version:
-1.2.6-37
LibVulpes Version:
-0.2.7-27
**is this the latest curseforge build?**
Yes? - FTB Revalation Release Pack 1.0.0
--------------
Crash Report: https://pastebin.com/ZpzzqxQh 
----------
Explain issue in detail:
Setup: Electrolyzer and Chemical reactor next to each other (front and back).

Interacting with the Electrolyzer fluid output hatch (right side when facing the machine) the server would crash instantly. This happened in multiple instances - once when hooking up fluiducts to the system with servos; once when using tanks on the system. We even moved the systems into a new area with new blocks and recreated the setup - all paths crashed the server. The server world file become corrupted after the crash.

**Comment by Alex-Irwin** [comment]
After doing more investigating, The crash seems to happen right after both Fluid Outputs of the Electrolyzer are connected to the Fluid Input of the Chemical Reactor. Specifically when the fluid is transferred into the chemical reactor. I used Extra Utilities 2's Fluid Transfer Nodes and got the same result as with the Fluiducts. I also Tested connecting the pipes with out power and it was fine.

**Comment by nonenothing** [comment]
> Advanced Rocketry Version: -1.2.6-37

Update this and close issue.
