### ISSUE TITLE
[1.7.10]<GC oxygen over ride to AR oxygen> oxygen system Incompatible

### ISSUE THREAD

**Issue by impbk2002** [zmaster587/AdvancedRocketry#1027]
Minecraft Version:
-1.7.10
Forge Version:
-10.13.4.1614
Advanced Rocketry Version:
-1.2.5-52
LibVulpes Version:
-0.2.7-28
**is this the latest curseforge build?**
yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
When I use override config option GC evolved Mobs went suffocationg...
None of them survive... Is this intended to be?
+None of the galatic craft air system supporting mods doesn't support AR's air system...
especially Modular powersuits...

If it is not intented, can you make another over ride config option to over ride your air system?
I just want to have another armor independently like GC oxygen tank.

**Comment by zmaster587** [comment]
Several things here... what version of modular powersuits are you using, O2 support for modular power suits was tested and working in 1.7.10 less than a year ago.

2nd: there already is a config to allow specific mobs to ignore the O2 system (see "entityAtmBypass")

**Comment by impbk2002** [comment]
oh.. sorry I'm an idiot... I mischeck the config, got answer from config file.
so.. the new enchantment for all 4 pair of armor is needed...
It's too bad that airtight seal enchantment doesn't need any oxygen or IC2 compressed aircells
Lastly, could you tell me the correct text type for "entityAtmBypass"?
: Thaumcraft.BrainyZombie
or...
: BrainyZombie

**Comment by zmaster587** [comment]
The enchantment should make the chestpiece require O2 like a spacesuit with a tank.

As for the Zombie, Im not sure how it is in the Thaumcraft mod, AR will take the full class name or the unlocallized name (the name used with the spawn command) of the mob.

**Comment by impbk2002** [comment]
Really? For modularpowersuits the enchantment is applied on the helmet not the chestplate and doesn't need any oxygen
Plus when I apply enchantment on any 4 pair of armor then I'm free from suffocating without any oxygen

**Comment by zmaster587** [comment]
That sounds like something is broken then.  I'll take a look

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
