### ISSUE TITLE
Ender Storage Rocket loader/unloader CTD

### ISSUE THREAD

**Issue by artaficialAI** [zmaster587/AdvancedRocketry#1028]
Minecraft Version: 1.7.10
-
Forge Version: 10.13.4.1614
-
Advanced Rocketry Version: 1.2.5-52
-
LibVulpes Version: 0.27-28universal
-
---------------------
Crash Report: https://pastebin.com/uTpK6dUD
----------
Minecraft CTDs after a rocket is built by the rocket assembler if the rocket contains a Ender Storage ender chest (The one by Chicken bones) and if there is a rocket loader/unloader linked to the rocket assemlber.  The issue occurs as soon as that world is loaded again, meaning the world is essentially unusable.  Issue only occurs with loader/unloader present.

After removing the loader/unloader with MCEdit the world could be loaded.

**Comment by zmaster587** [comment]
I may have to simply blacklist it from being accessed as an inventory, there's not really any other fix I can think of without hacky workarounds or fully emulating each rocket as a world
