### ISSUE TITLE
asteroidConfig.xml - chance by libvulpes:ore0

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#1029]
<asteroid name="Enriched asteroid" distance="110" mass="100" massVariability="0.5" minLevel="0" probability="0.75" richness="0.2" richnessVariability="0.3">
		<ore itemStack="libvulpes:ore0 8" chance="15" />
		<ore itemStack="libvulpes:ore0 9" chance="10" />
		<ore itemStack="libvulpes:ore0 10" chance="5" />
	</asteroid>
Explain issue in detail:
Quantity in found asteroids always same for all 3 type of ores (maybe calculation ignore part of name after whitespace)

**Comment by zmaster587** [comment]
What version of the mod, minecraft, libvulpes?

**Comment by nonenothing** [comment]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.12.2-1.2.6-42
LibVulpes Version:
1.12.2-0.2.7-24

**Comment by zmaster587** [comment]
Thanks!

Turns out the issue occurs because the number of ores is stored in a map where the item is the key, so metadata was being ignored.

**Comment by zmaster587** [comment]
Fixed in next build
