### ISSUE TITLE
[Suggestion] recipe adding for machines

### ISSUE THREAD

**Issue by Darquewolf** [zmaster587/AdvancedRocketry#103]
would be nice to add support for Minetweaker or a JSON recipe addon to modify the current and to add recipes to your machines as they look so nice. This would allow more customization to your mod. 

https://github.com/jaredlll08/ModTweaker2/issues/271
was requested on modtweaker's github before

**Comment by zmaster587** [comment]
Once the core features of space travel are implemented and I go back to finalizing machines.  Yes.

**Comment by zmaster587** [comment]
Probably actually going to go with an XML system actually, less messing around with other mods and more robust
