### ISSUE TITLE
Exception in server tick loop: zmaster587.advancedRocketry.util.XMLPlanetLoader.writePlanet(XMLPlanetLoader.java:539

### ISSUE THREAD

**Issue by drazisil** [zmaster587/AdvancedRocketry#1030]
Minecraft Version:
- 1.12.2
Forge Version:
- forge-1.12.2-14.23.1.2583
Advanced Rocketry Version:
- AdvancedRocketry-1.12.2-1.2.6-42
LibVulpes Version:
- LibVulpes-1.12.2-0.2.7-24-universal

**is this the latest curseforge build?** Yes

Please Pastebin crash
---------------------
Crash Report: https://pastebin.com/RLJdCgER
----------
Explain issue in detail:

Hitting a tick issue with `zmaster587.advancedRocketry.util.XMLPlanetLoader.writePlanet(XMLPlanetLoader.java:539` The server is running with 6G. I know I have a lot of other mods, but I would not expect this to cause a crash. The line number doesn't match up, so I can't debug the code myself.

**Comment by drazisil** [comment]
Further musings, I suspect it's related to OTG rewriting the biomes. I'm going to look for a config setting that might help.

**Comment by drazisil** [comment]
Nope. Will have to stop using it for now.

**Comment by zmaster587** [comment]
There appears to be either a null biome, or a biome with no name that it's trying to save.

**Comment by drazisil** [comment]
Do you happen to know what build number it will be? Doesn't look like it's in the changelog for 43 https://minecraft.curseforge.com/projects/advanced-rocketry/files/2516505

**Comment by zmaster587** [comment]
Should be build 44

**Comment by fimzks** [comment]
i have the same bug but with other number with lastest version

`java.lang.StackOverflowError: Exception in server tick loop
	at zmaster587.advancedRocketry.util.XMLPlanetLoader.writePlanet(XMLPlanetLoader.java:828)
	at zmaster587.advancedRocketry.util.XMLPlanetLoader.writePlanet(XMLPlanetLoader.java:920)
	at zmaster587.advancedRocketry.util.XMLPlanetLoader.writePlanet(XMLPlanetLoader.java:920)
	at zmaster587.advancedRocketry.util.XMLPlanetLoader.writePlanet(XMLPlanetLoader.java:920)`
[https://pastebin.com/jgVcd3cP](url)
