### ISSUE TITLE
Edit: crash at data network

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#1032]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.12.2-1.2.6-43
LibVulpes Version:
1.12.2-0.2.7-24
**is this the latest curseforge build?**
**Yes**
---------------------
Crash Report:
----------
https://pastebin.com/ZVeykdMw

Explain issue in detail:
After some time on the space station rocket do this: Exception caught during firing event zmaster587.advancedRocketry.api.RocketEvent$RocketLandedEvent

**Comment by nonenothing** [comment]
Addition: crash again after some time at space station (rocket was dismantled) - 
 java.util.ConcurrentModificationException
at java.util.Hashtable$Enumerator.next(Hashtable.java:1367)
at zmaster587.advancedRocketry.cable.HandlerDataNetwork.tickAllNetworks(HandlerDataNetwork.java:20)
at zmaster587.advancedRocketry.event.CableTickHandler.onTick(CableTickHandler.java:26)

may be chunk with data cable at overworld go sleep - and this cause crush.

**Comment by zmaster587** [comment]
Are you running any other mods like sponge or foamfix?

**Comment by nonenothing** [comment]
No, only this:
 AdvancedRocketry-1.12.2-1.2.6-43.jar
 BiblioCraft[v2.4.3][MC1.12.0].jar
 ImmersiveEngineering-0.12-75-core.jar
 ImmersiveEngineering-0.12-75.jar
 jei_1.12.2-4.8.0.114.jar
 LibVulpes-1.12.2-0.2.7-24-universal.jar
