### ISSUE TITLE
Crash when looking at the contents of a satellite bay

### ISSUE THREAD

**Issue by gluff95** [zmaster587/AdvancedRocketry#1033]
Minecraft Version:
- 1.12.2
Forge Version:
- 1.12.2-14.23.1.2555
Advanced Rocketry Version:
- 1.12.2-1.2.6.-42
LibVulpes Version:
- 1.12.2-0.2.7-24

Crash Report:
https://pastebin.com/R549GRky

Explain issue in detail:
When trying to view the contents of a satellite bay on a built rocket and the satellite bay contains a station module kit to add to an existing station, the game freezes, and then crashes to launcher.

**Comment by zmaster587** [comment]
Are you sitting in the rocket when you do this?  Does this occur with only AR and libvulpes installed?

**Comment by gluff95** [comment]
We have other mods installed too, and it happens if you are sitting in the rocket or not.

**Comment by zmaster587** [comment]
Can you try to find the minimum mod list this issue occurs with?

**Comment by gluff95** [comment]
A previous crash report mentioned buildcraft, but we no longer have Buildcraft installed and it still happens.

**Comment by zmaster587** [comment]
can you send the crash report you get without buildcraft installed?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
