### ISSUE TITLE
Pipe is dead, just shoot them

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#1034]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.12.2-1.2.6-43
LibVulpes Version:
1.12.2-0.2.7-24
is this the latest curseforge build?
Yes
Crash Report:
ava.lang.NullPointerException: Ticking entity
> 	at zmaster587.advancedRocketry.cable.CableNetwork.merge(CableNetwork.java:163)
> 	at zmaster587.advancedRocketry.cable.HandlerCableNetwork.mergeNetworks(HandlerCableNetwork.java:75)
> 	at zmaster587.advancedRocketry.tile.cables.TilePipe.mergeNetworks(TilePipe.java:298)
> 	at zmaster587.advancedRocketry.tile.cables.TilePipe.onNeighborTileChange(TilePipe.java:217)
> 	at zmaster587.advancedRocketry.block.cable.BlockPipe.onNeighborChange(BlockPipe.java:98)
> 	at net.minecraft.world.World.func_175666_e(World.java:3791)
> 	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:163)
> 	at zmaster587.advancedRocketry.tile.cables.TilePipe.func_70296_d(TilePipe.java:96)
> 	at zmaster587.advancedRocketry.tile.cables.TilePipe.onNeighborTileChange(TilePipe.java:238)
> 	at zmaster587.advancedRocketry.block.cable.BlockPipe.onNeighborChange(BlockPipe.java:98)
> 	at net.minecraft.world.World.func_175666_e(World.java:3791)
> 	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:163)
> 	at zmaster587.advancedRocketry.tile.cables.TilePipe.func_70296_d(TilePipe.java:96)
> 	at zmaster587.advancedRocketry.event.CableTickHandler.chunkLoadedEvent(CableTickHandler.java:43)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_123_CableTickHandler_chunkLoadedEvent_Load.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> 	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:860)
> 	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105)
> 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
> 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
> 	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
> 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)

Explain issue in detail:
As in #1032 - but now it's fluid pipe.

All it's look very funny, in particular - faulty and ugly native power pipe without native source of power.

**Comment by Frontrider** [comment]
I can confirm, and removing them might be the best course of action. This mod will never ever be used alone, and other mods provide better options.

**Comment by zmaster587** [comment]
There pipes were originally added because at the time of updating to 1.10, no other mods did exist with fluid or power pipes for RF.  While I'd really like to get rid of the pipes entirely, the data pipes use the same system and cannot be substituted with pipes from other mods at this point in time.  Until such a thing occurs (I doubt it will because data is highly specific to AR) I have no choice but to maintain the pipes.

@nonenothing as a sidenote, AR has multiple sources of native power, a coal generator, a solar panel, and the microwave reciever

**Comment by zmaster587** [comment]
@Frontrider @nonenothing can you test with this build of the mod and report any issues that arise with the fml-client-latest(singleplayer) or fml-server-latest(multiplayer).  I've added some debugging info and cannot replicate the issue locally
[AdvancedRocketry-1.12.2-1.2.6-DEBUG.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1610191/AdvancedRocketry-1.12.2-1.2.6-DEBUG.jar.zip)

**Comment by Frontrider** [comment]
Well, the data pipes are neccessarry, but still.Should't keep the rest in active maintainance :/

**Comment by nonenothing** [comment]
@zmaster587 try - but no promises. It's irregular bug.
@Frontrider data pipe is **not** neccessarry.
Simpliest decision - connection throught sort of WIFI.

**Comment by Frontrider** [comment]
@nonenothing I would still prefer a pipe, because in general it is easier to handle from a user standpoint. No need to care about ranges and stuff.

I am agreed on "pipes are useless in mods like this". RFTools is actually better for not having any pipes. It can focus its resources on what its actually doing, and it doesn't bloats its environment with an another system, which can not even be on the same level as other mods, where pipes are actual content.

**Comment by zmaster587** [comment]
@Frontrider There's really nothing else to maintain, the only difference between the data pipe and the other pipes are what they accept, all the handling logic is identical and in a base class.

@nonenothing I'm sorry, I meant to say solar generator, they're slightly different, and if they didn't work, then my station in my play world wouldn't work.  Issue two, sending data "over the air" would require pretty much the same system anyway.  IE WIFI would have the same flaws as the pipes.

The pipes, as they are implemented, only look at endpoints, the same exact way any "over the air" system would.  Pipes have id's, much like over the air systems would need so people don't all share the same data pool.

**Comment by DVorriose** [comment]
Have no issue with pipes/cables save aesthetics (and beauty is in the eye of the beholder).  I'm glad they are there.  AR may never be used alone (sounds a bit tedious in survival), but I can see the value of making sure it can be.  Thank you for the pipes.

That all said, satellite communications is a pretty cool idea.  Microwave Tx/Rx as a block for same-dim/line-of-sight point-to-point data or power transfer?  Biome scanner multi-block rendered upside-down (with different base block?) as a radio telescope or inter-planetary communications?  (i.e. use your Earthly satellites from Sol-#?).

Not sure what all you plan for AR, been worried that you'd burn out with the constant bug fixes in multiple versions of MC, but can't wait to see what other content you come up with.
