### ISSUE TITLE
[1.7.10] Crash when assembling rockets

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#1036]
https://pastebin.com/JvfQuEDT
Using AdvancedRocketry-1.7.10-1.2.5-53 and LibVulpes-1.7.10-0.2.7-28-universal

**Comment by zmaster587** [comment]
Probably the patch for the endertank got botched

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
