### ISSUE TITLE
Crash_rocketassemblymachine

### ISSUE THREAD

**Issue by Redwoodstudio** [zmaster587/AdvancedRocketry#1037]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.2.6-37
LibVulpes Version:
0.2.7-21

Crash Report:
https://pastebin.com/geKuhw3W

When I tried to place rocket assembly machine next to 4x4 launch pad, the game crashed

**Comment by zmaster587** [comment]
Does this occur with only Advanced rocketry and Libvulpes installed?

**Comment by Redwoodstudio** [comment]
I have installed plenty of mods. When I started the game again, it all worked fine
