### ISSUE TITLE
Oxygen vent stop working

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#1038]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.12.2-1.2.6-43
LibVulpes Version:
1.12.2-0.2.7-24
Mods:
AdvancedRocketry-1.12.2-1.2.6-43.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
ImmersiveEngineering-0.12-75-core.jar
ImmersiveEngineering-0.12-75.jar
jei_1.12.2-4.8.0.114.jar
LibVulpes-1.12.2-0.2.7-24-universal.jar

Explain issue in detail:
Every time after fly from station to planet and return back oxygen vent stop working.
Dismantle and rebuild don't help, restart minecraft - do.
Oxygen vent with 2 CO2 scrubber, energy from immersive MV connector.

**Comment by zmaster587** [comment]
can you upload a copy of the world?

**Comment by nonenothing** [comment]
Sure - https://nofile.io/f/qOcGSTrXqkE/minecraft.zip
Mods included - just in case.

**Comment by zmaster587** [comment]
@nonenothing I'm getting a 404 on the link, can you try reuploading or verify the link is correct?

**Comment by nonenothing** [comment]
Try this, look like ok:
https://files.fm/u/hbmfs2dh

**Comment by zmaster587** [comment]
Alright, that one works, thanks!

**Comment by zmaster587** [comment]
Interesting thing of note, totally sealing off the room with the chemical reactor oxygenizes the room.  It may actually be that the setup is not valid but because the chunk with the hole is not loaded right away that it is allowed to seal.  Investigating further.

**Comment by zmaster587** [comment]
Turns out the sealer is failing to seal on when you come back on the rocket.

**Comment by zmaster587** [comment]
fixed for next build
