### ISSUE TITLE
Wonderfull interraction  pressure tank and electrolyser

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#1039]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.12.2-1.2.6-43
LibVulpes Version:
1.12.2-0.2.7-24

Explain issue in detail:
Example: when put super high pressure tank (8000 max capacity) with 6000 hydrogen to electrolyser output fluid hatch (12000 max capacity) with 11000 hydrogen - next time in fluid output 12000 hydrogen, but in tank still 6000 - and tank still in upper slot.
It's perpetum mobile or just magic?

**Comment by zmaster587** [comment]
Should be fixed in next build of libvulpes
