### ISSUE TITLE
invisible block when block selecting completed machine

### ISSUE THREAD

**Issue by Darquewolf** [zmaster587/AdvancedRocketry#104]
when you select a machine block (not every one of them does this, though) the placed selected block will be invisible. Does not crash nor does it generate anything in the log the block is just labeled "machine" don't know if it's a bug its there. i'm sure the "Machine" block shouldn't be able to be gotten as such.

**Comment by zmaster587** [comment]
Which machine(s) do this? and can you post a step-by-step guide on replicating?

**Comment by Darquewolf** [comment]
I'll remove all other mods to check if it's a compatibility bug

**Comment by Darquewolf** [comment]
seems to have been a compatibility issue I'll see if i can isolate the mod causing it

**Comment by zmaster587** [comment]
Is this still occuring?

**Comment by Darquewolf** [comment]
haven't been able to check life has happened.

**Comment by zmaster587** [comment]
I understand completely

**Comment by zmaster587** [comment]
Several patches have been made that may fix this issue.  closing for now
