### ISSUE TITLE
Forestry Bee Hives and Tinkers' Construct Slime Islands on Moon

### ISSUE THREAD

**Issue by phillipasmith1995** [zmaster587/AdvancedRocketry#1040]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2583
Advanced Rocketry Version:
1.2.6-44
LibVulpes Version:
0.2.7-24
**is this the latest curseforge build?**
Yes
Explain issue in detail:
Earth's moon (Luna) generates with bee hives from Forestry and Slime Islands from Tinkers' Construct

**Comment by IMarvinTPA** [comment]
I have a partial solution:
You can set dimension blacklists in tconstruct.cfg in  I:slimeIslandBlacklist.

I don't have anything for the bee hives though.

IMarv

**Comment by dmodoomsirius** [comment]
are there any particular hives that generate or is it all of them?

**Comment by phillipasmith1995** [comment]
Only ones I saw were Wintry Hives, and a pretty high density of them.

**Comment by dmodoomsirius** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1940

**Comment by temp1011** [comment]
Config blacklist is good. https://github.com/MinecraftForge/MinecraftForge/pull/4666 should make this a lot better once implemented and should let advanced rocketry tell others not to generate in their dimension.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
