### ISSUE TITLE
Freeze on world generation.

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1041]
Minecraft Version: 1.12
Forge Version: 1.12.2-14.23.1.2578
Advanced Rocketry Version: 1.12.2-1.2.6-44
LibVulpes Version: 1.12.2-0.2.7-24-universal
**is this the latest curseforge build?** yes
https://pastebin.com/MNt0z0bP
When trying to make new world, it stops and the crash in the pastebin appears in the game log.
this is probably the key: java.lang.Exception: Missing Stars

**Comment by zmaster587** [comment]
Does the world/advRocketry/planetDefs.xml file exist?  If so can you upload it?

**Comment by Jummit** [comment]
It does not exist. The only thing in advRocketry is the folder DIM-2

**Comment by zmaster587** [comment]
It looks like it may be related to invalid syntax in the asteroid config file, can you try running http://starlogs.net/#Zmaster587/AdvancedRocketry/asteroidConfig.xml through an XML validator and/or uploading that as well?

**Comment by Jummit** [comment]
Oh! that's probably because I updated from version 1.10 to 1.12! AR didn't rewrite the configs because there were already there! And the 1.12 didn't liked the 1.10 syntax or so.

**Comment by Jummit** [comment]
But still, whats the problem with this? https://pastebin.com/RcMk0d4M

**Comment by zmaster587** [comment]
Helpful tool I use is https://www.xmlvalidation.com/  Line 8: timeMultiplier=3> should be timeMultiplier="3">

**Comment by Jummit** [comment]
Thanks. I still wonder how it worked in 1.10...
