### ISSUE TITLE
[1.12] custom ore gen 

### ISSUE THREAD

**Issue by Frontrider** [zmaster587/AdvancedRocketry#1043]
Minecraft Version:
-1.12
Forge Version:
-
Advanced Rocketry Version:
-Dev
LibVulpes Version:
-
Explain issue in detail:

Can you brief me on how the ore generation config works? I think I could use it to customize the decorations on the planets.

**Comment by zmaster587** [comment]
AR has it's own ore generator buillt in.  Basically when a planet is given an ore configuration, AR cancels events on the OREGEN event to prevent other mods from generating ore.  Then it generates the ores specifies in stone with the given cluster frequency and size.

I don't see how it would be useful for controlling decorations other than ores, but if you find a way, I'd be curious to hear about it

**Comment by IMarvinTPA** [comment]
COHF World also works on AR worlds.  I've been using that to do ores and decorations.

**Comment by Frontrider** [comment]
Mainly to generate biome/planet specific stones. Also, currently a planet like the moon, has the default overworld oregen, and stuff like dirt shouldn't be there.

**Comment by zmaster587** [comment]
@Frontrider You mean dirt underground?

You could definatly use it for that, I got silly once and made giant boulders of furnaces once

**Comment by Frontrider** [comment]
I tried changing in a dimension definition, but it just crashed.

**Comment by IMarvinTPA** [comment]
@Frontrider 
I overrode all ore gen using COFH World config/cofh/world/config.cfg using     B:ReplaceStandardGeneration=true
Then customize all of the ore gen using their config files.  I don't use AR's ore gen capabilities at all in my pack.  COFH World ore generation config files are much more versatile compared to AR.
My overworld has 1/4 the normal generation rate.  A couple examples below where dimension ID filtering is used.  One blacklist and one whitelist. 
```
"copper_general": {
			"distribution": "uniform",
			"generator": {
				"block": {"name" : "ic2:resource", "metadata":"1"},
				"material": "minecraft:stone",
				"cluster-size": 8
			},
			"cluster-count": 10,
			"min-height": 45,
			"max-height": 60,
			"retrogen": false,
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1, 0, 6, -11325, 7
				]
			}
		}
	,	"copper_overworld": {
			"distribution": "uniform",
			"generator": {
				"block": {"name" : "ic2:resource", "metadata":"1"},
				"material": "minecraft:stone",
				"cluster-size": 8
			},
			"cluster-count": 3,
			"min-height": 45,
			"max-height": 60,
			"retrogen": false,
			"biome": "all",
			"dimension": {
				"restriction": "whitelist",
				"value": [0]
			}
		}
```

Good luck.

**Comment by Frontrider** [comment]
@IMarvinTPA  I'm on the discord of Team COHF (moving there from twich), but I'm not allowed to make Advanced rocketry depend on Cohf core. Right now, I have a set of prototype Biomes, what I'm trying to integrate with the mod.

Theres a reason why I added "dev" to the version. Right now this is the channel I have to communicate it.

**Comment by zmaster587** [comment]
@Frontrider can you send the crash report and the config you used?

**Comment by Frontrider** [comment]
Crash report:

https://pastebin.com/urxj5i92

Altered code segment:
https://pastebin.com/zHaqrKJX

This was the first thing I tried, (should work I think) looking into more direct methods about now.(when I can)

**Comment by zmaster587** [comment]
is there a reason http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/OreConfiguration.php won't work for you?

**Comment by Frontrider** [comment]
I was trying to go planet specific and not heat specific.

**Comment by zmaster587** [comment]
You can do that using the OreGen tag, it's specific to the planet you assign it to.
