### ISSUE TITLE
[1.12] vacuum kills underwater creatures

### ISSUE THREAD

**Issue by Frontrider** [zmaster587/AdvancedRocketry#1044]
Minecraft Version:
-1.12
Forge Version:
-
Advanced Rocketry Version:
-Dev
LibVulpes Version:
-
Explain issue in detail:

While fiddleing with my frozen ocean biome I noticed that underwater mobs still die from the vacuum. I really don't want that, since the surface should definietly be inhabitable.

**Comment by zmaster587** [comment]
Creatures or players in water or lava should no longer suffer from atmosphere effects.
