### ISSUE TITLE
1.2.6 No planets show up on choose destination

### ISSUE THREAD

**Issue by Lemikoo** [zmaster587/AdvancedRocketry#1045]
Minecraft Version: 1.12.2
-
Forge Version:1.6
-
Advanced Rocketry Version:1.2.6
-
LibVulpes Version:0.2.7
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:

I have rocket built and everything and I am ready to go, but when I put an unprogrammed planet-id chip in the guidance computer and go to pick a destination, only earth shows up. I can't find any tutorial on how to reveal the other planets or go to other planets using this version of advanced rocketry

**Comment by zmaster587** [comment]
can you run the command "/advRocketry planet list" and report back with the full printout?

**Comment by Lemikoo** [comment]
Dimensions:
DIM0: Earth
DIM2: Mining planet
DIM3: Void planet
DIM4: deep dark planet
DIM6: lost cities planet

**Comment by Lemikoo** [comment]
The issue I have is that in the "select dst" map, the only planet is earth. Luna does not show up.

**Comment by vendias** [comment]
I having the same issue. And I'm getting the same printout of that command.
Dimensions:
DIM0: Earth
DIM2: Mining planet
DIM3: Void planet
DIM4: deep dark planet
DIM6: lost cities planet

**Comment by nonenothing** [comment]
Are you trying to press "UP" and check all star systems?

**Comment by Lemikoo** [comment]
Tried that

**Comment by Frontrider** [comment]
Luna might not even be defined.
Can you show a planetDefinition?

**Comment by Lemikoo** [comment]
-<galaxy>


-<star numGasGiants="0" numPlanets="0" y="0" x="0" temp="100" name="Sun">


-<planet name="Earth" customIcon="earthlike" dimMapping="" DIMID="0">

<isKnown>true</isKnown>

<fogColor>1,1,1</fogColor>

<skyColor>1,1,1</skyColor>

<atmosphereDensity>100</atmosphereDensity>

<gravitationalMultiplier>100</gravitationalMultiplier>

<orbitalDistance>100</orbitalDistance>

<orbitalPhi>0</orbitalPhi>

<rotationalPeriod>24000</rotationalPeriod>

<biomeIds>0</biomeIds>

</planet>


-<planet name="Mining Planet" customIcon="earthlike" dimMapping="" DIMID="2">

<isKnown>true</isKnown>

<gravitationalMultiplier>100</gravitationalMultiplier>

<orbitalDistance>110</orbitalDistance>

<orbitalPhi>0</orbitalPhi>

</planet>


-<planet name="Void Planet" customIcon="gasgiantblue" dimMapping="" DIMID="3">

<isKnown>true</isKnown>

<gravitationalMultiplier>100</gravitationalMultiplier>

<orbitalDistance>120</orbitalDistance>

<orbitalPhi>0</orbitalPhi>

</planet>


-<planet name="Deep Dark Planet" customIcon="moon" dimMapping="" DIMID="4">

<isKnown>true</isKnown>

<gravitationalMultiplier>100</gravitationalMultiplier>

<orbitalDistance>130</orbitalDistance>

<orbitalPhi>0</orbitalPhi>

</planet>


-<planet name="Lost Cities Planet" customIcon="earthlike" dimMapping="" DIMID="6">

<isKnown>true</isKnown>

<gravitationalMultiplier>100</gravitationalMultiplier>

<orbitalDistance>140</orbitalDistance>

<orbitalPhi>0</orbitalPhi>

</planet>

</star>

</galaxy>

**Comment by Lemikoo** [comment]
<galaxy>
    <star name="Sun" temp="100" x="0" y="0" numPlanets="0" numGasGiants="0">
        <planet name="Earth" DIMID="0" dimMapping="" customIcon="earthlike">
		    <isKnown>true</isKnown>
            <fogColor>1,1,1</fogColor>
            <skyColor>1,1,1</skyColor>
            <atmosphereDensity>100</atmosphereDensity>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>100</orbitalDistance>
            <orbitalPhi>0</orbitalPhi>
            <rotationalPeriod>24000</rotationalPeriod>
            <biomeIds>0</biomeIds>
        </planet>
		<planet name="Mining Planet" DIMID="2" dimMapping="" customIcon="earthlike">
		    <isKnown>true</isKnown>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>110</orbitalDistance>
            <orbitalPhi>0</orbitalPhi>
        </planet>
		<planet name="Void Planet" DIMID="3" dimMapping="" customIcon="gasgiantblue">
		    <isKnown>true</isKnown>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>120</orbitalDistance>
            <orbitalPhi>0</orbitalPhi>
        </planet>
		<planet name="Deep Dark Planet" DIMID="4" dimMapping="" customIcon="moon">
		    <isKnown>true</isKnown>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>130</orbitalDistance>
            <orbitalPhi>0</orbitalPhi>
        </planet>
		<planet name="Lost Cities Planet" DIMID="6" dimMapping="" customIcon="earthlike">
		    <isKnown>true</isKnown>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>140</orbitalDistance>
            <orbitalPhi>0</orbitalPhi>
        </planet>
    </star>
</galaxy>

**Comment by Lemikoo** [comment]
yea luna isnt defined in config files

**Comment by Frontrider** [comment]
Define luna, as described in the wiki, and the issue is solved.
http://65.78.115.159:8000/AdvancedRocketry/config/AdvancedPlanetConfiguration.php

**Comment by Lemikoo** [comment]
i dont know what the specifications of luna are. The wiki only gives examples of each type of specifications.

**Comment by Frontrider** [comment]
Create a world with the default configs. That'll give it to you. The cleanest way is to have only AR installed in that instance.

**Comment by Lemikoo** [comment]
I defined Luna in the config files as shown. It did not work

**Comment by Lemikoo** [comment]
If it helps, I am playing through the FTB revelations modpack

**Comment by Lemikoo** [comment]
![image](https://user-images.githubusercontent.com/35202087/34666380-b3a3158c-f429-11e7-9baa-21fcf4e0de38.png)

**Comment by Lemikoo** [comment]
here is my planet defs folder

**Comment by dmodoomsirius** [comment]
Luna is defined right in that picture.

**Comment by zmaster587** [comment]
I noticed you have dimmapping for the moon there.  Do you have a mod that add the dimension id 7?  Can you post a forge log.

**Comment by Lemikoo** [comment]
I manually defined luna in that picture

**Comment by Frontrider** [comment]
remove dim mapping (if thats set, than it will not create a new dimension, instead it will use an existing one) and add  a biome list containing the id of the "moon" biome.

**Comment by Lemikoo** [comment]
how do i include the moon biome

**Comment by zmaster587** [comment]
if you're using the latest build of AR, or one built within the last 4 days, you can use <biomeIds>advancedrocketry:moon</biomeIds> as one of the tags, otherwise you'll need to find the biomeID of the moon biome via startup logs or peeking at the level.dat file.  In 1.12 it appears the id is set by forge, so it may differ from the config.

**Comment by EasterncheesE** [comment]
https://pastebin.com/6H3mUBBT

Please have a look at the standard config as of 1.2.4. Biome definition is in the bottom of Luna section. The biome ID is usually written in AdvancedRocketry.cfg

**Comment by Lemikoo** [comment]
Why is the "isknown" tag false in that config?

**Comment by EasterncheesE** [comment]
Bbecause moons always inherit the planet config of this part. It was in default config, i didn't touch it.
It does nothing for moons, actually.

**Comment by Lemikoo** [comment]
alright i put it in as displayed. still didnt work. moon isnt showing up

**Comment by zmaster587** [comment]
Can you test with 1.12.2-1.2.6-48-UNSTABLE build -48, I patched an issue with child planets not properly linking when I added the overworld sky override option.  That may fix your issue

**Comment by Lemikoo** [comment]
That worked. Thank you so much for all of your help (all of you).

**Comment by zmaster587** [comment]
No problem!

**Comment by Athanasius44** [comment]
some1 on our server had the same issue but all he needed to do is add a warp drive

**Comment by bblay** [comment]
Thanks for the tip and unblocking me. It's actually just the warp core you need to select planets in the same system: _"A warp core block placed on a rocket allows the rocket to travel to other planets in the same solar system."_
http://arwiki.dmodoomsirius.me/AdvancedRocketry/blocks/WarpCore.php

**Comment by riyan119** [comment]
dont forget allow dimension.
