### ISSUE TITLE
Crash going to the Space Station from Planet.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#1046]
Minecraft Version: 1.12.2
-
Forge Version:  2555
-
Advanced Rocketry Version:   ...-45
-
LibVulpes Version:  0.2.7-24
-
Is this the latest curseforge build?**  Yes

Crash Report:  https://pastebin.com/uNGs8Uvn
----------
Explain issue in detail:

I built a second space station.
Its ID chip and package are in my inventory.
I built two rockets.
I copied my used space station ID chip.
Put a copy in each rocket.
Launched the first rocket and let it fly off without me.
I got in the second rocket and rode it to orbit.
Crash occurs when I reach orbit.
Relog has me land on the pad I took off form.

I think the first rocket is on the only docking pad on the station (that has a linker in it) and the second rocket won't fly to the origin area as the documentation claims.

Edit:
First rocket sent landed in the default area.
The docking pad on the station has a linker in it.
Successfully got the second rocket to the station after removing the ID chip and putting a linker set to the docking pad on the station in the docking pad under the rocket.

IMarv

PS, I added a video to #1031 showing that the issue does not appear to be fixed, at least for me.

**Comment by Frontrider** [comment]
Can you include the configuration of your solar system? Its location:
saves/<World Name>/advRocketry/planetDefs.xml

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
