### ISSUE TITLE
Planet discovery

### ISSUE THREAD

**Issue by nonenothing** [zmaster587/AdvancedRocketry#1048]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2555
Advanced Rocketry Version:
1.12.2-1.2.6-43
LibVulpes Version:
1.12.2-0.2.7-24

Explain issue in detail:
1) Every planet called Sol-number - in any system.
2) Some discovered planet cannot be found in visible systems (Sol-48:0, Sol-54:0, Sol-11:0, Sol-11:2).
World and config, chest with discovered planet chip - at warp controller.
https://files.fm/u/hbmfs2dh

**Comment by dmodoomsirius** [comment]
the Sol-number is default. yes some are hidden by default using <isKnown>false</isKnown>. as far as not being discovered either set them to true in the <isKnown> portion of that planet's info or add an [artifact ](http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/AdvancedPlanetConfiguration.php#artifact).
