### ISSUE TITLE
sudden crash

### ISSUE THREAD

**Issue by Darquewolf** [zmaster587/AdvancedRocketry#105]
I was building the observatory completed it then went to access the GUI and accidentally placed the block I had in my hand (creative capacitor from immersive engineering)

http://pastebin.com/ejZJfL0z

**Comment by zmaster587** [comment]
Is this on a server and if so, is latenty high/tps low, and if single player, is the computer severely bogged down?

Reason I ask is I see this exact trace when I try to open an inventory on a laggy server.  Example being: forestry bags, if I open it and drop the bag before the server responds I get an identical crash.

**Comment by Darquewolf** [comment]
most likely bogged down but i will try to reproduce it again

**Comment by Darquewolf** [comment]
I can reproduce the crash http://pastebin.com/ws503RT9

**mods installed are:**
AdvancedRocketry-0.4.12b6
ImmersiveEngineering-0.7.5
LibVulpes-0.0.6e

https://youtu.be/EZzvX_vUQKo

I use immersive engineering for RF

**Comment by zmaster587** [comment]
Sorry I took so long been rather busy.  It only seems to occur when the RF inputs are connected, this isn't related to Immersive Engineering in anyway.  Investigating fix.

**Comment by zmaster587** [comment]
Looks to be a problem with the structure of the telescope.  Should be fixed in next build.
