### ISSUE TITLE
Crash with Ore Scanner

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1050]
Minecraft Version: 1.12.2
Forge Version: 14.23.1.2578
Advanced Rocketry Version: 1.2.6-44
LibVulpes Version: 0.2.7-24-universal
latest curseforge build: yes
https://pastebin.com/ecBL8ZhW

Explain issue in detail:
After a few seconds of clicking on the map of the ore scanner remote it crashes.

**Comment by Chrimio** [comment]
I believe i have discovered the cause for the crash.
The ore scanner GUI functions as it should but the moment i clicked outside the GUI the game began freezing and then crashing. Unsure if this is the cause and would like confirmation from other people if the same happens to them.

**Comment by Kaeteker** [comment]
I built an ore scanning satellite with 3 large solar panels and 3 data storage units. I'm playing on FTB Continuum 1.4.1.

When I use the ore scanner, it takes forever to load up the ore data (but it does eventually display a map!), but when I try to click anywhere on the gui or off the gui the game crashes. It doesn't matter whether the map has loaded yet or not, clicking anywhere crashes the game.

Here's a crash log:
https://pastebin.com/KaMrMaAM

**Comment by zmaster587** [comment]
I can confirm that a crash occurs if you click outside the window.  Additionally there appears to be a crash associated with changing view distance too fast because of a race condition.
