### ISSUE TITLE
Unable to select planet on unmanned rocket

### ISSUE THREAD

**Issue by GamerTommy** [zmaster587/AdvancedRocketry#1051]
Minecraft Version: 1.10.2
-
Forge Version: 12.18.3.2511
-
Advanced Rocketry Version: 1.10.2-1.2.5a (1.2.5a)
-
LibVulpes Version: 1.10.2-0.2.6 (0.2.6)
-
**is this the latest curseforge build?**

It almost certainly isn't, as I'm running the Forever Stranded modpack.

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
I've successfully built a rocket with the unmanned vehicle assembler (not the rocket assembler). It has two satellite bays and a guidance computer (other than the fuel tanks and thrusters). However, when I open up the rocket UI to select the destination, there is no "Select Dst" button, as I've seen in several walkthroughs and screenshots. Instead, there's a warning that says "No Gas Here" and two arrows which do not do anything. I've tried launching the rocket with just an unprogrammed chip (and no chip) in the guidance computer, but it hasn't responded (and the monitoring station is properly linked to the rocket.) I've tried placing unprogrammed Planet ID Chips in the rocket with no success. I noticed an undocumented block called the Planet Selector, so I tried linking that with the rocket. I tried programming the chips with the selector, but there's no way I can find to do that. I tried attaching the Planet Selector to the rocket and reassembling it, but there's still no "Select Dst" button and the Planet Selector does not show up as a selectable block in the rocket's UI. Am I doing something obvious wrong, or is there some incompatibility with the custom configs in Forever Stranded for this version?
If it's the former, sorry for wasting you time.

![image](https://user-images.githubusercontent.com/35240163/34694583-34a3cf4c-f48d-11e7-988f-310a1309333f.png)

(The blocks shown in the rocket are two satellite bays and a guidance computer)

**Comment by nonenothing** [comment]
> Am I doing something obvious wrong, or is there some incompatibility with the custom configs in Forever Stranded for this version?

Yes.

**Comment by sdfg2** [comment]
Thank you for this.  I was wondering why my satellite launching unmanned rocket wasn't working - I guess they aren't supposed to, which is a shame.

**Comment by zmaster587** [comment]
You should be able to launch them from stations as well, but you still have to use the regular rocket to do so.

**Comment by sdfg2** [comment]
Thanks @zmaster587, that explains a lot.  Any chance we can get them launched from unmanned on a station too?  Saves on fuel and tanks :-)
