### ISSUE TITLE
Second moon on overworld doesn't appear in sky

### ISSUE THREAD

**Issue by Mitchel75814** [zmaster587/AdvancedRocketry#1052]
Minecraft Version:
1.12.2
Forge Version:
1.12.2-forge1.12.2-14.23.1.2583
Advanced Rocketry Version:
AdvancedRocketry-1.12.2-1.2.6-45
LibVulpes Version:
LibVulpes-1.12.2-0.2.7-24
**is this the latest curseforge build?**
custom modpack
Explain issue in detail:
I added a second moon to the overworld and it added successfully. The planet selector shows both just fine. However, in the sky only the normal moon is visible.

**Comment by zmaster587** [comment]
This is because AR does not override the vanilla skybox to prevent possible conflicts with other mods.  I hadn't thought about it until now, but I suppose I could add a config option.
