### ISSUE TITLE
Flying speed breaks after wearing space-suit

### ISSUE THREAD

**Issue by DragonShadesX** [zmaster587/AdvancedRocketry#1054]
Minecraft Version: 
-1.12.2
Forge Version: 
-8.0.99.99
Advanced Rocketry Version: 
-1.2.6.-40
LibVulpes Version:
-0.2.7.-23
**is this the latest curseforge build?** 

It's Feed The Beast Revelations mod pack, so I assume so.

#Please Pastebin crash
---------------------
Crash Report: N/A
----------
Explain issue in detail:
While using a flight ring from Extra Utils 2 you get a speed boost while flying.  After putting on the space suit from Advanced Rocketry I noticed that my flight speed with the ring had been severely slowed down.  Upon taking off the space suit my flight speed remained that slow, and the only way I could fix it was by deleting my player data in the World ->playerdata folder.

**Comment by Capiachi** [comment]
Hey.

Any possible fix for this? Im currently having this in All The Mods 3 modpack using -1.2.6.-49

**Comment by DragonShadesX** [comment]
I did find out it's only if you put on a space suit with a jetpack in it, so as long as you don't put a jetpack in the suit you should be fine.

**Comment by Capiachi** [comment]
Thanks Dragon! That actually makes it so I could continue untill it gets fixed!

**Comment by zmaster587** [comment]
Redid flight speed in next build, should no longer interfere
