### ISSUE TITLE
Unable to Change Gravitational Multiplier in the Overworld

### ISSUE THREAD

**Issue by HorizonsMC** [zmaster587/AdvancedRocketry#1056]
Minecraft Version:
1.12.2

Forge Version:
14.23.1.2587

Advanced Rocketry Version:
AdvancedRocketry-1.12.2-1.2.6-46

LibVulpes Version:
LibVulpes-1.12.2-0.2.7-25-universal

Explain issue in detail:
Changing the gravity multiplier in the overworld is having no effect.

planetdefs.xml: 
https://pastebin.com/BNuSdCKx

Dimension Information: 
https://pastebin.com/eiVhReJ1

Using /advancedRocketry planet set gravitationalMultiplier 0.1 for example does nothing.

Using /advancedRocketry planet get gravitationalMultiplier shows the value in the xml.

**Comment by zmaster587** [comment]
Might be related to an early design descision to prevent the overworld from being altered, I'll take a poke around.

**Comment by zmaster587** [comment]
It appears to work in single player, but not on servers, investigating

**Comment by HorizonsMC** [comment]
Not sure if it's related, but I also noticed if somebody dies from lack of oxygen it spams it to all players in the dimension.

**Comment by zmaster587** [comment]
I can't say I've run into that issue, even with the following tests:
Two players on a server, one in overworld, one suffocates on the moon.
Two players on a server, both on the moon, one suffocates.

Can you test with only AR and libvulpes installed and if you can replicate it under those conditions, then open a new issue?

**Comment by zmaster587** [comment]
Also the gravity multiplier should be fixed in the next build
