### ISSUE TITLE
Advanced rocketry chest crashing upon equip

### ISSUE THREAD

**Issue by Bobbydevis** [zmaster587/AdvancedRocketry#1057]
Minecraft Version:
- 1.7.10
Forge Version:
- 10.13.4.1614
Advanced Rocketry Version:
- 1.2.5-55
LibVulpes Version:
- 0.2.7-29
**is this the latest curseforge build?**
 Yes?
#Please Pastebin crash
---------------------
Crash Report: https://pastebin.com/5G3DcM6x
----------
Explain issue in detail: Put on advanced rocketry chest piece, Crashed game.

**Comment by zmaster587** [comment]
should be fixed next build, going back a build or two may solve it in the meantime.
