### ISSUE TITLE
[Bug] Inventory Models don't display if "Booster Rockets" or "Flexible Tools" are installed.

### ISSUE THREAD

**Issue by TeetoKaziim** [zmaster587/AdvancedRocketry#1059]
Minecraft Version:
- 1.12.2
Forge Version:
-14.23.1.2573
Advanced Rocketry Version:
-1.12.2-1.2.6-47
LibVulpes Version:
-1.12.2-0.2.7-25
**is this the latest curseforge build?**
Yes it is.

Explain issue in detail:
When either of the mods:
[Flexible Tools](https://minecraft.curseforge.com/projects/flexible-tools) (version 1.2.7) or [Booster Rockets](https://minecraft.curseforge.com/projects/booster-rockets) (version 1.1.1) are installed along side advanced rocketry, the inventory models for a wide swath of the blocks in Advanced Rocketry and Lib Vulpes display as "Missing Texture Cubes" instead of their actual block models.

The blocks in question appear to display just fine in-world when placed.

https://i.imgur.com/hjtbyat.png

**Comment by davqvist** [comment]
Can confirm with Flexible Tools, additionaly the Flexible Sword takes on the texture of an AR block. Seems to be the same bug as #987 and #1002

**Comment by davqvist** [comment]
So any news on this? My pack that is about to be released has both Advanced Rocketry and Flexible Tools and I really don't want to release the pack with broken textures.

**Comment by zmaster587** [comment]
Still have not been able to identify the cause.  What I do know is that AR textures load properly, then somehow later become null through an unknown mechanism.  I'll give it another look today though, maybe something will come of another few hours of debugging this time.

**Comment by zmaster587** [comment]
I did find a stopgap measure would be to manually specify the paths off all AR textures.  So that's something at least.

**Comment by zmaster587** [comment]
an update to libvulpes will be required to fix libvulpes's items too.

**Comment by davqvist** [comment]
The AR textures are fixed now which is the main concern, thanks for that, for some reason the Flexible Sword still takes the texture of an AR machine. Maybe you can have another look and figure out why?
