### ISSUE TITLE
Duplication glitch with GriefPrevention [Sponge plugin]

### ISSUE THREAD

**Issue by JoeSGT** [zmaster587/AdvancedRocketry#1064]
Minecraft Version:
- 1.12.2
Forge Version:
- 1.12.2-14.23.1.2581 
Advanced Rocketry Version:
-  1.12.2-1.2.6-47 
LibVulpes Version:
- 1.12.2-0.2.7-25
- SpongeForge:  1.12.2-2555-7.1.0-BETA-2834
- griefprevention-1.12.2-4.3.0.511
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
so my friend had made a basic claim using GriefPrevention
and i made sure i do not have any permission to break/place blocks into his claim
then my friend place a cobble stone down in his claim then i stand about 5-6 blocks away from cobblestone then i used `Basic Laser Gun` and right click it and it drop the items but it does not break the block. Essentially you can still do this and get infinity blocks 
can you please fix this ? it seem to be a more of this mod issue and not Sponge related

**Comment by dmodoomsirius** [comment]
Does this happen without sponge? Does this happen without the GriefProtection plugin? Does this only happen with advanced rocketry and LibVulpes? Did you report this to the sponge developers?

**Comment by JoeSGT** [comment]
no this does not happen without spongeForge
it is a compatibility issue not sure who side is it on
because it seem Advanced rocketry is ignore events from sponge

**Comment by zmaster587** [comment]
Advanced rocketry uses all the same hooks the vanilla pickaxes do.  The laser gun makes a call to forge, which is then in turn responsible for checking to see if the block can be harvested, and if so then drop the block.  The laser gun itself does not make any calls to minecraft to directly drop the block.

**Comment by gabizou** [comment]
(I'll be replying to both issues on sponge and here)
I have a feeling that I'll need to port over the same sort of workaround fixes for Sponge's entity drop captures to work with block drop captures, similar to the [in development branch handling entity drop captures automatically with sponge's tracking system](https://github.com/SpongePowered/SpongeForge/compare/stable-7...refactor/entity-drop-compatibility?expand=1) to resolve the [hatchery issue with sponge itself](https://github.com/SpongePowered/SpongeForge/issues/1259). I'll be working on the fixes and testing against AR and Hatchery to verify issues are resolved and report back here.

**Comment by JoeSGT** [comment]
Closing this issue it got fixed
