### ISSUE TITLE
[1.7.10] Crash on generating new world

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#1066]
Using AdvancedRocketry-1.7.10-1.2.5-58 and LibVulpes-1.7.10-0.2.7-29-universal

https://pastebin.com/nsxJgJmZ
Got this crash on new world generation, old worlds works fine.

Please tell me if you need a full log

**Comment by zmaster587** [comment]
Yeah, I think I'll need the full log for this one if you don't mind.

**Comment by zmaster587** [comment]
Nevermind, was able to replicate

**Comment by zmaster587** [comment]
Fixed for next build
