### ISSUE TITLE
Unable to apply Air Tight Seal to armor with Chemical Reactor.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#1069]
Minecraft Version: 1.12.2
-
Forge Version: 2577
-
Advanced Rocketry Version: 1.2.6.-49
-
LibVulpes Version:  0.2.7.-25
-
**is this the latest curseforge build?**  I think so.

Explain issue in detail:

Both JEI and actually doing it show no enchantment applied to the armor.  It just eats the materials and gives you the same armor back that you put in.  It also strips any enchantments that were on the armor.

**Comment by zmaster587** [comment]
You will also have to update libvulpes are delete the config/advRocketry/ChemicalReactor.xml file since the issue was due to recipes being written to the file without enchantments.
