### ISSUE TITLE
game crash after finishing writing on asteroid id chip in astrobody data processor

### ISSUE THREAD

**Issue by ToserBan** [zmaster587/AdvancedRocketry#1070]
Minecraft Version:
1.7.10
Forge Version:
1.7.10-1.2.0.345
Advanced Rocketry Version:
1.7.10-1.2.5-58
LibVulpes Version:
1.7.10-0.2.7.29
**is this the latest curseforge build?**
2nd last
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
game crashes to windows without error message after the astrobody data processor finishes his work and wrote 1000 data of each data type into a asteroid id chip. I can reproduce the error.

**Comment by ToserBan** [comment]
did two more chips and no crash, so no more reproducable

**Comment by ToserBan** [comment]
again crashes, and the astrobody data processor duplicates the asteroid chips that are filled with data. I think this is not intendet ?

**Comment by dmodoomsirius** [comment]
Can you please pastebin the entire crash report and link it here?

**Comment by ToserBan** [comment]
https://pastebin.com/embed_js/5Ey2q0mL

**Comment by zmaster587** [comment]
What version of AR was the world generated with?  if you break and replace the astrobody data processor, does this still occur?

**Comment by ToserBan** [comment]
i changed the version very often to test everything. The world was generated without AR installed. Then, i installed the latest beta from AR, i think its from Oktober 2017. I will try now to break the device and replace it.

**Comment by ToserBan** [comment]
I breaked the mainblock and put it in the structure again. The game still crashes, when the writing is finished.

**Comment by zmaster587** [comment]
is there anything in the output hatch?

**Comment by ToserBan** [comment]
yes, the machine copies the asteroid id chip, i dont know if this is intended. The original chip stays in the mein gui and the copy goes to the output hatch

**Comment by zmaster587** [comment]
A stray 2 was left behind in the 1.7.10 builds.  The ABDP used to use internal storage for outputs, that changed in the 1.1.x builds where it began using the output hatch instead.  But this should fix both the dupe and crash

**Comment by ToserBan** [comment]
That means if i play in minecraft 1.10.2, the error should be gone ?
