### ISSUE TITLE
crash when rocket from asteroid mining mission returns

### ISSUE THREAD

**Issue by ToserBan** [zmaster587/AdvancedRocketry#1071]
Minecraft Version:
1.7.10
Forge Version:
1.7.10-1.2.0-345
Advanced Rocketry Version:
1.7.10-1.2.5.59
LibVulpes Version:
1.7.10-0.2.7.29
**is this the latest curseforge build?**
yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
crash when rocket from asteroid mining mission returns.
![grafik](https://user-images.githubusercontent.com/22052809/34997234-3520be26-fadc-11e7-95cf-dee4c573a6cb.png)

**Comment by ToserBan** [comment]
forgot to mention that i now cant see any mission progress inside the rocket monitoring station. I think, these two problems are one.

**Comment by ToserBan** [comment]
suggetions for some better german translations: disassemble is translated with "auseinandersetzen". Much better is "demontieren". Mission progress is translated with "Missionsvorankommen". Although germans would understand what is meant, there is no such word. Much better would be "Missionsfortschritt". The N/A shortcut is now translated with "nicht erreichbar". The translation is good, but it is so long, that the text appears outside the window box. So, either I would make a cr/lf after "Missionsfortschritt" or leave the N/A

**Comment by zmaster587** [comment]
The image you posted is of a generic network timeout and contains no information about the issue whatsoever, the same message could just mean a bad internet connection.  Can you send a copy of the forge log file or a crash report?

**Comment by ToserBan** [comment]
This problem didnt generated a crash report in the crash-report folder. To avoid the issue, i downgraded AR to the last beta now.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
