### ISSUE TITLE
overlapping planets

### ISSUE THREAD

**Issue by ToserBan** [zmaster587/AdvancedRocketry#1073]
Minecraft Version:
1.7.10
Forge Version:
1.7.10-1.2.0.345
Advanced Rocketry Version:
1.7.10-1.2.5
LibVulpes Version:
1.7.10-0.2.6
**is this the latest curseforge build?**
no
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
The planets in the solar system sol-3 and sol-13 are overlapping. Because they have the same distance from sun, the overlap dont get away from itself by time. I tried to fix this with the Orbital Theta tag but it didnt worked. I tried also to change the distance value of one of the 2 planets, but the game overrides my changes.
![sol-3](https://user-images.githubusercontent.com/22052809/35033735-04a0b25c-fb6c-11e7-8299-dc2931116b4a.png)
![sol-13](https://user-images.githubusercontent.com/22052809/35033736-04c41422-fb6c-11e7-9294-ddfec85f7293.png)

**Comment by zmaster587** [comment]
Close the game entirely, open the xml file, change the Orbital distance tag, then relaunch the game.  It is critical you close the game completely before opening the file in a text editor because the file is overwritten when the game closes by the most recent configs, this is required for ingame commands to take effect.  Alternatively, use the ingame /advRocketry planet set <dimid> orbitalDist <distance>  command.

**Comment by ToserBan** [comment]
Both didnt worked. i edited the planetdefs.xml in the .../saves/Worldname/advRocketry folder, thats right isnt it ? I set the orbital distance of Sol-13 to 250, but after starting my world, the old value of 200 is written into the file or better, the original file is restored.
Also i tried the command
/advRocketry Sol-13 set orbitalDist 250
it had no effect.

**Comment by zmaster587** [comment]
the proper command would be "/advRocketry planet set 13 orbitalDist 250" sorry for the confusion.

When you first opened the planetdefs file, was there an instance of minecraft running?

**Comment by ToserBan** [comment]
Ok, the proper command works and writes the new orbital distance into the xml file. But the 2 plantes are still overlapping in the warp controller "select planet" view. I cant remember if mc was running, when i first opened the planet defs file. Maybe i messed up something when i tried different versions of ar and deleted the whole \config\advancedrocketry folder in the meantime. Maybe thats the reason for some strange problems like the oxygen display of my space suit is not blue like it should be but is white. In a test world and in my brothers world it is blue.

**Comment by ToserBan** [comment]
just found the reason for the white oxygen display. Its the electromagnet from ender io. If i switch it on, the display is white, if i switch it off, the display is blue. Strange but ok.

**Comment by zmaster587** [comment]
can you send a copy of the XML with the differing planet distances where it still overlaps in the select planet view?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by PercyJames** [comment]
im having this issue in 1.12.2
