### ISSUE TITLE
cause graphical glitch with any shaders(on optifine)

### ISSUE THREAD

**Issue by Nanawith7** [zmaster587/AdvancedRocketry#1076]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.1.2587
Advanced Rocketry Version:
-1.2.6-49
LibVulpes Version:
-0.2.7-25
Optifine version:
HD_U_8
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Use any shader with this mod will cause unplayable graphical glitch
it seems only happens with AR version 1.2.6-48 and later 
Some example
https://imgur.com/a/kqdzX

**Comment by zmaster587** [comment]
Optifine is know to have interaction short of making a custom build of optifine, im not sure there's much that can be done short of removing some graphical features of AR.  As for this one, it's likely caused by the recent change to allow AR to render it's own skybox in the overworld, if that's the case this issue should occur on earlier versions of AR but only on planets.  There's a config option to disable the skybox override in the overworld, and one coming for planets in the next build.

**Comment by sp614x** [comment]
Looking at RenderPlanetarySky I see several things which may be problematic:

A. It uses a mix of GL11, OpenGlHelper and GlStateManager calls.
It is recommended to use ONLY GlStateManager as much as possible so its state doesn't get out of sync with the OpenGL state.
There is one line useing `OpenGlHelper.glBlendFunc(770, 771, 1, 0)` and a bit later `GlStateManager.blendFunc(SourceFactor.SRC_ALPHA, DestFactor.ONE)`. 

B. It uses BufferBuilder in mode TRIANGLE_FAN which may be problematic for shaders (not sure)
`buffer.begin(GL11.GL_TRIANGLE_FAN, DefaultVertexFormats.POSITION_COLOR);`

https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderPlanetarySky.java

**Comment by leagris** [comment]
### Work-around Shaders Compatibility

Edit `config/advRocketry/advancedRocketry.cfg` to disable custom skyboxes:
```
    B:PlanetSkyOverride=false
    B:StationSkyOverride=false
    B:overworldSkyOverride=false
```

**Comment by Garagoth** [comment]
Hi.

I have set those three options to false, so overworld looks fine now.
However, all dimensions from rftools dimensions still have flickering sky and shaders issues (stripped shadows).
Is there a way to disable AR skyboxes completely everywhere?
Or make then work with OptiFine ?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by tbreuerAcqua** [comment]
Still an issue running the Omnifactory modpack. 
White full screen, literally cant see anything.

Version: AdvancedRocketry-1.12.2-1.5.0-139-universal
Optifine: OptiFine_1.12.2_HD_U_E3

**Comment by Das-Hans** [comment]
> Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

Yes, this is still a problem, and changing the settings to false in the toml file does little to nothing  at all, it actually made the problem worse. 
Running Forge 1.16.5 36.0.42
Optifine 1.16.5 HD_U_G7
Sildurs Vibrant Shaders v1.283 High
(Screenshots taken midday in MC)
EDIT: There also doesnt seem to be a file @ config/advRocketry/advancedRocketry.cfg, and config wasn't available from inside MC itself, guessing this is a bug with Advanced Rocketry 1.16.5-2.0.0-10 build -10 for 1.16.5.
With default skybox off in shader settings.
![2021-05-01_12 04 49](https://user-images.githubusercontent.com/83508519/116788048-87bae480-aa75-11eb-8439-46f8d888bb28.png)
With default skybox on in shader settings.
![2021-05-01_12 05 11](https://user-images.githubusercontent.com/83508519/116788050-8ab5d500-aa75-11eb-94a6-7c1dc228b033.png)

**Comment by Das-Hans** [comment]
Using Continuum, the problems are less severe, but still very present

![2021-05-01_12 27 49](https://user-images.githubusercontent.com/83508519/116788653-d3bb5880-aa78-11eb-9d9a-14a2d05ecca1.png)
![2021-05-01_12 27 12](https://user-images.githubusercontent.com/83508519/116788655-d5851c00-aa78-11eb-9e7a-31c5f9403c0f.png)

**Comment by voidsong-dragonfly** [comment]
Optifine is unsupported
