### ISSUE TITLE
Custom sky textures not working on Moon/planets

### ISSUE THREAD

**Issue by lolmetimbers** [zmaster587/AdvancedRocketry#1077]
Hi there, I am using Soartex Fanver texture pack which has some really nice night sky textures + moon/sun sprites. These work on the overworld - world0 - dimension 0. However, when travelling to other planets or the moon it defaults back to the crappy minecraft night sky e.g - the sun is a square. The other problem is that the space station dimension also has vanilla skybox textures :x 

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/sky.properties
I have also tried creating a new world2 folder (for the moon) through the optifine mcpatcher but the custom sky does not work still. Do advanced rocketry planets render the sky differently from the overworld? How do you get night sky textures to work with Advanced Rocketry planets?

Please advise as I would like custom textures + planet/sun sprites from AR. The only workaround is perhaps using Just enough dimensions and then dimmapping it - but I'm afraid of losing the planet sprites in the sky.

Minecraft Version:
1.10.2
Forge Version:
2511
Advanced Rocketry Version:
1.10.2.5.a-74

**Comment by lolmetimbers** [comment]
So I can change the sun sprite by replacing sun.png in the textures/env folder which is a step forward...

However, the 'stars' are still a massive problem that breaks immersion. Are these procedurally generated? Would be fantastic if you could tweak this or make the sky compatible with textures or other mods such as stellarsky. Please let me know if there is any simple way to do the above^

**Comment by lolmetimbers** [comment]
Okay this is becoming even more frustrating. Using Just Enough Dimensions - I can get create a new dimension with CUSTOM sky textures working - if you teleport to the dimension everything is fine.

However, once you dimmap the dimension to a planet and then launch a rocket to it, AR completely overrides the sky settings and it reverts back to pixel textures. Furthermore, going back to the overworld breaks custom sky textures on Earth.

@zmaster587 Can you please provide a compatibility fix or option to turn off AR Skyboxes as it completely breaks/and is incompatible with texture mods. I cannot find a workaround for this at all.

**Comment by dmodoomsirius** [comment]
Did you turn off the config for the `B:overworldSkyOverride=true in the `advancedRocketry.cfg`?

**Comment by lolmetimbers** [comment]
Yes, I set it to false. This does prevents the overworld from being changed but any other planet (or dimension other than the overworld) still gets affected upon loading in with a rocket. If anyone can provide a fix I am willing to donate/pay as this is incredibly important to me for my project.

**Comment by zmaster587** [comment]
give me 5 minutes and I'll add a config option for planets too

**Comment by zmaster587** [comment]
Also second note: you can override AR's sun texture too

**Comment by lolmetimbers** [comment]
Thank you so much!

Yes, I just realised you can replace AR sun texture but Optifines MCPatcher is alot more powerful so you can create some amazing looking skys. Please let me know how I can support you mod/efforts financially.

**Comment by zmaster587** [comment]
It's a full sky overhaul mod?

**Comment by lolmetimbers** [comment]
It is Soartex Fanver https://soartex.net/downloads/

And it replaces the sky textures via Optifine's MCpatcher (Betterskies)
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/sky.properties

I noticed that the DIM ID has to be a low number or the patcher sometimes breaks. I will post a screenshot of what the night sky looks like in a sec

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.2.6-skyTest.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1649490/AdvancedRocketry-1.12.2-1.2.6-skyTest.jar.zip)

Can you try this and see how it works before I publish it?

**Comment by lolmetimbers** [comment]
sure one moment :p

**Comment by lolmetimbers** [comment]
Ok, after some extensive testing it still does not work with or without using JustEnoughDimensions

Working textures = Overworld, teleporting directly teleporting to new dimension
AR Textures = when going to space, landing on a new planet or dimmapped dimension

1.12 - latest optifine - that new test AR file - config has custom skybox true and overworldoverride = false

**Comment by zmaster587** [comment]
ah... right... I forgot that the skybox override is required to display the planet under the rocket.  Give me a bit.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.2.6-skyTest.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1649536/AdvancedRocketry-1.12.2-1.2.6-skyTest.jar.zip)

I think I've got the appropriate changes this time.

**Comment by lolmetimbers** [comment]
Ok testing now. Be right back!

**Comment by lolmetimbers** [comment]
Sigh, I still cannot get it to work. The skybox is still overwritten by AR as soon as you launch a rocket. Upon loading a new dimension (or planet) the screen shows a custom skybox for 1 second and then switches to AR again.

The only way to see a custom skybox is to directly teleport to the dimension. I am now going to test whether travelling from the Moon->Earth enables the custom skybox back on the overworld again.  Thank you for trying to fix it so far. If need be I can record a video.

**Comment by zmaster587** [comment]
Give me a few minutes to run tests

**Comment by zmaster587** [comment]
With overworldSkyOverride, PlanetSkyOverride, and StationSkyOverride set to false, using a rocket to go to a planet does not appear to change the skybox on my end.

**Comment by lolmetimbers** [comment]
OK I will try all false now

Uploading a video now to show you my current situation

**Comment by lolmetimbers** [comment]
https://www.dropbox.com/s/gmw60wnxoryirz7/Skybox-1.m4v?dl=0

Here is my example

Using Soartex Fanver and custom sky via optifine for dimensions 0 (overworld) and 5 (The Moon)

**Comment by lolmetimbers** [comment]
OMG it works on all FALSE!!!!!

I derped and thought the original settings of custom skybox meant the opposite. I would suggest just editing the description as "Use AR Skybox" where true=override and false=use own/vanilla.

Thank you so much for this! It has really opened up possibilities for having really immersive skyboxes for individual planets. I am currently developing a VR space experience for students (via AR + Vivecraft) and having amazing skyboxes makes it so much better.

I would like to donate $50 Australian dollars as a token of appreciation. Please leave your paypal account or contact me here: anthony.hermawan@cewa.edu.au

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
