### ISSUE TITLE
Shaders Graphical Glitch with version 48 and above

### ISSUE THREAD

**Issue by Nickk888PL** [zmaster587/AdvancedRocketry#1078]
Minecraft Version:
- 1.12.2

Forge Version:
- forge-1.12.2-14.23.1.2590-universal
MD5: fa6edeb7d1f09fcf9393440a50f77eaa

Advanced Rocketry Version:
- AdvancedRocketry-1.12.2-1.2.6-48
MD5: 2784bf809575286c0e9a438ee5625ef7
- AdvancedRocketry-1.12.2-1.2.6-49
MD5: 1c5ef78dc4797e5c81fbab326893426a

LibVulpes Version:
- LibVulpes-1.12.2-0.2.7-24-universal
MD5: 208e81d88637e2920dc0f92e3080bbd8

Optifine version:
- OptiFine_1.12.2_HD_U_C8
MD5: 4d9f34e3fb23ad5f4917fbe9e85623a0

**is this the latest curseforge build?**
Yes

Explain issue in detail:
This "Glitch" appears only on version 48 and above, version 47 and beyond works perfectly fine!
It happens when i enable a shaders pack, this appears on many Packs like Chocapic13's Shaders, Sushi Shader V2, Wisdom Shaders and so on. 

**Without Shaders:**
![2018-01-20_12 51 57](https://user-images.githubusercontent.com/35627647/35183149-8436dda8-fde1-11e7-8563-a21dcbdf2256.png)
**With Shaders:**
![2018-01-20_12 50 20](https://user-images.githubusercontent.com/35627647/35183148-841bf8b2-fde1-11e7-88cd-690779ae7d43.png)

**Comment by zmaster587** [comment]
see #1076
