### ISSUE TITLE
AoE: Warp core, and everything on the space station stopped working

### ISSUE THREAD

**Issue by eaanon01** [zmaster587/AdvancedRocketry#1079]
Minecraft Version:
1.10.2
Forge Version:
12.18.3.2511
Advanced Rocketry Version:
1.19.19
LibVulpes Version:
0.1.19

Crash Report:
----------
Explain issue in detail:
This is the newest AoE 1.1.2 version.

Been running the world as a mulitiplayer server and recently updated. Somthing happend to AdvancedRocktry.

The space station is stuck "Orbiting: Space". The warp controller cant find the warp drive, I cant select destination, the O2 is not working, the gravity setting is not working.

( server available for debugging )
![image](https://user-images.githubusercontent.com/10269034/35186538-17b32602-fe16-11e7-90df-60f0cab8de6a.png)

**Comment by zmaster587** [comment]
can you send a copy of the advRocketry/temp.day file?

**Comment by eaanon01** [comment]
The file is empty. 0 bytes

**Comment by zmaster587** [comment]
Can you upload a copy of the log file from before and after this occured, it seems very similar to #1004 in cause.

**Comment by eaanon01** [comment]
[temp.txt](https://github.com/zmaster587/AdvancedRocketry/files/1664839/temp.txt)
I just renamed it to .txt

**Comment by eaanon01** [comment]
The oxygen sometimes work it seems.. But when it does not work I cant hear the sound from it ( as of the upload dat file nothing works )

**Comment by eaanon01** [comment]
If it helps the server is available for testing / debugging. Not sure what caused it and how to reproduce.

**Comment by eaanon01** [comment]
I see that when I created a new space station the old one was fixed afterwards.

Still having a lot of problems with oxgygen sometimes not working.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
