### ISSUE TITLE
Oxygen Trace Crash

### ISSUE THREAD

**Issue by TheCowKing-moo** [zmaster587/AdvancedRocketry#1080]
Minecraft Version:
-1.12.2
Forge Version:
-
Advanced Rocketry Version:
[-1.2.6-49]
LibVulpes Version:
-0.2.7-25
**is this the latest curseforge build?**
no

#Please Pastebin crash
[pastebin link](https://pastebin.com/81JEuYcg)
---------------------
Crash Report:
----------
Description: Ticking block entity
java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle

Explain issue in detail:

We have a rather large space station without air. Attempted to close off a smaller part of the station (a room the size  of 15x15x9) and pressurize it. Couldn't find where the leak was and noticed the Oxygen Trace button in the GUI of the oxygen vent. Clicked it and had an immediate crash. Server continued to crash on start and was forced to rollback.

**Comment by zmaster587** [comment]
Missed a sideonly check in PacketX
