### ISSUE TITLE
Modules get destroyed with space suit

### ISSUE THREAD

**Issue by Ithronyar** [zmaster587/AdvancedRocketry#1081]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.1.2555
Advanced Rocketry Version:
-1.2.6-49
LibVulpes Version:
-0.2.7-25
**is this the latest curseforge build?**
Yes

Explain issue in detail:
When modules are installed in a space suit, they vanish when their suit parts break. I don't know if this is intentional or an oversight, but it can waste expensive resources and doesn't make a lot of sense. Break the suit, but not the separate add-ons. They should be popped into the inventory or dropped, not just disappear.

The wiki also says that the space suit shouldn't take damage or break, but mobs definitely damage it. That's how I found out all my expensive modules vanished when the suit broke. So maybe this report should be "Mobs damage space suits". But at least a breakable space suit makes some sense; deleted modules don't.

**Comment by zmaster587** [comment]
Can the mobs damage the spacesuits with only AR and libvulpes installed and nothing else?

**Comment by nonenothing** [comment]
Sure they do - my suits has also damaged before i install any other mods.
Also when i fly to station experience and level indicator just dissapear - and i can't enchant anything.
After returning to overworld and getting some experience - it's appear back.

**Comment by zmaster587** [comment]
@nonenothing I cannot replicate this in 1.12.
What I have done: 
Installed only AR and libvulpes from curse.
Put on a the full space suit
Spawn zombies and skeletons
Switch to survival and let them attack me
Result: spacesuit remains undamaged.  Though I also die.

**Comment by Ithronyar** [comment]
@zmaster587 Suit damage isn't always consistent. I tried the same thing, and indeed: No damage. Not at first. Then I spawned some zombie pigmen, and suddenly:
![spdmg](https://user-images.githubusercontent.com/26017430/35314254-cbd406b4-0079-11e8-9b4a-81db98da7302.png)

**Comment by zmaster587** [comment]
@Ithronyar Thanks!  That was enough info to track the issue down.  Fixed for next update.
