### ISSUE TITLE
assembling machine error

### ISSUE THREAD

**Issue by cwashington1217** [zmaster587/AdvancedRocketry#1084]
Minecraft Version: 1.7.10
-
Forge Version: 10.13.4.1614
-
Advanced Rocketry Version: 1.7.10-0.2.7-29
-
LibVulpes Version: 1.7.10-0.2.7-29
-
**is this the latest curseforge build?**
yes
# machine problem
---------------------
Crash Report: client suffered fatal error 
----------
Explain issue in detail: rocket assembling machine crash on rocket landing on launch pad 
[crash report.txt](https://github.com/zmaster587/AdvancedRocketry/files/1650169/crash.report.txt)

**Comment by zmaster587** [comment]
Do you have anything like thermos installed?  Does this occur with no other mods?

**Comment by cwashington1217** [comment]
like thermal dynamics or foundaton

**Comment by cwashington1217** [comment]
and i haven't found any thing else that does this

**Comment by cwashington1217** [comment]
Ok, i found out wasn't the assembler or other mods, it was an engine bug
more than one engine apparently crashes my client
