### ISSUE TITLE
[Request] Add Moon Turf to the Ore Dictionary

### ISSUE THREAD

**Issue by turbodiesel4598** [zmaster587/AdvancedRocketry#1087]
Hi there,

Dev of NuclearCraft here - someone just sent me a comment asking if there could be a way for GC moon turf to be harvested and processed in NC machines to produce small amounts of Helium-3. I thought that the same could also be possible for Advanced Rocketry moon turf. The easiest way for this to be implemented would be for moon turf to be added the ore dict, so then I can simply reference the entry in a new recipe on my side.

Would you be okay with this feature being added? Thanks in advance.

**Comment by radfast** [comment]
We suggest ```"turfMoon"``` as the OreDict name.

**Comment by zmaster587** [comment]
Sounds good

**Comment by turbodiesel4598** [comment]
Fantastic - thanks a bunch :)
