### ISSUE TITLE
[1.7.10] Fluid dupe with gas charge pad

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#1088]
gas charge pad only uses like 1/100th of what it's supposed to
so you can fill up tanks when they're in your armour, take them out, empty, repeat

**Comment by zmaster587** [comment]
It's a design flaw, before I made it so the suits used tanks, I had it fill the "fuel" amount some number of times the number of mb consumed to make it easier to fuel the jetpack, though with the tanks now this does make for an easy dupe.
