### ISSUE TITLE
gregtech compat (warp core does not oredict dilithium)

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [zmaster587/AdvancedRocketry#1090]
Minecraft Version:
1.7.10
Forge Version:
1614
Advanced Rocketry Version:
1.2.5-61
LibVulpes Version:
0.2.7-29
**is this the latest curseforge build?**
yes
#Please Pastebin crash
N/A
Crash Report:
N/A
Explain issue in detail:

The warp core does not accept GT5U dilithium.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
Can confirm by [looking at the code.](https://github.com/zmaster587/AdvancedRocketry/blob/b9733aaa946a6c4315a74b8e4d15a087dbff2324/src/main/java/zmaster587/advancedRocketry/tile/multiblock/TileWarpCore.java#L72)

I had to do some digging, but `MaterialRegistry.getItemStackFromMaterialAndType("Dilithium", AllowedProducts.getProductByName("CRYSTAL"))` is just keyword for "crystalDilithium"
