### ISSUE TITLE
Question: Is it possible to have two space stations?

### ISSUE THREAD

**Issue by gluff95** [zmaster587/AdvancedRocketry#1092]
Not a crash per se, but a genuine question: We already have a space station in orbit, launched by my friend which both of us use. When attempting to get another one set up, the rocket carrying the station launches just fine, and returns to earth. Attempting to travel there on a rocket results in the rocket arriving in empty space. Attempting to teleport to roughly where the coordinates of the space station are (locating it via the region file) results in a very glitchy hell where you are stuck randomly teleporting in this region of space, unable to move and with nothing visible but the skybox. So, is it possible to have two space stations?

**Comment by Jummit** [comment]
It is possible. Just repeat the process of building a space station, sending it in a rocket with the station id chip in orbit, and then travel with a rocket with the same id chip. Should work.

**Comment by gluff95** [comment]
My point is, it didn't work.

**Comment by zmaster587** [comment]
Yes, it is possible to have two stations.  Though the behavior you described I have yet to encounter despite having now built at least 10 stations.
What did you have on the rocket?
Did it have a guidance computer?  A seat?  Were you sitting on it when it went up?

**Comment by gluff95** [comment]
We're going to try to do it again and see if it works. I'll make sure to
document everything.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by gluff95** [comment]
Right, so due to the (still unfixed) issue where space elevator capsules are stuck in the air, the space station  never actually deployed, instead the rocket carrying the space station collided with the bugged capsules.
