### ISSUE TITLE
Pressurized tank: Fill/empty logic tweak & modes

### ISSUE THREAD

**Issue by Ithronyar** [zmaster587/AdvancedRocketry#1097]
One problem with pressurized tanks is their filling/emptying behavior with partially full containers. Let's say you have a pressure tank item with 1500/2000 oxygen in it. You want to refill it, so you go to your pressurized tank block for a refill. It has 63000/64000 oxygen in it: Plenty to refill your little pressure tank.

But wait, the tank block is too full! Since the pressure tank item isn't empty, it tries to dump all its oxygen into the block instead, but it can't because the tank is too full. Now you're left with just 500 oxygen in your pressure tank item, _and_ you can't refill it, despite having _64 buckets' worth_ right in front of you.

To fix this, I have two suggestions: Some internal logic tweaks to the tank block, and a toggle button for players to set automatic fill/empty behavior. Implementing one (or both) solutions would solve the filling/emptying problem with pressure tanks.

**Modified Tank Logic**
If an item placed in the input slot _isn't_ full and the tank _is_ full, the tank will fill the item in the input slot instead of doing nothing.
Depending on how tanks are used, this could cause unwanted behavior with automation. Which brings me to my next suggestion.

**"Mode" Button**
This basically allows players to override the default tank behavior, providing more robust automation possibilities and tank specialization.
This is a toggle button that cycles between Auto/Fill/Empty modes in that order. Different modes should probably change the block's texture in some way (like Thermal Expansion's blue/orange slot outlines for input/output ), to indicate to players what mode it's in without making them tediously look at its GUI every time they want to check.
Auto mode uses normal filling/emptying behavior. This is the default button setting.
Fill mode always tries to fill items placed in the input slot.
Empty mode always tries to empty containers placed in the input slot.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Ithronyar** [comment]
> 
> 
> Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

Still an issue in v1.5.0-131.
![2019-03-05_00 21 08crop](https://user-images.githubusercontent.com/26017430/53791058-52d69580-3edd-11e9-8624-6bb17774ecae.png)

Also, apparently tanks disappear when hovered over in the GUI.
