### ISSUE TITLE
Crash with Gravity Controller after launching to space station. 

### ISSUE THREAD

**Issue by ffh24054** [zmaster587/AdvancedRocketry#1100]
Minecraft Version:
1.7.10
Forge Version:
10.13.4.1614
Advanced Rocketry Version:
1.2.5
LibVulpes Version:
0.2.6
https://pastebin.com/vNZWJ8pQ
Crash Report:
I built a space station with a pre-built warp core and gravity controller and then launched it.  When trying to launch to it, the game crashes.  Upon a quick glance at the crash report, it appears the the pre-built gravity controller caused the crash.

**Comment by CTH999** [comment]
Yikes,

It is the gravity controller. (As far as I can Tell, I don't know java... YET!)


P.S

CONGRATS, YOU ARE THE 1100th ISSUE POSTER!

**Comment by zmaster587** [comment]
does this occur with the more recent versions of Libvulpes and AR?

**Comment by ffh24054** [comment]
No it doesn't occur, but a cosmetic note, the fuel, alt. vel. bars in the rocket are no existent
