### ISSUE TITLE
No water

### ISSUE THREAD

**Issue by Shurik1236** [zmaster587/AdvancedRocketry#1101]
Minecraft Version:
1.7.10
Forge Version:
1614
Advanced Rocketry Version:
AdvancedRocketry-1.7.10-1.2.5-60
LibVulpes Version:
LibVulpes-1.7.10-0.2.7-29

В реках и океанах нет воды.
В чём может быть проблема?
(Google)
There is no water in the rivers and oceans.
What could be the problem?

![2018-01-25_13 27 55](https://user-images.githubusercontent.com/17496452/35374264-bc8a3014-01d4-11e8-8f77-44b9e5661a22.png)
![2018-01-25_13 28 25](https://user-images.githubusercontent.com/17496452/35374265-bcb35b1a-01d4-11e8-990a-c189c7de94aa.png)

**Comment by Shurik1236** [comment]
> <galaxy>
	<star name="Sol" temp="60" x="0" y="0" size="1.0" numPlanets="0" numGasGiants="0">
		<planet name="Earth" DIMID="5">
			<isKnown>true</isKnown>
			<fogColor>0.58824,0.00000,0.53725</fogColor>
			<skyColor>0.58824,0.00000,0.53725</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>80</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
			<seaLevel>63</seaLevel>
			<biomeIds>145</biomeIds>
			<planet name="Volcanic" DIMID="4" customIcon="lava">
				<isKnown>true</isKnown>
				<fogColor>0.4,0.4,0.4</fogColor>
				<skyColor>0.4,0.4,0.4</skyColor>
				<gravitationalMultiplier>110</gravitationalMultiplier>
				<orbitalDistance>100</orbitalDistance>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>128000</rotationalPeriod>
				<atmosphereDensity>150</atmosphereDensity>
				<seaLevel>63</seaLevel>
				<biomeIds>102</biomeIds>
				<OreGen>
				<ore block="minecraft:coal_ore" minHeight="5" maxHeight="160" clumpSize="16" chancePerChunk="20" />
				<ore block="minecraft:iron_ore" minHeight="5" maxHeight="72" clumpSize="8" chancePerChunk="14" />
				<ore block="minecraft:gold_ore" minHeight="5" maxHeight="30" clumpSize="12" chancePerChunk="3" />
				<ore block="libVulpes:libVulpesore0" meta="10" minHeight="5" maxHeight="20" clumpSize="5" chancePerChunk="2" />
				<ore block="libVulpes:libVulpesore0" meta="8" minHeight="5" maxHeight="32" clumpSize="6" chancePerChunk="8" />
				<ore block="minecraft:diamond_ore" minHeight="5" maxHeight="20" clumpSize="12" chancePerChunk="2" />
				<ore block="Thaumcraft:blockCustomOre" minHeight="5" maxHeight="160" clumpSize="1" chancePerChunk="16" />
				<ore block="Thaumcraft:blockCustomOre" meta="2" minHeight="5" maxHeight="160" clumpSize="4" chancePerChunk="20" />
				<ore block="Thaumcraft:blockCustomOre" meta="4" minHeight="5" maxHeight="160" clumpSize="4" chancePerChunk="20" />
				<ore block="Thaumcraft:blockCustomOre" meta="6" minHeight="64" maxHeight="160" clumpSize="2" chancePerChunk="8" />
				</OreGen>
			</planet>
			<planet name="Snow1" DIMID="6" customIcon="EarthLike">
				<isKnown>true</isKnown>
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>1.0,1.0,1.0</skyColor>
				<gravitationalMultiplier>100</gravitationalMultiplier>
				<orbitalDistance>150</orbitalDistance>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>16000</rotationalPeriod>
				<atmosphereDensity>100</atmosphereDensity>
				<biomeIds>3,131,34,162,133,5,19,32,160,0</biomeIds>
			</planet>
		</planet>
	</star>
</galaxy>

Это ещё просто набросок.
(Google)
This is just a sketch.

**Comment by Shurik1236** [comment]
Обновил до версии 1.2.5-63. Проблема осталась.
Updated to version 1.2.5-63. Problem still exists.

**Comment by zmaster587** [comment]
I'll try to look at it tomorrow, today has been really busy for me.

**Comment by zmaster587** [comment]
water block accidently was set to null if it was not set anywhere in the config.  Fixed for next build.

**Comment by Shurik1236** [comment]
Подождите, блок океана указывается в planetDefs? А как он указывается?
Wait, the ocean block is indicated in the planetDefs? And how is it indicated?

**Comment by zmaster587** [comment]
It can, it should be in the wiki soon, it's the <oceanBlock></oceanBlock> tag.  So you can put minecraft:dirt for example and it'll use dirt for the oceans instead, tested with forestry milk, oil from tech reborn, minecraft vanilla chests (for the love of all things good don't use chests as an ocean block)
