### ISSUE TITLE
Various space elevator bugs (glitchy capsules & disappearing chip)

### ISSUE THREAD

**Issue by Ithronyar** [zmaster587/AdvancedRocketry#1103]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.1.2555
Advanced Rocketry Version:
-1.2.6-52
LibVulpes Version:
-0.2.7-26
**is this the latest curseforge build?**
Yes

Explain issue in detail:
This is a multi-layered issue, unfortunately. Space elevators and their capsules can be pretty buggy.
I have an Earth-station space elevator. On one trip from the space station, I noticed the capsule had gone black and the screen was severely jittering up and down. Seemed like some harmless desync, so I wasn't worried.

Then Earth loaded, and I instantly died miles up in the sky because I "hit the ground too hard", even though I was safe in the space elevator capsule. Even though I have a gravestone mod, it was above the block-placing limit, so my items flew everywhere anyway. That was... irritating.
Side note: That was for Advanced Rocketry v1.2.6-50. I had just used a gravity controller on my space station, so gravity was still adjusting when I went in the elevator. That might have been related; I don't know.

Later, I went up the Earth space elevator back to my station, this time with the latest version (v1.2.6-52). No black capsule, no jittering. Everything was stable. But a couple minutes later, the space station still hadn't loaded. I tried to exit the capsule, but it instantly kept popping me back in.

I finally managed to escape the capsule, and I saw this: 
![bugtasticcapsules](https://user-images.githubusercontent.com/26017430/35422344-069ad118-01fd-11e8-863b-c2ef1930f65e.png)

...It was the capsule I died in. Now both are stuck, and I can't use the elevator. My world is littered with broken space elevator capsules, so this is nothing new. The others were caused by moving space elevators around in older mod versions. That seems to be fixed now, but they're still there.

Then I encountered another bug. When trying to fix this latest annoyance with space elevator capsules, I broke and rebuilt the multiblock structure, looked in the space elevator's GUI, and... no chip. It seems to have vanished when I dismantled the space elevator. Yes, I looked on the ground. And I have a magnet item that picks things up from a distance, so I would have had the chip if it fell out anyway. I'm guessing the space elevator block doesn't drop its contents when broken, so the chip just vanishes.

So now my world has two more broken space elevator capsules, I've lost an expensive space elevator chip with three entries on it, and now I'm afraid to even use the elevator on my space station because I might die when going back to Earth. I think I'll just use rockets for now.

**Comment by zmaster587** [comment]
#800 I think is the same, linking for organization

**Comment by zmaster587** [comment]
Chip thing I didn't know of before now, fixing that.

**Comment by zmaster587** [comment]
should be fixed in next build
