### ISSUE TITLE
biome changer satellite not powered

### ISSUE THREAD

**Issue by Yogscastlalna** [zmaster587/AdvancedRocketry#1104]
I've launched a number of biome changing satellites with no success. Ive tried with 5 solar panels and a battery but when I use the biome scanning remote they never have any power

**Comment by zmaster587** [comment]
It does work if you use the three of the x2 batteries and 3 large solar panels, however it probably ought to work with the smaller varients as well.

**Comment by zmaster587** [comment]
Found another issue in the process, power storage was accidently being set to powergeneration, that's also fixed.
