### ISSUE TITLE
Rocket landing enhancement

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1105]
I don't like how you cant control where rockets land. It is hard to automate, and you cannt make a spaceport where rockets start and land. I have no idea ho to fix this though. Maybe make a new Pad ID chip that you can link to a landing site, kind of like the space station landing pad.

**Comment by zmaster587** [comment]
You can already do that with the landing pads and linkers I think?

You can link a linker to a landing pad by shift right clicking on the landing pad (we'll call it A) with the linker.  Then you can put the linker into another landing pad (B).  If a rocket takes off from B it will fly to A.  This works both in space to planet, planet to planet (with warp core on the rockeet), planet to same planet, and planet to moon.

If that doesn't work for you, can you clarify?

**Comment by Jummit** [comment]
Sorry that I didn't make myself clear. It was more like a question. I searched for a possibility to control where a rocket lands in the wiki and found nothing, it looks like the [Docking Pad page](http://65.78.115.159:8000/AdvancedRocketry/blocks/LandingPad.php) should be updated. I will close this now.

**Comment by dmodoomsirius** [comment]
@Jummit by the way the wiki was moved to http://arwiki.dmodoomsirius.me/AdvancedRocketry/blocks/LandingPad.php
