### ISSUE TITLE
Possible Bug / User Error : Rocket won't go mining

### ISSUE THREAD

**Issue by TheCowKing-moo** [zmaster587/AdvancedRocketry#1106]
Minecraft Version:
-1.12.2

Advanced Rocketry Version:
-1.2.6-47
LibVulpes Version:
-0.2.7-25

[Pictures of setup](https://imgur.com/a/ceRp2)

Explain issue in detail:

Trying to get my rocket to go asteroid mining. The chip is loaded into the guidance computer and the rocket is fueled, but when I click launch on the monitoring station nothing happens (I do hear a click). I noticed that there are two guidance computers when shift clicking the rocket despite only one computer in said rocket. When clicked they both store to the same location. 

I've used this same launch pad to get satellites into orbit so I know there are no issues with the flight path. or the pad itself. 

I have made modifications to the asteroidConfig.xml so maybe I messed that up? [asteroidConfig.xml](https://pastebin.com/UUXMaWSS)

I have noticed that the asteroid chip only holds 1000 of each data but most guides I attempted to follow had 2000 of each.

**Comment by zmaster587** [comment]
May be related to recent changes to when rockets are allowed to take off, are you launching from a planet or station?

**Comment by TheCowKing-moo** [comment]
Oh forgot to mention that. This is from a station.

**Comment by zmaster587** [comment]
Got it, should be fixed next build
