### ISSUE TITLE
Space Station not deploying when sent up with rocket

### ISSUE THREAD

**Issue by CyNightCBG** [zmaster587/AdvancedRocketry#1108]
Having issue with space station not building once the rocket has entered space. It leaves the satellite bay once it enters space, however nothing shows up. Going back to earth and attempting to go back using the station is chip only results in going into space and right back. There is no space station to go to. 
# If enabled, any request for a chunk not currently loaded will be denied (exceptions apply for things like world gen and player movement). 
        # Note: As this is an experimental setting for performance gain, if you encounter any issues then we recommend disabling it.
        deny-chunk-requests=false

Multi-player server.

AdavancedRocketry-1.12-1.2.6-42

sponge/spongeforge-1.12.2-2555-7.1.0-BETA-2822

**Comment by TheCowKing-moo** [comment]
A player on the server I am on had a similar issue where if he launched a premade station a cube the size of 8x8x5 would have the exact error that you describe. He tried again with a simple 5x5x1 platform and  it worked fine. 

note: This was the second player generating a space station if that helps at all. 
note: The player went up with the rocket building the station the station the second time.

AR ver: 1.12.2-1.2.6-47

**Comment by K1ltu** [comment]
change
deny-chunk-requests=true to deny-chunk-requests=false
in /config/sponge/worlds/advancedRocketry/space/DIM-2/world.conf (assuming you left the defauld dimension id for space)
and that should fix your issue

**Comment by CyNightCBG** [comment]
Changing that config did not work. Problem is still there.

**Comment by K1ltu** [comment]
Look in my profile for the repository unlimitedtech it contains working sponge configs for adv rocketry in config/spong its confirmed working on the packs official server so if it does not work for you it has to be a mod conflict

**Comment by shdwdrake8** [comment]
I have this same issue and am not using sponge as the mentioned folders don't exist. I am using the Revelation 1.8.0 pack but have adjusted the planet configs to have actual planets. Easily replicated as I can send stations into space, follow them with a rocket, and there's just empty space and I fall forever.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
