### ISSUE TITLE
Biomes terrain is incorrect.

### ISSUE THREAD

**Issue by Arashiiku** [zmaster587/AdvancedRocketry#1110]
Minecraft Version:
-1.7.10
Forge Version:
-10.13.4.1614
Advanced Rocketry Version:
ar 1.2.5

LibVulpes Version:
vulpes 0.2.6

Latest Curseforge Yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Biomes arnt spawning in correctly, they ahev right names and stuff but they dont have the correct terrain.

**Comment by zmaster587** [comment]
Can you pastebin a copy of the forge startup log?

**Comment by Arashiiku** [comment]
[fml-client-latest.log](https://github.com/zmaster587/AdvancedRocketry/files/1676181/fml-client-latest.log)

**Comment by zmaster587** [comment]
Does this issue occur without RTG?

**Comment by Arashiiku** [comment]
Im not sure i'll have the mod pack maker look into it.

**Comment by Arashiiku** [comment]
yes, it does occur sans RTG

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
