### ISSUE TITLE
Crash from fragile string-parsing code in SatelliteParserNoDrill.java

### ISSUE THREAD

**Issue by Baughn** [zmaster587/AdvancedRocketry#1113]
Minecraft Version: 1.12.2
Forge Version: 14.23.1.2604
Advanced Rocketry Version: 1.2.6-54
LibVulpes Version: 0.2.8-27

Crash Report: https://madoka.brage.info/crash-reports/crash-2018-01-30_15.22.41-server.txt

The parsing code in https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/satellite/SatelliteLaserNoDrill.java#L56 assumes that ore names contain colons. It may be incorrect for them not to, but clearly it can happen.

Due to #1112, I can't debug the issue in more detail.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Baughn** [comment]
This appears to have been fixed by https://github.com/zmaster587/AdvancedRocketry/commit/e35186134cd6698486a9a2ee8f907e0f8425f01f
