### ISSUE TITLE
Enabling AdvRocketry lets my lights and shadows disappear...

### ISSUE THREAD

**Issue by dornenfeld** [zmaster587/AdvancedRocketry#1115]
Minecraft Version:
-1.12.2
Forge Version:
-newest
Advanced Rocketry Version:
-1.2.6-49
LibVulpes Version:
-0.2.7-25-universal
 
Optifine + Sildur Shader (also tested on Chocapic13)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
