### ISSUE TITLE
Observatory does not function if built above 128

### ISSUE THREAD

**Issue by mskurnik** [zmaster587/AdvancedRocketry#112]
My server's build height is set to 256 and it seems that building the observatory above 128 causes it not to open at night.  It does form the multiblock structure however.

**Comment by zmaster587** [comment]
I'm having difficulty replicating the issue on my test server.
Did you make sure to build in at least one data bus and and least one power source and to turn it on though the interface on the observetory block?  And is there anything above the observetory structure?

**Comment by mskurnik** [comment]
There was nothing above my observatory.  It turned out my server was just being odd and after a restart, everything worked.  You can close the bug.
