### ISSUE TITLE
I go blind when scanning my rocket

### ISSUE THREAD

**Issue by Kacymythom** [zmaster587/AdvancedRocketry#1121]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.1.255
Advanced Rocketry Version:
-1.12.2-1.2.6-54
LibVulpes Version:
-1.12.2-0.2.8-27
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail: It doesn’t particularly cause a crash. It makes it so I’m unable to see. It basically turns my screen a sky blue color until I look away from the scanning animation. However if I’m far enough away or looking away from it I can see perfectly fine. It even overlays the menus, being I can’t even see the disconnect or options button.

**Comment by Kacymythom** [comment]
After further experimentation me and a friend have noticed it’s only on my end but not theirs. It also seems to be that I can look at it when underwater (as useless as it sounds). Also it’s not a server issue, since I’ve been studying it in single player. We have exactly the same Mods installed so I’m not sure what is going on.

**Comment by zmaster587** [comment]
This is a known issue with optifine/betterfps, are you using either of those?

**Comment by Kacymythom** [comment]
Ah yes definitely using both, is there a way to fix it in settings?

**Comment by CTH999** [comment]
Could be a feature though! It could be a strange radiation from scanning, and It causes you to go temporarily blind! So, don't look, or have a space suite!

Just an idea though!

**Comment by zmaster587** [comment]
@Kacymythom there might be, you'd have to play with it I think, it's been a while since I used either mod.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
