### ISSUE TITLE
Stuck in an elevator

### ISSUE THREAD

**Issue by FaolanKusibo** [zmaster587/AdvancedRocketry#1122]
Minecraft Version:
-1.11.2
Forge Version:
-13.20.0.2315
Advanced Rocketry Version:
-1.2.5a
LibVulpes Version:
-1.11.2  0.2.4
**is this the latest curseforge build?**
No

Explain issue in detail:
The space elevator works just fine for the most part until a single capsule gets stuck in the at the beginning of the decent, making other attempts to use the elevators useless. There is no apparent reason for one to get stuck like that, no opticals, entities, any form of collusion, nor any specific condition is there. It happens across planets, moons, and stations in every world I create.
In survival mode, the stuck capsule will kill you labeling it fall damage, so perhaps a bug happened and two capsules were summoned at once causing a coalition.

**Comment by zmaster587** [comment]
This should have been fixed in the most recent alpha build for 1.11.2, can you try that and report back?

**Comment by FaolanKusibo** [comment]
It works! But I ran into a crash while rocketing from the moon back to earth, But I don’t think Advanced rocketry was the culprit as it crashed 5 hours into gameplay.(sent a sat and went afk) But yea, Problem fixed!
