### ISSUE TITLE
Suggestion: Solar generator power output varies with sun proximity/brightness

### ISSUE THREAD

**Issue by Ithronyar** [zmaster587/AdvancedRocketry#1123]
Basically, the brighter the sun is relative to the solar generator, the more power it produces. If you were in an orbit close to the sun, solar generators would produce a huge amount of power. If you were in the outer solar system, you would need a giant array of panels just to produce a few RF per tick.

**Comment by NutMaster6942** [comment]
So, basically the brighter the star and the closer the orbit of the planet, the more power output?

**Comment by Ithronyar** [comment]
> 
> 
> So, basically the brighter the star and the closer the orbit of the planet, the more power output?

Yes, exactly.

**Comment by NutMaster6942** [comment]
> > So, basically the brighter the star and the closer the orbit of the planet, the more power output?
> 
> Yes, exactly.

This is a great idea.

**Comment by Gliese-832-c** [comment]
Possibly compatability with other solar panels like those from NuclearCraft could be added.
