### ISSUE TITLE
Equipping a Space Suit with a Jetpack Permanently slows creative flight from angel ring.

### ISSUE THREAD

**Issue by Castone22** [zmaster587/AdvancedRocketry#1126]
Minecraft Version:
- 1.12
Advanced Rocketry Version:
- 1.12.2-1.2.6-54
LibVulpes Version:
- 1.12.2-0.2.8-27
**is this the latest curseforge build?**
Yes

Involved Mods:
Botania, EXU2, AR

Replication:
Equip Angel Ring with Globetrotters Sash and give yourself a mana tablet.  Fly around a bit, note that your speed in all direction is unhindered.

Give yourself a Space Suit Chest with a Jet Pack and fly around a bit, then remove the space suit.

Try flying with creative and note that your speed forward is still unhindered, though up, down, sideways and back all now have the move speed you would have using the jetpack.

*Update*
As a work around, killing yourself resets your speed.

**Comment by zmaster587** [comment]
#1054

**Comment by zmaster587** [comment]
Redid flight speed in next build, should no longer interfere
