### ISSUE TITLE
Message spam and crash on world enter

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1127]
Minecraft Version: 1.12
Advanced Rocketry Version: 1.2.6-52
LibVulpes Version: 0.2.7-24
Game output: https://pastebin.com/0RnAZt8U
Explain issue in detail:

I used a custom planetDef file, this here; https://pastebin.com/dewntJk0
When I try to enter the world, it freezes. Something like this also happens when you have an xml with wrong syntax. But this one (with correct syntax) spams a massage in the game output.
I changed the planetDef.xml a few times, maybe this is the problem?

**Comment by zmaster587** [comment]
Without the rest of the message, the game output unfortunatly isn't all the helpful.  The type of error is not included, nor is most of the stack trace.  Would it be possible to send a copy of the report with a few lines above and at least 50 lines below the first line in the file you've send?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
