### ISSUE TITLE
Cannot get on a second rocket seat

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1128]
Minecraft Version:
1.10.2
Advanced Rocketry Version:
1.2.5a
LibVulpes Version:
**is this the latest curseforge build?**
Yes

Explain issue in detail:
When I travel from my homeworld to a moon... and I build a second spaceport there with a second rocket, I cannot sit on that rocket as if it would not have a seat.

This happend to me multiple times:
Once when I had one rocket with a seat and build a second spaceport with a second rocket
Second time when I traveled to a moon, lost the rocket on landing (it felt into void, I saved myself using jetpack) and so built a new one on a new spaceport.

In both cases the second rocket was the same as the first one, had guidance computer and seat... except I could not board this rocket for some reason. Do you have some advice what to do in such a case? I am trying combinations of assemble/disassamble, replacing the Rocket Assembler, restarting the Saved Game and the whole Minecraft, but so far I have no pattern how to fix it.

I tried several rockets... from the second cosmodrom, none accept passangers.
From the first cosmodrom however, it acceps passangers as normal.

**Comment by zmaster587** [comment]
Can you send screenshots of the rockets that are not working?

**Comment by gdarai** [comment]
Sure thing... just, that is the same skeletal rocket I use in the whole pack... Engines + Fuel Tanks + 1 Guidance Computer + 1 Seat... And the Same rocket works from cosmodrome 1... and does not work from cosmodrome 2. Today I will try to find out what is the mod/setting constelation, which is causing this... I will send you the screenshots in few minutes.

**Comment by gdarai** [comment]
Ok, did some trials...and I figured out following: The Cosmoport 2 Location is wrong for some reason.
All ships I launched from it disapeared and did not arrived into their destination... Also All ships with seat did not registered as passanger ships. I was able to force the ships to land back by breaking n placing on random places the Rocket Assembler of this SpacePort.

Then i tried different locaton (SpacePort 3) and the ship was registered as passanger there and worked.... so I was thinking that maybe the height is wrong (SpacePort 2 was on Y=150 and SpacePort 3 on common Y=70) So I built SpacePort4 on Y=170... but this one also worked.

So I have no clue and I did not figured out how to make that SpacePort2 to work. But now I know that moving it can help, which is good enough for me now.

A pro po, when I link with linker 2 SpacePorts, each in a different Dimension, can I force a rocket if i flies from the first to the other dimension use exactly those spaceports? Which block do I Link with the Linker in such a case?

**Comment by EasterncheesE** [comment]
I did have this issue on 1.7.10 server (about the seat).
Usually, just disassembling the rocket and putting the seat to some other place on the rocket helps to fix it.

**Comment by zmaster587** [comment]
I'm almost wondering if there's invisible blocks or something.  Try opening it in MCedit or something maybe?

@EasterncheesE are there any patterns?  Does it only happen if the seat is the topmost block for instance?

**Comment by EasterncheesE** [comment]
Hello. Not, actually, i cannot find any system in this bug. Sometimes it's the topmost block, sometimes it's not.
Also, there are no invisible blocks in the rocket. 

As for my server, the issue happens pretty rarely and is always fixed by moving the seat to other place.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
