### ISSUE TITLE
"Attempted to load class btf for invalid side SERVER", particles are being loaded serverside

### ISSUE THREAD

**Issue by Yantrio** [zmaster587/AdvancedRocketry#1129]
Minecraft Version: 1.12.2
-
Forge Version: 14.23.1.2601
-
Advanced Rocketry Version: 1.12.2-1.2.6-50
-
LibVulpes Version: 1.12.2-0.2.7-25-universal
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report: https://gist.github.com/Yantrio/c17d4495eb36bc87eedca03c4ce7b3b0
----------
Explain issue in detail: Looks like the mod is trying to load a particle server side.

**Comment by zmaster587** [comment]
fixed in build 1.12.2-1.2.6-52 and later

**Comment by Yantrio** [comment]
Confirmed to be fixed in latest unstable version, thanks 👍
