### ISSUE TITLE
Game crashes when a rocket lands

### ISSUE THREAD

**Issue by CrazyGamer313** [zmaster587/AdvancedRocketry#1130]
Minecraft Version:1.7.10
-
Forge Version: latest 1558
-
Advanced Rocketry Version: 
in error log
-
LibVulpes Version:
unknown
-
**is this the latest curseforge build?**
yes

#Please Pastebin crash
https://pastebin.com/S7Dt0enj
Crash Report:
as stateed in title
----------
Explain issue in detail: everi time in SP and MP when an rocket is about to land from any mission the game or server crashes and the save file gets coruppted

**Comment by zmaster587** [comment]
This is indicating that the world object itself is becoming null somehow, does this occur with only AR and libvulpes installed?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
