### ISSUE TITLE
Rocket Seat height bugged in VR

### ISSUE THREAD

**Issue by lolmetimbers** [zmaster587/AdvancedRocketry#1131]
Minecraft Version:
1.10.2
Advanced Rocketry Version:
- 1.10.2 - build 77 Unstable

Very similar issue to this one https://github.com/micdoodle8/Galacticraft/issues/3100
 where upon **'sitting' on the seat on the rocket my view in virtual reality (vivecraft) is positioned UNDER the seat instead of over it.**

Wondering if there is a specific source code that I can edit and then recompile so I can give you a good value for Vivecraft + add an option in config. For now easy workaround is to position seat above head.

Side bug: Build 79 Unstable - it seems the rocket assembling machine is broken, i cannot open it when using right click.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
