### ISSUE TITLE
Crash on interaction with Guidance Computer

### ISSUE THREAD

**Issue by Eeverion** [zmaster587/AdvancedRocketry#1132]
Minecraft Version:
1.10.2
Forge Version:
1.10.2-12.18.3.2511
Advanced Rocketry Version:
1.2.5
LibVulpes Version:
0.2.6
----------
Crash Report:
https://pastebin.com/rjDa7dfV
----------
Explain issue in detail:

Minecraft crashed when I clicked on the guidance computer to interact with it. After this minecraft crashes everytime when loading the world.
The modpack (Resonant Rise 4.3.0.3b) has run without problems for at least 3 weeks.

Edit: Vsync & VBOs are both on (and were always on). No new mods have been installed or removed prior to the error.

Edit2: I've started a new world, build a new rocket, also crash. This time it occureed when I right clicked on the rocket (specifically a fuel tank).
https://pastebin.com/5neZAxBc

**Comment by zmaster587** [comment]
Does it occur in the latest version of the mod?  https://minecraft.curseforge.com/projects/advanced-rocketry/files/2525398

**Comment by Eeverion** [comment]
The modpack (Resonant Rise) doesn't have the newest version of AR yet.
I'm now using 1.2.5a for over a week and haven't had any issues so far. I can't reproduce the bug anymore, so I'm closing this thread.
