### ISSUE TITLE
Override GC air config is not working in 1.12.2

### ISSUE THREAD

**Issue by Saereth** [zmaster587/AdvancedRocketry#1135]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.2.2611
Advanced Rocketry Version:
-1.12.2-1.2.6-54
LibVulpes Version:
-1.12.2-0.2.8-27
**is this the latest curseforge build?**
yes
#Please Pastebin crash
---------------------
Crash Report: Not a crash
----------
Explain issue in detail:
Enabling the option to override GC's air is not working with the most recent versions of GC and AR, here is an album showing the issue
https://imgur.com/a/Dio4g

From the config: 
"mod interaction" {
    # If true Galaciticcraft's air will be disabled entirely requiring use of Advanced Rocketry's Oxygen system on GC planets
    B:OverrideGCAir=true
}

GC versions:
GalacticraftCore-1.12.2-4.0.1.132
Galacticraft-Planets-1.12.2-4.0.1.132
MicdoodleCore-1.12.2-4.0.1.132

If there is anymore testing or data you'd like me to collect lemme know, thanks!

**Comment by zmaster587** [comment]
I'll take a look

**Comment by cwashington1217** [comment]
I've had the same problem but i couldn't find an answer for weeks maybe GC and AR should talk about there mod interactions.

**Comment by Saereth** [comment]
Any word on this? We're working on a big expert pack and would like to feature both ar and gc, but without unified air system we feel we'd have to end up picking on for consistency.

**Comment by zmaster587** [comment]
Currently in the process of upgrading GC handling to 1.12

**Comment by zmaster587** [comment]
for the time being, I would advise setting the mass of GC planets to 1.0 until  a workaround for gravity interaction can be found

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
