### ISSUE TITLE
Orbital Laser Dissapearing / Crash

### ISSUE THREAD

**Issue by TheCowKing-moo** [zmaster587/AdvancedRocketry#1136]
Minecraft Version:
-1.12.2
Forge Version:
-
Advanced Rocketry Version:
-AdvancedRocketry-1.12.2-1.2.6-54
LibVulpes Version:
-LibVulpes-1.12.2-0.2.8-27-universal

[Crash](https://pastebin.com/jabRYycf)
[Pictures](https://imgur.com/a/NzeSv)

Explain issue in detail:

The Orbital Laser I have setup likes to have a lot of blocks that build the multi block just disappear if I leave the station.  If you hover your mouse over the "missing" blocks you can see the outline of them and you can still mine them up. Typically I can just mine up a block, the multi block breaks and all of the other blocks appear fine. I put mined block back down and rebuild the multi block. This time I mined up the Orbital Laser block and popped it back down and crashed.

**Comment by zmaster587** [comment]
Can you send a copy of the advRocketry/advRocketry.cfg?  it's looking like it's being given an invalid oredictionary name in the list of ores somewhere.

I've added code to prevent it from crashing there and provide a log output with the invalid ore to make things a bit more clear as to the exact ore causing the problem

**Comment by TheCowKing-moo** [comment]
[advancedRocketry.cfg](https://pastebin.com/p6p5wGEf)
I added a lot of ores to the config so that could be the issue.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
