### ISSUE TITLE
Atmosphere Terraformer testing in Dimension 0 (overworld) vs. Dim 3 (luna)

### ISSUE THREAD

**Issue by Tedyhere** [zmaster587/AdvancedRocketry#1137]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.2.2613
Advanced Rocketry Version:
-1.12.2-1.6.20
LibVulpes Version:
-1.12.2-0.2.8-27
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report:
n/a
----------
Explain issue in detail:
The Atmospheric Terraformer does not work on Dimension 0.
Steps I have taken to make sure it was done correctly
1) Biome Changing Satellite is Airborne and Connected to the Biome changing Remote
  - I tested changing a Biome and it worked as expecte
2) Modified config to not require fluids for the Terraformer to work
3) Built terraformer and put Biome Remote inside
   - I should mention I modified the Overworld (Dimension 0) to have 0.25 Atmosphere
4) Clicked Increase Atmosphere
5) Checked status, said was running, checked back after 1 hour and Atmosphere was still at 0.25

I than moved everything to the Moon
Repeated steps 1 through 5  Except now the Atmosphere of the Moon is at 0.02 after 30 minutes.
I believe the Atmosphere of Dimension 0 is not being affected by the Atmosphere Terraformer for some reason.

Is it possible for you to test this? I can zip the config folder up for you to use if need be.

**Comment by zmaster587** [comment]
You are correct about dim 0 not being affected by the terraformer.  The terraformer was designed to not work in the overworld out of fear that if the atmosphere were removed it would be possible for people top softlock the game (death, respawning in overworld, suffocation loop) and I didn't want that to be possible.

**Comment by Tedyhere** [comment]
Could you make it configurable? If not that is fine, I can start my modpack in another dimension I suppose and just blacklist dimension 0.  The modpack I am making assumes the Overworld has been decimated and the atmosphere has mostly been burned off leaving 0.25 atmosphere and there are Biospheres scattered around that are extremely old that can be pressurized for safety.  The overarching goal of the modpack is to eventualy repopulate the overworld.

**Comment by zmaster587** [comment]
I could make it configurable with default to false, that's a quick change to make.
