### ISSUE TITLE
Space station coordinates are buggy

### ISSUE THREAD

**Issue by l4stofunicorn** [zmaster587/AdvancedRocketry#1138]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.2.2613
Advanced Rocketry Version:
- 1.2.6-54

LibVulpes Version:
- 0.2.8-27
**is this the latest curseforge build?**
 - yes, it is.

Explain issue in detail:
My space station is very buggy! I can't move to the platform I built, when I leave the rocket I flew with.
In the console chat (Playing in MP) it says "<name> moved too quckly".

Note: I changed the option "# The largest size a space station can be.  Should also be a power of 2.." in config to 2024  BEFORE creating anything. (I will test it with the default option and give you information more later.
My coordintes in the dimension are x1024 z-3075
Note: I can move to -x and -z but not to my station

**Comment by l4stofunicorn** [comment]
Fixed it:
Simply changed config setting "Largest size a space station can be" to default (1024)

**Comment by zmaster587** [comment]
2024 is not a power of 2, try 2048.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
