### ISSUE TITLE
No planet exept earth at the destination screen.

### ISSUE THREAD

**Issue by Tropicaner** [zmaster587/AdvancedRocketry#1139]
Minecraft Version:1.1.12
-
Forge Version:
-
Advanced Rocketry Version:1.12.2-1.2.6-50
-
LibVulpes Version:1.12.2-0.2.7-25-universal
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail: I can´t find any other planet than the earth when I want to set my destination. I can launch a rocket but as I told only to earth. And I cant see the star systems when I'm clicking at up.

**Comment by C1ffisme** [comment]
> I can launch a rocket but as I told only to earth.

If you've launched a rocket, you'll only be able to get to moons around that planet. You need to use a space station to get to other planets. Is this your issue?

**Comment by Tropicaner** [comment]
No, I can't even go to the moon because I don't see the moon at the screen.

**Comment by C1ffisme** [comment]
Do you have a screenshot?

**Comment by Tropicaner** [comment]
![screenshot 2](https://user-images.githubusercontent.com/36380533/36077233-47d5e460-0f68-11e8-874d-e6856254601a.png)

**Comment by Tropicaner** [comment]
![screenshot 4](https://user-images.githubusercontent.com/36380533/36077240-660cb8e6-0f68-11e8-9bb8-c6255711bda1.png)

**Comment by C1ffisme** [comment]
Hmmm...

**Comment by dmodoomsirius** [comment]
So you have any planets defined in the planetDef.xml?

**Comment by Tropicaner** [comment]
I got Mining Planet, Void Planet, Deep Dark Planet and Lost Cities Planet.

**Comment by Tropicaner** [comment]
![screenshot 6](https://user-images.githubusercontent.com/36380533/36084805-1d805e44-0fc1-11e8-83a3-dc4cb650cfb5.png)

**Comment by C1ffisme** [comment]
It doesn't seem as though you have a moon around the earth in your file, so you may just need to upgrade from your rocket to a space station to get to those other planets.

**Comment by Tropicaner** [comment]
Ok but after I build the Space Station its possible to go too the other planets?

**Comment by Tropicaner** [comment]
OK thank you for the help!
