### ISSUE TITLE
Other mod's Steel Ingot

### ISSUE THREAD

**Issue by mskurnik** [zmaster587/AdvancedRocketry#114]
When I added your mod to my pack, it removed the recipes for making steel ingots for other mods in the Thermal Expansion Induction Smelter.  I am really not sure why.  Out of all the mods that I have in my pack these are the ones that were affected:

- Immersive Engineering
- Tinker's Construct
- Railcraft

Again I am not sure why these got removed since I looked at your code and you aren't adding/removing anything for ThermalExpansion.  I have confirmed it in Single Player as well.

**Comment by zmaster587** [comment]
Latest version of each?

**Comment by mskurnik** [comment]
I am using quite a few others mods.  I will experiment later today with just those mods plus COFH mods to see if I can reproduce it.

- ImmersiveEngineering-0.7.5
- TConstruct-1.7.10-1.8.8
- Railcraft_1.7.10-9.12.2.0

**Comment by zmaster587** [comment]
does the instance contain gregtech?

**Comment by mskurnik** [comment]
No.  This is my mod pack:
- AdvancedRocketry-0.5.0b1.jar
- ae2stuff-rv3-0.5.1.9-mc1.7.10.jar
- AOBD-2.9.1.jar
- appliedenergistics2-rv3-beta-6.jar
- Aroma1997Core-1.7.10-1.0.2.16.jar
- Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar
- ATG-1.7.10-0.12.0.jar
- bdlib-1.9.4.109-mc1.7.10.jar
- BiblioCraft[v1.11.5][MC1.7.10].jar
- BigDoors-1.7.10-1.0.0.jar
- BigReactors-0.4.5-A.jar
- boilerplate-1.7.10-6.2.1.68-universal.jar
- buildcraft-7.1.16.jar
- buildcraft-compat-7.1.5.jar
- Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10.jar
- ChickenChunks-1.7.10-1.3.4.16-universal.jar
- CodeChickenCore-1.7.10-1.0.7.47-universal.jar
- CoFHCore-[1.7.10]3.1.2-325.jar
- CollectiveFramework-1.0.0-132.jar
- compacter-1.2.1.15-mc1.7.10.jar
- ComputerCraft1.75.jar
- Decocraft-2.3.2_1.7.10.jar
- DynIMC-1.7.10-1.1.0.12-universal.jar
- EnderCore-1.7.10-0.2.0.34_beta.jar
- EnderStorage-1.7.10-1.4.7.37-universal.jar
- EnhancedPortals_1.7.10-universal-3.0.12.jar
- extrabiomesxl_1.7.10-3.16.4.jar
- ExtraCells-1.7.10-2.3.9b188.jar
- fastcraft-1.23.jar
- ForgeMultipart-1.7.10-1.2.0.347-universal.jar
- ForgeTSIntegration-0.0.3.jar
- Galacticraft-Planets-1.7-3.0.12.375.jar
- GalacticraftCore-1.7-3.0.12.375.jar
- GardenStuff-1.7.10-1.7.0.jar
- generators-0.9.20.123-mc1.7.10.jar
- GrimoireOfGaia3-1.7.10-1.2.7.jar
- ImmersiveEngineering-0.7.5.jar
- immersiveintegration-0.6.8.jar
- InventoryTweaks-1.59-dev-152.jar
- ironchest-1.7.10-6.0.62.742-universal.jar
- LibVulpes-0.0.6e.jar
- LLOverlayReloaded-1.0.7-mc1.7.10.jar
- LunatriusCore-1.7.10-1.1.2.21-universal.jar
- malisiscore-1.7.10-0.14.3.jar
- malisisdoors-1.7.10-1.13.2.jar
- Mantle-1.7.10-0.3.2b.jar
- MicdoodleCore-1.7-3.0.12.375.jar
- MineFactoryReloaded-[1.7.10]2.8.1-174.jar
- moarcarts-1.7.10-1.1.1-48.jar
- MobiusCore-1.2.5_1.7.10.jar
- ModularPowersuits-0.11.0.300.jar
- More-Planets-1.7.10-1.3.0-Pre-1.jar
- MrCrayfishFurnitureModv3.4.8(1.7.10).jar
- natura-1.7.10-2.2.0.1.jar
- neiaddons-1.12.13.38-mc1.7.10.jar
- NEIIntegration-MC1.7.10-1.1.2.jar
- NetherOres-[1.7.10]2.3.1-22.jar
- NotEnoughItems-1.7.10-1.0.5.118-universal.jar
- Numina-0.4.0.131.jar
- OpenBlocks-1.7.10-1.5.1.jar
- openccsensors-1.7.5.jar
- OpenModsLib-1.7.10-0.9.1.jar
- OpenModularTurrets-1.7.10-2.2.2-217.jar
- Opis-1.2.5_1.7.10.jar
- OptiFine_1.7.10_HD_U_D3.jar
- OreDictionaryConverter-1.6.1.jar
- Pam's HarvestCraft 1.7.10k.jar
- Peaceful Plus [1.7.10].jar
- Peripherals++-1.3.6.jar
- PlayerAPI-1.7.10-1.4.jar
- QuartzPlus-1.7.10-0.9.04.jar
- Railcraft_1.7.10-9.12.2.0.jar
- RenderPlayerAPI-1.7.10-1.4.jar
- sampler-1.60.jar
- Schematica-1.7.10-1.7.6.131-universal.jar
- Simple Recipes 1.7.10-1.8.2.jar
- SimplyJetpacks-MC1.7.10-1.5.3.jar
- SmartMoving-1.7.10-15.6.jar
- SmartRender-1.7.10-2.1.jar
- SolarFlux-1.7.10-0.8b.jar
- StorageDrawers-1.7.10-1.9.8.jar
- TConstruct-1.7.10-1.8.8.jar
- thermalcasting-0.0.3.jar
- ThermalDynamics-[1.7.10]1.1.0-161.jar
- ThermalExpansion-[1.7.10]4.1.2-240.jar
- ThermalFoundation-[1.7.10]1.2.3-112.jar
- ThermalSmeltery-1.3.1.4.jar
- TiCTooltips-mc1.7.10-1.2.5.jar
- TMechworks-1.7.10-0.2.15.106.jar
- TorchLevers-V1.4.2-MC1.7.10.jar
- twilightforest-1.7.10-2.3.7.jar
- Waila-1.5.10_1.7.10.jar
- WailaHarvestability-mc1.7.10-1.1.6.jar
- WAILAPlugins-MC1.7.10-0.2.0-23.jar
- Wawla-1.3.3-1.7.10.jar
- weaponmod-1.14.3.jar
- worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar
- zettaindustries-1.1-116.jar
- [1.7.2+] KingCore v3.4.2.19.jar
- [1.7.2] EnderBook v2.1.2.6.jar
- [MC1.7.10]deconstruction[2.2.7].jar

**Comment by mskurnik** [comment]
OK.  The other mods steel recipes still work but they just don't show up in NEI.  Also when making those steel ingots, it makes Advanced Rocketry's steel but that is easily fixed by inserting it into a unifier.

**Comment by zmaster587** [comment]
That sounds a lot more like somebody else is messing with the recipes, you did state you looked in AR earlier for any recipe removal, neither AR nor libvulpes removes or modifies recipes from any mod other than GT (I have recently removed the code from libvulpes, it was  relic from a pack I was working on and got a bit lazy and was only intended to add tinkerers ore recipes to GT machines).  I'm sorry I couldn't be of more help.
