### ISSUE TITLE
Wrong star temperature on space station

### ISSUE THREAD

**Issue by Ithronyar** [zmaster587/AdvancedRocketry#1145]
Minecraft Version: 1.12.2
Forge Version: 1.12.2-14.23.2.2611
Advanced Rocketry Version: 1.2.6-55
LibVulpes Version: 0.2.8-27
is this the latest curseforge build? Yes

Self-explanatory. Stars just look like the default sun on space stations. No blue, no red, no orange, just yellow-white.

**Comment by zmaster587** [comment]
Now that you mention it... I didn't think about it until now but you're right.  I'll look into it.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
