### ISSUE TITLE
Planet Sky Rendering crash... maybe?!?

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketry#1148]
Minecraft Version:
- 1.10.2
Forge Version:
- 12.18.3.2185
Advanced Rocketry Version:
- The latest from Curseforge for 1.10.2, 1.2.5a.
LibVulpes Version:
- 0.2.6
**is this the latest curseforge build?**Crash
Yes, for 1.10.2

#Please Pastebin crash
---------------------
Crash Report:

Gist: https://gist.github.com/C1ffisme/7d1c5d9e1532267e91400971ab3a5aea
----------
Explain issue in detail:

I couldn't manage to get the whole crash report when this happened. When I copied it from the launcher, Ctrl+C didn't work and I just copied what I could from latest.log. This happened when trying to get a chip out of a guidance computer, though it seems to be related to sky rendering.

**Comment by zmaster587** [comment]
Does it occur with this build? https://minecraft.curseforge.com/projects/advanced-rocketry/files/2525398

**Comment by C1ffisme** [comment]
I'll see if I can recreate it, although it might have been a very rare occurence...

**Comment by C1ffisme** [comment]
On one hand, I couldn't recreate the issue with the new version. On the other, I couldn't recreate it on the old version either. That new version seems to have some bizzare problems too... I couldn't access a rocket assembler or station assembler for some reason...

There is one other planet rendering problem that I found in both versions related to render distance, but it's unlikely to be related to this issue. (#1150)

Until then, I don't know what else to do about this issue...

**Comment by lolmetimbers** [comment]
79 rocket/space station assembler is broken

On 1.10.2 - 77 and I am having a related issue where the planet skybox is not rendered when on a space station (you can still see stars/sun)

**Comment by zmaster587** [comment]
I've fixed a crash similar to this not too long ago, which is why I asked.

@lolmetimbers Please do not post non related issues in a thread, I have 310 issues to look through, causing disorganisation such as this requires me to spend more time looking through tabs to figure out what is where and as a result it's going to take me longer to actually get to fixing issues and making sure they are fixed and not lost in the shuffle.

**Comment by lolmetimbers** [comment]
Fair enough, I did end up creating/closing that ticket. As for assemblers not working, LibVulpes 1.10.2-0.2.8-8-UNSTABLE indeed needed to be updated.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
