### ISSUE TITLE
BUG - Mod interaction with refined storage

### ISSUE THREAD

**Issue by DarVillous** [zmaster587/AdvancedRocketry#1149]
Minecraft Version: 1.12.2
-
Forge Version: 14.23.2.2616 (found in 2613)
-
Advanced Rocketry Version: 1.12.2-1.2.6-55 (found in 54)
-
LibVulpes Version: 1.12.2-0.2.8-27 (found in 27)
-
**is this the latest curseforge build?** yes

---- I found this issue in a mod pack and tested in a creative mode custom profile with only the 3 mods on the latest forge.

![image](https://user-images.githubusercontent.com/7937470/36291807-dddde912-1292-11e8-9c19-502b502626bf.png) 

No crash
---------------------
Crash Report:
----------
Carbon collection cartridges seem to get confused when importing/exporting
basic test rig- 
![image](https://user-images.githubusercontent.com/7937470/36292761-b7139794-1299-11e8-8fc1-1e84aea5ff55.png)

The exporter is able to stack collection cartridges with the same durability inside the co2 scrubber
![image](https://user-images.githubusercontent.com/7937470/36292672-12c9485a-1299-11e8-8665-f496c92d36df.png)

the importer is configured with a specific durability on the cartridge (0) imports all cartridges and ignores the damage
![image](https://user-images.githubusercontent.com/7937470/36292702-472f6b1a-1299-11e8-8bb5-02abec47b53b.png) 
(compare NBT is also on)

**Comment by zmaster587** [comment]
The cartridge scrubbers are standard items with a damage value and a max stack size of one.  So this is really strange.  Does this occur with tools like bows, swords and pickaxes in the same manner?

**Comment by DarVillous** [comment]
no, this does not happen with bows or other damaged items.  
I was able to reproduce this with AR 1.4.1-120, forge 12.23.5.2796 and libvulpes 0.3.0-45

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
