### ISSUE TITLE
Low Rendering Distance causes planets/moons not to render in skies.

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketry#1150]
Same version parameters as in #1148.

Explain issue in detail:

![2018-02-16_17 57 09](https://user-images.githubusercontent.com/9893266/36336971-50706ab6-1353-11e8-818f-a03e87116424.png)

This only happens with a rendering distance of less than 7.

**Comment by lolmetimbers** [comment]
This is similar to optifine issue and not sure if it can be fixed
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/requests-ideas-for-mods/2543674-mod-to-allow-the-sky-in-a-low-render-distance

**Comment by zmaster587** [comment]
I think this is just related to culling distance

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
Cannot confirm the issue in the latest 1.12.2 :+1:
