### ISSUE TITLE
[1.12.2] Docking Pads not appearing in "Select Destination" screen on rocket guidance computer GUI

### ISSUE THREAD

**Issue by Meissa** [zmaster587/AdvancedRocketry#1151]
Minecraft Version:
- 1.12.2
Forge Version:
- forge-1.12.2-14.23.2.2613-universal
Advanced Rocketry Version:
- AdvancedRocketry-1.12.2-1.2.6-55
LibVulpes Version:
- LibVulpes-1.12.2-0.2.8-27-universal

**is this the latest curseforge build?**
- yup
---------------------
Crash Report: N/A
----------
Explanation of issue in detail:
----------

Placing a docking pad on a space station and then attempting to land on it via the "Select Destination" button in the rocket guidance computer does not function. When the "Select Destination screen is opened, there are no landing pads listed as being available.

I've attached what the destination select screen looks like when I attempt to land on a docking pad on my station, as one can see nothing is listed.
![2018-02-17_15 33 28](https://user-images.githubusercontent.com/10284121/36346257-5cad2d14-13f8-11e8-91b4-3a66ee590e30.png)

Also a picture of the docking pad to make sure I am not building it wrong. I've also tried it surrounded by launch pad blocks, but I am not sure if the block tests for nearby block dimensions when determining if a docking pad is viable or not.
![2018-02-17_15 36 11](https://user-images.githubusercontent.com/10284121/36346266-83bf864a-13f8-11e8-8686-1baad8e77c88.png)

I have also attached my advancedRocketry.cfg file, in the event that the information from it may be useful.
[advancedRocketry-config.zip](https://github.com/zmaster587/AdvancedRocketry/files/1734229/advancedRocketry-config.zip)

Things I have tried:
----------
- Placing the docking pad with a name, placing it without a name
- Placing the docking pad down on the station, traveling to the overworld to unload dimension -2, and then attempting to select a destination back on the docking pad pad
- Placing the docking pad down on the station, traveling back to the overworld to unload dimension -2, stopping the minecraft server, restarting the minecraft server, and then attempting to select the destination.
- Placing the docking pad down on the station, traveling back to the overworld to unload dimension -2, stopping the minecraft server, restarting the minecraft server, assembling a new rocket to make sure the rocket entity isn't loading destinations improperly, and then attempted to select a destination.
- Starting minecraft in windowed mode to make sure that the destination selection screen was not loading improperly on 21:9 aspect ratio

At this point I have run out of ideas of more ways to test and make sure that I'm not being the idiot here somehow, but if there is any more information that I can provide regarding this issue, please let me know.

**Comment by zmaster587** [comment]
Is this in multiplayer or single player?
