### ISSUE TITLE
Advanced Rocketry space station skybox not generated properly (SERVER)

### ISSUE THREAD

**Issue by lolmetimbers** [zmaster587/AdvancedRocketry#1152]
**I am currently running...**
Forge version: 1.10.2-12.18.3.2511
Java version: jre1.8.0_151

**Mods**
AdvancedRocketry-1.10.2-1.2.5a-77
LibVulpes-1.10.2-0.2.7-7-universal

**What is the expected result?**
Space station skybox is generated. Stars + planet view

**What is the current result?**
Star skybox is generated but cannot see the 'planet' underneath at all

**Possible starting points:**
Advanced Rocketry recently included a config for custom skyboxes on spacestation, planet etc. In my config it is set to 'true' so it will use AR's skybox:
If true, AR will use a custom skybox on space stations
B:StationSkyOverride=true

**Build 79 rocket/space station assembler is broken**

**On 1.10.2 - 77 and I am having the issue where the planet skybox is not rendered when on a space station (you can still see stars/sun)** This is on a **server config** and not singleplayer. Singeplayer works fine apparently but on server it breaks

**Comment by lolmetimbers** [comment]
Geez I think this issue is just fixed upon relogging into the server...the planet magically appears. Have not tested Warp drive yet

Upon initial creation it is invisible for some reason. For reference I am travelling with the rocket to create the space station. Keeping open so you can see this!

**Comment by zmaster587** [comment]
So it's broken when B:StationSkyOverride=true on the server and B:StationSkyOverride=true on the client?  or does it need to be false on the server and true on the client?

**Comment by lolmetimbers** [comment]
Relogging has fixed this issue so not sure. Closing for now as have bigger problems.
