### ISSUE TITLE
Atmosphereblob

### ISSUE THREAD

**Issue by mandrac** [zmaster587/AdvancedRocketry#1154]
Minecraft Version:
1.12.2
Forge Version:
2601
Advanced Rocketry Version:
1.2.6-50
LibVulpes Version:
0.2.7-25

Part of the FTB revelation 1.4.0 pack

---------------------
Crash Report:
https://pastebin.com/HvXYP9Cy
----------
Explain issue in detail:

So my friend made the first space station on the server. He told me that right befor the crash he had thrown a few carbon cartridge in the co2 scrubber and turned on his oxygen vent and then a few minute latter the server crashed.

edit: here is the dimention that cause trouble : 
https://www.dropbox.com/s/qcelf553c9gn1c1/DIM-2.rar?dl=0

**Comment by zmaster587** [comment]
see #1129

**Comment by mandrac** [comment]
thanks
