### ISSUE TITLE
Possible Issue with Mod Author?

### ISSUE THREAD

**Issue by Avalynne** [zmaster587/AdvancedRocketry#1157]
I was not sure where to post this since there is no Discord link on your CurseForge page or website to contact you privately and I wanted you to be aware of something:

MJRLegends recently made a mod that is an add-on to Galacticraft. It is exact to how you progress or do things in Advanced Rocketry. Here is a link to the screenshot with the description in case he decides to change it later and claim this is being fabricated to make him look bad:
The mod: https://minecraft.curseforge.com/projects/planet-progression
The description: https://imgur.com/a/dr5fI

A friend of mine spoke to him about it when he first discovered the mod and shared this with me. MJRLegends' answer was not nice and in my opinion was outright disrespectful, especially given the fact that both of you are mod authors.

I don't know if there is anything you can do, but I felt that you should be aware of what is going on. If I can help in any way, please let me know.

**Comment by zmaster587** [comment]
Thanks for letting me know.  Advanced Rocketry is technically released under the MIT license so there's nothing stopping him from using the assets from AR if he really wanted to.

That being said, I do find his comment about Advanced Rocketry being "trash" kind of amusing despite the fact he's going along with identical concepts.

Hopefully he'll help add some more variety into the space stuff for MC.  I might actually take a look and see about adding integration.  Though it doesn't look like there's much yet to integrate to.
