### ISSUE TITLE
Error using Tank in other mods

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1159]
Minecraft Version: 1.10
Forge Version:
**is this the latest curseforge build? yes**
#Please Pastebin crash
https://github.com/gdarai/SpaceRace/issues/14

Explain issue in detail:
I had a crash when I tried to use the low pressure tank in a guidebook mod, and according to the mod author, the problem is on the AdvancedRocketry side so here is the warning:
https://github.com/gigaherz/Guidebook/issues/33

> After some investigation, I believe I know the exact issue: Advanced Rocketry handles the case where the itemstack has the NBT data set to null, but not the case where the itemstack has the NBT data not null, but doesn't contain the information needed to get the tank info.

>You can reproduce this same crash by taking an empty tank, and giving it a name in an anvil.

>I recommend that you submit a bug report to them, with this information.

**Comment by zmaster587** [comment]
added null check on the returned fluidstack
