### ISSUE TITLE
Space Station Assembler Not Working.

### ISSUE THREAD

**Issue by bonnedav** [zmaster587/AdvancedRocketry#1162]
Minecraft Version: 1.12.2
-
Forge Version: 14.23.2.2611
-
Advanced Rocketry Version: 1.2.6-56
-
LibVulpes Version: 0.2.8-27
-

Explain issue in detail: When i try to build a space station the assembler, After i put in a bay and chip it still says missing chip. Pressing scan does nothing, and pressing build consumes the bay and chip but does nothing else.

**Comment by bonnedav** [comment]
I updated to 1.2.6-57 and am still encountering this bug.

**Comment by bonnedav** [comment]
I figured it out! the problem is with structure tower height. if the tower is 3 blocks or smaller it will say invalid launch pad structure. if the tower is 4 blocks it will act as above. if the tower is 5 blocks or higher it will work as intended. Tested with latest versions as of today. AR:1.4.0-93 LV:0.2.8-26 in MC:1.12.2 with Forge:14.23.4.2746

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Kidd021705** [comment]
Yes this is still an issue on 1.10.2
