### ISSUE TITLE
Selection Issues with Warp controller/Planet Selector [+VR Incompatible]

### ISSUE THREAD

**Issue by lolmetimbers** [zmaster587/AdvancedRocketry#1163]
**I am currently running...**
Forge version: 1.10.2-12.18.3.2511
Java version: jre1.8.0_151

**Mods**
Heavily modded
AdvancedRocketry-1.10.2-1.2.5a-80
LibVulpes-1.10.2-0.2.8-8-universal
Optifine

**On a 'large' GUI scale or even 'auto', everytime I open the warp controller/planet selector etc my view is off in space in the top left. I have to drag my way south-east heaps to even view the planets. This occurs even on a normal non-VR client. The issue is fine with GUI scale is set to small/normal**

The left side 'Planet Select' list is also broken where I can only see 3 entries before it is cut off.

Pic upon opening: https://imgur.com/a/ZZ7Xy

**This problem is even worse in VR (Vivecraft) where for some reason you cannot select any planet at all.** The mouse cursor is heavily OFF centre - if my hand is in the centre of the screen the actual cursor is in the bottom-right. In order to even see the cursor I have to point to the top-left. I can highlight planets and see the name/number of moons but cannot select them (maybe due to off centre cursor)

Is there anyway to fix the GUI screen to be static locked in the centre of the HUD? The drag function + GUI scaling does not play well at all for me. Galacticrafts planet selector UI works and seems to be more compatible albeit more simple.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
