### ISSUE TITLE
Planets incorrectly textured (even when using customIcon)

### ISSUE THREAD

**Issue by lolmetimbers** [zmaster587/AdvancedRocketry#1164]
I am currently running...
Forge version: 1.10.2-12.18.3.2511
Java version: jre1.8.0_151

Mods
Heavily modded
AdvancedRocketry-1.10.2-1.2.5a-80
LibVulpes-1.10.2-0.2.8-8-universal

On a server with the below config, I am getting problems with planets being correctly textured. My mars is set to 'earthlike' even though in config it is 'marslike. Jupiter onwards all look the same as Blue gas giant instead of the custom icons I have set. Have I incorrectly coded my config or is the planet texturing bugged? The incorrect textures are both for the planet selector GUI and orbiting planet texture.

**Tried editing the planetsdefs in the 'world' folder as well as refreshing from XML but no luck with getting them to change.**

Pastebin of planetdefs.xml https://pastebin.com/A2uc2L5Z

**Comment by EasterncheesE** [comment]
I confirm the issue with 1.7.10 build of AR (1.2.5).
The only thing that changes the planet picture and look is pressure and gravity, customicon doesn't change anything. Tested both on server and client. Please note, all my planets have dimmaping added to them (i do make generation with other mod), maybe that could affect it.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
