### ISSUE TITLE
random planets generate 2x more planetsDefs.xml specifies

### ISSUE THREAD

**Issue by Landstryder** [zmaster587/AdvancedRocketry#1165]
Minecraft Version:
-1.12.2

Forge Version:
-14.23.2.2613

Advanced Rocketry Version:
-1.2.6-55

LibVulpes Version:
-0.2.8-27

**is this the latest curseforge build?**
yes

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Creating a custom Galaxy for my modpack (Atom Smasher), and what ever number I set for numPlanets and numGasGiants gets doubled when the world is generated.

Pastebin of my planetDefs.xml https://pastebin.com/bURqY051

**Comment by CTH999** [comment]
Well, just halve what you want!

P.S. You cant have to many planets, [right](https://www.bing.com/images/search?view=detailV2&ccid=Tkkl5%2bsm&id=C82613896C02334CC4E0B9EC10E4A772CAFB38DE&thid=OIP.Tkkl5-smBQSBCUa5vp4LKAHaEK&mediaurl=http%3a%2f%2fmedia.fromthegrapevine.com%2fassets%2fimages%2f2015%2f8%2finterstellar-black-hole.jpg&exph=720&expw=1280&q=black+hole&simid=608048289002294694&selectedIndex=17&ajaxhist=0)?

**Comment by zmaster587** [comment]
You mean if it already has planets and then you set numPlanets=1 then it generates one more planet in addition to the existing ones?

**Comment by Landstryder** [comment]
I mean if you set the file to numPlanets=2 for a certain star it it will generate 4 random planets in addition to any predefined ones. This happened on world creation, I'm using a custom planetsDefs.xml in the config folder.

@CTH999 but what if I want an odd number like 3 or 7... or just one random gas giant...

**Comment by CTH999** [comment]
@Landstryder 
true, true!

However, did you check the link? Also, I'm certain it's going to be fixed!

Good luck with your mod pack!

**Comment by Tedyhere** [comment]
Dang you Landstryder! *muddles off to his own space modpack*

**Comment by CTH999** [comment]
@Tedyhere Welcome to my world

And, Minecraft's been crashing a lot (I'm not sure which mod it is, so I haven't mad an issue for the mod/ mods in question) (Your not the only two here attempting a mod pack)

So, has it been fixed yet?

**Comment by zmaster587** [comment]
I still cannot replicate this, setting numPlanets="1" creates one additional planet, setting it to "2" makes 2, and so on.  setting numPlanets to 2 and numGasGiants to 1 makes one additional gas giant and two planets.
I've tried this in build 55 and the most recent 1.4.0 build.

**Comment by zmaster587** [comment]
Fixed for next build
