### ISSUE TITLE
There no some methods in official release: AdvancedRocketry-1.7.10-1.2.5-63 && || LibVulpes-1.7.10-0.2.8-30-universal

### ISSUE THREAD

**Issue by my-thanks** [zmaster587/AdvancedRocketry#1166]
Minecraft Version:
- v. 1.7.10
Forge Version:
- 1.7.10-Forge10.13.4.1614-1.7.10
Advanced Rocketry Version:
- 1.7.10-1.2.5-63
LibVulpes Version:
- 1.7.10-0.2.8-30-universal
**is this the latest curseforge build?**
yes
#Please Pastebin crash
---------------------
no crash
---------------------
Crash Report:
----------
no report
----------
Explain issue in detail:
zmaster587, good day, and my great wishes you. This mod is Amazing & I trying to made armor with "vacuum" immunity. But in class zmaster587.libVulpes.util.EmbeddedInventory my compiler can' found some methods. Is it really deleted? Or there my mistake with "obfuscated"?

**Comment by my-thanks** [comment]
I using released .jar for compile

**Comment by my-thanks** [comment]
Methods that compiler can't found : "getSizeInventory()" ; "getInventorySlotContents" ; e t.c. 
Maybe in release this methods deleted?

**Comment by my-thanks** [comment]
I am  trying to make other spacesuit model that can changed in "BlockSuitWorkstation"

**Comment by zmaster587** [comment]
getSizeInventory, getInventorySlotContents, etc are all vanilla methods, so I would suspect you either have the wrong version of MC, something wrong with the dev env, or maybe using the wrong language mappings.

If you're not compiling from scratch and compiling against the jar released on curse, if you're not using deobf, then it's all obfuscated and won't be able to find those methods anyway.

**Comment by dmodoomsirius** [comment]
there is always deobfCompile if you are using the curseforge maven. tho that is iffy. it deobf's if you put them in the libs/ folder.

**Comment by my-thanks** [comment]
zmaster587 and dmodoomsirius: Thank you for answer! In that case vanilla methods still obfuscated throught compilation of any mod.(It is first time i have this issue with compiled ".jar") If file "LibVulpes-1.7.10-0.2.8-30-universal" has compiled from neighbor repo, there only way by extending of classes that using vanilla methods. I will try it.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
