### ISSUE TITLE
Wrong planet/ring scale and distance when viewed from moons

### ISSUE THREAD

**Issue by Ithronyar** [zmaster587/AdvancedRocketry#1169]
**Minecraft Version:** 1.12.2
**Forge Version:** 1.12.2-14.23.2.2611
**Advanced Rocketry Version:** 1.2.6-57
**LibVulpes Version:** 0.2.8-27
**is this the latest curseforge build?** Yes

When a planet with a ring system is viewed from its moons, the rings always look the same, no matter the moon's actual distance from the planet. As a result, on more distant moons, the planet is too small to even see, and yet the rings form a giant circle in the sky, with a dark area in the center where a planet should be.
![badscale](https://user-images.githubusercontent.com/26017430/36571391-501fc394-17eb-11e8-925d-210e49a3610b.png)

This results in all the moons looking like they have smaller orbits than the ring system's inner edge. This is virtually impossible, since rings tend to indicate an object's Roche limit. Anything as large as an explorable moon would be ripped apart by tidal forces at that distance.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Ithronyar** [comment]
> 
> 
> Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

Still an issue in 1.5.0-131
![2019-03-05_00 41 47](https://user-images.githubusercontent.com/26017430/53792031-9d591180-3edf-11e9-8184-c2f5d96a86f0.png)

**Comment by zmaster587** [comment]
Are you suggesting having two modes for rings, one for moon inside of a ring system (yeah, I know it doesn't occur frequently irl, but it looks cool.  It's also not impossible for a moon to be within a ring system, the roche limit depends on the mass and size of both bodies, a smaller moon can survive closer to a large mass than a larger moon.), one for moons outside of a ring system?

**Comment by Ithronyar** [comment]
> 
> 
> Are you suggesting having two modes for rings, one for moon inside of a ring system (yeah, I know it doesn't occur frequently irl, but it looks cool. It's also not impossible for a moon to be within a ring system, the roche limit depends on the mass and size of both bodies, a smaller moon can survive closer to a large mass than a larger moon.), one for moons outside of a ring system?

Either two modes like that, or some sort of single dynamic mode. I don't know how the sky background works internally, but ideally it would just be one ring model that gets scaled/moved based on the moon's properties. That way there's no need for separate modes, and it's fully dynamic and visually accurate. Might be best to have the two modes thing, depending on how difficult that would be to implement.

The thing about moons inside the roche limit is that they have to be exceptionally small/dense so they can withstand the tidal forces. I doubt there are very many scenarios that would permit them to have high enough gravity to walk on like in-game (maybe a massive asteroid or core made of solid heavy metals). I don't think any visual appeal is going to be lost by forcing moons' minimum distance to be outside that boundary, since it would still be possible for rings to fill the sky with this suggestion.

![roche](https://user-images.githubusercontent.com/26017430/53942536-e17b1c00-406f-11e9-8831-088902b9c9dd.png)
