### ISSUE TITLE
Game insta crashs when opening airlock door

### ISSUE THREAD

**Issue by Dogenutt** [zmaster587/AdvancedRocketry#117]
`---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/25/16 7:31 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at zmaster587.advancedRocketry.event.PlanetEventHandler.blockPlaceEvent(PlanetEventHandler.java:79)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_575_PlanetEventHandler_blockPlaceEvent_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:353)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at zmaster587.advancedRocketry.event.PlanetEventHandler.blockPlaceEvent(PlanetEventHandler.java:79)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_575_PlanetEventHandler_blockPlaceEvent_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:353)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@79969049
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 340993488 bytes (325 MB) / 2532835328 bytes (2415 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 125 mods loaded, 125 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	AdvancedRocketry{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	fastflyblockbreaking{0.1} [FastFlyBlockBreaking] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	libVulpes{0.0.6f.20160521161207} [${modname}] (LibVulpes-1.7.10-0.0.6fb20160521161208-universal.jar) 
	UCHIJAAAA	advancedRocketry{0.5.2} [Advanced Rocketry] (AdvancedRocketry-0.5.2.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UCHIJAAAA	BetterAchievements{0.1.0} [Better Achievements] (BetterAchievements-1.7.10-0.1.0.jar) 
	UCHIJAAAA	betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	Forestry{4.2.12.60} [Forestry for Minecraft] (forestry_1.7.10-4.2.12.60.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	catwalks{2.0.4} [Catwalks Mod] (catwalks-2.0.4.jar) 
	UCHIJAAAA	catwalkmod{x.x.x} [Legacy Catwalk Compat] (catwalks-2.0.4.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	ChiselFacades{1.7.10-2.12-chiselteam} [Chisel Facades] (ChiselFacades-1.7.10-2.12-chiselteam.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	Mekanism{9.0.0} [Mekanism] (Mekanism-1.7.10-9.0.0.268.jar) 
	UCHIJAAAA	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.26.jar) 
	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	endercompass{1.2} [Ender Compass] (EnderCompass-1.7.10-1.2.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.34_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.34_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.425_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.425_beta.jar) 
	UCHIJAAAA	waterhooks{1.2.1} [Water Hooks] (waterhooks-1.2.1.jar) 
	UCHIJAAAA	enderioaddons{0.10.9} [Ender IO Addons] (EnderIOAddons-1.7.10-2.3.0.425_beta-0.10.9.52_beta.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	ShetiPhianCore{v3} [ShetiPhian-Core] (ShetiPhianCore-v3-beta2.jar) 
	UCHIJAAAA	EnderTanks{rev16-beta1} [EnderTanks] (EnderTanks-rev16-beta1.jar) 
	UCHIJAAAA	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
	UCHIJAAAA	hgp{Release} [Horizontal Glass Panes] (hgp-1.7.10-1.1.0.4-universal.jar) 
	UCHIJAAAA	HoloInventory{1.9.1.124} [HoloInventory] (HoloInventory-1.7.10-1.9.1.124.jar) 
	UCHIJAAAA	infiniteinvo{1.0.44} [InfiniteInvo] (InfiniteInvo-1.0.44.jar) 
	UCHIJAAAA	intellie{2.1.4.573} [IntelliE] (IntelligentEnergistics-1.7.10-2.1.4.573-universal.jar) 
	UCHIJAAAA	appaero{2.1.4.573} [AppliedAerodynamics] (IntelligentEnergistics-1.7.10-2.1.4.573-universal.jar) 
	UCHIJAAAA	appaeronei{2.1.4.573} [AppliedAerodynamicsNEI] (IntelligentEnergistics-1.7.10-2.1.4.573-universal.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	irontank{1.0.1 build @BUILD@} [Iron Tanks] (irontank-1.7.10-1.0.1.50.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJAAAA	je_calculation{0.3.3} [Just Enough Calculation] (JustEnoughCalculation-1.7.10-0.3.3.jar) 
	UCHIJAAAA	LogisticsPipes{0.9.3.122} [Logistics Pipes] (logisticspipes-0.9.3.122.jar) 
	UCHIJAAAA	MekanismGenerators{9.0.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.0.268.jar) 
	UCHIJAAAA	MekanismTools{9.0.0} [MekanismTools] (MekanismTools-1.7.10-9.0.0.268.jar) 
	UCHIJAAAA	nhlib{2.0.9} [NHAVE's Library] (nhlib-1.7.10-2.0.9.jar) 
	UCHIJAAAA	nhwrench{3.1.3} [NHAVE's OmniWrench V3] (nhwrench-1.7.10-3.1.3.jar) 
	UCHIJAAAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	powersuits{0.11.0.301} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.301.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	nhintegration{1.0.10} [NHWRENCH Integrations] (nhintegration-1.7.10-1.0.10.jar) 
	UCHIJAAAA	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-121.jar) 
	UCHIJAAAA	openmodularturrets{2.2.2-217} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.2-217.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHIJAAAA	SonarCore{1.1.2} [SonarCore] (SonarCore-1.7.10-1.1.2.jar) 
	UCHIJAAAA	PracticalLogistics{0.2.3} [Practical Logistics] (Practical-Logistics-1.7.10-0.2.3.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	RIO{2.4.0} [Remote IO] (RemoteIO-1.7.10-2.4.0-universal.jar) 
	UCHIJAAAA	rftools{4.23} [RFTools] (rftools-4.23.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar) 
	UCHIJAAAA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJAAAA	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
	UCHIJAAAA	VeinMiner{0.31.6_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.31.6.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.6_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.31.6.unknown.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	WorldSelectionAdvanced{1.7.10-7} [Advanced World Selection] (WorldSelectionAdvanced-1.7.10-7.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAA	aobd{2.9.1} [Another One Bites The Dust] (AOBD-2.9.1.jar) 
	UCHIJAAAA	UniDict{1.7.10-1.8} [UniDict] (UniDict-1.7.10-1.8.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.2-325
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	List of loaded APIs: 
		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
		* BetterAchievements|API (0.1.0) from BetterAchievements-1.7.10-0.1.0.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.16.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|core (1.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.16.jar
		* BuildCraftAPI|recipes (4.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.16.jar
		* BuildCraftAPI|tools (1.0) from EnhancedPortals_1.7.10-universal-3.0.12.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.16.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.2) from OpenModularTurrets-1.7.10-2.2.2-217.jar
		* CoFHAPI|block (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|core (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.2.jar
		* CoFHAPI|energy (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.2.jar
		* CoFHAPI|fluid (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|inventory (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|item (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.2.jar
		* CoFHAPI|modhelpers (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|tileentity (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.5.jar
		* CoFHAPI|world (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|audio (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|gui (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|gui|container (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|gui|element (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|inventory (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|render (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
		* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* ComputerCraft|API (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|FileSystem (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Lua (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Media (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Peripheral (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Permissions (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Redstone (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Turtle (1.75) from ComputerCraft1.75.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-0.0.1.4-universal.jar
		* IC2API (1.0) from SonarCore-1.7.10-1.1.2.jar
		* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.0.0.268.jar
		* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0-121.jar
		* NHWrenchAPI (1.7.10V1.0.0) from nhwrench-1.7.10-3.1.3.jar
		* PracticalLogisticsAPI (1.4) from Practical-Logistics-1.7.10-0.2.3.jar
		* VeinMinerApi (0.1) from VeinMiner-1.7.10_0.31.6.unknown.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
		* waterhooks|API (1.0) from waterhooks-1.2.1.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:ON, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['D0genutt'/457, l='New World', x=-1535.36, y=126.00, z=-1536.12]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

Also there is only one airlock door as the space station being made of steel and glass panes.
Willing to add more information if needed.
Thanks!

**Comment by zmaster587** [comment]
Does this occur if you are holding an item?

**Comment by dmodoomsirius** [comment]
please use something similar to [http://pastebin.com](http://pastebin.com )

**Comment by zmaster587** [comment]
This should be fixed in newer verions, if it continues with 0.5.5+ please re-open the ticket.
