### ISSUE TITLE
Moon has disappeared

### ISSUE THREAD

**Issue by Cubemania119** [zmaster587/AdvancedRocketry#1171]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.2.2618
Advanced Rocketry Version:
-1.12.2-1.2.6-57
LibVulpes Version:
-1.12.2-0.2.8-27
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------- N/A
Crash Report:
---------- N/A
Explain issue in detail:
The Minecraft moon has disappeared from the sky as long as a planetsDefs.xml file is loaded into the config folder. With the xml file removed, the moon appears again just fine.
This was tested with the template planetDefs.xml provided

**Comment by dmodoomsirius** [comment]
Well you do define the moon aka Luna in the planetDef.xml file. When you removed it it was regenerated. the template may need to be updated.

**Comment by Cubemania119** [comment]
Whoops, I see the problem now. It appears that I overlooked the important change as of 1.1.3.
![image](https://user-images.githubusercontent.com/7896585/36636028-ea6671c2-1972-11e8-8f6e-396db393e47f.png)
The template includes a planet A with a planet A moon, but planet A isn't mapped to DIM 0.

Thank you for your help!
