### ISSUE TITLE
Railgun not working on Station

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1172]
Minecraft Version: 1.10.2
**is this the latest curseforge build?** YES
----------
Explain issue in detail:
No crash, just not functioning feature. The RailGun (Orbital) is working from Moon to Station orbitting Panet and from Moon to Station orbitting Moon. But I cannot make it work from the Station back to the Moon regardless where I park the station.

Is this intentional? Should it work only from Station to Planet or it just isn't ment to work from Station at all?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
