### ISSUE TITLE
Unmanned Drone harvested different gas than I ordered

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1173]
Minecraft Version: 1.10.2
**is this the latest curseforge build?** yes
----------
Explain issue in detail:
Observed behavior: Unmanned Drone harvested different gas than I ordered him.
Suspected reason:
I had inconsistency between the Planets cfg file in the Save and the Config folder... I believe this is what happened: I picked a gas, it found the gas in the Savefile Gas List => id of the gas in that list => gas in the Global list with the same Id. And that is the gas the Probe delivered.

Example: If I had in Save file gases A, B, and C and in the Config X, Y, A, B, C and I select gas A it would deliver gas X, since id A = 0 and list2[0] = X.

**Comment by gdarai** [comment]
Now the sad part:
It looks like I cannot fix this. I set the:
``` B:resetPlanetsFromXML=true ```
But it is still the same, how can I change which gasses are harvestable where in existing save?
The Planet config in save does not contain the information any more, so it has to be somewhere else... but where?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
