### ISSUE TITLE
[Cross-Mod Bug]: BWM + BoP breaks Advanced Rocketry's Rendering

### ISSUE THREAD

**Issue by Lanse505** [zmaster587/AdvancedRocketry#1174]
- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Advanced Rocketry: 1.12.2-1.2.6-57
- BetterWithMods: 1.12-2.0.25
- BiomesOPlenty: 1.12.2-7.0.1.2302-universal
- Hwyla: 1.8.23-B38_1.12
- JEI: 1.12.2-4.8.5.157
- LibVulpes: 1.12.2-0.2.8-27

**is this the latest curseforge build?**
Yes

**Explain issue in detail:**
BWM + BoP breaks Advanced Rocketry's Rendering

This can be reproduced with HCStrata turned off as well, tested per @DaedalusGame 's request in discord.

As long as both BoP and BWM are present in the same modded environment it breaks Advanced Rocketry's Rendering for most blocks.

- Screenshots:
- Working Vs Non-Working:
https://i.imgur.com/sveUfTn.png
https://i.imgur.com/grqWsSE.png

**Comment by Lanse505** [comment]
https://github.com/BetterWithMods/BetterWithMods/issues/772
https://github.com/Glitchfiend/BiomesOPlenty/issues/1190

**Comment by zmaster587** [comment]
Looks to be about the same as #946.  Still have not been able to track this one down, help/suggestions would be appriciated.

**Comment by wamc2017** [comment]
Hmm, there was a similar problem with the Lootbags mod prior version 2.5.4. Maybe @Malorolam could help out and tell what's the problem is/was?

**Comment by Malorolam** [comment]
What was happening for me was that the Item Rendering wasn't being registered in the right time during initialization, so the items themselves weren't being registered under Lootbags, leaving the textures to the wind to conflict with every other mod that had the same error during stitching.  The specific code I found to lead me to this is the `IRegistryDelegate<T> delegate` field inherited through IForgeRegistryEntry.  Set up a breakpoint in the item code and check if the referent is null for that.  If it is, then you've got some registration issue most likely.  I'm using the RegistrationHandler system the added to do all the registration now and it appears to all be working correctly.
I think this is the cause of all the 1.12.2 item texture glitches, I remember that the location of item rendering wasn't as important in earlier versions, as long as you did it after registering the item in general it all worked fine.

**Comment by zmaster587** [comment]
@Malorolam I suspected something with texture stiching but didn't know where to start looking, thanks for the tip!  I'll give that a shot.

**Comment by zmaster587** [comment]
Is this still an issue with build 60?

**Comment by Lanse505** [comment]
This has been resolved by an update on BWM's End!
