### ISSUE TITLE
Crash when filling water bucket

### ISSUE THREAD

**Issue by pmmeyourpassword** [zmaster587/AdvancedRocketry#1178]
Minecraft Version: 1.12.2
-
Forge Version: 1.12.2-forge1.12.2-14.23.2.2611
-
Advanced Rocketry Version: AdvancedRocketry-1.12.2-1.3.0-58
-
LibVulpes Version: LibVulpes-1.12.2-0.2.8-27-universal
-
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report: 
https://pastebin.com/LazdAE0v
----------
Explain issue in detail:
I filled a bucket with water then it crashed.

**Comment by dmodoomsirius** [comment]
already fixed #1177
