### ISSUE TITLE
[1.12.2] Crashes when drinking milk or filling a water bucket

### ISSUE THREAD

**Issue by wamc2017** [zmaster587/AdvancedRocketry#1179]
Minecraft Version:
1.12.2
Forge Version:
14.23.2.2623
Advanced Rocketry Version:
1.12.2-1.3.0-59
LibVulpes Version:
1.12.2-0.2.8-27
**is this the latest curseforge build?**
yes
#Please Pastebin crash
https://pastebin.com/43EkbZcV
Crash Report:
Crashes when drinking milk or filling a water bucket.
Explain issue in detail:
Game crashes when drinking milk or filling a bucket with water, I know it's similar to #1177 and #1178 but it still happens in 1.12.2-1.3.0-59 where commit https://github.com/zmaster587/AdvancedRocketry/commit/ee0a9b8961863d00128b9896b9da8a98eb8a429d should be included according to the changelog... :smile:

**Comment by zmaster587** [comment]
Strange, it's not crashing when fill or dump water, nor when I drink milk.  Just going to guess the raytrace is null under certain circumstances.  Take 2!

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.3.0.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1766148/AdvancedRocketry-1.12.2-1.3.0.jar.zip)
Try this one and see if it's still broken?

**Comment by wamc2017** [comment]
This version works fine. :+1:

**Comment by Austin5003** [comment]
Having the same issue here
[crash-2018-02-28_14.01.43-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1768470/crash-2018-02-28_14.01.43-client.txt)

**Comment by zmaster587** [comment]
@Austin5003 what about the build I linked above?  That's slated to be the next release

**Comment by DoctorJew** [comment]
Can confirm this was an issue but the new build seems to have fixed it

**Comment by Austin5003** [comment]
@zmaster587 That build fixed the issue.
Thanks for the quick response

**Comment by zmaster587** [comment]
Alright, good to know!  I'll close the issue then
