### ISSUE TITLE
Electrolyser and Chemical Reactor rendering bug

### ISSUE THREAD

**Issue by mskurnik** [zmaster587/AdvancedRocketry#118]
The electrolyser and chemical reactors when built facing east/west have a strange rendering bug where the model is not placed correctly.  The machine itself still works but the way it looks is odd as you can see below with the electrolyser

![2016-05-30_20 17 55](https://cloud.githubusercontent.com/assets/10066235/15662257/cc00f57c-26a3-11e6-84fa-30ae412facaa.png)
![2016-05-30_20 17 58](https://cloud.githubusercontent.com/assets/10066235/15662258/cc0c5e62-26a3-11e6-9994-b0d02672c1c3.png)

**Comment by zmaster587** [comment]
I had been working on standardizing the renderers as they were a bit of a mess before, I had obviously not tested enough after the changes.  Should be fixed for next update
