### ISSUE TITLE
Orbital laser drill suggestions

### ISSUE THREAD

**Issue by EasterncheesE** [zmaster587/AdvancedRocketry#1180]
Minecraft Version:
1.7.10
Forge Version:
1614
Advanced Rocketry Version:
1.2.5-69
LibVulpes Version:
2.8
**is this the latest curseforge build?**
Not, pre-patest

Hello. Could you please check and consider the update for orbital laser drill?

Let me explain the situation a little, then i will give the improvement suggestion.
We do have the tech server with IC2 and advanced solar panels.
For now on, the EU-matter fabricator takes about 1m of energy per mB (millibucket) of UU matter.
Getting about 8 mb of UU matter will give the ability to make 1 piece of iron ore from it.
Means, 1 iron ore = ~8m EU/32m RF.
The Advanced Solar panels Ultimate panel gives 512 EU/T, resulting in 10k eu-sec. Players keep stacking them to get really big numbers of energy income.

For the laser drill, it does have the inner storage of 700 000 RF. Not sure for the energy conversion inside machines (can use both RF and EU, but it doesn't show difference on usage - both EU and RF receivers can be placed in one multiblock resulting of total 700 000 energy (not defined) storage).

I have put a power multiplier for drill on 50 - means mining 1 block of anything costs 500000 RF (as far as i remember, base value is 1000 rf/block). Even through it mostly mine cobble, it made my playes possible to have like 8k of diamon ore within once day. Changing the value to 70 won't help much. Also, i tried to change it to 150 and it seems that it doesn't allow machine to mine any block - because buffer is too low. So, my meaning that with given mod setup, having the drill with maximum energy cost is still way too profitable for players. My suggestions to improve it as follows:
Forgot to mention, i turned off actual planet mining not to damage them and prevent massive chunk update.

1) Is it possible to add % chance per ore, for example, 95% for cobble and 5% chance for other ore (if we can define chance per ore, it would be great)? Also, if that config could contain the chance for getting 1-5 ore, that would be nice (So i could define that in 95% of cases player get 5 cobble, 5% case - get 1-2 ore).
2) Other suggestion is to make it selectively mine the specified ore with set cost per ore (EG iron mining mode use 100 000 rf per block, diamond mining mode use 500 000 rf per block).
3) Add lens upgrades that allow the drill to mine specific ores, then we can balance it with lens cost and cannot mine all players want - need to make some maintenance on the drill.
4) Add drill work speed regulator (like IC2 miner, which work pretty slow until you put many accelerators inside). Or maybe make drill inherit the coils speed boost as it was made for other AR machines with possible config for each upgrade speed increase.

If you have any questions or suggestions, please let me know, i will try to explain my idea more exactly with correct examples of real server experience.
BTW, having the config for coils speed mult would also be great, so then we can adjust those numbers at will and find the balanced numbers for it. I specifically think that crystallizer and precision assembler are way too fast with iridium coils.

**Comment by Silfryi** [comment]
The point of the drill, I believe was to be something similar to Extra Utilities' quantum quarry, an easy way, at an extreme amount of power, to gain ore. This sounds like a power generation ease issue, not a laser drill issue. Even though the drill makes little sense, the selective filtering makes even less sense, because the laser will still hit everything. For that reason, lenses make it seem strange as well. These also make it, I feel, too close to the MFR or Industrial Foregoing laser drill. The point of the iridium coils is that they are endgame, AFTER much successful asteroid mining, so the speed multiplier seems balanced. Here it seems the issue is an outside source of iridium, not that they're overpowered for their cost.
Lastly, I think the idea of "anything fully configurable is therefore balanced" is ridiculous. This lets people mess with the mod much more, therefore stripping it of how it was meant to be played. 1.7.10 support has also been dropped, so this would only go into affect for 1.12

**Comment by Silfryi** [comment]
Sorry about lateness. While I am not an official part of the team, I do try to help alout around here. I probably have a different outlook on mods than you do, so take what I say with a grain of salt. 

I am NOT against customization. However, I feel that full customization is the mod author saying ‘I don’t know how to balance this’.  Having a customizer for the laser drill’s power consumption would be nice. The coil adding to improve efficency up to today’s base could also be cool. I think, however, the coil multipliers are fine. I like unique ecosystems, however I do not like total rebalanves of mods ro make them fit.

**Comment by EasterncheesE** [comment]
Well, as soon as author leave his basic config for how it was meant by him, totally remove the issue with "i don't know how to balance this". But well, it's his own vision and it cannot include all the things existing, like Enderio, Mutant monsters and many other mods, so he cannot keep them in mind when making the balance. That's why full customization helps a lot when coming to build a real server with a defined list of mods with their compatibility and energy system issues. 

I understand your position, and do not mean any offence against it. I just try to persuade you to the fact that "fully customizible mod" is always better then "not fully customizible mod" and there is no situation where it could be vise versa in the view of finished product. Of course, hardcoding some things is much easier in the view of making mod as author don't have to think on what should be customizible. But, in fact, if mod balance is okay for server in first place, nobody's gonna change it, right? So those, who feel okay, just use default stuff, those, who know what they want, change the variables and get what they want. Everyone's happy. It's just a matter of authors passion and time investment or both options.

**Comment by Silfryi** [comment]
Also, what I mean by full customization is this”The laser drill could lake between 1 and 1000000 Rf/t”, or other things such as that. However, some consumption multiplier that could not go below one would be great.

**Comment by EasterncheesE** [comment]
Well, actually, i think of "define 1 or 99999999, default is 100 RF" or "default is 100 RF, define the multiplier" as pretty same things. Both allow for customization, but second one is less intuitive and is harder for fine tuning some numbers, but they both do exactly the same thing, just in slightly different method.

**Comment by Silfryi** [comment]
No, the multiplier is on the already existing value, effectively limiting it to more than the base value. I prefer a hard limit of no less than, and a mult makes it more intuitive in that respect for me.

**Comment by zmaster587** [comment]
I believe "LaserDrillPowerMultiplier" handles power requirement customisation?  It's not a per ore config but it is something.  I'm not sure when it was added, but it's old enough to be in the 1.7.10 test world config.

The laser drill is due for an overhaul, it's more just a matter of finding time.

**Comment by Silfryi** [comment]
I believe the OP's problem was not enough energy storage on the machine to cope with the values he was trying to set for that config.

**Comment by EasterncheesE** [comment]
Please ignore this thread. As i’m a topicstarter and its just a necroposting by Sylfryu. 1710 version is suspended long ago, so there is no much sense to discuss it anymore.

**Comment by Silfryi** [comment]
Sorry, I just had a vested interest in the issue. I can agree, though. This was a long argument for no gain. OP made some fair points though.
