### ISSUE TITLE
[1.10.2]Fuel loader not working

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1181]
Forge Version:
-1.10.2 - 12.18.3.2511
Advanced Rocketry Version:
- AdvancedRocketry 1.10.2-1.3.0-83-UNSTABLE build -83 for 1.10.2
LibVulpes Version:
-libvulpes-[1.10.2]-0.2.8-8
**is this the latest curseforge build?**
Yes
----------
Explain issue in detail:
Fuel loader not accepting rocket fuel. Shift right click on Rocket also does not work, just open GUI.
![2018-02-28_14 41 17](https://user-images.githubusercontent.com/27149563/36790704-ff4f46c4-1c95-11e8-971a-8fa8fceb7964.png)

**Comment by tonicsense** [comment]
Same here. Cant even fuel per Hand

**Comment by zmaster587** [comment]
Does this occur with only AR and libvulpes installed?

**Comment by zmaster587** [comment]
Replicated

**Comment by zmaster587** [comment]
Accidently removed the bucket registration code
