### ISSUE TITLE
Server crash when activating oxygen vent 

### ISSUE THREAD

**Issue by Aderyn** [zmaster587/AdvancedRocketry#1182]
Minecraft Version:
1.12.2
Forge Version:
14.23.1.2601
Advanced Rocketry Version:
AdvancedRocketry-1.12.2-1.2.6-50.jar
LibVulpes Version:
-
**is this the latest curseforge build?**
Not sure, but it's the latest FTB revelations release (stable version). Survival version.
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:

I connected an oxygen vent into a powergrid of solar generators. and the server went down instantly as soon as the trace was activated. 

The puzzling part is that it used to work for a brief moment when i first got up there. But now the server instantly dies no matter what i do as soon as i turn it on. What kind of logs do you want me to send you? Is there a way to fix it without downloading the unstable version?

As a sidenote, i get the same bug as everyone else where i can't see any planets just like most others. Can't seem to find any threads with a fix. Do you have any solutions? I have tried building a warp controller and warp core in the space station but alas, no luck.

**Comment by zmaster587** [comment]
two things, I highly recommend updating to the unstable version, it's so far only been bugfixes.  As for the logs, fml-server-latest.log

There's a few packs floating I've heard are being distributed with a blank planet file, I'd suggest deleting the config/advRocketry/planetDefs.xml and the <world>/advRocketry/planetDefs.xml and <world>/advRocketry/temp.dat and let them regenerate (or preferably back them up).

**Comment by Aderyn** [comment]
Thanks @zmaster587, i'll have the server admin try these things :) :+1:

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
