### ISSUE TITLE
Dimensions made with Just Enough Dimensions have incorrect Skybox.

### ISSUE THREAD

**Issue by Axieum** [zmaster587/AdvancedRocketry#1186]
**Minecraft Version:** 1.12.2
**Advanced Rocketry Version:** 1.3.0-60
**LibVulpes Version:** 0.2.8-27
**Is this the latest CurseForge build?** Yes

As the title says, when making a dimension with Just Enough Dimensions and Dim mapping it via the planetDefs.xml file, everything else works but the skybox is the vanilla one. Even when setting the World Provider to `WorldProviderPlanet` it just crashes (https://hastebin.com/eposasasiq).

Perhaps, add a feature to create a standard "overworld-like" dimension with certain generator type and settings (so I can have a `lostcities_bop` world with `{profile:wasteland}`). An in-game command for creating planets on the go would be helpful for servers who want to create a new planet for every player without having to edit the world planetDefs etc.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by eagleyes005** [comment]
Please re-open this issue. Because i'm using the latest version of the two mods and i have the same problem.
