### ISSUE TITLE
Rolling machine does not run

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#119]
I power it, put some ingots in the input hatch and nothing happens.

**Comment by zmaster587** [comment]
What metal are you putting in the hatch and what mod is it from?  Also did you make sure the machine is switched on in the Rolling machine block?

**Comment by Tarkov** [comment]
I am sorry, it works fine. I have been using it lately, but I just noticed that now it needs water.

**Comment by zmaster587** [comment]
Ah alright/
