### ISSUE TITLE
Microwave Reciever should be Receiver

### ISSUE THREAD

**Issue by neclimdul** [zmaster587/AdvancedRocketry#1195]
Minor spelling mistake, easy enough to fix in a language file without needing to change any class names or blocks.

**Comment by zmaster587** [comment]
It's been fixed in the 1.2.x builds for a while now.  I probably ought to rebase the 1.12 builds to master though.

**Comment by neclimdul** [comment]
Ah, yeah I saw it in an old pack and then searched master and saw it still there. Thanks!
