### ISSUE TITLE
1.7.10 server bug

### ISSUE THREAD

**Issue by huajimi** [zmaster587/AdvancedRocketry#1196]
Most of the mods used by the server are normal, but the Moon is not compatible with the territory Residence4.7.3.1 plugin, restarting the server does not save the territory (home) and territory items on the moon. The MOD version is the latest version of 1.7.10, Server is Thermos-1.7.10-1614-58-server, I hope to be able to solve it, I am not good at English so Google translation, I am sorry, please understand.

**Comment by zmaster587** [comment]
Does Residence4.7.3.1 support dimensions other than vanilla?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
