### ISSUE TITLE
[1.12.2] Broken EU support?

### ISSUE THREAD

**Issue by MasterEnderman** [zmaster587/AdvancedRocketry#1197]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.2.2623
Advanced Rocketry Version:
-1.3.0-60
LibVulpes Version:
-0.2.8-27
IndustrialCraft Version:
-2.8.61

Explain issue in detail:
I can't power any Multiblock Machines in Advanced Rocketry with EU. Even the cables won't connect. Am I missing something?

**Comment by CTH999** [comment]
Was it using the EU input port?

**Comment by Digimortal2014** [comment]
It seems everyone is not having the same problem. I have advanced rocketry and ic2 installed along with jei, optifine all on 1.12.2. I have just barely finished my electric induction furnace when i noticed all 3 of the transfer cables data, energy, and fluid says decrepitated or something close on jei, and i cant craft them to power my furnace. I tried using an insulated copper cable instead from ic2, and it didnt even recognize anything. I would make a new post, but im not sure if im not the only one with this issue, so i dont know for sure if its a real issue or just me. Mind helping?

**Comment by MasterEnderman** [comment]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.3.2679
Advanced Rocketry Version:
-1.4.0-80
LibVulpes Version:
-0.2.8-31
IndustrialCraft Version:
-2.8.75

![image](https://user-images.githubusercontent.com/24524662/39733307-64b0aa28-5272-11e8-9031-2df2371445f3.png)

I only see one "Power Input Plug" in JEI and the cables from IC2 won't even connect to the machine (in this case the lathe)

**Comment by TheBlackDevil0955** [comment]
I've got the same problem @MasterEnderman it just doesn't connect and i don't find any other input plugs
@Digimortal2014 that was just a place holder and now it isn't implemented anymore
