### ISSUE TITLE
1.10.2 Mo'Creatures not spawning

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1200]
Minecraft Version:
1.10.2 Latest stable
Explain issue in detail:
When trying with Mo'Creatures custom mob spawner system, I noticed that it is not spawning anything on any AdvRocketry Biomes. Does anyone know why and how to fix it? It even stops spawning animals in the Alien Forest.

PS: Writing this issue here since Mo'Creatures development seams to be dead.
Also it seems that the only solution is stop using CMS (Customm Mob Spawner) even though it is described as Mo'Creatures dependency:
https://forum.micdoodle8.com/index.php?threads/mocreatures-conflict.4598/
But wihout CMS it stops spawning Mo'Creaures water mobs so this is also not solution.

**Comment by zmaster587** [comment]
From the looks of it custom mob spawner totally overrides vanilla spawn.  AR uses vanilla's system, so unfortunately there does not appear to be anything I can do besides update custom mob spawner

**Comment by gdarai** [comment]
Yes, it overrides it. The thing is that you have to specify there what should spawn where, biome by biome... and I trid to add your biomes the best way I could with no success. It even stop giving errors or warnings, the config just passed as correct, but no spawn happend. That is why I hoped somebody had similar issue. In this case actually not you directly. But thanks anyway.
