### ISSUE TITLE
Space Elevator text staying on screen when changing dimension

### ISSUE THREAD

**Issue by GippoHippo** [zmaster587/AdvancedRocketry#1202]
Minecraft Version:
1.12.2
Forge Version:
14.23.2.2618
Advanced Rocketry Version:
1.12.2-1.2.6-56
LibVulpes Version:
1.12.2-0.2.8-27
**is this the latest curseforge build?**
No (Latest Stable FTB Revelations build)
Explain issue in detail:
This issue isn't a crash rather, Space Elevators seem to leave their text on the screen when changing dimensions via any sort of teleport commands (thus more noticeable on servers). The problem being I have "No Destination Selected" stuck on my screen when I'm on my Space Station. Walking into an elevator and back out seems to remove the text from the screen, however I destroyed the elevators to see if it would fix the issue and unfortunately it didn't.

**Comment by zmaster587** [comment]
Display timer was not being reset on dimension change, should be fixed in the next build
