### ISSUE TITLE
Trying to BAN Dilithium from the Overworld to force travel too Moon

### ISSUE THREAD

**Issue by dragon076** [zmaster587/AdvancedRocketry#1203]
Not sure if this is the appropriate section for this or it may even be a mod interaction issue.
I've been making a modpack and testing a way to Ban ore from everything but the moon and other planets.
But i can't seem to get COFH world gen to do this, or some other mods i've tested.

Minecraft Version: 1.12.2
Forge Version: 14.23.2.2617
Advanced Rocketry Version: 1.12.2-1.3.0-61
LibVulpes Version: 1,12,2-0.2.8-27
Mods installed:
Actually Additions
Applied Energistics 2
Aroma1997's Dimensional World
Astral Sorcery
Advanced Rocketry
Biomes O' Plenty
Botania
CoFH Core
CoFH World
Compact Machines
CraftTweaker2
Cyclic
Draconic Evolution
Forestry
Immersive Engineering
IndustrialCraft 2
JEI
Mekanism
NuclearCraft
Quark
Refined Storage
RFTools
Tech Reborn
Thermal Expansion
Thermal Foundation
This is not the full list just the major stuff, it's a big pack atm.
I've been trying to get this too work since the 55 version of advanced rocketry.
I realize it may be my fault or something with COFH core.
Just looking to see if this can be done or not.
Thanks for all your work.
Files attached
[12_ore_ban.json.txt](https://github.com/zmaster587/AdvancedRocketry/files/1810015/12_ore_ban.json.txt)
[advancedRocketry.cfg.txt](https://github.com/zmaster587/AdvancedRocketry/files/1810019/advancedRocketry.cfg.txt)
[planetDefs.xml.txt](https://github.com/zmaster587/AdvancedRocketry/files/1810020/planetDefs.xml.txt)

![2018-03-14_18 02 12](https://user-images.githubusercontent.com/12526194/37389974-0726f79e-27b2-11e8-8ca6-21d31790ad2a.png)

.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Have you tried setting "DilithiumPerChunk" in the config to 0 while leaving "DilithiumPerChunkLuna" alone?

**Comment by dragon076** [comment]
Not a bad idea there thanks but will that work so that it spawns on other planets.
And i was trying to do much the same with Rutile/Titanium.
ie. Ban from all but those added by advanced rocketry

**Comment by dragon076** [comment]
Setting "DilithiumPerChunk" to 0 and leaving "DilithiumPerChunkLuna" alone works fine but i only have Dilithium on the moon and no other planets. This is usable for what i wanted but i did want to try an have rutile on the moon and other planets without being in the overworld and deep dark or mining dimensions. has anyone got an idea to make that work. I still can't see why my 12_ore_ban.json.txt file doesn't work, it's setout as per cofh help page says it's suppose to be and i checked for json errors.
Thanks for the input.

**Comment by zmaster587** [comment]
is there any reason using http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/OreConfiguration.php won't work for setting ore generation on other planets?

**Comment by dragon076** [comment]
i can try the ore config files but i was a little confused as how to set those up. but will those allow me to ban rutile from the overworld at the same time as letting those spawn on planets?

**Comment by dragon076** [comment]
I just did a quick edit of ore config. so in theory changing the pressure to something other than the overworld will have it spawn on other planets just not those with attributes similar to the overworld?
If i have referenced things correctly that is.
Thanks.
[oreConfig.xml.txt](https://github.com/zmaster587/AdvancedRocketry/files/1828603/oreConfig.xml.txt)

**Comment by dragon076** [comment]
@zmaster587 I know your probably busy with real errors so i don't expect too much.

I quickly found i messed up the formatting in the above file. But the one i adjusted seems to work, but a little unsure as to how i reference rutile ore. The new file still hasn't stopped rutile spawning in the overworld and keeping it on planets. Still open to ideas if anyone has some.
Thanks
[oreConfig.xml.txt](https://github.com/zmaster587/AdvancedRocketry/files/1843917/oreConfig.xml.txt)

**Comment by bHXDgiuMa5yLHyC8** [comment]
I think it would be handy to have a config option that would ban dilithium from dimension 0 under any circumstances.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I think it would be handy to have a simple config option that would prevent dilithium ore from generating in dimension 0 under any circumstances.

**Comment by gdarai** [comment]
I may ask a lot from you, but, here is what I did, when I was facing the same issue. This is Python script, generating the necessary COFH file vanilla.json...
You can write the input files for biome groups ores and ore config... in this much more organized format and it will generate the json for you:
[Darai's SpaceRace OreGenerator](https://github.com/gdarai/SpaceRace/tree/master/Ores)
Hope this helps.

**Comment by gdarai** [comment]
Also, start with smaller pack, only those mods, giving dimensions and ores... set the config and check how it looks. I am using World Stripper for that.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
