### ISSUE TITLE
Issue with Open Terrain Generator Biome being used on a planet.

### ISSUE THREAD

**Issue by TJPlaysNow** [zmaster587/AdvancedRocketry#1204]
For some reason, when I have an Open Terrain Generator biome it takes biome things such as grass color, but it doesn't build the biome with OTG settings. I have tested the biome in a plane world and it worked, but when I put it on a planet it doesn't work. As well as that, there are just two biomes on the planet, "openterraingenerator:moon_plains", and "openterraingenerator:moon_crater". But yet the planet is also getting two more biome, the desert and the ocean.

Here are all the configs and the mods if you want to test it.
[OTG Tester.zip](https://github.com/zmaster587/AdvancedRocketry/files/1817692/OTG.Tester.zip)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
