### ISSUE TITLE
Question regarding IFillableArmor and the Gas Charger

### ISSUE THREAD

**Issue by mallrat208** [zmaster587/AdvancedRocketry#1205]
I've been working on an armor mod that add's an environmental suit (think Prey/Half-Life) and was looking at the interfaces AR provides. Most of it seems pretty straight forward though I do have a question about IFillableArmor. It looks like the Gas Charger/Oxygen Charge specifically looks for ItemSpaceArmor rather than an item that implements IFillableArmor. That's not really a problem if you extend the AR Class, but in my instance that's not really possible. I'm curious if that's an intended function or just a bug that needs to be fixed. It'd definitely be handy if checked for IFillableArmor instead.

https://github.com/zmaster587/AdvancedRocketry/blob/61d7b2b0bd9ee58a5cc67ab6c2bbb3b00328e0d6/src/main/java/zmaster587/advancedRocketry/tile/oxygen/TileOxygenCharger.java#L65-L72

**Comment by zmaster587** [comment]
IFillableArmor was added much later, this was just a reference that was missed, I'll get it corrected.
