### ISSUE TITLE
Asteroid chip disappeared after breaking guidance computer (Satellite Terminals+Bays neither dropping nor retaining inventory)+ unable to program new chip, visual inventory shifting

### ISSUE THREAD

**Issue by PG-Fuury** [zmaster587/AdvancedRocketry#1206]
As the title says, Modpack: FTB:Revelations with minor tweaks

**Comment by PG-Fuury** [comment]
I have been able to program chips from time to time, however when I open up the satellite terminal it shuffles my inventory around (hotkey 1-8->hotkey 2-9, hotkey 9 disappears, satellite chip inside gets visually duped into top left inventory slot, inventory gets shifted around 1 to the right per row, last flows into next row, bottom right appears in hotkey 1), fixes itself when opening an inventory outside of the player inventory (visual only)

**Comment by PG-Fuury** [comment]
Inventory as it should be: 
https://i.imgur.com/91khHYL.png
Inventory Shuffle:
https://i.imgur.com/G993OUh.png

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
