### ISSUE TITLE
Modular powersuits compatibility?

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1208]
Maybe making it possible to use an modular powersuit as an space suit?
https://github.com/MachineMuse/MachineMusePowersuits/issues/834

**Comment by gdarai** [comment]
It is possible, through SpaceTight enchantment.
I used following MineTweaker Code to do that, you can too:
Of course you must set the ```airSeal```  to whatever item you want to use.
I am using modular powersuit 1.10.2 - 1.2.129
```
val airSeal = <bqmie:icon_item:24>;
recipes.addShaped(<powersuits:powerArmorHead>.withTag({ench: [{id: 128 as short, lvl: 1 as short}]}), [[null, null, null], [airSeal, <powersuits:powerArmorHead>, airSeal], [null, null, null]]);
recipes.addShaped(<powersuits:powerArmorTorso>.withTag({ench: [{id: 128 as short, lvl: 1 as short}]}), [[null, null, null], [airSeal, <powersuits:powerArmorTorso>, airSeal], [null, null, null]]);
recipes.addShaped(<powersuits:powerArmorLegs>.withTag({ench: [{id: 128 as short, lvl: 1 as short}]}), [[null, null, null], [airSeal, <powersuits:powerArmorLegs>, airSeal], [null, null, null]]);
recipes.addShaped(<powersuits:powerArmorFeet>.withTag({ench: [{id: 128 as short, lvl: 1 as short}]}), [[null, null, null], [airSeal, <powersuits:powerArmorFeet>, airSeal], [null, null, null]]);
```

**Comment by ErdbeerbaerLP** [comment]
how to increase the oxygen volume with that?

**Comment by lehjr** [comment]
This isn't impossible to do, but probably should be done as a module, similar to the Hazmat module in the mod. However, I'm not entirely familiar with Advanced Rocketry. Or how the space suit works.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Leonitus454** [comment]
How do you add pressure and radiation protection?
