### ISSUE TITLE
[FTB:Revelation (slightly modified)] Error saving planet data, unable to load world

### ISSUE THREAD

**Issue by PG-Fuury** [zmaster587/AdvancedRocketry#1209]
[fml-client-latest.log](https://github.com/zmaster587/AdvancedRocketry/files/1829979/fml-client-latest.log)

As asked in the console, here's the fml-client-latest.log

**Comment by PG-Fuury** [comment]
reproduced with latest AR version:
[fml-client-latest.log](https://github.com/zmaster587/AdvancedRocketry/files/1830165/fml-client-latest.log)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by PG-Fuury** [comment]
Been nearly a year, don't have the world anymore. I didn't manage to fix the issue before I got rid of the world though
