### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by gunboy001** [zmaster587/AdvancedRocketry#121]
There is no oxygen in the nether but to make oxygen you need glowstone, sooo derp I guess.

**Comment by zmaster587** [comment]
Nether is supposed to have O2.  I think I know what happened though.  I'll have a fix out I'm a few hours.  In the meantime O2 can be disabled via config if needed.

**Comment by DarkGuardsman** [comment]
I would just hard code the main dim to have O2 in your hasO2 method

**Comment by zmaster587** [comment]
That's the plan
