### ISSUE TITLE
Crash w/Quark (caves)

### ISSUE THREAD

**Issue by mmelvin0** [zmaster587/AdvancedRocketry#1210]
If Quark's (experimental) cave generation is enabled, 1.4.0-63 crashes thusly:

https://git.io/vxcmM

Seems due to the this block state not being what you are expecting:

https://github.com/zmaster587/AdvancedRocketry/blob/09c8b2552afceb21c6237701b840ff8809fe4714/src/main/java/zmaster587/advancedRocketry/world/ChunkProviderPlanet.java#L124

**Comment by zmaster587** [comment]
It actually looks to be more to do with getting the cavegenerator https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/world/ChunkProviderPlanet.java#L82, it's just that the cave generator is cast to MapGenCaveExt on line 128 when it's not a MapGenCaveExt.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.4.0.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1831898/AdvancedRocketry-1.12.2-1.4.0.jar.zip)
Does this build work for you?

**Comment by mmelvin0** [comment]
Derp. You're right of course I didn't even read the variable name.

That build works great.

Your mod is the bees knees BTW!

**Comment by zmaster587** [comment]
Great, I'll update the other versions too and Thanks!
