### ISSUE TITLE
[1.10.2] Missing entries in en_US.lang file

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1211]
![2018-03-21_17 33 05](https://user-images.githubusercontent.com/27149563/37723213-199d2fe8-2d2e-11e8-9f8b-de996ba25c7f.png)
![2018-03-21_17 36 14](https://user-images.githubusercontent.com/27149563/37723310-6366ecfe-2d2e-11e8-918e-db07329ecca6.png)
![2018-03-21_17 37 50](https://user-images.githubusercontent.com/27149563/37723402-9b6040ba-2d2e-11e8-93de-eb2bb622d9da.png)

And the fluid tank is called Fluid Hatch
![2018-03-21_17 41 58](https://user-images.githubusercontent.com/27149563/37723677-3afec6a0-2d2f-11e8-8f85-e75b694ae205.png)

**Comment by zmaster587** [comment]
May be a failure during branch refactoring, investigating

**Comment by zmaster587** [comment]
I was was able to id a fix all of those except the first one, the seal detector and atmosphere analyzer seem to work fine in 1.4

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
