### ISSUE TITLE
Newest Unstable 1.10 version crashing server

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1213]
[crash-2018-03-21_17.53.48-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1837134/crash-2018-03-21_17.53.48-server.txt)

**Comment by ErdbeerbaerLP** [comment]
Not fixed with AdvancedRocketry-1.10.2-1.4.0-3

**Comment by zmaster587** [comment]
Fix for next update, typo in the moongendark biome constructor
