### ISSUE TITLE
Still white screen when scanning using the rocket assembling machine

### ISSUE THREAD

**Issue by stephen92** [zmaster587/AdvancedRocketry#1214]
Still happening after update when placing the Rocket Assembling Machine and hitting scan, everyone looking in the direction of the machine gets a white screen, it does not go away. Using latest 1.12.2 version.

AdvancedRocketry 1.12.2-1.4.0-65-UNSTABLE build -65 for 1.12.2

**Comment by zmaster587** [comment]
it was fixed in 68cc272b8a4f7613b37f9cd141c35d5b016df7b3, it missed the auto commit by a few hours.  It'll be fixed in build 66
