### ISSUE TITLE
planetDefs.xml is being overwritten when creating a new world

### ISSUE THREAD

**Issue by matt091498** [zmaster587/AdvancedRocketry#1215]
Version: AdvancedRocketry-1.12.2-1.4.0-65
My planetDefs.xml file (in config folder): https://pastebin.com/uZQhM6cv
planetDefs.xml in saves folder: https://pastebin.com/e1DXmrUJ
Error causing world load to fail: https://pastebin.com/b6BWViZp

Something seems to overwrite my planetDefs.xml file and puts in some of the default planets, erasing some of the ones I have created. When the overwrite happens, the number of planets and gas giants specified in the star tag turn to 0. My planetDefs.xml does have the correct number of planets and gas giants. The error given during world load says something is null at getMaxNumGasGiants.

Any help would be appreciated.

**Comment by zmaster587** [comment]
It appears Stelloth and Aclara are missing the number of gas giants, if you add numGasGiants="0" to both of those, does the issue persist?

**Comment by matt091498** [comment]
Adding in the numGasGiants to Stelloth and Aclara has fixed the issue. One more question, when i had oregen tags on the planets, the log would show that some of them were invalid. Is there any way to fix this or should i use a different mod for the oregen on the planets?

**Comment by zmaster587** [comment]
If you know of another mod that can do ore gen on planets, go for it.  Though the fix kinda depends on the exact error printed.  Only thing I can think of was that an invalid block or metadata was provided somewhere or there was a syntax error.  Would you be able to provide the log with the errors?

**Comment by matt091498** [comment]
I can recreate the errors with oregen and I'll post them when I'm done. The overwriting of the planetDefs.xml file still seems to happen. When it gets overwritten, the numPlanets and numGasGiants in the star tag both get changed to 0.  https://pastebin.com/PC6TVqTE

**Comment by matt091498** [comment]
This is the oregen error I get: 
[17:26:11] [Server thread/WARN]: thermalfoundation:ore:0 is not a valid name for ore
and here is the oregen tag in my planet:
<ore block="thermalfoundation:ore:0" minHeight="0" maxHeight="200" clumpSize="8" chancePerChunk="42" />

**Comment by zmaster587** [comment]
do you have thermal foundation installed, and have you verified it has a block named "ore"?

**Comment by zmaster587** [comment]
would you be able to send the xml over so I can give it a test?

**Comment by matt091498** [comment]
https://www.dropbox.com/s/xudpphestp6uu2u/planetDefs.xml?dl=0

**Comment by zmaster587** [comment]
Have you tried <ore block="thermalfoundation:ore" meta="0" minHeight="0" maxHeight="200" clumpSize="8" chancePerChunk="42" />

**Comment by matt091498** [comment]
tried what

**Comment by matt091498** [comment]
Yeah i can try that but the issue of the overwriting is still present if you check the xml file in the saves folder

**Comment by zmaster587** [comment]
I mean does it fix the error with the ore loader, Im still looking into the issue of files being overwritten

**Comment by zmaster587** [comment]
do you have "resetPlanetsFromXML" set to true in the config/advRocketry/advRocketry.cfg?

**Comment by matt091498** [comment]
it is set to false.

**Comment by zmaster587** [comment]
Does this issue occur in the most recent 1.2.x build or the 1.3.x build?

**Comment by matt091498** [comment]
The ore gen works now or at least it doesnt give invalid ore and I havent tried the 1.2.x or 1.3.x builds

**Comment by zmaster587** [comment]
Do the planets vanish or just get moved to the wrong star system?  I'm seeing the latter on my end.

**Comment by matt091498** [comment]
the planets are vanishing on mine. Kernkrag was one i checked and it isnt in the world file at all.

**Comment by zmaster587** [comment]
I'm not seeing Kernkrag is any of the files you sent, including the one in the config directory.

**Comment by matt091498** [comment]
weird let me check

**Comment by matt091498** [comment]
in the dropbox it is the second planet, or it is for me at least

**Comment by zmaster587** [comment]
Oh, Kerkrag, i was doing ctrl+f for "Kernkrag", the 'n' threw me off

**Comment by matt091498** [comment]
oh -_- I spelled it wrong in my file but that shouldnt matter.

**Comment by matt091498** [comment]
that one seems to get erased entirely

**Comment by zmaster587** [comment]
Either way, I've positivly identified the issue.  It appears to be some conflict with reconciliation of the temp.dat and planet xml.  A quick fix would be to delete the temp.dat file, that would also have the side effect of deleting spacestations you may have in orbit or satellites.  

Though I hope to have the issue fixed within a few hours.

**Comment by matt091498** [comment]
Cool I think I'll just wait for the mod update. Been trying to do some modpack stuff but was having trouble. Thanks for the help :)

**Comment by zmaster587** [comment]
no problem, thanks for the quick replies!

**Comment by zmaster587** [comment]
Should be fixed next update
