### ISSUE TITLE
[Any] Rocket invisible till chunk unloaded and reloaded

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1216]
The same also happens when landing with the rockewt/space elevator.
In survival you die at Y1000 because of fall damage (with the space elevator) resulting in no gravestone generating.
You are glitching in the invivible Rocket/Space elevator.
Tested in 1.10 and 1.11 (Multiplayer, Not tested in Singleplayer yet)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
