### ISSUE TITLE
[1.7.10] A problem with Advanced Rocketry

### ISSUE THREAD

**Issue by demycat** [zmaster587/AdvancedRocketry#1218]
Game version: any
When I play in the world after a while, it hangs (you can break it, but you can not use it or open inventory), but if you try to keep that the main line hangs forever (the same efect will be if you try to go to the same world)
How fix it?

**Comment by zmaster587** [comment]
I'm sorry, I don't quite understand.  Are you saying that the game hangs in such a way that you can walk around but not manipulate any blocks?  Is this on a server or client?  Have you verified it's not exhuasting memory?  Is there something in particular that you can do that causes the game to hang every time?

Would it also be possible to provide a copy of the fml-client-latest(if the client is hanging, you cannot look around or move at all) or fml-server-latest(if you can look around and walk, but cannot open inventories, break/place blocks) log file if it is not exhuasting memory?

**Comment by demycat** [comment]
@zmaster587 I recorded the video and my problem will be visible there
https://www.youtube.com/watch?v=vU6UmGwiyeU&feature=youtu.be

**Comment by demycat** [comment]
@zmaster587 How fix this?

**Comment by demycat** [comment]
I found problem and fix him!
