### ISSUE TITLE
Rocket render

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#122]
With the new release 0.5.4 when I build a rocket in my oldest games, it renders one block above the original place. If I remove the Rocket Assembling Machine it renders where expected.

Also once built, If I place any block next to the rocket or the launch pad, the rocket always renders at the level of the highest new block.

It only happens with the oldest games.

**Comment by zmaster587** [comment]
does it occur if you deconstruct and rebuild it?

**Comment by Tarkov** [comment]
Yes, I tried building it in different ways, and changing the position of the structure tower and the rocket assembling machine. Finally I found that the problem is when the rocket is built with a structure pipe from buildcraft.

If you put a structure pipe in a external side of a rocket and after the building you place a block next to the rocket, it can rises to the level of the new blocks (depending on the side you place the new block). Also depending on where you place the structure pipe it can rises just after the building without new blocks.

![2016-06-08_12 52 47](https://cloud.githubusercontent.com/assets/19404111/15892634/0b2a5832-2d7b-11e6-9220-11c7d5081f5e.png)

**Comment by zmaster587** [comment]
Does it do this if you replace the structure pipe with a vanilla block like dirt?  Wondering if maybe just the size is doing this is why i ask.

**Comment by Tarkov** [comment]
Exactly, it does not matter the kind of block, it all depends on the size of the rocket. If the rocket is not a perfect square, 3x4 for example, and once built you place a block next to one of the larger sides, it renders above that block.

**Comment by Tarkov** [comment]
I am not sure if this is related but I cannot fuel rockets when they are six blocks width or bigger. It says is too far away, even if the fuel station is placed next to the rocket.

**Comment by Tarkov** [comment]
Have you been able to replicate this issue or it only happens to me? I am concerned about the fuel station as I cannot fuel big rockets and do not know what to do.

**Comment by zmaster587** [comment]
I'll look into this tonight
