### ISSUE TITLE
planets around non-sol stars are still named as if they were around sol

### ISSUE THREAD

**Issue by lag42** [zmaster587/AdvancedRocketry#1221]
## Version of Advanced Rocketry
1.12.2-1.4.0-67-UNSTABLE
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.2.8-27-UNSTABLE
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
view planets around a star that's not sol and they're all sol-XX

**Comment by C1ffisme** [comment]
This is actually intended behavior for randomly generated planets at the moment. Personally, though, I would change planet names to either:

- A randomly generated name.
- The Star name with a **lowercase letter** next to it. This is the naming convention for actual exoplanets in real life. (e.g. TRAPPIST-1f, Proxima-b, etc.)

A letter is a lot easier to remember than a number too, IMO.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
![2019-03-03_19 18 35](https://user-images.githubusercontent.com/9893266/53705328-36593100-3de9-11e9-8960-9a94a8c08340.png)

Can confirm
