### ISSUE TITLE
space elevators can't connect a planet and it's moon

### ISSUE THREAD

**Issue by lag42** [zmaster587/AdvancedRocketry#1222]
## Version of Advanced Rocketry
1.12.2-1.4.0-67-UNSTABLE
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.2.8-27-UNSTABLE
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
build space elevators on a planet and it's moon and see how they can't reach eachother

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
