### ISSUE TITLE
[1.10.2] Server crash when changing dimensiosn (Unsure if it is advancedrocketry)

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1224]
## Version of Advanced Rocketry
1.4.0-4
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-8
## Version of Minecraft
1.10.2
## Crash report or log (if applicable)
https://pastebin.com/a2ynz5g9

## Description of the problem
When i change dimensions sometimes the server crashes. I dont know if it is AdvancedRocketry or any other mod. Even changing from Overworld to nether crashes sometimes.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
