### ISSUE TITLE
[1.10.2] Applied energistics meteors are not generating on any planet

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1225]
## Version of Advanced Rocketry
any
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-8
## Version of Minecraft
1.10.2
## Description of the problem
The meteorites are not generating. That is somehow missing, because in space are many of them

**Comment by zmaster587** [comment]
That's actually really confusing, features from other mods are not supposed to spawn in either.  The space dimension is based on the planet dimension generator, just with only one biome and no blocks to generate.  I'll have to dig deeper on this one.

**Comment by ErdbeerbaerLP** [comment]
TinkersConstuct islands are still spawning in the air. Because of that i disabled them

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
