### ISSUE TITLE
Problem with Advanced Rocketry and Mystcraft [1.7.10]

### ISSUE THREAD

**Issue by demycat** [zmaster587/AdvancedRocketry#1226]
I had a world with the Mystcraft mod, but after adding the Advanced Rocketry mod to the same world, I can not log in anymore, that is, I have to choose (when I create a new world with two mods, then everything is OK)
Log:
[2018-03-30-2.log](https://github.com/zmaster587/AdvancedRocketry/files/1863554/2018-03-30-2.log)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
