### ISSUE TITLE
Interaction with ActuallyAdditions

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1227]
## Version of Advanced Rocketry
1.4.0-4 Most advanced unstable Alpha on Curse
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
0.2.8-8 universal
## Version of Minecraft
1.10.2
## Description of the problem - Interaction with ActuallyAdditions
[ActuallyAdditions](https://github.com/Ellpeck/ActuallyAdditions/issues)

- Interaction with ActuallyAdditions ESD (Multidirectional Hopper) is not working on any AR machine - The hopper cannot insert or withdraw Tried with Input/Output hatch and with Rocket Unloader

- Interaction with ActuallyAditions Energy Laser (RF transfer) the Plug is not accepting the power.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
