### ISSUE TITLE
Re-saving of planetDefs.xml messes up Artefacts

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1228]
1.4.0-4 Most advanced unstable Alpha on Curse
------------
Have you verified this is an issue in the latest unstable build: Yes
Version of LibVulpes: 0.2.8-8 universal
Version of Minecraft: 1.10.2

The Artifact is wrongly re-saved into the save planetDefs.xml file...
Every time I enter and exit a game, there is 1 added to the damage of every artefact, so artefact 
```<artifact>bqmie:icon_item 14</artifact>``` is re-saved as ```<artifact>bqmie:icon_item 141</artifact>```
Of course also not recognized with any item in the game and so warp is not possile.

**Comment by dmodoomsirius** [comment]
Try putting 1 after as it uses after the item name is meta then stack. See if that resolve the issue.

**Comment by zmaster587** [comment]
fixed for next update
