### ISSUE TITLE
Can't launch any Rockets.

### ISSUE THREAD

**Issue by tterrag1112** [zmaster587/AdvancedRocketry#123]
For some reason, whenever I try to launch any type of rocket, it doesn't do anything. I know it's a bit vague, but I don't know what is happening. I know the rocket can launch because it gets built, but I do not know what is causing it to remain stationary.

**Comment by HyperMan19680** [comment]
Are you fueling them up?
Using the Moniter Station?

**Comment by tterrag1112** [comment]
I found the problem. I thought that the rockets still needed water, but now they use rocket fuel.
