### ISSUE TITLE
Fuel not consumed on Warp

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1230]
## Version of Advanced Rocketry
1.4.0-4 Most advanced unstable Alpha on Curse
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
0.2.8-8 universal
## Version of Minecraft
1.10.2
## Description of the problem - The fuel when warping is not substracted but added
Do warp an see your fuel rise not drop.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
