### ISSUE TITLE
Planets Must Be Discovered - and next?

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1231]
## Version of Advanced Rocketry
1.4.0-4 Most advanced unstable Alpha on Curse
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
0.2.8-8 universal
## Version of Minecraft
1.10.2
## Description of the problem - I am not sure how to use "Discover Planets through Warp Controller"

I know I was discussing this topic some months ago, but now it works, sort of so I would like to ask, how to actually use it. I found that when I manipulate the ```<isKnown>``` tag of a planet and I set the config ```B:planetsMustBeDiscovered=true``` then in Planet Selector I still see all the planets. But in Warp Controller I see only what has ```<isKnown>True</isKnown>``` It says that I must provide 100 of each data to start planet research... Ok, I give it 100 of each. And I click the start button. To increase my chances I even set config ```I:planetDiscoveryChance=1``` so I shoud discover a planet every time.

So far so good... now here the new and confusing part come: When the research ends I still have the same planets available in the warp controller. So I investigate, try few more times, and I find that I can put there in the bottom slot a Planet ID chip and when the research ends it sets the chip to a random planet.... well... good, but how do I transfer this into my Warp Controller? :) Thanks for the hint and keep up the great work, this is superb mod and I enjoy using it every single second.

As a present I am sending you a small picture of my so far biggest ship:
![snowflake-sideiso](https://user-images.githubusercontent.com/26735549/38167007-3d9406bc-352e-11e8-8b6f-f568e8a32026.jpg)

**Comment by sdfg2** [comment]
I was struggling with this as well.  From what I can discover, a chip needs to be in the warp controller when searching for planets, but once that planet has been discovered it is automatically listed in the 'select planet' screen of the warp controller.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
