### ISSUE TITLE
invalid launchpad structure

### ISSUE THREAD

**Issue by DragonGamer25** [zmaster587/AdvancedRocketry#1232]
## Version of Advanced Rocketry
1.12.2-1.4.0-67 
## Have you verified this is an issue in the latest unstable build
yes
## Version of LibVulpes
1.12.2-0.2.8-28
## Version of Minecraft
1.12.2

## Description of the problem
i do the base for the rocket with launchpads and Structure Tower, but the rocket assembly machine keep saying "invalid launchpad structure"
the base with launchpad is 5x5 and the structure tower is 7 block tall
![2018-03-31_22 06 38](https://user-images.githubusercontent.com/37963843/38167109-17e4b428-3530-11e8-8a35-124024b2d697.png)
![2018-03-31_22 08 22](https://user-images.githubusercontent.com/37963843/38167111-1d869b62-3530-11e8-8184-52a0beedc991.png)

**Comment by gdarai** [comment]
Isn't the monitor supposed to be one block heigher?

**Comment by DragonGamer25** [comment]
i don't know, i read the guide and it didn't talk about any monitor

**Comment by DVorriose** [comment]
Try Rocket Assembling Machine one block higher.

http://arwiki.dmodoomsirius.me/AdvancedRocketry/blocks/RocketAssemblingMachine.php

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by mastrude** [comment]
Seems to still be an issue. See https://imgur.com/TrzqfEx and https://imgur.com/JMOHTfc. Please reopen.

**Comment by TripTripy** [comment]
@mastrude your assembling machine is turned the wrong way, Try turning it around so that the front of the assembling machine faces away from the pad

**Comment by qrmaster** [comment]
i have same problem on 1.12.2 with space station assembler it turned away from launchpad and one block higher, launchpad is 16x32 and structure tower is 16 blocks first block is on one level with launchpad
