### ISSUE TITLE
Advanced Rocketry Crash.

### ISSUE THREAD

**Issue by vinyl90** [zmaster587/AdvancedRocketry#1235]
## Version of Advanced Rocketry
[AdvancedRocketry-1.12.2-1.4.0-68]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-28-universal
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
https://pastebin.com/WvYCvami

## Description of the problem
[I had updated this mod and when it crashed tried removing it and it launched immediately]

**Comment by Zer0Lyfe** [comment]
I have the exact same problem and lowering the version to 2626 works but when to in 2653 it also crashes when mekanism is in the pack. soon as i remove Advanced rocketry(but not libvulpes) or mekanism it stops crashing.

**Comment by zmaster587** [comment]
That appears to be an ASM interaction.  Does this continue of openmods and randompatches is removed?

**Comment by Zer0Lyfe** [comment]
Yeah it does but in a pack with just mekanism and advanced rocketry it crashes but mekanism does have coremod though so i don't know why.

**Comment by Zer0Lyfe** [comment]
and i had tested in 14.23.2.2641 and 14.23.2.2653  and only 2641 worked.

**Comment by zmaster587** [comment]
Build 1.12.2-14.23.2.2642:
	bs2609: Fix entities sometimes not rendering when out-of-world (#4823)

The ASM in AR that's crashing does exactly this, so I think it highly likely that a change to forge is why this is happening now when it wasn't before.  I'll look into patching AR so it works with the new builds, or rather unpatching AR since forge may fix the issue the patch in AR was intended to fix for previous builds of forge.

**Comment by PWaksman** [comment]
I got the same error, I have post a thread in the Forge forum to see if any one can help with this.

http://www.minecraftforge.net/forum/topic/63838-inconsistent-stackmap-frames-at-branch-target-914/

**Comment by zmaster587** [comment]
It's an AR issue, I just need to get around to fixing it for the latest builds of forge

**Comment by HiggsBonbon** [comment]
Literally just ran into this issue, good to see you're right on top of it.

**Comment by SzymonSwistun94** [comment]
Same crash, https://ptpb.pw/90f3
Even with just Advanced Rocketry, LibVulpes and a mod I'm working on (client launched via gradle, my mod is working with other problems without issues).

**Comment by 88880** [comment]
Hello. So should we just wait for the next release of AR or do we need to do something

**Comment by smurfyjay** [comment]
https://hastebin.com/wihekalini.go i am receiving a crash also same problem on the latest forge with advanced rocketry just posting report if it is any help to you love the mod and cant wait to start using it again

**Comment by zmaster587** [comment]
@8880 You can wait for the next release or you can use a build of forge prior to 1.12.2-14.23.2.2642.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.4.0.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1882297/AdvancedRocketry-1.12.2-1.4.0.jar.zip)
For those experiencing this issue, can somebody let me know if this build fixes the problem?

**Comment by Zer0Lyfe** [comment]
Does Work :D

**Comment by zmaster587** [comment]
@Zer0Lyfe Thanks!  good to know.  It should be slated for the next build on curse.
