### ISSUE TITLE
Space Elevator won't let me select valid destination.

### ISSUE THREAD

**Issue by AlbinoBlackHawk** [zmaster587/AdvancedRocketry#1238]
## Version of Advanced Rocketry
1.10.2-1.2.5a
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.10.2-0.2.6
## Version of Minecraft
1.10.2

## Description of the problem
So I'm trying to get a space elevator up and running between my rftools dimension (ID 23) and my space station (ID -2), which I launched from the aforementioned rftools dimension. I built my space elevator both on the space station and in my dimension. I was able to link and power them successfully, a green destination even pops up at both ends. As seen below:
![image](https://user-images.githubusercontent.com/13131343/38355644-e63888da-3900-11e8-8dd4-52b6bd91212f.png)
However, it won't actually let me select the destination, clicking it does nothing. I tried re-establishing the link, clearing the space above each space elevator in case that was required, and have double checked that both are powered, on, and chunk loaded.

Also, I'm playing All The Mods Modpack (v4.2) on a server.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by JoshuaWright42** [comment]
I haven't played this modpack in a while, but the issue was never resolved while I was playing.

**Comment by flyingyalie** [comment]
I am also having this same issue on the most recent build.
