### ISSUE TITLE
IFluidItem recipe compatibility

### ISSUE THREAD

**Issue by DarkGuardsman** [zmaster587/AdvancedRocketry#124]
Dragonlord requested that the wooden buckets should be able to be used in some recipes. Since I do not want to code support for a large mod in a small mod, the better solution is to support IFluidItem api from forge.

**Comment by zmaster587** [comment]
It should already work with any item registered in the FluidContainerRegistry

**Comment by DarkGuardsman** [comment]
that doesn't support NBT items which the bucket is, hence the need for the API usage

**Comment by DarkGuardsman** [comment]
Ty I'll test it when you make your next release to ensure it works 100%
