### ISSUE TITLE
No hovermode button for jetpack

### ISSUE THREAD

**Issue by 88880** [zmaster587/AdvancedRocketry#1241]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-27-universal
## Version of Minecraft
1.12.2
## Description of the problem
Hello. There doesn't seem to be a button for jetpack hovermode in the controls. I cannot toggle hovermode. Am I missing something obvious? Thanks :)

**Comment by zmaster587** [comment]
Shift toggle button, should be shift X by default.

**Comment by Bufhimat** [comment]
For the folks searching for this later

Toggling hover mode is sneak + jetpack toggle
