### ISSUE TITLE
[1.12.2] Forge energy Crash

### ISSUE THREAD

**Issue by YOYOK9** [zmaster587/AdvancedRocketry#1244]
## Version of Advanced Rocketry
1.12.2-1.4.0-73
## Have you verified this is an issue in the latest unstable build
Y 
## Version of LibVulpes
1.12.2-0.2.8-29-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/aqYX0RwJ
## Description of the problem
1) went to the moon with /advrocketry goto 2
2) built a small sealed box (iron blocks + glass blocks)
3) placed an oxygen vent in the box
4) went to place A.R. energy cable 
then crash. 

Extra info:
only AR and libVulpes are installed. Have tried with thermal mods[before this] as well for alternate power source and still crashes with AR cables. Placing the create power plug from A.R. crashes as well. 

Edit: Works with Forge version: 1.12.2 - 14.23.2.2654
Forge version: 1.12.2 - 14.3.2657 breaks it

**Comment by zmaster587** [comment]
There was a flurry of builds after 2657, which indicates to me something may have been broken.  I tested it with the latest built (2661) and im not experiencing any problems when performing the steps you provided.  Can you confirm whether or not this continues in forge 2661?

**Comment by zmaster587** [comment]
did you by any change connect it to an AR fluid tank?  or was it only the vent?  in reference to #1245
