### ISSUE TITLE
Entity ID for Space Elevator Capsule?

### ISSUE THREAD

**Issue by AlbinoBlackHawk** [zmaster587/AdvancedRocketry#1246]
Hey, just using a version of advanced rocketry which predates the capsules getting stuck in the sky fix. I'm trying to navigate the issue with the command /kill @e[type=<entity>], but I can't seem to get the entity name/id right. I've tried different combinations of the words space, elevator, capsule and entity. Also tried "ARSpaceElevatorCapsule" which I found in the mod's code. Wondering what ID/Name is the correct one to use with this command?

**Comment by zmaster587** [comment]
ARSpaceElevatorCapsule would be the name.  It might show up as advancedrocketry.ARSpaceElevatorCapsule too.  The entity ID itself is determined by the game at runtime and changes based on what other entities are added by other mods.  That you might be able to find by digging through the level.dat

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by JoshuaWright42** [comment]
I believe this issue was addressed in a later version of the mod.
