### ISSUE TITLE
Guidance Computer not showing up in GUI

### ISSUE THREAD

**Issue by tonicsense** [zmaster587/AdvancedRocketry#1247]
## Version of Advanced Rocketry
AdvancedRocketry-1.10.2-1.4.0-8
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.10.2-0.2.8-8-universal
## Version of Minecraft
Minecraft 1.10.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
No crash occured.

## Description of the problem
I tried building a rocket with a Guidance computer BUT the Guidance computer doesnt show up in the GUI 
![2018-04-15_18 28 46](https://user-images.githubusercontent.com/29627970/38780703-1b181da4-40db-11e8-9acd-de7cdb2db2ba.png)
![2018-04-15_18 28 48](https://user-images.githubusercontent.com/29627970/38780704-1b43e1f0-40db-11e8-9a5b-93f816f13fb6.png)

The screenshot with the flatland behind is without modifications and 
the one with the quartz n stuff is with 18 other mods. So i made sure that the mods are not the problem. ![2018-04-15_18 25 23](https://user-images.githubusercontent.com/29627970/38780651-6c4b1fd8-40da-11e8-94db-5f5904ebd6a0.png)
![2018-04-15_18 25 18](https://user-images.githubusercontent.com/29627970/38780658-7a03aabe-40da-11e8-8437-026f26d197fa.png)

I am sorry if this is false alarm and i missed something but i just wanted to make sure and show this to you.

**Comment by tonicsense** [comment]
NOTE: Travelling to another planet/spacestation works if you place a chip in before you build the rocket. Once again. dont know if i missed an update or anything

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Revemohl** [comment]
Just a heads-up in case this is still happening, I seem to have gotten this fixed on my personal fork by reverting 44464bf.

**Comment by dmodoomsirius** [comment]
Why not find a fix as well and submit a pull request? I know we would appreciate it.

**Comment by coolman9902** [comment]
> 
> 
> Just a heads-up in case this is still happening, I seem to have gotten this fixed on my personal fork by reverting [44464bf](https://github.com/zmaster587/AdvancedRocketry/commit/44464bf4a0ae5478dfcde7aae8677203bdf4834e).

Any way to get a copy of the fork i tried reverting it myself but cant get it to work
