### ISSUE TITLE
Satellites seem to "fall out of the sky" after a single-player world reload.

### ISSUE THREAD

**Issue by AmandaCameron** [zmaster587/AdvancedRocketry#1248]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-74
## Have you verified this is an issue in the latest unstable build
N?
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-29-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
Nothing is logged from this mod on world unload, or load.

## Description of the problem
It seems whenever I save and exit my single-player world, then go back in, all my satellites have "fallen out of the sky" -- when I look at the Satellite Trackers with their chips loaded in, they all say "No link..." and so I can't get any additional data out of them.

**Comment by robbcrg** [comment]
I believe this may is also happening to multiple player and satellite microwave transmitters. Launch satellite, confirm MW receiver is working; shows power and visual effects. Do this as often as needed - no problem. Restart server - MW shows 0 power, there is no special visual effects and output plugs slowly draining (indicating power is not just invisible).

**Comment by Landstryder** [comment]
Also having the same issue on my server

AR- 1.12.2-1.4.0-80
LibVulpes- 1.12.2-0.2.8-31
Forge- 14.23.3.2679

Satellite Terminals just started saying no link even tho the ID chip shows all the proper info still. They worked fine for a day or 2 after creation but then just was not working the next time I logged in.

**Comment by FoxBotGames** [comment]
Can confirm issue with SP and MP. 

AR- 1.12.2-1.4.0-80
LibVulpes- 1.12.2-0.2.8-31
Forge- 14.23.3.2679

After closing SP world the rockets fall out of orbit and land randomly upon loaded chunks, upon server restart same result.

**Comment by gdarai** [comment]
The same is happening on 1.10.2 Single World all satellites says No Link after save and load.
Version is current newest alpha:

AR- 1.10.2-1.4.0.12
LibVulpes- 1.10.2-0.2.8.37
Forge- 12.18.3.2511

No other mods installed

**Comment by zmaster587** [comment]
fixed in next build
