### ISSUE TITLE
Server Crashing with AdvancedRocketry

### ISSUE THREAD

**Issue by SpaceRiceBowl** [zmaster587/AdvancedRocketry#1249]
## Version of Advanced Rocketry
1.4.0-65
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
0.2.8-27
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/fTBX28Ad

## Description of the problem
Crashes towards the end of booting up a server. Not exactly what causes it, but the logs say there's a problem with Advanced Rocketry.

**Comment by zmaster587** [comment]
Can you provide the planet configuration?

**Comment by SpaceRiceBowl** [comment]
Where would I find those two files?

**Comment by dmodoomsirius** [comment]
the advRocketryFolder in your worlds folder.

**Comment by SpaceRiceBowl** [comment]
Would I have to upload the, xml file? Cause I do not see anything for me to copy down in notepad.

**Comment by dmodoomsirius** [comment]
Either upload it to a gist.github.com gist or a pastebin or something to that effect

**Comment by SpaceRiceBowl** [comment]
Ah, I can't physically open it. It says the class is not registered.

**Comment by zmaster587** [comment]
can you put it into a zip file and upload the zip to github by dragging it into the textbox where you enter your response?

**Comment by SpaceRiceBowl** [comment]
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/1930137/planetDefs.zip)

**Comment by ErdbeerbaerLP** [comment]
Notepad++ shows many of "nul"

![image](https://user-images.githubusercontent.com/27149563/39052467-57641158-44ac-11e8-938c-11dab14fdfc4.png)

**Comment by dmodoomsirius** [comment]
you can not open a .dat file in note pad you need something like NBTExplorer.

**Comment by SpaceRiceBowl** [comment]
So would this mean I have a corrupt world?

**Comment by NillerMedDild** [comment]
This issue and similar corruption issues with the `planetDefs.xml` can (and often will) occur if a server or SP world is shut down incorrectly.

**Comment by zmaster587** [comment]
I've added a sync call, so these kind of corruptions should no longer occur
