### ISSUE TITLE
UI config recommendations

### ISSUE THREAD

**Issue by Rightfuldeathray** [zmaster587/AdvancedRocketry#1250]
It appears that in config files you can move the armor ui overlay for the space suit, you seamed to make this possible since issue 379. With the ui lock set to false in the config I cannot move the ui while having chat open with middle click, I don't know if another mod I'm running is preventing me from doing this.

Having a button that opens a configuration screen in the suit workstation to change the location and scale of the ui's would make a lot of sense to me, since one needs the workstation to get any real use out of the suit, additionally an option to disable the armor ui overlay would be nice since it only tells you what's in your suit, which can be checked through a mouse over of the items, and jet pack state, which could be separate.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
