### ISSUE TITLE
Issues with going from planet to space station and vise versa

### ISSUE THREAD

**Issue by Tritanium** [zmaster587/AdvancedRocketry#1252]
## Version of Advanced Rocketry
1.7.10-1.4.0-8
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.7.10-0.2.8-31
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
1st issue
https://pastebin.com/TagT0C9S
2nd issue
https://pastebin.com/usGGQGd9
## Description of the problem
1st issue
Started when I started using multiple landing pads on my station. Whenever I try landing on the station I get disconnected and get "A fatal error has occurred, this connection is terminated". Only able to go back on if someone on the server removes the landing pads.
2nd issue
landing on any non earth like planet (except moon) crashes server every time the player that entered the planet joins the game (had to edit player files to get them out of the dimension). I disabled villages and generated new planets and am able to land on most planets. still can't land on the desert looking ones.

**Comment by zmaster587** [comment]
Does issue 2 occur with dragonAPI removed?

**Comment by Tritanium** [comment]
doesn't occur without dragon api, rotarycraft, reactorcraft. Is there a way to get them working together then? rotarycraft and advanced rocketry are the main mods the modpack is based around

**Comment by Tritanium** [comment]
I'm guessing it's to do with the geodes on the red planets?

**Comment by zmaster587** [comment]
Geodes generally occur on any planet with high pressure ( greater than 1.25 atm density), though the red planets also generally have high pressure.  But yeah, it looks like during generation it's triggering an event in rotatarycraft to trigger terrain generation and creates an infinite loop (or rather loops until it runs out of stack space and crashes).  one workaround for now is you could just set the atm density on those planets lower.

It looks to have to do with setting the meta data during chunk creation though.

**Comment by Tritanium** [comment]
so if i were to generate those planets without rotorycraft (load all the chunks etc) by moving the dim files to a separate world. then place the dim file back into the modpack with rotorycraft, would that fix it?

**Comment by zmaster587** [comment]
That could work too, you'd just need to take care not to generate new chunks while rotatrycraft is in there until a better solution can be found

**Comment by Tritanium** [comment]
Thanks! first issue is fixed. finally can join the server now

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
