### ISSUE TITLE
NO SLOT IN Guidance Computer for chip.

### ISSUE THREAD

**Issue by RedStoneMaster01** [zmaster587/AdvancedRocketry#1253]
## Version of Advanced Rocketry
[AdvancedRocketry-1.11.2-1.4.0-89]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[LibVulpes-1.11.2-0.2.8-36-universal]
## Version of Minecraft
[Forge-1-11-2]
w/ [liteloader 1.11.2]

## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[N/A]

## Description of the problem
Build and fuel the rocket. There is not slot in the Computer Guidance for the programmed planet/(des.) chip.

**Comment by zmaster587** [comment]
Backported bugfix for 1.12 to prevent duplicate entries apparently is not required for 1.11

**Comment by RedStoneMaster01** [comment]
File not updated? Revision 1.4.0-89  us still no good.
