### ISSUE TITLE
Remote Rocket machines losing connection

### ISSUE THREAD

**Issue by TotalHamman** [zmaster587/AdvancedRocketry#1256]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0.

## Have you verified this is an issue in the latest unstable build
Unsure, using build from Discord posted April 14 at 1:50 AM CDT

## Version of LibVulpes
 LibVulpes-1.12.2-0.2.8-29

## Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

## Crash report or log (if applicable)
No Crash

## Description of the problem
Multiple machines such as the Guidance Computer Access Hatch, Fueling Station, Rocket Unloader, etc are losing their link to the rocket if sent to a planet or on an Asteroid mission.  This necessitates a manual re-connection to fuel / load / unload the rocket after every mission.

**Comment by TotalHamman** [comment]
When I logged this it was with linking to Rocket only.  I can test Assembler real quick.  

This also happens to unmanned rockets when linked to either rocket or the assembler.

**Comment by zmaster587** [comment]
This would be expected when linking to the rocket.  Linking to the rocket is a "one time" link, whereas linking to the rocket assembler is designed to persist since you're basically linking to the ground station that handles any rocket landing or taking off from that pad.

I tested it whith linking to the unmanned assembler and ran a gas mining mission about 20 minutes ago.  Came back fine, linked properly, and I was able to send it off without needing to do more than put some extra fuel in the fueling station and wait for the fluid to drain.

**Comment by zmaster587** [comment]
I did find an issue where if the a gas mining mission is started and the space world unloads, (or if you close and reopen the game) the infrustructure is only half connected (blocks are registered with the rocket, but the rocket does not register itself with the blocks) which results in it appearing unconnected.  This is only true for the unmanned rockets though, the unmanned rocket was missing a registration step that was not copied from the base rocket class.

**Comment by Landstryder** [comment]
I'm also having this issues with Asteroid Mining rockets on my server.

AR- 1.12.2-1.4.0-80
LibVulpes- 1.12.2-0.2.8-31
Forge- 14.23.3.2679

Linking Fueling Station, Rocket Unloader and Guidance Computer Hatch to the Rocket Assembly Machine... every launch when it comes back it's unlinked. Having them linked before building the rocket does not link them once it's built either. Tried Linking with the rocket on the pad... unlinked when returned. Tried re-linking the while the rocket was in space on the asteroid mission... unlinked when returned. 

I have had them link and stay linked once for a series of missions by some luck, but soon as I left the server and came back they were back the unlinking problem.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
