### ISSUE TITLE
Lost unmanned rocket / crash when mission completed

### ISSUE THREAD

**Issue by TotalHamman** [zmaster587/AdvancedRocketry#1257]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0.

## Have you verified this is an issue in the latest unstable build
Unsure, using build from Discord posted April 14 at 1:50 AM CDT

## Version of LibVulpes
 LibVulpes-1.12.2-0.2.8-29

## Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

## Crash report or log (if applicable)
https://pastebin.com/5sDNEVXf

## Description of the problem
Had a gas mission that was finishing shortly and went to the overworld.  The station is not chunkloaded at all.  Game randomly crashed and based on the crash-log it appears that it tried to complete the mission and land the rocket but failed with the chunks not loaded.

After relaunching the game, the rocket is nowhere to be found.

**Comment by zmaster587** [comment]
fixed for next update
