### ISSUE TITLE
Excessive update calls to AtmosphereHandler by Flux Network

### ISSUE THREAD

**Issue by TotalHamman** [zmaster587/AdvancedRocketry#1258]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-73

## Have you verified this is an issue in the latest unstable build
Have not verified at this time.

## Version of LibVulpes
 LibVulpes-1.12.2-0.2.8-29

## Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

## Crash report or log (if applicable)
No Crash

## Description of the problem
Logging this here first to let you weigh in on if this is something resolvable on your end or needs to be logged with Flux Networks.

One of the players on the server was using Flux Networks for wireless power transfer to his Space Station.  Several of the Flux Points were in unloaded chunks and whenever a player was not at the space station, there was significant tick lag spiking.  Some plugs were in rooms with an Oxygen Vent, others were not.  As soon as the chunks were all loaded, lag spikes disappeared regardless of player location / status on the server.

Attaching several Sampler mod spike nps files to assist in the investigation.  

[sampler-output.zip](https://github.com/zmaster587/AdvancedRocketry/files/1926127/sampler-output.zip)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
