### ISSUE TITLE
Unmanned rocket has to be Disassembled and Built between each mission.

### ISSUE THREAD

**Issue by TotalHamman** [zmaster587/AdvancedRocketry#1260]
Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0.75

Have you verified this is an issue in the latest unstable build
Yes

Version of LibVulpes
LibVulpes-1.12.2-0.2.8-29

Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

Crash report or log (if applicable)
No Crash

Description of the problem
Unmanned rocket has to be Disassembled and Built between each mission.  Additionally have to relink Unloader / Fueling Station after the mission to unload before rebuilding the rocket.

After the relink, the rocket fuels properly and unloads fluids properly.  However the Launch button in the Monitoring Station does nothing.

**Comment by TotalHamman** [comment]
Persists between world loads

**Comment by zmaster587** [comment]
Cannot replicate

**Comment by TotalHamman** [comment]
This is on Single Player world, custom pack.  However it may be occurring because I am building the rocket using Vanilla Structure block and then scan / build.

**Comment by zmaster587** [comment]
building the rocket with Vanilla structure block?

**Comment by TotalHamman** [comment]
1.12 adds a structure system ala Buildcraft Blueprints that in creative allows you to rebuild any saved structure preserving all TileEntity data as well.

**Comment by zmaster587** [comment]
is the space dimension being unloaded at any point during a mission?

**Comment by TotalHamman** [comment]
Space is not being unloaded during.  And I have that modifier set to 0.01 in both the pack and now the only AR / Vulpes test.  Unable to recreate in the test world.  Creating a new rocket in the pack manually and will retest.

**Comment by TotalHamman** [comment]
Unable to reproduce after building the station / unmanned rocket launcher manually.  Looks like this issue is fully the blame of using a Structure to build the Station / Rockets.
