### ISSUE TITLE
Two slots in Artifacts Section of Warp Controller are Mirrored

### ISSUE THREAD

**Issue by TotalHamman** [zmaster587/AdvancedRocketry#1261]
Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0.75

Have you verified this is an issue in the latest unstable build
Yes

Version of LibVulpes
LibVulpes-1.12.2-0.2.8-29

Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

Crash report or log (if applicable)
No Crash

Description of the problem
![image](https://user-images.githubusercontent.com/543169/38975571-f856ab32-4373-11e8-87b3-22b2a93ed095.png)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
