### ISSUE TITLE
Orbital Laser causes extreme lag. Constant timed outs

### ISSUE THREAD

**Issue by Tritanium** [zmaster587/AdvancedRocketry#1262]
## Version of Advanced Rocketry
1.7.10-1.4.0-9
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.7.10-0.2.8-31
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
https://pastebin.com/LcJ5gStm

## Description of the problem
Turned on orbital laser and landed on the planet it was mining. Constantly rubber banded while landing. then timed out. now whenever someone loads the orbital laser chunk on the station, it timed out everyone.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
