### ISSUE TITLE
Dilithium Ore in SAG Mill only outputs stone

### ISSUE THREAD

**Issue by ProxyPlayerHD** [zmaster587/AdvancedRocketry#1264]
AR: 1.4.0-77
Forge: 14.23.3.2669
EIO: 5.0.22

![javaw_2018-04-23_16-10-30](https://user-images.githubusercontent.com/13576843/39131987-11863938-4711-11e8-8532-9e8ac69be76d.png)
for some reason the SAG Mill's output of Dilithium ore is just stone. not even all the time, it is a 15% chance to output stone.

all other machines that grind/smelt work fine with the ore.

**Comment by tyler489** [comment]
This is on enderios end

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
