### ISSUE TITLE
Unable to build space station

### ISSUE THREAD

**Issue by TotalHamman** [zmaster587/AdvancedRocketry#1265]
Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0.77

Have you verified this is an issue in the latest unstable build
Yes

Version of LibVulpes
LibVulpes-1.12.2-0.2.8-29

Version of Minecraft
1.12.2 - forge-1.12.2-14.23.2.2654

Crash report or log (if applicable)
No Crash

Description of the problem
Clicking Scan when there everything is present does nothing.  Clicking Build deletes the Satellite Bay and Station ID Chip with no RF usage.  

Gif of Structure:  
https://gyazo.com/b6da23ab9f99a103efa535e880841463

Gif of Issue Replication:  
https://gyazo.com/c4e94d6e62c9523c526a034602190c7a

**Comment by bonnedav** [comment]
I have the same issue. has never worked for me.

**Comment by zmaster587** [comment]
does this occur in single player and on server?  Or just one or the other?

**Comment by bonnedav** [comment]
Any progress?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
