### ISSUE TITLE
Gravity machine  NOT building or working

### ISSUE THREAD

**Issue by RedStoneMaster01** [zmaster587/AdvancedRocketry#1268]
## Version of Advanced Rocketry
[AdvancedRocketry-1.11.2-1.4.0-90]
[insert here]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[LibVulpes-1.11.2-0.2.8-36-universal]
## Version of Minecraft
[1.11.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[N/A]

## Description of the problem
[Build the Gravity machine on the moon. Does not build or work.
![2018-04-24_08 00 40](https://user-images.githubusercontent.com/38401044/39190343-09fa27cc-479a-11e8-9f7d-2761f7d5ab2b.png)
![2018-04-24_08 00 34](https://user-images.githubusercontent.com/38401044/39190362-128c44e2-479a-11e8-8a53-18cceb32d01a.png)
![2018-04-24_08 00 21](https://user-images.githubusercontent.com/38401044/39190379-18c2b940-479a-11e8-81a4-bcde322b442c.png)

]

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
