### ISSUE TITLE
Client crashes when launching rocket from a space station

### ISSUE THREAD

**Issue by Aardonyx9** [zmaster587/AdvancedRocketry#1269]
## Version of Advanced Rocketry
1.4.0.-67
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-27
## Version of Minecraft
1.12.2 (FTB Revelations Modpack)
## Crash report or log (if applicable)
https://pastebin.com/6d7pX9pT

## Description of the problem
I know it's kind of shitty of me to drag an outdated version into this, but since it's what's public in the FTB Revelations modpack I imagine I'm not the only person who will be dealing with this issue. Maybe it's a simple fix on my end.
Anyway, whenever I launch my rocket from my space station to come back to Earth, the game crashes the INSTANT I press the space bar to launch. This is reproducible; it happened to me twice in a row and even happened to somebody else on my dedicated server. So far nobody on my server has managed to launch from a space station without crashing the game. When I log back in, the I'm still in the rocket, which is in motion, and I do land back on earth, but not where I left from. It's only the client that crashes, the server goes on like nothing happened. I can go to and from planets with no issue, I can even go TO a space station no problem. It's just leaving a space station that causes this. The crash log is in the pastebin.

**Comment by Aardonyx9** [comment]
Alright I figured out the issue a little more specifically.
This only happens if I touch the chip that's placed in the Guidance Computer before leaving, rather than just leaving the station 1 chip in. I'll play around with it a little more and report findings.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
