### ISSUE TITLE
Game starts to freeze while starting rocket unmanned

### ISSUE THREAD

**Issue by Golgroth** [zmaster587/AdvancedRocketry#1270]
## Version of Advanced Rocketry
1.4.0-10
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-8
## Version of Minecraft
1.10.2
## Crash report or log (if applicable)
https://hastebin.com/ojatiwizet.log

## Description of the problem
When launching a rocket and leaving it with SHIFT, then it starts to freeze game while rockets changes dimension (eg. from Moon to Earth).

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
