### ISSUE TITLE
Client crashes when accessing chest on rockets

### ISSUE THREAD

**Issue by beamer91** [zmaster587/AdvancedRocketry#1272]
## Version of Advanced Rocketry
1.4.0-78
## Have you verified this is an issue in the latest unstable build
No
## Version of LibVulpes
0.2.8-29
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://paste.ee/p/xLpar
## Description of the problem
any time i build a rocket with a chest and shift right click it to get to it gui if I then click on a square for the chest my client crashes. I have tried it with a vanilla chest and a diamond chest form Iron Chest.

**Comment by golyalpha** [comment]
The latest unstable build doesn't have the chests crash the client, but the GUI closes as soon as the chest is opened.

**Comment by zmaster587** [comment]
The chest opening issue is known, some of the ASM is broken and is unfortunately a bit hard to fix.
#1407
