### ISSUE TITLE
Rocket not able to find a destination 

### ISSUE THREAD

**Issue by 016Nojr** [zmaster587/AdvancedRocketry#1274]
## Version of Advanced Rocketry
1.4.0-77
## Have you verified this is an issue in the latest unstable build
No
## Version of LibVulpes
0.2.8-29
## Version of Minecraft
1.12.2
## Crash report
https://pastebin.com/N3F52mhr

## Description of the problem
Create a space station, place a docking pad. Make a rocket in the overworld, launch it to the docking pad, send it back. Then break the docking pad and remove the blocks were the rocket landed the first time. When you launch the rocket next time (In this case it was unmanned) it crashes the server.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
