### ISSUE TITLE
Game crashed after updated Libvulpes

### ISSUE THREAD

**Issue by FuYang001** [zmaster587/AdvancedRocketry#1276]
## Version of Advanced Rocketry
1.7.10-1.4.0-11
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.7.10-0.2.8-32
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
https://pastebin.com/m6Xuw5z2

## Description of the problem
After updated Libvulpes game crashed when entering world.

**Comment by zmaster587** [comment]
Gregtech ore support was added in AdvancedRocktry-1.4.0-12, this required an update to libvulpes as well, it looks like you've updated libvulpes but not advanced rocketry.

You should be able to fix this by downgrading to an older version of libvulpes or AdvancedRocktry-1.4.0-12 or newer

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
