### ISSUE TITLE
Wireless Transcievers are either broken or overly confusing to use

### ISSUE THREAD

**Issue by aaronhowser1** [zmaster587/AdvancedRocketry#1279]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-79
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-30-universal
## Version of Minecraft
1.12.2

## Description of the problem
I have [260 Dist Data](https://i.imgur.com/VAEsiao.png) before connecting to [this](https://i.imgur.com/sMYn61y.png) Satellite Terminal. After connecting them with Wireless Transceivers I have [299](https://i.imgur.com/t2Nbcmz.png), so that's working. However, when I try the same with Mass [(starting with 55](https://i.imgur.com/7TP6hrH.png)), it doesn't change. [I linked the further one on the left with the one of the back of the Warp Core on the right](https://i.imgur.com/j4zw190.png), the Sat Terminal is [on with extract enabled](https://i.imgur.com/cSZYfkc.png) and the Warp Core is [on with extract disabled](https://i.imgur.com/ReuzYfm.png). Mass Data *is* being removed from the [Sat Terminal](https://i.imgur.com/rWhJ0cf.png), but it isn't going into the Warp Core. The same happens when I try with the [Composition Data](https://i.imgur.com/BfFMKMV.png), set up like the other two. Am I doing something wrong?

**Comment by aaronhowser1** [comment]
There's also a smaller issue where they have a full bounding box, pushing you out of the block that they're in if you try to walk into them instead of being flat or having a smaller bounding box that matches the model.

**Comment by zmaster587** [comment]
If you log out and log back in, do the numbers change?

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.4.0.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1973196/AdvancedRocketry-1.12.2-1.4.0.jar.zip)
Can you use this build and see if you run into the same issues if you create the setup from scrach?

**Comment by aaronhowser1** [comment]
I tried launching without changing any other mod and crashed on startup, [here's the log](https://pastebin.com/nkFHVfQ8)

**Comment by aaronhowser1** [comment]
Oh sorry, that crash was a graphics card problem. Do you want me to try again with that version?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
