### ISSUE TITLE
[1.12.2] Tank of Rocket Fuel unobtainable

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1282]
## Version of Advanced Rocketry
1.12.2-1.4.0-80
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[insert here]
1.12.2-0.2.8-30-universal
[insert here]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
[How can you reliably reproduce the problem]
Water + Hydrogen in the Chemical Reactor produces Rocket Fuel, however it cannot be put into buckets, nor made into Tanks of Rocket Fuel - atleast I'm unable to.

Steps to reproduce:
1. Build a Chemical Reactor, and supply it with energy, water and hydrogen (turn it on aswell=
2. Try to take the rocket fuel out with a bucket
3. No result

**Comment by Snownee** [comment]
Can confirm this issue

**Comment by AtlasRiker** [comment]
Also can confirm the inability to tank rocket fuel as well as oxygen and hydrogen

**Comment by dmodoomsirius** [comment]
This is not the latest unstable build. https://minecraft.curseforge.com/projects/advanced-rocketry/files/2676571

**Comment by NillerMedDild** [comment]
Ofcourse not, the issue is from May 2018.

**Comment by MrEyeballs29** [comment]
Close this issue because it is longer than 8 months.

**Comment by cooljackgi** [comment]
its still there...
