### ISSUE TITLE
can't ride rocket or access guidance computer 1.7.10

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#1283]
## Version of Advanced Rocketry
AdvancedRocketry-1.7.10-1.4.0-16
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.7.10-0.2.8-33-universal
## Version of Minecraft
1.7.10

## Description of the problem

Hello,
i have a double issue but maybe they are linked.
I upgraded advanced rocketry from 1.2 to 1.4.
I was able to mount on my rocket seat but something seemed strange. So i went down and try to access my guidance computer to check my moon chip. Impossible to access it like issue 1247.
Then i disassembled my rocket, there i can see my chip. I reassembled my rocket. No guidance computer access again. But worst i'm able to mount on my rocket seat anymore....

**Comment by choum33** [comment]
Ok, i dismonted totally the rocket and rebuilt it. So i can select moon, so there without any issue.
When i want to go back to earth, as i can't access to the chip, i select earth as destination and launch the rocket. It begin to consume fuel but rocket is not mooving... And i can take damage from nearby monsters, where is should not ....

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
