### ISSUE TITLE
lost connection to my satellites 1.7.10

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#1284]
## Have you verified this is an issue in the latest unstable build
AdvancedRocketry-1.7.10-1.4.0-16
## Version of LibVulpes
LibVulpes-1.7.10-0.2.8-33-universal
## Version of Minecraft
1.7.10

## Description of the problem
Hello After upgrade from advanced rocketry 1.2 to 1.4 my satellites terminals displays "no link". and the connect button doesn't change anything ... satellite chip is inserted, and all worked fine before the upgrade.
![minecraft 1 7 10](https://user-images.githubusercontent.com/16777906/39665910-ad0f0fd6-509b-11e8-8f82-9dbb76f15967.jpg)
![prtscr capture](https://user-images.githubusercontent.com/16777906/39665911-ad338b2c-509b-11e8-9092-9c2022500c29.jpg)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
