### ISSUE TITLE
Microwave Transmitter is not formed with RF inpud plug

### ISSUE THREAD

**Issue by demycat** [zmaster587/AdvancedRocketry#1285]
## Version of Advanced Rocketry
1.4.0-16
## Version of LibVulpes
0.2.8-33
## Version of Minecraft
1.7.10

## Description of the problem
When I wanted to build a Microwave Transmitter, it was not configured with the RF inpud plug
![2018-05-08_13 49 22](https://user-images.githubusercontent.com/34833284/39753523-cf0598fc-52c7-11e8-8382-d89f05d17735.png)
![2018-05-08_13 49 39](https://user-images.githubusercontent.com/34833284/39753524-cfe375aa-52c7-11e8-8422-ba83944965aa.png)

**Comment by zmaster587** [comment]
For those that might read this in the future, it does not accept an RF input plug, only output plugs since it doesn't use energy, it only creates energy.
