### ISSUE TITLE
BoP Biome ID conflict 1.7.10

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [zmaster587/AdvancedRocketry#1286]
## Version of Advanced Rocketry
1.4.0-15
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-33
## Version of Minecraft
1.7.10

## Description of the problem
BoP uses biome IDs up to 122 and this includes AR biomes by default.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
