### ISSUE TITLE
[1.7.10] Taint gen

### ISSUE THREAD

**Issue by Shurik1236** [zmaster587/AdvancedRocketry#1287]
## Version of Advanced Rocketry
1.7.10-1.4.0-16\1.7.10-1.4.0-8
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.7.10-0.2.8-34\1.7.10-0.2.8-31
## Version of Minecraft
1.7.10

ID биома не указан, но он появился.
Добавление в S:BlacklistedBiomes не помогает.
(Google)
The biome ID is not specified, but it appeared.
Adding to S: BlacklistedBiomes does not help.
planetDefs:
https://pastebin.com/eVHmVbz8
![2018-05-10_14 18 56](https://user-images.githubusercontent.com/17496452/39857590-0f0f7bd8-545e-11e8-80da-99eb1a2596c0.png)

**Comment by C1ffisme** [comment]
Out of curiosity, does this happen in the End or Nether?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
