### ISSUE TITLE
[Enhancement] Scan warp signatures

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1288]
In star trek it is possible to trace down a ship by following its warp signature. I think it would be possible to implement it in the mod somehow, but I don't know how exactly. Its just an idea.

Maybe a block that shows the ships that moved from and to the planet the ship is currently orbiting around.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
