### ISSUE TITLE
Crash When Exiting Rocket on a Newly Created Space Station

### ISSUE THREAD

**Issue by FoxBotGames** [zmaster587/AdvancedRocketry#1289]
## Version of Advanced Rocketry
1.4.0-80
## Have you verified this is an issue in the latest unstable build
What?
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/msM40vqg
## Description of the problem
Create space station, place in satellite bay and place station card in guidance computer, launch, land on station, attempt to exit rocket, crash (NOT TESTED IF REPEATABLE)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
