### ISSUE TITLE
[Suggestion] Holo-projektor blocks destroying grass

### ISSUE THREAD

**Issue by 456Xander** [zmaster587/AdvancedRocketry#129]
I noticed that the blocks the holo projector creates will not destroy grass, and so the structure is incomplete if there is grass on the floor.

**Comment by zmaster587** [comment]
The idea is that it is a hologram so would be blocked by grass/etc.  However I admit it is kindof annoying.  If it's not too much of a pain I'll look into changing that.  No garuntees though.
