### ISSUE TITLE
Holo-Projector Scrolling Issue

### ISSUE THREAD

**Issue by FoxBotGames** [zmaster587/AdvancedRocketry#1290]
## Version of Advanced Rocketry
1.4.0-80
## Have you verified this is an issue in the latest unstable build
What?
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
Not Applicable
## Description of the problem
Can not use scroll wheel when using the holo-projector, have to middle click and move that way.
(Many mods added as in creating modpack, find us at github.com/grimco modpack is CoopLife2)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by kdx7214** [comment]
This is still happening as of 1.5.0-128

**Comment by MrEyeballs29** [comment]
Then reopen

**Comment by kdx7214** [comment]
If I knew how to do that I would have done it.

**Comment by zmaster587** [comment]
Do you have a configurable mouse, any kind of software for it running?  Have you tried scrolling in both directions?  Does this occur with only libvulpes and AR?  What version of Java are you running?

**Comment by MrEyeballs29** [comment]
And also forge version and mc version too.

**Comment by Silfryi** [comment]
Remove MouseTweaks if you have it. This is mostly a MouseTweaks issue from what I remember, they change something about the scrollwheel that makes it stop working, I think.

**Comment by MrEyeballs29** [comment]
Then close there is nothing related to this.

**Comment by Silfryi** [comment]
Don’t have those permissions, sorry. I help out as much as I can, though.

**Comment by Silfryi** [comment]
People other than the owner can be be given contributing/collaborating permissions, Cl1ff and Dmod are the two I know of, they could close as well.

**Comment by Archilyte** [comment]
the holo list still doesnt scroll up. i have to drag it with my mouse

**Comment by zmaster587** [comment]
@Archilyte does this occur with just AR and libvulpes installed?

**Comment by Silfryi** [comment]
Do you have MouseTweaks? Did you disable wheel tweak already?

**Comment by Archilyte** [comment]
i dont have mousetweaks

**Comment by Archilyte** [comment]
and for the above question from @zmaster587 , i havent checked
imma check it when i go home

**Comment by deltanedas** [comment]
this is still present with mouse tweaks 2.10.1 and AR 2.1.6

disabling wheel tweak in MT settings fixes the bug so the cause listed in the comments was correct
