### ISSUE TITLE
Missing guidance computer in rocket GUI

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [zmaster587/AdvancedRocketry#1294]
## Version of Advanced Rocketry
1.4.0-16
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-34
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
N/A

## Description of the problem
After building a simple rocket of tanks, engines, a seat and a guidance computer, I can't access the guidance computer in the GUI that opens when you shift-right click on the rocket. The "Disassemble" and "Select Destination" buttons are there but the guidance computer is missing.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Revemohl** [comment]
Reverting 44464bf on my personal fork seems to have fixed this for me.
