### ISSUE TITLE
Warp Controller Not Recognizing Space Station / Warp Core / Can't Interact

### ISSUE THREAD

**Issue by Vyraal1** [zmaster587/AdvancedRocketry#1295]
## Version of Advanced Rocketry
1.4.0-80
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
No crash reports but video here of the problem: https://streamable.com/fi9tw

## Description of the problem
The link above has the video, but I created a Space Station, had it built out, however the Warp Controller doesn't seem to work, or at least recognize the Space Station / Warp Core.

**Comment by zmaster587** [comment]
Seems to be working ok in the latest build, closnig
