### ISSUE TITLE
Chests on rockets immediately closing the GUI

### ISSUE THREAD

**Issue by Elektron72** [zmaster587/AdvancedRocketry#1296]
## Version of Advanced Rocketry
1.4.0.-67
## Have you verified this is an issue in the latest unstable build
No
## Version of LibVulpes
0.2.8.-27
## Version of Minecraft
1.12.2
## Description of the problem
Whenever I open a chest on a rocket, the chest GUI immediately closes, preventing me from accessing items. I am using FTB Revelation, although I have had the same problem in other modpacks
[https://youtu.be/bUTKsbLf-z0](https://youtu.be/bUTKsbLf-z0)

**Comment by FoxBotGames** [comment]
At least you aren't crashing like most of us over on issue #1272

**Comment by zmaster587** [comment]
moving conversation to #1407
