### ISSUE TITLE
Advanced Rocketry 1.12. [Sponge] Space Station not saving blocks.

### ISSUE THREAD

**Issue by A-T-L-A-S** [zmaster587/AdvancedRocketry#1297]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-80
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-31-universal
## Version of Minecraft
1.12.2

## Description of the problem
This is an issue appearing on the "Beyond" Server of the "KineticNetwork". After a server Restart any blocks in a space station from that moment will turn into ghost blocks and will not be saved after reloading the chunks. Chunkloading did not fix the issue. According to one the Server owers this appears to be an issue with Advanced Rocketry not working properly with sponge.
If you need more information I will try to obtain it but I am new to github and may not respond very quickly.

**Comment by zmaster587** [comment]
the space station is a registered forge dimension.  It uses forge chunkloading and block storage.  IE, it's the same as the nether or end.

**Comment by zmaster587** [comment]
@phit Thanks, I really appriciate the offer
