### ISSUE TITLE
Lost connections and Inventory problems

### ISSUE THREAD

**Issue by Landstryder** [zmaster587/AdvancedRocketry#1298]
## Version of Advanced Rocketry
1.12.2-1.4.0-80
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem

3 Major issues with the current build-
-Unmanned rockets lose their connections after each mission. This seems to be a bit random, sometimes or location or configurations seem to be more susceptible to this.
-Opening a Satellite terminal totally screws up your inventory with ghost items and can cause item lose
-Satellites work for a while after launch but then lose connection and cease to function.

To illustrate these issues here is a short video I made to showcase the problems:
https://youtu.be/mUHxhCbNF1U

**Comment by mtimyself** [comment]
I am experiencing the same issues with the Satellite Terminal in the FTB Continunum mod pack.
https://github.com/FTBTeam/FTB-Continuum/issues/202

**Comment by lhw** [comment]
We also ran into this issue on our server. Since the restart today we lost connection to all satellites.
Generally we run into all of these problems according to other players.

**Comment by zmaster587** [comment]
Does this issue exist with build 84?

**Comment by lhw** [comment]
Currently only the inventory bug still exist on our server. Some crashes with inventory and weird ghost inventories but satellites currently work.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by lhw** [comment]
The inventory thing with the satellite terminal is most definitely still a thing.

**Comment by SergeantTibbs** [comment]
> Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

I can report that this is still an issue.

**Comment by zmaster587** [comment]
Under what circumstances does this occur?  I'm opening a satellite terminal in singleplayer and not seeing anything unusual occuring.
I've tried it with an empty satellite terminal and with an item in the top right slot.

**Comment by SergeantTibbs** [comment]
I'm not quite sure what details you want about the circumstances.  It's been happening when I play on the server hosted by my brother.  There are 3-5 of us on there at most, and I haven't had any of them try it because I've been the only one focusing on exploring the Advanced Rocketry features.
