### ISSUE TITLE
Planets data is know although no research is done and normal Gravity on the moon

### ISSUE THREAD

**Issue by 456Xander** [zmaster587/AdvancedRocketry#130]
I just tested a bit in Creative Mode and noticed, that when I built the Planet Analyser, all Planets already have relative accurate data, but aren't on the right places: 
![image](https://cloud.githubusercontent.com/assets/16427898/15990407/ba23a050-3091-11e6-9094-598c605141b7.png)
Also the Planet Numbers are not in correct order, and on the moon there was normal gravity. Could this be because I'm playing in Creative mode?

**Comment by zmaster587** [comment]
The planet numbers do not have any particular order as they are placeholders for names to be generated later.  The data system has been taken out for the time being and wil be used for asteroid discoveries instead.  However the lack of gravity on the moon is unusual.  Can you try running 0.5.3 to see if that fixes the gravity issue?  I changed how gravity was handled in the newest build.  if gravity is still broken with 0.5.3, can you upload the temp.dat found in <save/server directory>/AdvancedRocketry/temp.dat?

**Comment by 456Xander** [comment]
In 0.5.3 Gravitiy works fine

**Comment by zmaster587** [comment]
gravity should be fixed in 0.5.5, asm derp
