### ISSUE TITLE
Wrong Planet icons on server

### ISSUE THREAD

**Issue by CaptainStalfoss** [zmaster587/AdvancedRocketry#1302]
## Version of Advanced Rocketry
1.12.2 1.4.0-80
## Version of LibVulpes
1.12.2  0.2.8-30
## Version of Minecraft
1.12.2
## Description of the problem
Hi me again, i was creating my solar system and it worked fine in single player.
but when i moved it to my server, most of the planets had the wrong icon.
Red Gas Giants are Blue, and some smaller planets have moon icons instead.

This only happens on the server.

Here's the PlanetDef:
[Planetdeftextfile.txt](https://github.com/zmaster587/AdvancedRocketry/files/2018518/Planetdeftextfile.txt)

i checked the file in the World save, and it still says Redgasgiant for jupiter/saturn, so it wasnt a change there.

**Comment by zmaster587** [comment]
I don't think the server sends icon information, let me check on that.

**Comment by CaptainStalfoss** [comment]
Do you need me to give any other files regarding the matter?

**Comment by zmaster587** [comment]
Oddly enough, I've found connecting to the server twice seems to show the correct texture.

**Comment by CaptainStalfoss** [comment]
im on 1.12.2-1.4.0-33, and issue is still present.
unless you mean the upcoming version?

**Comment by dmodoomsirius** [comment]
@CaptainStalfoss try the one before -33. that is a version that should not be on curse. It compiled when i made a commit to curseforge.
