### ISSUE TITLE
[1.12.2] Crash when trying launch rocket

### ISSUE THREAD

**Issue by ghost** [zmaster587/AdvancedRocketry#1305]
## Version of Advanced Rocketry
1.4.0-81
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://paste.dimdev.org/wujedarujo.txt

## Description of the problem
I built my rocket and was ready to launch, but when I press space to launch the rocket the game crashes.  I have no idea of what might be causing it.

**Comment by Janrupf** [comment]
Looks like it's trying to run server side code on the client, the stacktrace tells me that this is a problem in LibVulpes

**Comment by zmaster587** [comment]
looks like a client world is returning false for isRemote (basically the client world is claiming it's a server world) in the rocketBuilder class.  Does this occur with only advanced rocketry and libvulpes installed?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
