### ISSUE TITLE
Cutting machine doesn't handle multiple outputs well

### ISSUE THREAD

**Issue by belathus** [zmaster587/AdvancedRocketry#1308]
## Version of Advanced Rocketry
1.4.0-80
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
The cutting machine is putting out more items than it should in a custom recipe. For reference, here is the relevant recipe I've added: https://github.com/belathus/Wanderlust-Renewed/blob/90ec36734fc8e210e80274be2140edfcaae762c0/config/advRocketry/CuttingMachine.xml#L951-L959

If I immediately pull out the items produced, there isn't a problem. However, if I leave the items in the output slot, it sometimes shifts the stack left, then copies the stack it just shifted and adds one to the stacksize. Here are some screenshots to show what I'm talking about:

![2018-05-22_09 08 29](https://user-images.githubusercontent.com/3826783/40364582-b6d36262-5da0-11e8-88b7-953f58204079.png)
![2018-05-22_09 08 32](https://user-images.githubusercontent.com/3826783/40364595-bcfa8a44-5da0-11e8-8490-843cabcc255f.png)
![2018-05-22_09 08 37](https://user-images.githubusercontent.com/3826783/40364603-c24b81e2-5da0-11e8-804a-b63ca07c09d1.png)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
