### ISSUE TITLE
Rocket not returning to departure location on Earth when returning from space station

### ISSUE THREAD

**Issue by bladeroth** [zmaster587/AdvancedRocketry#1310]
## Version of Advanced Rocketry
1.4.0
## Have you verified this is an issue in the latest unstable build
N.A
## Version of LibVulpes
0.2.8
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
Not crashing

## Description of the problem
I take off from my base on Earth (overworld) to my space station. I then return back to Earth from the space station and am landing in some random location that I have never been before.

**Comment by Kzorith** [comment]
I am experiencing the same thing but not quite the same way.  I take off to Luna and upon my return I'm brought into Earth at 0,0,0, suffocating in stone or burning in lava if I can't switch to creative mode quickly enough.  I did have it happen on my trip to Luna once as well but it spawned me under bedrock and I died in the void.  Subsequent journeys seem to work ok.

Images attached below.

I've tested this in a single player world with only Adv.Rocketry and libVulpes installed. No changes to the config, it's "out of the box"
Adv. Rocketry 1.4.0-88
libVulpes 0.2.8-32 

![2018-06-30_14 24 42](https://user-images.githubusercontent.com/13224348/42128931-7a8a8ca8-7c73-11e8-9e23-b21b0112c488.png)
![2018-06-30_14 29 14](https://user-images.githubusercontent.com/13224348/42128933-7ea487ee-7c73-11e8-976a-9001dc218f0d.png)

**Comment by Kaeteker** [comment]
I'd just like to say that I'm experiencing the exact same bug Kzorith did. I'm playing on FTB Continuum 1.4.1.

When I first went to Luna, I spawned at x0 z0 inside bedrock and suffocated. I launched a rescue attempt, only to find that the rocket had disappeared. I did manage to dig down there and grab my grave though. My first launch back to Earth had the exact same issue, suffocating in bedrock. Subsequent launches all work fine. I'm afraid I'm going to have to make two sacrificial rockets whenever I go to a new place, one to suffocate getting there and one to suffocate getting back before everything works right.

**Comment by zmaster587** [comment]
Found the issue, there was an instance where destId's y coordinate was used when there was no previous position stored, since only the x and z coordinates are used then y comes from altitude of orbit from the configuration the previous position's y is always 0.  I've changed it to use Configuration.orbit in the patch.
