### ISSUE TITLE
Mod Conflict Aether II Highlands

### ISSUE THREAD

**Issue by V3STR4** [zmaster587/AdvancedRocketry#1311]
## Version of Advanced Rocketry
1.12.2-1.4.0-80
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.12.2-0.2.8-31
## Version of Minecraft
1.12.2 Forge Current
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
Not a crash 
Mod Conflict when using all the mods mod pack and Adding Aether II Highlands mod
## Description of the problem
I use the Aether portal and it spawns me either on the moon sometimes or it puts me in the Aether but with moon gravity and i die of no oxygen
[How can you reliably reproduce the problem]
I have the .minecraft folder thats the best way i can show you and see if you can find whats going wrong
https://drive.google.com/open?id=16EWhnNjj6ZmYVOT8CaOdFM9XPrZ5yNgj

**Comment by Rightfuldeathray** [comment]
i got the same problem, here was my solution, I hope you have no aether2 inventory or have it remembered, your AETHER2 inventory will be cleared. you must save the game from outside the aether2, destroy the totem portal thing and delete it from your inventory, then relaunch the game without aether2, quit the game. go to the config file labeled aether, inside there should be a section that controls the dimensions of the aether2 and necromancer castle. change the numbers to unused dimensions (castle uses same DIM as aether 1). I recommend using random 4 character numbers example:2065. Install aether2, then relaunch and you should be good.

**Comment by Rightfuldeathray** [comment]
By the way I blame the Aether2 for this error, it is created by using a dimension that is already being used

**Comment by V3STR4** [comment]
Exactly what i told them they wont listen to me can you get in contact with
them on my behalf please?

**Comment by Rightfuldeathray** [comment]
no I don't have that ability

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
