### ISSUE TITLE
Rolling Machine Custom Recipes

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1313]
## Version of Advanced Rocketry
1.12.2-1.4.0-82-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.2.8-31-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
[How can you reliably reproduce the problem]
I've replaced Water with Lubricant in all Rolling Machine recipes, with this script: 
https://gist.github.com/NillerMedDild/6ac2e60d827a75aa488582e0169ca6a9
It loads up, and the new recipes are displayed in JEI, however the Rolling Machine isn't able to make any of them.

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/40619950-5276eae0-6297-11e8-95ca-5b5f833145b0.png)
![javaw_2018-05-28_16-51-17](https://user-images.githubusercontent.com/21295394/40619992-7a8d352a-6297-11e8-8f6c-f3643e9c0784.png)
![javaw_2018-05-28_16-51-22](https://user-images.githubusercontent.com/21295394/40619993-7aa869b2-6297-11e8-9d99-9cb0028b4a61.png)
![javaw_2018-05-28_16-51-27](https://user-images.githubusercontent.com/21295394/40619994-7ac01b5c-6297-11e8-8805-864755ff59a3.png)
![javaw_2018-05-28_16-51-31](https://user-images.githubusercontent.com/21295394/40619995-7ae8507c-6297-11e8-83df-bc78c964152d.png)

**Comment by belathus** [comment]
Looks like your inputs are missing a stack size.

```
<oreDict>ingotGold</oreDict>
```
should be:
```
<oreDict>ingotGold 1</oreDict>
```

**Comment by NillerMedDild** [comment]
The recipes work just fine if `lubricant` is changed to `water`, without giving the oredicts a stacksize.

**Comment by NillerMedDild** [comment]
Changing all oredicts to also account for amount didn't change anything.

**Comment by belathus** [comment]
... I got nothing. :P

**Comment by NillerMedDild** [comment]
Lava doesn't work either, but it also displays properly in JEI.

**Comment by zmaster587** [comment]
The rolling machine is currently hardcoded to take water at the moment.  It'll take a patch to fix.

**Comment by NillerMedDild** [comment]
Good to know, thanks.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/2065252/AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip)

Can you try this build and let me know if it's working as expected for you?

**Comment by NillerMedDild** [comment]
That works perfectly :)
I'm noticing, when the Rolling Machine is crafting and runs out of fluid, it doesn't automatically start again when supplied with more fluid through buckets. Taking the input items out and back in start the machine again.
It's a minor thing, so I don't really mind, just thought I'd let you know.

**Comment by zmaster587** [comment]
I'll check on that, might be that the inventory update event is not firing when fluid is added

**Comment by zmaster587** [comment]
Pushing an update to libvulpes to fix the fluid not updating the rolling machine.

**Comment by NillerMedDild** [comment]
Awesome, thank you!
