### ISSUE TITLE
Custom Recipes with NBT

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1315]
Version of Advanced Rocketry
1.10.2 - 1.4.0.12
## Description of the problem
Is it by any chance possible to add NBT to items in the custom recipes? I mean for the AR Machines.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
