### ISSUE TITLE
Conflict crash with Betweenlands

### ISSUE THREAD

**Issue by Tinemither** [zmaster587/AdvancedRocketry#1317]
## Version of Advanced Rocketry
Most recent (30/5/2018) stable build. Used in AllTheMods3 modpack, 5.9.5
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-31-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/TN890bne

## Description of the problem
Upon opening the GUI for the guidance computer in rocket entities, the mod conflicts and crashes due to a Betweenlands conflict. Is this relevant here?
Pastebin below and above.
https://pastebin.com/TN890bne

**Comment by zmaster587** [comment]
#1372
