### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1319]
## Version of Advanced Rocketry
1.12-1.4.0-33-UNSTABLE build -33 for 1.12
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.2.8-31-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://gist.github.com/NillerMedDild/89dc882ada02029f9f801b719212570b

## Description of the problem
I crash on startup in the latest AR build - I downgraded to the prior version, and the issue was fixed.

**Comment by wormzjl** [comment]
Similar crash here
https://pastebin.com/G2bJxhP8

**Comment by wormzjl** [comment]
![image](https://user-images.githubusercontent.com/2989009/40792694-d2a49130-64fa-11e8-8c47-e0766d19834d.png)
stupid curseforge -.-

**Comment by NillerMedDild** [comment]
According to the date, the top one is the most recent update.

**Comment by NillerMedDild** [comment]
Your crash is not similar to mine at all @wormzjl - I suggest you make an issue for your crash.

**Comment by jengeld4** [comment]
Most recent in date, yes, but you will notice it says "unstable" and the version numbers are out of order. Install the latest one that doesn't say "Unstable" and it should work.

**Comment by NillerMedDild** [comment]
Switching to an older version of the mod doesn't fix the bug, I'm not sure I'm understanding you @jengeld4?

**Comment by ikkerens** [comment]
Was able to reproduce this with the same crash report that NillerMedDild had.
Did someone upload an older version?

**Comment by jengeld4** [comment]
For some reason, Twitch is up loading his unstable versions out of order and and higher then the current version. There are about 20 of them. Scroll down until you find AdvancedRocketry-1.12.2-1.2.5a-18.jar and install that one.
![image](https://user-images.githubusercontent.com/10388293/40848235-357df826-6584-11e8-9eef-0a404d342022.png)
I think this should fix your crash.
