### ISSUE TITLE
Latest builds crashes with just itself and LibVulpes

### ISSUE THREAD

**Issue by Alan19** [zmaster587/AdvancedRocketry#1322]
## Version of Advanced Rocketry
1.12.2-1.4.0-33
## Have you verified this is an issue in the latest unstable build
Y,N
## Version of LibVulpes
1.12.2-0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://paste.ee/p/2if8O

## Description of the problem
The latest unstable build crashes the game

**Comment by royalcw** [comment]
Problem solved...So, if you look at the versioning history, 1.4.0-33 is actually a huge step back on versions.  The version history is in the wrong order in Twitch.  To fix your problem "downgrade" to version 1.4.0-82 and it will work just fine with your forge version.  I figured this out by looking at the other issue tickets about versions out of order for the latest pushes.
