### ISSUE TITLE
Ticking entity after launching a rocket with satellite in the Betweenlands

### ISSUE THREAD

**Issue by ShageJack** [zmaster587/AdvancedRocketry#1324]
## Version of Advanced Rocketry
Most recent (30/5/2018) stable build 1.12.2-1.4.0-82
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-31-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/mm5RbVmS

## Description of the problem
I'm running my own mod pack in a forge server. After I launched a rocket with a satellite in the Betweenlands, the server crashed. And then I restarted the server. Since then, every time I join the server, the server crashes again.

**Comment by jalako** [comment]
got the same error on build 1.12.2-1.4.0-83-UNSTABLE and 1.12.2-1.4.0-84-UNSTABLE

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
