### ISSUE TITLE
Serious bug, Satellite chips invalid after game load, all minecraft versions

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1326]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-74 and newer
AdvancedRocketry-1.10.2-1.4.0.12 (actualy 1.4.0.9 and newer)
## Have you verified this is an issue in the latest unstable build
YES
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-29-universal
LibVulpes- 1.10.2-0.2.8.37
## Version of Minecraft
All builds, confirmed on 1.10.2, 1.12.2
## Crash report or log (if applicable)
Satelite chips are not working any more after save & load.
## Description of the problem
Launch a satelite (any)
Put chip ito Sattelite Terminal
Save & Load the game
Observe the Chip has now status No Link...

This is replicate of issue #1248 since it is a very serius and confirmed bug... and it is now so back in the history that I am afraid it was missed by @zmaster587

I checked on pure game, AR only... on 1.10.2 this happened between versions 1.4.0.8 and 1.4.0.9.
This is no small bug... i makes the whole satellites concept useless so it MUST be fixed with top priority. There is no workaround so the only solution is to revert to 1.4.0.8 or not use satellites.

**Comment by zmaster587** [comment]
Introduced when fixing loading of XML, fixed
