### ISSUE TITLE
Biome changer remote doesn't work properly

### ISSUE THREAD

**Issue by sndmax** [zmaster587/AdvancedRocketry#1330]
## Version of Advanced Rocketry
1.4.0-82-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
ATM3 v5.9.6b modpack
## Crash report or log (if applicable)
https://pastebin.com/4s11Yx4L

## Description of the problem
Biome changer remote GUI opens only once, further tries throws error in a console.
It happens after "Darklands Forest" biome scan from "Abyssalcraft" mod.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
