### ISSUE TITLE
Arc Furnace not crafting with Automation

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1331]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-84-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-32-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
The Electric Arc Furnace doesn't start to craft when automation (Pipes, Applied Energistics Interfaces, etc) places the input in its Input Hatch.

**Comment by zmaster587** [comment]
This likely effects all machines, switching over to capabilities kinda threw the start crafting function off a bit.  Should be fixed in the next version of libvulpes

**Comment by NillerMedDild** [comment]
Thank you :)
