### ISSUE TITLE
The save's planetDefs.xml does not update to reflect changed in the config's planetDefs.xml

### ISSUE THREAD

**Issue by aaronhowser1** [zmaster587/AdvancedRocketry#1334]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-84-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-32-universal
## Version of Minecraft
1.12.2

## Description of the problem
There's a bit problem with Continuum right now where none of the AR planets have the right ores or artifacts. For some reason, the planetDefs.xml from the save is not being updated to match the one in the config, so there's no way for modpack makers to ever update the planets 

Specifically, this is what an old save's planetDefs.xml looks right now:

```
 <planet name="Litherite" DIMID="30" customIcon="iceworld">
            <isKnown>false</isKnown>
            <fogColor>1.0,1.0,1.0</fogColor>
            <skyColor>0.533,0.509,1.0</skyColor>
            <gravitationalMultiplier>90</gravitationalMultiplier>
            <orbitalDistance>180</orbitalDistance>
            <orbitalPhi>270</orbitalPhi>
            <rotationalPeriod>54000</rotationalPeriod>
            <atmosphereDensity>50</atmosphereDensity>
            <biomeIds>advancedrocketry:crystalchasms</biomeIds>
            <oceanBlock>techreborn:techreborn_techreborn.potassium</oceanBlock>
            <fillerBlock>minecraft:snow</fillerBlock>
        </planet>
```

while this is what the config's looks like for the same planet

```
		<planet name="Litherite" DIMID="30" customIcon="iceworld">
			<isKnown>false</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>0.533,0.509,1.0</skyColor>
			<gravitationalMultiplier>90</gravitationalMultiplier>
			<orbitalDistance>180</orbitalDistance>
			<orbitalPhi>270</orbitalPhi>
			<rotationalPeriod>54000</rotationalPeriod>
			<atmosphereDensity>50</atmosphereDensity>
			<oreGen>
				<ore block="environmentaltech:litherite" minHeight="4" maxHeight="80" clumpSize="15" chancePerChunk="64" />
			</oreGen>
			<biomeIds>advancedrocketry:crystalchasms</biomeIds>
			<artifact>environmentaltech:structure_panel 0 64</artifact>
			<oceanBlock>techreborn:techreborn_techreborn.potassium</oceanBlock>
			<fillerBlock>minecraft:snow</fillerBlock>
		</planet>
```

This is from FTBTeam/FTB-Continuum/issues/218

**Comment by dmodoomsirius** [comment]
is the config to `B:resetPlanetsFromXML=false` in the `advancedRocketry.cfg` set to true? that should reset the one from the world to match the config.

**Comment by aaronhowser1** [comment]
Oh wow, I had no idea there was a config setting for that. That's totally on us then, if that works. Thanks!

**Comment by aaronhowser1** [comment]
It apparently resets itself before the game even reaches the launch screen, so it doesn't affect saves in any way whatsoever.

**Comment by aaronhowser1** [comment]
It also puts it on the modpack player to change configs, instead of letting the modpack maker do it, which is also pretty bad for pack makers.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
