### ISSUE TITLE
Client Crash when opening Guidance Computer on Rocket

### ISSUE THREAD

**Issue by mtimyself** [zmaster587/AdvancedRocketry#1336]
Happens in the Continuum pack (v1.3.1)

## Crash report or log (if applicable)
https://pastebin.com/jANASSvk

**Comment by zenoran** [comment]
Yep.  Getting this nonstop among many other crashes and bugs :(  Making Continuum a chore to get through right now.

**Comment by dmodoomsirius** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1337

Fixed. Closing issue.
