### ISSUE TITLE
Opening the Planet on Warp Drive crashes

### ISSUE THREAD

**Issue by zenoran** [zmaster587/AdvancedRocketry#1337]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-85-universal
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-32-universal
## Version of Minecraft
1.12
## Crash report or log (if applicable)
https://paste.dimdev.org/esowabunuv.mccrash

## Description of the problem
I'm trying to move my space station back to earth but I can't get the UI to select Earth.  I'm on the Environmental Tech universe in Continuum and if I click the "up" button to go back to select solar systems it instantly crashes.  No way out.  Tried updating to the latest version of AR hoping it would fix other bugs too but still having lots of crashing problems.  Usually I can just restart and keep going but this one is a blocker.  Would love a workaround for selecting Earth so I can port home. :)

**Comment by dmodoomsirius** [comment]
Can you please pastebin or something similar the planetDefs.xml and upload the temp.dat please?

**Comment by zenoran** [comment]
temp.dat
https://paste.dimdev.org/egurohudar

planetDefs.xml
https://paste.dimdev.org/oqofuwiyih.xml


btw... was having earlier issue with planetDefs.xml not being read properly in the pack or something... I had to overwrite it with what was in the config and regen the worlds.  Not sure if that's related or not but it's regarding feedback in this issue ticket:

https://github.com/FTBTeam/FTB-Continuum/issues/218

**Comment by zmaster587** [comment]
can you try the build here? https://github.com/zmaster587/AdvancedRocketry/issues/1320#issuecomment-397499044

**Comment by zenoran** [comment]
Yes that version works.  Thanks. :)

**Comment by zmaster587** [comment]
Good, I'd fixed it and forgotten to push the changes, the next build on curse should contain the fix
