### ISSUE TITLE
Oxygen consumption rate - Is there a config?

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#1338]
## Version of Advanced Rocketry 1.10.2, latest
Is there a way to set up, how long will a bucket of oxygen last?
I know I can set up, how long will the INTERNAL buffer of the space suit last, but that does not influence added tanks, right?
So, when I want to set up that low pressure tank will last 5 mins and normal 10 mins, how can I do it?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
