### ISSUE TITLE
Conflict with Multihotbar

### ISSUE THREAD

**Issue by budgej** [zmaster587/AdvancedRocketry#1339]
## Version of Advanced Rocketry
1.12.2-1.40.0-84
## Have you verified this is an issue in the latest unstable build
No
## Version of LibVulpes
1.12.2-0.2.8-29
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
There seems to be a conflict with Advanced Rocketry's space suit GUI and Multihotbar. With Forge 2655, Multihotbar 1.12-4.0.1-T116, and Advanced Rocketry 1.12.2-1.4.0-84 (and their dependencies), the space suit GUI is not rendered. Removal of Multihotbar mod restores the GUI (but you can leave Multihotbarcore and the GUI will render). I am not sure which mod is the cause of the issue so I am reporting on both issue trackers. Thanks for your consideration.

[Multihotbar issue](https://github.com/rolandoislas/multi-hotbar/issues/54)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
