### ISSUE TITLE
Galacticraft airlocks not solid

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#134]
dont know if this is a bug or not since it seem to keep air in without problems but the galacticraft airlock is marked as not solid.
galacticraft version 460 and AR 0,54

![2016-06-14_18 53 18](https://cloud.githubusercontent.com/assets/1352518/16051842/c453457c-3261-11e6-9fea-4297481396bf.png)

**Comment by zmaster587** [comment]
Will check into that

**Comment by zmaster587** [comment]
When sided checks for atmosphere are implemented later down the line this should be fixed

**Comment by zmaster587** [comment]
GC airlocks can be added to sealable block in config. closing
