### ISSUE TITLE
 Advanced Rocketry Shift Click Crash (rocket)

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1340]
## Version of Advanced Rocketry
1.12.2-1.4.0-84-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.2.8-32-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/239LJXSN

## Description of the problem
Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/118
Issue relayed from a user of Enigmatica 2 Expert.
When shift+ right clicking on a formed Advanced Rocketry rocket and going into the nav computer I crash 50% of the time if not more.

**Comment by zmaster587** [comment]
The provider for the dummyworld that's used for the rocket was never assigned a world object.  Fixing.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/2126344/AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip)

Would you be able to give this build a shot and see if the crashing continues?

**Comment by NillerMedDild** [comment]
Still no word from the first reporter, I'll trust this is fixed, thank you :)
