### ISSUE TITLE
BUG in 1.12.2

### ISSUE THREAD

**Issue by AnthonyFuller** [zmaster587/AdvancedRocketry#1342]
## Version of Advanced Rocketry
Alpha latest 1.12.2 as of now
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
Latest
## Version of Minecraft
1.12.2

## Description of the problem
Try to take off, to no avail. Just stays there, draining fuel

**Comment by zmaster587** [comment]
can you post a screenshot of your setup?  what is the acceleration of the rocket?

**Comment by AnthonyFuller** [comment]
I reinstalled the mod and it works now. Never mind! Thanks!
