### ISSUE TITLE
Unable to load planetDefs.xml during world loading, crashes whole client

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [zmaster587/AdvancedRocketry#1343]
## Version of Advanced Rocketry
86
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
0.2.8-32
## Version of Minecraft
Forge 2709
## Crash report or log (if applicable)
A high-lighted full log
https://pastebin.com/bJUUK7fJ

Complete full log
https://1drv.ms/u/s!AuxrrFvXeZw1g4h3ZwaGVp7tEgLz8A

## Description of the problem
[How can you reliably reproduce the problem]

**Comment by dmodoomsirius** [comment]
What libVulpes version? Can you pastebin the planetDefs.xml? And link it here.

**Comment by Pythonic-Rainbow** [comment]
@dmodoomsirius 
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/2152932/planetDefs.zip)

**Comment by dmodoomsirius** [comment]
I don't know if something is wrong with your planetDefs.xml but when i extract it its not valid showing a ton of `000 000 000`'s

**Comment by Pythonic-Rainbow** [comment]
@dmodoomsirius thats unfortunate. However I found that the issue happens in both client and server side. If it occurs again I will try to reupload a sample to you

**Comment by Pythonic-Rainbow** [comment]
We have been unable to replicate this issue. We have not seen it for awhile as well, so I guess this will be closed.
