### ISSUE TITLE
Airtight Seal problem

### ISSUE THREAD

**Issue by Rexiie** [zmaster587/AdvancedRocketry#1345]
## Version of Advanced Rocketry
AdvancedRocketry-1.7.10-1.4.0-18.jar
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.7.10-0.2.8-34-universal
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
Unnecessary

## Description of the problem
I had AR installed and it worked all good (and I could get Airtight Seal), but because I was getting  slowness and mining fatigue in the Aether I tried removing some mods to see what caused it. Turns out it was AR. I reinstalled it with the exact same AR and LibVulpes files as before and changed the config so atmospheric effects were off. However when I reopened Minecraft I could no longer apply Airtight Seal. The recipe doesn't show up with NEI anymore, and nothing happens if i try applying it with the chemical reactor... Hope I can get some help :)

**Comment by Rexiie** [comment]
Fixed!
I have no clue why, but re-enabling atmospheric effects did the trick! I also uninstalled The Aether II, so the slowness and mining fatigue don't matter now, as long as I (hopefully) only get them on Hot Dry Rock planets...

**Comment by zmaster587** [comment]
The dimension for the aether probably had atmosphere density set to a value over 100 in world/advRocketry/planetDefs.xml

Or the dimid may have overlapped with another planet.  If you want to keep both without the effect you may want to look into that.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
