### ISSUE TITLE
Problem opening chests

### ISSUE THREAD

**Issue by man03** [zmaster587/AdvancedRocketry#1347]
Sorry if this is a duplicate, but I haven't been able to find anything about this
## Version of Advanced Rocketry
1.12.2-1.4.0-88-UNSTABLE build -88 for 1.12.2
## Version of LibVulpes
1.12.2-0.2.8-32-UNSTABLE build -32 for 1.12.2
## Version of Minecraft
1.12.2
## Description of the problem
Whenever I try to open a chest that is built into a rocket, the GUI closes within a few ticks. This happens with vanilla chests, as well as chests from Iron Chests and Colossal Chests.

**Comment by Kzorith** [comment]
Also with Actually Additions crates.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
