### ISSUE TITLE
Can't fly with rockets to planets

### ISSUE THREAD

**Issue by EscolarProgramming** [zmaster587/AdvancedRocketry#1348]
## Version of Advanced Rocketry
1.4.0.-84
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8.-32
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
Log in MP: https://paste.feed-the-beast.com/view/e4eda409
Log in SP: https://paste.feed-the-beast.com/view/81a0a362

## Description of the problem
We are a server which uses the FTB modpack continuum. In a lot of times, it's impossible to reach the moon, the space base or other planets. The rocket is big enough and we've already reached the moon and the space station once with that rocket once.
In all the other tries we can start and the rocket launches up to y=998, but than the velocity goes to 0, the fuel gets empty and you fall back to earth.
![java_2018-07-04_20-42-37](https://user-images.githubusercontent.com/6965961/42342209-c461165a-8095-11e8-80c3-be7985334224.png)
![java_2018-07-04_20-43-34](https://user-images.githubusercontent.com/6965961/42342212-c63d8652-8095-11e8-8a15-53042d984a9e.png)
Also bigger and smaller rockets only work once. 

Here's a video of the issue: https://www.youtube.com/watch?v=m9F8RNTbvo0

I've already reported it in the issues of FTB, but I think I can get better help here. Here's the issue: FTBTeam/FTB-Continuum#302

**Comment by dmodoomsirius** [comment]
Have you reported this issue on the continnum issue tracker? You are using a old version of the mod.

**Comment by EscolarProgramming** [comment]
Yes, I have linked it at the end of the issue report.

**Comment by dmodoomsirius** [comment]
https://github.com/FTBTeam/FTB-Continuum/issues/302#issuecomment-403547298 Closing as this has been fixed as tfox states he will get a update out soon.
