### ISSUE TITLE
Wireless Relays converting all data types into "Distance" data.

### ISSUE THREAD

**Issue by TeetoKaziim** [zmaster587/AdvancedRocketry#1349]
## Version of Advanced Rocketry
1.4.0-88
## Have you verified this is an issue in the latest unstable build
Nope
## Version of LibVulpes
0.2.8-32
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
None applicable.
## Description of the problem
Data extracted from a "Satellite Terminal" by a "Wireless Relay" becomes "Distance" data inside the "Wireless Relay", regardless of what kind of data it was while it was stored inside the "Satellite Terminal".

The easiest way to see this in effect is to launch some satellites, one of each for distance, composition, and mass, put their chips into a satellite terminal, and link those terminals to an astrobody data processor. The only bar that will fill is distance.

Or, just attach a wireless relay to a satellite terminal full of composition or mass data, turn on "extract" in the relay's UI, then turn it off again. The data you extracted will go back into the terminal, but in its new distance form, effectively "clogging" the terminal from downloading any more non-distance data from its linked satellite.

**Comment by xenoflot** [comment]
This issue remains valid in ver 1.4.1.-114  lib 0.3.0.-44  forge 14.23.5.2768

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by StefanTT** [comment]
It still happens, I can reproduce it on 1.12 in this way:

* have a satellite terminal with a satellite chip but no data in it
* connect a wireless transceiver

When the satellite terminal contains some data it does not happen.
