### ISSUE TITLE
Opening rocket inventory crashes game

### ISSUE THREAD

**Issue by nickwood** [zmaster587/AdvancedRocketry#1350]
## Version of Advanced Rocketry
1.4.0
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8
## Version of Minecraft
1.12.2 forge-14.23.4.2708
## Crash report or log (if applicable)
crash#1 https://pastebin.com/bLR6aUZp
crash#2 https://pastebin.com/mtrY3ybW

## Description of the problem
Opening the inventory of a constructed rocket causes Minecraft to crash to desktop. I'm running the Enigmatica 2: Expert modpack (v. 1.32) and have also reported to the Modpack Author [here](https://github.com/NillerMedDild/Enigmatica2Expert/issues/146)

**Comment by dmodoomsirius** [comment]
What is the build number for advanced rocketry that the pack is using?

**Comment by nickwood** [comment]
1.4.0-88

libVulpes is 0.2.8-32

**Comment by zmaster587** [comment]
The crashes listed do not appear related to opening a chest, it looks like you have a satellite ID chip in the guidance computer, can you check what's in it?

**Comment by nickwood** [comment]
From memory this sounds right. I had a blank satellite chip in the guidance computer when i assembled the rocket. 

(My logic was that the moon is the earth's natural satellite)

**Comment by zmaster587** [comment]
That might do it, see if it works with a chip that's not blank or with the latest build
