### ISSUE TITLE
Space station GONE. ??????

### ISSUE THREAD

**Issue by GmanAtheist** [zmaster587/AdvancedRocketry#1352]
## Version of Advanced Rocketry
AdvancedRocketry-1.7.10-1.4.0-18
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.7.10-0.2.8-34-universal
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
Built a massive lovely space station. Worked without problems. Then came back into game next day and I can not land on my space station. The station comes and goes fast past me while I am just floating in space.  I loaded a older version (AdvancedRocketry-1.7.10-1.0.19b) , (LibVulpes-1.7.10-0.1.19-universal) and space station is back stable. But without space elevator and beacons are not on the overworld.

**Comment by zmaster587** [comment]
A lot changed between 1.0.x and 1.4.x, the format for some of the saves changed for sure so there's a strong likelyhood a world made with 1.0.x is not compatible with 1.4.x.  If you're willing, I can try to convert the save for you by hand.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
