### ISSUE TITLE
Space Suit Infinite speed (Even walking) bug with TiC LongSword Right-Click Ability

### ISSUE THREAD

**Issue by ReiDaTecnologia** [zmaster587/AdvancedRocketry#1353]
Version of Advanced Rocketry?
1.4.0-88
Have you verified this is an issue in the latest unstable build?
Yes
Version of LibVulpes?
0.2.8-32
Version of MineCraft?
1.12.2

Description of the problem:
When you use LongSword from TiC (Tinkers' Construct) ability while wearing Space Suit with Bionic Legs upgrade, you can have infinite speed even if you stop you will still have it, removing the suit will not fix or stop the speed bug but at least you will continue losing hungry fast as normal. Exit the world and back don't fix it, restart the client too.
ModList (Have only Info/Utility and Performance mods)
theoneprobe-1.12-1.4.23
TConstruct-1.12.2-2.10.1.87
OptiFine_1.12.2_HD_U_E1
Mantle-1.12-1.3.2.24
JustEnoughResources-1.12.2-0.8.5.27
journeymap-1.12.2-5.5.2
jeiintegration_1.12.2-1.5.1.36
jei_1.12.2-4.10.0.198
InventoryTweaks-1.63
foamfix-0.9.9.1-1.12.2-anarchy
MultiMC Instance: https://drive.google.com/open?id=1pajTPgz3sPk3SF472Eu3DFHEptGl5heh (The Save have this bug already active because i don't managed a way to fix it)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
