### ISSUE TITLE
Crash after sending a satellite to Luna

### ISSUE THREAD

**Issue by DestinyPlayer** [zmaster587/AdvancedRocketry#1354]
## Version of Advanced Rocketry
1.4.0-88
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-31
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/1Y8w5qpY

## Description of the problem
I was testing a few things, and tried to launch a rocket to Luna along with a satellite. The moment the rocket got out of the atmosphere, the game crashed, and now the world refuses to load no matter what.

For further info, here's the full list of my mods.
http://prntscr.com/k4eavk

**Comment by dmodoomsirius** [comment]
Can you update libVulpes version to build 32 please?

**Comment by DestinyPlayer** [comment]
Done. Still crashes in the same way.
https://pastebin.com/GwJjBNry Here's the crash log

**Comment by DestinyPlayer** [comment]
https://pastebin.com/F8snUMvY
Nope, still crashed. Here's the most recent log.

**Comment by zmaster587** [comment]
It appears that there was a change in variable names when updating to 1.12, should work ok next build.

**Comment by enderger** [comment]
I have encountered this issue with the latest version installed within the Enigmatica 2 modpack.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
