### ISSUE TITLE
Crash caused by launching to another planet from a starship

### ISSUE THREAD

**Issue by GarethPW** [zmaster587/AdvancedRocketry#1356]
**This issue originally detailed a crash which took place during every startup following the original crash. It is now evident that these crashes were caused by a corrupted `ElectricArcFurnace.xml` configuration file. The crashes listed below are still a valid issue, however.**

## Version of Advanced Rocketry
1.12.2-1.4.0-89-UNSTABLE (and 1.12.2-1.4.0-88-UNSTABLE)

## Have you verified this is an issue in the latest unstable build?
Y

## Version of LibVulpes
1.12.2-0.2.8-32-UNSTABLE

## Version of Minecraft
1.12.2 (forge-1.12.2-14.23.4.2705-universal – recommended build)

## Crash report or log (if applicable)
https://pastebin.com/Hu811LtM (build 88 – Terra Nova)
https://pastebin.com/Bcd9JGBc (build 89 – Terra Nova)
https://pastebin.com/gfs4nvWD (build 89 – Stella)

## Other potentially useful files
`planetDefs.xml`: https://pastebin.com/FqktJPC8

I can provide other files from the server upon request if necessary.

## Description of the problem
Our issue arose during our first expedition with our first starship. Initially orbiting around Earth, our expedition took the following order of warps:

* Earth -> Uranus
* Uranus -> KELT-1b
* KELT-1b -> Novus (landed rockets here briefly)
* Novus -> Terra Nova (attempted to land rockets here before crash)

The first player to have their rocket teleport from the starship's dimension to that of Terra Nova was *yalnif*. Upon this teleportation, the server closed with the first listed crash report.

The second player to have their rocket teleport was myself, *GarethPW*. This occurred using build 89 rather than build 88. The same exact error occurred, detailed by the second crash report above.

A third crash has occurred following the launch to the planet, Stella. Its report can also be found above.

Upon each of these crashes, the rocket used ceases to exist and the player inside floats back to their starship.

**Comment by zmaster587** [comment]
It looks like it may be having trouble loading the traverse biomes, can you try swapping those out for AR or vanilla biomes and see if the crash occurs with those?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
