### ISSUE TITLE
Client Crashes When Opening Satellite Terminal UI

### ISSUE THREAD

**Issue by bobgrey1997** [zmaster587/AdvancedRocketry#1357]
## Version of Advanced Rocketry
1.7.10-1.4.0-18 (1.4.0-18)
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.7.10-0.2.8-34 (0.2.8.-34)
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
https://pastebin.com/pwjnHaG1

## Description of the problem
Whenever I try to open the Satellite Terminal's UI, my client crashes. I noticed the first time I tried this, it crashed. It was late at night, so I just went to bed. The next day (today) I go to open it, and it worked. I noticed an issue with the satellite not sending data, so I continued to open the Terminal several times I worked out the issue (it ended up being an issue with Data Cables), but now all of a sudden, every time I try to open it, my client crashes. I have not tested this on a newer version, as the mod is part of our server's pack, and my system can not handle playing Minecraft on Single Player, so I am unable to go load up a new instance with a newer version of the mod.
The above pastebin log is the resulting crash log. If a full game log is needed, please let me know where I can find such file.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
