### ISSUE TITLE
Bug: World renders blue

### ISSUE THREAD

**Issue by DarkGuardsman** [zmaster587/AdvancedRocketry#136]
While in a space dim everything turns blue in a set area, however some areas are not blue.

https://youtu.be/pdNjynmgEpE
watch the first few mins, rest is junk

**Comment by zmaster587** [comment]
does this occur without the rest of the stuff in that pack?  Last I checked there were several mods in there that messes with world rendering in some way.

**Comment by DarkGuardsman** [comment]
No clue, I have heard of some random render issues in the over world. Other than this I only see this issue on space stations, and only in unlit areas.

**Comment by zmaster587** [comment]
should have been fixed by lighting changes a few versions ago
