### ISSUE TITLE
Satellite Builder Wonkiness

### ISSUE THREAD

**Issue by Prometheus0000** [zmaster587/AdvancedRocketry#1361]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-91-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-34-universal
## Version of Minecraft
1.12.2

## Description of the problem
First of all, if you build a satellite, everything in the 7 slots on the right is consumed, even if it's a full stack. Secondly, if you put in, say, a basic solar panel, and then put in any number more in the same slot, it will consume the stack, leaving you with the number in the slot in your hand if it goes over 64 (and none added to the slot), or zero in your hand (and none added to the slot) if less than 64. Probably, you're only supposed to be able to put one item in each slot, which causes this problem. Third, if you build a satellite with 6 large solar panels, the built satellite will say 60 power generation, but if you launch it and try to receive the power from a Microwave Receiver, you only get 10RF/t. The same is true for a satellite with one large solar panel, or even a basic one. You do get 20RF/t if you put two different satellite's chips in the MR though, so that works. It seems all power satellites generate 10RF/t regardless of what you put on them.
I tested this on an instance with AR+LV and RFtools+RFTools Power (for power checking) and JEI.

**Comment by zmaster587** [comment]
Fixed stack size issue with the satellite assembler.  Power generation seems to be functioning as intended: 500RF/t with solars and a large battery.  Without a battery, 10 is the max you can get out of it though.  I guess it may be a bit counterintuitive, I'll remove the battery storage capacity as a limiting factor for throughput.
