### ISSUE TITLE
Server crashes when user changes dimension.

### ISSUE THREAD

**Issue by Zexceil** [zmaster587/AdvancedRocketry#1362]
## Version of Advanced Rocketry
1.12.2-1.4.0-88
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.12.2-0.2.8-32
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/W1duXAhZ

## Description of the problem
Anytime a user on my server attempts to change planets a crash occurs which first kicks him and then when he joins the server crashes; I have noticed each time the server trying to gen a spawn zone for this dimension.

**Comment by dmodoomsirius** [comment]
I am noticing a wireless red stone in the stack trace. Did you report it to them we well?

**Comment by zmaster587** [comment]
Does this occur without sponge?

**Comment by Zexceil** [comment]
The user can change dimensions with anything else; I'm currently running the test without WR-CBE and sponge.

**Comment by zmaster587** [comment]
What about without sponge?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
