### ISSUE TITLE
Rocket Launching Crash

### ISSUE THREAD

**Issue by GameMonster2745** [zmaster587/AdvancedRocketry#1363]
## Version of Advanced Rocketry
[1.12.2-1.4.0-88]
## Have you verified this is an issue in the latest unstable build
 N/A
## Version of LibVulpes
[1.12.2-0.2.8-32]
## Version of Minecraft
[1.12.2]
## Crash Report
[https://pastebin.com/ruQA6y5j]

## Description of the problem
[Rocket Launches And Game Crashes]

**Comment by zmaster587** [comment]
Can you pastebin a copy of the latest.log file, there should be "A TileEntity <something here> has thrown an exception during loading, its state cannot be restored. Report this to the mod author" and i need to know what that thing is.  Or if you could figure out what tile/machine you're putting on the rocket it is that's causing problems, either one works

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
