### ISSUE TITLE
Broken Observatory UI

### ISSUE THREAD

**Issue by ZeekDaGeek** [zmaster587/AdvancedRocketry#1364]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-88-universal.jar
## Have you verified this is an issue in the latest unstable build
No, but I have checked the changelogs and didn't notice any fix listed.
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-32-universal.jar
## Version of Minecraft
Minecraft 1.12.2 (FTB Continuum 1.4.1)

## Description of the problem
If you attempt to scan for asteroids you will get a nice long list in the Observatory that you can't scroll through at all. Every time you attempt to scroll it goes back to the top of the list, I assume every time the UI redraws. This means you just have to get lucky that a desired asteroid is in the top 4.

**EDIT:** Apparently part of the problem is Mouse Tweaks' Wheel Tweaks making it so you can't scroll using the mouse wheel but, there's still a problem with the clicking and dragging alternative option, even when all tweaks are disabled.

**Comment by dmodoomsirius** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+created%3A%3C2018-09-03+-label%3Aenhancement

**Comment by mopsyd** [comment]
This issue is still persisting, and the link you responded with is broken

**Comment by mopsyd** [comment]
Suggested to implement the possibility to scroll menus with the arrow keys to properly address this. That would circumvent all other collisions with other mods altering mouse behavior.
