### ISSUE TITLE
server crash with gas miner

### ISSUE THREAD

**Issue by ATerribleModder1** [zmaster587/AdvancedRocketry#1365]
## Version of Advanced Rocketry
1.4.0-93 universal 
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-32 universal
## Version of Minecraft
1.12.2 forge server
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/gv8sFZUF

## Description of the problem
every time i try to launch a gas miner the moment it goes out of render (or it gets deleted) the server will crash booting me to the server select screen, i tried the same setup in single player without any crash or freezing. i can load up the server just fine afterwards without any problems but the gas miner is gone for good.

**Comment by zmaster587** [comment]
By any change could you upload the planetDefs.xml file and check to see if any gasses were selected for mining?

**Comment by BOOMHEADSHOT111** [comment]
https://pastebin.com/yyWWyQqj

**Comment by zmaster587** [comment]
@BOOMHEADSHOT111 The chat message stuff looks like another casualty of not allowing capital letters in identifiers, I'll go through and prune it

**Comment by zmaster587** [comment]
@BOOMHEADSHOT111 Does not seem to occur in single player.... hmm... as it turns out, there's no localization on servers, might be part of the issue.
