### ISSUE TITLE
Machines take full stacks instead of one item at a time

### ISSUE THREAD

**Issue by NyukoNoxus** [zmaster587/AdvancedRocketry#1366]
## Version of Advanced Rocketry
1.12.2-1.4.0-93
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.12.2-0.2.8-34
## Version of Minecraft
1.12.2
## Description of the problem
Put a stack of items (e.g 64 Sand) in any machine, it takes them all and gives back only 1 (e.g. 1 Silicon)
Same on every machine.

**Comment by Prometheus0000** [comment]
The fix was made in LibVulpes, so you need to update that too. See #1359.
