### ISSUE TITLE
Can't land on Luna from Earth with iChunUtil installed.

### ISSUE THREAD

**Issue by bonnedav** [zmaster587/AdvancedRocketry#1367]
## Version of Advanced Rocketry
1.4.0-94
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-36
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
Not crashing.

## Description of the problem
![2018-08-02_21 39 26](https://user-images.githubusercontent.com/14209707/43623544-0b9257c2-969f-11e8-92c7-15de4fba1fa2.png)
Only and always happens with iChunUtil installed. version: 7.1.4

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
