### ISSUE TITLE
Request: Zero model engines and tanks

### ISSUE THREAD

**Issue by DarkGuardsman** [zmaster587/AdvancedRocketry#137]
Started build a massive rocket for lolz, FPS went from 120 to 0 with about 2k+ engines. It would be useful to have engines and tanks that have no models. This way I can ignore visual looks for better performance, I think others might want the same thing. 

Edit: Might also be easy to implement a config that doesn't render the models.

**Comment by zmaster587** [comment]
I've mentioned i was planning on doing that a few dozen times...

**Comment by DarkGuardsman** [comment]
Just make an issue to remind you...

**Comment by zmaster587** [comment]
Things are baked in 1.10, closing
