### ISSUE TITLE
[question] How is decided which issue gets help / which feature is getting added?

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1371]

**Comment by zmaster587** [comment]
Usually Dmoddoomsiruius pokes me with severe issues and I work on them as I have time (which unfortunately is rare these days).  Sometimes I'll pick an issue where a lot of people show interest.

**Comment by Jummit** [comment]
Thanks! I may try to look a little bit more into modding to help creating this mod, so I wanted to see what is currently worked on.
