### ISSUE TITLE
Crashing when opening Satellite bay (issue with betweenlands mod possibly)

### ISSUE THREAD

**Issue by Chloe-Acqua** [zmaster587/AdvancedRocketry#1372]
## Version of Advanced Rocketry
1.12.2-1.4.0-93-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.2.8-34-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/7iAexrbT

## Description of the problem
Crashing when opening the satellite bay on a built rocket to insert satellite.
Crash to Desktop after freezing for a min or two
(Possible issue with betweenlands compatibility?)

**Comment by zmaster587** [comment]
#1372
