### ISSUE TITLE
Biome Changer remote not working - Possible crashing of server

### ISSUE THREAD

**Issue by myles438a** [zmaster587/AdvancedRocketry#1373]
## Version of Advanced Rocketry
1.12.2-1.4.0-95

## Have you verified this is an issue in the latest unstable build
N

## Version of LibVulpes
1.12.2-0.2.8-32

## Version of Minecraft
1.12.2 (modded) forge-14.23.4.2715

## Crash report or log (if applicable)
https://gyazo.com/7639786cfb01144a9c7d047095b0fc4c

## Description of the problem
Shift right click with biome changer remote, it doesn't open the GUI, and it throws that error on the server. 

I implemented this to the file in question for the biome changer. https://github.com/zmaster587/AdvancedRocketry/commit/6b2ccaff8cf76d5de1f415f6d24efb1d5b7164ca

Since this, the satellite isn't even being picked up.

**Comment by AujreliaLyon** [comment]
while i don't have access to see any errors on the server, my remote worked for about half a dozen areas then stopped. This *may* be related to the Remote unexpectedly changing to a biome of ocean. This biome is being used while trying to change land areas but I can't seem to get it to learn more than one biome, OR to change from ocean. ((Is it even possible to select a biome from another world ?))

**Comment by zmaster587** [comment]
What I think needs to happen is that biome.getBiomeName() needs to pass an isRemote check or needs to go though a proxy.  The problem is the getBiomeName does not exist server side for some reason.
