### ISSUE TITLE
Server crash on 1.12.2

### ISSUE THREAD

**Issue by TacticalUniverse** [zmaster587/AdvancedRocketry#1375]
## Version of Advanced Rocketry
[1.4.0-95]
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
[0.2.8-36]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[https://gist.github.com/TacticalUniverse/2776531fa4dccdfc71a6a96537a3b349]

## Description of the problem
[How can you reliably reproduce the problem]
It's only happening when I launch the server on any version of forge for 1.12.2

**Comment by zmaster587** [comment]
This is a metalchests problem, not an AR problem
