### ISSUE TITLE
Freezes on world generation with a custom planetDefs.xml related fatal error.

### ISSUE THREAD

**Issue by Peppernose145** [zmaster587/AdvancedRocketry#1378]
## Version of Advanced Rocketry
1.4.0-95-universal

## Have you verified this is an issue in the latest unstable build
Y

## Version of LibVulpes
1.12.2-0.2.8-33

## Version of Minecraft
1.12.2-forge1.12.1-14.23.2.2625

## Crash report or log (if applicable)
https://pastebin.com/nHbKREUU

## Description of the problem
I created a planetDefs.xml containing multiple custom star systems that include tags to generate random planets and gas giants. When generating the world the log shows errors that includes: 

> java.lang.NullPointerException: null at zmaster587.advancedRocketry.util.XMLPlanetLoader.getMaxNumGasGiants(XMLPlanetLoader.java:78) ~[XMLPlanetLoader.class:unspecified]

I have attached my PlanetDefs.xml in the file below:

[PlanetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/2298253/PlanetDefs.zip)

**Comment by Pythonic-Rainbow** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1343

**Comment by zmaster587** [comment]
Sol is missing the "numGasGiants" entry

**Comment by Peppernose145** [comment]
I went through and added the entry to "Sol", then made sure all other systems have it, but the error still occurs.

The log: https://pastebin.com/2ZGWKyp6

The new PlanetDefs.xml: [PlanetDefs2.zip](https://github.com/zmaster587/AdvancedRocketry/files/2316939/PlanetDefs2.zip)

Any other errors in this XML?

**Comment by Peppernose145** [comment]
Wow, I must have been tired. Thank you. It worked.
