### ISSUE TITLE
observatories and ansteroid mining in 1.10.2

### ISSUE THREAD

**Issue by falizure** [zmaster587/AdvancedRocketry#1379]
advanced rocketry 1.10.2-1.2.5a-jar
libvulpes 1.10.2-0.2.6.jar
minecraft 1.10.2

first of all when attempting to scroll threw the list of asteroids in a observatory scrolling down more then a single asteroid resets the scroll position to the top of the list, meaning you can not see or select roughly the bottom half of the asteroid list, this can also happen occasionally simply when letting go of the mouse while attempting to scroll, this could possibly be solved with a scroll bar or keyboard controls to arrow up or down, second related issue is that when i send a rocket up to mine from the surface using a chip fill of all 3 data types it returns nothing but cobblestone no matter what the contents of the asteroid i selected are, from what i understand filling the mass or composition is supposed to give you a higher ratio of actual ores so its behaving as if the chip has none in those even though i fill all 3 data types before i launch anything.

**Comment by Silfryi** [comment]
That scrolling is mousetweaks.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
