### ISSUE TITLE
Bed's Explode in space

### ISSUE THREAD

**Issue by Mariomette** [zmaster587/AdvancedRocketry#138]
So as in the Nether/End Vanilla beds explode in different dimensions upon right clicking there. I hope this is fixed so I don't have to go to the overworld again and go to the spacestation manually

**Comment by zmaster587** [comment]
Vanilla has a check only for the nether.   Advanced rocketry does not interfere with beds at all, it is more than likely some other mod you have installed in the shadowcrypt pack.
