### ISSUE TITLE
Odd bug makes non-vanilla/AR dimensions such as the Aether or the Twilight Forest "uninhabitable"

### ISSUE THREAD

**Issue by rundownturner4** [zmaster587/AdvancedRocketry#1380]
## Version of Advanced Rocketry
1.4.0-96 (but the bug happens in all 1.12.2 MC versions of Adv Rocketry)
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-37
## Version of Minecraft
1.12.2
## Description of the problem
If you have a dimension mod such as Aether Legacy or Twilight Forest installed together with Advanced Rocketry, and if you actually go to one of the dimensions, you will get the "No Oxygen Detected" warning and start losing health unless you have a spacesuit, and the gravity will be very low aswell, as if you were on the moon.

**Comment by rundownturner4** [comment]
Forgot to mention, all the mobs in the dimension take damage aswell from the "lack of oxygen".

**Comment by rundownturner4** [comment]
I've actually went ahead and edited the planetDefs.xml file, but the problems still persist. Is there anything i forgot to add?
![advancedrocketrytwilightforest](https://user-images.githubusercontent.com/30832634/44474600-55edf080-a633-11e8-93e8-467fa9e84e90.PNG)

**Comment by zmaster587** [comment]
this doesn't look like a valid planetDefs.xml, nor does it look like an xml at all (unless you've modified windows settings)?  Can you upload the saves/name_of_world/advRocketry/planetDefs.xml file?

**Comment by rundownturner4** [comment]
I have actually modified the windows settings, and verified that this is an XML file, see the picture below.
![planetdefs](https://user-images.githubusercontent.com/30832634/44693659-b7fe8980-aa69-11e8-997f-36f1eaa54d59.PNG)

I've also tried using multiple different configs that i've made, but they still didn't fix the problem. Also here is the file you asked for: http://dl.dropboxusercontent.com/s/i977nzbakmyxgea/planetDefs.xml?dl=0 (GitHub doesn't allow XML files to be directly uploaded.)
