### ISSUE TITLE
[Server thread/FATAL] Error while loading

### ISSUE THREAD

**Issue by Nezmin2** [zmaster587/AdvancedRocketry#1381]
## Version of Advanced Rocketry
[AdvancedRocketry-1.12.2-1.4.0-96-universal.jar]
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
[LibVulpes-1.12.2-0.2.8-37-universal.jar]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
[https://goo.gl/MtHbaF]
[[06:12:18] [Server thread/FATAL] [advancedrocketry]: !!!!!!!!!!!!!! An error has occured saving planet data, please report to the mod dev with the entire fml-latest.log file!  This report may contain information relevent to solving a longstanding bug.]

## Description of the problem
[Just Loading game, this FATAL error occured][I am just reporting it for your information]

**Comment by zmaster587** [comment]
Thanks for reporting the issue!

I don't think this issue is related to the issue with planet saving.  It looks like something is messing with mob spawn, which in turn is causing the world to save before AR stuff is loaded.
