### ISSUE TITLE
Two Saturns in planetDefs?

### ISSUE THREAD

**Issue by bigguy132l** [zmaster587/AdvancedRocketry#1382]
## Version of Advanced Rocketry
1.4.0-88
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-32
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
planetDefs.xml has two Saturns by default. One has rings, one doesn't.

**Comment by C1ffisme** [comment]
Erm, where are you getting Advanced Rocketry from? I've been playing with the mod for a while, and usually, the default planets are all named Sol-(dim-number). (Unless this has changed.)

This default config is [hardcoded](https://github.com/zmaster587/AdvancedRocketry/blob/e6b1e919bacb2e55c2504b14a0686ee380916745/src/main/java/zmaster587/advancedRocketry/AdvancedRocketry.java#L1739) into the game, which means there isn't even a default planetDefs.xml. All planetDefs.xml files are created by a 3rd party.

**Comment by dmodoomsirius** [comment]
as @C1ffisme said planetDefs.xml can be made custom by a 3rd party the default one is generated on world load, please remove the one from your world/advRocketry folder and try again.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
