### ISSUE TITLE
Warp core won't accept fuel

### ISSUE THREAD

**Issue by kotja3** [zmaster587/AdvancedRocketry#1384]
MC 1.10.2
libVulpes 0.2.8-37
Advanced rocketry 1.4.0-14
I cannot insert dilithium crystals into input hatch nor by hand, nor by hopper. Breaking doesn't work

**Comment by dmodoomsirius** [comment]
Why did you not use the template as I have set it? If you would have filled that out zmaster and I would have known the mc version, the libVulpes version and the advanced rocketry version.

**Comment by zmaster587** [comment]
That's rather strange, the input hatches have no code to limit what you can put into them.  I've tested this (Forge 12.18.2.2104) and I'm having no issues inserting things like chicken into it, let alone dilithium crystals.  Are you sure you used an input hatch and not an output hatch?

**Comment by kotja3** [comment]
I forgot to mention that i had hopper connected to it, Without it it works well

**Comment by zmaster587** [comment]
So it works by hand but not with the hopper?

**Comment by kotja3** [comment]
No I use Enderio conduit, 
forge 12.18.3.2511

**Comment by zmaster587** [comment]
Tested with EnderCore-1.10.2-0.4.1.66-beta and EnderIO-1.10.2-3.1.193, seems to work fine when the pipe on the chest is set to extract+no redstone activation and the pipe in the input hatch is set to insert.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
