### ISSUE TITLE
When i back from luna , i spawn under bedrock.

### ISSUE THREAD

**Issue by Hawuc** [zmaster587/AdvancedRocketry#1385]
## Version of Advanced Rocketry
[1.4.0-88]
## Have you verified this is an issue in the latest unstable build
No because i am playing ftb continuum and i dont want change any folder of modpack.
## Version of LibVulpes
[0.2.8-32]
## Version of Minecraft
[1.12.2 (FTB Continuum)]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
[when i come back from luna to earth , i am directly falling to under bedrock. But if i fast enough i can survive.this is disgusting because every launch i have to make a new rocekt and i dont have any guarantee to survive when i back. What should i do? should i set launch up another place? And i had check the position of the landing place. it is not rock or ground. it is water maybe this is be reason of my problem ? and as you see my english is vey bad ]

**Comment by zmaster587** [comment]
The issue was fixed in  build 93

**Comment by Hawuc** [comment]
thank u
