### ISSUE TITLE
Random crash when placing down Rocket Assembler

### ISSUE THREAD

**Issue by golyalpha** [zmaster587/AdvancedRocketry#1386]
## Version of Advanced Rocketry
1.12.2-1.4.0-96
## Have you verified this is an issue in the latest unstable build
Yes (happened in it)
## Version of LibVulpes
1.12.2-0.2.8-37
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
[Here ye go](https://github.com/zmaster587/AdvancedRocketry/files/2343142/crash-2018-09-02_11.36.34-client.txt)
## Description of the problem
The crash happened when placing down the "Rocket Assembling Machine" next to a 3x3 launchpad with 4+1 block tall structure tower.
Here is the brid's eye view of the build:
```
[P][P][P]
[P][P][P][T]
[P][P][P][F]
[M][A]

[P] - Launch Pad (layer 1)
[T] - Structure Tower (layers 1-5)
[F] - Fueling Station (layer 2)
[M] - Monitoring Station (layer 2)
[A] - Rocket Assembling Machine (layer 2)
```
The world isn't corrupted, and breaking and after re-loading the world, breaking and replacing the Rocket Assembling Machine doesn't cause a crash again.

Note that there's also a space elevator a few blocks away from the launchpad. Not in contact with the launchpad.

Will update if I find out anything more.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
