### ISSUE TITLE
[Bug][Dupe - Infinte Oxygen] - Gas Chargers only use 10mB oxygen to fill spacesuit

### ISSUE THREAD

**Issue by BasieBrinkie** [zmaster587/AdvancedRocketry#1389]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-96-universal
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-37-universal
## Version of Minecraft
1.12.2
## Description of the problem
Gas chargers filled with oxygen only consume 10 mB of oxygen per 1000 units in each pressure tank (only works if the tanks are equipped on the space suit chest piece). This happens with every kind of pressure tank. For example the low pressure tank is filled with 10mB oxygen, the pressure tank with 20 mB etc.
I also tested this with hydrogen and pressure tanks equipped on the space suit but this functions like expected, drain 1000 mB per 1000 in the tanks. So this problem is fully related to oxygen handling.

Dupe: fill the oxygen tank when equipped on chest and after it filled up remove the tank from the spacesuit and manually put the filled tank in the fill slot of the charger for infinite oxygen.

**Comment by zmaster587** [comment]
Fixed
