### ISSUE TITLE
Gasses Dupe with charge pad

### ISSUE THREAD

**Issue by Cynnimon** [zmaster587/AdvancedRocketry#1393]
## Version of Advanced Rocketry
1.4.0.-88
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
N/A
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
No Crashes

## Description of the problem
Within the charge pad, gas can be infinitely created, no matter the type.
Step 1: Place Gas Charge Pad
Step 2: In second slot of gui, place empty pressurized tank
Step 3: In slot one, place tank of gas (any)
Step 4: Click repeatedly, gas charge pad fills.
Video: https://youtu.be/vws4khRA8OE

This was achieved on a Continuum server, and can also be replicated in single player.

**Comment by dmodoomsirius** [comment]
Please update to the latest version which is build 99 and try to see if this happens. You are using a old version of advanced rocketry. 

Also what version of LibVulpes are you using? I saw you put N/A for it but zmaster and myself like to know. Please make sure that is the latest as well.

**Comment by BasieBrinkie** [comment]
This problem has been solved in version 99 of unstable advanced rocketry builds. Tested myself

**Comment by Cynnimon** [comment]
Thanks a ton guys! :)
