### ISSUE TITLE
trying to open the satellite bay

### ISSUE THREAD

**Issue by TheSGWanderer** [zmaster587/AdvancedRocketry#1396]
I'm playing on all the mods 3 Version: v5.9.8d
Im playing on a friends server and im trying to make my first ship launch everything should be working (i have played this mod alot) but when i build the ship it has a sat bay and a guidence computer aswell as a seat when i try to access the sat bay after building the ship (when the ship becomes an entity not just blocks) i get this error that crashes just my game not the server and i havent found a reason yet and was hoping some one here might be able to help.

This is the direct crash message from the Minecraft launcher: 
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: World (zmaster587.advancedRocketry.world.util.ProviderDummy) does not have BetweenlandsWorldStorage capability

and here is the paste bin link: https://pastebin.com/6waRGDfR

**Comment by zmaster587** [comment]
Can you try build 101?  Betweenlands issue was patched only added 3 days ago.
