### ISSUE TITLE
Non-english players can't select fluid for mining.

### ISSUE THREAD

**Issue by Proha5** [zmaster587/AdvancedRocketry#1397]
AdvancedRocketry-1.12.2-1.4.0-88-universal
Non-english players (russian) can't select fluid for mining. (list of fluids is empty)
I posted problem there:
https://github.com/FTBTeam/FTB-Continuum/issues/456

**Comment by zmaster587** [comment]
Is this still an issue?  I've not been able to replicate it with using locales other than english in my worlds.
