### ISSUE TITLE
Lava acts unexpectedly on planets without a breathable atmosphere

### ISSUE THREAD

**Issue by LenardMiller** [zmaster587/AdvancedRocketry#1398]
## Version of Advanced Rocketry
1.4.0-101
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-37
## Version of Minecraft
1.12.2

## Description of the problem
On planets without a breathable atmosphere when you bucket up generated lava it sometimes gets all desynced (doesn't cause an update, reappears, still sets you on fire, etc.) and no lava can manually be placed into any sort of storage block.

**Comment by zmaster587** [comment]
That's really strange, the atmosphere system is just a tick handler that applies damage to a player on certain planets.

Do you have any other mods installed, is the server/game running slow?
