### ISSUE TITLE
Mekanism Enrichment Chamber Issue

### ISSUE THREAD

**Issue by HFinner** [zmaster587/AdvancedRocketry#1399]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-100-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-37-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
Not able to grind any of the Vulpes Library ore inside of my mekanism enrichment chamber. Not entirely sure if this is the right place to put this but it's worth a shot :)

**Comment by zmaster587** [comment]
Any of the ore, or just aluminum/iridium/titanium?
