### ISSUE TITLE
Station builder does not destroy blocks upon job completion

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#14]
essentialy causing a dupe.
Also actions like copying nbt data is a potential souce of item duplication, consider adding a block whitelist for initial station creation?

**Comment by zmaster587** [comment]
Any item drops from tiles should be removed on the same tick that it is dropped so duping shouldn't occur.  I don't want to whitelist blocks as the number of usable blocks would outweigh the number of blocked blocks, however I can add a blacklist.

**Comment by wormzjl** [comment]
Well it's just from your video, I see that the original station structure was not removed after building completion.

**Comment by zmaster587** [comment]
Ah,I thought I specified that the stations not being removed was a debug thing only and that they would be removed from the world in the release build.  Guess I need to stop being lazy and not show off debug builds XD.  I'll add an annotation to the video to specify that they are removed from the world in the release.

**Comment by wormzjl** [comment]
lol ok
