### ISSUE TITLE
Error: World start, World Gen

### ISSUE THREAD

**Issue by DarkGuardsman** [zmaster587/AdvancedRocketry#140]
http://pastebin.com/2mQvZdSU

Little bit of a mixed crash as it contains advanced rocketry and another mod in the error. Also it doesn't crash the server, but does error out on world load.

**Comment by zmaster587** [comment]
Does this occur without emasher core?

**Comment by DarkGuardsman** [comment]
No clue, its hard enough to replicate with it installed. Something tells me its an edge case...

**Comment by zmaster587** [comment]
seems to be emasher: https://github.com/Emasher/EmashersMods/issues/155
