### ISSUE TITLE
[From Discord] Radio Interferometry for the Discovery of Black Holes and Data Collection

### ISSUE THREAD

**Issue by Silfryi** [zmaster587/AdvancedRocketry#1400]
Endgame multiple multiblock interferometry (VLA) type thing. It requires fine tuning and a large area and power to get data for black holes and asteroids very quickly. It would need a control computer and satellites be used at all, to control orientation. The dishes need to be spaced in a certain configuration so they all work together. The control computer requires iridium so it is after your first asteroid mining.

Smallest size is 6(2 per arm) dishes, and largest is 21 dishes(7 per arm). 10 coils and 5 motors per dish so you can speed it up. 

Data collection for the array setup would be exponential between the two stated endpoints, so bigger gets much better as you go on. Iridium coils, best motors, and all 21 dishes would mean a speed of ~2000 data/ second (100 data/t). For comparison, a copper coiled, basic motor, 6 dish inferometry setup is about 9 satellites worth of data.

The telescopes would be arranged in a Y as the VLA is.

If you were to include black holes as a power source, have them only be discoverable by inferometry, but remember that a spinning black hole gives back ~40% of the energy that the mass was so... LOTS OF POWER

The black hole detection will take 10s of thousands of data so it is a pain to do it with just satellites

This is your only endgame power, with the correct amount of mass fed in(1 item/t), you get TONS of power out.

Satellites are still required for anything with visible light (planet hunting), but will be eclipesd by inferometry otherwise.

World Download with interferometry coming

—————————————— ADDED AFTER DISCORD DISCUSSION —————————-

NEW THINGS :

If you want to be VERY fancy, have the gas giants be only one harvestable gas, but have the inferometry arrray be able to tell you what gas is on a gas giant before you go there and get a mix of “Gasses”, which would be used for two things:  to use on the terraformer for a thicker atmosphere, or to somehow separate into the gasses, but with some loss.

**Comment by Silfryi** [comment]
Here is a world where I did the 2 hours of work that constitute the model in multiblock form and the spacing of the dishes. It only needs AR and LibVulpes. It has the materials for one dish, and the spacing for the smallest array laid out. I would hope it saves you work in the long run because it is useable for the mod.

[](url)https://www.dropbox.com/sh/nvwohajrnz3hxpm/AACbv9qzBPsRh3Bxz1W1q9Jva?dl=0

**Comment by Silfryi** [comment]
New thought: we may have to use a smaller percentage of the mass into energy for black holes, because at 40% efficiency, 1 item per tick is 3,296,000,000,000,000 RF/t, using Reika's 520 W=1 RF/t. That is 3.2 Quadrillion RF/t for 1 item/tick. If we do a 4% conversion; plausible, with a very non-optimal black hole we still have 329 Trillion RF/t. So if we go with about the conversion rate for fission (~.04%), we get 3 Trillion RF/t. So have the generation be @1 item/second, and the generation is 164 Billion RF/t. The end result: get this thing to produce as much power as you want, and it would be fine, as long as it is over a million RF/t.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Perhaps instead you could use the power of the black hole to manufacture dilithium from other materials?

**Comment by Silfryi** [comment]
The power suggestion was from discord as well, just I fleshed it out here. However, I see no way to make something from putting matter through an accretion disk and collecting the radiation emitted as energy, as that is the basis for getting energy out.
What you propose is true fiction, as dilithium, even though fictional, has to have been created through fusion, and therefore, is not going to be harvestable from a black hole. It is not even in the “theoretically possible” department, as all of my proposed black hole ideas are. Lastly, dilithium is common(very) on the moon, so I see no reason for such an endgame way when, to get there, you should have already gotten much dilithium.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Well many mods already have their own endgame energy sources (one of the mods I play with already has its own _extremely_ lategame black hole generator partially implemented), so while I like the idea of building big radio telescopes it would be nice if they could be used for something other than generating lots of power.

**Comment by Silfryi** [comment]
They are, they are used for extremely quick data collection, e.g. for asteroid mining, or something else that needs data.

**Comment by voidsong-dragonfly** [comment]
Closed as other methods of data collection speedup are coming and this suggestion was poorly thought out at the time it was suggested.
