### ISSUE TITLE
Crash after rocket scan

### ISSUE THREAD

**Issue by TheCreeperCow** [zmaster587/AdvancedRocketry#1401]
## Version of Advanced Rocketry
1.4.0
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.2.8-32
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/ge4LivwD

## Description of the problem
I clicked scan the scan was progressing but after the scan finished it crashed the server and the server keeps on crashing and cant be booted back up

**Comment by zmaster587** [comment]
Can you also send the entire server log?  I expect there to be a listing something along the lines of "A TileEntity X has thrown an exception during loading, its state cannot be restored. Report this to the mod author"

**Comment by TheCreeperCow** [comment]
https://pastebin.com/2EPNzn9f :)

**Comment by zmaster587** [comment]
Alright, that makes sense, I've already pushed a patch for next update so that it won't crash, though for now you may have to break and replace the transceiver if you disassemble the rocket though.

**Comment by TheCreeperCow** [comment]
That's all good and all but the issue is that when it's done building the rocket it crashes and breaks the server. So im unable to get me a rocket

**Comment by zmaster587** [comment]
it should stop crashing in build 102

**Comment by zmaster587** [comment]
it'll be on curse within the next few days at the latest.

**Comment by TheCreeperCow** [comment]
Thank you very much closing issue
