### ISSUE TITLE
planetDefs file resets everytime world is reopened/server restarted

### ISSUE THREAD

**Issue by RedBlockFilms** [zmaster587/AdvancedRocketry#1402]
## Version of Advanced Rocketry
1.4.0-102
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-37
## Version of Minecraft
1.12.2

## Description of the problem
I am running AdvRocketry on a server, with a custom planetDefs.xml file. Whenever I restart the server, it seems all my custom planets (and the xml file) are reset. I have to put the xml file back in when this happens. I've also noticed that only sometimes does it generate more, and others it leaves just earth and luna with nothing else

**Comment by zmaster587** [comment]
Would you be able to upload a server log from before it resets and another server log from the startup after, additionally can you provide the world/advRocketry/temp.dat file?
