### ISSUE TITLE
When I go to the end there's no oxygen and very low gravity

### ISSUE THREAD

**Issue by pricken2000** [zmaster587/AdvancedRocketry#1403]
## Version of Advanced Rocketry
1.4.0-88
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8-32
## Version of Minecraft
1.12.2

## Description of the problem
When I go to the end there's no oxygen and very low gravity.

**Comment by Silfryi** [comment]
What are the dimensions in the blacklist for converting to planets?

**Comment by slappav** [comment]
Could you attach your advancedRocketry.cfg and planetDefs.xml ?
