### ISSUE TITLE
Rocket return flight to Earth lands in the wrong location

### ISSUE THREAD

**Issue by MagmarFire** [zmaster587/AdvancedRocketry#1405]
## Version of Advanced Rocketry
1.4.0-102
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-37
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
I took off from Earth to the Moon to replenish my oil (BC) but took a pit stop at my space station to build a warp core (not a warp controller). Then I went and did a return trip to Earth and found myself at -1535,-1535 on reentry, which ends up being a Deep Ocean biome. Now, it's not impossible for me to refuel the rocket and fly back up to the moon and space station again--I just need to set a waypoint and painstakingly fly to and from my home to refuel it instead of having it land on the landing pad like it was supposed to.

**Comment by zmaster587** [comment]
Did you go to your space station from earth before going to the moon?

**Comment by slappav** [comment]
I spent a couple of hours trying to figure out how this works the other day. This is what I found out (hoping that someone corrects me if I'm wrong).

The station ID chip saves the planet coordinates when flying from a planet to the space station. It can save coordinates for multiple planets. When using the station ID chip to fly from the station to the planet it's orbiting, it lands on the coordinates recorded for that planet. You can see the coordinates for the planet you are orbiting by hovering the cursor over the station ID chip. If it does not have any coordinates saved for that planet, you will land on the same coordinates that you took off from on the space station. For station 1, this is somewhere around -1500,-1500.

Planet ID chips does not save the coordinates for reentry. So when using those, you will always end up on the same coordinates as your takeoff coordinates.

**Comment by slappav** [comment]
I have a few ideas, I think would make them easier to understand and use. Not sure if this is the right thread for it though.

**Comment by MagmarFire** [comment]
> Did you go to your space station from earth before going to the moon with the same rocket?
> 
> Reasoning:
> space stations don't exactly track the location they orbit around 9you can get tot the station from many points), the rockets do that.
> so if you go from earth, to the moon, to a space station, to earth, the rocket has no idea where to land from the space station because it never went from earth to the station.

Your reasoning seems spot-on in regards to what I was doing. For now, I should just avoid going from one to the other directly without a linker as a workaround, then, right?

**Comment by Mitchel75814** [comment]
It’s a pretty good system. The one part where I think it could use improvement is for example if you take off from earth at 0,0 to the station then want the same rocket to land at 100,100 on planet 1 there doesn’t appear to be a clear way.

I used Nbtedit and it shows the list of planet id’s and the coords so I just edited it there and it worked.

What about if you right click the station Id chip it shows a gui with tracked planets and their coords and then allows you to change the coords per planet?

**Comment by cooljackgi** [comment]
Any solution for this problem without an extra mod?

**Comment by slappav** [comment]
Would be good if the "dest: [planet]" when you're about to take off had the x,z coordinates below it. Would make it so much easier for people to understand what's going on.

Also, being able to modify the coordinates for the planet one's orbiting around would be a HUGE help. This would make server play SO much more enjoyable. (we just ended up using rftools teleporting to get to shared planet bases on my server, which is a shame)

**Comment by zmaster587** [comment]
I'm not a fan of the idea of requiring users to have to actually enter in coordinates since it feels kinda like it's breaking the magic of it.  But I do agree, the current system is kinda clunky.  I'd prefer to at least require the player to have at least gone to the base at least once.

What if, instead of the player entering coordinates, they could right click with the ID chip to program it with a destination.  Shift right clicking on the chip would open a UI that allowed players to select which destination (renamable) and delete the currently selected dest if desired?

**Comment by slappav** [comment]
I totally agree. But this method requires you to have 2 ID chips, since one will be overwritten on your way back to the station. Could the docking pads be used on planets in the same way they are used on stations?

**Comment by zmaster587** [comment]
You can in a way, you can link linkers to docking pads.  If a rocket is taking off from a docking pad and the docking pad has a linker in it, the rocket will go to the destination programmed in the linker.  It's a bit cumbersome I admit, but it can do what you describe i think.

I did spend the last two days developing a system that would let you use one station Id chip to be able to select arbitrary destinations:
"Last" is always the location you arrived from, but you can manually set and choose other locations if you like (and ofc name them).  They're unique per-planet, so if you move your station to mars from earth, you'll get a different set of destionations for Mars descent.  Basically if you set destinations on earth, they'll only show up when you're prepping for a descent to earth.  If you set destinations on mars with the same chip, you'll only see them when orbiting mars, etc.  You're also not limited to two destionations, I just only have two for the screen cap.  If you copy the chip in the satellite builder then the destionations will be copied to the new chip as well in case you want to hand them out to friends.
![image](https://user-images.githubusercontent.com/3536685/56455548-7b034200-632d-11e9-9ea5-32370344c20d.png)
![image](https://user-images.githubusercontent.com/3536685/56455549-7dfe3280-632d-11e9-866c-2727eac91bd7.png)

**Comment by slappav** [comment]
I love it! When can I try it?!

So you can add a location by 1. taking off from a new location, 2. right clicking with the ID chip on the ground and 3. adding it by typing the coordinates in the "Add New" selection?

Could you show the location name (or coordinates if there's no name) on the screen before takeoff?

**Comment by zmaster587** [comment]
Right now it's just 1 and 3, I could make it so right clicking on the ground would add a new location if that feels more obvious though.

Yeah I can, right now it only shows location, but I can update it to show the name too.

**Comment by zmaster587** [comment]
![image](https://user-images.githubusercontent.com/3536685/56463530-441c4300-63a4-11e9-9a16-ef86ee491ae3.png)

**Comment by slappav** [comment]
Yes. Right-clicking on the ground would be a great addition. Since that will make it easier to fine tune a location.
