### ISSUE TITLE
Entering the Spacestation ends with Fatal Error(Sponge server exclusive)

### ISSUE THREAD

**Issue by Silentstone04** [zmaster587/AdvancedRocketry#1406]
## Version of Advanced Rocketry
[1.4.0-101]
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
[0.2.8-37]
## Version of Minecraft
[1.12.2]
## Server Version
Sponge Forge 1.12.2-2705-7.1.0-BETA.3442
## Crash report or log (if applicable)
https://pastebin.com/kxMGUVE9

## Description of the problem
all players are kicked by the server if you want to fly with the rocket to the Spacestation
A Fatal Error .....

**Comment by Silfryi** [comment]
Do you have any graphics altering mods, or sky altering mods?

**Comment by Silentstone04** [comment]
we play the modpack Continuum on a huge server so it only works on Sponge
whether graphics altering mods or sky altering mods are present, I can not say with my knowledge

**Comment by Silfryi** [comment]
Try to reproduce the issue(Not on your server) with just forge (not sponge) on Continuum.

**Comment by Silentstone04** [comment]
in the single player it works, with my knowledge I have no idea how to make a forge server to run
Sorry

**Comment by Silfryi** [comment]
Then this sounds like a Sponge server error, and I cannot help Zmaster any more. To be more concise, could you change the name of the issue to “Entering the Spacestation ends with Fatal Error(Sponge server exclusive)”

**Comment by takarabako** [comment]
Updating to 1.4.1-113 should fix the kick all player thing. And the client crash is due to the star info not recieved from server (sponge only) so it crashed trying to get the sun color (star is null). See #1439 for detail.
