### ISSUE TITLE
Can't open storage in rocket

### ISSUE THREAD

**Issue by QuicksilverBou** [zmaster587/AdvancedRocketry#1407]
## Version of Advanced Rocketry
1.4.0-102
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-39
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
After assembling rocket I had try open an any inventory (chest, shulker box, any storage from other mods) in roket, it just close at once.
But Any block from AR opens fine.

**Comment by QuicksilverBou** [comment]
Opening an inventory from Tincer's Construct will crash the game.

**Comment by zmaster587** [comment]
@QuicksilverBou Can you open a seperate issue from that and post the crash report and relevent info.  I don't think it's quite the same issue
