### ISSUE TITLE
Rocket Networking Possible CME

### ISSUE THREAD

**Issue by Mariomette** [zmaster587/AdvancedRocketry#141]
http://pastebin.com/yZzVGr6w is what happened

**Comment by DarkGuardsman** [comment]
Most likely is just MC being MC, but seeing as your rocket was in the area it could be related. Mariomette at the time was adding and removing items from barrels on a space station.

**Comment by zmaster587** [comment]
Need to know what you were doing immediately before this

**Comment by DarkGuardsman** [comment]
I think this issue was fixed in your last patch to the thread, going to close.
