### ISSUE TITLE
Aether 2 with no Oxygen

### ISSUE THREAD

**Issue by Charismara** [zmaster587/AdvancedRocketry#1411]
## Version of Advanced Rocketry
1.4.1-103
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
0.2.8-39
## Version of Minecraft
1.12.2

## Description of the problem
In addition to Advanced Rocketry I also have the Mod Aether 2 installed and if I enter the dimension of Aether then the message appears that no oxygen exists and I suffocate. How can I fix this?

**Comment by Silfryi** [comment]
#1403, attach planetdefs.xml and advancedrocketry.cfg

**Comment by Charismara** [comment]
[advancedrocketry.cfg](https://pastebin.com/smFvTSqy)
[planetDefs.xml](https://pastebin.com/E6RjvNTx)

**Comment by Silfryi** [comment]
What is your Aether II config?

**Comment by Silfryi** [comment]
You currently have the Aether as a planet, to be exact Sol-5 as a gas giant for the necromancer dim. And the moon is currently dim-4, the Aether dim. You should change Aether dimensions to somewhere around 100, and then see if that works.

**Comment by Charismara** [comment]
Okay, I'll try it.

**Comment by Charismara** [comment]
Now I'm on the moon when I go to the Aether.

**Comment by Silfryi** [comment]
Find some unused for planets dims and try? That’s what I can say.

**Comment by Charismara** [comment]
I now just edited the dim with the commands:
```
advRocketry planet 4 set gravitationalMultiplier 1.0
advRocketry planet 4 set atmosphereDensity 100
```
now it's okay
