### ISSUE TITLE
planetDef.xml Corruption

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1414]
## Version of Advanced Rocketry
1.4.1-103
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.2.8-39
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://gist.github.com/NillerMedDild/423c541a9731d4bf9aa8a77388b1d0d0

## Description of the problem
Sometimes when my server is shutdown unexpectedly, by for example Windows Update or a power outrage, the planetDef.xml will corrupt and prevent the world from loading.

**Comment by zmaster587** [comment]
Recent updates to the file writing code should fix this, let me know if you have issues on 107 or later

**Comment by NillerMedDild** [comment]
Will do, thank you very much :)

**Comment by NillerMedDild** [comment]
The issue is still present. Making a new issue :)
