### ISSUE TITLE
Client is crashing at server join

### ISSUE THREAD

**Issue by djdanby** [zmaster587/AdvancedRocketry#1415]
## Version of Advanced Rocketry
1.12.2-1.4.1-104
## Have you verified this is an issue in the latest unstable build
Yes. Before i use the version 104, i had used version 96. No crashes when i join server.
I have now again to test the version 96 loaded on the server. Now the client does not crash anymore. The error is clearly at the 104. 

Older version that i used before: LibVulpes 0.2.8-37 and AdvancedRocketry 1.4.0-96. This Versions make any Error messages in the Server logs, but i can join the server.
## Version of LibVulpes
1.12.2-0.2.8-39
## Version of Minecraft
1.12.2
##Forge Version
forge-1.12.2-14.23.5.2768-universal.jar
## Crash report 
https://pastebin.com/jcTkunLQ

## Description of the problem
When joins the server, the screen turns white and shortly afterwards the game crashes.

**Comment by zmaster587** [comment]
Welp, I guess that solves the question as to whether it occurs without sponge and/or optifine

**Comment by Agrax** [comment]
I think i might have the same exact issue with AR. Unless im just tremendously dumb. Here's the [log](https://pastebin.com/LV6beJ6K)

**Comment by zmaster587** [comment]
Can you upload the planetDefs xml and startup log?

**Comment by Agrax** [comment]
https://pastebin.com/cesCGYEu

Cannot find planetDefs.xml (we haven't made one. Shouldn't it be created automatically or smth?). The weirdest thing is that it works perfectly on a dedicated machine, but fails on localhost o.O

**Comment by zmaster587** [comment]
It should be in the <world folder>/advRocketry/planetDefs.xml, and it should be created automatically.

Works perfectly on dedicated machine but fails on localhost.... that is strange, but helpful information.

**Comment by LemADEC** [comment]
Issue is reproduced on the Rebirth3 modpack.
https://gist.github.com/LemADEC/e90cc1d70cf54e7faaf9422149bdb654 (planetDefs.xml)
AdvancedRocketry-1.12.2-1.4.1-108-universal

**Comment by FallenEagle1** [comment]
Kind of an update on this, had someone come by with this same crash coming up. For testing they updated the server and client(s) to v111 but same issue. For the moment they just set `PlanetSkyOverride, StationSkyOverride, and overwoldSkyOverride` to false and that is allowing them to not crash currently.
https://pastebin.com/QjqF2eig This is the crash when using v111

**Comment by zmaster587** [comment]
@FallenEagle1  that makes sense since it's a thing with the sky renderer.
@LemADEC what version, latest as of Nov 1?

**Comment by FallenEagle1** [comment]
Just thought I'd mention it, since I was thinking that v109 was to fix the issue.

**Comment by zmaster587** [comment]
I thought it would but apparently not.  It's hard to fix an issue I've not been able to recreate.  I'll keep looking.

**Comment by LemADEC** [comment]
@zmaster587 my comment said it was AdvancedRocketry-1.12.2-1.4.1-108-universal . What do you mean by latest?

**Comment by zmaster587** [comment]
@LemADEC I meant of Rebirth3

**Comment by LemADEC** [comment]
It was on Rebirth3-1.12.2-r13-hotfix2.

**Comment by zmaster587** [comment]
Above patch should have fixed it
