### ISSUE TITLE
Texture pack compatibility

### ISSUE THREAD

**Issue by QuintenMC** [zmaster587/AdvancedRocketry#1416]
## Version of Advanced Rocketry
[AdvancedRocketry-1.12.2-1.4.1-104-universal]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[LibVulpes-1.12.2-0.2.8-39-universal]
## Version of Minecraft
[1.12.2]
## Description of the problem
![2018-10-13_18 13 01](https://user-images.githubusercontent.com/35098735/46907577-f31f2400-cf14-11e8-82aa-d53495decbe9.png)
![2018-10-13_18 22 18](https://user-images.githubusercontent.com/35098735/46907582-fca88c00-cf14-11e8-9101-e7f632cad7c6.png)

[space helmet not compatible with texture packs (resource pack : conquest) see screenshots above]

**Comment by QuintenMC** [comment]
yes i have other mods installed but normally they aren't the problems since in vanila texture it works fine

**Comment by zmaster587** [comment]
Some mods DO modify texture loading and can cause incompatibilities with texture packs even when vanilla textures work fine.  So I wouldn't nessessarily make that assumption.  I'll look into it though

**Comment by zmaster587** [comment]
![image](https://user-images.githubusercontent.com/3536685/46908562-8a26b480-cef2-11e8-93a8-abbf0e1454ed.png)
Cannot replicate with AR and libvulpes alone.
