### ISSUE TITLE
Can't load world with other mod ores in asteroid config

### ISSUE THREAD

**Issue by Feafroth** [zmaster587/AdvancedRocketry#1418]
## Version of Advanced Rocketry
1.4.1-105, 1.4.1-106
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
0.2.8-39
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
not crashlog but exception: https://pastebin.com/9j1bZHcS
## Description of the problem
Trying to load world with asteriod cotfig with ores from Immersive Engineering and Applyed Energistic in console appears exception and trough several seconds either world closed or minecraft client stuck to "window not responce"
astiroidConfig.xml

\<Asteroids>
	\<asteroid name="Iron-Nickel Asteroid" distance="10" mass="200" massVariability="0.5" minLevel="0" probability="15" richness="0.2" richnessVariability="0.5">
		\<ore itemStack="minecraft:iron_ore" chance="15" />
		\<ore itemstack="immersiveengineering:ore 4" chance="10" />	\
		\<ore itemStack="minecraft:redstone_ore" chance="10" />
	\</asteroid>
	\<asteroid name="Galena Asteroid" distance="10" mass="200" massVariability="0.5" minLevel="0" probability="10" richness="0.2" richnessVariability="0.5">
		\<ore itemstack="immersiveengineering:ore 3" chance="15" />	\
		\<ore itemstack="immersiveengineering:ore 2" chance="15" />	\
		\<ore itemStack="minecraft:redstone_ore" chance="10" />
	\</asteroid>
	\<asteroid name="Small Luxury Asteroid" distance="10" mass="100" massVariability="0.5" minLevel="0" probability="5" richness="0.2" richnessVariability="0.5">
		\<ore itemStack="minecraft:gold_ore" chance="10" />
		\<ore itemstack="minecraft:diamond_ore" chance="5" />
		\<ore itemStack="minecraft:redstone_ore" chance="10" />
		\<ore itemstack="appliedenergistics2:quartz_ore" chance="10" />	\
	\</asteroid>
	\<asteroid name="Titan-Aluminum Asteroid" distance="10" mass="200" massVariability="0.5" minLevel="0" probability="15" richness="0.2" richnessVariability="0.5">
		\<ore itemstack="libvulpes:ore0 8" chance="10" />				\
		\<ore itemstack="immersiveengineering:ore 1" chance="10" />	\
		\<ore itemStack="minecraft:redstone_ore" chance="10" />
	\</asteroid>
	\<asteroid name="Tin-Copper Asteroid" distance="10" mass="200" massVariability="0.5" minLevel="0" probability="15" richness="0.2" richnessVariability="0.5">
		\<ore itemstack="libvulpes:ore0 5" chance="10" />				\
		\<ore itemstack="immersiveengineering:ore" chance="10" />		\
		\<ore itemStack="minecraft:redstone_ore" chance="10" />
	\</asteroid>
	\<asteroid name="Iridium Enriched asteroid" distance="100" mass="25" massVariability="0.5" minLevel="0" probability="0.75" richness="0.2" richnessVariability="0.3">
		\<ore itemStack="minecraft:iron_ore" chance="25" />
		\<ore itemStack="libvulpes:ore0 10" chance="5" />
	\</asteroid>
\</Asteroids>

Names of ores taken from advanced tooltips and "/mt hand" command of minetweaker

**Comment by zmaster587** [comment]
Can you upload the server log too? I expect there to be errors printed during loading.

**Comment by zmaster587** [comment]
I also noticed you're using "itemstack" in some places where you need to have "itemStack", it is case sensative.

**Comment by Feafroth** [comment]
Sorry my inattention. It was late evening after workday and i was tired. After fix this typo everithing is OK

**Comment by zmaster587** [comment]
Fair enough, and thanks for replying that it's fixed, not many people do that and issues tend to get left open because of that.
