### ISSUE TITLE
rocket monitoring station

### ISSUE THREAD

**Issue by quentfr21** [zmaster587/AdvancedRocketry#142]
hello

Forge 1614
Advanced Rocketry 0.6.1

when i try to link rocket monitoring station and a builded rocket it tell me object is too far

http://rousteurs.free.fr/pb.png

another thing how can i set the planed id chip to a selected planet ?

sorry for my english and thanks in advance

**Comment by zmaster587** [comment]
I'll look into the too far thing tonight.  To set the planet id chip you need to put it into the Guidance Computer in the rocket and when the rocket is built, then shift+right click to open the rocket's interface.  Inside should be a select planet button.

**Comment by quentfr21** [comment]
@zmaster587  thanks for info

**Comment by zmaster587** [comment]
Should not work on code after midnight, I'll have it fixed for next build
