### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by happymy** [zmaster587/AdvancedRocketry#1422]
## Version of Advanced Rocketry
[AdvancedRocketry-1.12.2-1.4.1-104-universal or higher]
## Have you verified this is an issue in the latest unstable build
YES
## Version of LibVulpes
[LibVulpes-1.12.2-0.2.8-39-universal]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[NO Crash]

## Description of the problem
If you use BetterFps MOD and build space elevator. 
or
Use SEUS or SM or other shaderpack（except KUDA-Shaders v6.1 Legacy ） .

The screen is very dark.  you can not see anything.

**Comment by happymy** [comment]
![image](https://user-images.githubusercontent.com/44517078/47599858-7e0a1f00-d9e9-11e8-8de3-e5ada468cb04.png)

**Comment by zmaster587** [comment]
is it only with the space elevator or does this happen with other things too?

**Comment by zmaster587** [comment]
I'm not able to replicate:
Forge 1.12.2-14.23.5.2768
BetterFps-1.4.8.jar
OR
OptiFine_1.12.2_HD_U_E2 + SEUS-Renewed-1.0.0

What version of forge are you using?

**Comment by zmaster587** [comment]
I did make a few changes to the render system anyway since a few entities (the space elevator, planet sky, rocket builder) were still using components that have been changed since 1.7.

Since I cannot replicate the issue I have no idea if it'll help or not, but if you like you can give it a go.
[AdvancedRocketry-1.12.2-1.4.1-universal.zip](https://github.com/zmaster587/AdvancedRocketry/files/2522160/AdvancedRocketry-1.12.2-1.4.1-universal.zip)

**Comment by happymy** [comment]
I am so sorry . I do more test.
if use "AdvancedRocketry-1.12.2-1.4.1-108-universal" then
BetterFps-1.4.8 and space elevator you get NO ERROR. that is fine.

But shaderpack Error is same.

Forge 1.12.2-14.23.5.2768 or 14.23.4.2739

I make test package.
SEUS-Renewed-1.0.0 and KUDA-Shaders v6.1 Legacy is OK NO ERROR.
But most shaderpack get error.
you can find in:
http://shaders.wikia.com/wiki/Shader_Packs

**Comment by happymy** [comment]
tested shaderpacks:
[shaderpacks.zip](https://github.com/zmaster587/AdvancedRocketry/files/2522388/shaderpacks.zip)

**Comment by happymy** [comment]
I need help
https://github.com/zmaster587/AdvancedRocketry/issues/1423

Unmanned Vehicle not work :(

**Comment by zmaster587** [comment]
As far as I can tell, it's the sky modification that's causing issues with SEUS-v11.0 at least.  Setting PlanetSkyOverride should be a workaround if you want to keep using that particular shader.

**Comment by happymy** [comment]
if set overworldSkyOverride=false
That is in NO Error in the overworld .
But set
PlanetSkyOverride=false or true
StationSkyOverride=false or true

Get ERROR in space Station and Luna. I do not test other plant.

TEST IN 
AdvancedRocketry-1.12.2-1.4.1-108-universal or https://github.com/zmaster587/AdvancedRocketry/files/2522160/AdvancedRocketry-1.12.2-1.4.1-universal.zip
Forge 1.12.2-14.23.5.2770
