### ISSUE TITLE
Unmanned Vehicle not work

### ISSUE THREAD

**Issue by happymy** [zmaster587/AdvancedRocketry#1423]
## Version of Advanced Rocketry
[AdvancedRocketry-1.12.2-1.4.1-104-universal or higher]
## Have you verified this is an issue in the latest unstable build
YES
## Version of LibVulpes
[LibVulpes-1.12.2-0.2.8-39-universal]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[NO Crash]

## Description of the problem

Unmanned Vehicle cannot Lunch
linked！gas plant！Fueled ！Scaned ! Build! all pass green light! and push lunch button .
Nothing happened. no dump Unmanned Vehicle.

![image](https://user-images.githubusercontent.com/44517078/47599949-90855800-d9eb-11e8-928f-1d02aaf90258.png)

![image](https://user-images.githubusercontent.com/44517078/47599951-9f6c0a80-d9eb-11e8-8659-65ccec2264e5.png)

![image](https://user-images.githubusercontent.com/44517078/47599954-abf06300-d9eb-11e8-830d-fbed34dd04e5.png)

![image](https://user-images.githubusercontent.com/44517078/47599958-b90d5200-d9eb-11e8-9d46-09898559f15e.png)

**Comment by happymy** [comment]
I need help . that is not work. I just follow：
https://www.youtube.com/watch?v=rLI-2YZ6DXM
https://www.youtube.com/watch?v=cCAY79JIcjI
https://www.youtube.com/watch?v=LDBxxTv_2Lk

I try but is not work.
linked！
gas plant！
Fueled ！
Scaned ! 
Build!
all pass green light! and push lunch button .
Nothing happened. no dump Unmanned Vehicle.

why?

**Comment by zmaster587** [comment]
Can you take a screencap of the interface on the rocket, have you verified that the planet you're in orbit around has gasses set in the <saves>/world/advRocketry/planetDefs.xml?

**Comment by happymy** [comment]
I didn't edit planetDefs.xml.
I build NEW rocket. NOT WORK
linked and fueled.
I read planetDefs.xml. this plant is gas plant.get all 3 gas.




![2018-10-29_19 56 20](https://user-images.githubusercontent.com/44517078/47648893-6e8c0100-dbb6-11e8-85a3-c9d291800d94.png)
![2018-10-29_19 59 39](https://user-images.githubusercontent.com/44517078/47648913-7e0b4a00-dbb6-11e8-85f0-c3165aab97e4.png)
![2018-10-29_19 59 47](https://user-images.githubusercontent.com/44517078/47648919-82376780-dbb6-11e8-9b57-73eb2c9708b9.png)
![2018-10-29_19 59 54](https://user-images.githubusercontent.com/44517078/47648921-8499c180-dbb6-11e8-96f9-2b0a38a26455.png)
![2018-10-29_20 00 01](https://user-images.githubusercontent.com/44517078/47648924-882d4880-dbb6-11e8-859f-4d0a0599367d.png)
![2018-10-29_20 00 51](https://user-images.githubusercontent.com/44517078/47648938-911e1a00-dbb6-11e8-99f2-888da86e804b.png)
![2018-10-29_20 01 01](https://user-images.githubusercontent.com/44517078/47648952-9f6c3600-dbb6-11e8-8538-2a98d2bd1b90.png)
![2018-10-29_20 01 08](https://user-images.githubusercontent.com/44517078/47648957-a3985380-dbb6-11e8-8cd1-efab5b48cb1d.png)

**Comment by zmaster587** [comment]
Does the rocket monitoring station register than the rockeet is fueled?

**Comment by zmaster587** [comment]
Should be fixed for next build

**Comment by happymy** [comment]
NO error info
that is linked and fueled

**Comment by happymy** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1422

set
PlanetSkyOverride=false
StationSkyOverride=false

NOT work

**Comment by happymy** [comment]
AdvancedRocketry-1.12.2-1.4.1-110-universal

fixed this bug 
thank you !!!
