### ISSUE TITLE
Rocket unloader takes satellites from rocket

### ISSUE THREAD

**Issue by nullpointspace** [zmaster587/AdvancedRocketry#1427]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-108-universal
## Have you verified this is an issue in the latest unstable build
yes
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-39-universal
## Version of Minecraft
1.12.2
## Description of the problem
Forge: forge-1.12.2-14.23.4.2758-universal

rocket unloader takes satellites from rocket

**Comment by zmaster587** [comment]
Should it not?

**Comment by nullpointspace** [comment]
Translated translate.google.com:

Does he have to take satellites, they are only sent to orbit and can not be prey in missions
The optional ban on unloading newly loaded items will allow creating more versatile launch pads.
Now need to use another launch pad if need to send the cargo into orbit.
