### ISSUE TITLE
Gregtech: CE + AR crash at start

### ISSUE THREAD

**Issue by Agrax** [zmaster587/AdvancedRocketry#1429]
## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.4.1-109-UNSTABLE build -109 for 1.12.2
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
LibVulpes 1.12.2-0.3.0-42-UNSTABLE build -42 for 1.12.2
## Version of Minecraft
1.12.2
## Version of Gregtech
.120
## Crash report or log (if applicable)
https://pastebin.com/Hsz6QWnK

## Description of the problem
Crash at the start. More info in the log

**Comment by zmaster587** [comment]
You know... it might actually help if the version on curse was the latest version of libvulpes

**Comment by zmaster587** [comment]
Build 43 of libvulpes should fix this

**Comment by Agrax** [comment]
https://gitlab.com/GregTechCE/GregTech/-/jobs

Just fot the future reference. All the newest GT builds are stored here. CF tends to be outdated af usually
