### ISSUE TITLE
iridium in meteorites

### ISSUE THREAD

**Issue by QuintenMC** [zmaster587/AdvancedRocketry#1430]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-110-universal

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
LibVulpes-1.12.2-0.3.0-42-universal

## Version of Minecraft
1.12.2

## Description of the problem
the observatory said 1 iridium ore 0+/- (see picture) but when i send my rocket it came with only 7 iron ore i had 1K on all 3 items

![2018-11-01_14 47 42](https://user-images.githubusercontent.com/35098735/47855994-57cbf100-dde6-11e8-9128-c86d4d243957.png)
![2018-11-01_14 58 21](https://user-images.githubusercontent.com/35098735/47856119-aed1c600-dde6-11e8-8b20-2261c564a4aa.png)

**Comment by nullpointspace** [comment]
> ## Версия Advanced Rocketry
> AdvancedRocketry-1.12.2-1.4.1-110-универсальный
> 
> ## Вы подтвердили, что это проблема в последней нестабильной сборке
> да
> 
> ## Версия LibVulpes
> LibVulpes-1.12.2-0.3.0-42-универсальный
> 
> ## Версия Minecraft
> 1.12.2
> 
> ## Описание проблемы
> обсерватория сказала 1 иридиевую руду 0 +/- (см. рисунок), но когда я отправляю свою ракету, она пришла с 7 железными рудами, у меня было 1K на всех 3 предметах
> 
> ![2018-11-01_14 47 42](https://user-images.githubusercontent.com/35098735/47855994-57cbf100-dde6-11e8-9128-c86d4d243957.png)
> ![2018-11-01_14 58 21](https://user-images.githubusercontent.com/35098735/47856119-aed1c600-dde6-11e8-8b20-2261c564a4aa.png)

Go to Asteroid Configuration (config\advRocketry\asteroidConfig.xml) and update the richness parameter from 0.2 to 0.3

**Comment by nullpointspace** [comment]
Go to Asteroid Configuration (config\advRocketry\asteroidConfig.xml) and update the richness parameter from 0.2 to 0.3

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by QuintenMC** [comment]
it's fixed i'm full on living on iridium atm
