### ISSUE TITLE
Star/Gas Giant not rendering in sky

### ISSUE THREAD

**Issue by Golrith** [zmaster587/AdvancedRocketry#1431]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-110-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
LibVulpes-1.12.2-0.3.0-44-universal
## Version of Minecraft
1.12.2
## Description of the problem
I've generated a gas giant with a closely orbiting moon, and the gas giant closely orbits the star.
But when visiting the moon, there's no sign of the gas giant or star in the sky.

	    <planet name="Gigantica" DIMID="5">
			<isKnown>True</isKnown>
			<GasGiant>true</GasGiant>
			<orbitalDistance>10</orbitalDistance>
			<planet name="Infernus" DIMID="6">
				<isKnown>false</isKnown>
				<gravitationalMultiplier>50</gravitationalMultiplier>
				<orbitalDistance>10</orbitalDistance>
				<rotationalPeriod>2400</rotationalPeriod>
				<atmosphereDensity>100</atmosphereDensity>
				<biomeIds>advancedrocketry:hotdryrock</biomeIds>
            </planet>
        </planet>

**Comment by Golrith** [comment]
Edit, discovered it's the closeness that prevents the rendering, at distance 15, everything renders in the sky.

**Comment by zmaster587** [comment]
Are you referring to render distance?  
```
	<star name="Alykitt" temp="120" x="75" y="200" size="1.0" numPlanets="0" numGasGiants="0" >
		<planet name="Sol-102" DIMID="102">
			<isKnown>false</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>0.8,0.62229246,0.0</skyColor>
			<gravitationalMultiplier>114</gravitationalMultiplier>
			<orbitalDistance>1</orbitalDistance>
			<orbitalPhi>-1</orbitalPhi>
                        <GasGiant>true</GasGiant>
			<rotationalPeriod>16199</rotationalPeriod>
			<atmosphereDensity>200</atmosphereDensity>
			<biomeIds>advancedrocketry:hotdryrock</biomeIds>
			<planet name="Sol-102: 0" DIMID="103">
				<isKnown>false</isKnown>
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>0.0,0.77448624,1.0</skyColor>
				<gravitationalMultiplier>72</gravitationalMultiplier>
				<orbitalDistance>10</orbitalDistance>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>64300</rotationalPeriod>
				<atmosphereDensity>23</atmosphereDensity>
				<seaLevel>73</seaLevel>
				<biomeIds>advancedrocketry:moon,advancedrocketry:moondark</biomeIds>
				<oceanBlock>advancedrocketry:oxygenfluid</oceanBlock>
			</planet>
			<planet name="Sol-102: 1" DIMID="104">
				<isKnown>false</isKnown>
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>0.0,0.86020344,1.0</skyColor>
				<gravitationalMultiplier>35</gravitationalMultiplier>
				<orbitalDistance>1</orbitalDistance>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>559766</rotationalPeriod>
				<atmosphereDensity>14</atmosphereDensity>
				<biomeIds>advancedrocketry:moon,advancedrocketry:moondark</biomeIds>
			</planet>
			<oceanBlock>minecraft:lava</oceanBlock>
		</planet>
</star>
```
Render distance 6
Advanced Rocketry build 112, libvulpes build 44, forge 14.23.4.2739
![image](https://user-images.githubusercontent.com/3536685/48299068-d59e9500-e495-11e8-8eda-fc0b4ce34ff1.png)

**Comment by Golrith** [comment]
Not render distance, the actual OrbitalDistance set in the JSON.
Anything below 12 does not show the planet/moon/star in the sky for me. As soon as I set it to 15 then it displays.


Separate issue on rendering (nothing major), can you push the Size variable to planets, so that this variable controls the size of the planet/moon on the planet selector, and not the actual gravity value? A planets size is not dependent on just it's Gravity.
Purely just a visual enhancement.

**Comment by zmaster587** [comment]
I can't replicate it, that above screenshot is with <orbitalDistance>1</orbitalDistance>
