### ISSUE TITLE
RenderPlanetarySky.drawStar Null Pointer Exception

### ISSUE THREAD

**Issue by Rsslone** [zmaster587/AdvancedRocketry#1433]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-112-universal
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.3.0-44-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/F75wrtGZ

## Description of the problem
I'm not sure whats going on, but when I remove AR it works fine. If I load a local map it works, but if I join a server it freaks out.

**Comment by zmaster587** [comment]
Does this occur without sponge?  Does it occur with only AR installed?  If not, what's the minimum mod set required to replicate the issue?

**Comment by Rsslone** [comment]
I tried with only AR, it crashes. All other mods and sponge uninstalled. O.O

**Comment by dmodoomsirius** [comment]
> I tried with only AR, it crashes. All other mods and sponge uninstalled. O.O

Can you please Pastebin the crash report and post that here? 
Keep in mind LibVulpes is required for AR.

**Comment by themaster402** [comment]
Think I'm getting an identical issue.
https://pastebin.com/3dJL62ay

**Comment by nullpointspace** [comment]
Translated translate.google.com

I have a similar error
Conducted tests on a clean server only from the AR and on the AR + Sponge
The problem occurs when using the sponge
On the main server, deleting the sponge also solved the problem.

**Comment by nullpointspace** [comment]
This is the same mistake.
Client is crashing at server join #1415

**Comment by zmaster587** [comment]
Should be fixed by above commit
