### ISSUE TITLE
Fatal Error on Server Connection

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1434]
## Version of Advanced Rocketry
1.12.2-1.4.1-112
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.3.0-44
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
Client latest.log:
https://gist.github.com/NillerMedDild/d626820834586bb11520f706f8c98d93

## Description of the problem
Fatal Error when attempting to join server.

**Comment by TheSnowyChickens** [comment]
Same here.
I was desperate to find the mistake. xDD

**Comment by TheSnowyChickens** [comment]
I upload it later today, because its on a other PC. :.)
Should I open a new issue for that?

**Comment by NillerMedDild** [comment]
It's a very long latest.log, you need to view it raw :) 

The server log only shows a normal login followed by a disconnect, but I'll upload it when I get on my PC.

**Comment by NillerMedDild** [comment]
I edited the latest.log a bit: https://gist.github.com/NillerMedDild/de3eb97e7c7eb297c87d63a93653f3aa
Server log: https://gist.github.com/NillerMedDild/140cb7f16693f252b173e0529b6b53f6

The server log is truncated, there's a button to view the entire thing at the top of the text.

**Comment by TheSnowyChickens** [comment]
My crash:
[crash-2018-11-07_14.56.18-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/2557584/crash-2018-11-07_14.56.18-server.txt)

**Comment by NillerMedDild** [comment]
Version 110 does not have this issue, if that helps.

**Comment by NillerMedDild** [comment]
@TheSnowyChickens Your error is completely unrelated, MagnetiCraft is the most likely culprit.

**Comment by TheSnowyChickens** [comment]
Hmm, MagnetiCraft is no longer maintained.
So what can I do? (without removing the mod)

**Comment by NillerMedDild** [comment]
Downgrade ModelLoader: https://github.com/Magneticraft-Team/Magneticraft/issues/145

**Comment by TheSnowyChickens** [comment]
Ahh, nice. Ty

**Comment by TheSnowyChickens** [comment]
WAIT, it don't work.

Every version (ML 1.1.4, AR 109, 112, LV 44, 42) end in a crash ...

**Comment by zmaster587** [comment]
It's amazing how one line of code can break everything

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by TheSnowyChickens** [comment]
Ty

**Comment by dannydjdk** [comment]
I am still getting this issue with Advanced Rocketry 1.4.1-113 and LibVulpes 0.3.0.44 with what appears to be the same error. Here's a log snippet: https://pastebin.com/AiJfyXwD

Problem started when upgrading from 1.4.0-102 to 1.4.1-111 and persists through 113. Can be reproduced with brand new worlds using this pack: https://minecraft.curseforge.com/projects/integrated-progressions

**Comment by zmaster587** [comment]
I'll look into it, I downloaded 113 directly off curse and can confirm I don't get the error with AR and libvulpes alone when logging into a server.

**Comment by mxnmnm** [comment]
113 doesn't seem to have fixed anything for me

**Comment by zmaster587** [comment]
@dannydjdk Cannot replicate 
![image](https://user-images.githubusercontent.com/3536685/48326592-233b0f00-e608-11e8-99c3-a950ec1477ab.png)

**Comment by dannydjdk** [comment]
@zmaster587 The problem is fixed for me after deleting the config files and allowing them to be recreated. Sorry, I mentioned this in an edit to my post in a confusing way and probably should have just created another post.
@mxnmnm Try deleting the advancedrocketry folder within your server's config folder. That fixed the problem for me after upgrading to 113.

**Comment by mxnmnm** [comment]
Yea that didn't do it for me :/
