### ISSUE TITLE
 java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by catagris** [zmaster587/AdvancedRocketry#1435]
## Version of Advanced Rocketry
1.12.2-1.4.1-108-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.2.8-39-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/jeMih3Gq

## Description of the problem
Even with the mod removed from the server the error still happens but the . This error goes away when both the client and the server have the mod removed. 

Editing the cleint config:
```
client {
    # If true, AR will use a custom skybox on planets
    B:PlanetSkyOverride=false

    # If true, AR will use a custom skybox on space stations
    B:StationSkyOverride=false
    I:atmBarModeX=-1
    I:atmBarModeY=1
    I:atmBarX=8
    I:atmBarY=27
    I:hydrogenBarModeX=0
    I:hydrogenBarModeY=1
    I:hydrogenBarX=-8
    I:hydrogenBarY=74

    # If UI is not locked, the middle mouse can be used to drag certain AR UIs around the screen, positions are saved on hitting quit in the menu
    B:lockUI=true
    B:overworldSkyOverride=false
    I:oxygenBarModeX=0
    I:oxygenBarModeY=1
    I:oxygenBarX=-8
    I:oxygenBarY=57
    I:suitPanelModeX=-1
    I:suitPanelModeY=-1
    I:suitPanelX=8
    I:suitPanelY=8
}
```

This lets people connect with the mod installed on both. I am wondering what is causing it and how is the error still happening when the server has the mod removed. (At least the world data and jar file)

**Comment by zmaster587** [comment]
see #1433
