### ISSUE TITLE
Planets/Stars data not sent to client on Sponge server (With a working temporary fix)

### ISSUE THREAD

**Issue by takarabako** [zmaster587/AdvancedRocketry#1439]
## Version of Advanced Rocketry
1.12.2-1.4.1-113
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.3.0-44
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
I'm playing FTB continuum on a sponge server and there are several bugs (client crashing when go to space, not able to select Luna, etc. Not happening on native Forge server) on the server. After some hours of work I managed to track down to a single problem: The ServerConnectionFromClientEvent is somehow not fired on spongeforge-1.12.2-2768-7.1.4 Recommand build. The same mod pack also features ProjectE inside and they are sending data to client correctly so I dig into their source and find out they are using PlayerLoggedInEvent to sync data. I modified AR to use PlayerLoggedInEvent and problem solved(I only applied the fix on server, client still using 1.4.1-113). Here's the modified method https://gist.github.com/takarabako/c3e6940e0249192e248544787fe7ee40

**Comment by zmaster587** [comment]
Does this work when a player is logging into the world when he's on another planet?  I believe I had tried that initially and it caused a client crash due to the world not yet existing.

**Comment by takarabako** [comment]
> Does this work when a player is logging into the world on a non-sponge server when he's on another planet as opposed to a vanilla or world added by a mod other than AR on a dedicated server? Reason I ask is that I had tried using the playerloggedin event initially and it caused a client crash due to the world not yet existing, though it was in MC1.7.10.

It crashed, only when you log out on a AR dimension, RESTART the whole client and join back. My guess is the data is a bit slow than the client trying to render the first frame. It won't crash if you set the sky overrides to false. I made some additional changes to RenderPlanetarySky to check when the star is null just don't do anything. as far as I can tell, I can't see any difference.

**Comment by zmaster587** [comment]
Just to clarify, is it crashing to desktop or just not letting the player log into the server?
If it's just not being able to log in, I think I know what's causing that.  There's a line in `PacketDimInfo::readClient` that needs to be moved to `PacketDimInfo::executeClient`.
```
			dimProperties = new DimensionProperties(dimNumber);
			dimProperties.readFromNBT(dimNBT);
```

**Comment by takarabako** [comment]
> Just to clarify, is it crashing to desktop or just not letting the player log into the server?
> If it's just not being able to log in, I think I know what's causing that. There's a line in `PacketDimInfo::readClient` that needs to be moved to `PacketDimInfo::executeClient`.
> 
> ```
> 			dimProperties = new DimensionProperties(dimNumber);
> 			dimProperties.readFromNBT(dimNBT);
> ```

To the desktop with a crash report.

**Comment by zmaster587** [comment]
> > Just to clarify, is it crashing to desktop or just not letting the player log into the server?
> > If it's just not being able to log in, I think I know what's causing that. There's a line in `PacketDimInfo::readClient` that needs to be moved to `PacketDimInfo::executeClient`.
> > ```
> > 			dimProperties = new DimensionProperties(dimNumber);
> > 			dimProperties.readFromNBT(dimNBT);
> > ```
> 
> To the desktop with a crash report.

Could you share it?

**Comment by brunyman** [comment]
That null check will only work if you also update the client mod right?

**Comment by takarabako** [comment]
> That null check will only work if you also update the client mod right?

Those are client side code so Yes.
Also doing those checks seems not right to me the ultimate fix should be Sponge firing events correctly (by correctly I mean exactlly like what native Forge do) so we don't have to change the login event at the first place.

**Comment by brunyman** [comment]
yea, not sure that will happen soon, sponge had bugged events since 1.10 and like they broke it even more on 1.12
However we will need to find a workaround and only patch the server side if possible

**Comment by takarabako** [comment]
> yea, not sure that will happen soon, sponge had bugged events since 1.10 and like they broke it even more on 1.12
> However we will need to find a workaround and only patch the server side if possible

You can set sky overrides to false on client side config and it should work. Still on client side though but no source change. But it looks terrible :(

**Comment by brunyman** [comment]
We may be able to force tp players on the overworld if they join elsewhere, I will look into this option, with a sponge plugin

**Comment by takarabako** [comment]
> We may be able to force tp players on the overworld if they join elsewhere, I will look into this option, with a sponge plugin

If you teleport them after they join back, it would not do the trick as the client will crash on the first frame it tries to render before it can switch dimension.

**Comment by brunyman** [comment]
> > We may be able to force tp players on the overworld if they join elsewhere, I will look into this option, with a sponge plugin
> 
> If you teleport them after they join back, it would not do the trick as the client will crash on the first frame it tries to render before it can switch dimension.

Maybe will work on ClientConnectionEvent.Join , I will give it a try

ClientConnectionEvent.AuthCalled asynchronously when the client attempts to authenticate against the server.
ClientConnectionEvent.JoinCalled when a Player joins the game World for the first time after initial connection.
ClientConnectionEvent.LoginCalled after the client authenticates and attempts to login to the server.

**Comment by takarabako** [comment]
For anyone interested, [these](https://gist.github.com/takarabako/b5c6c2a93e9f25063b90d3e82ac61b59) are the changes I made to the client mod to make it working. I'm editing source file in Windows Notepad so the format is as bad as it can be :)

**Comment by brunyman** [comment]
these changes must also be added to the client?


> For anyone interested, [these](https://gist.github.com/takarabako/b5c6c2a93e9f25063b90d3e82ac61b59) are the changes I made to the client mod to make it working. I'm editing source file in Windows Notepad so the format is as bad as it can be :)

**Comment by takarabako** [comment]
These are the changes mentioned above applied additionally to sponge_login_fix branch to prevent first join crash on client side. For servers just use the branch as is.

**Comment by brunyman** [comment]
ok, I will give it a try now, thanks

**Comment by takarabako** [comment]
I finally got enough time to track down the exact problem in sponge.
The ServerConnectionFromClientEvent is fired in net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(), which is patched in by Forge at [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/server/management/PlayerList.java.patch#L37).
However sponge decided to implement their own initializeConnectionToPlayer method in MixinPlayerList [here](https://github.com/SpongePowered/SpongeCommon/blob/6a5c17dbf7185fe292ae28d5454e30d3adc60bb1/src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java#L230), without firing the forge event. I'll close this and open an issue on sponge. Thanks @zmaster587 for helping.
