### ISSUE TITLE
O2 Thread: Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by Mariomette** [zmaster587/AdvancedRocketry#144]
http://pastebin.com/09SDNYUx

**Comment by DarkGuardsman** [comment]
I know I said I wouldn't help but...

It Seems the thread is constantly crashing on the SC server with the same index out of bounds exception. Luckily it's not taking out the server due to it being a thread, however, it is spamming the console.

**Comment by DarkGuardsman** [comment]
Re-opening as I don't think the patch I made will correct the issue. Still have not tested it on the server experiencing the problem. Going to implement a try-catch in the O2 thread to spit out data with the error. This way I can see what is exactly going wrong when the out of bound exception happens. As well the try-catch should prevent the thread from crashing and not finishing its bubble creation.

**Comment by DarkGuardsman** [comment]
https://github.com/zmaster587/AdvancedRocketry/commit/adf69726b1adf54230bf865b6b6d98f074101c3b
