### ISSUE TITLE
Mobs Spawn on Planets Without Atmosphere

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1441]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-113-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.3.0-44-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
Planets without atmospheres still spawn mobs when the light level allows it. They eventually die from suffocation, leaving behind tons of item entities.

**Comment by NillerMedDild** [comment]
Tested with a Planet generated with the below settings:

<planet name="Mars" DIMID="103" customIcon="marslike">
			<biomeIds>advancedrocketry:hotdryrock</biomeIds>
            <skyColor>1,0.2,0</skyColor>
			<fogColor>0.9,0.6,0.1</fogColor>
			<atmosphereDensity>0</atmosphereDensity>
			<orbitalDistance>105</orbitalDistance>
			<gravitationalMultiplier>38</gravitationalMultiplier>
			<rotationalPeriod>20000</rotationalPeriod>
		</planet>

**Comment by xenoflot** [comment]
It's rather amusing to have mobs dying and leaving their loot around, but I do find that my FPS drops quite a bit as it's processing continuous small damage hits to dozens of mobs at any one time.

**Comment by C1ffisme** [comment]
IMHO, Zombies and Skeletons shouldn't need oxygen to breathe since they're dead. I can't say the same for Creepers or Spiders, of course, but I think these two should be able to breathe in an oxygen-less atmosphere. (That being said, it doesn't really make sense how dead bodies ended up on a lifeless planet except through some apocalyptic situation, although that lore doesn't work for every Minecraft modpack.)

The AR wiki mentions a "Spawnable" tag, although I don't know if this effects mob spawns in dark areas.

**Comment by CaptainStalfoss** [comment]
I had this issue to, But i fixed it by using Incontrol and Biometweaker.
Since it gets rather hard to keep track of mobs when you have a lot of mods.

However, for vanilla it would be nice to have an option to disable their spawn in certain dimensions/biomes.

**Comment by MSandro** [comment]
I use a other workaround: I've installed Mobs Properties Randomness and added the space suit to all monsters with oxygen tanks. Now they are not dying so fast and there are not so much mob drops on the ground.

**Comment by themechman** [comment]
Can confirm this is still present in 1.5.0-125
