### ISSUE TITLE
Server Error when trying to launch a satellite

### ISSUE THREAD

**Issue by jamie-34254** [zmaster587/AdvancedRocketry#1442]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-108-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-39-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://gist.github.com/JamieH/429a2e4de619ffb0293368f65dbc91e7

## Description of the problem
Built a satellite and tried to launch it - threw an error on the server then tried to break it and it went invisible

**Comment by zmaster587** [comment]
Can you test the latest (or at least 111+) build with this, there was some packet handling stuff fixed in 111.
Secondly, are there any other mods in use, if so, does this occur without ther other mods?

**Comment by JamieH** [comment]
We're playing the All the Mods 3 Remix pack so I guess they need to update the version of the mod

**Comment by martmists** [comment]
It would help us see if this is fixed in the newer versions if you could test this for us. If you're unable to, I'll see if I can figure out what causes this somewhere next week.

**Comment by JamieH** [comment]
@zmaster587 @martmists I downloaded:

`AdvancedRocketry-1.12.2-1.4.1-108-universal`
`LibVulpes-1.12.2-0.2.8-39-universal`

Tried with the same satellite, didn't launch, also the select destination button caused an error: https://gist.github.com/JamieH/f5ae3c8559f0d9848d76d2d84c83fdf7

**Comment by dmodoomsirius** [comment]
Try with https://minecraft.curseforge.com/projects/advanced-rocketry/files/2641964 
And https://minecraft.curseforge.com/projects/libvulpes/files/2633668

**Comment by JamieH** [comment]
Still broken...

Select Destination: https://gist.github.com/JamieH/8154665ff81529ba1c9093201654cd23#file-gistfile1-txt
Trying to launch: https://gist.github.com/JamieH/8154665ff81529ba1c9093201654cd23#file-gistfile2-txt

**Comment by zmaster587** [comment]
The "select destination" one looks to be a seperate issue (selecting destination without a guidance computer).

there was a missing isRemote check for when launching from a monitoring station, that should be fixed in the upcoming build.

**Comment by Silfryi** [comment]
This seems to be fixed, do you have this problem on the latest builds? Please test and close the issue if you do not.
