### ISSUE TITLE
Please help! I have a problem with the rocket bulder interface and the rest of the machines. They are black. What should I do? Sorry for my English, I'm from Ukraine

### ISSUE THREAD

**Issue by 7ShadowFOX7** [zmaster587/AdvancedRocketry#1444]
## Version of Advanced Rocketry
[1.4.0-20]
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
[0.2.8-34]
## Version of Minecraft
[insert [here]]([url]([url]([url](url))))
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
[I have a dark interface of the rocket bulder and other machines, see only the buttons, and the progress is not visible. Help. And sorry for my English.
![2018-11-24_13 30 50](https://user-images.githubusercontent.com/45121316/48967836-329a5f00-efef-11e8-8092-077354854192.png)
![2018-11-17_13 20 20](https://user-images.githubusercontent.com/45121316/48967837-329a5f00-efef-11e8-8430-6e66a846a08f.png)
![2018-11-17_13 20 25](https://user-images.githubusercontent.com/45121316/48967838-3332f580-efef-11e8-9065-1aa9e8782ec6.png)

]

**Comment by nullpointspace** [comment]
Попробуй обновиться до последней версии, судя по версии LibVulpes, ты давно не обновлялся
Так же проверь что нет никаких конфликтов с другими модами, судя по первому скрину, у тебя текстура немного поехала. Попробуй запуститься только с AR без других модов, если есть Optifine попробуй запуститься без него.
На будущее, версии AR, LibVulpes и minecraft лучше писать полностью

**Comment by 7ShadowFOX7** [comment]
> Попробуй обновиться до последней версии, судя по версии LibVulpes, ты давно не обновлялся 
> Так же проверь что нет никаких конфликтов с другими модами, судя по первому скрину, у тебя текстура немного поехала. Попробуй запуститься только с АР без других модов, если есть Optifine попробуй запуститься без него. 
> На будущее, версии AR, LibVulpes и minecraft лучше писать полностью

I have minecraft version 1.7.10, and the latest version of Libvulpes, I do not use Optifine and other mods

**Comment by 7ShadowFOX7** [comment]
> Я заметил, что у вас был NEI на 3-м снимке экрана, и я не могу сказать, модифицирован ли первый из них или нет. Эта проблема возникает только при использовании только продвинутой ракеты и libvulpes?

Yes, in the third screenshot I have one additional mod, but in the first screenshot I only have Advanced rocketry and Libvulpes and no more mods.
