### ISSUE TITLE
Modpack-Crash

### ISSUE THREAD

**Issue by Hplr63** [zmaster587/AdvancedRocketry#1446]
## Version of Advanced Rocketry
[1.4.0-63]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[N/A]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-63.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 11/26/18 5:03 PM
Description: Initializing game

java.lang.VerifyError: Inconsistent stackmap frames at branch target 914
Exception Details:
  Location:
    net/minecraft/client/renderer/RenderGlobal.func_174970_a(Lnet/minecraft/entity/Entity;DLnet/minecraft/client/renderer/culling/ICamera;IZ)V @905: ifle
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @905
    flags: { }
    locals: { 'net/minecraft/client/renderer/RenderGlobal', 'net/minecraft/entity/Entity', double, double_2nd, 'net/minecraft/client/renderer/culling/ICamera', integer, integer, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, 'net/minecraft/util/math/BlockPos', 'net/minecraft/client/renderer/chunk/RenderChunk', 'net/minecraft/util/math/BlockPos', integer, 'java/util/Queue', integer, integer, integer, integer, 'net/minecraft/client/renderer/chunk/RenderChunk' }
    stack: { double, double_2nd, integer }
  Stackmap Frame:
    bci: @914
    flags: { }
    locals: { 'net/minecraft/client/renderer/RenderGlobal', 'net/minecraft/entity/Entity', double, double_2nd, 'net/minecraft/client/renderer/culling/ICamera', integer, integer, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, 'net/minecraft/util/math/BlockPos', 'net/minecraft/client/renderer/chunk/RenderChunk', 'net/minecraft/util/math/BlockPos', integer, 'java/util/Queue', integer, integer, integer, integer, 'net/minecraft/client/renderer/chunk/RenderChunk' }
    stack: { 'net/minecraft/client/renderer/culling/ICamera', 'net/minecraft/util/math/AxisAlignedBB', double, double_2nd }
  Bytecode:
    0x0000000: 2ab4 00e5 b402 b2b4 02c3 2ab4 00d4 9f00
    0x0000010: 072a b602 902a b402 7eb4 02fc 1304 dab6
    0x0000020: 0303 2bb4 02d4 2ab4 00bd 6739 072b b402
    0x0000030: f52a b400 bf67 3909 2bb4 02d7 2ab4 00c1
    0x0000040: 6739 0b2a b400 c42b b404 dda0 0031 2ab4
    0x0000050: 00c6 2bb4 04e0 a000 262a b400 c82b b404
    0x0000060: e3a0 001b 1807 1807 6b18 0918 096b 6318
    0x0000070: 0b18 0b6b 6314 04e4 979e 0042 2a2b b402
    0x0000080: d4b5 00bd 2a2b b402 f5b5 00bf 2a2b b402
    0x0000090: d7b5 00c1 2a2b b404 ddb5 00c4 2a2b b404
    0x00000a0: e0b5 00c6 2a2b b404 e3b5 00c8 2ab4 029a
    0x00000b0: 2bb4 02d4 2bb4 02d7 b602 db2a b402 7eb4
    0x00000c0: 02fc 1304 e7b6 0346 2bb4 0325 2bb4 02d4
    0x00000d0: 2bb4 0325 6728 6b63 390d 2bb4 0328 2bb4
    0x00000e0: 02f5 2bb4 0328 6728 6b63 390f 2bb4 032b
    0x00000f0: 2bb4 02d7 2bb4 032b 6728 6b63 3911 2ab4
    0x0000100: 0113 180d 180f 1811 b604 ec2a b402 7eb4
    0x0000110: 02fc 1304 eeb6 0346 2ab4 04f0 c600 2ebb
    0x0000120: 04f2 592a b404 f0b7 04f5 3a13 1913 2ab4
    0x0000130: 00df b404 f82a b400 dfb4 04fb 2ab4 00df
    0x0000140: b404 feb6 0501 1913 3a04 2ab4 00e5 b404
    0x0000150: 5e13 0503 b603 46bb 0018 5918 0d18 0f2b
    0x0000160: b605 068d 6318 11b7 0508 3a13 2ab4 029a
    0x0000170: 1913 b605 0c3a 14bb 0018 5918 0d14 04e4
    0x0000180: 6fb8 0512 1010 6818 0f14 04e4 6fb8 0512
    0x0000190: 1010 6818 1114 04e4 6fb8 0512 1010 68b7
    0x00001a0: 0514 3a15 2a2a b400 e19a 004d 2ab4 0096
    0x00001b0: b905 1501 0099 0041 2bb4 02d4 2ab4 00ca
    0x00001c0: 979a 0035 2bb4 02f5 2ab4 00cc 979a 0029
    0x00001d0: 2bb4 02d7 2ab4 00ce 979a 001d 2bb4 0518
    0x00001e0: 8d2a b400 d097 9a00 102b b405 1b8d 2ab4
    0x00001f0: 00d2 9799 0007 04a7 0004 03b5 00e1 2a2b
    0x0000200: b402 d4b5 00ca 2a2b b402 f5b5 00cc 2a2b
    0x0000210: b402 d7b5 00ce 2a2b b405 188d b500 d02a
    0x0000220: 2bb4 051b 8db5 00d2 2ab4 04f0 c600 0704
    0x0000230: a700 0403 3616 2ab4 00e5 b404 5e13 051d
    0x0000240: b603 4615 169a 0277 2ab4 00e1 9902 702a
    0x0000250: 03b5 00e1 2ab8 0368 b500 9fb8 0523 3a17
    0x0000260: 2ab4 00e5 b402 b2b4 02c3 8714 0524 6f0f
    0x0000270: 1405 26b8 052b b805 2f2a b400 e5b4 04b3
    0x0000280: 3618 1914 c600 a803 3619 bb00 1159 2a19
    0x0000290: 1401 c004 4103 01b7 0532 3a1a 2a19 13b7
    0x00002a0: 0536 3a1b 191b b904 bc01 0004 a000 2c2a
    0x00002b0: 2b28 b605 3a3a 1c19 1cb4 053f 191c b405
    0x00002c0: 4219 1cb4 0545 b805 49b6 054d 3a1d 191b
    0x00002d0: 191d b905 5002 0057 191b b905 1501 0099
    0x00002e0: 0006 0436 1915 1999 0017 1506 9a00 122a
    0x00002f0: b400 9f19 1ab9 03b8 0200 57a7 002e 1506
    0x0000300: 9900 172a b402 7e19 13b6 042a b905 5501
    0x0000310: 0099 0006 0336 1819 1415 05b6 0558 5719
    0x0000320: 1719 1ab9 0559 0200 57a7 00a4 1913 b603
    0x0000330: 909e 0009 1100 f8a7 0005 1008 3619 2ab4
    0x0000340: 00d4 7436 1a15 1a2a b400 d4a3 0082 2ab4
    0x0000350: 00d4 7436 1b15 1b2a b400 d4a3 006c 2ab4
    0x0000360: 029a bb00 1859 151a 0778 1008 6015 1915
    0x0000370: 1b07 7810 0860 b705 14b6 050c 3a1c 191c
    0x0000380: c600 410e 1913 b603 909e 0009 1405 5aa7
    0x0000390: 0006 1405 5e0e b605 63b9 040d 0200 9900
    0x00003a0: 2319 1c15 05b6 0558 5719 17bb 0011 592a
    0x00003b0: 191c 01c0 0441 0301 b705 32b9 0559 0200
    0x00003c0: 5784 1b01 a7ff 9184 1a01 a7ff 7b2a b400
    0x00003d0: e5b4 045e 1305 65b6 0303 1917 b905 6601
    0x00003e0: 009a 00d1 1917 b905 6901 00c0 0011 3a19
    0x00003f0: 1919 b403 7d3a 1a19 19b4 056c 3a1b 2ab4
    0x0000400: 009f 1919 b903 b802 0057 b805 6f3a 1c19
    0x0000410: 1cbe 361d 0336 1e15 1e15 1da2 0094 191c
    0x0000420: 151e 323a 1f2a 1915 191a 191f b705 753a
    0x0000430: 2015 1899 0010 1919 191f b605 4db6 0579
    0x0000440: 9a00 6915 1899 001a 191b c600 1519 1ab6
    0x0000450: 03fd 191b b605 4d19 1fb6 057d 9900 4d19
    0x0000460: 20c6 0048 1920 1505 b605 5899 003e 1904
    0x0000470: 1920 b405 81b9 040d 0200 9900 2fbb 0011
    0x0000480: 592a 1920 191f 1919 b405 8404 6001 b705
    0x0000490: 323a 2119 2119 19b4 0588 191f b605 8c19
    0x00004a0: 1719 21b9 0559 0200 5784 1e01 a7ff 6ba7
    0x00004b0: ff2b 2ab4 00e5 b404 5eb6 0461 2ab4 00e5
    0x00004c0: b404 5e13 058e b603 462a b405 9099 0012
    0x00004d0: 2a18 0d18 0f18 11b7 0593 2a03 b505 902a
    0x00004e0: b400 e5b4 045e 1305 95b6 0346 2ab4 0096
    0x00004f0: 3a17 2ab8 0094 b500 962a b400 9fb9 0370
    0x0000500: 0100 3a18 1918 b903 7501 0099 009f 1918
    0x0000510: b903 7901 00c0 0011 3a19 1919 b403 7d3a
    0x0000520: 1a19 1ab6 0598 9a00 0f19 1719 1ab9 059b
    0x0000530: 0200 9900 752a 04b5 00e1 191a b603 8310
    0x0000540: 0810 0810 08b6 059f 3a1b 191b 1913 b605
    0x0000550: a314 05a4 989c 0007 04a7 0004 0336 1cb2
    0x0000560: 05aa 9a00 1019 1ab6 05ad 9a00 1715 1c9a
    0x0000570: 0012 2ab4 0096 191a b905 ae02 0057 a700
    0x0000580: 292a b400 e5b4 045e 1305 b0b6 0303 2ab4
    0x0000590: 02a1 191a b605 b457 191a b605 b72a b400
    0x00005a0: e5b4 045e b604 61a7 ff5d 2ab4 0096 1917
    0x00005b0: b905 bb02 0057 2ab4 00e5 b404 5eb6 0461
    0x00005c0: b1                                     
  Stackmap Table:
    same_frame(@21)
    append_frame(@124,Double,Double,Double)
    same_frame(@187)
    append_frame(@330,Double,Double,Double)
    full_frame(@502,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24]},{Object[#2]})
    same_locals_1_stack_item_frame(@506,Object[#2])
    full_frame(@507,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24]},{Object[#2],Integer})
    same_frame(@563)
    same_locals_1_stack_item_frame(@564,Integer)
    full_frame(@728,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24],Integer,Object[#1362],Integer,Integer,Object[#17],Object[#658]},{})
    same_frame(@741)
    same_frame(@766)
    same_frame(@791)
    chop_frame(@809,3)
    same_frame(@812)
    same_frame(@826)
    same_locals_1_stack_item_frame(@828,Integer)
    append_frame(@837,Integer,Integer)
    append_frame(@853,Integer)
    full_frame(@914,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24],Integer,Object[#1362],Integer,Integer,Integer,Integer,Object[#895]},{Object[#847],Object[#1373],Double})
    full_frame(@917,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24],Integer,Object[#1362],Integer,Integer,Integer,Integer,Object[#895]},{Object[#847],Object[#1373],Double,Double})
    chop_frame(@961,1)
    chop_frame(@967,1)
    chop_frame(@973,2)
    same_frame(@986)
    full_frame(@1047,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24],Integer,Object[#1362],Integer,Object[#17],Object[#895],Object[#1089],Object[#1393],Integer,Integer},{})
    append_frame(@1091,Object[#1089],Object[#895])
    same_frame(@1119)
    chop_frame(@1193,2)
    full_frame(@1199,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24],Integer,Object[#1362],Integer},{})
    same_frame(@1202)
    chop_frame(@1212,2)
    same_frame(@1247)
    append_frame(@1284,Object[#658],Object[#882])
    append_frame(@1333,Object[#17],Object[#895])
    append_frame(@1372,Object[#24])
    same_locals_1_stack_item_frame(@1373,Integer)
    append_frame(@1394,Integer)
    same_frame(@1409)
    full_frame(@1447,{Object[#2],Object[#721],Double,Object[#847],Integer,Integer,Double,Double,Double,Double,Double,Double,Object[#24],Object[#895],Object[#24],Integer,Object[#658],Object[#882]},{})
    chop_frame(@1450,1)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 336860088 bytes (321 MB) / 1040187392 bytes (992 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                   | Signature                                |
	|:----- |:-------------------- |:----------------- |:---------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2            | minecraft.jar                            | None                                     |
	| LCH   | mcp                  | 9.42              | minecraft.jar                            | None                                     |
	| LCH   | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2784.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2784      | forge-1.12.2-14.23.5.2784.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | advancedrocketrycore | 1                 | minecraft.jar                            | None                                     |
	| LCH   | libvulpes            | 0.3.0.-41         | LibVulpes-1.12.2.jar                     | None                                     |
	| LCH   | advancedrocketry     | 1.4.0.-63         | AdvancedRocketry-1.12.2-1.4.0-63.jar     | None                                     |
	| LCH   | codechickenlib       | 3.2.2.353         | CodeChickenLib-1.12.2.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | jei                  | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                | None                                     |
	| LCH   | journeymap           | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar              | None                                     |
	| LCH   | mekanism             | 1.12.2-9.4.13.349 | Mekanism-1.12.2-9.4.13.349.jar           | None                                     |
	| LCH   | mekanismgenerators   | 9.4.11            | MekanismGenerators-1.12.2-9.4.13.349.jar | None                                     |
	| LCH   | mekanismtools        | 9.4.11            | MekanismTools-1.12.2-9.4.13.349.jar      | None                                     |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-63.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '3.3.0 - Build 8.15.10.2712' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2784
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 3.3.0 - Build 8.15.10.2712, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz]

## Description of the problem
[When it's suppose to show main menu, it crashes]

Mods I put in the modpack: **Advanced Rocketry**, Codechickenlib, Just Enough Items, Journey Map, LibVulpes, Mekanism, Mekanism Generators, Mekanism Tools, Waila

**Comment by zmaster587** [comment]
Could you get me a crash report from version 113?  The codebase has changed significantly since 63 was released months ago and so the line numbers on the crash report from 63 are fairly useless.

**Comment by Hplr63** [comment]
> Could you get me a crash report from version 113? The codebase has changed significantly since 63 was released months ago and so the line numbers on the crash report from 63 are fairly useless.

That was the latest file on MinecraftCurseForge (for 1.12.2 (cuz 1.13 S*CKS))

**Comment by Silfryi** [comment]
He means test with the latest alpha build, the mod has not updated to 1.13 yet. Could you please test with the latest alpha, please?
