### ISSUE TITLE
Rocket disappears after pressing build, leaves impassible zone behind

### ISSUE THREAD

**Issue by AMFried** [zmaster587/AdvancedRocketry#1448]
## Version of Advanced Rocketry
1.4.1.-1
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
0.3.0.-44
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
On Multiplayer after placing the blocks for the rocket (In this case a satellite rocket), pressing build and waiting for the sequence to finish all the blocks disappear and no rocket entity takes it's place. This only sometimes happens, so far with a 66% occurrence rate in the last 3 rockets I've launched, the first occurrence self-launched for some reason and became visible again after doing so.

Update: 12/9/18 the server owner decided to kill all entities in the world in an attempt to reduce lag, this killed the invisible rocket entity, allowing me to pass through again. The server has ProjectE installed and the consensus so far is that ProjectE watch of flowing time pedestals were causing skipped ticks.

**Comment by neograymatter** [comment]
I am having this issue as well, and I've narrowed it down to using Advanced Rocketry with Valkyrien Warfare. When both these mods are running, rockets often turn into an invisible non-interactable area when built.

**Comment by AMFried** [comment]
The pack my friends and I use has VW installed, I'll ask my friend to remove it and see if it's what's causing the issue.

**Comment by SupernovaCo** [comment]
I've found this to also randomly happen when the rocket leaves loaded chunks, or sometimes for no apparent reason at all. At one point, I turned around and my rocket had vanished, while I was in the same chunk as it. It was not newly built, but rather had just landed on a planet.
