### ISSUE TITLE
Airlock door isn't dropped when harvested with pick

### ISSUE THREAD

**Issue by xenoflot** [zmaster587/AdvancedRocketry#1449]
## Version of Advanced Rocketry
1.4.1.-114
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.3.0.-44
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
Building a station module, prior to assembly.
Place door.
Decide you want to move it.
Harvest with a pick (tested with TiCo and vanilla picks)
Get nothing in return

**Comment by zmaster587** [comment]
Appears to only effect bottom half of the door.
