### ISSUE TITLE
Station truncated

### ISSUE THREAD

**Issue by xenoflot** [zmaster587/AdvancedRocketry#1450]
## Version of Advanced Rocketry
1.4.1.-114
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.3.0.-44
## Version of Minecraft
1.12.1
## Version of Forge
14.23.5.2768
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
Launchpad area is 13x19x11
Spent a couple of hours building a hub station
Scanned OK but 3 rows were missed during the Build (from the long dimension)
Once deployed, the station is missing that section
https://i.imgur.com/BMHgKOV.png

Did I do anything incorrectly?

**Comment by zmaster587** [comment]
just to verify, it's 19 blocks tall, not 19 blocks long correct?  Reason I ask is because max size length or width-wise is 16 blocks, and 19-16 = 3, which is consistant with the number of rows you report to be missing.

**Comment by xenoflot** [comment]
That'll be it then. It was indeed 19 blocks _long_. I didn't spot that in the docco. Thanks very much.
