### ISSUE TITLE
Satellite chip data lost if Sat Terminal is broken

### ISSUE THREAD

**Issue by xenoflot** [zmaster587/AdvancedRocketry#1451]
## Version of Advanced Rocketry
1.4.1.-114
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
0.3.0.-44
## Version of Minecraft
1.12.2
## Version of Forge
14.23.5.2768
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
Chips inside a Satellite Terminal lose their data and become Unprogrammed if the terminal is broken. This may be intentional but as here's no warning to "safely remove the USB before shutdown" I can't tell if it is or not. Glad I had a backup!

**Comment by Silfryi** [comment]
I cannot reproduce this in the newest version. Can you update and provide more information if it still happens, please?

**Comment by xenoflot** [comment]
Sure. Will close this and open a new report if needed.
