### ISSUE TITLE
Rocket landed underlava :(

### ISSUE THREAD

**Issue by xenoflot** [zmaster587/AdvancedRocketry#1453]
## Version of Advanced Rocketry
1.4.1.-114
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
0.3.0.-44
## Version of Minecraft
1.12.2
## Version of Forge
14.23.5.2768
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem

Took my rocket to Sol-128. Plenty of land around but it decided to land here: https://i.imgur.com/R08YAsI.png rather than the nice, firm ground in every other direction.

Fortunately I have flight and good armour so I was able to survive long enough to get to land, but I'm inclined to suggest that this is a less-than-ideal landing spot.

**Comment by attichicco** [comment]
Is that Enigmatica 2? btw I agree it shouldn't land in lava, that's pretty unlucky :P

**Comment by xenoflot** [comment]
Yes, Enigmatica 2

**Comment by Nomad7** [comment]
With some help from dmodoomsirius and Pyrosshade on discord I created a pure lava planet, and my rocket landed on an autogenerated platform.
![image](https://user-images.githubusercontent.com/3387240/72077941-5f720a00-32b5-11ea-99ef-a3b121cc168e.png)
This was on the latest version of Enigmatica 2 Light pack, which uses AdvancedRocketry build 190.
@xenoflot I suggest updating your modpack to the latest version and trying again, this seems to be working correctly in recent builds at least.
