### ISSUE TITLE
[1.12.2][FML]: FMLIndexedMessageCodec exception caught io.netty.handler.codec.DecoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by lays24mc** [zmaster587/AdvancedRocketry#1457]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-116
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.3.0-45
## Version of Minecraft
1.12.2
## Version of Forge
forge-14.23.5.2784
## Crash report or log (if applicable)
https://pastebin.com/puTtY8Ew
## Description of the problem

The server throws me out on the first login attempt. According to Log, there seems to be a problem with AR and LibVulpes.

**Comment by SniperHauss89** [comment]
I've had a very similar issue to this for several versions now on my server. It takes one or two attempts to get in. sometimes it will say fatal error detected and then a java.lang something followed by connection lost I believe,

**Comment by zmaster587** [comment]
Should be fixed in 117, fixed with 3ac9da6e6b4f84acbda90e965f0903c33d3be8bd
