### ISSUE TITLE
Crash on launching satellites in latest build.

### ISSUE THREAD

**Issue by enderger** [zmaster587/AdvancedRocketry#1461]
## Version of Advanced Rocketry
1.12.2-1.4.1-117
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.3.0-45
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
http://bit.ly/2GAYPpp

## Description of the problem
Bug #1354 occurs in the latest version of Advanced Rocketry. I made a new issue, as the old one seems to have fallen out of notice and the bug probably should be fixed in the near future. Thanks for being considerate and I am sorry to have to create a duplicate issue.

**Comment by Silfryi** [comment]
I cannot reproduce this in the newest version, can you update to the newest version (Yours is _not_ the newest) and report back if the issue persists, please?
