### ISSUE TITLE
Biome IDs not registered.  I know you took them out but...

### ISSUE THREAD

**Issue by Turrari** [zmaster587/AdvancedRocketry#1462]
I am working on a mod pack with Advanced Rocketry as a core mod in conjunction with BiomeTweaker.  I noticed when I upgraded last that BiomeTweaker can no longer see Advanced Rocketry biomes to copy or customize them.  Would it be possible to add that back in?  I am using it to make variations on the Advanced Rockery biomes for things like ice, volcanic, sulfuric moons and planets with different surface materials, decorations and mob spawns.

Thanks

**Comment by TheFlash787** [comment]
Hey! Is there any progress on this? There is currently no way to determine the ID of a biome that could be used in conjunction with CraftTweaker.

Thanks.
