### ISSUE TITLE
[Question] Can you put a star in a host star?

### ISSUE THREAD

**Issue by MrEyeballs29** [zmaster587/AdvancedRocketry#1463]
## Version of Advanced Rocketry
Version 1.4.1 Build 117
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
Version 0.3.0 Build 45
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
No log

## Description of the problem
Since you can obviously can put a planet in a host star but what about the minor star in the host star. That seems like a problem to me. I haven't tried testing out the game but here is the code for the Alpha Cent A and B:
<pre>
&lt;star name="Alpha Centauri A" temp="100" x="-100" y="100" size="1.2" numPlanets="0" numGasGiants="0"&gt;
  &lt;star name="Alpha Centauri B" temp="85" size="0.8" numPlanets="0" numGasGiants="0"&gt;
    &lt;planet name="&#945; Centauri Bb" DIMID="42" customIcon="marslike"&gt;
       ...
    &lt;/planet&gt;
  &lt;/star&gt;
&lt;/star&gt;
</pre>
If there is something else wrong with this then what should be the solution of this problem? Thanks for your time.

**Comment by ViciousGamer** [comment]
This should work
`<star name="Alpha Centauri A" temp="100" x="-100" y="100" size="1.2" numPlanets="0" numGasGiants="0">
  <star name="Alpha Centauri B" temp="85" size="0.8" numPlanets="0" numGasGiants="0"></star>
  <planet name="α Centauri Bb" DIMID="42" customIcon="marslike">
       ...
  </planet>
</star>`
I dont think planets can revolve around the host/secondary star.

**Comment by zmaster587** [comment]
Yeah, it's actually been 99% in there for a while... I just forgot to document and polish it until two days ago or so.
