### ISSUE TITLE
[Disscusion] Whats up with that AdvancedRocketry.java file?

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1466]
It seems pretty bloated and the whole thing could be done so much easier, split into different classes.
![2018-12-27-193610_1366x768_scrot](https://user-images.githubusercontent.com/28286961/50490697-bdb3ae00-0a0e-11e9-877a-d7780456d6b2.png)
Is there any reason why it looks the way it does?

EDIT: Also, aren't recipes just json files since 1.12?
This
![2018-12-27-193451_1366x768_scrot](https://user-images.githubusercontent.com/28286961/50490660-91982d00-0a0e-11e9-9358-27816b932de4.png)
could be refactored massively.

**Comment by zmaster587** [comment]
Closing because the AdvancedRocketry.java file has been mostly refactored out and recipes are JSONs now
