### ISSUE TITLE
Biome noise seems to be heavily/entirely disconnected with heightmap noise

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketry#1471]
![2019-01-03_11 51 14](https://user-images.githubusercontent.com/9893266/50653395-01e30900-0f4f-11e9-8f78-db8b9c4696b9.png)

The planet shown above has only 3 biomes: Mushroom Island, Mushroom Island Shore, and Ocean. I do not want the planet to have grass or trees, only giant mushrooms and mycelium.

I've noticed this bug happen with other planets too, including randomly generated planets. Interestingly certain biomes seem unaffected by this bug: Mesa Plateaus will still spawn rather high up compared to regular terrain, for example, but Extreme Hills might end up under the ocean.

**Comment by Gliese-832-c** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1787

**Comment by C1ffisme** [comment]
This has since been fixed, the issue was just duplicated
