### ISSUE TITLE
All the Mods 3 v5.11.2 apparently crashes because of AdvancedRocketry

### ISSUE THREAD

**Issue by moonplayer333** [zmaster587/AdvancedRocketry#1474]
## Version of Advanced Rocketry
[AdvancedRocketry-1.12.2-1.4.1-108-universal.jar]
## Have you verified this is an issue in the latest unstable build
No
## Version of LibVulpes
[LibVulpes-1.12.2-0.2.8-39-universal.jar]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[https://pastebin.com/iGedvv2v]
## Description of the problem
[i just joined an atm server and the screen went white and then it crashed.]

**Comment by FallenEagle1** [comment]
Go into the adv rocketry config and set PlanetSkyOverride, StationSkyOverride, and overwoldSkyOverride to false. This happens because you are trying to connect to a sponge server and there is an incompatibility between sponge and advanced rocketry.
