### ISSUE TITLE
Rocket won't launch/rocket can only be used once

### ISSUE THREAD

**Issue by Spaig** [zmaster587/AdvancedRocketry#1478]
## Version of Advanced Rocketry
1.12.2-1.4.1-120-UNSTABLE build -120 for 1.12.2
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes 1.12.2-0.3.0-45-UNSTABLE build -45 for 1.12.2
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
none - thankfully

## Description of the problem
We've been having two issues fairly reliably - we create a rocket (making sure to fuel it and have an acceleration over 0), set a destination, then hop in and launch it. 

About 80% of the time, when the countdown ends, it does not launch, spawns a lot of black smoke under the engines, and refuses to ever respond again. Cannot set a new destination, cannot unload fuel, can only disassemble it and try again.

During the 20% of the time that it *does* work, it works very well- launching up into space and down to the moon. Upon arrival at the moon, (or wherever, honestly), we loop back around to stage 1 - unresponsive rocket. I have yet to be able to launch a rocket twice without reassembling it.

It could be a rocket design thing, but I'm skeptical - all of these have been stripped down test pods with at least 1ms/2 of acceleration and full fuel tanks. It could be some sort of mod interaction though - we have a lot of them.

Summary: rockets fail to launch, cannot try again. Any ideas?

**Comment by zmaster587** [comment]
Can you verify that there's no collidable blocks over the rocket (F3 + b to show hitboxes)?  Does this occur without other mods installed?  Is there something you can do to get this issue to occur 100% of the time?

**Comment by Spaig** [comment]
There's no collidable blocks over the rocket - I double checked that first. We have no cloud mods and there's no snow or anything. I've been keeping the rocket design consistent and launching from the same spot to keep variables minimal too.

If I could get it to happen 100% of the time, I'd have a better idea of just what the heck is going on, but no such luck. Out of 20 launches, only 3 made it off the ground, and none of those were able to launch again.

 I'll check if it happens without other mods installed tomorrow.

**Comment by Spaig** [comment]
I tested this with only AdvRockets installed, and I was able to launch to the moon without any trouble. However, I added a second moon via configs, and I wasn't able to launch to that one - it said "destination unreachable". That's probably my fault and I'll have to check the planetDefs file, but I noticed that the effects for a "destination unreachable" launch were identical to what happens with my failed launches here:

https://imgur.com/a/SAmFUZd

It still doesn't explain why I can't pick another destination and try again though - server lag?

**Comment by Spaig** [comment]
Yeah, the second moon is definitely inside the overworld planet tags. Also, it seems like relogging lets me try the rocket again? Will update when I have more data.

**Comment by spiro-angelakis** [comment]
Guys, i've been struggling with a similar issue, I am adding planets for my modpack StevesNewGalaxy.com, starting with just Mercury in the Sol System, **I can add the planet just fine, it seems**, but there is no way to land on the planet even if already orbing it on a space station. The destination is set to Mercury, with Coords printing as "???, ???", yet when attempting to launch it says destination unavailable. 

The "goto" command prints back as "dimension not found", even though Mercury DIM-10 prints in the /planet list function, seemingly meaning it *does* exist, and should be reachable.

Any help here would be greatly appreciated, I love the mod, and our new update public launch date was pushed back to keep working on this

**Comment by spiro-angelakis** [comment]
https://pastebin.com/VJMT87ry
