### ISSUE TITLE
Suffocation with airtight seal armour and resistance 5

### ISSUE THREAD

**Issue by sdfg2** [zmaster587/AdvancedRocketry#1482]
## Version of Advanced Rocketry
1.4.1.-108
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.2.8.-39
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
I put the airtight seal enchantment on my armour (Tinker's), and it's been perfectly fine.  Then I made the personal nanobot beacon from Environment Tech and gave myself resistance 5.  Now when wearing the armour in areas with no oxygen, I take suffocation damage.

**Comment by dmodoomsirius** [comment]
Armor from vanilla or from what mod? Does this only happen with the air tight seal and not the nano beacon?

**Comment by sdfg2** [comment]
Yeah I edited the post straight after writing it, it's Tinker's armour.  I'm not sure what you mean by the second question.

**Comment by dmodoomsirius** [comment]
Did you try it without the environmental tech beacon?

**Comment by sdfg2** [comment]
Yes, that's how I realised the air sear was missing.  And as I said, I also tried replicating this situation by making an armour set, then reactivating the beacon.

**Comment by kragnoth** [comment]
Wonder if the beacon adds the resistance 5 by editing the armor nbt tag.  If so, it might be overwriting the seal from Advanced Rocketry.

**Comment by sdfg2** [comment]
Ok, I think I figured it out.  I made a new set of more awesome TiCon armour, and in the process of levelling up and applying modifiers, I realised that the airtight seal enchantment gets removed each time I apply a modifier.  I think I must have applied soulbound (netherstar) at some point around the time I was setting up the beacon which confused things.  It's nothing to do with the beacon at all!

**Comment by Silfryi** [comment]
Can you please close this issue since it is resolved and not the mod author's fault? (This is TiCon's leveling system's fault)
