### ISSUE TITLE
Lightwood Leaves are not shearable!

### ISSUE THREAD

**Issue by MSandro** [zmaster587/AdvancedRocketry#1483]
## Version of Advanced Rocketry
1.4.1-121

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
0.3.0-1

## Version of Minecraft
1.12.2 

## Description of the problem
The Lightwood Saplings are not shearable and the Whater Extractor from Sky Resources 2 doesn't work on them. I think this might be caused by the same issue.

**Comment by zmaster587** [comment]
I don't think it's related.  The water extractor only checks to see if it's type "treeLeaves"
https://github.com/Bartz24/SkyResources/blob/1.12-2.0/src/main/java/com/bartz24/skyresources/registry/ModCrafting.java#L442.  AR registers the saplings as "treeLeaves" in the forge ore dict.  There does not seem to be any location in Sky Resources that check if leaves are shearable before adding the water to the item.
I fixed the leaves not being shearable though.
