### ISSUE TITLE
Planets disappeared on server after updating to 121

### ISSUE THREAD

**Issue by MoonTurkey** [zmaster587/AdvancedRocketry#1487]
## Version of Advanced Rocketry
Build 121
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
Newest at the time, don't know the number on top of my head
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
I run a server with AR installed, along with the pack FTB revelations. I upgraded to 121 today and now all the planets are gone for me, even the moon. It worked in the version I previously had installed (118), since I was on the moon back then. 

When I looked at the planet ID chip, wich was previously set to moon, it gave me the message "Programming failed". 

Checking the planetDef file I can see that there are only the galaxies in it. 

Here comes the bug: I tried replacing the file with only the galaxies with one from singleplayer, but as soon as I restarted the server (yes, it is a serverside issue) it went back to containing only galaxies.

**Comment by zmaster587** [comment]
That's really odd, nothing involving planets was changed between those builds.  The changes there were basically fix balck hole rendering, fix a few recipe systems.  Wither skulls stop breaking forcefields, and if the user forgets to provide an option in the config, just assume the user doesn't want addition planets.  That wouldn't affect existing planets though.

Can you upload the log file that was printed the firs time you ran 121?

**Comment by T3DDY14** [comment]
https://gist.github.com/T3DDY14/699a0f37de331867b0b2896251516665

**Comment by zmaster587** [comment]
I'm seeing
`[20:33:04] [Server thread/INFO] [advancedrocketry]: Checking for config at E:\wamp64\www\ScafPack 3\server\.\world\advRocketry\planetDefs.xml
[20:33:04] [Server thread/INFO] [advancedrocketry]: File not found.  Now checking for config at E:\wamp64\www\ScafPack 3\server\.\world\advRocketry\planetDefs.xml` in your log, which indicates to me that the file either isn't being generated, or was deleted at some point.  Can you verify whether or not a file is being created there and whether it's there when you start the server?

**Comment by T3DDY14** [comment]
This is on a new server when I check there is no folder when I start the server but later on one gets generated but this issues still happens on that server as well

**Comment by T3DDY14** [comment]
Okay ive updated it to 124 and it still doesnt work

**Comment by T3DDY14** [comment]
https://gist.github.com/T3DDY14/7bddd4d536997d790445883b78db8cbd

**Comment by zmaster587** [comment]
Is this gist on a new world or an existing world?  If it's a new world, can you get me a server log from a startup other than the first time?  If it's an existing world, can you verify that `E:\wamp64\www\ScafPack 3\server\.\world\advRocketry\planetDefs.xml` exists?

**Comment by T3DDY14** [comment]
This is a existing world and I can verify that planetdefs.xml exists

**Comment by zmaster587** [comment]
Can you ensure the permissions on the file allow it to be read by the game?
If you're sure that the file is readable by the user running the MC instance, can you upload the world folder?

**Comment by T3DDY14** [comment]
Wait a second I restarted the server and I got a differen line of code saying config found
Just loading my pack to see if it works

**Comment by T3DDY14** [comment]
https://gist.github.com/T3DDY14/e76196606011baf486f0fbc80a802f74

**Comment by T3DDY14** [comment]
Okay just tested it and it does not work even though it says it's found the file

**Comment by T3DDY14** [comment]
https://www.dropbox.com/s/hatw1dry8rnxy18/world.zip?dl=0  here is the world file and the server can read it

**Comment by T3DDY14** [comment]
There are no planets and I sent the world file which should have the planet Def file in it

**Comment by T3DDY14** [comment]
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/2785257/planetDefs.zip)

**Comment by zmaster587** [comment]
Using that XML file: 
![image](https://user-images.githubusercontent.com/3536685/51579243-3a12a300-1e8e-11e9-9901-e083b92bd6bc.png)
Modlist:
Forge1.12.2-14-23-4.2760
AdvancedRocketry-1.12.2-1.5.0-124-universal
LibVulpes-1.12.2-0.4.0-49-universal

Have you tested this without other mods installed?

**Comment by T3DDY14** [comment]
Which config

**Comment by T3DDY14** [comment]
Also I have over 100 mods installed on client and I think it could be sponge?

**Comment by T3DDY14** [comment]
Okay the planet must be discovered is set to false and what would be the best way to test which mod is causing the issue

**Comment by T3DDY14** [comment]
okay i tested it without the plugins and it worked so im not too sure what the issue is now

**Comment by T3DDY14** [comment]
okay now i have a different issue i now cant launch a rocket i get all the effects and it is filled with fuel just it wont take off

**Comment by T3DDY14** [comment]
also when i check the guidance computer when i select luna it says earth

**Comment by T3DDY14** [comment]
![image](https://user-images.githubusercontent.com/41326850/51633473-9edf0380-1f49-11e9-8eaa-c588d2d604f9.png)
