### ISSUE TITLE
Crash when loading game

### ISSUE THREAD

**Issue by CindyLouWho03** [zmaster587/AdvancedRocketry#1490]
## Version of Advanced Rocketry
121 and 123
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.4.0-1
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://paste.dimdev.org/vukimesesi.mccrash

## Description of the problem
By loading the game

**Comment by Rongmario** [comment]
I had a similar issue: https://hastebin.com/namiwanudu.rb

**Comment by zmaster587** [comment]
You need to have both the newest libvulpes and newest AR build, build 124 of AR and build 49 of libvulpes
