### ISSUE TITLE
Large Solar Panel Recipe Bug

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1493]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-125-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-49-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
The Large Solar Panel is crafted with 6x Large Solar Panels, making it unobtainable.

**Comment by zmaster587** [comment]
fixed with 
05f49b2
