### ISSUE TITLE
Oxygen Vent massive lag when placing many simultaneous blocks

### ISSUE THREAD

**Issue by tprussak** [zmaster587/AdvancedRocketry#1494]
## Version of Advanced Rocketry
1.5.0.-125
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.4.0.-49
## Version of Minecraft
1.12.2
## Crash report
This report is of when the server crashed due to not having any ticks in 60 seconds (from placing 500 blocks simultaneously)
https://pastebin.com/SEy55idw

## Description of the problem
When large numbers of blocks are placed simultaneously in an oxygen vent, it causes massive lag, scaling proportionately to the number of blocks being placed. The easiest way to reproduce this is with a large setting for the oxygen vent radius (I used a radius of 80 and a calculation method of 3) and an RFTools Shield Projector using a shape card. Building a shield of 25 blocks resulted in about 5000ms between ticks, and 500 blocks was over 60 seconds, which caused the server to shut itself down.

My guess is that it recalculates the fill area once for every new block that is placed, so when many blocks are placed simultaneously it recalculates the area hundreds of times.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
