### ISSUE TITLE
Airlock door not sealing

### ISSUE THREAD

**Issue by Rocksnotch** [zmaster587/AdvancedRocketry#1495]
## Version of Advanced Rocketry
1.4.1-120-UNSTABLE build -120 for 1.12.2
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.3.0-1-UNSTABLE build -1 for 1.12.2
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
Airlock doors are reporting back as leaking air. Using the seal detector it says it is leaking air, and my O2 Vent (which has both power and O2 being supplied to it) is failing to fill because of it. Currently playing Enigmatica 2

**Comment by Silfryi** [comment]
Retry on the newest version, as I cannot replicate this on the latest version.
