### ISSUE TITLE
lathe recipe

### ISSUE THREAD

**Issue by Atomicfruits** [zmaster587/AdvancedRocketry#1496]
## Version of Advanced Rocketry
[1.5.0]
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
[0.4.0]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
[Hi I'm in my survival world and I'm trying to make a lathe but I need iron rods for the lathe but the only way to make it is to use the lathe??? is there some other way or is it a bug?]

**Comment by Silfryi** [comment]
You can craft 3 iron ingots to four rods in a crafting table. Place them diagonally, going upwards to the right. There may be other ways if the mudpack you are playing has disabled that recipe. Look around in JEI if that does not work.
