### ISSUE TITLE
Crash when going to space

### ISSUE THREAD

**Issue by T3DDY14** [zmaster587/AdvancedRocketry#1497]
## Version of Advanced Rocketry
125
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
49
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://gist.github.com/T3DDY14/8a71212f23640e4f5273005c64a77f44

## Description of the problem
Have a server with sponge and other mods try and go to a space station and player will crash

**Comment by T3DDY14** [comment]
This does not occur with sponge I don't think and I believe this is the latest sponge that won't crash my server-------- Original Message --------Subject: Re: [zmaster587/AdvancedRocketry] Crash when going to space (#1497)From: Dmodoom Sirius To: zmaster587/AdvancedRocketry CC: T3DDY14 ,Author Does this occur without sponge? If no then Does this occur with the latest sponge? Try these and let me know how they work.

**Comment by MrEyeballs29** [comment]
I just noticed that template is blank for odd reason. Where on earth is the
info? You supposed to fill out information about what Mc version, which
forge version, and also paste the link that leads to the log. Oh yeah don't
paste it directly.

Just please follow the template rules, *please* and *thank* you.

I am going to work on my project so later. ]:(

**Comment by T3DDY14** [comment]
I filled the template in I remember doing it and I posted a log what happened here-------- Original Message --------Subject: Re: [zmaster587/AdvancedRocketry] Crash when going to space (#1497)From: Joe Issac III To: zmaster587/AdvancedRocketry CC: T3DDY14 ,Author I just noticed that template is blank for odd reason. Where on earth is the
info? You supposed to fill out information about what Mc version, which
forge version, and also paste the link that leads to the log. Oh yeah don't
paste it directly.

Just please follow the template rules, *please* and *thank* you.

I am going to work on my project so later. ]:(

**Comment by T3DDY14** [comment]
i just checked and its there

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
