### ISSUE TITLE
Minimal File Issue

### ISSUE THREAD

**Issue by BranTuna** [zmaster587/AdvancedRocketry#1498]
## _I caught this in my crash log..._

**Minecraft Version:** 1.12.2
**Minecraft Forge Version:** 14.23.5.2808
**Advanced Rocketry Version:** 1.5.0-126
**LibVulpes Version:** 0.4.0-49

> [05:10:45] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in [1.12.2] Advanced Rocketry by zmaster587 (1.5.0-126).jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [05:10:45] [main/WARN] [FML]: The coremod AdvancedRocketryPlugin (zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin) is not signed!

### **Note:** This showed up in the crash log 3 times whilst I was debugging my modpack. It seems to be spammed for many mods, actually.

**Comment by ezeiger92** [comment]
Is this ticket just to say "This message is annoying"? It's not something that would contribute to a crash

**Comment by BranTuna** [comment]
I just had no idea why this message has spammed the console for so many mods? I was curious, and thought to report it...

**Comment by ezeiger92** [comment]
That's fair, I'm not familiar enough with forge to explain why they yell about it (not the mod dev, obviously). I just didn't want you thinking that warning lead to a crash, because then you'd be off on a wild goose chase trying to get things running again D:

**Comment by dmodoomsirius** [comment]
that is fine. as long as its not crashing the game.
