### ISSUE TITLE
(Question) docking pads on planets

### ISSUE THREAD

**Issue by C0XB0X** [zmaster587/AdvancedRocketry#1499]
## Version of Advanced Rocketry
1.5.0.-126
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.4.0.-49
## Version of Minecraft
1.12.2
## Description of the problem
Is it possible to specify where a rocket lands on a planet by placing docking pads at either destination, linking them and then having the rocket launch from one to land on the other? (in my case earth and the moon). Whenever I launch a rocket from a linked docking pad on earth, it always lands in the same place on the moon where it first arrived using the planet id chip, and not the linked docking pad  (which is placed elsewhere). Thanks.

**Comment by scribbler957** [comment]
Did you try a docking pad? I don't know if they'll work on a planet.
http://arwiki.dmodoomsirius.me/AdvancedRocketry/blocks/LandingPad.php
The page has information on linking ID chips and stuff. I just got to space so I'm not in a position to test it just yet.
