### ISSUE TITLE
No information how to use mod

### ISSUE THREAD

**Issue by AnarchySage** [zmaster587/AdvancedRocketry#150]
Can you write a quick wiki on how to get started in the mod or make a book ingame for it. Would be extremely usefull. Thanks

**Comment by zmaster587** [comment]
There is a link to youtube videos on the curse page.  I do have a wiki half
written up but has a lot left to write.

**Comment by AnarchySage** [comment]
Yeah but the videos are update, and not so much a "how to" or anything

**Comment by zmaster587** [comment]
The first one on there should be general how the mod works, the rest are
update.  Once I get to a computer I'll link it

**Comment by AnarchySage** [comment]
Alright, why not create an open wiki and let users update/help?

**Comment by zmaster587** [comment]
I have a wiki half made, however most wiki hosting places either has nasty catches or is not free... If i could find one I would use it.
https://youtu.be/00XS_n6zR14 is the youtube with the main info.

**Comment by AnarchySage** [comment]
true, make a book ingame then

**Comment by AnarchySage** [comment]
`package com.vanityblocks.Dimensions;

import java.util.List;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import net.minecraft.nbt.NBTTagString;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

public class VbMwManual extends ItemBlock
{
    public static ItemStack manual;

    static
    {
        NBTTagCompound nbt = new NBTTagCompound();
        nbt.setString("author", "AnarchySage");
        nbt.setString("title", "Vanity Mining Dimension Help");

        NBTTagList pages = new NBTTagList();
        pages.appendTag(new NBTTagString("1", "      VanityBlocks\n      Mining World\n      Dimensions\n\nUser's Manual v1.0\n\n\n"
                + "Attention: If you still dont understand this, check the thread."));
        pages.appendTag(new NBTTagString("2", "Thank you for using the VB Dimensions Mod. Most everything can be changed in the config. Please check there for more config options."));
        pages.appendTag(new NBTTagString(
                "3",
                "This section will teach you how to make the portal shapes. You can see the design here(hard to explain) \n http://imgur.com/a/uKxAL \n The structure is always in that shape except for the hell dimension. "));
        pages.appendTag(new NBTTagString(
                "4",
                "Note the middle block in that structures bottom(the grass block(Redstone Ready world so discolored) \n Anyways, its the identifier, on the next page is biome name and its identifier block to open the portal there. \n (Lapis Block is always Required at top cept for hell)"));
        pages.appendTag(new NBTTagString(
                "5",
                "The possible dimensions are.. \n Plains - Grass Block \n Desert Hills - Sandstone Block \n Extreme Hills - Emerald Block \n Forest - Any Wood Log(Vannila)(direction doesnt matter) \n Taiga - Snow Block \n  Cont -> Next Page"));
        pages.appendTag(new NBTTagString(
                "6",
                "Swampland - Clay Block \n Shroom Island - Mycelium \n Jungle - Any leaves(Vannila) \n For the hell dimension its a bit different. All the stone is netherbrick and the lapis/identifer blocks are normal Nether Quartz Blocks."));
        pages.appendTag(new NBTTagString("7",
                "Then you right click with the lighter on the identifier block and the portals spawn, viola :) Enjoy. Please report any bugs you find, this was alot of work and effort for me."));
        pages.appendTag(new NBTTagString("7",
                "      Credits\nThanks to RebelKeithy for making Atum. Helped alot. \n\nThanks to mDiyo for help here and there. \n\nThanks to Kodos for helping with ideas/testing."));

        nbt.setTag("pages", pages);
        manual = new ItemStack(Item.writtenBook);
        manual.setTagCompound(nbt);
    }

    public VbMwManual(int id)
    {
        super(id);
        setContainerItem(this);
        setCreativeTab(DimensionManagement.tabDimensions);
        setMaxStackSize(1);
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Override
    @SideOnly(Side.CLIENT)
    public void addInformation (ItemStack stack, EntityPlayer player, List infoList, boolean advancedTooltips)
    {
        infoList.add("If you're lost, read the (in-game) manual");
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Override
    @SideOnly(Side.CLIENT)
    public void getSubItems (int itemId, CreativeTabs creativeTab, List subTypes)
    {
        subTypes.add(new ItemStack(itemId, 1, 0));
        subTypes.add(manual);
    }
}`


Bit of book code to help btw if you didnt know how it worked/used it

**Comment by zmaster587** [comment]
It'll take just as long to make an ingame book as it would a wiki.  I have hosting for a wiki, but user generated posts are out of the question for now.

**Comment by TheGuyRunningSouth** [comment]
@zmaster587 Doesn't the mod have a partially created wiki here on Github that can be edited by anyone? I remember pushing at least one page to a wiki somewhere.

**Comment by zmaster587** [comment]
I had forgotten about that, I'll push what I have to that later tonight

**Comment by AnarchySage** [comment]
So hows that info going @zmaster587 , cant seem to get started with the mod myself without some info, like where is dilithium, what does the observatory do, etc, get with direwolf20 for a proper spotlight, or something man, awesome mod, but i want to remove it for gc(just cause of lack of info :/)

**Comment by zmaster587** [comment]
There are several videos on YouTube which can be found on the curse forge
page for the mod

**Comment by zmaster587** [comment]
There are also several good walk throughs around youtube which come up if
you search the name of the mod.  As of late I have had no time to develop
the mod let alone write docs for it.  From what I understand, dire wolf
does not do reviews by just asking him.
On Jul 16, 2016 4:14 PM, "Taylor Loz" <zmasterfun@gmail.com> wrote:

There are several videos on YouTube which can be found on the curse forge
page for the mod

**Comment by AnarchySage** [comment]
i found one which explains the function of each block but thats it, not a guide line persee

**Comment by zmaster587** [comment]
I'll make a video guide at some point then

**Comment by AnarchySage** [comment]
Appreciate it, thanks, i can understand not having time to code, but video guide is easy, if i knew how to use it, i would have lol.

**Comment by TheGuyRunningSouth** [comment]
@zmaster587 If you want to send me what you have written already, I can attempt to get it posted. (Not rushing you, just offering help.)

**Comment by zmaster587** [comment]
This is the wiki as it is so far http://65.78.115.159:25565/AdvancedRocketry/

**Comment by AnarchySage** [comment]
Why not host it on github?

**Comment by zmaster587** [comment]
github does not allow 90% of the formatting I'm using to make it look polished

**Comment by DarkGuardsman** [comment]
@zmaster587 maybe he means host the site code on github so it can be downloaded & viewed?

**Comment by AnarchySage** [comment]
What dark said, sorry, just basic info for now then polish it up would be nice tbh

**Comment by AnarchySage** [comment]
@zmaster587 Heres another solution, makes you money as well, http://www.indiewikis.com/  Not sure how it works, came across it via mekanism wiki.

**Comment by DarkGuardsman** [comment]
As long as he puts ads on the site it makes money :)

**Comment by zmaster587** [comment]
I've got a site halfway built, just I don't have time to work on it.
https://github.com/zmaster587/AdvancedRocketryDoc

**Comment by zmaster587** [comment]
I've got it hosted here for now, wasn't linking it before due to bandwidth limitiations, but I've got it solved now.
http://65.78.115.159:25565/AdvancedRocketry/

**Comment by DarkGuardsman** [comment]
@zmaster587 if you have issues with bandwidth just tell dmod and I will host the files for you no problem :)
