### ISSUE TITLE
Server Crashes on startup, Ticking block entity

### ISSUE THREAD

**Issue by AngelShadow9451** [zmaster587/AdvancedRocketry#1501]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-126-universal.jar
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-49-universal.jar
## Version of Minecraft
1.12.2 Forge: forge-1.12.2-14.23.5.2784
## Crash report or log (if applicable)
https://pastebin.com/wTyJzzEr

## Description of the problem
It will crash at start up, after only a few seconds.

**Comment by AngelShadow9451** [comment]
That did seem to work thank you!

**Comment by zmaster587** [comment]
Great!  I'll push it then
