### ISSUE TITLE
[Assistance Required] 1.12.2 Custom Recipes

### ISSUE THREAD

**Issue by Morpheus1101** [zmaster587/AdvancedRocketry#1504]
Does this mod have CraftTweaker//ModTweaker Support?  If not i am told it has some sort of custom recipe system.

I ask as currently without using the UniDict Mod the ArcFurnace produces Steel from Thermal, Extreme Reactors & libvulpes and no other method ive tried has been able to resolve this. However using UniDict it at least produces 3 of the 1 mods steel, however i want to reduce it to 1 steel output.

Forge *.5.2808
Adv Rock v1.5.0-127
libvulpes v0.4.0-2

**Comment by dmodoomsirius** [comment]
The mod doesn’t have crafttweaker support but http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/RecipeConfiguration.php

**Comment by Morpheus1101** [comment]
Thanks, this will allow me to move forward in some more customizations with my pack.
