### ISSUE TITLE
microwave receiver

### ISSUE THREAD

**Issue by D3s0l4ti0n** [zmaster587/AdvancedRocketry#1506]
## Version of Advanced Rocketry
latest 1.7.10
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
latest
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
are microwave receivers supposed to only generate 10 rft a tick per solar panel installed in the satellites if so that seems pretty weak for base power gen , also when i flick it on and off it spikes to 1690 power gen then drops to  70 per tick

**Comment by NutMaster6942** [comment]
what
