### ISSUE TITLE
Trying to turn Galacticraft and Extra Planets Planets into AR planets through Dimmapping crash

### ISSUE THREAD

**Issue by ViciousGamer** [zmaster587/AdvancedRocketry#1507]
## Version of Advanced Rocketry
1.12.2-1.5.0-127-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.4.0-51-universal
## Version of Minecraft
1.12.2
## Forge Version
14.23.5.2807
## Crash report or log (if applicable)
https://pastebin.com/PMPEfj5E (i actually dont know if it is it or not i just copied the log from my launcher help i am not sure)

## Description of the problem
Title says it all
Note that without the planetDefs file everything works fine
[planetDefs](https://pastebin.com/H3yA4GWC)
[modlist](https://imgur.com/a/IhixP9O)
[Galacticraft planets config file](https://pastebin.com/F2B3bkJy)
[Extraplanets config file](https://pastebin.com/fdJM0vV4)

**Comment by zmaster587** [comment]
There's a syntax error in your XML file:
`<planet name="Earth" DIMID="0">` was `</planet name="Earth" DIMID="0">`, and your planet tags are missing the `</planet>` end tags
```
<galaxy>
    <star name="Serenity" temp="100" x="0" y="0" numPlanets="10" numGasGiants="1">
	  <planet name="Earth" DIMID="0">
            <atmosphereDensity>100</atmosphereDensity>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>1000</orbitalDistance>
            <orbitalTheta>180</orbitalTheta>
            <rotationalPeriod>24000</rotationalPeriod>
            <planet name="Moon">
                <fogColor>1,1,1</fogColor>
                <skyColor>1,0.5,0.5</skyColor>
                <atmosphereDensity>60</atmosphereDensity>
                <gravitationalMultiplier>20</gravitationalMultiplier>
                <orbitalDistance>150</orbitalDistance>
                <orbitalTheta>190</orbitalTheta>
                <rotationalPeriod>100</rotationalPeriod>
             </planet>
         </planet>
         <planet name="Mercury" DIMID="-13" dimMapping=""></planet>
		 <planet name="Venus" DIMID="-31" dimMapping=""></planet>
		 <planet name="Mars" DIMID="-29" dimMapping=""></planet>
		 <planet name="Jupiter" DIMID="-15" dimMapping=""></planet>
		 <planet name="Saturn" DIMID="-16" dimMapping="">
		     <hasRings>true</hasRings>
                  </planet>
		 <planet name="Uranus" DIMID="-17" dimMapping=""></planet>
		 <planet name="Neptune" DIMID="-18" dimMapping=""></planet>
		 <planet name="Pluto" DIMID="-19" dimMapping=""></planet>
    </star>
</galaxy>
```

In the future, you can try validating XML here to verify there's not any syntax errors: https://www.xmlvalidation.com/index.php

You may also want to consider adding properties for Mercury thru Pluto, Advanced rocketry will treat them as earthlike unless otherwise specified.

**Comment by PercyJames** [comment]
<galaxy>
    <star name="Sol" temp="100" x="0" y="0" numPlanets="1" numGasGiants="0">
        <planet name="Overworld" DIMID="0" dimMapping=""> 
            <fogColor>1,1,1</fogColor>
            <skyColor>0,0,1</skyColor>
            <atmosphereDensity>100</atmosphereDensity>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>20</orbitalDistance>
            <orbitalTheta>180</orbitalTheta>
            <rotationalPeriod>24000</rotationalPeriod>
            <biomeIds>0</biomeIds>
            <planet name="Moon" DIMID="-28" dimMapping="" customIcon="moon">
                <fogColor>1,1,1</fogColor>
                <skyColor>1,0.5,0.5</skyColor>
                <atmosphereDensity>180</atmosphereDensity>
                <gravitationalMultiplier>100</gravitationalMultiplier>
                <orbitalDistance>150</orbitalDistance>
                <orbitalTheta>190</orbitalTheta>
                <rotationalPeriod>100</rotationalPeriod>
                <biomeIds>94</biomeIds>
            </planet>
        </planet>
    </star>
</galaxy>

advanced rocketry 1.12.2-1.7.0-221-universal 

libvulples 1.12.2-0.4.2-75-universal

forge version 1.12.2-14.23.5.2847

galacticraft moon will not replace luna, and earth will not rename to overworld. explain
