### ISSUE TITLE
Rockets not building with same stats as scanned

### ISSUE THREAD

**Issue by BroCookiee** [zmaster587/AdvancedRocketry#1514]
## Version of Advanced Rocketry
1.12.2-1.5.0-128-UNSTABLE build -128 for 1.12.2
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.4.0-51-UNSTABLE build -51 for 1.12.2
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
1) Build rocket on launch pad with engines, tanks, guidance computer and seat
2) Check that structure tower is tall enough to cover entire rocket and more.
3) Scan rocket - see what appear to be valid stats
4) Build rocket, stats are all zero'd out, with 0.00m/s²
5) Rocket does not launch, only starts and drains fuel on the pad

Only mods installed are Advanced Rocketry, LibVulpes and JEI. This was previously working in my main world, but appears to have stopped. I updated to the latest versions available, encountered the same issue again. So I then set up a separate testing environment to replicate the issue and I was able to. The rocket configuration appears to be valid and many others have been tested. Is there just something I'm missing?

Thank you for making this mod, it is appreciated!

Screenshots
![2019-02-10_21 23 23](https://user-images.githubusercontent.com/47512758/52545053-35008f80-2d7a-11e9-9495-b27a0b8208da.png)
![2019-02-10_21 23 35](https://user-images.githubusercontent.com/47512758/52545054-35008f80-2d7a-11e9-89f0-c13e77fb5e71.png)
![2019-02-10_21 23 44](https://user-images.githubusercontent.com/47512758/52545055-35008f80-2d7a-11e9-891c-5a54d7a5534e.png)

**Comment by Silfryi** [comment]
The zeroed out stats are normal, as there is now a rocket entity and therefore no more blocks to scan and get stats from. How long did the rocket stay on the pad? And did it consume all of its fuel?

**Comment by BroCookiee** [comment]
Thank you for clarification there! The rocket remained on the pad until it's fuel ran out.

**Comment by Silfryi** [comment]
It is probably an error in the calculator, but Zmaster will have to have the final say.

**Comment by Offliner78** [comment]
Same Prob here. only "arrival not possible" version:"AdvancedRocketry-1.12.2-1.5.0-139"

**Comment by Silfryi** [comment]
I cannot reproduce this in the newest version, update and test again.
