### ISSUE TITLE
Space Flight Concept

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#1515]
So I have this Idea how to make space flight better:

Rockets
=====
When you fly into space with a rocket you get teleported to the 'space' dimension and get assigned a position in the galaxy (next to the planet you came from).
All planets, suns and moons in the system get rendered. You can fly around in the captain seat to change your position and fly to other planets/moons. This is all 2d, so you can't fly up (What do you think? Should it be 3d?).
If you launch a rocket while you are near a planet the rocket will land there.

Warping
======
Warping is essentially flying fast. You can't change your rotation in while warping. If you get into a gravity-well (like one from a planet or a sun) while warping the warp stops. You can stop a warp travel manually.

Docking / Meeting other space ships / SPACE BATTLE!
======================================
You can also see other space ships if you have sensors. Flying close to one teleports your ships next to it. If you build your ship larger than it was before, you have to reconfigure the warp core so its range includes the new blocks. This can  also be used to 'steal' other ships, but your warp core can't transport blocks that are shielded.

Combat / Weapons / Gadgets
=====================
There could be more low-range weapons now,  but long range could also work by targeting another space ship while being far away. Shields would absorb weapong damage including arrows, fireballs, tnt etc. Transporters would also be cool, you could set the position local to the spaceship (~ ~10 ~2) to configure its target. Tractor beams could work like this: You target some blocks and activate the beam. A white ball would travel along it, indicating where it would be placed if you deactivate it. Deactivating just teleports all blocks to the position of the white ball

Autopilot / AI / Autonomous Battle Agents
==============================
There could be a block that can steer and fly a spaceship automatically. Weapons could also be configured to shoot enemies or do orbital bombardement.

Research / Satelites
==============
Of course satelites should be real ships now. You can launch a rocket with some interplanetary engines, an autopilot, solar panels and some sensors and let it roam around the system. If it gets close to planets it will gather data about its biomes, gravity, resources, atmosphere and more. You can also use satelites to send items around in a system.

**Comment by Silfryi** [comment]
Orbital bombardment? Sounds amazing, maybe have Kinetic Bombardment with varying explosive damages from heavier rods, with iridium being nuke-sized? It is one of the densest elements, after all. https://en.wikipedia.org/wiki/Kinetic_bombardment

**Comment by ViciousGamer** [comment]
I think you can semi-orbital bombard a planet with the laser drill, because there is a config file for the drill to generate a hole in the coordinates it dug.

**Comment by Silfryi** [comment]
Yeah, but _giant explosions._ Also, this would not require power, just resources and time. Also would be much more destructive than the laser drill.
