### ISSUE TITLE
Iron rod dependency loop

### ISSUE THREAD

**Issue by TheMadmanofChaos** [zmaster587/AdvancedRocketry#1517]
## Version of Advanced Rocketry
1.12.2-1.5.0-128
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
1.12.2-0.4.0-51-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
In the current version of the mod, from a fresh installation in a pack containing only Advanced rocketry, LibVulpes, and JEI, iron rods can not be crafted inside a crafting table. The only listed way to craft them requires a lathe, which in itself requires iron rods. All other rod types can be crafted as normal in the crafting table.

No configs have been touched, and no recipe editing mods are present.
![2019-02-16_14 25 49](https://user-images.githubusercontent.com/5651102/52904820-0dd11480-31f7-11e9-9e7d-a45d26ccb701.png)
![2019-02-16_14 26 52](https://user-images.githubusercontent.com/5651102/52904821-0e69ab00-31f7-11e9-8bca-023e30c0193c.png)

**Comment by MrEyeballs29** [comment]
This looks like more of a core mod issue rather than an actual mod issue. :/

**Comment by TheMadmanofChaos** [comment]
Well, I would throw this on the page of LibVulpes but it doesn't have an issue tracker. Compound that with the fact both mods have the same author, so this seems like the best place for the issue. If you know of a better location to post this, I'll happily move it over there.

**Comment by MrEyeballs29** [comment]
Nevermind.

**Comment by zmaster587** [comment]
for the time being, the Advanced rocketry issue tracker is there the libvulpes stuff should go.  This may change when other mods that use libvulpes are finished.
Also, fixed the issue, it was a missing json.
