### ISSUE TITLE
Arc Furnace Not Crafting Steel

### ISSUE THREAD

**Issue by KaneHart** [zmaster587/AdvancedRocketry#1518]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-128-universal
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-51-universal
## Version of Minecraft
1.12.2

## Description of the problem
So I have quite a few mods installed but nothing that should effect Advance Rocketry besides UniDict to make the output of items to another mods like IC2 Steel.
Oddly enough it seems most if not all Arc Furnace recipes work but steel. 

**Setup:**
https://i.imgur.com/wdD5vgI.png
https://i.imgur.com/Hrt6LdH.png
https://i.imgur.com/P4MFSiv.png

**Recipe:**
https://i.imgur.com/kwh4JyL.png

N/m I removed unidict and it did not fix it but showed every single steel in the pack lol.

https://i.imgur.com/fYf2lWW.png

Thanks.

**Comment by lythro** [comment]
Just a +1:
I've got a similar issue, with `AdvancedRocketry-1.12.2-1.5.0-131-universal` and `LibVulpes-1.12.2-0.4.0-52-universal`. Though I'm just trying rocketry for the first time and am wondering why the furnace won't create silicon from sand, and neither does creating stell work. Haven't tried other recipes yet...

Oh, and I'm running the "A Bit Of Everything" modpack, if that helps?

Still looking forward to launching rockets. 🙂

**Comment by Silfryi** [comment]
I believe you need charcoal.

**Comment by lythro** [comment]
Well, yeah. Sorry for that, you are right: I created steel from iron and regular coal in another mod before and didn't notice that the arc furnace actually needs charcoal for this.

**Comment by tonyvans** [comment]
I am using charcoal and it isn't working, Second furnace, I have silicon being made in the first. both built exactly the same

![image](https://user-images.githubusercontent.com/6739653/62407482-167f9200-b56e-11e9-8235-003a27c54993.png)

![image](https://user-images.githubusercontent.com/6739653/62407486-26977180-b56e-11e9-936e-bd38d45c7475.png)

but it does work to make the Titanium aluminide

![image](https://user-images.githubusercontent.com/6739653/62407540-bd642e00-b56e-11e9-8569-61163dc7b889.png)


![image](https://user-images.githubusercontent.com/6739653/62407517-83932780-b56e-11e9-88b8-a2877562a5f5.png)

**Comment by KilledBySandvich** [comment]
Another +1...
All arc furnace crafting works except for the steel.

**Comment by Mrsneff** [comment]
Found a solution that worked for me, removed all except one output from the steel recipe in ElectricArcFurnace.xml at .minecraft/config/advRocketry. Right-click ->edit, and remove all except one of the diffrent mods steel ingot lines under output. I think the problem was that the output hatch only has 4 slots and the furnace was trying to create 9 different ingots at the same time.

**Comment by zmaster587** [comment]
There was a fix for a similar issue pushed last night https://github.com/zmaster587/libVulpes/commit/8a229a693458477f07a4250912a3d5b1f71af7d5.  Can anyone confirm if downloading the latest build of libvulpes and regenerating the XML files works?

**Comment by Cvn97** [comment]
> Found a solution that worked for me, removed all except one output from the steel recipe in ElectricArcFurnace.xml at .minecraft/config/advRocketry. Right-click ->edit, and remove all except one of the different mods steel ingot lines under output. I think the problem was that the output hatch only has 4 slots and the furnace was trying to create 9 different ingots at the same time.

This solution is what did it for me. Still apparent in this version. XML recipes are now outdated but this seems to be an issue with this older version of the mod.
