### ISSUE TITLE
RF Plug don't really consume rf 

### ISSUE THREAD

**Issue by quentfr21** [zmaster587/AdvancedRocketry#152]
hello

Advanced Rocketry 0.6.4
libvulpes 0.0.7

when you link a capacitor bank or energy conduit (from Enderio) to the rf plug, the rf plug don't drain power from capacitor but machine was fully powered 

thanks

**Comment by wormzjl** [comment]
so this issue is still there in the latest version?
What I got:
fill it with power using BC kinesis pipes
break the pipes
profit infinite power

**Comment by zmaster587** [comment]
Will check when i get off work

**Comment by wormzjl** [comment]
Seem that this only occurs for some machines, like rolling machine, lathe...

**Comment by zmaster587** [comment]
Only multiblocks?
