### ISSUE TITLE
Space station returning to earth at every restart

### ISSUE THREAD

**Issue by Mieskoh** [zmaster587/AdvancedRocketry#1521]
## Version of Advanced Rocketry
1.12.2-1.5.0-131-universal
## Have you verified this is an issue in the latest unstable build
No
## Version of LibVulpes
1.12.2-0.4.0-51-universal
## Version of Minecraft
1.12

## Description of the problem
Everytime I relog my space station is above earth, even if it was in another solar system.

**Comment by kugamer** [comment]
Is there any word on this? I am having the same issue in Enigmatica 2. Everytime I log off my spacestation returns to homeworld no matter what planet I was on.

**Comment by zmaster587** [comment]
Under what conditions does this occur?  Is it on a server, does it happen in single player?  Is there any mentions of moving the station to earth in the log file (ctrl+F "station")?

**Comment by kugamer** [comment]
I was on a single player player world, Enigmatica2 latest update. I just logged out and station was on stella. I logged in and it was back on "earth". The log generated has no mention of station.

**Comment by kugamer** [comment]
https://pastebin.com/r8zuyMLy

**Comment by zmaster587** [comment]
Does the warp controller also list earth as the current orbitting planet?

In single player with just AR, everything seems to work fine.
With the Enigmatica2 pack, when logging out and back in, the station is still orbitting the planet I was last on, however the graphic for the planet is missing.

I strongly suspect a mod interaction of some kind, can you test with just advanced rocketry?  If everything works as expected with that, can you identify the smallest set of mods required to replicate the issue?

**Comment by zmaster587** [comment]
So, with a fresh download, I'm not able to replicate the issue even with the latest Enigmatica2.  If I log out while standing on a station orbitting Stella, I log in and the station is still orbitting Stella.

**Comment by kugamer** [comment]
I have not made any modifications to configure. Only thing I can think of that would be different is a matter reciever is attached to the station linked to “earth”.

**Comment by zmaster587** [comment]
I think it's unlikely but not impossible.  AR's stations use custom callins to move around, so unless it's got AR integration, it's probably not it.   I'm leaning more towards maybe something to do with something in the temp.dat or the planetDefs.xml (what would be even better is if dim99, the id of the station you're using, and the /world/level.dat could be included too, then I don't have to build a station and it would include the entire setup).  I can't reproduce it on my end, so I was hoping that a save state where it was occuring might provide clues.

**Comment by slappav** [comment]
I'm also having this issue. Happens every time the server reboots. I just confirmed that it also happens on single player (every time the world is loaded).

It happens with the below settings in config. Setting both to the opposite values, solves the issue.
B:ResetOnlyOnce=false
B:resetPlanetsFromXML=true

**Comment by zmaster587** [comment]
@kugamer Are you also using these settings?

**Comment by zmaster587** [comment]
@slappav That would make sense, `resetPlanetsFromXML` forces the game to reload settings from the config folder and resets all spacestations.

**Comment by kugamer** [comment]
I finished the pack, but I did go back and check the config and yes, that is the way the config was set by the pack author. I am surprised more people hadn't said anything. I was watching direwolf20 playthrough the last week and he had the exact same issue.

**Comment by slappav** [comment]
B:ResetOnlyOnce=false is a great feature for anyone that does not use the generate random planets feature. But when it resets things that are not changed, it's broken in my opinion.

Could you do something like you did here instead? To only reset orphaned stations.
https://github.com/zmaster587/AdvancedRocketry/blob/ecd0c10557d41b696dd5ee02d19f0e33b6c44508/src/main/java/zmaster587/advancedRocketry/AdvancedRocketry.java#L1745

Anything else that gets reset with this config every time the server reboots, even when no changes are made to the config folder's planetDefs.xml?

**Comment by zmaster587** [comment]
Yeah, that actually already happens elsewhere, I'd just forgotten that the reset option was to reset EVERYTHING, not just planet data.

**Comment by slappav** [comment]
So resetPlanetsFromXML might strand you on a different planet then. Then what is the recommended way to update the world PlanetDefs.xml when new planets are added to the pack?
