### ISSUE TITLE
placing lightwood planks cause client lag

### ISSUE THREAD

**Issue by MSandro** [zmaster587/AdvancedRocketry#1522]
## Version of Advanced Rocketry
1.12.2-1.5.0-131-UNSTABLE build -131
## Version of LibVulpes
1.12.2-0.4.0-52-UNSTABLE build -52
## Version of Minecraft
1.12.2

## Description of the problem
if I place lightwood planks, my FPS drops from ~100 to ~5 for half a second.

**Comment by MrEyeballs29** [comment]
Where did you place it?

>

**Comment by zmaster587** [comment]
Does placing a torch cause lag too?
