### ISSUE TITLE
AtmosphericEffects "flickering"

### ISSUE THREAD

**Issue by superon** [zmaster587/AdvancedRocketry#1532]
## Version of Advanced Rocketry
[AdvancedRocketry-1.7.10-1.4.0-20]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[LibVulpes-1.7.10-0.2.8-34-universal]
## Version of Minecraft
[1.7.10]

## Description of the problem
the Slowness and mining fatigue effects occasionally run below their timers causing the player to gain regular mining/speed until it kicks in a second or 2 later, suggest having an atmospheric effects timer in the config as i feel setting them to about 5 minutes will resolve this issue, also thinking 5 minutes of "decompression" sounds fair :)

**Comment by dmodoomsirius** [comment]
1.7.10 is not supported at this point in time. Closing this issue.
