### ISSUE TITLE
[Question} Planet Discovery/UnDiscovery 

### ISSUE THREAD

**Issue by jaxmacky** [zmaster587/AdvancedRocketry#1533]
## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.5.0-131-UNSTABLE build -131 for 1.12.2
## Version of LibVulpes
LibVulpes 1.12.2-0.4.0-52-UNSTABLE build -52 for 1.12.2
## Version of Minecraft
1.12.2

## Description of the problem
How does one reset the Discoverability of a particular Planet or Planets for ModPack Development purposes. 
With:
planetsMustBeDiscovered=true (advancedRocketry.cfg)
&
isKnown=false (planetDefs.xml-Per Planet)

Once a planet is discovered via Warp Controller, where is that data stored so that it may be reset or removed?

**Comment by Nomad7** [comment]
I have a very similar question; we originally used the default config for AR which has planetsMustBeDiscovered=false, but some of our players thought the discovery process would be more fun so we changed it to planetsMustBeDiscovered=true.

However, I've already built my space station and warp core, and am seeing all of the stars & planets on my list even after the config change. Is this expected, and I just can't choose them as destinations until I've discovered them? Or should other planets not show up in the Warp Core map at all until I've discovered them first?

I'm on AR v1.5.0-139 and LibVulpes v0.4.0-26, Minecraft 1.12.2 (Enigmatica 2 Light modpack).
