### ISSUE TITLE
Rutile ore processed to Rutile ingots instead of Titanium by RotaryCraft and AOBD2

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [zmaster587/AdvancedRocketry#154]
Because the ore dictionary entry for rutile ore is oreRutile instead of oreTitanium, both Another One Bites the Dust 2 and RotaryCraft assume that its processed form should be rutile dust, flakes, ingots, etc. instead of titanium dusts, flakes, and ingots, which can get a bit messy if one unwittingly attempts to process any rutile ore through any other mod's production chains.

May I suggest changing the ore dictionary key for rutile ore to oreTitanium (similar to how Immersive Engineering's Bauxite ore is oreAluminum instead of oreBauxite)?

**Comment by nekoexmachina** [comment]
Nope, still have an issue with Rotarycraft and AOBD2. 
![screenshot from 2017-02-11 00-45-16](https://cloud.githubusercontent.com/assets/3796961/22848433/9e1c7ee0-eff4-11e6-80b1-e154d7b8ee40.png)
![screenshot from 2017-02-11 00-45-24](https://cloud.githubusercontent.com/assets/3796961/22848434/9e1cb770-eff4-11e6-832b-e68f3b7e7714.png)
Latest versions of all the mods.

**Comment by nekoexmachina** [comment]
Grinder processes it to titanium flakes, problem only exists in the extractor.

**Comment by nekoexmachina** [comment]
Last comment was intended to go to the issue in Reika's repo. Sorry!

**Comment by Barhandar** [comment]
Unless you intend your Rutile to be processed like Mariculture's (ore - unusable rutile - titanium) I suggest not registering it as oreRutile at all, only oreTitanium.

**Comment by zmaster587** [comment]
That's actually probably the best course of action
