### ISSUE TITLE
Editing Recipe for Carbon Collection Cartridge in Chemical Reactor results in endless creation of outputs

### ISSUE THREAD

**Issue by ConnorMiner** [zmaster587/AdvancedRocketry#1540]
## Version of Advanced Rocketry
1.5.0-133
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
0.4.0-52
## Version of Minecraft
1.12.2

## Description of the problem
1: Install LibVulpes and Advanced Rocketry
2: Edit config for the Chemical Reactor
3: Insert a used Carbon Collection Cartridge
4: INFINITE ITEMS!!!!

**Comment by dmodoomsirius** [comment]
what mod are you using to edit the recipe? if ARTweaker can you please paste the script file into a gist or a pastebin and link them here and if its the xml/json files in the config folder please post them on gist or pastebin and link those here.

**Comment by ConnorMiner** [comment]
Here is the xml file:
https://drive.google.com/file/d/1cuZPGqK6fkxR7s3rpJTOQc9iJW20Lwg7/view?usp=sharing

**Comment by zmaster587** [comment]
as it turns out 32767 can't be used as a value for the damage because it's forge's wildcard value.  Should all be fixed in the next update, max damage for the Carbon Collection Cartridge is being changed to 32766.
