### ISSUE TITLE
Solar Generator Issues

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#1542]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-132-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-51-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
Solar Generators do not work on Space Station while it's raining in the overworld. Tested with Mekanism Solar Neutron Activators

**Comment by Silfryi** [comment]
This might be more of a Mekanism issue than an Advanced Rocketry issue, post it on the Mek tracker as well.

**Comment by NillerMedDild** [comment]
Roger :)
https://github.com/mekanica/mekanica/issues/46

**Comment by dizzyd** [comment]
I've been overhauling the solar panels in Mekanica to account for this, but one unexpected problem I ran into is that the [WorldProviderPlanet](https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/world/provider/WorldProviderPlanet.java#L199) winds up calling the base implementation for sun brightness...which then incorporates rain strength into the brightness factor. My suggestion is that the call to the super should be removed to avoid variation in the brightness strength when the given planet/dimension can't even support rain. :)

**Comment by Poxorosa** [comment]
> This might be more of a Mekanism issue than an Advanced Rocketry issue, post it on the Mek tracker as well.

this problem is not only in mekanism mod. This problem appears in galacticraft too.
