### ISSUE TITLE
[Bug] Astrobody Data Processor

### ISSUE THREAD

**Issue by jaxmacky** [zmaster587/AdvancedRocketry#1543]
AdvancedRocketry-1.12.2-1.5.0-132-universal.jar
LibVulpes-1.12.2-0.4.0-52-universal.jar
1.12.2

 Astrobody Data Processor capped at holding 1000 Data out of 2000, each type effected.

**Comment by MyNameIsKodos** [comment]
Can confirm this is still an issue in 134. 

In addition, when using more than one filled data sticks in the IO of an ADP, the extra sticks' data is consumed and wasted as well.

**Comment by zmaster587** [comment]
Filled Data sticks shouldn't be stacking to begin with.  Fixing that should make it impossible to accidently consume data from extra sticks.

Unfortunately I cannot replicate the issue.  Using two seperate sticks to fill the data in the ADP, one after another, results in the data being filled completely to 2000

**Comment by MyNameIsKodos** [comment]
Then the issue is probably based around the fact that we/I was testing with a stack of filled data sticks. I hadn't thought to test with a fresh one. I will do so later this evening and edit this comment with results.
