### ISSUE TITLE
Syntax error on wiki

### ISSUE THREAD

**Issue by Spaig** [zmaster587/AdvancedRocketry#1544]
## Version of Advanced Rocketry
[N/A]
## Have you verified this is an issue in the latest unstable build
N/A
## Description of the problem
[How can you reliably reproduce the problem]
Binary star specification example on wiki says:

`<galaxy>
    <star name="Sol" temp="100" x="0" y="0" numPlanets="1" numGasGiants="0" blackHole="false">
        <star name="Sol-2" temp="200" seperation=10.0 />
        <planet name="Jole">
            ...
        </planet>
    </star>
</galaxy>`

This is incorrect, the seperation value should be in quotation marks. 

(Also separation is spelled wrong, but I know that's a trickier fix)

**Comment by zmaster587** [comment]
Fixed!  Misspellings in the config should correct themselves after the first time running it with the new build of AR
