### ISSUE TITLE
Moon biome explicitly prohibits spawning

### ISSUE THREAD

**Issue by timhuff** [zmaster587/AdvancedRocketry#1545]
It appears that the moon biome is hard-coded to not permit mob spawning. This prevents the `<spawnable>` tag from being used in `planetDefs.xml`

https://github.com/zmaster587/AdvancedRocketry/blob/b9733aaa946a6c4315a74b8e4d15a087dbff2324/src/main/java/zmaster587/advancedRocketry/world/biome/BiomeGenMoon.java#L29

**Comment by zmaster587** [comment]
I'm not entirely convinced this is the issue.  Adding things like minime's or entities that do not nomally spawn still works and those are not returned in the list by getSpawnable.
Minecraft also has seperate code for spawning entities in the world after the chunk has finished loading in `findChunksForSpawning`.  This is ultimately where `net.minecraftforge.event.ForgeEventFactory.getPotentialSpawns` is called from which in turn calls AR's spawning code.

**Comment by zmaster587** [comment]
It could be the fact that getSpawningChance is 0 though :thinking:

**Comment by timhuff** [comment]
So I cloned down the repo and have been experimenting with modifications. Removing both methods results in all creatures spawning (and subsequently dying). I modified my configuration to let skeletons survive without an atmosphere. That lets them not die. The issue I seem to be running up against is having the biome respect the configuration to *only* spawn skeletons.

**Comment by timhuff** [comment]
also, I've been making these changes to both `BiomeGenMoon` and `BiomeGenMoonDark`

**Comment by zmaster587** [comment]
Weird thing I'm getting is that the code to do the spawning seems to be running without any modifications to the game, the canCreatureSpawnHere check passes, it eventually gets to `worldServerIn.spawnEntity(entityliving)` despite the list being empty.

![image](https://user-images.githubusercontent.com/3536685/54508331-fc754800-491b-11e9-86cc-4b8da9cf3c57.png)

**Comment by zmaster587** [comment]
So... turns out setting atmosphere density to 100 suddenly makes a ton of skeletons show up.

**Comment by timhuff** [comment]
I'm pretty unfamiliar with all this (this is literally my first dive into minecraft mods). But you don't have some sort of global mob/atmosphere restriction, do you? Seems odd that you're seeing that behavior when I do see them spawn but die. It might help to know that I'm on commit `22c4ef8e85ef8d59c28608a44c90488134492843`. I'm running on FTB Continuum, so I needed Vulpes < 0.4

**Comment by zmaster587** [comment]
The only one i remember having will slowly kill mobs, not prevent them from spawning, I'm still looking to see if there's something I put in and forgot.

**Comment by zmaster587** [comment]
Are you seeing them spawn and die without your modifications?

**Comment by timhuff** [comment]
No. I had to make modifications to see anything at all. I seem to have it working, though. I'm reviewing my changes...

**Comment by zmaster587** [comment]
> So... turns out setting atmosphere density to 100 suddenly makes a ton of skeletons show up. At least with the above config.

I may have spoke too soon, after turning the atmosphere back to 0, they still spawn.  This is confusing, maybe I hadn't waited long enough?

**Comment by zmaster587** [comment]
if they're spawning and dying, the only thing you should need to do is change entitryAtmBypass in the config to include skeletons like this:
```
    S:entityAtmBypass <
	minecraft:skeleton
     >
```

**Comment by timhuff** [comment]
So it looks like the only changes I have at this point is I removed `getSpawningChance` from both Biome objects. That, along with the modifications to the two config files (the one you mentioned in your last comment and the `<spawnable>` tag you mentioned above)

**Comment by timhuff** [comment]
If you're seeing different behavior, perhaps it's something that changed between `22c4ef` and your commit?

**Comment by zmaster587** [comment]
I'm sorry, I totally glossed over the commit number in your earlier comment.  It's very possible something has changed.  Looking over the diff...

**Comment by timhuff** [comment]
You know... after taking a closer look, it seems that perhaps it's still spawning all creatures but the super-high `weight` attribute is just making the skeletons an overwhelming majority. On my minimap, I see red dots show up/disappear from time to time and I occasionally run into rotten flesh on the ground.

**Comment by timhuff** [comment]
I'm reducing weight to `1`...

**Comment by zmaster587** [comment]
It's possible, though if you've only changed the spawn chance and not the list, im not sure if other mobs would spawn or not.

**Comment by timhuff** [comment]
What is the mechanism by which the `<spawnable>` tag is brought in? I'd assume it defaults to all creatures in the absence of such a tag? But then restricts to only those entities if at least one exists?

**Comment by zmaster587** [comment]
Unless you're using a debugger, im not sure reducing weight would be solid test, there's a lot of other things that occur between choosing the entity that could make them spawn or not spawn.  Light checks, air checks, etc.

**Comment by timhuff** [comment]
Ah, yea, I wouldn't know where to begin in setting up a debugger against this. I'm literally changing, compiling, replacing the jar, restarting the game, goto 1.

**Comment by zmaster587** [comment]
the spawnable tag is read from the XML, it resolves class names from the entity name, stores the relevant data with it (nbt, minGroup, maxGroup, etc) then is put into a list stored in the dimension properties.  Then that gets read by the SpawnEntity event in event/PlanetEventHandler.SpawnEntity.

**Comment by zmaster587** [comment]
Are you using an IDE?

**Comment by timhuff** [comment]
nah. This all started as a "I wonder...", so I just edited the files in Visual Studio Code. I have Eclipse installed and do Android dev for work, so I'm familiar, but the idea of tapping it into a running minecraft instance made me go "eh, let me just see if I can `gradle`".

So, this might be good to know - ever since I reduced the `weight` attribute, I'm seeing *a lot* more non-skeleton drops. So it looks like maybe that `getSpawnableList` override doesn't really do anything - and the `getSpawningChance` override was added to do what it wasn't doing?

**Comment by zmaster587** [comment]
Maybe I wasn't patient enough before.  Skeletons still spawn regardless of atmosphere setting it seems.  This being with the mentioned config changes and the code in this commit bf64a0a39e9ad6d10c6de80c5d0d39485a08dd3e

**Comment by timhuff** [comment]
I can't run against that commit due to `libVulpesVersion=0.4.0`

**Comment by zmaster587** [comment]
how much of a pain would it be to move to a newer version of libvulpes?

**Comment by timhuff** [comment]
I mean... you tell me. haha. I have an install of FTB Continuum. I'll try to download the libvulpes 4.0 jar and replace it

**Comment by zmaster587** [comment]
I you're just compiling AR and running it, it shouldn't be too bad, I wouldn't work on it in a world that you'd want to keep though.

**Comment by timhuff** [comment]
nah, this is just a test world for a multiplayer server. I'm backing up the jars I need.

I've got 4.0 installed, branch `1.12` checked out, with my modifications retained, compiling... launching...

**Comment by zmaster587** [comment]
Alright.

I set a breakpoint in `WorldServer.getSpawnListEntryForTypeAt(EnumCreatureType creatureType, BlockPos pos)`, on bf64a0a (unmodified).  I'm only seeing the listing for skeleton here, no other mobs.

**Comment by timhuff** [comment]
That... seems to work. I've been exploring caves to get around time issues. I'm seeing skeletons... no other mob drops.

**Comment by timhuff** [comment]
I'm still inspecting to make sure it's not a fluke

**Comment by timhuff** [comment]
Yea... I'm not seeing anything but skeletons

**Comment by zmaster587** [comment]
I'm not seeing anything in the diff between 22c4ef8e85ef8d59c28608a44c90488134492843 and  bf64a0a that I'd expect to affect it.  hmmm

**Comment by timhuff** [comment]
On second thought... those skeletons may have been remnants from a previous load. Do they persist across reboots?

**Comment by timhuff** [comment]
Currently running to chunks that are definitely new

**Comment by zmaster587** [comment]
I was watching them appear in front of me

**Comment by zmaster587** [comment]
Admittedly I am on a old save, I'll try loading a new world and seeing what happens though.

**Comment by timhuff** [comment]
just found a large underground crevasse. It's empty. Disregard my earlier comments. There seems to be no spawning.

**Comment by zmaster587** [comment]
They should show up on the surface too

**Comment by timhuff** [comment]
I'm confused by how that works on the moon (pretty new to this mod). If I do `/time set night`, I can still see the sun.

**Comment by zmaster587** [comment]
They appear to still be spawning in a brand new world for me.

/time set night (I believe, I don't know for sure) is set to change the world time to 13000 ticks.  Because Advanced Rocketry does it's day night cycle by changing the angle of the sun with respect to the number of ticks, 13000 ticks may not always be night time.

You can set it to be the same as the overworld by running `/advRocketry planet set rotationalPeriod 24000` as OP while standing on the target planet or changing the rotational period in the XML to 24000

**Comment by timhuff** [comment]
that seems to have worked in getting night. That's a really cool mechanic. Still no skeletons, though. You only removed the `getSpawningChance` method, right?

**Comment by zmaster587** [comment]
I've been testing  bf64a0a without any modifications to it.

**Comment by timhuff** [comment]
alright. I'll stash my changes and load a new world

**Comment by zmaster587** [comment]
What I've been doing to test is teleport to a new location and just stand in one spot for 15 to 30 seconds while looking around.

**Comment by timhuff** [comment]
alright. So after creating a new world, it seems to be working. Might this be a property that is set upon the creation of the dimension or soemthing?

**Comment by zmaster587** [comment]
It's set when the XML is loaded which is whenever you load a save.  All the data that's not vanilla gets put in either the XML or the temp.dat.  The spawnable is only in the XML though.

Actually, quick question, which planetDefs.xml are you modifying?  the one in the config folder, or the one in the saves/<world>/advRocketry folder?

**Comment by timhuff** [comment]
oof. I didn't realize there were two. I've been modifying the one in the config folder

**Comment by zmaster587** [comment]
That could do it.  The one in the config folder is only read when the world is first created.  The one in the saves/WORLD_NAME/advRocketry folder is read every time the world loads.  I just kinda assumed you were modifying that one and didn't think to ask.  Sorry about that.

**Comment by zmaster587** [comment]
I suppose it might be a good time to give it a go on the older build again?

**Comment by timhuff** [comment]
And that explains the test I just ran, where I replaced my jars and created a new world and it worked perfectly...

**Comment by timhuff** [comment]
Wow. Thank you for all the time you've spent on this. Apologies for getting caught on such a minor issue.

**Comment by zmaster587** [comment]
yeah, that'd also explain the behavior difference too.

**Comment by zmaster587** [comment]
No problem!  I still want to know why things were not spawning for me earlier for a little bit of time though.  I should probably make an explicit comment on the wiki.  This isn't the first time this has happened, though it's certainly the longest without having a clue what's going on.
