### ISSUE TITLE
[Bug] GC solar panels crashing the game and destroying half of my ship.

### ISSUE THREAD

**Issue by Poxorosa** [zmaster587/AdvancedRocketry#1547]
## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.5.0-136-UNSTABLE build -136 (latest)
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes 1.12.2-0.4.0-53-UNSTABLE build -53 (latest)
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/qeKSDW2J

## Description of the problem
When I build my rocket with GC solar panels on the ship, game just crashes and after restart my ship just destroying to half

**Comment by dmodoomsirius** [comment]
Did you report this to GC as well?

**Comment by Poxorosa** [comment]
> Did you report this to GC as well?

this happens in new AR version. In older version all ok and I think problem in AR

**Comment by Poxorosa** [comment]
Ok, GC devs fix it in the new build

**Comment by dmodoomsirius** [comment]
> Ok, GC devs fix it in the new build

since you said that the GC devs fixed this in new build i am going to close this issue.
