### ISSUE TITLE
astroid chip not programable in observetory

### ISSUE THREAD

**Issue by hacker104** [zmaster587/AdvancedRocketry#1548]
## Version of Advanced Rocketry
1.12.2-1.5.0-136
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.12.2-0.4.0-53
## Version of Minecraft
1.12.2

## Description of the problem
i can't program a astroid chip in the observetory

**Comment by jaxmacky** [comment]
Observatory needs at least 100 Distance Data, and it to be night time to scan for Asteroids. Red Letter Scan Button means no Data. This may not be your issue, but adding it anyways.

After choosing an Asteroid, click the gears between the Unprocessed Chip and the empty slot "Process Discovery". and the processed Asteroid Chip should switch to the empty slot. 

Chip must then be filled with Data in the ADP multiblock before using in Sat Rocket. This may not be your issue either, but adding it anyways.

If still unable process chip, break the Observatory block, replace and Try again.

**Comment by hacker104** [comment]
if i click on the gears then it doesn't do enything

**Comment by Silfryi** [comment]
Do you have the required everything? Did you turn it on?

**Comment by hacker104** [comment]
yes i did

**Comment by hacker104** [comment]
but in the night it doesn't open to

**Comment by hacker104** [comment]
m

**Comment by eduradboranov** [comment]
Running into this issue also, in Enigmatica 2 Expert Modpack, but SMP.
Modpack original libVulpes and AdvancedRocketry mod versions;
 AdvancedRocketry-1.12.2-1.5.0-139
 LibVulpes-1.12.2-0.4.0-56

**Comment by dmodoomsirius** [comment]
You are using a old version. Are you on the latest enigmatica 2?? I thought they updated to a more recent version of ar.

**Comment by eduradboranov** [comment]
> 
> You are using a old version. Are you on the latest enigmatica 2?? I thought they updated to a more recent version of ar.

Correct, I was running Enigmatica2 v1.72a.  I didn't update as I couldn't spot any useful fixes in their patch notes.  But just updated it to 1.76a and much to my surprise, it's working fine - chip programs as expected, and observatory dome opens/closes with day/night cycle.

Sorry for the noise! :]

**Comment by dmodoomsirius** [comment]
It is fine. I wanted to make sure it worked. Thanks for confirming that.

**Comment by Splutty** [comment]
Ran into this same issue. The first chip worked fine, now clicking the gears does nothing.

AR: 1.12.2-1.7.0-209
E2E: 1.80
Forge: 1.12.2-14.23.5.2847

**Comment by Splutty** [comment]
And it just got worse. Not the observatory just eats my chips. Scan, Select an Asteroid, click gears, and the chip just disappear.

It's at night, and nothing in the log or the debug log.
