### ISSUE TITLE
Satellite Crash 

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#1550]
## Version of Advanced Rocketry
1.5.0-36
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.4.0-53
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)

https://paste.dimdev.org/unidiwigej.mccrash

## Description of the problem
I built a rocket with a satellite and guidance computer and I gave the guidance computer a planetary chip with earth selected as the destination.  Then I opened the satellite bay when the rocket returned causing the crash.  I'm pretty sure dynamic surroundings/orelib is involved.  If you need more info let me know.

**Comment by zmaster587** [comment]
Does this occur without DynamicSurroundingsCore installed?

**Comment by mxnmnm** [comment]
I haven't tested and it happens somewhat randomly so I'm not sure how to recreate it.  But just messing around with stuff causes it to happen.  So I'm not sure

**Comment by mxnmnm** [comment]
idk if it's still an issue or not

**Comment by dmodoomsirius** [comment]
are you able to test and verify with the latest build please?

**Comment by mxnmnm** [comment]
Yea I can't really recreate it so I guess I'll close this issue, I'll make a new issue if anything happens
