### ISSUE TITLE
Weird Client crash when opening guidance computer of a Rocket

### ISSUE THREAD

**Issue by ben-mkiv** [zmaster587/AdvancedRocketry#1559]
## Version of Advanced Rocketry
1.5.0-136
## Have you verified this is an issue in the latest unstable build
no
## Version of LibVulpes
0.4.0-53
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
different ones linked in this issue => https://github.com/HellFirePvP/AstralSorcery/issues/1049

## Description of the problem
When opening the Guidance computer of a rocket the client game crashs randomly to Desktop (crashs like 90% of tries to open the guidance computer gui). 

(Modpack is Enigmatica2Expert)

**Comment by zmaster587** [comment]
Does this occur without cyclicmagic installed?
