### ISSUE TITLE
Cannot place any block in the moon

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#156]
It crashes when place a block in the moon. 
http://pastebin.com/zdAJHL9m

Also it has regular gravity, no low gravity. 
0.6.4

**Comment by zmaster587** [comment]
Can you send me your world/advRocketry/temp.dat file?

**Comment by Tarkov** [comment]
Galacticraft was installed first, but it also happens in new games.

I think it is related with Galacticraft´s air, if OverrideGCAir is set to false, it crashes when place a block.

The low gravity in the moon do not work for me since 0.5.5

Also I cannot find Dilithium ore anywhere, I mined the moon with a few quarries and also tried in other planets and nothing found.

[temp.dat.zip](https://github.com/zmaster587/AdvancedRocketry/files/352301/temp.dat.zip)

**Comment by zmaster587** [comment]
do the other planets have earth gravity?

**Comment by Tarkov** [comment]
The other planets and moons have slightly changes in gravity. I did not notice them till I measured the jumps, ranging between one to two meters high.

By the way, I do not know how to use github properly or make a language file, I tried to make a pull request with no exit, so I do not know where to put this, but in the link you can find the spanish translation for Advanced Rocketry.

http://pastebin.com/2eGfSRJu

**Comment by zmaster587** [comment]
Can you paste a full server start log?  Also which spanish?  There's Spain, Mexican, Uruguay, Venezuelan variations.

**Comment by Tarkov** [comment]
Not sure if this is what you need.

http://pastebin.com/hmX7kKqy

The translation is spanish from Spain.

**Comment by zmaster587** [comment]
I need the FML-latest.log, unfortunatly the client log file doesn't contain much useful information.

**Comment by Tarkov** [comment]
latest.log 
http://pastebin.com/S3d2v7Ri
fml-client-latest.log
http://pastebin.com/WrSfUEUC

**Comment by zmaster587** [comment]
odd... not seeing anything.. on the moon what is printed if you run the command "/advRocketry planet get gravitationalMultiplier"?

**Comment by Tarkov** [comment]
It says 0.166
