### ISSUE TITLE
Crashes on dedicated server because ClassNotFoundExeption ITooltipFlag is missing

### ISSUE THREAD

**Issue by Benedikt20** [zmaster587/AdvancedRocketry#1562]
## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.5.0-137-UNSTABLE build -137 for 1.12.2
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes 1.12.2-0.4.0-54-UNSTABLE build -54 for 1.12.2
## Version of Minecraft
1.12.2 (modded) forge-14.23.5.2825
## Crash report or log (if applicable)
https://pastebin.com/9WNeUzy5 

## Description of the problem
When I start a server with your mod enabled I get an error message that the class _ITooltipFlag_ is missing. I serached for the reason of this error and found something. It seems that _ItemTooltipEvent_ in forge now referernces the client-only _ITooltipFlag_ . This causes your mod to crash on dedicated servers with a _ClassNotFoundException_ . The only fix for this would be to mark the handler method as client-only.

**Comment by dmodoomsirius** [comment]
Does this happen with only libVulpes and advanced rocketry? Please paste in the atual crash report found in the crash report folder.

**Comment by PG-Fuury** [comment]
/mnt/./crash-reports/crash-2019-04-09_16.23.17-server.txt should be the location according to the pastebin.

Seems to me that the mod actually triggering the crash is mhfc, which afaict is located [here](https://minecraft.curseforge.com/projects/monster-hunter-frontier-craft) with the github issue page [here ](https://github.com/Guild-Hall/MHFC/issues)

**Comment by Benedikt20** [comment]
I read through the log again and it realy seems that mhfc is causing the crash while advanced rocketry itself then has an error because of this. I will try again tomorrow if it still crashes without mhfc and write back again. If it is in Fact MHFC I will post this issue to their site. even if there isn't any development going on since November.
