### ISSUE TITLE
Override the WorldProvider#canSleepAt Method

### ISSUE THREAD

**Issue by jaxmacky** [zmaster587/AdvancedRocketry#1568]
-AdvancedRocketry-1.12.2-1.5.0-138-universal.jar
-LibVulpes-1.12.2-0.4.0-54-universal.jar
-MC 1.12.2

Comfort Mod Sleeping Bags Explode. 

"Okay, I figured out the issue. Advanced Rocketry actually overrides regular beds with their own "space-friendly" copy when you place them down, and these do not have any explosion logic at all which is why they don't explode. Vanilla beds will explode, it's just that Advanced Rocketry never lets you place a real vanilla bed down. Advanced Rocketry needs to override the WorldProvider#canSleepAt method so that modded beds like mine do not explode." -TheIllusiveC4

**Comment by jaxmacky** [comment]
Also, sleeping in a regular bed does NOT change time to day.

**Comment by jaxmacky** [comment]
Any update on a Comforts/SleepingBag Mod compat?

**Comment by zmaster587** [comment]
I can take a look, last time i handled the code none of this existed, so I have to make sure things mesh well.

**Comment by zmaster587** [comment]
It looks like it should be workable.  Implemented in 026cc62

**Comment by MrEyeballs29** [comment]
Since 1.12 the beds are wrong color when placed an vanilla.
