### ISSUE TITLE
client crash when opening rocket inventory

### ISSUE THREAD

**Issue by ascendedqbit** [zmaster587/AdvancedRocketry#1570]
## Version of Advanced Rocketry
1.5.0-139
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.4.0-54
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/wrGVc9W8

## Description of the problem
Trying to open a rocket inventory disconnects from a server pretty much 95% of the time, regardless if you're trying to open a rocket with a satellite bay or a rocket with a guidance computer. Neither of those crashes seem to happen on single player.

I first thought this was an instance of issue #1559 but neither the crash report provided there nor any relation with cyclicmagic ( I removed it to test ) had any effect on the issue.

Pack is a custom one (mod list can be taken from https://pastebin.com/VQFdtbPm, an older crash unrelated to this, but showing the loaded mods with their versions (aside of advancedrocketry, which I updated to -139, libvulpes likewise updated to -54 and cyclic which I removed to test if its crash related per #1559 ).

IF you need anything else to reproduce, please let me know.

**Comment by MagicWookie** [comment]
Having the same issue occur while using the Enigmatica 2 Expert modpack. Happened while using 1.5.0 -132 and 1.5.0-138.

https://paste.dimdev.org/agijobifod.mccrash

The game will even crash the moment I assign a hotkey to open the rocket GUI.

**Comment by MagicWookie** [comment]
Found a workaround: Needed to scan and then press the build option on the assembly, then you can access the GUI while sitting in a seat. Still crashes if we try and access the GUI while not in a seat.

**Comment by ascendedqbit** [comment]
Above mentioned workaround by @MagicWookie does not work for me, however I was able to access the satelite bay while the satelllite was disasembled. less convinient, but a workable workaround for now.
