### ISSUE TITLE
[From Discord] Addition of Bussard Ramjets as Subluminal Propulsion

### ISSUE THREAD

**Issue by Silfryi** [zmaster587/AdvancedRocketry#1572]
Bussard ramjets collect their fuel from the medium through which they travel, allowing them to only require power. They are fusion engines, and therefore subluminal.  They would be used for interplanetary travel only, no traveling to other systems. They would be affected by coil tier for speed and power usage, with speed increasing quadratically and power usage increasing cubically. The structure would look something like this:
![BussardRamjetConcept02](https://user-images.githubusercontent.com/40431605/56478453-82396580-647d-11e9-92be-f493fd9b170f.png)
![BussardRamjetConcept03](https://user-images.githubusercontent.com/40431605/56478454-82396580-647d-11e9-98e8-8174294a2292.png)
The angel block is the controller, with the four power plugs and it forming the front. The coils are solid all the way through, and the structure is symmetrical. Power usage starts at 1024 RF/t, and increases to a max of 8192 RF/t with iridium (2^3 multiplier).

**Comment by Poxorosa** [comment]
Its like a spaceship?

**Comment by Silfryi** [comment]
It would be a space station drive, similar to warp. Because the drive is not FTL (subluminal), it would be limited to planets within the system you are in, you could not travel to other systems. Look up Bussard Ramjet, but they require space to function, as they collect interplanetary/interstellar hydrogen/helium via magnetic fields and fuse them using those fields. They need lots of power, however.

**Comment by RenanVieira88** [comment]
Silfryi, I've do not need to open another issue duo our conversation about that, u explain so much better my idea too
the engine be local system travel only and warp to another system travel

ps: just to increment yout post, ive thing the warp drive travels can have this background (without the ship :p)

![maxresdefault](https://user-images.githubusercontent.com/24437327/56553186-fe0ddd80-6563-11e9-8eb2-eef2f6eed740.jpg)

**Comment by voidsong-dragonfly** [comment]
Closing this as while BRJs are cool, they run into the same problem any STL drive does n AR.
