### ISSUE TITLE
[Suggestion][FR][From Discord] TiAl and TiIr Tools

### ISSUE THREAD

**Issue by Silfryi** [zmaster587/AdvancedRocketry#1573]
Titanium Aluminide and Titanium Iridium Alloy tools, each with their own uses and bonuses.
**Titanium Aluminide**

- Durability is 2048
- Speed is 16 (To diamonds 8)
- The alloy is light and hard, making for durable tools that are fast because you can swing them fast
- Damage is the same as diamond, but faster attack speed.

**Titanium Iridium Alloy**

- Durability is 8192
- Speed is 12 (To diamonds 8)
- The alloy is tough and hard, making for durable tools that are fast because it is hard to wear the cutting edge
- Damage is 2x diamond, as the hard material keeps an edge _very_ well, same attack speed, as iridium can be heavy

Textures for TiAl:
![TiAlHoe](https://user-images.githubusercontent.com/40431605/56478579-6edaca00-647e-11e9-875d-7695052cb4ca.png)
![TiAlPickaxe](https://user-images.githubusercontent.com/40431605/56478580-6f736080-647e-11e9-8017-8db621bbf6fc.png)
![TiAlShovel](https://user-images.githubusercontent.com/40431605/56478581-6f736080-647e-11e9-8aab-6207c2dfc028.png)
![TiAlSword](https://user-images.githubusercontent.com/40431605/56478582-6f736080-647e-11e9-85a3-3660445b67b7.png)
![TiAlAxe](https://user-images.githubusercontent.com/40431605/56478583-6f736080-647e-11e9-8bba-eb8061873ee1.png)

**Comment by MrEyeballs29** [comment]
This is for Advanced Rocketry not Advanced Armory

**Comment by Silfryi** [comment]
Zmaster already approved it on Discord. While it is true that this is not an armory mod, that does not mean we cannot add tools for some of the specific to Advanced Rocketry metals. As far as I know, no other mod adds TiAl and TiIr, so this mod would be the only mod to add tools for them. It also gives a nice reward for completing the progression through the mod.

**Comment by Silfryi** [comment]
Closed because, honestly, AR doesn't need tools and high-tier Vanilla ones are usually superseded by power tools.
