### ISSUE TITLE
Overworld skybox rendering issue

### ISSUE THREAD

**Issue by RozyZzx** [zmaster587/AdvancedRocketry#1575]
## Version of Advanced Rocketry
1.5.0-139-universal
## Have you verified this is an issue in the latest unstable build
YES
## Version of LibVulpes
0.4.0-56-universal
## Version of Minecraft
1.12.2 forge 14.23.5.2831 

## Description of the problem
sky color suddenly change and the sun and moon disapeared at certain 'y' level in the overworld.
![2019-04-27_12 19 05](https://user-images.githubusercontent.com/38360062/56845175-1c1e6980-68e7-11e9-9750-ca2f4f5848f8.png)
![2019-04-27_12 19 02](https://user-images.githubusercontent.com/38360062/56845176-1cb70000-68e7-11e9-9327-8cbb5f462f31.png)

**Comment by Silfryi** [comment]
That’s a MC thing, not an Advanced Rocketry thing.

**Comment by MrEyeballs29** [comment]
No it's not. I tested without it and MC does work internally when I am at y
level 60 and lower.

**Comment by Silfryi** [comment]
The sky darkening in some way when you go below sea level is an MC thing. What possibly happens here is AdvR changes skyboxes below sea level so they don’t include planets.

**Comment by zmaster587** [comment]
It is an MC thing to change how the skybox is rendered when under sealevel, however AR does override this functionality to try to make it behave with planets.  It shouldn't be doing this though.

**Comment by MrEyeballs29** [comment]
When I am at y level 60 and lower, the vanilla MC Sun didn't have a blue
color when looking above if this mod is not installed.
