### ISSUE TITLE
 Failed to register dimension for id -2, One is already registered (1.12.2)

### ISSUE THREAD

**Issue by PaperMachine1** [zmaster587/AdvancedRocketry#1578]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-139-universal
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-56-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/gnx5Uz2t

## Description of the problem
 java.lang.IllegalArgumentException: Failed to register dimension for id -2, One is already registered

**Comment by PaperMachine1** [comment]
i am new to stuff, and don't know how to change configs. I still want those two mods, can you give me a walkthrough?

> There’s a config to change the station dimension, you can use that. If you don’t want to, you could try without LordCraft and/or aether. [Likely]One of them is registering a dimension to DIMID-2 before AdvR does.

**Comment by Silfryi** [comment]
@MrEyeballs29, not necessarily. It registers them in alphabetical order _after resolving dependencies_. So LibVulpes would load before Advanced Rocketry.
————————————————
@PaperMachine1, In your config there should be a line something like this:
spaceStationDimensionID=-2
Change this number to something like -8 and it should work

**Comment by PaperMachine1** [comment]
> @MrEyeballs29, not necessarily. It registers them in alphabetical order _after resolving dependencies_. So LibVulpes would load before Advanced Rocketry.
> ————————————————
> @PaperMachine1, In your config there should be a line something like this:
> spaceStationDimensionID=-2
> Change this number to something like -8 and it should work

i see, thank you

**Comment by Silfryi** [comment]
Did it work? If so, could you close the issue? Otherwise, is there anything we can do to help?

**Comment by PaperMachine1** [comment]
it worked, thanks for the help
