### ISSUE TITLE
Crash when opening Guidance Computer GUI in a rocket

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [zmaster587/AdvancedRocketry#1579]
## Version of Advanced Rocketry
1.5.0-139
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
0.4.0-56
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/CKNp7C6x

## Description of the problem
I built a rocket, scanned it, built it in the rocket assembling machine, and everything was successful. Then every time I shift-right click the rocket to open the GUI, and as soon as I click on the Guidance computer button in the GUI, the GUI for the guidance computer shows up for half a second and then the game crashes

**Comment by zmaster587** [comment]
Does this occur without DynamicSurroundingsCore?

**Comment by SmokeyTheBandicoot** [comment]
No, it does not, just tried it and everything works fine

**Comment by MrEyeballs29** [comment]
Since Dynamic Soundings causes

**Comment by ErdbeerbaerLP** [comment]
https://github.com/OreCruncher/DynamicSurroundings/issues/484

**Comment by nephatrine** [comment]
I have this same issue, but it doesn't happen every single time. There are times I can access the guidance computer on an assembled rocket w/o issue and other times it crashes with the same error here.
