### ISSUE TITLE
Observatory not placing data in data units after first 1000 units

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [zmaster587/AdvancedRocketry#158]
After completely filling a data unit from the observatory, every attempt to place data on any data unit will remove the data from the observatory buffer but will not add data to the data unit.

**Comment by TheGuyRunningSouth** [comment]
Just tried with a non-empty chip (extra data from satellite that would not fit in ADP buffer) and it transferred data. Will post new developments as they occur.

**Comment by zmaster587** [comment]
so if the chip lists as storing "Some Random data" it removed data from the observetory without adding it to the chip?

**Comment by TheGuyRunningSouth** [comment]
Yes.

**Comment by zmaster587** [comment]
A video may be helpful, I'm not able to replicate this

**Comment by TheGuyRunningSouth** [comment]
Video is up unlisted.
Also, I am providing a modlister link for this collection of mods in case that helps any.

Video: https://youtu.be/xRGsNTGENek
Modlister: https://modlister.com/user/GuyRunningSouth

**Comment by zmaster587** [comment]
Will try to get to this tomorrow

**Comment by zmaster587** [comment]
Thank you very much for your help!

**Comment by TheGuyRunningSouth** [comment]
You're quite welcome. Thank you for such an awesome mod.
