### ISSUE TITLE
[BUG] Crash when right-clicking Ore Scanner

### ISSUE THREAD

**Issue by twothe** [zmaster587/AdvancedRocketry#1581]
## Version of Advanced Rocketry
1.5.0-139

## Have you verified this is an issue in the latest unstable build
N

## Version of LibVulpes
0.4.0-57

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
N/A

## Crash report or log (if applicable)
https://paste.dimdev.org/uvazalegoc.mccrash

## Description of the problem
When right clicking an unprogrammed ore scanner, the client instantly crashes.

**Comment by zmaster587** [comment]
Does this happen in single player or only on servers?

**Comment by zmaster587** [comment]
I can confirm this error occurs, however at least on my end the error doesn't cause a client crash, just a console printout.

**Comment by zmaster587** [comment]
Should be fixed for build 140
