### ISSUE TITLE
[BUG] Glithed Landing

### ISSUE THREAD

**Issue by EpicDanger2015** [zmaster587/AdvancedRocketry#1582]
Version of Advanced Rocketry
1.12.2
AdvancedRocketry 1.5.0-139
LibVulpes 0.4.0-57

Rocket when landing has the countdown timer, and has the option to land whenever, when I press space because I don't want to wait 25 seconds, it shows me going down in altitude, then back up, then down and so on, for about the remaining time left on the counter, then it proceeds to go downward after and lands successfully.

**Comment by Poxorosa** [comment]
Yes, Im too find this bug.

**Comment by EpicDanger2015** [comment]
If wanted, I can make a video of the bug in action and link it here.

**Comment by magn0053** [comment]
I have the same bug too. Happened after trying to land on Luna, which is also bugged and therefore not possible.
