### ISSUE TITLE
[Question] Can AR rockets travel between close planets?

### ISSUE THREAD

**Issue by GamerwithnoGame** [zmaster587/AdvancedRocketry#1590]
## Version of Advanced Rocketry
n/a
## Have you verified this is an issue in the latest unstable build
n/a
## Version of LibVulpes
n/a
## Version of Minecraft
1.12.2

Hi, I had a question and I wasn't sure if this was the best place to ask - if you have a Discord, do let me know; can AR rockets travel between planets that are close, if they use the advanced rocket engine or anything like that? I'm putting together a modpack and we were hoping to use warp travel to go to further planets, and gated warp travel (i.e. requiring an item as an "upgrade") for interstellar travel, but were really hoping to be able to travel from the home planet to the next closest one by using a rocket?

**Comment by Silfryi** [comment]
Rockets with warp cores on them can do within the same system. Just the core, nit the controller.
