### ISSUE TITLE
[BUG] Space station disappearing.

### ISSUE THREAD

**Issue by Poxorosa** [zmaster587/AdvancedRocketry#1592]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
> AdvancedRocketry 1.12.2-1.5.0-139-UNSTABLE build -139 for 1.12.2

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
Yes

>Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
>LibVulpes 1.12.2-0.4.0-57-UNSTABLE build -57 for 1.12.2

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.

## Version of Minecraft
>1.12.2
>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
N/A

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>insert here

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.

## Description of the problem
I landed on the planet from the galaxy space addon for galacticraft, but I cant go to the space station, because it "Not in the same planet". I dont know what happened, but station just gone.
UPD: When I back to the Earth, I can rech the space station.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.

**Comment by SynexWolf** [comment]
Have you tried heading back to the overworld and then try going to the space station? Space stations might be dimension bound.

**Comment by Poxorosa** [comment]
> Have you tried heading back to the overworld and then try going to the space station? Space stations might be dimension bound.

I cant back to the Erath, because im on very far planet.

**Comment by SynexWolf** [comment]
How did you land on the a galacticraft planet? Did you use AR or did you use Galacticraft?

**Comment by Poxorosa** [comment]
> How did you land on the a galacticraft planet? Did you use AR or did you use Galacticraft?

im using AR planetDefs to land on the planets from other mods with AR rockets.

**Comment by Silfryi** [comment]
This is a symptom of the station-returning-to-earth-after-restart bug that we could never reproduce. Can you give information on that instead? A full log and the circumstances preferably.
