### ISSUE TITLE
[BUG] FTB Interactions, unable to reach planet from space station. Rocket Disappears at maximum altitude.

### ISSUE THREAD

**Issue by ggkhs** [zmaster587/AdvancedRocketry#1594]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-139-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-57-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N/A

## Description of the problem
https://www.youtube.com/watch?v=eSk3L2bde98

On FTB Interactions when we try to access Aurelia dimension or advRocketry/DIM147 by taking a rocket from space station it reaches the maximum y:1000 altitude and it disappears without teleporting us to the planet, we also cannot access it through teleport commands.

We tried [force-loading](https://i.imgur.com/umcMZUj.png) the dimension at startup and the same issue occurs, rest of the packs dimensions have no issues like this and are accessible as intended.

This is on a Sponge server but I am not sure if its related, it does not happen on single player either, I opened an issue on the modpack already, just asking here if you guys have any suggestions on how to go about fixing it.

**Comment by dmodoomsirius** [comment]
Does this occur without sponge?
