### ISSUE TITLE
[Request] black holes, dyson spheres, black hole bombs, theoretical space objects

### ISSUE THREAD

**Issue by AwesomeNoob999** [zmaster587/AdvancedRocketry#1596]
Me and a ton of other people would like to see the ability to make dyson spheres and black hole bombs and I would like to see random rare white holes that can spew out random resources. Also the ability to make antimatter, wormholes, and black holes/kugleblitz. Also neutron stars/quark stars and huge planet mining missions

**Comment by Silfryi** [comment]
Black holes are already a thing in the latest versions. What was your purpose for black hole bombs? They don't seem to be very useful at the moment, as I cannot think of a good way for them to be implemented. What place would anitmatter have? Most of the time it has only industrial applications and bombs, and we already have warp, so there is no need for drives. Neutron stars/quark stars also have no use as far as I can tell, what were you planning for them?

**Comment by NutMaster6942** [comment]
Dyson Spheres might be an insanely useful late game way of power generation.
