### ISSUE TITLE
Crash while landing on station

### ISSUE THREAD

**Issue by JenisisJo32** [zmaster587/AdvancedRocketry#1599]
## Version of Advanced Rocketry
[1.5.0-139]
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
[0.4.0-56]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
[https://paste.dimdev.org/rutofoyiha.mccrash]

## Description of the problem
[Crash while rocket descends towards new station. The rocket entity turned invisible, but was able to begin landing on the station. Was able to re-log once, then the crash became consistent on world load.]

**Comment by Silfryi** [comment]
Could you try and reproduce this with the minimum amount of mods so the cause of the conflicts is?
