### ISSUE TITLE
[BUG] Holographic Planetary Selector Rendering Bug

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#1603]
## Version of Advanced Rocketry
1.12.2-1.5.0-139

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.12.2-0.4.0-57

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y (I have JEI installed)

## Crash report or log (if applicable)
https://pastebin.com/UyKug3MH

## Description of the problem
I used the holographic planet selector and I tried to zoom in on a custom planet (I'm pretty sure it was a binary star system if that helps) and it caused a rendering crash.  Here are the configs I used: https://pastebin.com/ZX2GprP1

**Comment by MrEyeballs29** [comment]
Check the file to .make sure it's validated.

**Comment by mxnmnm** [comment]
I'm curious what you mean by checking that the file is validated.  How would I do that exactly?

**Comment by MrEyeballs29** [comment]
https://pastebin.com/ZX2GprP1
This link. Make sure there is no mismatched brackets.

**Comment by mxnmnm** [comment]
Yea it's fine, I minimized all of the things using notepad++ and nothing stood out as wrong.

**Comment by ErdbeerbaerLP** [comment]
Same thing happened here, https://paste.dimdev.org/vuhuduyude.mccrash

**Comment by mxnmnm** [comment]
probs still an issue maybe I'll retest it for newer versions but since change log doesn't mention anything idk
