### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tonyvans** [zmaster587/AdvancedRocketry#1605]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-139-universal.jar

## Have you verified this is an issue in the latest unstable build
- [x] Unfortunately No, AdvancedRocketry 1.12.2-1.5.0-139-UNSTABLE-deobf build -139 for 1.12.2 will not load. causes minecraft to crash 

## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-56-universal.jar

## Version of Minecraft
1.12.2

## Does this occur without other mods installed

- [x] N/A, it is an issue within advanced rocketry, the connection of two blocks 

## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>no crash with stable version of mod, space station assembler just does not get power with normal input plug

## Description of the problem
>Space station assembler unable to get power from input plug on any side, however it does get power from creative input plug, was able to reproduced the issue in both multiplayer survival and single player creative.

I will attach screen shots, which will hopefully help. Thank you, fully willing to admit I am doing something wrong, just can't figure out what.

to show setup trying to input power from multiple sides
![spacestation assembler ext](https://user-images.githubusercontent.com/6739653/59728084-6a682e80-91ed-11e9-8b87-457a80d29ff3.JPG)

to show assembler interface is not getting power
![spacestation builder](https://user-images.githubusercontent.com/6739653/59728115-88359380-91ed-11e9-9b81-40232ff8d955.JPG)

To show input plug is getting power
![input plug](https://user-images.githubusercontent.com/6739653/59728155-aa2f1600-91ed-11e9-8fa3-93f633d99593.JPG)

to show creative plug has power (obviously it would, just a demonstration)
 ![creative input](https://user-images.githubusercontent.com/6739653/59728171-c5018a80-91ed-11e9-87e0-873617524a16.JPG)

to show assembler gets power but only with creative input plug
![powered](https://user-images.githubusercontent.com/6739653/59728201-ef534800-91ed-11e9-8e22-3eee93628394.JPG)

to show device does work, but only with creative power.
![scanning](https://user-images.githubusercontent.com/6739653/59728213-01cd8180-91ee-11e9-9220-554cb3b311e4.jpg)

**Comment by zmaster587** [comment]
This is expected behaviour, the rocket assembling machine takes power directly and doesn't need a plug.  There's no need for a battery block on it.  The reason the creative battery works is because it's outputting power the the rocket assembling machine.

I hope this helps!

**Comment by tonyvans** [comment]
ok thank you, my main power comes though flux plugs, which didn't seem to provide it power, I will try other power options. and the videos I have been watching as a tutorial have the creative so I assumed the input was required. amazing mod. just building my rocket now for the first time.
