### ISSUE TITLE
Casting exception when trying to take off [BUG]

### ISSUE THREAD

**Issue by benserwa** [zmaster587/AdvancedRocketry#1607]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.5.0-139

## Have you verified this is an issue in the latest unstable build
- Y

## Version of LibVulpes
0.4.0-57

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- Y

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log (if applicable)
https://paste.dimdev.org/uwayobekom.mccrash

## Description of the problem
Crash prevents takeoff in a rocket.

**Comment by zmaster587** [comment]
Can you replicate this without any other mods installed?
