### ISSUE TITLE
[Q]how can i load Galactic craft planets?

### ISSUE THREAD

**Issue by tmvkrpxl0** [zmaster587/AdvancedRocketry#1608]
Ok, this could be sounds ridiculous, i heard a rumor that AR rockets can go to galactic craft planets if i do some configuration, so i tried
but i can't find a configuration about it.
so, is this possible(for now)?
if it is, how?

**Comment by Poxorosa** [comment]
U can add ANY dimensions from the mod as a planets to AR. And u can create your own planets. U need to create planetDefs.xml file in the AR config folder.
More information u can found here: http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/AdvancedPlanetConfiguration.php

**Comment by Silfryi** [comment]
You're going to want the Dimmapping already created dimensions section.
