### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RedBlockCreator** [zmaster587/AdvancedRocketry#1609]
## Version of Advanced Rocketry
>AdvancedRocketry 1.12.2-1.5.0-139-UNSTABLE build -139 for 1.12.2

## Have you verified this is an issue in the latest unstable build
- [x] Yes

## Version of LibVulpes
>	LibVulpes-1.12.2-0.4.0-57-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

## Crash report or log (if applicable)
https://paste.dimdev.org/movarebebu.mccrash

## Description of the problem
Got this error message when opening 1 of 2 input hatches on the electric arc furnace

**Comment by zmaster587** [comment]
can you try it again with the latest builds?  (libvulpes 59 and AR 153)
