### ISSUE TITLE
[BUG] Lathe recipes/JEI display issue

### ISSUE THREAD

**Issue by Gamertech** [zmaster587/AdvancedRocketry#1610]
## Version of Advanced Rocketry
1.12.2-1.6.0-149

## Have you verified this is an issue in the latest unstable build
Y

## Version of LibVulpes
1.12.2-0.4.1-59

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Y - At a minimum, Advanced Rocketry, LibVulpes and JEI (tested with JEI 1.12.2-4.15.0.283)

## Crash report or log (if applicable)
N/A

## Description of the problem
Load a pack with AR and JEI. Check JEI recipes to create LV rods and the lathe tab wont be displayed, only the manual craft recipes.

Right-click/U on the lathe itself, and the recipes display the starting item, but the side with the crafted item is empty.

Inserting the crafting items into the lathe still correctly crafts the intended items, and as far as I can see, recipes for all other machines still display correctly.

**Comment by Nachtflame** [comment]
Having a similar issue;
Since updating from 139 to 149 recipes for AR Machine processes have not properly shown ITEM outputs in JEI; Recipes that output a Fluid display just fine (screenshots displaying default & added recipes - https://imgur.com/a/J3VpDaS).

Confirmed that this is also the issue with 150 as well, and that rolling back to 139 shows all recipes properly.

**Comment by ErdbeerbaerLP** [comment]
Does not work with any machines for me (rolling machine, ...).

**Comment by pyure** [comment]
We are experiencing the same issue.  Tested Precision Assembler, Lathe, Rolling Machine.

Curiously, the Chemical Reactor is mostly broken as well, but does display the output for the Rocket Fuel recipe.

- **AdvancedRocketry-1.12.2-1.6.0-151-universal.jar**
- **CraftTweaker2-1.12-4.1.19.jar**
- **Forge .2838**

**Comment by itsmeow** [comment]
Same issue, so far noticed with precision assembler.
MC 1.12.2
AR 1.6.0-150
LV 0.4.1-59
JEI 4.15.0.268
Forge 14.23.5.2823

**Comment by zmaster587** [comment]
I might need to compile against a newer version of JEI, hang tight.

**Comment by zmaster587** [comment]
Bug was introduced in build 140 when adding capabilities for outputs only having a chance to appear.  However breaking JEI was probably not the same kind of "surprise mechanics" EA was talking about.

**Comment by Gamertech** [comment]
Can confirm fixed in today's update.

**Comment by pyure** [comment]
Thanks as always zmaster
