### ISSUE TITLE
[BUG]  Crash world

### ISSUE THREAD

**Issue by zayats1** [zmaster587/AdvancedRocketry#1611]
https://paste.dimdev.org/ipudizesur.mccrash
Latest AR and LV

**Comment by BasieBrinkie** [comment]
AR version 1.6.0-149
LibVulpes Version 0.4.1-59
MC Version 1.12.2
Singleplayer world

I'm experiencing the exact same crash. This is my crash-report https://gist.github.com/BasieBrinkie/daf321a8427630dc5f0db9b933224552
I was just in the experimental asteroid dimension when it randomly crashed.

**Comment by Yoosk** [comment]
And one more from me: https://gist.github.com/d9d594d31723ff199b9ff4b1b9c93030

**Comment by Frikkle** [comment]
+1

**Comment by zmaster587** [comment]
looks like an issue related to weather handling
