### ISSUE TITLE
[BUG] Extreme Server Lag

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#1614]
## Version of Advanced Rocketry
1.6-149

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.12.2-0.4.1-59

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N

## Crash report or log (if applicable)
https://imgur.com/a/Fxi0Z9y

## Description of the problem
I updated advanced rocketry in my custom modpack and everything became extremely laggy (server lag not fps lag).  If you need a mod list or something let me know and I can send it.

**Comment by ben-mkiv** [comment]
you can help the project coders by installing [laggoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles) and running server profiling and posting the screenshot of the output (analyze result)

the screen looks like this:
![](https://raw.githubusercontent.com/TerminatorNL/LagGoggles/master/docs/timingsmenu.png)

**Comment by mxnmnm** [comment]
that's what the screenshot is

**Comment by mxnmnm** [comment]
also something to note is that going from peaceful to easy made the lag much worse

**Comment by Frikkle** [comment]
This also happened on our server after updating from `1.12.2-1.5.0-139` to `1.12.2-1.6.0-150`.

See https://imgur.com/a/tZ546Wk for two screenshots. Similar behavior as can be seen in @mxnmnm's screenshot. Our server tps went from 20 stable (with small dips when players were exploring) to about 6-8tps with huge lag spikes after updating.

**Comment by zmaster587** [comment]
conversation in #1624 i would appriciate a visualvm sample, please post there.
