### ISSUE TITLE
How to get to Mars with the Advanced Rocketry mod

### ISSUE THREAD

**Issue by Cmdb26** [zmaster587/AdvancedRocketry#1619]
## Version of Advanced Rocketry
1.7.10-1.0.19b.jar
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.7.10
## Version of Minecraft
1.7.10
## Crash report or log (if applicable)
This never crashed!

## Description of the problem
I want to go to galacticraft's mars. However, I can't seem to find out how. Any help would be helpful!:)

**Comment by Poxorosa** [comment]
U need to create planetDefs.xml file in the advRocketry config file.
http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/AdvancedPlanetConfiguration.php
And desirable to use 1.12.2 version.

**Comment by Cmdb26** [comment]
Do I need to add fog color or can I erase the fog part?

**Comment by Poxorosa** [comment]
U can erase it

**Comment by Cmdb26** [comment]
Thanks!
