### ISSUE TITLE
Removed galacticraft and get errors

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#162]
i just removed galacticraft from my instance and wanna only run AR but get the error below.
Have tried changing the dim id in AR but that dont change.
Edit: AdvancedRocketry-0.6.4.jar
Edit2: http://paste.ee/p/kshUh

> java.lang.IllegalArgumentException: Failed to unregister dimension for id -28; No provider registered
> 	at net.minecraftforge.common.DimensionManager.unregisterDimension(DimensionManager.java:134)
> 	at zmaster587.advancedRocketry.dimension.DimensionManager.deleteDimension(DimensionManager.java:324)
> 	at zmaster587.advancedRocketry.AdvancedRocketry.serverStarted(AdvancedRocketry.java:1052)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
> 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
> 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
> 	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
> 	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by zmaster587** [comment]
Will have a patch out tonight

**Comment by bludde** [comment]
did anyone tell you you are awesome?:)

**Comment by zmaster587** [comment]
do you have the moon id in the config set to -28?

**Comment by bludde** [comment]
Sorry but i still get the same error
http://paste.ee/p/3Mkh0
if i add galacticraft again it works fine but i dont like that oxygen system...

**Comment by zmaster587** [comment]
Will try again tonight, I had only 15 minutes last night to fix and try to
test.

**Comment by zmaster587** [comment]
0.6.6 should hopefully fix (I have not had time to actually test unfortunatly due to being busy irl)
