### ISSUE TITLE
[BUG]проблема с иридием не спавнится в мире

### ISSUE THREAD

**Issue by doni09** [zmaster587/AdvancedRocketry#1622]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>[insert here

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [x] N
- [x] N/A

>Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
>insert here

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.

## Version of Minecraft
>insert here

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
- [x] Y
- [x] N
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>insert here

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.

## Description of the problem
>How can you reliably reproduce the problem

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.

**Comment by MrEyeballs29** [comment]
What is the title again.

**Comment by Poxorosa** [comment]
Иридий и не должен спавниться в мире. Его можно добыть на астеройдах. И пиши на английском.

**Comment by MrEyeballs29** [comment]
What in the world. Now I don't know what are you saying

**Comment by ErdbeerbaerLP** [comment]
![image](https://user-images.githubusercontent.com/27149563/61115862-b7a98a00-a493-11e9-8093-e38ab9c5f4bc.png)

**Comment by mchaker** [comment]
I think Poxorosa is also saying that in-game text is showing up in English when it is not expected to be in English.

**Comment by zmaster587** [comment]
@mchaker If that's the case, that's more of a lack of everything being translated.  I don't speak russian and don't trust google translate enough to do it, so unfortunately without help I cannot really fix that.

@Poxorosa Iridium shouldn't be spawning in the world unless there's other mods installed that add it (or unless you manually add it in the planetDefs.xml).  It's obtainable only via the asteroid mining missions by default
