### ISSUE TITLE
[BUG] Extreme lag in flat worlds

### ISSUE THREAD

**Issue by Kehaan** [zmaster587/AdvancedRocketry#1623]
Hello

I am not sure what kind of logs etc you want, or if you already know of the issue.

I am using:
AdvancedRocketry-1.12.2-1.6.0-151-universal.jar
LibVulpes-1.12.2-0.4.1-59-universal

In flat worlds, it seems like the tick rates, is like 100-150ms which gives a very very low tps. In normal worlds, it seems to also "lag" but mostly noticeable in flat worlds.
I tried to remove every mod one by one to find the one causing the issue. And when i removed Advanced Rocketry the issue was gone. I readded all other mods, which did not make the issue again. But as soon as i re-enabled Rocketry, the world was not happy.

I can make a sampling file if that helps you.

Thanks

**Comment by zmaster587** [comment]
a sampling file would be good, please respond in #1624
