### ISSUE TITLE
Extreme Server Lag after version #139

### ISSUE THREAD

**Issue by xlea99** [zmaster587/AdvancedRocketry#1624]
## Version of Advanced Rocketry
This seems to only occur starting with versions 149, 150, and 151 (can't test versions 148-140)
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
Version 59, however problem goes away when I'm just running LibVulpes and not AdvRocketry
## Version of Minecraft
1.12.2 (forge-14.23.5.2838)
## Crash report or log (if applicable)
I installed lag goggles and did a dump to my log, this was the result.

https://pastebin.com/kgxsCzVJ

## Description of the problem
When using any available version after 139, massive amounts of RAM are used by the server causing some extreme server lag. This is especially present on worlds with a lot of blocks, ESPECIALLY worlds with a lot of water blocks. I first noticed this problem when trying to make a water world- if you try to make a world with a lot of water (from y=128+) this problem gets crazy and I average ~7-9 TPS on the server. The debug screen showed me using about 3 gigs of ram every second in a water world on version 149, and about 1/10 of that on version 139.

I also tried tweaking every one of the various settings in the config file to see if it helped, but none of them made a difference. To recreate this bug yourself, just make a new superflat world and choose 'water world' under presets, then edit the amount of water blocks so it's between 100 and 200.

Its weird cause version 139 works totally smooth, TPS is 20 in the exact same world I tested for version 149+. Hope I've provided enough information to help! Love this mod btw, one of my all time favs

**Comment by zmaster587** [comment]
Can you get me a visualVM dump?  Lag goggles isn't really showing anything useful.  See the last half of https://github.com/zmaster587/AdvancedRocketry/issues/1621#issuecomment-510112937 for how to do that.  VisualVM is far superior because it tells me exactly what is lagging in the code, not just a vague 'something in this 700 lines of code that could be called from anywhere is taking a while'.

What confuses me is that not really much changed between 139 and the most recent build.  The only thing I can think of would be the change for rain, but that would only make a difference when its raining.  Other than that, a hovercraft was added, volcanoes generate in certain biomes.  Unless you went and added those biomes they should never spawn.  Fixed a bug with the keybinds.  but that's about it.

**Comment by xlea99** [comment]
Sure thing. I ran VisualVM twice, once on version 149 and once on version 139, both on the same world. 


Heres 139 without the lag:
https://www.dropbox.com/s/ufhx21yn2grw34o/advanced_rocketry139.nps?dl=0

And heres 149 with the lag:
https://www.dropbox.com/s/32qbjnccgfvyu7n/advanced_rocketry149.nps?dl=0


Hope this helps

**Comment by Poxorosa** [comment]
Yeah, same lags on 1.6.0 version

**Comment by zmaster587** [comment]
@xlea99 alright, it looks like entity spawning from AR is taking way longer in 149, can you upload your planetDefs.xml file?  Can you also check to see if there's any entries for spawning mobs, if there are can you remove them and see if the lag continues?

**Comment by Poxorosa** [comment]
@zmaster587 I removed all spawnable tags from my planet defs, but nothing. This lag continues.

**Comment by xlea99** [comment]
I actually didn't make a planetDefs.xml for the pack I made the nps files with, i just put libvulpes and advanced rocketry into vanilla minecraft and made an ocean superflat world. There were 120 or so entities in the world, I think all of them squids, but the number wasn't really fluctuating. 

I don't know if this helps, but I tried using In Control! to disable all mobs from spawning in the game, but it didn't seem to help with the lag, even with entities at 0.

lmk if you need anything else to help

**Comment by zmaster587** [comment]
@xlea99 would you be able to send me a copy of the world?  I'm having difficulty replicating the issue.

**Comment by zmaster587** [comment]
Scratch that, I think I found the issue https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/event/PlanetEventHandler.java#L133

**Comment by zmaster587** [comment]
Yep, that was definitely it.  Sometimes it's hard to tell the difference between a super bogged down PC and a real lag issue.

**Comment by zmaster587** [comment]
Since it's a gamebreaking issue I'll have a build out to fix it in a few minutes now that I actually have it working.
