### ISSUE TITLE
[Small Request] Prevent rocket from falling to void.

### ISSUE THREAD

**Issue by Poxorosa** [zmaster587/AdvancedRocketry#1627]
This gonna be very small, but usefuel feature: if there is no solid surface under the rocket, then the rocket will stop at a certain height. This can help when u landing on the aether dimension or something like that.
UPD: can be made so that the rocket can be stopped by pressing a certain key

**Comment by NutMaster6942** [comment]
Why did you close this?

**Comment by MrEyeballs29** [comment]
The bad grammar user is currently offline.

**Comment by TripTripy** [comment]
Landing floats were added as well. So rockets don't fall into the void anymore
