### ISSUE TITLE
[BUG] Broken Biometweaker Compat

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#1628]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.5.0-139-universal.jar	

## Have you verified this is an issue in the latest unstable build
- [x] Y (I don't use the latest version because it's too laggy so here's the part in the code where it's bad according to the people on the biome tweaker wiki: https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/world/biome/BiomeGenMarsh.java#L18 )

## Version of LibVulpes
LibVulpes-1.12.2-0.4.0-57-universal.jar	

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
biometweaker + advanced rocketry

## Description of the problem
I was trying to make a biome using biome tweaker and I tried copying an advanced rocketry biome and didn't work.  I asked them at their discord and they said it was because "They need to not set registry names in their biome constructors"

**Comment by mxnmnm** [comment]
probs still an issue maybe I'll retest it for newer versions but since change log doesn't mention anything idk

**Comment by mxnmnm** [comment]
still an issue for sure

**Comment by mxnmnm** [comment]
I tried to copy a biome using biometweaker and it just ignored it

**Comment by mxnmnm** [comment]
biometweaker gave no errors so I think this is the only other issue I can think of

**Comment by MrEyeballs29** [comment]
The issue is you are using a mod biome copy instead of the vanilla biome
copy.

**Comment by mxnmnm** [comment]
Well it works for biomes o plenty and pretty much any other biome I've attempted to register

**Comment by MrEyeballs29** [comment]
Have you looked what the biome registry names are for AR?

**Comment by mxnmnm** [comment]
advancedrocketry:moon (I'm trying to copy this one)
advancedrocketry:alien forest
advancedrocketry:hotdryrock
advancedrocketry:space
advancedrocketry:stormland
advancedrocketry:crystalchasms
advancedrocketry:deepswamp
advancedrocketry:marsh
advancedrocketry:oceanspires
advancedrocketry:moondark
advancedrocketry:volcanicbarren

**Comment by MrEyeballs29** [comment]
Have you gave yourself an item from using the registry domain
"advancedrocketry". If that is the case, then check for the scripts for
biome tweaker.

**Comment by mxnmnm** [comment]
I was able to modify other biomes I just can't copy them

**Comment by mxnmnm** [comment]
Tweaker.setScriptStage("BIOME_REGISTRY")
Tweaker.createBiome("tech_wasteland", "minecraft:void")
Tweaker.createBiome("cheese_land", "advancedRocketry:moon")

**Comment by mxnmnm** [comment]
the first one registers 
the second one does not

**Comment by MrEyeballs29** [comment]
You capitalized the word "Rocketry".

**Comment by mxnmnm** [comment]
Oh I was testing to make sure it wasn't acting stupid where it wanted me to capitalize Rocketry but it didn't work when it was lowercase either.

**Comment by MrEyeballs29** [comment]
Did you flip flop the ordering for the new biomes?

**Comment by mxnmnm** [comment]
Tweaker.setScriptStage("BIOME_REGISTRY")
Tweaker.createBiome("tech_wasteland", "minecraft:void")

this worked

Tweaker.setScriptStage("BIOME_REGISTRY")
Tweaker.createBiome("tech_wasteland", "advancedrocketry:moon")

this did not work

**Comment by MrEyeballs29** [comment]
Set to a different biome stage.

**Comment by mxnmnm** [comment]
I tested every single possible script stage: PRE_INIT, BIOME_REGISTRY, INIT, POST_INIT, FINISHED_LOAD, SERVER_STARTING, SERVER_STARTED

None of them worked

**Comment by mxnmnm** [comment]
and considering BIOME_REGISTRY worked with other biomes (different modded ones and vanilla) 
I'd say that this is on advanced rocketry's end

**Comment by mxnmnm** [comment]
especially considering when I asked the author of biometweaker he said so himself

**Comment by MrEyeballs29** [comment]
Then this mod might be registered after biome tweaker.

**Comment by mxnmnm** [comment]
"They need to not set registry names in their biome constructors" he mentioned this as the issue because it limits functionality

**Comment by mxnmnm** [comment]
biome tweaker's author

**Comment by mxnmnm** [comment]
so I'm not sure if it would be feasible to fix or not
