### ISSUE TITLE
Multiblock not making...

### ISSUE THREAD

**Issue by AnarchySage** [zmaster587/AdvancedRocketry#163]
Since there is a severe lack of documentation(which i rather some documentation and feature pause than new content, or a new video with how to start it/play it), anyways, i cant get it to activate into the multiblock

http://imgur.com/Z36pLMw

@zmaster587

**Comment by zmaster587** [comment]
You only built the bottom section, the holo projector should tell you how
to use it if you mouse over it

**Comment by AnarchySage** [comment]
Ah ok, thanks
