### ISSUE TITLE
[BUG] Mobs dont spawn.

### ISSUE THREAD

**Issue by Poxorosa** [zmaster587/AdvancedRocketry#1631]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.6.0-155-UNSTABLE build -155

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes 1.12.2-0.4.1-60-UNSTABLE build -60

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y

## Description of the problem
After update -154 mobs just dont spawn in the world. They dont spawn in the modded dimensions or vanilla dimensions too. Only friendly mobs spawn.

**Comment by Kazzamkablam** [comment]
Had this happen too

**Comment by zmaster587** [comment]
Already fixed in build 156 and later
