### ISSUE TITLE
[BUG] Space station ID configuration chip dont working.

### ISSUE THREAD

**Issue by Poxorosa** [zmaster587/AdvancedRocketry#1632]
##Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.6.0-155-UNSTABLE build -155

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
LibVulpes 1.12.2-0.4.1-60-UNSTABLE build -60

## Version of Minecraft
1.12..2

## Does this occur without other mods installed
- [x] Y

## Description of the problem
Space station ID chip configuration just dont work. I cant add new coords or rename it. When I press "rename" or "add new" button, nothing hapens.
1 Screenshot: with mods
2 Screenshot: without mods
![2019-07-15_09 17 14](https://user-images.githubusercontent.com/46987042/61211504-6b1ab480-a708-11e9-930a-70fba6785673.png)
![2019-07-15_09 33 41](https://user-images.githubusercontent.com/46987042/61211510-7077ff00-a708-11e9-9179-13eef18539b3.png)

**Comment by Aridean** [comment]
Having the same issue.

Also not sure if related, but the chip has coordinates as "???" When trying to launch back to earth from space station, and travelling back puts me in a seemingly random location.

I'd post a screenshot but I'm nowhere near my PC at the moment.

Latest version available from curse.
