### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bdesflounders** [zmaster587/AdvancedRocketry#1635]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.4.0-63

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- N

>Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
>all it says is 1.12.2

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.

## Version of Minecraft
>1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
- I can't get just libvulpes and advanced rocketry to launch by themselves

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>https://paste.dimdev.org/qowihacuhi.mccrash 

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.

## Description of the problem
>using the scan/build feature on the rocket assembler instantly crashes game

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.

**Comment by Poxorosa** [comment]
Do u have any modded or just unusual blocks on your rocket?

**Comment by Poxorosa** [comment]
U used universal battery on rocket builder and seems like this crashes game

**Comment by Poxorosa** [comment]
Oh, u using VERY old version of AR and libvulpes. Download new version https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry

**Comment by bdesflounders** [comment]
thanks, I saw that a while ago and didn't realize there were newer downloads on there.
