### ISSUE TITLE
dont start server

### ISSUE THREAD

**Issue by origamerpro** [zmaster587/AdvancedRocketry#164]
Dont start server on Thermos core server. remove mod in mods folder and all good.
Thermos - https://github.com/CyberdyneCC/Thermos

**Comment by zmaster587** [comment]
I cannot even begin to start fixing this without more information like a crash report or startup log.

**Comment by origamerpro** [comment]
no crash log. server dont starting. all time reboot.

**Comment by zmaster587** [comment]
it will still write a FML-latest.log file in <server dir>/logs

**Comment by origamerpro** [comment]
log - http://pastebin.com/GTurqC5Q

**Comment by zmaster587** [comment]
What version of advanced rocketry are you using?

**Comment by origamerpro** [comment]
0.6.5 and LibVulpes-1.7.10-0.0.7

**Comment by zmasterbah** [comment]
AR uses asm injection for some of its core functions such as atmosphere handling and gravity modification.  Thermos, being a fork of Cauldron/MCPC+ makes a lot of modifications to Minecraft base code, for me to make AR compatible will take some time.

**Comment by zmaster587** [comment]
AR uses asm injection for some of its core functions such as atmosphere handling and gravity modification. Thermos, being a fork of Cauldron/MCPC+modifies a lot of base classes, so a fix is going to take some time to make.

**Comment by wormzjl** [comment]
IMO you can make something like this 
https://github.com/ReikaKalseki/DragonAPI/blob/5bcfb39c5dac5fecb6bc8ddbee69deac3ba8095f/ASM/Patchers/Hooks/Event/World/BlockTickEvent.java#L30

**Comment by zmaster587** [comment]
That's not really a fix, that's just a check to see if it's running a modified forge.  I may come back and look at this once the 1.10.2 update is working.  And thermos is not the only viable option, there's a ton of bukkit equivilent mods (world gaurd, world edit, teleport, home, etc) availible, while i will admit they are not perfect, but it is enough to let you manage a public server.
