### ISSUE TITLE
[BUG] Docking Pads on Planets can't be navigated by linkers.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#1643]
Minecraft Version:1.12.2
Forge Version: 2838
Advanced Rocketry Version: 1.6.0-160
LibVulpes Version: 0.4.1-60

is this the latest curseforge build? Yes.

Explain issue in detail:

This worked a while due to #1019, but it seems to have regressed.
I built a rocket on a planet with a warp core.
I place a docking pad, linked coords with a linker.
I fly it to another planet, it lands at the same coords as the rocket took off from.
I place a docking pad under the rocket.
I put the linker in it.
I remove the planet id chip.
I launch.

Expected Result:
I land on the pad I linked to.

(I also think it would be handy if I could just stick the linker into the guidance computer so I can move the rocket around.)

Actual Result:
I land in the same coords as I took off from on the Overworld/Earth.

Going from one pad to another on the same planet also does not work.

Thanks,
IMarv

**Comment by Poxorosa** [comment]
Now u can change coords in the space station ID chip without docking pads.

**Comment by IMarvinTPA** [comment]
How do I do that?
How does it work if a space station isn't involved?
