### ISSUE TITLE
[BUG]Station sending me to its coords on Earth not the original launch pad

### ISSUE THREAD

**Issue by nebbne1st** [zmaster587/AdvancedRocketry#1647]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.2-1.6.0-160

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y

>Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
>1.12.2-0.4.1-60

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.

## Version of Minecraft
>1.12

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
- [x] Y around 90
>If Y, what is the MINIMUM set of mods required.

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>N/A

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.

## Description of the problem
>After going to my space station i land where i should do on the station, however when i try and go back it sends not to the launch pad where i originally launched from, but to the space stations coordinates but in the overworld and has happened every time i have returned

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.

**Comment by Targren** [comment]
@nebbne1st  

Hey, did you happen to be flying a two seater? I just ran into the same problem on Enigmatica 2 Expert 1.65d, both my partner and I crashed to desktop, and when we logged back in, he was floating in space and I was still on the rocket, landing at the same coordinates on earth that our station was at.

**Comment by nebbne1st** [comment]
@Targren

No, I was on a 1 seater rocket and there was no crash at any point which is annoying

**Comment by zmaster587** [comment]
Related to station chips not saving their previous position if no previous position was ever saved before.

**Comment by zmaster587** [comment]
Fixed for next update
