### ISSUE TITLE
Dim mapped gas giant moons get deleted on world load [BUG]

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [zmaster587/AdvancedRocketry#1650]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.2.5a-18 (1.12.2)

>Why is this important?

## Have you verified this is an issue in the latest unstable build
I don't use the unstable builds.

## Version of LibVulpes
0.2.6-1.12.2

## Version of Minecraft
1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
- [x] Y
- [x] N
- [x] N/A
>If Y, what is the MINIMUM set of mods required.
I NEED other mods installed for these moons to work properly since they use dimensions from Galacticraft. This issue is N/A without other mods.

Crash? No. It didn't crash. It just erased the moons when I loaded the world.

I don't know how to reproduce this. I have gas giants who have moons that are dim mapped to Galacticraft and Galaxy Space dimensions. Upon loading the world, they are deleted. I've cheked the config for typos, syntax errors and pretty much any other mistake and couldn't find any.
I'm convinced it has something to do with my config but I can't tell what the problem is. Everything else except for the moons of the gas giants works fine.

**Comment by Silfryi** [comment]
Which planetDefs are you editing?

**Comment by AGiLE-EaGLE1994** [comment]
The one that is on my world save. The one I posted is a backup that has the moons in it.
So what I do is open planetDefs.xml and the backup in notepad++ and then I copy everything in the backup and replace everything in planetDefs.xml with everything from the backup before I boot the world. And when I load the world, the moons get deleted.
