### ISSUE TITLE
[BUG] Terraformer not working

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [zmaster587/AdvancedRocketry#1651]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.6.0-160

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

>Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
>0.4.1-60

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.

## Version of Minecraft
>1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A (not tested)
>If Y, what is the MINIMUM set of mods required.

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
> N/A

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.

## Description of the problem
> The terraformer always says "Not running".
> It has both enough oxygen and nitrogen but it doesn´t start terraforming
> 
![image](https://user-images.githubusercontent.com/27149563/62300185-a3472480-b476-11e9-8221-cbb873c7c207.png)

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.

**Comment by ErdbeerbaerLP** [comment]
Forgot to add: It does consume the gases but nothing happens

**Comment by Silfryi** [comment]
It's slow. Are you sure nothing happens? Also: is it enabled in the config?

**Comment by ErdbeerbaerLP** [comment]
Yes, i double checked if it is enabled

**Comment by ErdbeerbaerLP** [comment]
My servers config: https://pastebin.com/Y1sVCTjw

**Comment by Silfryi** [comment]
Are you on an Advanced Rocketry planet?

**Comment by ErdbeerbaerLP** [comment]
Yes, i want it to increase the atmosphere (see image: 0.04 atm)

**Comment by ErdbeerbaerLP** [comment]
Found the bug... When it is disabled on the client it can not be used on the server 🤔

**Comment by ErdbeerbaerLP** [comment]
Also the terraformer does not do anything exept the gas particles. I let it run for 30 minutes and it dit not change the atm value at all

**Comment by Silfryi** [comment]
It needs _insane_ amounts of time and gas. Leave it to run overnight. Or multiple nights. Terraforming is never a fast process.
