### ISSUE TITLE
[BUG] "Failed to register dimension for id -2, One is already registered"

### ISSUE THREAD

**Issue by DJPhilGames** [zmaster587/AdvancedRocketry#1656]
## Version of Advanced Rocketry

>1.12.2 forge-14.23.5.2838
>Can't play this with other dimensional mods
>AdvancedRocketry-1.12.2-1.6.0-162-universal.jar

Crash log: https://pastebin.com/xkPHFVur

**Comment by Poxorosa** [comment]
Its a just ID conflict. Just change AR space station dimension ID to something different, than -2
