### ISSUE TITLE
Rocket disappears

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#166]
I tried to do an orbital flight, but when you select the earth in the destination chip and liftoff from the earth the rocket disappears before reaching the orbit.

**Comment by zmaster587** [comment]
This may occur in all cases where the source and destination are the same... investigating...

**Comment by Tarkov** [comment]
Is this implemented in the latest release? Because it is still happening

**Comment by zmaster587** [comment]
is this with player rockets or automated rockets?  Cargo/automated rockets are supposed to vanish on reaching orbit if being sent to the same planet id it took off from.  It's supposed to be more of it's being programmed for orbit.

**Comment by Tarkov** [comment]
It is with manned rockets, when the rocket disappears I start falling. However if in the moment it disappears, I restart minecraft, the rocket comes back and displays the space bar signal for the descent and everything is ok. 

I really like the idea of orbital flights. You can test rockets, fuel consumption, take pictures and come back. It is also very useful for some ideas I have. If it is too hard to avoid the rocket disappearing, please keep it as it is now.

Thank you very much for this awesome mod! :-)

**Comment by zmaster587** [comment]
Alright, manned rockets should now reach orbit and prepare for descent then should come back down to the same pad they took off from... maybe I should have it land on a barge instead...
