### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MuteTiefling** [zmaster587/AdvancedRocketry#1660]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
 AdvancedRocketry-1.12.2-1.6.0-162-universal

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
LibVulpes-1.12.2-0.4.1-1-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y

RecurrentComplex-1.4.8.2
justenoughdimensions-1.12.1-1.5.5

## Crash report or log or visualVM (if applicable)

No crash, but here's the log generated during startup anyway.
https://gist.github.com/MuteTiefling/7b1588142ea9a7a5da03b95677135582

## Description of the problem
Create a planet in Advanced Rocketry.
Set that planet as the default spawn location via JustEnoughDimensions.
Set a spawn structure ([guide](https://minecraft-recurrent-complex.fandom.com/wiki/Guide:_Spawn_Structure)) via recurrent complex. The structure will not spawn in a new world. Note that during creation of said structure RC must be told to allow the structure to spawn either in the planet's dimension or allowed in all dimensions. 

If the initial spawn dimension is listed as the overworld, the spawn structure works as expected.

I messaged the RC dev on Discord to see if I was just doing something wrong and he suggested that I speak with you first as it may be something that's being done here that's incompatible with RC Spawn Structures. 

MotokoYesterday at 9:20 PM
Hey all. Trying my hand at working with RC and I'm having a bit of trouble with spawn structures. I've made one that works just fine in a default world (MC Overworld, no mods but RC), but when I try to combine that with Advanced Rocketry dimensions and JustEnoughDimension to force initial spawn on one of the advanced rocketry planets, it just doesn't spawn
I've tried setting the dimension in the structure to both the AdvRocketry dimension and to nothing 'all' but it just never spawns on the planet as I'm loading in a new world
Not sure what I might be doing wrong

IvoriusToday at 3:45 AM
@Motoko Try talking to the specific mod authors
About this https://github.com/Ivorforce/RecurrentComplex/blob/9937aef9794463cd87e1b0c22992c19b354a1c2f/src/main/java/ivorius/reccomplex/world/gen/feature/GenerationSanityChecker.java#L41-L47

Sometimes it will not work even with my fallback generation code if mod authors set it up weirdly

**Comment by MuteTiefling** [comment]
Ok, nevermind. A week of trial and error and then I find the problem as soon as I post about it here...

The structure is spawning. But I'm spawning almost 1000 blocks away from it. So I need to approach this from a different angle.

**Comment by maruohon** [comment]
Are you spawning on the overworld spawn coordinates on the planet? Did you place the ReC structure at world spawn or some hard coded coordinates? You might want to enable WorldInfo overrides for the planet in JED, allowing it to have it's own separate-from-the-overworld spawn point, unless Advanced Rocketry already does that (doesn't look like it does). Also I'd highly recommend using the latest 1.6.0 build of JED instead of the old 1.5.5.

**Comment by MuteTiefling** [comment]
@maruohon Thanks for the response. I'll look into the 1.6 JED. I've just been using whatever Twitch installed for me, which is apparently the old one.
