### ISSUE TITLE
[BUG] Rocket fails to descend and clips into terrain

### ISSUE THREAD

**Issue by Taylor7500** [zmaster587/AdvancedRocketry#1661]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.6.0-160

## Have you verified this is an issue in the latest unstable build
N

>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
0.4.1-60

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
N/A

## Description of the problem
Took my first manned mission to Luna and my rocket fails to descend. I arrive and get the "Auto descent in 25" however the countdown doesn't count down. If I press space to manually descend then the altitude reader on the left does go down, however my player model doesn't move and I remain stuck "sitting" in mid-air. Am invisible in third person view. When the rocket "lands" I get the "press space to launch" issue however if I do launch I get the countdown and then nothing. No visual, no animation, and when the rocket thinks it reaches the limit I get put back to square one of being stuck and unable to descend.

I'm unable to access my rocket GUI by right clicking or leave the rocket. No input I've tried so far has done anything.

Upon failing to descend on earth I get stuck in the same place and my waypoints are jittering around like crazy. Trying to use a teleport item to get out initially threw my player around like crazy, inflicting damage. Re-logging (multiplayer server) left me stuck and suffocating in a wall. After I died and respawned I saw that the rocket was heavily clipped through my base. Was still completely unable to move and get out and had no choice but to disassemble it and replace the parts of my base it destroyed from the slipping issue.

Other mods: All The Mods 3 Remix 1.4.9 modlist here: https://github.com/AllTheMods/ATM3-Remix/blob/master/modlist.html

Screenshot where you can see the UI works but I'm stuck: https://i.imgur.com/Yx2AhVk.png

Screenshot of the ensuing chaos (rainbow box shows where the seat was): https://i.imgur.com/WztgKif.png

**Comment by Trellinane** [comment]
I am having this exact same issue.
Version of Advanced Rocketry
1.7.0-207

Have you verified this is an issue in the latest unstable build
Y

Reporting bugs that have already been fixed wastes everyone's time. (please look in open issues too, somebody else could have already reported it!)

Version of LibVulpes
LibVulpes-1.12.2-0.4.2-74-universal

Version of Minecraft
1.12.2

Does this occur without other mods installed
N/A

Description of the problem
Identical as originally reported above.  Why would Luna Coords show as "??? ???" on screen?

**Comment by zmaster587** [comment]
Does it still occur without any other mods installed?

What about with AR build 201?

What is the value of "    B:experimentalSpaceFlight" in the config?
