### ISSUE TITLE
[BUG] New stations appear in empty space when launched.

### ISSUE THREAD

**Issue by pwncc** [zmaster587/AdvancedRocketry#1668]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.0-1.5.0-139-universal

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y

>Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)

## Version of LibVulpes
>1.12.2-0.4.0-51

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.

## Version of Minecraft
>1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!

## Does this occur without other mods installed
- [x] Y
- [x] N
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

>Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>insert here

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.

## Description of the problem
>Launch a rocket with a space station. The space station will appear but it's orbiting nothing.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.

**Comment by pwncc** [comment]
It's orbiting space

**Comment by pwncc** [comment]
![image](https://user-images.githubusercontent.com/32709410/63058263-8e45a900-beec-11e9-89eb-80fbc96918f9.png)
everything i place turns into air

**Comment by zmaster587** [comment]
I'm afraid I'm unable to replicate the issue with only the details you've given me.

Using the most recent build (163, which is a good bit newer than 139, but you said you attempted it on the latest build anyway which should be 163) I built a space station using the station assembler.  I then assembled a spaceship with engines, tanks, and a satellite bay.  I took the constructed space station container from the space station assembler and placed it into the satellite bay of the constructed rocket.  I then fuelled the rocket and connected it to a rocket monitoring station using a linker.  I then pressed launch in the rocket monitoring station.  After that I built a rocket with a guidance computer and passenger seat and put the space station chip into the guidance computer.  I then assembled that rocket, fuelled it, and rode that rocket to the space station.  The space station was placed in orbit around earth as expected.

If your process differed significantly from this, please explain **_in detail_** the steps you took to make this issue occur.

**Comment by pwncc** [comment]
Ah, what I did is I placed the container inside the rockets satellite bay, put the station Id chip in that same rocket's guidance computer and rode that one to space with a seat.
