### ISSUE TITLE
[BUG] Sky becomes empty when used with shaders

### ISSUE THREAD

**Issue by TechnosophyModPack** [zmaster587/AdvancedRocketry#1669]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.6.0-162

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
LibVulpes-1.12.2-0.4.1-1-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
Shaders Mod / Optifine

## Description of the problem
Use AdvRocketry with Optifine and activate shaders to reproduce

**Comment by TechnosophyModPack** [comment]
Sky is blank and pink when using shaders, see:
![image](https://user-images.githubusercontent.com/50528659/63081085-8f300800-bef7-11e9-8a1f-8b3b8f8855ea.png)

**Comment by Silfryi** [comment]
Optifine is not supported, it breaks many rendering assumptions. If it's Optifine/shaders, it's very unlikely to be fixed.
