### ISSUE TITLE
[V0.6.5] Rutile Ore not Registered in Game

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [zmaster587/AdvancedRocketry#167]
After upgrading to version 0.6.5, NEI shows no method of obtaining titanium ingots/dust, and DragonAPI has identified zero ores registered for either oreRutile or oreTItanium.

**Comment by TheGuyRunningSouth** [comment]
May be related to the fix for #154 .

**Comment by zmaster587** [comment]
When I run it i still see it showing up in the electric arc furnace for NEI and it crafts just fine.

**Comment by zmaster587** [comment]
I'm an idiot.. I already patched it and forgot to push

**Comment by TheGuyRunningSouth** [comment]
@zmaster587 I'm sorry to bother you, but is there any chance the files on curse can be updated with this fix whenever you get the time? I need to restart my world due to an unrelated, fixed bug and can't because Rutile ore won't generate.

**Comment by zmaster587** [comment]
I'll push it in an hour or two
