### ISSUE TITLE
[BUG]Render Bags

### ISSUE THREAD

**Issue by Rumaruka** [zmaster587/AdvancedRocketry#1676]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>-1.6.0-164

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>-0.4.1-62

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>Logs: Very langer for pastebin D:

## Description of the problem
>More items and HUDS in mods changed. Looked screenshots:
![image](https://user-images.githubusercontent.com/8148679/63526842-7c31bf00-c519-11e9-8a01-ecc45e69e361.png)

![image](https://user-images.githubusercontent.com/8148679/63526909-99ff2400-c519-11e9-91e4-9ae921b65da9.png)

**Comment by Poxorosa** [comment]
Clipboard

**Comment by MrEyeballs29** [comment]
Just a clipboard really.

**Comment by zmaster587** [comment]
Is there something that has to be onscreen?  does this occur in a new world with just clipboard and AR ith nothing built?

**Comment by Rumaruka** [comment]
It's interested , but no , only textures changed after update your libs D: maybe temporary problem , I play 3-4 day and answer this question :)

**Comment by Rumaruka** [comment]
> Is there something that has to be onscreen? does this occur in a new world with just clipboard and AR ith nothing built?

after reload resoursepacks don`t changed =(
