### ISSUE TITLE
[BUG] Localization conflict with Thaumcraft?

### ISSUE THREAD

**Issue by bloche14** [zmaster587/AdvancedRocketry#1678]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.12.2-1.6.0-164

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
LibVulpes-1.12.2-0.4.1-62-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Did not test yet

## Description of the problem
I have Thaumcraft installed and the centrifuge from Advanced Rocketry is named "Essentia Centrifuge" (a machine from Thaumcraft). Could this be because both machines have the same unlocalized name and there is overlap?

**Comment by TripTripy** [comment]
I've had this issue as well in the past
