### ISSUE TITLE
[BUG] A serious error has occured while loading planetDefs XML

### ISSUE THREAD

**Issue by XplosiveP3nguin** [zmaster587/AdvancedRocketry#1679]
## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.6.0-164-UNSTABLE build -164 for 1.12.2

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
LibVulpes 1.12.2-0.4.1-62-UNSTABLE build -62 for 1.12.2

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Not Sure

## Crash report or log or visualVM (if applicable)
https://pastebin.com/nP3XD5Cm

## Description of the problem
I have created a modpack with about 200 mods in it. This includes advanced rocketry and so far no one has touched it. It has been about week of playing and no issues, for some reason when I launched it today this error occured and closed the server. First I checked to see if I had the latest version which at the moment I do. The first time I looked there was no planetDefs.xml so I copied a version off the internet to no avail. Then I tried deleting the configs, still didnt work. Then I deleted the library and advancedrocketry launched it to which some error appeared with moofluids. So I put them back in and then the same error appeared. This hasnt happened since I made tha pack and have played it and no one on the server has touched advanced rocketry since the start.

**Comment by XplosiveP3nguin** [comment]
No one has an answer? :(

**Comment by Yamza** [comment]
Typically happens when a world is terminated without saving properly aka corruption. You can try removing the planetdefs xml from the world folder and see if that helps, but if what I said is correct you more likely should just load a backup.
