### ISSUE TITLE
[BUG] Rocket takes off for no reason whilst on launch pad and/or is despawning.

### ISSUE THREAD

**Issue by LordVile20** [zmaster587/AdvancedRocketry#1685]
Version of Advanced Rocketry
>1.12.2 (In ATM 3)

## Have you verified this is an issue in the latest unstable build
- No

 Version of LibVulpes
>Unsure

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A

## Description of the problem
>One time I saw the rocket just take off with no one inside it and without any seeming provocation meaning that I couldnt go back to my space station because it was sent to the space station with my only chip. A second time I went into my base to pick up some supplies for my (new) space station and came outside to no rocket at all nor any signs of launching (smoke, etc.)

**Comment by Silfryi** [comment]
Did you have a rocket monitoring station anywhere near it?

**Comment by LordVile20** [comment]
> Did you have a rocket monitoring station anywhere near it?

Yes there was one however they were not linked

**Comment by Silfryi** [comment]
Was it linked to the pad? And did it have a redstone signal near it?

**Comment by LordVile20** [comment]
No redstone signal and i hadnt linked it at all
