### ISSUE TITLE
[BUG] Unable to Open Space Station Id Chip Config GUI

### ISSUE THREAD

**Issue by Dunklheit** [zmaster587/AdvancedRocketry#1688]
## Version of Advanced Rocketry
>1.6.0-164-universal

## Stack trace
[Available Here](https://i.imgur.com/HwCrjDt.png)

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>0.4.1-62-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

## Description of the problem
>Shift right-clicking the sat id chip to bring up GUI on dedicated server fails to open, causing a task failure.

**Comment by zavar152** [comment]
Yes, I have the same bug. It should be fixed. That's why we couldn't play multiplayer
