### ISSUE TITLE
White screen and crash after I pressed "scan rocket" in the rocket assembly machine

### ISSUE THREAD

**Issue by Craftingcat99** [zmaster587/AdvancedRocketry#1689]
[Neues Textdokument.txt](https://github.com/zmaster587/AdvancedRocketry/files/3569114/Neues.Textdokument.txt)
## Version of Advanced Rocketry
[1.4.0-63]
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
[0.4.0-51]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
[https://pastebin.com/kz4z89hR]

## Description of the problem
[I built a rocket launch pad, placed the rocket assembly machine, fueling station and rocket monitoring station. Then I build a very simple rocket(maybe 10 parts) and pressed scan, my world gets white(I still saw the gui) and 5sec later the world crashed and cannot be reopened(I tried it with normal power and creative(unlimited) power.)]

**Comment by Silfryi** [comment]
Can we have a log?

**Comment by zmaster587** [comment]
This looks like a advanced rocketry/libvulpes version mismatch.  However the versions of Advanced Rocketry and LibVulpes you're running are both really old.  Unfortunately I can't really fix anything without requiring you to update anyway.  Since this looks like a version mismatch issue anyway, would you be so kind as to see if this issue still occurs?

**Comment by Craftingcat99** [comment]
Hello, wich version is the newest version of adv. Rocketry and Lib Vulpes
that are compatible with each other? When I search for it get different
results.

Am Mi., 4. Sept. 2019 um 00:46 Uhr schrieb zmaster587 <
notifications@github.com>:

**Comment by Silfryi** [comment]
You need the latest versions for 1.12 for both.

**Comment by Craftingcat99** [comment]
Ok, I downloaded both zip files from GitHub, but how can I "activate" them?
If I extract both mods in the mod folder, minecraft doesn't load them.

Am Mi., 4. Sept. 2019 um 13:05 Uhr schrieb Silfryi Kalsandryn <
notifications@github.com>:

**Comment by Silfryi** [comment]
What. On. Earth. Use the jars on CurseForge, then put them unextracted into your mods folder.

**Comment by Craftingcat99** [comment]
Ok, sorry for my dumbness. I finally downloaded the right files, and got it
to work. And the problem with scanning a rocket is also fixed. Thank you
for your time and my bad grammar :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Do., 5. Sept. 2019 um 23:22 Uhr schrieb Silfryi Kalsandryn <
notifications@github.com>:
