### ISSUE TITLE
[BUG] crashing when using the rocket assembly

### ISSUE THREAD

**Issue by memebigboisplay** [zmaster587/AdvancedRocketry#1691]
## Version of Advanced Rocketry
>latest

## Have you verified this is an issue in the latest unstable build
Y

## Version of LibVulpes
>latest

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
>1.7.10

## Does this occur without other mods installed
yes

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/BvJW9B3Y (other mods)

https://pastebin.com/Tg6dUq37 (only rocketry and the dependency)

## Description of the problem
>just put the assembly down and left click it it just crashes

**Comment by Silfryi** [comment]
We need the versions, not just "latest"

**Comment by MrEyeballs29** [comment]
And the MC version is outdated.

**Comment by zmaster587** [comment]
It looks like an AR, libvulpes version mismatch.  THe version of libvulpes you're running appears to not have a build number, but the minor version is 2 (the latest is 4) so it's definately pretty far out of date.

The latest unstable build for 1.7.10 for libvulpes is located here: https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2558972

Unfortunately I don't really have time to continue to maintain 1.7.10 builds so if there's further issues beyond version mismatches it probably will not get fixed unless somebody else is willing to submit code or unless you're willing to update minecraft.

**Comment by memebigboisplay** [comment]
thanks for the help it worked thanks for all your help
