### ISSUE TITLE
[BUG] Server Fails to Start w/ 1.6.0-180 (NoClassDefFoundError)

### ISSUE THREAD

**Issue by nephatrine** [zmaster587/AdvancedRocketry#1692]
Getting a java.lang.NoClassDefFoundError error from zmaster587/advancedRocketry/network/PacketBiomeIDChange when starting dedicated server. Mod seems to work w/o issue on clientside.

## Version of Advanced Rocketry

AdvancedRocketry-1.12.2-1.6.0-180-universal

## Have you verified this is an issue in the latest unstable build

- [x] Y - This is the latest unstable build on Curse.

## Version of LibVulpes

LibVulpes-1.12.2-0.4.1-62-universal

## Version of Minecraft

1.12.2

## Does this occur without other mods installed

I do not know. Since it only happens server side it's not as trivial to test. If you cannot easily reproduce, I'll set up another server with just this and try and determine more information.

## Crash report or log or visualVM (if applicable)

https://pastebin.com/TbbvkfAG

## Description of the problem

Install mod on dedicated server. Launch server.

**Comment by nephatrine** [comment]
Tried using 1.6.0-164 and get same error. I've seen other people supposedly running that version w/o issue on a server so I'm assuming issue must be some sort of mod conflict. Unfortunately the mod list on this server is somewhat large, but I'm going to try and narrow it down to find a culprit.

**Comment by matrix07012** [comment]
I figured it out. JustEnoughIDs causes this issue. I tested only the latest versions though.

**Comment by nephatrine** [comment]
Guess I should have expected that since it was related to biome IDs. The previous version (along with jeidsi addon) do work just fine fyi. Disappointing since they claimed to have moved that compat into the main mod. Thanks for helping t/s even though I guess it wasn't really an issue on your end at all.
