### ISSUE TITLE
[BUG] AdvancedRocketry causing server crash: java.lang.NoClassDefFoundError: zmaster587/advancedRocketry/network/PacketBiomeIDChange

### ISSUE THREAD

**Issue by slushieboy99** [zmaster587/AdvancedRocketry#1693]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.6.0-180-UNSTABLE build -180 for 1.12.2

## Have you verified this is an issue in the latest unstable build
I've tried multiple version dating back to 2018, all with the same issue, but the issue persists in the latest version.

## Version of LibVulpes
LibVulpes-1.12.2-0.4.1-62-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
N

## Crash report or log or visualVM (if applicable)
https://pastebin.com/2G0rq70F

## Description of the problem
Advanced Rocketry causes server crash on my custom modpack. I have not narrowed down the issue to any specific mod, but if anyone has insight on the 
"zmaster587/advancedRocketry/network/PacketBiomeIDChange" error, that would be very helpful.

**Comment by nephatrine** [comment]
Are you using JustEnoughIDs? That was my issue - see #1692. If you roll back to the previous JEIDs version (and use JEIDsI since it's not built into that version) then it should work.

**Comment by slushieboy99** [comment]
Ahh that seems to be my problem. Thank you so much!
