### ISSUE TITLE
[Question] How to make an asteroids dimension.

### ISSUE THREAD

**Issue by TripTripy** [zmaster587/AdvancedRocketry#1694]
I've heard that an asteroids dimension and its possible to create controllable rockets in that dimension. What would I have to put into a planet defs to create a dimension like this?

**Comment by Silfryi** [comment]
Try <genType>asteroids</genType> ? And/or <genType>asteroid</genType>

**Comment by Silfryi** [comment]
It's definitely going to be some string in the `<genType>`tag, though, if those don't work

**Comment by TripTripy** [comment]
Thank you, ill let you know and close if that works

**Comment by Silfryi** [comment]
That'd be it, yeah. Code perusal is fun. `<genType>1</genType>` should be a nether type world. If you're done, close the issue please. There's enough clutter on here already.

**Comment by TripTripy** [comment]
Alright. Closed
