### ISSUE TITLE
[BUG] Exponential speed increase issue with Colytra

### ISSUE THREAD

**Issue by MuteTiefling** [zmaster587/AdvancedRocketry#1696]
## Version of Advanced Rocketry
>1.12.2-1.6.0-180

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [] N
- [] N/A

## Version of LibVulpes
>1.12.2-0.4 1-62

## Version of Minecraft
>1.12.2

## Does this occur with other mods installed
- [x] Y
- [] N
- [] N/A
> Colytra  (1.12.2-1.2.0.3)
> Baubles (1.12-1.5.2)

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>No crash

## Description of the problem
Equip a space suit with jet pack module. Equip bauble Elytra. Activate the bauble Elytra and fly.

Speed increases exponentially. I initially travelled over 300k blocks in about a minute. My PC finally gave up loading chunks....

This does not occur when the space suit chest is un-equipped. It does not occur with other armor. It also does not occur if the jet pack is not installed. It does occur regardless of whether the jet pack is enabled/disabled.

**Comment by zmaster587** [comment]
Is this with only the jetpack module with no speed upgrades in the helmet?  Also does this occur in hover mode as well or just normal mode?

**Comment by MuteTiefling** [comment]
I didn't even know there were speed modules, lol. The chest was the only piece with upgrades. It had 2 oxygen tanks, the jet pack, and a tank for jet pack fuel.

I was not in hover mode to my knowledge. I simply activated the jetpack (base keybind x, hud turned green), then double space bar while falling to start flying with the elytra.

**Comment by MuteTiefling** [comment]
Here's with the hover upgrade installed. 

https://streamable.com/bxdjn

Doesn't really matter what state the chest is in though. If the jet pack is installed, this happens. Only way to stop it is to remove the chest plate/jetpack. Works fine with a space suit chest with no jetpack though.

**Comment by zmaster587** [comment]
Hmm.... what version  of forge?  I'm just getting a straight up crash from Colytra on forge-1.12.2-14.23.4.2760

**Comment by MrEyeballs29** [comment]
You should add in the forge version as well.

**Comment by zmaster587** [comment]
Nevermind, I got it, 14.23.5.2824 works

**Comment by zmaster587** [comment]
So it turns out there was an off-by-one where it would give you one invisible speed upgrade.  Speed upgrades work by multiplying player velocity by some factor greater than one and it eventually hits an equilibrium with "friction".

Specifically
```
		//Apply speed upgrades
		player.motionX *= 1 + speedUpgrades*0.02f;
		player.motionZ *= 1 + speedUpgrades*0.02f;
```

But it looks like when an elytra is worn it seems the friction isn't calculated so you get infinite speed.

**Comment by zmaster587** [comment]
fixed for next build.
