### ISSUE TITLE
[BUG]Astroid ID chip dissapearing when mining mission lands

### ISSUE THREAD

**Issue by Dreadknott456** [zmaster587/AdvancedRocketry#1699]
## Version of Advanced Rocketry
>1.12.2-1.6.0-164

## Have you verified this is an issue in the latest unstable build
- [x] Yes

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.1-62

## Version of Minecraft
1.12.2
## Does this occur without other mods installed
- [x] Yes

>If Y, what is the MINIMUM set of mods required.
I have 36 in total on the server that I first encountered the issue but on my single player I tried it with just libvulpes and adv rocketry latest versions (to test if there was a fix) and the asteroid chip still dissapears on finishing the mission. 

## Crash report or log or visualVM 
Not applicable no crashes occured 

## Description of the problem
Build the full setup for an asteroid mining mission, including waiting until the asteroid chips data includes the full amount of 1000 distance, mass, and comp. Send an asteroid mining rocket up with the chip and upon the rocket landing back bringing the up to 15 of each ore the chip is no longer in the guidance computer. which is not worth the time it takes to send the mission. Does not allow for automation of missions either removing a whole entire playable part of the mod.

**Comment by Silfryi** [comment]
Working as intended. You cannot mine an already mined asteroid.

**Comment by Silfryi** [comment]
I've talked to Z about it previously, and they are meant to be a midgame source of ore. If you want to have it be more worth it, increase the mass of asteroids in the config.

**Comment by TripTripy** [comment]
Here's a possible idea. Perhaps instead of just strait up deleting the chip, it could return an empty unprogrammed chip so that it could be reused for a different asteroid. This would allow for better automation. Instead of making endless supplies of asteroid chips, you could instead have just a few that flow through your automation system. This wouldn't allow revisiting asteroids, but would still fix the automation problem.

**Comment by Dreadknott456** [comment]
I do agree the amount of resources being sunk into the asteroid mining outways it's usefulness even if the asteroids are bigger but I do understand that you can't mine the same Astroid. Maybe having an Astroid field chip where it could do multiple mining missions off of the astroids in that field. But then again that would take alot of recoding
