### ISSUE TITLE
[Suggestion]add config for used dimension IDs

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#17]
Since there would be lots of planets I gusse it will use lots of dim id.
Better to make it configurable to prevent conflicts with others.

**Comment by zmaster587** [comment]
Planet ids are generated dynamically, right now when the planets are first generated it will not use any dimIds used by other mods.  The moon and space station dimension are the only ones that are hard assigned.  What can be done is have AR check when the server is loaded if another mod has allocated the dimension previously assigned to a planet and remap it to prevent a conflict

**Comment by wormzjl** [comment]
IMO It's better to use the standard system and predefine the dimID beforehands if the planet numbers are not procedurally generated.
I would like to use Custom Ore Generation mod to generate different ores on different planets, but this requires that these dimID are known before starting MC.

**Comment by zmaster587** [comment]
The planet numbers are procedurally generated, right now the mod is hard-coded to make a certain number of planets when the server is first run.  But in the next major update planets will be generated on-the-fly when first visiting a new solar system.  As of right now planets just take whatever the next free Id is when generating and running "/advrocketry planet list" should give you a dump of the ids.  The planets are not generated until you visit them so you should be able to set the ore generator so match up with one of the planets.  Mind if I ask which ore generator mod you are using?  I Might look into adding support for it.

**Comment by wormzjl** [comment]
I'm using this mod to generate ore veins
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291128-custom-ore-generation-first-revival
https://github.com/lawremi/CustomOreGen
http://customoregen.shoutwiki.com/wiki/Main_Page

It's an extremely powerful tool to define ore formations, it even allows generataion of tileEntities with predefined NBT tags

**Comment by zmaster587** [comment]
Could see something like adding a by-planet-type category being useful

**Comment by wormzjl** [comment]
It can use dimension.generator.class as reference, such as "ChunkProviderGenerate" for the overworld and "ChunkProviderFlat" for flat worlds, I guess AR has its own dimemsion provider?

**Comment by zmaster587** [comment]
It does, I might be able to work with that
