### ISSUE TITLE
[BUG] Crash when Rocket Builder tries to build (conflict with Stellar Sky)

### ISSUE THREAD

**Issue by sumrex** [zmaster587/AdvancedRocketry#1701]
## Version of Advanced Rocketry
>1.6.0-183

## Have you verified this is an issue in the latest unstable build
- Y

## Version of LibVulpes
>0.4.1-62

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- Y, the conflict is with Stellar Sky

## Crash report or log or visualVM (if applicable)
>[Crash Report](https://pastebin.com/SwLr3YW7)
While this crash log shows many other mods, I have already tracked the problem to Stellar Sky alone. 

## Description of the problem
>When the rocket builder tries to build a rocket the game crashes. It is very consistent and is perfectly fine while scanning or placing the blocks. I could not find anything in either mod's configs to fix this error.

**Comment by zmaster587** [comment]
Looks like the dummy rocket world is returning null for the mapStorage and stellarySky is not liking that.  I'll modify it to return a dummy object instead.
