### ISSUE TITLE
Can't use other Pipes[BUG]

### ISSUE THREAD

**Issue by MGW14** [zmaster587/AdvancedRocketry#1702]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.12.2 - 182

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
0.4.1 - 62

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- Yes, Mekanism, EnderIO

## Description of the problem
Since we can't craft the Fluid Pipes we need to use Pipes from other Mods. None of them are transporting Oxygen or Hydrogen. The pipe is pointing in to the Fluid Output Hatches but nothing is happening. I tried to put Oxygen into my Chemical Reactor

**Comment by Silfryi** [comment]
Are they set to extract? Can I have a picture of the setup? What about chunkborders?

**Comment by MGW14** [comment]
I tried this:
![2019-09-21_09 21 58](https://user-images.githubusercontent.com/40062542/65369750-60712400-dc51-11e9-8902-07a455c91172.png)
![2019-09-21_09 20 54](https://user-images.githubusercontent.com/40062542/65369751-60712400-dc51-11e9-9d07-bc831d78cddb.png)
(I also tried to power them with a lever but it didn't work)

Even in one Chunk:
![2019-09-21_09 26 09](https://user-images.githubusercontent.com/40062542/65369783-e2f9e380-dc51-11e9-800c-12491135a6fc.png)

I don't know that you mean when your saying extract.
Thanks anyway

**Comment by Silfryi** [comment]
The Mekanism pipes in the picture are not set to extract. Shift-right-click with the configurator to so do. Can I see the conduit GUI on the extract?

**Comment by MGW14** [comment]
Oh wow.
Thank you, now it worked i had to Shift-Rightclick the end/begin of the pipe and set it to pull/push.
NOT A BUG
