### ISSUE TITLE
[BUG] Crash after pulling id chip from space station assembler

### ISSUE THREAD

**Issue by dovaezburn** [zmaster587/AdvancedRocketry#1705]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.6.0-160-universal

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.1-60-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A

## Crash report or log or visualVM (if applicable)
>https://pastebin.com/bgytH06t

## Description of the problem
>Crash after pulling id chip from space station assembler

**Comment by Silfryi** [comment]
Does this happen without Sponge?

**Comment by dovaezburn** [comment]
Yes, seems like a sponge issue

**Comment by zmaster587** [comment]
There doesn't appear to be anything AR related in the stack trace, does this happen with mods other than AR?   If so please close the issue and report it to sponge instead.

**Comment by dovaezburn** [comment]
Conflicting with only sponge, closing thread
