### ISSUE TITLE
Make Advanced Rocketry compatible with Matter Overdrive dilithium

### ISSUE THREAD

**Issue by Gliese-832-c** [zmaster587/AdvancedRocketry#1706]
This should be extremely easy to do.

The dilithium crystals from AR should have gemDilithium in the oredict, and AR machines should also be able to accept things with gemDilithium as their oredict.

**Comment by zmaster587** [comment]
Renamed crystalDilithium -> gemDilithium in b02dac9e49abd79fccf2d08a7edfde970e16018e
