### ISSUE TITLE
Client crashing when opening Guidance Computer inside built rocket. [BUG]

### ISSUE THREAD

**Issue by KrinonValian** [zmaster587/AdvancedRocketry#1711]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.12.2-1.6.0-183-UNSTABLE build

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.12.2-0.4.1-62-UNSTABLE

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/UwiSu9cp

## Description of the problem
Problem is easily replicated by opening a guidance computer inside of a built rocket ready for take off on a server. This only crashes the client, not the entire server or those nearby the rocket when the crash occurs. Additionally, the guidance computer does not crash the client every time it is opened. If a player is riding the rocket when they crash, the rocket disappears until the player rejoins the server.

**Comment by Silfryi** [comment]
Does this happen without LittleTiles?
