### ISSUE TITLE
[BUG] Twilight Forest Has No Oxygen.

### ISSUE THREAD

**Issue by NutMaster6942** [zmaster587/AdvancedRocketry#1712]
## AR Version
>1.6.0 build 183

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>Latest?

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
3, AR, LibVulpes, and Twilight Forest (I have some more but these are probably the offending mods.)

## Crash report or log or visualVM (if applicable)
>N/A

## Description of the problem
>Head to the Twilight Forest while not wearing a Modular Space Suit.

**Comment by Silfryi** [comment]
This is caused by a DIMID conflict, not anything on AR's part. Set the dimensions for planets to something above that of TF's DIMID. Close this issue after please, not a bug, user error (though unintentional).

**Comment by NutMaster6942** [comment]
Thanks.

**Comment by Nikkkkk4** [comment]
> 
> 
> This is caused by a DIMID conflict, not anything on AR's part. Set the dimensions for planets to something above that of TF's DIMID. Close this issue after please, not a bug, user error (though unintentional).

Can you be a bit more specific and tell me step by step what to do? I have no idea what you guys mean

**Comment by bczhc** [comment]
Info to anyone reaching this issue page: I resolved this by changing TF's dimension ID to an unused one, in the config file of Twilight Forest.
