### ISSUE TITLE
[BUG] Server crash on launch

### ISSUE THREAD

**Issue by Sauzzey** [zmaster587/AdvancedRocketry#1713]
## Version of Advanced Rocketry
>1.12.2-1.6.0-160

## Version of LibVulpes
>1.12.2-0.4.1-60
I have tried the latest version of LibVulpes+AdvRocketry as well.

## Have you verified this is an issue in the latest unstable build
I have verified this is an issue in the latest unstable build.

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
I've pinpointed that it is AdvancedRocketry causing the server crash (and not LibVulpes).
For a non-custom modpack like All The Mods 3, it launches just fine.

## Crash report or log or visualVM (if applicable)
>https://pastebin.com/Yssd5x4k

## Description of the problem
I've only managed to reproduce this issue by starting the server with AdvancedRocketry so far. The client is fine and unaffected, so unlike a previous issue I've seen it should not necessarily be OpenTerrainGenerator at fault. (#1030)
I'm personally completely mystified why this would be fine on client but crashes the server, hence I tried replicating the issue again with the same version All The Mods 3 uses.
With that in mind, it's probably a mod conflict. (I'm so sorry I don't have further pointers.)

**Comment by Silfryi** [comment]
Are you running Advanced Rocketry on a Sponge server? If so, that would likely be why.

**Comment by Sauzzey** [comment]
Nope, running it on the latest Forge version server.

Op zo 6 okt. 2019 13:23 schreef Silfryi Kalsandryn <notifications@github.com

**Comment by chawolbaka** [comment]
Try to delete JustEnoughIDs?

**Comment by Sauzzey** [comment]
Hey, sorry for the late response.
I've made a new modpack without JustEnoughIDs and most of the same mods and it seems to have fixed the issue. My only issue is AdvRocketry saving biomes for world 8, 29 and 70.

You're free to close this issue as I figure out what I'm doing!
