### ISSUE TITLE
Game Crashes on Startup With No Other Mods [createAutoGennedRecipes]

### ISSUE THREAD

**Issue by Stedal24** [zmaster587/AdvancedRocketry#1716]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.6.0-183
## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A
## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-66
## Version of Minecraft
>1.12.2
## Does this occur without other mods installed
- [x] Y
- [ ] N
- [ ] N/A
>The minimum set of mods for the game to crash is just Advanced Rocketry and LibVulpes.
## Crash report or log or visualVM (if applicable)
>Crash Report: https://pastebin.com/EdCSAQTj Log: https://pastebin.com/Yg4hEHxQ
## Description of the problem
>When I downloaded Advanced Rocketry and LibVulpes, I was greeted with Minecraft crashing when Forge was initializing Advanced Rocketry on stage four of initialization. I tested with just the two mods, and I found the crash still occurred. I am using Forge version 14.23.5.2847. The game just crashes whenever I launch it with Advanced Rocketry.

**Comment by Archilyte** [comment]
https://paste.dimdev.org/ixapisofap.mccrash
is this in any way, shape, or form related?

**Comment by zmaster587** [comment]
Libvulpes 66 is for AR 184+, due to a misconfiguration on the build server it got released a little bit early.  186 should be out shortly

**Comment by Archilyte** [comment]
ok
thanks

**Comment by zmaster587** [comment]
@Archilyte yeah, internally crystal got renamed to gem to fall in line with ore dict naming conventions.  Build 184 here was meant to go with libvulpes 66 http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/1.12/changes

**Comment by zmaster587** [comment]
AR 186 is out, it'll run with libvulpes 66+
