### ISSUE TITLE
[Request] Alien/abandoned ships, inter-planetary weapons and starships

### ISSUE THREAD

**Issue by Meatball1230** [zmaster587/AdvancedRocketry#1718]
I have multiple suggestions, but didn’t want to spam the issues tab.

My first suggestion is alien/abandoned ships. The idea for this is that while in a space station, you can scan for other bodies orbiting the planet/moon/ whatever you’re currently orbiting. If it finds an alien ship, you can copy its coordinates to a ship and fly to it. If the ship is an alien ship, it’ll be full of alien creatures (no specific design). With random loot and some structures like biome scanners. Abandoned ships will have holes, ruptured power lines, dark rooms and maybe some space junk around it. They have no mobs and very little loot, and some broken structures.

Next up is inter-planetary weapons! (Although some can be shot at moons or other stations) My first idea was a large super laser. With three different colors (red, green and blue) it can be set to attack set coordinates with three different modes:

Spiral- the laser spirals from about 50-80 blocks out toward a central location, doing light block damage to softer blocks like dirt, gravel and sand, but then increases power and does very high damage to both entities and blocks when nearing the center.
Multi-burst- blasts about 3-4 beams in succession at a set coordinate location
Single beam- launches a single but deadly beam at a set location.

The next weapon is a missile. Well… multiple missiles. Whether this be a way to launch missiles from icbm or other missile mods, or new missile mechanics entirely. The way missiles would be launched is with a silo. A multiblock structure which varies in size. The silo is what holds the missile and is what fires it from a silo controller which can be wireless. A large silo can hold three missiles. A warp silo can send missiles across solar systems with a neat warp animation to give it extra flare. Some new missiles come with this, too. One of which isn’t actually a missile.

EMP clamp- emp clamps can be launched from silos. They can only target stations as long as they or the one launching are in hyperspace. When the clamp is successfully…… clamped, the light will turn green on the back and will disable any electronics withib a 20, 35, or 50 block radius in any direction until it is destroyed.

Warp interceptor- a warp interceptor is another launchsble tool that clamps on a station. This one works in the way that when a warp is commenced, the interceptor will collect energy from the warp, disconnect from part of the interceptor and fly back to you. The part left behind is a ticking time bomb that if left alone for too long, will cause an energy based explosion based on how far the warp was, complete with its own animation. The interceptor will need to be reloaded before use again.

Energy missile- a missile that creates an energy based explosion dependent on the tier.

Implosion missile- makes a set area implode with a block-hole style effect

Defense crippler destroys low quality defense systems.

This last one is kinda out there, so I don’t care if it’s not possible or too hard to program. This last missile is inspired by the M.D. (molecular disrupter) from the book Ender’s Game (and later titles). This missile is so big it needs its own silo. A tier 4 silo. The missile is 7 blocks long, 5 blocks wide and 5 blocks tall. This giant missile can destroy an entire planet, moon or space station, turning it into a huge ball of space dust. As I said, this is inspired from the Ender’s Game series, (skip to next paragraph for no spoilers!) which the MD was used to annihilate both a swarm of Formic ships and the Formic home world.

The target won’t be destroyed unless all players are off the planet. After it’s been destroyed, it acts as a gas giant. It still shows up on the map, just as a giant cloud of space dust that can’t be landed on. A set of new blocks called high power magnets and dust containers can be put on unmanned ships to collect metal dust, and lots of it.

Finally, starships. Starships work different to spaceships. They are horizontal instead of vertical. To build one, a control deck is required. It’s like a guidance computer but looks like a steering terminal. To take off, they must have a clear line of runway takeoff blocks, which they will fly above before flying upward into space. For landing, they also need a strip of runway landing blocks, which it will hover across before turning to face the direction of takeoff blocks. I thought of maybe letting the player control the flight until they decide to land or travel to another planet, but I feel that might get too complicated. If we ever get new thrusters, some ion or energy trail would be cool. Plus If it supported multiple passengers we could make space bus ports like in the Jetsons or something.

I think these features should be added because:

A. The abandoned and alien ships would add a bit of extra exploration and maybe lore with like hidden codex tapes or something
B. There’s not much in the form of weaponry and a way to have wars with friends or enemies except maybe block damage from the mining laser
C. Having starships alongside rockets would add so much potential for builds for one. Instead of having holes in the roof for rockets to land on or awkward landing pads sticking out, we could have landing ports flush with the station itself. Plus if the landing and takeoff blocks can take a ship vertically, we could do things like tie fighter hangars. Other than the build potential, if my other idea of letting a player control the flight before landing or traveling, maybe weapons could be added and we could get a bit of a Death Star attack going on with laser turrets and energy torpedoes. But otherwise, having starships could support multiple passengers, so multi-person travel would be possible. Other than that, unless you devs come up with something, it’s really up to preference whether you want a rocket or starship.

**Comment by Meatball1230** [comment]
Yeah it’s a lot. Sorry.

**Comment by TripTripy** [comment]
Have you seen some of the open suggestion threads? This isn't that much to suggest. You can always suggest stuff, it just might not get done for quite a while.

**Comment by TripTripy** [comment]
@Meatball1230
