### ISSUE TITLE
Oxygen detector wrong name

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#172]
After update from AR 0.6.6 to 0.6.7 Oxygen detector lost its name and only has the tile name.
![2016-08-07_15 45 05](https://cloud.githubusercontent.com/assets/1352518/17462710/407cf8a4-5cb6-11e6-8100-b0ab2b49f31a.png)

**Comment by zmaster587** [comment]
not sure how that happned...
