### ISSUE TITLE
[BUG] Rocket doesn't land on space station

### ISSUE THREAD

**Issue by Archilyte** [zmaster587/AdvancedRocketry#1721]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>latest as of this writing

## Have you verified this is an issue in the latest unstable build
-  Y

## Version of LibVulpes
>latest as of this writing

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- N/A
>idk if this issue is with other mods or not

## Description of the problem
>Rocket doesn't land on space station, it just keeps going down, until it goes back to the orbiting planet. Orbiting planet isn't shown either

![2019-10-19_20 25 43](https://user-images.githubusercontent.com/39607601/67152981-44dc5600-f2af-11e9-9dd6-ed5f0f7aa7c9.png)
you can see that the rocket is falling

![2019-10-19_20 25 47](https://user-images.githubusercontent.com/39607601/67152985-676e6f00-f2af-11e9-979d-30cd1f67645a.png)
space station (i didnt move from the place i took the first screenshot from, just looked upward)

**Comment by Silfryi** [comment]
Are there blocks in your space station? Were there some before they were moved away from origin of the station?

**Comment by Archilyte** [comment]
wait
if i make another mod generate stuff in the space station dimension, does it affect where rocket lands?
(i tweaked matter overdrive config to spawn gravitational annomalies in that dimension)

**Comment by Archilyte** [comment]
yep
if any mod generates stuff in the space dimension, it messes up the landing place of rocket
