### ISSUE TITLE
[BUG] Orbital Laser Drill bug while mining the moon

### ISSUE THREAD

**Issue by nebigoktug** [zmaster587/AdvancedRocketry#1723]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.6.0-186-universal

I changed the Orbital Laser Drill option to mine the moon turf and dilithium but it only mines the Matrix Frame from Applied Energistic2. I don't know if it is related to AR or AE2 but Orbital Laser Drill mines the Matrix Frames from Luna.

**Comment by Silfryi** [comment]
Can I see your config file?

**Comment by nebigoktug** [comment]
I just changed this line:

    # If true the orbital laser will actually mine blocks on the planet below
    B:laserDrillPlanet=true
It works fine for overworld btw.
[advancedRocketry.zip](https://github.com/zmaster587/AdvancedRocketry/files/3776231/advancedRocketry.zip)

**Comment by zmaster587** [comment]
What coordinates is it mining at on the moon, what blocks appear to have been dug up.  Could it possibly be hitting a base of some kind?

**Comment by nebigoktug** [comment]
I first mined 0-0 then 1000-1000 , tried couple coords. 
> Could it possibly be hitting a base of some kind?

I had landed moon i'm sure there isn't any bases and the surface is fine
I'll try removing AE2 then mining again.

**Comment by nebigoktug** [comment]
![2019-10-27_22 01 17](https://user-images.githubusercontent.com/57064423/67639832-c19dae80-f905-11e9-92a7-ff602a48d68e.png)
Me and that two rocket is standing mid air.


> Could the lunar surface somehow end up being Matrix Frames due to some terrain gen bug?

Sorry i tried to land moon again twice. I think the moon's sky somehow turned into that invisible matrix frames.
