### ISSUE TITLE
Oxygen Vent not working

### ISSUE THREAD

**Issue by sossololpipi** [zmaster587/AdvancedRocketry#1724]
## Version of Advanced Rocketry
[1.12.2 1.5.0 139 ]
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
[insert here]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)

[None]

## Description of the problem
Space Station's Oxygen Vent not working, despite all requirements being met and no leaks being present. Double checked a lot of times, might be Chisel's blocks.

![2019-10-28_19 56 12](https://user-images.githubusercontent.com/43117641/67726691-0e908c00-f9bd-11e9-82cc-33742cba8774.png)

**Comment by zmaster587** [comment]
Can you run the O2 tracer?

**Comment by TripTripy** [comment]
Does the oxygen vent have a redstone signal?

**Comment by sossololpipi** [comment]
> Can you run the O2 tracer?  There should be a button inside the vent for that.
I don't know what the O2 tracer is. Theres this weird green button with "Trace" on it, if that's what you're talking about.


> Does the oxygen vent have a redstone signal?
I have it making noise, indicating that it is infact active. I have a lever next to it for good measure.

**Comment by sossololpipi** [comment]
Nevermind, it just takes an entire real life day to update.
