### ISSUE TITLE
[BUG] My Black Hole Generator isn't working (maybe i'm missing something)

### ISSUE THREAD

**Issue by Conansson** [zmaster587/AdvancedRocketry#1727]
## Version of Advanced Rocketry

AdvancedRocketry-1.12.2-1.6.0-186-universal.jar

## Have you verified this is an issue in the latest unstable build

- [x] N

## Version of LibVulpes

LibVulpes-1.12.2-0.4.2-68-universal.jar

## Version of Minecraft

1.12.2

## Does this occur without other mods installed

- [x] N/A

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read

## Description of the problem

I tried to set up the black hole generator. I created a black hole using the planetDefs file, went to the black hole, set up the multiblock, filled the input hatches with Dirt/cobblestone/Stone as set in the config of advanced rocketry and turned it on, but it doesn't drop any items, nor does it generate power. There is no wiki page or other resource on this multiblock, so i figured i'd just ask here. 
I added screenshots of my setup. 
Love your mod!
![2019-11-03_22 55 34](https://user-images.githubusercontent.com/57071946/68092751-b8c15580-fe8e-11e9-8c1a-b006a11de66b.png)
![2019-11-03_22 55 39](https://user-images.githubusercontent.com/57071946/68092752-b8c15580-fe8e-11e9-8a57-921271825ed3.png)
![2019-11-03_22 55 43](https://user-images.githubusercontent.com/57071946/68092754-b8c15580-fe8e-11e9-849b-973bd8e4c680.png)
![2019-11-03_22 55 49](https://user-images.githubusercontent.com/57071946/68092756-b959ec00-fe8e-11e9-8a20-7920e10d5301.png)

**Comment by zmaster587** [comment]
Do you have any energy output hatches on it?

**Comment by NutMaster6942** [comment]
> Do you have any energy output hatches on it?

It does not appear they do, which is 100% the problem.

**Comment by Conansson** [comment]
It totally worked, thanks!
