### ISSUE TITLE
Having issues with asteroid configuration

### ISSUE THREAD

**Issue by supermattdab0ss** [zmaster587/AdvancedRocketry#1731]
Running version 1.12.2-1.6.0-187 currently, lib-vulpes 1.12.2-0.4.2-68

Crash report found here, including full mod list as well.
https://pastebin.com/gAmv76AA

I'm having issues configuring the asteroids in the xml file currently. The game initially loads fine, however upon attempting to load a world it fails and gives me the crash report above. I linked the xml file down below, it appears to be fine however it is very likely I'm just missing something or using improper syntax, although it remains possible that this is a bug. Could someone please review the file and

(I just found that lowering the D in Draconicevolution:draconic_ore 2 was an issue however it is still crashing even with the D lowercase. This probably means it's just my fault somewhere else and not an actual bug.)

xml configuration can be found here: https://pastebin.com/mS4TArBM

EDIT: I'm just retarded and there is a syntax error at line 47, missing quotation mark. Sorry.

**Comment by Silfryi** [comment]
Try changing replacing all of the spaces with semicolons in the ItemStack definitions. Other than that, try renaming the "small asteroid" to something different. If that doesn't work, can I have the full log?

**Comment by supermattdab0ss** [comment]
> Try changing replacing all of the spaces with semicolons in the ItemStack definitions. Other than that, try renaming the "small asteroid" to something different. If that doesn't work, can I have the full log?


I resolved the issue, thanks for the feedback anyways though. It was a simple syntax error, forgot a quotation mark, along with the improper capitalization of draconicevolution:draconic_ore:2.
