### ISSUE TITLE
Oxygen and Rocket Launch overlay not existing

### ISSUE THREAD

**Issue by JW6677** [zmaster587/AdvancedRocketry#1732]
## Version of Advanced Rocketry
1.6.0-187
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
0.4.2-68
## Version of Minecraft
[insert here]
N/A
## Description of the problem
Entering a rocket that has been built doesn't show any overlay. I am running it on a Forge server (14.23.5.2847) and I'm also using Optifine(1.12.2_HD_U_F4)

**Comment by JW6677** [comment]
I found not I shouldn't use a dual Hotbar mod :)

**Comment by MrEyeballs29** [comment]
Report to the dual hot bar mod.
