### ISSUE TITLE
[Request] multiple suns

### ISSUE THREAD

**Issue by Meatball1230** [zmaster587/AdvancedRocketry#1733]
I’m not exactly sure how this would be implemented. I think it would be cool to have multiple subs in one system that appear when looking at the sky from the planets, just like how tatooine in Star Wars had its two suns. It’s a simple Request but would be awesome.

**Comment by zmaster587** [comment]
Thanks for the suggestion, but this is actually already implemented.  Docs and example available here: http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/AdvancedPlanetConfiguration.php#starSpec

**Comment by Meatball1230** [comment]
Really? Sweet! Thanks for letting me know!
