### ISSUE TITLE
[BUG] 1.12.2 rockets leaving players stranded in the sky

### ISSUE THREAD

**Issue by YOYOK9** [zmaster587/AdvancedRocketry#1734]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.6.0-187-universal

## Have you verified this is an issue in the latest unstable build
- [x] N

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-68-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N/A
Modpack: businesselite-plus

## Crash report or log or visualVM (if applicable)
Lates log: https://gist.github.com/YOYOK9/f6c4b1eeaf0eee9609e9751ec4b3362a
No crashes are produced. 

## Description of the problem
It seems sometimes when launching a rocket back between planets the rocket will sometimes vanish leaving the player above Y 500 meaning death when they hit the ground. Other times the rocket is just spawned at build limit (or just below) and stuck there leaving the player again stuck in the air but also loss of a rocket if they get "pushed" off when the exit the ship. Can still access the ship when it is stuck in the air. 

Pictures:
![2019-11-17_17 49 21](https://user-images.githubusercontent.com/12290062/69015790-9b4bbb80-0965-11ea-93c9-e58a433a54b6.png)
![2019-11-17_17 51 27](https://user-images.githubusercontent.com/12290062/69015791-9b4bbb80-0965-11ea-8253-006bde0e38df.png)

**Comment by zmaster587** [comment]
Does this occur without any other mods installed?

**Comment by YOYOK9** [comment]
It appends some of the time. I spawned in the first time on the rocket however it was the first time I saw the "press space to descend" option. the second time I spawned without a rocket and it was down on the planet without me. 

Seems to be a 50/50 thing.

**Comment by zmaster587** [comment]
can you get it to happen at all with just advanced rocketry and libvulpes installed?

**Comment by YOYOK9** [comment]
Sorry should have clarified. My last response was with just the 2 mods installed. It was a 50/50 chance it seemed. Out of my tests (going to the moon and back) only once did I land on a planet with the rocket smoothly. The rest was either stuttering hard, left in the air without a rocket or the rocket stuck in the air.

**Comment by MrEyeballs29** [comment]
This does not answer the question.

**Comment by YOYOK9** [comment]
So far I have only had the chance to test with just AR and libvulpes installed. It still showed the same issues as above. How ever this time I actually had gotten the "press space to descend" message where with all the other mods I had not. I plan to test mod by mod this weekend when I have some more time.

**Comment by AwesomeNoob999** [comment]
no stale
