### ISSUE TITLE
Rocket stuck in air

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#174]
When traveling to a Spacestation in 0.6.7 the rocket lands and stop on a Z level around 1000 and you fall out of the rocket. You fall to the spacestation on Z 128 and after around 20-30 seconds the rocket falls down next to you.

EDIT: Y level..... not z

Pic:
![2016-08-07_19 18 05](https://cloud.githubusercontent.com/assets/1352518/17463988/24974c48-5cd4-11e6-8312-b321d4f4a0a8.png)

**Comment by zmaster587** [comment]
logging out and logging back in appears to put the player back on the rocket, possibly some desync
