### ISSUE TITLE
Oxygen Vent does not accept liquid oxygen from Mekanism

### ISSUE THREAD

**Issue by Nomad7** [zmaster587/AdvancedRocketry#1740]
## Version of Advanced Rocketry
> 1.12.2-1.5.0-139

## Have you verified this is an issue in the latest unstable build
- [x] N
We're running Enigmatica 2 v1.4.2 and I can't update individual mods outside of the pack, sorry!

## Version of LibVulpes
> 1.12.2-0.4.0-56

## Version of Minecraft
> 1.12.2

## Does this occur without other mods installed
- [x] N/A
> I'm constrained by the Enigmatica 2 modpack, but this seems to be specifically a conflict between Mekanism and Advanced Rocketry related to how they handle Oxygen / Liquid Oxygen

## Crash report or log or visualVM (if applicable)
> N/A

## Description of the problem
> It seems the only valid input for an oxygen vent is the oxygen that comes from an electrolyser, not a rotary condensentrator.
Steps to reproduce:
1, place (and power) an oxygen vent.
2, using Mekanism, pipe some water into an electrolytic separator to generate oxygen, transport that oxygen to a rotary condensentrator to convert it to liquid oxygen, then pipe that liquid oxygen to the oxygen vent.
3, observe the oxygen vent.

Expected results: the oxygen vent should receive oxygen.

Actual results: no oxygen is added to the oxygen vent.

Notes:
There appear to be a few older tickets about (what appears to be) the same type of issue:
https://github.com/zmaster587/AdvancedRocketry/issues/663
https://github.com/zmaster587/AdvancedRocketry/issues/1239
https://github.com/zmaster587/AdvancedRocketry/issues/1620
and in my various searches I heard about a possible issue where Forge can sometimes use the wrong default fluid for a type - not sure how to diagnose that - but I'm hoping for a sustainable method of oxygenating my moon base and space station that doesn't involve building bunches of bulky Electrolysers all over the place :)

Please let me know if there's any additional information or details I can provide.

**Comment by Nomad7** [comment]
This may belong in a separate ticket, but after some additional testing it seems like the oxygen consumption of the vent is dramatically reduced if I have two scrubbers adjacent to it - even if those scrubbers do not have cartridges.
The advancedRocketry.cfg values are set to scrubberRequiresCartrige=true, and oxygenVentConsumptionMultiplier=0.5 (default values for the Enigmatica 2 Light modpack).
Is this working as intended? How quickly should vents consume oxygen without scrubbers vs. with adjacent empty scrubber(s), vs. with cartridge-containing scrubber(s) ?

**Comment by Gliese-832-c** [comment]
Same with the gas charge pad

**Comment by Nomad7** [comment]
One additional update after further testing; I now have a handful of oxygen vent + electrolyser setups in my space station, and I'm seeing at least three different behaviors for what should be identical setups:

- In some cases the vent consumes oxygen slower than the electrolyser produces it. The fluid output hatch eventually fills up and the electrolyser stops running until enough drains that it needs to do another cycle.
- In some cases the vent seems to guzzle down the oxygen in the fluid output hatch faster than it can be produced. However, the pipe from the hatch to the vent never gets drained.
- In other cases the the behavior I described in my previous ticket occurs; the vent guzzles down so much oxygen so fast that i would need a dozen or more electrolysers to have a chance of keeping up with the consumption. 

I'm not seeing any obvious differences between my setup when observing these behaviors - in the event of the rampant oxygen guzzling I seem to usually be able to fiddle with it enough to get it to just insta-draining the fluid output hatch, but I'm not sure how/why. I'm placing the vent and scrubbers in what appears to be the same orientation, in the same order, and getting different results.
I'm sure there's an element of user error at work here, but without knowing the expected results I'm not sure what's broken.

**Comment by Nomad7** [comment]
Based on this conversation it sounds like this may be fixed in recent versions. Now I just need to get the Enigmatica pack folks to update :)

**Comment by zmaster587** [comment]
Fixed in build 180, Mekanism uses a different name for oxygen fluid 9cf779f7a2573de04665745f33f9bb14361d90f1

**Comment by Nomad7** [comment]
Just for the record I also tested this in build 190 and this issue appears to be resolved there; I was able to pipe liquid oxygen from a condensentrator to an oxygen vent without issue.

There does still seem to be some weirdness related to the vent's oxygen consumption - for example it seems like I can attach empty scrubbers to vents and get the same benefits as I would if they had cartridges in them - but this isn't an issue I'm worried about pursuing at this point, especially now that Mekanism-based solutions are available :)
