### ISSUE TITLE
Ore Gen not working

### ISSUE THREAD

**Issue by Conansson** [zmaster587/AdvancedRocketry#1743]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.6.0-188
## Have you verified this is an issue in the latest unstable build
 N

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-68
## Version of Minecraft
1.12.2
## Description of the problem
I am working on a Modpack using Advanced Rocketry as it's core mod. I have created a huge planetDefs file with custom ore generation for each of ~15 custom planets using <oreGen> and </oreGen> under each planet (added my planetDefs file). 
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/3955703/planetDefs.zip)
I disabled all the other ore generation (like cofhWorld) except for advancedRocketry.cfg, because i actually want some random planets with normal advancedRocketry ores. 
When i load up the world, all the ores are spawned in normally. I then went to a Space Station (my modpack starts in Space) and worked there for some time (my ingame time was 3h44). When i teleported back to the planet using /advancedRocketry goto command, all the oreGen was reverted (i only found coal ore/iron ore/ advancedRocketry ores). 

Do i have to disable the oregen in the advancedRocketry.cfg? 
I know that i can use cofH world, but i wanted to use the oreGen this mod offers. If there is no solution, i will have to use cofH world. 
Do you have any other idea? 

Thank you a lot in Advance!

**Comment by Silfryi** [comment]
I'd use CoFH World anyway, as it's much more customizable if you're making your own planetDefs and so know dimension IDs.

**Comment by zmaster587** [comment]
Was it an existing world you tested this on?  If so, it's important to note that AR config changes are not retroactive, so if you loaded some parts of the world before the change, you'd see normal world gen there.  After loading up the world with the change only new areas of the world will contain AR ore gen.  So if you teleported back to the planet to a newly generated chunk, I'd expect there to be AR ore gen there.

Can you verify this is a problem in chunks that are created only _after_ the config change?

**Comment by Conansson** [comment]
I just tried again by creating a new world (the planetDefs config is unchanged), the starting area (a few chunks) is generated normally, then i went to Space, restarted the game and went back to the planet without changing any configs. The chunks that were already generated were the same, but once i flew a few chunks to the distance, it was just Vanilla Stone and ores again.

So yes, i can verify what you asked.
Thanks for your work!

**Comment by Conansson** [comment]
I added two screenshots: In the first, you see the working ore gen (Terracotta and Soul Sand).
The other is on the same world, 290 m away and it is only generating coal ore (not specified in planetDefs) and no terracotta/Soul Sand. The working part was generated when i used /advancedRocketry goto on first joining the planet, the second one, after i restarted the game, left the Dimension and came back. 

![2019-12-13_11 34 07](https://user-images.githubusercontent.com/57071946/70793873-a5ae7900-1d9c-11ea-9db1-0256ba47cfb3.png)
![2019-12-13_11 32 04](https://user-images.githubusercontent.com/57071946/70793869-a1825b80-1d9c-11ea-9a20-ff46c32de564.png)

**Comment by Silfryi** [comment]
Can I see your ore gen configs for Advanced Rocketry and the planetDefs for Advanced Rocketry?

**Comment by Conansson** [comment]
My planetDefs is in my original comment, my main oregen file is unchanged (i think it is just <oreGen> </oreGen>
