### ISSUE TITLE
[Request] Nerf Space Suit

### ISSUE THREAD

**Issue by Conansson** [zmaster587/AdvancedRocketry#1744]
Currently, the Space Suit prevents all damage from low damage sources, which means you can never die to Zombies/Skeletons/spiders while wearing it nor do you take damage standing in magma blocks. This makes the space suit clearly better than diamond armor (you still take some damage from Zombies/Magma blocks) and makes creating an adventure - based pack in space difficult.

**Comment by MrEyeballs29** [comment]
Actually the space suit is same as gold armor so in hard mc difficulty,
skeletons would deal good amount of damage. Therefore it doesn't needed to
be nerfed.

**Comment by Conansson** [comment]
That is not the point i was trying to make with this post. I didn't check gold armor in particular, but i'm sure it doesn't make you invincible to Zombies/unable to take damage from Cactuses/magma blocks...

**Comment by MrEyeballs29** [comment]
Haven't you worn it yet? It only has 5 armor points so most likely the
skeletons will deal around 2 to four damage.

**Comment by zmaster587** [comment]
The space suit isn't supposed to protect that much without a good amount of armor (unobtainable currently) installed in it.
