### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by rhammy49** [zmaster587/AdvancedRocketry#1745]
I have a server with friends running a 1.12.2 mod pack currently. I wanna add this but the 1.12.2 version is labeled as unstable. How unstable is it? They don’t wanna add it because we don’t wanna mess up our world. Thanks.

**Comment by Silfryi** [comment]
The latest alphas are not that unstable, the build system just has them marked as such. There's no serious bugs with them, those builds should be fine.

**Comment by dmodoomsirius** [comment]
Closing this issue as Silfryi answered the question. The builds are mainly bug fixes.
