### ISSUE TITLE
[BUG] - Plate presser breaks lever when pressing block

### ISSUE THREAD

**Issue by BasieBrinkie** [zmaster587/AdvancedRocketry#1746]
## Version of Advanced Rocketry
>1.6.0-188

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>0.4.2-69

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

## Description of the problem
When using the small plate presser with a lever. I can activate it so a block is compressed but once i put the lever back it pops right off along with the final press products.

### Why is this important?
My modpack starts in the asteroid plane so trying to catch the lever every time makes it thougher than it could have been without the breaking lever.

**Comment by Silfryi** [comment]
There's a reason for this because of how MC works, it has to do with where levers can and cannot stay. If you place it next to but not on the plate presser it should work.

**Comment by BasieBrinkie** [comment]
Guess that will have to do
