### ISSUE TITLE
[BUG] Minecraft Crash 1.7.10 

### ISSUE THREAD

**Issue by iFreezinq** [zmaster587/AdvancedRocketry#1747]
My minecraft keeps crashing and i dont know why. 

https://pastebin.com/DxhrRcLL

**Comment by MrEyeballs29** [comment]
Change the dimension number. And also only 1.12 is supported because it
never goes any above alpha. Not to mention all of the versions are alpha
since the first one.

**Comment by Silfryi** [comment]
Yes, somewhere a dimension 31 was already registered. You need to register your dimension to something not 31.
