### ISSUE TITLE
[BUG] Unable to place Lava Buckets in Thermal Expansion (and other modded) Tanks in Low/No pressure AR worlds.

### ISSUE THREAD

**Issue by MuteTiefling** [zmaster587/AdvancedRocketry#1748]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.2-1.6.0-190

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>1.12.2-4.15.0.291

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

>If Y, what is the MINIMUM set of mods required.

>AdvancedRocketry-1.12.2-1.6.0-190-universal.jar	
>CodeChickenLib-1.12.2-3.2.3.358-universal.jar	
>CoFHCore-1.12.2-4.6.3.27-universal.jar	
>CoFHWorld-1.12.2-1.3.1.7-universal.jar	
>jei_1.12.2-4.15.0.291.jar	
>LibVulpes-1.12.2-0.4.2-69-universal.jar	
>RedstoneFlux-1.12-2.1.0.6-universal.jar	
>ThermalExpansion-1.12.2-5.5.4.43-universal.jar	
>ThermalFoundation-1.12.2-2.6.3.27-universal.jar

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>No crash.

## Description of the problem
>Start a new world and go to any planet without a breathable atmosphere. Or just Luna. Place a modded tank in world. Right click with bucket of lava. The noise plays but the lava doesn't go in. Update the block and it will visually show that the lava is there, but this is a lie. Waila and other such mods report no fluid in the tank, no pipes will extract that lava, and right clicking it with a different type of fluid (water, for instance) will overwrite the 'lava' with the new fluid. From that point on, it functions as one might expect. 

>I don't recall this being an issue a few releases back, but I haven't yet had time to load up more than one version prior (build 188). Same issue there.

**Comment by zmaster587** [comment]
Does this occur with non-vanilla fluids?

**Comment by zmaster587** [comment]
Likely related to code preventing lava from being placed on low atmosphere worlds in the rightclick event handler
