### ISSUE TITLE
visible liquid through smoke

### ISSUE THREAD

**Issue by madmichael2004** [zmaster587/AdvancedRocketry#175]
whenever something launches from the launch pad the smoke left behind lets liquids be visible. modded and not ( except lava)

**Comment by zmaster587** [comment]
Sadly this is a bug with the way vanilla  handles transparency and liquids,
supposedly it was patched in newer versions of Minecraft, it would be
possible for me to fix however it would require me to modify a lot if code
in vanilla and I'm not sure is really worth the effort

**Comment by bludde** [comment]
damn and here i made a beautiful video to show the effect:) https://youtu.be/ezTufxDBL94

**Comment by zmaster587** [comment]
If it's not fixed in 1.10 I may patch it.  I'll see if I can find a quick
fix for 1.7, but I'm not confident I'll be able to

**Comment by zmaster587** [comment]
Sadly does not appear to be fixed in 1.10, it would still be way to much work for me to fix this.  Honestly this is more of a forge/mojang problem anyway.  Closing.
