### ISSUE TITLE
[BUG] Infinite tank of rocket fuel if inventory is full

### ISSUE THREAD

**Issue by AzazazChannel** [zmaster587/AdvancedRocketry#1750]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.6.0-190-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-69-universal

## Version of Minecraft
>1.12.2 + forge 14.23.5.2838

## Does this occur without other mods installed
- [x] N

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>No crash

## Description of the problem
>If your inventory is full, when you Shift+Right click rocket while holding _**tank of rocket fuel**_, rocket is fueling, but tank doesn't disappear and you can fuel your rocket again and again.

**Comment by dmodoomsirius** [comment]
What kind of tank’s have you tried this with?

**Comment by AzazazChannel** [comment]
I've tried only with usual fuel can from AR

**Comment by zmaster587** [comment]
Fixed for next update, thanks for reporting this edgecase!
