### ISSUE TITLE
[BUG]Advanced rocket disappears when landing on spacestation

### ISSUE THREAD

**Issue by DarthCY-K** [zmaster587/AdvancedRocketry#1752]
## Version of Advanced Rocketry
>1.6.0-191-universal

## Have you verified this is an issue in the latest unstable build
- Y

## Version of LibVulpes
>0.4.2-69-universal

## Version of Minecraft
>1.12.2-forge-14.23.5.2847

## Does this occur without other mods installed
- Y

## Crash report or log or visualVM (if applicable)
>https://paste.ubuntu.com/p/T9WTdKJ5WN

## Description of the problem
>I had found a problem when the rocket nearly landing on spacestation, it just disappered and leaving me alone in the air of space.
But the rocket was not "disappered", there are some air walls(something that i can not pass through) and it had the shape of my rocket.
After i restarted my server, something strange happend, my rocket appeared at the location of the air walls.
This happends everytime when i landing on the spacestation or the earth in my server, but does not happend in singleplayer mode.

**Comment by NBTPXX** [comment]
well,faced with the same problem XD

**Comment by DarthCY-K** [comment]
> well,faced with the same problem XD

seems some people have the same problem
