### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by sossololpipi** [zmaster587/AdvancedRocketry#1753]
It would be amazing to allow multiple seats to be used on one rocket allowing players to go to space at the same time.

**Comment by MrEyeballs29** [comment]
That is already a feature.

**Comment by dmodoomsirius** [comment]
Correct that was added almost 6 months ago.

**Comment by sossololpipi** [comment]
I was confused at first because I couldn't choose the seat on my rocket. Tested with another player and it is indeed a feature.
