### ISSUE TITLE
don't know what's wrong with custom planetdefs.xml

### ISSUE THREAD

**Issue by NotCoolKiwi** [zmaster587/AdvancedRocketry#1757]
## Version of Advanced Rocketry
>[AdvancedRocketry-1.12.2-1.6.0-188-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [] N
- [] N/A

## Version of Minecraft
>[1.12.2

## Does this occur without other mods installed
- [] Y
- [x] N
- [] N/A

## Description of the problem
>Please help me with this planetdefs.xml. It says something wrong with the format I think. Reproduce it by running AR with this planetdefs.xml. I have used (http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/AdvancedPlanetConfiguration.php) to help me. file is at (https://pastebin.com/3NDcnZK8).

**Comment by NotCoolKiwi** [comment]
Not actually a bug, It's something i'm doing wrong

**Comment by NotCoolKiwi** [comment]
I might have just figured this out?

**Comment by NotCoolKiwi** [comment]
Nope! i fixed one thing,but there are still other problems. I have changed the paste link to he new one.

**Comment by zmaster587** [comment]
It looks like you have two galaxy tags, there can only be one.  Also as a helpful hint, you can run it through https://www.xmlvalidation.com/ and it will tell you if there's any format errors.

**Comment by NotCoolKiwi** [comment]
Thank you so much, you are awesome!
