### ISSUE TITLE
crash on bootup

### ISSUE THREAD

**Issue by LegoArtcher** [zmaster587/AdvancedRocketry#1760]
## Version of Advanced Rocketry
1.7.10
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.10.2
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
just pressing play on the Minecraft launcher

**Comment by MrEyeballs29** [comment]
There is no logs or crash reports

**Comment by LegoArtcher** [comment]
There was no report

**Comment by MrEyeballs29** [comment]
Then look at the logs in the launcher.

**Comment by LegoArtcher** [comment]
https://paste.ubuntu.com/p/bmt38GbKKp/

**Comment by MrEyeballs29** [comment]
That seems like the error might not be related to this mod.

**Comment by LegoArtcher** [comment]
what do you think caused the error?

**Comment by Silfryi** [comment]
Is that it? That's just a log of files with no hashes, and so no checks. I need something more to be able to diagnose.

**Comment by LegoArtcher** [comment]
like what?

**Comment by MrEyeballs29** [comment]
An actual game log and the crash report

**Comment by LegoArtcher** [comment]
how do I get that info?

**Comment by MrEyeballs29** [comment]
Find the lastest.log and the crash-report.txt file and paste them in
pastebin.

**Comment by LegoArtcher** [comment]
https://paste.ubuntu.com/p/45dMKWtCCv/ that is the latest.log

**Comment by MrEyeballs29** [comment]
Huh. This needs some further investigation

**Comment by LegoArtcher** [comment]
oops wrong log
let me get the right one

**Comment by LegoArtcher** [comment]
https://paste.ubuntu.com/p/fsbzNyKNpV/ this is the right log

**Comment by dmodoomsirius** [comment]
You are using a 1.7.10 version of the mod. 
https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/2864309
https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/2841976

**Comment by LegoArtcher** [comment]
still crashing https://paste.ubuntu.com/p/PSbJY4hGFK/ in game
https://paste.ubuntu.com/p/7q2fn5tz6r/ latest.log

**Comment by MrEyeballs29** [comment]
What version of minecraft are you using?

**Comment by MrEyeballs29** [comment]
Omg never mind

**Comment by LegoArtcher** [comment]
why?

**Comment by dmodoomsirius** [comment]
looking at the report i can see you are using a version of Advanced Rocketry from 1.7.10. update to the version's i linked above. and it ill fix your issue.

**Comment by LegoArtcher** [comment]
I did

**Comment by dmodoomsirius** [comment]
did that fix your issue?

**Comment by LegoArtcher** [comment]
no
 https://paste.ubuntu.com/p/PSbJY4hGFK/ in game
https://paste.ubuntu.com/p/7q2fn5tz6r/ latest.log

**Comment by dmodoomsirius** [comment]
You downloaded the deobf version which is for Developers. the one i linked i the correct one. just click download do not scroll down.

**Comment by LegoArtcher** [comment]
that worked.Thanks!

**Comment by dmodoomsirius** [comment]
Great. i am now closing the issue.

**Comment by MrEyeballs29** [comment]
Don't download incorrect minecraft version or the developer only files. It
will crash your game.
