### ISSUE TITLE
Conflicting with Thermal Foundation

### ISSUE THREAD

**Issue by Zunfix23** [zmaster587/AdvancedRocketry#1762]
## Version of Advanced Rocketry
1.6.0
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.4.2
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
None

## Description of the problem
Pretty much i cant build iron frames cause its the same as thermal foundations gears

**Comment by MrEyeballs29** [comment]
Can you explain the steps on how there is a conflict.

**Comment by Zunfix23** [comment]
So when i put the 4 pieces of iron in the crafting table it shows a gear when i want it to be a iron frame

**Comment by Silfryi** [comment]
Iron Frame?

**Comment by Zunfix23** [comment]
Nevermind i guess i was looking at a item from advanced generators sorry
