### ISSUE TITLE
Precision Assembler only makes Bionic Leg upgrades from recipes like Padded landing boots

### ISSUE THREAD

**Issue by Teslakoyal** [zmaster587/AdvancedRocketry#1763]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>Advanced Rocketry 1.12.2-160-197

Seems the Precision Assembler has 2 different recipes for the bionic legs upgrade, any recipe containing the simple version of the recipe, Advanced Circuit and Control Circuit Board, the assembler will pull just those 2 items and make the bionic upgrade not the intended item.

I have tried it with the Padded Landing Boots, Anti-Fog Visor, and the Flight Speed Control Upgrade

**Comment by Silfryi** [comment]
Delete your recipe XMLs and try reload, does that change the recipes/fix the issue?

**Comment by Teslakoyal** [comment]
yes that fixed it, I added Advanced Rocketry at the on set of making my pack so not sure why it gave me both recipes, but thanks for the assistance :)

**Comment by Silfryi** [comment]
Because there was a bug with how XMLs were generated at some point, and you hit that. Can you close the issue now?

**Comment by Teslakoyal** [comment]
Yes, sorry didnt see the close and post button. Thanks again for the rapid assistance :-)
