### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ParasiticSquid** [zmaster587/AdvancedRocketry#1764]
## Version of Advanced Rocketry
Ive tested between all versions between 1.12.2-1.6.0-190 to 1.12.2-1.6.0-199

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
Ive tested versions 1.12.2-0.4.2-69 to 1.12.2-0.4.2-71 build

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N/A
I haven't had time to test with just advanced rocketry and libvulpes but it definately occurs without fail in the enigmatica 2 expert modpacks in versions 1.72, 1.74, 1.75, and 1.76a if that helps.

## Crash report or log or visualVM (if applicable)
None since it doesn't crash, just doesn't work properly.

## Description of the problem
Simply enable terraforming and terraform a planet any amount on a server and then restart the server, suddenly all atmosphere is reset to the planets original after the restart and is no longer breathable if it was post terraforming. Even weirder is torches placed after terraforming but before the restart will act like there's still a breathable atmosphere until they're replaced. From what ive seen the changes aren't saving to the temp.dat at all even though it's not read only, even if I manually change the planets NBT data in temp.dat it still resets to the planets default on server startup or restart. Doubt it's another mod causing it since no other mods on a enigmatica 2 expert server should be touching the worlds temp.dat or preventing the saving of NBT data in said file for obvious reasons.

Torch burning and emiting light with no atmosphere due to terraforming issue after server restart:
https://i.imgur.com/vwZUG8t.png

**Comment by zmaster587** [comment]
Investigating

**Comment by zmaster587** [comment]
I suspect it's related to some changes that were made in how planets got loaded, it used to be they were loaded primarily from the temp.dat, which  contains technical data the planetDefs.xml doesn't have, like terraforming info.  Now it's loaded from the XML and some values are copied back from the temp.dat, so im wondering if it's related

**Comment by zmaster587** [comment]
Should hopefully be fixed by 7aa5298c7f3a94ae33cf9b4dd5030cda10e75448
