### ISSUE TITLE
[BUG] Fillerblock tag overrides Biome surface blocks

### ISSUE THREAD

**Issue by Dr-Ergmern** [zmaster587/AdvancedRocketry#1768]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-202-universal.jar

## Have you verified this is an issue in the latest unstable build
- N/A

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-74-universal.jar

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- N/A

## Description of the problem
> When using the Filler Block Tag in PlanetDefs.xml, it overrides the Upper layers of the defined biomes. This results in barren looking planets where the surface material is identical to that of the underground material. When the Filler Block tag is not used, the top layers of the biomes behave correctly but the below surface blocks default back to stone etc. (essentially basic overworld generation) which can appear somewhat unrealistic with some of the chosen biomes (in this case custom planetary biomes). I have linked two photographs below demonstrating the issue.

Surface when not using the filler tag: https://prnt.sc/r0e53g
Surface when using the filler tag: https://prnt.sc/r0ea4r

**Comment by Silfryi** [comment]
Can't be fixed, vanilla MC behavior. Use BiomeTweaker to rectify if you absolutely need to.

**Comment by Dr-Ergmern** [comment]
If there was a Surface Block parameter would this not rectify the issue?

**Comment by Silfryi** [comment]
Maybe? It has other problems, I'll link you the BiomeTweaker article here:https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Block-Replacement . It requires some ASM and more complicated things. There's already utilities within BT for that, so there's a smaller use for it.
