### ISSUE TITLE
[BUG] Bimoes O Plenty issue

### ISSUE THREAD

**Issue by LordRocket1988** [zmaster587/AdvancedRocketry#1769]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>[most recent 

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build yes 
- [x] Y
- [x] N
- [x] N/A

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
>[latest 

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
>[1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- [x] no 
- [x] 
- [x]
>If Y, what is the MINIMUM set of mods required.

>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>[insert here

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
>[AdvancedRocketry planets don't seem to allow any plants or trees to grow on single biome biomes o plenty worlds 

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by Silfryi** [comment]
Is there atmosphere 75<atmpressure<125? Is this an Advanced Rocketry created dimension?

**Comment by MarkOfTheBeast** [comment]
I've seen this myself. When I was testing out my code in a superflat test world, no trees would show up when BOP biomes were used on a planet. This only occurred in superflat worlds. When I played a normal game in a world generated by climatic biomes, the planets had trees on them and the biomes generated normally.


Did you originally experience this on a superflat world? If so, try it with a different world type.
