### ISSUE TITLE
Config for particles in warp

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#177]
i f*cked up, i built my ship the wrong way, now it travels at warp sideways.
https://youtu.be/1-Vy3J7CNIQ
is it possible to change the warp way with some sort of config?

**Comment by zmaster587** [comment]
The warp controller determines the direction of the ship, if break it and place it so the back is facing the front the warp effect should change direction accordingly

**Comment by bludde** [comment]
Ahhh worked perfecly,
(Thanks ill get a full tour up when its done, gonna be a roleplaying adventuremap for some friends:))
