### ISSUE TITLE
[BUG] Gas Tag doesn't work with Thermal Foundation Fluids

### ISSUE THREAD

**Issue by Dr-Ergmern** [zmaster587/AdvancedRocketry#1770]
Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-202-universal.jar

Have you verified this is an issue in the latest unstable build?
N

Version of LibVulpes
LibVulpes-1.12.2-0.4.2-74-universal.jar

Version of Minecraft
1.12.2

Does this occur without other mods installed?
N/A

Description of the problem
The Gas Tag in PlanetDefs.xml doesn't appear to work with fluids from Thermal Foundation. Whenever I set the fluid to "thermalfoundation:fluid_cryotheum" (the correct fluid id for gelid cryotheum) or "fluid_cryotheum" (non-localised) or just "cryotheum", and I load up a new world, the PlanetDefs for that world changes it to one of the Advanced Rocketry fluids: oxygen, hydrogen, nitrogen etc, instead of the fluid I set it to in the main config. I haven't tested this with other mods fluids.

**Comment by Silfryi** [comment]
That's the wrong ID. If you have crafttweaker, do `/ct fluids` or `/ct liquid`, it's one of those that prints the fluid registry to your CT log. That's where you get fluid IDs, not the block ID of the fluid.

**Comment by Dr-Ergmern** [comment]
> That's the wrong ID. If you have crafttweaker, do `/ct fluids` or `/ct liquid`, it's one of those that prints the fluid registry to your CT log. That's where you get fluid IDs, not the block ID of the fluid.

As it happens the time I just put cryotheum in initially it must have been a typo, now working as intended.
