### ISSUE TITLE
rocket assembling gui dont work

### ISSUE THREAD

**Issue by dzh121** [zmaster587/AdvancedRocketry#1774]
## Version of Advanced Rocketry
>1.10.2

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>1.10.2

## Version of Minecraft
>1.10.2

## Does this occur without other mods installed

- [x] N/A

## Description of the problem
>im on a server when im trying to open the rocket assembling mechine the gui dont work. i tryed aslo on singelplayer on the same version

**Comment by Silfryi** [comment]
Can I see an image? Can you see the GUI at all? Does it open? What do you mean by "not work"?
