### ISSUE TITLE
[BUG] Can't open Biome Changer Remote 

### ISSUE THREAD

**Issue by turret001** [zmaster587/AdvancedRocketry#1782]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>[1.6.0-190]

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>[0.4.2.-69]

## Version of Minecraft
>[1.12.2!]

## Does this occur without other mods installed
- [x] N/A

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>[insert here

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
>[After launching my biome changer satellite and scanning my first biome (Origin Islands biome from BoP) I was able to change the biome of the place I was living, however when I went out and tried to scan a second biome (Woodlands biome probably from BoP as well) remote gui stopped working. I can still change the biome to Origin Island but I can't open the GUI anymore. Another weird thing is whenever I open some Advanced Rocketry GUIs (like Rocket Monitoring station) my inventory shows up blank but when I press 'R' to tidy my inventory (Inventory Tweaks), items come back. I'm running this mod on ATM 3 Remix modpack.]

**Comment by turret001** [comment]
update, launched a second biome changer satellite and it worked just fine (GUI as well) but after picking up the 'bugged' remote, new remote GUI stopped opening as well.

**Comment by zmaster587** [comment]
Do any errors show up in the log when you right click it?

**Comment by turret001** [comment]
oddly enough, it works now. I guess bug was caused because I tried to use first remote on Lost Cities dimension, not sure tho. (satellite were launched from that biome as well.)
