### ISSUE TITLE
[BUG] Space Elevators go up not down on a return trip to a planet

### ISSUE THREAD

**Issue by StargateMC** [zmaster587/AdvancedRocketry#1783]
This sounds silly, but the space elevator should go downwards when in space. 
Unless Im missing something?

**Comment by zmaster587** [comment]
I'm not sure I follow.  Can you describe what is happening and what you expect to happen? (There are cases when an elevator is supposed to go upward in space, such as when taking a return trip to a planet from a space station.  It wouldn't make sense if you were taking a return trip to a station from a planet and you teleport to the station then the elevator goes up.)

Version information?  (for all I know, this might have been already fixed)

Are other mods installed? (for all I know, you have some mod that modifies entity movement, like a directional gravity mod)

**Comment by StargateMC** [comment]
When you are leaving a station you travel upward, not down toward the planet.
Its an aesthetic thing, really. Not that important.

I am running the latest version of AR on 1.12.2.
