### ISSUE TITLE
Atmosphere Terraformer not working!!

### ISSUE THREAD

**Issue by KrAzYGEEK32** [zmaster587/AdvancedRocketry#1785]
## Version of Advanced Rocketry
1.6.0-197
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
0.4.2-69
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
Done everything. Formed the structure, powered it, added both fluids, two liquid oxygen(mekanism), two nitrogen(nuclearcraft). Sent a biome changer satellite from the planet( Mars).put the biome remote. Still says not running. What did I do wrong? Or is it still bugged?

**Comment by Silfryi** [comment]
Have you enabled it in the config?

**Comment by KrAzYGEEK32** [comment]
Not at first. But after seeing this comment I went through the whole config file for anything terraformer related. I enabled them all( whatever is required). Then it said "ran out of gasses" ( I guess the issue here is it's trying to detect both oxygen and nitrogen from the same fluid input (or) mekanism liquid oxygen isn't supported). Then I disabled gas requirement in the config. This time it started to say "not running" again, but the progress bar started up. the whole machine animation was also not playing to show that it was running.i waited for 5 min (I made its soeed to 4x) with no change.

**Comment by Silfryi** [comment]
Hmm. Yeah, IIRC Mekanism oxygen is not supported. Try re enabling gas useage and running with AR oxygen and nitrogen. Also, were you on an Advanced Rocketry world? Did you provide enough power?

**Comment by dmodoomsirius** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1740#issuecomment-562873084

**Comment by KrAzYGEEK32** [comment]
I'm providing it with more than enough power and I'm trying it on mars

**Comment by KrAzYGEEK32** [comment]
And enabling gases and using ar oxygen won't help I think. I'm doing it in survival and I dunno how to get AR oxygen😅. It wouldn't work anyway coz it didn't work with gases disabled

**Comment by WywySenariosa** [comment]
I have the same issue using mekanism oxygen and nuclearcraft nitrogen. I fixed it by using AR oxygen and nitrogen. But I want to use nuclearcraft's because nitrogen is so hard to get
