### ISSUE TITLE
World generation noise is disconnected from the biome map, causing really bad world generation.

### ISSUE THREAD

**Issue by Gliese-832-c** [zmaster587/AdvancedRocketry#1787]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-208-universal.jar

## Have you verified this is an issue in the latest unstable build
As stated above, I am using the as of the 14th march 2020 latest build, 1.7.0-208.

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-74-universal.jar

## Version of Minecraft
1.12.2-forge1.12.2-14.23.5.2847

## Does this occur without other mods installed
Yes, it does.

## Description of the problem
If I input several biomes, the vertical and horizontal noise scaling gets mixed. Like, if I have a plains biomes which uses dirt blocks, and a hills biome which uses granite blocks, dirt blocks will spawn in the hills biome and granite blocks will spawn in the plains biome. The vertical and horizontal scaling seem to be uncoupled from the biome. This means that only single biome planets make sense, or planets with biomes with the same biome height generation. It also makes creating modpacks with custom planets really really hard.

This has been a thing for many versions now. The only solution would be to use some kind of external dimension mod and dimmap it, but 1. you would loose the custom skybox that way, and 2. afaik there are no such mods, to my knowledge JED can't do that. And even if it could, it would still be a bandaid fix, it should be in AR by default.

If you don't know what I mean, here's an example:
(disregard the wrong blocks please, that's an issue with BiomeTweaker)
![2020-03-14_19 22 22](https://user-images.githubusercontent.com/55159077/76689401-e46efc00-6635-11ea-92f7-251732bc6bbc.png)

There are 4 biomes assigned to this planet (Mars) currently. Mars Plains, Mars Mountains, Mars Canyons, Mars Poles. In this case, as JourneyMap currently shows it, I'm in the Mars Poles biome. It's a custom BiomeTweaker biome, but it's based off of the plains biomes. It doesn't look like plains in the slightest. The vertical scaling is way too extreme...I don't need to explain how this isn't a plains biome.
Also, I am 100% sure that it's not a BiomeTweaker bug; it happens with vanilla, BOP and biomes from other mods too.

[A similar bug report](https://github.com/zmaster587/AdvancedRocketry/issues/1471) seems to exist already, but it's very old and has no replies besides an automated github reply telling that it is, indeed, an old thread.
While I usually am against duplicate bug reports, because they create more clutter, this is an exception; it's a bug that needs urgent fixing, because it removes the ability for modpack devs to be able to create good custom planets.

This needs to be fixed as quickly as possible.

**Comment by zmaster587** [comment]
This seems like a really bizzare issue.  I've created a ton of planets with multiple biomes and have never run into anything like this save a few bugs with the terraformer.
Can you replicate this with vanilla biomes and without biome tweaker?

**Comment by C1ffisme** [comment]
I've mentioned this before in the linked issue with a world that uses only ocean, mushroom islands and mushroom shore, but I can test this with the latest version if you'd like

**Comment by C1ffisme** [comment]
```
<planet name="Ross 128 b" customIcon="EarthLike">
			<isKnown>false</isKnown>
			<orbitalDistance>90</orbitalDistance>
			<orbitalTheta>20</orbitalTheta>
			<orbitalPhi>40</orbitalPhi>
			<skyColor>0.7,0.8,0.1</skyColor>
			<fogColor>0.7,0.8,0.2</fogColor>
			<atmosphereDensity>120</atmosphereDensity>
			<rotationalPeriod>250000</rotationalPeriod>
			<gravitationalMultiplier>110</gravitationalMultiplier>
                        <biomeIds>minecraft:mushroom_island,minecraft:mushroom_island_shore,minecraft:ocean</biomeIds>
			<OreGen>
				...
			</OreGen>
		</planet>
```

![2020-03-25_08 30 34](https://user-images.githubusercontent.com/9893266/77541833-3eac6000-6e73-11ea-80fb-5d91297c7017.png)
Testing with Advanced Rocketry 1.7.0-208 for 1.12.2 and LibVulpes 0.4.2-74.

It should be noted that beyond oceans there are a lot of biomes that have an effect on height in Vanilla Minecraft like Extreme Hills, Plains, Swamps, etc.

I did have Biome Tweaker installed, but it shouldn't be doing anything theoretically as I haven't configured any biomes. Just in case, however, I decided to run a second test without Biome Tweaker or Biomes O' Plenty.

![2020-03-25_08 50 28](https://user-images.githubusercontent.com/9893266/77543484-c3987900-6e75-11ea-8a6c-16f917c78bf2.png)

Well, the good news is that AR is compatible with Biomes O' Plenty I guess.

(Offtopic but, the biomes on this planet seem really small for some reason. I feel like the ability to customize some biome noise parameters would be nice just so when you're making a planet with oceans you don't get tiny little lakes of Deep Ocean)

**Comment by zmaster587** [comment]
![image](https://user-images.githubusercontent.com/3536685/77609009-23823480-6ef5-11ea-9916-ee0796064c59.png)

This.. uh... might be related.

**Comment by zmaster587** [comment]
Nvm, I remember why now
![image](https://user-images.githubusercontent.com/3536685/77609351-1fa2e200-6ef6-11ea-9bc1-7229211b5acc.png)

**Comment by zmaster587** [comment]
Narrowed the issue down to `ChunkProviderPlanet` somewhere.  Confirmed it's not `ChunkManagerPlanet`

**Comment by zmaster587** [comment]
`getBiomesForGeneration` vs `getBiomes` RIP.

It's fixed now so whatever.
