### ISSUE TITLE
[BUG] null crash

### ISSUE THREAD

**Issue by runescapejon** [zmaster587/AdvancedRocketry#1789]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-208

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
>[insert here

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
 LibVulpes-1.12.2-0.4.2-74

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- [x] Y
- [ ] N
- [ ] N/A
>If Y, what is the MINIMUM set of mods required.
Only 2 just Advanced Rocketry and LibVulpes
>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/raw/2ePz3mT5

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
This issue happen when you have both mods installed and you can join a normal vanilla server without the mods installed. Or even if the mods are installed onto the server it still crash it but only randomly. It also happen when the server is rebooting and players attempt to join in the middle of a reboot, yeah it happen again also.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]
It's easy to reproduce and the quick way to recreate the issue is to have the mods installed that is Advanced rocketry and Libvulpes and just join a vanilla server that is the quickest way to reproduce. Bare in mind this issue happen even if the mods are installed onto the server but only random.

**Comment by Exaxxion** [comment]
One of my users on the Omnifactory Discord reported a crash that appears to be the same as this one. Here's their provided log, if it helps:

[Crash Log](https://cdn.discordapp.com/attachments/564248854363635722/702033512001437696/crash-2020-04-21_17.49.02-client.txt)

**Comment by zmaster587** [comment]
Can either of you provide a step by step process on how to reliably replicate the issue? 
I've tried connecting to a vanilla server a few times in a row.  I was able to log in and walk around successfully each time.

I have also tried connecting to a modded minecraft server while it's starting up a few times in a row.  Then connecting to the server after it's starting up and teleported around to different planets a few times.  Nothing abnormal occured.

**Comment by zmaster587** [comment]
The crash report itself looks like the solar system the player is in is nonexistant or the overworld's star is non-existant.  But I have no idea how that could happen during normal gameplay or even when connecting a few times.

**Comment by runescapejon** [comment]
I'll go into detail on how i am able to reproduce consistently.
 
`How to reproduce`
1) download the official vanilla server here https://www.minecraft.net/en-us/article/minecraft-1122-released
2) put the server.jar into a folder and run `java -jar server.jar`
3) have a forge client with forge version 14.23.5.2854 
4) installed the mods 
`AdvancedRocketry-1.12.2-1.7.0-209-universal`  & `LibVulpes-1.12.2-0.4.2-74-universal`
5) connect to the server with `localhost`
6) You will instantly crash.

This is the best method that i am able to reproduce. Please let me know if you need more detail or any other information. As always thank you for looking into this. <3

**Comment by zmaster587** [comment]
Thanks!  I'll give it a shot!

**Comment by zmaster587** [comment]
Not entire sure why I couldn't replicate it with the forge versions/server jar I was using, but it does seem to be the result of the client not having the fallback star setup properly.

It'll still error, as this issue is a result of the server not sending data required to setup planets, but it should no longer crash and just display a default sun instead now.
