### ISSUE TITLE
How to fuel a space station?

### ISSUE THREAD

**Issue by SureLucky12** [zmaster587/AdvancedRocketry#1790]
Sry, but i got a Question. How can I fuel my space station. I got about 60 fuel and wanted to fly back to the earth but I cant because I have to low fuel. Does anyone now how to fuel the space station?

**Comment by Silfryi** [comment]
You need dilithium crystals, input into the top of the warp core.

**Comment by MrEyeballs29** [comment]
Currently there is a bug where normally needs 2 but it consumes a stack.

**Comment by SureLucky12** [comment]
Thanks Guys
