### ISSUE TITLE
[BUG] Skyboxes on dimMapped planets are incosistent

### ISSUE THREAD

**Issue by brom10** [zmaster587/AdvancedRocketry#1794]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-209

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-74-universal

## Version of Minecraft
>1.12.2

## Description of the problem
When creating dimMapped planets, if you arrive in the dimension by rocket then the custom skybox is visible, as seen here with the end dimension as an example. 
![image](https://user-images.githubusercontent.com/21183477/77830201-4aab5280-70fd-11ea-9e68-de6fd2b5e387.png)

However, upon a re-log OR if visiting the dimension by other means such as the goto command or a portal or some other mods teleportation, only the default skybox is shown
![image](https://user-images.githubusercontent.com/21183477/77830262-bbeb0580-70fd-11ea-9712-87664754f32f.png)
Flying in a rocket, even if returning to the same planet, does seem to reset the skybox back to the custom AR one immediately. 
![image](https://user-images.githubusercontent.com/21183477/77830324-11271700-70fe-11ea-8afa-3aab0bbf7316.png)

**Comment by MrEyeballs29** [comment]
That should not be allowed for other vanilla dimensions especially the
nether and the end. The overworld is fine since it always uses the AR
skybox no matter what.

**Comment by brom10** [comment]
Well I do have the planet sky override set to true, so I would expect that skybox to work on any dimension that I have dimMapped to a planet. The end isn’t the dimension I am trying to get it to work with though, just a test I did to verify that it was advanced rocketry and not the mod that added the dimension

**Comment by brom10** [comment]
Soooo whether or not custom skybox is supposed to appear in dimMapped dimensions or not, it isn’t consistent, so this is still a bug right? Also I would think that it is supposed to show the custom skybox all the time, based on the planet sky override option
