### ISSUE TITLE
Because I can't figure out how to suggest a commit -_-

### ISSUE THREAD

**Issue by Storm-HF** [zmaster587/AdvancedRocketry#18]
I did a ru_RU.lang file (russian) as best I could, I'm fairly sure it's all correct, but I haven't spoken the language in a good year or so.

http://pastebin.com/DQFKXEu2

**Comment by zmaster587** [comment]
Thank you!  And as for suggesting a commit, it's fork -> modify/add whatever change you want, then pull request.
