### ISSUE TITLE
warp particles not showing in AR 0.6.8

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#180]
When traveling at warp after update the particles are not showing after update to newest version.
https://www.youtube.com/watch?v=0k1m_MNB_hg

**Comment by zmaster587** [comment]
Does it persist after a second time through warp or after breaking and replacing the warp controller?

**Comment by bludde** [comment]
second jump dont fix, but after break and replace it work again.
https://youtu.be/h2nHpxdTWbE
(ill let you close this one:))

**Comment by bludde** [comment]
too slow:D
