### ISSUE TITLE
[BUG]Server crash when going to planet

### ISSUE THREAD

**Issue by MarkOfTheBeast** [zmaster587/AdvancedRocketry#1800]
## Version of Advanced Rocketry
>[AdvancedRocketry-1.12.2-1.7.0-209-universal.jar

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build

- [x] N/A: don't see a later build

## Version of LibVulpes
>[LibVulpes-1.12.2-0.4.2-74-universal

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
>[1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- [x] Y: Only with AR and libvulpes

>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read

https://pastebin.com/ecvqwB3z

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
Server crash when I try to fly to a planet. Can't find a problem with the code

        <planet DIMID="4" name="Venus">
            <isKnown>false</isKnown>
            <fogColor>1.0,0.75,0.0</fogColor>
            <skyColor>1.0,0.75,0.0</skyColor>
	    <gravitationalMultiplier>65</gravitationalMultiplier>
            <orbitalDistance>60</orbitalDistance>
            <orbitalPhi>180</orbitalPhi>
            <rotationalPeriod>4224000</rotationalPeriod>
            <atmosphereDensity>200</atmosphereDensity>
            <generateCraters>true</generateCraters>
            <generateVolcanos>true</generateVolcanos>
            <generateStructures>false</generateStructures>
            <generateGeodes>true</generateGeodes>
            <biomeIds>advancedrocketry:hotdryrock,advancedrocketry:volcanic</biomeIds>
            <oceanBlock>minecraft:lava</oceanBlock>
        </planet>

**Comment by Silfryi** [comment]
You have craters on and too high of an atmosphere, the crater function can't handle it. For now, change one of the two.
