### ISSUE TITLE
[BUG] zero gravity on Earth 

### ISSUE THREAD

**Issue by cytor67** [zmaster587/AdvancedRocketry#1804]
## Version of Advanced Rocketry
[1.12.2-1.7.0-209 build -209 ]
## Have you verified this is an issue in the latest unstable build
 N/A
## Version of LibVulpes
[1.12.2-0.4.2-74 build -74 ]
## Version of Minecraft
[1.2.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
[How can you reliably reproduce the problem]
When I launch into space my rocket disappears and I have to do /kill as I'm stuck and can't fly ever and when I respawn there is no gravity and I just float off  so  I have to exit the game to fix the gravity but it dose not fix anything else I still get stuck in space

**Comment by Gliese-832-c** [comment]
Take a look at your planetDef.xml's Earth, if the gravitationalMultiplier is at 0, set it to 100.

**Comment by dmodoomsirius** [comment]
after editing what @Gliese-832-c said please upload the planetdefs.xml from the world's folder to gist.github.com or pastebin please.
