### ISSUE TITLE
[BUG] No way to disable BiomeID assignments

### ISSUE THREAD

**Issue by croftyraider** [zmaster587/AdvancedRocketry#1807]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.12.2-1.7.0-209

## Have you verified this is an issue in the latest unstable build
No (N/A)

## Version of LibVulpes
1.12.2-0.4.2-74

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
No, but see below.

## Crash report or log or visualVM (if applicable)
Description: Exception in server tick loop

java.lang.RuntimeException: Tried to register biome openterraingenerator:overworld_frozen_forest to a id 53 but it is occupied by biome: advancedrocketry:volcanic. This can happen when using the CustomBiomes setting in the world config or when changing mod/biome configurations for previously created worlds. OTG 1.12.2 v7 and above use dynamic biome id's for new worlds, this avoids the problem completely.

## Description of the problem
So what's going on is I'm trying update a modpack I'm playing (OminiFactory) and I've been using BiomeBundle (which uses OTG) for my overworld terrain generation. All has been well until the pack updated to use the latest? very recent? version of advanced rocketry and apparently this version registers some biome IDs causing the shown exception when trying to load my world (a copy fortunately). The older version of OmniFactory used 1.12.2-1.5.0-139 and that version didn't conflict with BiomeBundle/OTG (as far as I could tell...)

Looking at the config file there doesn't seem to be a way to prevent advanced rocketry from assigning it's biome id's or remapping them...

I would be happy to be proved wrong so I can update the pack.

**Comment by Silfryi** [comment]
There's nothing we can do and nothing they can do other than some very specific stuff on their end that's unlikely to happen. Short answer is you're stuck on that version because of the quirks of how BiomeBundle and OTG do their generation & biomes as it says in the log.

**Comment by croftyraider** [comment]
Dang. Thanks for answering.
