### ISSUE TITLE
Space station assembler not working

### ISSUE THREAD

**Issue by BramDeCreep** [zmaster587/AdvancedRocketry#181]
Whenever i place a space station assembler next to the launch pads it says nothing here am i doing something wrong or is it a bug?

My Setup
![setup](https://cloud.githubusercontent.com/assets/21101377/17770937/ba0b7dd4-6540-11e6-94d1-0f4f6d08a1af.png)

**Comment by bludde** [comment]
It will say nothing there until you scan it the first time. so just try scan and see if that works?

**Comment by BramDeCreep** [comment]
Whenever i click scan nothing happens and whenever i click build it consumes the items but doesnt do anything

**Comment by TheGuyRunningSouth** [comment]
Do you have an uprogrammed  space station chip and a satellite bay in the
assembler?

**Comment by BramDeCreep** [comment]
yes

**Comment by zmaster587** [comment]
even after hitting scan it still says "nothing here"?

**Comment by BramDeCreep** [comment]
yes and the scan wont start

**Comment by zmaster587** [comment]
Replicated, investigating

**Comment by zmaster587** [comment]
You have a satellite hatch in the top left and an unprogrammed station ship in the top right?

**Comment by BramDeCreep** [comment]
if you mean satellite bay then yes

**Comment by zmaster587** [comment]
are you on a server or single player?

**Comment by BramDeCreep** [comment]
singleplayer

**Comment by zmaster587** [comment]
is the power bar full?  and does it persist through a game restart?

**Comment by BramDeCreep** [comment]
Reinstalled minecraft and updated forge it seems to work now? but the bar was full and i dont understand what you mean with persist (im dutch)

**Comment by zmaster587** [comment]
does it keep happening after restarting, but i guess you answerd that.  What verion of forge were you using before and what did you update to?

**Comment by BramDeCreep** [comment]
i dont know what i was using before cause i needed to rename it to modpak for my modpack but its now 10.13.4.1614

**Comment by BramDeCreep** [comment]
Going to shut off pc if you need more answers ill be online again tomorrow

**Comment by zmaster587** [comment]
Unless it breaks again I don't think there's much else that can be done

**Comment by jrunestone** [comment]
Not to resurrect this bug but I encountered the same problem (couldn't click scan, when I clicked build it consumed my items), even if I restarted. But then I put the station assembler so that it didn't touch the rocket assembler and it worked perfectly...

**Comment by zmaster587** [comment]
would you be able to post images of the setup that didn't work?
