### ISSUE TITLE
[BUG] Holographic Projector Bug

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#1817]
## Version of Advanced Rocketry
>1.7.0-220

## Have you verified this is an issue in the latest unstable build
- Yes

## Version of LibVulpes
>0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
-Not sure but probably not

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
> https://pastebin.com/5td7XBc5

## Description of the problem
>Here's a modlist https://pastebin.com/rZ1HCuMf
Optifine is installed so keep that in mind.
The holographic projector crashes and when I renter the world it ends up having a bunch of artifacts

**Comment by Silfryi** [comment]
It seems like your stars are missing properties somehow? That's confusing. As a long shot, try removing LagGoggles, it's mentioned in the crashlog, but that doesn't mean it's causing it. It just means it's either listening or doing something else.

**Comment by TerminatorNL** [comment]
LagGoggles acts transparently. It redirects the method in order to time it if someone enables profiling. Neither the variable scope or variables have been changed.

```java
	public static void redirectRenderEntity(RenderManager manager, Entity entityIn, double x, double y, double z, float yaw, float partialTicks, boolean b){
		if(ProfileManager.PROFILER_ENABLED_UPDATE_SAFE){
			long LAGGOGGLES_START = System.nanoTime();
			manager.renderEntity(entityIn, x, y, z, yaw, partialTicks, b);
			timingManager.addGuiEntityTime(entityIn.getUniqueID(), System.nanoTime() - LAGGOGGLES_START);
		}else {
			manager.renderEntity(entityIn, x, y, z, yaw, partialTicks, b); //This has been called.
		}
	}
```

**Comment by Silfryi** [comment]
Cool, good to know!

**Comment by mxnmnm** [comment]
Could this be caused by a poorly made xml file? If so https://pastebin.com/ssXh9qQe tell me if I need to fix something.

**Comment by zmaster587** [comment]
I'd imagine lag goggles shouldn't cause any issues here, the entities shouldn't be created until AR makes them show up.  Looks to me it's more like an issue finding a star.

**Comment by mxnmnm** [comment]
So is this an issue with my config or something on your end?

**Comment by zmaster587** [comment]
Dunno yet, still looking into it.

**Comment by zmaster587** [comment]
Looks like it's on my end, I'll have a fix up shortly.
