### ISSUE TITLE
[BUG] Rockets getting stuck at y=1000 when launching

### ISSUE THREAD

**Issue by MarkOfTheBeast** [zmaster587/AdvancedRocketry#1818]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.2-1.7.0-221

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>1.12.2-0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

## Description of the problem
>When I take my rocket to a space station, it hangs up in space, the countdown to descent does not start, and it does not descend. Shortly after it says "press space to take off" to go back to the overworld. Sometimes it will descend if I go back to the overworld, sometimes it does the same thing when I go back. I am not able to land on the space station unless I restart my game. 

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by zmaster587** [comment]
What environment are you running in?  Are you using other mods (I'm not sure how N/A applies here), particularly sponge or similar?  What version of forge?

**Comment by MarkOfTheBeast** [comment]
Running Forge 14.23.5.2854 using a multiMC instance.

MultiMC has a console where you can see what's getting logged in real time. I looked at that when the rocket was launching, no exceptions logged relating to other mods, in fact it didn't log exceptions at all. The one thing I saw once was a message relating to IC2's worldgen. I take IC2 out, same thing happens. When I restart the game the rocket is landed where I left off from, so it appears to be a disconnect between what's happening to the rocket server side and client side.

**Comment by MarkOfTheBeast** [comment]
It's a JourneyMap issue.

[11:23:12] [Client thread/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null

Removing JourneyMap solved it. (This was the latest version of Journeymap)

**Comment by MarkOfTheBeast** [comment]
Was going to say that Journeymap was an issue, but the same thing happened after a few times after I took Journeymap out. If I look at the altitude meter, the altitude goes down but the player remains stuck in the original position.

**Comment by zmaster587** [comment]
Does this occur with no mods other than AR and libvulpes installed?

**Comment by MarkOfTheBeast** [comment]
I set up a test for that and didn't see it, so I looked back at the main pack where I first saw the issue. My main pack is a tech heavy one and runs at 60% of my 8GB memory allocation. The test instance barely cracked 20% of that. Could lag be a factor here? It doesn't happen all of the time, but I am seeing a "server overloaded" message in the console when it does.

**Comment by zmaster587** [comment]
Does logging out of the server then logging back in fix it?  If so, then it could be a factor (some kind of client desync due to something being time sensative?).

**Comment by zmaster587** [comment]
I think I found a mechanism.  So there's a segment of code after going between worlds that checks if the number of ticks the rocket entity is alive is exactly 20 (to give the world some time to load), if the server is "falling behind", it can skip processing ticks, so I'm wondering if the entity is never exactly 20 ticks old because some are being skipped.  Therefore the initial setup that is supposed to occur after moving the player and such never gets run.

**Comment by zmaster587** [comment]
Ruled out as a possible cause.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/4673015/AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip)

Could you try this build and let me know if it works for you?

**Comment by MarkOfTheBeast** [comment]
This was happening for me on single player so logging out and in to the server just meant restarting the game. Once I reduced the size of my modpack, the issue never happened again.

**Comment by zmaster587** [comment]
Would you be able to at least test it in the same conditions it was happening before just to check?  I have not had luck replicating the issue locally so I've got no idea if it's really fixed or not

**Comment by MarkOfTheBeast** [comment]
I added more mods to my pack to get it to the same level of memory usage as before and did not experience the same issue with the jar you linked to. I think it's safe to call it fixed at this point.
