### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#182]
Trying new 0.7 and i get a crash on startup:
http://paste.ee/p/zicRm
newest lib and forge 1614

edit:Another modpack: http://paste.ee/p/E4ryN
edit2: just AR0.7 and EnderIO http://paste.ee/p/mgRAD

**Comment by zmaster587** [comment]
What if you just use:
AR
buildcraft
libvulpes
codechickencore
?

**Comment by zmaster587** [comment]
Should be fixed in AR 0.7.0b and LibVulpes 0.1.0b
I honestly don't know why it broke, maybe it didn't like libvulpes and AR being compiled against a different version of forge.
