### ISSUE TITLE
Star renaming, editing, and removal also ringed icons for asteroid belts 

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1820]
i want to add custom star systems but some currently are in the place i want them to be. my idea is a command in game to delete star systems and the planets in them, edit star systems already in the game somehow, and the ability rename stars in the XML file. 

i also think ringed icons for asteroid belts would be cool. you choose an asteroid image and it's patterned randomly in a ring relative to it's location in the star system.

**Comment by Silfryi** [comment]
Most of this is already either possible or not happening. Most of your editing woes can be solved by editing the XML file itself, the ingame commands were _never_ meant to high precision additions, only for basic stuff or people who want to add one or two planets.

**Comment by PercyJames** [comment]
understood. i just have one question. by naming a star system that already exists in game in the XML file even if it's randomly generated will i be able to add planets to them?

**Comment by Silfryi** [comment]
You can already add planets manually to any star system, randomly generated or not.

**Comment by PercyJames** [comment]
ok! thanks!
