### ISSUE TITLE
[BUG] TE tank gets emptied in one go when filling rocket.

### ISSUE THREAD

**Issue by Splutty** [zmaster587/AdvancedRocketry#1825]
AdvancedRocketry-1.12.2-1.7.0-209-universal
forge-1.12.2-14.23.5.2847-universal
LibVulpes-1.12.2-0.4.2-74-universal
ThermalExpansion-1.12.2-5.5.7.1-universal

Hitting a rocket with a Thermal Expansion portable tank to fill it up uses up all the fluid in the portable tank. (All 800 buckets :)

**Comment by dmodoomsirius** [comment]
Why did you remove the whole template. Can you please follow it?

**Comment by Splutty** [comment]
I actually added more information than the template wanted, but here you go.

## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-209-universal

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-74-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N/A

## Description of the problem
Hit a built rocket with a Thermal Expansion portable tank to refuel it. Tank empties completely.
Themal Expansion version 1.12.2-5.5.7.1

**Comment by Gliese-832-c** [comment]
Not only TE tanks, it empties any container, even if it has more than the rocket can take.
