### ISSUE TITLE
Crash on adding bionic legs

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#183]
in the suit workstation when adding bionic legs i get a crash
Can not enter world after testing this.
http://paste.ee/p/g9OdZ

**Comment by TheGuyRunningSouth** [comment]
Reading that, try updating/downgrading  Forge. It seems that AR is looking
for a field that's not present in your version of Forge.

**Comment by zmaster587** [comment]
That code was tested against forge 1560-something, I'll try to fix it
tonight though

**Comment by TheGuyRunningSouth** [comment]
@zmaster587 I meant for @bludde to update his forge version.

**Comment by zmaster587** [comment]
I don't think updating would help because AR is built against an older
version of forge than he's using

**Comment by bludde** [comment]
yeah im running  forge 1614. 
tried with 1541 and same problem http://paste.ee/p/dSALm

**Comment by bludde** [comment]
same for 1517

**Comment by zmaster587** [comment]
Alright, I'll check it later, right now I'm in the middle of moving.

**Comment by TheGuyRunningSouth** [comment]
Huh. Good luck with your move @zmaster587.

**Comment by zmaster587** [comment]
It's the obfuscation helper... the field is apparently obfuscated, I thought using the obfuscation helper was supposed to automatically check that... fixing
