### ISSUE TITLE
[BUG] can't dimmap galacticraft moon in place of luna nor can i rename overworld

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1830]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.2-1.7.0-221-universal 

>IMPORTANT: "As of Advanced Rocketry 1.1.3 the overworld is no longer added to the solar system automatically. Instead the overworld must now be dimmapped to a star. This was done to allow for more flexibilty (ability to rename overworld, not require luna, etc)." <- does not seem to be true

>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
> 1.12.2-0.4.2-72 universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed-
- [x] N/A

>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>[insert here

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
 copy and paste the following into a planetDefs.xml file
<galaxy>
    <star name="Sol" temp="100" x="0" y="0" numPlanets="1" numGasGiants="0">
        <planet name="Overworld" DIMID="0" dimMapping="" customIcon="earthlike">
            <fogColor>1,1,1</fogColor>
            <skyColor>0,0,1</skyColor>
            <atmosphereDensity>100</atmosphereDensity>
            <gravitationalMultiplier>100</gravitationalMultiplier>
            <orbitalDistance>1000</orbitalDistance>
            <orbitalTheta>180</orbitalTheta>
            <rotationalPeriod>24000</rotationalPeriod>
            <biomeIds>0</biomeIds>
            <planet name="Luna" DIMID="-28" dimMapping="" customIcon="moon">
                <isKnown>True</isKnown>
                <fogColor>1,1,1</fogColor>
                <skyColor>1,0.5,0.5</skyColor>
                <atmosphereDensity>180</atmosphereDensity>
                <gravitationalMultiplier>100</gravitationalMultiplier>
                <orbitalDistance>150</orbitalDistance>
                <orbitalTheta>190</orbitalTheta>
                <rotationalPeriod>100</rotationalPeriod>
                <biomeIds>0</biomeIds>
            </planet>
        </planet>
    </star>
</galaxy>

**Comment by zmaster587** [comment]
Well..... can you try a valid xml file?  What you have here is not valid and will not load.

Maybe consider running the game in a new world then renaming stuff in the file if you don't feel comfortable with copy/paste?

**Comment by zmaster587** [comment]
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/4678966/planetDefs.zip)
Here's a sample with the galactic craft moon as a moon of the overworld.  My game uses dimid33 from the galacticraft moon, you may need to change it to fit galacticraft's config in your game.

**Comment by PercyJames** [comment]
ok! just so you know, i wouldn't have reported it as a bug if i could report it as something else. what should i report things like this as in the future? also before i close the issue im going to test it,

**Comment by PercyJames** [comment]
good news and bad news. good news, the moon is dimmaped. bad news, the icon is mars like and the gravity is the same as earths

**Comment by PercyJames** [comment]
ok so new problem. i can't change the moons gravity thus size without making me float. i really don't want the moon to be the same size as earth
