### ISSUE TITLE
[BUG] cannot edit gravity of galacticraft moon below 100 without making me float

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1831]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.2-1.7.0-221-universal >

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>1.12.2-0.4.2-72 universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y
Galacticraft, micdoodlecore, libvulpes, advanced rocketry.

## Description of the problem
> first dimmap galacticraft's moon to be the moon of earth, second, set it's gravity to be less than 100, third, go to the moon, fourth, watch as you float up.

**Comment by dmodoomsirius** [comment]
Going to assume that you have figured this issue out since you closed it.
