### ISSUE TITLE
[BUG][CRASH][COMPAT] Build Crash with Stellar Sky & Rocket Assembler

### ISSUE THREAD

**Issue by CitrusHappy** [zmaster587/AdvancedRocketry#1832]
## Version of Advanced Rocketry
>1.7.0-221

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
>0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
This is a compatibility issue with the Stellar Sky mod. This bug has also tried to be fixed in the past but it has since come back. The original git issue is #1701

## Crash report or log or visualVM (if applicable)
>[crash report 1](https://pastebin.com/e7eAG6it)
Apologies, I would use PasteDimDev but it's currently offline.

## Description of the problem
Reproducing the crash:
Try to build ANY rocket using the assembler.

Why this is important:
This is a severe crash that makes the entirety of this mod completely unplayable.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/4686261/AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip)

would you be able to test this and let me know if it resolves the issue?

**Comment by CitrusHappy** [comment]
Yes, still crashes. Albeit a different crash.
[crash 2](https://pastebin.com/N2a7DD66)

**Comment by zmaster587** [comment]
Idk what to really do about that one, AR doesn't look to be involved in the stack trace at all and the source for stellar sky looks outdated so I can't really confirm what's going on.  Looks like it's this issue though https://github.com/Johni0702/BetterPortals/issues/85
