### ISSUE TITLE
[BUG] overlapping planets, cannot change orbital distance/theta/phi.

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1833]
## Version of Advanced Rocketry
>1.12.2-1.7.0-221-universal

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.  Galacticraft, micdoodlecore, libvulpes, advanced rocketry

<galaxy>
	<star name="Sol" temp="100" x="0" y="0" size="1.0" numPlanets="0" numGasGiants="0" >
		<planet name="Overworld" DIMID="0" dimMapping="">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>100</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
		    <planet name="Luna" DIMID="33" dimMapping="" customIcon="moon">
			    <isKnown>false</isKnown>
			    <fogColor>1.0,1.0,1.0</fogColor>
			    <skyColor>0.77725655,0.7686322,1.0</skyColor>
			    <gravitationalMultiplier>100</gravitationalMultiplier>
			    <orbitalDistance>78</orbitalDistance>
			    <orbitalPhi>2</orbitalPhi>
			    <rotationalPeriod>10923</rotationalPeriod>
			    <atmosphereDensity>0</atmosphereDensity>
		    </planet>
		</planet>
                <planet name="Venus" DIMID="-31" dimMapping="" customIcon="iceworld"></planet>
			<isKnown>false</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>50</orbitalDistance>
			<orbitalPhi>180</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
	</star>
</galaxy>

if this turns up as just numbers then i have no idea. i downloaded the zip zmaster provided, the moon was dimmaped correctly, i just can't modify Venus' orbit for some reason.

## Description of the problem
when i try to change Venus' orbital distance, and phi, it doesn't work. unlike a previous issue, the numbers in the XML are not overridden. they stay the same but they don't effect the world. when i try to use the orbital distance command it works only for the time i'm in the world and resets when i rejoin. the only reason i know the config file still works is cause i can set the icon to ice world.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by MrEyeballs29** [comment]
Use the code block next time.

**Comment by PercyJames** [comment]
what's a code block?

**Comment by MrEyeballs29** [comment]
Use the graves for your xml file. Graves are used for code blocks. Heck you
can even put the xml in pastebin.

**Comment by PercyJames** [comment]
i have an idea

+++<galaxy>
	<star name="Sol" temp="100" x="0" y="0" size="1.0" numPlanets="0" numGasGiants="0" >
		<planet name="Overworld" DIMID="0" dimMapping="">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>100</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
		    <planet name="Luna" DIMID="33" dimMapping="" customIcon="moon">
			    <isKnown>false</isKnown>
			    <fogColor>1.0,1.0,1.0</fogColor>
			    <skyColor>0.77725655,0.7686322,1.0</skyColor>
			    <gravitationalMultiplier>100</gravitationalMultiplier>
			    <orbitalDistance>78</orbitalDistance>
			    <orbitalPhi>2</orbitalPhi>
			    <rotationalPeriod>10923</rotationalPeriod>
			    <atmosphereDensity>0</atmosphereDensity>
		    </planet>
		</planet>
                <planet name="Venus" DIMID="-31" dimMapping="" customIcon="iceworld"></planet>
			<isKnown>false</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>50</orbitalDistance>
			<orbitalPhi>180</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
	</star>
</galaxy>+++

ignore the plus signs

**Comment by PercyJames** [comment]
i tried to copy it to a text program so i could paste but it still showed up as just numbers.

**Comment by MrEyeballs29** [comment]
Here is the example of a XML file: https://pastebin.com/As6S5k1h

**Comment by PercyJames** [comment]
https://pastebin.com/AybkA8pV i think i got it.

**Comment by MrEyeballs29** [comment]
https://pastebin.com/Fsqwyx0X.
You put the other tags outside of the planet tag.

**Comment by PercyJames** [comment]
ok, i'm testing

**Comment by PercyJames** [comment]
it worked boii! i do have one more question though. in the series exoria i saw that you could use the atmosphere to color the planet icon when you are in a starship. like, when you look out a window you see a red earthlike what tag to i use to something like that?
