### ISSUE TITLE
[Question] how do i color planets like in exoria?

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1834]
**What do you think is missing or what do you think can be done better**
this is more of a question so, in a lets play of the modpack exoria i saw things like a red colored earthlike, and a purple colored earthlike,. what tag do i use to color the planets

**Comment by Silfryi** [comment]
You can add custom icons to the game, that's how you'd do it.

**Comment by PercyJames** [comment]
yes but, what tag in the custom icons would you use to
![iz4VTcK](https://user-images.githubusercontent.com/65469481/83156059-8f387780-a0c7-11ea-9a49-e2192cac232a.png) look here. the atmosphere's colored in yellow thus the planet is seen as such

**Comment by Silfryi** [comment]
Oh, you meant color the _atmosphere_, not the planet icon itself. Look at the [wiki](http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/), or ask in the [Discord](https://discord.gg/R42Et8,) not here

**Comment by MrEyeballs29** [comment]
The wiki may be outdated at this point.

**Comment by Silfryi** [comment]
The wiki is in good enough shape to work as a fine resource. Sure, it might not have the latest stuff, but nothing's invalidated the old stuff yet either.

**Comment by PercyJames** [comment]
so i'm assuming ether sky or fog
