### ISSUE TITLE
[BUG] Multiple Moons rendering at same position and moving at same speed

### ISSUE THREAD

**Issue by Golrith** [zmaster587/AdvancedRocketry#1836]
##Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-221-universal.jar

## Have you verified this is an issue in the latest unstable build
Yes, was fine in AdvancedRocketry-1.12.2-1.7.0-208-universal.jar. 

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal.jar

![Moons](https://user-images.githubusercontent.com/41104391/83305635-09b4e480-a1f9-11ea-816e-d4922eb6a816.jpg)
In this version two moons rendered the same size (not taking into account distance from planet), but had different orbit duration's.
Now, their size is based on distance, but their orbits are exactly the same.

**Comment by dmodoomsirius** [comment]
Can you provide your planetDefs.xml from the save folder please?

**Comment by Golrith** [comment]
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/4707485/planetDefs.zip)

Here you go. This is the from the latest version.

Version 209 was the last version this doesn't occur.

Also, anyway to remove the transparency on the rendered textures? The raw textures themselves have no transparency. Looks a bit weird when they overlap.

**Comment by Silfryi** [comment]
Which planet is it around?

**Comment by Golrith** [comment]
<planet name="Neu-Minecraftia" DIMID="0" dimMapping="">

In v209 they are fine (apart from being the same size in the sky), travelling at different speeds.

Beyond v209, they are constantly in the same position (i've advanced time by days), but are now different sizes (as expected, as one is further away then the other 150 vs 200 distance).

Wait, Orbital Thetas? I'm aware off Orbital Phi's.

This is the code I've defined, with AR filling in the blanks (brilliant feature!)

        <planet name="Neu-Minecraftia" DIMID="0" dimMapping="">
			<orbitalDistance>100</orbitalDistance>
			<rotationalPeriod>24000</rotationalPeriod>
			<isKnown>True</isKnown>
            <planet name="Primus" DIMID="2">
				<isKnown>false</isKnown>
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>1.0,1.0,1.0</skyColor>
				<gravitationalMultiplier>32</gravitationalMultiplier>
				<orbitalDistance>150</orbitalDistance>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>128000</rotationalPeriod>
				<atmosphereDensity>0</atmosphereDensity>
				<biomeIds>advancedrocketry:moon,advancedrocketry:moondark</biomeIds>
            </planet>
			<planet name="Secunda" DIMID="3" customIcon="iceworld">
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>1.0,1.0,1.0</skyColor>
				<atmosphereDensity>0</atmosphereDensity>
				<gravitationalMultiplier>16</gravitationalMultiplier>
				<orbitalDistance>200</orbitalDistance>
				<orbitalPhi>5</orbitalPhi>
				<rotationalPeriod>36000</rotationalPeriod>
				<biomeIds>advancedrocketry:crystalchasms</biomeIds>
            </planet>
        </planet>

**Comment by Silfryi** [comment]
Ohh, I was thinking of something else. That's strange.

**Comment by Ninjajax66** [comment]
I think i might have the same problem
![2020-06-17_10 04 01](https://user-images.githubusercontent.com/67060979/84908606-aba25100-b082-11ea-8b03-a09106e26953.png)

**Comment by agentwolf88** [comment]
This is the Problem ---> https://github.com/zmaster587/AdvancedRocketry/issues/1852
