### ISSUE TITLE
[Help] i want to color Venus' atmosphere yellow but it's coming up green.

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1837]
## Version of Advanced Rocketry
1.12.2-1.7.0-221-universal
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
1.12.2-0.4.2-75-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
![2020-06-01_16 58 20](https://user-images.githubusercontent.com/65469481/83459947-e83b3f00-a42a-11ea-8f87-b72ab277f9b8.png)

c59d28 <-- the color i want the atmosphere to be

**Comment by Silfryi** [comment]
It's applied on top of the blue tint the atmosphere normally is, there's not much you can do.

**Comment by MrEyeballs29** [comment]
I suggest either a red color or an orange color.
