### ISSUE TITLE
[BUG] Broken Weather

### ISSUE THREAD

**Issue by Arekk122** [zmaster587/AdvancedRocketry#1838]
## Version of Advanced Rocketry
1.12.2-1.7.0-221-universal

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
1.12.2-0.4.2-75 build -75

## Version of Minecraft
1.12.2

## Crash report or log or visualVM (if applicable)
[2020-06-03-6.log.gz](https://github.com/zmaster587/AdvancedRocketry/files/4738056/2020-06-03-6.log.gz)

## Description of the problem
After some in-game progress the weather stopped working. With chunkloaded overworld, moon and other dimensions the weather cycle stopped working. For example, when changing weather by command line it changes for a sec and turns to clear. Maybe interaction with other mod, but its more than 200, so hard to determine which one exacly, or Advanced Rocketry itself. When mod is disabled weather cycle works fine. Probably problem with dimensions or something like this

**Comment by notWaterGuy12** [comment]
Can confirm that this is an issue, I am also having this issue
