### ISSUE TITLE
crash on open inventory

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#184]
When having NEI installed, upon opening inventory you i get this crash
http://paste.ee/p/sHPnh
if nei is removed works fine.

![mods](https://cloud.githubusercontent.com/assets/1352518/17838624/1e01fc12-67d2-11e6-802a-b11c2d52dc0c.jpg)

**Comment by zmaster587** [comment]
Does that happen when libvulpes and AR are removed?

**Comment by bludde** [comment]
works fine when they are removed

**Comment by zmaster587** [comment]
Does this version fix it? http://65.78.115.159:25565/img/minecraft/AdvancedRocketry-0.7.0.jar

**Comment by bludde** [comment]
Yes it does, and also the bionic legs, but i suspect this is a further version so thats why that is.

**Comment by zmaster587** [comment]
Used the same method for flyspeed, forgot to fix that.. but this is really strange issue with nei

**Comment by bludde** [comment]
have also tried with 
NotEnoughItems-1.7.10-1.0.4.105-universal
CodeChickenCore-1.7.10-1.0.4.29-universal
CodeChickenCore-1.7.10-1.0.6.43-universal
CodeChickenCore-1.7.10-1.0.6.39-universal
but mostly some NEI errors and also the same

**Comment by bludde** [comment]
WAIT, now it seem to work.......
