### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MCSuchter** [zmaster587/AdvancedRocketry#1846]
## Version of Advanced Rocketry
>1.12.2-1.7.0-221

## Have you verified this is an issue in the latest unstable build
- [x] Y

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
>1.12.2-0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A

## Crash report or log or visualVM (if applicable)
>https://pastebin.com/sNNY0sji

## Description of the problem
>My console gets filled with that error message

**Comment by dmodoomsirius** [comment]
something is wrong with your planetefsf.xml as per the pastebin shows please upload said document to gist.github.com or to pastebin and link it here please? please also attach the temp.dat to the issue as well please.
