### ISSUE TITLE
[Request] add a wiki/ guide in game. consolidate external wikis and allow edits

### ISSUE THREAD

**Issue by CTH999** [zmaster587/AdvancedRocketry#1847]
So, I noticed that on the wiki (Which, by the way, you should either do an [Ingame Guide](url) and, either [Update The Github Wiki and make it the one linked into curseforge](https://github.com/zmaster587/AdvancedRocketry/wiki) or [Update the website wiki, and tie it into forge.](http://arwiki.dmodoomsirius.me/AdvancedRocketry/)

I personaly think you should use githubs wiki, that way other people can help with the wiki. No-one has edited it, because either they don't know what to put there, don't know the wanted format, or don't want to be "the first". But, the github wiki has the problem of links being hidden, so a gamepedia wiki could be nice, or that website one. But, just have a wiki! And, make sure it's tied into curseforge, and that you don't tie the wrong one in (:

But, even that won't help completly. Sometimes, you need something right there. So, I present, the HoloGuide

The HoloGuide is the succesor to the Holo-Projector. When used, it opens a fancy screen (That looks semi-holographic), with menues showing information. It's tied into the wiki, so when you alter the wiki, the next time it makes the config file it has the new data, or it might just retrieve it, store it, then the next time it detects a change, repeat. That way, you can just alter the wiki and the ingame guide changes to match. Or, have it hardcoded. But, it's set into catagories. Structures is just like the current one, a list of the structures. Used just like the current Holo-Projector, just has structures

Going back, there are sections on Inter-Stelar Travel, Satelites and Data, Items, Rockets, and so on. If it describes a machine, there is a visulize feature that does the same thing as the Structures section

And, the HoloGuide could have a section that only opens in creative that explains stuff like how to use the Planets.defs file. Because, while it might not update till you re-set the game, atleast the info is in-game...

**Comment by dmodoomsirius** [comment]
so i just checked. the wiki link on curseforge does update to the newest pulled WIKI that anyone can pr to. its a repo. https://github.com/zmaster587/AdvancedRocketryDoc it pulls every x amount of mins. its on a cron job. some of your suggestions are being discussed. If you want to contribute please do a pull request to that repo I linked in this message.

**Comment by CTH999** [comment]
> I made your topic what it is supposed to be.

Not quite. I have a confusing method of writing. I'll divide it to make it less windy, if you will
- Add in some sort of in-game documentation (Probably using holo-stuff, just because the holo-guide), and have it include said holo-guide
-There are 2 wiki's. The one that is that **arwiki.dmodoomsirius.me**, and one on **GitHub**. I was just saying that the github one has pretty much nada, and the other one is way out of date in some areas, missing info in others...

So, I was basicly saying "Either use the **arwiki.dmodoomsirius.me**, or could you change the link in curseforge (The same bar that has "Issues" and the files tab) to Github, or try to make it to where people can help with the other wiki (Pick one, have it linked on forge)
- The final part was just a concept, basicly, use the wiki to pull the info for the guide, instead of hard-coding it into the mod. That was just an idea to make it so you can have ingame documentation changes quicker.

I, personaly, would help, other than the fact that I still haven't learned programing (I plan on it, but... there's never enough time, am I right?)

**Comment by CTH999** [comment]
> so i just checked. the wiki link on curseforge does update to the newest pulled WIKI that anyone can pr to. its a repo. https://github.com/zmaster587/AdvancedRocketryDoc it pulls every x amount of mins. its on a cron job. some of your suggestions are being discussed. If you want to contribute please do a pull request to that repo I linked in this message.

Cool

Still think an ingame guide/ wiki is in order, mb it wold pull from the repo?

also, by "Some of the suggestions are being discussed", I will assume that includes the ingame guiude, which therefore means this needn't bee open, which therefore means I will hit the close and comment button. Can you tell I like the word "Therefore"?
