### ISSUE TITLE
[BUG]<orbitalPhi>xx</orbitalPhi> change everytime to 10

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#1852]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-224-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Description of the problem
>In planetDefs.xml (in world folder) the "orbitalPhi>xx</orbitalPhi" is everytime changing to "orbitalPhi>10</orbitalPhi" when i create a world. But only when "skyoverdrive" is true in advancedRocketry.cfg.
It will change only the moon phi. Overworld phi will not change.

**Comment by agentwolf88** [comment]
The result: https://i.imgur.com/HIFYwde.png

**Comment by Gliese-832-c** [comment]
I have tested this out myself, and it only happens with moons of planets that you visit.

Let's say that there's a planet called Planeto. It has three moons: Planeto-I, Planeto-II, and Planeto-III. After visiting Planeto, the orbitalPhi value of Planeto-I, Planeto-II, and Planeto-III gets set to 10, no matter the value that it was before.

**Comment by Silfryi** [comment]
This is a bug with a PR open to fix it. No closing, gh-actions :P
