### ISSUE TITLE
[BUG] New Galacticraft Dependency with Old Config

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#1854]
## Version of Advanced Rocketry
>1.7.0-6

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A
(haven't tested without any mods but it probably does still crash)

## Crash report
https://gist.github.com/mxnmnm/2613d6ee4f792461b344a0b28647ce80

## Description of the problem
>Install the latest version of AR with the old configs and make sure galacticraft isn't installed
Disabling the galacticraft compat in the config fixes the issue but it may confuse people who don't know how to read crash reports

**Comment by Silfryi** [comment]
Latest is from the gradleTest branch when it should not have been. You want the second-latest.

**Comment by dmodoomsirius** [comment]
Please revert back to the previous ar build as well and test again. A branch pushed that was not supposed to.

**Comment by mxnmnm** [comment]
Oh ok. Should I close this issue?

**Comment by Silfryi** [comment]
Preferably, yeah.
