### ISSUE TITLE
[BUG] Rocket Builder Crashing Server (Ticking Entity)

### ISSUE THREAD

**Issue by Calebbiz08** [zmaster587/AdvancedRocketry#1862]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-226-universal (Latest as of July 2020)

## Have you verified this is an issue in the latest unstable build
- [x] Y
- N
- N/A

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- Y
- N
- [x] N/A

## Crash report or log or visualVM (if applicable)
>https://pastebin.com/ZViLQEQ2

## Description of the problem
>Me and my friend are playing on an Aternos server with AR on it, and when I scan the rocket, the server closes and states that there is a ticking block entity that apparently is the rocket builder. Every time we start a scan or build, the server crashes.

**Comment by dmodoomsirius** [comment]
What blocks are you building the rocket out of? Can you upload the full log files to pastebin or gist.github.com and link them here?

**Comment by Calebbiz08** [comment]
The full log from Aternos: https://mclo.gs/MYgw2YF

**Comment by Silfryi** [comment]
That looks like it's a problem on the server software side, try in a singleplayer world with the same pack. Something isn't liking the storage chunk.

**Comment by Calebbiz08** [comment]
Ok

**Comment by wesleytech** [comment]
hey Calebbiz,

i saw this bugreport and i'm having the same issue and and i was wondering if you're using plugins and loading them with something called "Magma" (not advertising, just asking). i'm interested because without magma building rockets work (modpack we tried it with is Enigmatica 2 Expert skyblock).

Sincerely,
~Wesley

**Comment by Calebbiz08** [comment]
@wesleytech I am loading them using Magma because I play on VR, so I use Magma to load in the mods and the Vivecraft (VR) plugin.

**Comment by wesleytech** [comment]
ok. we've tested this with and without magma and we've found that its not a adv. rocketry issue but a magma issue (it runs fine on normal forge). i've since reported this on their support thread (https://github.com/magmafoundation/Magma/issues/182)

**Comment by Calebbiz08** [comment]
Thanks!
