### ISSUE TITLE
[Help] how make new star

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1863]
## Version of Advanced Rocketry
[1.12.2-1.7.0-221-universal]
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
[1.12.2-0.4.2-75-universal]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/UUEDQxZf

## Description of the problem
i finished the solar system (yay me) now i want to do the Kepler-22 system from extra planets. but i have no idea how do add another star.

how to reproduce:

step 1: copy text from pastbin. 

step 2: paste it in a valid PlanetDefs XML file.

step 3: click the PlanetDefs XML without opening it

step 4: feel angry

edit: here's what XML validator said "The markup in the document following the root element must be well-formed." i have no idea what that means

**Comment by dmodoomsirius** [comment]
Can you link the planetDefs.xml you are having issues with either to gist.github.com or pastebin.com and link it here?

**Comment by MrEyeballs29** [comment]
Actually he did.

**Comment by PercyJames** [comment]
so, any ideas on what i can do?

**Comment by PercyJames** [comment]
i fixed it
