### ISSUE TITLE
Acheivement: Wonder if there is beer on the sun

### ISSUE THREAD

**Issue by DarkGuardsman** [zmaster587/AdvancedRocketry#187]
Send a lawn chair into space with nothing more than a gunpowder rocket and no computer. Results will be death but get a cool achievement for effort.

Recommend based on Maxwolf's comment with difficulty level me & dragonlord were designing of "Hillbilly rocketry"

**Comment by zmaster587** [comment]
Tnt and a seat could work too

**Comment by DarkGuardsman** [comment]
yep, just one of those comical things that would be nice to have lol

**Comment by bludde** [comment]
solid fuel rocketry:)

**Comment by Tronzoid** [comment]
What about getting a rocket seat, putting loads of TNT under it, and lighting it? :)
