### ISSUE TITLE
[BUG] Ghost lasers appearing from orbital laser drill

### ISSUE THREAD

**Issue by Silivek** [zmaster587/AdvancedRocketry#1873]
## Version of Advanced Rocketry
1.7.0-227

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
0.4.2.-75

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Yes

## Crash report or log or visualVM (if applicable)
No crash log, but I do have a screenshot.

## Description of the problem
Lags the game out insanely. We currently have 5 ghost lasers and each produces particles and sound, but none work as an actual orbital laser drill. Seems to occur any time the laser runs out of power or is turned off. The problem persists on a server restart and client restart.
![2020-07-09_16 04 00](https://user-images.githubusercontent.com/43481327/87091182-dbb2bf00-c1fe-11ea-8719-54c74388f77c.png)

**Comment by dmodoomsirius** [comment]
Ok please fill this out correctly. You have not filled it out correctly. 

An example is  

**> Have you verified this is an issue in the latest unstable build
There doesn't seem to be any in the issue tracker.**


Please fill this out correctly.

**Comment by Silivek** [comment]
Do I just download the most recent unstable build and test it in there? The most recent unstable build is from a month ago on cursegorge.

**Comment by Silivek** [comment]
Updated to have correct information I believe.

**Comment by zmaster587** [comment]
Does this occur with only libvulpes and advrocketry installed with a standard forge env (no sponge/etc)?

**Comment by Silivek** [comment]
Yes, it seems to happen with only those two installed.

**Comment by zmaster587** [comment]
Is there anything in particular you need to trigger this?  So far in my testing I can't replicate the issue.

What i've done to test is the following:
Test 1:
1. Changed the AdvRocketry config option B:EnableLaserDrill to true
2. Changed the AdvRocketry config option laserDrillPlanet to true
3. launched a minecraft dedicated server and client and connected to the server.
4. Built a space station.
5. Moved the station to a random planet (I had stuff in the overworld I didn't want to break)
6. Built a space laser and powered it with creative energy cells
7. Set the drill mode to spiral and coords to 0,0
8. Activated the drill with a level
9. Ensured the drill was actually mining by checking the inventories of the output and verifying that it was filling up.
10. Deactivated the drill by turning the lever off
11. Teleported to the planet below and coords 0,0.  Observed that there was a hole as expected, but there was also no laser entity.
12. Repeat 8 thru 11 a few times, no change in results other than the drill hole getting bigger.
13. Logged in with 2nd client, teleported client to the drill site and moved original client to the station, repeated 8 thru 11.  Verified that the laser entity spawned when the drill was active and the laser entity despawned the instant the drill was turned off.

Test 2:
continuing with the setup from test 1 (laser drill in orbit, player 1 at the drill in orbit, player 2 on the ground at the drill site)
1. Activated the drill
2. removed the power source and monitored the drill's power until the drill's storage hit 0RF
3. Charge the drill again then repeat 1 and 2

In both instant the laser entity appeared on the surface the instant the drill was activated.  The instant the drill hit 0RF, the entity on the surface vanished.



So unfortunately I cannot seem to replicate the issue.  Is there something you're doing differently?  Can you try this same setup and do you get the same results?

**Comment by Silivek** [comment]
Upon further testing, if your game crashes while you can see the laser firing (or use ALT+F4) that's what causes a new laser to appear. The original pack I was playing on was a bit unstable so that would explain why we had 5 ghost lasers.

**Comment by zmaster587** [comment]
Ahh okay, that seems to do it

**Comment by Silivek** [comment]
Is there any quick fixes for this? Like maybe /killing the UUID of the lasers?

**Comment by zmaster587** [comment]
You could probably open the world in MC edit and kill them that way or use an NBT edittor on the world, idk if there's a way to kill by UUID without a mod.  I do know there used to be a mod for 1.7.10 that let you kill entities by type, but idk the 1.12 equivilent.

Patch should be ready within the hour though.
