### ISSUE TITLE
not a bug, but can you change the name of a space station

### ISSUE THREAD

**Issue by MrLonely27** [zmaster587/AdvancedRocketry#1881]
## Version of Advanced Rocketry
>1.12.2

**Comment by dmodoomsirius** [comment]
Am i gathering that you would like the ability to name your station?

**Comment by Gliese-832-c** [comment]
I second this, I'd also like to have the ability to rename the station from "Station 23" to something else. Maybe that could be done in the form of a fourth control block, into which you can input the name as a string and maybe select an icon out of a few available ones (or draw one yourself with a simple pixel editor similar to GalactiCrafts space race flag editor).
