### ISSUE TITLE
[BUG] Rocket assembler glitch

### ISSUE THREAD

**Issue by Vlarki** [zmaster587/AdvancedRocketry#1885]
## Version of Advanced Rocketry
>1 (playing on the forever stranded modpack, so not completely sure if the mod is up to date)

## Have you verified this is an issue in the latest unstable build

- N/A

## Version of LibVulpes
>1.10.2-0.2.6

## Version of Minecraft
>1.10.2

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>Will put a screen shot if not fixed
## Description of the problem
I have been playing on this modpack for 60+ hours, but have just found a game breaking glitch in advanced rocketry. Every attempt I make at using the unmanned rocket assembler, it will always say “invalid launch pad”. The weird part, when i made several new worlds and went into creative and made the same exact set-up I had in the original world, it would work fine. Even weirder, in only one test world did I encounter the same glitch. I’m not sure you can fix this since you didn’t make the modpack, but I just have to know; Am I being a total dumbass or is the mod just broken in that version?

**Comment by MrEyeballs29** [comment]
1.10 is not supported use latest mc version of that mod to receive support.

**Comment by Vlarki** [comment]
Is there any way to do that within the modpack or am I just screwed?

**Comment by MrEyeballs29** [comment]
> 1.10 is not supported, use latest mc version of that mod to receive support.
That mc version is 1.12

**Comment by Vlarki** [comment]
Guess I’m just fucked, lol. Forever stranded doesn’t run mc 1.12, I’ll just close the issue since nobody can do anything about it. Thanks for the quick response!
