### ISSUE TITLE
Question - Change Warp animation

### ISSUE THREAD

**Issue by TheRedCreations** [zmaster587/AdvancedRocketry#1890]
I have a question. I want to change the warp animation for private use. Where can i change it?

**Comment by Silfryi** [comment]
You'd need to modify the code [here](https://github.com/zmaster587/AdvancedRocketry/blob/9e9dd80c8425b772ad15ef2646b4bfee644334b4/src/main/java/zmaster587/advancedRocketry/client/render/planet/RenderSpaceTravelSky.java#L76).

**Comment by TheRedCreations** [comment]
Is it possible to change the warp background with an picture?

**Comment by Silfryi** [comment]
No.

**Comment by TheRedCreations** [comment]
ok. thanks for your help.
