### ISSUE TITLE
[BUG] Planet not visible on it's moon's sky (but planet's ring is!)

### ISSUE THREAD

**Issue by MadAlchemist** [zmaster587/AdvancedRocketry#1891]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-232-universal.jar

## Have you verified this is an issue in the latest unstable build
N/A

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal.jar

## Version of Minecraft
>1.12.2-forge1.12.2-14.23.5.2847.jar

## Does this occur without other mods installed
Y

## Description of the problem
1) Create solar system with at least one planet, with or without ring, and at least one moon.
Example:
		[(https://pastebin.com/GEy5hqpB)]
2) Fly to moon (DIMID=3 in example)
3) Look at the sky - you will see ring, if parent planet has it, but not a planet!
4) Change time of day - if there is a ring, you will find a moment when almost whole ring without planet is visible, if there is a ring. If no ring, you will see only stars.

**Comment by Gliese-832-c** [comment]
The parent planet is actually visible, but for some reason there's a bug that makes it very small:
![grafik](https://user-images.githubusercontent.com/55159077/89788052-d0fd8980-db1e-11ea-96e8-387a54a36f43.png)
![grafik](https://user-images.githubusercontent.com/55159077/89788060-d3f87a00-db1e-11ea-99e7-fe4a6b39a2cf.png)

**Comment by Dr-Ergmern** [comment]
I think this is part of the same bug, after setting the orbital distance of my moon, it appears very large (as I intended) from the planets surface, but for some reason when looking at the planet from the surface of the moon, the planet appear significantly smaller, the planet should appear larger from the moons surface than the moon does from the planet, but for some reason, they don't.
![Moon From Planet](https://user-images.githubusercontent.com/48629785/89910382-11750a00-dbe8-11ea-807f-10e8838cc109.png)
![PlanetFromMoon](https://user-images.githubusercontent.com/48629785/89910388-146ffa80-dbe8-11ea-898d-6840ca521253.png)
