### ISSUE TITLE
what do i use to set the atmosphere color (the part seen from space)

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1893]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N

## Description of the problem
> created a custom planet, but what do i use to set the atmosphere color? (the part you see in space) sky or fog? this hasn't been a problem with DIMMAPPED planets cause i can just use both sky and fog to be safe. but custom planets are different

**Comment by zmaster587** [comment]
I believe it's just sky color.  Fog is only used for fog.  The idea being if you look up, you kinda should get the same color as looking down from above.

**Comment by PercyJames** [comment]
thank you!
