### ISSUE TITLE
Not enough fuel capacity

### ISSUE THREAD

**Issue by kamild1996** [zmaster587/AdvancedRocketry#1898]
## Version of Advanced Rocketry
>1.7.0-232

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>0.4.2-75

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A

## Description of the problem
>See screenshots. The rocket assembly machine keeps saying there's not enough fuel capacity despite having 4 liquid fuel tanks.
![2020-08-15_10 58 22](https://user-images.githubusercontent.com/5320414/90309227-fc99be80-dee6-11ea-9fe5-6f0df12606e0.png)
![2020-08-15_10 58 12](https://user-images.githubusercontent.com/5320414/90309229-fe638200-dee6-11ea-83d5-89d82583eed1.png)

**Comment by PyralIron** [comment]
I think it is pretty clear: you don't have enough fuel to get off the planet. Not a bug.

**Comment by kamild1996** [comment]
Sorry, forgot to post an update but initially I ripped off this rocket design from someone else for whom this amount of tanks worked. I tried adding even more later on (about 10 AFAIK) but it still complained about fuel capacity.

After some experimentation, simply rebuilding the launch pad helped, and tanks are now properly detected. Unfortunately i was unable to reproduce the issue...
