### ISSUE TITLE
Pig spawns on the moon?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#19]
just found some :P

**Comment by zmaster587** [comment]
Do you have any biome-adding mods installed (like BOP), I have had biome conflicts do that to me.  Easiest way to check is F3-> biome name

**Comment by wormzjl** [comment]
yeah there is a id conflict with BOP
Could you make the biome ids configurable too?

**Comment by zmaster587** [comment]
Done for 0.3.1
