### ISSUE TITLE
[BUG] oreGen tag cannot accept metadata

### ISSUE THREAD

**Issue by aaronhowser1** [zmaster587/AdvancedRocketry#1908]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A

## Description of the problem
![image](https://user-images.githubusercontent.com/15698722/92308397-dd7cd280-ef62-11ea-8c1b-b5ab858a2d46.png)
```xml
<ore block="thermalfoundation:storage;0" minHeight="20" maxHeight="80" clumpSize="5" chancePerChunk="100" />
```
I've tried replacing the semicolons with spaces and colons, none work.

I [asked about this on the Discord](https://discordapp.com/channels/399708323126968321/399708323722821643/751822358196518913), so I'll link that conversation thread here.

**Comment by zmaster587** [comment]
Try the (yet to be documented) meta attribute

<ore block="block:minecraft:dirt" <OTHER attributes HERE> meta="1">
