### ISSUE TITLE
suit charge stop in inventory

### ISSUE THREAD

**Issue by bludde** [zmaster587/AdvancedRocketry#191]
When accessing inventory the bar for charging of gas (o2 or H) stops
https://youtu.be/tLzGhS4iXPc

**Comment by zmaster587** [comment]
it Is looking like when an inventory is open that if the item isn't in a slot handled by the inventory then it doesn't get updated.  I might be able to fix it, but I would be a lot of effort and I don't really see this as a critical problem.

**Comment by bludde** [comment]
i agree not a critical problem at all. but i thought i would mention it if it was an easy fix

**Comment by zmaster587** [comment]
I'm glad you mentioned it, but sadly it's far from an easy fix this time
