### ISSUE TITLE
[BUG] Typo in goto command

### ISSUE THREAD

**Issue by aaronhowser1** [zmaster587/AdvancedRocketry#1912]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A

## Description of the problem
![image](https://user-images.githubusercontent.com/15698722/92412899-515ddd00-f113-11ea-8cc8-c8af568acc70.png)
It says `gotostation` when it should be `goto station`

**Comment by zmaster587** [comment]
Thanks!
Fixed next release.
