### ISSUE TITLE
Unable to build stations or rockets at all, double checked to ensure I followed the guides.

### ISSUE THREAD

**Issue by AlephN-ll** [zmaster587/AdvancedRocketry#1916]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal.jar (Twitch client)
## Have you verified this is an issue in the latest unstable build
N - I only have access to the version on the Twitch client, there is no indication that this is an unstable build.
## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal.jar
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A - Does not crash
## Description of the problem
Unable to build Stations or Rockets, both devices throw "Invalid Launch pad structure!" errors on correctly built launch pads. Both instances I've built the launch pads as such: 4x4 launch pad, structure tower starting at the same level as the launch pad & Rocket assembler / station builder 1 block above the launch pad, directly next to it as depicted in images on the Advanced Rocketry guide site and in other issues listed on github. They also refuse to scan or build despite being powered.

![2020-09-16_07 02 15](https://user-images.githubusercontent.com/29993054/93348250-d3709480-f7ea-11ea-9b5a-4f8111c9a69c.png)
![2020-09-16_07 02 21](https://user-images.githubusercontent.com/29993054/93348259-d66b8500-f7ea-11ea-92fb-eb4e0a0b91b2.png)
![2020-09-16_07 02 26](https://user-images.githubusercontent.com/29993054/93348270-d8cddf00-f7ea-11ea-89a0-701d074a7a4f.png)
![2020-09-16_07 02 32](https://user-images.githubusercontent.com/29993054/93348277-dbc8cf80-f7ea-11ea-823f-fbd03db59700.png)

**Comment by GityUpNow** [comment]
You're Rocket Assembler and Space Station Assembler are flipped.

The Interface side(the side with the green bars and the green and red light at the bottom) has to face away from the launch pad.

I recreated your setup locally and once I've flipped both machines the Launch Pad got recognized.
![2020-09-18_18 11 33](https://user-images.githubusercontent.com/16244495/93620980-26a93980-f9db-11ea-9191-19c1fbe7ef78.png)
![2020-09-18_18 11 38](https://user-images.githubusercontent.com/16244495/93620986-2a3cc080-f9db-11ea-923e-6ca98700eb52.png)
![2020-09-18_18 11 50](https://user-images.githubusercontent.com/16244495/93620990-2c9f1a80-f9db-11ea-8ddc-167372dbe7c5.png)
