### ISSUE TITLE
Oxygen Vent is bugged and Laser Drill missing bottom texture

### ISSUE THREAD

**Issue by BramDeCreep** [zmaster587/AdvancedRocketry#192]
I tried to use the oxygen vent at first it disnt work cause the area was too big then i made the area smaller it worked i placed two of them so i can have enough oxygen for my station but it didnt work then i tried both of them apart from eachother and didnt work even though its using power 

And the bottom texture of the laser drill is also missing

Forge: 1.7.10-Forge10.13.4.1614-1.7.10

![front](https://cloud.githubusercontent.com/assets/21101377/17981257/4bb31932-6b03-11e6-9a53-219169c3751d.png)

![back](https://cloud.githubusercontent.com/assets/21101377/17981265/551d591a-6b03-11e6-94db-fc55d96761b5.png)

![laser drill](https://cloud.githubusercontent.com/assets/21101377/17981284/623f1ca0-6b03-11e6-9371-5bcc5dfab5fc.png)

**Comment by zmaster587** [comment]
Did you put Carbon Collection Cartridge in the scrubbers?
Oops... meant to fix that missing texture and forgot

**Comment by BramDeCreep** [comment]
yes

**Comment by BramDeCreep** [comment]
do you need more oxygen vents for larger areas?

**Comment by zmaster587** [comment]
right now areas need to be sectioned off, make sure no sides are exposed to space see if that fixes it

**Comment by BramDeCreep** [comment]
it worked for a second but when i made  the size bigger again and then small it stopped working there are no holes

**Comment by BramDeCreep** [comment]
restarted the game two time first time lever was on and didnt help second time lever was off got the bug to happen two times by changing the size of the area and add second oxygen vent not shure what causes it

**Comment by BramDeCreep** [comment]
second time it worked

**Comment by zmaster587** [comment]
how big is the area you're trying to seal?

**Comment by BramDeCreep** [comment]
very large 4 halways of 3x60x3

**Comment by BramDeCreep** [comment]
are you planning on making it so they work together?

**Comment by zmaster587** [comment]
yeah I am, also what "atmosphereCalculationMethod" are you using in the config?

**Comment by zmaster587** [comment]
setting to 2 or 3 might work better for that

**Comment by BramDeCreep** [comment]
im using 0 okay thanks
