### ISSUE TITLE
[BUG] Can see and warp to planets that aren't known

### ISSUE THREAD

**Issue by aaronhowser1** [zmaster587/AdvancedRocketry#1920]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal
## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A

## Description of the problem
My config's planetdefs.dml has this:
```xml
	<star name="Null" temp="100" x="-5" y="20" size="0.4" numPlanets="6" numGasGiants="3">
	</star>
```
and even in my save, it shows as
```xml
    <star blackHole="false" name="Null" numGasGiants="0" numPlanets="0" size="0.4" temp="100" x="-5" y="20">
        <planet DIMID="2048" name="Sol-2048">
```
but all the planets are visible in the Warp Controller
![](https://cdn.discordapp.com/attachments/399708323722821643/757598026931110079/unknown.png)
Tested in both creative and survival, though not in a new world.

**Comment by aaronhowser1** [comment]
Additionally, the star shows as a black hole when in orbit
![image](https://user-images.githubusercontent.com/15698722/93775059-9429b580-fbe7-11ea-950b-12e4c50650f0.png)

**Comment by zmaster587** [comment]
Heya, would it be at all possible to upload the full planet xml file so I can look into debugging the issue further.

As for planets not being known, what is the value of "B:planetsMustBeDiscovered" in config/advRocketry/advancedRocketry.cfg?

**Comment by aaronhowser1** [comment]
```
    # If true planets must be discovered in the warp controller before being visible
    B:planetsMustBeDiscovered=false
```
I have brought shame upon my entire family.

**Comment by aaronhowser1** [comment]
This is only for `isKnown=false` planets, right? Known planets can still be warped to without discovering them?
