### ISSUE TITLE
[BUG] Space Station Assembler cant build

### ISSUE THREAD

**Issue by DestroyerMCE** [zmaster587/AdvancedRocketry#1921]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.7.0.-231
## Have you verified this is an issue in the latest unstable build
N

## Version of LibVulpes
0.4.2-75

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
N/A

## Crash report or log or visualVM (if applicable)
no crash

## Description of the problem
the space station assembler can not seem to detect any blocks on the launch pad
![image](https://user-images.githubusercontent.com/45300174/93940550-85272e00-fce1-11ea-8212-80dcdf2d9bcc.png)
![image](https://user-images.githubusercontent.com/45300174/93940563-8bb5a580-fce1-11ea-9981-69955ea71177.png)
building just deletes the items

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by DestroyerMCE** [comment]
So either this is intended, as it may just happen outside of the overworld, or is fixed by dim switching.

**Comment by Silfryi** [comment]
Try making the pad bigger?
