### ISSUE TITLE
Chat message about toughness bar

### ISSUE THREAD

**Issue by vizthex123** [zmaster587/AdvancedRocketry#1922]
I keep getting this when I enter a world, and I can't fix it. It's super annoying. There's nothing in the config about any sort of toughness bar either.

![image](https://user-images.githubusercontent.com/31721920/93953084-19a88500-fd10-11ea-8703-0b85e1e3aa6c.png)

**Comment by dmodoomsirius** [comment]
why did you delete and replace the templete that would have given us info like Advanced Rocketry version, LibVulpes version, minecraft version, etc?

**Comment by vizthex123** [comment]
Sorry, I didn't wanna fill in a bunch of fields. Guess I can re-do it....

**Comment by dmodoomsirius** [comment]
just click new issue. don't make a new report. it just helps us see what is happening. could it be a issue with a mod conflict etc could be a issue with our code etc. we just try to streamline the process so we can attempt to diagnose it quicker.

**Comment by vizthex123** [comment]
alright
