### ISSUE TITLE
[BUG] Custom Solar System Destabilization on Mod Version Update

### ISSUE THREAD

**Issue by adwalters** [zmaster587/AdvancedRocketry#1925]
## Version of Advanced Rocketry
1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
N/A

## Version of LibVulpes
0.4.2-75-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Y

## Crash report or log or visualVM (if applicable)
N/A

## Description of the problem
Updating my mod from version 1.4.1 to 1.7.0 destabilized my custom solar system in the following ways:

- The visual orbital distance changed significantly (using the `<orbitalDistance>` tag). The starter planet is orbiting a black hole at a distance of 100, and that was unchanged visually. However, the moon (which is orbiting at 10) became so large that it filled the entire sky. When I go to the moon, the planet looks normal and relatively small (which doesn't make any sense at all if the moon is filling the entire sky). If I attempt to fix this by increasing the orbital distance to 100 for the moon, it looks normal on the planet, but the planet from the moon's perspective is so small you can't even see it.

- Mob spawns (using the `<spawnable>` tag) went completely off the rails. I have a challenge planet that spawns withers and endermen (wither weight is 1, enderman weight is 3). Before, it spawned them slowly and at a managable rate. Now, it spawns them so insanely fast that my frame rate drops to around 2 in about 10 seconds (it seems to be spawning a wither every tick). I cannot fix this by reducing the weight into decimals.

I do understand that 1.4.1 to 1.7.0 is a large jump, and these kinds of bugs can be expected. However, according to the wiki, my config should be working (and it was working in 1.4.1). Trying to go from 1.4.1 to 1.6.0 fixed the orbital distance visual bug, but the mob spawning was still absurd.

Here is all of my config:  [advRocketryConfig.zip](https://github.com/zmaster587/AdvancedRocketry/files/5273755/advRocketryConfig.zip)
*(note that oregen from other mods is defined; I did test with only Advanced Rocketry and LibVulpes, commenting out the custom oregen, but the issues remained)*

I would just continue to use 1.4.1, but Curseforge is requiring me to update the mod to publish my modpack.

**Comment by Silfryi** [comment]
The planet size seems to have some bugs, but there should have been a ~5x jump for that distance because of newer, more realistic size calculations. Spawnable I don't know much about.

**Comment by adwalters** [comment]
Gotcha. I did read in the change log that the orbital mechanics were updated, so the visual bug (if it is a bug) is only a minor concern. The spawnable bug is my main concern as that breaks my mod pack.
