### ISSUE TITLE
Toughness bar chat message on world login

### ISSUE THREAD

**Issue by vizthex123** [zmaster587/AdvancedRocketry#1926]
## Version of Advanced Rocketry
>1.7.0-232

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
> 00.4.2-75

## Version of Minecraft
>1.12.2, ~~the best one~~

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.

It's in my new modpack, which has almost 200.

## Description of the problem

Load my modpack and you'll get this chat message. I think [Classic Bars](https://www.curseforge.com/minecraft/mc-mods/classic-bars) is causing the issue though, it overrides the vanilla UI

Doesn't cause issues or crashes, but it's quite irksome.

![image](https://user-images.githubusercontent.com/31721920/94110195-e21d0400-fe07-11ea-80f1-7a61d2709679.png)

**Comment by Silfryi** [comment]
_Other_ than the fact that it explicitly said there that it is not a bug, that is not even Advanced Rocketry's doing - it's theirs. AND, they have a config options! Please read configs or have a general sense of what you're doing before posting here. 
https://github.com/Tfarcenim/ClassicBar/blob/c9cf03e2ac1727a555b48d2cb3ffbb4239ea0135/src/main/java/tfar/classicbar/config/ModConfig.java#L194
https://github.com/Tfarcenim/ClassicBar/blob/c9cf03e2ac1727a555b48d2cb3ffbb4239ea0135/src/main/java/tfar/classicbar/config/ModConfig.java#L224

**Comment by vizthex123** [comment]
I was hoping I could disable whatever Advanced Rocketry was doing, as I refer the Classic Bars UI.

**Comment by MrEyeballs29** [comment]
This is not a bug, but this might be more invalid report.

**Comment by vizthex123** [comment]
Ok then, guess I'll close it. Would be nice if I could at least disable the chat message though.

**Comment by Silfryi** [comment]
I. Told. You. There. Was. A. Config. Option. Go into the Classic Bars config file. There should be a config option for "Show Advanced Rocketry Warning" - turn that to false. that will stop the message. The thing it's complaining about IIRC is the AR oxygen bars, which are unlockable by config - change that in the AR config to move them. This has very very little to do with AR as that warning and the "incompatibility" are both on Classic Bars' side.

**Comment by vizthex123** [comment]
Ah ok, didn't see that. Sorry. No need to sound so fed-up though, I've just never used this mod before.
