### ISSUE TITLE
[BUG]Cant Scroll in Holoprojektor

### ISSUE THREAD

**Issue by Entiz** [zmaster587/AdvancedRocketry#1930]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.7.0-232  AdvancedRocketry
>0.4.2-75 LibVulpes

## Description of the problem
If i Scroll it only Scrolls in the Hotbar

**Comment by dmodoomsirius** [comment]
Do you have mouse tweaks installed?

**Comment by Entiz** [comment]
No
