### ISSUE TITLE
Transferring Power [Request]

### ISSUE THREAD

**Issue by highfrequencyhertz** [zmaster587/AdvancedRocketry#1931]
I have a space station and I need to distribute power from plugs around the station, but pipes were removed. Are there plans for this in the future and how do I transfer power. The only mod I have installed is Advanced Rocketry.

**Comment by Silfryi** [comment]
Advanced Rocketry is not a logistics mod, the pipes were removed because they were buggy and they were only added to bridge the lack of logistics mods in early 1.10. There are no plans for power transfer in Advanced Rocketry, get another mod to do that.

**Comment by highfrequencyhertz** [comment]
Do you have any recommendations for minimalist mods that would do this job? I want to play just Advanced Rocketry and need a mod that is small and does not add lots of ores.

**Comment by Silfryi** [comment]
Flux Networks adds no new ores and is wireless, along with only adding <20 blocks. That's a good one to use.

**Comment by highfrequencyhertz** [comment]
Thanks that look great I may try it out. I have decided on a few mods to make my private mini modpack. Thermal expansion, (energy gen, storage transmission) Applied energistics, (futuristic space base feel) and big reactors or nuclearcraft. (lots of power for mining lasers. I may use your recommendation later.

**Comment by Archilyte** [comment]
why not use thermal dynamics if you are gonna have thermal expansion? people put both of those mods together a lot

**Comment by Gliese-832-c** [comment]
Shouldn't this be closed, now that 1) it's clear that the power pipes aren't coming back, and 2) the user figured out a solution to their problem?

**Comment by highfrequencyhertz** [comment]
Oh, sorry. I will close it. I am new to Github.
