### ISSUE TITLE
[BUG] Screen turns grayish after start of scanning/building rocket.

### ISSUE THREAD

**Issue by Szymonicus** [zmaster587/AdvancedRocketry#1948]
## Version of Advanced Rocketry
>1.10.2-1.0.19

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [ ] N
- [x] N/A

## Version of LibVulpes
>1.10.2-0.1.19

## Version of Minecraft
>1.10.2

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

## Description of the problem
>After clicking scan or build the rocket, screen makes grayish.
It's grayish only when we're looking at the rocket/launch pad direction. 
I've found only 2 posts about this issue and both didn't helped.
Im playing on expanded Age Of Engineering (130 mods) about 2-3 months after adding & removing last mod this issue happened, only mod that was changed in meanwhile was OptiFine, from E3 to H5. I've made a downgrade, but didn't helped.
(I've upgraded earlier OptiFine due to glitch/bug what was happening after turning off shaders)

**Comment by Silfryi** [comment]
1.10.2 Is unsupported. Please close this issue.
