### ISSUE TITLE
[CRASH] Realistic Terrain Generation, Biome Tweaker scripts incompatibility

### ISSUE THREAD

**Issue by juraj-hrivnak** [zmaster587/AdvancedRocketry#1949]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-235-universal

>This crash happened to me when transporting to other dimensions using rocket

## Have you verified this is an issue in the latest unstable build
> Tested on both latest and stable

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2
>Latest Forge

## Does this occur without other mods installed
> Latest version of Biome Tweaker
> Only mods needed are AdvancedRocketry, Realistic Terrain Generation and Biome Tweaker

## Log
> https://paste.ee/p/vm9Ys

## Description of the problem
> I think the problem is in the Biome Tweaker scrips. The configuration for Biome Tweaker is intended for Realistic Terrain Generation mod, but AdvancedRocketry is taking these scripts like for themselves.
Maybe this can be fixed rewriting the configuration but I don't know how.

## Additional files
> These are the Biome Tweaker scripts:
[scripts.zip](https://github.com/zmaster587/AdvancedRocketry/files/5458576/scripts.zip)

**Comment by Silfryi** [comment]
Can I see your planetDefs.xml? There's a chance this isn't BT at all, and instead is a failure there.

**Comment by Silfryi** [comment]
Oh, and one thing to try: try upping the number of biomes per world to 10 - that's likely to fix the issue at least somewhat.

**Comment by juraj-hrivnak** [comment]
Hi, here is the planetDefs.xml
Increasing the planets per world didn't help. :D Even with like 100, game still crash.

> [planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/5478400/planetDefs.zip)

Here is one photo what it looks like after the crash.
![2020-11-02_23 34 00](https://user-images.githubusercontent.com/71150936/97928022-6d25de00-1d66-11eb-8337-98bdc71fa4fe.png)

**Comment by Silfryi** [comment]
What planet were you going to?

**Comment by juraj-hrivnak** [comment]
The Moon.

**Comment by juraj-hrivnak** [comment]
I fixed it! The crash was related with Biome Tweakers Script- More concretely - with the errors in the script.

**Comment by miad2401** [comment]
> I fixed it! The crash was related with Biome Tweakers Script- More concretely - with the errors in the script.
Could you tell me what you did to fix it? I am having the same issue.

**Comment by juraj-hrivnak** [comment]
- Explanation:
https://github.com/superckl/BiomeTweaker/issues/269#issuecomment-785241844
