### ISSUE TITLE
[BUG] Advanced Rocketry modifying other mods dimensions forcing the use of space suits where they shouldn't be needed

### ISSUE THREAD

**Issue by KangyKSLG** [zmaster587/AdvancedRocketry#1952]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.7.0-232

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
0.4.2-75

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
Advanced Rocketry and The Dalek Mod

>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>[insert here

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
When entering a Tardis from the Tardis mod. I catch fire and gain slowness till I die. I also get a no oxygen warning on Trenzalor (not coded in by The Dalek Mod). The however, only seems to happen server side. Client and Server running same mods

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by KangyKSLG** [comment]
Closing this. I figured that setting the DIMIDs of the effected dimensions to below the value Advanced Rocketry assigned planets from (2 by default) it doesn't interfere anymore

**Comment by Nikkkkk4** [comment]
> 
> 
> Closing this. I figured out that setting the DIMIDs of the effected dimensions to below the value Advanced Rocketry assigned planets from (2 by default) it doesn't interfere anymore

Can you make a youtube video or make a step by step toutorial how you did this? I have no idea how to do this

**Comment by KangyKSLG** [comment]
> > Closing this. I figured out that setting the DIMIDs of the effected dimensions to below the value Advanced Rocketry assigned planets from (2 by default) it doesn't interfere anymore
> 
> Can you make a youtube video or make a step by step toutorial how you did this? I have no idea how to do this

Hi, either go into the advanced rocketry configs and change the value from 2 to something ridiculously high (like 1000). I can't remember when the config option is called now but it's something like "dimension id advanced rocketry can make into planets" or something like that.

The option is to go into the affected mod configs and change the dimension IDs to below 2. I.e., I set mine to -1000. This all depends on the mod and if they allow dimension changes.

The first method is more fool-proof
