### ISSUE TITLE
[BUG] Missing chip after rocket mission 

### ISSUE THREAD

**Issue by alessandriLuca** [zmaster587/AdvancedRocketry#1958]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Description of the problem
After a rocket come back from a mission the Asteroid chip just disappear.

**Comment by Silfryi** [comment]
This is normal, intended behavior. Please close the issue.
