### ISSUE TITLE
[BUG] only two biomes spawn

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1959]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal
## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

advanced rocketry, defiled lands, libvulpes.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>https://pastebin.com/PwZiAzuF

## Description of the problem
> my id's for the defiled biomes are 389,388,387,385,386,384,383. but when i load the planet only the biomes in the first and the third place generate. the comma at the end doesn't seem to do anything. i checked.

**Comment by MrEyeballs29** [comment]
Numerical ids are unsupported use named ids instead.

**Comment by PercyJames** [comment]
Ok? cause somewhere else i heard i should use numbered id's and the developer for the exoria pack uses number id's.

i'll try name id's and get back to you

**Comment by PercyJames** [comment]
the exact same thing happens in the exact same way with names.

**Comment by MrEyeballs29** [comment]
Remove the last comma

**Comment by PercyJames** [comment]
here's a pastebin https://pastebin.com/8FHNdPps in my previous number test the comma after the last number did nothing.

**Comment by MrEyeballs29** [comment]
Test with the last biome with a vanilla Minecraft biome.

**Comment by PercyJames** [comment]
ok so, three biomes generated. the biomes in the first and third places and the vanilla biome. i used names for all of them

**Comment by MrEyeballs29** [comment]
Now try replace all 6 of them as vanilla biomes.

**Comment by PercyJames** [comment]
just so you know, using names is causing minecraft to crash a lot.

**Comment by MrEyeballs29** [comment]
If you put invalid id's that is.

**Comment by PercyJames** [comment]
all biomes generate when vannilla.

**Comment by PercyJames** [comment]
how do i proceed?

**Comment by Silfryi** [comment]
It sounds like you have the resource IDs wrong. Check your logs for errors.

**Comment by PercyJames** [comment]
logs are just gibberish of random symbols?

**Comment by MrEyeballs29** [comment]
No they are used for checking errors. You might have an error in the log.

**Comment by PercyJames** [comment]
ok everything is even more confusing. https://pastebin.com/6TJ5fGJk despite JITL (journey into the light) not using the id i set anywhere minecraft still thinks something is wrong with the id and JITL  it happened once before and i tried to change the id but apparently something else is wrong.

**Comment by PercyJames** [comment]
i think i might stop trying for now. i'm gonna close the issue. i might reopen it i might not
