### ISSUE TITLE
No Dilithium Ore is generated in the moon

### ISSUE THREAD

**Issue by Tarkov** [zmaster587/AdvancedRocketry#198]
Checked it with MCEdit, I cannot find Dilithium Ore.

**Comment by zmaster587** [comment]
Do you have galacticcraft installed and what are the configs for dilithium generation set to be?

**Comment by Tarkov** [comment]
Yes, I have galacticraft installed. I have tried with the default settings, and with 100 PerChunkLuna.

**Comment by zmaster587** [comment]
will investigate.

**Comment by Tarkov** [comment]
I think Dilithium does not generate yet, I tried the latest build with no luck. Is it possible to change the recipe for the space station so It does not need Dilithium?

**Comment by TheGuyRunningSouth** [comment]
Dilithium should generate randomly on the overworld as well (or it has for
as long as I've been playing).

**Comment by zmaster587** [comment]
If you updated from the older  version, you may need to delete old chunks or explore new ones to see it work.  What are the settings for Dilithium Generation in the config?

**Comment by Tarkov** [comment]
I used the default settings in a new world with a fresh installation and checked it with McEdit as I always do before report. As I was focused in the moon I did not check if it generates in the overworld, I though it only generates in the space. It generates in the overworld, but not in the moon, yet.

**Comment by zmaster587** [comment]
What version of GC are you using?  I'm using 3.0.12.454 and it's genertating just fine for me

**Comment by Tarkov** [comment]
Really? I am using 3.0.12.463 , and I always tried with only Advanced Rocketry, Buildcraft and Galacticraft. That means it is my problem, but I have no idea where to start to fix it.

**Comment by zmaster587** [comment]
It's possible something in GC changed, or something different about the dev environment, I'll admit I've not tried it in  production, I'll check that too, I'll try it with that version as well.  Set settings in config to
"    I:DilithiumPerChunk=1
    I:DilithiumPerChunkLuna=10
    I:DilithiumPerClump=16"
and regen the moon and see if it spawns then, I'll get back to you when i try the other build

**Comment by zmaster587** [comment]
is B:"Generate all other mods features on planets" set to true or false in config/galacticcraft/core.conf?

**Comment by Tarkov** [comment]
Exactly! it was set to false. Sorry to bother you with this issue that it wasn´t in your mod, and many thanks for the help. :-)

**Comment by zmaster587** [comment]
no problem!
