### ISSUE TITLE
[BUG] Loose Satelites afert clean stop and restart of forge server

### ISSUE THREAD

**Issue by P3FBLN** [zmaster587/AdvancedRocketry#1987]
## Version of Advanced Rocketry
>AdvancedRocketry-1.10.2-1.4.0-12.jar

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>LibVulpes-1.10.2-0.2.8-37-universal.jar

## Version of Minecraft
Server:
>forge-1.10.2-12.18.3.2511-universal.jar
Client:
>1.10.2 by CurseForge

## Does this occur without other mods installed
- [x] not tested

## Crash report or log or visualVM (if applicable)
There is no crash

## Description of the problem
I have same problem like #638 and #705

Means that I loosing my sats every new start of my multiplayer forge server.

/world/advRocketry/planetDefs.xml => https://pastebin.com/NC2DtqYS
/advRocketry <= not exists

**Comment by Silfryi** [comment]
You're on an old version, we no longer support 1.10; only 1.12.2 is supported at this time. As such you should update as your issue has likely been fixed. There's nothing we're going to do about bugs on older version. Please close this issue.

**Comment by P3FBLN** [comment]
> You're on an old version, we no longer support 1.10; only 1.12.2 is supported at this time. As such you should update as your issue has likely been fixed. There's nothing we're going to do about bugs on older version. Please close this issue.

Sorry that make no sense.
http://arwiki.dmodoomsirius.me/AdvancedRocketry/ 
here you see that 1.4. is the actuall version.
I use AdvancedRocketry-1.10.2-**1.4.0**-12.jar

**Comment by MrEyeballs29** [comment]
That is still 1.10.2. Please close or update to latest version.

**Comment by Silfryi** [comment]
And the wiki isn't perfectly up-to-date; I've written part of the mod, you'd think I would know what version it's on. Latest AR is 1.7.[something], it's certainly not 1.4.[something].

**Comment by P3FBLN** [comment]
The Bug is still existing. So why to close :-D
Can you please help me to merge the latest version to the 1.10.2 compatible Version?
My pack have lot mods depending of 1.10.

**Comment by MrEyeballs29** [comment]
Yeah but the bug is fixed in the 1.12.2 version.

**Comment by Silfryi** [comment]
>  Can you please help me to merge the latest version to the 1.10.2 compatible Version?
..... you _do_ realise how much work you're asking of me? There's been hundreds of hours of work past the latest 1.10 version, I don't know it very well, and much has changed -- if you want the bug fixed, update to 1.12 and stop asking for me to spend hours I can ill afford on your flights of fancy that don't allow you to update to 1.12 where the bug is fixed.
