### ISSUE TITLE
[Crash] same Issue with Mekanism OR JustEnoughIDs (JEIDs)

### ISSUE THREAD

**Issue by gatoborrachon** [zmaster587/AdvancedRocketry#1996]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-237-universal

## Have you verified this is an issue in the latest unstable build
- [x] No

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] No

it happens when JustEnoughIDs OR Mekanism is present

## Crash report and log, or VisualVM snapshot (if applicable)
JEIDs: https://pastebin.com/yhpPck1p
Mekanism: https://pastebin.com/2ge1BN6F

## Description of the problem
There's a crash when you do the following:

1.- Open (or create) a world
2.- Once it loaded, return to the main menu
3.- try to enter to the same world (i also works with any other world)
4.- See Error. (if you use VanillaFix it will simply freeze the screen, without it it will take you out)

**Comment by MrEyeballs29** [comment]
I think it might be more of JEIDs issue.

**Comment by gatoborrachon** [comment]
ok, i will try to open a new issue on their side but i think they will not do anything, you may know what is happening? (to help them)

**Comment by MrEyeballs29** [comment]
Hmm. Try to remove JEIDs.

**Comment by gatoborrachon** [comment]
well, i use it because i exceded the limit of IDs...

**Comment by gatoborrachon** [comment]
or you need the log with and without JEIDs?

**Comment by MrEyeballs29** [comment]
Which ids are you using? Items, Blocks, Dimensions, or Biomes

**Comment by gatoborrachon** [comment]
well, i can't recreate the issue, it is pretty know: "java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded."

**Comment by gatoborrachon** [comment]
well, i can recreate the issue but give me a moment, it is pretty known: "java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded."

**Comment by gatoborrachon** [comment]
wait, wtf, i use JEIDs since i have 180+ mods because of that issue, but now i tryied to generate the same issue with 232 mods and it didn't happen again! (i removed some mods since that moment, but wtf, it was because a specific mod fault instead of having too much mods?)

well, the issue seems to be fixed for me (because i will not use JEIDs), but for anyone who uses AdvancedRocketry and JEIDs will have the same issue so nothing's fixed

**Comment by gatoborrachon** [comment]
I'm going to have to swallow my words, the same error has appeared again but now without JEIDs, (i need to test which mod does this but now we have another issue along this one (AR+JEIDs))

**Comment by gatoborrachon** [comment]
@MrEyeballs29 i found that Mekanism if the other gulty mod with the [same issue ](https://pastebin.com/2ge1BN6F)
(java.lang.IllegalArgumentException: Could not get provider type for dimension 0, does not exist)

should i made a new Issue or just update this one?

**Comment by MrEyeballs29** [comment]
Try without AR.

**Comment by gatoborrachon** [comment]
without Advanced Rocketry (Only Mekanism) it does not crash, so yeah, this is a compat issue between AR and Mek, well, maybe you know that sadly Mekanism 1.12 is dead for the authors, this is possible to be fixed from AR's Side?

**Comment by gatoborrachon** [comment]
i want to add that i use OpenJ9 by performance reasons, but i confirmed that this [issue](https://pastebin.com/JBEqp1Gm) also happens with the default JVM (HotSpot)

**Comment by MrEyeballs29** [comment]
Let me see if I can reproduce the issue.

**Comment by gatoborrachon** [comment]
yeah, please test it, i wish it is possible to fix from AR's side, as i said, Mekanism will not recieve an update by their authors (or if it's an easy fix in Mekanism's side, i can do it myself, just tell me exactly what i need to do)

**Comment by MrEyeballs29** [comment]
I cannot reproduce the issue. My end my game doesn't have any crashes related to mekanism or AR.
https://pastebin.com/4viMTahh
https://pastebin.com/TFhiT8G9

That might be your end. I even used the same mods and no issue. You might be using an outdated version of AR.

**Comment by gatoborrachon** [comment]
> You might be using an outdated version of AR.

But i use AdvancedRocketry-1.12.2-1.7.0-235-universal (the latest according to CurseForge)


> That might be your end. I even used the same mods and no issue.

well, i really have no idea what may be happening, i used HotSpot to confirm this is not an issue related to OpenJ9 and i only used these 2 mods so it's impossible to be the fault of any other mod, is there a way to know what's different in our computers? that VisualVM snapshot should tell us what is happening? (sorry for late reply)

**Comment by MrEyeballs29** [comment]
No the latest is actually build 237.

**Comment by Silfryi** [comment]
Backing up a step. I think this is neither of those mods' issues. I think your planetDefs.xml got corrupted somehow. DIM0 not having a provider is pretty serious. Best guess is you have a `DIMID="0"` without a `DIMMAPPING=""` tag for your overworld planet. Can you verify this for me?

**Comment by gatoborrachon** [comment]
>  Can you verify this for me?
@MrEyeballs29 @Silfryi well, i think that was the issue, i copied one of the examples on PlanetDefs-Sharing and modified somethings, except that one, many thanks, but now what exactly i need to put in my planet earth? 

1.- `DIMID="0" DIMMAPPING="0"`
OR
2.- `DIMID="0" DIMMAPPING=""`

**Comment by gatoborrachon** [comment]
well, i just need to try it by myself, many thanks again

**Comment by MrEyeballs29** [comment]
That is not a bug but a user error.
