### ISSUE TITLE
More gas giant icons/ fully customizable icons

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#1998]
**What do you think is missing or what do you think can be done better**
basically, I think there should be more colors of gas giant and/or fully customizable icons. my reasoning for the gas giant icons is that people might want to make a gas giant of a specific color that does not exist in the current pallet. say: green. I know green isn't realistic, but there is another option aside from ignoring me entirely. 

fully customizable icons would allow players to fully customize their universe. as long as they can make pixel art, they can use a fully customizable icon system. or, you could allow for both AR icons and fully custom icons.

**Comment by voidsong-dragonfly** [comment]
There's this magic thing called reading the wiki thoroughly, which would answer your proposition quite well were you to actually attempt it. Please make sure to do so before making issues such as this one again.

**Comment by PercyJames** [comment]
understandable. have a nice day.
