### ISSUE TITLE
Space Station currently orbiting nothing / "space", and destinations cannot be selected.

### ISSUE THREAD

**Issue by MightyBidoof** [zmaster587/AdvancedRocketry#1999]
## Version of Advanced Rocketry
1.7.0-209

## Have you verified this is an issue in the latest unstable build
No I have not.

## Version of LibVulpes
0.4.2-74

## Version of Minecraft
1.12.2, Forge version 14.23.5.2847

## Does this occur without other mods installed
As I'm playing a modpack (Omnifactory), I'll be safe and say yes, although it should be possible to replicate with just AR

## Crash report and log, or VisualVM snapshot (if applicable)
Due to what happened to cause this (Blue-screen), I'm not entirely sure the relevant logs exist, but I'm fine with sifting through them if needed to see if they do exist.

## Description of the problem
Title gets the gist of it across - My space station is stuck orbiting nothing, and I also can't modify the orbit as any attempts to select a destination are completely unresponsive.

What happened to cause this is as follows:
My computer blue-screened as I hit "Save & Quit", forcing me to recover from a backup as the level.dat (along with level.dat_old) had became corrupted as a result, although everything to do with chunks was (and still seems to be) seemingly fine. I ended up grabbing the level.dat from my most recent backup & replacing the corrupted one with it.
Before the blue-screen, I was orbiting a black hole I had manually added. After restoring from the backup, I was orbiting nothing. Absolutely everything else about the world was completely fine.

Screenshot of the Warp Controller's UI, moving to different tabs is fine, but attempting to click "Select Planet" is completely unresponsive besides the usual "button clicked" sound.
![image](https://user-images.githubusercontent.com/12218253/108632983-a2675080-7469-11eb-8bb5-5d2aff084fc8.png)

## Final notes
Before making this report I did a bit of searching to see if anyone else has had this issue, and I found a single closed issue #552.
The fix implemented after that issue (Invalid orbits being forced to orbit earth) seems to be missing from 1.12 versions of the mod.
Along with re-implementing the fix into the modern version, I'd also suggest a command to force an orbit around any valid planet/black hole/other celestial body in-case the fix doesn't work for whatever reason.
While you work on fixing this, some pointers to what files I'd edit in the world folder to fix this manually would be appreciated.

**Comment by voidsong-dragonfly** [comment]
Said fix does exist in the 1.12 code. As to why it's not working, I am unsure.
