### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Tsyklop** [zmaster587/AdvancedRocketry#2]
Crash: http://pastebin.com/8P3vWBdh

AdvancedRocketry-0.1.0, Carpenter's Blocks 3.3.7 mc 1.7.10, Forge 1492, Forge 1517
 if I remove AdvancedRocketry all is normal.

**Comment by zmaster587** [comment]
I have seen this issue occur on my debug server with certain combinations of reika's mods and carpenter's blocks.  Try removing reika's mods and see if it fixes, when I have a chance I will try to replicate it myself.  And post my findings. Back here.

**Comment by Tsyklop** [comment]
yes. I remove reika`s mods and all OK.

**Comment by Tsyklop** [comment]
Why closed? I need reika`s mods...Solve this problem

**Comment by dmodoomsirius** [comment]
Why not ask Reika to fix the issue on his end.

**Comment by zmaster587** [comment]
It's not a problem with Advanced Rocketry nor libvulpes, nowhere in my code do I touch carpenter's blocks.  In fact the only mod I interact with at all right now is NEI and cofhcore for recipes and power respectively.  This issue also occurs without Libvulpes or Advanced Rocketry in an instance.  So there really is not anything I can do about it unfortunately.

**Comment by Tsyklop** [comment]
@zmaster587 Such an error I have a bet only when Advanced

**Comment by zmaster587** [comment]
this error has been occurring for months: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=972#c19721

Try adding back all of Reika's stuff except Rotarycraft and see if it runs.  In the meantime I'll take a poke around to see if I can find a better solution

**Comment by Tsyklop** [comment]
I stand only 3 reika`s mods. It: DragonAPI, RotaryCraft, Reactor Craft. ReactorCraft not work without RotaryCraft...

Removed RotaryCraft and ReactorCraft and everything is fine.DragonAPI not deleted

**Comment by zmaster587** [comment]
I'm currently strongly suspecting a load order issue, it seems if Rotarycraft is loaded before carpenter's blocks, this error occurs.  It seems introducing Advanced Rocketry changes the load order (which is controlled by forge).

**Comment by zmaster587** [comment]
I've done some testing and found load order does appear to be the issue and have notified Reika accordingly:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/295

**Comment by zmaster587** [comment]
I made a tweak to libvulpes to try to make things load in a better order:
http://minecraft.curseforge.com/mc-mods/236541-libvulpes/files

**Comment by Tsyklop** [comment]
Everything is working. thank!
