### ISSUE TITLE
After updating to 0.3, machines can no longer process stuffs

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#20]
Tried lathe and rolling machine, they can no longer process ingots into corresponding items.

And rolling machine can be completed without that fuel tank :P

![233](https://cloud.githubusercontent.com/assets/2989009/10551233/0e29acd8-744c-11e5-8269-3ec30d45a0b8.jpg)

**Comment by zmaster587** [comment]
I cannot replicate any material processing issue however it seems hologram blocks are treated like the real thing, allowing the machines to be built when the ghost blocks are down and a real controller is placed

**Comment by wormzjl** [comment]
ummm my bad, forgot to turn on the machine switch after building it.
However, I still cannot use titanium ingots from techreborn mod to make stuffs, is it a exception or a bug?

**Comment by zmaster587** [comment]
Load order bug, apparently techReborn doesn't register it's ores until after preinit.  I'll just move the machine recipe loader to postInit in case somebody else does this as well.

**Comment by zmaster587** [comment]
fixed in 3.0.1
