### ISSUE TITLE
crash on logging out then in

### ISSUE THREAD

**Issue by zmaster587** [zmaster587/AdvancedRocketry#200]
InsanityPie

Not sure if it's something stupid with my game but im having this issue where I start a world and enter just fine. Play a while, then after exiting the world then going to play it later I always get these:
"The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
 and
"The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded." and just kicks me back to the title screen.

The log says the problem is something to do with the game being unable to unregister dimension 256 since no provider was registered. If you need the part of my log that shows the full error just let me know. And yes, I tried with only advance rocketry and 1 RF powered mod to see if it was a mod conflict and got the exact same error and the inability to enter a played on world.
Im using the most recent version, 0.8.0

**Comment by TheGuyRunningSouth** [comment]
I'm experiencing a similar issue involving dimensions but since I removed
Compact Machines the game no longer includes a dimension ID in the crash
report, just that it's something at unregister.
