### ISSUE TITLE
[BUG] Bipropellant fuel - fuel calculation

### ISSUE THREAD

**Issue by tabr** [zmaster587/AdvancedRocketry#2001]
## Version of Advanced Rocketry
latest

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
0.4.2-75

## Version of Minecraft
1.12

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.

## Description of the problem

When use a Bipropellant fuel, it seems to be when AR is calculating fuel (in Bi-fuel) as a part of all capacity(fuel+oxidizer). But Monitoring station(and other) gets "fuel part" and can start rocket BEFORE it will fully fueled.
So rocket turns back.

**Comment by voidsong-dragonfly** [comment]
I'm a little confused by what you mean... could you try and explain it more clearly?

**Comment by tabr** [comment]
Mono rocket has only 1 tank: fuel.
Bi has two tanks: fuel+oxi.
Rocket monitoring station gets:
getFuel(FuelType fuelType) {return (int) (stats.getFuelCapacity(fuelType)...
So if oxi tanks is not fulled, RM thinks all ok and starts rocket.
But there is not oxi, so rocket turns back.
I thins the problem is:
TANK=FUEL+OXI
And sometimes there is checks getCapacity(FUEL) and sometimes getCapacity(TANK).

**Comment by tabr** [comment]
I've made some checks and a problem may be in server software.
Will check more and re-open when gather more info.
