### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2005]
## Version of Advanced Rocketry
1.16.5-1.7.1

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
1.16.5-1.0.1

## Version of Minecraft
1.16.5

## Crash report and log, or VisualVM snapshot (if applicable)
https://paste.ee/p/7MFIM

## Description of the problem
Crash at startup

**Comment by DIO-CAMELOT** [comment]
[crash-2021-03-18_19.59.36-fml.txt](https://github.com/zmaster587/AdvancedRocketry/files/6164362/crash-2021-03-18_19.59.36-fml.txt)

**Comment by DIO-CAMELOT** [comment]
The same problem.

**Comment by Danxv33** [comment]
I also crash on startup. Similar crash logs.
https://pastebin.com/fS0zrB25

**Comment by slyd0x** [comment]
Similar crash for me
[crash-2021-03-18_18.41.02-fml.txt](https://github.com/zmaster587/AdvancedRocketry/files/6166219/crash-2021-03-18_18.41.02-fml.txt)

**Comment by EnderMelody** [comment]
[latest.log](https://github.com/zmaster587/AdvancedRocketry/files/6167819/latest.log)
same crash, here is log instead

**Comment by Warbringer12** [comment]
got same crash too
[latest.log](https://github.com/zmaster587/AdvancedRocketry/files/6167847/latest.log)
[crash-2021-03-18_17.22.30-fml.txt](https://github.com/zmaster587/AdvancedRocketry/files/6167848/crash-2021-03-18_17.22.30-fml.txt)

**Comment by dmodoomsirius** [comment]
https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/3244421
