### ISSUE TITLE
space suit crash

### ISSUE THREAD

**Issue by Warbringer12** [zmaster587/AdvancedRocketry#2006]
## Version of Advanced Rocketry
1.16.5-1.7.1-1

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.16.5-1.0.1

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] N

## Description of the problem
equipped space suit causes crashes
[crash-2021-03-18_22.12.05-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/6168761/crash-2021-03-18_22.12.05-client.txt)
[latest.log](https://github.com/zmaster587/AdvancedRocketry/files/6168762/latest.log)

**Comment by zmaster587** [comment]
Fixed
