### ISSUE TITLE
fuel loader rendering screen error

### ISSUE THREAD

**Issue by Warbringer12** [zmaster587/AdvancedRocketry#2007]
## Version of Advanced Rocketry
1.16.5

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.16.5-1.0.1

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] N

[crash-2021-03-18_22.17.19-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/6168769/crash-2021-03-18_22.17.19-client.txt)
[2021-03-18-1.log](https://github.com/zmaster587/AdvancedRocketry/files/6168772/2021-03-18-1.log)

## Description of the problem
right click fuel loader

**Comment by zmaster587** [comment]
Fixed in libvulpes
