### ISSUE TITLE
JEI don't open with AR installed

### ISSUE THREAD

**Issue by hodo1962** [zmaster587/AdvancedRocketry#2008]
Versions: 
* AdvancedRocketry-1.16.5-1.7.1-1-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [] N

## Version of LibVulpes
 LibVulpes-1.16.5-1.0.1-universal

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] Y
- [] N
>If Y, what is the MINIMUM set of mods required.
Mods:
  AdvancedRocketry-1.16.5-1.7.1-1-universal
  jei-1.16.5-7.6.1.75
  LibVulpes-1.16.5-1.0.1-universal
  Forge 36.1.1

## Crash report and log, or VisualVM snapshot (if applicable)
No crash occured.

## Log:
https://paste.ee/p/TkUbI

## Description of the problem
After I've installed AR and LibVulpes, JEI didn't open anymore. I've made a clean installation only with JEI, AR and LibVulpes.
The problem only happened when AR is installed. With LibVulpes alone there is no problem.

**Comment by Danxv33** [comment]
I have this error as well.

**Comment by zmaster587** [comment]
I'm not quite sure what's going on with this one, I've fixed some issues with resource locations being uppercase.  Now there's no JEI related errors printing in the log and it still doesn't show.

I've gone so far as to rip out all references to JEI and all JEI support and it's still broken :/

**Comment by zmaster587** [comment]
might be something similar to this? https://github.com/mezz/JustEnoughItems/issues/2258

**Comment by zmaster587** [comment]
Yep, it was
