### ISSUE TITLE
Rocket immediately launches upon selecting destination in guidance computer (v0.8)

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [zmaster587/AdvancedRocketry#201]
Satellite bay, no seat. Not a lot else to say here.

**Comment by zmaster587** [comment]
can you send me a screenshot of your rocket setup?  And do you have any infrastructure connected to it?  Is this single player or on a server?  I've so far been unsuccessful in replicating this.

**Comment by TheGuyRunningSouth** [comment]
Does the fueling machine output a redstone signal when the rocket is full on fuel? Because I've noticed it's actually once the rocket is fully fueled, and my monitoring station is next to it.

(If that is what it is, can we get a UI button for monitoring station redstone sensitivity?)

**Comment by zmaster587** [comment]
yes, it does, and I'll look into adding that.
