### ISSUE TITLE
Crash at right click on seat

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2011]
## Version of Advanced Rocketry
1.16.5-1.7.1-3

## Version of LibVulpes
1.16.5-1-0-1-4

## Version of Minecraft
1.16.5

## Crash report and log, or VisualVM snapshot (if applicable)
https://paste.ee/p/pxPZk

## Description of the problem
Building a rocket in creative mode. Rightclick on seat. Crash.
I play on mac.

**Comment by zmaster587** [comment]
Fixed by eca66b898d0625bc3da192d7548beefca4839484
