### ISSUE TITLE
[1.16.5] Blocks not dropping when broken

### ISSUE THREAD

**Issue by FynnWaelsing** [zmaster587/AdvancedRocketry#2014]
## Version of Advanced Rocketry
Advanced Rocketry 1.16.5-1.7.1-3 build -3 for 1.16.5

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes 1.16.5-1.0.1-5 build -5 for 1.16.5

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] Y
- [ ] 
>If Y, what is the MINIMUM set of mods required.
This occurs with only AR and LibVulpes

## Crash report and log, or VisualVM snapshot (if applicable)
Debug log: https://pastebin.com/iMzqyF87

## Description of the problem
Breaking the LibVulpes ores, blocks, and numerous AR machines drops nothing. Confirmed with a variety of different pickaxes.

**Comment by zmaster587** [comment]
Might be a lack of loot tables, ugh... 1.13 - 1.16 changed a lot of things.

**Comment by thetunkery** [comment]
> Might be a lack of loot tables, ugh... 1.13 - 1.16 changed a lot of things.

Using latest version of Advanced Rocketry and LibVulpes for 1.16 as of posting this comment, it seems there are no game ticks occurring, meaning blocks do not drop items, fluids do not flow, mobs do not move etc.

**Comment by FynnWaelsing** [comment]
I did not have the ticking issue described above. All other game behaviors were working like normal besides the busted loot tables

**Comment by hodo1962** [comment]
> 
> 
> > Might be a lack of loot tables, ugh... 1.13 - 1.16 changed a lot of things.
> 
> Using latest version of Advanced Rocketry and LibVulpes for 1.16 as of posting this comment, it seems there are no game ticks occurring, meaning blocks do not drop items, fluids do not flow, mobs do not move etc.

I have the same problem. Think you are right. The generation of chunks stops after a while and interaction with the world is not possible anymore. From Waila mod i've got the message "Waiting for server". From this moment on, i couldn't save the game and i have to kill the MC - task manually. With LibVulpes installed alone (without AR), the problem doesn't occure. So i think that this isn't a problem of the loot tables alone. I think we have two different bugs here. I'll make a new issue later.

![2021-03-22_13 04 21](https://user-images.githubusercontent.com/69686049/111993568-10f60780-8b17-11eb-8460-68ef6578e950.png)

**Comment by prjohns** [comment]
> > > Might be a lack of loot tables, ugh... 1.13 - 1.16 changed a lot of things.
> > 
> > 
> > Using latest version of Advanced Rocketry and LibVulpes for 1.16 as of posting this comment, it seems there are no game ticks occurring, meaning blocks do not drop items, fluids do not flow, mobs do not move etc.
> 
> I have the same problem. Think you are right. The generation of chunks stops after a while and interaction with the world is not possible anymore. From Waila mod i've got the message "Waiting for server". From this moment on, i couldn't save the game and i have to kill the MC - task manually. With LibVulpes installed alone (without AR), the problem doesn't occure. So i think that this isn't a problem of the loot tables alone. I think we have two different bugs here. I'll make a new issue later.
> 
> ![2021-03-22_13 04 21](https://user-images.githubusercontent.com/69686049/111993568-10f60780-8b17-11eb-8460-68ef6578e950.png)

This type of issue is usually caused be the following:

1.15+ worldgen is handled off-thread, where the main thread pauses while waiting for worldgen thread to process.

Mod-related worldgen may call methods which require to be run on the main thread, or after the chunk is fully generated. In either of these two cases, the worldgen thread then pauses and waits for the main thread to hand back the result. This causes a deadlock and the freeze as seen above.

The Solution I used for my mods: 

Check all code which runs during world-gen, and ensure that it only runs when the ChunkStatus is at the appropriate stage. For things that need a full chunk, use the MinecraftServer's execute method to schedule the update when it gets to the main thread.

**Comment by hodo1962** [comment]
This problem seems to be solved in the newest version. I've tested this with MC dimensions and RFTools dimensions.

**Comment by FynnWaelsing** [comment]
Do you mean the ticking issue? Because the loot tables are still busted in the latest version (Advanced Rocketry 1.16.5-1.7.1-4 build -4 for 1.16.5 and LibVulpes 1.16.5-1.0.1-6 build -6 for 1.16.5).

Debug (just for completion's sake): https://pastebin.com/reyFdpir

**Comment by hodo1962** [comment]
> 
> 
> Do you mean the ticking issue? Because the loot tables are still busted in the latest version (Advanced Rocketry 1.16.5-1.7.1-4 build -4 for 1.16.5 and LibVulpes 1.16.5-1.0.1-6 build -6 for 1.16.5).
> 
> Debug (just for completion's sake): https://pastebin.com/reyFdpir

Yes i mean the ticking issue. That's the reason why i haven't made a new issue for that.

**Comment by FynnWaelsing** [comment]
This appears to be fixed in the latest LibVulpes (LibVulpes 1.16.5-1.0.1-8 build -8 for 1.16.5) and AR (Advanced Rocketry 1.16.5-1.7.1-5 build -5 for 1.16.5) versions
