### ISSUE TITLE
Nothing happens with click on „select dst“

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2016]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-1.7.1-4-universal.jar

## Version of LibVulpes
LibVulpes-1.16.5-1.0.1-6-universal.jar

## Version of Minecraft
1.16.5

## Crash report and log, or VisualVM snapshot place to put them
> https://paste.ee/p/WJn2v

## What happens?
With click on "select dst" nothing happens

**Comment by criv5** [comment]
Been having same thing as well.

**Comment by zmaster587** [comment]
Copying my last comment from #2020 here for organizational purposes:

I've not had much luck with replicating the Select Dst button not working in single player on my end, is this in single player, multiplayer? Are there chips in the rocket at all?

**Comment by agentwolf88** [comment]
In this video can u see what i do. Singleplayer.

https://www.youtube.com/watch?v=qgtCGtP9Y60

**Comment by zmaster587** [comment]
Turns out the issue only happens OUTSIDE the development environment, likely this:
https://pastebin.com/079X1NJN

**Comment by agentwolf88** [comment]
Ok, is there a way to fix it temporary?

**Comment by zmaster587** [comment]
No there's not, because it's a code problem in libvulpes, but I'll be pushing a new release out today probably within the next hour or two with another round of patches.
