### ISSUE TITLE
Advanced Rocketry Enchantment Crashes Server

### ISSUE THREAD

**Issue by Arkaethen** [zmaster587/AdvancedRocketry#2017]
## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.16.5-1.0.1-6-universal

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
Unknown, sorry

## Crash report and log, or VisualVM snapshot (if applicable)
https://pastebin.com/bXwm4WSu

## Description of the problem
Crashes server due to attempted spawn of zombie with Advanced Rocketry enchantment

**Comment by Darkfiend009** [comment]
Can confirm this happening with my server as well. The crash log is below:

https://pastebin.com/mC4wAC7A
