### ISSUE TITLE
Error in log about Crafting Recipe when loading the game

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [zmaster587/AdvancedRocketry#2018]
## Version of Advanced Rocketry
1.7.0-240

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
0.4.2-75

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y

## Crash report and log, or VisualVM snapshot (if applicable)
Log: [Gist](https://gist.github.com/ALongStringOfNumbers/b923700bc11a8493867f18e557164d67)

## Description of the problem
When loading up the game, this error populates in the log.
It seems like the key `S` is not specified at https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/resources/assets/advancedrocketry/recipes/blockfueltank_alt.json

**Comment by zmaster587** [comment]
The alt recipe was removed in a more recent build in version 2.0.0 (sorry about taking so long to get back)
