### ISSUE TITLE
Warning in log about some Config default gases are not spawnable

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [zmaster587/AdvancedRocketry#2019]
## Version of Advanced Rocketry
1.7.0-240

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
0.4.2-75

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N

## Crash report and log, or VisualVM snapshot (if applicable)
Log: [Snippet](https://gist.github.com/ALongStringOfNumbers/38876659bf8d3efefaa73418fb382da6)
Log: [Full](https://gist.github.com/ALongStringOfNumbers/bfdea4db0eb41736af03f87026af02cb)

## Description of the problem
The log states that gases registered in the config by default do not work as spawnable Fluids. The declarations in the config should be fixed so that they are workable, or they should be removed from the defaults.

**Comment by voidsong-dragonfly** [comment]
Hello! I know about this, I wrote that system. Yes, it will throw a few errors on load, but without it we cannot provide default compat to some mods gasses for spawning. That is why they are there regardless of whether they give errors or not, as they are default compat There is no bug, and no reason to fix it - after all, the way for the user (who actually notices the output, which is very few) to fix it is to simply remove them - which is both easy and not required for the game to start. Those few who notice it can simply fix it themselves.

**Comment by voidsong-dragonfly** [comment]
Removed actually pertinent log errors in 2.0.0. These stay because they are not a bug
