### ISSUE TITLE
Second load of world crashs and "luna" planet is deleted in planetDefs.xml

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2020]
## Version of Advanced Rocketry
Advanced Rocketry 1.16.5-1.7.1-4 build -4 for 1.16.5

## Version of LibVulpes
LibVulpes 1.16.5-1.0.1-6 build -6 for 1.16.5

## Version of Minecraft
1.16.5

## Crash report
https://paste.ee/p/JYmfa

## Description of the problem
Create a world, save world, load second time, crash. After crash in planetDefs.xml (in saves folder) the dimension "luna" is deleted.

**Comment by zmaster587** [comment]
Luna vanishing should be fixed by 0e9d3ea068337b3440cc8bcdfc14b48c893d4594

**Comment by zmaster587** [comment]
There were a bunch of changes involving syncing planet data in both single and multiplayer, one of those may have fixed this issue, could you try AdvancedRocketry-1.16.5-1.7.1-5 and LibVulpes 1.16.5-1.0.1-8?

**Comment by agentwolf88** [comment]
Second load works now. Luna planet will not deleted.

**Comment by agentwolf88** [comment]
But the "Select Dst" button does not working.

**Comment by zmaster587** [comment]
I've not had much luck with replicating the Select Dst button not working in single player on my end, is this in single player, multiplayer?  Are there chips in the rocket at all?

**Comment by zmaster587** [comment]
Actually, lets move this to #2016 to keep things cleaner
