### ISSUE TITLE
[1.12.2] crash and corruption of world when teleporting to wrong coordinates on space station dimension

### ISSUE THREAD

**Issue by Alessandro404** [zmaster587/AdvancedRocketry#2023]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-240-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y   (I guess its the beta i'm playing)
- [] N

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [] Y
- [x] N cannot teleport without other mods
>If Y, what is the MINIMUM set of mods required.

## Crash report and log, or VisualVM snapshot (if applicable)
https://pastebin.com/B2n0iWtT

## Description of the problem
This crash was with my modpack because I used a mod item for changing coordinates and  teleporting around. My guess is, in places where there is not a generated space station, the mod cannot understand what kind of sun brightness there is and crashes. Maybe add a fallback? This was not a problem in earlier version of the mod.

**Comment by voidsong-dragonfly** [comment]
[AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/6212512/AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip)
Does this LibVulpes + AR combination work for you? Be warned that it will break some multiblocks, and you will NEED  to make a backup if you want to use it in a survival world if you want to downgrade.
[LibVulpes-1.12.2-0.4.2-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/6212559/LibVulpes-1.12.2-0.4.2-universal.jar.zip)

**Comment by Alessandro404** [comment]
Now the game kicks me out of the dimension if none has been created correctly.
Also, with a built structure but in a wrong coordinate, the game now places you in the "center" of the space dimension. I guess its a safe spot? 
It seems to be working good.

**Comment by voidsong-dragonfly** [comment]
Yes, it kicks you out of the dimension without any stations to send you to. Otherwise it sends you to the spawn point of the station (the same place you spawn if you fall out of the world in a space station dimension).

**Comment by Alessandro404** [comment]
Will this version that you gave me be upgradeable to the next curse forge version?

**Comment by voidsong-dragonfly** [comment]
Yes, it will be. It's essentially the next CF version, probably minus a few fixes.

**Comment by Alessandro404** [comment]
Thank you for fixing this bug and for your help!
