### ISSUE TITLE
Rocket GUI Bug

### ISSUE THREAD

**Issue by Gaminguide1000** [zmaster587/AdvancedRocketry#2028]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-232-universal
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: zmaster587.advancedRocketry.world.util.WorldDummy cannot be cast to net.minecraft.client.multiplayer.WorldClient
Exit-Code: -1

## Description of the problem
Build a Rocket, then add 2 or more Satelite Bays. 
Then open the GUI of the Rocket, (Shift & Right Click), then open one of the Bays and put a Satelite in it (i dont know if you have to put one in it). Then just close the GUI, and open it again, go to another Satelite Bay , and open it. Everytime i tried, it crashed. Maybe you have to start the Rocket sometimes. The rocket was full with fuel.

**Comment by voidsong-dragonfly** [comment]
Are you using any nonstandard not-pure-Forge server software?

**Comment by Gaminguide1000** [comment]
Im just using the Forge Version, from the Forge installer.
In Singleplayer & Multiplayer.

**Comment by zmaster587** [comment]
Could you post the full crash report?
The exception reason alone isn't all that helpful for tracking it down because the list that's usually under it is what tells us WHERE in the code the problem is, `Error: java.lang.ClassCastException: zmaster587.advancedRocketry.world.util.WorldDummy cannot be cast to net.minecraft.client.multiplayer.WorldClient` only tells us the why and narrows it down to a few million lines it could be on. 

The list under it would narrow the location of the actual exception down to 1 line and will give us the context to get an understanding of what the program was doing at the time.

**Comment by Gaminguide1000** [comment]
> Could you post the full crash report?
> The exception reason alone isn't all that helpful for tracking it down because the list that's usually under it is what tells us WHERE in the code the problem is, `Error: java.lang.ClassCastException: zmaster587.advancedRocketry.world.util.WorldDummy cannot be cast to net.minecraft.client.multiplayer.WorldClient` only tells us the why and narrows it down to a few million lines it could be on.
> 
> The list under it would narrow the location of the actual exception down to 1 line and will give us the context to get an understanding of what the program was doing at the time.

Sorry for the late reply.
Here is it:
Edit: Im now using the newest Version of LibVulpes & Advanced Rocketry.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.12.0.2_Forge_1.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.4.0.1_Forge_1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/30/21 7:48 PM
Description: Unexpected error

java.lang.ClassCastException: zmaster587.advancedRocketry.world.util.WorldDummy cannot be cast to net.minecraft.client.multiplayer.WorldClient
	at xaero.map.MapProcessor.setMainValues(MapProcessor.java:1109)
	at xaero.map.events.Events.renderTick(Events.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_765_Events_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at xaero.map.MapProcessor.setMainValues(MapProcessor.java:1109)
	at xaero.map.events.Events.renderTick(Events.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_765_Events_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Gaminguide1000'/407, l='', x=-14.71, y=67.00, z=211.17]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (116,64,100), Chunk: (at 4,4,4 in 7,6; contains blocks 112,0,96 to 127,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1276815 game time, 880064 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 45 total; [EntityCow['Cow'/136, l='MpServer', x=16.24, y=62.00, z=208.49], EntitySheep['Sheep'/137, l='MpServer', x=12.45, y=62.00, z=210.26], EntityCow['Cow'/138, l='MpServer', x=12.45, y=62.00, z=209.36], EntitySheep['Sheep'/139, l='MpServer', x=17.43, y=62.00, z=211.51], EntityCow['Cow'/140, l='MpServer', x=17.55, y=62.00, z=210.31], EntitySheep['Sheep'/141, l='MpServer', x=17.06, y=62.00, z=212.55], EntityCow['Cow'/142, l='MpServer', x=14.49, y=62.00, z=211.61], EntityCow['Cow'/143, l='MpServer', x=14.31, y=62.00, z=212.55], EntityCow['Cow'/145, l='MpServer', x=13.43, y=62.00, z=210.68], EntitySheep['Sheep'/147, l='MpServer', x=18.55, y=62.00, z=209.51], EntityCow['Cow'/148, l='MpServer', x=17.95, y=62.00, z=212.46], EntityCow['Cow'/149, l='MpServer', x=18.55, y=62.00, z=207.45], EntitySheep['Sheep'/150, l='MpServer', x=13.77, y=62.00, z=207.45], EntityCow['Cow'/151, l='MpServer', x=12.45, y=62.00, z=208.36], EntityCow['Cow'/152, l='MpServer', x=18.55, y=62.00, z=211.47], EntityCow['Cow'/153, l='MpServer', x=15.23, y=62.00, z=212.55], EntityCow['Cow'/154, l='MpServer', x=13.43, y=62.00, z=211.63], EntityCow['Cow'/155, l='MpServer', x=15.40, y=62.00, z=210.51], EntityCow['Cow'/156, l='MpServer', x=16.63, y=62.00, z=207.49], EntityVillager['Villager'/160, l='MpServer', x=19.31, y=61.00, z=201.50], EntitySheep['Sheep'/161, l='MpServer', x=16.39, y=62.00, z=209.76], EntityCow['Cow'/162, l='MpServer', x=15.40, y=62.00, z=211.52], EntityCow['Cow'/163, l='MpServer', x=14.70, y=62.00, z=207.55], EntitySheep['Sheep'/164, l='MpServer', x=14.51, y=62.00, z=209.56], EntityVillager['Villager'/165, l='MpServer', x=15.84, y=61.00, z=202.42], EntityCow['Cow'/166, l='MpServer', x=16.47, y=62.00, z=211.40], EntitySheep['Sheep'/167, l='MpServer', x=18.55, y=62.00, z=207.45], EntitySheep['Sheep'/169, l='MpServer', x=18.55, y=62.00, z=208.52], EntityPlayerSP['Gaminguide1000'/407, l='', x=-14.71, y=67.00, z=211.17], EntitySheep['Sheep'/170, l='MpServer', x=16.18, y=62.00, z=212.55], EntitySheep['Sheep'/171, l='MpServer', x=12.45, y=62.00, z=212.33], EntityCow['Cow'/172, l='MpServer', x=13.37, y=62.00, z=208.38], EntityPig['Pig'/173, l='MpServer', x=15.65, y=62.00, z=207.07], EntityCow['Cow'/174, l='MpServer', x=12.45, y=62.00, z=207.45], EntitySheep['Sheep'/175, l='MpServer', x=13.35, y=62.00, z=212.55], EntitySheep['Sheep'/176, l='MpServer', x=17.33, y=62.00, z=209.33], EntityPig['Pig'/177, l='MpServer', x=17.62, y=62.00, z=207.60], EntityCow['Cow'/178, l='MpServer', x=18.55, y=62.00, z=210.49], EntityPig['Pig'/179, l='MpServer', x=12.45, y=62.00, z=211.36], EntitySquid['Squid'/1988, l='MpServer', x=-57.50, y=53.00, z=180.50], EntityCreeper['Creeper'/1989, l='MpServer', x=-59.50, y=15.00, z=202.50], EntityZombie['Zombie'/1990, l='MpServer', x=-59.12, y=69.00, z=203.68], EntitySpider['Spider'/1992, l='MpServer', x=-59.50, y=9.00, z=258.50], EntityCreeper['Creeper'/1995, l='MpServer', x=-62.50, y=9.00, z=257.50], EntityRocket['Rocket'/125, l='MpServer', x=-17.50, y=67.00, z=211.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 531948216 bytes (507 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                          | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore              | 1                 | minecraft.jar                                   | None                                     |
	| LCHIJA | xaerominimap_core                 | 1.12.2-1.0        | minecraft.jar                                   | None                                     |
	| LCHIJA | xaeroworldmap_core                | 1.12.2-1.0        | minecraft.jar                                   | None                                     |
	| LCHIJA | bspkrscore                        | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar          | None                                     |
	| LCHIJA | treecapitator                     | 1.43.0            | [1.12]TreeCapitator-client-1.43.0.jar           | None                                     |
	| LCHIJA | libvulpes                         | 0.4.2.-75         | LibVulpes-1.12.2-0.4.2-75-universal.jar         | None                                     |
	| LCHIJA | advancedrocketry                  | 1.7.0.-232        | AdvancedRocketry-1.12.2-1.7.0-232-universal.jar | None                                     |
	| LCHIJA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2444        | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar   | None                                     |
	| LCHIJA | buildcraftlib                     | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftcompat                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                     | None                                     |
	| LCHIJA | jei                               | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHIJA | enderio                           | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | ctm                               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCHIJA | twilightforest                    | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCHIJA | conarm                            | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar                      | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | cyberware                         | 0.2.11.26         | cyberware-1.12.2-0.2.11.26.jar                  | None                                     |
	| LCHIJA | enderiobase                       | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiozoo                        | 5.2.66            | EnderIO-zoo-1.12.2-5.2.66.jar                   | None                                     |
	| LCHIJA | eyemod                            | 1.1.0             | EyeMod-Mod-1.12.2.jar                           | None                                     |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCHIJA | psf                               | 0.2.1             | practical-space-fireworks-0.2.1.8.jar           | None                                     |
	| LCHIJA | rild                              | 1.0.0             | Rild Mod.jar                                    | None                                     |
	| LCHIJA | travelersbackpack                 | 1.0.35            | TravelersBackpack-1.12.2-1.0.35.jar             | None                                     |
	| LCHIJA | xaerominimap                      | 21.4.0.1          | Xaeros_Minimap_21.4.0.1_Forge_1.12.jar          | None                                     |
	| LCHIJA | xaeroworldmap                     | 1.12.0.2          | XaerosWorldMap_1.12.0.2_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.12.0.2_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
XaeroMinimapPlugin (Xaeros_Minimap_21.4.0.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8729' Renderer: 'Intel(R) UHD Graphics 620'
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/gamin/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 27.20.100.8729, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Sound Pack.zip, PVP Pack.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU 5405U @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8729
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by voidsong-dragonfly** [comment]
Okay, I think I know the problem. Xaero's assumes our WorldDummy (where the client is temporarily when they open rocket-contained inventories so they can access them) is WorldClient, and then the ClassCast happens.

**Comment by Gaminguide1000** [comment]
> Okay, I think I know the problem. Xaero's assumes our WorldDummy (where the client is temporarily when they open rocket-contained inventories so they can access them) is WorldClient, and then the ClassCast happens.

So this is a Problem from Xaero's Minimap/World Map?

**Comment by thexaero** [comment]
I'm going to fix this on my end very soon.

**Comment by Onii-133** [comment]
Were you guys able to find a fix for this? its making FTB:Interactions very frustrating to play. I have this identical crash, and I'm not sure how i would go about fixing it

**Comment by voidsong-dragonfly** [comment]
Xaero is fixing it on their end. Because of how we handle rocket entity inventories interaction we can't really.
