### ISSUE TITLE
(Suggestion) Hardcore space station configuration 

### ISSUE THREAD

**Issue by Tronzoid** [zmaster587/AdvancedRocketry#203]
In hardcore mode satellite boxes should be disabled so space stations would have to be launched using large rockets, so people couldn't send up super mega hyper ultra giant 1000x1000 youtuber-esque space stations in one go.

**Comment by DarkGuardsman** [comment]
I think the author is working on this by allowing stations to be sent up piece by piece. In which once the code is there a max size could be implemented for each piece. 

Also as a note you could have edited issue #202 instead of leaving it blank

**Comment by Tronzoid** [comment]
I accidently created it when I was making a page and I clicked "new issue"

**Comment by Tronzoid** [comment]
Space stations should really be launched in pieces, like in real life

**Comment by zmaster587** [comment]
The satellite boxes have always had limited size anyway, and the modules have the same limit.  16x32x16 if memory serves.

**Comment by zmaster587** [comment]
Added in 0.9.1
