### ISSUE TITLE
1.12.2 Launch crash

### ISSUE THREAD

**Issue by inspiiree** [zmaster587/AdvancedRocketry#2032]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-2.0.0-242-universal.jar
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-82-universal.jar  
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/tRsvNer8

## Description of the problem
Booting the game up.

**Comment by voidsong-dragonfly** [comment]
This is JAOPCA's fault, not ours. Go tell them our plate press class name got updated if they want to continue adding support for it as they did before.
