### ISSUE TITLE
[1.16.5] JEI integration not working, plate presser only crushes ores, not plates. 

### ISSUE THREAD

**Issue by SquirrelKiev** [zmaster587/AdvancedRocketry#2034]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-1.7.1-5-universal

## Have you verified this is an issue in the latest unstable build
- [x] Yes, probably

## Version of LibVulpes
LibVulpes-1.16.5-1.0.1-8-universal

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] Yes

## Crash report and log, or VisualVM snapshot (if applicable)
https://paste.ee/p/soKRW

## Description of the problem
JEI support doesn't work, console floods with errors, and when an Iron Block is placed under the press and has redstone power, nothing happens. Ore doubling works however. 
Maybe recipes are broken?

**Comment by zmaster587** [comment]
Ugh... forgot to commit the libvulpes changes that fix JEI integration, hold on

**Comment by SquirrelKiev** [comment]
JEI works, but you still can't make iron plates using the plate press.
