### ISSUE TITLE
Rocket wont Build says:Not Enough Fuel Capacity

### ISSUE THREAD

**Issue by PortTNT** [zmaster587/AdvancedRocketry#2038]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-2.0.0-242-universal
AdvancedRocketry-1.12.2-1.7.0-240-universal
(Others not Tested)

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-82-universal

## Version of Minecraft
1.12.2 Forge-14.23.5.2855

## Does this occur without other mods installed
- [x] Y

>If Y, what is the MINIMUM set of mods required.
2 Advanced Rochetry and Libvulpes

Description of the problem:
I tried to build a Rocket (a Disign what works 100%) but the Rocket Assambly Station says "Not enough fuel Capacity" and it wont let me build the Rocket.
And the Fuel Can does not exist in this version(Libvulpes)

**Comment by voidsong-dragonfly** [comment]
Can I see a screenshot of the rocket? Also, the "buckets" that were tanks got replaced with actual Forge-system buckets.

**Comment by PortTNT** [comment]
I tried to find the reason of the bug, but i did not  find any clues how that coud happended.I hope that the Problem will be fixed soon.Thanks  Gesendet von Mail für Windows 10 Von: Sílfryí KalsandrynGesendet: Sonntag, 4. April 2021 15:39An: Advanced-Rocketry/AdvancedRocketryCc: PortTNT; AuthorBetreff: Re: [Advanced-Rocketry/AdvancedRocketry] Rocket wont Build says:Not Enough Fuel Capacity (#2038) Can I see a screenshot of the rocket? Also, the "buckets" that were tanks got replaced with actual Forge-system buckets.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by PortTNT** [comment]
Yea i think the Mod is broken…Mabe my version that i downloaded got curuppted. Gesendet von Mail für Windows 10 Von: Sílfryí KalsandrynGesendet: Sonntag, 4. April 2021 15:39An: Advanced-Rocketry/AdvancedRocketryCc: PortTNT; AuthorBetreff: Re: [Advanced-Rocketry/AdvancedRocketry] Rocket wont Build says:Not Enough Fuel Capacity (#2038) Can I see a screenshot of the rocket? Also, the "buckets" that were tanks got replaced with actual Forge-system buckets.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by voidsong-dragonfly** [comment]
I _cannot_ understand that, at all. The mod is unlikely to be broken, and if your download got corrupted you wouldn't be able to launch the game. Please respond on github from now on.

**Comment by PortTNT** [comment]
![2021-04-06_18 34 04](https://user-images.githubusercontent.com/81903182/113759774-c4651b80-9715-11eb-9a9d-95671e1b2cac.png)
![2021-04-06_18 33 56](https://user-images.githubusercontent.com/81903182/113759781-c5964880-9715-11eb-8669-0dfbfcb555aa.png)
![2021-04-06_18 20 15](https://user-images.githubusercontent.com/81903182/113759783-c62edf00-9715-11eb-95d1-e1a3031c0708.png)
![2021-04-06_18 17 58](https://user-images.githubusercontent.com/81903182/113759785-c62edf00-9715-11eb-9c9a-f66f6d1dfe4e.png)

Fuel Tanks are getting Scanned wrong.
And Fuel Station does not Work on Rockets.

AdvancedRocketry-1.12.2-2.0.0-242-universal.jar
LibVulpes-1.12.2-0.4.2-83-universal.jar

**Comment by voidsong-dragonfly** [comment]
First off, I call BS on you being on 2.0.0 . I changed how JEI was ordered in 2.0.0, and that is the old layout, as well as changing the item models. Please tell me your _actual_ version. Secondly, which tanks are those? You're probably matching the wrong tanks to the engines.

**Comment by PortTNT** [comment]
I used the same Tanks as Engines: Advanced Biopropellent Rocket Engine & Biopropellent Fuel Tank.
My version of the Mod is AdvancedRocketry-1.12.2-2.0.0-242-universal.jar
I found out that somtimes the scann glitch out and you have to replace one of the Tanks and it schows correct (This Works) but still i can put Fuel into the Rocket not Manuelly or by the Fueling Station that is the Problem.
![Mods Installed](https://user-images.githubusercontent.com/81903182/113763209-b5806800-9719-11eb-8825-5c3bdea54328.PNG)

**Comment by voidsong-dragonfly** [comment]
Do you have oxidizer tanks as well? Bipropellant rockets need both.

**Comment by PortTNT** [comment]
Now i tried now the Rocket Assambleling Machine shows me Clear for Liftoff and the Right Stats but still i can load the Rocket with Fuel.

**Comment by voidsong-dragonfly** [comment]
Well, what fuel are you using? Bipropellant rockets don't load with rocket fuel.

**Comment by PortTNT** [comment]
What Fuel do you need for Bipropellant Rockets?

**Comment by voidsong-dragonfly** [comment]
Hydrolox by default.

**Comment by PortTNT** [comment]
Still does not work...

**Comment by PortTNT** [comment]
The Rocket just smokes but does not take off.

**Comment by voidsong-dragonfly** [comment]
do you have both hydrogen and oxygen input?

**Comment by PortTNT** [comment]
Now but i still does not Work.

**Comment by PortTNT** [comment]
With the Normal Rockets (Monopropellant) and Rocket Fuel it Works.

**Comment by voidsong-dragonfly** [comment]
Also, what is your destination set to?

**Comment by PortTNT** [comment]
Luna

**Comment by PortTNT** [comment]
Wait Suddenly it Worke after i Reassembled the Rocket and Replaced the Fueling Stations it Works.

**Comment by PortTNT** [comment]
So as i see this.
This is not an Bug, the only thing thats wired is the Display bug
