### ISSUE TITLE
The electric arc furnace dont start

### ISSUE THREAD

**Issue by Alejandro2400** [zmaster587/AdvancedRocketry#2039]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-1.7.1-6-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.16.5-1.0.1-11-universal

## Version of Minecraft
1.16.5

## Does this occur without other mods installed

- [x] N
>If Y, what is the MINIMUM set of mods required.

## Description of the problem
Just finished building the furnace and test if it works. I set it on and starts. But seconds later it turns off. In a singleplayer world i did not have any problems, but in my multiplayer server yes, have this issue.

**Comment by zmaster587** [comment]
it looks like the packet to notify the server that the machine is enabled is getting dropped somehow.  Write is called for the machine enabled toggle packet, but read never is called on the server
