### ISSUE TITLE
Complains about performance

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#204]
I`m using 0.8.0
Got some Performance complains.

Launched rocket with many thrusters generate HUGE amount of Smoke Particles.
This particles impact FPS, dropping it from 240+ to 2-3

Microwave reciever got AWESOME animation, but this animation drops FPS from 240+ to 110+ (basicaly half it). Considering the fact Microwave reciever generate HUMILIATINGLY low amount of power you ether need alot more recievers, or just refuse in disgust of that type of powergen.

**Comment by zmaster587** [comment]
Microwave receiver has an option in the config to entirely disable it's
heat effect for performance reasons, the smoke particles should not
generate if particles are turned off/decreased in options.  I will look
into making it generate less particles if there are more engines.

Also, that's really nice framerate.  I wish I got even 90 in vanilla with
everything on low.

**Comment by zmaster587** [comment]
In response to the receivers generating low power: launch more satellites?
Currently each receiver has a max output of 3×4×11 = 132 RF/t.  I plan on
adding more powerful solar arrays for the satellites which should
significantly increase output.  (Looking at theoretical max being 10x or
100x the above number).

**Comment by DevTimur** [comment]
Resoursewise 132 RF/T is WAY too low power output. Other mod`s power output (I`m talking about various Solar aka Free power sources) is much more efficient, even considering they work only during daytime. Is there a way to tweak amount of power Solars generate? Config file?

Also, i didn`t test it, but is there a way to launch multiple Satelites in one rocket? Multiple bays?
Or maybe there a way to retrieve used Satelite rockets back, so i don`t lose a bunch of rocket building material only to launch one piny satelite?
Maybe every time rocket goes to "Space" (Even if it`s going to other planet) onboard satelite bay will launch satelite, so you don`t lose rocket materials?
Also, suggestion, how about you`ll make Solar array, using NBT (or Meta, idk how is correct) data to determine how much power it produce.
So it looks like:
You got 1 item "Solar Battery array", you put it on crafting table, and surround with Solar battery pieces, and Meta data of this Array increase. You can surround same array multiple times, to a certain Max, 256 pieces, for example. And this Array produce 256 rf/t (for example) And you can have up to 5 this arrays on single Satelite (6th slot for battery, Satelite don`t give power without battery in 0.8.0)

**Comment by zmaster587** [comment]
Going to add a power output multiplier to the config
