### ISSUE TITLE
Game crash after chunks are broken

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2040]
## Version of Advanced Rocketry
 AdvancedRocketry-1.16.5-1.7.1-6-universal

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
LibVulpes-1.16.5-1.0.1-12-universal

## Version of Minecraft
1.16.5

## Crash report 
[debug.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6257517/debug.log) (20MB)
[debug.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6258653/debug.log) (1MB, without other mods)
Crashlog does not generate

## Description of the problem
Create a world, log out, load world again, all is fine. 
Load this world again, build a rocket, log out.
Load this world third time, chunks are broken. Try to log out will crash the game.

**Comment by zmaster587** [comment]
What's the nature of the crash exactly and in what way are the chunks broken?
I'm not seeing anything unusual in the non-modded debug log

**Comment by agentwolf88** [comment]
Some chunks will not load, the rocket is not loaded and the game is freezing after click on "Save and Quit to Title".

https://youtu.be/YD4FhsoBfeg

Better video: https://youtu.be/pVbCzYQaqK0

**Comment by agentwolf88** [comment]
https://youtu.be/YD4FhsoBfeg

**Comment by greystarMC** [comment]
I started up a server and noticed I was getting failure to save chunks log messages. I started spawning new worlds, removing one mod at a time until I got to Advance Rocketry, I am not seeing failure to save chunk logs anymore. These issues could be related. I looked at one of the chunks, there wasn't really anything in it but ores.

**Comment by zmaster587** [comment]
@greystarMC Could you post the log containing the failure to save chunk error messages?

**Comment by agentwolf88** [comment]
It is only happen when a rocket is builded.

**Comment by greystarMC** [comment]
I think my issue may not be related to Advanced Rocketry. Let me see if I can reproduce it with just that mod.

**Comment by zmaster587** [comment]
> It is only happen when a rocket is builded.

@agentwolf88 with the one world with only AR/libvulpes in it, does it break every subsequent time you log in too?  Or do things start working again after you relaunch the game after it crashes?

**Comment by agentwolf88** [comment]
It will crash randomly. Sometimes it works, sometime it does not work.

**Comment by agentwolf88** [comment]
And yes, it will work again after restart the game.
