### ISSUE TITLE
Space Station Assembler false Writing

### ISSUE THREAD

**Issue by Gaminguide1000** [zmaster587/AdvancedRocketry#2041]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-2.0.0-242-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes

LibVulpes-1.12.2-0.4.2-83-universal
## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.

Only Advanced Rocketry & LibVulpes
## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem
If you look in the GUI of the Space Station Assembler, without a valid launchpad structure (this is important), and then make it valid, it says "Rocket Unscanned", without being / having a rocket
![Space Station Assembler Bug](https://user-images.githubusercontent.com/63616197/113617619-d469f600-9656-11eb-9bce-3fb62523d441.png)
heres the picture

**Comment by dmodoomsirius** [comment]
Newest build along with not filling in the minecraft version will not get you support. Stop cheating and ignoring the information that we requested. Fill those out or I will close this issue.

**Comment by zmaster587** [comment]
As per Dmod's comment, which newest build?  We're at a point where builds are coming out nearly every day, sometimes multiple times per day.
