### ISSUE TITLE
No recipe for liquid fuel tank

### ISSUE THREAD

**Issue by DragarX** [zmaster587/AdvancedRocketry#2045]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-1.7.1-8-universal.jar

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
LibVulpes-1.16.5-1.0.1-14-universal.jar

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
Unsure

>If Y, what is the MINIMUM set of mods required.

## Description of the problem
For some reason the liquid fuel tank has no recipe in JEI, nor does it work if i manually craft it.
![2021-04-06_20 11 36](https://user-images.githubusercontent.com/19335785/113695625-697ef480-9714-11eb-9d54-ab851c4203f5.png)

**Comment by zmaster587** [comment]
fixed at some point while merging the multiblock stuff into 1.16.5
