### ISSUE TITLE
Warp Core randomly malefunctions

### ISSUE THREAD

**Issue by SebastianPreker** [zmaster587/AdvancedRocketry#2047]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.1-120 universal
## Have you verified this is an issue in the latest unstable build
 N/A
## Version of LibVulpes
LibVulpes 1.12.2-0.3.0-45-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
no crash

## Description of the problem
I believe this issue is modpack related but I am not quite certain as I did run into this issue playing with the "vanilla" planetdefs.
The warpcore was for some planets working correctly and without a problem, however a few certain ones I could only visit ones, afterwards it just didnt warp. I checked the fuel etc and it was all functional I could even travel to planets further away from the actual target. I cannot reproduce this problem as it just happens randomly for random planets. Or, at least, I didnt find a pattern. I was playing FTB Continuum (newest version as of April the 6th 2021) when I ran into this issue again. It happend, like already mentioned in a single player world with only advanced rocketry and some other mods loaded before. 

The warpcore does say: "ready" and also displays fuel cost etc. But It just doesnt warp...

**Comment by voidsong-dragonfly** [comment]
Extremely old version. Update or we don't support your issue.
