### ISSUE TITLE
"Updating Screen Event" Bug

### ISSUE THREAD

**Issue by Gaminguide1000** [zmaster587/AdvancedRocketry#2049]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-2.0.0-242-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y (i think)

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-83-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
Advanced Rocketry & LibVulpes i think

## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroWorldMapPlugin (XaerosWorldMap_1.12.0.2_Forge_1.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.4.0.1_Forge_1.12.jar)
  CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-242-universal.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/7/21 1:18 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at zmaster587.advancedRocketry.tile.satellite.TileSatelliteBuilder.canAssembleSatellite(TileSatelliteBuilder.java:76)
	at zmaster587.advancedRocketry.tile.satellite.TileSatelliteBuilder.onInventoryButtonPressed(TileSatelliteBuilder.java:205)
	at zmaster587.libVulpes.inventory.modules.ModuleButton.actionPerform(ModuleButton.java:186)
	at zmaster587.libVulpes.inventory.GuiModular.func_146284_a(GuiModular.java:50)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at zmaster587.libVulpes.inventory.GuiModular.func_73864_a(GuiModular.java:88)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at zmaster587.advancedRocketry.tile.satellite.TileSatelliteBuilder.canAssembleSatellite(TileSatelliteBuilder.java:76)
	at zmaster587.advancedRocketry.tile.satellite.TileSatelliteBuilder.onInventoryButtonPressed(TileSatelliteBuilder.java:205)
	at zmaster587.libVulpes.inventory.modules.ModuleButton.actionPerform(ModuleButton.java:186)
	at zmaster587.libVulpes.inventory.GuiModular.func_146284_a(GuiModular.java:50)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at zmaster587.libVulpes.inventory.GuiModular.func_73864_a(GuiModular.java:88)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: zmaster587.libVulpes.inventory.GuiModular

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Gaminguide1000'/271, l='MpServer', x=301.86, y=91.00, z=266.51]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (196,64,116), Chunk: (at 4,4,4 in 12,7; contains blocks 192,0,112 to 207,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 224543 game time, 224543 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 20 total; [EntityDummy['entity.mountDummy.name'/320, l='MpServer', x=312.50, y=97.20, z=264.50], EntityDummy['entity.mountDummy.name'/321, l='MpServer', x=313.50, y=97.20, z=265.50], EntityPlayerSP['Gaminguide1000'/271, l='MpServer', x=301.86, y=91.00, z=266.51], EntityLatchedRenderer['unknown'/3, l='MpServer', x=8.50, y=65.00, z=8.50], EntityCow['Cow'/323, l='MpServer', x=252.84, y=74.00, z=320.65], EntityCreeper['Creeper'/2372, l='MpServer', x=243.50, y=27.00, z=262.50], EntityCyberZombie['Cyberzombie'/2437, l='MpServer', x=342.98, y=63.00, z=257.67], EntitySkeleton['Skeleton'/838, l='MpServer', x=344.50, y=56.00, z=326.50], EntityCreeper['Creeper'/2376, l='MpServer', x=243.50, y=27.00, z=261.50], EntityCreeper['Creeper'/1483, l='MpServer', x=283.50, y=27.00, z=346.50], EntityCow['Cow'/1484, l='MpServer', x=258.17, y=70.00, z=344.56], EntityCreeper['Creeper'/2188, l='MpServer', x=379.50, y=17.00, z=325.50], EntityFancyItemFrame['Manyullyn Item Frame'/275, l='MpServer', x=247.50, y=74.50, z=258.03], EntityInfHuman['Infected Human'/155, l='MpServer', x=256.21, y=72.00, z=224.70], EntitySkeleton['Skeleton'/1955, l='MpServer', x=372.50, y=36.00, z=330.50], EntityBat['Bat'/2486, l='MpServer', x=377.50, y=25.10, z=214.50], EntityCow['Cow'/312, l='MpServer', x=270.55, y=71.00, z=333.79], EntityWitch['Witch'/2041, l='MpServer', x=340.50, y=45.00, z=339.50], EntitySkeleton['Skeleton'/2234, l='MpServer', x=371.50, y=35.00, z=260.50], EntityDummy['entity.mountDummy.name'/319, l='MpServer', x=312.50, y=97.20, z=266.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/3, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 270081736 bytes (257 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G6_pre1 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                          | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore              | 1                 | minecraft.jar                                   | None                                     |
	| LCHIJA | creativecoredummy                 | 1.0.0             | minecraft.jar                                   | None                                     |
	| LCHIJA | xaerominimap_core                 | 1.12.2-1.0        | minecraft.jar                                   | None                                     |
	| LCHIJA | xaeroworldmap_core                | 1.12.2-1.0        | minecraft.jar                                   | None                                     |
	| LCHIJA | securitycraft                     | v1.8.21           | [1.12.2]+SecurityCraft+v1.8.21.jar              | None                                     |
	| LCHIJA | bspkrscore                        | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar          | None                                     |
	| LCHIJA | treecapitator                     | 1.43.0            | [1.12]TreeCapitator-client-1.43.0.jar           | None                                     |
	| LCHIJA | libvulpes                         | 0.4.2.-83         | LibVulpes-1.12.2-0.4.2-83-universal.jar         | None                                     |
	| LCHIJA | advancedrocketry                  | 2.0.0.-242        | AdvancedRocketry-1.12.2-2.0.0-242-universal.jar | None                                     |
	| LCHIJA | ctm                               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                     | None                                     |
	| LCHIJA | jei                               | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHIJA | thaumcraft                        | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| LCHIJA | enderio                           | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | twilightforest                    | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCHIJA | bhc                               | 2.0.3             | baubley-heart-canisters-1.12.2-2.0.3.jar        | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2444        | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar   | None                                     |
	| LCHIJA | buildcraftlib                     | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftcompat                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHIJA | carryon                           | 1.12.3            | carryon-1.12.2-1.12.3.15.jar                    | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | chiselsandbits                    | 14.33             | chiselsandbits-14.33.jar                        | None                                     |
	| LCHIJA | conarm                            | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar                      | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | creativecore                      | 1.10.0            | CreativeCore_v1.10.47_mc1.12.2.jar              | None                                     |
	| LCHIJA | cyberware                         | 0.2.11.26         | cyberware-1.12.2-0.2.11.26.jar                  | None                                     |
	| LCHIJA | enderiobase                       | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | enderiozoo                        | 5.2.66            | EnderIO-zoo-1.12.2-5.2.66.jar                   | None                                     |
	| LCHIJA | ichunutil                         | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | gravitygun                        | 7.1.0             | GravityGun-1.12.2-7.1.0.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHIJA | inventorypets                     | 2.0.12            | inventorypets-1.12-2.0.12.jar                   | None                                     |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCHIJA | neat                              | 1.4-17            | Neat+1.4-17.jar                                 | None                                     |
	| LCHIJA | opframe                           | 1.4.0             | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar         | None                                     |
	| LCHIJA | portalgun                         | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | psf                               | 0.2.1             | practical-space-fireworks-0.2.1.8.jar           | None                                     |
	| LCHIJA | rild                              | 1.0.0             | Rild Mod.jar                                    | None                                     |
	| LCHIJA | srparasites                       | 1.8.2             | SRParasites-1.12.2v1.8.2.jar                    | None                                     |
	| LCHIJA | tcinventoryscan                   | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10.jar      | None                                     |
	| LCHIJA | thaumicjei                        | 1.6.0             | ThaumicJEI-1.12.2-1.6.0-27.jar                  | None                                     |
	| LCHIJA | thaumicwaila                      | 1.12.2-0.0.2      | ThaumicWaila-1.12.2-0.0.2.jar                   | None                                     |
	| LCHIJA | trashcans                         | 1.0.8             | trashcans-1.0.8-mc1.12.jar                      | None                                     |
	| LCHIJA | travelersbackpack                 | 1.0.35            | TravelersBackpack-1.12.2-1.0.35.jar             | None                                     |
	| LCHIJA | xaerominimap                      | 21.4.0.1          | Xaeros_Minimap_21.4.0.1_Forge_1.12.jar          | None                                     |
	| LCHIJA | xaeroworldmap                     | 1.12.0.2          | XaerosWorldMap_1.12.0.2_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
XaeroWorldMapPlugin (XaerosWorldMap_1.12.0.2_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
XaeroMinimapPlugin (Xaeros_Minimap_21.4.0.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-242-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8729' Renderer: 'Intel(R) UHD Graphics 620'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/gamin/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 27.20.100.8729, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Sound Pack.zip, PVP Pack.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU 5405U @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8729
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

## Description of the problem
I just opend the Satelite Builder, put a Satelite  Cassis in it, put a Satelite Chip in the Sateliteprimaryfunction Slot, and pressed build. Then Minecraft just crashed and said something like "Updating Screen Event", and "Exit Code -1"
Edit: it happens with other like the fueling station

**Comment by Nick1st** [comment]
The players on my server also have this problem. I try to get the logs and upload them with additional information

**Comment by Nick1st** [comment]
It happens also when you put a "Biome changer remote" in the top right field of the "Satellite Builder" and click "BUILD". If all parts were valid, we were able to build the satellite.
