### ISSUE TITLE
world does not load with voxels

### ISSUE THREAD

**Issue by lag42** [zmaster587/AdvancedRocketry#205]
i just load a world and it kicks me back to the menu as usual when this type of error happens,
but i can't get them to work i read the launcher log and it seems to be mostly advanced rocketry and voxels but i can't figure out exactly what it is that makes this happen
see the launcher log below
[crashed.txt](https://github.com/zmaster587/AdvancedRocketry/files/482934/crashed.txt)

**Comment by zmaster587** [comment]
The crash itself appears to be originating from pricechecker/pricegaps from voxel, but because it unloads the world when it breaks, it tries to unregister the gas giant dimension as reported in #200.

**Comment by lag42** [comment]
thank you, is there any way i can disable gas giants and fix this?

**Comment by zmaster587** [comment]
I am skeptical disabling gas giants will fix it, but is worth a shot, use
an nbt editor to edit world/advancedrocketry/temp.dat and remove dim256

**Comment by lag42** [comment]
didn't work also that's just launcher spam apparently, it happens with 0.7.0d too here's a log of that
[truelog.txt](https://github.com/zmaster587/AdvancedRocketry/files/485132/truelog.txt)

**Comment by zmaster587** [comment]
I'm not even seeing AR in the stack trace, remove AR/libvulpes, and don't
change anything else  and see if this still occurs

**Comment by lag42** [comment]
doesn't happen, it's something between the two i'll go get purplicious_cow's attention

**Comment by capnkirok** [comment]
Yeah, it's definitely Voxels. It doesn't like the jackhammer. Looking now.

**Comment by capnkirok** [comment]
Fixed in 1.0.2
https://minecraft.curseforge.com/projects/voxels?gameCategorySlug=mc-mods&projectID=251175
