### ISSUE TITLE
setting overworldSkyOverride = false Does not turn off Render 1.16.5 bug

### ISSUE THREAD

**Issue by IchigoGames** [zmaster587/AdvancedRocketry#2050]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-1.7.1-8-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes 
LibVulpes-1.16.5-1.0.1-14-universal

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] Y 
- [ ] the way you ask this seems odd should i say yes or no yes it happens with no other mods installed

## Crash report and log, or VisualVM snapshot (if applicable)
N/A

## Description of the problem 
Config option to turn off custom sky render does not work setting it to false does not turn it off even setting all sky render and even setting advancedVFX to false does not turn this off

wanted to turn it off do to it not working with optfine-shaders the issue with config not workin happens with no other mods installed.

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/114115278-2190d680-98a8-11eb-99bd-602f88004f8c.png)
with is turned off as you can see its not off

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/114116705-c1e7fa80-98aa-11eb-86e0-4a3c48e1668e.png)
this is the optfine shader issue and reason for me wanting to turn off the sky render

**Comment by DragarX** [comment]
Can cofirm this bug in my case too.

**Comment by Ezoteric** [comment]
I can confirm that SEUS PTGI kinda works, it does have a sky but just a weird border.

![2021-04-09_23 37 44](https://user-images.githubusercontent.com/14137626/114243296-9b9a8b80-998c-11eb-9500-4c701068df86.png)

**Comment by Ezoteric** [comment]
Also chocapic works.
And i prolly can find more that do work so i guess its the way BSL for example handle things?

![2021-04-09_23 41 47](https://user-images.githubusercontent.com/14137626/114243675-490d9f00-998d-11eb-9a30-39b1794ebbf5.png)

**Comment by IchigoGames** [comment]
ya but just to be clear my issue is not that Shaders dont work its that the config option to turn off the custom sky does not work

**Comment by IchigoGames** [comment]
seus renewed works without any issues

**Comment by zmaster587** [comment]
Should fix both the station and planet sky toggles not working

**Comment by IchigoGames** [comment]
is the update for that coming out today was about to update pack but if it is ill wait.

**Comment by Ezoteric** [comment]
Fixed it for me :) 

(checked with building source)

**Comment by IchigoGames** [comment]
hopefully its out before i have to update


also who turned out the lights ? ohh darkmode looks good
