### ISSUE TITLE
Space Station Elavator

### ISSUE THREAD

**Issue by Gaminguide1000** [zmaster587/AdvancedRocketry#2051]
## Version of Advanced Rocketry

1.12.2-1.7.0-232

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
1.12.2-0.4.2-83

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
Adv Rocketry & Lib Vulpes

## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem

After building a space station, i wanted to build a space station elavator. So i build ône on the spacestation, and one on the earth. Then i just opened the GUI, theres no slot for a ID Chip (not the problem). In the GUI, there stood something like:"This thing needs a theth..." and the rest was covered by other stuff. I didnt thought anything so i tried to link both, but it said, it cant link bcause they are not in the same "geostationary orbit" So, my problems are:
1. You cant read the full text
2. How the hell do i make a "thether" ???
3. And is this "geostationary orbit" thing a bug, or did i do something wrong 
Is this just not supported at the moment or am i just stupid?

**Comment by voidsong-dragonfly** [comment]
You should be using the discord for this ask. Please acquire thineself towards it.

**Comment by MrEyeballs29** [comment]
For any user errors, you should go to Discord for guides and support.
