### ISSUE TITLE
Fluid Input/Output Hatch Bug

### ISSUE THREAD

**Issue by ColtonXan** [zmaster587/AdvancedRocketry#2056]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-2.0.0-10-universal, also tested on AdvancedRocketry-1.16.5-1.7.1-8-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.16.5-1.0.2-17-universal, also tested on LibVulpes-1.16.5-1.0.1-14-universal
## Version of Minecraft
1.16.5
## Crash report or log (if applicable)
N/A
## Description of the problem
Fluid Input & Output cannot receive or output fluids, even if done manually. Fluid Input appears to be stuck in a state of containing 1 mB of water while Fluid Output rapidly flickers between 1 mB of water and 0 mB of air. Problem persists even if the blocks are completely isolated.

The problem appears to exist exclusively on multiplayer servers, as I wasn't able to reproduce the bug in a singleplayer world.  The problem still persists even on fresh multiplayer servers and worlds. 

Other Mods Used: jei-1.16.5-7.6.1.75 (Just Enough Items). 
Forge Version: forge-1.16.5-36.1.4.

Here I would expect fluid output hatch to be empty after placing it down, but it is not, nor can it input or output fluids:
![Capture2](https://user-images.githubusercontent.com/5303565/114701486-7f7a4f80-9ce8-11eb-805f-7414b1b319ec.PNG)

**Comment by zmaster587** [comment]
Also note that putting a lava bucket in the input slot of a fluid input hatch adds lava instead.  Likely due to an issue in the fluid indicator module where an int is used for the fluid ID but a short is sent over the network.

**Comment by zmaster587** [comment]
To be fixed in libvulpes build 18
