### ISSUE TITLE
Crash by click on "up" in planet select gui.

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2057]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-2.0.0-10-universal.jar

## Version of LibVulpes
LibVulpes-1.16.5-1.0.2-18-universal.jar

## Version of Minecraft
1.16.5

## Crash report
https://paste.ee/p/q7MVM

## Description of the problem
Open planet select gui, click on "up". The problem is the clicking on the JEI buttons in background at the same time.

**Comment by zmaster587** [comment]
Does this issue occur with only AR, libvulpes, and JEI?  Or are there any additional mods needed?

If it doesn't crash with just AR, libvulpes, and JEI, does it crash if you add  ftb-gui-library-1605.2.1.40-forge.jar too?

**Comment by agentwolf88** [comment]
It crashs only with ftb-gui-librar.

**Comment by zmaster587** [comment]
hmm, ok, thanks.  Will take a take a peek.
