### ISSUE TITLE
Cannot launch

### ISSUE THREAD

**Issue by agentwolf88** [zmaster587/AdvancedRocketry#2058]
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-2.0.0-10-universal.jar

## Version of LibVulpes
LibVulpes-1.16.5-1.0.2-18-universal.jar

## Version of Minecraft
1.16.5

## Description of the problem
Press sspace to lift off, count down is going down..."Cannot launch: destination is not in the same planet system".
![2021-04-15_11 29 15](https://user-images.githubusercontent.com/9948479/114848503-0c073980-9ddf-11eb-9b57-5d4ef21ac411.png)
![2021-04-15_11 29 10](https://user-images.githubusercontent.com/9948479/114848519-0f9ac080-9ddf-11eb-8bc5-2881211a20ae.png)

**Comment by agentwolf88** [comment]
[debug.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6316845/debug.log)
[latest.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6316846/latest.log)

**Comment by zmaster587** [comment]
Confirmed issue, looking into it.
