### ISSUE TITLE
space elevator crashes game

### ISSUE THREAD

**Issue by FlyingPotato-131** [zmaster587/AdvancedRocketry#2059]
## Version of Advanced Rocketry
1.16.5-2.0.0-10

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N

## Version of LibVulpes
1.16.5-1.0.2-18

## Version of Minecraft
1.16.5 forge

## Does this occur without other mods installed
- [x] Y
- [ ] N

## Crash report and log, or VisualVM snapshot (if applicable)
latest.log https://pastebin.com/LvFrvEMw

## Description of the problem
when a linked space elevator is loaded in in the overworld the game crashes (doesn't crash on space stations)

**Comment by zmaster587** [comment]
Could you post the crash report or repost the latest.log (though preferably just the crash report)?  Im getting a "Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it."  on the pastebin you linked there.

**Comment by zmaster587** [comment]
Actually nevermind, I think i found the issue
