### ISSUE TITLE
Advanced Rocketry planet data save bug

### ISSUE THREAD

**Issue by Gaminguide1000** [zmaster587/AdvancedRocketry#2062]
## Version of Advanced Rocketry

AdvancedRocketry-1.12.2-2.0.0-242-universal
## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-83-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
Idk, but i think only AdvRocketry&LibVulpes

## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem

First of all: I have a custom PlanetDefs.xml (not mine). So, always after a while, the server console says: "[Server thread / FATAL] [advancedrocketry]: An error has occurred saving planet data,
this can happen if another mod causes the game to crash during game load. If the game has fully loaded, then this is a serious error, Advanced Rocketry data has not been saved. "There are no conflicts between different mods, nor does the game / server crash when I start it. should that be a "serious error".

**Comment by voidsong-dragonfly** [comment]
Yes, because it means your planetDefs has a _high_ chance of becoming so corrupt you cannot load your world.
