### ISSUE TITLE
Oxygen tanks not working + Chisels & Bits not being rendered.

### ISSUE THREAD

**Issue by KASTYAMBA** [zmaster587/AdvancedRocketry#2064]
## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes

LibVulpes 1.16.5-1.0.2-18 build -18

## Version of Minecraft

1.16.5

## Does this occur without other mods installed
- [x] N

## Description of the problem

Tested with and without other mods. The oxygen bar doesn't appear when wearing the spacesuit, and when you try to fuel it, the oxygen is being used in the gas charging pad but none of it ends up in the spacesuit's tanks.
Another issue is the one, I've seen before, and I believe it was fixed a while ago but, sadly, it's back for me and my friends. Chisels and bits carved blocks are invisible when you build the rocket.

**Comment by KASTYAMBA** [comment]
Screenshots related to the oxygen issue:
![2021-04-18_16 05 09](https://user-images.githubusercontent.com/56523457/115146837-fa34c900-a060-11eb-950d-171600f41b02.png)
![2021-04-18_16 05 20](https://user-images.githubusercontent.com/56523457/115146840-fb65f600-a060-11eb-863c-c62ea08e44f5.png)

**Comment by zmaster587** [comment]
Fixed O2 not filling the taks, the O2 bar not displaying onscreen

**Comment by zmaster587** [comment]
One report per issue please though, when there's multiple bug in a single issue it makes it harder to keep track.  The O2 tanks and stuff should be fixed now, but this really should have been two tickets.

**Comment by zmaster587** [comment]
For the chisel and bits aspect, see issue #2067
