### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by vizthex123** [zmaster587/AdvancedRocketry#2066]
## Version of Advanced Rocketry
1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
1.12.2-0.4.2-83-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Not sure

## Crash report and log, or VisualVM snapshot (if applicable)
Log: https://pastebin.com/yRi0Wctn
Crash Report: https://pastebin.com/VMbKaBX7

## Description of the problem
Whenever I load up the game, it crashes. It seems like the issue is with WrapUp, but they use pull requests for issues (why?) so I can't report it to them.

**Comment by MrEyeballs29** [comment]
that is not AR fault. it caused by mod interaction

**Comment by voidsong-dragonfly** [comment]
Old version.

**Comment by vizthex123** [comment]
I'm using the latest release of the mod. The latest beta still crashes the game.

**Comment by voidsong-dragonfly** [comment]
a) you need to be on the latest beta, period. b) with the latest of both JAOPCA and AR you should be fine.
