### ISSUE TITLE
Legs Upgrade does not go onto Leggings in 1.16

### ISSUE THREAD

**Issue by PancakeTAS** [zmaster587/AdvancedRocketry#2068]
## Version of Advanced Rocketry

Newest Alpha Build from Branch

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
Newest

## Version of Minecraft
1.16.5 

## Does this occur without other mods installed
- [x] Y

## Description of the problem

Bionic Legs Upgrade goes into Helmet, instead of Leggings

**Comment by zmaster587** [comment]
Fixed by cdce0509f07ace37e7de9ad366eb94c3a8fd482c
