### ISSUE TITLE
Some blocks in assembled rocket crash game.

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#207]
Ver. 0.6.8
Placed IC2 Trade-O-Mat at rocket (for testing)
After assembling rocket trad-o-mat disapeared (Become invisible)
When i shift click rocket, game crashed. Crashlog [here](http://pastebin.com/YLYxJU1Q)

Can you please make a whitelist config for blocks? So you can`t use inapropriate blocks in rocket. It will reduce accident crash A LOT! Maybe made it as an option, so i can add own blocks to whitelist (blacklist)

How can i disassemble this rocket now? Maybe add "Disassemble" button in Rocket terminal. or ever "Self-destruct" :-D

**Comment by zmaster587** [comment]
It's looking like ic2 does something unusual with how it's handling block
data, I'll look into it.
