### ISSUE TITLE
LibVulpes FluidUtils areFluidsSameType NPE

### ISSUE THREAD

**Issue by cyantifical** [zmaster587/AdvancedRocketry#2070]
After building a rocket, tried linking it to the fuelling station and it crashes with a null pointer exception. Interestingly, it returned the same crash both before i put the fuel into the fuelling station and after. I am seeing botania mentioned in the crash file but what exactly its referring to im not sure. Planetdefs are custom and probably not functional, I am yet to test (because I can't get there yet). After rejoining, the rocket is gone.

[Crash Log](https://pastebin.com/uuAbQgCM)

**Comment by zmaster587** [comment]
Same issue as #2065 fixed in libvulpes build 20
