### ISSUE TITLE
[BUG] Clientside Crash only on Multiplayer Server when trying to launch rocket

### ISSUE THREAD

**Issue by GamesGrandpa** [zmaster587/AdvancedRocketry#2072]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.16.5-2.0.0-10
## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>1.16.5-1.0.2-18
## Version of Minecraft
>Forge 1.16.5 36.1.4
## Does this occur without other mods installed
- [x] Y
>LibVulpes, Advanced Rocketry.
## Crash report or log or visualVM (if applicable)
Crash Report
VVV
https://pastebin.com/8hytS9uG
Log
VVV
https://pastebin.com/erqHsuYm

## Description of the problem
>Ok so when I try to launch a rocket to a space station in singleplayer, everything works fine. When I try to do this on a server, everyone on the server gets a client side crash.
On crash it claims that there is a missing registry entry of "rocketfx". I closed the server and dug through the config. I found advancedVFX, so I turned set that to false for both client and server. When I relaunched the server I found that the rocket had launched? I managed to land on the space station and it was all there. Every other time this crash has occurred, the rocket does nothing when I relog. I am simply in my seat right where I was. I don't know what to make of that tbh, hope this helps tho.

EDIT: I tried to recreate the rocket launching after logging back in but failed. Not sure what happened the first time...

**Comment by zmaster587** [comment]
it looks like the check to see if the rocket can go to its destination doesn't work on client only.  I'll get a fix in for that.

**Comment by zmaster587** [comment]
i've fixed the issue causing the crash in the report you submitted, as for the particle thing, it's looking like somehow they're all getting unregistered on the client but only in multiplayer.  I'll follow up on that one too.
