### ISSUE TITLE
[Mod Conflict] Overworld Ore Generation stops completely and other planets only generate ore from another mod

### ISSUE THREAD

**Issue by AccidentalBetaTester** [zmaster587/AdvancedRocketry#2075]
## Version of Advanced Rocketry
1.16.5-2.0.0-10-universal.jar

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.16.5-1.0.2-18-universal.jar

## Version of Minecraft
1.16

## Does this occur without other mods installed
No. I've tried deleting the "easy steel and more" mod, yet the issue persists. Ore generation does not cease if libvulpes is installed without Advanced Rocketry, but none of the Advanced Rocketry ores spawn. 

## Crash report or log or visualVM (if applicable)
N/A

## Description of the problem
In an existing modded 1.16 world, Installing Advanced Rocketry causes all Overworld Ore Generation to cease except for the ores added by Create Mod 0.3.1. These ores stop spawning in the Overworld but appear to be the only ores which spawn on other planets.

Possible mod conflicts that could be causing this issue:
https://www.curseforge.com/minecraft/mc-mods/easy-steel-forge/
EasySteel-1.16.4-1.2.13.jar - adds its own ores. Tried uninstalling. Result: existing world still does not generate ores. New world does not generate ores.

https://www.curseforge.com/minecraft/mc-mods/create
create-mc1.16.5_v0.3.1c.jar - adds its own ores. Did not try uninstalling as that would mess up the whole world I have.

https://www.curseforge.com/minecraft/mc-mods/extended-caves
extcaves-2.4.jar - adds block deposits like lavastone deeper underground. This generation is not affected.

https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
BiomesOPlenty-1.16.4-13.0.0.425-universal.jar - changes world generation by adding new biomes. I tested ore generation in Minecraft's Default Biomes to control for this.

**Comment by zmaster587** [comment]
if you create a world with only Advanced rocketry, libvulpes, and create, does the issue occur there too?

**Comment by AccidentalBetaTester** [comment]
@zmaster587 
No, the issue doesn't occur when creating a new world with those three.
It also doesn't occur when creating a new world with those three plus easy_steel mod. It might be caused by adding advanced rocketry to an existing world?

**Comment by zmaster587** [comment]
Could you double check in a new world if you can create it without AR, then add AR and goto a distant location to force generation of new chunks?  If it does break when you do that, that at least gives me something I can try to replicate and hopefully debug.

The whole issue is really confusing to me because ore generation is something that's registered every time the game starts, it doesn't look at save data at all.

**Comment by AccidentalBetaTester** [comment]
It seems to also work fine under those circumstances also. The other mods I'm using shouldn't be causing this, but I'll list them here:

1. Biomes O' Plenty - Tested ore generation on both modded and vanilla biomes just to make sure
2. Curios API (Forge) - shouldn't have an effect
3. Dungeon Crawl - adds structures but I don't think this could be the cause?
4. Dungeons Plus - adds structures but I don't think this could be the cause?
5. Easy Steel & More [FORGE} - doesn't seem to be the cause
6. ForgeEndertech - shouldn't have an effect
7. Scaling Health - shouldn't have an effect
8. Large Ore Deposits - does not have an effect, I tested it the same way as the other relevant ones like Easy Steel and Create
9. Silent Lib (silentlib) - adds some weapons and mob AI effects, shouldn't have an effect
10. Spawner Bug Fix - not relevant
11. Structure Gel API - library used by Structurize mod, I don't know a lot about this but don't *think* it should be the cause?
12. Structurize - Adds custom blocks for structures and some worldedit-like commands
13. U Team Core - appears to be mainly for inventory access for the Useful Backpacks mod
14. Useful Backpacks - adds large backpacks
15. Waystones - Adds teleporting waystones that can be crafted and placed, shouldn't have an effect
16. Wonderful Enchantments - adds enchantments, shouldn't have an effect
17. WorldEdit - adds world-editing commands, I don't think this has anything to do with this problem
18. XP Tome - can store XP in books, probably irrelevant
19. Advanced Rocketry - adding it to the existing mods is our problem
20. Balanced Enchanting - changes XP used by enchanting, shouldn't have an effect
21. Baubles - Reborn? - shouldn't have an effect
22. BetterEnd (Forge) - only affects the way the END dimension is generated
23. BountifulBaubles - shouldn't have an effect
24. Chisels & Bits - shouldn't have an effect
25. Create - We've verified this shouldn't be the cause
26. DisenchantingForge - allows disenchanting items, shouldn't have an effect
27. Extended Caves - possibly has an effect since it generates cave structures,
28. Just Enough Items (JEI) - shouldn't have an effect
29. LibVulpes - we've determined this isn't the issue
30. MineColonies - shouldn't have an effect, but I'm not as familiar with this mod
31. Optifine - shouldn't have an effect
32. Regrowth - basically mobs eat grass and heal hp from it, shouldn't have an effect
33. Valhelsia Structures - adds blocks and some structures like houses, shouldn't have an effect

**Comment by githubuser49** [comment]
> 31. Optifine - shouldn't have an effect

turn off fast math, that effects terrain generation and might be causing it because of easy steel. it should be located under "performance"

**Comment by zmaster587** [comment]
I'm kinda confused.
So if you add AR to a world containing create, libvulpes, and easy steel, the ore generates as expected?

Is there like a procedure you can follow and replicate that makes this issue occur starting from a new world?

Something along the lines of:
- Create new world with mod x,y, and z, 
- Explore a little
-  Add AR, now ore gen is broken.
