### ISSUE TITLE
Satellite Builder machine crash on build satellite

### ISSUE THREAD

**Issue by Sx-e** [zmaster587/AdvancedRocketry#2077]
## Version of Advanced Rocketry
1.12.2-2.0.0-242-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.12.2-0.4.2-83-universal

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y

## Crash report or log or visualVM (if applicable)
https://pastebin.com/fG1Rrf44

## Description of the problem
Build Satellite Builder machine. Then insert in a blank Satellite. Add one blank Satellite Chip and any content of satellite. Push Build button.

**Comment by voidsong-dragonfly** [comment]
Known and in the works for next release,
