### ISSUE TITLE
[Request] Making the mod more advanced

### ISSUE THREAD

**Issue by LFTY-LILFOXTVYT** [zmaster587/AdvancedRocketry#2078]
**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]
Hello! I enjoy your mod, and personally think this mod is way better than Galacticraft. But the name of the mod is Advanced rocketry. Yep the mod is pretty advanced, but here I listed some features, that might make the mod truly advanced. Keep in mind, that I am comparing this mod to Kerbal Space Program, so some of the features might not be easy to implement, or something like that. So here are the features I would like to see in this mod:
1. Stages
Stages might be a very cool addition to the mod. This will make it more advanced. For stages to work, fuel would need to be nerfed, so stages make sense. I might have an Idea how to impement it. When building the rocket check for the seperator block. then if it is placed vertically (to seperate the top of the rocket from the bottom) you scan all of the blocks in a box of: width of the seperator (X), depth of the seperator (Z) and the nearest seperator above (Y). If there is none: the height of the rocket left is the stage. The blocks of the rocket, placed under the box, or are not in the box will be, for example, ID:0, then next will be ID:1 and so on. side seperators are the same, but on the X and Z axis, instead of Y axis.
How to seperate stages mid flight: you could click on the seperators in the rocket menu, to seperate the stages (cut the whole rocket and create new entities from the ID set up, when the rocket is built), or create a Stager block to put in the launchpad multiblock, so you can configure what things should happen.
2. Rocket control
I know it would be a very difficult task to do this, but it will be worth it. You can build a special rocket, that is intended to do sub-orbital filghts (like Earth to Earth rockets) or a space plane. This means the mod will require better controls on the rocket, fins and other stuff. This means adding unmanned controllers, if the player wants to land like the mod's landing currently is. If there is no such controller in the rocket, then the player will have to land the rocket manually (turn on the engines, parashutes or whatever). Pls add landing legs
3. More modules to add in a rocket
Your mod has amazing features in the rockets, but more blicks would be a very good thing to add. Heat shields (Ill come to that in a moment), more cargo bays (the more things you place in them: the more mass the rocket has), Solid fuel rocket engines (SRBs), fairings and much more
4. Aerodynamics and atmosphere
You cant just build a cube and launch it to space! One of the things I didn't like in the mod is, that you can build way too weird rockets. The aerodynamics dont have to be that complicated. You can just check for too big flat surfaces on the rocket, facing where the rocket moves (Up or down) and make a warning: "The Rocket has too much flat surfaces. It can burn up on reentry". Talking about burning up on reentry: if the rocket is landing: It can burn in the atmosphere. This is calculated by the speed of the rocket: At first: create a variable for the rocket instance called: temperature. If the speed is over, for example, 50 blocks per second, then find the flattest part of the rocket, put a particle system there and increase the variable. The higher the rocket is: with less speed the rocket will heat up, but the velocity will change slower. The more parts of the rocket are flat (>2 blocks on the same height) the faster the rocket is heating up. If you are going to make this feature, then add advanced moving and stages, so it would be easier to control the rocket. while landing. If the rocket overheats: then explode it.
5. Improve the UI, please
Make the rocket controll easier. The velocity should be a number, that changes. Not a bar. Instead replace the velocity/speed bar with temperature. If you will add Rocket control, then add some kind of horizon device, like in Kerbal Space Program (optional)
6. Fix the stars
You cant visually distinguish a black hole and a star. Please make the sky look like a star, when you orbit it.
7. Science/Data like in KSP
You are planning to add some kind of a progression tree to the game. If you wondered how to collect the points for that: look at KSP! Make the feature to send satelites interplanetary (from planet A to planet B). Make the satelites send science points back to a satelite data collector of some kind. put the data in a special Researcher block and use it for upgrades. You can also get data, by visiting other places manually. Just take a item, go to another planet or fly a space station to it, use the Item and it creates science points (you can configure how much a planet gives in the planetDefs.xml file). But this method can be used only twice per planet (In orbit and on the planet itself), but you can add Atmosphere probes, Sample drills (can be added like a module for a rover), Temperature scanners and other things. This means you'll need to research about the planet, before landing on it (or risk and land there)

That's all I think should be added in AR. I have read the instructions, and I mainly focus on features, added in KSP. About the gameplay: I think with this mod Minecraft will be way more fun to play, but will make space more of an End-game thing, which you'll not only need to build, but design it, design a lander and all of these fun things. Thank you for reading, and I hope you'll add these features in the mod :)

**Comment by LFTY-LILFOXTVYT** [comment]
oops. point 2 in my request is already requested lol

**Comment by voidsong-dragonfly** [comment]
We're not looking to add research at the current point, so # 7 is moot, # 1 and # 2 have already been requested, # 6 has a fix in the pipeline, # 4 isn't happening because the math for that is complicated and painful (and the raycasting/etc isn't performant), # 5 I will add in another issue to remove duplicates.

**Comment by LFTY-LILFOXTVYT** [comment]
Thank you
