### ISSUE TITLE
Game crash when enter new planet

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#208]
Any idea why [this](http://pastebin.com/hbh5aWjK) happens every time i`m entering planet?
I got many more mods, but i had this error even on clean setup, with no mods.

ver. 0.6.8

P.S. I didn`t had this problem with disabled particles in Video options. The moment i turn particles ON, i start crashing on planet enter.

**Comment by zmaster587** [comment]
I've known about this particular error for a while now, but I've only been
able to get it to occur 1 time in 100, making it very difficult to actually
fix, and due to it's rarity has not been a major issue.  Is there anything
unusual about your setup that you think may make it occur more often?
