### ISSUE TITLE
[Mod Conflict] Create Mod's Fluid Spout or pipes interacting with the fluids causes game crash

### ISSUE THREAD

**Issue by AccidentalBetaTester** [zmaster587/AdvancedRocketry#2080]
Version of Advanced Rocketry
1.16.5-2.0.0-10-universal.jar

Have you verified this is an issue in the latest unstable build
 Y
Version of LibVulpes
LibVulpes-1.16.5-1.0.2-18-universal.jar

Version of Minecraft
1.16

Does this occur without other mods installed
N/A - Mod Conflict

Crash report or log or visualVM (if applicable)
See Attached

Description of the problem
When pumping Advanced Rocketry fluids (hydrogen was tested) into the Create Mod's fluid spout, the game crashes. 
Further Details: Create Mod has a hand crank to provide power which requires constant right-click input. Using this to get the fluid in crashes the game, but you can get back in and hydrogen will be in the spout and you can play. Using a constant power source makes the save crash every time when loading. This suggests the issue might be with the **pipes** and not the spout itself. Possibly the pipe drip animations or the fluid porthole view when the pipe has a visible window to see the fluid passing through. Could also be the spout filling animation, but that seems unlikely as the spout draining animation doesn't cause problems - no crash is caused by retrieving the liquid from the spout once you reach that point.

[latest.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6407489/latest.log)

**Comment by AccidentalBetaTester** [comment]
Possibly related to a similar issue caused by Mekanism's Pipes: https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2073

**Comment by voidsong-dragonfly** [comment]
Yes, likely the same issue, as it's a NPE in what seems the same way
