### ISSUE TITLE
Yes, again more features [Request]

### ISSUE THREAD

**Issue by LFTY-LILFOXTVYT** [zmaster587/AdvancedRocketry#2085]
Hello, again. You probably remember my from the last feature request, so I decided to refresh my list. Anyways, welcome to: Begging the AR team for more features part 2
So lets start with some cool things like:
1.More satelites (70% sure it was already requested)
Have you ever had some bases around the world, but only 1 energy source? Well introducing to: RF Orbital recievers. This satelite takes 1 input of a multiblock machine, that sends power to space, and 1 output, where the power goes. But there is a trade-off: The farther a output is: the more energy you'll need in the satelite. 1 satelite can send, for example, 100 RF per tick, but the more satelites you send in space, the more RF you'll send. Let's get that 5G boiiiiii. The same can go for Items and Fluids, travelling from earth to earth or Planet A to Planet A (90% that It was already in the game, but im too lazy to check)
2.Orbital mechanics (95% sure it was already requested)
I have read, that you are planning to add more rocket control for Hard-mode. Then where is the fun in flying a space-craft without orbital mechanics. The system doesn't have to be as advanced, as in KSP, but still a very cool thing
3.More power sources for satelites (45% sure this was already requested)
Currently the only way to get power for a satelite is to pack tons of solar panels. If you are going to add Option 1, then add, for example, RTG generators, solar sails or some other thingies. But then you're going to add uranium or something. The radiation system doesn't have to be as advanced, as in Nuclear Craft, or HBM's Nuclear Tech. Talking about Radiation:
4.Magnitospheres (25% sure someone already requested)
The reason Mars is dead is because he lost its Magnitosphere. Add a tag in planetDefs for magnitosphere. If the magnitosphere is too low, you'll get radiation effects without proper protection in your spacesuit, or if the magnitosphere is too high, then your satelites will stop working, but it may come with a few bemefits, like some kinnd of energy source. And yes, in space you'll die from radiation without protection too. But you can also make a machine for stations. that will create an artifical magnitosphere around your space station
5.Advanced satelite builders (70% sure this again was already requested)
TBH the current satelite bulder is kinda bad. So make a multiblock structure, that allows making of bigger satelites. By bigger I mean you can add more than 1 extension to a satelite (for example 3), more solar panels, more storage. But you'll need better motors or something like that to build the satelites faster.
6. Orbital telescopes (75% sure this was reqeqe lol)
Let's imagine this situation: You just built a Warp drive in your space station, and you are playing on a very big planetDefs. Imagined? Good! Some people can't imagine. I just checked you. Anyways jokes aside, The Idea of this orbital telescope (You can also build it on a station) is to research stars you can visit. There you scan for all stars and unlock after time or/and energy them. The farther a star is from your location, the more time/energy/both you'll need to research about it, so the warp drive is less OP

That's all for now. If this gets cancelled (which it most likely will be) Ill make part 3 with new requests. pls don't ban me. See Ya later! ; )

**Comment by voidsong-dragonfly** [comment]
We do about the maximum orbital mechanics MC can handle well, it doesn't have a physics engine to deal with anything much more than what we have. We're not adding radiation, that's up to other mods to implement, same for RTGs (and we have an API for this if they want to). Large satellite builder could be considered, but the current satellite meta works VERY well and satellites making multiple types of data is honestly sort of boring - specialized satellites work better for us than large ones. I will be reorganizing your issues _again_, so if you want a huge post like this please come through the Discord first so I don't have to deal with four different issues all in one again. Once again closing this to split it up.
