### ISSUE TITLE
[BUG] [1.12.2] ClassCastException crash during Mystcraft world profiling (and potentially other world generation)

### ISSUE THREAD

**Issue by tomdodd4598** [zmaster587/AdvancedRocketry#2089]
## Version of Advanced Rocketry
- 2.0.0-242

## Have you verified this is an issue in the latest unstable build
- Yes

## Version of LibVulpes
- 0.4.2-83

## Version of Minecraft
- 1.12.2

## Does this occur without other mods installed
- Yes, at least Biomes O' Plenty and possibly Mystcraft.

## Crash report or log or visualVM (if applicable)
- [https://pastebin.com/EecWa9RQ](https://pastebin.com/EecWa9RQ)

## Description of the problem
- It seems the cast made [here](https://github.com/Advanced-Rocketry/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/atmosphere/AtmosphereHandler.java#L222) can fail and crash, and does with BoP and Mystcraft installed. Can only guess it's because some mods such as BoP have blocks extending BlockLiquid without implementing IFluidBlock.

**Comment by voidsong-dragonfly** [comment]
Oh FFS. I knew _water_ didn't, so I checked for that, but if that doesn't hold true for every block..... darn. I can take a look at doing that another way then,

**Comment by ShadowFlame365** [comment]
Just wanted to add some more information on top of this, the same issue also seems to affect Dynamic Trees generation as well, with a slightly different error message, so I thought I would provide my log file. I tested with every currently available build for 1.12.2; all three 2.0.0 builds cause a crash, while all three 1.7.0 builds seem to work correctly, using the latest version of LibVulpes, Mystcraft, and Dynamic Trees. If more information is needed please let me know.

https://paste.ee/p/LRDIo
