### ISSUE TITLE
You cannot make rocket fuel

### ISSUE THREAD

**Issue by githubuser49** [zmaster587/AdvancedRocketry#2091]
## Version of Advanced Rocketry
>2.0.0-10

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>1.0.2-22

## Version of Minecraft
>1.16.5

## Does this occur without other mods installed
- [x] N/A

## Description of the problem
>try to make rocket fuel it won't work

**Comment by githubuser49** [comment]
poo poo

**Comment by MrEyeballs29** [comment]
Could you reproduce the steps. I do not understand what is wrong.

**Comment by githubuser49** [comment]
> Could you reproduce the steps. I do not understand what is wrong.

Sílfryí Kalsandryn said i can't make it in the discord
also im trying to make some and it doesn't work

**Comment by zmaster587** [comment]
> > Could you reproduce the steps. I do not understand what is wrong.
> 
> Sílfryí Kalsandryn said i can't make it in the discord
> also im trying to make some and it doesn't work

I tried to make some rocket fuel in my test world and had no problem doing it.
So can you please describe what you are doing step by step?    Without knowing exactly what you're doing, I have no idea if it's something specific to the way you're doing it, something specific about your game setup or what.  I cannot fix something I cannot replicate.

**Comment by voidsong-dragonfly** [comment]
Failing to use Mekanism pipes. (Shown in Discord)

**Comment by githubuser49** [comment]
sorry to cause trouble >_<
