### ISSUE TITLE
[BUG] No recipe for air tight seal enchanment

### ISSUE THREAD

**Issue by rbarron-2** [zmaster587/AdvancedRocketry#2092]
## Version of Advanced Rocketry
>2.0.0-11

## Have you verified this is an issue in the latest unstable build
-  Yes

## Version of LibVulpes
>1.0.2-22

## Version of Minecraft
>1.16.5

## Does this occur without other mods installed
- [x] Yes, the only other mods are libVulpes and JEI
- [x] N
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

## Description of the problem
>There is no recipe for adding the airtight seal to armor. When armor is right clicked in JEI, you can't see how to add the airtight enchantment through the chemical reactor. If I use the recipe(In the chemical reactor) shown in a 1.12 version, it doesn't work.

**Comment by githubuser49** [comment]
there is a fix, there is a bug where it appears in villager trades, that is the workaround!
hope this helps

**Comment by timehm** [comment]
1.16.5-2.0.0-12
this is still an issue in 2.0.0-12 
also the enchantment isnt working at all not sure if i should open a different issue for this.
