### ISSUE TITLE
[MOD CONFLICT] clicking on satellite block or guidance computer crashes the game

### ISSUE THREAD

**Issue by githubuser49** [zmaster587/AdvancedRocketry#2093]
## Version of Advanced Rocketry
>2.0.0-11

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>1.0.2-23

## Version of Minecraft
>1.16.5

## Does this occur without other mods installed
- [x] N

## Crash report or log or visualVM (if applicable)

>https://pastebin.com/YwbxD7Bm

## Description of the problem
>(THIS IS AN ISSUE WITH JOURNEYMAP) make a rocket, assemble it, shift+right click and click guidence computer. it crashes the game. only happens with journeymap which is strange, it shouldn't happen

**Comment by githubuser49** [comment]
when you remove journeymap it only crashes when you click guidence computer
trying to identify 2nd mod now

**Comment by githubuser49** [comment]
2nd mod has been identified, its senere seasons, it has trouble with the dimension whitelist and crashes, if this happens to you, delete the seasons config and it should fix it
hope this help silfryi!

**Comment by zmaster587** [comment]
Where did you get journeymap-1.16.5-5.7.1b3.jar?  Only version I can find on curse is journeymap-1.16.5-5.7.1.jar

**Comment by githubuser49** [comment]
> Where did you get journeymap-1.16.5-5.7.1b3.jar? Only version I can find on curse is journeymap-1.16.5-5.7.1.jar

wdym? i have the one everyone else has? maybe i accidently typed b in the config or smth

**Comment by voidsong-dragonfly** [comment]
No, that's their naming scheme for betas and earlier releases. It's not on CF at the current moment. You should try with the latest from CF.

**Comment by githubuser49** [comment]
> No, that's their naming scheme for betas and earlier releases. It's not on CF at the current moment. You should try with the latest from CF.

just checked, i do indeed have the one with the b, ill update and check if the issue persists.

**Comment by githubuser49** [comment]
> No, that's their naming scheme for betas and earlier releases. It's not on CF at the current moment. You should try with the latest from CF.

sorry for the VERY late reply, yes it still persists even with the non beta version
