### ISSUE TITLE
Visible Space Stations [Request]

### ISSUE THREAD

**Issue by KonamiCodeX** [zmaster587/AdvancedRocketry#2096]
Hey, I think it could be a cool new feature if we would be able to see space stations from the surface of the planet they are orbiting. Maybe a new block could be added (like the rotation controller or altitude controller) in which you could set the coordinates the space station will be positioned in the sky on the planet. And maybe the altitude controller could decide how big/close the station will appear from the surface

**Comment by voidsong-dragonfly** [comment]
Math is annoying for little to no visual reward. Not going to happen, implementation effort is not overridden by usefulness of the feature.
