### ISSUE TITLE
Dimension Registration Conflicts

### ISSUE THREAD

**Issue by Towsty** [zmaster587/AdvancedRocketry#21]
In Issue #17 you mentioned that dimensions are dynamically registered when the server is run. I am having an issue with them conflicting with some existing RFTools dimensions. From the way you described it tough, it does not seem like this should happen.

Basically, server and client startup fine, when I attempt to connect there are some packet handling exceptions when the server and client sync the dimensions? It started with dim 3, which was a test dim so I removed it. Then 4, then 5, then 14, and now its stuck on 15 which I cannot remove. 

Any thoughts?

See line: 85326 and 85346 of client log
(gist and the like are freaking out with the massive logs, sorry)

Client: https://www.dropbox.com/s/kg02d8z10pe3axs/fml-client-latest.log?dl=0
Server: https://www.dropbox.com/s/k2ru07vsiuyn620/fml-server-latest.log?dl=0

**Comment by Towsty** [comment]
I was able to work around this by editing the temp.dat

**Comment by zmaster587** [comment]
It's looking like Advanced Rocketry loads before RFTools, but because both Advanced Rocketry and RFTools register their dimensions in the onServerStarted event ( https://github.com/McJty/RFTools/blob/ed4462c2c0a15174f72d83cd8a3b359266f9712b/src/main/java/mcjty/rftools/RFTools.java#L209 ) .  However because RFTools loads after Advanced Rocketry, RFTools has not yet registered its dimensions so Advanced Rocketry thinks they are free and uses them.  When RFTools loads it does not check if a dimension is registered before trying to use it.  It's really more an issue on their side than mine by the looks of it.

**Comment by Towsty** [comment]
Sounds good, I'll see if I can put something up on McJty git. Thanks for the response! 
Im going to assume that if the world had been created with AdvRocketry and/or RFTools had no generated dims this wouldn't happen to anyone else.

**Comment by zmaster587** [comment]
Was this a new world or existing one?

**Comment by Towsty** [comment]
Existing, very much existing.

**Comment by zmaster587** [comment]
Alright, in that case it probably isn't RFTool's fault, just the fact that the load order was bad.  I'll see if I can do something to fix that.

**Comment by Towsty** [comment]
Sounds good, me and a fried of mine are going to be doing some testing with this on our server. I'll let you know if I find any other issues

**Comment by zmaster587** [comment]
Ok, thank you

**Comment by Towsty** [comment]
Not sure if this was closed because it was fixed in an upcoming or not, but this issue also happens in new worlds.

**Comment by zmaster587** [comment]
Can you send a log file with a new world?

**Comment by Towsty** [comment]
You want the world folder as well??

**Comment by zmaster587** [comment]
The world/AdvancedRocketry/temp.dat would probably be helpful.

**Comment by Towsty** [comment]
Kk, as soon as  I get my son to go down I'll send it

**Comment by Towsty** [comment]
Go ahead and close this again, I derped up with some configs and got a very similar error and jumped to conclusions.

**Comment by zmaster587** [comment]
I've  done that many times myself :P
