### ISSUE TITLE
[sugestion] compatible with modular powersuit

### ISSUE THREAD

**Issue by slendercreeper1010** [zmaster587/AdvancedRocketry#210]
Can you make ti compatible with MachineMuse's modular powersuit?
https://minecraft.curseforge.com/projects/modular-powersuits (link)
Because then I enter any planet/moon it say say that I didn't have spacesuit on me.

**Comment by zmaster587** [comment]
Will look into it

**Comment by slendercreeper1010** [comment]
Thanks ;). probably you can ad a module for it
