### ISSUE TITLE
[BUG]Rocket linking crash

### ISSUE THREAD

**Issue by JustASalmon** [zmaster587/AdvancedRocketry#2107]
## Version of Advanced Rocketry
2.00-12-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
1.02-18-universal
## Version of Minecraft
1.16.5
## Crash report or log (if applicable)
https://pastebin.com/sFRtQp3y

## Description of the problem
Game crashes when I try to link rocket builder to a fueler

**Comment by voidsong-dragonfly** [comment]
Duplicate of #2070
