### ISSUE TITLE
circumvent atmospheric effects with something other than a space suit

### ISSUE THREAD

**Issue by SanAndreaP** [zmaster587/AdvancedRocketry#2113]
I'd like to see ways of circumventing atmospheric effects with something other than the space suit. We already have a way of applying an "enchantment" to armor to allow breathing in oxygen-deprived atmospheres.

Maybe having a similar enchantment on your armor (alternatively having fire resistance) stops you from spontaneously combusting on hot planets.
Holding a "hot" item in your offhand (lava bucket, magma block, etc.) / another armor enchantment prevents you from turning into an icicle on cold planets.

**Comment by voidsong-dragonfly** [comment]
You should already be protected from all of that with airtight seal.
