### ISSUE TITLE
[BUG] Crash after reaching certain altitude

### ISSUE THREAD

**Issue by Luckycoffeepot** [zmaster587/AdvancedRocketry#2116]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
its called AdvancedRocketry-1.16.5-2.0.0-12-universal so i assume its version 2.0.0

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
Yes

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
>1.0.2

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
>1.16.5

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
Yes, and no. Ive tried both
>If Y, what is the MINIMUM set of mods required.
like 90, so i guess this is impossible to fix, without not doing extensive research
>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/3X58fBVa 

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
>Doing the general stuff to make a simple rocket, like making a 4x4 landing pad, putting the structure blocks on the side, the rocket builder, the fuel block(i forgot what it was called but it is used to fuel the rocket), and launching it, with me on it, to "luna" or the moon. I should probably note that I didnt know what the "cords" part meant when it appeared on screen when i rode on the seat. So i continued to launch it, without doing anything about the cords thing. I set it to luna, as i said before, so I was expecting it to be successful. Note that this was all done in creative to test it out. So, as the rocket ascended, i felt more and more confident about it, but when it reached a certain altitude(i cant tell how high), it just randomly crashed. I have tried this in many different worlds and suspect that it might be because of one of the mods. I then proceeded to try it without the mods, but it still didnt work. 

[crash-2021-05-11_22.43.52-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6463699/crash-2021-05-11_22.43.52-server.txt)
^^ This is the crash report, probably the same as the one above.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by githubuser49** [comment]
eek, please remove the square brackets, it makes me cringe every time
