### ISSUE TITLE
Lag and crashing[BUG]

### ISSUE THREAD

**Issue by AtlasRiker** [zmaster587/AdvancedRocketry#2122]
## Version of Advanced Rocketry
>1.16.5-2.0.0-12
## Have you verified this is an issue in the latest unstable build
- [x] Y
## Version of LibVulpes
>1.16.5-1.0.2-25
## Version of Minecraft
>1.16.5
## Does this occur without other mods installed
- [x] N
## Crash report or log or visualVM (if applicable)
>https://pastebin.com/tFEvX98N
## Description of the problem
When a rocket has been assembled, going near the rocket and looking at it dramatically drops fps, like ~5fps. When selecting destination on the rocket, the game just crashes. Some players experienced crashing just opening the rocket UI.
Server also crashes regularly, see attached log.
## How can you reliably reproduce the problem
>Build rocket and go near it or use the ui.

This is the modpack being used https://www.curseforge.com/minecraft/modpacks/hentyecraft/

**Comment by zmaster587** [comment]
The crash report appears totally unrelated to advanced rocketry, however, I do know I had to undo a rendering optimization for the rocket temporarily so I suspect that's probably the cause of the FPS drop.
