### ISSUE TITLE
"Station is not in Geostationary Orbit!"

### ISSUE THREAD

**Issue by Joey-Destroyah** [zmaster587/AdvancedRocketry#2127]
## Version of Advanced Rocketry
1.12.2 2.0.0-247
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.4.2-83
## Version of Minecraft
1.12.2 Forge build 14.23.5.2847
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here] N/A; not a crash

## Description of the problem
Simply try to link a space elevator on a station to an elevator on any planet. and an error in chat will say "Station is not in Geostationary Orbit!"
Also, there is no slot in the elevator GUI for the chip nor is there a wiki article telling people why this occurs or an update to said article from the link provided in the Curseforge page.

**Comment by voidsong-dragonfly** [comment]
Stuff changed since 2.0.0. Your station needs to be in geostationary orbit (wow, it says that in chat, who knew?) and the elevator chip is currently unused but may be getting a use later.

**Comment by Joey-Destroyah** [comment]
How do I get the station to Geostat orbit anyway?

**Comment by voidsong-dragonfly** [comment]
You look up what geostationary orbit is, then move your station there.

**Comment by Joey-Destroyah** [comment]
Last I checked, there was nothing in the creative inventory that moves the station's orbit aside from the warp drive.
How else would I move it?

**Comment by voidsong-dragonfly** [comment]
http://arwiki.dmodoomsirius.me/AdvancedRocketry/1.12.2/blocks/SpaceStationControllers.php

**Comment by Joey-Destroyah** [comment]
Thanks!

**Comment by 0SpaceWorld0** [comment]
> Thanks!

and how did you do it?
