### ISSUE TITLE
Biome Analyser uses old OD name for blockAluminium

### ISSUE THREAD

**Issue by ZeroMe1a** [zmaster587/AdvancedRocketry#2129]
## Version of Advanced Rocketry
>[1.16.5-2.0.0-12-universal

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>[1.16.5-1.0.2-25-universal

## Version of Minecraft
>[1.16.5 Forge 36.1.23

## Does this occur without other mods installed
- [x] Y

>[No Chlorine -> https://pastebin.com/LSnqsn1c
>[With Chlorine -> https://pastebin.com/34nNaBHN

## Description of the problem
>[Create a new world, build biome analyzer (motor under biome analyzer, just like the holo shows) right click biome analyzer

**Comment by MrEyeballs29** [comment]
I know that resource locations can only have lowercase characters. That caused that game to crash.
