### ISSUE TITLE
[BUG] can't make crystalizer

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#2130]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-235-universal

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-75-universal

## Version of Minecraft
>1.12.2

- [x] N/A

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read

## Description of the problem
>I try to make a crystallizer and there's just an x up and to the left and i don't know what to do 

![2021-05-27_18 04 53_2](https://user-images.githubusercontent.com/65469481/119903882-64217780-bf17-11eb-9d7a-ed0f9955a2c8.png)

**Comment by MrEyeballs29** [comment]
Use a holoprojector. that item allows you to project any multiblock structures with ease.

(Also outdated version)

**Comment by PercyJames** [comment]
i did that

**Comment by PercyJames** [comment]
yet it doesn't really show the problem

**Comment by voidsong-dragonfly** [comment]
Version out of date.

**Comment by PercyJames** [comment]
ok then. i'll try updating

**Comment by PercyJames** [comment]
i updated to AdvancedRocketry-1.12.2-1.7.0-240-universal and it did the same thing

edit: i used the holo-projector multiple times and it didn't work

**Comment by voidsong-dragonfly** [comment]
a) that's still not the latest 
b) you might want to take a look at your middle mouse wheel's scroll feature

**Comment by PercyJames** [comment]
i'm trying to update and i downloaded two libvulpes versions. they didn't work. I then tried to find out what the right version was by removing libvulpes all together and letting the crash tell me. i apparently need "%LIBVULPESVSERSION% or above (missing)"

**Comment by voidsong-dragonfly** [comment]
you need a) the latest LV (possibly an alpha) and b) the latest AR (a beta I think), all the latest 1.12 versions

**Comment by PercyJames** [comment]
thank you! i figured it out. The reason i didn't think to scroll is cause i use a trackpad.
