### ISSUE TITLE
issue:adding fuel to fuel-station too quick cause crash

### ISSUE THREAD

**Issue by XiaoKu573** [zmaster587/AdvancedRocketry#2136]
Version of Advanced Rocketry
1.12.2-0.4.2-83

Have you verified this is an issue in the latest unstable build
N/A

Version of LibVulpes
1.12.2-2.0.0-248

Version of Minecraft
1.12.2

Description of the problem
When the fuel-station is linked to a rocket and loading fuel to the rocket(in working condition), if you put fuel buckets quickly one by one  into the fuel-station and make the storge bar reach the top, the game crashes. If you do this in a server, the server gets stucked.
[crash-2021-06-06_02.29.34-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/6603654/crash-2021-06-06_02.29.34-server.txt)

**Comment by spiro-angelakis** [comment]
confirmed this is a bug

**Comment by spiro-angelakis** [comment]
occurs in ARv248
the fuel loader immediately attempts to accept the new bucket's fuel and doesn't know what to do when overfilled, freezing the game completely

**Comment by spiro-angelakis** [comment]
i believe you could just set the fuel loader to not use fuel buckets in it's gui inventory until there is proper space for the liquid

**Comment by voidsong-dragonfly** [comment]
Likely old version
