### ISSUE TITLE
[Issue] GC alien villagers keep suffocating. 

### ISSUE THREAD

**Issue by PercyJames** [zmaster587/AdvancedRocketry#2140]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.7.0-235-universal
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-75-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/SbCAuF42
## Description of the problem
when I went to the GC moon and found a village the villagers suffocated.

**Comment by voidsong-dragonfly** [comment]
Use the config to blacklist them needing oxygen.

**Comment by PercyJames** [comment]
thanks!
