### ISSUE TITLE
Water acts as a portal to a flat planet on planets where water can be placed.

### ISSUE THREAD

**Issue by EntityIridescent** [zmaster587/AdvancedRocketry#2141]
## Version of Advanced Rocketry
1.12.2-2.0.0-250
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
1.12.2-0.4.2-83
## Version of Minecraft
1.12.2

I came across this issue in survival. Any time I am on a planet with water, and I accidentally get in the water, I seem to be teleported to this other dimension. It looks like a planet. It is breathable, superflat with grass blocks and a few trees, plus a few lakes. The entire layer below the surface seems to be water, and you can see where sand has fallen down to the bedrock level. If one tries to escape this dimension through the water, you are teleported back to the same place in that same world. After taking off from a station to the destination planet, I landed in water and was teleported instantly to this dimension, and am unable to return. Teleporting back to the planet's ID usually causes an extreme amount of lag as it registers being teleported, then being submerged in water, teleporting you back to the flat world. These pictures are from a creative world where I tested the issue again.
![2021-06-12_19 04 00](https://user-images.githubusercontent.com/57729635/121791594-1b252080-cbb1-11eb-94e7-c0afeb9385ab.png)
![2021-06-12_19 03 54](https://user-images.githubusercontent.com/57729635/121791596-1c564d80-cbb1-11eb-957b-52e37521b3f1.png)

**Comment by voidsong-dragonfly** [comment]
This is _definitively_ another mod. Please test to find which one it is.

**Comment by voidsong-dragonfly** [comment]
Not AR, no response. Closing.
