### ISSUE TITLE
[BUG] Dark moon turf item texture not dark enough

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#2144]
## Version of Advanced Rocketry
>2.0.0-250

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>0.4.2-83

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

## Description of the problem
When in item form, dark moon turf looks just like normal moon turf. The block is normal.
![2021-06-15_22 27 35](https://user-images.githubusercontent.com/8508976/122162772-ee7b3e00-ce28-11eb-953f-f69feab20d5f.png)

**Comment by voidsong-dragonfly** [comment]
Fixed in latest dev
