### ISSUE TITLE
[BUG] Space Elevator Multiblock won't work

### ISSUE THREAD

**Issue by SeaSwept** [zmaster587/AdvancedRocketry#2145]
## Version of Advanced Rocketry
>AdvancedRocketry-1.16.5-2.0.0-12-universal.jar
>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- Y 

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
>LibVulpes-1.16.5-1.0.2-25-universal.jar

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
>1.16.5

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- Y

>If Y, what is the MINIMUM set of mods required.
Advanced Rocketry and LibVulpes

>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
>When I try to build the Space Elevator, an X appears, I tried to rotate the Motor and Elevator and It wouldn't work
![2021-06-16_18 16 34](https://user-images.githubusercontent.com/86028148/122307991-0efed300-ced1-11eb-93fb-56b8505d0192.png)

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by SeaSwept** [comment]
I also went into another world with just Advanced Rocketry and LibVulpes, I used regular stone slabs and it still didn't work

**Comment by voidsong-dragonfly** [comment]
You need steel blocks in the corners of the structure, diagonal with the diagonal advanced machine casing branches.

**Comment by SeaSwept** [comment]
Thank You! It didn't show in the Holo-Projector, or in the item list

**Comment by HNGamingUK** [comment]
Anyway we can get this re-opened? I have added steel blocks like mentioned but it still doesn't work 
![Space Elevator](https://user-images.githubusercontent.com/5269015/124400435-45827d80-dd1a-11eb-8276-8185522731bf.png)

**Comment by voidsong-dragonfly** [comment]
see #2146
