### ISSUE TITLE
[1.16.5 - BUG] Wrong item tag in Space Elevator

### ISSUE THREAD

**Issue by SeaSwept** [zmaster587/AdvancedRocketry#2146]
## Version of Advanced Rocketry
>AdvancedRocketry-1.16.5-2.0.0-12

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
-Y

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
>LibVulpes-1.16.5-1.0.2-25

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
>1.16.5

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- Y

>If Y, what is the MINIMUM set of mods required. LibVulpes and Advanced Rocketry

>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
>In my server console it says that there is no forge:blocks/steel tag, and the steel block from LibVulpes is forge:storage_blocks/steel
![2021-06-17_10 50 34](https://user-images.githubusercontent.com/86028148/122431618-3b126680-cf5a-11eb-904e-32564d4d44c5.png)
![Screenshot 2021-06-17 105336](https://user-images.githubusercontent.com/86028148/122431694-4bc2dc80-cf5a-11eb-8d5d-7f1c50ab8970.png)

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by HNGamingUK** [comment]
I can report that I am also having the same issue, running same versions as author of the issue.

**Comment by HNGamingUK** [comment]
Tested with running just Advanced Rocketry and LibVulpes and still does not work. 

Minecraft 1.16.5
Forge 36.1.32
Advanced Rocketry 2.0.0-12
LibVulpes 1.0.2-25

Not sure if a new thread should be raised but the texture for the advanced machine structure goes see through when slabs are placed next to them. 
![2021-07-05_21 29 58](https://user-images.githubusercontent.com/5269015/124516027-b8eac480-ddd8-11eb-92ea-bb492a49603e.png)
![2021-07-05_21 30 09](https://user-images.githubusercontent.com/5269015/124516031-bab48800-ddd8-11eb-9533-4f1a7ec33e1f.png)

A final point to note is as was found in #2145 steel blocks are needed but don't show in the hologram.

**Comment by voidsong-dragonfly** [comment]
Fixed in latest
