### ISSUE TITLE
[QUESTION] Biome Ids

### ISSUE THREAD

**Issue by thiago1255** [zmaster587/AdvancedRocketry#2149]
I was looking for the Biomes id of this Mod. But I can't find them anywhere, the wiki just says "Their IDs can be changed in the advRocketry/advancedRocketry.cfg" but there's nothing in the configuration. Have the settings changed? Have the biomes been removed from the Mod? Where can I find the ids?

**Comment by voidsong-dragonfly** [comment]
What version are you on? 1.8+ They're all assigned automatically and don't even have numbers the player can use. Resourcelocations are shown with `/advancedRocketry dumpBiomes`

**Comment by thiago1255** [comment]
I'm using the last one for 1.12.2. Thanks for answering !
