### ISSUE TITLE
[Small] Incompatibility with JEI. Advanced Rocketry 1.10.2 

### ISSUE THREAD

**Issue by TripOptic** [zmaster587/AdvancedRocketry#215]
Don't know who I should go to about this, but JEI crashes on server join because of a duplicate entry with the electrolyzer recipe registry between Ic2 and Advanced rocketry. 

https://gist.github.com/TripOptic/650f3521ecefc06b625506aef4f92303\

submitted to JEI also.

**Comment by mezz** [comment]
To avoid conflicts with other mods, you should make your category keys more unique, like "zmaster587.advancedRocketry.electrolyzer" instead of something like plain "electrolyzer".
