### ISSUE TITLE
Small plate press will not make plates out of metal blocks

### ISSUE THREAD

**Issue by HobbsC** [zmaster587/AdvancedRocketry#2154]
## Version of Advanced Rocketry
>Version 1.16.5

## Have you verified this is an issue in the latest unstable build
- yes this is the latest build that I am aware of

## Version of LibVulpes
>version 1.16.5

## Version of Minecraft
>version 1.16.5

## Does this occur without other mods installed
- [x] Y

>If Y, what is the MINIMUM set of mods required.
Advanced Rocketry and Libs. I tried it with just those and still.

## Description of the problem
Everything seems to work well it is just I cannot make plates with the small plate press.I have tried everything I can think of it jsut will not make them. It works with ore to make dust it is just the blocks of metal it does nothing.
>[How can you reliably reproduce the problem

**Comment by voidsong-dragonfly** [comment]
This should be fixed in latest. If it reappears, reopen issue
