### ISSUE TITLE
Rocket doesn't render, is lost every time attempt to land on Docking Pad on Station[BUG]

### ISSUE THREAD

**Issue by or0b0ur0s** [zmaster587/AdvancedRocketry#2155]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>1.12.2-1.7.0-204

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>1.12.2-0.4.2-74

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A

## Description of the problem
>Launch a space station with a named Docking Pad aboard OR another means of teleporting to the station, then add a Docking Pad to it.  Any rocket launched with the Space Station ID chip in the Guidance Computer and the Docking Pad selected as destination in the rocket GUI lists the pad name as destination and launches.  

When it appears in orbit neither the rocket nor the player render and both are completely invisible and un-interactable.  The prompt to Descend occurs, and whether you wait for it or press space, the only indication of descent is the Altitude gauge dropping.  When you arrive, there is no station (and still no rocket or visible player, even in F5).  

Minimaps show you are aboard the station centered on the Docking Pad, but there is nothing.  The ship prompts you to lift off again, but pressing space does nothing but dismiss the prompt.  I did not try dismounting because I didn't want to lose my armor if fatal, but you can teleport out via any portable means.  Upon returning to the station, your rocket is not there, nor is it on the ground.

**Comment by voidsong-dragonfly** [comment]
Old Version, update past 2.0.0 or you will receive no help.
