### ISSUE TITLE
[1.16.5 BUG] Warp Core not recognising other aluminium blocks

### ISSUE THREAD

**Issue by HNGamingUK** [zmaster587/AdvancedRocketry#2158]
## Version of Advanced Rocketry
2.0.0-12

## Have you verified this is an issue in the latest unstable build
Y

## Version of LibVulpes
1.0.2-25

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
N

## Description of the problem
I have noticed that when assembling the warp core it does not recognise any other mod's aluminium blocks. eg in my pack I have Tinkers Mechworks and Immersive Engineering both of which have aluminium blocks. Both of which are not accepted by the warp core.

Tinker's Mechworks 2.2.5
Immersive Engineering 5.0.1-136

Hope this is enough information!

**Comment by voidsong-dragonfly** [comment]
Intentional, there is a specific tag that the warp core blocks are added to for use. By default, this only allows AR ones. You'd need to add them yourself or have the other mod add them to that.
