### ISSUE TITLE
[BUG] screen of holoprojecter to small

### ISSUE THREAD

**Issue by emidblol** [zmaster587/AdvancedRocketry#2160]
lbuild 12 of 1.16.5>

**Comment by MrEyeballs29** [comment]
You did not follow the template. Your issue will be closed and ignored if
you did not follow the template.

**Comment by emidblol** [comment]
Someone here?

**Comment by voidsong-dragonfly** [comment]
Holoprojector GUI scale fine for me, no evidence provided.

**Comment by emidblol** [comment]
but it is still for me
