### ISSUE TITLE
[BUG] "Soft crash" when using spacesuit leggings with bionic legs in multiplayer

### ISSUE THREAD

**Issue by Rosentti** [zmaster587/AdvancedRocketry#2161]
## Version of Advanced Rocketry
1.16.5-2.0.0-12

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.16.5-1.0.2-25

## Version of Minecraft
1.16.5

## Does this occur with other mods installed
- [x] N

## "Crash report" 
https://pastebin.com/RBzvtM2e

## Description of the problem
1. Create and join a server with advanced rocketry.
2. Get spacesuit leggings and equip them with bionic legs.
3. Place said legs into leggings slot.
4. Internal server error 
Nobody else is affected, however said player cannot logon unless their playerdata file is deleted.

**Comment by Brycey92** [comment]
@Silfryi this can be closed once the giant 1.16.5 merge is done #2148
