### ISSUE TITLE
Ticking Entity[BUG]

### ISSUE THREAD

**Issue by Gaminguide1000** [zmaster587/AdvancedRocketry#2166]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-2.0.0-250-universal

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] Y

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-83-universal

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
>1.12.2

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- [x] Y
- [ ] 
>If Y, what is the MINIMUM set of mods required.
I think, only Advanced Rocketry & LibVulpes, 
>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-250-universal.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.14.5_Forge_1.12.jar)
  ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.12.4_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 7/8/21 12:07 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at zmaster587.advancedRocketry.entity.EntityElevatorCapsule.func_70030_z(EntityElevatorCapsule.java:287)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at zmaster587.advancedRocketry.entity.EntityElevatorCapsule.func_70030_z(EntityElevatorCapsule.java:287)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: advancedrocketry:arspaceelevatorcapsule (zmaster587.advancedRocketry.entity.EntityElevatorCapsule)
	Entity ID: 171902
	Entity Name: entity.ARSpaceElevatorCapsule.name
	Entity's Exact location: -1551.50, 117.00, -1537.50
	Entity's Block location: World: (-1552,117,-1538), Chunk: (at 0,7,14 in -97,-97; contains blocks -1552,0,-1552 to -1537,255,-1537), Region: (-4,-4; contains chunks -128,-128 to -97,-97, blocks -2048,0,-2048 to -1537,255,-1537)
	Entity's Momentum: 0.00, 0.85, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Gaminguide1000'/171898, l='MpServer', x=-1514.50, y=1221.00, z=-1535.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 09 - Space, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (104,64,252), Chunk: (at 8,4,12 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18717215 game time, 189234 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 6 total; [GCEntityClientPlayerMP['Gaminguide1000'/171898, l='MpServer', x=-1514.50, y=1221.00, z=-1535.50], EntityLatchedRenderer['unknown'/1, l='MpServer', x=8.50, y=65.00, z=8.50], EntityRocket['Rocket'/171899, l='MpServer', x=-1514.50, y=1000.00, z=-1535.50], EntityElevatorCapsule['entity.ARSpaceElevatorCapsule.name'/171902, l='MpServer', x=-1551.50, y=117.00, z=-1537.50], EntityElevatorCapsule['entity.ARSpaceElevatorCapsule.name'/171900, l='MpServer', x=-1551.50, y=119.85, z=-1538.50], EntityElevatorCapsule['entity.ARSpaceElevatorCapsule.name'/171901, l='MpServer', x=-1551.50, y=120.00, z=-1537.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/1, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5429954592 bytes (5178 MB) / 8689025024 bytes (8286 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx18G -Xms1G -XX:PermSize=1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G6_pre1 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version            | Source                                               | Signature                                |
	|:------ |:--------------------------------- |:------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2             | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                               | 9.42               | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                               | 8.0.99.99          | forge-1.12.2-14.23.5.2855.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2855       | forge-1.12.2-14.23.5.2855.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore              | 1                  | minecraft.jar                                        | None                                     |
	| LCHIJA | creativecoredummy                 | 1.0.0              | minecraft.jar                                        | None                                     |
	| LCHIJA | micdoodlecore                     |                    | minecraft.jar                                        | None                                     |
	| LCHIJA | xaerominimap_core                 | 1.12.2-1.0         | minecraft.jar                                        | None                                     |
	| LCHIJA | xaeroworldmap_core                | 1.12.2-1.0         | minecraft.jar                                        | None                                     |
	| LCHIJA | securitycraft                     | v1.8.22.2          | [1.12.2] SecurityCraft v1.8.22.2.jar                 | None                                     |
	| LCHIJA | wolffsmod                         | 2.2                | [1.12.2]-Flan's-Mod-Vehicles-for-Custom-NPCs-2.2.jar | None                                     |
	| LCHIJA | libvulpes                         | 0.4.2.-83          | LibVulpes-1.12.2-0.4.2-83-universal.jar              | None                                     |
	| LCHIJA | advancedrocketry                  | 2.0.0.-250         | AdvancedRocketry-1.12.2-2.0.0-250-universal.jar      | None                                     |
	| LCHIJA | baubles                           | 1.5.2              | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LCHIJA | flyringbaublemod                  | 0.3.1_1.12-d4e654e | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar          | None                                     |
	| LCHIJA | flansmod                          | 5.10.0             | Flan's Mod-1.12.2-5.10.0.jar                         | None                                     |
	| LCHIJA | flansmodapocalypse                | 1.4.0              | Apocalypse-Content Pack-1.12.2-5.10.0.jar            | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55      | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76      | EnderCore-1.12.2-0.5.76.jar                          | None                                     |
	| LCHIJA | jei                               | 4.16.1.301         | jei_1.12.2-4.16.1.301.jar                            | None                                     |
	| LCHIJA | thaumcraft                        | 6.1.BETA26         | Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
	| LCHIJA | enderio                           | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | twilightforest                    | 3.11.1021          | twilightforest-1.12.2-3.11.1021-universal.jar        | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183  | TConstruct-1.12.2-2.13.0.183.jar                     | None                                     |
	| LCHIJA | bhc                               | 2.0.3              | baubley-heart-canisters-1.12.2-2.0.3.jar             | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2444         | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar        | None                                     |
	| LCHIJA | botania                           | r1.10-364          | Botania r1.10-364.4.jar                              | None                                     |
	| LCHIJA | buildcraftlib                     | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcraftcompat                  | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.8          | buildcraft-all-7.99.24.8.jar                         | None                                     |
	| LCHIJA | carryon                           | 1.12.3             | carryon-1.12.2-1.12.4.16.jar                         | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | codechickenlib                    | 3.2.3.358          | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks                     | 2.4.2.74           | ChickenChunks-1.12.2-2.4.2.74-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chiselsandbits                    | 14.33              | chiselsandbits-14.33.jar                             | None                                     |
	| LCHIJA | creativecore                      | 1.10.0             | CreativeCore_v1.10.61_mc1.12.2.jar                   | None                                     |
	| LCHIJA | cucumber                          | 1.1.3              | Cucumber-1.12.2-1.1.3.jar                            | None                                     |
	| LCHIJA | cyberware                         | 0.2.11.29          | cyberware-1.12.2-0.2.11.29.jar                       | None                                     |
	| LCHIJA | divinerpg                         | 1.7.1              | DivineRPG-1.7.1.jar                                  | None                                     |
	| LCHIJA | enchantingwiththaumcraft          | 1.3                | enchantingwiththaumcraft-1.3.jar                     | None                                     |
	| LCHIJA | enchdesc                          | 1.1.15             | EnchantmentDescriptions-1.12.2-1.1.15.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderiobase                       | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderioconduits                   | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderiomachines                   | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | enderiopowertools                 | 5.3.70             | EnderIO-1.12.2-5.3.70.jar                            | None                                     |
	| LCHIJA | motnt                             | 1.0.1              | EvenMoreTNT-1.0.1.jar                                | None                                     |
	| LCHIJA | galacticraftcore                  | 4.0.2.280          | GalacticraftCore-1.12.2-4.0.2.280.jar                | None                                     |
	| LCHIJA | galacticraftplanets               | 4.0.2.280          | Galacticraft-Planets-1.12.2-4.0.2.280.jar            | None                                     |
	| LCHIJA | gravestone                        | 1.10.3             | gravestone-1.10.3.jar                                | None                                     |
	| LCHIJA | ichunutil                         | 7.2.2              | iChunUtil-1.12.2-7.2.2.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | gravitygun                        | 7.1.0              | GravityGun-1.12.2-7.1.0.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | waila                             | 1.8.26             | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LCHIJA | llibrary                          | 1.7.20             | llibrary-1.7.20-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                        | 1.9.1              | iceandfire-1.9.1-1.12.2.jar                          | None                                     |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844  | ironchest-1.12.2-7.0.72.847.jar                      | None                                     |
	| LCHIJA | ironjetpacks                      | 1.1.0              | IronJetpacks-1.12-2-1.1.0.jar                        | None                                     |
	| LCHIJA | mcef                              | 1.11               | mcef-1.12.2-1.11.jar                                 | None                                     |
	| LCHIJA | mechapartspack                    | 5.7.2              | Mecha Parts-Content Pack-1.12.2-5.7.2.jar            | None                                     |
	| LCHIJA | modernweaponspack                 | 5.8.2              | Modern Warfare-Content Pack-1.12.2-5.8.2.jar         | None                                     |
	| LCHIJA | stevekung's_lib                   | 1.1.10             | SteveKunG's-Lib-1.12.2-1.1.10.jar                    | None                                     |
	| LCHIJA | moreplanets                       | 2.2.1              | More-Planets-1.12.2-2.2.1-GC280.jar                  | None                                     |
	| LCHIJA | morph                             | 7.2.0              | Morph-1.12.2-7.2.1.jar                               | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | morpheus                          | 1.12.2-3.5.106     | Morpheus-1.12.2-3.5.106.jar                          | None                                     |
	| LCHIJA | natura                            | 1.12.2-4.3.2.69    | natura-1.12.2-4.3.2.69.jar                           | None                                     |
	| LCHIJA | neat                              | 1.4-17             | Neat+1.4-17.jar                                      | None                                     |
	| LCHIJA | opframe                           | 1.4.0              | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar              | None                                     |
	| LCHIJA | p455w0rdslib                      | 2.3.161            | p455w0rdslib-1.12.2-2.3.161.jar                      | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | portalgun                         | 7.1.0              | PortalGun-1.12.2-7.1.0.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | rild                              | 0.4                | Rild Mod V.1.12.2-0.4.jar                            | None                                     |
	| LCHIJA | simplepartspack                   | 5.7.2              | Simple Parts-Content Pack-1.12.2-5.7.2.jar           | None                                     |
	| LCHIJA | srparasites                       | 1.8.2              | SRParasites-1.12.2v1.8.2.jar                         | None                                     |
	| LCHIJA | tc6aspects4jei                    | 0.0.2a             | tc6aspects4jei-0.0.2a.jar                            | None                                     |
	| LCHIJA | thaumcraftnoresearch              | 1.0                | ThaumcraftNoResearch-1.0.jar                         | None                                     |
	| LCHIJA | tcinventoryscan                   | 2.0.10             | ThaumicInventoryScanning_1.12.2-2.0.10.jar           | None                                     |
	| LCHIJA | thaumicjei                        | 1.6.0              | ThaumicJEI-1.12.2-1.6.0-27.jar                       | None                                     |
	| LCHIJA | thaumicwaila                      | 1.12.2-0.0.2       | ThaumicWaila-1.12.2-0.0.2.jar                        | None                                     |
	| LCHIJA | titanpack                         | 5.7.2              | Titan-Content Pack-1.12.2-5.7.2.jar                  | None                                     |
	| LCHIJA | tntguns                           | 1.0.5              | TNTsGuns1.0.5.jar                                    | None                                     |
	| LCHIJA | travelersbackpack                 | 1.0.35             | TravelersBackpack-1.12.2-1.0.35.jar                  | None                                     |
	| LCHIJA | wailaharvestability               | 1.1.12             | WailaHarvestability-mc1.12-1.1.12.jar                | None                                     |
	| LCHIJA | webdisplays                       | 1.1                | webdisplays-1.12.2-1.1.jar                           | None                                     |
	| LCHIJA | ww2pack                           | 5.7.2              | WW2-Content Pack-1.12.2-5.7.2.jar                    | None                                     |
	| LCHIJA | xaerominimap                      | 21.12.4            | Xaeros_Minimap_21.12.4_Forge_1.12.jar                | None                                     |
	| LCHIJA | xaeroworldmap                     | 1.14.5             | XaerosWorldMap_1.14.5_Forge_1.12.jar                 | None                                     |
	| LCHIJA | yeoldepack                        | 5.8.2              | Ye Olde-Content Pack-1.12.2-5.8.2.jar                | None                                     |
	| LCHIJA | zombiepack                        | 5.8.5              | Zombie-Content Pack-1.12.2-5.8.5.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-250-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  
XaeroWorldMapPlugin (XaerosWorldMap_1.14.5_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
XaeroMinimapPlugin (Xaeros_Minimap_21.12.4_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14831 Compatibility Profile Context 21.5.2 27.20.21003.8013' Renderer: 'AMD Radeon RX 6700 XT'
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 6700 XT GL version 4.6.14831 Compatibility Profile Context 21.5.2 27.20.21003.8013, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14831 Compatibility Profile Context 21.5.2 27.20.21003.8013
	OpenGlRenderer: AMD Radeon RX 6700 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 24

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

>Why is this important?
>Full crashlogs contain valuable information like where exactly in the code the error occurred, what other mods may be running and what version of forge you have.  This helps us replicate and diagnose the issue FAR faster.]

## Description of the problem
>Well i Tried to go to the Space Station, using a ocket (worked fine). Then i built a Space Station Elevator, linked it to another one on the earth, and wqhen i try to go to the earth, using the Elevator, it works. But when i want to go to the Space Station using the Elevator, it just Crashes. When i tried the same with the Rocket, it happend too. When i try to rejoin on the Server, my Minecraft crashes, and crashes ovr an over again. The same happend to my Friend :/

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by voidsong-dragonfly** [comment]
Format not followed + this is likely multiple different crashes, each of which is I believe fixed in the next update.
