### ISSUE TITLE
[1.12.2] Server crashing after rocket landed on space station

### ISSUE THREAD

**Issue by crunchy121** [zmaster587/AdvancedRocketry#2167]
Version of Advanced Rocketry
>1.7.0

Have you verified this is an issue in the latest unstable build
- N

## Version of LibVulpes
> 0.4.2

## Version of Minecraft
> 1.12.2
## Does this occur without other mods installed
- N/A

## Crash report or log or visualVM (if applicable)
>  [https://pastebin.com/01i90J5R]

## Description of the problem
> My friend launched a rocket to the space station and the whole server crashes after the rocket landed. We've sent rockets to the space station before without crashes but we did add new mods between then such as Thermal Expansion, Ender Chest, Open Computers, web displays and draconic. Whenever my friend connected to the server, the whole server crashed.

**Comment by voidsong-dragonfly** [comment]
Old version, unsupported.
