### ISSUE TITLE
[Request] Station Satelites

### ISSUE THREAD

**Issue by CTH999** [zmaster587/AdvancedRocketry#2175]
This idea is simple. Basicly, I think that you should be able to access the data from a satelite anywhere in the planetary system (Moons, station) Simple as that. Not much, but just a simple addition

Of course, ultimatly it is your choice.

**Comment by voidsong-dragonfly** [comment]
Should already be possible?

**Comment by CTH999** [comment]
> Should already be possible?

maybe... i'll check

due to time constraits, might be tommoro that you get an answer

**Comment by CTH999** [comment]
Just realized, either way, I can just put them in orbit around the space station, and I have them anywhere… so that kinda makes my suggestion not necessary
