### ISSUE TITLE
[Request] Asteroids

### ISSUE THREAD

**Issue by CTH999** [zmaster587/AdvancedRocketry#2176]
So, I want (Landable) asteroid fields. Basicly, what this does is it's a "planet" that, if you put in the "asteroid" tag, it will only generate special biomes (Biomes related to asteroids). Gravity is zero (Unless you change it, if this tag is there it defaults to 0). It generates biomes similar to the end islands. The main difference is that the end is one biome, and the islands are flat on top. Here, clusters of special biomes form that tell it how to generate the asteroids (big, small) (what ores), and so on.

another tag allows you to make it form derilict stations and crashed ships. Some of these have rooms that are still pressurized, and some of them have useful components. Problem is, if you can survive in it...

However, it is ultimatly your choice

**Comment by voidsong-dragonfly** [comment]
What of this we can easily do and still be well-themed already exists

**Comment by CTH999** [comment]
> What of this we can easily do and still be well-themed already exists

really? Which parts are that? I can get not haveing derilicts, but an asteroid tag, does that alread exist? In which case, my bad (:
