### ISSUE TITLE
Crash when using Holo-Projecter 1.10.2

### ISSUE THREAD

**Issue by DonkeysWTF** [zmaster587/AdvancedRocketry#218]
So most of the holo-projecter blue prints causes a crash on placement but when the client is restarted and I go back into the world the holo blocks are all there and I can move between layers.

Forge version: 12.18.1.2095
Minecraft: 1.10.2
[crash-2016-10-06_20.55.36-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/513539/crash-2016-10-06_20.55.36-client.txt)

**Comment by zmaster587** [comment]
I can only get it to occur with rapid fire clicking, but should be fixed in the next build
