### ISSUE TITLE
[BUG]Server crash - 'Biome Swampland' w/ Mystcraft and Biomes O' Plenty (Adv Rocketry added) 

### ISSUE THREAD

**Issue by mgenjoker** [zmaster587/AdvancedRocketry#2187]
## Version of Advanced Rocketry
>1.12.2-2.0.0-250

## Have you verified this is an issue in the latest unstable build
- Y

## Version of LibVulpes
>1.12.2-0.4.2-83

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A
Advanced Rocketry (New Addition)
Biomes O Plenty
Mystcraft

## Crash report or log or visualVM (if applicable)
>https://pastebin.com/eneQvCgg

## Description of the problem
>Server Start

Advanded Rocketry is the new would-be addition to a working server version of our pack. Just passing along the info.

**Comment by mgenjoker** [comment]
The Crash can be bypassed with MystCarft Config: 
"# If true, the baseline calculations won't run and instead a config file will be read.
    B:useconfigs=true"
It's a band-aid solution and I'm not sure what that will do to MystCraft, Baseline calculations should probably be run before adding in Advanced Rocketry, but i'm not sure if the config is fully configured by it or if it is a base valueless config until configured.

**Comment by voidsong-dragonfly** [comment]
Duplicate
