### ISSUE TITLE
[BUG] Game crashes when oxygen of any amount is put inside of a vent

### ISSUE THREAD

**Issue by JustaFloatingEye** [zmaster587/AdvancedRocketry#2198]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.12.2-1.7.0-232

## Have you verified this is an issue in the latest unstable build
N

## Version of LibVulpes
1.12.2-0.4.2-84

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
N/A, there was 2 other mods (other than LibVulpes and AR): AliensVsPredator and MDXLib

## Crash report or log or visualVM (if applicable)
https://pastebin.com/C741ujt7

## Description of the problem
Well I was on the moon of an Earthlike planet, the moon had a tiny bit higher gravity than normal Earth, so basically Earth gravity. There was atmosphere but a tiny bit, only just barely purple. What I was doing was just making a dome to be a moon base but as soon as I put oxygen in any oxygen vent the game would just crash.

**Comment by voidsong-dragonfly** [comment]
Old AR version. Update to the latest beta

**Comment by JustaFloatingEye** [comment]
Ah ok

**Comment by JustaFloatingEye** [comment]
Oh the game just crashes on the latest version when I start the game. Gonna continue using the old version
