### ISSUE TITLE
[BUG] Unable to open Rocket Assembling Machine UI

### ISSUE THREAD

**Issue by Veylyn** [zmaster587/AdvancedRocketry#2199]
## Version of Advanced Rocketry
1.16.5-2.0.0-16

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
1.16.5-1.0.2-26

## Version of Minecraft
1.16.5 (Forge 36.2.2)

## Does this occur without other mods installed
Yes

## Description of the problem
Cannot open the rocket assembling machine UI. Even with a launch pad constructed as shown below, right clicking on the machine does nothing
![2021-08-28_10 10 31](https://user-images.githubusercontent.com/61519606/131222521-3097d4c8-f747-419c-a9df-cb5da186ee35.png)

**Comment by agentwolf88** [comment]
Same problem

**Comment by benyap** [comment]
Having the same issue!

**Comment by Iglesias-Leafwind** [comment]
Same thing... Tried with many different mods and just adv rocketry and I was unable to open UI. 
I downgraded to version 1.16.5-2.0.0-12 and everything seems to be working.

**Comment by Trinsdar** [comment]
here's a log for the issue: https://gist.github.com/Trinsdar/e8c3a5728bd1f98ce49bd89c35fa8c3c
