### ISSUE TITLE
[Suggestion]Support for more materials for plates and rods

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#22]
Currently there is no copper plate, gold and tin rod, etc
They could be used to replace crafting ingredients from other mods since machines from this mod are moar awsome :P
Is it possible to make a scan and add a plate / rod variants for ingots found in the oredict?

**Comment by zmaster587** [comment]
Slated for next content release.

**Comment by wormzjl** [comment]
Do you need a list of products or going to make something automatic?

**Comment by zmaster587** [comment]
will be automated
