### ISSUE TITLE
[BUG] Console spam-world save error

### ISSUE THREAD

**Issue by IchigoGames** [zmaster587/AdvancedRocketry#2203]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
>AdvancedRocketry-1.16.5-2.0.0-16-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>LibVulpes-1.16.5-1.0.2-26-universal

## Version of Minecraft
>1.16.5

## Does this occur without other mods installed
- [x] Y

## Crash report or log or visualVM (if applicable)
>https://www.dropbox.com/s/fv85phs5b10wpp5/latest.log?dl=0
>https://www.dropbox.com/s/9slkxxyka8qvs30/debug.log?dl=0

## Description of the problem
>Console spam on server error not being able to save world 

![image](https://user-images.githubusercontent.com/11888162/131280249-b9caa8ac-e2f7-4b8c-9b8b-bd015e599824.png)

**Comment by kdavis0619** [comment]
I had this issue as well. Reverting back to an older version of the mod fixed it for me. I'm not sure if the previous version works since I jumped back to version 10.

**Comment by Diversion98** [comment]
I got this issue as well also that it spams every 5 minutes that there is no minecraft:rutile minecraft:dilithium ...

**Comment by MWG-Logan** [comment]
Had the same thing. World would partial save it seemed, as I could restart the game and my newly created world would only then show up. Removing AR2 was the solution, very sadly.
