### ISSUE TITLE
[BUG] Game crashing whenever I use a tank or build a space station [1.12.2]

### ISSUE THREAD

**Issue by choombdev** [zmaster587/AdvancedRocketry#2205]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
-1.7.0-232

>Why is this important?

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
0.4.2-84

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y

>If Y, what is the MINIMUM set of mods required.

Aether, Aurorian, Atum 2. All explained below.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
PASTE 1 (From building space station): https://pastebin.com/mqa4gMmf
PASTE 2 (From using Oxygen Tank): https://pastebin.com/PcbZAnD6

## Description of the problem
I'm working on introducing Advanced Rocketry to my modpack currently and I was testing in the development version of the modpack on whether the PlanetsDefs was working or not, I fueled the rocket from multiple tanks and went to Luna no problem but once I tried launching a space station, I crashed.
I created a new instance on curseforge with only the listed mods (And extra utilities 2 for power) but still, I crashed twice. I crashed once while trying to insert an oxygen tank into the oxygen vent and another time when trying to build the actual space station (Like the first time). It seems to happen also with Fuel Tanks as my first crash in the dev version of the modpack mentioned the fuel tanks in the config.

>Why is this important?
>If we cannot reproduce the problem, we probably cannot fix it at all.]

**Comment by voidsong-dragonfly** [comment]
Outdated version.

**Comment by Qrbaker** [comment]
@Silfryi 1.12.2-1.7.0-232 is the main release file on [curseforge](https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files). Please consider marking -240 as release if you aren't backporting fixes: https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/3247375

If you are only supporting the "unstable" builds, you cannot call them unstable -- that is your primary support.

We have experienced the same issue on our server, with the following dump (essentially identical to the top report):

* Crash Report: https://gist.github.com/Qrbaker/89c2b3fa015875ee67ffc1dc2e5c03da
