### ISSUE TITLE
Crushing [BUG]

### ISSUE THREAD

**Issue by JPr874** [zmaster587/AdvancedRocketry#2206]
hello so i am using (AdvancedRocketry 1.12.2-2.0.0-254 build -254 for 1.12.2) version on minecraft 12.2.2,
I have every mod i need and have updated.
but every time i place one of these block (altitude control block, orientation control block, and the station gravity control block) and try to interact with any of these block my game crushes, and if i try to break the block it crushes my game.

**Comment by voidsong-dragonfly** [comment]
99% chance of failing to update LibVulpes. Needs the latest to run correctly.

**Comment by JPr874** [comment]
libvulpes is fully updated

**Comment by voidsong-dragonfly** [comment]
I need your LV version then.

**Comment by JPr874** [comment]
LibVulpes 1.12.2-0.4.2-84 build -84 for 1.12.2

**Comment by JPr874** [comment]
I am using LibVulpes 1.12.2-0.4.2-84 build -84 for 1.12.2
@Silfryi

**Comment by voidsong-dragonfly** [comment]
I need the log

**Comment by voidsong-dragonfly** [comment]
AR isn't updated. Closing
