### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NTrixner** [zmaster587/AdvancedRocketry#2207]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
1.12.2-2.0.0-254-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.12.2-4.22

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N/A

## Crash report or log or visualVM (if applicable)
https://pastebin.com/JAYb696t

## Description of the problem
Get a ClassDefNotFoundException on startup - I have a lot of mods so it's kinda difficult to discern where it comes from. My guess is it might be an issue with load order?

**Comment by NTrixner** [comment]
Update: Seems like this is an issue with JAOPCA and therefore a duplicate of https://github.com/TheLMiffy1111/JAOPCA/issues/193, but I am on the current version of JAOPCA and according to @TheLMiffy1111 this should work now

**Comment by festro** [comment]
Yeah the problem is with JAOPCA; had the same issue and deactivating it lets the game load.

**Comment by festro** [comment]
OK, it turns out the bug with JAOPCA is applicable to the release version of Advance Rocketry, the latest Beta build is compatible as NTrixner said. I didn't realize the curse client wasn't installing the latest version
