### ISSUE TITLE
Crash on bootup

### ISSUE THREAD

**Issue by Joey-Destroyah** [zmaster587/AdvancedRocketry#2209]
## Version of Advanced Rocketry
[Latest 1.12 deobf beta ]
## Have you verified this is an issue in the latest unstable build
Y,N, N/A Y
## Version of LibVulpes
[Latest 1.12 build]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.clamp(FFF)F
Exit Code: -1

## Description of the problem
[How can you reliably reproduce the problem]
Try to boot up with these mods 
![Screenshot (15)](https://user-images.githubusercontent.com/62820134/132267154-1332782c-acc9-4ab6-b652-62bf89ba639b.png)

**Comment by dmodoomsirius** [comment]
Why are you trying to launch with the front version? That is for development environments not for playing with.
