### ISSUE TITLE
[User Error?] Elevator automatically turns off

### ISSUE THREAD

**Issue by Joey-Destroyah** [zmaster587/AdvancedRocketry#2210]
## Version of Advanced Rocketry
[latest 1.12.2 version (not dev)]
## Have you verified this is an issue in the latest unstable build
Y,N, N/A Y
## Version of LibVulpes
[Latest 1.12.2 version]
## Version of Minecraft
[insert here]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[insert here]

## Description of the problem
[How can you reliably reproduce the problem]
Try to go into the elevator after turning the switch on.

**Comment by voidsong-dragonfly** [comment]
Reopen when an actual version number is provided. 'Latest' is _NOT_ a valid version.
