### ISSUE TITLE
Nuke engines???

### ISSUE THREAD

**Issue by Joey-Destroyah** [zmaster587/AdvancedRocketry#2211]
What is the NTM Engine supposed to be used for? It doesnt register as an engine on a launch pad. I'm using the latest 1.12.2 version. 
![2021-09-07_14 09 29](https://user-images.githubusercontent.com/62820134/132391130-56cab6b9-0cd0-4838-9f81-927b980d2441.png)

**Comment by Joey-Destroyah** [comment]
![2021-09-07_14 10 30](https://user-images.githubusercontent.com/62820134/132391253-ad8b7772-dab5-48a3-b42b-af651603e322.png)

**Comment by voidsong-dragonfly** [comment]
Needs a core block too.
