### ISSUE TITLE
[Request] Laser Drill Configuration - Weight and Quantity

### ISSUE THREAD

**Issue by anabsolutesloth** [zmaster587/AdvancedRocketry#2216]
Essentially an expansion to the existing Laser Drill configuration, Weight to determine the chance of something, instead of needing to shove an entry in multiple times to increase the Weight of it, and Quantity, to determine how much of the item is gotten when the item is rolled.

It could be formatted somewhat like this in configuration: `ITEM;QUANTITY;WEIGHT`
So `minecraft:cobblestone;5;10` is 5 Cobblestone, with a Weight of 10.

**Comment by voidsong-dragonfly** [comment]
Stack size should already be possible in 2.0.0
Weight I am not adding because all it would do is make multiple entries in the list - so you can do that yourself. Much more headache on my end than on yours.
