### ISSUE TITLE
[BUG] Game crashing upon using canister

### ISSUE THREAD

**Issue by cw4015** [zmaster587/AdvancedRocketry#2218]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-1.7.0-232-universal

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-84-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y

>If Y, what is the MINIMUM set of mods required.
- It occurs with only LibVulpes and AR

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>https://paste.ee/p/gRca5

## Description of the problem
>The crash occurs whenever I put an oxygen filled pressure tank into the gas charge pad interface. It happened with a normal sized tank and a low pressure tank. The crash also happens when putting an empty tank into the oxygen part of the Electolyser, however this can be worked around by directly right clicking with the tank instead of opening the interface. After a crash, the tank vanishes and is not in the player inventory or in the interface.

**Comment by voidsong-dragonfly** [comment]
Version out of date
