### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#222]
If you got only:
AdvancedRocketry-0.8.4 and LibVulpes-1.7.10-0.1.3-universal

Game will not launch, giving this [crash](http://paste.ee/p/BzmN8).
Yes, i know, you need ANY power generation mod (Thermal expansion, EnderIO, IC2) for this to work.
But can you make so it game don`t just crash, but explain what it needs. Or just add any power generator to game, and stop this nasty bug.

**Comment by zmaster587** [comment]
I'll look into backporting the 1.10.2 internal power system in the future when less preventable bugs stop coming in so quickly.

**Comment by zmaster587** [comment]
Should be standalone in AR 1.9.0
