### ISSUE TITLE
[BUG] [1.12.2] Server crash

### ISSUE THREAD

**Issue by aking4125** [zmaster587/AdvancedRocketry#2226]
Upon starting the server, the server crashes with the attached crash report. I also attached debug and latest.log files if anything. Occurs with 2.0.0 and 1.7.0. Deleted both configs and regenerated them. Nothing changes. 

## Version of Advanced Rocketry
>AdvancedRocketry 1.12.2-2.0.0-255 build -255 for 1.12.2
or
>AdvancedRocketry 1.12.2-1.7.0-232 build -232 for 1.12.2

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [] N
- [] N/A

## Version of LibVulpes
>LibVulpes 1.12.2-0.4.2-84 build -84 for 1.12.2
or
>LibVulpes 1.12.2-0.4.2-75 build -75 for 1.12.2

## Version of Minecraft
>Minecraft 1.12.2

## Does this occur without other mods installed
- [] Y
- [] N
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

## Crash report or log or visualVM (if applicable)
[crash-2021-09-17_21.23.59-server.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7188982/crash-2021-09-17_21.23.59-server.txt)

[debug.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7188983/debug.log)

[latest.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7188984/latest.log)

**Comment by voidsong-dragonfly** [comment]
Nothing to do with us.
