### ISSUE TITLE
[BUG] Crash on placing or right-clicking on altitude controller when reskillable is installed

### ISSUE THREAD

**Issue by juraj-hrivnak** [zmaster587/AdvancedRocketry#2227]
## Version of Advanced Rocketry
- Advanced Rocketry 1.12.2-2.0.0-255

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
libVulpes 1.12.2-0.4.2-84

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] N
- You need to have [reskillable](https://www.curseforge.com/minecraft/mc-mods/reskillable)

## Crash report & log
Crash report: https://pastebin.com/wXiEBmpJ
log: [latest.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7189905/latest.log)

## Description of the problem
Minecraft crashed when I placed the altitude controller. Then I opened the world again, right-clicked on the altitude controller, and it crashed again.

**Comment by voidsong-dragonfly** [comment]
That crash should be fixed in the latest release, I thought. Which you have. Can you check to make sure it's truly the latest?

**Comment by juraj-hrivnak** [comment]
Yeah, for sure! Here is a photo:
![advRocketry-TheTruth](https://user-images.githubusercontent.com/71150936/133890663-7e05249d-a6f7-4d24-88f3-5edb065b3e4e.png)

**Comment by juraj-hrivnak** [comment]
Is more information needed?

**Comment by voidsong-dragonfly** [comment]
Latest hasn't been released yet, I forgot the PRs hadn't been merged yet. In the future, don't pester mod devs, we'll ask if we need info.

**Comment by juraj-hrivnak** [comment]
Sorry, I was confused because of the Needs-Info label, my bad.

**Comment by voidsong-dragonfly** [comment]
Fixed in latest
