### ISSUE TITLE
Server crash after trying  to enter rocket assembling interface!

### ISSUE THREAD

**Issue by Grizzle1208** [zmaster587/AdvancedRocketry#2233]
## Version of Advanced Rocketry
1.7.10-1.4.0-20
## Have you verified this is an issue in the latest unstable build
 N/A
## Version of LibVulpes
1.7.10-0.2.6
## Version of Minecraft
1.7.10 FTB infinity evolved

## Description of the problem
As soon as i try to right click the rocket assembling block the server crashes, every thing else like the multiblock-machines and other stuff work perfectly. This problem is also accuring on the space station assembler. 

This is my given crash report:

https://pastebin.com/Ayzn4ELf

**Comment by Grizzle1208** [comment]
P.S. I used the modpack as a base and added a view other mods to it.

**Comment by voidsong-dragonfly** [comment]
OLD VERSION. We told you already. 1.7.10 is OUT OF SUPPORT
