### ISSUE TITLE
[Request] Disable spring world gen on planets

### ISSUE THREAD

**Issue by Lach01298** [zmaster587/AdvancedRocketry#2234]
I would like it if there was a way to disable minecarfts world gen feature: springs. Featured Below:
![2021-10-07_16 37 47](https://user-images.githubusercontent.com/8176057/136326126-92b41947-03b8-4431-80df-e22e2f0d67d4.png)

Main reason is I don't want them on certain bodies like the moon. I haven't seen any lava springs yet but I'm sure they probably spawn to.

**Comment by Gliese-832-c** [comment]
While I cannot fix this with my meager programming skills, I can provide you a temporary workaround. You can use BiomeTweaker and replace water blocks with stone/air/whatever you want. Of course this does require your planet to be either a custom biome or a biome you don't use anywhere else.

**Comment by voidsong-dragonfly** [comment]
Biome-dependent, datapackable therefore, and out of our control (we don't control the gen ourselves), and therefore fixed on 1.16.
