### ISSUE TITLE
[BUG] AR, SimpleDifficulty, ChickenLib

### ISSUE THREAD

**Issue by SilverBackSpartan** [zmaster587/AdvancedRocketry#2242]
[crash-2021-10-12_04.51.04-client.txt](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7328395/crash-2021-10-12_04.51.04-client.txt)

Crash happened while i was on my spacestation and viewing my RocketGui

**Comment by SilverBackSpartan** [comment]
![image](https://user-images.githubusercontent.com/91655215/136924996-3171a8b5-d99d-4422-9bf2-75ac699aac65.png)

Also placed an issue on SimpleDifficulty github

https://github.com/Charles445/SimpleDifficulty/issues/30

**Comment by voidsong-dragonfly** [comment]
Format not followed
