### ISSUE TITLE
[BUG] Moon/Luna Not loading completely/At all "bug" "MC 1.12.2"

### ISSUE THREAD

**Issue by Episec** [zmaster587/AdvancedRocketry#2245]
## Version of Advanced Rocketry
>AdvancedRocketry 1.12.2-1.7.0-232 build -232 for 1.12.2

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [ ] N
- [x] N/A

## Version of LibVulpes
>LibVulpes 1.12.2-0.4.2-84 build -84 for 1.12.2

## Version of Minecraft
>1.12.2, Using Hamachi for free multiplayer with a friend

## Does this occur without other mods installed
- [ ] Y
- [ ] N
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>I don't have access to this and it's not a crashing problem

## Description of the problem
>While on the Moon no terrain actually loads at all, while in singleplayer the terrain loads just fine. I am on my friends server and we are playing through lan using a hamachi network. 
![image](https://user-images.githubusercontent.com/92661565/137613866-d26a820b-18f5-44d4-9b21-17951bad9e8e.png)

**Comment by Episec** [comment]
This is my first github post so i don't really know how to navigate this sort of stuff that well. I can release the Modpack if someone wants to check this out

**Comment by voidsong-dragonfly** [comment]
Old Version
