### ISSUE TITLE
[Request] Square planets for the map and skybox

### ISSUE THREAD

**Issue by dazadazu** [zmaster587/AdvancedRocketry#2247]
For the life of me I can't figure out how to join the discord and I see that there is no config or resource packs online. In my opinion the sphere planets on the map and in the sky boxes are not really minecraft like and for me its hard to choose AR over GC but I really wanna make custom planets.

How come the planets are square when you're in the atmosphere but circle everywhere else?

**Comment by voidsong-dragonfly** [comment]
They're only 64x, they're pretty MC-y. Anyway, the ones rendered for space stations and such are square for tiling reasons, those can't be circular or they wouldn't tile well. Discord should be linked both from the readme and from CF. Planets are not going to become square as we tried that a while ago and it looked pretty bad.

**Comment by dazadazu** [comment]
They do look good. I found the discord it's just I dont understand giving myself a role because when I do nothing happens. Thank you for quick response. Also, what's the simplest way to delete all default planets so theres a clean slate?
