### ISSUE TITLE
[BUG] Moon is there if its day

### ISSUE THREAD

**Issue by Canina-X** [zmaster587/AdvancedRocketry#2252]
## Version of Advanced Rocketry
1.7.0-232-universal
## Have you verified this is an issue in the latest unstable build
N/A
## Version of LibVulpes
0.4.2-85-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[N/A]

## Description of the problem
So if its day the moon is too there... 
Is that normal?

**Comment by voidsong-dragonfly** [comment]
Old AR version
