### ISSUE TITLE
[BUG] in Altitute Controller and StationGravity Controller

### ISSUE THREAD

**Issue by n0home** [zmaster587/AdvancedRocketry#2254]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-2.0.0-256-universal.jar

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-85-universal.jar

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y

## Description of the problem
When i place the Altitute Controller and the StationGravity Controller,
they first can not be configed. They always take the maximum amount possible.

For example the Altitute controller lifts the Planet graphic as far away as it is possible.
There is no way to set the amound by clicking at the scale.

Only when i first click at the redstone control button
the machines start working.

After that is is all fine.

**Comment by voidsong-dragonfly** [comment]
... I don't see how it's a bug that redstone control overrides the value set in the GUI, redstone control is being constantly set but GUI is not.
