### ISSUE TITLE
[BUG]Fueling Station Tank Crash

### ISSUE THREAD

**Issue by mxnmnm** [zmaster587/AdvancedRocketry#2255]
## Version of Advanced Rocketry
>2.0.0-256

## Have you verified this is an issue in the latest unstable build
- Y

## Version of LibVulpes
>1.12.2-0.4.2-85 and 1.12.2-0.4.2-84

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
Haven't tested

## Crash report
>https://gist.github.com/mxnmnm/474d0b08fe1506a12a68c2561e7728cd

## Description of the problem
>Putting super high pressure tank in fueling station causes crash (do not shift click it in)

**Comment by GuineaPig2000** [comment]
Same issue here

**Comment by KasumiNova** [comment]
Same

**Comment by KasumiNova** [comment]
https://paste.ubuntu.com/p/jYPv6GCzHk/

**Comment by KasumiNova** [comment]
build250 no problem

**Comment by voidsong-dragonfly** [comment]
LibVulpes is too old

**Comment by mxnmnm** [comment]
Still occurs with the latest versions and no other mods installed :/

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/bd18ebf91f455c64f60ac86c1a1d0232
