### ISSUE TITLE
[BUG] rutile/dilithium block IDs not working

### ISSUE THREAD

**Issue by Sirenamogus** [zmaster587/AdvancedRocketry#2260]
## Version of Advanced Rocketry
>version(s): 232, 256.
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
>build(s): 85, 75.
## Version of Minecraft
>1.12
## Does this occur without other mods installed
Yes
## Description of the problem
when trying to add titanium and dilithium to only one specific world in my modpack I noticed that the "oreDilithium" ID reported by JEI didn't work. using NEI blockID dump I determined that the actual ID should be "ore0"
no big problem, I just put it as ore0 and it worked fine.
when I had the exact same experience with rutile ore I tried the same fix. however, for whatever reason, using the blockID reported by the block ID  dump didn't work. I tried substituting libvulpes:(blockID) with advancedrocketry:(blockID) to no avail. 
at this point I was using the most recent version of libvulpes and AR so I decided to go back a few versions to fix the issue. I went from the latest alpha build of AR to the latest release, and the latest version of libvulpes to the most downloaded version.
the issue still persisted after downgrading my version.

**Comment by voidsong-dragonfly** [comment]
Lean how to use block IDs and oredictionary IDs, this is not something you'll get help with here as these are basic packmaking questions.
