### ISSUE TITLE
[BUG] Server crashing when someone attempts to use a rocket.

### ISSUE THREAD

**Issue by choombdev** [zmaster587/AdvancedRocketry#2261]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
2.0.0-256

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
0.4.2.-85

## Version of Minecraft
> 1.12.2

## Does this occur without other mods installed
- It only occurs on the server.

## Crash report or log or visualVM (if applicable)
https://paste.gg/p/YTGF/b0f27840c35a47d5b91c2fccd89985be

## Description of the problem
Attempting to use a rocket to fly to either a planet or a space station causes the entire server to crash, if a player attempts to rejoin the server, the entire server crashes once more.

**Comment by voidsong-dragonfly** [comment]
This doesn't happen with just AR so I'm going to need you to find me the minimum modlist for it to happen. Try with just Phosphor and LagGoggles

**Comment by choombdev** [comment]
The issue only really happens on servers, I've tried on the same pack in a singleplayer world and it worked normally so I was hoping there was a way to figure out why it's only happening on the server.

Could this be an issue with Magma/Plugins?

**Comment by voidsong-dragonfly** [comment]
Oh almost certainly in that case. We can't support nonForge server softwares so if you want this fixed I'm going to need you to reproduce it on a plain-Forge server.

**Comment by choombdev** [comment]
Ah, I'll test it out then and let you know, thank you!
