### ISSUE TITLE
[Request] Individual station dimensions

### ISSUE THREAD

**Issue by Bysokar** [zmaster587/AdvancedRocketry#2264]
**What do you think is missing or what do you think can be done better**

I've recently had an incident on StargateMC.com that has resulted in infinite chunk generation in the space dimension.
I've so far been unable to recover it.

This is not necessarily a must, or even a want, and may be impossible based on how the mod is structured.

Would it be possible to split stations in the Space Dimension, having the station ID updated to be the dimension ID even?
This would have to be an opt-in feature, as I dont see how existing servers would be able to make use of it.

I've been making some  customizations as mentioned previously in #1781, I just thought I'd run this by you guys first to see if there was a game breaking reason it shouldn't happen OR if you're willing to implement.

**Comment by voidsong-dragonfly** [comment]
Not happening, and nothing should be generating in the station dimension anyway. They're all in a single dimension for good reason.
