### ISSUE TITLE
[BUG] Incompatibility with Mist Biomes mod

### ISSUE THREAD

**Issue by Pseudonomenclature** [zmaster587/AdvancedRocketry#2267]
## Version of Advanced Rocketry
All versions, as far as I can tell.

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
1.12.2-0.4.2-85 (latest)

## Version of Minecraft
1.12.2

## Description of the problem
Whenever the mod [Mist Biomes](https://www.curseforge.com/minecraft/mc-mods/mist-biomes), (which runs on [Mist Core](https://www.curseforge.com/minecraft/mc-mods/mist-core)) — which creates new biomes with a mist effect in the overworld — is installed alongside Advanced Rocketry, the mist of Mist Biomes will not render at all.

Reproducible by installing both Advanced Rocketry and Mist Biomes and entering any mist biome. (Worth installing Mist Biomes by itself first, to see what it's supposed to look like).

I've tried disabling possibly applicable things in the config file for Advanced Rocketry but with no luck.

If whatever is causing this issue is a common feature of Advanced Rocketry, then perhaps an easy fix could be to add an option in the config file to disable whatever that feature is.

It would be greatly appreciated if this was fixed on the end of Advanced Rocketry, as Mist Biomes has seemingly not been touched by its creator since 2018, and the issue is unlikely to be fixed at that end.

**Comment by voidsong-dragonfly** [comment]
AR 1.12 is at EOL and is only getting critical bugfixes. This is not critical.
