### ISSUE TITLE
[BUG] Server crash when loading chunks on certain planets

### ISSUE THREAD

**Issue by Firecube247** [zmaster587/AdvancedRocketry#2269]
## Version of Advanced Rocketry
2.0.0.-250

## Have you verified this is an issue in the latest unstable build
No

## Version of LibVulpes
0.4.2.-83

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Not tested since planet is custom made in Enigmatica 2: Expert.

## Crash report or log or visualVM (if applicable)
https://pastebin.com/zhHPSFEH

## Description of the problem
Every time I try to load new chunks on the planet Stella the whole server crashes. Other planets from the solar system like Neptune and Luna don't have this issue.

**Comment by voidsong-dragonfly** [comment]
Update, you should be on 256 and not 250.

**Comment by Firecube247** [comment]
I updated both Advanced Rocketry and LibVulpes to the newest version (-256 and -85), however the issue persists.

**Comment by NielsPilgaard** [comment]
This issue persists on build 257 and 88, it seems to be caused by generation of Hot Spring Water from Biomes O' Plenty.

**Comment by voidsong-dragonfly** [comment]
mmmkay, can I get a crash report from 257?I have a feeling they do something funky with hot spring water to make it return water blocks for everything, and it's causing the crash. I just need the new line #s to verify

**Comment by NielsPilgaard** [comment]
Sure thing, I asked the person who tested it for logs here: https://github.com/EnigmaticaModpacks/Enigmatica2Expert/issues/1973#issuecomment-1030074930

**Comment by Terra-B-Welch** [comment]
I have provided some crash reports on the E2E issue, I'll see if I can fetch the actual log files.

**Comment by voidsong-dragonfly** [comment]
So I _thiiiink_ I might have a very slim chance of a possible guess at what is happening. What's happening is that we set the hot spring water to air. BoP sees "oh, someone got/modifed the block" and returns water somehow, so we set _that_ to air but BoP ends us up in an endless loop from it of infinite water placement. The line that is erroring is [AtmosphereHandler#227](https://github.com/Advanced-Rocketry/AdvancedRocketry/blob/614442ed004093dbe20719d33ce3b71e278d7899/src/main/java/zmaster587/advancedRocketry/atmosphere/AtmosphereHandler.java#L227), which is just a block set.

Now I haven't looked at BoP code at all, but that is my guess

**Comment by NielsPilgaard** [comment]
Any chance of it being fixed? 😅

**Comment by voidsong-dragonfly** [comment]
Considering I don't have the time to support 1.12 any longer, very unlikely.

**Comment by NielsPilgaard** [comment]
Fair enough, thanks anyway 👍
