### ISSUE TITLE
Pipes don`t connect to Laser drill.

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#227]
http://imgur.com/kxxVui4
It`s not that big problem, but usually there is no such big chests to hold all items Laser can mine (Because laser works pretty fast) So you need to clear this chest pretty fast.
But most of mods don`t have item moving mechanics so fast to clear chest faster then it fill. That why dirrect pipe output would be much better.

**Comment by zmaster587** [comment]
Laser drill has 4 outputs now, should be enough I would think
