### ISSUE TITLE
[Request] Staging/Stage recovery

### ISSUE THREAD

**Issue by Joey-Destroyah** [zmaster587/AdvancedRocketry#2270]
**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]
I think you should add stage/booster separation because 
1. It's more realistic
2. You could be more efficient with your launches
3. You could recover them SpaceX style.
I understand if it's too much of a hassle, and I don't blame you.
Thanks for your consideration.

**Comment by voidsong-dragonfly** [comment]
Duplicate of #316
