### ISSUE TITLE
[Request] Manual Docking/ Gravity Assists

### ISSUE THREAD

**Issue by Joey-Destroyah** [zmaster587/AdvancedRocketry#2273]
**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]

Maybe add a 3d rendezvous and docking mechanic for rockets/spacecraft. Extendable Solar panels and stuff would be required, or else the craft wouldnt be able to fire its engines and move. And for hard mode, throw in KSP style orbital mechanics like gravity assists.

**Comment by voidsong-dragonfly** [comment]
Explain more, please, but this sounds unlikely to happen.

**Comment by Joey-Destroyah** [comment]
It would not be like the current alpha implementation of space travel. It could have a map screen and sorta realistic trajectories. You can use gravity assists to use less fuel. Cassini for example was only possible thanks to a series of gravity assists off venus, earth, and jupiter. This could lessen the rocket requirements for interplanetary, or possibly interstellar travel.

**Comment by voidsong-dragonfly** [comment]
Onscreen map and planning trajectories is still a massive pain. That is all automated to leave the mod accessible to people who are not looking to do trajectory planning. That is like seven hundred levels above where we are right now. Unlikely, maaaaybe later, probably not.
