### ISSUE TITLE
[BUG] Advanced Rocketry - Warp Core - Warp Controller Bug

### ISSUE THREAD

**Issue by Bonquarti** [zmaster587/AdvancedRocketry#2274]
I am encountering this error in 2 Modpacks.

FTB Continuum
Enigmatica 2: Expert

How can I solve this problem?

- No Planet Selected

- Destination is not visible

- Warp Core not working, I'm putting fuel.

Screenshots;
https://ibb.co/JqfHn7v
https://ibb.co/G9Tk9rD

**Comment by voidsong-dragonfly** [comment]
No version and both of these modpacks are (IIRC) on an old version. Update or no support. Do note that updating will likely break the pack, so go bug the authors.
