### ISSUE TITLE
[BUG] NullPointerException when looking at asteroids with the observatory in multiplayer

### ISSUE THREAD

**Issue by Scrungofan666** [zmaster587/AdvancedRocketry#2278]
## Version of Advanced Rocketry
> 2.0.0-232

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [] N
- [] N/A

## Version of LibVulpes
> 0.4.2-85

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y
- [] N
- [] N/A
>If Y, what is the MINIMUM set of mods required.
Advanced Rocketry
LibVulpes

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>https://pastebin.com/CniqsZVr

## Description of the problem
>Note: The problem occurs exclusively in multiplayer.  And the error only occurs in the client.
>Description: When trying to view asteroid contents in the observatory, a NullPointerException occurs in the client and no asteroid content information is shown in the GUI.
>Step 1: Create 1.12.2 multiplayer server
>Step 2: Build observatory multiblock
>Step 3: Insert data storage module with distance data
>Step 4: Scan for asteroids
>Step 5: Click on any asteroid.  Nothing will appear in the right hand side of the GUI, and there will be a NullPointerException in the client log.

**Comment by voidsong-dragonfly** [comment]
Version out of date.
