### ISSUE TITLE
[BUG] Multiplayer observatory NullPointerException on latest version

### ISSUE THREAD

**Issue by Scrungofan666** [zmaster587/AdvancedRocketry#2279]
## Version of Advanced Rocketry
> 2.0.0-257
> The latest code from the 1.12.2 branch on github

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [] N
- [] N/A

## Version of LibVulpes
> 0.4.2-87
> The latest code from the 1.12.2 branch

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y
- [] N
- [] N/A

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>(257 crash report) https://pastebin.com/QrJrXQz4
>(latest source code) https://pastebin.com/H0DzMWtg

## Description of the problem
>Note: The problem occurs exclusively in multiplayer.  And the error only occurs in the client.
>Description: When trying to view asteroid contents in the observatory, a NullPointerException occurs in the client and no asteroid content information is shown in the GUI.
>Step 1: Create 1.12.2 multiplayer server
>Step 2: Build observatory multiblock
>Step 3: Insert data storage module with distance data
>Step 4: Scan for asteroids
>Step 5: Click on any asteroid.  Nothing will appear in the right hand side of the GUI, and there will be a NullPointerException in the client log.

**Comment by voidsong-dragonfly** [comment]
You've somehow given the asteroid an invalid bask stack? Can I see the asteroid defs?

**Comment by Scrungofan666** [comment]
Here is the file that i'm using. 
https://pastebin.com/8qSYA92t

**Comment by voidsong-dragonfly** [comment]
Hmmmm..... I don't see why it's crashing but I'll poke around at the code and see what I can do without an IDE
