### ISSUE TITLE
[BUG] Multi-block machines not working

### ISSUE THREAD

**Issue by j3s5e4** [zmaster587/AdvancedRocketry#2280]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry

1.12.2-2.0.0-250-universal

## Have you verified this is an issue in the latest unstable build
- [x] N
Did find a similar issue but is years old: https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/718

## Version of LibVulpes

1.12.2-0.4.2-83-universal

## Version of Minecraft

Enigmatica2Expert-1.83, on Forge 14.23.5.2855

## Does this occur without other mods installed

- [x] Y
Standard E2E mods

## Crash report or log or visualVM (if applicable)

No crash

## Description of the problem

I have multi-block machines hooked up to ae2 interfaces or chests, when items are inserted into the input hatch, the machine doesn't take them unless I remove and re-insert them, or sometimes if I open the machine interface a few times.

**Comment by voidsong-dragonfly** [comment]
Old version.
