### ISSUE TITLE
[BUG] Weather still breaks with loaded space stations

### ISSUE THREAD

**Issue by Kammerjunk** [zmaster587/AdvancedRocketry#2283]
## Version of Advanced Rocketry
1.12.2-1.7.0.-232 (latest version for 1.12)

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

## Version of LibVulpes
1.12.2-0.4.2-75 (latest version for 1.12, 1.12.2-0.4.2-87 for unstable build)

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [x] Y
- [ ] N
- [ ] N/A

Requires a mod that lets you load chunks in order to reproduce it alone. I used FTBUtilities, which also requires FTBLib. If necessary, I can try with a different chunkloader as well.

## Crash report or log or visualVM (if applicable)
Not applicable. No error output either.

## Description of the problem
If a space station chunk is loaded, non-clear weather stops working in the Overworld. Rain or snow is for a second or so, and then it goes back to clear weather.
Reported a few times before in issues that went stale, see #1690 and #1838

To reproduce:
1. Build a space station
2. Launch the space station container in a satellite bay
3. Go to the new station (`/advRocketry goto station 1`)
4. Chunkload a chunk in the dimension
5. Go back to the overworld
6. Do `/toggledownfall`

**Comment by voidsong-dragonfly** [comment]
Old version. Also not much we can do if it's not already fixed, likely, because downfall is _worldwide_ AFAIK. (Specifically, update to a 2.0.0 version)

**Comment by Kammerjunk** [comment]
I'm sorry, I should have included that version number at the top or in the unstable version section. Yeah, I tried with 1.12.2-2.0.0-257 as well.
Makes sense that you can't if it's global. Thanks for the answer.

**Comment by voidsong-dragonfly** [comment]
Should be fixed in 1.16 hopefully but that's both likely not useful to you and still fairly broken, but I thought you might want to know.
