### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by freopt** [zmaster587/AdvancedRocketry#2285]
## Version of Advanced Rocketry
2.0.0-16

## Have you verified this is an issue in the latest unstable build
yes

## Version of LibVulpes
1.0.2-31

## Version of Minecraft
1.16.5

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://www.toptal.com/developers/hastebin/degihomocu.rb

## Description of the problem
Game crashes during startup

**Comment by voidsong-dragonfly** [comment]
new AR was supposed to release alongside new LV, it did not. This is almost certainly your issue.

**Comment by freopt** [comment]
how would it be my issue

**Comment by voidsong-dragonfly** [comment]
It's a turn of phrase saying that "this is the issue you are having". however, the fix is simply to roll back for now.

**Comment by freopt** [comment]
oh im stupid sorry

**Comment by SecretSeptus** [comment]
So fix for this issue is literally just wait for new AR update? kind of sad

**Comment by SecretSeptus** [comment]
> So fix for this issue is literally just wait for new AR update? kind of sad

![image](https://user-images.githubusercontent.com/98252762/150668960-0a60c28d-4425-49ab-97e2-4d50a0917807.png)

**Comment by dmodoomsirius** [comment]
What's kind of sad is people are expecting updates when you don't know peoples personal life. You don't know how much time they have to allocate to working on a project that they do in their free time. I've locked this issue for the time being.
