### ISSUE TITLE
Configuration file is not correct? [BUG]

### ISSUE THREAD

**Issue by Han-Solo-Order66** [zmaster587/AdvancedRocketry#2286]
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-2.0.0-12-universal.jar

LibVulpes-1.16.5-1.0.2-25-universal.jar
## Version of Minecraft
>1.16

building a server for Create Above and Beyond and when I launch the server it goes into a loop of saying Configuration file /user/Elerivalduke?Documents/minecraft Server/server/config/Advancedrocketry.toml is not correct. correcting, shortly after it repeats this exact same warning ad infinitum, any thoughts on how I may fix this?

**Comment by voidsong-dragonfly** [comment]
Just sort of happens atm, IIRC. is C:A&B with those exact versions, or did you update anything? AR 1.16 is extremely broken currently. (closed the issue because it's fixed in dev but there's several other things that need to happen for that to be pushed to prod)

**Comment by Han-Solo-Order66** [comment]
sounds good,k I'll look at a few things with updates to figure that out tomorrow. I've also got my main dev who understands mods infinitely better than I do on it, so we'll figure that out.

**Comment by voidsong-dragonfly** [comment]
Basically, C:A&B selected the best versions they could. If the ones they selected don't work there's very little we can do. I'm doing as much as I can in terms of updates but it's a one woman job atm because it's rewrites and concepts I specifically need to work through. Until then the versions that are out there is what's out there.

**Comment by Han-Solo-Order66** [comment]
sounds good and thank you for the work you do!
