### ISSUE TITLE
[BUG - 1.12.2] Space station is always a vacuum, air vents not working.

### ISSUE THREAD

**Issue by Terra-B-Welch** [zmaster587/AdvancedRocketry#2287]
## Version of Advanced Rocketry
>Initially tested with 2.0.0 build 250, but later tested with 2.0.0 build 257 with the same result.(latest beta on curseforge)

## Have you verified this is an issue in the latest unstable build
- [x] N/A

## Version of LibVulpes
>Initially tested on version 0.8.3, but later tested with version 0.8.8 with the same result.(latest beta on curseforge)

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A (This was on Enigmatica 2 Expert FYI)

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>No crash, so N/A

## Description of the problem
>Space stations will not fill with air, regardless of blocks used, even if the space station is airtight-ly sealed. A noteworthy thing with this bug is that when initially loading the world into the space station, it'll say there's pressurized air, but after the oxygen vents start making noise, it becomes a vacuum again.

Some images
https://imgur.com/GmMcDDt
https://imgur.com/0cw00Rq

I've tried changing the settings regarding the oxygen vents, but regardless of settings this issue occurs, even tried whitelisting blocks to no avail, just FYI I also tested this with a station made only out of vanilla blocks(glass and iron blocks), the same issue happens.

If it helps at all, I've had a discussion on this issue in the Enigmatica 2 Expert github too, linked below.
https://github.com/EnigmaticaModpacks/Enigmatica2Expert/issues/1998

**Comment by voidsong-dragonfly** [comment]
Your vent seems to not be redstone activated. The scrubbers may also not have carbon collection cartridges in them.

**Comment by Terra-B-Welch** [comment]
I have a cartridge in the scrubber, and I've both set the vents to ignore redstone signal and have tried it with a lever.
Keep in mind, they're making the sounds to indicate they're working, but checking with the analyzer still shows vacuum, in addition I still loose oxygen from my tank and without it I'd take damage from lack of air, torches also not working too, so I know it's not visual.

**Comment by voidsong-dragonfly** [comment]
oH I didn't even see that. You need two _scrubbers_ and one _vent_. Not two vents and one scrubber XD

**Comment by Terra-B-Welch** [comment]
When was this changed? Because I swear it used to be 2 vent 1 cartridge, now I feel stupid.

**Comment by Terra-B-Welch** [comment]
changed it to oxygen vent and two C02 collectors with cartridges on a server, issue persists, seems bug happens on servers.

**Comment by voidsong-dragonfly** [comment]
It has been this way since the system was introduced. That said, can you show me how the vent is being powered?

**Comment by Terra-B-Welch** [comment]
https://imgur.com/a/YdhKzf7

It's the same double-layer setup I've done in an earlier build of AR(In all the mods 3 remix) where I have the inner room surrounded by an outer shell to keep it airtight while allowing clean cable-running.

In all the mods 3 remix, this worked fine, but not here. Idk what got changed in 2.0.0 of AR to break this setup, though this setup also worked in singleplayer so idk.

**Comment by voidsong-dragonfly** [comment]
Only not working in multiplayer is a little weird. _That_ I have no clue why it's happening

**Comment by Terra-B-Welch** [comment]
Not sure if it just needed time or if the server's automatic restart fixed it, but my room in my space station on the server has air now, so I'm gonna close this, tho I will close it with this statement, torches still don't work in a space station even when it has oxygen in it.
