### ISSUE TITLE
[QUESTION] Making rocket land in specific area of space station?

### ISSUE THREAD

**Issue by Terra-B-Welch** [zmaster587/AdvancedRocketry#2288]
So I built a rocket bay on my space station and it's where I'd like my rocket to land, but I can't figure out how to force it to land on the specific coordinates of the space station. I've tried messing around with the ID chip while on the station as well as tried to set it up with a station docking port(It says on the wiki you're supposed to keep the chip when adding a module to a space station? Mine gets eaten every time, though I've been good about keeping extras)

I just want my rocket to land in the room I made for it, and not on top of my Astral Sorcery celestial gateway room every time, how can I get it to land where I want it to?

Heck if there's some unknown wiki link I don't know about, tell me that too, but I checked the space station page, the space station assembler page, the id chips page and a few others, following what I read but still getting stuck.

**Comment by voidsong-dragonfly** [comment]
Re: chip eating. That's intentional as it was causing duplication bugs the other way and it makes more logical sense for it to eat the chip. Copy chips in the satellite builder.
Re: docking. Use the landing pad (looks like an all-border concrete block) and explicitly select it in the station ID chip.

**Comment by Terra-B-Welch** [comment]
How do I select it with the ID chip? Do I just right click? Because I swear I tried to right click it with no result.

**Comment by voidsong-dragonfly** [comment]
Should be I think shift-rightclick to open the UI.

**Comment by Terra-B-Welch** [comment]
I tried a shift + right click at the landing pad and tried to save as a new one while on the station, it didn't save the coordinates at all, it just did nothing.

**Comment by Terra-B-Welch** [comment]
But yeah, I've tried shift + right clicking and clicking add new, works fine on the overworld but on my space station it does nothing at all, clicking the other options also doesn't get rid of a "last" coordinate either if one is there, but it doesn't matter if the last coords are there or not, it won't add the new coords regardless of how many times I shift+right click the launch pad and click "add new"

**Comment by voidsong-dragonfly** [comment]
You should be able to specifically select a placed pad block on the station.

**Comment by Terra-B-Welch** [comment]
https://imgur.com/a/UtDWUcX

I've tried the single launch pad tile as well as a 3x3 launch pad(I've a 3x3 rocket), no option to select the launch pad on the station shows up.

I know enigmatica 2 expert is still on build 250, not sure if this is a build 250 bug that was fixed in a later build, or if I'm just so dense I can't figure it out.

**Comment by Terra-B-Welch** [comment]
Once again, I am dumb, I got the launch pad mixed with the docking pad, my bad.
I wholeheartedly apologize for wasting your time.
