### ISSUE TITLE
Can`t find Laser Drill dimmension blacklist.

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#229]
I looked at config, bit can`t find Blacklist for Laser drill. You sayed you will add it in Ver. 0.8.4.

**Comment by zmaster587** [comment]
I apologise, I actually forgot to implement it, outside of mod dev, my schedule is absolutly hectic right now.

**Comment by zmaster587** [comment]
implemented in build 0.8.5
