### ISSUE TITLE
[BUG] Server crashes with "NoSuchMethodError: zmaster587.libVulpes.util.FluidUtils.attemptDrainContainerIInv"

### ISSUE THREAD

**Issue by pillose** [zmaster587/AdvancedRocketry#2291]
## Version of Advanced Rocketry
 1.12.2-1.7.0-232

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
 1.12.2-0.4.2-88

## Version of Minecraft
 1.12.2

## Does this occur without other mods installed
- [x] N/A
 I didn't tried to do same thing without other mods. However, according to the crash report, I'm quite sure that libVulpes cause the crash.

## Crash report or log or visualVM (if applicable)
 https://pastebin.com/tCS0gY8S

## Description of the problem
 I was trying to build a space station using Space Station Assembler. When I pressed the "Build" button, my server crashed. I assume that a Oxygen Vent in my station cause the crash.

As I know, the "NoSuchMethodError" occurs when when an application does not find a called method(`attemptDrainContainerIInv` in this case) at runtime. 
So I decompiled the "AdvancedRocketry-1.12.2-1.7.0-232-universal.jar" and "LibVulpes-1.12.2-0.4.2-88-universal.jar", and found the functions in the crash report: `zmaster587.advancedRocketry.tile.oxygen.TileOxygenVent.func_70299_a` and `zmaster587.libVulpes.util.FluidUtils.attemptDrainContainerIInv`.

Then, I found that libVulpes contain "attemptDrainContainerIInv" method;
>`public static boolean attemptDrainContainerIInv(EmbeddedInventory inv, IFluidHandler tank, @Nonnull ItemStack stack, int inputSlot, int outputSlot)`

... I could't find the the cause of crash.
I whish this issue could help fixing the bug  : )

**Comment by voidsong-dragonfly** [comment]
Old AR version
