### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by YarinQuapi** [zmaster587/AdvancedRocketry#2293]
## Version of Advanced Rocketry
1.16.5-2.0.0-16-universal

## Have you verified this is an issue in the latest unstable build
This is the only build available for 1.16.5 to my knowledge

## Version of LibVulpes
1.16.5-1.0.2-31

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
I currently don't know, and if so, I can't test each mod currently.

## Crash report or log or visualVM (if applicable)
https://pastebin.com/s505CF06

## Description of the problem
Open Minecraft and crash.

**Comment by voidsong-dragonfly** [comment]
Downgrade LibVulpes
