### ISSUE TITLE
Crash on World Generation with Bonus Chest

### ISSUE THREAD

**Issue by condensedapple** [zmaster587/AdvancedRocketry#230]
Game crashes when creating a world **with "Bonus Chest" enabled**: [Crash Report](https://gist.github.com/condensedapple/fc1165538f2ec9ceec436ad49f976102)

**Comment by zmaster587** [comment]
Should be fixed in next release, dupe of #221 and #219 
Thank you for at describing the conditions under which this occurs though, is very helpful comparatively.

**Comment by condensedapple** [comment]
Thank you for the quick reply. I will check the existing issues in the future.

**Comment by zmaster587** [comment]
No problem!
