### ISSUE TITLE
Advanced Rocketry load_registries event Phase Crash - 1.16.5 - Forge 36.2.21

### ISSUE THREAD

**Issue by Whottech** [zmaster587/AdvancedRocketry#2301]
Hi, After updating a few mods for our pack and after checking to ensure it was working correctly, i comes up with the following.

![Screenshot 2022-03-21 105839](https://user-images.githubusercontent.com/89362802/159191623-7bc01497-670e-4079-9bbd-80c2bed26380.png)

The following is the crash log - https://pastebin.com/A8bufhBi

Has anyone had this issue before? i did a quick scan through the issues but couldn't see anything.

**Comment by voidsong-dragonfly** [comment]
Downgrade libvulpes. new release wasn't quite meant to go out yet
