### ISSUE TITLE
[BUG] Item texture missing when install with certain mods, cause by registering at wrong event

### ISSUE THREAD

**Issue by kappa-maintainer** [zmaster587/AdvancedRocketry#2304]
## Version of Advanced Rocketry
[1.12.2-2.0.0-257 build -257 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/3587070)

## Have you verified this is an issue in the latest unstable build
- [x] Y
- [ ] N
- [ ] N/A

## Version of LibVulpes
[1.12.2-0.4.2-88 build -88 for 1.12.2](https://www.curseforge.com/minecraft/mc-mods/libvulpes/files/3611363)

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
- [ ] Y
- [x] N
- [ ] N/A

## Crash report or log or visualVM (if applicable)
No crash

## Description of the problem
Install Advanced Rocketry with the latest [Double Slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs/files/3387140) or [Grappling Hook Mod](https://www.curseforge.com/minecraft/mc-mods/grappling-hook-mod/files/3711089), launch the game, all blocks registered through LibVulpesBlocks.registerBlock will have a black & purple checkerboards model. This is because https://github.com/Advanced-Rocketry/libVulpes/blob/2c0231c5d821e2901459401a21dd253c6759821c/src/main/java/zmaster587/libVulpes/api/LibVulpesBlocks.java#L85 was executing at block register event, not model register event.

**Comment by voidsong-dragonfly** [comment]
1.12 is no longer supported via code changes
