### ISSUE TITLE
Creating a unified space

### ISSUE THREAD

**Issue by Titlehhhh** [zmaster587/AdvancedRocketry#2307]
[Translated]
I really like your interplanetary flight system. 
I was introduced to your mod at a young age, but also to galacticraft. I liked everything about them, but I would like a mod where space is a separate dimension in which each planet is an entity that you fly into and get to the actual planet. 
Now I already have a better knowledge of the workings of mincraft(protocol) and I was wondering how difficult it is to implement something like that.
My concept is as follows: take off on the ground (for example), to a height of 20k blocks. Then the space itself appears, but with one condition - there is no division into chunks, just 3D space (This is done for performance reasons). Then a long flight through hundreds of thousands of blocks and to the planet, which will be a sphere (or cube) in which you fly in and get to the planet.
The main thing about this concept is the long journey through infinity, comparable to the journey to the edge of the world. A rocket or spaceship is a more convenient means of transportation. In theory, you can fly without it.

I ask you, as more experienced developers (I have almost no experience in this area), how hard is it to do? Can it be done in AR? And are you interested in it?

**Comment by Titlehhhh** [comment]
I'm sorry, I chose the wrong type of question.

**Comment by voidsong-dragonfly** [comment]
First off, read the pinned issues. Second off no, this is out of useful implementation range to do properly in MC _anyway_ and provides the wrong feeling.
