### ISSUE TITLE
[suggestion] changing animals on planets

### ISSUE THREAD

**Issue by slendercreeper1010** [zmaster587/AdvancedRocketry#231]
then I enter earth-like planets (with no oxygen on them) I sometimes find animals spawning and dying on these planets, maybe you can make them despawn, or make mutated versions of them, so they can live in no oxygen planets

**Comment by zmaster587** [comment]
Will look into it

**Comment by slendercreeper1010** [comment]
thanks

**Comment by zmaster587** [comment]
I've just modified the threshhold at which a planet is considered to have to atmosphere.
