### ISSUE TITLE
[BUG] Space Elevator not working

### ISSUE THREAD

**Issue by ScriptAccount323** [zmaster587/AdvancedRocketry#2310]
Version of Advanced Rocketry
- 2.0.0-257(1.12.2)

Have you verified this is an issue in the latest unstable build
- No

Version of LibVulpes
- 0.4.2-88(1.12.2)

Version of Minecraft
- 1.12.2

Does this occur without other mods installed
- Yes

Description of the problem
Basicly when i want to use the space elevator i cant put a chip inside of it it says this:
https://prnt.sc/04K60LnM6qyw

**Comment by voidsong-dragonfly** [comment]
Space elevators changed, you need to link them with the linker to have them function. They're also 1:1 now and not many:many
