### ISSUE TITLE
[BUG] Space Elevator not working properly

### ISSUE THREAD

**Issue by ScriptAccount323** [zmaster587/AdvancedRocketry#2311]
## Version of Advanced Rocketry
> 2.0.0-257(1.12.2)

## Have you verified this is an issue in the latest unstable build
- No

## Version of LibVulpes
> 0.4.2-88(1.12.2)

## Version of Minecraft
> 1.12.2

## Does this occur without other mods installed
- No

## Description of the problem
> Space Elevator dosent land on platfrom
https://prnt.sc/4O7EKNIJhIKr() its the capsle below

**Comment by voidsong-dragonfly** [comment]
"The screenshot was removed"

**Comment by ScriptAccount323** [comment]
> "The screenshot was removed"

https://prnt.sc/4O7EKNIJhIKr
https://prnt.sc/8_pmCCmQjy02
last one is better

**Comment by voidsong-dragonfly** [comment]
That's normal. It faces down now
