### ISSUE TITLE
[BUG] Cant use or even add Flight Speed Control Upgrade to helmet

### ISSUE THREAD

**Issue by Otaku22** [zmaster587/AdvancedRocketry#2312]
## Version of Advanced Rocketry
>Current release 1.12.2-1.7.0-232

## Have you verified this is an issue in the latest unstable build
- [x] Yes, it is still a problem

## Version of LibVulpes
>Current release 1.12.2-0.4.2-22

## Version of Minecraft
>1.12.2 

## Does this occur without other mods installed
- [x] Y 

>If Y, what is the MINIMUM set of mods required.
Advanced rocketry
LibVulpes

## Crash report or log or visualVM (if applicable)
No crashing, the item just wont go into my helmet

## Description of the problem
>I made a space suit helmet, and a flight speed control upgrade to make the jetpack faster, yet it wont install. I can install all other mods, but this one. It acts just like a iron chest piece does if you attempt to put it into a furnace fuel slot. It wont go in

**Comment by voidsong-dragonfly** [comment]
Old version.
