### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by crabbee88** [zmaster587/AdvancedRocketry#2313]
## Version of Advanced Rocketry
 1.12.2-2.0.0-7
## Have you verified this is an issue in the latest unstable build
Yes
## Version of LibVulpes
1.12.2-0.4.2-22
## Version of Minecraft
1.12.2
## Does this occur without other mods installed
Yes
>If Y, what is the MINIMUM set of mods required.
Only advanced rocketry and libvulpes.
## Crash report or log or visualVM (if applicable)
https://pastebin.com/ZJFQcJYd
## Description of the problem
"Latest version" of advanced rocketry and libvulpes crash together when downloading on launcher with no other mods. Can replicate by creating a new profile/pack and just downloading advanced rocketry then updating to the latest beta on the versions tab then it'll prompt you to update again giving you the AR 2.0.0-7 version. version 2.0.0-12 works.  The problem is it prompting people to use the broken version. Hope this helps, thanks!

**Comment by dmodoomsirius** [comment]
Maybe curse is taking a bit to update as I archived that version when I found it was bad while working on getting it working properly. Not sure what happened. If it continues I'll reach out to curseforge support.

**Comment by crabbee88** [comment]
I tested today looks like it has resolved itself so far in my launcher.
