### ISSUE TITLE
[Request 1.12.2] Relax whatever is blocking grass spreading on space stations

### ISSUE THREAD

**Issue by Deiwos** [zmaster587/AdvancedRocketry#2314]
Currently, there appears to be some sort of method in the mod that intercepts any change of a block into grass in the space station dimension, and turns it back into dirt instead, presumably as a kinda blunt way to prevent grass spread in space. However, the problem is that this prevents any method of turning dirt into grass, such as Botania's Pasture Seeds. ...or Effortless Building's block replace functionality. Even when the room in question is pressurized.

So I'd like to please request that this method at least be removed if it can't easily be made to check for whether there's oxygen, because the stuff it inadvertently prevents outweighs the break in 'realism' grass spreading in space would present in my opinion.

**Comment by voidsong-dragonfly** [comment]
It should work with pressurized environs. Regardless this system is being reworked in 1.16 and is currently nonfunctional, and work on 1.12 has stopped.
