### ISSUE TITLE
compat with tfc

### ISSUE THREAD

**Issue by Woody-0w0** [zmaster587/AdvancedRocketry#2318]
forge version:
forge1.12.2-14.23.5.2847
mod version:
AdvancedRocketry-1.12.2-1.7.0-231
TerraFirmaCraft-MC1.12.2-1.7.10.168

Item firestarter in tfc mod can lit fire or firepit in somewhere not allowsCombustion.
I try to add a judgement at the onUsingTick of Itemfirestarter, set chance of lit-success to 0.
```      
//..............
import zmaster587.advancedRocketry.atmosphere.*;
//..............
 if (world.func_175727_C(pos)&&AtmosphereHandler.getOxygenHandler(world.field_73011_w.getDimension()).getAtmosphereType(pos).allowsCombustion()) {
            chance *= 0.5;
        }
        else if (world.func_175727_C(pos)&&!AtmosphereHandler.getOxygenHandler(world.field_73011_w.getDimension()).getAtmosphereType(pos).allowsCombustion()) {
            chance *= 0.0;
        }
//............
```
bug report:
```
java.lang.VerifyError: Expecting a stackmap frame at branch target 103
Exception Details:
  Location:
    net/dries007/tfc/objects/items/ItemFireStarter.onUsingTick(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;I)V @87: ifeq
  Reason:
    Expected stackmap frame at this location.

```

how to fix it ?

**Comment by voidsong-dragonfly** [comment]
I need version information

**Comment by Woody-0w0** [comment]
> I need version information

Maybe I should ask dries007 for solution :D

**Comment by voidsong-dragonfly** [comment]
I still need version information because that function may change significantly later on

**Comment by Woody-0w0** [comment]
> I still need version information because that function may change significantly later on

forge version:
forge1.12.2-14.23.5.2847
mod version:
AdvancedRocketry-1.12.2-1.7.0-231
TerraFirmaCraft-MC1.12.2-1.7.10.168

**Comment by voidsong-dragonfly** [comment]
Ah, we're no longer developing for 1.12
