### ISSUE TITLE
Rocket sometimes launching as soon as it gets fuel/lands

### ISSUE THREAD

**Issue by HyperionNexus** [zmaster587/AdvancedRocketry#233]
This is a really sporadic bug that has happened throughout different versions. Nothing specific causes it to happen either. All I do know is that it can happen just after a rocket is formed and it gets fuel, or it's landing.

Current version: 0.8.4

**Comment by TheGuyRunningSouth** [comment]
Probable dupe of #201. What's next to your monitoring station block?

**Comment by HyperionNexus** [comment]
A space station assembler and rocket unloader.

**Comment by TheGuyRunningSouth** [comment]
IIRC, the unloader emits a redstone signal when the rocket is empty.
Placing it next to a monitoring station (which is redstone sensitive) will
cause an empty rocket to launch as soon as it can. Try moving the unloader
away from the monitoring station.

**Comment by zmaster587** [comment]
Redstone level behavior should be configurable in the next build
