### ISSUE TITLE
1.12.2 Pipes and cables? 

### ISSUE THREAD

**Issue by JedaiGames** [zmaster587/AdvancedRocketry#2334]
## Version of Advanced Rocketry
> 2.0.0 build 13

## Have you verified this is an issue in the latest unstable build
- Y

## Version of LibVulpes
> 0.4.2 build 25

## Version of Minecraft
> 1.12.2

## Does this occur without other mods installed
- Y

## Description of the problem
> There's no solution for energy and liquid transporting. 
I remember that early there was a 3 types of pipes, for energy, liquid and data. Now we have only wireless data transmiter, but no energy or fluid transportation. 
Please, can you return pipes if there's no replacement for them?

**Comment by voidsong-dragonfly** [comment]
Intentional. Use other mods.
