### ISSUE TITLE
Rocket disapear when travel to station

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#238]
Ver. 0.8.5
If you make station, and launch it. Then make rocket, and travel to newly created station, rocket will disapear when you arive to station. You will start falling from 1000 block heigh.

**Comment by DevTimur** [comment]
New info i found (Maybe will help to understand something?)
If you use any handhelp teleportation device (I use Daconiv Evolutions Dislocator) you will teleport WITH vehicle you sitting on.
When you arive to station, rocket is invisible (Looks like it disapear) But... If you teleport to any other location, (In diffrend dimension) you will get there sitting on your rocket, so its not disapear.

**Comment by DevTimur** [comment]
New obseravations.
When i traveled to station, i spawned without rocket, but a moment later rocket spawned aswell, and i teleported to its seat.

**Comment by DevTimur** [comment]
New data.
In console i see this message if rocket spawns at space station
"[Draconic Evolution]: Successfully placed player on mount after 0 ticks"
and if rocket disaper i get this message
"[Draconic Evolution]: Unable to locate player mount after 500 ticks! Aborting"
Not sure what this all about...

**Comment by zmaster587** [comment]
is this MC 1.7.10 or MC 1.10.2?

**Comment by DevTimur** [comment]
1.7.10

**Comment by zmaster587** [comment]
That sounds nearly identical to #211
