### ISSUE TITLE
Rocket reach Y =995 and won't load "space" dimension

### ISSUE THREAD

**Issue by EnnekPL** [zmaster587/AdvancedRocketry#239]
Hi 
AR 0.8.0 (client side)
when the rocket took off with me, the rocket stopped at y = 995 and nothing has happened, after burning fuel rocket fell to earth,  I tried again but the same thing happened.

**Comment by zmaster587** [comment]
Did you have a rocket go missing at any point in time?

**Comment by EnnekPL** [comment]
no.
btw you have made great mod! can I try make cosmetic addon to your mod like rocket structure parts? (tanks, cocpits, pods, decouplers, nos cone, fins, body tube for more realistic)

**Comment by zmaster587** [comment]
if you like, also could you upload the world (or at least the region with the rocket and level.dat) so i can try to see what's going on with that?

**Comment by zmaster587** [comment]
What do you have in the guidance computer of the rocket?

**Comment by EnnekPL** [comment]
I made custom world for testing something, i make space station and i send in rocket (satelit bay). first space station on map always crash but You know about this bug and You fix this. I send my self to station and it work well, but second time when i try to get to spac station from minecraft earth i just stop at y=995.  in the guidance computer i had copy of space station ID chippset. i was trying 3 timse and always stop at 995. I deleted this world map after this problem.

english is my not first language ;)

**Comment by zmaster587** [comment]
Did you regenerate the world between the one where it crashed and when it got stuck at 995?

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
Same happened when i tried to go to MOON (luna) CREATIV and SURVIVAL
at 995 says press Space to ......
sinks to 800 and restarts at 995 to sink

**Comment by zmaster587** [comment]
That sounds like a lag issue @ThisIsTheGitHubAccount4MUHAKL , I think ennekpl is describin taking off, not landing

**Comment by EnnekPL** [comment]
I started testing on new world (on new world all works great)
