### ISSUE TITLE
[BUG] Rolling Machine does not assemble under mod v1.12.2-2.0.0-17

### ISSUE THREAD

**Issue by ghost** [zmaster587/AdvancedRocketry#2395]
## Version of Advanced Rocketry
>v1.12.2-2.0.0-17

## Have you verified this is an issue in the latest unstable build
- [x] N/A
- [ ] I appear to be using the most recent build

## Version of LibVulpes
>1.12.2-0.4.2-25

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] Y
>If Y, what is the MINIMUM set of mods required.
do you mean, if N? The minimum set of mods required to reproduce the issue is Advanced Rocketry and LibVulpes.

## Crash report or log or visualVM (if applicable)
>I can, if you like, take screenshots of the multiple configurations I have tried, including the one in the holo projector, the one on the FTB wiki, and one from the most-recommended instructional video. None were viable. There is no crash, hence no crash log.

## Description of the problem
>Rolling Machine multiblock structure will not assemble, regardless of build design used. I have tried three, and get a red X for each one.

**Comment by ghost** [comment]
![2024-05-29_09 24 04](https://github.com/Advanced-Rocketry/AdvancedRocketry/assets/29690206/dd5cb144-6ff0-4cbb-9625-773a2f584213)
Holo Projector design

![2024-05-29_09 28 01](https://github.com/Advanced-Rocketry/AdvancedRocketry/assets/29690206/23cd1222-274f-422c-aa2d-6869056deb7e)
Feed The Beast wiki design

**Comment by voidsong-dragonfly** [comment]
Missing the second layer for the holoprojector design, which is the correct one.
