### ISSUE TITLE
Crash on Server during World Gen

### ISSUE THREAD

**Issue by rckymtnrfc** [zmaster587/AdvancedRocketry#240]
This crash appears to be an issue between JurrasicCraft and Advanced Rocketry but if I pull that mod out, it changes to being an issue with Realistic Survival and Advanced Rocketry (the Realistic Survival mod generates clay underground).  If I turn off the clay spawn, the crash goes away.

It only seems to happen right after the initial world generation.  If I add in AR after that point, I don't seem to have any issues even as new land generates.

http://pastebin.com/HJ8uHgkg

Thanks for taking a look at this.

**Comment by zmaster587** [comment]
Try 0.8.5, I fixed a similar crash involving the bonus chest in that
version

**Comment by rckymtnrfc** [comment]
Sorry, I should have checked that I had the latest version before reporting the crash.  Somehow I missed the notification you updated.

That seems to have resolved the problem.  Just fired up the server and let it generate a new world.  No crash.

Thank you!  Super excited to play with your mod.
