### ISSUE TITLE
Item belonings?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#241]
Seem that in the latest version all ingots, plates, etc belongs to libvulpes
But the newly added titanium aluminide is still in the main mod

**Comment by zmaster587** [comment]
That is intentional, I'm in the process of moving the common materials and ore system in libvulpes so an upcoming machine mod I'm working on can reuse the code and ores, titanium aluminide has not been moved over as I do not intenend to use it in any other mod.

**Comment by wormzjl** [comment]
oh that's really amazing, can you give a sneak peek about what's coming?

**Comment by zmaster587** [comment]
Is basically an ore processing/machine mod, kinda my take on gregtech/IC2, but with multiblock machines
