### ISSUE TITLE
Intermittent Crash With the HoloProjector

### ISSUE THREAD

**Issue by Hastling** [zmaster587/AdvancedRocketry#245]
Referencing #243. When using the latest version of Advanced Rocketry both myself and a friend on our server experience a crash when using the Holo Projector. The steps to repeat the crash are as follows. 

1. Place the initial hologram, in this case the cutter.
2. While holding shift scroll up.
3. Right click the cutting block to set the next layer
4. Crash and proceed to cry. 

[Here's](http://pastebin.com/GL7L0xxt) a copy of my log, [here's](http://pastebin.ca/3728630) a copy of my friends, additionally [here's](http://pastebin.com/1nQc62xF) a snippet of the server FML latest log at the moment of crash.

Edit: It appears that when you scroll down with the Holo Projector to display all the layers at once you can avoid the crash, but when you scroll up you're almost certainly going to experience the aforementioned crash.

**Comment by zmaster587** [comment]
I'm not able to replicate this at all with just AR and libvulpes,  does this still occur if you remove McJtyLib?

**Comment by Hastling** [comment]
Removed McJtyLib and tested on SSP and couldn't replicate the crash, additionally upon re-adding along the dependency's it and testing in the same server that caused the aforementioned crash I could not get the crash to occur with the steps I laid out before..... So with that in mind I think I'll be closing this issue and if I run into any more Java oddity's in the future I'll let you know.

**Comment by zmaster587** [comment]
I think I found the problem with it and I suspect it was possibly a timing
issue, also led me to find another bug where some machines didn't
differentiate between input and output plugs in the holo projector

**Comment by Hastling** [comment]
Ahhhhhh that explains MechaJ's issue with the power port, cause we both saw it asking for that rather than an input/heat block in the holo projection.

**Comment by zmaster587** [comment]
The bug I found had proper visuals but pick block always returned an input
hatch instead if an output hatch, input /output hatches share the same
block but the power block doesn't.. the mystery deepens...

**Comment by Hastling** [comment]
Yes I see now that you have all the libvulpes:hatch's the same just differentiate with NBT which I always prefer to keep block ID count low. I'm no Modder by any means but I can definitely see the mystery in this.
