### ISSUE TITLE
Crash when right clicking input power plug

### ISSUE THREAD

**Issue by MechaJ** [zmaster587/AdvancedRocketry#246]
Crash when right clicking input power plug on side arc furnace.  It was a complete multiblock before server restart, but not after
http://pastebin.ca/3728696

**Comment by zmaster587** [comment]
I'm not able to get it to crash, however I have observed some other odd effects that i suspect stem from the same source as that problem (such as the power bar showing 0/0)

**Comment by Hastling** [comment]
He had a power port (rather than a input port) on the side which I suspect was causing the odd effects that you were talking about. When I replaced the power port with an input port and replaced the arc furnace control block it reformed the multiblock and it was functional.

**Comment by zmaster587** [comment]
Oh, that's an entirely different beast

**Comment by zmaster587** [comment]
I thought he had built it correctly  (and was kinda wondering about the odd
phrasing a bit)

**Comment by Hastling** [comment]
Well the thing is, it "was" working with that power port prior to the restart, but after the restart he was talking about it's like the check to see that it was a multiblock realized that it wasn't indeed a correctly formed structure and when right clicking on that side power port to open the GUI that's when the crash would occur. But as I said, when I removed the power port and replaced it with the appropriate block the multiblock check worked and now that GUI opens without issue.

**Comment by zmaster587** [comment]
Alright, that last patch should still fix that I think though so ima close this, if it happens with libvulpes 0.1.5, I'll dig into it again.
