### ISSUE TITLE
[Suggestion] chisel and bits support 

### ISSUE THREAD

**Issue by ChilledDayz** [zmaster587/AdvancedRocketry#247]
Are there any plans to add chisel and bits support for rockets and space stations?

**Comment by zmaster587** [comment]
Chisel and bits already seem to work (Advanced Rocketry 1.10.2-0.8.6 and chiselsandbits-12.6)

**Comment by ChilledDayz** [comment]
Oh thanks for letting me know that's awesome. Do you want me to close this issue?

**Comment by SFort** [comment]
![unbuilt](https://cloud.githubusercontent.com/assets/1879846/25812278/1b21dfce-3416-11e7-9f21-28490bffae75.png)
![built](https://cloud.githubusercontent.com/assets/1879846/25812283/1e6cfa88-3416-11e7-9c8d-688fd82d741f.png)
Minecraft: 1.10.2
C&B: 12.12
Advanced Rocketry: 1.1.7

**Comment by zmaster587** [comment]
@Jummit preliminary support was added in build 95, it turned out to be really difficult compared to 1.7 due to changes in the rendering engine and it's a bit hacky.  The lighting on C&B may or may not be darker that it's supposed to some of the time and I've not yet been able to pinpoint why.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
