### ISSUE TITLE
Right Clicking Laser Drill with a laser drill crashes the game and the world for good. 

### ISSUE THREAD

**Issue by KaneHart** [zmaster587/AdvancedRocketry#249]
http://pastebin.com/F6XDVyFR

So we just testing things on our server in creative. My friend shift right clicked or maybe right clicked a laser drill block with another in his hand and boom it crashed his client and the server. The server crash loops at that point.

**Comment by zmaster587** [comment]
Will look into it, disabling the laser drill in the config should at least
recover the world

**Comment by KaneHart** [comment]
Thanks. It was a pure test server just screwing around testing random mods :) Gives me a chance to say hi to half the developers hehe :)

**Comment by zmaster587** [comment]
Hello then!
Should hopefully get this fixed fairly soon

**Comment by KaneHart** [comment]
Not a problem. Not in a rush :) Thanks for keeping us updated :)

**Comment by zmaster587** [comment]
Should be fixed now for the next release.
