### ISSUE TITLE
Oxygen system NOT working

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [zmaster587/AdvancedRocketry#250]
"**_Muhakl dies in an collapsing world_**"
AdvancedRocketry-1.10.2-0.9.1.jar ; LibVulpes-1.10.2-0.1.5-universal.jar

 happened on **MOON** ( luna) in **S U R V I V A L**   mode
in a **SEALED ROOM** ,  atmosphere detector emits redstone signal,

wearing a fully upgraded, fully loaded SPACE SUIT 
atmosphere analyzer shows:
     **_Atmosphere type : air
     Breathable : Yes_**

**Comment by TheGuyRunningSouth** [comment]
That's a rftools death message.

**Comment by zmaster587** [comment]
Advanced rocketry's death message is something like X suffocated in the
vacuum or death . damage.vacuum depending on the version in use

**Comment by zmaster587** [comment]
If you remove all mods except libvulpes and AR does this still occur?

**Comment by dmodoomsirius** [comment]
This issue is because RFtools thinks that the Space Dimension doesn't have power so that is why you have died.

**Comment by TheGuyRunningSouth** [comment]
But that check never should have occurred. I'd suggest reporting this to
McJty when you get the chance.

**Comment by dmodoomsirius** [comment]
I am creating a issue on the RFtools repo and linking this.

**Comment by McJty** [comment]
The only way that I see that this can happen is if this mod was added later while an rftools dimension was already created at that given ID. In that case it is not a bug in either mod but simply related to adding mods later. You can do /rftdim safedel <id> to let RFTools forget about this dimension and then regenerate the dimension by this mod if this is the case

**Comment by zmaster587** [comment]
Well, it could also be due to the fact that AR dimensions are dynamically generated and not actually created until postinit, or later if created during gameplay.

**Comment by McJty** [comment]
Same with RFTools but I do check in advance if the dimension is registered and I properly register it when I take a dimension ID. If you do that then there cannot be a clash

**Comment by zmaster587** [comment]
AR only checks and registers dimensions the first time the server is started, at that point the dimids for planets are set, DIMIDs checks are not performed on subsequent loads.

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
it could help that AD dimensions start with e.g. 2xxx , 
so there will be no confict with RFTOOLS dim ID's .
They also overlap if in region and Biomes 
http://imgur.com/a/o3T4A

**Comment by zmaster587** [comment]
I'm not sure what's wrong with this picture other than a structure spawned under two giant swamp trees that happened to be too close together.
I'm also not sure what AD is, but if you're referring to AR, there's a config option to set the DIMID offset, so if you change it to 2000 in the config it'll do exactly that

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
sorry for mistyping , Adv.Rocketry was ment
I did not find an entry for an offset, so please specify.
This should be a must for coexist with RFTOOLS Dimension.
regards

**Comment by zmaster587** [comment]
"I:minDimension"
also did you try the commands proposed by McJty?

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
I already set ;
  I:minDimension=2000 , restarted even my PC 
used a rocket to travel to a new planet
result: 
The dimension is 3 which was already an existing RFTOOLS dimension.
"collapsing world" 
I had to "power up" the dimension in RFTOOLS , travel back to the AR Planet,
and everthing was ok 

MY conclusion ; USE THE MOD ONLY ON NEW WORLDS , or set  I:minDimension=2000 (offset)
**B E F O R E  very first use**.
NO WAY to repair my world , power up every RFTOOLS Dimension before travel to new AR Planets

regards

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
i did following test
create a NEW WORLD (ARtest), in creative
set up a rocket , traveled to planet SOL-138 
result : 
in /saves/ARtest/advRocketry/ following was created
==================================
19.10.2016  03:59    <DIR>          .
19.10.2016  03:59    <DIR>          ..
19.10.2016  03:37    <DIR>          DIM-2
19.10.2016  03:48    <DIR>          DIM138
19.10.2016  03:37    <DIR>          DIM256
19.10.2016  03:59                 0 list.txt  this is for creating this by dir>list.txt
19.10.2016  03:59             1.541 temp.dat
=============================================
LibVulpes-1.10.2-0.1.5-universal.jar
AdvancedRocketry-1.10.2-0.9.1.jar
rftools-1.10-5.52.jar
rftoolsdim-1.10-4.41.jar
mcjtylib-1.10-2.1.4.jar
MC 1.10.2 ; 1.10.2-forge1.10.2-12.18.2.2105

 # Dimensions including and after this number are allowed to be made into 
planets [range: -127 ~ 127, default: 2]
    **I:minDimension=2000**

conlusion : the offset is useless, the conflict with RFTOOLS will occur

**_PLEASE TEST YOURSELF BEFORE RELEASING A NEW VERSION_** 

i will continue to play minecraft without your mod, using a backup made before AR

sorry for that
regards

**Comment by dmodoomsirius** [comment]
I see A no leveltemp.dat. B Please don't tell modders to test something exp when they are doing this for a fun.

for now i am locking this issue. Zmaster will unlock it when he has the time to work on this issue more.

**Comment by zmaster587** [comment]
Could you at the very least post a startup log file so I can see the order things are occuring.

**Comment by zmaster587** [comment]
@McJty Kinda I've been poking around RFToolsDimensions for about 30 minutes now and am having difficulty finding where the check to see if another dimension is registered is performed, would it be possible to send me a line number and file or at least the file to look in, so i can further diagnose this issue?

**Comment by zmaster587** [comment]
Did you create any dimlets though the RFToolsDimension mod or does this occur without touching anything from the mod?

**Comment by zmaster587** [comment]
I've finally got around to attempting it, I have found I am unable to replicate.
Using the following:
Forge 1.10.2-12.18.1.2094
LibVulpes-1.10.2-0.1.4-universal
AdvancedRocketry-1.10.2-0.9.1
mcjtylib-1.10-2.1.4
rftools-1.10-5.54
rftoolsdim-1.10-4.43

What I did:
after placing all mods into the mods folder, I create a new survival world with the default world type.
Upon joining the world, I built a rocket, flew to the moon, created a small air tight shelter, sealed the room with an O2 vent and 2 CO2 scrubbers, power it, flicked the switch on.
Player took  no damage, I have the game running as I am writing this.

See if it is still broken using the latest RF tools and RFdim.

Sidenote: If i intentionally kill myself with vacuum damage, the kill message is "You have been depressurized"

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
My test have the same results as yours, if you don't have an previously created RFTOOLS dimension.
you can do this just place an empty dimlet n the creator, create, this creates a random dimension, and an DIM ID. see results in /save/yournamedworld/rftooolsxxx (were xxx ias the DIM ID 

regards


all the problems will be solved if the overhead I:minDimension=xxx would
have an effect.
for further info please contact McJty , i'm just a stupid MCplayer
regards

**Comment by zmaster587** [comment]
Given the fact you reported the folder DIM138 existing, it obviously does have an effect, albeit clamped (I mentioned the reasons for this earlier).   If you had mentioned you had created a dimension from RF tools earlier that would have been helpful.

**Comment by zmaster587** [comment]
Can you do be a favor, and in the world you are havingf this bug
can you run the command "/rftdim list" and the command "/advancedRocketry planet list" and paste the printouts of each?

**Comment by zmaster587** [comment]
I've attempted it again with the follwing mods
Using the following:
Forge 1.10.2-12.18.1.2094
LibVulpes-1.10.2-0.1.4-universal
AdvancedRocketry-1.10.2-0.9.1
mcjtylib-1.10-2.1.4
rftools-1.10-5.54
rftoolsdim-1.10-4.43

What I did:
after placing all mods into the mods folder, erased the config folder, started the game, I create a new survival world with the default world type.
Note: this means AR's planet offset is the default value.

Upon joining the world, I created a dimension using the enscriber and dimension builder.
I then ran "/rftdim list", I got the follwing result:
Loaded: id-1, Nether
Loaded: id1:, The End
Loaded: id:0, Overworld
RfTools: id:25 (power 4000) (owner zmaster587)

I then ran "/advRocketry planet list":
Dimensions:
DIM256: Sol-256
DIM2: Luna
DIM3: Sol-3
Dim4: Sol-3: 0
....
DIM23: Sol-20: 2
DIM24: Sol-24

Observation: the RFTools dimension starts at 25, and is not overlapping AR dimensions at all.

after this, I built a rocket, flew to the moon, created a small air tight shelter, sealed the room with an O2 vent and 2 CO2 scrubbers, power them, flicked the switch on to activate them.
I took no damage.

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
thanks for your effort
if i do /rftdim list , i get dim 2 up to 9 already occupied by RFTOOLS dimensions, e.g 
_RFTOOLS: dim8, dim_shard (power 0) ( owner MUHAKL)_ for mining Dimensional shard's    
which i created to mine/get important resources. 

My personal conclusion ;
If an existing world has already existing RFTOOLS dimensions , DO NOT USE adv.rocketry, 
they will have overlapping DIM ID's

If you plan to start from SCRATCH ( new world ) , there will be NO PROBLEM ( as you have tested)

me and my 2 son's spent a lot of effort to create our little universe, so we will not give up 

for time being we play with our backup created BEFORE AR, 
and we wait eighter AR has an working offset
or galacticraft has been released for 1.10.x. 
Only then we will explore the outer space 

greeting from bavaria

**Comment by zmaster587** [comment]
Due to the way forge loads mods, short of hardcoding AR to load after RFToolsDimensions, there's not really much that can be done, I'll tell you what though, what you can do is use an NBT editor on the advRocketry/temp.dat file to change the dimIds of the planet.
Contrary to what you have said before, the offset does indeed work, as indicated by your own logs, the offset is not capable of going to 2000, for reasons I explained earlier.  One solution you can try is using an NBT editor to modify the advRocketry/temp.dat file, then change the numbers under dimList (do NOT change 0) to a dimid more agreeable with the world you are currently using.  https://gyazo.com/12530a8635c45a75141a714734d57a1c

Unfortunatly due to contrainsts with FML, it is impossible for me to garuntee that AR works with preexisting worlds with dimension altering mods, and is outside the scope of what I can do.

What I will do, however is increase the maximum range for the dimid offset for the next build if I can find a way to do so safely.  But that is really the limit of what I can do.

For future reference though, when you document things, please specify if something worked or if something didn't work, as the way you documented the second test led me to belive that even a new world does not behave as expected.  It would also be much easier to read your reports if you did not have the bizzare capitalization and bolding, in general, if somebody can write computer code, they can probably read standard English.  And to be honest, it comes off as rather insulting and unprofessional on your part.  I am not trying to put you down or anything, but there are a lot of mod authors out that that would not stand for the kind of formatting you currently employ or the lack of startup logs for issues such as this.  Just trying to give a helpful tip here.
