### ISSUE TITLE
Geodes crash game, and corrupt map

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#251]
http://paste.ee/p/vogBm
This i get in some planet.

http://paste.ee/p/SdewW
This i get if try to load world after pervious crash.

MC 1.7.10 ver. 0.9.0
I don`t think you can replicate it, because it happens randomly.

**Comment by zmaster587** [comment]
Does the second crash occur without voxel maps?
Will add a check for the first issue, only way that should be possible if the world has a very low bottom or a very high top, will investigate
