### ISSUE TITLE
Crash if open Gas tank at Unmanned vehicle.

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#252]
After "Gas collection" mission if you try to open unmanned vehicle with full tanks, and click tank, your game will crash.

**Comment by zmaster587** [comment]
Could you append the crash report please, makes fixing much faster/easier.  Can't run MC on mobile but I can still write code.

**Comment by DevTimur** [comment]
Wasn`t able to replicate bug. Probably one time crash...

**Comment by zmaster587** [comment]
Unless you deleted it, the crash report should be in the "crash-reports" folder somewhere.  The way inventories on rockets work is kinda jenky, because it's essentially trying to use blocks stored in a different world,  So it is possible there are some race conditions that exist.

**Comment by zmaster587** [comment]
Will close unless it comes up again i guess
