### ISSUE TITLE
Exiting the seat puts me in the void!

### ISSUE THREAD

**Issue by Luckie21** [zmaster587/AdvancedRocketry#258]
As the title says everytime i exit the seat i get thrown into the void! which is a pain in the butt because i play survival and lose everything.

**Comment by zmaster587** [comment]
Can you give me a step-bystep set of instructions on how to replicate this?  Is the seat on the rocket or being placed in the world?  Is there a particular block you are placing it on?

**Comment by Luckie21** [comment]
it is in a unbuilt rocket on top of a liquid fuel tank. lastest version of AR in 1.10.2 I place the seat then right click it. the rocket has not been built by the assembler yet. and then i push Lshift to dismount and i get thrown into the void!

**Comment by zmaster587** [comment]
I'm not able to replicate this.  My setup: http://imgur.com/KpSYXRV.png  Can you post a picture of the setup and a list of installed mods and forge version?

**Comment by Luckie21** [comment]
Zmaster copy this setup i just made is what i do every one of my rockets! im just installed the latest forge version which is 2111. and i have over 40 mods installed. so the list is pretty long.
Copy this setup throws me into the void everytime! http://imgur.com/a/LnQiz , http://imgur.com/MzLwv7A

The mods are:
Immersive Engineering
Mekanism
Ender IO
Ender Storage
Ender Core 
Advanced Rocketry
AutoPickup
Extreme Reactors
Brandon's Core
Draconic Evolution
CodeChickenCore
Calculator
cxlibrary
Extra Utilities 2
More Furnaces
Advanced Generators
Pressure Pipes
Flux Networks
Quantum FLux
ShetiphianCore
TheOneProbe
JEI
The stuff extension
ZeroCore
Sonar Core
Prefab
Nether Metals
Multistorage
Iron chest
Multipage chest
Mekanism Generators
Mekanism Tools
Malisis Core
Malisis Doors
Libvulpes
Heaven and Hell 
God's Weapons
Guide API
Floocraft
Bdlib

**Comment by zmaster587** [comment]
Alright, I can replicate with that setup.

**Comment by Luckie21** [comment]
Awesome

**Comment by Luckie21** [comment]
Also Zmaster i watch the videos on how to program a planet id chip and that didnt work because the planet analzer had a name change and now longer includes the planet selector can u explain to me how to program one?

**Comment by zmaster587** [comment]
So for some reason my email didn't make it to github, but anyway..
If you put a planet id chip into the rocket (before or after assembly, doesn't matter) then click the select destination/planet button, it'll open up a planet screen from which you can select the destination.

**Comment by Luckie21** [comment]
oh okay. and dont worry about it Zmaster! Github tweeted a couple days ago they were having problems with some stuff and idk if they still are but they might

**Comment by Luckie21** [comment]
If i find another issue ill report it here but if i have another question ill post it on curse.

**Comment by Luckie21** [comment]
So will the seat be fixed in the next release?

**Comment by zmaster587** [comment]
Yes, and the github tweet was due to a massive cyber attack that was resolved late friday if it's the same one i think you're referring to

**Comment by Luckie21** [comment]
maybe idk i dont pay much attention to what time the tweet was sent out!

**Comment by zmaster587** [comment]
You put it in the guidance computer of a constructed rocket and click
select planet/destination and that should bring up the same menu as the
planet selector
