### ISSUE TITLE
Pokecube Support

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#259]
I would like to add support in Pokecube for AdvancedRocketry.

I would like to know if the following is possible:

Allow specific blacklisting of certain entities from some atmposheric effects.  I would have various pokemobs spawn in space/planets/moons, some of them should be fine in vacuum, such as lunatone/solrock/deoxys, currently they all take damage from being in vacuum.

I would then on my end handle making sure things spawn in the correct spot, as it seems at least your moon biome is registered as "plains", which results in currently plains things trying to spawn on it, this I can fix on my end.

One way to go about the atmosphere thing would be to make a capability that can do the checks, when given an atmosphere, that capability can then be used to override the existing atmosphere behaviour.

**Comment by zmaster587** [comment]
I'll add a cancelable event

**Comment by zmaster587** [comment]
You should be able to make an event handler for the event zmaster587.advancedRocketry.api.event.AtmosphereTickEvent and then if getUnlocalizedName() from event.atmosphere.equal("vacuum") is true then if you cancel the event it should prevent damage from being taken by the entity.

**Comment by Thutmose** [comment]
ahh ok, thanks, I will get to that tomorrow.
