### ISSUE TITLE
Can't Copy ID cards

### ISSUE THREAD

**Issue by Towsty** [zmaster587/AdvancedRocketry#26]
Copying the ID cards in the satellite builder does not seem to be working. In version 0.3.1 I have tried it with both a Satellite ID card and a Space Station ID card. This makes getting to your space stations a tad bit tricky if you are not able to save/load your inv using NEI.

**Comment by zmaster587** [comment]
With the space station ID card: did you have the programmed one on the left and an unprogrammed station id card on the right?

Did find a bug with the satellite id chips, I had checked for the satellite itself instead of the chip in the left slot, so attempting to copy the chip will fail with that.  However for me both the planet and station id chip copy correctly.

**Comment by Towsty** [comment]
Ya, just double checked. 

Programmed on the Left:
![image](https://cloud.githubusercontent.com/assets/5897643/10864958/905b9a74-7fcb-11e5-8201-f7e048248005.png)

Blank on the Right:
![image](https://cloud.githubusercontent.com/assets/5897643/10864962/a844feb4-7fcb-11e5-855f-5cc3bd5c6947.png)

Then I click Write to secondary chip and it does not seem to copy

**Comment by zmaster587** [comment]
It the metadata on the station id chip 1?

**Comment by Towsty** [comment]
Yep, the one on the left has the meta. It got me to the space station no
problem. I tired the break and replace, no dice.

**Comment by zmaster587** [comment]
I think I got the issue fixed, was related to the fact that the coordinates you land at when leaving the station is stored on the ID chip as NBT and the satellite builder was refusing to duplicate anything without NBT (as a result of the original design).

**Comment by Towsty** [comment]
Nice! Looking forward to the next update

**Comment by zmaster587** [comment]
Should be out within 15 minutes
