### ISSUE TITLE
Crash when landing in a planet

### ISSUE THREAD

**Issue by jonabrv1965** [zmaster587/AdvancedRocketry#260]
After arriving to a planet and starting the landing, MC crash,  happens in any planet. See log attached,
[crash-2016-10-23_20.01.32-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/546960/crash-2016-10-23_20.01.32-server.txt)

**Comment by zmaster587** [comment]
Does this occur if you remove everything except AR and libvulpes?

**Comment by jonabrv1965** [comment]
Uhm... A little bit tricky, for example I've all my items in storage drawers, several automated machines (grinders smelters etc), a big transport system based in RFTools. The weird part is that I was able to visit two planets some days ago... I'm going to make a "mod debug" eliminating gradually the latest and non essentials... I'll keep you posted...

**Comment by zmaster587** [comment]
Can make a copy of the world folder, so you don't lose anything permanently

**Comment by jonabrv1965** [comment]
Yep, working with world backups :-). I manage to isolate 9 mods, now trying one by one... work in progress!!! :-) -:)  (I mean, without this 9 mods I can land ok)...

**Comment by jonabrv1965** [comment]
Gotcha! https://minecraft.curseforge.com/projects/jurassic-park-minecraft-genesis?gameCategorySlug=mc-mods&projectID=250575
Jurassic Park Minecraft Genesis... When this mod is removed the landing crash is no more...Why? gee.... why knows! should I report this to the JPME developer? (with what evidence?)

**Comment by zmaster587** [comment]
I'll look at it once I get to a computer so I can see exactly why it's
doing this and I'll report back

**Comment by zmaster587** [comment]
Alright, if you get it down to one or two I'll see if I can do fixes

**Comment by jonabrv1965** [comment]
Uhm.. I'm slower than normal :-), what do you mean with "if you get it down to one or two"?

**Comment by zmaster587** [comment]
I sent that email well before you reported that you narrowed it down to the one mod...  but I meant find one of two mods that seems to cause it and I'll look... out of order conversations lead to odd results..

**Comment by zmaster587** [comment]
What is the minimum set of mods installed when you can still make it crash?  Just LibVulpes, AR, and Jurassiccraft?
Also if you put it back in does it crash again?

**Comment by TheGuyRunningSouth** [comment]
ZMaster's emails to github glitched out the other day. He probably sent
that before you figured out which mod it was and github just now got it.

**Comment by zmaster587** [comment]
I meant of you narrow it down to one or two mods, which you already have it
seems

**Comment by jonabrv1965** [comment]
Hi all, thank you for your time!. Yes, I was able to isolate the culprit, see my last message up here.

**Comment by jonabrv1965** [comment]
https://minecraft.curseforge.com/projects/jurassic-park-minecraft-genesis?gameCategorySlug=mc-mods&projectID=250575
Jurassic Park Minecraft Genesis...

Just in case my messages does not get you... :-)

**Comment by zmaster587** [comment]
does it happen every time or just some of the time?  I've got LibVulpes, AR 0.9.1, forge 12.18.1.2094 and JPME  1.0.0 (latest build, because they're not numbered :/) in a pack, but I don't crash even if i go to multiple new worlds.  Is there anything in particular that you do?

**Comment by jonabrv1965** [comment]
I've forge-1.10.2-12.18.2.2107, LibVulpes-1.10.2-0.1.5-universal, AdvancedRocketry-1.10.2-0.9.1. 

It happened to me every time I load JPME.jar (without numbers). Also use OptiFine_1.10.2_HD_U_C3.jar (and installed the latest OptiFine_1.10.2_HD_U_D1, with same results : crash)

In the crash log you can find the mods loaded :-)

**Comment by zmaster587** [comment]
Hmm... I just got the same crash in the overworld

**Comment by zmaster587** [comment]
Nailed it down to the list of dinosaurs to spawn having a total weight of 0 from here.

`    public static <T extends WeightedRandom.Item> T getRandomItem(Random random, List<T> collection, int totalWeight)
    {
        if (totalWeight <= 0)
        {
            throw new IllegalArgumentException();
        }
        else
        {
            int i = random.nextInt(totalWeight);
            return getRandomItem(collection, i);
        }
    }`

**Comment by zmaster587** [comment]
Still working on it, but I've found the crash still occurs when JPME is loaded, so it is definitely not an AR interaction.  

Got this by loading a new world with only JPME installed.
[crash-2016-10-27_20.52.25-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/557371/crash-2016-10-27_20.52.25-server.txt)

**Comment by zmaster587** [comment]
I've left a comment on the mod page so hopefully it'll get fixed fairly soon.
https://minecraft.curseforge.com/projects/jurassic-park-minecraft-genesis?comment=14
