### ISSUE TITLE
Rocket spawn in spacestation at lvl 0 (video)

### ISSUE THREAD

**Issue by EnnekPL** [zmaster587/AdvancedRocketry#261]
Hi

AR 0.9.1 (on server)

Like you can see on video when rocket (with id spacestation 2 in copputer gui.) go in to space station without player then rocket spawn on position y=0. Dpcking port is empty (x and z rocket position is correct but y is 0) 
btw. first space station dimension (-2 id) was created with AR 0.8.1

  [Video](https://www.youtube.com/watch?v=jFY5l7N8d9Y)    (look at 26:00 min)

**Comment by zmaster587** [comment]
Does it persist through logging out and back in?

**Comment by zmaster587** [comment]
Also are you creating the space station or just sending a rocket to an existing one?

**Comment by Luckie21** [comment]
@zmaster587 i just replicated the problem ennekpl had. its not the rocket spawning in the space station. and he was sending it to an existing space station ill upload some pics of of my rocket! and i can only get this to happen with cargo rockets that r unmanned!

**Comment by zmaster587** [comment]
That previous commit should have fixed it.

**Comment by Luckie21** [comment]
oh ok

**Comment by Luckie21** [comment]
should i openan issue with the warp core and controller?

**Comment by Luckie21** [comment]
sorry im a bit excited atm.

**Comment by zmaster587** [comment]
You can, but at least what is posted on the forum is not enough info to go by.  I need to know what you did, what you expected to happen, and what went wrong.
