### ISSUE TITLE
Items in Water "Float" or desync location

### ISSUE THREAD

**Issue by rckymtnrfc** [zmaster587/AdvancedRocketry#264]
When items drop in water (killing squid, digging clay) they appear to float in the water and occasionally fly off in one direction but then moments later, appear back where they should actually be.  This happened repeatedly.  http://imgur.com/a/38HGE (animated gif of the effect)

I'm seeing this with only Forge, Advanced Rocketry and LibVulpes.  If I remove AR it goes away.  I searched the config for perhaps a setting that is causing it, but I don't see anything.  Not sure if this is a bug or intended behavior. 

Thank you

**Comment by zmaster587** [comment]
Is this in the overworld are an AR planet?

**Comment by rckymtnrfc** [comment]
Overworld.

**Comment by TheGuyRunningSouth** [comment]
That sounds like regular old desync to me. How much memory do you have
allocated to Minecraft?

**Comment by zmaster587** [comment]
AR doesn't do anything to items in the overworld.  I could see it happening on planets due to gravity being applied but... 
I have seen this in forge with no mods installed on servers under load so, it could be just that.  But I'll verify that it doesn't break anything on other planets anyway.

**Comment by rckymtnrfc** [comment]
Well, I first noticed it on my server and thought that it was simply a desync issue but I thought I'd try and see if that was the case or caused by a mod.

I created a duplicate of my instance and removed everything, then started adding mods 1 at a time and killing a few squid until I saw the problem again.  This happened after adding AR.

I then removed all mods except AR and LibVulpes and saw the same issue.  Just to test, I removed AR but left LibVulpes, and it went away.

All of these test were performed in a single player world to rule out server lag.  I have 4gbs of RAM allocated to MC on my PC, FYI.

**Comment by zmaster587** [comment]
I'll investigate

**Comment by zmaster587** [comment]
The code to apply gravity is not being called, which is expected,  but i have verified a difference in behavior between AR/libvulpes in the dev environment and vanilla + forge in the wild, so something is going in.  Investigating further...

**Comment by zmaster587** [comment]
Turns out items had no gravity applied while in water, which there should be.
