### ISSUE TITLE
World wont load after i used some multi-page chests!!

### ISSUE THREAD

**Issue by Luckie21** [zmaster587/AdvancedRocketry#265]
Ok  i decided to try the multi-page chest on a asteroid mining mission and everything was going great until it started to descend back to the overworld. IT then said the was a fatal error and it shutdown a mythical multiplayer server because i play single player. I tried reloading the world but it then said disconnected from server connection and bring back to the multiplayer screen.

**Comment by Luckie21** [comment]
Zmaster i was trying to replicate ennekpl problem with the rocket and ran into another issue! when i launched a space station in this new test world i created to test some of these bugs. the rocket released the space station around it. and when i visit the space station the rocket is sitting in dead middle of it!

**Comment by zmaster587** [comment]
As github apparently didn't get the email...  "What is a multipage chest and would it be possible to paste the fml-server/client-latest.log files?".

with regard to the space station issue, did you have anything on the rocket besides the satellite bay with the space station inside?

Also there really is no need to add another '!' to the end of the title, I can see it perfectly fine with just the one '!', but I am very busy throughout the day and can only check back so often.

**Comment by Luckie21** [comment]
I added the extra "!" by accident. really sorry about that. and i understand that ur busy and didnt mean anything by that extra exclamation point.

Now on with the issues. is like a chest but but u can scroll through different pages. visit this link for more info! https://minecraft.curseforge.com/projects/multi-page-chest?gameCategorySlug=mc-mods&projectID=78779

Now about the space station i had the satellit ebay and a guidance cpu

**Comment by zmaster587** [comment]
It's all good.
but anyway, would it be possible to upload the log from when you got the fatal error?

Ok, so the email's not going through again, but anyway.  Did you have anything in the guidance computer or was it empty?

**Comment by Luckie21** [comment]
Yes there was a space station id chip in it! i cant upload the latest log because i went to a backup

**Comment by zmaster587** [comment]
alright, investigating

**Comment by Luckie21** [comment]
wait i just duplicated the fatal error again. ill post that log file in a second

**Comment by Luckie21** [comment]
the log file is so big it it exceeded the 512 kb limit on pastebin

**Comment by zmaster587** [comment]
try uploading it to git

**Comment by Luckie21** [comment]
Ok i had to Zip the folder but it should hopefully be it!
[fml-client-latest.zip](https://github.com/zmaster587/AdvancedRocketry/files/554857/fml-client-latest.zip)

**Comment by zmaster587** [comment]
It appears to be being caused by something trying to send too large a packet.

**Comment by Luckie21** [comment]
Could it be the ores that the mining mission is bringing back?

**Comment by zmaster587** [comment]
It shouldn't be, there's an upper limit of a few chests, so the remainder should be empty

**Comment by zmaster587** [comment]
Would you be able to upload the region file the rocket took off from?  Here's a coord to file converter if you need it: https://dinnerbone.com/minecraft/tools/coordinates/

**Comment by Luckie21** [comment]
Where are the region files located? and for which rocket? the one that did the asteroid or the one stuck in the spaces station?

**Comment by zmaster587** [comment]
saves/<save file name>/region/something.mca
And the one for the asteriod mining rocket, I'm fairly sure i know what happened with the space station rocket.

**Comment by Luckie21** [comment]
Never minnd about the region files.

**Comment by Luckie21** [comment]
ok

**Comment by Luckie21** [comment]
i got it where do i upload it to?

**Comment by Luckie21** [comment]
or do i just give u the region info

**Comment by zmaster587** [comment]
you should be able to upload here in a zip , or you could upload to dropbox or google drive

**Comment by Luckie21** [comment]
oh ok and removing extra ultilties didnt work.

**Comment by Luckie21** [comment]
sorry have to step away from the cpu for a min my gf / soon to be fiance is calling!

**Comment by zmaster587** [comment]
huh, that one's only got 7 chunks generated and none of them have any entities, you sure you got the region the rocket was launched from?

can you also send the /advrocketry/temp.dat on the offchance it's not returned from it's mission before the world saves or something?

**Comment by Luckie21** [comment]
might have loaded wrong file and if u mean the original spawn point of the game yes i moved headquarters to a base in the desert and the nearest one i could find was nearly twen thousand blocks away!

**Comment by Luckie21** [comment]
Yep uploaded wrong this one should be it!

**Comment by zmaster587** [comment]
Guess you beat me to it, was gonna ask if you were off by one or something

**Comment by Luckie21** [comment]
i type in my location into the chunk one instead of the block one!

**Comment by zmaster587** [comment]
You sure that's right?  That one has a single unpopulated chunk in it.  A region file with any kind of base should be at least 100KB.

**Comment by Luckie21** [comment]
Ill just duplicate the dang error again so i exactly which region file to go it! brb in about 5 or so mins

**Comment by Luckie21** [comment]
or wait would one with 4k KB be it?

**Comment by Luckie21** [comment]
[r.-19.11.zip](https://github.com/zmaster587/AdvancedRocketry/files/555165/r.-19.11.zip)
[r.-19.11.zip](https://github.com/zmaster587/AdvancedRocketry/files/555166/r.-19.11.zip)
[r.-19.11.zip](https://github.com/zmaster587/AdvancedRocketry/files/555172/r.-19.11.zip)
[r.-19.11.zip](https://github.com/zmaster587/AdvancedRocketry/files/555173/r.-19.11.zip)


[r.-19.11.zip](https://github.com/zmaster587/AdvancedRocketry/files/555169/r.-19.11.zip)

**Comment by zmaster587** [comment]
No rush, I need to sleep anyway as its 3am here

**Comment by zmaster587** [comment]
Did you have anything in the guidance computer or was it empty?

**Comment by zmaster587** [comment]
What is a multi page chest and would it be possible to paste the
fml-server/client-latest.log files?

**Comment by zmaster587** [comment]
Alright, so all the emails arrived at once... interesting... Looking through the region files...

**Comment by zmaster587** [comment]
I set a test to run in the background, fully filled asteriod chip, 4 drills, guidance computer, 1 multipage chest, the results I got was it brought back way more ore than it should, but the game didn't crash... still looking through the region files though...

**Comment by zmaster587** [comment]
Wait, so are you able to get back into the world after the crash occurs?

**Comment by zmaster587** [comment]
if you change miningMissionMultiplier to 0 and launch a new mission does this bug still occur?  (also for the sake of testing I'd suggest making a copy of a full asteriod chip in creative until we can sort this out)

**Comment by zmaster587** [comment]
My current theory of what happened is that due to the limit for the amount of ore generated by an asteroid mining mission was way too high, coupling that with the assumption you had a larger rocket/more chests? than the one i was testing with the amount of ore generated + the rocket was over 1MB in size.  I've since fixed the limit to be something much more reasonable (100 stacks of ore max), but I'd like to you test the theory by changing the conig such that 0 stacks are generated which would either confirm or rule said theory out.

**Comment by Luckie21** [comment]
Ok many things here!

First im not able to get into the world that crashed it loads normal but as soon its done it flashes and like it wants to be played but the shuts down!

Second how do u duplicate a full asteroid chip?

third ill wont be able to test ur theory until later tonight as im currently driving my gf to the airport. She had a family emergency back in england. 

finally love ur thinking on the space station bug!

**Comment by Luckie21** [comment]
ok git hub would let me edit the last comment i posted so ill type it here. 

The rocket that caused this whole mess was decent size with a lot of thrust. it also had about 50-60 chest on it. 
1/3 multi page 
1/3 vanilla chests
1/3 crystal chests from iron chests

**Comment by zmaster587** [comment]
That makes sense. You can duplicate the chip by going into creative and middle clicking it in the inventory, like any  other item or block.

**Comment by Luckie21** [comment]
oh ok!

**Comment by Luckie21** [comment]
Setting the multiplier to 0 brought back nothing!

**Comment by Luckie21** [comment]
and didnt crash with 25 chests moving up to 50 chest now!

**Comment by Luckie21** [comment]
No crash with over 100 chests i got carried away

**Comment by zmaster587** [comment]
"Setting the multiplier to 0 brought back nothing!" that was the point, I was trying to rule out the number of items being the cause.

"and didnt crash with 25 chests moving up to 50 chest now!" this with the multiplier still at 0?

**Comment by Luckie21** [comment]
yup

**Comment by zmaster587** [comment]
what happens if you do the same with it set to 0.01?

**Comment by Luckie21** [comment]
Ok ill try that real quick

**Comment by Luckie21** [comment]
do u have to reload minecraft or just the world if i change the configs?

**Comment by zmaster587** [comment]
You'd have to relaunch the game.

**Comment by Luckie21** [comment]
ok it brought back ores

**Comment by zmaster587** [comment]
so i didn't crash?

**Comment by Luckie21** [comment]
nope!

**Comment by zmaster587** [comment]
alright, then the fix I committer earlier will solve this for next release, thank you very much for your patience with this issue!

**Comment by Luckie21** [comment]
no problem one question.

**Comment by Luckie21** [comment]
when i link the rocket unloader it says that the linker is now set to the fueling station.

**Comment by zmaster587** [comment]
I forgot to update the strings

**Comment by Luckie21** [comment]
ok
