### ISSUE TITLE
Issue with warp drive

### ISSUE THREAD

**Issue by Luckie21** [zmaster587/AdvancedRocketry#266]
First i went to the space station and built the warp core and then threw 5 stacks of dilithium crystals into it. Then i went back to earth and built the warp controller. then went back to the station with the warp core

Second. hit warp before i selected a destination on accident . I didnt expect it would do anything . but the stars started flying by.

Then i tried selecting a destination. I click on the gas giant i want to go to and then nothing happened and after 10 mins of watching the stars fly by i tried again. But still the same thing. i tried breaking the warp core and controller both one at a time and same time. But still the stars just keep flying by my windows. with now gas giant appearing. I even built a brand new warp core and controller and nothing worked. hope this is enough info and sorry if im irritating you with all these post i have been making its always my luck that things dont work for me!

**Comment by zmaster587** [comment]
I've run into that issue when testing before, but I've always had a hard time replicating it on demand, investigating...

**Comment by Luckie21** [comment]
I can help try replicating it too.

**Comment by zmaster587** [comment]
I think I got a fix for it anyway, not 100% sure why it happens, but somehow nextStationTransitionTick gets set to -1 even though there's a station waiting for transit, also found a memory leak in the process, the space station manager did not clean up when logging out, this would lead to logging in and out having some odd effects

**Comment by Luckie21** [comment]
thanks
