### ISSUE TITLE
[Suggestion] configurable ore generations and gas/liquid mining

### ISSUE THREAD

**Issue by EnnekPL** [zmaster587/AdvancedRocketry#268]
is there any chance to add ore generations (if possible mods ore) to planets or moon (by config or xml file) and also configurable gas/liquid mining (possible to mine liquids from other mods).

f.e. like i saw in Your last commits
+<galaxy>
 +<star name="Sol" temp="100" x="0" y="0" numPlanets="1">
      <planet name="Earth">
          <ore gen>ore name or (mod name) and other ore steups  </ore gen>
             
          <planet name="Luna">
 
      <planet name="Mars">
      ...
      </planet>
 +</star>
 +</galaxy>

Why this sugestion is good?
That's give us posibility to make modpacks, maps more challenging f.e. I need go to "Planet X"/"Gas Gigant" to get ore/gas/liquid that make progress. :) and more options to transport by rocket all mining ore :)

btw. Flag with small text area will be nice :)

**Comment by wormzjl** [comment]
You can use custom ore generation mod to deal with such stuff

**Comment by zmaster587** [comment]
Although if he wants to do it by planet or planet type (only low pressure planets have double gold etc) it may be a bit harder to do especially given the random nature of planet generation.

**Comment by EnnekPL** [comment]
What if you give us option in config that we can if we want to override ore generation on your dimensions (planets/moons) or use your method ( list of blocks to spawn as ores) that's some solution. For random planets option can be always false.
It's boring when I see all ores at all planet (there is no reason to fly there without to see how looks like).

That's will be nice to see (f.e.) GT 5 ores customized (by the player) on all galaxy/ star sytem. that's make AR a fully used (transport, mining, discover)

I'm huge fan of your mod!

**Comment by zmaster587** [comment]
So far got ore definitions by planet type programmed in, I plan on doing individual planet ore specification tomorrow as well as implement #269 as well as a way to add non AR dimensions as planets (Twilight forest as a moon around Neptune?)
I have some WIP documentation here:
http://65.78.115.159:8000/AdvancedRocketryNew/concepts/OreConfiguration.php feedback on how easy that is to read would be appreciated.

**Comment by EnnekPL** [comment]
"pressure" and "temp" attributes define ore generation on planets... that's very good concept!, TF as Neptune moon? brilliant! and for me it's easy to understand your concept

**Comment by zmaster587** [comment]
Will add more types of gas giants in the first content update after 1.0.0
