### ISSUE TITLE
Ore Textures (MFR Laser Drill)

### ISSUE THREAD

**Issue by Towsty** [zmaster587/AdvancedRocketry#27]
Not sure if this is a bug per se. If you set up the laser mining drills from MFR the collect (the regular advanced rocketry ores) a steel, titanium, and silicon ore all of which are untextured.

![image](https://cloud.githubusercontent.com/assets/5897643/10865001/7573c190-7fcc-11e5-9190-c46636f88da8.png)

![image](https://cloud.githubusercontent.com/assets/5897643/10865005/7c20b1ba-7fcc-11e5-878c-a174ded77c41.png)

![image](https://cloud.githubusercontent.com/assets/5897643/10865006/80e0e260-7fcc-11e5-8f5c-08d5d9e13410.png)

I'm guess those should not be attainable and are used more for behind the scenes kind of work?

**Comment by zmaster587** [comment]
It's more an artifact of the resource system I created for AV that allows me to add ores just by listing names and a few properties.  I think it's doing this because I added the unobtainable block to the ore dictionary by mistake.  Good catch!

**Comment by zmaster587** [comment]
Does this occur with the most recent builds?

**Comment by Towsty** [comment]
Testing

**Comment by Towsty** [comment]
Doesnt look like it, drills have been runnin for about 15 minutes
