### ISSUE TITLE
Air sealing algorithm needs improvement.

### ISSUE THREAD

**Issue by vxcvbzn** [zmaster587/AdvancedRocketry#272]
AR 0.9.1
I'm building a moon base on Creative.
It's almost done so i sealed it with oxygen.

Some places have no oxygen:
-corridor in front of O2 vent (rest of room has air)
-one empty block in ae room
-2x2x1 passage between two rooms
-IC2 cables

I've checked 3 times and i found no holes.

Also that passage glitches seal completly:
When i block it with blocks both rooms are sealed with air.
When i place airlock door in it both rooms are sealed until i open it.

This is very annoying and it happens for other people too (in one of @EnnekPL's yt videos he cannot seal his space station due to same bug).

I suggest new/improved algorithm and/or command to recalculate it.

I need this fixed ASAP.
Thanks for attention!

**Comment by zmaster587** [comment]
What do you have the config set to under the performance category in the
config file?  Does this occur for all of them or just some of them?  And is
this the 1.10.2 version or the 1.7.10 version of the mod?

**Comment by zmaster587** [comment]
Also would it be possible to take screenshots of the unsealed areas (other
than the ic2 cables)?

**Comment by EnnekPL** [comment]
all in [Video](https://youtu.be/_btH-ncZekk)

**Comment by zmaster587** [comment]
What atmosphereCalculationMethod do you have set in the config?

**Comment by zmaster587** [comment]
Will see what i can do about it tomorrow, not sure if I'll be able to fix the IC2 cable issue or not, but everything else should be fixable

**Comment by EnnekPL** [comment]
All my config [here](http://pastebin.com/CzZv07Y5)

**Comment by zmaster587** [comment]
If you change the calculation method to 3 does it still occur?

**Comment by zmaster587** [comment]
is the vent on the north, south east or west wall of the building?

**Comment by zmaster587** [comment]
So I think the off-by one issue plus the IC2 cable issue explains everything in the video, I made a mockup on my dev server to test it and am fairly confident the off-by-one error caused the issue next to the wall and electrolyser.  The IC2 cable issue is probably the same as #135  I'll try to tackle that now too.
