### ISSUE TITLE
Interference with canInteractWith(EntityPlayer player)

### ISSUE THREAD

**Issue by Malorolam** [zmaster587/AdvancedRocketry#273]
Something in the code is preventing net.minecraft.inventory.Container.canInteractWith(EntityPlayer playerIn) from being called.

**Comment by zmaster587** [comment]
It's supposed to be ignored for rockets, otherwise minecraft forcably shuts the container due to distance (rockets are actually their own 'world' so nearly all blocks on it are near 0,0), however it's not supposed to ignore inventories in the world as it appears to be doing in the 1.10.2 build.
