### ISSUE TITLE
1.10.2 Linker/Rocket launching

### ISSUE THREAD

**Issue by YOYOK9** [zmaster587/AdvancedRocketry#274]
Issue description: The Linker for advanced rocketry is not linking the rocket to the Rocket monitoring station So I am not able to Launch anything.

What happens: Its says this when trying to link to the rocket "Nothing to be linked"

What you expected to happen: It will say "Link successful"
Steps to reproduce:
1.Get a linker and Shift-Right click on the Rocket monitoring station (after you build your launch pad)
2.Then Right click the Built rocket

Extra Information:
Seems that the Linker is not linking with other blocks as well. ex; the fueling station. The rocket will scan and build just fine. Just nothing seems to want to link. Also on a side note have noticed when we click "Disasemble" rocket the rocket dissaperes visually but the blocks are still there. Not sure if this is due to having optifine in or if there is an error somewhere (Do not crash) 

- Minecraft: 1.10.2
- Forge: 2092
- Advanced rocketry/versions 1

Does this issue occur on the server? yes
Pictures: [Using puush]
http://puu.sh/s70MY/113cad2d5a.jpg
http://puu.sh/s71dG/a76cb0c8a1.jpg

**Comment by zmaster587** [comment]
Are you shift right clicking on the rocket and the infrastructure blocks or just right clicking?

**Comment by zmaster587** [comment]
I've just tried to replicate this on a server running on localhost.
What I have done:
1. Build a new rocket and rocket launch pad, placed down a Rocket Monitoring Station.
2. Shift right click the Rocket Monitoring Station with a new linker
3. right clicked on the rocket with the linker
Result: Linked Sucessfully.

The only thing i could do to replicate this was shift right click on a block that was not a structure before right clicking the rocket.  However shift rightclicking on a non Infrastructure block clears the linker by design.

**Comment by jameshforster** [comment]
I can confirm I can duplicate this bug. Running on a server using forge 2125 (and SpongeForge 2123 in case it is relevant) with version 1.0.1 of the mod. Rockets work when manned but no linking works.  It is part of a modpack and I can provide a full list of mods (as well as the server IP if necessary). While I can have it on what other information would you want me to gather?

**Comment by zmaster587** [comment]
If you run it on regular forge does this issue also occur or is it only with spongeforge?

**Comment by zmaster587** [comment]
Just got around to testing it myself, Linker does not work with spongeforge installed, it claims to have copied the coordinates but the coordinates do not actually appear to be stored as NBT on the linker, however it does work as expected without spongeforge.  Investigating further...

**Comment by zmaster587** [comment]
Found a solution, looks like spongeforge reverts NBT modification if the "onItemUse" returns anything other than SUCESS
