### ISSUE TITLE
Pokecube Compatibility Questions.

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#276]
I am planning on making it so that if the player is flying on a Mega Rayquaza, it will act like a rocket and be able to take the player to/from space.

So far I have got it partially working.

I have the following question:

How can I find the appropriate dimension to transfer to/from for a planet? currently I am testing with sending to Configuration.spaceDimId when above 300 (testing at 300 for easier testing) and to 0 when below 0, but I assume there is a way to find the appropriate dimension instead?

edit: removed unneeded question.

Edit 2: I figured I would add some screenshots of the compatiblity:

Magnezone powering a rolling machine:
![image](https://cloud.githubusercontent.com/assets/2363472/20045165/3e277122-a475-11e6-82a7-4a6330645c8d.png)

the block he is sitting on is my block for getting energy from nearby electric types, I should probably get a new model for it made at some point...

Rayquaza to the moon:
![image](https://cdn.discordapp.com/attachments/232644586638540811/244969462371975168/unknown.png)

Rayquaza back to earth:
![image](https://cdn.discordapp.com/attachments/232644586638540811/244970230789439488/unknown.png)

**Comment by zmaster587** [comment]
I'm not really sure what you're asking.  Are you asking how to find what planets are moons of other planets?

**Comment by Thutmose** [comment]
that might work, but I am not sure how far I should allow the player to go.

What I was mainly asking was how can I find the dimension space stations and sattelites would be in for a planet or moon.

The idea is based on in ORAS how you can fly Mega Rayquaza to near orbit, so I figured that I would allow flying it to orbit, but wasn't sure whether I want to allow it to also go farther than that, but it would be an interesting things to do, to be able to fly on one to get to say a space station nearby, then maybe have a ship there to take you elsewhere.

If there isn't such a dimension, then I guess I would have them able to go to a moon of the planet instead.

**Comment by Thutmose** [comment]
I guess another way to ask this would be this:

How should I determine which dimension to transfer a player to if they fly up above the orbital transition height, and how to determine which dimension to transfer them to if they get below 0, given that they can be in any arbitrary dimension.

**Comment by zmaster587** [comment]
It's a bit harder to determine what dimension to go to once above a certain height as some planets have multiple moons, hence the planet ID chips.  However if you're on a space station and go below 0, you can get the planet it's in orbit around using AdvancedRocketryAPI.spaceObjectManager.getSpaceStationFromBlockCoords()
do a null check on the returned ISpaceObject then call ISpaceObject.getOrbitingPlanetId() to get the id of the planet it's in orbit around.
It's important to check the dimid against DimensionManager.getInstance().canTravelTo(id) because if you try to travel to a gas giant the game will crash as gas giants don't actually have a dimension registered to them.

As for where to get if above a certain height, if the planet is a moon then DimensionMaanger.getInstance().getDimensionProperties(currentDimId).isMoon() will return true and 
DimensionMaanger.getInstance().getDimensionProperties(currentDimId).getParentPlanet() will return the dimid of the planet it's orbiting.  

If you're on the planet that orbits a star directly and has moons, you're gonna need to do some logic to find out which moon to go to.

DimensionMaanger.getInstance().getDimensionProperties(currentDimId).getChildPlanets() will return a Set containing the DimId of all it's moons.

**Comment by Thutmose** [comment]
ok, thanks, that will help quite a lot with figuring out where to go.  I will try to figure something out for which moon to send to in case of multiples.

**Comment by Thutmose** [comment]
for now I will be lazy and just take current time of day, and divide it by number of moons and send to one based on that.

When I feel like doing maths, I will instead use the 
    public double                        orbitTheta;
    public double                        prevOrbitalTheta;
    public double                        orbitalPhi;
    public double                        rotationalPhi;
to figure out where to send them to, will send to whichever moon is in appropriate location for that, will probably not bother to deal with correct phase for optimal transfer orbits, and will just do whichever is closest to straight up.

Do those values get updated each tick? I would assume they do?

**Comment by zmaster587** [comment]
Sorry I've taken so long to respond things got away from me a bit.  orbitTheta and prevOrbitTheta are updated every tick and are used to calculate the planet/moon's angluar location in it's orbit.  prevOrbitTheta is only used client side to interpolate frame renders between ticks.

rotationalPhi is how far off the planet's axis is (90 results in the sun rising/setting on the north/south, 0 is normal, 180 is rising in the west/setting in the east) and is only updated via a command or on first world load.  

orbitalPhi is how far off the the plane of the solar system the planet is, also only updated via command or first world load.

**Comment by Thutmose** [comment]
ahh ok, so for direction planet is "facing" I would need to take world.currentWorldTime()/DimensionProperties.rotationalPeriod and then check the orbitTheta of the various moons to see which is appropriate?

**Comment by zmaster587** [comment]
You'd probably want to do world.currentWorldTime() % DimensionProperties.rotationalPeriod and check the orbitTheta.  I suppose you'd want whichever planet is closest to azimuth?

**Comment by Thutmose** [comment]
ya, so far I have done this:

```Java
double angle = (event.getEntity().worldObj.getWorldTime() / (double) props.rotationalPeriod)
        * 2 * Math.PI;
double diff = 2 * Math.PI;
int whichMoon = 0;
for (int i = 0; i < moons.size(); i++)
{
    DimensionProperties moonProps = DimensionManager.getInstance()
            .getDimensionProperties(moons.get(i));
    double moonTheta = moonProps.orbitTheta % (2 * Math.PI);
    if (diff > Math.abs(moonTheta - angle))
    {
        diff = Math.abs(moonTheta - angle);
        whichMoon = i;
    }
}
dim = moons.get(whichMoon);
```

I take the relative time of day, convert it to an angle, then look to see which moon's orbitTheta is closest to that angle.

it does seem that I do need to also do the %props.rotationalPeriod as you suggested, I will make that change.
