### ISSUE TITLE
[Suggestion] Make the armour interfaces support capabilities

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#278]
It would be easier to add in support for other mods which add types of armour which would work for breathing/spacesuit/etc if you also supported having the interfaces added via a capability.

Where you do this:
https://github.com/zmaster587/AdvancedRocketry/blob/MC1_10/src/main/java/zmaster587/advancedRocketry/atmosphere/AtmosphereVacuum.java#L54-L60
you could also add a check for if the item has the appropriate capability, then use the capability for the IFillableArmor instead of the item itself.  This will allow adding support for other mod items by simply adding the capability to the item itself.

Here is an example of where I use capabilities for something similar:

 The Interface in question:
https://github.com/Thutmose/Thut/blob/1.9/Misc/ThutWearables/src/main/java/thut/wearables/IActiveWearable.java

Registering a default application of the capability:
https://github.com/Thutmose/Thut/blob/1.9/Misc/ThutWearables/src/main/java/thut/wearables/ThutWearables.java#L110-L150

An item that directly uses the interface (uses the super for the interface, but IWearable is the main needed thing in my case, could be IActiveWearable instead):
https://github.com/Thutmose/Thut/blob/1.9/Misc/ThutBling/src/main/java/thut/bling/ItemBling.java

A support class to make other mod items use the capability:
https://github.com/Thutmose/Pokecube/blob/1.9/Pokecube%20Addons/src/main/java/pokecube/compat/wearables/WearableCompat.java

And where the capability or item itself is checked for use:
https://github.com/Thutmose/Thut/blob/48221b1be029329308cca51d533a0feae79504f3/Misc/ThutWearables/src/main/java/thut/wearables/EnumWearable.java#L43-L46

I should probably mention why this would be relevant to me:

I have a feeling that at some point pokecube, or one of the addons for pokecube, will be adding in aqua/magma armour, which canonically can be used as space suits, and I would like to be able to make them actually viable space suits when used with this mod, and this would be the most convenient way to do so, as if it is added by an addon, I might not be able to add the interface to the items themselves and use @Optional notation to make it not a hard dependency.

**Comment by zmaster587** [comment]
Added the Capability zmaster587.advancedRocketry.api.capability.PROTECTIVEARMOR
The Capability uses the IProtectiveArmor interface where the method protectsFromSubstance(IAtmosphere atmosphere, ItemStack stack, boolean commitProtection); returns true if the atmosphere is to have no effect on the player.

**Comment by Thutmose** [comment]
Thanks, when those armours get added, I will definitely see about getting them supporting this :D
