### ISSUE TITLE
[1.7.10] [1.0.0 RC1] Beds still explode on other planets

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [zmaster587/AdvancedRocketry#279]
I tried using a bed on another planet and it exploded. The planet has 66% gravity, 110 atmosphere and is Earthlike.
Note: This only applies to MODDED BEDS such as the ones from XtraBlocks.

**Comment by zmaster587** [comment]
There's not much I can do about modded beds unfortunately.  To make vanilla beds work I need to detect when a player places a bed and swap the blocks out with and AR bed and switch it back when the player breaks.

The reason this is an issue is for me to be able to check to make sure a player can spawn on a planet and fail over if there's a lack of O2 AR worlds need to return false on canPlayerRespawn().  With vanilla beds if that function returns true and the dimId is not the Overworld then it makes the bed explode.

Making it work with modded beds would require doing a similar process with all modded beds as well.
This is something I may tackle in the future (as it would also require me replicating visuals for other beds, or making it a TE).

**Comment by TheGuyRunningSouth** [comment]
Hypothetically speaking, could you just make your own bed and warn the user
that other beds will likely explode (a la Galacticraft)?

**Comment by AGiLE-EaGLE1994** [comment]
I only play  single player.
The reason I wanted to use the Xtra Blocks beds instead of vanilla ones was so I could have a bed with a different texture WITHOUT using a texture pack.
So I had to use the texture on the vanilla bed instead.
While I'm at it, how do I create a warp ship?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
Quark's colored beds no longer have this problem in the way of exploding, but Vanilla's colored beds will be automatically set to Advanced Rocketry's astrobed block, which is always red.
