### ISSUE TITLE
Tin Plate/RF Plug

### ISSUE THREAD

**Issue by Towsty** [zmaster587/AdvancedRocketry#28]
Unless I missed something, none of the machines are craftable without another mod that adds ore dictionaried plates. The Rolling Machine like all other machines required RF plugs which are made with the small batteries which are made with the Tin Plates. But the small plate presser does not work on tin. Seems to be a bit of an issue in the progression here.

**Comment by zmaster587** [comment]
This is an oversight on my part, going to add a block so it can be processed in the small plate presser.  Scheduled for 0.3.2.
