### ISSUE TITLE
update space station dim from 0.9.1 to 1.0.0

### ISSUE THREAD

**Issue by EnnekPL** [zmaster587/AdvancedRocketry#280]
mc 1.7.10
After updated AR from 0.9.1 to 1.0.0 I got crash server side ()
[crash](http://pastebin.com/NjkcgmVa)

when I removed oxygen vent, all works fine and when I builded orbital laser (added last multiblock block laser drill) on space station server crashed ) 
[crash](http://pastebin.com/qPcpgx2A)

**Comment by zmaster587** [comment]
Should be fixed next build
