### ISSUE TITLE
Space Station Asteroids Mining mutiplayer error

### ISSUE THREAD

**Issue by Swifter945** [zmaster587/AdvancedRocketry#282]
When I launched a drill rocket from the space station on my server the game kicked me out of a game and said: "Internal server error" or "Fatal error has ocured"

**Comment by zmaster587** [comment]
Would it be possible to send me a copy of the fml-server-latest.log file
from the event as well as the fml-client-latest.log from a client that was
kicked?

**Comment by zmaster587** [comment]
Massive changes to the function of mining missions I think would make any error such as this from so long ago irrelevent
