### ISSUE TITLE
[Question] how to setup in confing gas mining fluids?

### ISSUE THREAD

**Issue by EnnekPL** [zmaster587/AdvancedRocketry#285]
how to setup in confing  fluid names that can be harvested as Gas. (I know that I must use f.e. minecraft:water but i dont know where) there is no list space like f.e.
 S: <
     minecraft:water
     >

**Comment by zmaster587** [comment]
there was a bug with 1.0.0RC2 where there was a name conflict in the config.  Should show up as "harvestableGasses" under "gasmining" in the next update.  Fluids are also not locallized by mod so the correct entry I believe would actually be just 
S: < 
water 
>

**Comment by EnnekPL** [comment]
ok thanks :)
