### ISSUE TITLE
Idea: Saturn-like gas giants? Other planet types?

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [zmaster587/AdvancedRocketry#286]
I'd love to see gas giants that looked like Saturn, pale yellow with rings, and you could choose to generate terrestrial planets with rings as well.
Also, I'd like to see other planet types, such as habitable desert planets (The whole planet is one vanilla desert biome), jungle planets, Venus-like planets, And possibly also plains, savannah and taiga planets as well. Basically a planet type for each main biome, 
so these biomes would be made into planet types:
Desert
Plains
Roofed Forest
Taiga
Ice Plains
Extreme Hills 
Ocean
Mesa 
Jungle
Mushroom
And also Venus- and Saturn-like planets. I'm hoping to recreate the entire Solar System in this mod instead of Galacticraft.

**Comment by zmaster587** [comment]
I'll add rings to the todo list for the first content update. 

Also single biome planets are already a thing.  You can either configure biomes allowed to be the only biome on a planet via the "SingleBiomes" option in the Advanced Rocketry config or you can specify manually used the advanced planet XML config as detailed here: http://65.78.115.159:8000/AdvancedRocketry/concepts/AdvancedPlanetConfiguration.php

**Comment by AGiLE-EaGLE1994** [comment]
What I meant was different planet icons and LEO images so that planets with those biomes would look different from Earthlike planets.
Also ,will this update be for 1.7.10? Because most of my mods haven't updated to 1.10.2 yet and I don't plan on upgrading until they do.

**Comment by zmaster587** [comment]
I'd have to devise a method of doing that that would not destroy frame
rates, probably would involve layering several noise images with different
opacities and colors.  Also I plan to support 1.7.10 unless I explicitly
state otherwise.

**Comment by AGiLE-EaGLE1994** [comment]
Thanks for letting me know. I can tell 1.7.10 is still the most popular version of the game.
Do you think you might be able to add horizontal thrusters as well as the vertical ones, and perhaps antimatter or fusion engines which require the respective fuel in order to work, but have much higher thrust to weight ratios? Like Antimatter would have 20:1 and Fusion would have  10:1?  So you'd only need 1 antimatter engine to put a 20 block rocket into orbit?

**Comment by AGiLE-EaGLE1994** [comment]
Also, what about binary star systems?

**Comment by zmaster587** [comment]
Binary stars would be interesting to have.  Not quite sure what application horizonal rockets would have though.  Could you elaborate on that?

**Comment by PhilCrafter** [comment]
Is there a way to change the size of a planet or star in the PlanetDefs.xml?
I didn t found a way to that, am I missing sth?
And is it possible to enable rendering for moons when looking at a solarsystem?

**Comment by zmaster587** [comment]
Planet sizes are directly proportional to the planet's Gravitational Multiplier, it's not actually stated in the docs currently and I will make sure to add it.

the size of a star cannot be changed as of right now.

I can look into rendering moons around planets in the solar view.  I've been apprehensive to do that because it already feels somewhat cluttered.

**Comment by PhilCrafter** [comment]
ty for the quick response

**Comment by AGiLE-EaGLE1994** [comment]
I'm back.
Well, the reason I suggested horizontal rockets is because having a horizontal warp ship or a shuttle with vertical rockets when the ship is parallel to the ground looks quite silly.
I use a small shuttle to go from my warp ship to the planet the ship is orbiting, and the ship is horizontal but the engines are on the bottom which looks strange. I'd prefer if you could have horizontal rockets that would do one of two things:
If on a warp ship: They'd decrease the warp time and allow for moving the ship into different areas of the orbit (To dock with a station directly in front of and above the ship, for example)
And if on a rocket: They'd act like vertical thrusters but just look better on certain designs.

**Comment by zmaster587** [comment]
Horizontally launched rockets have their own tracker, binay/ n-ary star systems implemented.
