### ISSUE TITLE
Low Gravity on overworld

### ISSUE THREAD

**Issue by mrtopf** [zmaster587/AdvancedRocketry#287]
I just started a new world in my pack and put advanced Rocketry into it again. 

Problem: The gravity on the overworld is lower than it should be (like default).

Here is my modlist: 
https://gist.github.com/mrtopf/c6103911ef0fea67485dd9637699ec3c

Here is the advRocketry folder from my world save: 
https://drive.google.com/open?id=0B4Osm0iwYkrMLV9XSlhXc3VnQnc

(there is another one in the instance root with only temp.dat but that's empty)

Direct link to temp.dat:
https://drive.google.com/open?id=0B4Osm0iwYkrMR29Nd1h1SGFpOXM

Versions: Forge 2125, AdvRocketry 1.0.0-RC2, Minecraft 1.10.2

In pack with only Advanced Rocketry everything is fine so it seems to be a mod compat issue. I will also try around a bit more and keep you posted in case I find the mod making problems (I assume something with dimensions).

**Comment by mrtopf** [comment]
I looked into the dat files with nbt explorer and the one in my test world has 59 entries (with only few mods) but the one above has only 2 with a wrong grav multiplier for id 0 (which I assume is the dimid and thus overworld). So apparently something is breaking that generation.

**Comment by zmaster587** [comment]
Are you using xml to generate planets or have you modified AR'S config at
all?

**Comment by mrtopf** [comment]
I only changed the space station dimension to -12 because voidcraft already has a dimension -2. I also tested voidcraft and AR in a testworld though and there it worked (also with the -12 setting). 

Also I just broke my modlist link I guess, will fix that shortly.

**Comment by mrtopf** [comment]
fixed it and here it is again: https://gist.github.com/mrtopf/c6103911ef0fea67485dd9637699ec3c

I can also provide new logfiles later.

**Comment by mrtopf** [comment]
Here is the complete logfile: https://gist.github.com/mrtopf/807a74902f2f102e1c00320aeaaba4d3

And here are only the lines with advancedrocketry: https://gist.github.com/mrtopf/4bf184875ce2dfc86f30e26d0195417a

(I deleted the advRocketry folder before starting it again. Is the advRocketry in the root folder actually obsolete? It still gets created with an empty temp.dat though). 

Here is my main AR configuration file: https://gist.github.com/mrtopf/810baa264ee58d614fcf920bd16c2152

(I just noticed that I also set the min dimension to 1200)

I hope that helps. In case you need something more please tell me. I guess more debug output on creating that file might be useful. I also see an exception on loadDimension in that log.

**Comment by mrtopf** [comment]
so I renamed my config folder and after that it seems to be ok. Now that's even more annoying to debug.. I will keep you posted in case I find the offending config/mod.

**Comment by zmaster587** [comment]
Try using 2 as the dim offset and see if it still occurs with that

**Comment by mrtopf** [comment]
With the new configs it seems to be ok. I now copied my old configs to a backup and then used winmerge to merge back in the lines I needed. Now even with only changing the space station dim id to -12 it works (because of the voidcraft dim conflict on -2).  Maybe broken/old configs will lead to an incomplete temp.dat? 

That at least fixes it. So feel free to close this or add this to some readme or so. Now I only hope the rest works and I can finally go to space :-)

**Comment by mrtopf** [comment]
on another note: Maybe some more debug on temp.dat creation would be cool (e.g. via some config flag) in case this keeps happening.

**Comment by zmaster587** [comment]
Is it fixed even with the min dimension set to 1200 on first world load?
also AR doesn't do any planet gen at all if a temp.dat exists, so I cannot imagine configs would play a role in that.

**Comment by zmaster587** [comment]
Overworld gravity gets messed up with high offsets and not loaded from planet def xml

**Comment by mrtopf** [comment]
so I tested it again and indeed I die again with 1200. But apparently you have fixed it already. I also usually deleted my world on every test so advRocketry/ should also have been deleted. The one in the instance root stayed of course though.

**Comment by zmaster587** [comment]
I'll figure out why there's a copy generating in root.  That shouldn't be happening

**Comment by mrtopf** [comment]
that was the one I send you in the other bugreport which was empty. So this might also be confusing for bug reports.
