### ISSUE TITLE
Crash when loading a world

### ISSUE THREAD

**Issue by QuantumSheep** [zmaster587/AdvancedRocketry#290]
Hi,

I had a crash when trying to connect at my modpack's server.
Don't know how to reproduce but I was on the overworld.

Crash-Report: http://pastebin.com/czd50z9n
Error beforge crash: http://pastebin.com/6g1Ue0Z9

Forge version: 1.10.2-12.18.2.2124
Advanced Rocketry version: 1.10.2-1.0.0RC3
Modpack: https://minecraft.curseforge.com/projects/quantic-experiments

**Comment by zmaster587** [comment]
Is you dont use the ConcMarkSweepGC does this still occur?

**Comment by QuantumSheep** [comment]
That's just happened one time, I don't know how to reproduce...
I just had this crash and post it 😄

**Comment by zmaster587** [comment]
Hmm, will look into it further.

**Comment by Divineaspect** [comment]
I think I'm having the same one on attempting to join a server.

http://pastebin.com/JRiBHEN8

**Comment by zmaster587** [comment]
That does look like the same one.  Can you repeat it on demand?

**Comment by Divineaspect** [comment]
It seems irregular.

**Comment by zmaster587** [comment]
Hopefully fixes along with #346
