### ISSUE TITLE
Crash when right-clicking an Extinguished Torch

### ISSUE THREAD

**Issue by QuantumSheep** [zmaster587/AdvancedRocketry#292]
The crash happend when I right-click an extinguished torch after turn on an oxygen vent.

Forge: 1.10.2-12.18.2.2151
Advanced Rocketry: 1.10.2-1.0.1

Crash-Report: http://pastebin.com/epsdjuqF

**Comment by zmaster587** [comment]
Appears to occur if the player is not holding anything in the hand they are clicking with, looks like I missed a null check.
