### ISSUE TITLE
Cannot travel to planets with dimId >= 256

### ISSUE THREAD

**Issue by RealGrep** [zmaster587/AdvancedRocketry#293]
This is with Advanced Rocketry 1.0.1, and LibVulpes 0.1.9, on Minecraft 0.1.9 and Forge 2125.

I've been tearing my hair out, metaphorically, trying to figure out why I can't launch my ship to Luna. I believe I've found the reason. Recall that we're supposed to be able to set the minimum dimension Id to higher numbers so that it doesn't interfere with things like RFTools Dimensions. So mine is set to 7000, which should keep it well out of the way.

However, every time I try and launch to Luna, it says "Destination Unreachable". I have tons of fuel, thrust, etc. Well, I looked into the source code, and found this in DimensionManager.java which is called and, when failed, leads to the message I see:

```
public boolean canTravelTo(int dimId){
		return dimId < GASGIANT_DIMID_OFFSET && net.minecraftforge.common.DimensionManager.isDimensionRegistered(dimId) && dimId != -1;
}
```
Now, GASGIANT_DIMID_OFFSET is defined as:
`public static final int GASGIANT_DIMID_OFFSET = 0x100; //Offset by 256`

So if I'm reading this right, it will refuse to launch to any planet or moon with a dimId of 256 or greater. Luna is at DIM7000.

Perhaps this needs to be an offset from the minimum dimension Id? I also notice if I do `/advrocketry planet list`, I see 'DIM256: Sol-256', which I assume is the gas giant. Probably also needs to be offset from the minimum dimension Id? Honestly, a better way might be to not rely on the dimension Id number at all here for gas giants. Either way, that limits the number of dimensions available for planets. A fair number, but still.

As an aside, neither Earth or Luna appear in the Astrobody Data Processor. Not sure if it's generally related to this or not, but it wouldn't surprise me if it has something to do with the minimum dimension d being higher.

**Comment by zmaster587** [comment]
Yeah, this is some old code I forgot to remove while switching over to using a stored boolean to determine whether or not a planet was a gas giant,  guess I missed two spots (one being the destination check the other when registering gas giants, probably getNextGasGiantId()), will have the fixed for the next build.
