### ISSUE TITLE
Unable To Get AR Achievements

### ISSUE THREAD

**Issue by HyperionNexus** [zmaster587/AdvancedRocketry#294]
I made a small plate press, placed it, used it, etc and didn't get the achievement. 

Version: 1.10.2-1.0.1

**Comment by zmaster587** [comment]
Did you make it in a vanilla crafting bench or something else?

**Comment by zmaster587** [comment]
Turns out crafting a warp core would give you the achievement for crafting an arc furnace, which should also be fixed now.
