### ISSUE TITLE
O2 scrubber doesn't work

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [zmaster587/AdvancedRocketry#296]
MC 1.10.2 , forge-1.10.2-12.18.2.2151, 
AdvancedRocketry-1.10.2-1.0.1,LibVulpes-1.10.2-0.1.9-universal

Issue: 
O2 Scrubber does not use up  CarbonCollectionCardridge(carbonScrubberCardridge)
The cardridges also not accepted by ChemicalReactor

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
Found the "problem"
the O2 scrubber is working, eating  CarbonCollectionCardridge when:
- placed next to an working O2Vent , which must be supplied with O2, 

It does not supply the vent with O2, just reduce the amount of consumplion 

my fault

**Comment by zmaster587** [comment]
No problem.

When I get a chance to write the docs I'll make sure it is clear there.
