### ISSUE TITLE
[suggestion] drill bay 

### ISSUE THREAD

**Issue by ChilledDayz** [zmaster587/AdvancedRocketry#298]
I was wondering if you could add a drill bay similar to a satellite bay for storing all of the mining drills as I hate building them on top of the rockets. I like to build nice looking rockets. I can't help but think a rocket wouldn't fly with a huge drill on top. You could also extend the mission time to allow for the drill building itself before mining an asteroid. 

This isn't a huge thing if it's not possible or not worth doing I just thought I'd ask.

**Comment by zmaster587** [comment]
I actually much prefer this idea over the current implementation.  I always ended up build rockets with pancakes on top and it looks ugly...

**Comment by zmaster587** [comment]
I just ended up making it so they can be placed anywhere on the ship.  But have double mining power on top.
