### ISSUE TITLE
Precision Assembler not forming 

### ISSUE THREAD

**Issue by megaloloful** [zmaster587/AdvancedRocketry#299]
Ive built the precision assembler like shown with the holo projector but I can't form it. Pictures: http://imgur.com/a/ynsCX

Mc 1.10.2
Forge 12.18.2166
Advanced Rocketry 1.0.2
LibVulpes  1.10

**Comment by ChilledDayz** [comment]
Use the scroll wheel to move up to the next layer of the holo project. You've only built the Base Layer of the machine.
