### ISSUE TITLE
Can't create a new world

### ISSUE THREAD

**Issue by Tsyklop** [zmaster587/AdvancedRocketry#3]
Error - http://pastebin.com/uCQLNMb0

**Comment by zmaster587** [comment]
you have a dimension Id conflict, try changing the moon dimension to something other than 2 in the config, try 23 or something

**Comment by Tsyklop** [comment]
23 and put all works. Why by default you do not put 23 that there were no questions asked.

**Comment by zmaster587** [comment]
Because the only other dimension mods I know of occupy Id 7 and negative ranges so 2 would work with them.  2 is also the first positive free Id and sticking it in the middle of nowhere seemed odd.
