### ISSUE TITLE
Scanning not occurring, what's going on?

### ISSUE THREAD

**Issue by HyperMan19680** [zmaster587/AdvancedRocketry#30]
I made a simplistic rocket on a 3x3 pad, and the structure tower is high enough, am I doing something wrong? I since tried a 4x4 pad, and nothing else changed.

http://prntscr.com/8z55h6 for a approximation of what my pad looks like.

**Comment by zmaster587** [comment]
The rocket builder needs to have its back facing the pad and needs to be one block above the pad.  So try rotating the builder next to the creative energy cell

**Comment by HyperMan19680** [comment]
It was the above the pad bit that caused it. Mine was right next to the pad.
