### ISSUE TITLE
[suggestion] Asteroid selection 

### ISSUE THREAD

**Issue by ChilledDayz** [zmaster587/AdvancedRocketry#300]
Just an idea but is there a possibility of adding an machine to scan for nearby asteroids. It could work similar to this, place an full asteroid data chip in the machine and press a button to scan near by space. 

It could show results of the nearby asteroids for you to chose. You could add different types of asteroids which have different ores and blocks, like a dense asteroid, superheated asteroid. 

It's just an idea to add a bit more verity to asteroid mining.

**Comment by ChilledDayz** [comment]
Sorry for closing I thought it might not of been a viable option.

**Comment by zmaster587** [comment]
It's fine, I just have been  very busy as of late and did not get a chance
to reply.

**Comment by zmaster587** [comment]
I actually really like this idea, it was originally what I was going to do with planets, that didn't pan out out of fear of the same issue that occurs with mystcraft during play (servers I ran in the past just got 400+ dims that were visited once and discarded and just wasting space).  Setting up the UI was kinda hard as well, what I may to is add another machine similar to the planet selector used to be on the AOBD that allows "searching" and would give enough room in the interface for selecting viable asteroids.

**Comment by ChilledDayz** [comment]
I'm not a programer so I don't know really know how AR creates asteroids. But that makes sense that they'd be a dimension of there own. I don't know if it's possible but is there a way you could make a dimension that spawns biomes each made up of a specific asteroid type and then just tell to mine that biome type at least you'd only need to generate one asteriod dimension.

**Comment by ChilledDayz** [comment]
To expand on my above comment. I believe exu2 has something similar for the quantum quarry where it only loads one chunk at a time. If you could what chunk to load and in what biome. It's most likely not possible but thought I'd mention it.

**Comment by zmaster587** [comment]
The rocket missions actually don't go anywhere, when it's about to return it just spawns in a bunch of ore and shoves it in the chest depending on the parameters passed, the main problem comes from finding a way to get the data for what the user wants onto the chip without an over complex GUI.

Although that may work for manned asteroid missions.

**Comment by ChilledDayz** [comment]
Okay I see the problem. How about turning the telescope into the asteroid scanner, I mean I hardly ever use it because its just to slow compared to the satellites. You could have a mission type progress bar for the scan time add a chip process slot and a planet selection button that takes you to the planet selection screen were you could show the results of the scan. You could then select the asteroid you want, go back to the mission and process the chip with the data. You could also randomise the type of asteroids that show up when you scan too. 

Just an idea, I'm probably way off what could work but thought I'd mention it

**Comment by EnnekPL** [comment]
my suggestion is You can make two type of asteroids small and large:

Small asteroids can be mining by "ASTEROID MISSION" (no dimension needed, too small to visit by player) and 
Large asteroids (like an asteroid belt dimension or one big rock in dimension) we can add by planets xml config.

Small asteroid can be setup by xml config file like this (your setup is default but other peoples can change like they wants for modpack creators)
f.e. xml file
<smallAsteroid name="Typ A" id="1" distance="1000" randMaxSpawn="4" x="0" y="0" size="1"> //ice asteroid
	<ore block="minecraft:iron_block" chanceRatio="0.3" /> //chanceRatio is value to get this block + mass data + conposition data
	<ore block="minecraft:ice_block" chanceRatio="1.0" />
	<ore block="minecraft:snow_block" chanceRatio="1.0" />
	<ore block="minecraft:lapis_block" chanceRatio="0.1" />
	...
</smallAsteroid>
<smallAsteroid name="Typ B" id="2" distance="3000" randMaxSpawn="1" x="0" y="0" size="2"> //nether asteroid. no nether needed ^^
	<ore block="minecraft:netherrack_block" chanceRatio="1.0" />
	<ore block="minecraft:nether_quartz_block" chanceRatio="0.2" />
	<ore block="minecraft:soulsand_block" chanceRatio="1.0" />
</smallAsteroid>
<smallAsteroid name="Typ C" id="3" distance="2000" randMaxSpawn="2" x="0" y="0" size="3"> // other type of asteroids
   // distance value -  can be used for fueal calculation
   // randMaxSpawn value - is random value that  "asteroid mission command" block
   // size value - for max mining calculation 
   // x and y value for graphical scrren option
	...
</smallAsteroid>

How this can work? Create a block "asteroid mission command" when you open gui in this block you can see graphical or list of available asteroids and one slot for id asteroid chip to write on him type of asteroid and distance data bar.
How to get available asteroids? connect f.e. observatory by cable to "asteroid mission command" block and when block rich f.e. 1000 distance data you can see ice asteroid in your "asteroid mission command" block. now i can put my id asteroid chip to select asteroid type destination and put id chip to "mining rockat" like this work now and start rocket.
What we get by this method? abilities to harvest other types of asteroids to progress your game, you can get ores/blocks that don't exist on other planets, better data usage :)

**Comment by ChilledDayz** [comment]
Any thoughts on the above ideas? Still loving the mod by the way, it's so much fun

**Comment by zmaster587** [comment]
Turning the Observatory into an asteriod finding device I think would work very well, it would help declutter the ABDP and give the Observatory a use again.  It would also give the player more control over the resources brought back.  With that method it would give some reason to want to upgrade the observetory.  (better sensors increase accuracy, spot more distance asteroids etc).

Large asteriods as suggested by EnnekPL is something I'd like to do eventually but I see some implementation difficulties with it.  What I may end up doing with that is having an asteriod belt dimension where the large asteriods discovered by the player are generated some minimum distance from the nearest other player spawned asteriod and the rest of the dimension is full of smaller completely randomly generated asteriods.

**Comment by zmaster587** [comment]
Got a partial build working in the alpha 1.10 release, just need to add documentation in the generated XML

**Comment by EnnekPL** [comment]
that's good new :) you are master!

**Comment by zmaster587** [comment]
Implemented in a1d5cef5e7c1431c98c382decfc2d5beb09e14e9 and finallized in 7ce95c6037ee198709f7bf19ee48a58aca882f24
