### ISSUE TITLE
[1.10.2] Data Storage Unit displays as 0/0 Data no matter what

### ISSUE THREAD

**Issue by DestinyPlayer** [zmaster587/AdvancedRocketry#302]
Basically what I've described above. The Data Storage units ALWAYS display 0/0 Data, and I can't input anything into them. Also, maybe related to that, I can't get the data cables to work. But maybe I just can't figure how to pump data from the observatory into the Astrobody thingy.

http://prntscr.com/deyoyk - My current modpack
http://pastebin.com/382Nn1QH - The latest log

**Comment by dmodoomsirius** [comment]
Does this happen with just Advanced Rocketry, Lib Vulpus and forge?

**Comment by zmaster587** [comment]
I've just tested both the data cables and the data chips, the data chip (freshly crafted) displays 0/1000 until filled from a data bus.  Data cables tested with either the observetory and satellite terminal transfer data to an Astrobody data processor when the pulling sides are powered by redstone.

Does it show 0/0 in the creative menu/JEI and does this still occur under the conditions Dmod specified?

**Comment by DestinyPlayer** [comment]
Yes, it showed up as 0/0 in the creative menu and JEI. And no, it doesn't occur when I only install AR, Lib Vulpus and Forge... Pardon me for asking it here, but do you have any ideas what might have caused AR to break in my pack? I don't, personally. Maybe it's ProjectE, as one of the only mods that affects other items in any way?

**Comment by zmaster587** [comment]
best think to do is remove half the mods at a time, if the issue no longer occurs remove the current half and swap in the half you took out, repeat until it's just AR, libvulpes and that other mod (and it's dependancies if any)

**Comment by DestinyPlayer** [comment]
Either that or to turn off all mods and to then turn them on one at a time... Will do that.

**Comment by DestinyPlayer** [comment]
It appears to be some strange reaction between Advanced Rocketry, Vazkii's Quark and some other mod. Investigating more specifics right now.

**Comment by DestinyPlayer** [comment]
Discovered that my Quark was slightly old. The new version doesn't have that bug. Thank you all for helping, but the bug seems of have fixed itself.

**Comment by DestinyPlayer** [comment]
Added: the liquids appear to miss textures with this pack of mods installed, but at least it works now.

**Comment by zmaster587** [comment]
So it appears to have been some issue with the old build of Quark?

Also, no problem! Thank you for reporting a potential issue.
