### ISSUE TITLE
[1.7.10] AdvancedRocketry + ICBM

### ISSUE THREAD

**Issue by DrunkenVobla** [zmaster587/AdvancedRocketry#303]
I get a crash while starting my client with just AR, ICBM and Thermal Expansion installed (latest versions with libs)
Separately both mods works perfect.
Crashlog http://pastebin.com/8HdZhGDS

**Comment by SvEgiiVEteR** [comment]
I also have a crash

**Comment by zmaster587** [comment]
Reminds me a lot of https://github.com/zmaster587/AdvancedRocketry/issues/281
investigating

**Comment by zmaster587** [comment]
Turns out the fix applied to #281 did not work in 1.7.10 because if no block for a given item is found in 1.7.10 it returns Block.air, in 1.10.2 it returns null, I had assumed the that return in 1.7.10 would also be null which is why this occured.

**Comment by zmaster587** [comment]
will probably push a release today or tomorrow with the fix

**Comment by SvEgiiVEteR** [comment]
no (((
https://gist.github.com/aa4b2a6c54ca8e890e82a0765c0abb88
AdvancedRocketry-1.7.10-1.0.3.jar
LibVulpes-1.7.10-0.1.11-universal.jar
and
ICBM-1.7.10-2.14.0b26-universal.jar
VoltzEngine-1.7.10-0.23.1b11-universal.jar
separately work...
do not work together

**Comment by zmaster587** [comment]
That looks like you're missing the RF API

**Comment by zmaster587** [comment]
Try deleting and redownloading libvulpes

**Comment by SvEgiiVEteR** [comment]
@zmaster587 
AdvancedRocketry-1.7.10-1.0.3.jar
CRC-32: 8b58ea2d
   MD4: f4db399eb2b59cb431c09c1564f48a76
   MD5: 1e1bdd3da83f166d962978fb14539316
 SHA-1: 8ad3ac1a5b944a33c94334c9659b7fda04447bd8

LibVulpes-1.7.10-0.1.11-universal.jar
CRC-32: 33af05ac
   MD4: 5e8b06aedeb75b139e08ee0aba7758a7
   MD5: 89bfc04765ee07246c3f2ca7e0fde690
 SHA-1: e599cb9079da493ca79d26ec3d247439f719665e

AdvancedRocketry-1.7.10-1.0.3
ICBM-1.7.10-2.14.0b26-universal.jar
separately these mods work single player world is also checked.
and together do not want

**Comment by zmaster587** [comment]
I suspect VoltzEngine is doing something cooky as I am unable to get it to launch with buildcraft or enderIO.

looks like this issue here now: https://github.com/BuiltBrokenModding/VoltzEngine/issues/56

**Comment by SvEgiiVEteR** [comment]
Oh.... very bad ((

**Comment by zmaster587** [comment]
Was talking to Darkcow earlier, he's working on a fix for it so hopefully everything should be working soon.

**Comment by dmodoomsirius** [comment]
I didn't push the fix to curseforge yet. I will be doing that soon. going to test and make sure it works fine.

**Comment by dmodoomsirius** [comment]
https://minecraft.curseforge.com/projects/voltz-engine/files/2353112 ok fix has been pushed to curseforge.
Thank you for your patience :)

**Comment by SvEgiiVEteR** [comment]
Yes, now without crash, start with 400 mod)
