### ISSUE TITLE
[1.10.2] [1.0.3] Seats are dangerous, and confusing!

### ISSUE THREAD

**Issue by Tokeli** [zmaster587/AdvancedRocketry#304]
I've found two issues with seats, one of which is pretty big--

1, in SMP, a seat with just 2 open spaces above it will ALWAYS fail to find an appropriate dismount spot, and instead drop you beneath the bedrock, to your death. From my testing, it functions correctly in singleplayer. A three-high space above the seat or around it will let you dismount as usual.

Trying to sit and then stand-up from this seat will drop you into the void in SMP.
![java_2016-12-09_07-10-46](https://cloud.githubusercontent.com/assets/6316563/21048710/a543fbf0-bdde-11e6-81c7-77a29fc89565.png)

2, Upon sitting down on the seat, each time, I will be given various items, from Vanilla and, so far, two other mods. I haven't done enough testing to tell whether it's another mod or Rocketry doing it however. So far, I've gotten Raw Squid from Improving Minecraft, Ink Sacs, Sugar Canes, Cooked Chicken, Leather, and "Coralium plagued flesh on a bone" from AbyssalCraft.

**Comment by zmaster587** [comment]
Will look into that for the 1.0.4 release, sorry about the late reply, been very busy

**Comment by zmaster587** [comment]
Not quite sure why you're getting random drops when you sit on the seat.  I've had reports of people getting eggs once in a blue moon when sitting on it, but there was always a chicken nearby when it was reported and not reproducable.

The death part was caused by me neglecting to properly set the bounding box of the entity that you actually sit on.

**Comment by zmaster587** [comment]
Turns out the player is somehow colliding with far away drops when sitting down.  Sitting in the same seat multiple times in quick succession does not pick up items
