### ISSUE TITLE
Aluminum ore not generating

### ISSUE THREAD

**Issue by jmdisher** [zmaster587/AdvancedRocketry#306]
Looks like an omission in zmaster587/advancedRocketry/world/ore/OreGenerator.java (in generate).

Looking at the history (wanted to make sure that this wasn't deliberate and being handled in a different way), it looks like this was an oversight in commit df38ac4 which may have managed to go unnoticed if those using this already have aluminum ore in their packs (I don't so I was wondering why I wasn't seeing any).

**Comment by zmaster587** [comment]
Thank you!
