### ISSUE TITLE
[1.10.2] Custom XMl recipes: No metadata support?

### ISSUE THREAD

**Issue by MechWarrior99** [zmaster587/AdvancedRocketry#309]
I ether don't know how, or there is no way to use a item/block with metadata in a custom XML recipe.  

This is what it looks like in JEI when I have it set for the input to be black wool (metadata 15)
![image](https://cloud.githubusercontent.com/assets/8076495/21151422/51c4c9b4-c117-11e6-99fb-f5712c2d63b6.png) 

And here is what I have in the xml if you are interested:
![image](https://cloud.githubusercontent.com/assets/8076495/21151604/f38bf3c6-c117-11e6-8283-79b1da7ede0b.png)

**Comment by zmaster587** [comment]
Try entering the recipe like in the guide:
http://65.78.115.159:8000/AdvancedRocketry/concepts/RecipeConfiguration.php

<itemStack>minecraft:wool 1 15</itemStack>

**Comment by MechWarrior99** [comment]
Yep, that works. Thank you. Sorry for the bother, I for some reason couldn't find the guide. 

Also, as a random side note. Seems like strange formatting, why have the quantity before the metadata? Just seems weird to me.

**Comment by zmaster587** [comment]
I based it off the vanilla give command.

**Comment by zmaster587** [comment]
Is fine, did you try looking on the site at all or could you not fond the
site?

**Comment by MechWarrior99** [comment]
I did look, but I didn't see the recipe section for some reason at the time.

**Comment by zmaster587** [comment]
I'll look into building a better layout, I suppose putting it under
"concepts" does not makeep much sense

**Comment by MechWarrior99** [comment]
I would just add another second called "customization" Or something like that, and put the XML recipes in there along with other stuff.

**Comment by zmaster587** [comment]
I can do that
