### ISSUE TITLE
Consider updating the source?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#31]
Just want to see the changes since 0.2 :)

**Comment by zmaster587** [comment]
There really hasn't been any other than the minor bugfixes, I have been very busy with life so have not had much time to do anything, expect things to speed up again in December though

**Comment by wormzjl** [comment]
Do you need and help with bugfixing?

**Comment by zmaster587** [comment]
the big TODO right now is the oxygen system, and better recipes for things
