### ISSUE TITLE
Failed to register dimension crash

### ISSUE THREAD

**Issue by CJMinecraft01** [zmaster587/AdvancedRocketry#312]
Upon using the mod with many other mods I have found that another dimension is registered with the ID of -2 so I was wondering if you could provide an update to change this dimension id to be something else.
Thanks in advance :smile:
Here is the crash in case you want it 
[crash-2016-12-15_17.09.49-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/655369/crash-2016-12-15_17.09.49-client.txt)

**Comment by zmaster587** [comment]
There is an option in the AdvancedRocketry config to change the dimId for use for space stations.  See if changing the config option "spaceStationId" to some other value works for you.

**Comment by CJMinecraft01** [comment]
Sorry I didn't notice that :smile:

**Comment by zmaster587** [comment]
It's fine.  If that works feel free to close the issue, if not let me know so I can see what's wrong,
