### ISSUE TITLE
[1.7.10] Small Plate Presser doesn't work properly with oredict

### ISSUE THREAD

**Issue by Kataiser9** [zmaster587/AdvancedRocketry#314]
Non-vanilla ore/ingot blocks from other mods (e.g. TiCon copper ore, Railcraft Block of Steel) do not work in the press, even though NEI says they should. Equivalent blocks from LibVulpes work fine. Perhaps not a critical issue, but one that I imagine would be easy to fix.

**Comment by zmaster587** [comment]
Ironically I fixed this issue in one of the last 3 commits.

Turns out it's actually the order the recipes are registered in.  It would
only work with the first recipe added.

It should be fixed in the next build.

Thank you for reporting, it really helps build a more stable mod!
