### ISSUE TITLE
[1.7.10] Server timed out when returning to Earth from a Space Station

### ISSUE THREAD

**Issue by turboclonerider** [zmaster587/AdvancedRocketry#315]
I have a serer i play with my friends and whenever i try to return to Earth from my space station, i get a timed out error, then i cant join server until i restart the server or my game. i haven't tested this whith my friends yet, but it is an issue i encounter.

**Comment by zmaster587** [comment]
Does everyone else on the server time out or is it just you?

**Comment by turboclonerider** [comment]
no one else has been on yet since i was on late, but i can test that with my friends hopeully today

**Comment by zmaster587** [comment]
Does it occur if it's just you still?

**Comment by m0nkm0nk** [comment]
Server specs? Seems it cant keep up. Throttles, all clients time out, then regain TPS and is joinable again.
Cannot repro this one. Teleported 10 times from overworld to dim -2 while 8 other players connected. No issues.

**Comment by turboclonerider** [comment]
i think it's something to do with loading worlds terrain, it happens only when im on by myself

**Comment by zmaster587** [comment]
That's what I suspect as well.  What if others are on but really far away
from your landing site?

I almost wonder if it's trying to load all the chunks at once and taking
too long to do so.

**Comment by turboclonerider** [comment]
so far everyone's been at the base we use when landing so i haven't tested for when they're far away.

**Comment by turboclonerider** [comment]
i have had this issue with other planets too, i remember trying to land on sol-2 , this was the blue gas giant in the solar system. I'm not sure if it's just not landable or if its the same issue i have with earth.

**Comment by zmaster587** [comment]
It shouldn't even let you attempt to let you land on a gas giant as the gas giants do not actually have a dimension associated with them.  

Do you know the specs of the server this is being run on?  And would you be willing to run a program like VisualVM to better determine the source of the problem?

**Comment by turboclonerider** [comment]
i dont really know the specs of the server but there are a lot of mods and this may be whats causing the crash. i know when i was trying this with a couple extra mods it would be really slow so it might just be too much ram being used at once.

**Comment by zmaster587** [comment]
If you're timing out it's not crashing, but something is taking enough time on the main thread that the network connection is timing out.

Could be lack of RAM, could also be excessive CPU or HDD usage.  Is kinda hard to troubleshoot without a profiling tool or some way to reliably replicate.

**Comment by zmaster587** [comment]
probably safe to say either slowish hw or large amount of calculations performed by another mod or incorrect JVM config.
