### ISSUE TITLE
Possible incompatibility with Dynamic Surroundings [1.7.10]

### ISSUE THREAD

**Issue by m0nkm0nk** [zmaster587/AdvancedRocketry#317]
Let it rain, build a rocket, shift + right click to get in the interface. Select the guidance computer for example, crash to desktop.

Crashlog: http://pastebin.com/1v50GfKU

Not sure if this is AR related.

**Comment by zmaster587** [comment]
I only see DynSurroundings in the trace.  Will investigate though.

**Comment by zmaster587** [comment]
Looks like I had to do with the voodoo around the fake world the rocket uses for inventory/tile interaction.

**Comment by zmaster587** [comment]
Will close this for now, if it persists in 1.0.4 just comment on this issue again.
