### ISSUE TITLE
[1.10.2][1.0.3] Placing a stack of [bucketRocketFuel] into [fuelingStation] should add more fuel and return more buckets.

### ISSUE THREAD

**Issue by codetaylor** [zmaster587/AdvancedRocketry#318]
Thank you for this amazing mod and keep up the good work!

When placing a stack of [bucketRocketFuel] into the [fuelingStation] only one bucket's worth of fuel is added and only one bucket is returned.

**Comment by zmaster587** [comment]
You're welcome, I've run into this myself a few times while debugging other stuff but keep forgetting to fix.
