### ISSUE TITLE
Electric arc furnance integrity check issue

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#32]
For example, when I put my engine here after completion, the arc furnace's gui will be bugged (not showing total power) but sometimes it can still smelt stuff, it no longer works after reenter the game
![2](https://cloud.githubusercontent.com/assets/2989009/11080747/4566eea2-8817-11e5-867d-c8354715680a.jpg)
![3](https://cloud.githubusercontent.com/assets/2989009/11080749/4900892e-8817-11e5-89c3-e39a5f006436.png)

But if I put the engine like this it worked smoothly
![1](https://cloud.githubusercontent.com/assets/2989009/11080761/66c4496e-8817-11e5-8641-d36f6baed3ec.jpg)

So I guess it checks the integrity of air blocks beside the rf plug too?

**Comment by zmaster587** [comment]
Yes, but that's an oversight on my part, will fix for next release

**Comment by wormzjl** [comment]
it working now :3
