### ISSUE TITLE
[1.10.2][1.0.3] Compatibility with Immersive Engineering power

### ISSUE THREAD

**Issue by codetaylor** [zmaster587/AdvancedRocketry#322]
I can't seem to get power to transfer into the Power Input Plug when using Immersive Engineering's Wire Connectors.

**Comment by zmaster587** [comment]
is the generator from AR as well or are you using a generator from another mod?

Reason I ask is that I'm finding neither IE nor EnderIO are pulling power from AR generators however EnderIO can put power into AR machines at least.  I've not been able to insert power with IE either.

**Comment by zmaster587** [comment]
I got a fix for the enderIO stuff, but Immersive Engineering is not something I can easily fix.  As far as I can tell problem with IE is that he's not using Forge's Capability system to extract and/or insert energy into blocks but rather checks for the existance of Tesla or RF interfaces on the tileentity.  For me to do that would require me to backport to the old way of handling power, which is much more rigid.  I'll look into submitting a pull request and/or developing a workaround.

**Comment by zmaster587** [comment]
Submitted a pull request to IE to allow it to insert power into blocks implementing the Forge Capability system here: https://github.com/BluSunrize/ImmersiveEngineering/pull/1821.

**Comment by codetaylor** [comment]
> is the generator from AR as well or are you using a generator from another mod?

I didn't try the AR generators, I used creative capacitors from IE and EnderIO with the wire connectors from IE.

**Comment by zmaster587** [comment]
Alright, either way testing with the patches to libvulpes and the pull request to IE seems to work fine in every case.  Compat should work with the next builds of IE and LibVulpes.
