### ISSUE TITLE
[MP-1.10.2] [1.0.4] Build rocket = ticking world entity crash

### ISSUE THREAD

**Issue by darkshadow1809** [zmaster587/AdvancedRocketry#324]
In multiplayer on my own server it appears as to when I build a rocket as soon as its done it throws an ticking world entity error. (Won't fix itself anymore world is plain corrupt in that chunk until entity is removed)

Heres the crashlog as follows;
https://pastebin.ubuntu.com/23692536/

**Comment by zmaster587** [comment]
It appears to be crashing while writing a line to the log file?
If you test with only AR and Libvulpes does this still occur?

**Comment by darkshadow1809** [comment]
Ooph.. give me a few.

**Comment by darkshadow1809** [comment]
Confirmed. After only installing AR and Libvulpes it throws this exact error. 

https://paste.ubuntu.com/23693489/

Looks like quite a few things erroring.

**Comment by zmaster587** [comment]
looks like it was introduced in commit b35a5357a9d7c4ec7bf2bcf84c6601b90ff40c33
It should have been ChunkProviderDummy rather than ChunkProviderClient.  The 1.7.10 build was done properly, not sure what happened here though.  Things sometimes fall through the cracks i guess.
