### ISSUE TITLE
Placing Orbital Laser Block Crash and Ticking Entity Corruption

### ISSUE THREAD

**Issue by scottosx** [zmaster587/AdvancedRocketry#326]
On Spacestation, simply placed block in the world to see what it does. Crash and then world would no longer load.

[crash-2016-12-29_22.47.58-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/678270/crash-2016-12-29_22.47.58-server.txt)
[crash-2016-12-29_22.55.15-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/678271/crash-2016-12-29_22.55.15-server.txt)

**Comment by zmaster587** [comment]
I've not been able to replicate with Forge 12.18.3.2185, AR 1.10.2-1.0.4b and LibVulpes 1.10.2-0.1.12 when placing the Orbital Laser Block.  If you remove all mods other than Ar and LibVulpes does this still occur?

**Comment by scottosx** [comment]
Ok. Will try. I suspect that Malisis Switches may be related as it is indicated in the error log. I hope not though. That mod makes redstone control so much easier.

I should also mention that I did not use the Holograph projector or place the Laser in a multiblock. Nor did it have air blocks below it. I just threw it down on a platform.

**Comment by zmaster587** [comment]
By any chance did you place two next to each other?

**Comment by scottosx** [comment]
No, just the single one. I will test in a little while. I am in the middle of building my second space station to test the Warp Core.

![2016-12-30_12 29 33](https://cloud.githubusercontent.com/assets/5866215/21572160/d0ef5dd0-ce9b-11e6-9159-32b8923bfb1e.png)
![2016-12-30_14 24 03](https://cloud.githubusercontent.com/assets/5866215/21572161/d0ef7478-ce9b-11e6-812f-eeb7717d29d2.png)

**Comment by zmaster587** [comment]
Alright.  That looks epic!

**Comment by scottosx** [comment]
Ha :) You wanna see epic? Here is my first space station and earth space center. Your mod is awesome!

I'll make a fly through video when I am finished.

![2016-12-30_14 37 48](https://cloud.githubusercontent.com/assets/5866215/21572429/60d0507e-ce9e-11e6-8962-26a413bcae50.png)
![2016-12-30_14 41 26](https://cloud.githubusercontent.com/assets/5866215/21572430/60d369d0-ce9e-11e6-9556-e2b59bb200d3.png)
![2016-12-30_14 42 04](https://cloud.githubusercontent.com/assets/5866215/21572431/60d4468e-ce9e-11e6-85c8-6afd196d2967.png)
![2016-12-30_14 42 28](https://cloud.githubusercontent.com/assets/5866215/21572432/60d4b2f4-ce9e-11e6-8a87-2d0def53ace7.png)

**Comment by zmaster587** [comment]
Thanks, I'm glad you like it!  And I would love to see a flythrough video of both stations

**Comment by zmaster587** [comment]
Going to assume fixed as I cannot replicate the issue since the patch and from lack of feedback
