### ISSUE TITLE
Crash when placing a data cable in front of an observatory block

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#327]
http://pastebin.com/3sGtLen0

**Comment by zmaster587** [comment]
Do you have any items in your inventory like bags and does this happen every time you place down a cable?

**Comment by wormzjl** [comment]
Cleared my inventory and it's no longer crashing, weird -_-

**Comment by zmaster587** [comment]
It looks identical to the crash I get if my game is running a little slow and i try to open a forestry bag and switch slots real quick.  Is why I asked... Is strange though...

**Comment by wormzjl** [comment]
Could be related to terrafirmacraft, I think it have some special inventory system

**Comment by zmaster587** [comment]
Going to close, no more reports and unable to replicate or ID source
