### ISSUE TITLE
[Request] Delay before No Oxygen Damage

### ISSUE THREAD

**Issue by scottosx** [zmaster587/AdvancedRocketry#328]
There should be a small delay when you move into an non-oxygen environment  of say 3 seconds before you start to take damage.

As indicated elsewhere, I have a large space station and I need multiple oxygen vents and scrubbers to keep pressurized air. I have areas cordoned off by doors as it is kind of strange sometimes when your air detection algorithm switches from one sensor to another. When I move through a door although there is air on both sides the detection has to catch up for a few seconds and I take damage.  It seems to be tied to the duration that the door is open.

A simple delay would fix this.

I have found creating pressurized spaces to be one of the most challenging parts of the mod so far. Running on pure oxygen is not at all feasible because it uses it up too fast to keep supplied across multiple units.

The CO2 scrubbers work ok but are very expensive in iron and of course overall cost of a complete system. Still trying to balance out everything that I would have to do in survival.

I always play new mods in creative to understand all the bells and whistles, then start to focus on the effort required to do it in survival.

**Comment by zmaster587** [comment]
Maybe a better solution would be to allow O2 networks to "merge" so that if two networks are adjacent to each other and a door opens between them then rather than removing both "bubbles" it connects them.

That would prevent any damage when opening a door between two networks

**Comment by scottosx** [comment]
That might be the best long term solution. I may not need as many doors then. Doors now serve mainly to force a switch to a closer vent which seems not always to act perfectly.

**Comment by zmaster587** [comment]
I meant to do it and forgot to implement it before stable actually.  Also curious, what "atmosphereCalculationMethod" are you using in the config?  You may find mode 2 or 3 may work better for your build.  Main problem with volume based calculation could make the game lag a bit more depending on your setup.

**Comment by scottosx** [comment]
I am using the default method of a 32 block range. I did see the other options in the config but since I was setting up a large area for the first time I wanted to at first see how this method works being easier to visualize and as mentioned less resource intensive. I will get around to playing with the others.

**Comment by zmaster587** [comment]
Makes sense.  All calculation methods would have the same problem with the doors though.

**Comment by zmaster587** [comment]
Because the lack of O2 doesn't kill you outright but only does a bit of damage I don't think a delay would be worth the extra timers and stuff that would need to be coded in.  However if both sides of a door are oxygenated the O2 won't just vanish in the next build so you should be able to safely move between rooms without damage.

**Comment by scottosx** [comment]
Works for me.

**Comment by zmaster587** [comment]
Will consider closed for now, if the new build is still broken let me know.
