### ISSUE TITLE
Orientation Controller visual bug

### ISSUE THREAD

**Issue by 0othomio0** [zmaster587/AdvancedRocketry#330]
https://youtu.be/yxrxq2YD4sM

**Comment by zmaster587** [comment]
I think what's happening is that AR uses the direction of the warp controller to determine what direction is 'forward', but unless a warp controller is placed on the station it just assumes ForgeDirection.UNKNOWN.  But because that direction is a zero vector(0,0,0), no rotation occurs.

**Comment by TheGuyRunningSouth** [comment]
I'd been wondering what I had done wrong.

**Comment by 0othomio0** [comment]
I use all 4 directions

**Comment by zmaster587** [comment]
at the same time
