### ISSUE TITLE
Oversized stack in rocket unloader

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#333]
![1](https://cloud.githubusercontent.com/assets/2989009/21618257/56070b02-d1ea-11e6-973b-8b85cf50901b.png)
Just returned from a mining mission, should this be possible?
The normal stack size for these ores is 16

**Comment by zmaster587** [comment]
Shouldn't be unless some interaction is going on.  Can you see if the stack in the rocket is also an unusual size or if it's only the unloader?

**Comment by wormzjl** [comment]
In fact I couldn't access the chest on the rocket, probably another TFC derp _-_

**Comment by zmaster587** [comment]
Did you have a block over the chest?

**Comment by wormzjl** [comment]
Umm yes....I'll do some further testing.
BTW is there any way to spawn an astroid chip with full data?

**Comment by zmaster587** [comment]
I think I added "/advRocketry filldata" for debugging at some point.  It should fill the chip currently in your hand.

**Comment by wormzjl** [comment]
![2](https://cloud.githubusercontent.com/assets/2989009/21620240/b15125ac-d1f3-11e6-9d89-797eac91178d.png)
Ok this is what I got inside the chest, normally they should be 16 per stack

**Comment by zmaster587** [comment]
That may lead to an underflow in the rocket unloader.  Looks like the asteriod mining mission is just assuming 64, will fix that.  What mod are the ores from so I can test?

**Comment by wormzjl** [comment]
Terrafirmacraft

**Comment by zmaster587** [comment]
will look into

**Comment by zmaster587** [comment]
It looks like what is happening is the unloader takes the stack size of the stack it's transferring subtracted from the maximum stack size.  In your case (16-64 = -48).  It then calls decrease stack size with that number, which in turn subtracts the given number so then you end up actually making the stack bigger which eventually turns into numbers greater than 64.
