### ISSUE TITLE
[Bug]Tesselating block model (Repeated Crash)

### ISSUE THREAD

**Issue by MysticAura** [zmaster587/AdvancedRocketry#337]
MC: 1.10.2
Forge: 2185
Mod Version: 104b

When my rocket completed building the game crashed to desktop. Now this crash happens on every load.
Appears that Quark and your mod are having issues with eachother.

[Crash Log](http://pastebin.com/G0gDhrnJ)

**Comment by zmaster587** [comment]
Does this occur without quark installed and can you upload an image of the rocket and/or detail what you put on it?

**Comment by zmaster587** [comment]
After thinking about it for a while it looks like it may be just getting grass color in general,  This should also impact vanilla grass
