### ISSUE TITLE
[Request] More sound effects

### ISSUE THREAD

**Issue by scottosx** [zmaster587/AdvancedRocketry#338]
It would add a lot to the mod to have rocket sound effects, warp, etc. If this is not an area of expertise then I can help. That is, if you will just provide a few hooks, ie blank named sound files that are code referenced. Then I can test out various sounds.

Here is a good starting base for the rocket. No license issues. 
https://www.freesound.org/people/LimitSnap_Creations/sounds/318688/

However, I also have the tools and skill to start completely from scratch.

**Comment by zmaster587** [comment]
I've actually already got sound for the rocket in the mod under "assets/advancedrocketry/sounds/rocket.ogg" that I plan on using eventually.  It's just an issue of code at the moment for that.  Although some of the machines could use sounds.

I actually didn't realize until now MC had a way of looping sounds built in, so probably switching code over to that, once I do that I'll put dummy files for stuff in and probably add the rocket sound.

**Comment by scottosx** [comment]
I will visit this during the upcoming week. I am playing Advanced Rocketry in the Forever Stranded mod pack.

**Comment by scottosx** [comment]
Here is a test file to be sure I am on the right track. It is for the cutting machine. For me, the animation measured to 16 seconds.
[cuttingMachine.ogg.zip](https://github.com/zmaster587/AdvancedRocketry/files/910827/cuttingMachine.ogg.zip)

**Comment by zmaster587** [comment]
I'm not able to listen to it on mobile.  But if you have not already, keep
in mind that it may not always be 16 seconds because not all recipes are
garunteed to take the same amount of time and it is possible that it's on a
laggy server or there is not enough power to the machine.

**Comment by scottosx** [comment]
I suspected but we will have to find a happy medium somewhere. Unless there is a way in code to call sound files at specific animation points. Then I could give you layered sounds.

**Comment by zmaster587** [comment]
Short of redesigning half the sound system that's not going to be possible
I'm afraid

**Comment by scottosx** [comment]
Understood. In that case we'll try for the best sync possible within a range and if not feasible then focus on background ambience.

**Comment by scottosx** [comment]
Like here is an example one for the lathe that could sync to the animation at serendipitous times but can also stand alone as an ambience to a degree. This is mp3 for mobile preview.
[lathe.mp3.zip](https://github.com/zmaster587/AdvancedRocketry/files/910959/lathe.mp3.zip)

**Comment by scottosx** [comment]
Here is one for the Crystallizer that is purely background ambience. We may end up closer to here..
[crystallizer.mp3.zip](https://github.com/zmaster587/AdvancedRocketry/files/911073/crystallizer.mp3.zip)

**Comment by scottosx** [comment]
Love this sound for the Precision Assembler. Although it is best when it syncs it still gives a magnificent ambience to the processing.
[precisionAssembler.mp3.zip](https://github.com/zmaster587/AdvancedRocketry/files/911192/precisionAssembler.mp3.zip)

**Comment by scottosx** [comment]
Quite glitchy sound for the Electrolyzer
[electrolyzer.mp3.zip](https://github.com/zmaster587/AdvancedRocketry/files/911687/electrolyzer.mp3.zip)

**Comment by scottosx** [comment]
Chemical Reactor. BTW, none of these are yet normalized for volume or precisely edited for time and seamless loops (but pretty close). Once I have the whole group I will replace the dummy files in my copy of AR and hear how they play and mix together in a factory.

[chemicalReactor.mp3.zip](https://github.com/zmaster587/AdvancedRocketry/files/911757/chemicalReactor.mp3.zip)

**Comment by scottosx** [comment]
Electric Arc Furnace

[electricArcFurnace.mp3.zip](https://github.com/zmaster587/AdvancedRocketry/files/911778/electricArcFurnace.mp3.zip)

**Comment by scottosx** [comment]
Here are proposed final sounds. They are looped, normalized and compressed. Tested in game and I think they mix well. An extra sound for the lathe is included but there is no hook for that so untested.

Please review and comment.
[AR Machine Sounds.zip](https://github.com/zmaster587/AdvancedRocketry/files/935969/AR.Machine.Sounds.zip)

**Comment by zmaster587** [comment]
Oops, yeah, lathe uses the rolling machine sound for some reason.  Also I'm not sure if these are for a resource pack or if you want me to integrate them into the mod as default.  If you do want me to incorporate them into the default mod I would prefer if it was explicit so there are not any misunderstandings.

Anyway, will add the hook for the lathe

**Comment by scottosx** [comment]
You are welcome to incorporate them into the mod if they fit with your vision. Otherwise, I could do a resource pack at some point. Don't feel obligated to add them though. And if you have constructive criticism then I can do some alterations. Credit would be to my MC user name ScottoMotto.

**Comment by scottosx** [comment]
Here are versions of the sounds mixed to mono which might be better for the spatialization that MC provides.

[AR Machine Sounds Mono.zip](https://github.com/zmaster587/AdvancedRocketry/files/945165/AR.Machine.Sounds.Mono.zip)
