### ISSUE TITLE
Crash 1.7.10 [1.0.5]

### ISSUE THREAD

**Issue by 0othomio0** [zmaster587/AdvancedRocketry#339]
Rocket doesnt reach to space station. Rocket stops when the height of 1000 blocks. When  I'm out of rocket minecraft crashs
[crash-2017-01-08_00.42.25-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/691755/crash-2017-01-08_00.42.25-client.txt)

**Comment by zmaster587** [comment]
is it your first time going to that particular space station?

**Comment by 0othomio0** [comment]
No, it is second

**Comment by 0othomio0** [comment]
I created new world, and i saw this bug in first time going to that particular space station

**Comment by 0othomio0** [comment]
A have qustion. How to destroy rocket  ?

**Comment by 0othomio0** [comment]
I realized what the problem is. I flew to the space station, which was not launched into space. In 1.0.4 I do I could not, but 1.0.5 I can fly, but glide to 1000 222 00 33, as the station does not exist.

**Comment by zmaster587** [comment]
It's actually crashing because the rocket expects a player in the seat and when you get out of it it tries to reference the mounted which is no longer there and crashes.  If you fly to a non existant space station you should just end up falling back to Earth.

I'll try to replicate

**Comment by zmaster587** [comment]
With 1.0.7 if you go to a space station that is not yet in orbit you'll just drop down to the planet below.
Will consider fixed for now.
