### ISSUE TITLE
Crashed on right clicking the satellite terminal

### ISSUE THREAD

**Issue by yuyuyzl** [zmaster587/AdvancedRocketry#34]
[crash-2015-11-26_17.13.17-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/44783/crash-2015-11-26_17.13.17-client.txt)
using AdvancedRocketry-0.3.3.
ty.
I repeated it and it crashes every time.

**Comment by zmaster587** [comment]
Does it still crash if you break and replace it?

**Comment by yuyuyzl** [comment]
well yes and i tried create a new world or go to a server and it crashes too... trying to contact my friends to test it, maybe it's our modpack's fault.

**Comment by zmaster587** [comment]
It's looking to me like the tileEntity is missing.  Does it still occur if it's only libVulpes and AdvancedRocketry loaded?

**Comment by yuyuyzl** [comment]
idk sry...but a friend using windows 10 crashes the same time but another friend using win7 works well... and we all running jre8_60 x64...it seems really confusing. thanks.

**Comment by yuyuyzl** [comment]
Oh sorry, it's my fault because later i downloaded the original mod in Curseforge and it works well. The problem may be a wrong compiler , I mean, JDK version or sth. i tried to recompile your mod from your source and may i know the JDK version you are using?
And, great mod with impressive machines and rockets! Thank you very much!

**Comment by zmaster587** [comment]
I would still like to investigate this further if you don't mind, a tile entity should not exist on win7 but not the win10.
