### ISSUE TITLE
1.10.2 crash - ConcurrentModificationException

### ISSUE THREAD

**Issue by LewisMcReu** [zmaster587/AdvancedRocketry#346]
Occurs on world load while (I assume) iterating the dimensions in the DimensionManager.
Would fix if I had the time to look.
[crash-2017-01-16_02.36.00-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/707080/crash-2017-01-16_02.36.00-client.txt)

**Comment by dmodoomsirius** [comment]
Does this only happen with only LubVulpus and Advanced Rocketry?

**Comment by zmaster587** [comment]
I've seen this issue before, I've had it reported and I've run across it myself, however it is nearly impossible to replicate reliably and if the game is restarted it does not appear again in most cases which makes it kinda hard to fix.

**Comment by zmaster587** [comment]
I'm fairly sure this patch will fix the issue, will close for now unless something else comes up with 1.0.8
