### ISSUE TITLE
asteroide ore density setup and travel time (enhencement)

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#347]
Hello,

1) Is it possible to setup or decrease ores in asteroides, getting easily stacks of redstone for exemple unbalance the game ;)
 
2) is it possible to make rocket trip longer (1 day? 1 week?) to go to asteroide,mine and come back to make it little more realistic?

Thanks for all it's an amazing mod! (and yes i play it with gregtech 6 on my server as i like hard challange héhé)

**Comment by zmaster587** [comment]
There is the "miningMissionMultiplier" setting in the config which can increase or reduce the amount of material brought back from a mining missing.

I can go ahead and add a time multiplier too.  I did for the gas collection missions but not for the asteriod mining missions for whatever reason.

Glad you like it!
