### ISSUE TITLE
[Suggestion] Improvement to asteroid mining system config

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#349]
1. add a weight factor to different ore
2. allow specifying the ore block instead of oredict name only, sometime the oredict tag will not be enough (like harder ore mod, it has ore blocks with 15 meta value under the same oredict name)

**Comment by zmaster587** [comment]
1. ties into #300 and can probably be implemented in the same patch using the method described there.
2. I could do that however there really should not be a need to as an oredict name is assigned to a certain block and meta (I.E where modOre has block id 56, 56:0 can (and should unless actually compatible) have a different tag than 56:1).  LibVulpes takes advantage of this.

For harder Ores in particualr I do not believe you're actually supposed to be able to pick up the ore block, rather I think you're supposed to only get the chunks which you should be able to use with the existing config with the ore dict name "rawOreChunkIron" for iron and "rawOreChunkGold" for gold, etc. 

Given that, I could see some merit in having blocks/items and will implement it when I get a chance.

**Comment by zmaster587** [comment]
Got a partial build working in the alpha 1.10 release

**Comment by zmaster587** [comment]
Implemented in a1d5cef5e7c1431c98c382decfc2d5beb09e14e9 and finallized in 7ce95c6037ee198709f7bf19ee48a58aca882f24
Items are added by block/item and meta and amount in the new system
