### ISSUE TITLE
CTD interacting with RFTools powercell

### ISSUE THREAD

**Issue by xenoflot** [zmaster587/AdvancedRocketry#352]
https://gist.github.com/xenoflot/16ed83d032b21d2a6c50525cd3983119

Player on the server had switched to SSP to test the powercell linking and CTD.
I don't know the specifics of what he did, but I expect it wasn't much more than spawning in a generator and some powercells. Please let me know if the crashlog doesn't have enough information and I'll do some testing to narrow it down.

I first reported this to McJty and he advised: "It is trying to send RF into the powercells on client side!"

advancedrocketry-1.10.2-1.0.6
compatlayer-1.10-0.1.7
mcjtylib-1.1x-2.3.2
rftools-1.1x-5.81
libvulpes-1.10.2-0.1.13-universal

Cheers!

**Comment by zmaster587** [comment]
Looks like I missed an isRemote check.  Will fix when I get to my computer.

**Comment by xenoflot** [comment]
Thanks for the quick reply! Much appreciated.
