### ISSUE TITLE
Pressing Scan in the Rocket Assembling Machine Stops World Rendering [Optifine]

### ISSUE THREAD

**Issue by Zundrel** [zmaster587/AdvancedRocketry#354]
Hello :D 

Info:
Advanced Rocketry 1.0.7
Optifine HD_U_D6

Whenever I press Scan inside of the Rocket Assembling Machine with Optifine the world stops rendering while the block is in view. I can verify that it doesn't just happen to me, as a friend of mine also has the same issue. 

I also wasn't sure whether or not to direct the issue to you or to Optifine, so I just posted the issue here. If you have any reason to suspect that it's his fault however, I'll move the issue over to his Issue Tracker.

If you need any more information, feel free to ask.

**Comment by zmaster587** [comment]
does this occur without optifine?

**Comment by Zundrel** [comment]
No, it does not occur without Optifine installed.

**Comment by zmaster587** [comment]
What chunk loading setting are you using  (I think thats the right name)
should have the options default, smooth, and multicore.  Does it occur with
all of these or just some?

**Comment by Zundrel** [comment]
To my knowledge that option was removed from the mod recently. I can't find it anywhere, but I can find it in 1.7.10. This seems to only occur in 1.10.2.

**Comment by zmaster587** [comment]
Alright, I'll take a look at it and see if I can diagnose it further.  If
possible and if you have time  if you can find a particular setting in
optifine that does it it would be very helpful.

**Comment by Zundrel** [comment]
I just did actually. With the Fast Render option turned on however the I see things mostly properly, but there's an orange transparent filter over everything if Mipmap Settings set to 4. If I set Mipmap to 0 with Fast Render on however, I see everything almost perfectly. It only seems to darken most GUIs on the screen.

**Comment by Tkdmaster** [comment]
I'd like to chime in on this, as turning Fast render on didn't fix it for me.

this is the effect: http://i.imgur.com/oxN22RT.jpg

Mipmaps were also off as well.

**Comment by NicMoore88** [comment]
I'd like to confirm this as well.  I have optifine installed and get this when pressing Scan or Build.  Managing to break the block makes things normal again.  "Fast Render" on does just as @Zundrel said and puts sort of an overlay on everything.  
Another person on my server who does NOT have optifine, also has this issue.  I am testing now to see if removing Optifine from my install fixes it.

**Comment by LordSkittles** [comment]
I would like to chime in my own two cents, I have an NVIDIA GTX 1060 and in the Age of Engineering pack the entire world isn't rendering after scanning, I do not have Optifine installed but I do have Better FPS installed.

**Comment by zmaster587** [comment]
BetterFPS is also known to cause similar issues.

**Comment by Cxndolence** [comment]
Issue still occurs on the latest verison of OptiFine for 1.10.2, however it can be fixed by making sure that the "fog" option in details is set to either fast or fancy. Having it off causes the screen to turn blue or have an overlay on fast render (like previously mentioned).

**Comment by Hamvich** [comment]
Hi! I found what the problem might be, When building my rockets with the scan i was just playing around, I found that when the scanner thing that comes down is in view it turns things to turn white and not be able to see or just obscure your view. When the scanner thing will dissaper when your screen is not looking at it.
so when the scanner thing is in view it breaks the game. hope that helps

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
