### ISSUE TITLE
Ring Seal to allow cables to connect between pressurized and unpressurized zones

### ISSUE THREAD

**Issue by zmaster587** [zmaster587/AdvancedRocketry#357]
Ring Seal to allow cables to connect between pressurized and unpressurized zones.
Bascially would allow a non sealable block in the center but would make the O2 system treat it as sealed for the purposes of passing fluids/energy/items into/out of bases and stations

```
x = seal block
c = cable
Front:
xxx
xcx
xxx
```

**Comment by Xakorik** [comment]
I know GalactiCraft does something similar where there is a version of it's pipes, but as a full block to keep a room pressurized but allow the pipes to go through the walls.

**Comment by zmaster587** [comment]
GC's only works on a limited set of pipes though doesn't it?

**Comment by mallrat208** [comment]
They have specific full block variants of their gas conduit cables, that's it.  It doesn't work with anything else really as it's only for it's own cables.

**Comment by zmaster587** [comment]
TODO: make O2 ring have fake "O2 source" in the center.  Should make it work with O2 System merging

**Comment by zmaster587** [comment]
implemented in ff1fc8ec38f3022b77468faee702e301dab2495b and 5ec38ef902baca18b9b8e79e5f4b5a79014f6119
