### ISSUE TITLE
Microwave Reciever loses its beam of light and animation when you leave it alone

### ISSUE THREAD

**Issue by mrgreaper** [zmaster587/AdvancedRocketry#361]
Chunk loaded, but if you go away and come back the beam is gone..... it still works so very minor issue

**Comment by zmaster587** [comment]
Sounds like client isn't being notified that the machine is running, will investigate.  If this were the case I would assume opening the machine's UI would cause the beam to reappear.

**Comment by mrgreaper** [comment]
I'm pretty sure I had to turn the machine off and on via the switch, but I'll try again and confirm once home (it's update day so it will be the latest version :))
