### ISSUE TITLE
enhancement suggestion - ore lists for mining

### ISSUE THREAD

**Issue by mrgreaper** [zmaster587/AdvancedRocketry#362]
make the ore extraction for the miner and the fluid one for gas mining blacklistable instead of whitelistable (via a toggle) so you can say mine all ore* blocks that are not on the is list, mine all fluids that are not on this list * 
or add a command that fills the white list with blocks/fluids present (like i guess /dumpregistry but putting the fluids in the fluid section etc

**Comment by zmaster587** [comment]
Added a toggle in the config to switch between blacklist and whitelist for geodes, asteriod mining missions, and the orbital laser.
