### ISSUE TITLE
Rendering bug with entities

### ISSUE THREAD

**Issue by mrgreaper** [zmaster587/AdvancedRocketry#363]
My faithful crew http://imgur.com/3R6AUdl (was using pidgeons but i heard one talking about a coo)

vanished when i left the chunk for a bit 

http://imgur.com/rXIoOYv

They are however there, i hear them clucking, wailer sees them and they still lay eggs (slightly different from the enterprise crew yes) 

one of my crew has remained not invisible 

using the net from the chicken mod i was able to pick them up and replace them

These are not the first entities to vanish from my ship either, some mca (minecraft comes alive) villagers were in my prison (guest accommodation) and vanished... i put that down to a mca bug, now i wonder if they were not just invisible (the rooms have since been open to vacuum, which does not effect the chickens as when they are in the block they cant suffocate, but villagers need air) 

(ps sorry for the multiple bug reports)

edit..
the chickens completly vanished this time, the one that didnt go invisible last time is still there and visible (he is in the same room but a different chunk)

**Comment by zmaster587** [comment]
Like I had said on the curse page, the stations are just another dimension and there's no special world handling behind it other than the skybox and a tag keeping track of the dimension's properties and custom chunk gen.  The atmosphere handling with a tick handler and only checks if the dimension has air or not before applying damage on the server.

See if the same issue occurs with vanilla entities maybe?  Maybe try spawning some chickens in the same room and see if the vanilla chickens and the non-vanilla chicken both vanish.?

**Comment by mrgreaper** [comment]
Hmmm, I shall attempt some tests after work, most of the players on the server have said chickens and none have gone awol except those on the ship....that ofcourse does not mean advanced rocketry is to blame, it could be a chunk error and that can be in any world (time to set test chickens in each chunk of my ship lol) just this is thefirsttimeits been noted

**Comment by mrgreaper** [comment]
After extensive tests i was able to duplicate this bug in overworld, 100% sure this is not an Advanced rocketry bug (sorry chap)
