### ISSUE TITLE
Custom recipe time/power settings are handled wrong.

### ISSUE THREAD

**Issue by GazbonicAcid** [zmaster587/AdvancedRocketry#365]
For the default Cutting Machine recipes...
Circuit stuff 7 seconds slash 140 ticks,
and 200 rf per tick.
Logs 2 seconds slash 40 ticks,
and 20 rf per tick.
But when I set the [CuttingMachine.xml to this](https://hastebin.com/rololesixo.js),
The time it takes is halved and the power it takes is doubled from what I set it.
In order to get an identical result I have to set the [CuttingMachine.xml to this](https://hastebin.com/irerukudex.js).
P.S. The defult recipes for the Cutting Machine don't include Dark Oak, nor AR's alien trees.

**Comment by zmaster587** [comment]
Your second config is consistant with the default values.  Although I halve measured time being halfed and power being doubled for everything.  This is leading me to beleive it's a much deeper issue than loading configs.  It  seems more like the machine is ticking twice or something.  So I'll look into that.

On the subject of the dark oak and alien trees, I'll add dark oak for next build, alien trees do not yet have a plank form so I cannot really add that as of yet.  When I get around to actually adding a few new trees and woods I'll probably circle back to that though.

**Comment by zmaster587** [comment]
Confirmed, both TileMultiblockMachine and TileMultiPowerConsumer are having their update method called for each machine resulting in double ticking.

**Comment by GazbonicAcid** [comment]
I can't wait until this bug fix is released...on curse.
I look forward to it.
