### ISSUE TITLE
Crash when viewing Orbital Laser Drill Entity

### ISSUE THREAD

**Issue by mallrat208** [zmaster587/AdvancedRocketry#366]
Advanced Rocketry version 1.10.2-1.0.7
LibVuples version 1.10.2-0.1.13

Crash Report: https://gist.github.com/mallrat208/b6c54c24f8105dc067e51b38befa80e2

I've been playing around in creative with the Laser Drill and turned on the ability for it to actually drill the planet below which works as expected. I decided to 'see' it in action and left my station Chunkloaded using chickenchunks. When I got within range of the drilling area I experienced a Client Crash in related to the laserNode entity.

**Comment by zmaster587** [comment]
Looks like crash trying to render the shadow/fire of the entity.  Investigating

**Comment by zmaster587** [comment]
I did not figure out the exact cause, however because the laser itself should never be on fire or have a shadow I'm just gonna nuke the call to that method so it _should_ prevent this issue from occuring again anyway.
