### ISSUE TITLE
[Suggestion] Command to reload recipes ingame

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#367]
So it's no longer necessary to restart the game in order to find out if the recipe is working

**Comment by GazbonicAcid** [comment]
I definitely need this too.

**Comment by zmaster587** [comment]
I've got it to the point where the recipe actually works ingame, but have yet to figure out how to actually update JEI

**Comment by TheGuyRunningSouth** [comment]
Iirc MineTweaker/CraftTweaker's code is open source and I know that /mt
reload triggers a JEI update. Maybe look and see how they did it in case it
could apply here too?

**Comment by zmaster587** [comment]
I ended up just digging through JEI to find it, ironically it did explicitly mention MineTweaker in the method description.  I'll probably end up doing that for NEI though since I'm backporting to the 1.7 builds.

**Comment by TheGuyRunningSouth** [comment]
Amusingly enough I just did the same thing as was typing up a reply to
share my findings.
