### ISSUE TITLE
[1.10.2] Concurrent Modification Exception using O2 Vent and Threaded Atmo Calc

### ISSUE THREAD

**Issue by mallrat208** [zmaster587/AdvancedRocketry#369]
Advanced Rocketry: 1.10.2-1.0.8
LibVuples: 1.10.2-0.1.14

Crash Log: https://gist.github.com/mallrat208/867e363312618e511fce666d1fb8598c

Note: I had the settings for Atmosphere Calculation set to Threaded Volume Based

I was testing out how air seals work on the moon and ran into this crash shortly after activating the O2 Vent.

Turning the Atmosphere Calculation to  non-threaded Volume Based seems to work as expected.

**Comment by zmaster587** [comment]
This definatly looks like a concurrency issue, if i had to take a guess I think it's that while the game was checking for torches to put out it tried to create a new atmosphere from the same source causing a CME.. Investigating
