### ISSUE TITLE
[1.10.2] Solar Generators work below other Solar Generators

### ISSUE THREAD

**Issue by mallrat208** [zmaster587/AdvancedRocketry#370]
Advanced Rocketry: 1.10.2-1.0.8
LibVuples: 1.10.2-0.1.14

First off, a little screenshot to show what I'm talking about.

![Solar Generator in a Quartz Block Room](https://cloud.githubusercontent.com/assets/5694243/22362217/14ad2f36-e42f-11e6-9833-a860bd30dafb.jpg)

This feels like it's an unintended behavior. Since the Solar Generator does not work under the Blocks of Quartz there is little to no reason they should work below the Solar Generator itself. It kind of feels like the Solar Generator is being treated as a Transparent block.

**Comment by zmaster587** [comment]
for some reason the block for the solar panel (which is the same block for most othermachines) was transparent, It may have been an early hack to make the observatory not render dark, but should be fixed now.
