### ISSUE TITLE
[Feature] Rocket Unloader and Loader

### ISSUE THREAD

**Issue by Liinche** [zmaster587/AdvancedRocketry#374]
I try to automate mining satellite but i hurt a problem , the rocket unloader do this job to well , i can auto insert an asteroid chip in my rocket but the unloader pick it before the rocket launch. 
My sugesstion is to make a whitelist/blacklist systeme for the different hatch/loader (fluid and item).

**Comment by zmaster587** [comment]
Hmm, yes, very yes.  I like this idea.

**Comment by Liinche** [comment]
Still in loader unloader feature we can't shut down an unloader from doing his job.
My sugesstion is to make 2 redstone control : 
-the input one for turning it OFF or ON 
-the output one for his actual job BUT the output signal should be given by a comparator pointing into it (self-feeding redstone signal problem otherwise)

**Comment by Feafroth** [comment]
Satellites also unloads from Satellie Bay by Unloader before rocket ic launched
