### ISSUE TITLE
[Dupe Bug] Rocket Loader

### ISSUE THREAD

**Issue by Liinche** [zmaster587/AdvancedRocketry#375]
If we try to load any item in the rocket while the rocket is still full the item in the first slot of the rocket will be duplicate by the number of item we try to insert.

**Comment by zmaster587** [comment]
I don't quite follow.  I did try filling a rocket up with stone and putting stone into the rocket loader.   I did notice some odd behavior where the stone disappeared on the client (reopening the loader a few times made it reappear in the loader and attempting to load more stone into the load just swapped the invisible stone stacks with the one you try to drag in) but the total number of items in the world remained the same.

**Comment by Liinche** [comment]
you seem to fix something so i gonna tell you if its fix in the next update or not :)

**Comment by zmaster587** [comment]
Have you got a chance to test the recent builds?

**Comment by Liinche** [comment]
gonna try this evening i keep you up to date

**Comment by Liinche** [comment]
i have test it the same ways as before and the dupe is still here
To recap i put in each slot of my rocket 1 stone and in the first slot of the first storage says a diamond block when the loader try to insert an item thait is not the stone or the diamond block this item is converted to a diamond block if its not clear enough i gonna make a video ^^

**Comment by zmaster587** [comment]
Alright, Thanks!  I've been able to replicate it now.
