### ISSUE TITLE
Crash with Perfect Spawn [1.10.2]

### ISSUE THREAD

**Issue by parcel31u** [zmaster587/AdvancedRocketry#377]
http://pastebin.com/pQN1tysZ

**Comment by zmaster587** [comment]
Looks like some ASM transform perfectspawn is doing, will investigate when I get time

**Comment by zmaster587** [comment]
Is this on a client or server?

**Comment by zmaster587** [comment]
Seems to be something involving loading the skyrenderer for some reason

**Comment by zmaster587** [comment]
I do not know what exactly went wrong, but this patch seems to fix it.  Due to the fact the error occurs during asm transform I suspect it's some optimization the compiler is doing.
