### ISSUE TITLE
Unable to respawn on planets [1.10.2]

### ISSUE THREAD

**Issue by parcel31u** [zmaster587/AdvancedRocketry#378]
Unable to respawn on planets with beds, /spawnpoint, or /worldspawn. All respawns are in the overworld. The config is set to B:allowPlanetRespawn=true

**Comment by zmaster587** [comment]
did you sleep in the beds on those planets and are the beds in a breathable atmosphere?

**Comment by parcel31u** [comment]
Yes.
<atmosphereDensity>100</atmosphereDensity>
<gravitationalMultiplier>115</gravitationalMultiplier>

For the planet

**Comment by zmaster587** [comment]
There was some bad logic in the check to see if a planet was valid, was comparing block and blockstate
