### ISSUE TITLE
GUI Moveable?

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#379]
Hello!

Is there a possibility of allowing the GUI elements of the mod (specifically the Space Suit) to be movable? I'm working on a modpack that has a GUI in the same location and would love to be able to move these around to make sure everything has proper room: http://i.imgur.com/BpexXs7.jpg

Advanced Rocketry: 1.0.8
Lib Vulpes: 0.1.14
Forge: 2221
MC: 1.10.2

Thank you for your consideration :)

**Comment by zmaster587** [comment]
I'll look into doing that tonight

**Comment by zmaster587** [comment]
Will a draggable system like the following work with the ability to lock the UI in place via config?

UI can be dragged with middle click and location is saved in the AR config under a client catagory.

![tut](https://cloud.githubusercontent.com/assets/3536685/22534602/13456634-e8c3-11e6-86a5-e6e53e513772.gif)

**Comment by zmaster587** [comment]
Gui is locked by default in config, there's an option in the client category to unlock the UI, with the UI unlocked you can click and drag with the middle mouse button if you have the chat window open or something of that nature.  The position is saved to config when the world is exitted via quit.  You could also tweak the config values by hand, but that's a but harder.

The UIs should be anchored to the nearest edge or center, whichever is closest.  So resizing should work ok, but if you do move the UIs make sure to test to see if it scales with the window properly in case something got missed.

**Comment by Darkosto** [comment]
That looks great! Thank you for your help!

**Comment by mcdodge34** [comment]
Sorry to open this one, but it doesn't seem to work for the armor gui on latest 1.2.2 version for MC 1.10.2, I tried with the chat open or the inventory, and none seems to allow me to move the armor gui which is way too big and bulky like the atmospheric part, I have problems with my eyes so I have to play with the large gui option in video settings, when I switch it to normal, the GUI of your mod seems ok, would appreciate an option to scale it down when I use the large gui in Minecraft video settings,

**Comment by Jezebel77** [comment]
Hi, sorry to open this after so long.
I was wondering if you could add a toggle option for the armour GUI? or perhaps a scaling option, it is still quite massive on my screen and I've looked through the config but I can't seem to find an option to do either. Thank you so much.

**Comment by milkev** [comment]
this config doesnt seem to be here on 1.12.2, im on version [256](https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry/files/3487193l)
there also doesnt seem to be config integration with mod menu?

**Comment by voidsong-dragonfly** [comment]
GUI movement broke because of one of our hooks breaking. GUI is no longer movable. Integration with the config menu in-game was a fleeting feature and rife with problems. Don't use it, use the file.
