### ISSUE TITLE
Mining Gas Giants for Special Liquids.

### ISSUE THREAD

**Issue by Divineaspect** [zmaster587/AdvancedRocketry#387]
Could we get a config for gas giants to be able to have other liquids which can be mined from them?

**Comment by zmaster587** [comment]
I thought I implemented that a while back.  There should be a "harvestableGasses" entry in the config where you can specify a list of fluids by their fluid name.  If i remember correctly it was reported that the client and server must have the same settings for that particular entry or weird things happen.

**Comment by Divineaspect** [comment]
I may be missing it if it's not mentioned in the advanced planets configuration guide

**Comment by mallrat208** [comment]
There's a config entry where you can specify gasses, but the planetDef.xml definitely doesn't mention you being able to specify any given gas giant's composition.

**Comment by zmaster587** [comment]
Gas giant's do not have their own list of gasses as of yet so..

**Comment by Xakorik** [comment]
I think being able to set certain gas giants to specific liquids would be nice.
