### ISSUE TITLE
MAJOR: Astrobody Data processor

### ISSUE THREAD

**Issue by metnavman** [zmaster587/AdvancedRocketry#388]
Feeding the 3 types of data to the processor and then starting research on an Asteroid chip causes the total amount of stored data for the 3 types to RESET to the last state it was at whenever closing out of the GUI.

- Start with 500 of each data
- Begin research on Asteroid
- Asteroid chip begins to fill 0/2000, 1/2000, 2/2000, etc
- CLOSE GUI before the three data type reach 0 in the processor. Started with 500, closed at like 200.
- Asteroid chip will show 300/2000, as per the spent data.
- Upon RE-OPENING the processor GUI, the 3 data type storages will have reset to 500, while the Asteroid chip continues earning points. In essence, free data. This is repeatable infinitely.

**Comment by metnavman** [comment]
Oh I can confirm it, lol. I've deleted all my satellites  and turned my observatory off. I've had max data since reporting this and have mapped at least 6 asteroids. Still have the data, isn't going down.

**Comment by zmaster587** [comment]
Unconfirmed just means I've not yet gotten around to testing it myself

**Comment by metnavman** [comment]
Roger that. Let me know if you need a mod list or anything else I can provide to assist as needed!

**Comment by zmaster587** [comment]
Turns out I just forgot to decrement after fixing the ABDP reseting upon being out of power or whatever.  Probably from the fix from #331
