### ISSUE TITLE
[1.10.2] Crash when placing a fluid pipe

### ISSUE THREAD

**Issue by feldim2425** [zmaster587/AdvancedRocketry#389]
I placed a fluid pipe between 3 other pipes one was connected to the inputs of 2 Electrolyzer the second one was also connected to the inputs of 2 Electrolyzer and the third pipe was connected to two tanks filled with Water.

The World is unplayable since I placed that pipe.

Crash Log:  https://pastebin.com/jr4hprub

**Comment by dmodoomsirius** [comment]
Have you tried removing the erroring pipe using mcedit?

**Comment by feldim2425** [comment]
No. I will try but MCEdit doesn't start on my computer. Don't know why.

**Comment by feldim2425** [comment]
I can't load the World file with mcedit. It just shows a blank grid.

**Comment by feldim2425** [comment]
Ok. I created a second world and reproduced that bug. If I delete the connection to the Electrolyzer it won't crash anymore. 

But I know more about that. The pipe on the Tanks was redstone powered. The game crashes if you place a fluid pipe between a pipe at the input of the Electrolyzer and a redstone powered pipe on the tank and the tank has water in it. 

![](https://i.imgur.com/0J4r6MD.png)
