### ISSUE TITLE
Satellite builder 

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#39]
Right click the satellite builder does not do anything, no gui shows up
is that normal right now?

**Comment by Towsty** [comment]
I believe the builder is a multi block, you need a machine block below it

**Comment by zmaster587** [comment]
It does require a power block directly underneath it currently, still trying to decide whether to make it an actual multiblock or standalone.

**Comment by Towsty** [comment]
Something that assembles satellites seems like it should be a large multi
block structure

**Comment by zmaster587** [comment]
Yeah, it does, was also thinking of requiring it to either be built in a vacuum chamber, or have a vacuum chamber as part of the machine itself.

**Comment by Towsty** [comment]
Definitely sounds cool with a vacuum chamber
