### ISSUE TITLE
Determine front end of station / Select docking pad (suggestion) (1.7.10)

### ISSUE THREAD

**Issue by rkane31174** [zmaster587/AdvancedRocketry#390]
After testing, it seems the mod decides the north end of the station is the front with respect to rotation and warping. For large multi-module stations, I think it would be helpful if the player could decide which end was the front. For instance: a block with an arrow on it that could be rotated with a wrench (or other 'modifying' tool).

Additionally, it might be helpful if docking pads could be given names like station docking ports. When flying to a station, a player would be able to choose which pad to land on. The current system of pad linking works well enough for cargo rockets and other unmanned vessels, but not as well for player transport.

**Comment by zmaster587** [comment]
The direction the most recently placed warp controller is placed should determine the direction of the ship.

Named docking pads would be nice, upon reaching orbit a UI could come up and allow for the selection of the destination pad.
