### ISSUE TITLE
[1.7.10] Crash on "reload"

### ISSUE THREAD

**Issue by Kahra** [zmaster587/AdvancedRocketry#391]
Hi,
I am making test for a modpack, and I just notice that : 
I can launch any world without problem in soloplayer (an empty 'new world' tbh), but when I get back to the Minecraft Menu and try to load whatever world (the same or another), I get this crash : 
[crash-2017-02-10_18.06.49-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/767349/crash-2017-02-10_18.06.49-server.txt)

There are some other mod that may conflict about dimension, so here is an AntiIDConflict'report for dimension (I notice some dimension like Gallacticraft'one didn't get register in that report)
[AllIDs.txt](https://github.com/zmaster587/AdvancedRocketry/files/767366/AllIDs.txt)

(sorry for bad english btw)

**Comment by zmaster587** [comment]
Unfortunately the crash report doesn't say much other than the dimension
manager got screwed up somehow as far as I can tell.  Would it be possible
to provide the fml-client-latest log so I can trace dimension loads and
unloads?

**Comment by Kahra** [comment]
Sure, It should be this one : 

[fml-client-2.txt](https://github.com/zmaster587/AdvancedRocketry/files/767461/fml-client-2.txt)
So much line !

**Comment by zmaster587** [comment]
Not seeing any exceptions or anything in there on world unload...
Does this also occur without AR?

**Comment by Kahra** [comment]
Nope, I have retested without advanced rocketery 1.0.8 and LibVulpes 0.1.14 and this crash never appear. This more the fact there are a lot of mod installed is why I was thinking of a conflict.

**Comment by zmaster587** [comment]
Do you have a copy of the mods and config files I'd be able to mess around
with or would you be willing to try to narrow it down to an interaction
between a reasonable number of mods ( less than 10)?

**Comment by Kahra** [comment]
I made some investigation to reduce the number of mod and still have the crash, and good news, I've found the guilty.
The crash occurs when AR and "[Warp Drive](https://mods.curse.com/mc-mods/minecraft/233565-warpdrive)" are both present. (Warp Drive version : 1.3.30)

**Comment by zmaster587** [comment]
Atfer some testing I suspect warp drive's other dimensions are conflicting with AR's.  I found that changing the hyperspace_provider_id and space_provider_id ids such that they do not overlap with AR's planet IDs solved the issue.  (I used -4 and -5 respectivly for warpdrive's new IDs)

**Comment by Kahra** [comment]
No more crash on my side with your change. Thanks a lot for your time (and your mod !)

So, does AR dimension (except the spaceStation) are hardcoded ? Because I don't see anything on id= 14 or 15 (the former value in warpdrive). 
I'm just curious to know for the next dimension modification that I could do.

**Comment by zmaster587** [comment]
No problem!

None of the AR dimensions are exactly hardcoded.  Because AR has to be able to generate any number of planets at runtime, essentially what it does it start at the "minDimension" there and for every new planet just adds one to the dimension number.  Unless ofc you use the advanced planet config and set the number of dimensions to generate to 0 and set all the dimids yourself.  But AR by default will generate more than 15 planets and if you start at 2, theres good chance you'll have AR generate a DIM15.

I have added some code to try to avoid generating dimensions on top of already existing ones but if the mod loads after AR that code won't help at all.

**Comment by Kahra** [comment]
I've got it, thanks
