### ISSUE TITLE
Server crash using the orbital mining drill

### ISSUE THREAD

**Issue by Saereth** [zmaster587/AdvancedRocketry#396]
Advanced rocketry vs 1.0.9 for mc 1.10.2 
Server crashed upon activating the orbital mining drill, crashlog:

https://hastebin.com/jihaqameku.pas

currently only running a handful of mods besides yours, less than 10.

The config is set to mine planets = false;

**Comment by zmaster587** [comment]
Looks like no ores are in the list that dermines what ores the drill is allowed to mine.  In the AR config what are the values of "laserDrillOres" and "laserDrillOres_blacklist"?

**Comment by Zundrel** [comment]
I can confirm this crash, and my laserDrillOres is not empty and laserDrillOres_blacklist is set to false: http://puu.sh/u5h7g/c7e1e7fbf1.txt

**Comment by zmaster587** [comment]
Huh... that's really odd, I didn't change the anything with the drill between 1.0.8 and 1.0.9, will take a look though

**Comment by Saereth** [comment]
my settings are:
    # List of oredictionary names of ores allowed to be mined by the laser drill if surface drilling is disabled
    S:laserDrillOres <
        oreIron
        oreGold
        oreCopper
        oreTin
        oreRedstone
        oreDiamond
     >

    # True if the ores in laserDrillOres should be a blacklist, false for whitelist
    B:laserDrillOres_blacklist=false


Pretty much a brandnew install of advanced rocketry, havent changed any configs beyond default.
