### ISSUE TITLE
[Suggestion] Allow customization of default machine recipes via the recipe tweaking system

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#399]
In case one would like to tweak the processing time, output, or removal of default machine recipes in order to favorite other custom processes

**Comment by GazbonicAcid** [comment]
There's already a way to do this.
Set "useDefaults" in the custom recipe xml to false,
and then add the default recipes back in with your tweaks.
Still waiting on a way of exporting the default recipe's for easier tweaking via the custom recipe xml though.

**Comment by zmaster587** [comment]
Probably going to end up resolving this by just having AR dump XML for the machine recipes if the XML files is non existant.  Recipes with the same input and output would be overridden with the new time/power requirements.  If you wanted full control over the recipes then all you'd need to do is add/remove/change the recipes dumped and set the register default recipes to false.

**Comment by zmaster587** [comment]
In the next alpha release if the XML for the machine is not in the config folder it will write an XML file containing all the recipes for the given machine.  From there you can set useDefault to false and tweak them however you like.

**Comment by wormzjl** [comment]
nice
