### ISSUE TITLE
Question about Satellites and Other planets/Moons

### ISSUE THREAD

**Issue by HyperMan19680** [zmaster587/AdvancedRocketry#4]
Is it currently possible to launch a satellite from the Overworld towards another planet for it to scan? If so, how?

**Comment by zmaster587** [comment]
It is not currently possible, however it is a planned feature, and will be required for probes.  As of right now though, satellites can collect data on any planet regardless of the planet it is in orbit around.

**Comment by HyperMan19680** [comment]
Okay, my satellite is over the Overworld, and I want to scan Luna. How would I go about doing that?

**Comment by zmaster587** [comment]
In the planet Analyser machine there is a Planet Selector, right click that, find Earth and double-click it, you should zoom in and see luna off to the right, click luna once then click Select in the top left corner, it will close the interface.  Next click the Planet Analyser itself, the text in the middle should say either "Planet 2", put an unprogrammed Planet Id Chip in the top right slot and click on the gears.  Once it is done processing put it into one of the input hatches in the Planet Analsyer.  Then you can transfer data into the Planet Analyser with the data chips, by toggling the various research options you should start to get research on Luna.

There's also a clip on the tutorial video that explains it a bit if you prefer that.
https://youtu.be/00XS_n6zR14?t=1110

**Comment by HyperMan19680** [comment]
I've done all that, but none of the jars are filling up with data on this. Like as if it isn't working somehow. Am I doing something wrong?

Machine is set up, has power, and I have a Luna planet chip in the left Input slot.

**Comment by HyperMan19680** [comment]
Never mind. I figured out I have to provide the data from elsewhere.
