### ISSUE TITLE
x-ray

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#40]
![image](https://cloud.githubusercontent.com/assets/2989009/11763866/5da68f60-a124-11e5-87d8-8ab234afa95d.png)
![image](https://cloud.githubusercontent.com/assets/2989009/11763867/6c4de4be-a124-11e5-8fdd-5a29486f9219.png)

:P

**Comment by zmaster587** [comment]
Will patch for next update
