### ISSUE TITLE
Little bug while showing the manually added recipe in NEI with chemical reactor

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#400]
![image](https://cloud.githubusercontent.com/assets/2989009/23071941/523a4840-f530-11e6-8e42-883cc5afc44a.png)
I've used a fluid input, but it shows as a bucket
Things works normally, it's just a graphical bug imo

Not like the default one with rocket fuel
![image](https://cloud.githubusercontent.com/assets/2989009/23071988/7457698a-f530-11e6-8632-cfd26919b79a.png)

**Comment by zmaster587** [comment]
What does the XML for that recipe look like and what mod(s) are those items from?

**Comment by wormzjl** [comment]
This is the script I used, sees that it just chooses a random fluid container

	<Recipe timeRequired="100" power="128">
		<input>
			<fluidStack>sulfuricacid 1000</fluidStack>
			<itemStack>capptfc:purifiedoredust 1 0</itemStack>
        </input>
		<output>
			<fluidStack>slurrynativecopper 1000</fluidStack>
			<itemStack>techreborn:smallDust 2 5</itemStack>
		</output>
	</Recipe>

**Comment by zmaster587** [comment]
Do you know which mod the bucket container is being pulled from?

**Comment by wormzjl** [comment]
terrafirmacraft
