### ISSUE TITLE
Rendering problem on machines

### ISSUE THREAD

**Issue by Thysium** [zmaster587/AdvancedRocketry#401]
Possible problem with immersive engineering?

The holoprojector affects the paddle wheel of immersive engineering, rendering some advanced rocketry machines are black except the sides and the back of the machines.

https://image.noelshack.com/fichiers/2017/07/1487359568-2017-02-17-17-02-51.png
https://image.noelshack.com/fichiers/2017/07/1487359555-2017-02-17-18-16-04.png

**Comment by zmaster587** [comment]
Looks like I may be missing some cleanup in the rendering code for the hologram blocks.

**Comment by zmaster587** [comment]
Is this with the 1.7.10 build or 1.10.2 build of Minecraft?

**Comment by Thysium** [comment]
Minecraft 1.10.2, I still have the same problem and my friend also with Advanced Rocketry v1.0.11 and LibVulpes v0.1.16.

**Comment by Thysium** [comment]
Hello, a recent update of the mod storage drawers solves the problem. Immersive Engineering and Advanced Rocketry are clean. :)
