### ISSUE TITLE
Orbital Mining Drill throwing errors in the server log

### ISSUE THREAD

**Issue by Saereth** [zmaster587/AdvancedRocketry#402]
I downloaded the latest version and it fixed our server crash but when changing corrdinates in the UI
it throws some server errors. The drill does work now though!

Here's a log of the errors:
https://hastebin.com/qaxirakuka.css

update: Looks like part of this is the lens, It doesn't get written so the lens gets deleted every server restart.

**Comment by zmaster587** [comment]
Do you have it set to spiral mode?

**Comment by Saereth** [comment]
Yes I did

**Comment by zmaster587** [comment]
That makes sense then, should be fixed in next update
