### ISSUE TITLE
Game crash with underwater utilities

### ISSUE THREAD

**Issue by Liiw** [zmaster587/AdvancedRocketry#404]
Hello, 

I have experienced a game crash while having Advanced Rocketry and Underwater Utilities mods installed. While equipping UU-s Scuba Breather in SP, the game crashed (please see crash log attached)

[crash-2017-02-17_23.39.43-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/784804/crash-2017-02-17_23.39.43-server.txt)

I have contacted the author of Underwater Utilities who took a look at the crash log and said:

> Advanced Rocketry is passing null for the capability parameter in hasCapability.

**Comment by zmaster587** [comment]
I was assuming direction for armor would not matter but apparently in some cases it doesn.  Will patch next build

**Comment by Liiw** [comment]
Thank you for your prompt reply!

**Comment by zmaster587** [comment]
It helps when the capability is actually registered
