### ISSUE TITLE
Precision Assembly Machine only accepts 4 inputs, but Atmosphere Analyzer requires 5

### ISSUE THREAD

**Issue by sandalle** [zmaster587/AdvancedRocketry#405]
The Precision Assembly Machine has a single Input Hatch, which allows for four inputs, but the Atmosphere Analyzer requires five crafting components:

1. Small Battery

1.  Advanced Circuit

1. Tin Plate

1. Basic Lens

1. User Interface

So I cannot craft the Atmosphere Analyzer, even when manually adding the crafting components to the Input Hatch, much less through automation (e.g. Crafter from [Refined Storage](https://minecraft.curseforge.com/projects/refined-storage)) .

Minecraft: 1.10.2
Forge Mod Loader: 1.10.2-12.18.3.2221
Advanced Rocketry: 1.10.2-1.0.10
LibVulpes: 1.10.2-0.1.15
Modpack: [NST Unofficial - Frostburn](https://minecraft.curseforge.com/projects/nst-unofficial-frostburn)

**Comment by zmaster587** [comment]
I think that particular recipe requires the Precision Assembly Machine having at 2 input hatches.  The machine will treat the 2 input hatches like a total of 8 input slots.

**Comment by Miroku999** [comment]
You are correct.  I had the same problem, and added the second input hatch.  It worked like a charm!

**Comment by zmaster587** [comment]
I need to get around to writint docs for the machines... will definitely
need to remember to mention this in the docs

**Comment by sandalle** [comment]
Adding a second Input Hatch lets me manually create the Atmosphere Analyzer; I forgot that the Holo-Projector showed that multiple Input Hatches _could_ be used, but I only built with one. ;)

My automation will need to be re-worked a bit as multiple Input Hatches do not make the internal buffer larger (e.g. for a single Refined Storage Crafter to point to a single Input Hatch and still insert five items), so I'll need to put some piping in there and make sure multiple crafting jobs don't mess up the buffer chests/pipes.
