### ISSUE TITLE
Duplication bug with the stepper

### ISSUE THREAD

**Issue by Thysium** [zmaster587/AdvancedRocketry#406]
I accidentally clicked on the stepper (Precision Assembler) with the holoprojector and i discovered a duplication bug.

https://image.noelshack.com/fichiers/2017/07/1487498324-2017-02-18-19-58-30.png
https://image.noelshack.com/fichiers/2017/07/1487498321-2017-02-18-19-58-40.png

**Comment by zmaster587** [comment]
If you break them does it actually drop something or is that a hologram?
