### ISSUE TITLE
Phantom block render crash

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#41]
http://pastebin.com/HaVvnZZD

**Comment by zmaster587** [comment]
What did you do to right before this?

**Comment by wormzjl** [comment]
Placed a schematic, left it there and did some other stuff, then boom

**Comment by zmaster587** [comment]
which schematic?

**Comment by wormzjl** [comment]
rolling machine

**Comment by wormzjl** [comment]
Since it's on a server, could it be some sort of desync bug?
Like when the client think that it's still there but in fact the phantom block has already vanished on the server

**Comment by zmaster587** [comment]
It appears the RanderBlocks.getInstance() is returning  null, trying to find out why

**Comment by zmaster587** [comment]
Are you able to get it to happen again?  I'm not seeing any way this should be possible.

**Comment by wormzjl** [comment]
it's pretty much random, but it occured at least 5-6 times

**Comment by zmaster587** [comment]
ok, will keep trying to replicate

**Comment by zmaster587** [comment]
I still cannot replicate this, does this still occur without fastcraft and the xray mod?

**Comment by wormzjl** [comment]
without xray yeah, and normally fastcraft shouldn't mess with this?
I'll see what I can get without it, but this happens quiet rare

**Comment by zmaster587** [comment]
Tenative fix in 4.0.1 which should be up in about 5 minutes, not sure if it'll work as I cannot find any reason RenderBlocks.getInstance() could ever be null, but it's something.

**Comment by wormzjl** [comment]
http://pastebin.com/pkZMrFP5
got kinda the same crash...

**Comment by zmaster587** [comment]
That isn't the same crash as before even though it does occur in the same file.  Fixed.

**Comment by zmaster587** [comment]
Marked as fixed?
