### ISSUE TITLE
Rod Recipes not correct

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#411]
AdvRocketry 1.0.11
MC 1.10.2
Forge 12.8.3.2221

The Lathe makes rods 1:1 from ingots. Given that the crafting recipe is more efficient and comparing to Immersive Engineering Rods, I'm pretty sure that the Lathe should give 2 rods per ingot. (I have not tested if the Lathe really only gives one rod per ingot, I was just seeing it in JEI). It also makes only one rod per ingot for rods from other mods as AdvRocketry adds the recipes for the rods.

Also the Iron Rod crafting recipe only gives one rod from 3 ingots instead of 4 like the other crafting recipes.

**Comment by zmaster587** [comment]
When I run it I see 1 ingot -> 2 rods (using AR/vanilla ingots) in JEI and have tested with the lathe to verify its correctness.  By any chance are you working with non-AR and non-vanilla ingots?  Does this still occur if "makeMaterialsForOtherMods" is false in the AR config?

Also I've been meaning for fix that issue with the iron ingot -> rod for 3 versions now and keep forgetting...

**Comment by zmaster587** [comment]
Confirmed the 1->1 recipes are a compat issue
