### ISSUE TITLE
[Request] Planet to planet transport.

### ISSUE THREAD

**Issue by Shane371** [zmaster587/AdvancedRocketry#412]
Kind of a back burner thing.  Would like to see a method to automate transporting goods to and from planetary/Galaxy systems. Upgraded railgun or new engines/fuel for rockets. Mostly just want to avoid using ender chest styles of transporting goods to and from dimensions.  I like the idea of it needing fuel, tech level and time to transport stuff around.

**Comment by zmaster587** [comment]
At some point I meant to make it such that if you put a minature warp core on a rocket then it could be automated to go between planets with the landing pads + linker, though it would only be good for cargo and not entity transport.  Some excuse like minature warps cores are too volitile for human use or something.

**Comment by zmaster587** [comment]
Putting warp core on rocket now allows interplanetary transport see fbcb4004b8452f8d56b6c5ccf7c828678b3aa507
