### ISSUE TITLE
Oxygen vents not working in pasted schematic

### ISSUE THREAD

**Issue by Jord5i** [zmaster587/AdvancedRocketry#413]
For the creative part I tend to use schematics/creative mode, which I then use for surivival. I pasted in a starship into a space station world, and had difficulty getting the oxygen vents to work (have them working in other stations/moons). I realized it may have something to do with the pasting of the schematic. I found that when I moved outside the pasted zone, the oxygen vents would work again. 

Is it possible to get the oxygen vents to work in combination with using schematics?

**Comment by zmaster587** [comment]
It may have to do with how and what order schematics place blocks.  Does the vent still fail to work if the redstone to it is switched off and on?

**Comment by Jord5i** [comment]
@zmaster587 
Yes I tried multiple times with toggling redstone, destroying the block and replacing it, adding and removing power supply etc.

**Comment by zmaster587** [comment]
Would you be able to provide a copy of the region containing the pasted schematic? I'm wondering if there's some invisible non-air block stuff going on.
