### ISSUE TITLE
Sneaky Enderman disabled Blast Furnace

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#414]
Funny story: I logged on my server tonight to find out that the Blast Furnace Multiblock wasn't formed anymore. First I was thinking it was a bug, but while trying to fix it by breaking the blocks I saw that it was no bug. A sneaky Enderman teleported in it and placed a Grass Block which unformed the multiblock. I know this isn't really a bug and it is minor because of the unlikelyhood of it happening, but still very annoying given how long the recipes take and if you run it overnight and come back the next day with the crafting being stopped you would be annoyed.

So, could this somehow be prevented? Is there for example a particular reason the center blocks having to be Air or could you make it that it accepts any block? This would probably the easier way, easier than somehow preventing blocks being placed inside after the multiblock has been formed or prevent Enderman teleporting in there or whatever...

Advanced Rocketry 1.0.11
MC 1.10.2
Forge 12.18.3.2239

**Comment by zmaster587** [comment]
I could modify the recipe so the interior is filled with heatproof blocks as well (or at least one extra layer), generally during play after building the machine you have between 8 and 14 blocks left over so it shouldn't cost the player much extra in the way of resources if 9 more blocks were used.

**Comment by davqvist** [comment]
Sure, if you don't mind the Blast Furnace breaking in an update, go ahead. I just thought it would be easier to allow any block in the center instead of having to be air.

**Comment by zmaster587** [comment]
Only other solution I could come up with is to scan for entities or blocks
inside the machine every tick or every few ticks, but that'll add overhead.

**Comment by davqvist** [comment]
Yeah, that seems no good.

**Comment by zmaster587** [comment]
The 1.1.x build of advanced rocketry is going to have some changes to machines anyway that may require most machine to be rebuilt, or at least recompleted.  So I'll just slide the change into the 1.1.x build.
