### ISSUE TITLE
All the planets are gone?

### ISSUE THREAD

**Issue by sharkck** [zmaster587/AdvancedRocketry#415]
I've upgraded from version 1.0.8 to version 1.0.11 and have noticed that there arent any planets to choose in the selection screen.  Even the moon is gone.  I havent been anywhere in space yet as I've been building up resources, etc. and have always been able to see other planets.  Currently, the only one that shows up in the rocket or the planet selector machine is Earth (moons: 0).  

Any suggestions?  I can provide whatever you need.  Currently the server is running on Forge version 2239.

**Comment by sharkck** [comment]
FYI, creating a fresh single-player world shows planets in each solar system.
I've also looked at my Satellite Terminal's and each of them show 'No Link'.  They still have the Satellite ID chips in them.

**Comment by zmaster587** [comment]
There was a bug introduced in 1.0.11 that broke the planets, I released a fix for 1.7.10 and thought I released the 1.10.2 update but i apparently forgot, I'll have a build up in a minute

**Comment by zmaster587** [comment]
Should be up on curse now, just waiting approval.

**Comment by sharkck** [comment]
Thank you!  I'll keep an eye out.

**Comment by sharkck** [comment]
It works!  Thanks again for your prompt response and fix!
