### ISSUE TITLE
java.io.EOFException ?

### ISSUE THREAD

**Issue by DeadSix27** [zmaster587/AdvancedRocketry#416]
Not sure what causes this, I get that error in my logs, my game also won't start, but I am not sure if AdvancedRocketry is the culprit for that, main point is the EOF exception, of which the stacktrace is here:

http://pastebin.com/KiB3wrf5

**Comment by zmaster587** [comment]
I belive it's casued by JEI loading one of the items which in turn tries to load planet information before a file is set to load from.  It doesn't corrupt the state of the game so I have not spent a ton of energy trying to track it down.
