### ISSUE TITLE
No moons or planets

### ISSUE THREAD

**Issue by ilriveril** [zmaster587/AdvancedRocketry#419]
On my MP server, started a fresh modpack with advanced rocketry and when I try to go to the moon there is nothing there.   When I click select destination, there is just the earth and no moon.  When opening the planet selector, all of the solar systems have 0 planets.  Getting this with a fresh server and fresh config.

**Comment by zmaster587** [comment]
Was this with AR version 1.0.11?

**Comment by ilriveril** [comment]
yes.  I just upded to 1.0.12 and seems to be better, except now i'm having issues with a lot of planets showing up as gas planets, including the moon on earth.  I have changed in the config to have the dimensions for the planets to start at number 1000, but I don't know if that is causing it.

**Comment by ilriveril** [comment]
If you want me to test anything let me know.  Also, where is this planet data located?  I'm trying to get this fixed in my modpack so I don't have to start over from scratch.

**Comment by zmaster587** [comment]
Planet data is located in <save location>/advRocketry/temp.Dat. you can
open it with an nbt editor
