### ISSUE TITLE
Could the rocket entity despawn?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#42]
Got some weired observations today while testing the mod on a server
When launching a manned rocket from the overworld to the moon, sometimes the rocket just disappeards upon arrival at the moon dim, but the player motion remains to be sitting.
When the rocket does not dissappear, I always got crushed to ground death no matter how slow I'm moving.
And when goes out of visual range of the rocket and come back, the rocket just dissappears, sometime a relog makes the rocket reappear, but sometimes it does not work, makes the rocket becoming a permanent invisible entity.

Actually I'm using kcauldron as server, so there might be some weird stuff regarding it. But I would like to know if there is anything that could be done on the mod's side

**Comment by zmaster587** [comment]
The entity does not despawn however there is a client/server postion desync when the rocket comes in to land on another dimention, came from trying to avoid huge rubber-banding, going to try to fix the desync in the next update or two

**Comment by zmaster587** [comment]
The rubber banding should finally be fixed
