### ISSUE TITLE
Advanced Rocketry does not like Tile Acceleration

### ISSUE THREAD

**Issue by metnavman** [zmaster587/AdvancedRocketry#425]
I'm betting you've never dealt with it before, which is why this is a thing.

Tile Acceleration breaks all aspects of your mod. Every one of your machines can be affected by them, and it does horrible things to them. I don't know how Torcherinos or the acceleration wand or any of the other items that increase tick rate on a machine works. My experience is with Chromaticraft Tile Accelerators.

* All production blocks are VASTLY broken by it. I can process a stack of just about anything in about 30sec. I can fill a 512 bucket storage with rocket fuel in about a minute. Basically, all of your time gates are broken by them. 

* The Astrobody Data Processor has NO CLUE how to deal with acceleration, lol. It creates Asteroid mining guidance chips in about 30sec, while using no data. Completely breaks the block. I don't know if that's also because of the earlier bug I reported that you fixed with the Data Processor, but yeah. It's bad.

* The Arc Furnace starts double-producing silicon, and produces at an absurd rate. 

I don't know if you want to confer with other mod authors to blacklist your machines from their tile acceleration items, or if you want to add your own code that prevents it from working, but as it stands right now, Chromaticraft tile accelerators (and I'd assume any other mod with a form of tile acceleration) are cheat-mode for Advanced Rocketry.

**Comment by zmaster587** [comment]
Is the ABDP still occuring with AR 1.10 or later?
That being said, tile accelerators are _designed_ to circumvent time gates.  It is also the responsibility of the mod providing time acceleration functionality to provide a blacklist.  This is because many time accelerators work by just calling the updateEntity() (which is an override of a vanilla MC function as it is) function multiple times per tick, which makes it very hard to check for. let alone circumvent.

Also if memory serves Chromaticcraft allows for up to x256 acceleration (I've not played with it in about a year tbh) which is a rather large acceleration to begin with.

**Comment by metnavman** [comment]
The pack I'm playing doesn't do super quick updates, so if you've pushed an update for AR, I'd have to grab it manually. I'll check on that. Problem being, even with the bug in the older version, it would still use data if the GUI was open. With the tile accelerator going, it doesn't even do that. Just fills the asteroid chip up.

Chromaticraft does indeed have a blacklist. If it has to come from that end, then Reika like has just never played with AR, and therefore hasn't blacklisted any of your constructs.

Yep, 256 is the max for CrC. I've only plopped a 64x down on the AR machines, because quite frankly, I was afraid 256 would break/corrupt something far more seriously.

**Comment by metnavman** [comment]
Updated to the most recent version of 1.7.10 for both AR and the Libvulpes. You've got it sorted! The tile accelerator still makes everything run super-fast though, haha.

Astrobody is properly spending data, even under acceleration. Hooray!
