### ISSUE TITLE
Space Station dimension changed

### ISSUE THREAD

**Issue by metnavman** [zmaster587/AdvancedRocketry#428]
Using the latest versions of the mod and Libvulpes for 1.7.10

Dimension ID for space is 200

Upon arrival to a newly-launched space station, the "dimension" is all black, with no stars and no Overworld "planet". There are also clouds.

Edit: It also has gravity. Basically looks like something changed "Space" to be a regular "world" type dimension, instead of being in space.

**Comment by zmaster587** [comment]
Yeah, it does sound like it's using the overworld provider or something.  Is this in single player or multiplayer and are there other dimension adding mods in the pack if you've got more than just AR and Libvulpes?

**Comment by metnavman** [comment]
Single player, and yes, there's a couple. RFTools, CrC, and Enviromine all immediately come to mind.

I can confirm that your mod is using Dimension -200 for space, if that helps.

**Comment by zmaster587** [comment]
If you remove everything except AR and Libvulpes does this still occur?

**Comment by metnavman** [comment]
That would require some work in a separate world with all of the other mods removed. One does not simply remove Reikas mods from a current world, lol. I can test that but I won't be able to until probably tomorrow night. I'll see what happens.
