### ISSUE TITLE
Request: Upgrades to machines

### ISSUE THREAD

**Issue by SplitInfinitive** [zmaster587/AdvancedRocketry#429]
I love the way the mod works but I am somewhat dismayed by how slow the machines get, especially in comparison to many other mods which have machines that are slow by default but which can have upgrades applied to them (either by using them as a part of the crafting recipe for a faster/more efficient machine or by having upgrade items applied to them).

Could something like this be applied to the multiblock machines in AR as well?

I'm aware that I could go into the configs and speed up the machines there, but I was hoping for more progression then cheating.

**Comment by zmaster587** [comment]
This was intended functionality at the beginning, hence things like the coils and motors, but the upgrade system kinda got lost in everything.  Will mark to make sure it makes it in the next content update.
