### ISSUE TITLE
Request: asteroid/mining laser collecting ores added from other mods as well?

### ISSUE THREAD

**Issue by SplitInfinitive** [zmaster587/AdvancedRocketry#431]
Not sure how hard this would be but I would be pretty darn happy if I could send a rocket to a meteor to collect Certus Quarts (from Applied Energistics) or draconium dust/ore (from Draconic evolution) etc. etc.

What's the possibility of that happening?  with config file to enable/disable/configure rarity.

**Comment by zmaster587** [comment]
The config file in the 1.1.x version already accepts any block/item specified by item/block name and meta.  The 1.1.x version also allows configuration of rarity/probability/amount.  There's not any docs for it atm, but as a stable release comes closer I will add docs.

The 1.0.x builds also already allow specification via oredict name.  So it should be possible to do this in the already existing versions.
