### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by BrisingrAerowing** [zmaster587/AdvancedRocketry#433]
I am not sure whether the crash is from this mod or Stellar Sky, so I am posting to both.

MC: 1.10.2
AR: 1.1.0
Forge: 12.18.3.2239

I am getting a ticking entity crash after launching myself into the air above the world build height limit (I was at about Y = 800) using a booster rocket from another mod. As I dropped down, the instant I hit Y = 255 the crash happened.

[Crash Log](https://gist.github.com/BrisingrAerowing/d65e38824341c8e275684ce85e43d817)

**Comment by zmaster587** [comment]
Looks like something involving stellarium's world provider.  Will see if i can figure out what's going on

**Comment by zmaster587** [comment]
I think I see what's going on there though, I set the sky renderer to null because normally that makes MC use the vanilla sky renderer, but StellarSky attempts to call methods on the passed skyRenderer which results in an NPE.

**Comment by BrisingrAerowing** [comment]
Ah, good. That was bugging me a bit. Thanks! This is a very cool mod.

**Comment by zmaster587** [comment]
No problem,  I'm going to close this for now, if the 1.0.13 build or the 1.1.1 build doesn't fix it just reopen the issue.
