### ISSUE TITLE
AE/AR crafting

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#435]
Went to figure out why I could not craft the Liquid tank for the Rocket. I was doing it through the AE System and Clicked on the Lathe and crashed. 

Here is the File: https://www.dropbox.com/home?preview=3-3-17.txt

**Comment by zmaster587** [comment]
The link you sent for the file appears to be private.  Would you be able to either upload the crash to http://pastebin.com or get me a public facing link?

**Comment by Tyrantin** [comment]
https://www.dropbox.com/s/ctymarmudc07nbh/3-3-17.txt?dl=0

**Comment by zmaster587** [comment]
Thanks.  investigating

**Comment by zmaster587** [comment]
Turns out rolling machine would have had the same issue as well

**Comment by Tyrantin** [comment]
Happy to Help! 

TyRao
Vermilion Modded Servers
