### ISSUE TITLE
Planets aren't reachable anymore

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#436]
So after testing your mod on its own for a while and tweaking configs and planets and everything working, I added it to my upcoming modpack and updated it to the newest version. But now in my testing world and even in new worlds the planets aren't reachable. Here is my planetDefs.xml: http://pastebin.com/eSeDAa0Y
I configured the starting dim id to 1000 and if I do /advancedRocketry planet list, Luna is 1000 as intended as I didn't specify it and all the other planets are shown correctly. But there is an extra Luna at 1024 which is not intended which wasn't there before when I tested it and weirdly the only planet I can get to with /advancedRocketry goto is the second Luna (1024).

Probably I just did something wrong or it is one of the mods in my modpack misbehaving (RFToolsDim?) or  one of the updates broke it, I'm not sure. Thanks for the help you've already given to me, I appreciate it.

MC 1.10.2
Forge 12.18.3.2239
AdvRocketry 1.0.12

**Comment by zmaster587** [comment]
Did you ever run AR 1.0.11 in that world and does this issue occur in a new world?

**Comment by davqvist** [comment]
Yes to both. In my main test survival world where I just now discovered the issue I wanted to start a rocket to Luna and didn't work. This world had 1.0.11 and is now on 1.0.12, but then I created a new creative world and tried /advancedRocketry goto and none of the planets (except the second Luna) worked as well.

**Comment by zmaster587** [comment]
Reason I asked about 1.0.11 is that that particular build screwed up some packet handling, which I suspect, but have not yet confirmed, that possible data corruption occured because of it in single player worlds.

That being said, when generating from that config in a new world and starting the game up from scratch after deleting the old planets config.  I do also see the planet listing, but I do not see an extra luna (if you loaded a world then created a new one that may explain the extra luna, will have to check to make sure it's properly reset).  I also see that the planets are created and properly loaded.  /advRocketry goto 1000, etc for all the planets are working for me without a problem.  Would you be able to send a copy of the advRocketry/temp.dat file from your world so I can see if i can figure out what's going on with it?

**Comment by davqvist** [comment]
> (if you loaded a world then created a new one that may explain the extra luna, will have to check to make sure it's properly reset)
This might be the problem yes. Will check probably tomorrow if this doesn't happen when I create a new world right after starting the pack.

Here's the temp.dat https://drive.google.com/file/d/0BzovnuYeeSkiaFVDZmhkbzZxTlU/view?usp=sharing (wasn't sure if pastebin would screw up special chars)

**Comment by zmaster587** [comment]
Other than the extra luna, things look ok.  However I see what you mean by it won't let you go to the moon.  Trying to track the cause of that down.

**Comment by zmaster587** [comment]
[temp.dat.zip](https://github.com/zmaster587/AdvancedRocketry/files/820268/temp.dat.zip)

I've removed the Extra luna from this one and tested that I can actually go there this time.
The temp.dat file can be opened with an NBT editor.  What I did was delete the dimList/1000 entry and then remove "1000" from dimList/0/childrenPlanets

**Comment by davqvist** [comment]
So, I replaced my temp.dat with yours in my world, but it did not fix it, I again have a second Luna (1024) and can't teleport to other planets (Dimension does not exist). Maybe I have to delete the DIM1024 folder? Even if it would I wonder why it happens in the first place, because that's the real problem if I want to publish my modpack soon. The extra luna doesn't bother me that much honestly, especially as I don't know how to go there without cheats, but I need the other planets to get working. Maybe it's a cross mod incompability? But the only mods adding dimensions are Aroma Mining Dimension (DIM 6), ExtraUtilities (DIM -9999 and DIM -11325) and RFToolsDim, at least I can't think of any more. Not sure what information to give you though, do you want a copy of the modpack?

**Comment by zmaster587** [comment]
I'm fairly sure it's not a mod incompatability as AR requires explicit registration of dimensions (other than galacticcraft).  AR doesn't look for the folder when loading worlds so i don't think it's that.

If you replaced the temp.dat file with MC closed then loaded the pack it should have worked and you shouldn't have an extra luna...  The problem with the extra luna is that you won't be able to get to either of the Lunas in survival as they overlap each other in the UIs.

Even with your temp.dat I could teleport to the other planets without any problem so I'm a bit confused on that point...
I'll double check the temp.dat and make sure I uploaded the right one.

**Comment by zmaster587** [comment]
[temp.dat.zip](https://github.com/zmaster587/AdvancedRocketry/files/823515/temp.dat.zip)

**Comment by davqvist** [comment]
Thanks a lot for your hard work. I appreciate it. This time it worked perfectly.

2 questions now:

1.) This temp.dat was the one created in the new world. I assume I can just use the same one for my actual test world on the modpack dev server I'm playing on or do I need to adjust some values?
2.) In general I'm less worried about this world though and more about future worlds. What can I do to prevent that happening again when creating new worlds for my modpack? Does 1.0.13 fix this already?

**Comment by davqvist** [comment]
Well, regarding 1.) I looked into the temp.dat file with a NBT Explorer and couldn't find anything world specific, so I put it just on my server, but I still can't go to Luna with my rocket, still saying "Destination unreachable".

**Comment by zmaster587** [comment]
Sorry I took so long to get back, but yes, the temp.dat is not specific to a world unless you have dimension mappings, for example like twilight forest.  If there are dim mappings any world that loads it must have the same dimension ID for that other mod, which in the case of a modpack, dimids are unlikely to change.

2.) I've not come across any cases with broken worlds that have not been touched by the 1.0.11 build, nor have I encountered it myself in the 50+ times I've reset my dev env.

Have you verified that earth only has one moon and that it's not a gas giant or are you using the most recent one I uploaded?

Also just to confirm, when you try to go to the moon the planet ID chip in the rocket lists "Luna" as the destination?

**Comment by davqvist** [comment]
Sorry, one week not feeling well, had only time today. Planet List shows me only one Luna as well as Guidance Computer, not sure how to verify if it isn't a Gas Giant, but I looked in the temp.dat and it says it is not. Yes, I took the recent temp.dat and I looked into it, everything seems fine. I have a Planet Id Chip in the Guidance Computer with destination Luna. So it seems everything right, so it's a remaining problem from the 1.0.11 version, maybe?

**Comment by zmaster587** [comment]
It's fine, I'm in the same boat with lack of time...
Looking in the NBT should be enough to verify whether or not it's a gas giant, so if the NBT shows gas giant to be false it shouldn't be a gas giant.
Is the chip in the rocket left over from before you modified the temp.dat?  If so does programming a new chip solve the problem or does it still occur?

  The only possible sideeffects from the 1.0.11 distaster i can think of should show up in the temp.dat.. so if temp.dat is fine then it should be ok...

**Comment by davqvist** [comment]
Well, in new worlds it works and that's what matters. I'm closing this now because I don't care that much about my test world anymore.

**Comment by davqvist** [comment]
So I released the pack, and got the same bug report again. I requested the temp.dat and all the planets are generating as Gas Giants again. This is really bad. He experienced the same thing though, that it only happens on the server, works fine in a singleplayer world. Pack released (and world generated probably as well) in AR 1.0.13, current version is AR 1.0.15

**Comment by davqvist** [comment]
So I played around a bit and it seems even if I change the planets in temp.dat to GasGiant = 0 the temp.dat gets overridden with GasGiant = 1 or I did something wrong. I don't have the config enabled that recreates the temp.dat from the XML, so it must be something else. I looked into your code and found this: https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/backwardCompat/VersionCompat.java

Sorry if I'm wrong but it seems this might be the cause. https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/dimension/DimensionManager.java#L671 tries to get prevVersion from the temp.dat but I can't find this tag, so in VersionCompat version.isEmpty() is probably true and my DimIds are set to >256 so then it converts all planets to GasGiants. Not sure why it would only happen on a server though. Again sorry if this is the wrong track, I didn't setup the environment, I was just reading the code here on github. I just want to get this fixed soon and I'm trying to help.

**Comment by davqvist** [comment]
Sorry for spamming. But after testing I can confirm that this is the issue. I added a NBT String prevVersion and set it to "1.10.2-1.0.15" and the planets stayed having GasGiant = 0, but prevVersion of course disappeared which means it's only a fix until the next server restart. I also saw that the compat method is only called on ServerStartEvent which would be the explanation why it only happens server side. 

I hope you can fix this soon now that the error is found. I unfortunately can't change Dimids to lower than 256 as the modpack is already released and has a lot of downloads, so you need to fix it in another way (maybe getting rid of the compat function as it seems to fix an issue that is half a year old).

**Comment by zmaster587** [comment]
That would make sense, though it should generate a version tag before that
section of code is hit.  Earliest I can get to a computer  is 7 hours from
now.  I'll push out another patch then

**Comment by davqvist** [comment]
Thanks for the quick response. 
It seems to only read the version NBT tag written in the temp.dat which is only read and never saved again.

**Comment by zmaster587** [comment]
It should be updated/initially written in dimensionmanager if memory serves

**Comment by zmaster587** [comment]
Also onserverstart is also called when loading single player.  So idk

**Comment by zmaster587** [comment]
Version compatible definitely sounds like a promisimg culprit, I wonder if
theres some kind of isserver check somewhere

**Comment by davqvist** [comment]
Thank you for fixing it so fast, but I can't find this issue in the changelog of 1.0.16, so can you clarify if this fix is already in 1.0.16 or if I have to wait for the next release?

**Comment by zmaster587** [comment]
It'll be the next release

**Comment by davqvist** [comment]
Thanks for clarification.
