### ISSUE TITLE
Dilithium.

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#437]
Ok so I have Mined the planet and I have minned the moon and I cannot find Any Dilithium ore on either planet! Am I missing something or do I have to use the Orbital laser drill?

**Comment by zmaster587** [comment]
Dilithium should spawn on both the moon and overworld by default.  Dilithium is much more common on the moon though.  It is also very rare on Earth and most planets.

Are you able to find other advanced rocketry ores and do you have any other mods that may be controlling ore generation?

**Comment by Tyrantin** [comment]
I have found all the AR ores Except Dilithium! I have Quarried with the builder block a 4 chunk x 4 chunk area found none! So i did a world edit removing everything but ore in a 10 x 10 chunk and their was none.

**Comment by Tyrantin** [comment]
If you would like I can send you the configs of all the mods

**Comment by zmaster587** [comment]
if you could do that that would be helpful.  I'm wondering if maybe something in there is interfering with ore gen.

**Comment by Tyrantin** [comment]
Will do bud, when I get out of work

**Comment by Tyrantin** [comment]
Here you go, I appreciate this!

https://www.dropbox.com/s/w07u7x7wpc1nqam/Unstoppable%20Config%20files.zip?dl=0

**Comment by zmaster587** [comment]
No problem!
I think OreSpawn is overriding ore generation.  If you were to add dilithium to one of the json files in there it should probably begin to spawn.

**Comment by Tyrantin** [comment]
ok I will let the mod pace creator know so he can make the adjustment and see if it works

**Comment by Tyrantin** [comment]
Solved! Was a mod conflict...
