### ISSUE TITLE
[1.10.2] Graphical glitch on Atmosphere Analyzer

### ISSUE THREAD

**Issue by xSparky911x** [zmaster587/AdvancedRocketry#438]
Forge: 2239
Advanced Rocketry: 1.0.12
LibVulpes: 0.1.16-universal

When adding in the Atmosphere Analyzer to the helmet and placing the helmet on I get a weird blue angled transparent image on the left side of the screen from top to bottom (see screenshot)

![2017-03-04_12 24 59](https://cloud.githubusercontent.com/assets/6767483/23581220/c74c4060-00d5-11e7-994e-4ec770aa4edd.png)

**Comment by zmaster587** [comment]
Does that occur with only AR and libvulpes installed?

**Comment by xSparky911x** [comment]
I have InGameInfo. I disabled it thinking that was causing it but that wasn't the case. I will disable ALL other mods and try again...

**Comment by xSparky911x** [comment]
Only mods installed now are:

Advanced Rocketry
LibVulpes

Tried in fullscreen and windowed mode as well. Noticed now there is blue lines going all the way across the screen. On a side note incase it matters, I am running:

I7 4770k
16gb ram (8gb dedicated to Minecraft)
nVidia 770ti

![2017-03-04_12 57 33](https://cloud.githubusercontent.com/assets/6767483/23581494/a63f1992-00da-11e7-9748-dd0082b97a6c.png)

**Comment by zmaster587** [comment]
Hmm, strange indeed, I've only seen this once before (oddly enough while making the tutorial vid) thought it may have just been my graphics drivers screwing up (in vanilla sometimes a tri of the block vanishes or even in other games sometimes, etc).  Will see if I can track it down.
