### ISSUE TITLE
atmosphereCalculationMethod threaded varieties crash the server

### ISSUE THREAD

**Issue by hagfelsh** [zmaster587/AdvancedRocketry#440]
I realize they're still marked as experimental in the comments of the cfg file, so crashing isn't as surprising.  I wouldn't mind using non-threaded volumetric calculation except for the 15 second lag it induces any time I open an airlock door.

Is this crash something that I can influence somehow?  I'd very much like to use a threaded calculator since the machine this MC instance is on isn't very robust. That makes non-threaded volume unusable, sadly.  The non-volume option (default) should work, too, but once I open an airlock to space and it shuts, the whole station is no longer breathable... and stays that way until I brick up the doorway I opened.  However, non-threaded volume works great except for its utter performance destruction on this old machine.

Crash dump text: http://pastebin.com/byW5six5

Thank you for your help, we love this mod!
h

Notable strings for future searchers:
atmosphereCalculationMethod
Ticking block entity
ConcurrentModificationException

**Comment by zmaster587** [comment]
Can you replicate this with Advanced rocketry 1.0.10 or later?  I'm fairly sure I had fixed this with the 1.0.10 build.

**Comment by hagfelsh** [comment]
Will do--I'll see about trying that on a snapshot tonight.

**Comment by zmaster587** [comment]
Should be fixed with the sync code implemented a few versions back
