### ISSUE TITLE
Machine unloading? Also a client crash.

### ISSUE THREAD

**Issue by sharkck** [zmaster587/AdvancedRocketry#441]
I have noticed that the multiblock machines (precision assembler, saw for silicon, the silicon vat, rolling machine and lathe) all keep forgetting they're on.  When I queue up a job (using AE2 connected to the input bus of its respective machine via an interface) the machine does nothing most of the time until I right click on the primary block for that respective machine before it becomes active.  I do not recall having this issue at all in previous versions of the mod.  I also have noticed that, while staying in the area, the machine sometimes becomes inactive again, after a period of time, if it has nothing to do and I will have to repeat the steps mentioned above.

I was trying to make some tin plates and noticed the rolling machine was not working.  When I right click on the rolling machine's main block, my client crashed with the attached logfile.
[crash-2017-03-07_00.46.06-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/823674/crash-2017-03-07_00.46.06-client.txt)

I hope this helps!  Let me know if there's anything else you need.

**Comment by zmaster587** [comment]
I think I fixed an issue with AE and AR's machines in last night's release (1.0.13) (issue #435 ) , can you give that build a try and see if it's still broken there?

As for the machine unloading, is there any pattern or way to make them stop working on demand?  Also can you verify if they've stopped working on the server as well.  Something like requesting rods or plates through AE should be enough to test that.

**Comment by sharkck** [comment]
I have tried to duplicate the issue and it appears that the changes have fixed the problem.  I have queued up multiple jobs from the various machines and everything was crafted successfully.  If I have any further issues I'll let you know!

**Comment by zmaster587** [comment]
Alright, good to hear!

**Comment by sharkck** [comment]
Not sure what's going on but I'm seeing this happen again.  The machines are unloading.  I have chunk loaders in the area where these are located.  Should I open a new ticket?
