### ISSUE TITLE
Iridium block turn into dilithium ore blocks

### ISSUE THREAD

**Issue by Luckie21** [zmaster587/AdvancedRocketry#442]
When placing a Iridium Block it shows the the texture of Dilithium Ore. Could this be a bug or mod interaction? See pictures
http://imgur.com/jDUn4fq
http://imgur.com/8xKjr1Q
http://imgur.com/eecSEHD

**Comment by zmaster587** [comment]
If this is the MC 1.10.2 (I assume it is) it is likely me screwing up the model definition.  I'll get that fixed

**Comment by zmaster587** [comment]
Fixed in https://github.com/zmaster587/libVulpes/commit/f47ad8fb37d596cfd3c2e077c35a5c12ea4f78df

**Comment by Luckie21** [comment]
Thxs
