### ISSUE TITLE
Problem with custom recipe registration for electrolyzer

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#444]
only the last registered recipe remains, all else including the default one are gone

http://pastebin.com/PMVWxpR1
here is my script if you want to take a look

**Comment by zmaster587** [comment]
I'm wondering if I neglected to check fluidstacks in the isEqual method

**Comment by zmaster587** [comment]
Turns out I was checking NBT tags rather than the fluid ID.  Should be fixed now
