### ISSUE TITLE
"Simple" Crash

### ISSUE THREAD

**Issue by ProxyPlayerHD** [zmaster587/AdvancedRocketry#448]
[Crash Log](http://pastebin.com/9g8fTQ5Y)
I have NO freaking idea what i did.
I must've done something for this to just... Appear.
Hopefully you can make sense out of the Log.
I can Provide Extra Information if needed.

**Comment by zmaster587** [comment]
Looks like one of the recipe XML files is missing the "Recipes" tag?

**Comment by ProxyPlayerHD** [comment]
wow... I am not a Smart man.
I wanted to remove all Recipes from the Chemical Reactor, but accidentally deleted more than my own Recipe.
Welp, you can Close this. It was just my own Failure xD

**Comment by zmaster587** [comment]
It happens
