### ISSUE TITLE
Planet/moon/destination selection UI zoomed in so far that finding planets to land on is difficult

### ISSUE THREAD

**Issue by hagfelsh** [zmaster587/AdvancedRocketry#452]
Is this a user error--is there a way to zoom the UI back so I can see an entire solar system without having to drag and scroll 5-10 times to find a planet or moon to select? 

Running MC 1.7.10
Forge 10.13.4.1558
Adv Rocketry 1.0.8

Here's a picture of my destination selection UI:
http://imgur.com/MoNwUeR

![image](https://cloud.githubusercontent.com/assets/6445682/23826612/58a04810-0665-11e7-8d2b-045680693590.png)

**Comment by zmaster587** [comment]
I don't think you can right now... I thought I had the ability to scroll in and out with the scroll wheel at one point... I'll have to see what happened to it.

**Comment by zmaster587** [comment]
Added dropdown list in 1.2.2
