### ISSUE TITLE
Is it possible let overworld in a custom galaxy?

### ISSUE THREAD

**Issue by indoorsNB** [zmaster587/AdvancedRocketry#453]
On wiki, I found the document about custom galaxies and planets, but I don't know how to let overworld be a custom planet

**Comment by zmaster587** [comment]
Right now there's not really a "safe" to do this.  One way you may be able to do that is to make a custom galaxy and dimmap it like a modded dimension to somewhere in the first galaxy specified.

Likely what I'm going to end up doing in the end is remove the hardcoding for the Overworld and moon and provide a default config instead, it should make things less confusing as well as a bit cleaner

**Comment by indoorsNB** [comment]
Thank you :)

**Comment by zmaster587** [comment]
Better method implemented in https://github.com/zmaster587/AdvancedRocketry/commit/2b66c4e5596af770337001c36972978b856c5511

In newer 1.1.x builds of AR you'll have to dimmap the overworld, but at the same time you'll also no longer be forced to have a moon and you can put it in any star, not just the first one.

**Comment by wormzjl** [comment]
can you explain a bit how does this work?
