### ISSUE TITLE
ABDP missing astro chip interface

### ISSUE THREAD

**Issue by shizoXL** [zmaster587/AdvancedRocketry#458]
in the version 1.10.2-1.1.1 in the astro body data programmer the interface for programming an unprogrammed chip is missing.

![abdp bug](https://cloud.githubusercontent.com/assets/12348244/23870622/4c9aebc4-0827-11e7-9b66-511ab51bd133.GIF)
g.

**Comment by zmaster587** [comment]
Programming the asteroid chip is now done in the observatory in the 1.1.x builds.

**Comment by shizoXL** [comment]
ah! ok thanks for the info.

**Comment by skypilottome** [comment]
I have tried to program an Asteroid chip in the observatory with no luck.  what are the steps to do it?  Am i missing something?

I am loving the mod.  It is amazing!

![2017-03-13_20 33 12](https://cloud.githubusercontent.com/assets/26396288/23882082/60976b0c-082c-11e7-875d-fc392c073d34.png)
![2017-03-13_20 33 13](https://cloud.githubusercontent.com/assets/26396288/23882081/6096ecae-082c-11e7-8658-f4cd9a6153dd.png)
![2017-03-13_20 33 20](https://cloud.githubusercontent.com/assets/26396288/23882083/60998d74-082c-11e7-9c46-81d3b7c1090b.png)

**Comment by zmaster587** [comment]
You need to have 100 distance data in one of the data blocks, then you need to hit scan (It should be green with the data).  From there a list of asteroids will come up, select the one you want then click the gears.  Note for it to work it has to be night and the telescope must be open.

**Comment by SkypilotTom** [comment]
wow, thanks for the fast reply.  i have tried to get data first.  it never loads any data.  i have also tried to insert some data from a chip that got the data from a satellite.

**Comment by SkypilotTom** [comment]
the observatory has been operating since the update was released with data collected.

**Comment by zmaster587** [comment]
you have to feed it distance data from a satellite now, it no longer creates data on its own.

You should have been able to insert data from the chip though.  Will see why that''s not working

**Comment by SkypilotTom** [comment]
Yes, i have tried to send data to the buffer from a chip.  the chip has almost 500 data on it.  I have also tried multiple data buses

**Comment by zmaster587** [comment]
I think what happened is that if the data buffer has no data when the observatory is built it won't accept any other kind of data.  So if you break the observetory and put some distance data into the hatch before rebuilding it, it should fix the issue

**Comment by SkypilotTom** [comment]
That worked!  the screenshots are before and after.

![2017-03-13_20 33 13](https://cloud.githubusercontent.com/assets/26396288/23883871/a6ae73a0-0837-11e7-9a43-fc0749ad3aae.png)
![2017-03-13_21 54 17](https://cloud.githubusercontent.com/assets/26396288/23883872/a6aeeee8-0837-11e7-9866-6fc81c641adc.png)

**Comment by SkypilotTom** [comment]
You rock!
