### ISSUE TITLE
Lightwood Sapling Issue

### ISSUE THREAD

**Issue by shank3001** [zmaster587/AdvancedRocketry#459]
I cannot seem to get a Lightwood Sapling from a Lightwood Tree. The sapling that I get are Oak Saplings. This occurs with normal decay or using a crook.

Forever Standed 
Advanced Rocketry Version 1.1.1

**Comment by zmaster587** [comment]
Meathod for drops apparently changed between 1.7.10 and 1.10.2 and I missed it the whole time.  Nice catch!

**Comment by shank3001** [comment]
I am glad to help. I have really enjoyed your pack. Off course, once you get past the initial grind and a few Blood Moons!!! I was not sure if there was a special ritual on getting the lightwood sapling like stripping down into your skivvies and jumping into a pool of lava with an oak sapling in your hand :)

You did an amazing job!!!!! 

-Shank3001
