### ISSUE TITLE
Power calculation bug?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#46]
Plugged some powersource to the arc furnance like this:
![image](https://cloud.githubusercontent.com/assets/2989009/11788452/b8b24c20-a299-11e5-9709-1c6a93d3628d.png)
It's fully charged
![image](https://cloud.githubusercontent.com/assets/2989009/11788460/c5021b04-a299-11e5-9f23-1edeb2f5465f.png)
But in the interface it shows:
![image](https://cloud.githubusercontent.com/assets/2989009/11788467/d15dcb0a-a299-11e5-9cbe-7daa47ceffe3.png)
The other 2 power plugs are never charged

**Comment by Towsty** [comment]
You have to power all three plugs to fully charge the furnace

**Comment by wormzjl** [comment]
yeah but there is a difference of 3392 power

**Comment by zmaster587** [comment]
Both RF and IC2 blocks are implemented the same way, looks like it may be a packet handling fail.

**Comment by zmaster587** [comment]
Fixed in 0.0.6c libVulpes
