### ISSUE TITLE
Observatory not showing progress on coding Asteroid ID Chip

### ISSUE THREAD

**Issue by Rue82** [zmaster587/AdvancedRocketry#463]
Not sure if I am the only one having this issue but currently using 1.1.1 version of the mod and I like the changes but i can't seem to get my observatory to get any distance data or write it to an Asteroid ID chip.  When i hit the scan button nothing happens.  Wondering if i am doing something wrong of derped it up in some way.  I have a view distance of 75 in the GUI but that is the only thing i can see.  I have nothing obstructing the view that i can tell.  Any help would be greatly appreciated.

**Comment by zmaster587** [comment]
Try deconstructing the observatory, then filling one of the data busses
with distance data, then reform it.  If you have at least 100 distance data
you'll not be able to scan for asteroids.  Only reason you need to
deconstruct it first is because there's a known issue where an empty data
bus in the observatory cannot recieve data while the observatory multi
block is fully formed

**Comment by Rue82** [comment]
Ok I was able to get the distance data into the observatory using the above method.  Once in there it did scan for asteroids but would still not give me the option to write to chip.  Do i need Composition data in there as well. I tried hooking up data cables directly to the data bus after i reformed the Observatory to try and pipe in the data but still the only way to get data into it is from the chip load to buffer.  Anything else i can try?

**Comment by zmaster587** [comment]
It should let you write to the chip if you have an asteroid selected, it's
night time and the observatory is open, an asteroid chip is in the bottom
left slot, and then click on the gears between the two slots.

Though you should be able to pipe data into the data buffer as long as it's
the same type of data

**Comment by Rue82** [comment]
Got it to write to the chip. But the chip was empty, 0/1000 of all attributes.

**Comment by Rue82** [comment]
do i need to have 1000 of distance, mass and composition to get it to write properly?

**Comment by zmaster587** [comment]
Once the chip is programmed you'd need to use the astrobody data processor to add distance data/etc to the chip.  More distance data decreases the amount of the mission failing.

**Comment by DestinyPlayer** [comment]
Having the same exact problem. All Data is filled up to at least 100, an asteroid is chosen, it is night, the observatory is open, it has power. It doesn't show any progress, and the chip is still Unprogrammed.
Minecraft Version 1.11.2
Forge 1.11.2-13.20.0.2310-universal
AdvancedRocketry-1.11.2-1.2.of.jar

**Comment by zmaster587** [comment]
For organization reasons: https://github.com/zmaster587/AdvancedRocketry/issues/676

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable?

**Comment by NiftySkilz** [comment]
im sorry for being so late however if you are still having this problem, set time to night and ensure the top opens up, then it will be able to "process discovery"
