### ISSUE TITLE
XML Planet config doesn't work

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [zmaster587/AdvancedRocketry#465]
I tried using the XML planet config by putting the correctly named XML file in the config/advancedRocketry folder and it didn't do anything even after I edited the document to have a custom planet.
Is there something I'm doing wrong?
I have the XML file in .minecraft/config/advRocketry folder and it's named "planetDefs.xml".
I'm running Windows 7.
Is there a configuration option I'm missing or something? I like having different solar systems for certain maps, is there any way to make the XML systems to be specific to one world so that you could have different planets and starts on a different world?

**Comment by indoorsNB** [comment]
http://pastebin.com/iXfCuh81 
maybe U can try mine XML planets, it work very well. (Maybe you need to use `tellme` to show the biomes, because I use TC biomes.)

**Comment by zmaster587** [comment]
@AGiLE-EaGLE1994 Are you creating a new world after changing the config or trying to load it on an existing world?

**Comment by AGiLE-EaGLE1994** [comment]
Trying to load it in an existing world.
Because I created the planets for a world I already had been working on.
Can you have individual XML files for each world or not?

**Comment by AGiLE-EaGLE1994** [comment]
Thanks for letting me know.
