### ISSUE TITLE
More configurable astriods

### ISSUE THREAD

**Issue by shivachirr** [zmaster587/AdvancedRocketry#466]
i want to config the astroids cont tant so lets say its 60% stone 20% iron 10% redstone 5% gold 5% sand or something becue i notice you can really limit what amounts are on astroids when you send a mining ship out after them

**Comment by zmaster587** [comment]
Are you asking for more asteroids to be added to the default configuration?  Well, rather a specific addition?

**Comment by shivachirr** [comment]
im asking to be able to set how much ore should be on an astrioded and set ratios of each ore like the astriod will contan 50% iron ore and 50% gold ore

**Comment by zmaster587** [comment]
You should be able to accomplish that with the "chance" variable.  I've not yet gotten around to really documenting the config yet but...
Mass controls the amount of material in the asteroid total
richness determines how much of the asteroid is ore vs cobblestone (higher value mean higher ore %)
probability determines how likely this asteroid type will occur compared to other types
chance determines how likely an ore is to spawn with respect to another

The below shows an asteroid that has around 1000 +/- 500 blocks with a high ore to cobble ratio.
Of the ores iron has a 50% chance of spawning, gold 25%, redstone ore 20%, and sand 5%.
There's also some randomness for ore richness and size
```
        <asteroid name="Large Asteroid" distance="10" mass="1000" massVariability="0.5" minLevel="0" probability="1" richness="0.8" richnessVariability="0.5">
		<ore itemStack="minecraft:iron_ore" chance="50" />
		<ore itemStack="minecraft:gold_ore" chance="25" />
		<ore itemStack="minecraft:redstone_ore" chance="20" />
                <ore itemStack="minecraft:sand" chance="5" />
	</asteroid>
```

**Comment by gdarai** [comment]
Hi... I have additional questions to this topic:

One Major:
This is all good, but how is it with ores, when you need metadata to distinguish them?
Like Titanium and Dilithium from the LibVupes. They have both the same block name and differs only by the Meta?

Few Minor:
And what is the minLevel in the asteroid config?
What is Richness? The ammount of cobble? Measured in fraction of 1?
Can I have different asteroids setting around different planets?
How can I clear/sort the list of asteroids in the observatory?

One example to verify:
When I have two ores, iron with chance 50 and gold with chance 25 and richness 0.5, and mass 100, 
I will get appx 50 cobble, 16 gold and 33 iron?

Thanks, GD.

**Comment by gdarai** [comment]
To add to my question on Meta Data: I tried "libvupes:ore0:1"
Without the MetaData it returns Dilithium (which is libvupes:ore0:0), with the Meta it fails and loads nothing.

By the way thanks for the mod it is really super... the best mod of this year.

**Comment by zmaster587** [comment]
You should be able to input meta in a similar way to the machine XML recipes with a specification similar to "<ore itemStack="modid:itemname meta" ... />" for example ""<ore itemStack="libvupes:ore0 1" ... />"" should be libvulpes's ore0 meta 1.

Minlevel is to specify what level the telescope needs to be to be able to view the asteroid, it's currently unimplemented and may be removed as distance may be enough.

Richness is a ratio of ore to cobble, so richness of 1 should produce no cobble and 0 should produce no ore.

Currently asteroids are universal so they cannot be limited to a particular planet, however that would be something neat to implement.

There is no way to clear or sort the list, and I'm not even sure where i could find room in the UI to stick a sort option to be honest...

As for the example, if my math is not wrong then that's about what you should get assuming variablity is very low or zero.
