### ISSUE TITLE
Invisible crystallizer

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#47]
![image](https://cloud.githubusercontent.com/assets/2989009/11788525/2adcac0a-a29a-11e5-995d-59ffd48fc89a.png)
And it disappears after right clicking, so it's no longer possible to make this machine

**Comment by zmaster587** [comment]
did this world exist before updating to the latest version?

**Comment by wormzjl** [comment]
No this is a new world :P

**Comment by zmaster587** [comment]
What happens if you try rebuilding it?

**Comment by wormzjl** [comment]
Umm in fact it's just the crystallizer block

**Comment by wormzjl** [comment]
https://youtu.be/RL6aVL7-vqI
made a short video to show what I got

**Comment by zmaster587** [comment]
Does this still occur if only libVulpes, Advanced Rocketry and Buildcraft are installed?  Also what mod adds the really short grass?

**Comment by wormzjl** [comment]
Yeah I have all these installed
the grass come from the mod BetterFoliage. which is only graphical changes

**Comment by wormzjl** [comment]
It's behaving normally now, trying to find the source of this

**Comment by SNIPER722** [comment]
prossble Problem find. DO you have mod StacksOnStacks?  I find this might be the issue. After i delete this mod from my mod pack, crystallizer will not disappear after place is down

**Comment by wormzjl** [comment]
That mod thinks the crystallizer is some sort of ingot :P
