### ISSUE TITLE
Ore scanner dose not work or unclear how to set it up

### ISSUE THREAD

**Issue by shivachirr** [zmaster587/AdvancedRocketry#471]
so ive followed the wiki and what other information i could ive sent up a ore scan sat with power and 4k data storage and when i try to link the ore scanner to it, it dose want to no matter what i try in the sat builder it just wont link. unless the ore scanner is apost to be the main part of the satlite which i wont work there

**Comment by wormzjl** [comment]
try to wait a bit more, scanning takes time

**Comment by shivachirr** [comment]
ok but what goses on the sat type area because the ore thing dose not work
there

**Comment by wormzjl** [comment]
english please?

**Comment by shivachirr** [comment]
never mind i got the sat to work it was just that how to do it was not well said and it did not say to build the satellite in the sat builder for the ore scanner to be in place other then a sat id chip

**Comment by zmaster587** [comment]
I've updated instructions here: http://65.78.115.159:8000/AdvancedRocketry/items/satellite.php hopefully this is a bit more clear.  I'd like to make it more clear http://65.78.115.159:8000/AdvancedRocketry/items/oreScanner.php here, but I cannot figure out a better order to put stuff together

**Comment by shivachirr** [comment]
maybe a picture showing how the ore scanner sat is made and linked
