### ISSUE TITLE
Chips with data debug and loot

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#478]
Hi,

When you want to test a rocket, or try to search for asteroids how do you obtain DATA, some fast way for debug purpouses?

Can we generate some data using a command? To have them for example as a Quest reward, or loot?
(I also added some questions to the Asteroid Mission Setting Issue, please read them)

Thanks and thanks for the mod it is superb.

**Comment by zmaster587** [comment]
There is currently a command to fill the data on the entire chip, but it fills all the data to 100%, If memory serves it's "/advRocketry filldata" while holding an asteroid chip.  If you've got a mod that can generate loot with items with NBT you should also be able to add data in whatever amounts you want that way too.
