### ISSUE TITLE
[Suggestion] Support for Environmental Tech Solarpanels

### ISSUE THREAD

**Issue by Bobynoby** [zmaster587/AdvancedRocketry#479]
I love the space stations... a lot... And I want to build an entire base in space but I need a lot of power.

I decided to go for solar power and use the environment tech panels, But they don't seem to work in space. I tried other mods that have solar panels like Mekanism, Industrial Craft, EnderIO and they seem to work fine in space but not environmental tech solar panels. So i'm guessing that the panels use a different system for time/light checking which might be something you can implement into the dimensions themselves maybe?

**Comment by zmaster587** [comment]
I'll take a look at it either later today or tomorrow sometime and see if i can figure out what's up

**Comment by zmaster587** [comment]
Seems to work fine on space stations for me in the MC 1.10.2 builds.  Did you make sure to assemble the multiblock strucuture from env tech?

**Comment by Bobynoby** [comment]
Yes, With the assembler as well. I'm sure it didn't produce power but maybe it doesn't like the cables I was using.

**Comment by zmaster587** [comment]
Is unsure, I just tested it by putting an empty power input plug from AR so it was touching the solar panel controller. 

Actually, is your space station oriented so the sun is overhead?

**Comment by Bobynoby** [comment]
... you know orientating it might of helped OH I FEEL SO STUPID Im so sorry :P

**Comment by Bobynoby** [comment]
i think ill just close this, i'm also face palming really hard. I think it was because of the orientation and the cables I was using just didn't like the controller.
