### ISSUE TITLE
The rocket does not look for a landing pad at the orbital station

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#482]
If the initial location of the landing site is transferred to the orbital station, then the rocket sits not on the platform, but on the place where the landing site (the initial place) was located. In addition, even if there are free landing sites, missiles always land on the site of the initial landing site (whether it is present or not). If the place is already occupied, then the rocket sits on top of another rocket. 
Sorry for bad my English.

**Comment by zmaster587** [comment]
if the landing pads are broken and replaced, do they still ignore the landing pads?

**Comment by denwd** [comment]
Probably, this is a mistake of the players.

**Comment by denwd** [comment]
The rocket sits at the point where there was a landing pad, in any case (if there are no linked sites). There were no errors.

**Comment by zmaster587** [comment]
Ah i see, I thought you were saying they always landed at origin, not just one landing pad.  If you're still getting the error that you have pasted into a few of the other reports you made it would be likely that the pad doesn't register as having a rocket on it, thus letting other rockets land in the same place.

**Comment by denwd** [comment]
understand thank you

**Comment by zmaster587** [comment]
likely related to #477 and #476

**Comment by zmaster587** [comment]
does this also occur with only forge, advanced rocketry, and libvulpes?
