### ISSUE TITLE
Planets dimensions

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#485]
I need to insert custom map into a planet dimension.
How do I do it?

The dimensions seems to not be generated into standard DIM folders... so how?
Thanks, GD.

**Comment by zmaster587** [comment]
Advanced Rocketry dimension data is stored in <save dir>/advRocketry/
A planet with the dim 13 will store it's data in <save
dir>/advRocketry/DIM13

So if you dump the world data in there you should be good
