### ISSUE TITLE
Copper Coils when broken returning Gold Coils

### ISSUE THREAD

**Issue by Divineaspect** [zmaster587/AdvancedRocketry#487]

**Comment by zmaster587** [comment]
What versions of AR and Libvulpes are you using.  I am unable to replicate with LibVulpes 0.1.16 and AR 1.0.13 for either MC 1.10.2 or 1.7.10

**Comment by Divineaspect** [comment]
on 1.10.2, on a server.
adv rocketry 1.1.1
lib vulpes 0.2.0

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by zmaster587** [comment]
I've tried breaking a copper coil using a diamond pick on an MC 1.10.2 server running AR 1.1.1 and libvulpes 0.2.0 and still only get copper coils back.

Do you have any other mods installed?  and if so does it continue to occur without them?
