### ISSUE TITLE
Config file does not keep changes (seems overwriten when MC starts) and misspelling in config file

### ISSUE THREAD

**Issue by jonabrv1965** [zmaster587/AdvancedRocketry#489]
Trying to change the microwave multiplier (because to expend 2376 gold ingots to get a lousy 4400 RF/t does not seem balanced :-) I have realized two things, one trivial : the entry for microwave multiplier have bad orthography (nevertheless the changed was applied to the mod, so I guess the code itself is wrong also) =

![capture](https://cloud.githubusercontent.com/assets/13445986/24572318/4245e4ca-163d-11e7-82ce-c83966381ebc.JPG)

But the bad part is that I discover that the config I changed was replaced/reverted/younameit with a earlier version at the moment to start MineCraft (therefore the changes expected never happen).... I do flag the .cfg file as read only and that was the only way to keep my changes.... weird thing...

Versions : AdvancedRocketry-1.10.2-1.0.13, LibVulpes-1.10.2-0.1.16-universal, forge-1.10.2-12.18.3.2254

**Comment by zmaster587** [comment]
Do you have minecraft running at the point in time when you save the config?

**Comment by jonabrv1965** [comment]
Uhm... I really can't tell...Maybe yes (and of course that explains this...) let me see if I can recreate the situation...
