### ISSUE TITLE
Where is Owerworld, Moon and how to get rid of them

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#491]
Hi,
I designed star system with a moon around GasGiant and I would like to get rid of Overworld and start there on that moon. Is there a way to do it? I hoped that
`<planet name="Jambo 4" DIMID="100">`
`    <GasGiant>true</GasGiant>`
`    <planet name="Joola" DIMID="0" dimMapping="">`
`   </planet>`
`</planet>`
would do the trick, but no,
I still have overworld with sun and not the Gas Giant and I still have the mysterious DIM 2 - Moon.
Can you suggest me the best practice how to create such a custom spawn?

Thanks, GD.

**Comment by zmaster587** [comment]
There's no way to get around that with the current release builds short of using an NBT editor on "advRocketry/temp.dat" and removing the entry for Earth.  However in the upcoming builds it will be required to map a planet to Earth on the custom XML, so what you want to do should work fine in the next alpha build with your existing setup.

**Comment by zmaster587** [comment]
Should be implemented in newest build

**Comment by PercyJames** [comment]
i can't remove luna! i dimmaped galacticraft's moon to the planet A moon but it's not working!
