### ISSUE TITLE
1.10.2 Rocket Assembling Machine not working...

### ISSUE THREAD

**Issue by TropicalCyclone** [zmaster587/AdvancedRocketry#492]
When i click scan the scanner pops up but not moving down. How do I fix it?

**Comment by TropicalCyclone** [comment]
![2017-04-01_20 30 44](https://cloud.githubusercontent.com/assets/26837539/24578771/2d7eaf30-171a-11e7-83da-28951d808c33.png)
here is a pic

**Comment by zmaster587** [comment]
does this occur on a server, single player, or both?

**Comment by zmaster587** [comment]
I meant to mention the other day, it should actually "Scan" but i think the visuals are screwed up, see if the progress bar inside the block is actually moving?

**Comment by zmaster587** [comment]
When testing i did notice the creative battery does not output power to blocks touching it.  So verify the rocket assembling machine has power?

**Comment by TropicalCyclone** [comment]
Both

**Comment by TropicalCyclone** [comment]
It shows that it is not scanning
