### ISSUE TITLE
Dupes of rockets and shuttles

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#493]
The rockets and shuttles are doubled after each server restart. If shortly before the server was restarted, the rocket or shuttle was not on the landing site or dock, it happens.

In addition, the player launched a shuttle for gas production. The shuttle was due to return in 15 minutes, but returned after about 10 minutes. A few minutes later, there was a scheduled restart of the server. After the server restart, 2 more shuttles arrived! With rockets about the same problem occurs.

![3333](https://cloud.githubusercontent.com/assets/3863970/24580877/c39c6ffc-1729-11e7-81d6-4d23418c30c9.png)

**Comment by zmaster587** [comment]
Does this occur with only Advanced rocketry and Libvulpes installed?

**Comment by denwd** [comment]
Was not able to repeat the bug himself(( He is not at all. Tried with mods and advanced rocketry Libvulpes, and the forge.

So I found a station under their invisible blocks that you cannot remove their id 737, if they can they form of the shuttles. And just 3 pieces, 3 pieces and are copied each time.
![1](https://cloud.githubusercontent.com/assets/3863970/24585433/cee82912-17a3-11e7-84eb-f85c59d5afd0.jpg)
![2](https://cloud.githubusercontent.com/assets/3863970/24585435/cee8c214-17a3-11e7-8489-d1050501c191.jpg)
![2017-04-02_12 26 57](https://cloud.githubusercontent.com/assets/3863970/24585436/ceeb12f8-17a3-11e7-8e86-45fc1d8d0ff0.png)
![2017-04-02_12 39 11](https://cloud.githubusercontent.com/assets/3863970/24585434/cee8ba1c-17a3-11e7-90a9-ef4e3fa11c09.png)

**Comment by denwd** [comment]
If you break down copies of shuttles or missiles, then in their place there are such blocks as in the screenshot.
![2017-04-02_18 00 20](https://cloud.githubusercontent.com/assets/3863970/24587393/fd1eb8fc-17ce-11e7-8006-d7ac9a7b02e6.png)

**Comment by zmaster587** [comment]
So you're saying you cannot repeat it with only AR libvulpes and forge?  Can it be repeated reliably with all the mods installed?

The invisible blocks just appear to be mekanism machine blocks?
What mod is that bounding block from?  And was anything from that mod put on the shuttle before when it was originally build?

**Comment by denwd** [comment]
I made a video, it will flood just after

**Comment by denwd** [comment]
https://www.youtube.com/watch?v=jZg3Hl4fKxA&feature=youtu.be

**Comment by denwd** [comment]
UP

**Comment by zmaster587** [comment]
I will take a look when I get time, the next 2 days for me are completely booked with other things u need to do

**Comment by zmaster587** [comment]
Other things I need to do*
I blame autocorrect

**Comment by zmaster587** [comment]
I've fixed the NegativeArraySizeException.  I had the patch in 1.10.2 for a while, and I must have missed backporting it.

**Comment by zmaster587** [comment]
forgot to patch rocket builder in last commit, oops.

**Comment by zmaster587** [comment]
I was able to identify a dupe glitch in single player, though Im not sure if it would occur on server as well due to it being an issue that looks like it can only be caused by the server and the client being the same program

**Comment by zmaster587** [comment]
Does this happen with passenger rockets or only mining mission/gas mining mission rockets

**Comment by denwd** [comment]
Thank you, finally understand each other))

**Comment by zmaster587** [comment]
I think so, took a bit longer than I would like.  Logs/step-by-step instructions are usually the fastest way to get things figured out.

Also when you get a chance can you test the changes and report back whether or not they fixed your issue?

**Comment by denwd** [comment]
Good afternoon, I have tested everything is fine, no more phantom objects. Remained a rare and obscure bug with wires and all.
