### ISSUE TITLE
Crystallizer and Precision Assembler will not assemble

### ISSUE THREAD

**Issue by mikamitcha** [zmaster587/AdvancedRocketry#494]
Running on minecraft 1.10.2, in the All The Mods pack.

Its possible I messed something up, but each of these machines show the red X over them when I attempt to right-click the control block to assemble them. I have tried reassembling them several times in several different locations, with no luck. Did I make some error, or is this a bug?

![image](https://cloud.githubusercontent.com/assets/26841939/24580925/7acc91ac-16df-11e7-9903-104655b1e86c.png)

![image](https://cloud.githubusercontent.com/assets/26841939/24580930/819d0728-16df-11e7-8c23-a69f4d836ac1.png)

I can post error logs or any other info if that would help.

**Comment by mikamitcha** [comment]
I just realized that I am only seeing one layer of each structure, is this a common issue?

**Comment by mikamitcha** [comment]
Closed because thats not the issue.

**Comment by Liloa** [comment]
So whats the problem hes running into? Im having the same problem

**Comment by mikamitcha** [comment]
shift-scroll to see the upper layers
