### ISSUE TITLE
UI incompatibility with JEI

### ISSUE THREAD

**Issue by samuelroy21** [zmaster587/AdvancedRocketry#495]
When playing with JEI installed and active, if you hover over the "Mods" button at the top of the screen while in a Advanced Rocketry machine, the UI will turn yellow.
Tested in 1.10.2 with version 1.1.1

**Comment by zmaster587** [comment]
How do you display the mods button in JEI?  I'm currently testing with JEI 1.10.2-3.14.7.416 and cannot find a "mods" button anywhere

**Comment by samuelroy21** [comment]
It's at the top of the screen; perhaps it's an addon I have. I believe it could be Just Enough Buttons (JEB), but I'm unsure.

**Comment by zmaster587** [comment]
with JEI I see creative toggle, weather toggles etc, but still don't see a mods button

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
