### ISSUE TITLE
Dupe bug (Tanks)

### ISSUE THREAD

**Issue by sharkck** [zmaster587/AdvancedRocketry#496]
I right clicked on an ender tank with a stack of low pressure tanks to get some liquid oxygen out of it and now I have an entire stack of low pressure tanks with 1k liquid oxygen in each at the cost of only 1k liquid oxygen from the ender tank.

**Comment by zmaster587** [comment]
Right clicking on an ender tank invokes the handler from EnderStorage, so chances are it's not checking for stack size, what I can do is disallow stacks of pressure tanks

**Comment by zmaster587** [comment]
what build are you using?   Using the 1.7.10 build of AR 1.0.13, EnderStorage-1.7.10-1.4.7.37-universal,  and CodeChickenCore-1.7.10-1.0.7.47 I am unable to fill the low pressure tank from an enderstorage tank full of liquid oxygen at all

**Comment by sharkck** [comment]
I'm using EnderTanks version 1.10.0-1.4.11

**Comment by zmaster587** [comment]
alright, will take a peek

**Comment by sharkck** [comment]
Does this help? https://www.twitch.tv/videos/132884657

**Comment by zmaster587** [comment]
I've been able to replicate it now

**Comment by zmaster587** [comment]
From shetiphian.endertanks.common.block.class:
```
shetiphian.endertanks.common.block(line 213)      
if (FluidContainerRegistry.isEmptyContainer(heldItem))
      {
        FluidStack tankLiquid = tankTile.getTankInfo().fluid;
        if (tankLiquid != null)
        {
          ItemStack filledItem = FluidContainerRegistry.fillFluidContainer(tankLiquid, heldItem);
          if ((filledItem != null) && 
            (!player.capabilities.isCreativeMode))
          {
            if (heldItem.stackSize > 1)
            {
              if (!player.inventory.addItemStackToInventory(filledItem)) {
                return false;
              }
              player.inventory.setInventorySlotContents(player.inventory.currentItem, consumeItem(heldItem));
            }
            else
            {
              player.inventory.setInventorySlotContents(player.inventory.currentItem, consumeItem(heldItem));
              player.inventory.setInventorySlotContents(player.inventory.currentItem, filledItem);
            }
            tankTile.drain(tankFacing, 1000, true);
            return true;
          }
        }
      }
shetiphian.endertanks.common.block(line 348)   
  private ItemStack consumeItem(ItemStack stack)
  {
    if (stack.stackSize == 1)
    {
      if (stack.getItem().hasContainerItem(stack)) {
        return stack.getItem().getContainerItem(stack);
      }
      return null;
    }
    stack.splitStack(1);
    return stack;
  }
```

It looks like the endertank mod takes the stack you're holding, then sets it to be full of the fluid and stores it in "filledItem", then it takes the stack your currently holding, decrements it by 1, but then overwrites it with "filledItem" which is the original stack size, resulting in filling the entire stack instead of creating a new stack with only one item filled and leaving the rest empty.
But yeah, looks like short of limiting stack size of the pressurized tanks to one, there's not much I can do as the filling code is not in AR.
