### ISSUE TITLE
rocket engines orientation

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#498]
Finally able to reproduce visual Glitch!

![2017-04-02_06 25 10](https://cloud.githubusercontent.com/assets/8041616/24586377/7070f57a-176d-11e7-936b-34d4c2d747be.png)
![2017-04-02_06 23 56](https://cloud.githubusercontent.com/assets/8041616/24586378/70717798-176d-11e7-81a0-7cf9b27bb303.png)
![2017-04-02_06 25 09](https://cloud.githubusercontent.com/assets/8041616/24586379/7073e348-176d-11e7-8657-764d7015bc58.png)
![2017-04-02_06 25 11](https://cloud.githubusercontent.com/assets/8041616/24586380/70753d92-176d-11e7-9ae0-e70e61613cc7.png)

**Comment by zmaster587** [comment]
Can you give steps to reproduce reliably so I can see if I can get a fix for it?
is absolute direction a factor?  Chunk loading?

**Comment by Tyrantin** [comment]
Placed a block next to the structure, placed engine. Broke starting block, built ship.

Engines
Fuel tanks 
Collection tanks
Collectors
Fluid unloader in front of bottom center engine. (Not sure if needed)
Slabs on top and bottom of tanks for astedics!
In that order.

**Comment by Tyrantin** [comment]
Would you like to come onto our server to see for yourself?

**Comment by zmaster587** [comment]
I can probably make it on on Wednesday

**Comment by Tyrantin** [comment]
Ok if you build it in a structure the rotate the wrong way. If you build it in the open they orient the correct way.

**Comment by zmaster587** [comment]
Appears to be an issue only when the rocket faces N/S
