### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#499]
http://65.78.115.159:8000/AdvancedRocketry/Commands.php

AdvancedRocketry-1.7.10-1.0.13
LibVulpes-1.7.10-0.1.16-universal
forge latest 1710

in the console is empty

**Comment by zmaster587** [comment]
Commands currently must be executed by a player and cannot be executed on console due to the requirement for a player reference for many commands

**Comment by denwd** [comment]
I introduced the team from the player
