### ISSUE TITLE
No Launchie!

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#500]
Ok, I have set up 4 gas mining ships and none of them will launch. I have everything set up correctly.
![2017-04-02_10 53 59](https://cloud.githubusercontent.com/assets/8041616/24588258/dde57836-1792-11e7-9905-21a49ea52b52.png)

**Comment by zmaster587** [comment]
Is there collision with the lip of the station in the front?  F3+B I think will display bounding boxes

**Comment by Tyrantin** [comment]
Figured it out! Limit on Size.
