### ISSUE TITLE
unmanned rocket engins rotated the wrong way

### ISSUE THREAD

**Issue by shivachirr** [zmaster587/AdvancedRocketry#505]
so i have a unamnned rocket were engines are facing inwords towards the front of the of rocket and the particles dont render properly. and they are like this from the moment they are built

![2017-04-03_06 23 20](https://cloud.githubusercontent.com/assets/9361172/24605276/32d52ff0-1836-11e7-9d50-619bff252fc7.png)

**Comment by Tyrantin** [comment]
This has been addressed. #498
