### ISSUE TITLE
Crash report from this morning. Client side!

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#506]
[crash-2017-04-03_08.02.18-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/889944/crash-2017-04-03_08.02.18-client.txt)

I understand this is alpha.....

**Comment by zmaster587** [comment]
Dies this occur with the libvulpes 0.2.x series as well?

**Comment by Tyrantin** [comment]
no
Can I get your TS?

**Comment by zmaster587** [comment]
I can send it in a pm later, though the earliest I will be able to get on
is Wednesday afternoon

**Comment by Tyrantin** [comment]
ok thx

**Comment by denwd** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/493   Good afternoon, please see

**Comment by Tyrantin** [comment]
How is that in relation to my crash?

**Comment by Tyrantin** [comment]
Please Don't use my posts to get attention to your issue.

**Comment by Tyrantin** [comment]
CANCEL! Lib didn't update... My Bad :/
