### ISSUE TITLE
Forcefield

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#507]
Real Quick. How does the force-field work?

**Comment by zmaster587** [comment]
The direction placed determines the direction the force field will extend
 (facing player if memory serves).  Apply Redstone signal to extend, remove
Redstone signal to retract

**Comment by zmaster587** [comment]
Darn enter key.
It extends up to 32 blocks and will stop extending if it hits anything
other than air

**Comment by Tyrantin** [comment]
Awesome thx! So ships cannot pass through it then?

**Comment by zmaster587** [comment]
They should, the force fields are solid

**Comment by zmaster587** [comment]
Should not...

**Comment by Tyrantin** [comment]
Ok thx
