### ISSUE TITLE
Unmanned launch Crash

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#508]
Not sure if the other post is the same  Alpha build:

[crash-2017-04-03_08.56.29-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/890486/crash-2017-04-03_08.56.29-server.txt)

**Comment by zmaster587** [comment]
Looks like you're trying to take off from a world not registered as a planet?  What dim are you taking off from and would you be willing to pass the /advRocketry/temp.dat?

**Comment by Tyrantin** [comment]
Will get you the info in the morning. Currently at work

**Comment by Tyrantin** [comment]
Ok. It is a fresh world. Dim2, Station 1::

https://www.dropbox.com/s/6lq7pmrlhglso67/temp.dat?dl=0

**Comment by zmaster587** [comment]
No idea why this is a new issue, this should have been broken the whole time...  perhaps something with the change that makes the overworld no longer a special case

**Comment by Tyrantin** [comment]
this was at the Gas Giant though.

**Comment by Tyrantin** [comment]
are the Force Field's not sealable?

**Comment by zmaster587** [comment]
Didn't matter, it was trying to pull properties from something that was never set.  No idea how it ended up that way or how it worked before.  Also the forcefield should be sealable, I admittedly only tested it in 1.10.2 but it worked there and the 1.7.10 sealer should run the same code.

**Comment by Tyrantin** [comment]
Forcefields​ are sealable.

**Comment by zmaster587** [comment]
Fixed in https://github.com/zmaster587/AdvancedRocketry/commit/734a0841053879c7f9613489ec33fe72c729d213
