### ISSUE TITLE
Zmaster, I was told I was supposed to contact you...

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#509]
https://i.artdude.uk/darkosto/PgZ6BVE5.png
![image](https://cloud.githubusercontent.com/assets/10309699/24617924/5dbb6b58-1863-11e7-93ce-c72078906dab.png)

:P 

Honestly, these ghost blocks were in my world before the last update and when broken and replaced with the Holo-Projector they show up perfectly fine. Thanks again for an awesome mod and your hard work!

Darkosto

**Comment by zmaster587** [comment]
Was it showing the correct block there before the update or did it just change during the update?

**Comment by Darkosto** [comment]
It wasn't showing before, it was showing the correct block. I closed the pack, updated the mod, and then loaded it back up to that. Everything is working as intended :)

**Comment by zmaster587** [comment]
alright, might be due to some block id change then or something, idk.  I actually completely forgot I put that message in there.  I don't think there's anything that really can or needs to be done about it, thanks for the tip though!
