### ISSUE TITLE
Visual glitch with the holo planet selector

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#511]
Looked from above
![image](https://cloud.githubusercontent.com/assets/2989009/24630500/3e6b1d3e-18bd-11e7-9f24-ea145da845c8.png)

Looked from below
![image](https://cloud.githubusercontent.com/assets/2989009/24630527/50ee746a-18bd-11e7-9169-4d49f0bf184c.png)

which is the correct one?

**Comment by zmaster587** [comment]
Is there something other than the blue, professionally name "holo effect thingy" that's wrong?

**Comment by wormzjl** [comment]
nope

**Comment by zmaster587** [comment]
Aright, should be fixed for next build then
