### ISSUE TITLE
Star remains after the holo selector is broken

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#512]
![image](https://cloud.githubusercontent.com/assets/2989009/24630639/bbb0abba-18bd-11e7-9dea-ef2c9175b372.png)

Which was normal in previous version

**Comment by zmaster587** [comment]
Oddly enough does not appear to occur in the 1.7.10 version

**Comment by wormzjl** [comment]
I'm using 1.7.10 actually

**Comment by zmaster587** [comment]
Odd, I was unable to replicate it in 1.7.10... either way I applied the same fix to both just in case so should still be fixed
