### ISSUE TITLE
WorldDummy cannot be casted to WorldServer

### ISSUE THREAD

**Issue by gabizou** [zmaster587/AdvancedRocketry#513]
Hello,

As you may know, Sponge does a lot of things to maximize compatibility with mods, and one of those things is checking that a `World` object is `isRemote` is `false`. That being said, I recently got a stack trace as follows:
![stacktrace](https://puu.sh/v8iBr/df1dbe9fee.png)

The issue for Sponge is that it does [this `!this.world.isRemote` check](https://github.com/SpongePowered/SpongeCommon/blob/stable-5/src/main/java/org/spongepowered/common/mixin/core/tileentity/MixinTileEntity.java#L108) and it will pass and attempt to cast the world being used as a `WorldServer` object. 

I do believe this can be fixed if your `WorldDummy.isRemote` is set to `true` to avoid server side logic being run erroneously by SpongeForge.

If there are any issues with what I've mentioned, or further discussion is required, I'd be more than willing to discuss this further.

**Comment by zmaster587** [comment]
I'm not really sure what I can do about this, i can't simply make it return isRemote to true due to the fact that worldDummy is used on both the client and the server.

sorry for the long delay, things just keep stacking up...

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by gabizou** [comment]
I don't think this is an issue at this point, Sponge has added quite a bit of handling for these types of objects to avoid processing where they're not wanted. However, I would still stand behind my original statement if AR is still creating dummy worlds to simulate changes and `isRemote` is `false` when the world is not directly managed by the Server.

**Comment by BestOwl** [comment]
It's still an issue on Forge+Bukkit server.
[crash-2019-03-10_19.36.43-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/2949624/crash-2019-03-10_19.36.43-server.txt)

**Comment by dmodoomsirius** [comment]
that is not a full crash report. also Are you using the latest UNSTABLE build of advanced Rocketry.

**Comment by BestOwl** [comment]
Here is a full crash report using the latest UNSTABLE build (1.12.2-1.
[crash-2019-03-14_10.37.49-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/2964619/crash-2019-03-14_10.37.49-server.txt)
5.0-134).
