### ISSUE TITLE
Allow renaming of overworld

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#514]
instead of "earth"

Could be related to https://github.com/zmaster587/AdvancedRocketry/issues/453

**Comment by zmaster587** [comment]
That should be doable with the new system.  The new system basically treats
the overworld as a non AR planet so you can move/rename/etc like any other
dimmapped planet

**Comment by wormzjl** [comment]
is the new system implemented in the latest version?

**Comment by zmaster587** [comment]
The 1.1.x builds, yes.

**Comment by wormzjl** [comment]
thx！
