### ISSUE TITLE
Newest update.

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#516]
I downloaded the newest Alpha build. Tried to load it and it would get stuck on Building Terrain.  So I did a test, I created a new instance and Downloaded the newest Alpha and Lib, same thing! So I reverted to the old Lib and it crashed.. Something in the Files are failing To finish rendering.

**Comment by Tyrantin** [comment]
I am on Discord if you have a fue minutes.... Will be on for about 2 more hrs Where did you send your TS in a PM

**Comment by Divineaspect** [comment]
resolved?

**Comment by zmaster587** [comment]
Should be, no longer occurs after the fix it seems

**Comment by zmaster587** [comment]
Turns out I made another screw up while trying to remove special cases for Earth/sun..  Was basically trying to get sol (null) to set sol (null) then do something with sol (still null) causing the crash
