### ISSUE TITLE
worldguard integration

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#517]
Good afternoon, on our server regions players based on worldguard, I've been trying for days to do so after assembling the rocket Builder it can sit only a person who is registered in the region. Please help or advice how to do this or add support to worldguard

**Comment by Tyrantin** [comment]
That sounds like a World Guard problem....

**Comment by denwd** [comment]
before writing, examine the code, and how that happens

**Comment by zmaster587** [comment]
I think Tyrantin is correct.  Sounds like worldguard not allowing mounting.

Worldgaurd usually works by intercepting block places/rightclicks/leftclicks and checks internally to see if it's allowed.

**Comment by denwd** [comment]
I've done it before, I will have to add code rockets make this work((((((((((
![1](https://cloud.githubusercontent.com/assets/3863970/24826893/f8ac219e-1c59-11e7-824b-2b4fd9db30d2.jpg)

**Comment by zmaster587** [comment]
Have you tried setting interact to allow?

**Comment by denwd** [comment]
I forbid all that is possible. But it didn't help, I had to change the server and the client + to connect to the api make this work.
