### ISSUE TITLE
Holographic Planet Selector

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#518]
I so love this idea! Amazing..... Was just wondering if you could fix it..... lol

![2017-04-07_06 51 08](https://cloud.githubusercontent.com/assets/8041616/24797301/ac9f2a22-1b5e-11e7-8de0-31208a7ee48f.png)
![2017-04-07_06 51 12](https://cloud.githubusercontent.com/assets/8041616/24797304/afd32d2e-1b5e-11e7-87c3-4d0a4567d25f.png)
![2017-04-07_06 51 17](https://cloud.githubusercontent.com/assets/8041616/24797306/b1ce72dc-1b5e-11e7-8e79-4dfb7e4acaa2.png)
![2017-04-07_06 51 28](https://cloud.githubusercontent.com/assets/8041616/24797307/b38468f2-1b5e-11e7-9645-aaf525820c34.png)
![2017-04-07_06 51 32](https://cloud.githubusercontent.com/assets/8041616/24797308/b5301eda-1b5e-11e7-89f5-128c378c616b.png)

**Comment by zmaster587** [comment]
What build are you running?

**Comment by Tyrantin** [comment]
1.1.3

**Comment by zmaster587** [comment]
I think it was fixed in 1.1.4. It was brought up by someone else recently

**Comment by Tyrantin** [comment]
Do you have a couple min to chat?

**Comment by zmaster587** [comment]
Not currently no.  I will in about 4 hours though

**Comment by Tyrantin** [comment]
ok I will be on!

**Comment by Tyrantin** [comment]
I'm on discord because I don't know your TS

**Comment by zmaster587** [comment]
Ts is currently offline anyway, I'll be on when I get to a computer
 (~30-60 minutes )

**Comment by Tyrantin** [comment]
ok
