### ISSUE TITLE
Rolling machine rendering crash

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#52]
When trying to make other mods plates from ingots
http://pastebin.com/xCgNsMKE

I guess the lathe would have the same problem

**Comment by zmaster587** [comment]
I appear to have neglected to handle materials I do not explicitly support.

**Comment by wormzjl** [comment]
Perhaps just let everything else that are not on the list show white color

**Comment by zmaster587** [comment]
Looking into just taking the average color of the icon and using that
