### ISSUE TITLE
How to change/delete default recipes in machines?

### ISSUE THREAD

**Issue by MoDDyChat** [zmaster587/AdvancedRocketry#520]
I want to change some recipes in machines, but instead I just add one more. This is quite an important part of my modpack, so I'm interested in how it's possible to change recipes.
Thank you for attention

**Comment by zmaster587** [comment]
Are you using the alpha build?
Does the output exactly match the output of the recipe you wish to modify?

**Comment by MoDDyChat** [comment]
I am using: 1.0.15. As I understand it is not alpha.
Probably it is influenced by the fact that in XML I put as a result of the itemstack format, and in game put oredict format.

`<Recipes>
    <Recipe timeRequired="10" power="50">
        <input>
            <oreDict>ingotIron 4</oreDict>
        </input>
        <output>
            <itemStack>libvulpes:productplate 1 1</itemStack>
        </output>
    </Recipe>
</Recipes>`

http://imgur.com/a/qBkQm

**Comment by zmaster587** [comment]
It only overwrites a recipe if the inputs are the same.  Unfortunatly there's no way for the program to know whether you intend to overwrite an existing recipe or just add a new one for the same output.

What you'll have to do I think is to use <Recipes useDefault="false">  and fill in the other recipes.

I do not know how well this'll work for you, but I have (and the alpha builds will generate) an XML copy of all the recipes used which I've attached for convience.

Github does not like XMLs, so you may need to change the extension
[RollingMachine.txt](https://github.com/zmaster587/AdvancedRocketry/files/907106/RollingMachine.txt)

**Comment by MoDDyChat** [comment]
It works as it should, thanks a lot for the XML file. If you have files of other machines, then I would be very grateful. Although, if not, then still a big thank you to you. Typically, mod developers respond days and weeks.

There is also another small question. Is it possible in any way to modify or completely delete the recipes of a small plate press, except how to remove the recipe of the block itself? (Sorry for my bad English)

**Comment by zmaster587** [comment]
I do have files for the other machines, yes.

[ChemicalReactor.txt](https://github.com/zmaster587/AdvancedRocketry/files/907575/ChemicalReactor.txt)
[Crystallizer.txt](https://github.com/zmaster587/AdvancedRocketry/files/907570/Crystallizer.txt)
[CuttingMachine.txt](https://github.com/zmaster587/AdvancedRocketry/files/907573/CuttingMachine.txt)
[ElectricArcFurnace.txt](https://github.com/zmaster587/AdvancedRocketry/files/907572/ElectricArcFurnace.txt)
[Electrolyser.txt](https://github.com/zmaster587/AdvancedRocketry/files/907571/Electrolyser.txt)
[Lathe.txt](https://github.com/zmaster587/AdvancedRocketry/files/907574/Lathe.txt)
[PrecisionAssembler.txt](https://github.com/zmaster587/AdvancedRocketry/files/907576/PrecisionAssembler.txt)

Currently there is no way to modify the recipes for the small plate press, but I'll look into changing that.
