### ISSUE TITLE
[Suggestion] Show planet ring on the overworld if hasRings=true

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#522]
Currently the ring can be seen from the space but not on the overworld
Is this possible without adding some ASM?

**Comment by zmaster587** [comment]
It is doable.  But if another mod tries to override the skyrenderer only
one will work.  Though it's not like that's not already the case with other
planels

**Comment by DVorriose** [comment]
Could you render it for moons of a planet with rings?

**Comment by zmaster587** [comment]
It should already do that.  Should look something like
http://65.78.115.159:8000/img/minecraft/2016-12-30_23.47.10.png

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
