### ISSUE TITLE
Models of planets

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#527]
Planet models

Can I somehow setup/change the picture/model of planets? Are there some default we can pick from? Can we somehow import our own?

Thanks, Darai

**Comment by zmaster587** [comment]
you can probably do this via a resource pack.  The planet image files are located in "assets/advancedrocketry/textures/planets/".  LEO is displayed when on a space station and from the holo planet selector.  The non-LEO textures are used in the planet selector and when displaying the planet in the sky.  There are a few unused textures in there such as waterworld, lava, and gasgiantOrange.  The Atmosphere and shadow textures are kinda more technical and use to put shadows and atmosphere on the rendered planets respectively

**Comment by gdarai** [comment]
Hi,
I see there are multiple pictures.
How do you decide, which picture will be selected for which planet? Is there something in the planetDefs config to set this? Or which mechanism is used?

**Comment by zmaster587** [comment]
Right now it's a function of atmosphere pressure and distance to the host star.
Code here: https://github.com/zmaster587/AdvancedRocketry/blob/master/src/main/java/zmaster587/advancedRocketry/dimension/DimensionProperties.java#L341

**Comment by zmaster587** [comment]
Updated Docs for next build http://65.78.115.159:8000/AdvancedRocketry/config/AdvancedPlanetConfiguration.php#customIcon
