### ISSUE TITLE
Moon shown as red?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#528]
![image](https://cloud.githubusercontent.com/assets/2989009/24831545/c9471692-1c9b-11e7-945e-0b18473284df.png)

Here is my planet definition, is there anyway I can change it?
https://pastebin.com/Hi37bGTU

Might be related to https://github.com/zmaster587/AdvancedRocketry/issues/527

**Comment by wormzjl** [comment]
ok I think I'll wait for the new version :3

**Comment by zmaster587** [comment]
I think temperature is screwed up with loading from XML
