### ISSUE TITLE
Can't add 2 moons to a single planet?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#530]
![image](https://cloud.githubusercontent.com/assets/2989009/24833216/00878d64-1cc2-11e7-90f9-ba50bf9d18ba.png)

With

        <planet name="Alpha Centauri B III" DIMID="15">
            <fogColor>1,1,1</fogColor>
            <skyColor>0,0,0</skyColor>
            <GasGiant>true</GasGiant>
            <atmosphereDensity>190</atmosphereDensity>
            <gravitationalMultiplier>150</gravitationalMultiplier>
            <orbitalDistance>160</orbitalDistance>
            <orbitalTheta>45</orbitalTheta>
            <rotationalPeriod>95000</rotationalPeriod>
            <hasRings>true</hasRings>
            <isKnown>false</isKnown>
            <planet name="Alpha Centauri B III Moon 1" DIMID="16">
                <fogColor>1,1,1</fogColor>
                <skyColor>0,0,0</skyColor>
                <atmosphereDensity>20</atmosphereDensity>
                <gravitationalMultiplier>30</gravitationalMultiplier>
                <biomeIds>95</biomeIds>
            </planet>
            <planet name="Alpha Centauri B III Moon 2" DIMID="17">
                <fogColor>1,1,1</fogColor>
                <skyColor>0,0,0</skyColor>
                <atmosphereDensity>20</atmosphereDensity>
                <gravitationalMultiplier>30</gravitationalMultiplier>
                <biomeIds>24</biomeIds>
            </planet>
        </planet>

Is there anything wrong?

**Comment by zmaster587** [comment]
Try setting the orbital distance for each moon.  I think I added code to prevent multiple bodies with the same orbital distance from being added to the same parent body.

**Comment by wormzjl** [comment]
Tried to set it's orbital distance, and they appeared in the wrong solar system (the first solar system instead of the second)

Full code
https://pastebin.com/btwXdf9t

**Comment by zmaster587** [comment]
Does it have both moon even though it's in the wrong system?

**Comment by wormzjl** [comment]
Yeah, both moon and it's mother planet moved to system A instead of system B
