### ISSUE TITLE
Weird worldgens

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#531]
![image](https://cloud.githubusercontent.com/assets/2989009/24835620/f29d58b0-1d06-11e7-9b2e-bd769badf987.png)
![image](https://cloud.githubusercontent.com/assets/2989009/24836521/891202de-1d1e-11e7-96a6-33be8ad7ec6a.png)
![image](https://cloud.githubusercontent.com/assets/2989009/24836828/bbc59490-1d26-11e7-980e-c8460e6386f4.png)

skycreeping single chunks on different worlds

**Comment by wormzjl** [comment]
![image](https://cloud.githubusercontent.com/assets/2989009/24836492/8fb6cc42-1d1d-11e7-90c3-5835287528a8.png)
and this

**Comment by wormzjl** [comment]
Getting a lot of these in the console while exploring other planets, might be related?
https://pastebin.com/qrRLraWP

**Comment by zmaster587** [comment]
That's probably related.  If you stand on the weird generation and look at the biome in F3, what biome is it and what do you expect it to be?

**Comment by wormzjl** [comment]
this one is not ocean...
![image](https://cloud.githubusercontent.com/assets/2989009/24837958/8de6514a-1d3f-11e7-808b-1cb0186a0f29.png)

**Comment by zmaster587** [comment]
How frequently do these oddities occur?  Are you running any other terrain generation mods?

**Comment by wormzjl** [comment]
I've been flying randomly and these occurs every few minutes, so i'd say it's quiet rare
I have been using terrafirmacraft, but it shouldn't affect worlds other than the overworld

**Comment by zmaster587** [comment]
Very strange... these planets have not been terraformed have they?

**Comment by wormzjl** [comment]
nope

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
