### ISSUE TITLE
How to change the generation of caves

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#533]
Good afternoon, how can I change the generation of these caves?to reduce the radius or that they are generated, or disable altogether. Just there's a lot of resources it brings imbalance to the game and the economy.
![cave](https://cloud.githubusercontent.com/assets/3863970/24836478/59d318ec-1d36-11e7-9ccc-8f526e5c2c08.jpg)

**Comment by zmaster587** [comment]
will add a config

**Comment by denwd** [comment]
Can you tell how?or you add?

**Comment by zmaster587** [comment]
There is currently no way to disable or change the sizes of the structures, so I'm going to add something to the config so you can, disable and/or change the size of them.  

Also as a note you should not be able to get into them without a jackhammer or creative.

**Comment by denwd** [comment]
that would be great))when can we expect ?the mod is very cool but it need balancing on the resources he gives

**Comment by zmaster587** [comment]
About now

**Comment by denwd** [comment]
Thank you very much)
