### ISSUE TITLE
Unmanned Rocket Dupe

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#534]
I am having another issue. When I log out and then log back in I have UMR's Waiting to get into my Hanger. I then Disassemble the UMR's that are their but they Don't want to Disassemble I have to keep Clicking on them and hit the Dis Button Repeatedly to finally get them to complete the action. Let me know what you want me to send you... :(

**Comment by zmaster587** [comment]
What version are you running?

**Comment by zmaster587** [comment]
Nevermind, found the issue, forgot about the 2nd internal sat list
