### ISSUE TITLE
Dupe satellite

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#535]
This dupe only if you launch from other planets.
if you launch a satellite from another planet, then returns the rocket and the satellite, thus it is infinite.

if you orbit everything is OK
from the ground everything is OK

**Comment by zmaster587** [comment]
Are you saying if you launch a satellite from one planet, but the rocket has another planet set as a destination then the satellite is launched and the rocket lands on the destination planet with the satellite still in the satellite hatch?

**Comment by denwd** [comment]
yes))that is just from another planet

**Comment by denwd** [comment]
Thank you)
