### ISSUE TITLE
Custom worlds beyond the first in file not loading or following Dim ID

### ISSUE THREAD

**Issue by Saereth** [zmaster587/AdvancedRocketry#536]
using version 1.1.4b for mc 1.10.2
I created a custom xml for some planets and set the config to rebuild from xml, then I made a fresh world. Only the first planet in the XML shows up on the /advancedrocketry planet list. Additionally the Dimids I set are completely ingored and it assigned the first planet (Risa) a random dimid

Here is my XML file contents
https://hastebin.com/uzirohacif.xml

Let me know if I can provide any more information

**Comment by zmaster587** [comment]
Would it be at all possible to post the fml log from the first startup with
that xml?

**Comment by Saereth** [comment]
Yeah I just deleted that save got a fresh log, here ya go
https://www.dropbox.com/s/z5kphkkwgatr1lt/latest.log?dl=0

**Comment by zmaster587** [comment]
Alright, XML looks alright.  I started it up with a new world on my end and I'm see all the planet show up plus 6 randoms and two gas giants.  So it seems everything is working ok there for new worlds.  Only odd thing I see is that Earth is present and it shouldn't be.

When you created the world was it immediatly after you launched the game such that you didn't just close another save or something?

**Comment by Saereth** [comment]
yeah I exited the game and completely deleted the save folder, I'll try changing the orbital distance so they're more varied and within 200 but they werent even showing on /advancedrocketry planet list.

**Comment by zmaster587** [comment]
Strange... they were for me when I loaded it from a cold start...

**Comment by Saereth** [comment]
ok so I fixed all the orbital distances, shut down the client, deleted the save folder and made a new world, still the same thing:
http://imgur.com/a/VU3G3

revised XML:
https://hastebin.com/bovizukoha.xml

**Comment by zmaster587** [comment]
I'll try it with that one after lunch

**Comment by zmaster587** [comment]
after replacing the XML, then launching minecraft from the launcher.  I keep getting this:
![image](https://cloud.githubusercontent.com/assets/3536685/24839187/e2325e0e-1d23-11e7-93a5-2a5b413b7bd3.png)
I've launched it 4 times now with the same result.

What happens if you change "numPlanets" and "numGasGiants" to 0 and try again?
Do you only get one planet total?

**Comment by Saereth** [comment]
didnt change it,
MinDimension=2
Here is my entire config: https://hastebin.com/gawujiveba.coffeescript

also changed the settings you suggested in the xml, same thing basically on another fresh world

http://imgur.com/a/5C5ey

**Comment by Saereth** [comment]
ok some progress, I got it working
http://imgur.com/a/piCeL

in the root folder of the pack above the config and world folders you create a folder called advRocketry with a temp.dat file in it. I dont know what this file does but being as its outside of the saves it's most likely applying to any and all new worlds created I'd assume. Anyway, deleting this file and letting it recreate with the modified XMLs worked perfectly. 

My two questions now are, is it safe to simply delete that file if you added worlds to an existing save? And how will this impact a server that's already been running if I delete this file?

**Comment by zmaster587** [comment]
That's kinda an odd location.  It should generate in the world/advRocketry

But to answer your question it depends on how the server has been used so
far.  That file contains info about planets, space stations, and
satellites.  So as long as no satellites have been launched, no space
stations have been made, and no planets have been visited there won't be
any impact at all.

Because of this I'd recommend deleting the dim folder for any planets abd
the space dimesion if they have been used otherwise you might have station
builds overlap and odd terrain gen on any existing planet

**Comment by Saereth** [comment]
Well a couple players have made space stations, would it be possible for them to relaunch and me move the region data for them back in manually after I delete?

**Comment by zmaster587** [comment]
If they are relaunched in order of id.  Though if resetfrom XML is set to
true in the config then it should do all of this for you and it would
preserve stations and reset planet info to whatever is in the xml

**Comment by Saereth** [comment]
ok I'll give that a shot

**Comment by zmaster587** [comment]
Please let me know how it turns out so I can know whether or not to close the issue.

**Comment by Saereth** [comment]
Ok this seemed to be working, deleting the advRocketry folder. just to clarify an earlier post, advRocketry folder is in the world folder on servers which is good, only in single player is it outside the saves folder so all that data in advRocketry applied towards every new game you create which is not always desirable if you've changed the xml between worlds etc.

**Comment by zmaster587** [comment]
Did resetFROM XML not work?

AlsI I'm not really sure how to fix the different XML for different world
problem short of copying the XML from the config folder to the world folder
upon first load then using the one in the world folder from thereon out.  I
feel like doing that would be a bit confusing though.

**Comment by Saereth** [comment]
reset from xml didnt work in single player no, not till I deleted the advanced rocketry folder. On the server I didnt try reset xml without deleting the folder first but it did work using that

**Comment by zmaster587** [comment]
Arlight, will investigate that
