### ISSUE TITLE
Not full landing rockets

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#537]
Another bug, sometimes the rocket gets to the end, because of this, it cannot be reused, have to take it apart and put it back together again.

Sometimes rockets for unknown reasons hang in the air at a great height, and when the next flight of the rocket they get stuck there on the old rocket.
You can add debugging to the event landing?

Oh my bad English)

**Comment by zmaster587** [comment]
can the rockets getting stuck in the air be replicated on demand (may be a rocket built a specific way), if so what blocks are on the rocket from AR (seat, guidance computer satellite hatches, etc)

**Comment by denwd** [comment]
I don't know what part of the rocket, but the rocket drill was stuck

**Comment by zmaster587** [comment]
I just need to know what's on the rocket and what's in the guidance computer.  Different parts being prescent or absent on the rocket change its behavior

**Comment by denwd** [comment]
ok)

**Comment by denwd** [comment]
When planting eject the player and remains hanging there, but if it is to fly, sit down and press space it will sit.

![2017-04-10_12 01 20](https://cloud.githubusercontent.com/assets/3863970/24849700/747c4c80-1de6-11e7-9d80-87da6cf54cdf.png)
![2017-04-10_12 01 21](https://cloud.githubusercontent.com/assets/3863970/24849699/747bc3dc-1de6-11e7-9f1c-4c58e887b2c3.png)
![2017-04-10_12 01 24](https://cloud.githubusercontent.com/assets/3863970/24849697/747a34fe-1de6-11e7-953a-527a9e590e99.png)
![2017-04-10_12 01 27](https://cloud.githubusercontent.com/assets/3863970/24849701/747c53d8-1de6-11e7-850f-c557d611631e.png)
![2017-04-10_12 01 30](https://cloud.githubusercontent.com/assets/3863970/24849702/74831ede-1de6-11e7-85e7-aabadba82ab5.png)
![2017-04-10_12 03 53](https://cloud.githubusercontent.com/assets/3863970/24849698/747add96-1de6-11e7-9554-d5f5c64b8072.png)
![2017-04-10_12 03 54](https://cloud.githubusercontent.com/assets/3863970/24849703/7497df68-1de6-11e7-82fd-af04d6f1c283.png)
![2017-04-10_12 03 55](https://cloud.githubusercontent.com/assets/3863970/24849704/74991932-1de6-11e7-8fe0-141b71acbaaf.png)
![2017-04-10_12 03 56](https://cloud.githubusercontent.com/assets/3863970/24849705/7499b950-1de6-11e7-99b1-d0e525d98e8c.png)

**Comment by zmaster587** [comment]
Sorry, still having a hard time understanding, just to clarify.  Are you saying that "if the player hits the shift key to get off the rocket, the rocket just stays in one spot and does not move, but to land the player must sit and hit space"?

**Comment by denwd** [comment]
1 He flew to the station from the ground
2 He flew into orbit and left it out with missiles
3 Reached a jetpack to rocket he got into it, pressed space and it went down

This bug randomly

**Comment by zmaster587** [comment]
I'M not following where the abnormal behavior is occurring.  The rocket is
supposed to stay there until a player riding it hits the space bar to begin
descent.  This was implemented so the player does not crash into the planet
if they are running a slow computer

**Comment by denwd** [comment]
the problem is that they eject from the rocket,even before you press the space bar and they fall. Rocket stays there and clinging for her other

**Comment by zmaster587** [comment]
Perhaps if the rockets would descend after some set timeout, say 30
seconds...

**Comment by denwd** [comment]
I have no ideas how to fix it(

**Comment by zmaster587** [comment]
I mean if in the next update the rockets would descend if left alone too
long

**Comment by denwd** [comment]
Let's try to make the fix, I'll play around

**Comment by denwd** [comment]
![2017-04-11_01 28 28](https://cloud.githubusercontent.com/assets/3863970/24881481/594afae4-1e57-11e7-9099-c13c707d8e98.png)

**Comment by zmaster587** [comment]
Context?

**Comment by denwd** [comment]
Began to appear frequently rockets that landed.

**Comment by denwd** [comment]
Have you seen this bug?
https://github.com/zmaster587/AdvancedRocketry/issues/545

**Comment by zmaster587** [comment]
I have seen it

**Comment by zmaster587** [comment]
the rockets are teleporting upward?

**Comment by denwd** [comment]
Yes, it happens, below the above, but it has a completely different bug)

**Comment by denwd** [comment]
A big problem with the fact that they don't land, throwing out the pilot

**Comment by zmaster587** [comment]
can it be replicated?

**Comment by denwd** [comment]
Good day, thank you I will test

**Comment by denwd** [comment]
thanks all ok
