### ISSUE TITLE
Rockets and gas shuttles stacking every start of MineCraft

### ISSUE THREAD

**Issue by jonabrv1965** [zmaster587/AdvancedRocketry#538]
Hi Master, once again me... I'm having though times with this glitch. Every time I reload Minecraft it appear another ship stacked over/under/beside the last one. See images. (I had been deleting the ships, but is becoming an issue because the rockets came full of ores and every time I dissemble/destroy one I got tons of ores everywhere, generating a very high lag)

![2017-04-09_12 18 58](https://cloud.githubusercontent.com/assets/13445986/24839463/49925c38-1d20-11e7-8c41-92be5854f3e0.png)

![2017-04-09_12 20 55](https://cloud.githubusercontent.com/assets/13445986/24839470/6bd536f8-1d20-11e7-8df3-f466c9bd04d7.png)

As a matter of fact I found rockets as high as Y=270 with the engines on (see image)

![2017-04-09_12 20 34](https://cloud.githubusercontent.com/assets/13445986/24839465/4efa979e-1d20-11e7-8c5a-a7ffef264c7c.png)

Versions : AdvancedRocketry-1.10.2-1.0.15, LibVulpes-1.10.2-0.1.17-universal, forge 2254...

**Comment by jonabrv1965** [comment]
Keep in mind that the rockets keep their shape and are "formed", there are no rocket parts anywhere..

**Comment by zmaster587** [comment]
I fixed it earlier today, should be fine next release

**Comment by zmaster587** [comment]
#534
