### ISSUE TITLE
Atmospheric Terraformer seems not working

### ISSUE THREAD

**Issue by jonabrv1965** [zmaster587/AdvancedRocketry#539]
Hi Master, I have two terraformers in different planets (actually one in the earth's moon and other in a planet with a high atmosphere) and both show the same behavior : the multiblock forms itself ok (very nice models as usual!) I insert the nitrogen and oxygen gases (the 4 fluid hatches are full, two with O2 and two with Ni) the energy metter is full, when I start the machine the led become green... so far s good, I close the GUI but if I open it (immediately) the machine appears shutdown (led in red) and no go, no nothing.... I've tested leaving the gui open (with the led in green) for a couple of hours but nothing happen... what I'm doing wrong? 

Versions : AdvancedRocketry-1.10.2-1.0.15, LibVulpes-1.10.2-0.1.17-universal, forge 2254...

**Comment by zmaster587** [comment]
If you disable fluid consumption in the config does this still occur?

**Comment by jonabrv1965** [comment]
YES, it works now. I changed this in the config : "    B:TerraformerRequiresFluids" to false, et voila.
Seems like you have another glicth in your awesome mod! :-)

**Comment by zmaster587** [comment]
It may also just be the fluid requirements are too high.  I put it somewhere like 2 maxed out diamond fluid pipes from BC.  I'll try playing with it see if that's the issue.

**Comment by jonabrv1965** [comment]
BuildCraft? in 1.10.x? how? I use pressurized fluid conduits from enderIO

**Comment by zmaster587** [comment]
The terraformer was implemented and balanced in 1.7.10

**Comment by zmaster587** [comment]
I'll add a config so the rate can be specfiied
