### ISSUE TITLE
Each time upon entering an existing or new world, I got this in the output of my crafting grid

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#54]
Asm conflict?
![image](https://cloud.githubusercontent.com/assets/2989009/11824459/55a03018-a382-11e5-8d98-35b215f215bb.png)

It can be taken out and placed, but if I leave it there, next time when I open my inventory it dissappears

**Comment by zmaster587** [comment]
Does this occur with only AR, libvulpes, and buildcraft?
The only ASM I do is intercepting block changes and I do not modify the crafting system whatsoever.

**Comment by wormzjl** [comment]
yes

**Comment by zmaster587** [comment]
Forge version?

**Comment by wormzjl** [comment]
tested with 1492 and 1566, both the same

**Comment by zmaster587** [comment]
Investigating

**Comment by zmaster587** [comment]
Appears to be some strangeness with the recipe
