### ISSUE TITLE
Request: Ability to whitelist mobs surviving various conditions

### ISSUE THREAD

**Issue by Divineaspect** [zmaster587/AdvancedRocketry#541]
Some mobs should logically be able to survive hostile environmental conditions, especially modded mobs.

**Comment by zmaster587** [comment]
I believe there's already a config for that. Idr what it is off the top of
my head.  I'll get the name when I get back to a computer

**Comment by zmaster587** [comment]
"entityAtmBypass" property.  Take unlocallized entity names
