### ISSUE TITLE
Incorrect Speeds for Arc Furnace

### ISSUE THREAD

**Issue by greenking13** [zmaster587/AdvancedRocketry#543]
Alright, so a few days ago I asked you about the various speeds for the tiers of coils, and you responded with

> As for coil Teirs:
Gold: reduces time by 10% per coil
Aluminum: reduces time by 20% per coil
Titanium: reduces time by 25% per coil
Iridium: reduces time by 50% per coil
The reducations also stack: such that 3 iridium coils yields (1-(0.5)^3) = 87.5% time reduction

Unfortunately, from what I can see in game with the latest version of both libvulpes and Advanced Rocketry, what I am seeing is
Copper: 1.00x
Aluminum: 1.00x
Gold: 1.37x
Titanium: 2.37x
Iridium: 1.00x

When you have 3 of the same type inside the arc furnace. Also, the formula you gave, are you sure that that is correct? Since it would seem that the increase would be most beneficial with gold, ending up being 99.9% time reduction.

**Comment by zmaster587** [comment]
Gold would be (1-0.9^3) as gold takes processing time to 90% it's original time (10% reduction per coil).

I'll see if i can figure out what's going on with the iridium block

**Comment by greenking13** [comment]
Alright, so I think I understand where I went wrong in the calculation bit at least, I thought that the 0.5 you had placed was the 50% you had stated that iridium reduced by, but it's rather the remaining out of 100. So, for example, the for aluminum it would be (1-(0.8)^3)=48.8% time reduction.

**Comment by zmaster587** [comment]
I should not have used an ambiguous number and probably explined it a bit
more thouraghly

**Comment by zmaster587** [comment]
is this with MC 1.7.10 or MC 1.10.2?

**Comment by greenking13** [comment]
Terribly sorry, it's for 1.10.2. (Could have sworn I had placed that in the title... maybe that was a different issue. Gah.)

**Comment by zmaster587** [comment]
Darn spelling errors in my code.
