### ISSUE TITLE
advancedRocketry givestation [stationID] 

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#544]
Gives a blank chip

**Comment by zmaster587** [comment]
What is the exact command you are entering?

**Comment by denwd** [comment]
/advancedRocketry givestation 3

station 3 exists

**Comment by zmaster587** [comment]
Some infrastructure changes in the 1.7.10 builds wents unnoticed.  Caused by using the old getDamage() method for determining station ID rather than the more up to date NBT method
