### ISSUE TITLE
(1.10.2 1.1.5) Space Station builder doesn't work

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [zmaster587/AdvancedRocketry#548]
I can't seem to get the space station builder to work and I need a space station ID chip for Station 1 so I can send rockets to and from the station.
Can I have a command for it? I'm running 1.10.2, AR version 1.1.5/

**Comment by zmaster587** [comment]
First off, what are you trying to do with the space station builder and what's not working about it.  Second off the command "/advancedRocketry givestation 1" should give you a chip for station 1

**Comment by Tyrantin** [comment]
Post a pic of your set up if you could plz. I set mine up and it worked flawlessly. It's possible that you have it set up wrong.

**Comment by AGiLE-EaGLE1994** [comment]
I was trying to build a small space station, so I could get a programmed station chip and edit the chip's NBT so it would be a station 1 chip, that way I could use rockets with my warp ship.
I had a pad around 6x6 with a tower about 5 blocks tall, I had the tower on the same level as the pad so that the tower's first block was touching the side of the pad.
I also had the station assembler with the correct side facing outwards, and a coal generator to power it.
I could put the satellite bay and chip in the assember slots, but when I click build, it consumes one of both items and does nothing after that. I don't know if I'm just lagging really bad or what.
I'm running this on my laptop, which has pretty decent specs.
I already destroyed the pad and scanner because I somehow managed to get it working in another situation. Do the assemblers work in space? If they don't, that would explain my problem. I was trying to build a shuttle in the hangar of my warp ship. I disabled fuel and set the per-engine thrust multiplier to 64 because I didn't want thrusters to be visible on the bottom of the shuttle.
I managed to get it working elsewhere, but I can't remember if it was on another world or another dimension in the same world I was having the issue in. Perhaps it's an issue with my world or that ship in specific?

**Comment by Tyrantin** [comment]
I don't believe so. Honestly in order to build a ship it stands to reason that you would start on the planet to launch a station...

**Comment by Tyrantin** [comment]
Also, anything you build on the station or not connected to the station but in that dimension is connected regardless. Meaning if you try and move the shuttle it's going to move the station as well. Already been over this with Zmaster. It's something that would take major work to get accomplished to be able to separate them from the station. But then you're also talking major lag due to having two entities within the same vicinity.

**Comment by zmaster587** [comment]
I don't think there's anything preventing rockets being built on spacestations other than the normal requirements, there's definatly no check for dimid in the assembler.  And if it comsumed the items it definately started. Did you run a scan first?  Did you open the multiblock to see if it actually has power/progress?

**Comment by AGiLE-EaGLE1994** [comment]
I also can't get rockets to launch even after I use a planet ID chip or station ID chip, whether it's programmed for a planet orbiting the one I'm on or not.
Like, if I'm on Earth with a chip for Luna, and try to launch with it, it won't take off, but it does ignite the engine, it just doesn't fly up. I can't get rockets to actually get off the ground no matter what I do.
So I don't know what to do. D:
It doesn't matter what planet/station the chip is programmed for, the rocket won't lift off even IF the chip is for a station or moon orbiting the planet I'm trying to take off from. I don't know if it's a mod conflict or what.

**Comment by zmaster587** [comment]
What was the acceleration rating for the rocket in the assembler.  Also are
you sure there are no blocks in top of it holding it down?

**Comment by AGiLE-EaGLE1994** [comment]
Acc:-.27
Thrust:450
Weight:223

**Comment by zmaster587** [comment]
you shouldn't be able to successfully build a rocket with negative acceleration to avoid this exact issue.
It looks like it's too heavy to fly.

**Comment by zmaster587** [comment]
So turns out the configuration affected the thrust in the assembler, but not of the rocket itself.  That'll be fixed in the next release

**Comment by AGiLE-EaGLE1994** [comment]
Also, I noticed a rendering issue in the alpha version with the planets when I'm in orbit.
The planet jitters and spazzes like crazy.
Do you know the cause of this?

**Comment by AGiLE-EaGLE1994** [comment]
I think I know what caused the issue: I deleted an unwanted station with an NBT editor. Do you think that could be the problem?
