### ISSUE TITLE
Crash on selecting destination

### ISSUE THREAD

**Issue by qwryzu** [zmaster587/AdvancedRocketry#550]
When I build a rocket and try to select the destination (using the Select Dst button, if I use the guidance computer with an Asteroid Chip there's no problem) the game freezes for a second then crashes to the launcher and gives me this:

The game crashed whilst rendering screen
Error: java.lang.StringIndexOutOfBoundException: String index out of range: -1

I am playing with a lot of other mods but so far that hasn't caused any issues with this one so I don't know if that's relevant.

EDIT: Also forget to mention that I'm using 1.10.2-1.0.16

**Comment by zmaster587** [comment]
Can you provide the entire crash-report or at least the stack trace?

**Comment by qwryzu** [comment]
[crash-2017-04-11_14.54.36-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/914771/crash-2017-04-11_14.54.36-client.txt)

Here you are.

**Comment by zmaster587** [comment]
Looks like an issue with NEI trying to draw something
