### ISSUE TITLE
The server stops responding when generating 94 biomes

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#551]
When the biome is loaded with ID 94, the server stops responding to commands. Players writes "timed out". There were no errors in the log.
We removed 94 biome in temp.dat. That helped.
Adding this biome to the blacklist had no effect.

**Comment by zmaster587** [comment]
Which biome is 94 in your setup

**Comment by denwd** [comment]
but where to look?

**Comment by denwd** [comment]
planet {
    # Dimensions including and after this number are allowed to be made into planets [range: -127 ~ 8000, default: 2]
    I:minDimension=2

    # Prevents any vanilla biomes from spawning on planets [default: false]
    B:blackListVanillaBiomes=false

    # Biomes that only spawn on worlds with pressures over 125, will override blacklist.  Defaults: StormLands, DeepSwamp [default: [96], [94]]
    S:HighPressureBiomes <
        96
        94
     >

    # List of Biomes to be blacklisted from spawning as BiomeIds, default is: river, sky, hell, void, alienForest [default: [7], [8], [9], [127], [91]]
    S:BlacklistedBiomes <
        7
        8
        9
        127
        91
     >

    # Some worlds have a chance of spawning single biomes contained in this list.  Defaults: deepSwamp, crystalChasms, alienForest, desert hills, mushroom island, extr
    S:SingleBiomes <
        96
        95
        91
        17
        14
        3
        12
     >
}

**Comment by denwd** [comment]
# Biomes that only spawn on worlds with pressures over 125, will override blacklist.  Defaults: StormLands, DeepSwamp [default: [96], [94]]
    S:HighPressureBiomes <
        96
        94
     >

    # List of Biomes to be blacklisted from spawning as BiomeIds, default is: river, sky, hell, void, alienForest [default: [7], [8], [9], [127], [91]]
    S:BlacklistedBiomes <
        7
        8
        9
        127
        91
     >

    # Some worlds have a chance of spawning single biomes contained in this list.  Defaults: deepSwamp, crystalChasms, alienForest, desert hills, mushroom island, extr
    S:SingleBiomes <
        96
        95
        91
        17
        14
        3
        12
     >
}

**Comment by zmaster587** [comment]
Do you have any mods installed that add any biomes and can you post the
server log?

**Comment by denwd** [comment]
Only this mod, but it only works in standard worlds
https://mods.curse.com/mc-mods/minecraft/237989-realistic-terrain-generation

**Comment by zmaster587** [comment]
If you remove everything other than AR and libvulpes, does the hang still
occur?

**Comment by denwd** [comment]
https://pastebin.com/Mc5ZkzH0

**Comment by denwd** [comment]
If you remove everything other than AR and libvulpes, does the hang still
occur?

NO

**Comment by zmaster587** [comment]
Can you then try adding back mods one at a time or in small clumps to try to determine which is causing the interaction?

**Comment by denwd** [comment]
Yes I'm doing it right)

**Comment by denwd** [comment]
Found mod which conflict CustomNPCs_1.7.10 d(21feb16), 

But in that area no NPCs

**Comment by zmaster587** [comment]
How was it conflicting?  Biome ID conflict?  some other conflict?

**Comment by denwd** [comment]
n the transition to a biome I:stormLandsBiomeId=94, the server stops responding, no error, if you remove the mod at PS everything is OK

**Comment by zmaster587** [comment]
remove the mod at PS?  What is PS?

**Comment by denwd** [comment]
If I remove the mod at NPC then everything is OK

**Comment by denwd** [comment]
Google translation)

**Comment by zmaster587** [comment]
Alright.  I don't think this is a problem with advanced rocketry.  But I'll check it out just to make sure.

**Comment by denwd** [comment]
http://rgho.st/8WCBPYWWl  dim 49   ([advRocketry/DIM49] -3583.5, 1000.5, 4608.5)

**Comment by zmaster587** [comment]
I'm not sure exactly what it's doing but it looks like customNPC's worldGenSpawning function is either running way longer than it should be, or infinitely
![nop](https://cloud.githubusercontent.com/assets/3536685/24932379/4d06700a-1edf-11e7-9cc1-6323f39ceb5e.png)

[visualVMProfileDump.zip](https://github.com/zmaster587/AdvancedRocketry/files/914762/visualVMProfileDump.zip)

**Comment by denwd** [comment]
What all can it do?to prohibit the generation of a biome?

**Comment by zmaster587** [comment]
Either that or remove customNPCs.  But customNPCs doesn't handle biomes that have a 100% spawn chance for an entity.
