### ISSUE TITLE
My space station is no longer orbiting any planet. Warp controller GUI not open-able, rocket cannot take off (destination unselectable)

### ISSUE THREAD

**Issue by marcus2518** [zmaster587/AdvancedRocketry#552]
![2017-04-11_23 07 10](https://cloud.githubusercontent.com/assets/11601669/24939504/caf88922-1f0b-11e7-8fc2-4a0c00e41815.png)

My server admin recently added new planets or something and had to restore my space station from backup files. TL:DR, it is not orbiting any celestial body and any warping/travelling option seems to be unavailable. For the warp controller, GUI will not open on right click. For the rocket, cannot open select destination GUI.

As you can see, no planet is visible from the space station.

**Comment by zmaster587** [comment]
Can you check to see if errors are appearing in the log?

**Comment by marcus2518** [comment]
https://hastebin.com/sorocosesi.vbs

**Comment by zmaster587** [comment]
is there one with the rocket too?

**Comment by marcus2518** [comment]
https://hastebin.com/udefewafez.vbs

Rocket^

The modpack is running Advanced Rocketry V 1.1.4

**Comment by zmaster587** [comment]
I've done a bit of testing, the only way this is possible is if the station is put into orbit around a non existant planet.  I'll put a patch in that forces stations not in orbit around a valid planet to be migrated to earth.

**Comment by NWBeez** [comment]
I have this same issue on ftb interactions. I had to reinstall the pack, is there a way to force that orbit?
