### ISSUE TITLE
Crash when going back to Space Station from planet

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#553]
Advanced Rocketry 1.0.15
LibVulpes 0.1.17
Forge 2254
MC 1.10.2

A player of my modpack went to a planet in a different star system and got the following crash when trying to start the rocket and go back to the space station. https://pastebin.com/zsFCSrgK
I saw that Foamfix is involved as well in the crash but giving it happened when doing something in your mod, I thought I report here first. He left also the following explanation, hope that helps:

> had the following crash when I flew to my space station from Vogosphere (note that the original area where I landed my rocket to start the space station was altered, and the launch pad was moved to a new area but I still used the same station chip ID in the rockets guidance computer)

**Comment by zmaster587** [comment]
It looks to be more of an issue with unlinking infrastructure.  Did he
break a fueling station that had been connected to the rocket before taking
off?

**Comment by davqvist** [comment]
Yes.
