### ISSUE TITLE
Small planets barely seeable

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#554]
Advanced Rocketry 1.0.15
LibVulpes 0.1.17
Forge 2254
MC 1.10.2

Not sure if that changed or I just didn't notice, but I configured some planets with a very low gravitational multiplier, I set it to recommended min value of 10. But now if I look up destinations in the warp controller, those planets are sooo small that you can't really find them, maybe only a few pixels. And I couldn't find a way to zoom in, is there? If not, is there are a way to fix that? Maybe you can set a min icon size for small planets? I mean it makes sense to draw them in relative size to each other, but if you can't see them, that's not a really practical solution, I suppose.

**Comment by davqvist** [comment]
I had another idea to potentially fix is. Maybe you could add two arrow buttons which cycle focussing on the next/previous planet. This is obviously more intricate than just setting a min planet icon size, but may be a useful feature to have nonetheless, especially if a star system has a lot of planets in it, so that the user can look through all of them and not miss any.

**Comment by zmaster587** [comment]
List implemented in 9806063d6e4d1f685ca47cd40d2e84fa6fa8a563
