### ISSUE TITLE
Cannot launch: destination does not exist

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#556]
With the latest fixes from 10-12 April, the rocket can't create a station. Chip station is created regularly, the station itself is packed too. The player, puts everything necessary in the rocket and tries to start it. The rocket does not take off and at the same time it shows the inscription "Cannot launch: destination does not exist".

**Comment by zmaster587** [comment]
are there any guidance computers on the rocket, if so, what is in them?

**Comment by denwd** [comment]
Standart Rocket, fuel tanks, engines, computer, seat and chip station
![2](https://cloud.githubusercontent.com/assets/3863970/24991288/2a119a70-2033-11e7-8dfb-a25b35d17d4b.jpg)
![1](https://cloud.githubusercontent.com/assets/3863970/24991292/2d1857fe-2033-11e7-916d-7fe456f355f4.jpg)

**Comment by zmaster587** [comment]
Is station 14 the one you are creating?

**Comment by denwd** [comment]
This is a chip of an already established station.
But the same thing happens if I try to create a new station. If I try to take off on a rocket with a station chip, then the above inscription is displayed. If I try to send a rocket without myself, to create a new station, then nothing happens, the rocket does not take off.

**Comment by zmaster587** [comment]
if you try to create a station around the overworld does it launch properly?

**Comment by denwd** [comment]
With the container and without the container does not work.

**Comment by zmaster587** [comment]
What about without the guidance computer or a seat and launching it with the monitoring station?

**Comment by denwd** [comment]
The rocket flies, if you do not put the chip with the coordinates to the guidance computer, but when entering the orbit happening crash the game (or server).

**Comment by zmaster587** [comment]
I assume you mean #567?

**Comment by zmaster587** [comment]
would it be possible to send the temp.dat and if you could put the station container in your inventory and then upload the player file that would also be helpful so I can trying to figure out how you possibly got a station container without creating the station

**Comment by denwd** [comment]
Yes, this is the same. I have kept for you the whole world map. Mods only AR and LibVuples. Player name player42.

Link: https://www.dropbox.com/s/srzlylfbwv25ky8/ARtests.zip?dl=0

If you need to enter the game, then I did it through the TLauncher in this case.

**Comment by zmaster587** [comment]
Port of change in data storage of station data went bad.
