### ISSUE TITLE
TotalWeight 0, nothing to spawn???

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#560]
The server writes the following inscription in the log when generating worlds: TotalWeight 0, nothing to spawn???

**Comment by zmaster587** [comment]
I am not aware of any printouts like that from Advanced Rocketry, only place I can think of would be GenLayerBiomePlanet, but I don't see any printlines in AR that would print anything like that.

Would it be possible to post a full log?

**Comment by denwd** [comment]
Good day, possible my mistake, sorry.
