### ISSUE TITLE
Enhancement: Use other world generator for planets

### ISSUE THREAD

**Issue by BakermanLP** [zmaster587/AdvancedRocketry#561]
Hello,

this ist a feature request / enhancement for Advanced Rocketry. 

Can you extend the planets xml definitions file? I want to use another world generator for the planets. I use Terrain Control for my overworld and would like to use it also for other planets and moons.

I think that could be easily adopted.

Thanks for reading

Michael (aka BakermanLP)

**Comment by Tyrantin** [comment]
#449

**Comment by BakermanLP** [comment]
Oh sorry, haven't seen that issue

Lynn <notifications@github.com> schrieb am Mi., 19. Apr. 2017, 12:40:

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
