### ISSUE TITLE
Unmanned rocket engine

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#562]
![2017-04-14_08 56 50](https://cloud.githubusercontent.com/assets/8041616/25043855/0fbbd3d4-20f1-11e7-99bf-838f403544db.png)

Build 1.1.5-5

**Comment by Tyrantin** [comment]
reduced the size and still:
![2017-04-14_09 06 41](https://cloud.githubusercontent.com/assets/8041616/25043968/c2352178-20f1-11e7-9f08-c82cd7da6dc8.png)

**Comment by zmaster587** [comment]
Was it dissembled and reassembled and what direction is it facing?

**Comment by Tyrantin** [comment]
Went to standard engines:
![2017-04-14_09 08 38](https://cloud.githubusercontent.com/assets/8041616/25044008/059d2a1e-20f2-11e7-8813-d52580d7554b.png)

**Comment by Tyrantin** [comment]
OK did some extensive testing.... I have came to a conclusion: Engine rotation is only experienced when you build the rocket facing any other way than East. Pick to follow.
![2017-04-14_09 17 10](https://cloud.githubusercontent.com/assets/8041616/25044228/7a5189a8-20f3-11e7-8a14-f7113461129e.png)
So, With that, that is the best info I can give you on this subject. If anyone has an issue with this very glitch and has more info please feel free to post your info. No other comments is needed nor is any repeat posts. zmaster will get to this issue WHEN he has time...... 

Please be patient....

**Comment by zmaster587** [comment]
Two more questions, does this occur in single player in the same manner and
does it occur without other mods?

**Comment by Tyrantin** [comment]
Yes
and one moment I'll check

**Comment by Tyrantin** [comment]
Ok it is a interaction issue. I rotated it in all directions and every time it rotated correctly! This is with only your mod...

**Comment by zmaster587** [comment]
Would it be possible to narrow down which mod is doing it?

**Comment by Tyrantin** [comment]
I can try. It will be a long process

**Comment by Tyrantin** [comment]
Ugh... I hope you appreciate this! after Hours and hours of testing.....

6 1/2 hours worth

Fence Overhaul v. 1.2.1

**Comment by zmaster587** [comment]
Geez dude, I'm kinda sorry about asking, I didn't think it would take that
long.
But I really do appreciate it.  I'll see if I can figure out what's going
on with that mod.

**Comment by Tyrantin** [comment]
NP If your on can you get on Disc for a fue min

**Comment by zmaster587** [comment]
Sorry, was not a good time, may have time monday or Wednesday, is unsure right now how my free time will be laid out

**Comment by Tyrantin** [comment]
NP

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
