### ISSUE TITLE
[1.7.10]crash using the Select Dst button crash

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#563]
When I build a rocket and try to select the destination using the Select Dst button   crash

LibVulpes-1.7.10-0.1.17-universal
AdvancedRocketry compiled from latest source, master branch

https://pastebin.com/H7F4TU1A

https://pastebin.com/M1WeDWYu

**Comment by denwd** [comment]
the problem https://github.com/zmaster587/AdvancedRocketry/commit/ba3e5b3c53c6966af07c188d972736ef138428e5

**Comment by zmaster587** [comment]
Bad handling of invalid icon it look like.  Will fix

**Comment by denwd** [comment]
thank you)
