### ISSUE TITLE
Swamped with Gas Giants

### ISSUE THREAD

**Issue by Kayinnasaki** [zmaster587/AdvancedRocketry#566]
Playing on a server running ATM 2.53 which is running AR 1.0.13 and... everything but Earth is a gas giant. L:una is a gas giant. The server has never been updated or anything so everything has been the same version. Singleplayer works fine.

Also on this topic, what would be the best thing to do to ungasify myself? I can't seem to get the planet generate command to work. Is there something I can delete that'll regenerate stuff?

**Comment by zmaster587** [comment]
Sounds like #436 there was an issue with the backward compat code in AR that made planets with dimids larger that 256 become gas giants.  I've fixed it for 1.0.16.  But you can reset AR's planets by deleting the <save>/advRocketry/temp.dat file

If you want to use the latest version now, I do have a build up here http://65.78.115.159:8080/
I do plan on releasing a build either later today or tomorrow on Curse

**Comment by Kayinnasaki** [comment]
That seems to have done it. Can't update without driving the server crazy but I changed the dimensions starting point (hopefully without causing other issues >_>) and reset temp.dat and it's working. Thank you!
