### ISSUE TITLE
[1.7.10]Crash the server, sent a rocket to create a station

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#567]
https://pastebin.com/F1Wj9tz9
https://pastebin.com/8Wn4ZWcv

When taking off the rocket sent to install the space station, there is a server crash when the rocket reaches a certain height.

LibVulpes-1.7.10-0.1.17-universal.jar
AdvancedRocketry latest github  branch master

**Comment by zmaster587** [comment]
Did you modify the advRocketry/temp.dat or restore from a backup or anything between creating the station and launching it?

**Comment by denwd** [comment]
No changes were made.

**Comment by zmaster587** [comment]
Do the line numbers in the given report?

**Comment by denwd** [comment]
316 and below in https://pastebin.com/8Wn4ZWcv

**Comment by zmaster587** [comment]
That's the same log as the one you reported before I made the commit.  URL is matching

**Comment by denwd** [comment]
You asked to show the line numbers in this report. I correctly understood?

**Comment by zmaster587** [comment]
After the update you claimed there was no change to the result.  I wanted
to make sure the report generated after the crash when trying after the
patch was identical even in the numbers printed in the crash report

**Comment by denwd** [comment]
Now it does not crash when a rocket with a container with a station is launched. Writes this:

[Server thread/WARN]: Somehow a non existant space station is launched.  Attempting to recover.  Debug info: Station ID=0 dimid=0

But it's still impossible to fly to an existing station. The rocket does not start.

Log: https://pastebin.com/FR87AGk0

**Comment by zmaster587** [comment]
You may have to create a new station for changes to take effect

**Comment by denwd** [comment]
Older chips are spoiled when the version is updated. We, of course, can get them through givestation. But we have reasons why it's hard to do this on the server. Is it possible to somehow through NBT editing to correct the old chips in a new way? Explain what and where it has changed.

**Comment by zmaster587** [comment]
Instead of using the metavalue of an item to determine the target station,
it now uses an nbt tag.  While I do not think it possible to automatically
convert the chips, it is possible to know which station they went to by
looking at the meta value on the chip

**Comment by denwd** [comment]
We have rewritten all owners of stations and chip numbers. And after the update they gave out the chips manually. It was not so long.
