### ISSUE TITLE
WAILA Incompatibility?

### ISSUE THREAD

**Issue by Neuron67** [zmaster587/AdvancedRocketry#568]
I couldn't even complete the first machine. The Hologram shows output location but Waila reads it as input.
I even tried to pick block the output from the hologram and it still places the input.
MC 1.10.2

**Comment by Neuron67** [comment]
I have since removed Waila and your mod is working as it should.
Waila version 1.7.0-B3_1.9.4

**Comment by zmaster587** [comment]
What version of AR/Libvulpes are you using?
I tried with AR 1.1.7, Libvulpes 0.2.2, Waila-1.7.0-B3_1.9.4, and forge 12.18.13.2221 as well as AR 1.0.17, Libvulpes 0.1.18, Waila-1.7.0-B3_1.9.4, and forge 12.18.13.2221 and could not replicate the issue with either set when building the cutting machine or electric arc furnace.
