### ISSUE TITLE
Crash opening the planet selector with the latest version

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#569]
https://pastebin.com/YDgF9RAS
There was no problem with 1.1.5 I think...

Update: after I specified the texture for each planet it's no longer crashing

**Comment by zmaster587** [comment]
This is a crash caused by placing a block rather than opening one.  It also
appears to be caused by a bad packet from the server. It you remove mods
other than advanced rocketry/libvulpes does this still occur?

**Comment by wormzjl** [comment]
I'm pretty sure that the crash is on gui open...

**Comment by zmaster587** [comment]
It appears to be on recieving a block place packet which is kinda confusing

**Comment by zmaster587** [comment]
I tried opening the planet selector with 1.1.6 and libvulpes 0.2.3 and forge 10.13.4.1614 and it seems to work without a problem

**Comment by wormzjl** [comment]
perhaps it's with my specific planet configuration or just random...anyway it's no longer crashing for me

**Comment by zmaster587** [comment]
Did you change anything?

**Comment by wormzjl** [comment]
I added customIcon=" " to every planet

**Comment by zmaster587** [comment]
If you remove customIcon="" does it occur again?

**Comment by wormzjl** [comment]
Nope... This thing is weird -_-

**Comment by zmaster587** [comment]
no idea then... if you can get it to occur again, just comment/reopen the issue
