### ISSUE TITLE
Problem with station

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#570]
So I've started a new world for testing, build a simple station, sent it into space, and the station id chips says it's station 1.
Then I made a rocket to go to the station, but when I tries to lift off, it says something like the destination is not valid.
Then I've used the command /advancedRocketry goto station 1, nothing is there.
When I type /advancedRocketry goto station 2, I found my station.
Something must be broken...

**Comment by zmaster587** [comment]
This is a 1.7.10 build, correct?

**Comment by wormzjl** [comment]
yep

**Comment by zmaster587** [comment]
Likely related to #556 and the 'patch' for #567
