### ISSUE TITLE
Crash On Client Startup

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#571]
Hey Zmaster!

Thank you for the updates!! 

I just loaded up the new Advanced Rockety/LivVulpes

https://pastebin.com/h31gbnwB

Forge: 2281
MC: 1.10.2
Advanced Rocketry: 1.1.6
LibVulpes: 0.1.18

Thank you!
Darkosto

**Comment by zmaster587** [comment]
The 1.1.x versions of AR go with the 0.2.x libvulpes series. So try it with
that?

**Comment by Darkosto** [comment]
Ahh, okay! Let me give that a try. Thanks for the quick reply. I'll let you know in a few minutes :)

**Comment by Darkosto** [comment]
Yep! That was the problem on my end. Thank you!
