### ISSUE TITLE
no moon on earth

### ISSUE THREAD

**Issue by Locke019** [zmaster587/AdvancedRocketry#572]
I noticed that after building my first manned rocket that I have no moon to select as a destination.
I'm unsure if its just random chance if earth will have a moon or not to go to or if its a bug?
I'm currently using version 1.1.5.

**Comment by zmaster587** [comment]
Are you using an XML file to specify planet layout?

**Comment by Locke019** [comment]
No I was just leaving everything as default.
Do I have to specify planets at all now?
I used the planet sector block just to see if there was other planets/systems showing and I do see a number of planets and moons around them.
Earth is just showing as no moons at all.

**Comment by zmaster587** [comment]
Sounds like the default setup is broken then.  Will fix

**Comment by Locke019** [comment]
Okay thank you.
Will I need to do something to fix it as far as my save is concerned?

**Comment by zmaster587** [comment]
You may need to delete the <save>/advRocketry/temp.Dat file after you
install the new version of the mod

**Comment by Locke019** [comment]
I take it that I might lose whatever I have in orbit of earth then?

**Comment by zmaster587** [comment]
if you already have stuff in orbit you can try the resetFromXML=>true setting in the config.  It should reset the planets without destroying anything in orbit around Earth.

**Comment by zmaster587** [comment]
If you run "/advRocketry planet list" ingame, does "Luna" show up in the printout?  I'm wondering if it's not the moon that's borken, but rather the Earth

**Comment by zmaster587** [comment]
Confirmed, Earth was broken.  Tested with the resetFromXML and it seemed to work alright, but because it was the earth that was broken, I'm not sure if the satellites will stay or not.  If they persisted through a game restart they should be ok if you use the resetFromXML option in the config.
