### ISSUE TITLE
"Destination Unavailable" when trying to fly to Luna

### ISSUE THREAD

**Issue by baspallada** [zmaster587/AdvancedRocketry#573]
Whenever me and my friends try to launch a manned rocked to Luna we get the "Destination Unavailable" error. 

I've selected Luna as the destination through the guidance computer and the GUI states Luna as the destination. Upon pressing space I'm greeted by the "Destination Unavailable" error.

We've tested the rocked and it works when we launched satellites.

Am I missing something or is this just a weird bug?

**Comment by zmaster587** [comment]
What version of AR/MC are you running and what is the printout of "/advRocketry planet list"

**Comment by baspallada** [comment]
My apologies, I should have included that in the original post.

I'm on minecraft version 1.10.2 and AR version 1.10.2-1.0.13 through curse/twitch.

Couldn't use the command from the terminal, so here's the printout of the command in-game:
![screenshot_19](https://cloud.githubusercontent.com/assets/9130319/25108434/073565e4-23d6-11e7-8491-0ec0b8063f6f.png)


I hope I've provided enough information.

**Comment by zmaster587** [comment]
That would make sense.  In builds prior to 1.0.17 there's a bug where having planets with dimids larger than 256 causes them to become gas giants upon restart and therefore unreachable.  See #566

Best course of action I would suggest is to either update to the newest version of the mod or to lower the minimum dimension ID for planet generation and change the "resetfromXML" config option to true.  That should regenerate the planets without destorying satellites/stations

**Comment by Neuron67** [comment]
I experienced this same message and discovered that the planet ID chip had vanished from the guidance computer. After replacing, it worked fine.

**Comment by baspallada** [comment]
Updating the mod and setting the "resetfromXML" to true worked. Thanks for the help
