### ISSUE TITLE
Launched Space Staion Rocket and crashed, world now inaccessible.

### ISSUE THREAD

**Issue by Neuron67** [zmaster587/AdvancedRocketry#574]
Built Space station on earth and packed it up, placed on rocket and launched successfully but crashed as it reached its destination. Cannot reopen world.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.6.24 mc1.10.2.jar)
  Plugin (NotEnoughIDs-1.5.3.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.16.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 4/18/17 10:04 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at zmaster587.advancedRocketry.stations.SpaceObjectManager.moveStationToBody(SpaceObjectManager.java:371)
	at zmaster587.advancedRocketry.stations.SpaceObjectManager.moveStationToBody(SpaceObjectManager.java:361)
	at zmaster587.advancedRocketry.entity.EntityRocket.unpackSatellites(EntityRocket.java:800)
	at zmaster587.advancedRocketry.entity.EntityRocket.onOrbitReached(EntityRocket.java:725)
	at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:635)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at zmaster587.advancedRocketry.stations.SpaceObjectManager.moveStationToBody(SpaceObjectManager.java:371)
	at zmaster587.advancedRocketry.stations.SpaceObjectManager.moveStationToBody(SpaceObjectManager.java:361)
	at zmaster587.advancedRocketry.entity.EntityRocket.unpackSatellites(EntityRocket.java:800)
	at zmaster587.advancedRocketry.entity.EntityRocket.onOrbitReached(EntityRocket.java:725)
	at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:635)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: advancedRocketry.rocket (zmaster587.advancedRocketry.entity.EntityRocket)
	Entity ID: 2979924
	Entity Name: Rocket
	Entity's Exact location: 392.50, 1001.13, 341.50
	Entity's Block location: World: (392,1001,341), Chunk: (at 8,62,5 in 24,21; contains blocks 384,0,336 to 399,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 2.50, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: I'm In Space!
	All players: 1 total; [EntityPlayerMP['HandyMan67'/175, l='I'm In Space!', x=392.32, y=79.00, z=348.10]]
	Chunk stats: ServerChunkCache: 642 Drop: 0
	Level seed: 6301924492737352416
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (297,64,277), Chunk: (at 9,4,5 in 18,17; contains blocks 288,0,272 to 303,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 847070 game time, 644084 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 86718 (now: false), thunder time: 7624 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 473582064 bytes (451 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	libVulpes{0.1.17.20170402130834} [libVulpes] (LibVulpes-1.10.2-0.1.17-universal.jar) 
	UCHIJAAAA	advancedRocketry{1.10.2-1.0.16} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.0.16.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.6.24 mc1.10.2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.62-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.62-beta.jar) 
	UCHIJAAAA	JEI{3.14.2.401} [Just Enough Items] (jei_1.10.2-3.14.2.401.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.156} [Ender IO] (EnderIO-1.10.2-3.1.156.jar) 
	UCHIJAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3c.jar) 
	UCHIJAAAA	justenoughbuttons{1.10.2-1.7.3} [Just Enough Buttons] (justenoughbuttons-1.10.2-1.7.3.jar) 
	UCHIJAAAA	neid{1.5.3} [NotEnoughIDs] (NotEnoughIDs-1.5.3.jar) 
	UCHIJAAAA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJAAAA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJAAAA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.6-mf-1.10.2-12.18.2.2125.jar) 
	UCHIJAAAA	XaeroMinimap{1.12.5} [Xaero's Minimap] (Xaeros_Minimap_1.12.5_Forge_1.10.2.jar) 
	UCHIJAAAA	XaeroWorldMap{1.8.1} [Xaero's World Map] (XaerosWorldMap_b1.8.1_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.6.24 mc1.10.2.jar)
  
Plugin (NotEnoughIDs-1.5.3.jar)
  ru.fewizz.neid.asm.Transformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.16.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Ron/AppData/Roaming/.minecraft/versions/1.10.2-forge%20Advanced%20Rockets/mods/mcjtylib-1.10-2.2.0.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['HandyMan67'/175, l='I'm In Space!', x=392.32, y=79.00, z=348.10]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by zmaster587** [comment]
Would it be possible to upload a copy of the world, or at least the region containing the rocket and the /advRocketry/temp.dat file?  Alternately, is it possible to replicate the issue on demand and if so, can you provide instructions on how to do it?

**Comment by Neuron67** [comment]
I'm unable to reopen the world but I could upload it for you. 
(https://1drv.ms/f/s!AjGyXQYEAU6zyna0cCxFZjbivmKq)

**Comment by zmaster587** [comment]
Looks like the NBT data on the station container in the rocket got erased somehow...  if you build and launch another station does it occur again?
Will link a build that'll prevent the game from crashing on you.  It will delete rockets that try to launch invalid stations however,

http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/MC1_10/15/

**Comment by Neuron67** [comment]
I tried again and everything worked great. 
I'm not sure but I may have used glass from another mod the first time.
Thanks for your time.
Sweet mod btw.

**Comment by zmaster587** [comment]
Yep, no problem.  And thanks!
