### ISSUE TITLE
When crafting motor, it crafts libVulpes, not Advanced Rocketry version, and the multiblock structure won't accept it. 

### ISSUE THREAD

**Issue by zackeezy** [zmaster587/AdvancedRocketry#575]
I realize my version of AR is three full releases behind, and I will install the current version and test it later, but this seems weird and isn't mentioned even in a closed issue. So I don't know if it's just me.  I tried creating the lathe, but the motor I made keeps getting the red 'x' on it and it won't take my iron.  I crafted it in the crafting terminal and got the libVulpes motor not the Advanced Rocketry motor.  Apparently it doesn't like that.  I'm running Advanced Rocketry v.1.0.16 (the release) in Minecraft 1.10.2 using forge 12.18.3.2254.

**Comment by zmaster587** [comment]
Are you using the 0.1.x builds of libvulpes?

**Comment by zackeezy** [comment]
No I'm using 0.2.1

**Comment by Neuron67** [comment]
Sounds similar to the problem I was having with WAILA. Try removing waila to see if that helps.

**Comment by zmaster587** [comment]
That's likely your problem then.  In the 1.1.x builds of AR the motor was
moved to libvulpes.  The 0.2.x builds of libvulpes are designed for the
1.1.x versions of AR.  The 0.1.x versions of libvulpes are designed for the
1.0.x versions of AR.

**Comment by zackeezy** [comment]
Okay I'll try it. Thanks.
