### ISSUE TITLE
Blueprints have a problem

### ISSUE THREAD

**Issue by RadicalBruh** [zmaster587/AdvancedRocketry#576]
For some reason in 1.0.18 of 1.7.10,its not showing the parts for all of the blueprints except 
the cutting machine don't show the main part of the machine and the motor.
Can anyone help me with this?
(P.S even with or without mods it still happens)

**Comment by zmaster587** [comment]
Are you using a 0.1.x build of libvulpes?

**Comment by RadicalBruh** [comment]
Yes,Why?

**Comment by zmaster587** [comment]
The 0.2.x builds have had a few components moved from AR to libvulpes which
could possibly cause this problem.  I'll look into it more when I get to a
computer

**Comment by zmaster587** [comment]
Running AdvancedRocketry-1.7.10-1.0.18,  LibVulpes-1.7.10-0.1.18-universal, and forge 10.13.4.1614 for MC 1.7.10 I cannot replicate the problem.
Is it at all possible there's just a small block (flower,grass, bush, etc) in the way

**Comment by RadicalBruh** [comment]
No, there is not, when this first happened there was no small block
and for some reason it still happens

**Comment by zmaster587** [comment]
does it list the motor and cutting machine in the tooltip when you mouse over it?

**Comment by RadicalBruh** [comment]
yes,it does except for i think the crystallizer is missing one
also,my game now just seems to crash now.

**Comment by zmaster587** [comment]
Can you post the crash report, also what did you do that fixed some of the
blueprints?

**Comment by RadicalBruh** [comment]
For the crash report i can't seem to get it because i can't seem to repeat the crash,
but for fixing the blueprints after a few times of crashing it suddenly works and then
it got fixed.
