### ISSUE TITLE
Missing ores in the orbital miner after a few updates ago

### ISSUE THREAD

**Issue by Saereth** [zmaster587/AdvancedRocketry#577]
We are currently on
AdvancedRocketry-1.10.2-1.1.7
LibVulpes-1.10.2-0.2.2-universal

Currently we are using the ATM fork of the rockhounding mod which has an ore call uninspected mineral ore. It'd doesn't have an oredict by default but I created one with minetweaker ore:oreUninspected. We have this added to the list of ores the orbital miner can use and it WAS working fine about 4-5 updates ago. Players started gradually reporting they werent getting any uninspected ores anymore so after looking into it we can confirm after a few hundred thousand ores mined it hasnt produced a single uninspected now..

About the same time the ore stopped showing up we started getting libvulpes aluminum ore from the miner where we were previously getting thermal expansion aluminum ore so seems like something definitely changed in that regard. Any further insight you may have into this would be helpful. Let me know if you require any additional testing/info on our end.

**Comment by zmaster587** [comment]
Couple questions.  Can you verify that the uninspected ore is indeed being
added to the oredictionary in game.  Second, is the oredictionary string
for the ore in the laserdrill ores config option in AR?

**Comment by Saereth** [comment]
yes to both, /mt hand shows it is added to two oredicts oreUninspected and mineralOres
I have both added to the advanced rocketry config and I havent changed anything with the oredicts or advanced rocketry ore config since the pack went public (Nuts and Bolts: Torqued) since the uninspected ore+orbital miner are key points of progression (the ore is unobtainable any other way).

here is the config directly:
https://hastebin.com/akamemucor.coffeescript

I've got alot of stuff added to that list but everything else on the list seems to be working except the uninspected ore. Also the strangeness where we started getting libvulpes aluminum instead of TE a few updates again when this started.

**Comment by zmaster587** [comment]
The business with the change in aluminum just sounds like a shift in
ordering of the ores being registered.  Also the config was not designed
with having duplicate entries in mind.  So I'm not even 100% sure what
that'll do.
Also can you post a start up log of the server so I can see if I can spot
anything funky?

**Comment by zmaster587** [comment]
What was the last known version that worked?

**Comment by Saereth** [comment]
So there didnt seem to be any way to "weight" the ores, but I found by adding the oredicts multiple times it caused them to appear more often. So the multiple entries exist there to try and create a more weighted mining result.
The last known version.. I'm unfortunately not 100% on which version it stopped working but I do know for sure that AdvancedRocketry-1.10.2-1.1.1 and LibVulpes-1.10.2-0.2.0-universal had everthing generating fine. I'm not sure which update beyond that caused it to stop generating. 

Here is a fresh set of all startup logs:
https://drive.google.com/drive/folders/0BwmxXoRAG3ddQ3RaOUhtXzFhU0U?usp=sharing

**Comment by zmaster587** [comment]
I don't see anything unusual in the log, I'll grab the pack off of curse and test it today sometime

**Comment by zmaster587** [comment]
I downloaded the pack from curse (nuts and bolts: torqued version 1.6.4.7) and loaded it up and built a mining laser on a space station.  I fired it up and got cobblestone, uninspected mineral, resonating ore, cobble, and stone in the first run.

**Comment by Saereth** [comment]
Server/pack is running on forge 2254, I can update to see if that makes a difference later today.
So, things get weirder. Upon seeing you had it working I went into singleplayer and built one and also was able to get uninspected ores. So it's working fine in singleplayer. The ores just arent showing up on the server/in multiplayer. The configs are identical, in fact the ones I linked here earlier were from the server directly.

**Comment by zmaster587** [comment]
Later ima see about running a diff on the log output of the server and
single player.  I wonder of its a server only issue?  What if you crate a
new server from scratch?

**Comment by Saereth** [comment]
I will setup a fresh server to test this after work today and let you know

**Comment by zmaster587** [comment]
Alright.  I also did go through the code and verified adding the same ore
to the list in the config multuple times should increase the chances for a
given ore without and odd side effects

**Comment by Saereth** [comment]
ok so I copied the server files exactly to a new directory nabt cp -R -> nabt-test
then I deleted the world directory and started it up. After building an orbital miner it's getting uninspected ores just fine.... But the primary server and the existing world there still isnt... this is super confusion now lol

**Comment by zmaster587** [comment]
That is really odd... maybe try running a diff on the configs on the new
server and configs on the old one.  If you don't get around to diffing the
startup logs I'll likely get to it within 2 hours.

**Comment by zmaster587** [comment]
Actually, hold on, I think I was a bit hasty with my last reply.  You said
you're using a copy of config and mods folder as the server with the
problem?  Stranger still... I'll add some print statements and build a
version with some print statements that should, I hope, shed light in the
issue

**Comment by Saereth** [comment]
yeah its an exact copy of everything the only thing I deleted was the world folder which recreated, even used the same world seed etc.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.10.2-1.1.7ExtraLog.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/948114/AdvancedRocketry-1.10.2-1.1.7ExtraLog.jar.zip)
Run this build on the server with the problems and post the generated log file.  I have it print when the ores are registered to the orbital drill and what ores are registered.  I'm wondering if it's being registered at the wrong time for some reason or something

**Comment by Saereth** [comment]
done:
https://www.dropbox.com/sh/gzn7kle5ope7egj/AACi0fmfXz6zeqJFo4dc3FwXa?dl=0

**Comment by zmaster587** [comment]
Thanks.  It looks like it's not registering too early at least; well after the loadComplete phase.  But oddly enough that ore is not showing up in the list.  Gonna dig a bit deeper.

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.10.2-1.1.7.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/948282/AdvancedRocketry-1.10.2-1.1.7.jar.zip)
Would it be possible to run this build and grab the logs for it.  I've modified it to print out when ores are registered.  This way we can verify when it was registred

**Comment by Saereth** [comment]
Yeah I'll run this soon. Just to make sure this part is clear, that ore has no intrinsic oredict, I'm specifically adding the oredict via minetweaker so if its attempting to load before minetweaker adds the oredict it wouldnt exist yet.

**Comment by zmaster587** [comment]
Yeah, the theory is maybe minetweaker is somehow screwed up or loads it after the laser checks for ores.

**Comment by Saereth** [comment]
ok fresh set of logs:
https://www.dropbox.com/sh/gzn7kle5ope7egj/AACi0fmfXz6zeqJFo4dc3FwXa?dl=0

**Comment by zmaster587** [comment]
I have a theory.  I think what's going on is that FTBUtilities is loading chunks before the world is finished loading.  Because the spacelaser registers what can be mined when the first instance of the machine is loaded and it's now being loaded before minetweaker finishes registering recipes that this is occuring

**Comment by Saereth** [comment]
Could you maybe load/build the cache a little later and just prevent the laser from running until the cache is built? I'm trying to test with ftbu chunk loading off but unfortunately turning chunkloading off doesnt clear chunks for loading it just prevents new ones from being added. Additionally wouldnt any chunkloading solution that loads it before the cache also potentially result in this issue?

alternatively, anyway to allow directly adding the ore like atmrockhounding:ore:1 to the list instead of an oredict entry?

**Comment by zmaster587** [comment]
I don't think I'll be able to cache it any later than I already am due to the fact the last thing that can happen is the block being loaded into the world.  The Ideal solution I thnink would be to have minetweaker load at ServerStartingEvent rather than ServerStarted, but I'm not sure if there's a reason they didn't do that and I don't maintain that mod, nor would I consider this situation their fault really.

I definatly could allow for parsing of blocks/items directly since I now have the infrastructure to do that and is the solution I'm gonna go with.

**Comment by Saereth** [comment]
ok adding the ore directly will work perfect, I'm pretty sure MT loads when it does because loading early caused timeouts on connecting to servers due to JEI reloads, was a huge issue a month or two ago until it got moved.

**Comment by zmaster587** [comment]
I've made the change so now you can specify not only by name/meta but for size as well.

Ores can now be specified by just the oreDictName:<size> or by <modname>:<blockname>:<meta>:<size> where size is optional.  So for example "minecraft:coal:1:32" is 32 charcoal, "oreTin:32" is 32 tin ores, and "oreCopper" is 5 copper ore (5 was the hardcoded size before)

**Comment by Saereth** [comment]
do you happen to have a jenkins or anything where we could grab a copy of a version with these changes?
