### ISSUE TITLE
About the repost of AR

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#578]
Hello I'm an editor of a Chinese website www.mcmod.cn which is an encyclopedia website of minecraft and mods，now we want your authority to repost your mod to there for Chinese players know more about AR，do you agree？
And I hope you can make a manual for us to understand it better。

**Comment by zmaster587** [comment]
Sure!  As long as there's a link somewhere on the page that links to the page on curse forge I have no problem with that.

I hope to get to improving the wiki eventually.  Been really busy as of late but.. once I finish the first content update (what's currently the alpha builds) documentation will be my primary focus
