### ISSUE TITLE
Give player a bit more resistence when landing with the rocket

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#58]
I was crushed to death even with the minium speed :\

**Comment by zmaster587** [comment]
Do you mean fall damage?

**Comment by wormzjl** [comment]
yeah...have you tried to land with survival mode?

**Comment by zmaster587** [comment]
I have but I normally wait after waiting 5 minutes or so... Investigating

**Comment by zmaster587** [comment]
Not sure how I missed that, thank you.
