### ISSUE TITLE
Gauss cannon misalignment

### ISSUE THREAD

**Issue by DevTimur** [zmaster587/AdvancedRocketry#580]
Not sure am I only one who get this issue.
But, when gauss cannon fire item, it`s not aligned with barrel.

P.S. Ver. "AdvancedRocketry-1.7.10-1.0.15"

**Comment by zmaster587** [comment]
Not aligned how? You mean not centered?  Also is this in MC1.10.2 or
MC1.7.10?

**Comment by DevTimur** [comment]
not centered with barrel.
1.7.10

**Comment by zmaster587** [comment]
I've confirmed this issue does not effect 1.10.2 builds as well.  Appears to have come around from the original smaller version of the railgun.  Looks like i just forgot to update the offset.
