### ISSUE TITLE
Is it a bug？

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#581]
![2017-04-21_17 57 35](https://cloud.githubusercontent.com/assets/23413915/25273028/a148af0e-26bc-11e7-825c-88f1c556c6de.png)
![2017-04-21_17 58 48](https://cloud.githubusercontent.com/assets/23413915/25273027/a14438d4-26bc-11e7-8520-e2b1cc058572.png)
I want to use RS to auto-make these items in the mod，but when I use TE‘s plate and IE’s stick，they won't be reciped。

**Comment by zmaster587** [comment]
Do the is it only that particular combination?  Do the TE plates work with
a known working stick.  Does the stick work with known working plates?

**Comment by forestbat** [comment]
@zmaster587 I seem to be blind because I saw tin plate as iron plate……
