### ISSUE TITLE
[Request]Higher resolution planet rings

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#585]
![2017-04-21_22 41 31](https://cloud.githubusercontent.com/assets/2989009/25296210/68c6c230-26e7-11e7-91bf-a52f49925cff.png)
The interior of planet ring looks a bit "sharp" right now, just want to make it match the ground texture

**Comment by zmaster587** [comment]
I'll see what I can do.  I'm afraid of increasing the file size a bit too much, and because the rings need transparancy unlike the ground it takes up a lot more space.  Though one 3MB file shouldn't hurt too much.  Will play with the files and see if i can get something reasonable.

**Comment by wormzjl** [comment]
ok thanks, but close this if you think it affects performace

**Comment by zmaster587** [comment]
I don't think it will, but depending on what I do with it the download
might get a little bigger.  I'll play with it and see what I can do
