### ISSUE TITLE
Destination Unreachable?

### ISSUE THREAD

**Issue by djcprone** [zmaster587/AdvancedRocketry#587]
I built a viable rocket, linked it, set destination, and fueled it, get in and press space and "destination unreachable." I also noticed that after building the rocket with the assembler, it changes to rocket not scanned- as if I didn't just scan it and then build it. And if you then scan it again, it'll say that the rocket has no guidance computer, which it does and passed the scan a minute ago. You can shift right click the rocket and choose disassemble, and then scan or build again, but it is just an endless loop of fail. 

Using version 1.10.2-1.0.16 with libvulpes 1.0.17. I have confirmed from a few youtube videos and the minimally informative website for the mod that I have done everything correct. I even rebuilt the entire setup including the rocket exactly as seen in one video since I saw it worked for him; still nothing.

I was so excited for a more in depth space mod after beating galacticraft to death, but at least I could leave the overworld with galacticraft, lol.

**Comment by zmaster587** [comment]
Can you verify the planet Id chip in the guidance computer has the correct
destination?  Can you relay the output of "/advRocketry planet list"?

**Comment by djcprone** [comment]
Verified, and luna is in the planet list. Here's a zip full of screenshots. I think I covered everything possible. Thanks for the fast reply
[advroc.zip](https://github.com/zmaster587/AdvancedRocketry/files/949555/advroc.zip)

**Comment by djcprone** [comment]
@zmaster587 so out of curiosity, I set the destination to earth. And up I went. Naturally, I didn't go anywhere but it sure looked cool, and I left the atmosphere, and then pressed space to descend back to the overworld. But that should show at least that the rocket works and everything is set up correctly, right? I'm not sure how to check if I have something else conflicting with whatever id (I thought I saw somewhere in a comment section that luna was id:2?) that luna is using. But I saw your minimum in config is 1000, so I doubt there's an issue there.  I do have an RFTools dimension that uses id:2, but if I understand the readout from /advRocketry planet list or whatever, it says DIM1000 for luna, so thatd be the id, right?

**Comment by zmaster587** [comment]
Ah, I think i may know what your issue is if luna is 1000.  Go into the ar
config, set reset from xml to true and launch the game.  There was a bug in
earlier versions that caused planets with is greater than 255 to become gas
giants.  (AR'S default config for starting Id is 2, so the bug went
unnoticed longer than i'd like to admit).  This was fixed in version
1.0.17, but if the world you are playing was ever loaded with a different
version of AR, this is certainly the issue.

**Comment by djcprone** [comment]
@zmaster587 I'm using AR version 1.0.16 and lib version 1.0.17, does that matter? Mod pack is all the mods v2.54b. I learned after warping that no matter what planet I orbit, I can't visit the planet via rocket from space station either. And thanks to jei being all massive I accidentally disassembled my rocket on my space station with no setup to rebuild (face palm). But prior to that I selected the planet and still got destination unreachable. I'll try your fix tomorrow morning when I get home from work. Rftools dimensions are using id like 4-15ish currently with the worlds I've made. Is that going to be an issue if i do that config change you said?

**Comment by djcprone** [comment]
Can't edit from mobile apparently- also, all planets except earth look the same from any map. So I'm guessing that's the gas giant effect?

**Comment by zmaster587** [comment]
Likely, if they have a bluish wavey color

**Comment by djcprone** [comment]
They do. Do I need to update that only on server side? Or all my clients too? And will it clash with existing rftools dimensions?

**Comment by zmaster587** [comment]
Only the server, and as long as minimum dimension id in AR's config is 1000
or all planets are manually specified you'll be good.  If you've not
changed anything in AR'S config since you've started the world, you'll also
be good

**Comment by djcprone** [comment]
@zmaster587 that didn't do the trick. I changed resetplanetsfromxml=false to =true on the server side of things and I still have all gas planets that I can't travel to.

**Comment by zmaster587** [comment]
Did you also upgrade to 1.0.17?

**Comment by djcprone** [comment]
I did not, I thought you meant this would fix the issue for the version I had. I'll try that now

**Comment by zmaster587** [comment]
Alright, I kinda got a bit confused when you mentioned 1.0.17 for libvulpes
and didn't notice that you mentioned AR 1.0.16 until just now.   I had
somehow had it in my head that you had upgraded fton 1.0.16 to 1.0.17.

**Comment by djcprone** [comment]
Yeah that's what the modpack had so I just left it alone. Just updated to AR 1.0.17. No go
![failed](https://cloud.githubusercontent.com/assets/27912390/25395580/82b65f32-29af-11e7-9fb9-1a1dfb0b9076.jpg)

**Comment by zmaster587** [comment]
Did you set reset from xml to true after updating the mod?  it changes back to false every time you start the game to prevent it from resetting every time a world is loaded.

**Comment by djcprone** [comment]
That would've been good information to know, haha. I did not. I'll do that in morning after work then. Thanks man, hope it works! I have been expanding my space station and warping around for fun and it's awesome, can't wait to actually visit the planets.

**Comment by zmaster587** [comment]
I do as well.  If your do need to end up deleting the folder, what I'd suggest doing is making a copy of world/advRocketry/DIM-2 before deleting the folder, then load the world and create 1 station for every one you have now, then shutting down the server and overwriting the new world/advRocketry/DIM-2 with the backup.  This will let you save whatever stations/warpship you have built, though you may need to replace blocks like the warpcore and landing pads.

Or if you really want you can send me the old and new advRocketry/temp.dat and I can try to copy the station data over or you could do it yourself with an NBT editor.

Also note that resetfromXML will automatically preserve stations.

Is kinda my fault for not being clear enough.  I also hope it works!

**Comment by djcprone** [comment]
:D ! Thanks man!

![image](https://cloud.githubusercontent.com/assets/27912390/25399542/b8f80862-29bd-11e7-933a-107a5c5ece39.png)

**Comment by zmaster587** [comment]
No problem!

**Comment by djcprone** [comment]
@zmaster587 sorry to bother you again - so, I changed **nothing** else on my server aside from updating to latest version of your mod as you said, and changing the resetplanetsfromxml to true for the launch after update (which got me working in space, woohoo) but now environmental tech multiblocks aren't working. Somehow your new version prevents things like the nano bot beacon controller that can give flight or saturation, w/e anywhere you go -from working now. A guy on my server has been using this structure and the lightning power generator, and the ore mining multiblock structure without issue but as soon as I updated AR, they all stopped working. He's tried taking them apart and redoing them and using the assembler as well. I was curious if you had any idea why? Like I said, I changed literally not one mod or config other than yours so I am hoping you have an idea, lol.

Also, first trip to another planet was WAY better than galacticraft. Except 3 out of 4 times now I have landed in an ocean, which is annoying lol.

**Comment by zmaster587** [comment]
I've not no clue, AR makes not modifications to other mods such as environmental tech whatsoever.  The only external things that AR changes that could have any effect at all is: addition of acceleration to player for gravity, a change in the skybox for space stations and other planets, addition of a hook into on block placed (this has not been changed since september).

So if possible, can you backport to the previous version of AR (perhaps on a copy) and see if the env tech behavior also changes back.

**Comment by djcprone** [comment]
@zmaster587 I'll do that tonight. The flight thing could be part of his issue because that nano bot thing gives you creative flight anywhere in the world. He says that doesn't work anymore. I noticed I have that issue with my angel ring for flight, gets disabled but only when I wear the AR space suit. Which I assumed for floating around in low gravity was on purpose. I'll report the results in like twelve hours or so.

**Comment by zmaster587** [comment]
If flight is disabled only when wearing the AR suit, that would make sense due to how the "hover mode" in the jetpack is handled (if the jetpack is not in hovermode it constantly disables creative flight for players not in survival.  Mostly due to not having a good technique down to tell exactly when the mode is changed.).  But that's not changed since the jetpack was added.
So see if not wearing the suit fixes the nano bot thing.
