### ISSUE TITLE
Register machine recipes on postinit

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#588]
Which will prevent issue with mod load order

**Comment by zmaster587** [comment]
Are there issues with AR's recipes and mod load order?

**Comment by wormzjl** [comment]
yes, some fluid that I used are not in recipes

**Comment by zmaster587** [comment]
For recipes registered via XML or default?  Reason I ask is because XML is already registered in postinit whereas default is registered in the init phase.

**Comment by wormzjl** [comment]
That's strange...Gonna look further tonight

**Comment by wormzjl** [comment]
Seems to be other issue
