### ISSUE TITLE
Lathe Outputtin TinCon Steel Tool Rods

### ISSUE THREAD

**Issue by Darktotaled** [zmaster587/AdvancedRocketry#589]
Hey o/

My Lathe is outputting steel tool rods and i cant use them in recipes that use steel rods(like steel gears)

Almost forgot:
Latest Forge
1.7.10
TGR ModPack(TioGrimReaper) + libVulpes and Advanced Rocketry

This is a modpack that i launched in technic platform. I added your mod to my pc but not to the platform yet cause i was testing it first.

**Comment by zmaster587** [comment]
Looks like AR is just using the most recenty registered recipe and Tinkerer's construct rods just happen to be at the end of the list.

Two fast fixes would be to change "makeMaterialsForOtherMods" to false in the AR config.  If you're using the 1.1.x builds you'll also need to delete the Lathe.xml file for the change to take effect.

AR should still be using it's own materials for things that are defined in libvulpes (like steel).  So I'll see what's up with that.

**Comment by zmaster587** [comment]
Odd thing is that when only running AR/Libvulpes and Tinkerer's construct the lathe outputs AR's steel rods.  So I'm wondering if there's something else going on here.

**Comment by Darktotaled** [comment]
Testing it right now.
thanks for the quick response.
Will edit this as soon as i confirm if it works.
By the way, this mod is awesome. The machines are beautiful too.

**Comment by zmaster587** [comment]
Thanks!  Glad you got things working.  I can't exactly tell how this happened in the first place, though given the fact it cannot be replicated with AR and TiC alone I think there's some other interaction going on.
