### ISSUE TITLE
Oxygen vent crash

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#59]
Crashed when tries to place it on the overworld
http://pastebin.com/u5cmidMu

**Comment by zmaster587** [comment]
Was it right after loading into the world and did you change any of the configs?

**Comment by wormzjl** [comment]
here is my config
http://pastebin.com/cA5CXmbB

**Comment by wormzjl** [comment]
btw I've used a superflat world, does that matters

**Comment by zmaster587** [comment]
No it doesn't, I was just curious if you had turned off atmosphere.  Should be fixed in 0.4.4
