### ISSUE TITLE
Crash when launching first rocket to moon

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#591]
MC 1.10.2
Forge 2281
AR 1.0.17

So a user of my modpack crashes whenever he tries to launch his first rocket to moon.
Here's the log: https://gist.github.com/L3thal1ty/239bf411f7cb530428e3003e90c340f1

What is weird though, he has a second Earth oribiting Earth, but everything else seems normal.
When typing "/advRocketry planet list" everything seems normal, no second Earth.
Here's the temp.dat https://cdn.discordapp.com/attachments/264861578556473344/307195297128513539/temp.dat
(I hope you can access it, if not I will upload it somewhere else)

I couldn't find anything special in the temp.dat, well beside childrenPlanets being 2 for Earth which would explain the second Earth, but a second Earth doesn't appear in the temp.dat either.

Here's the planetDefs.xml: https://pastebin.com/nS8Hheuf

Did I mess up in the XML?

**Comment by zmaster587** [comment]
It is definitely a problem with Earth orbiting earth I think.  That happens
when another dimenion gets set to orbit earth but the id is not valid.
This might be able to occur if a player switches between world's in single
player.  Otherwise I don't know exactly how the other dim got there.

I'm currently on mobile so I cannot open the temp.dat, I will look further
when I get to a computer.  However what I'd suggest doing in the meantime
is check the childplanet Integer list for plamer Id 0 and remove the int
that does not correspond to the moon and then launch the game.  If there's
only one value just leave it and I'll get to looking a it a bit better in a
few hours

**Comment by davqvist** [comment]
That's exactly what we try now, will report back.

**Comment by davqvist** [comment]
I got the answer and deleting the child planet indeed worked. The question is how to prevent that problem in the future. Can you look into that?

**Comment by davqvist** [comment]
And btw, he apparently has no other world in singleplayer.

**Comment by zmaster587** [comment]
it can also happen by leaving the world and opening it again after changing the xml at all

**Comment by davqvist** [comment]
He didn't touch the XML at all.

**Comment by zmaster587** [comment]
did he create a world, then exit it then create a new world without closing the game?

**Comment by davqvist** [comment]
He has only one world.

My best guess is, as he assumes as well, that it happened when I updated my modpack and updated AR to 1.0.17. Because to fix the id 255 Gas Giant issue, what I did, is set B:resetPlanetsFromXML=true so that the players could go to space again.

**Comment by zmaster587** [comment]
I think there'd have to be something else because I've done that many times now testing and have not run into that problem by using resetPlanetFromXML regardless of whether or not I'm doing an update or not.  There's also no difference between using that config and a first time launch.

**Comment by davqvist** [comment]
I mean only one user reported that so far and it works now, so I'm not sure how to reproduce it. I asked him and he didn't come up with anything which might be the problem. He only has one singleplayer world and haven't messed with the configs. /shrug

Sorry I'm not being any help, I'm as confused as you, I'm only reporting what happened.

**Comment by zmaster587** [comment]
Alright.  I'll go through a couple of cases for what I suspect happened and see if i can find anything.
