### ISSUE TITLE
Where titanium will generate？

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#593]
I have run for at least 20000 chunks，but there isn't any titanium ore，and I can't get titanium ores in quantum quarry of EXU2，so，where is it？

**Comment by zmaster587** [comment]
It should be called rutile

**Comment by forestbat** [comment]
@zmaster587 Yes I run a long distance，not only rutile but also copper and tin of AR were not been discovered。

**Comment by zmaster587** [comment]
Doy ou have the mod "orespawn" installed.  In not what other mods do you have installed?

**Comment by forestbat** [comment]
@zmaster587 Yes I have installed orespawn，does it lead to the problem？

**Comment by zmaster587** [comment]
Yes, orespawn completely replaces ore spawning in minecraft.  It does come with ore spawn lists for most mods, but it does not appear to include a list for advanced rocketry by default.  This leads to advanced rocketry's ores not spawning.  Easy way to fix this is to add advanced rocketry's ores to orespawn's config.

**Comment by forestbat** [comment]
@zmaster587 Okay thanks，I will change it。

**Comment by zmaster587** [comment]
Please report back on whether or not you get it fixed so I can either look further or close the issue

**Comment by forestbat** [comment]
@zmaster587 I know。

**Comment by forestbat** [comment]
![qq 20170430115019](https://cloud.githubusercontent.com/assets/23413915/25561348/98f6fcf2-2d9c-11e7-91a4-fad90ebb6b2b.png)
I have changed the config of orespawn like this，bug the game crashed，and the crash-report is here：
[crash-2017-04-30_11.52.14-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/966548/crash-2017-04-30_11.52.14-client.txt)

**Comment by zmaster587** [comment]
You've got an unmatched backet somewhere in the config.  Try searching for
a json validator online and it should give you and ides where the missing
bracket is.  Or you could try to find it yourself

**Comment by zmaster587** [comment]
Actually I think I see a missing comma on the closing brace right before
the libvulpes entry

**Comment by forestbat** [comment]
Okay，I found the rutile ores，thank you very much。
![2017-04-30_13 22 34](https://cloud.githubusercontent.com/assets/23413915/25561905/53b2a2a2-2da8-11e7-8eb3-fe8940cb47d7.png)

**Comment by zmaster587** [comment]
Alright good!  And no problem!
