### ISSUE TITLE
Cannot Assemble Chemical Reactor

### ISSUE THREAD

**Issue by mgwerner** [zmaster587/AdvancedRocketry#596]
AdvancedRocketry-1.10.2-1.1.7
Forge 12.18.3.2185

Using Holoprojector, have tried multiple times to get the CR to form, only getting the red X indicating something is wrong. Have tried two different motors in case that was the issue, as well as different orientations for the motors.
Pix attached.  Any advice?  Likely something simple I am overlooking.

![2017-04-30_12 32 40](https://cloud.githubusercontent.com/assets/12369588/25561562/d0e2b8b8-2da1-11e7-8b9e-1016fad6569a.png)
![2017-04-30_12 32 28](https://cloud.githubusercontent.com/assets/12369588/25561563/d0e9ca0e-2da1-11e7-8c6d-94091f0cef3b.png)

**Comment by zmaster587** [comment]
Which block is the red X appearing in?

**Comment by mgwerner** [comment]
Thanks for the fast reply.  I discovered the issue, I had not tried the basic motor (Motor), but had tried the higher tier motors.  As I thought, something simple on my part.
LibVulpes-1.10.2-0.2.2-universal

The red X moved with the movement of the character, but seemed to be around the motor.  However, it was not directly over the motor from different angles/heights.

**Comment by zmaster587** [comment]
The higher teir motors should work with it, I may have just forgotten to change the definition of ths structure.  Also the red X should appear in the center of the invalid block.  Was it not doing that?

**Comment by mgwerner** [comment]
Only the basic Motor worked, and while the X was in the area of the motor slot, it moved when I jumped on top and then over the blocks.  To me, it was not definitively indicating the motor, but also indicated the block above, or beside, depending on the angle and position of the character, which is why I posted after only trying the higher tiers.

I just built the Observatory, and after placing Quite Clear Glass inside instead of vanilla Glass, I had the red X directly over the top QCG block.  It did not move when I did.  When I replaced it, there was a black X for the QCG that was inside the structure.  This seemed a much more clear indication of what needed to be addressed than the motor issue with the CR.

Thanks again for the swift reply.  I am enjoying immensely progressing through your mod.

**Comment by zmaster587** [comment]
Strange, the sounds like something might be interfering with GL.  The same code is used to position the X for everything, the machine just passes a location of the block one time and the X gets rendered for 3 seconds.  Will look into the possibility of some kind of interaction.
