### ISSUE TITLE
Astrobody Data Processor - No Chip Input?

### ISSUE THREAD

**Issue by mgwerner** [zmaster587/AdvancedRocketry#599]
AdvancedRocketry-1.10.2-1.1.7
LibVulpes-1.10.2-0.2.2-universal
Forge 12.18.3.2185

Built above machine, connected to Satellite Terminals, all three data buffers full in ADP.  All tutorials I have found online show a slot in upper right of ADP GUI for inserting Asteroid Chip, but there is no such slot in the GUI.  Placing chips in input hatch and clicking the button for Research has no effect - no animation in the flask outlines, no decrease in the 2000 points of any of the three data types.

It appears the process has changed since the tutorials were made, but I cannot find a more recent guide than JAN 2017.  How does one program the Asteroid Chip for mining missions?

Cheers

EDIT:  All multiblocks are powered and indicating full.

**Comment by zmaster587** [comment]
For the alpha builds(1.1.x) chips are now programmed in the observatory
 (ui tab 2).  The observatory no longer collects it's own data and distance
 data must be put in from an external source.  Once the chip is programmed
then you can use it in the ABDP as normal.

One of these days I'll get a chance to make tutorial on it or something

**Comment by mgwerner** [comment]
OK, thanks.  No worries on the tutorial, it's fun discovering (or asking) how to get things right!

**Comment by mgwerner** [comment]
Sorry to reopen.

Linked the Sat Term to the Observatory, which has three data inputs.  There are three Sat Terms, one for each data type.  The three data inputs on the Observatory are all accepting only Distance data.  Data buffers are all full in both the Sat Term and the Observatory.  I have placed the unprogrammed Asteroid Chip into the Observatory.  Scan button remains red, and there is no effect when clicking.  Power is filled at 2000.

What am I doing wrong?  This is the sticking point with prepping an asteroid mission.

**Comment by zmaster587** [comment]
Is it night and does the observetory have an unobstructed view of the sky?  If so the observatory should be open

**Comment by mgwerner** [comment]
Yes, night has the Observatory opening up and gathering data.  However, I hooked the Sat Terms to the Data Ports and watched the data flow into the Observatory from them, which had full buffers due to the three satellites being up for so long.  So, all the data ports are filled with only distance data, and the Observatory Controller is also full.

**Comment by zmaster587** [comment]
It shouldn't be gather data, that was removed in the 1.1.x versions.  But it does need to be night when you scan for asteroids.

**Comment by mgwerner** [comment]
I have the three data inputs of the Observatory connected via data cable to the Sat Term array (6 total, three linked to sats, one of each type) with redstone to activate the data flow.  Observatory buffers filled very fast, I was watching after placing the data cable.  Before that, buffers filled very slowly when Obs was open at night.

What is the solution to being able to program an Asteroid Chip?  Disconnect and rebuild the Obs without the data cable and wait for the buffers to fill?  Also, the Obs Controller only has one data type, does that change automatically, does it matter?

I'd send a photo but am at work.  Can send one of the setup if needed in 10 hours or so.

**Comment by zmaster587** [comment]
If you can send a photo that would be helpful, esp of the UIs.

I'll send what I'm seeing when I test it.

![image](https://cloud.githubusercontent.com/assets/3536685/25689638/1eace6dc-3058-11e7-849a-c38101e8bf07.png)

Observetory tab 2
![image](https://cloud.githubusercontent.com/assets/3536685/25689647/3d769acc-3058-11e7-8c08-63268c97e27f.png)

**Comment by mgwerner** [comment]
First image matches, with the Distance data being completely full.
Second image has both Asteroid and Composition boxes empty, and the Scan! in red.
My observable distance is 100 or 110, how can that be increased, and does that have an effect on data and speed of acquisition?

Thanks for answering so many questions!

**Comment by zmaster587** [comment]
The observable distance only changes how far the telescope can see, some asteroids may require a certain distance for them to show up.  The observable distance can be increased by swapping out the motor for a higher teir version or replacing the glass with the lens block.  It does not have an effect on speed or data.

If you have at least 100 distance data I cannot think of any reason why the button should be in red.  Also is this in single player or on a server?  Also if you click it does it do anything?

**Comment by mgwerner** [comment]
Single player, no response if clicked.

**Comment by mgwerner** [comment]
I'll upgrade to lenses and a higher tier motor, as well as disconnect the data cables when I get home, and see if anything changes.

**Comment by mgwerner** [comment]
Breaking a data cable with bare hands or another block results in no drop.  Expensive error.  Bug or feature?

Here's the setup and pix before rebuilding:
![2017-05-04_18 26 27](https://cloud.githubusercontent.com/assets/12369588/25699851/883af720-30f7-11e7-9015-cd45d705877b.png)
![2017-05-04_18 26 31](https://cloud.githubusercontent.com/assets/12369588/25699849/8828cc58-30f7-11e7-9ce7-d86d898ab8ae.png)
![2017-05-04_18 27 39](https://cloud.githubusercontent.com/assets/12369588/25699850/882cd92e-30f7-11e7-9b2c-6c6ab1574ed0.png)

**Comment by mgwerner** [comment]
After 5 full nights and part of another, with lenses and no data connection, I have no data being loaded in the buffer.

Does the Obs have to be in a dark area?

![2017-05-04_21 15 20](https://cloud.githubusercontent.com/assets/12369588/25705166/f2955dce-310e-11e7-8627-b94ff1aa4b6e.png)
![2017-05-04_21 15 16](https://cloud.githubusercontent.com/assets/12369588/25705167/f31b3980-310e-11e7-8072-c412d0ba38a1.png)

**Comment by zmaster587** [comment]
It does need to be somewhat dark.
But it look dark enough where it is...

No data without a connection is expected as it no longer collects data on
its own.

Would it be possible to upload a copy of the world so I can run some tests
on it?

**Comment by mgwerner** [comment]
I can try to upload to Google Drive and send you and link, but it may not work.  I am in China, and the internet sucks.  Will let you know in 20 hours or so, the only time I can get a somewhat reliable connection is middle of the night.

"No data without a connection is expected as it no longer collects data on its own."
So, should I reconnect the OBS to the Sat Terms with data cable?

I'll also get rid of some of the local lighting, and see what that does.

Cheers

**Comment by zmaster587** [comment]
You can probably get away with uploading on the region that contains the observetory, or if you try to replicate it on a new world that may also work ( coordinate => filename convertor tool http://dinnerbone.com/minecraft/tools/coordinates/).

"So, should I reconnect the OBS to the Sat Terms with data cable?"
Yeah, you'll need to input data from the satellites in the 1.1.x builds.

Good luck, and thanks for bearing with me on this.

**Comment by mgwerner** [comment]
Upload is a nogo, rainy and cold here, everyone is at home streaming video, so connection is crap.

Used lenses to increase distance, reconnected data cables to refresh data, rebuilt OBS, removed local torches, turned it off and back on again.....

Same results.  Data buffer is filling, no asteroids in selection field.

![2017-05-06_09 28 02](https://cloud.githubusercontent.com/assets/12369588/25768833/b01b277c-323e-11e7-86e9-b2eee9ff84c2.png)
![2017-05-06_09 28 05](https://cloud.githubusercontent.com/assets/12369588/25768832/b01ae50a-323e-11e7-9e3b-f1f0a35036d3.png)

**Comment by mgwerner** [comment]
Something I noticed in fiddling with this:  Some machines, sometimes, need to be turned off and back on again when logging out and in, or leaving the chunk.  This seems to be constant with the Chemical Reactor.

**Comment by mgwerner** [comment]
Tried zipping just the region, seems to have uploaded.  
[r.-1.4.zip](https://github.com/zmaster587/AdvancedRocketry/files/980630/r.-1.4.zip)

**Comment by zmaster587** [comment]
Really hate to ask for another file, but can you send the level.dat as well?  The level.dat file contains info as to what block ID is what block in the game.

**Comment by mgwerner** [comment]
OK, here are the two together.  Apology for the delay.
[Desktop.zip](https://github.com/zmaster587/AdvancedRocketry/files/981970/Desktop.zip)

**Comment by zmaster587** [comment]
Thanks, sorry for the delay on getting back to you, but with the copy of the region file I've been able to nail down the issue.  I tried to extract some amount of data for each databus in the multiblock.  So it works fine when there's only one databus of each type of data, but when more than one contain the same type it breaks.

**Comment by zmaster587** [comment]
Until I can get a release out, you should be able to also fix this by removing two of the three data busses.
