### ISSUE TITLE
Duplicate tile entity name with Techreborn mod, causing a crash on startu

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#6]
Already reported on their page https://github.com/TechReborn/TechReborn/issues/162

Crashlog
http://pastebin.com/cMkFNRQ9

**Comment by zmaster587** [comment]
I'll rename all my tile entities to prevent this from crashing again for next release.  I suggest TechReborn ought to do the the same to prevent similar issues in the future.  Apparently Tile mappings are not scoped to a mod.

**Comment by zmaster587** [comment]
Fixed in 0.2.0

**Comment by modmuss50** [comment]
I have enamoured ours in https://github.com/TechReborn/TechReborn/commit/9c3bc97af21748fbf7cc2b5105927bbd90c2af77

Thanks for also doing it on your end.
