### ISSUE TITLE
[1.7.10]Dupe with the pressure tanks

### ISSUE THREAD

**Issue by denwd** [zmaster587/AdvancedRocketry#600]
Incorrect calculation of the filling and empting of tanks under pressure in the stack. Stack of any size is filled and empted as 1 tank (in fillers from other modifications, example Mekanism mod). That is, the stack of tanks is filled, and the fuel is spent as per 1 tank. Tanks from other mods are filled properly.
I saw that in the filler from AR full tanks do not stack, but this solution is only for AR, this is not suitable for other mods. Please solve this problem as soon as possible.

Video with dupe: https://youtu.be/uUPE82tUaCc

**Comment by zmaster587** [comment]
What version of the mod/libvulpes/mc?

**Comment by denwd** [comment]
AdvancedRocketry  latest master branches
LibVulpes-1.7.10-0.1.16-universal
Mekanism-1.7.10-9.1.0.281.jar

**Comment by denwd** [comment]
Good afternoon, when will be able to fix the dupe?

**Comment by zmaster587** [comment]
I'm not sure if i will even be able to.  Handling of buckets is done by the mod the tank is from rather than the bucket, so for me to even figure out what's going on I need to understand how mekanism's bucket handling code works for the fluid tank.  Only once I do that can I verify if it's some standards transgression I'm making, or if it's mekanism's code is broken.

**Comment by denwd** [comment]
I tested Mekanism c other mods or capsules, the bug is absent.

**Comment by zmaster587** [comment]
I get that, I do not know why that is.  It could be that they are using a different means to store fluid (in forge there are 2 standards to do it in 1.7.10 and you kinda have to support both of them in the fluid container).  IFluidContainerItem and FluidContainerRegistry, I do not know which method the other mods use and I have not yet had time to look.

**Comment by denwd** [comment]
Something you can do?

**Comment by zmaster587** [comment]
It doesn't look like there really is.  It is mekanism's block handling extraction of fluids and moving item stacks around, all AR's tanks do in this situation is report how full each item is.

This also appears to be happening with other things.
https://github.com/aidancbrady/Mekanism/issues/3964

**Comment by zmaster587** [comment]
I honestly don't know why the IC2 ones work and AR's don't...

**Comment by zmaster587** [comment]
Correction, turns out IC2 registers its cells like buckets, so the same code is not executed.  That would explain the difference in behaviors.  The IFluid container isn't used all the often but it is much less of a hassle to use...

**Comment by denwd** [comment]
Ic2 fills the capsules one by one with a delay, and your filled with Stak

**Comment by zmaster587** [comment]
Yes, but ic2 capsules are also programed to be buckets using the forge
bucket handler, this means they either are completely full, or completely
empty.  But on order for me to calculate fuel consumption from the tanks
among other things, the tanks have to be able to store everything in
between.  Therefore I have to use forge's other fluid handling system, the
IFluidContainer.  But mekanism treats IFluidContainers differently than
buckets.  In order for me to use the same system the IC2 cells use, I would
need to register more than 64000 items.

**Comment by denwd** [comment]
In this case, I temporarily disable the stacking of tanks, until there is no better solution. If I come up with a solution better, I'll write to you.

**Comment by denwd** [comment]
As an option, to do so with a mechanism they are not combined with the gas station)))

**Comment by zmaster587** [comment]
I would prefer not to disable stacking of the empty tanks at least, but there does not appear to be any other solution that I can think of either.  Might be better to do in case other mods have similar troubles though
