### ISSUE TITLE
Allow specifying if crater or extreme height mountains can be generated in the planetdef.xml

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#602]
It seems that right now they are generated everywhere

**Comment by zmaster587** [comment]
Number of craters generated are a function of atmosphere density already and should spawn more frequently on planets with low pressure atmospheres and should never spawn on planets with atmospheres higher than 75.  Is there any reason you'd want to specify craters independant of atmosphere density on a per-planet basis?

As for the exteme height mountains I'll look into why they're spawning so frequently.  I feel like they might be disabled in vanilla for some reason so their weights may have never been set.

**Comment by zmaster587** [comment]
Extreme height biomes can already be determined via the XML because they are all biomes of some type.  As for the craters, I'm probably not going to add that as an option due to the fact they can already be controlled by the atmosphere amounts.
