### ISSUE TITLE
Asteroid Chip into Observatory not Working

### ISSUE THREAD

**Issue by mgwerner** [zmaster587/AdvancedRocketry#604]
Sorry if this is a dupe, reopening the last issue did not seem to update the issues page.

Linked the Sat Term to the Observatory, which has three data inputs. There are three Sat Terms, one for each data type. The three data inputs on the Observatory are all accepting only Distance data. Data buffers are all full in both the Sat Term and the Observatory. I have placed the unprogrammed Asteroid Chip into the Observatory. Scan button remains red, and there is no effect when clicking. Power is filled at 2000.

What am I doing wrong? This is the sticking point with prepping an asteroid mission.

**Comment by zmaster587** [comment]
Duplicate: see #599 
It's fine, I get notifications from closed issues too.  Closing this to keep things organised
