### ISSUE TITLE
Suit workstation dupe?

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#605]
![image](https://cloud.githubusercontent.com/assets/2989009/25680673/f0697840-3051-11e7-9e50-15f4292f4202.png)
![image](https://cloud.githubusercontent.com/assets/2989009/25680693/fadcfd2e-3051-11e7-8963-63b4f1f0d6f1.png)
![image](https://cloud.githubusercontent.com/assets/2989009/25680705/02570cca-3052-11e7-9960-ab91bb7d2ea6.png)
![image](https://cloud.githubusercontent.com/assets/2989009/25680710/080fa78a-3052-11e7-8969-c2a0ded58d05.png)

Could be related to tfc through

**Comment by zmaster587** [comment]
How did you get from A to B with any of these?

**Comment by wormzjl** [comment]
just wear them and open the suit workstation

**Comment by wormzjl** [comment]
seems to be an TFC issue
