### ISSUE TITLE
[1.10.2] Newest Version Requires Old LibVulpes Version

### ISSUE THREAD

**Issue by MokahTGS** [zmaster587/AdvancedRocketry#608]
The 1.1.7 version of AR is requiring an out of date version of the LibVulpes mod asking for the 0.2.2 Alpha instead of the release which is 0.1.18.  Curse thinks this is a newer file and lists it for update.

**Comment by zmaster587** [comment]
Are you saying curse is trying to update from Libvulpes 0.1.18 to 0.2.2 or from 0.2.2 to 0.1.18 for AR 1.1.7?

**Comment by MokahTGS** [comment]
Trying to update from 0.2.2 to 0.1.18 for AR 1.1.7

**Comment by zmaster587** [comment]
I suspect that's more of an issue with the order in which I uploaded the versions of the mod to curse.  Next time I'll make sure to release the alpha build after the stable build to prevent this from happening again.
