### ISSUE TITLE
Machine problems

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#61]
I have been observing some weirdness with the machines

First is that sometimes they does not produce the same number of output item as input.
Like when I feed the rolling machine with 1 stack of steel ingot, and it produces something like 60 plates.
This might have something to do with unloaded chunks, when I go out sight of the machine does it save it's current condition properly upon chunk unload?

Secondly sometimes the machine just reset itself when working, this can happen before my eyes, the power button turns red, and all stuff inside disappeared.

3rdly sometimes the machine itself partially disappears, I need to right click on the main block to make it appear again. It's probable because the main block is located on different chunks with other parts of the machine.

**Comment by wormzjl** [comment]
More: if you use shift + click to move item into the input slot of machines you have more chance of losing stuff. And this can happen when the player is present.

**Comment by zmaster587** [comment]
Are there any pipes connected to the machine?

**Comment by DarkGuardsman** [comment]
Are you running a server? or is this single player?

**Comment by zmaster587** [comment]
both

**Comment by zmaster587** [comment]
See if it still occurs in 0.4.7

**Comment by wormzjl** [comment]
[18:52:09 INFO]: zmaster587.advancedRocketry.tile.multiblock.TileRollingMachine@4a1fddd4     wft?
[18:52:09 INFO]: zmaster587.advancedRocketry.tile.multiblock.TilePrecisionAssembler@21abc69f     wft?
[18:52:09 INFO]: zmaster587.advancedRocketry.tile.multiblock.TileLathe@37e44375     wft?

got this sort of stuff in the log :P

**Comment by zmaster587** [comment]
bit of debug code I missed...  The 0.4.x releases have been a bit of a mess :/

**Comment by wormzjl** [comment]
Got some sort of memory leak...investigating

**Comment by wormzjl** [comment]
Incoming dupe bug
https://youtu.be/Xr0i8KwCD0Y
