### ISSUE TITLE
Biome and planet texture specification in planetDefs.xml is broken 

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#610]
Using the experimental build you have given me
Seems that right now the biome is randomly generated

**Comment by zmaster587** [comment]
Which build is it?

**Comment by wormzjl** [comment]
AdvancedRocketry-1.7.10-1.2.0-12.jar

**Comment by zmaster587** [comment]
It looks like it's not loading the biomes only when the world is first created but it does appear to read from the saves/world/advRocketry/planetDefs.xml just fine on subsequent loads.  Investigating...

**Comment by wormzjl** [comment]
thx! can you get a new build on jenkins so I can test?
