### ISSUE TITLE
Jackhammer destroys chiseled stones

### ISSUE THREAD

**Issue by Geird** [zmaster587/AdvancedRocketry#611]
When using the Jack hammer to dig a rock that has been changed to a chisel variant, the block will not drop. (Tested with marble, cobblestone, diorite) It does not do this on the non chiseled variants with the exception of marble. (from chisel) I could be wrong, but I feel this is probably a mod interaction bug.
[Mod list](http://imgur.com/GWnq7by)

**Comment by zmaster587** [comment]
Turns out the jackhammer just did not work past the hardcoded list.  Fixed.
