### ISSUE TITLE
[1.10.2-1.0.17] Cannot disable ores through config

### ISSUE THREAD

**Issue by savosdarkran** [zmaster587/AdvancedRocketry#612]
I set the ores to "false" instead of true, but when I reload the pack to see if my changes have taken place the false turns to true.  I have  a work around of setting the PerChunk values to 0.

**Comment by zmaster587** [comment]
Did you only save the conif after minecraft was completely closed?

**Comment by savosdarkran** [comment]
Worked!  Sorry about that.  Thanks for the response.

**Comment by zmaster587** [comment]
No problem!  I've introduced a patch to make it not save the config on game save if UI editing is disabled (which is it by default and really only there for modpack makers' ease of use).  Hopefully it'll be less of an issue in the future
