### ISSUE TITLE
Only a single player may ride a rocket even if multiple seats are installed.

### ISSUE THREAD

**Issue by Poyo-SSB** [zmaster587/AdvancedRocketry#613]

**Comment by zmaster587** [comment]
Multiple riders per rocket has not been implelented yet.  While it is easily doable in 1.10.2, it's very hard to implement in 1.7.10 and I'm trying to keep feature sets consistant between the two versions.

**Comment by Poyo-SSB** [comment]
Good to know. Thank you.
