### ISSUE TITLE
Remove Rolling Machine Recipes From JEI?

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#615]
Hey Zmaster,

Due to progression, I've removed rolling machines/plate pressers except for the I.E. presser. But, the rolling machine and Plate Presser from Advanced Rocketry still shows in JEI as a possible recipe, which confuses players. Do you know of a way for me to disable these recipes from showing in JEI?

Thanks!
Darkosto

**Comment by zmaster587** [comment]
I've never expected the machine to be disabled so I didn't add anything explicit.  What you can do though is open the config/advRocketry/RollingMachine.xml, change useDefault="true" to useDefault="false" and remove any recipe from the list.  You can do the same with "SmallPlatePress.xml"

**Comment by Darkosto** [comment]
Yep, that works perfectly. Thank you :)

**Comment by zmaster587** [comment]
No problem!

**Comment by Darkosto** [comment]
Quick question for you, do you have plans to move to 1.11 in the future? :)

**Comment by zmaster587** [comment]
I do.
I'm not trying to be put-off-ish, but I had somebody ask me the same thing just yesterday, and because the explaination is rather lengthy, I hope you don't mind if i just link the post.
https://minecraft.curseforge.com/projects/advanced-rocketry#c1190

**Comment by Darkosto** [comment]
No worries, thanks for the post to see what's up :)

I'm looking forward to using the mod (hopefully!) in a future pack I have planned. Good luck on your work so far! and thank you for all the help!
