### ISSUE TITLE
Rocket GUI Client Crashing

### ISSUE THREAD

**Issue by GoodBob** [zmaster587/AdvancedRocketry#619]
Inconsistent crash-to-desktop while interacting with a built rocket's GUI. Seems to happen more so while interacting with the guidance computer.
[crash-2017-05-08_00.43.15-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/982461/crash-2017-05-08_00.43.15-client.txt)

**Comment by zmaster587** [comment]
Are you able to replicate the issue with only libvulpes and advanced rocketry installed?
If not can you find out what other mod(s) must be installed to reproduce the crash?

**Comment by GoodBob** [comment]
Eesh, I can try to figure out which mod it is but it might take awhile. I'm playing the modpack called "All the Mods" so there's a few to go through.

**Comment by GoodBob** [comment]
I've noticed that if i am only looking downward when interacting with a rocket's GUI, i don't crash.

**Comment by zmaster587** [comment]
Very strange indeed.  The crash indicates postworldrender and there's nothing in there that is direction dependant for rendering...

**Comment by zmaster587** [comment]
Anyway, few other people reported similar issues in completly different situations, so I just put in a nullcheck anyway.  I cannot diagnose random so..
