### ISSUE TITLE
[1.10.2] NPE crash in BiomeProvider#findBiomePosition()

### ISSUE THREAD

**Issue by maruohon** [zmaster587/AdvancedRocketry#623]
Advanced Rocketry doesn't seem to properly override or initialize all the `BiomeProvider` class's methods/fields. If the `findBiomePosition()` method is called for `ChunkManagerPlanet`, it will crash with an NPE because of the `genBiomes` field being null in the super/vanilla class. There may be other similar issues/fields, but this is one crash that occurs for sure.

This happens when using for example the Just Enough Dimensions mod, version 1.5.0 or newer (due to some spawn point search related changes in that version, which now causes the `findBiomePosition()` method to get called), if the WorldInfo override is enabled for an Advanced Rocketry dimension (which causes JED to try to find a spawn position for the dimension).

Here is one such crash report: https://pastebin.com/3rmyHxb5
And here is the situation at a breakpoint at the line that will crash: http://i.imgur.com/XVQCpWF.png

This is in MC 1.10.2, using libVulpes 0.2.2 and Advanced Rocketry 1.1.7.

**Comment by zmaster587** [comment]
This appears to be due to the fact that I was unable to access the private field in the super class to set it.  A method in the super class was called which relied on the uninitialized variable in the super class.  Easiest fix I suppose would be just to copy the method from the superclass

**Comment by maruohon** [comment]
Yep, just overriding the method (and copying the implementation if applicable) is an easy way to fix it. Unless you want to reflectively set the field in the super class when you set your own copy of it.

Yes, JED will search for and use per-dimension spawn points, **if** the WorldInfo override feature is enabled for a given dimension. JED itself uses those per-dimension spawn points in the teleport command, so that it will lead to a suitable position (and not for example inside ground, which is a common case, if it were to use the overworld spawnpoint, which would normally happen without the WorldInfo override), without having to search for a suitable position every time the command is run.

It is of course also possible for something else to call the `findBiomePosition` method, resulting in the same crash. But apparently such a case seems to be pretty rare, if nobody else has reported such a crash thus far.

**Comment by zmaster587** [comment]
Does this crash occur with default config in JED and first visiting a planet?

**Comment by maruohon** [comment]
No, the default configs in JED basically do nothing at all. If you want to reproduce this, enable the WorldInfo override option in the JED main config (via the in-game config menu for example), and then create a config file in `config/justenoughdimensions/dimensions.json`, like this: https://pastebin.com/izmtFaWH where the `dim` ID is whatever the Advanced Rocketry dimension uses. This should cause JED to try to find a spawn point for that dimension, when the dimension is loaded for the first time (it doesn't yet have its own `level.dat` file). For testing/debugging, I'd also recommend enabling the verbose logging option in JED, so you get log messages (at the INFO level) about when JED does certain things, like tries to find the spawn point.

**Comment by zmaster587** [comment]
Alright, confirmed the issue on my end.

**Comment by zmaster587** [comment]
Tested and appears to work
