### ISSUE TITLE
Standing Inside Door Causes Damage

### ISSUE THREAD

**Issue by GoodBob** [zmaster587/AdvancedRocketry#625]
I first noticed this with MalisisDoors' High-Tech Doors. While on a space station with an oxygen vent supplying oxygen to a room, if I stand next to a closed high tech door or inside an open one, i'll take suffocation damage.

I've also noticed this happening with the Small Airlock Doors from AdvancedRocketry. If the door is placed in a way to put the door on the edge farthest away from the room with oxygen, if i stand in the doorway itself with the door closed, i take suffocation damage.

![2017-05-11_00 13 40](https://cloud.githubusercontent.com/assets/7384393/25933736/f4ddca10-35de-11e7-84fb-fd2275d49e5a.png)
![2017-05-11_00 13 45](https://cloud.githubusercontent.com/assets/7384393/25933740/f91a7dd0-35de-11e7-9633-1755a05dc9f1.png)

**Comment by zmaster587** [comment]
Part of that is due to the fact that AR's atmosphere's stop whenever it encounters a solid block like a door.  I'm not really sure how to fix this without changing the logic for seal checking.  So a fix may take a bit of time.

**Comment by Divineaspect** [comment]
Would changing the model for the door to be solid on two parallel sides be a  workable fix?
Changing the accessibility rather then the seal checking.

**Comment by zmaster587** [comment]
I could do that, but the airlock door is not the only block with this problem.  So I'd just have a solution for a single block.  A Universal solution would be much better.

**Comment by GoodBob** [comment]
> AR's atmosphere's stop whenever it encounters a solid block like a door.

Would it not be possible to simply add +1 range to the check? To include the immediate surrounding blocks?
I'm still learning basics of coding so feel free to ignore my suggestion.

**Comment by zmaster587** [comment]
I'd have to do something similar to that, but the reason that's difficult is the algorithm does not allow air to occupy the same space as solid blocks and uses whether or not a block is solid to halt its propagation.  If I make it just +1, then I have to also make sure it doesn't try to propagate out the other side of any 1 block thick wall.

**Comment by Divineaspect** [comment]
might also do something on the player side, looking for air in adjacent blocks before suffocation starts.

**Comment by zmaster587** [comment]
That could work, but it would have to be on the server side (suffocation is calculated only on the server to prevent cheating) and the additional checks every tick would increase load slightly.  I'll consider it as an option though

**Comment by cad435** [comment]
bug is still present...

well, what about just prevent any player inside a sealed door from taking damage? Thats a very bad fix indeed, but we are able to walk inbetween spacestations and don't get hurt constantly....

greetings 
cad435

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
