### ISSUE TITLE
Rockets on mining missions return empty

### ISSUE THREAD

**Issue by rkane31174** [zmaster587/AdvancedRocketry#629]
Even when sent with chips that have all 2000 data points in them in the three important categories (distance, mass, composition), the rockets keep returning completely empty.

I set the mining mission multiplier to .125 just for testing, and these ores are listed to be spawnable on asteroids

        oreIron
        oreGold
        oreCopper
        oreTin
        oreRedstone
        oreYellorite
        oreRutile
        oreIridium
        oreSilver
        oreLead
        oreNickel
        orePlatinum

**Comment by zmaster587** [comment]
Are you using a 1.0.x build and did you put drills on the rocket?

**Comment by rkane31174** [comment]
1.7.10 build, and I have at least four drills and four chests on the rocket.

**Comment by rkane31174** [comment]
Oh wait, I misunderstood.
I'm using release build 1.0.18 for minecraft version 1.7.10

**Comment by zmaster587** [comment]
Does this still occur with the multiplier at 1?

**Comment by rkane31174** [comment]
With a time multiplier of 1.0? Yes it does.

**Comment by zmaster587** [comment]
Wait, are you changing the time multiplier or the ore multiplier?

**Comment by rkane31174** [comment]
I was changing the time multiplier, not the ore multiplier.

**Comment by zmaster587** [comment]
Ah, that's very strange then... I typcially keep the time multiplier at 0.1 in my dev environment and have not encountered this issue before.  I'll try exactly 0.125 and see if there's something odd about that number...

**Comment by rkane31174** [comment]
I tested it at multiplier value of 0.1 and it still didn't work.
Do you think that it's a problem with my ore list?
Also, the drills don't have to be connected to the chests, do they?

**Comment by zmaster587** [comment]
I don't think it's an issue with the orelist, because even if you had nothing in the orelist, you should still get stone back.

The Drills don't have to be connected to the chest, no, but you can't have any blocks above them in the 1.0.x builds

**Comment by rkane31174** [comment]
!!!
I can't have anything above the drills?
That might be the problem. Testing now.

**Comment by rkane31174** [comment]
That was it! My drills were all just covered by something.
Thank you!

**Comment by zmaster587** [comment]
No problem!  Got it working then?

**Comment by rkane31174** [comment]
With the 1.0.x version, it works if I uncover the tops of the drills.
With the 1.1.7 version, it crashes as soon as the mission is complete.
So it's fixed for the stable version, but the alpha still has some sort of problem.

**Comment by zmaster587** [comment]
Can you post a crash report for the 1.1.7 build?

**Comment by rkane31174** [comment]
[crash-2017-05-14_17.18.22-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/999780/crash-2017-05-14_17.18.22-server.txt)

That should do it.

**Comment by zmaster587** [comment]
Alright, I'm not 100% sure but I think this was fixed.  I do remember adding a null check because in the case of somebody sending up a chip that wasn't programmed in the observatory it would crash with a similar error.

**Comment by rkane31174** [comment]
Tested the 1.2.0 build, game does not crash, but rocket arrives empty again.

**Comment by zmaster587** [comment]
Did you program the asteroid chip in the observatory in the 1.2.0 build?

**Comment by rkane31174** [comment]
...No I did not. I was using one of the 1.0.x chips.
I will test this immediately.

**Comment by rkane31174** [comment]
No good. Even when programmed with the observatory, the rocket returns empty.

**Comment by rkane31174** [comment]
NEVERMIND!
My mistake, the unloader was not enabled.
It works.

**Comment by zmaster587** [comment]
Alright, good to hear!
