### ISSUE TITLE
Startup crash without galacticraft

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#63]
http://pastebin.com/L4MqxQW0

**Comment by wormzjl** [comment]
hmm seems to be https://github.com/zmaster587/AdvancedRocketry/issues/62

**Comment by zmaster587** [comment]
Forgot to check in one location of GC was loaded.   Turning "OverrideGCAir" to false in the config should get it to run until I get a build pushed.
