### ISSUE TITLE
Suit Workstation deletes tank

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#630]
MC 1.10.2
Forge 2281
AR 1.0.17
libvulpes 0.1.18

Steps to reproduce:
1.) Place Suit Workstation down
2.) Place Spacesuit Chestplate in Workstation
3.) Place Jetpack in first slot
4.) Place High Pressure Tank in second slot
5.) Shift click High Pressure Tank in Suit Workstation
This second High Pressure Tank just gets deleted.

**Comment by zmaster587** [comment]
I had already made some changes to the way the tank works in the more recent builds of the mod, would it be possible to test and see if it's still an issue with this build?
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/MC1_10/
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/MC1_10/

**Comment by davqvist** [comment]
Doesn't happen on the jenkins build anymore. Thanks.

**Comment by zmaster587** [comment]
No problem
