### ISSUE TITLE
Crash when taking Planet Id Chip out of rocket

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#631]
MC 1.10.2
Forge 2281
AR 1.0.17
LV 0.1.18

A user of my modpack was on moon and was trying to figure out how to get to earth. Accidently he took the Planet Id Chip out and immediately crashed. He logged later back in and could fly back to Earth without problem.

Here the crash:
https://pastebin.com/cV4n0VUW

**Comment by zmaster587** [comment]
I don't think that's related to the chip at all and happens to just be coincidence.  It appears something is screwing with the overworld provider's worldObj reference.  As far as I am aware this reference cannot be null in vanilla, so I strongly suspect some kind of mod interaction.

**Comment by zmaster587** [comment]
Are you able to replicate this issue without any other mods installed.  If not can you determine the minimum set of mods to replicate this issue?

**Comment by davqvist** [comment]
No, unfortunately not and it didn't happen again to him. Not sure what in fact caused it.

**Comment by zmaster587** [comment]
Alright, if you can replicate it post back here and we can reopen the issue.
