### ISSUE TITLE
1.10.2 crash on minecraft startup

### ISSUE THREAD

**Issue by Zygus42** [zmaster587/AdvancedRocketry#634]
Newest version AdvancedRocketry-1.7.10-1.0.19, LibVulpes-1.7.10-0.1.19-universal
No other mods
Forge forge-1.10.2-12.18.3.2254-installer-win
Crashing as soon as you start Minecraft up, but no crash report.

**Comment by zmaster587** [comment]
Can you post the logs/fml-client-latest.log logfile?

**Comment by Zygus42** [comment]
Been quite a few runs since I set up that test - think it was this one.

[2017-05-16-1.log.gz](https://github.com/zmaster587/AdvancedRocketry/files/1002647/2017-05-16-1.log.gz)

I notice that when I retry it now, it launches, whereas it was failing every time, normal minecraft and server as well.  Not sure what's going on.

**Comment by Zygus42** [comment]
doh
reading the above, was using the 1.7.10 in my 1.10.2 game :(  Talk about a Rookie mistake.  My humblest apologies.

**Comment by zmaster587** [comment]
It happens.  There was one time I spent nearly an hour trying to setup IC2 in my dev environment and I had done the same thing.
