### ISSUE TITLE
Player Kicked From Server When Selecting Destination (Space Elevator)

### ISSUE THREAD

**Issue by Zundrel** [zmaster587/AdvancedRocketry#635]
I'm having an issue with Space Elevators in SMP. Every time a friend of mine tries to select a destination (presses the Select Destination button) inside of the Space Elevator GUI it kicks him from the server with the message "A fatal error has occured, the connection has been terminated". The elevator is fully powered and the chips are linked. This occurs for other players as well, but it only kicks the person who presses the button. He's able to rejoin afterwards just fine, but nothing in the GUI has changed.

This is occuring in the alpha of Advanced Rocketry 1.2.0 for 1.7.10.

I assume something is going wrong while trying to send packets to the server/client.

**Comment by zmaster587** [comment]
Can you get the stacktrace from the server/client log?

**Comment by zmaster587** [comment]
Possibly fixed with #636

**Comment by Zundrel** [comment]
I'm not currently in a position to get the stacktrace from his client, but the server seems to say nothing. I'll test if it still happens later and if needed will provide a client stacktrace.

**Comment by Zundrel** [comment]
The issue is no longer present in the latest alpha. Thanks a lot :D.
