### ISSUE TITLE
Server Crash On Right-clicking Planet Selector

### ISSUE THREAD

**Issue by Zundrel** [zmaster587/AdvancedRocketry#636]
We placed down and right-clicked on the Planet Selector and the server crashed with this report: https://pastebin.com/PyU5gXZu

It seems to be missing a class from LibVulpes, but I checked and the class is still present in the jar file. We're currently using LibVulpes 0.2.3 for 1.7.10.

We rejoined and it did not crash the server again. Seems to only be triggered on right-click.

**Comment by zmaster587** [comment]
Trying to load a client only class on server, will fix
