### ISSUE TITLE
[1.7.10]Crash when placeing a Docking pad

### ISSUE THREAD

**Issue by KevKev919** [zmaster587/AdvancedRocketry#639]
Iam playing on the MC 1.7.10 Forge Version: 10.13.4.1614-1.7.10
Lib Vulpes Version 1.7.10-0.2.3 Mod Version  1.7.10-1.2.0 respectively 1.2.0b (i tryed both)

The Issue:

Quite Simple the game Crash everytime i try to place a Docking Pad (Crashlog in the attachment) 

[crash-2017-05-16_23.09.27-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1005837/crash-2017-05-16_23.09.27-server.txt)
For a full list of installed mods the Config Dic. or anything just ask.

I hope you can solve that Problem Quckly or tell me where the problem with my installation is so i can solve it.

greetings
Angel

**Comment by zmaster587** [comment]
Looks like it's trying to save an empty name and failing.  investigating
