### ISSUE TITLE
Broken Link on Mod Wiki

### ISSUE THREAD

**Issue by dsbookbug** [zmaster587/AdvancedRocketry#641]
Just a heads up, but on the ["Rockets Guide"](http://65.78.115.159:8000/AdvancedRocketry/guides/Rockets.php) page, where it says "A static shipping route can be set up by linking two [docking pads](http://65.78.115.159:8000/AdvancedRocketry/blocks/DockingPad.php) together with [linkers](http://65.78.115.159:8000/AdvancedRocketry/items/linker.php)", the docking pads link is broken. It appears that you remained the page to "[Landing Pad](http://65.78.115.159:8000/AdvancedRocketry/blocks/LandingPad.php)", but you didn't update the page, or change any of the pages that link to it.

**Comment by dmodoomsirius** [comment]
take a look at http://arwiki.dmodoomsirius.me I am now hosting the wiki for Zmaster. what ever is on his latest for what he has on github. I am finailizing updating that url atm.

**Comment by zmaster587** [comment]
i did rename the page, will have it updated in a bit

**Comment by zmaster587** [comment]
should be fixed
