### ISSUE TITLE
crashed when placing the Landing Pad

### ISSUE THREAD

**Issue by Uptobillion** [zmaster587/AdvancedRocketry#642]
The report ：
“MC: [12:38:39] [Server thread/ERROR] [FML]: A TileEntity type zmaster587.advancedRocketry.tile.station.TileLandingPad has throw an exception trying to write state. It will not persist. Report this to the mod author”

Minecraft version：1.10.2
Forge：2297
Mod：
advanced rocketry 1.20 and 1.20b
LibVulpes 0.2.3

**Comment by zmaster587** [comment]
darnit, thought that was fixed in 1.2.0b, investigating

**Comment by zmaster587** [comment]
Should be fixed in version c
