### ISSUE TITLE
Why the planet analyser don't work？

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#643]
![2017-05-18_17 25 25](https://cloud.githubusercontent.com/assets/23413915/26195947/f58bc694-3bef-11e7-8d3f-632ac74f080f.png)
Like this，the version is alpha 1.2.0b。

**Comment by zmaster587** [comment]
In the 1.1.x and 1.2.x builds asteroid chips are now programmed in the observatory.
http://65.78.115.159:8000/AdvancedRocketry/blocks/Observatory.php
http://65.78.115.159:8000/AdvancedRocketry/blocks/Abdp.php
