### ISSUE TITLE
Custom machine recipes cannot have more than 3 inputs

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#644]
Just updated to the latest version and some recipes I've made was broken
All recipes with less than 4 inputs stays normal
Here is my script and what they are shown in game

https://pastebin.com/5Dbz8bS7

![image](https://cloud.githubusercontent.com/assets/2989009/26263547/8ed8a0c6-3cd9-11e7-8105-cf2e73e9464c.png)
![image](https://cloud.githubusercontent.com/assets/2989009/26263564/9edf09ec-3cd9-11e7-8cd6-74b8169a728b.png)
![image](https://cloud.githubusercontent.com/assets/2989009/26263574/a7ab1e80-3cd9-11e7-8cb1-cfc5aee64c9d.png)

**Comment by wormzjl** [comment]
Ok... this could be a visual glitch
When I put my mouse between the first 2 ingredients I found the missing item, wtf
![image](https://cloud.githubusercontent.com/assets/2989009/26264595/b3e6d276-3cdd-11e7-8e13-1dee84c0c51e.png)

**Comment by zmaster587** [comment]
If you put all 4 in the machine does it process as expected?

**Comment by zmaster587** [comment]
It seems to work fine for NEI when no fluids are specified I noticed

**Comment by zmaster587** [comment]
input and output counters got swapped
