### ISSUE TITLE
Docking pad causes game crash

### ISSUE THREAD

**Issue by LawsOfScience** [zmaster587/AdvancedRocketry#645]
Whenever I place a docking pad (any dimension) in the world, it crashes my game. 
-Edit-
Found a report, here it is: 
[crash-2017-05-20_10.33.20-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1016236/crash-2017-05-20_10.33.20-server.txt)
Have fun reading it, cause I sure can't. :P 
Also, it seems my world won't load since I added a docking pad on my space station just to test. Thought I'd add this to make it known to you devs. (Yes, I was in the station at the time of the crash)

**Comment by zmaster587** [comment]
Appears to be the same as #639 
I thought i released a version C a few days ago with the patch, I guess i forgot, will have a build up shortly
