### ISSUE TITLE
1.11.2 startup crash

### ISSUE THREAD

**Issue by leftyde** [zmaster587/AdvancedRocketry#646]
https://pastebin.com/WRgAj5vD

it just crashes.

**Comment by mainframecn** [comment]
Same here, did a clean install with just AR & Libvulpes.

**Comment by leftyde** [comment]
Libvulpes does work! it's just Advanced Rocketry

**Comment by tiarnia** [comment]
same here

**Comment by zmaster587** [comment]
Turns out to be an ASM handing error.  I didn't catch it because my debug and testing environment doesn't take into account minecraft's obfuscation, I pushed out a build a few minutes ago that should be fixed.

**Comment by leftyde** [comment]
thanks :)
