### ISSUE TITLE
NEI not showing up in 1.11

### ISSUE THREAD

**Issue by rhoark** [zmaster587/AdvancedRocketry#649]
Tested with just 1.11.2, AdvRocketry, LibVulpes, JEI, NEI, and ChickenCore installed. No AdvRocketry machine support appears in NEI/JEI, just crafting table recipes.

**Comment by FangedHex** [comment]
I confirm this bug as well on my modpack. No JEI support but it was supported in 1.10.2 :)

**Comment by zmaster587** [comment]
Still working on it, planning on adding NEI support back in as well and is taking a bit of time.  There'll likely be a build with JEI support on the Jenkins within the next few hours

**Comment by zmaster587** [comment]
Should be fixed in this build http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/MC1.11/3/

**Comment by FangedHex** [comment]
Dude, you are amazing, you work so fast :O
