### ISSUE TITLE
gui for hydrogen

### ISSUE THREAD

**Issue by Arkeus121** [zmaster587/AdvancedRocketry#650]
Hi,
I've been playing on Darkosto's invasion modpack and I added a super high pressure tank to my space suit to store hydrogen but i found when trying to move the gui to be more eye-friendly that the hydrogen meter doesn't move when the oxgen meter and suit config does.
I also noticed there isn't a hydrogen meter configuration in the config file.
Thank you.

**Comment by zmaster587** [comment]
I guess I missed that.  Will look into adding ability to move it.

**Comment by Arkeus121** [comment]
Just checked you can't move the atmospheric analyzer display either
