### ISSUE TITLE
Crash When Shift Clicking Most Items

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#651]
Heya Zmaster, 

I've been getting this crash when shifting over, or shift-clicking on items from other mods:

https://pastebin.com/R1aQ6xbH

MC: 1.11.2
Forge: 2304
A.R.: 1.2.0d
LibVulpes: 0.2.3

Thanks for checking this out :)
Darkosto

**Comment by zmaster587** [comment]
Looks like a combination of a missing check from both AR and chisels and bits
