### ISSUE TITLE
[1.11.2] Multipart between cable doesn't show

### ISSUE THREAD

**Issue by FangedHex** [zmaster587/AdvancedRocketry#654]
It's just a graphical problem, the logic is working but when I put 2 cables next to each other, they doesn't connect :( But it works correctly between machine <-> cable.

EDIT : If I reload the world, the multipart that connect machine <-> cable disappear !

**Comment by zmaster587** [comment]
Looking into it.

**Comment by FangedHex** [comment]
It seems that the energy cable connects but not the fluid or the data cables
 
See that screenshot to see what I mean :
![2017-05-26 22_21_54-minecraft 1 11 2](https://cloud.githubusercontent.com/assets/2796509/26511314/c9455f3c-4261-11e7-9199-2d64615a37a5.png)

**Comment by FangedHex** [comment]
Thanks dude ! :)

**Comment by zmaster587** [comment]
no problem
