### ISSUE TITLE
dim's bug

### ISSUE THREAD

**Issue by Leaveleaf** [zmaster587/AdvancedRocketry#655]
we're can't move at a server about all rocketry dim's when we‘re’ close nether by '**server.properties**'.we're play a modpack 'Invasion'.AdvancedRocketry-1.10.2-1.2.0c,╮(╯_╰)╭

**Comment by dmodoomsirius** [comment]
Similar to https://github.com/zmaster587/AdvancedRocketry/issues/555 please look that that bug report.

**Comment by Leaveleaf** [comment]
oh! thanks
