### ISSUE TITLE
orbital laser drill bug

### ISSUE THREAD

**Issue by maxall4** [zmaster587/AdvancedRocketry#656]
when i try to open the interface for the orbital laser drill it crashes the game

**Comment by zmaster587** [comment]
Can you send a copy of the crash report?

**Comment by maxall4** [comment]
i cant it just freezes the game

**Comment by zmaster587** [comment]
Can you send a copy of the fml-client-latest log file after freezing the game then?

**Comment by maxall4** [comment]
minecraft version 1.11.2 and libvulpes 0.2.3b
