### ISSUE TITLE
Armour Crashes

### ISSUE THREAD

**Issue by TheRealM18** [zmaster587/AdvancedRocketry#659]
Hello

I have found a bug with the latest version of advanced rocketry in curse.  This bug will crash the client if you  are in multiplayer environments. the pastebin is the following https://pastebin.com/X6F7xB6P . the crash happeneds when you jump into water. it affects even iron armour. 

thank you and i hope that you will fix this soon.

**Comment by zmaster587** [comment]
I think this may actually be an interaction with the player progression mod.  I noticed that it is trying to create a default instance of the space armor capability on an object that doesn't have it (see line 52 of the report given).  Nor have I been able to replicate the issue without other mods installed.  Can you attempt to replicate the issue without player progression installed and let me know if the issue still occurs without it?
