### ISSUE TITLE
Allow shift-click to input hatches

### ISSUE THREAD

**Issue by pyure** [zmaster587/AdvancedRocketry#660]
Allow users to shift-click items into hatches, similar to other containers.

**Comment by zmaster587** [comment]
Assuming you're running 1.10.2 as mentioned https://github.com/zmaster587/AdvancedRocketry/issues/662 I've tried testing with the latest minecraft build and have had no problems shift clicking into input hatches.

**Comment by pyure** [comment]
As mentioned in 662, I think I've made the embarassing error of failing to double-check my version.  Will update this issue momentarily to confirm.

**Comment by pyure** [comment]
Confirmed non-issue.  You've fixed this already.

Not sure I can explain how I forgot to double-check version.  Apologies.
