### ISSUE TITLE
Multiblock input hatches don't update status on first iteration

### ISSUE THREAD

**Issue by pyure** [zmaster587/AdvancedRocketry#662]
If you place a valid recipe requirement into an input hatch (say wood into a cutting table), for a machine which is in ON state, the multiblock consumes an item for the recipe but the gui for the hatch doesn't always reflect this until the first iteration is complete (or you close/reopen the hatch)
(After this point, the gui updates on each completed recipe properly)

**Comment by zmaster587** [comment]
What version of minecraft?

**Comment by pyure** [comment]
Apologies: 1.10.2.

I'll add mod-version/mc-version to my other tickets as well.

In fact, I just realized I'm several versions behind (1.1.17).  I'm going to quickly update and see if I can close some of these.

**Comment by pyure** [comment]
I've updated to latest mod version, so we're looking at 1.10.2-1.2.0c

I can confirm that this issue still persists, although its not 100% reliably reproducible.

In the attached image, I've put a single silicon wafer into the hatch.  There was already 31 gold and redstone.  The recipe has begun processing, but the items in the hatch have not **visually** decremented to 0/30/30.

![image](https://cloud.githubusercontent.com/assets/8617528/26531884/3a90adb2-43c1-11e7-8ff1-b500a61ecd15.png)

**Comment by zmaster587** [comment]
Appears to only show up on servers, likely something to do with marking the block dirty and sending changes.

**Comment by pyure** [comment]
Not on a server.  Since its not 100% reproducible I think you're seeing a false positive as it were.

**Comment by zmaster587** [comment]
I've not seen it occur in single player over dozens of tests, but either way, if it gets fixed in multiplayer it'll fix it in single player too if it does show up.

**Comment by pyure** [comment]
Got it, thanks kindly.
