### ISSUE TITLE
FluidDict incompatibility with Mekanism

### ISSUE THREAD

**Issue by NotGyro** [zmaster587/AdvancedRocketry#663]
In a pack with AdvancedRocketry-1.10.2-1.2.0c, LibVulpes-1.10.2-0.2.3, and Mekanism-1.10.2-9.2.2.301, I'm running into an oxygen issue. When attempting to pipe oxygen into an oxygen vent, it does not accept it. The same thing happens with the gas charging pad. If I put oxygen into a pressurized tank, the tank accepts it - but when I put that tank into a spacesuit, I still suffocate in Survival Mode.

After some testing (with lots of help from a friend, MrEldritch), it seems that this is an inter-mod issue with Mekanism. Removing Mekanism allows the exact same setups to work as intended.

My guess here: Since Mekanism also supplies a Forge Fluid called Oxygen, it must grab the name for its fluid class. However, Advanced Rocketry is (apparently?) checking for the specific class instance or class when checking to see if a fluid is oxygen. 

It would also be worth checking to see if the same issue occurs with hydrogen, since Mek also supplies a Hydrogen fluid, but I haven't tested that at all yet.

Please let me know if you need any more info! I'm a bit rusty at submitting MC mod bug reports. Logs didn't seem necessary in this situation but I can provide logs if you'd like.

**Comment by zmaster587** [comment]
If you could provide logs, or at least the line specifying the default fluid used for oxygen, that would be helpful

**Comment by NotGyro** [comment]
Wow, okay, good idea. Weirdly enough, this is what I have: 
`[19:43:58] [Server thread/DEBUG] [FML/]: The fluid advancedRocketry:oxygen has been selected as the default fluid for oxygen`
I have just tested again, and confirmed that this bug only occurs when Mekanism is installed. Removing Mekanism and only Mekanism from the pack fixes the issue. So, it's still an inter-mod issue with Mek, even though advancedRocketry:oxygen is the default fluid for oxygen.

**Comment by zmaster587** [comment]
I was looking through mekanism's code and noticed his fluid is actually registered as "liquidoxygen".  Can you see if that shows up as a fluid as well?  And if so what other mods that supply oxygen are you testing with other than mekanism and AR?  Have you tested to see if oxygen produced by AR is still compatible?

**Comment by NotGyro** [comment]
Here are some screenshots of the testing setup. This works with Mekanism removed from the modpack:
![2017-05-29_21 46 15](https://cloud.githubusercontent.com/assets/4525370/26565411/ff2d89ea-44b8-11e7-901a-c2c80a38adc9.png)
![2017-05-29_21 45 52](https://cloud.githubusercontent.com/assets/4525370/26565412/0259d178-44b9-11e7-93b5-2b4acc41e498.png)
![2017-05-29_21 49 59](https://cloud.githubusercontent.com/assets/4525370/26565413/04208510-44b9-11e7-9354-f1e515d53e8c.png)

**Comment by zmaster587** [comment]
Strange indeed.  I'll see if I can replicate this on my end.

**Comment by Kin37ix** [comment]
Interesting. I was producing AR Rocket Fuel using Mekanism oxygen and hydrogen earlier today on MC 1.7.10.

**Comment by TheGuyRunningSouth** [comment]
I think we're talking about 1.10. That being said, I can produce rocket
fuel fine from fluids carried from the electrolyser to the chemical reactor
through mekanism fluid pipes, and if I use a pressurized tank block I can
convert the tanks of hydrogen back to liquid which the rotary
condensentrator works fine with, so I'm at a loss here.

**Comment by Kin37ix** [comment]
@TheGuyRunningSouth  I know that's why I specified. I did not see the OP say anything about a condensentraror.

@NotGyro are you converting the gas into fluid first?

**Comment by zmaster587** [comment]
Would you be willing to test again with the latest build of libvulpes/advanced rocketry on here: http://65.78.115.159:8080/
Apologies for my poor naming conventions, roundplanets/unstable is the 1.2.x builds and the other builds are for 1.0.x builds

**Comment by Shados** [comment]
Humm, I've tested with AdvancedRocketry-1.10.2-1.2.1-23, LibVulpes-1.10.2-0.2.4-14, and Mekanism-1.10.2-9.2.2.301. I have the gas charge pad fed from the output of an advanced rocketry electrolyser, but it still won't charge my suit.

**Comment by NotGyro** [comment]
@Shados is the primary maintainer of the modpack I'm testing.

The latest update has resolved the issue with the oxygen vents for me, but as @Shados said, the problem with the gas charge pads is still not resolved. They do accept piped-in oxygen, now, but they will not charge suits with that oxygen.

Kudos for fixing the oxygen vents, though!

**Comment by zmaster587** [comment]
Suits should be fixed now, and you're welcome!
