### ISSUE TITLE
Jet Pack will not recognize Hydrogen from other mods.

### ISSUE THREAD

**Issue by ShicKla** [zmaster587/AdvancedRocketry#669]
If another mod registers Hydrogen liquid first, that mod's Hydrogen is not recognized by the Jet Pack.

In my specific case I was forcing NuclearCraft to load before Advanced Rocketry, because I like how NuclearCraft's version of Hydrogen and Oxygen liquids are placed in the world and then evaporate. Sadly though, after doing this change in load order, I found that the jet pack would not recognize NuclearCraft's Hydrogen.

If you need additional information let me know.

**Comment by zmaster587** [comment]
Can you confirm that forge is actually using NuclearCraft's Hydrogen as the default fluid for hydrogen?  Even if NuclearCraft loads first it is possible that it registers its fluids at a later stage than AR (init vs preinit for instance).

**Comment by zmaster587** [comment]
Would you be willing to test again with the latest build of libvulpes/advanced rocketry on here: http://65.78.115.159:8080/
Apologies for my poor naming conventions, roundplanets/unstable is the 1.2.x builds and the other builds are for 1.0.x builds

**Comment by ShicKla** [comment]
Okay, I just got done testing. I can confirm builds "AdvancedRocketry-1.10.2-1.0.20-24" and "LibVulpes-1.10.2-0.1.20-15-universal" did correct the problem.

**Comment by zmaster587** [comment]
Alright, good to know, what I ended up doing was checking against the fluid names rather than the instance, I'm not entirely sure why it has to be done that way because the fluid instance it's checked against is pulled from forge's default selected fluid which makes me wonder if there's an extra instance roaming around.

Also as for the results of the O2 issue, was that working properly as well when you tested?

**Comment by ShicKla** [comment]
Sorry, I should of clarified. The NuclearCraft O2 did function in the suit. I did not however test to see if it worked in the air vent.

**Comment by zmaster587** [comment]
Alright, the hydrogen issue is fixed it seems, so I'll close this and leave the other one open
