### ISSUE TITLE
Direct Data

### ISSUE THREAD

**Issue by TheAmazingSpy** [zmaster587/AdvancedRocketry#67]
It's quite annoying having to go from  the terminal to the analyser and back all the time, so my idea is a wire that transmits info from one machine to another. And another thing is not having to connect all the time to get data

**Comment by zmaster587** [comment]
Still think it would be a good idea to keep the "connet" option for manually moving data.  But I am planning a version that automatically exports data to an adjacent machine.

**Comment by TheAmazingSpy** [comment]
! Yay! Now, what I was thinking is with the telescope it has different versions for different things, like a radio telescope for mass etc

**Comment by zmaster587** [comment]
That's what the satellites are for, in reality Earth's atmosphere distorts light too much to be able to make much of small distant objects

**Comment by TheAmazingSpy** [comment]
Okay

**Comment by TheAmazingSpy** [comment]
Dude, why are you so fast at replying?

**Comment by zmaster587** [comment]
Implemented in 0.6.0
