### ISSUE TITLE
Unable to create stations?

### ISSUE THREAD

**Issue by DarkyAlan** [zmaster587/AdvancedRocketry#672]
**Versions & Modpacks** (Via twitch Launcher)
1.10.2-1.1.7 [Invasion Modpack]
1.10.2-1.2.0 [All The Mods Modpack]

**Summary**
Whilst following instructions from [this spotlight](https://youtu.be/QeXY_HNEQ6o?t=7m42s), I've attempted to create space stations in a singleplayer creative world to then try it out on multiplayer servers, on both modpacks the method shown does not work and I can't seem to find any documentation relevant enough to help me. I'm unsure if they're known version specific bugs or not but I've made a quick [video](https://www.youtube.com/watch?v=uUFIf1B3NVY) demonstrating the error I'm encountering.

**Comment by zmaster587** [comment]
I think I see the issue.  The assembling block is not supposed to be level with the pad, but one block above it like this:

![image](https://cloud.githubusercontent.com/assets/3536685/26690939/4858a0ca-46c9-11e7-9ed8-774fd9940211.png)

If you can try that and get back to me I'd greatly appriciate it.

I also apologise for the lack of documentation, it's planned, but everything is still in a state of flux and I've got a lot on my plate.

**Comment by DarkyAlan** [comment]
Worked like a charm, that was exactly the issue, I'm sorry it took me this long to reply; been busy! 

I do however commend how quickly you responded, wish you luck down the line, it's shaping up to be a great mod.

**Comment by zmaster587** [comment]
Thank you and good luck!
