### ISSUE TITLE
Asteroids (enhancement idea)

### ISSUE THREAD

**Issue by Thanatos8088** [zmaster587/AdvancedRocketry#677]
I might be missing something, but I was wondering if there was any plan toward more granular asteroid mining times. I've adjusted the multiplier which impacts asteroids broad-scope, but the idea to provide asteroids as a source of otherwise difficult-to-obtain material is a tempting avenue. Concept wise, it provides another tech-tree to pursue for some later-game materials such as awakened draconium (some of my players are heavy industry, but couldn't care less about swinging a sword at a Chaos Guardian). In the spirit of balance I would prefer this come at significant (borderline punitive) cost, and time-to-mine is the most obvious price (on top of rarity, ore-to-stone ratios, etc). Anyway, just pitching the idea and the reasoning, but know it's a feature request on a mod already biting off a heck of a lot to chew (and handling it well). Thoughts for placement would be a secondary multiplier on a per-asteroid type basis (value 1 matching the global cfg setting, < || > 1 would adjust accordingly. That or some kind of 'per distance' factor on the 200 scale. Admins could work within that between assigned-to asteroid and the global setting. It's more roundabout, but might be more reasonable to implement in an already constructed system and config structure.....'Other' other idea, if you're feeling evil (or excessively ambitious) would be tagging asteroids to star systems and force them to perform the mining off-overworld and deal with item transport logistics. With tesseracts (or other cross dimensional means) this isn't much of a barrier for the work involved in coding that, but figured I'd add it while spitballing. Thanks for reading!

**Comment by zmaster587** [comment]
I'd like to avoid tying a time multiplier directly to distance, perhaps instead it would be better as its own setting in the asteroid.xml file in the asteroid tag.  If it were treated as a decimal it should give very fine control over mining time.  I suppose the real trick would be somehow alerting the player to its mining time.  I guess that would be in the observetory somewhere.

I'm likely not going to get around to requiring launching from another planet or system.  Though I may incorporate something like that later for asteroid belts or fields.

**Comment by zmaster587** [comment]
implemented in next build
