### ISSUE TITLE
Lag and Inability to Interact With Objects Like Chests And Furnaces On Other Planets or Moons

### ISSUE THREAD

**Issue by GingerPhoenix** [zmaster587/AdvancedRocketry#679]
So basically, as the above issue states, I cannot interact with things on other Planets/Moons.....   :3   I can't place things like Beds, but I CAN do all of these things in the End, the Nether, and the Overworld (the default Planet we would normally start on.....   :) )   Do you think you could fix this.....?   :3   I'd do it myself, but I'm only good at C.....   :<   Have a good day, ok.....?   :3

**Comment by zmaster587** [comment]
All of AR's handlers treat all dimensions the same, in fact, the overworld and end are treated like planet.  Advanced rocketry also does not have any effect on block placement other than intercepting right-clicking with a torch, but that is also treated the same way across all dimensions.  I can't think of anything else in the mod that could cause any similar interaction so I'm wondering if there's some other mod installed or if the heap is full.

Have you checked the log to see if any errors are printing? Do you have other mods installed, and if so does removing mods other than advanced rocketry and libvulpes fix the issue?

Also you have a nice day too!

**Comment by GingerPhoenix** [comment]
@zmaster587 So basically, you don't have any problems placing Blocks down on other Planets then.....?   :)   Well, the issue is likely on my end then.....   :)   I'm currently running 1.11.2, and I tried removing other Mods (placing them one Directory up), and it's still happening.....   :<   Also, I'll look into the Logs....   :)   Despite these issues, the Mod is still so.....   EPIC!.....   ^^   It's been AWESOME building homes on one of the other Planets!.....   :3   I created a Save called "Worlds Apart", where I live on a Planet that's far away from the MAIN Planet.....!   :D   Lol, I cheated to get there in the beginning, but after that.....   :)   Anywho, I'll look into the Log, and report back....   :D   Thank you SO much for making an AWESOME Mod!.....   ^^   Also, it's cool that it's Open Source, y'know.....?   Really helps with making it better.....   :D

**Comment by zmaster587** [comment]
I've honestly not tried placing blocks on other planets in 1.11.2, but the 1.11.2 build is identical to the 1.10.2 builds with the exception of having to rename every darn texture and and refactoring (worldObj => world).  I'll go ahead and actually try it in 1.11.2 though.  It's rather difficult for me to test everything for every update unfortunately.

I really like the idea of opensourcing most projects.  It would be disappointing to see something similar to redpower2's death to occur again.

**Comment by zmaster587** [comment]
I've tested placing blocks and opening chests on other planets in 1.11.2, there don't appear to be any problems for me.

**Comment by GingerPhoenix** [comment]
@zmaster587 I understand why it might be hard for you to test every Release.....   :3   Also, I didn't know all that went into updating a Mod Release.....   :O   Wow.....   :3   Also, Open Source is why I use Linux.....   :3   But currently, I'm having trouble's with GRUB freezing, but, that's another issue.....   :D   When I get that problem sorted out, I could try testing out Advanced Rocketry on there too.....   :3   Currently, I'm running it on Windows (I Triple-Boot between that, Linux, and FreeBSD).....   :)   But it really does seem like the problem is on my end now, doesn't it.....?   :3   How about Beds.....?   :)   Did you try placing Beds.....?   :)   Anywho, I'll get back to debugging this issue.....   And get back to studying C and C++.....   :D   Thank you for everything you do.....   Maybe someday, when I get better at Java, I can help with this cool Mod......   :D

**Comment by zmaster587** [comment]
It's a bit of a pain the rear to update, especially with how frequently new builds of MC are made.  I actually also use linux, though moreso because I find there's less overhead from the OS than with the more recent Microsoft operating systems (but I loaded it up with KDE so RIP RAM).  Plus it's so much easier to install libraries.  I did try placing beds and have found there was an issue with that, a method had been changed at some point, I'll have that fixed in a minute.

**Comment by GingerPhoenix** [comment]
@zmaster587 Yeah, I know what you mean.....   I wish I could help, but alas, I suck at Java.....   :D   And yeah, I like Linux for those reasons also.....   :D   As for KDE, do you use lots of Desktop Effects.....?   :)   I hear those can soak up RAM.....   :)   I LOVE me some wobbly windows.....   ;3   Also, will you release the update as a new File, or update the old one.....?   :3   It's nice to speak to you, and I'm happy I was able to play a small part in helping this Project out......   :D

**Comment by zmaster587** [comment]
I disable desktop effects moreso because it kills my cpu and gpu than RAM. As for the new file It'll likely appear here http://65.78.115.159:8080/ or on curse as a new file.  Though the only thing I've changed with regard to your issue is the beds.
It's been nice talking to you as well.

**Comment by GingerPhoenix** [comment]
@zmaster587 Ah, I see.....   :)   Also, I'll check on your Site for the new File first.....   :)   Also, I hope we can interact more in the future.....   :3   Also, when I get the File, I'll test it.....   :D   More also, I somehow fixed the Chests-not-opening issue, and the Stars, Sun, and those Planet thingies have all stopped lagging!.....   :3   Again also, do you think you could share your Save File where you build that Space Station, and the Rockets 'n stuff.....?   :3   I ask because I think it will be a while yet before I can get the hang of this deep, interesting Mod.....   :3

**Comment by zmaster587** [comment]
I can't say I really get why the lag and everything stopped, only thing I can think of is that it was still generating the world or something.  The jenkins and the latest files are here: http://65.78.115.159:8080 though some of the time it may not be playable in survival due to lack of recipes and things of that nature.

I can send the save for the 1.10.2 test world, the 1.11.2 test world doesn't even have a station that's more than 9 blocks wide.  But at the same time I cannot garuntee the world will work in 1.11.2.
https://www.dropbox.com/s/aitl9qs2x2ks0oq/world.zip?dl=0

Also, if you want to talk about other things unrelated to open issues, feel free to pm me on curse.

**Comment by GingerPhoenix** [comment]
@zmaster587 Thank you good sir!.....   :3   Also, I'll sign up on Curse, so I can talk to you about stuff.....   :3   I can also post some crap to GitHub so you can try out some cool Programs I made!.....   ^^   Thank you for the Saves, good sir.....   :3   I may use NBT to change it to Survival, since you already built some stuff.....   :3   I appreciate you updating the Mod.....   :D   Lol, it's kind of too late though, because I got slain on the foreign World I started out in.....   XD   Nevertheless, I appreciate it SO much.....   :D   Have a good day, ok.......?   :3
