### ISSUE TITLE
Different Types Of Telescopes And Different Tiers

### ISSUE THREAD

**Issue by TheAmazingSpy** [zmaster587/AdvancedRocketry#68]
So with the telescope, maybe we should give it a use so people use it, with different tiers. First tier is a small telescope, the type you find in a household, second is the current one and third is a giant one, which is customisable, (custom doors and blocks in telescope) and then for the types, I was thinking, a radio telescope. Tell me what you think

**Comment by zmaster587** [comment]
Probably going to so something similar in conjunction with #300
I meant to repsond to this a year ago and somehow I never came back to it.

**Comment by zmaster587** [comment]
At least for now a special type of glass (lens) is now allowed plus different motor types.  While it isn't exactly a whole new machine, given the new function of the telescope (to find asteroids) I think more precise motors and lenses probably fits the best.
