### ISSUE TITLE
Breaking Pipes

### ISSUE THREAD

**Issue by Dryxen** [zmaster587/AdvancedRocketry#680]
Breaking Pipes with your hand seems to destroy them where as with a pickaxe gives the item back even though they show no tool required with the one probe. they all seem to have no material hardness and are broken nearly instantly and appear to be having a graphical texture glitch where the textures dont connect correctly.
using,
LibVulpes-1.11.2-0.2.3b-universal
AdvancedRocketry-1.11.2-1.2.0f

**Comment by zmaster587** [comment]
The pipes are using material.IRON so they should require a pickaxe to break much like other, though I probably should make them harder to break without a tool
