### ISSUE TITLE
Breaking Satellite Terminal

### ISSUE THREAD

**Issue by Dryxen** [zmaster587/AdvancedRocketry#681]
Breaking a Satellite Terminal destroys any thing in its inventory instead of dropping it.
using,
LibVulpes-1.11.2-0.2.3b-universal
AdvancedRocketry-1.11.2-1.2.0f

**Comment by zmaster587** [comment]
Fixed in https://github.com/zmaster587/libVulpes/commit/253cd6ac12971b44ec3b7b283e85eb4d0c85ed1d and in versions 1.10.2 and 1.7.10
