### ISSUE TITLE
Unable to recieve data from satellite on a multiplayer server?

### ISSUE THREAD

**Issue by GoatMog** [zmaster587/AdvancedRocketry#683]
I sent optical, mass, and composition satellites to space on a multiplayer server, and they are connected, but they won't produce any data. I tried the exact same method on my single player world, and it worked fine. Is there a way to fix this?

**Comment by zmaster587** [comment]
what version of MC and AR are you using?

**Comment by GoatMog** [comment]
1.7.10 and the latest version of AR

**Comment by zmaster587** [comment]
Latest stable or alpha build?

**Comment by GoatMog** [comment]
AdvancedRocketry-1.7.10-1.0.19b.jar

**Comment by GoatMog** [comment]
stable

**Comment by zmaster587** [comment]
It appears to work fine when I create a setup on a server.  What did you use when building the satellite?  Did you make sure to include at least one data storage unit and one basic/advanced solar panel when building the satellites?

Also what numbers are displayed for power and data storage in the satellite terminal?

**Comment by GoatMog** [comment]
I used 3 large solar panels and 3 data storage units. 
![2017-06-05_22 13 54](https://cloud.githubusercontent.com/assets/29213753/26810931/909fec50-4a3c-11e7-9a3d-0497a9c939b0.png)
It displayed 0 for the power and 3.0k as the data storage.
![2017-06-05_22 14 55](https://cloud.githubusercontent.com/assets/29213753/26810942/adb344c2-4a3c-11e7-9103-bc8dfa70f5a1.png)

**Comment by zmaster587** [comment]
Odd, the second image displays that the satellite has no power.  investigating

**Comment by GoatMog** [comment]
It may associate with another mod. Idk.

**Comment by GoatMog** [comment]
And I already tried basic solar panels, sadly, they don't work either. :(

**Comment by zmaster587** [comment]
It shouldn't.  Also, by any chance are you running something like sponge on the server?  If so try with it removed.

**Comment by GoatMog** [comment]
We're using thermos

**Comment by GoatMog** [comment]
and the players would not be happy if it was removed

**Comment by GoatMog** [comment]
Would you like to see the mods this server uses?

**Comment by GoatMog** [comment]
https://www.dropbox.com/s/lq6z7as11gk52js/mods.zip?dl=0

**Comment by zmaster587** [comment]
The only thing that would cause an issue like this is something that affects forge at a low level, sponge, thermos, MCPC, cauldron, etc.

Unfortunately with the amount of issues I current have with forge alone, I cannot garuntee thermos support.

**Comment by GoatMog** [comment]
Okay.

**Comment by GoatMog** [comment]
Thank you.
