### ISSUE TITLE
Server crash after launching space station

### ISSUE THREAD

**Issue by Dryxen** [zmaster587/AdvancedRocketry#685]
Server crashed after launching my space station resulting in the loss of the said station heres the crash log
https://hastebin.com/jisudoqoxo.sql
was a server first launch so that might be the issue ill try a second time sometime tommarow

LibVulpes-1.11.2-0.2.3b-universal
AdvancedRocketry-1.11.2-1.2.0f
Thanks again in advance,
 Dryxen

**Comment by zmaster587** [comment]
Looks like the world is somehow null and this should not be able to occur in vanilla forge.  Try to see if this occurs without sponge?

**Comment by Dryxen** [comment]
this one didnt crash on the initial send but gave the same server crash when i tried to send the player rocket to the station on the forge server i might also mention sending new stations on the sponge server have stopped at around y400 and never leave dim0
https://hastebin.com/yesesukowe.sql
if theres any other helpful info i could provide let me know xD sry for keeping you busy

**Comment by zmaster587** [comment]
What if you use forge 1.11.2-13.20.0.2228?

**Comment by Dryxen** [comment]
ill set it up real fast what dim its the station trying to build in btw? maybe a dim conflict on our end for the first error i didnt even think about that

**Comment by zmaster587** [comment]
By default the dim is -2, though the server normally crashes on load in the case of a dimension conflict, so I find that unlikely.  It appears to be the world object itself that's non-existant though, even though the dimension itself appears to exist.

**Comment by Dryxen** [comment]
nope fresh copy of 1.11.2-13.20.0.2228 let it gen all the configs outside of the planetdefs i added the ones over with the earth destination, still crashing on launching player to the newly formed station 
https://hastebin.com/adulewabul.sql

**Comment by zmaster587** [comment]
That second crash still reports it's using forge 1.11.2-13.20.0.2288 rather than 1.11.2-13.20.0.2228, which even betwee those two the method sig may have changed.

**Comment by Dryxen** [comment]
hmm wasnt even paying attention to the version i was using before i just downloaded the version you requested xD which version are you wanting me to check it against ill download it in the morning and check if its crashing.

**Comment by zmaster587** [comment]
I think you may have just gotten a number switched somewhere, you used the correct number when replying to the issue, though it appears you just downloaded the wrong file.  But still version 1.11.2-13.20.0.2228

**Comment by Dryxen** [comment]
I was apparently to tired to read last night xD heres your 2228 crash log xD sry about that.
https://hastebin.com/ojukumogab.sql

**Comment by zmaster587** [comment]
I've been there XD.  Thanks.  I'll take a look into this now.

**Comment by zmaster587** [comment]
I've tried to replicate the issue in singleplayer, multiplayer, and 2 of the three versions of forge that you've had issues with, I simply cannot replicate the issue, the station builds fine every time I send a ship up.  I'm wondering if it's possible that your copy of the mod is corrupt.  If if you don't mind, can you try first deleting the advanced rocketry mod file on the server(esp if the server is a windows computer), then replacing it with a fresh copy from curse and then testing again?

**Comment by Dryxen** [comment]
sure ill do that now, also did the xml look ok since i needed to manually add earth?

**Comment by zmaster587** [comment]
Yeah, the XML looks ok.  Not to mention, this issue appears unrelated to planet configuration anyway.
This is a really bizarre issue...
Does it occur with these builds (Also, I'd suggest operating on a backup with these, unless you do not plan on going back to 1.2.0f)?
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/MC1.11/
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/MC1.11/

**Comment by Dryxen** [comment]
its a testing environment entirely to testing this bug so it doesnt matter =P

**Comment by zmaster587** [comment]
even better

**Comment by Dryxen** [comment]
appears advanced rocketry didnt register as a mod this go around libvulpes did though

**Comment by zmaster587** [comment]
Did you download the sources jar by mistake for AR?

**Comment by Dryxen** [comment]
AdvancedRocketry-1.11.2-1.2.1-13.jar nope lemme try to redownload it as it may have been corrupted can unzip it either

**Comment by Dryxen** [comment]
aye first download was corrupted sry bout that ;P testing now

**Comment by zmaster587** [comment]
Alright, if check the MD5 of the file ( https://md5file.com/calculator, linked for convenience.  Any MD5 calculator should work): it should be f326d9ee7988d477344493052a80fb93

**Comment by Dryxen** [comment]
space hates me xD https://hastebin.com/yuveqiyiko.sql

**Comment by zmaster587** [comment]
I'm totally at a loss... would it be possible to upload the entire server directory, or at least forge related files, the mod/config folders so I can try to attach a debugger to it?

**Comment by Dryxen** [comment]
yea gimme a sec ill compress them and find a upload site

**Comment by zmaster587** [comment]
Thank you, I appreciate it

**Comment by Dryxen** [comment]
never used this upload site so no idea how long it will take to download =/ https://ufile.io/xz6j5

**Comment by zmaster587** [comment]
The free download is still pretty fast: 340KBps, so less than 5 minutes

**Comment by zmaster587** [comment]
Alright, the mystery deepens, so I've run the server from the zip you sent over and constructed and launched a spacestation without any problem (only change I made to the server was change the dir in mod_list.json to point to the equivilent location on my disk, but mercurius wasn't found in either of our setups according to the output logs).  I've also double checked that I'm using the same java build

So the issue does not appear to lie with either the mods or forge but rather something system specific as far as I can tell.
Also have you tested to see if this occurs in single player as well?

**Comment by Dryxen** [comment]
havent test lemme load it up rq

**Comment by zmaster587** [comment]
If that works then it's likely some kind of sided mishap.  Though i still don't know why it would be different... I'll look into some way of getting around that line of code entirely.

**Comment by Dryxen** [comment]
ya seems to work in sp i think i messed up the landing process though

**Comment by zmaster587** [comment]
Try this build on the server and see if it still crashes
[AdvancedRocketry-1.11.2-1.2.1.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1059206/AdvancedRocketry-1.11.2-1.2.1.jar.zip)

Should run with the newest libvulpes from the jenkins.

Also what do you mean by you think you messed up the landing process?

**Comment by Dryxen** [comment]
oh that ive never been to space successfully so i saw the press space to decend and immeadiatly hopped out of the rocket to make sure i would stay there xD rocket disapeared ended up about 1k blocks away from the station with the rocket being on top of it

**Comment by zmaster587** [comment]
Oh, I'll have to make sure to mention not to do that when I get around to writing the guide for space travel.

**Comment by Dryxen** [comment]
that seemed to have fixed the issue i was able to land without a problem

**Comment by zmaster587** [comment]
Alright, good!  Thanks for your help!
