### ISSUE TITLE
Space Elevator not working

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#686]
Hi

I don't think that the space elevator is working. I set up two one on the base and the other on the space station. 

The first problem is that when building the Elevator facing north the capsule was about 5 blocks from the centre. When building it facing east the capsule was in the correct place.

The next problem was that the Elevator chip seems to have existing coordinates programmed in. I shift-right clicked the elevator on earth with the linker and then went to the space station and shift-right clicked the elevator, cleared the coordinates and shift-right clicked the elevator on the station and it had the Dim -2 coordinates. Went back to earth and the elevator chip already had two sets in even though I'd not right clicked it yet.

Now everything seems to be correct, the two coordinates match my elevators and they both have full power. I get in either one and the count down begins but nothing happens except the count down goes negative.

AdvancedRocketry-1.10.2-1.2.0c.jar and LibVulpes-1.10.2-0.2.3-universal.jar

**Comment by zmaster587** [comment]
I'll look into the capsule being off center, somebody else had reported it a while ago but neglected to mention direction when asked.

The Earth based space elevator having the coordinates of the other elevator is intended.  The idea is that linking one automatically linked the other because each base is two halves of a whole so when one tries to 'connect' to another, the second basestation must know where it's coming from so the coordinates are stored.  Plus it makes it a bit easier on the users.

Three conditions I know that cause the negative countdown to appear is the space elevator not being turned on in the UI, being out of power (but I think we can cross that one out because you said it was fully powered), and not being able to connect to the remote station.  So I'd suggest double checking the on/off state of the machine in the UI, I'll go and try to make the feedback for the machine more user friendly so if that doesn't work we can at least figure out the cause.

**Comment by zmaster587** [comment]
Upon testing, north seems ok, but west does not

**Comment by duncanwebb** [comment]
Hi,

Thanks again for your quick response. If you would like me to test anything like newer version then it will be my pleasure to help out.

I'm wondering it this has something to do with the different motors and coils used. I like to swap the components a bit to see what affect they have. I've only tried different coils and motors but not yet the blocks.

![image](https://user-images.githubusercontent.com/4198031/26870159-5933cba4-4b6f-11e7-83d7-4609edd88cbe.png)
![image](https://user-images.githubusercontent.com/4198031/26870247-aafb60be-4b6f-11e7-9dc4-c2cf2af59170.png)
![image](https://user-images.githubusercontent.com/4198031/26870272-c227d786-4b6f-11e7-96b6-f705a5c23eed.png)

**Comment by duncanwebb** [comment]
Doesn't seem to be the cause, I changed to coils to gold on both elevators and the motors to elite.

![image](https://user-images.githubusercontent.com/4198031/26871071-482b89e8-4b72-11e7-8035-36c110feee61.png)

![image](https://user-images.githubusercontent.com/4198031/26871040-377f8e82-4b72-11e7-9451-8036ed8b5e38.png)

Everything seems to be fine, the coordinates match too.

**Comment by duncanwebb** [comment]
This was the other side and I also changed the base from slabs to blocks. I noticed that slabs are not considered air tight for floors or ceilings on the space station.
![image](https://user-images.githubusercontent.com/4198031/26871745-7c665290-4b74-11e7-9a84-454ccb5bc471.png)

**Comment by zmaster587** [comment]
Currently the motors and coils have no effect on the operation of the space elevator, in the future they will increase the speed of the capsule and reduce energy cost respectively.

I'll have a build up later today on the Jenkins I hope

Also, just for the heck of it, what happens if you try it with no mods other than AR and Libvulpes installed?

**Comment by duncanwebb** [comment]
>  just for the heck of it, what happens if you try it with no mods other than AR and Libvulpes installed?

I die, it was night and mobs were everywhere! Just joking - I nearly died, lighting was with painted Glowstone and it was night.

It didn't seem to make a difference. However I only had the power stored, all the enderio cables and capacitors and Nether star generators were gone - LOL

**Comment by zmaster587** [comment]
Alright, what if you break and replace the control blocks for the space elevator?  I'm kinda running out of ideas >.>

**Comment by duncanwebb** [comment]
What I've tried is:

- breaking and replacing the control block
- move the elevator to a different position,
- rotated it 90 degrees
- connected it up to a microwave receiver providing 300 RF/t, using energy pipes.
- removing 9 blocks underneath the capsule.

**Comment by zmaster587** [comment]
Alright then.  Debug build it is I guess, give me a few minutes...

**Comment by zmaster587** [comment]
[AdvancedRocketry-1.10.2-1.2.1.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1059186/AdvancedRocketry-1.10.2-1.2.1.jar.zip)
http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_10/lastSuccessfulBuild/artifact/output/LibVulpes-1.10.2-0.2.4-16-universal.jar

Try this build.  All the debug into should appear in the log.  So I guess run this, let it count down to zero, and let me know what prints.

**Comment by duncanwebb** [comment]
I'm seeing a lot of these:
```
[22:37:15] [Server thread/INFO]: Elevator status in attemptLaunch(): Complete: true Enabled: true Energy: false
[22:37:15] [Server thread/INFO]: Tile zmaster587.advancedRocketry.tile.multiblock.TileSpaceElevator@1d918d4d at location Dimension 0 Location: 167 69 -1188 is not valid
[22:37:15] [Server thread/INFO]: Elevator status in attemptLaunch(): Complete: true Enabled: true Energy: false
[22:37:15] [Server thread/INFO]: Tile zmaster587.advancedRocketry.tile.multiblock.TileSpaceElevator@1d918d4d at location Dimension 0 Location: 167 69 -1188 is not valid
```

A bit of a dumb picture, standing on the space elevator block

![image](https://user-images.githubusercontent.com/4198031/26900516-ba5f84f0-4bd2-11e7-8a58-84f14cfef3a9.png)

So it looks correct.

**Comment by zmaster587** [comment]
Looks like it just doesn't have enough energy for some reason.  If you open the control block, how much energy does it say it has out of how much?

**Comment by duncanwebb** [comment]
Does this make sense, I think 30,000 is too little if it requires 50,000 per trip. The other images show how it is connected.

![image](https://user-images.githubusercontent.com/4198031/26901425-22ca4734-4bd6-11e7-9b1c-a1c920fcf0f2.png)

![image](https://user-images.githubusercontent.com/4198031/26901403-0efa07f8-4bd6-11e7-973d-a49f105568fc.png)

![image](https://user-images.githubusercontent.com/4198031/26901461-3d6700d2-4bd6-11e7-8a6f-3ef86b3968b7.png)

**Comment by zmaster587** [comment]
The power inputs should have a storage of 100,000, not 10,000.  I'm going to see what's up with that.

**Comment by zmaster587** [comment]
If you run this version of libvulpes and replace the power inputs, does that work?
[LibVulpes-1.10.2-0.2.4-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/1059394/LibVulpes-1.10.2-0.2.4-universal.jar.zip)

**Comment by duncanwebb** [comment]
I'll test this in the morning, if you don't mind waiting (bedtime and the kids will be up in six hours. ;-))

It did work with creative power plugs.

**Comment by zmaster587** [comment]
Alright, that's fine.

**Comment by duncanwebb** [comment]
Awesome it works just fine. Many thanks

Just a quick question, so with this release the building blocks and coils don't make a difference to the speed, just the motors?

**Comment by zmaster587** [comment]
In this release neither the motors nor coils make a difference to the speed of the space elevator.
