### ISSUE TITLE
Dying on planet without sleeping returns to overworld

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#689]
MC 1.10.2
Forge 2297
AR 1.2.0c
libvulpes 0.2.3

So, I use JED to let me spawn when creating a world on an AR planet.
I set B:allowPlanetRespawn=true in the config which works mostly as intended. So when I sleep and die, I indeed respawn on that planet. But if I haven't slept yet, I respawn in the overworld. Is there a way to fix that? Maybe adding an extra config option letting me always respawn on the planet I died in? Or can you detect what dimension the initial spawn dim was, and always respawn on that planet? That would help me tremendously for my new pack. Thanks in advance.

**Comment by zmaster587** [comment]
I could add compatibility for JED and use the default spawn dimid.  I don't believe there's a value for that in vanilla, so it would have to be added on a mod by mod basis.

**Comment by davqvist** [comment]
I would love you forever if you could add compatability for that.

**Comment by zmaster587** [comment]
Dying on an AR planet should now respect the "initialSpawnDimensionId" in JED

**Comment by davqvist** [comment]
That is awesome. Thanks so much.

**Comment by zmaster587** [comment]
No problem!
