### ISSUE TITLE
Fluid Pipes fill both Drums with Liquid.

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#691]
I sent a Gas Collecting Mission to get some Oxygen. When the rocket returned the oxygen was unloaded with the Rocket Fluid Unloader and then the gas was piped using Liquid Pipe into a drum containing Oxygen also connected to the pipe was drum containing Nitrogen. After unloading both drums contains 32 buckets more gas.

AdvancedRocketry-1.10.2-1.2.0c 
LibVulpes-1.10.2-0.2.3-universal

**Comment by zmaster587** [comment]
What mod was the drum from?  And was it AR pipes or pipes from another mod that you used?

**Comment by duncanwebb** [comment]
The drums are from Extra Utilities 2 and I was using Liquid Pipes from AR. I used Iron Drums and the hold 256 buckets, so fairly good for a space station. Normally you can't mix liquids in drums like this but I don't use them very often.

**Comment by zmaster587** [comment]
Alright, will try and replicate on my end

**Comment by zmaster587** [comment]
should be fixed in the latest release
