### ISSUE TITLE
Biome Scanner could work better

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#692]
The Biome Scanner only returns a list of possible biomes and this is very long and not very useful.

However, reading your configuration documentation it seems that certain pressures and temperatures create specific biomes and so the list for a specific planet could be more accurate.

Thanks again for such a fun mod.

**Comment by zmaster587** [comment]
It's supposed to return a planet specific list, but it had broken in the 1.10.2 update apparently.
Fixed
