### ISSUE TITLE
Custom recipes in the cutting machine

### ISSUE THREAD

**Issue by belathus** [zmaster587/AdvancedRocketry#695]
In an attempt to allow the cutting machine to process many modded logs, I wrote the following XML document: https://github.com/belathus/Wanderlust-Renewed/blob/master/config/advRocketry/CuttingMachine.xml

However, when starting the game, I cannot see these recipes in JEI, nor does putting the logs into the input slot of the cutting machine cause them to be processed. I saw no errors in the log related to the XML file, so I'm not sure if I've done something wrong.

We're running 1.10.2. I believe we last updated the mods on the 24th, so I know we don't have quite the latest version, but I see nothing related to this in the changelog. I'll update tonight to see if that helps.

**Comment by zmaster587** [comment]
The XML does appear valid.  Can you pastebin the section of the log related to registering recipes?

**Comment by belathus** [comment]
It'll be a few hours before I can, but I'll make sure I do so.

**Comment by zmaster587** [comment]
Few hours will be fine

**Comment by belathus** [comment]
Here is the server's log file. I'm posting the whole thing, though, as I'm not entirely sure where it is registering recipes. https://gist.githubusercontent.com/belathus/43d8ca4e349572c5e083d857a9e6b63a/raw/8c7d5f602cbb4884441838a23c5a4ffe864d9f49/fml-server-latest.log

**Comment by zmaster587** [comment]
I think I made it newline sensative by mistake.  Also LibVulpes apparently uses the wrong logger and prints to console but not file.  Anyway, try this file https://pastebin.com/8asn0tSm

**Comment by belathus** [comment]
Okay, Now that I've gotten a chance to test this, it works fine. Good to know it is just a newline sensitivity problem.

**Comment by zmaster587** [comment]
Yeah, I hadn't considered a case where there wouldn't be a newline so...  anyway, should be fixed in the most recent build
