### ISSUE TITLE
Landing pad

### ISSUE THREAD

**Issue by mike7998** [zmaster587/AdvancedRocketry#696]
When will the landing pad be added to the version for 1.10.2? I'm remaking my space station into the USS enterprise, and a rocket sitting haphazardly on an ugly platform extending from the ships isn't exactly nice looking

**Comment by zmaster587** [comment]
The landing pad has been there for a while now.  Though if you're referring to the behavior to allow ships to dock sideways, then I can't say for sure.

**Comment by mike7998** [comment]
How does the creator of a modpack disable/re enable it? I haven't been able to find it in the creative menu or JEI

**Comment by zmaster587** [comment]
What version of the mod are you using?  If you're using an older version it may be called the "docking pad" instead.

**Comment by mike7998** [comment]
NVM, I found it. It's quite buggy in the version that's in the invasion pack. I might manually update the mod
