### ISSUE TITLE
Space evelator question and laser bug?

### ISSUE THREAD

**Issue by tobiasvdp** [zmaster587/AdvancedRocketry#697]
Him first of great work on the mod.
I however can't get the laser drill to work, 

I've included 2 screenshots of the setup.
(power comes from the draconic wireless crystals)

Config is no damage to panets.

I do have an other issue that might have something to do with it: space elevator uses 50.000 however the 3 rf providers only store 10.000 so they don't activate without at least 1 eu plug in it (100.000)

Edit. spawned in a creative plug, the laser's problem does not appear to be power.

(version 1.2.0)

![image](https://user-images.githubusercontent.com/5156314/26966945-80faa034-4cfc-11e7-87e1-8e654951685b.png)
![image](https://user-images.githubusercontent.com/5156314/26966952-8cd0a020-4cfc-11e7-9aa3-81ec4dec1f95.png)

**Comment by duncanwebb** [comment]
This fixed in LibVulpes-1.10.2-0.2.4-universal, the power plugs should store 100,000 RF
The laser needs the basic lens and a lever on the controller.
Also use AdvancedRocketry-1.10.2-1.2.1

**Comment by tobiasvdp** [comment]
Ok, let me try
I put in a lens block in stead of the lens. Might be it

**Comment by tobiasvdp** [comment]
Ok, the turning on of the laser is still kinda wonky but it works!
The laser seems to break by simply leftclicking the controller (non creative)
and in my experience doesn't work if the redstone signal was on the block before forming the structure.
