### ISSUE TITLE
Rocket Unloader doesn't seem to unload

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#698]
Hi, 

AdvancedRocketry-1.10.2-1.2.1
LibVulpes-1.10.2-0.2.4-universal

I'm trying to unload a rocket using the unloader. I've linked to unloader to the rocket and the GUI is indicating it is a loader.

![image](https://user-images.githubusercontent.com/4198031/26971680-7d46cc4e-4d0e-11e7-9a3d-10f477baef0f.png)

I'm playing with the buttons as I don't understand what they are supposed to do.

The rocket loader does work and loads the rocket, the rocket fluid unloader was working last time I did some gas mining (older AR version)

The first time I right click a rocket and open a chest it doesn't work, the second and subsequent times it opens the chest.

Many thanks

**Comment by zmaster587** [comment]
extra instance of rocket floating around in subclass caused scoping issues.

**Comment by duncanwebb** [comment]
Does that it is a bug and fixed, sounds like it but not 100% clear?

**Comment by zmaster587** [comment]
Yeah, it's fixed

**Comment by duncanwebb** [comment]
I was hoping that you would say which version, LOL; guess that it is not yet released.
