### ISSUE TITLE
Warp Controller "Select" fails between Solar Systems

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#699]
Hi,

AdvancedRocketry-1.10.2-1.2.1
LibVulpes-1.10.2-0.2.4-universal

In the warp controller when you select a planet in the current solar system and press "select" the controller correctly sets up the destination.

However, if you press select on a planet in a different solar system and press "select" it selects Earth.

If you simply highlight the destination planet and exit and right the controller it destination planet is selected correctly.

**Comment by zmaster587** [comment]
extra instance of rocket floating around in subclass caused scoping issues.

**Comment by zmaster587** [comment]
Oops, had the wrong tab open the whole time, I meant to reply to #698

**Comment by zmaster587** [comment]
I can't say I can replicate the issue.  While orbiting Earth (orbiting Sol), if I click Magna Vulpes (orbiting Leo et Lupus) then hit select.  I see Dest: Magna Vulpes.

Though simply clicking on a planet should not select it as a destination

**Comment by duncanwebb** [comment]
That's really strange, earlier this week (version 1.1.7) and this morning (1.2.1) I could reproduce this every time, now I've restarted the game I cannot reproduce it. 

I'll see if I can find out what scenario causes this to fail, normally I've been playing for several hours going up and down to earth and then warping to a planet doing something else and travelling. Since the cause is not obvious then better close the case. If I can find out more I'll open a new ticket.

Sorry for the trouble.

**Comment by zmaster587** [comment]
No problem, that'll work.  It's still a strange issue though...

**Comment by duncanwebb** [comment]
Just figured out what I was doing:
Select planet -> Up -> Planet List -> "select another system" -> double click (in the list) -> Planet List -> "select a planet" -> double click (in the list) -> Select. It chooses Earth.

The last double click was the mistake, click -> select was correct. I would be nice if the double click did the select.

**Comment by zmaster587** [comment]
Problem with the double click for the select is that's already mapped to zoom into planet system, it'd work well if it were not for the moons, but somehow being able to zoom in and out has to work too.
But yeah, it shouldn't default to earth in that scenario either...

**Comment by duncanwebb** [comment]
Would it help if a double click zoomed and also selected (highlighted) the planet, then you could select moons or press select on the menu.

**Comment by zmaster587** [comment]
that works
