### ISSUE TITLE
disable torch placement on the moon

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#70]
Since there is no air

**Comment by zmaster587** [comment]
Maybe rather than disabling torch placement outright, could replace it with a block that looks like a torch but does not emit light or flame.

**Comment by QVBA** [comment]
@zmaster587 which would hopefully be dependant on whether that specific area had oxygen, rather than entirely dimension dependant.

**Comment by wormzjl** [comment]
problably need to consider torches from other mods too...

**Comment by zmaster587** [comment]
Would need to find a way of doing that, there is not really any way to designate a block as a torch other than it emits light, but non torches do that too.  May end up doing something like checking the unlocalized name for the phrase "torch"

**Comment by DaMachinator** [comment]
Please add a config, so we can whitelist things we come across (Magnum Torches and Torcherinos come to mind), that way you have to do less inter-mod support.

**Comment by DarkGuardsman** [comment]
Most likely you want to implement a tick handler so the torch can turn back on.

**Comment by bludde** [comment]
Torches stops burning when in vacuum and can be lit with other torches and flint and steel, but lava, blazepowder cant start torches again. In vacuum fire is completely extinguished if there is no oxygen, so it could not start again, what about to add som kind of oxidized torch that burn for a certain amout of time in vacuum? maybe made in the electrolyzer? here?
![2016-08-10_21 57 13](https://cloud.githubusercontent.com/assets/1352518/17568798/9311b8fc-5f45-11e6-9268-6e023628ae79.png)
