### ISSUE TITLE
Gas Mining Mission

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#700]
Hi

AdvancedRocketry-1.10.2-1.2.1
LibVulpes-1.10.2-0.2.4-universal

Looks like the gas name has disappeared.

![image](https://user-images.githubusercontent.com/4198031/26972843-bf08d668-4d13-11e7-92da-e8398cac2fe7.png)

I don't know if this is a bug but when a rocket from gas mining mission returned, was unloaded and refuelled, it couldn't be launched again. Needed to be disassembled and rebuilt.

**Comment by zmaster587** [comment]
Did any errors appear in console?  Was the "harvestableGasses" setting modified from default in the advancedRocketry.cfg file?  Can this be replicatied reliably?  If so, how?

**Comment by duncanwebb** [comment]
This was working in 1.1.7 and I harvested gases and could select the gas. The issue https://github.com/zmaster587/AdvancedRocketry/issues/691 shows this. The only thing I did was to add two more tanks, one on either side but removing them make no difference the text is empty and the rocket does not launch.

![image](https://user-images.githubusercontent.com/4198031/26993150-2ba7a576-4d62-11e7-8546-dd7fec17897a.png)

**Comment by zmaster587** [comment]
Have you tried it while in orbit around a gas giant?

**Comment by duncanwebb** [comment]
I feel a right idiot, I was checking if the Biome Scanner was working (it is BTW and very useful too).

Yes the station needs to orbiting a gas giant for the gasses to show, makes a lot of sense. As certain gas giant may have different gasses. (In my game I only have Sol-3)

What about adding a message like "No Gas on Planet" or "No Gas Found"?

**Comment by zmaster587** [comment]
Having a message to display when the planet has no gasses would work for sure
