### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by Forecaster** [zmaster587/AdvancedRocketry#703]
AR 1.2.0c
Lib 0.2.3

https://gist.github.com/Forecaster/e061f89b176ea1e9ca8a3505bedfbd98

**Comment by zmaster587** [comment]
Do you have a setup where you can reliably replicate this crash?

**Comment by Forecaster** [comment]
Unfortunately it happened randomly on a server (it crashed the server), but I don't know what triggered it.

**Comment by Forecaster** [comment]
There are a couple of users (me included that have fluid pipes set up. Presumably one of those randomly triggered this.

**Comment by Forecaster** [comment]
It just happened again, once again I was in my base. I have fluid pipes in my base transporting water to various tanks.

**Comment by zmaster587** [comment]
Can you create a minimum setup where this occurs and screenshot it and/or relay instructions on how to build it?  I suspect it may have something to do with one of the sources throwing a block update but I'm not 100% sure, also I did apply a patch that I hope will fix the issue in later releases and should be included into today's build on curse that I plan on pushing in an hour or so.

**Comment by zmaster587** [comment]
is this still an issue?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
