### ISSUE TITLE
Docking pad bug?

### ISSUE THREAD

**Issue by tobiasvdp** [zmaster587/AdvancedRocketry#704]
When trying to select the destination in the rocket an unnamed docking pad makes the gui not even open. with following error:
> [12:56:27] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
>         at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> **Caused by: java.lang.NullPointerException
>         at zmaster587.advancedRocketry.util.StationLandingLocation.toString(StationLandingLocation.java:59) ~[StationLandingLocation.class:?]**
>         at zmaster587.advancedRocketry.entity.EntityRocket.getModules(EntityRocket.java:1505) ~[EntityRocket.class:?]
>         at zmaster587.libVulpes.inventory.GuiHandler.getServerGuiElement(GuiHandler.java:44) ~[GuiHandler.class:unspecified]
>         at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
>         at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
>         at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
>         at zmaster587.advancedRocketry.entity.EntityRocket.useNetworkData(EntityRocket.java:1347) ~[EntityRocket.class:?]
>         at zmaster587.libVulpes.network.PacketEntity.execute(PacketEntity.java:102) ~[PacketEntity.class:unspecified]
>         at zmaster587.libVulpes.network.PacketEntity.executeServer(PacketEntity.java:107) ~[PacketEntity.class:unspecified]
>         at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:unspecified]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>         ... 5 more
> 

When I do give it a name however the gui opens, but it is not shown in the list:

![image](https://user-images.githubusercontent.com/5156314/27010450-b4c6b994-4ea4-11e7-8743-79bd7008a511.png)

**Comment by zmaster587** [comment]
So it appears that it's possible for the name to be null when the block is first placed before a server/world restart.  So I've gone and added an assignment to set the name to empty string instead which appears to fix the issue.
