### ISSUE TITLE
No link to satelites after server restart

### ISSUE THREAD

**Issue by tobiasvdp** [zmaster587/AdvancedRocketry#705]
Before server restart my satelites were producing data but I failed to retrieve the data using terminals.
The data stacks up in the satellite but is not transferred to the terminal even after pressing connect button.

Tought a server restart might help,
Now they are not even linking to the terminal anymore.

No errors in the logs

![image](https://user-images.githubusercontent.com/5156314/27010794-70f11350-4ead-11e7-9fdb-b6557f4a8964.png)

**Comment by AlphaNovaLight** [comment]
i have this issue too

**Comment by zmaster587** [comment]
Can you send a copy of the advRocketry/temp.dat file from the server?

**Comment by AlphaNovaLight** [comment]
i am using sponge with the bootstrap fix for AE2 

[temp.zip](https://github.com/zmaster587/AdvancedRocketry/files/1067002/temp.zip)

**Comment by zmaster587** [comment]
This looks very similar to #682, can you check the planetDefs.xml to see if there's a planet mapped to dimid 0?

**Comment by AlphaNovaLight** [comment]
i added ar to ftb beyond so i guess thats considered custom, and there is no DIMID 0 here is the file
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/1067068/planetDefs.zip)

**Comment by tobiasvdp** [comment]
It's added to direwolf20 10.0.2 mudpack. 
As far as I know no altering was done to forge by mods.
No configs were altered except for some added blocks in the sealing list

I've made the temp.dat available from this link
https://vdphome.synology.me:7002/sharing/PKHWGrMfy

I can't find a planet on id 0. 
Can see every star has a numPlanets="0" numGasGiants="0". Is that normal?
I should perhaps mention I did lose my earth's moon at some point. No clue why.
I've made the file available at
https://vdphome.synology.me:7002/sharing/NsBouSbBa

**Comment by tobiasvdp** [comment]
Ye read the other issue. That will prob be it then, 0 missing from the list.
I've followed the following update path if interested:
1.0.19 -> 1.2.0 -> 1.2.1
I'll try manually adding it in the xml

**Comment by tobiasvdp** [comment]
It has deleted earth from the xml after adding it.

**Comment by zmaster587** [comment]
What I'm most concerned about is the existance of a mod that forces the world to save at an unusual time such as before the world has finished loading, I've seen similar issues crop up due to mods that do that in the past.

**Comment by zmaster587** [comment]
So as it turns out, the server does not create an entry for the overworld by default.  Though I've still not been able to replicate the overworld properties dissappearing after being added to the xml while the server was offline.

**Comment by zmaster587** [comment]
That should fix the Earth not being added on first startup at least.

@tobiasvdp Are you 100% sure the server was completely shut down when you modified the XML config?

**Comment by tobiasvdp** [comment]
I'll try again in the morning and also from a solo mod forge. I'll keep you updated.

**Comment by zmaster587** [comment]
alright, I appriciate it

**Comment by AlphaNovaLight** [comment]
would you please apply the fix to the planetdefs file i uploaded above and reupload it here for me? i cant figure out how to manually add the fix

**Comment by tobiasvdp** [comment]
This is confirmation it gets deleted from the running modded server. going to try now as solo mod.

![image](https://user-images.githubusercontent.com/5156314/27069707-56a5187e-5016-11e7-8091-772d36801b9b.png)

![image](https://user-images.githubusercontent.com/5156314/27069855-e8e1d7a4-5016-11e7-8e1a-40d64c4e2f64.png)

**Comment by tobiasvdp** [comment]
Aaand fixed it.
Apperently you need to allow him to add the dimMapping="" attribute himself.
pasting it in without it adds the attribute and makes it stick.

**Comment by tobiasvdp** [comment]
@AlphaNovaLight this should fix yours
https://vdphome.synology.me:7002/sharing/z4YUO8mTc

**Comment by tobiasvdp** [comment]
Satellite link now persists. :)

**Comment by zmaster587** [comment]
Alright, good to hear,  I have fixed the Earth not being added by default in the most recent build so this issue should no longer pop up anymore on new world short of intentional editing
