### ISSUE TITLE
[Suggestion] Add Mod Integration to the Lathe

### ISSUE THREAD

**Issue by EmosewaGamer** [zmaster587/AdvancedRocketry#706]
Hello!
I believe that it could be a good idea to make the Lathe able to make Rods from other mods, just as the Rolling Machine can make Plates from other mods. That's it.

**Comment by zmaster587** [comment]
The Lathe should already do this automatically, though there has been some confusion over the correct ore dict entry for the rods, I've seen "rod" and "stick" so far, would you mind tossing me the name of the mod you're trying to get rods for?

**Comment by EmosewaGamer** [comment]
LightningCraft. The Plates work in the Rolling Machine, but the Rods don't in the Lathe. Actually, the same goes for every mod in my pack that has both. Are you sure that you set the rods correctly?

**Comment by zmaster587** [comment]
No I'm not, that's why I'm asking for examples, it was originally setup against the oredict entries used in IC2 and gregtech for 1.7.10.

I'll take a look into it and see what I can come up with.

**Comment by zmaster587** [comment]
Should be fixed in next release
