### ISSUE TITLE
Rocket Duplicates on Launch Pad

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#707]
Advanced Rocketry version 1.10.2-1.2.1 and libVulpes 1.10.2-0.2.4

I have an asteroid mining rocket, it was sent on a mission to mine an asteroid, it returned. After a game restart I tried to launch the rocket on a new mission but could not.

The Rocket monitoring stations and the fuelling station both reported that the rocket was full but the rocket was showing empty, I dismantled the rocket and rebuilt it then it fuelled and launched. However there was an identical rocket on the launch pad. I could dismantle and knock down and collect the parts.

Since this has happened twice now, there is something strange happening.

**Comment by zmaster587** [comment]
I've tried testing this by building an asteroid mining rocket, sending it off to mine asteroids, and waiting for it's return.  Upon returning I emptied the rocket by hand then restarted the server.  I did not experience a rocket duplication.  So I'm wondering does this happen every time or just some of the time?

**Comment by duncanwebb** [comment]
Hi, I know that this is going to be tricky as it doesn't happen every time but I don't think it is intermittent. It might be that I prepared an Asteroid chip left it in the rocket and restarted the game (single user mode). I'll try this and provide some feed back.

**Comment by zmaster587** [comment]
alright, did you have any other mods installed or only AR/libvulpes?

**Comment by duncanwebb** [comment]
I'm playing the Forever Stranded pack, so lots of other mods. I'm pretty sure it is to do with the order I'm doing things, rather than mod interaction or an intermittent bug. I tried the asteroid chip idea but the rocket worked expected. My next idea is that I forgot to put data in the Asteroid chip. Will test this today.

**Comment by zmaster587** [comment]
alright.  Also may somehow be related to #724?

**Comment by duncanwebb** [comment]
Sounds very similar. It may be that I was changing dimensions, I am trying to see if I can perform some terraforming so I was sending my rocket off to mine asteroids for rutile ore and also collecting gasses. So I would have been travelling to Sol-3.

**Comment by Forecaster** [comment]
I've observed this after a world reload while testing in singleplayer. After the reload the monitoring station looses it's connection to the rocket, but the mission continues and returns after the appropriate time, but the rocket is duplicated on the launch pad.

If you move out of range, causing the chunk the monitoring station to be unloaded, then move back to it it also looses the connection to the rocket, but the rocket is not duplicated on return.

**Comment by zmaster587** [comment]
is this still an issue?

**Comment by duncanwebb** [comment]
Since I've moved on from Forever Stranded to Forever Stranded Lost Souls I can't say if this still exists. I reckon you can close it and I'll create a new report if I come across this again.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
