### ISSUE TITLE
Asteroid Mining Mission Rocket gets stuck at top of world upon descent

### ISSUE THREAD

**Issue by AlphaNovaLight** [zmaster587/AdvancedRocketry#708]
every time i send a rocket to space for an asteroid mining mission, up untill it starts to come back down it goes smoothly, however when it reaches the top of the world, it just stops, when it is supposed to descend all the way back to the launch pad. i can fly up and access it and all that, but if i disassemble it, it just deletes all but the rocket boosters please help me fix this issue, i have re created it with many different designs and sizes, launching from different elevations. every time it gets stuck at the world height limit
![2017-06-11_18 04 58](https://user-images.githubusercontent.com/29361108/27015304-b262b320-4ed0-11e7-8106-1308c41018f3.png)
![2017-06-11_18 05 10](https://user-images.githubusercontent.com/29361108/27015305-b26b043a-4ed0-11e7-8776-d7120de54c19.png)
![2017-06-11_18 05 35](https://user-images.githubusercontent.com/29361108/27015306-b26bb222-4ed0-11e7-8c9f-a7fc82a8aa37.png)
![2017-06-11_18 05 52](https://user-images.githubusercontent.com/29361108/27015307-b26c01dc-4ed0-11e7-9acd-dbac1686ba58.png)

**Comment by zmaster587** [comment]
What version of the mod/minecraft?
Does this occur with no other mods installed?

**Comment by AlphaNovaLight** [comment]
FTB Beyond 1.8.1 and LibVulpes-1.10.2-0.2.3-universal.jar and AdvancedRocketry-1.10.2-1.2.0c.jar i havent tested this issue with no other mods present

**Comment by AlphaNovaLight** [comment]
only thing i changed in the configs to get the mod to work with ftb beyond was the space station dimension id, i changed it to -6. other than that i havent changed anything in the modpack or the mod of yours. regular rockets come back down fine, you know like the ones you ride

**Comment by AlphaNovaLight** [comment]
i just updated to the latest version of advanced rocketry and libvulpes and its still doing it

**Comment by zmaster587** [comment]
That's rather strange, the mining rocket is no different than a player ridden rocket, the only difference is that when orbit is reached there's a check that's run to see if there's an asteroid chip in the guidance computer.

I have tested it repeatedly on my end today and cannot replicate the same results, for me it reaches orbit and mines ores as expected.  This leads me to believe there may be some mod in that pack causing problems.  But I also cannot rule out something being odd with that particular save, so the idea is if you remove all the mods except AR and libvulpes and test it on that save again or a copy of it, then we can either be sure it's a problem with some other mod in the pack, or AR itself or the world.

**Comment by AlphaNovaLight** [comment]
i will do some more testing tomorrow and get back to you also i notice when i fly up to it at the top of the world and open the interface, the asteroid chip is missing, yet it was there when i launched it

**Comment by AlphaNovaLight** [comment]
ok i tested this on the same world but on vanilla with just the two mods, ar and libvulpes, and it landed fine. next ill test it on sp of ftb beyond to see if its sponge related, if it works on sp im betting it has something to do with sponge or one of my plugins.

**Comment by AlphaNovaLight** [comment]
ok i tested this on my single player for ftb beyond with the same world as my server has, and yay it worked fine, landed as it should, so must be an issue with sponge or one of my plugins, tomorrow i will remove my plugins one by one and ultimately remove sponge to figure out whats going on and then ill get back to you, im off to bed for now.

**Comment by AlphaNovaLight** [comment]
ok so i removed my plugins 1 by 1 with no luck, then proceeded to remove sponge....and it worked.... so i conclude this is an issue with sponge. im running version spongeforge-1.10.2-2281-5.2.0-BETA-2341.jar
i am going to update to 1.10.2-2281-5.2.0-BETA-2379 and see if it helps but i doubt it will as much hasnt changed between builds. so my testing kinda ends here. i hope i gave u the info u need to figure this out.

**Comment by AlphaNovaLight** [comment]
and just incase, this is the bootstrap i was using
https://github.com/simon816/SpongeBootstrap/releases/tag/v0.3.0

**Comment by AlphaNovaLight** [comment]
hmm odd i also notice that the rocket monitoring station is either unlinking from the rocket assembly machine or its just not showing the fuel being full when it is, and re linking it makes the fuel show up. and this is occuring with sponge installed, and when i uninstalled sponge to test the above issue this issue did not occur

**Comment by AlphaNovaLight** [comment]
OK i updated sponge and it did not help shit, still gets stuck at top of world. I'm sorry but i rely on my plugins so ill have to do without asteroid mining missions until this gets fixed, thanks

**Comment by zmaster587** [comment]
Alright, so that does sound like a sponge issue, like I've said in other threads, I've got too much on my plate with just keeping the mod stable as it is without supporting other platforms.  So I really can't garuntee sponge/thermos/etc support.  I'll keep it on the back burner in case I do somewhere get time to look into it though.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Feafroth** [comment]
The issue still actual. To reproduce you need create world then updste version of AR
