### ISSUE TITLE
data retrieval from satellite in spacestation

### ISSUE THREAD

**Issue by tobiasvdp** [zmaster587/AdvancedRocketry#709]
I'm able to retrieve the data from a satellite from the overworld, but not from the spacestation.
When orbiting another planet is says correctly 'to far'. 
When in the right system I can see it's data. however the connect button simply does nothing.

![image](https://user-images.githubusercontent.com/5156314/27024429-c5e5f890-4f56-11e7-9496-7019c0a54a31.png)

**Comment by tobiasvdp** [comment]
Wanted to verify it wasn't the overworld by launching them around another planet. Got this and a server crash as extra:

> Description: Ticking entity
> 
> java.lang.NullPointerException: Ticking entity
> 	at zmaster587.advancedRocketry.api.satellite.SatelliteBase.setDimensionId(SatelliteBase.java:111)
> 	at zmaster587.advancedRocketry.satellite.SatelliteData.setDimensionId(SatelliteData.java:76)
> 	at zmaster587.advancedRocketry.dimension.DimensionProperties.addSatallite(DimensionProperties.java:732)
> 	at zmaster587.advancedRocketry.entity.EntityRocket.unpackSatellites(EntityRocket.java:897)
> 	at zmaster587.advancedRocketry.entity.EntityRocket.onOrbitReached(EntityRocket.java:791)
> 	at zmaster587.advancedRocketry.entity.EntityRocket.func_70071_h_(EntityRocket.java:677)
> 	at net.minecraft.world.World.func_72866_a(World.java:1964)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
> 	at net.minecraft.world.World.func_72870_g(World.java:1934)
> 	at net.minecraft.world.World.func_72939_s(World.java:1750)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by tobiasvdp** [comment]
I havn't landed yet on the planet. Might that have something to do with it?

**Comment by zmaster587** [comment]
So it turns out that at least in the 1.10 builds the satellite terminals do not check for effective ID when the button is pressed even though they do for the insertion of the chip.  Fixed for next build
