### ISSUE TITLE
Machine problems part 2

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#71]
It seems with the latest version the issue with materials dissappearing has been solved, however, I still have 2 minor issues

First is the reset problem, the machine blinks and all block except the main block dissappears visually. I need to right click the main block again to make it reappear. and the power botton turned off by itself. This usually happens after that the machine finished processing stuff, but after a while the processing animation starts playing again, then if I right click the main block, the reset happens. This has happend many times before my eyes so it shouldn't be cross-chunk problem. Some kind of sever/clinet sync issue? I've attatched a screenshot for this
![image](https://cloud.githubusercontent.com/assets/2989009/11986288/89e574d2-a9d6-11e5-9500-06180d2e5872.png)
![image](https://cloud.githubusercontent.com/assets/2989009/11986291/955612f4-a9d6-11e5-9fcb-0bb6a9835e5c.png)

Second problem is purely visual, when I relog into the server all AR machines appears to be invisible except the main block, but I just need to right click them all to make them appear, and they are not switched off. 
![20151224004157](https://cloud.githubusercontent.com/assets/2989009/11986346/2509d886-a9d7-11e5-87e2-fdb6fcc07cb0.jpg)

**Comment by zmaster587** [comment]
Does the 2nd issue happen every time you log into the server?  Do these issues still occur  if you break and replace every block in the machines? (Reason I ask is a few changes made between updates broke existing machines in a similar manner to described)

**Comment by wormzjl** [comment]
These machines are placed after that update

**Comment by zmaster587** [comment]
Do you have anything like cauldron or fastcraft installed and if so does it still occur without it?

**Comment by zmaster587** [comment]
Does this build https://www.dropbox.com/s/nzaqj5irv142sh8/AdvancedRocketry-0.4.10.jar?dl=0 fix the machines vanishing?

**Comment by zmaster587** [comment]
Seems to occur more often on laggy servers

**Comment by wormzjl** [comment]
haven't observed such problems with the latest build, gonna cloise this for now
