### ISSUE TITLE
Machines Stopped

### ISSUE THREAD

**Issue by aszareel** [zmaster587/AdvancedRocketry#710]
When building the machines, everything works fine, but when leaving the game and re-entering later, they stop working or they do it randomly.
I have not been able to figure out what produces it, but it's quite annoying.
1.11.2 version

**Comment by tobiasvdp** [comment]
same on 1.10.2
The multiblocks aren't formed or initialized or sumthing and need to be 'right clicked' in order for them to function again.

**Comment by zmaster587** [comment]
Does this only occur in single player, servers, or both?  Does this only occur for machines straddling multiple chunks?

**Comment by aszareel** [comment]
Forge 13.20.0.2300
Optifine B9
Single player
Confirmed occurring in:
Electric Arc Furnace
Lathe
Crystallizer
Cutting machine
Rolling Machine
Precision Assembler

I can not confirm more, since I have not been able to go any further

**Comment by tobiasvdp** [comment]
Here server,
some of them are single chunk, so that is not the cause I'm afraid

**Comment by zmaster587** [comment]
as for the server, is anything like sponge, thermos, MCPC installed?  Reason I ask is because I've had some strange dealings with those mods in the past.

@aszareel does this also occur without optifine?

**Comment by zmaster587** [comment]
working on a fix

**Comment by zmaster587** [comment]
Can you test out this build of libvulpes and see if the issue still occurs?
MC1.11: http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/MC1.11/10/
MC1.10.2: http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_10/22/

**Comment by tobiasvdp** [comment]
Running clean dw20 1.10.2. Dont think any of the mods alter core code.
Ill try the lib in het morning.

**Comment by zmaster587** [comment]
Yeah, I was able to replicate it on a pack containing only libvulpes and AR.  I keep forgetting spawn is always loaded so it screwed up most of my previous tests.

**Comment by tobiasvdp** [comment]
No joy. remains same on 1.10.2

**Comment by aszareel** [comment]
Neither works with LibVulpes-1.11.2-0.2.5-10-universal.jar.

**Comment by tobiasvdp** [comment]
If I have the time tomorrow I might have a quick look at the code. Your main branch is 1.11?

**Comment by zmaster587** [comment]
the master branch on github is 1.7, the MC1.11 branch is 1.11

**Comment by rahangar** [comment]
any progress on this issue?

I have 18 Crystallizers (don't laugh - in 1.10.2 - 1.0.19 there is no ability to upgrade to faster machines, so I just added more machines).

All Crystallizers are getting input from AE2 interfaces (auto processing) in blocking mode.  I trigger creation of a ton of dilithium crystals (at least a stack).  But I'm lucky if only about a third of the crystallizers actually work. ... until I walk up to each non-working one and just right-click - then it starts working.  Until then, the dilithium dust just sits in the input hatch.   All Crystallizer are at a space station and they are all chunk loaded.

Let me know if you need more data.

**Comment by Flanks255** [comment]
i'm running into this issue as well, was trying to automate all the machines, but none actually function until i manually put the materials in, piping in with Thermal Dynamics, or AE2 interfaces dont trigger the machine to actually process it seems.

**Comment by dmodoomsirius** [comment]
Are you running the latest Versions of Advanced Rocketry and LibVulpes off curse? Just to see if this issue is fixed?

**Comment by Flanks255** [comment]
still does it with the newest version advrocketry and libvulpes

**Comment by zmaster587** [comment]
is this still an issue with builds after Dec 31st in the unstable versions?  There were quite a few fixes over that week all over the place.
