### ISSUE TITLE
Jetpack Hover Bug

### ISSUE THREAD

**Issue by chipgeekjr** [zmaster587/AdvancedRocketry#711]
When wearing the jetpack in the modular space suit, with 3 speed and a hover upgrade in the helmet, sprinting with ic2's quantum legs, toggling the jetpack on into hover mode and taking off, allows the jetpack to be turned off and all space suit parts to be unequiped, while still flying in the air. Lasts until you land on something. Advanced Rocketry 1.10.2-1.0.19, libVulpes 1.10.2-0.1.19, ic2 2.6.210-ex110

**Comment by chipgeekjr** [comment]
After more testing, it doesn't even need ic2 at all, simply sprinting, turning on the jetpack and wating for the speed increase, leaving the ground while still sprinting and then turning it off triggers the bug.

**Comment by zmaster587** [comment]
looking into it

**Comment by DietmarKrause** [comment]
in my case it simply not possible to go to hover mode. i havent understood from the beginning how to do that form the video i helped me with creative flight from angel ring (but even without that ring i cannot go to hover mode) i am playing All the mods 1

**Comment by zmaster587** [comment]
Redid jetpack hovermode, should be fixed now
