### ISSUE TITLE
Observatory in space

### ISSUE THREAD

**Issue by tobiasvdp** [zmaster587/AdvancedRocketry#713]
Do they still produce distance data? or do they get fed?

I can create asteroid id chips if fed with data, 
On overworld they don't produce data on their own.
In space they don't open up/work when turning the ship into darkness.

(you might have guessed by now my ship is my base ;))

**Comment by zmaster587** [comment]
The Observatories no longer produce data on their own so you do have to feed them now.

Though they should open up when the ship is rotated.  I'll look into that.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
