### ISSUE TITLE
rockets not launching

### ISSUE THREAD

**Issue by c0mical** [zmaster587/AdvancedRocketry#714]
Hi

I have an issue on my server where rockets are not launching.

everything builds OK, lets me into the rocket OK, set destination and all that good stuff

but when I press space, the only thing that happens is that the fuel bar on the bottom left goes down to empty, the rocket doesn't actually move

I've tried a few rockets with the same result

I have been able to launch a station however

I am running with a long list of mods so I am going start fresh and add them in batches trying to find if there are any conflicts there

does this sound like anything that you could recognise of the top of your head

Cheers, and great mod!

**Comment by tobiasvdp** [comment]
are you sure the entire rocket doesn't clip any blocks?
Is not only the rocket but the entire box that comprises the rocket.

**Comment by c0mical** [comment]
Hi yes that was it, it took me a fair while to figure out!

it seems that there has to be a decent number of blocks that it has to have clear around it. 

I was hoping to build an enclosure around the rocket/pad

do you know what the distance has to be?

**Comment by tobiasvdp** [comment]
you should think of the spaceship as a box. Normally when formed you can't even walk inside that box. 
The picture below illustrates that with a random end house. There are only a few blocks at the bottom but the box has to comprise the whole ship. Perhaps you have an extension of blocks on your ship that increases that box size?  Normally if the box fits trough the opening it should be ok.
![structure_block_4](https://user-images.githubusercontent.com/5156314/27122845-34cc158c-50ec-11e7-8757-4cd9e70e5405.png)

**Comment by c0mical** [comment]
Thanks for the reply, I did initially have nothing that would touch the width/length of the rocket, I then tried the height/with of the actual launch pad, the the launch pad plus the tower and assembly and finally about 5-6 block all around

none of these worked, but when I went into a new block where there was a good 10 or so block of space around it - it worked fine for me

**Comment by tobiasvdp** [comment]
mmm weird. Can you screenshot the place?

**Comment by c0mical** [comment]
yeah sure, I'll add them tonight when I get back home. I cant remember if I still have the old tests but I can create a little scenario to confirm, cheers for your help

**Comment by c0mical** [comment]
Hi

I've had a play around tonight, and I can't actually get them to not work. 

Thanks

**Comment by zmaster587** [comment]
strange indeed...  if it comes up again I guess just reopen the issue?
