### ISSUE TITLE
walking into the Pressurized tank

### ISSUE THREAD

**Issue by tobiasvdp** [zmaster587/AdvancedRocketry#715]
When getting close to the tanks you can walk a bit in them and the screen goes black.

![image](https://user-images.githubusercontent.com/5156314/27095163-08fcf1ee-506d-11e7-83ad-82c3dac59b8e.png)

**Comment by zmaster587** [comment]
What version of MC?

**Comment by tobiasvdp** [comment]
I'm playing on the 1.10.2

**Comment by zmaster587** [comment]
Alright, likely due to some bounds checing thing
