### ISSUE TITLE
Not enough fuel capacity (unmanned vehicle)

### ISSUE THREAD

**Issue by tobiasvdp** [zmaster587/AdvancedRocketry#716]
I'm trying to get the gas collector to work. but as soon as I put some storage in there (more then 3 pressurized tanks) is says there isn't enough fuel capacity. Is this intentional to limit the amount of gasses brought back? or a bug? The bars on the screen would disagree to the limiting.

![image](https://user-images.githubusercontent.com/5156314/27095680-d834c292-506e-11e7-997b-68acbd97203a.png)

![image](https://user-images.githubusercontent.com/5156314/27095725-f9cf05fc-506e-11e7-8790-055ce4425dfc.png)

**Comment by zmaster587** [comment]
There's no hard limit on any of the rockets, whether or not a rocket can fly is purely determined by fuel capacity and thrust.
Admittedly i can't tell what's wrong from the screen alone, I'll check to see if there's some place where a different calculation is used.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
