### ISSUE TITLE
Multiblock Machines don't work after update to 1.2.2 (MC 1.11.2)

### ISSUE THREAD

**Issue by aaronegger** [zmaster587/AdvancedRocketry#718]
Hello,

We started using AdvancedRocketry since Version 1.2.0f.
We have built some of those Multiblock Machines (Electric Arc Furnace, Lathe, Cutting Machine, Rolling Machine, Precission Assembly Machine, Crystallizer).
After the Update to 1.2.1 the Rolling Machine refused to work and to get the other machines working we had to remove the input/output hatches.

But now after the Update to 1.2.2 all these Machines completely refuses to work.

They all have energy and we provides materials from LibVulpes and IndustrialCraft 2.
Even rebuilding the machines didn't help.

Furthermore the Observatory doesn't work as expected since 1.2.0f.
It opens correctly, has power on both power input plugs, but i doesn't collect any data.
We took care that there is not light at all.

But now some information about our server.
It is an
SpongeServer (spongeforge-1.11.2-2282-6.1.0-BETA-2358)
running Minecraft 1.11.2

The mods that are currently installed:

AbyssalCraft-1.11.2-1.9.4-pre-2
AdvancedRocketry-1.11.2-1.2.2
AnimalBikes-1.11.2
Baubles-Mod-1.11.2
BiomesOPlenty-1.11.2-6.1.0.2238-universal
Botania r1.9-343
ChickenChunks-1.11.2-universal
CodeChickenLib-1.11.2-Recommended
CosmeticArmorReworked-1.11.2
ExtremeReactors-1.11.2
Galacticraft-Planets-1.11.2-4.0.0.107
GalacticraftCore-1.11.2-4.0.0.107
Gun-1.11.2
InventoryTweaks-1.62-dev-78
JourneyMap-1.11.2
JurassiCraft-2.0.5
LLibrary-1.11.2
Levels-Mod-1.11.2
LibVulpes-1.11.2-0.2.5-universal
Mantle-1.11.2-1.2.0.26
MicdoodleCore-1.11.2-4.0.0.107
MoreAnvils-1.11-7.0.0
TConstruct-1.11.2-2.7.0.26
aether_legacy-1.11.2-1.0
compatlayer-1.11.2-0.2.9
energyconverters_1.11.2-0.7.0.15
extrautils2-1.11.2-1.4.1
industrialcraft-2-2.7.60-ex111
jei_1.11.2-4.3.5.277
plustic-5.0.1.0
zerocore-1.11.2-0.1.0.4

**Comment by zmaster587** [comment]
The observatory no longer collects data after builds 1.0.x due to the fact it's function has been changed to only finding and programming asteroid chips because the data collecting satellite performs better and is cheaper anyway.

Would it be possible to try without any other mods installed, or at least without sponge?

**Comment by aaronegger** [comment]
Oh, thank for this info! I missed that.

I have now tested it without any other mods except of just enough items. I can't think about this mod could collide with your mod.

I disabled all mods, and firstly run the vanilla server to clear the world. Afterwards i started it with forge.

I built a simple setup with solar generators and a lathe.
I uploaded some screenshots:
http://mc.aaronegger.de/sc1.png
http://mc.aaronegger.de/sc2.png
http://mc.aaronegger.de/sc3.png
http://mc.aaronegger.de/sc4.png
http://mc.aaronegger.de/Server.png

But even now the machine refused to work.

Do you have any idea why?
Can you confirm/replicate this behaviour?

**Comment by aaronegger** [comment]
I downgraded to 1.2.1 and now the lathe starts working again.
It seems that some of the changes in the new version broke the machines..

**Comment by zmaster587** [comment]
May be related to #710,  can you give the 1.11 build of libvulpes in there a shot?

**Comment by EmosewaGamer** [comment]
Yup, many people have been complaining about it as the Rolling machine is required to progress in my pack. The problem is that simply the multiblocks form, but don't work. When you put the needed items in they do nothing.

**Comment by tobiasvdp** [comment]
Do they start working when you flip the power switch off an on again?

**Comment by EmosewaGamer** [comment]
No, it does not.

**Comment by aaronegger** [comment]
@zmaster587 I tried it again with the LibVulpes-1.11.2-0.2.5-10-universal file. But again it does not work.
It started a new single player map and built another setup with solar generators and a lathe. 

This time i also tried it with different types of motors.

**Comment by zmaster587** [comment]
@EmosewaGamer have you tried right clicking the control block, then taking an item out of the input slot and putting it back in?

**Comment by zmaster587** [comment]
At least one issue is patched in LibVulpes-1.11.2-0.2.5-11-universal-12, turns out when I tried to fix handling of recipes with multiple outputs a null check was introduced and I forgot to change it to item.isEmpty() in the 1.11 build.

**Comment by aaronegger** [comment]
Ok i tested the new LibVulpes mod.
The machines seems to be working now, except the rolling machine^^

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
