### ISSUE TITLE
Server Crash after launching rocket with satellite

### ISSUE THREAD

**Issue by aaronegger** [zmaster587/AdvancedRocketry#719]
Hello,

i have encountered another issue.

Our server crashed after building a small rocket with a satellite and an empty satellite within the bay.
The rocket launched succesfully. But after reaching the orbit, the server has crashed.

I've got a log on gist: https://gist.github.com/aaronegger/faeded8fccb2af297286b2ef1e2d66ba

Our server:
It is an
SpongeServer (spongeforge-1.11.2-2282-6.1.0-BETA-2358)
running Minecraft 1.11.2

The mods that are currently installed:

AbyssalCraft-1.11.2-1.9.4-pre-2
AdvancedRocketry-1.11.2-1.2.2
AnimalBikes-1.11.2
Baubles-Mod-1.11.2
BiomesOPlenty-1.11.2-6.1.0.2238-universal
Botania r1.9-343
ChickenChunks-1.11.2-universal
CodeChickenLib-1.11.2-Recommended
CosmeticArmorReworked-1.11.2
ExtremeReactors-1.11.2
Galacticraft-Planets-1.11.2-4.0.0.107
GalacticraftCore-1.11.2-4.0.0.107
Gun-1.11.2
InventoryTweaks-1.62-dev-78
JourneyMap-1.11.2
JurassiCraft-2.0.5
LLibrary-1.11.2
Levels-Mod-1.11.2
LibVulpes-1.11.2-0.2.5-universal
Mantle-1.11.2-1.2.0.26
MicdoodleCore-1.11.2-4.0.0.107
MoreAnvils-1.11-7.0.0
TConstruct-1.11.2-2.7.0.26
aether_legacy-1.11.2-1.0
compatlayer-1.11.2-0.2.9
energyconverters_1.11.2-0.7.0.15
extrautils2-1.11.2-1.4.1
industrialcraft-2-2.7.60-ex111
jei_1.11.2-4.3.5.277
plustic-5.0.1.0
zerocore-1.11.2-0.1.0.4

**Comment by zmaster587** [comment]
Appears to be caused by a bit of an oversight, before the last release an empty satellite was unobtainable and I had forgot to implement a check.

**Comment by aaronegger** [comment]
Oh i am sorry for testing only with an empty satellite.. 
But thank you for this fast fix :D

I appreciate your work very much!
