### ISSUE TITLE
crashed wile flying to space station

### ISSUE THREAD

**Issue by bloodheru** [zmaster587/AdvancedRocketry#720]
any and all help appreciated. after launching rocket crashed wile trying to load space dimension. tried to relaunch game several times only to keep crashing here is the report

[crash-2017-06-13_15.25.09-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1072990/crash-2017-06-13_15.25.09-server.txt)

**Comment by zmaster587** [comment]
Can you give it a try with this version of libvulpes and see if the crashing continues?  http://65.78.115.159:8080/job/LibVulpes/job/libVulpes/job/unstable1_10/20/

**Comment by bloodheru** [comment]
worked well had to replace some cables and such but it loaded first try and runs smooth. thank you very much for your timely response and hard work to fix my issue much appreciated!

**Comment by bloodheru** [comment]
one last note.. when I loaded in I was falling in space I enabled flight and watched rocket fall below me. (not sure if it landed on station or not there was a rocket docked with station) I used portable teleporter to earth and built a new rocket flew it back to station no problem. found I had 2 rockets up there.
