### ISSUE TITLE
opening creative tab fuel tank rendering?

### ISSUE THREAD

**Issue by tiarnia** [zmaster587/AdvancedRocketry#721]
WARNING: coremods are present:
[B#349]    LoadingPlugin (Bloodmoon-MC1.11-1.5.1 (1).jar)
[B#349]    AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
[B#349]    NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
[B#349]    AdvancedRocketryPlugin (AdvancedRocketry-1.11.2-1.2.2.jar)
[B#349]    LoadingPlugin (Quark-r1.2-93.jar)
[B#349]    Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
[B#349]    HammerCoreCore (HammerCore_1.11.2-1.8.1.jar)
[B#349]    LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
[B#349]    ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
[B#349]    ForgelinPlugin (Forgelin-1.4.2.jar)
[B#349]    Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
[B#349]    ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
[B#349]    RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
[B#349]    LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
[B#349]    DLFMLCorePlugin (DynamicLights-1.11.2.jar)
[B#349]    SFRCore (SolarFluxReborn_1.11.2-2.19r.jar)
[B#349]    BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
[B#349]  Contact their authors BEFORE contacting forge
[B#349]  
[B#349]  // I bet Cylons wouldn't have this problem.
[B#349]  
[B#349]  Time: 6/13/17 9:42 PM
[B#349]  Description: Rendering item
[B#349]  
[B#349]  java.lang.ClassCastException: net.minecraftforge.fluids.capability.templates.FluidHandlerItemStack cannot be cast to net.minecraftforge.common.model.animation.IAnimationStateMachine
[B#349]  	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:70)
[B#349]  	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248)
[B#349]  	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
[B#349]  	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
[B#349]  	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
[B#349]  	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
[B#349]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
[B#349]  	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
[B#349]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:124)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#349]  
[B#349]  
[B#349]  A detailed walkthrough of the error, its code path and all known details is as follows:
[B#349]  ---------------------------------------------------------------------------------------
[B#349]  
[B#349]  -- Head --
[B#349]  Thread: Client thread
[B#349]  Stacktrace:
[B#349]  	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:70)
[B#349]  	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248)
[B#349]  
[B#349]  -- Item being rendered --
[B#349]  Details:
[B#349]  	Item Type: zmaster587.advancedRocketry.item.ItemBlockFluidTank@496a1ba2
[B#349]  	Item Aux: 0
[B#349]  	Item NBT: null
[B#349]  	Item Foil: false
[B#349]  Stacktrace:
[B#349]  	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
[B#349]  	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
[B#349]  	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
[B#349]  	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
[B#349]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
[B#349]  	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
[B#349]  
[B#349]  -- Screen render details --
[B#349]  Details:
[B#349]  	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
[B#349]  	Mouse location: Scaled: (335, 176). Absolute: (1006, 488)
[B#349]  	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3
[B#349]  
[B#349]  -- Affected level --
[B#349]  Details:
[B#349]  	Level name: MpServer
[B#349]  	All players: 1 total; [EntityPlayerSP['tiarnia'/576, l='MpServer', x=251.31, y=70.00, z=264.78]]
[B#349]  	Chunk stats: MultiplayerChunkCache: 266, 266
[B#349]  	Level seed: 0
[B#349]  	Level generator: ID 00 - default, ver 1. Features enabled: false
[B#349]  	Level generator options: 
[B#349]  	Level spawn location: World: (228,64,248), Chunk: (at 4,4,8 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[B#349]  	Level time: 6339 game time, 6339 day time
[B#349]  	Level dimension: 0
[B#349]  	Level storage version: 0x00000 - Unknown?
[B#349]  	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[B#349]  	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
[B#349]  	Forced entities: 148 total; [EntityCreeper['Creeper'/261, l='MpServer', x=246.50, y=12.00, z=186.50], EntityCreeper['Creeper'/262, l='MpServer', x=248.50, y=12.00, z=186.50], EntityItem['item.item.animania_truffle'/264, l='MpServer', x=243.26, y=76.00, z=206.55], EntityFrogs['Frog'/265, l='MpServer', x=251.50, y=67.00, z=202.85], EntityItem['item.item.animania_truffle'/268, l='MpServer', x=242.41, y=77.00, z=210.54], EntityPigletLargeWhite['Large White Piglet'/269, l='MpServer', x=248.38, y=76.00, z=218.89], EntitySowLargeWhite['Large White Sow'/270, l='MpServer', x=248.13, y=76.00, z=219.88], EntityItem['item.item.animania_truffle'/271, l='MpServer', x=247.97, y=76.00, z=211.01], EntityChickRhodeIslandRed['Rhode Island Red Chick'/272, l='MpServer', x=266.22, y=73.21, z=226.13], EntityVillager['Villager'/273, l='MpServer', x=247.70, y=70.00, z=255.70], EntityWitch['Witch'/274, l='MpServer', x=255.50, y=36.00, z=258.50], EntityFrogs['Frog'/275, l='MpServer', x=250.85, y=70.00, z=288.85], EntityItem['item.item.feather'/276, l='MpServer', x=241.13, y=64.00, z=317.33], EntityCreeper['Creeper'/278, l='MpServer', x=244.50, y=9.00, z=338.50], EntityHedgehog['Hedgehog'/282, l='MpServer', x=255.81, y=75.00, z=221.65], EntitySentry['Sentry'/283, l='MpServer', x=263.78, y=64.00, z=236.55], EntitySkeleton['Skeleton'/299, l='MpServer', x=276.30, y=39.00, z=190.30], EntityBat['Bat'/300, l='MpServer', x=279.50, y=45.10, z=186.75], EntityCreeper['Creeper'/301, l='MpServer', x=274.30, y=37.00, z=191.30], EntitySkeleton['Skeleton'/303, l='MpServer', x=283.73, y=49.00, z=185.50], EntitySkeleton['Skeleton'/306, l='MpServer', x=276.50, y=37.00, z=193.50], EntityCreeper['Creeper'/307, l='MpServer', x=276.97, y=39.00, z=190.83], EntityCreeper['Creeper'/309, l='MpServer', x=277.50, y=18.00, z=231.50], EntityCreeper['Creeper'/310, l='MpServer', x=281.50, y=18.00, z=232.50], EntitySentry['Sentry'/311, l='MpServer', x=282.25, y=70.00, z=229.50], EntityHenRhodeIslandRed['Rhode Island Red Hen'/312, l='MpServer', x=283.59, y=62.71, z=275.52], EntitySentry['Sentry'/313, l='MpServer', x=273.50, y=64.00, z=293.50], EntityHedgehog['Hedgehog'/314, l='MpServer', x=280.63, y=80.00, z=299.92], EntitySentry['Sentry'/315, l='MpServer', x=285.67, y=77.00, z=298.50], EntitySentry['Sentry'/316, l='MpServer', x=286.69, y=77.00, z=298.50], EntitySowOldSpot['Old Spot Sow'/317, l='MpServer', x=287.03, y=75.00, z=291.87], EntityPlayerSP['tiarnia'/576, l='MpServer', x=251.31, y=70.00, z=264.78], EntitySkeleton['Skeleton'/328, l='MpServer', x=291.50, y=51.00, z=206.50], EntitySkeleton['Skeleton'/329, l='MpServer', x=301.70, y=49.00, z=202.50], EntitySkeleton['Skeleton'/330, l='MpServer', x=296.45, y=51.00, z=203.10], EntityHedgehog['Hedgehog'/331, l='MpServer', x=290.48, y=87.00, z=203.99], EntitySheep['Sheep'/332, l='MpServer', x=289.45, y=90.00, z=200.31], EntitySkeleton['Skeleton'/334, l='MpServer', x=290.50, y=55.00, z=220.50], EntityEnderman['Enderman'/335, l='MpServer', x=285.66, y=51.00, z=208.50], EntitySowOldSpot['Old Spot Sow'/336, l='MpServer', x=297.08, y=72.00, z=221.94], EntityCreeper['Creeper'/338, l='MpServer', x=301.50, y=30.00, z=237.50], EntityCreeper['Creeper'/339, l='MpServer', x=302.87, y=36.00, z=231.16], EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/340, l='MpServer', x=292.59, y=62.60, z=245.42], EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/341, l='MpServer', x=298.22, y=64.00, z=275.47], EntityZombie['Zombie'/342, l='MpServer', x=296.45, y=41.00, z=289.25], EntitySentry['Sentry'/343, l='MpServer', x=297.51, y=75.00, z=294.19], EntityItem['item.item.seeds'/345, l='MpServer', x=291.46, y=61.00, z=324.64], EntityBat['Bat'/348, l='MpServer', x=292.89, y=46.97, z=184.46], EntityBat['Bat'/349, l='MpServer', x=296.26, y=47.08, z=197.69], EntityHogOldSpot['Old Spot Hog'/353, l='MpServer', x=307.61, y=90.00, z=204.92], EntityItem['item.item.animania_raw_prime_pork'/354, l='MpServer', x=306.08, y=86.00, z=203.67], EntityItem['item.item.animania_truffle'/355, l='MpServer', x=305.95, y=83.00, z=206.12], EntitySkeleton['Skeleton'/357, l='MpServer', x=309.30, y=23.62, z=223.83], EntityCreeper['Creeper'/358, l='MpServer', x=304.50, y=20.00, z=226.50], EntitySkeleton['Skeleton'/359, l='MpServer', x=309.30, y=38.00, z=228.50], EntityItem['item.item.feather'/361, l='MpServer', x=307.25, y=67.00, z=240.74], EntityCowHolstein['Holstein Cow'/364, l='MpServer', x=315.06, y=63.00, z=268.04], EntityHenRhodeIslandRed['Rhode Island Red Hen'/366, l='MpServer', x=314.76, y=63.00, z=266.80], EntityZombie['Zombie'/368, l='MpServer', x=318.50, y=36.00, z=273.50], EntityZombieVillager['Zombie Villager'/369, l='MpServer', x=307.81, y=32.00, z=281.50], EntityZombie['Zombie'/370, l='MpServer', x=312.50, y=40.00, z=283.50], EntityZombie['Zombie'/371, l='MpServer', x=312.50, y=40.00, z=283.50], EntityHogLargeWhite['Large White Hog'/372, l='MpServer', x=310.95, y=70.00, z=293.96], EntityCreeper['Creeper'/373, l='MpServer', x=304.19, y=25.00, z=315.50], EntitySkeleton['Skeleton'/376, l='MpServer', x=316.50, y=36.00, z=333.50], EntityZombie['Zombie'/120, l='MpServer', x=173.45, y=37.00, z=238.26], EntitySheep['Sheep'/131, l='MpServer', x=172.81, y=80.00, z=312.50], EntityZombie['Zombie'/393, l='MpServer', x=328.22, y=35.00, z=200.52], EntitySkeleton['Skeleton'/396, l='MpServer', x=330.50, y=30.00, z=213.50], EntityZombie['Zombie'/141, l='MpServer', x=177.50, y=59.00, z=193.50], EntityBat['Bat'/397, l='MpServer', x=324.95, y=38.68, z=210.72], EntitySpider['Spider'/398, l='MpServer', x=324.79, y=30.00, z=238.07], EntityCowHolstein['Holstein Cow'/142, l='MpServer', x=193.04, y=73.00, z=246.99], EntityVillager['Villager'/145, l='MpServer', x=189.57, y=75.00, z=261.52], EntityVillager['Villager'/146, l='MpServer', x=191.50, y=73.50, z=256.50], EntityHedgehog['Hedgehog'/147, l='MpServer', x=204.28, y=71.00, z=288.53], EntitySheep['Sheep'/149, l='MpServer', x=184.50, y=78.00, z=314.50], EntityZombie['Zombie'/407, l='MpServer', x=323.50, y=36.00, z=265.80], EntityBat['Bat'/409, l='MpServer', x=321.67, y=45.85, z=281.05], EntityBat['Bat'/410, l='MpServer', x=327.04, y=27.86, z=301.84], EntitySheep['Sheep'/155, l='MpServer', x=176.50, y=80.00, z=324.19], EntityCreeper['Creeper'/411, l='MpServer', x=322.83, y=29.00, z=316.47], EntityBat['Bat'/412, l='MpServer', x=321.46, y=30.93, z=315.11], EntityBat['Bat'/170, l='MpServer', x=200.75, y=30.10, z=186.70], EntityBat['Bat'/171, l='MpServer', x=200.75, y=27.14, z=185.63], EntityHedgehog['Hedgehog'/173, l='MpServer', x=205.17, y=77.00, z=237.51], EntityArmorStand['Armor Stand'/174, l='MpServer', x=204.50, y=83.00, z=264.50], EntityArmorStand['Armor Stand'/175, l='MpServer', x=205.50, y=83.00, z=264.50], EntityArmorStand['Armor Stand'/176, l='MpServer', x=207.50, y=83.00, z=264.50], EntityArmorStand['Armor Stand'/177, l='MpServer', x=204.50, y=83.00, z=264.50], EntityArmorStand['Armor Stand'/178, l='MpServer', x=205.50, y=83.00, z=264.50], EntityArmorStand['Armor Stand'/179, l='MpServer', x=207.50, y=83.00, z=264.50], EntityGuard['Guard'/180, l='MpServer', x=193.95, y=87.00, z=264.37], EntityGuard['Guard'/181, l='MpServer', x=208.50, y=83.56, z=271.15], EntityGuard['Guard'/182, l='MpServer', x=203.45, y=78.00, z=278.82], EntityGuard['Guard'/183, l='MpServer', x=206.50, y=83.00, z=264.20], EntityGuard['Guard'/184, l='MpServer', x=205.81, y=83.56, z=273.70], EntityVillager['Villager'/185, l='MpServer', x=197.71, y=76.00, z=302.48], EntitySowLargeWhite['Large White Sow'/186, l='MpServer', x=198.99, y=73.00, z=290.93], EntityVillager['Villager'/187, l='MpServer', x=201.73, y=76.00, z=306.55], EntityVillager['Villager'/197, l='MpServer', x=219.30, y=79.00, z=233.70], EntityCreeper['Creeper'/198, l='MpServer', x=214.50, y=34.00, z=251.50], EntityVillager['Villager'/199, l='MpServer', x=218.54, y=81.00, z=254.73], EntityVillager['Villager'/200, l='MpServer', x=220.58, y=81.00, z=249.50], EntityZombie['Zombie'/201, l='MpServer', x=218.49, y=25.00, z=264.48], EntityZombie['Zombie'/202, l='MpServer', x=219.50, y=28.16, z=261.93], EntityBat['Bat'/203, l='MpServer', x=210.46, y=31.17, z=264.17], EntityArmorStand['Armor Stand'/204, l='MpServer', x=208.50, y=
[B#349] 83.00, z=264.50], EntityArmorStand['Armor Stand'/206, l='MpServer', x=208.50, y=83.00, z=264.50], EntityShopkeeper['Shopkeeper'/207, l='MpServer', x=208.53, y=85.56, z=256.50], EntityVillageLord['Village Lord'/208, l='MpServer', x=220.34, y=78.00, z=283.85], EntityGuard['Guard'/209, l='MpServer', x=224.31, y=73.00, z=278.51], EntityGuard['Guard'/210, l='MpServer', x=218.70, y=78.00, z=276.30], EntityGuard['Guard'/211, l='MpServer', x=216.41, y=78.00, z=278.48], EntityGuard['Guard'/212, l='MpServer', x=218.78, y=78.00, z=282.34], EntityGuard['Guard'/213, l='MpServer', x=218.51, y=73.00, z=276.76], EntityGuard['Guard'/214, l='MpServer', x=214.37, y=71.28, z=279.44], EntityGuard['Guard'/215, l='MpServer', x=216.55, y=78.00, z=276.77], EntityGuard['Guard'/217, l='MpServer', x=218.54, y=86.00, z=279.29], EntityGuard['Guard'/218, l='MpServer', x=216.50, y=86.00, z=284.50], EntityGuard['Guard'/219, l='MpServer', x=218.30, y=82.00, z=276.58], EntityGuard['Guard'/220, l='MpServer', x=216.30, y=82.00, z=276.30], EntityGuard['Guard'/221, l='MpServer', x=206.50, y=83.00, z=264.92], EntityGuard['Guard'/222, l='MpServer', x=222.75, y=86.50, z=279.44], EntityGuard['Guard'/223, l='MpServer', x=222.53, y=86.00, z=285.63], EntityVillager['Villager'/224, l='MpServer', x=220.50, y=64.00, z=293.50], EntityGuard['Guard'/225, l='MpServer', x=208.47, y=77.00, z=293.51], EntityVillager['Villager'/237, l='MpServer', x=210.59, y=64.94, z=318.49], EntitySentry['Sentry'/749, l='MpServer', x=274.50, y=68.00, z=300.50], EntityHenWyandotte['Wyandotte Hen'/238, l='MpServer', x=220.51, y=66.00, z=315.83], EntitySentry['Sentry'/750, l='MpServer', x=274.50, y=68.00, z=300.50], EntitySentry['Sentry'/751, l='MpServer', x=274.50, y=68.00, z=300.50], EntitySpider['Spider'/240, l='MpServer', x=224.00, y=13.00, z=234.99], EntityVillager['Villager'/241, l='MpServer', x=226.30, y=77.00, z=230.70], EntityHenRhodeIslandRed['Rhode Island Red Hen'/242, l='MpServer', x=231.78, y=74.24, z=238.50], EntityVillager['Villager'/243, l='MpServer', x=232.30, y=76.06, z=247.50], EntityVillager['Villager'/244, l='MpServer', x=233.30, y=74.00, z=253.70], EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/245, l='MpServer', x=237.83, y=76.00, z=242.66], EntityVillager['Villager'/246, l='MpServer', x=243.46, y=73.00, z=254.40], EntityGuard['Guard'/247, l='MpServer', x=234.49, y=82.00, z=255.74], EntityShopkeeper['Shopkeeper'/248, l='MpServer', x=223.73, y=72.56, z=266.53], EntityVillager['Villager'/249, l='MpServer', x=231.73, y=74.00, z=257.37], EntityGuard['Guard'/250, l='MpServer', x=225.20, y=82.00, z=276.56], EntityGuard['Guard'/251, l='MpServer', x=225.47, y=82.00, z=278.26], EntityVillager['Villager'/252, l='MpServer', x=224.60, y=63.00, z=289.51], EntitySentry['Sentry'/253, l='MpServer', x=226.50, y=63.00, z=301.50], EntityChickWyandotte['Wyandotte Chick'/254, l='MpServer', x=227.03, y=63.00, z=289.66], EntityRoosterWyandotte['Wyandotte Rooster'/255, l='MpServer', x=235.30, y=66.42, z=325.69]]
[B#349]  	Retry entities: 0 total; []
[B#349]  	Server brand: fml,forge
[B#349]  	Server type: Integrated singleplayer server
[B#349]  Stacktrace:
[B#349]  	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
[B#349]  	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:124)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by zmaster587** [comment]
Apparently there are some issue with rendering ItemBlocks with fluid capability attached?  Investigating

**Comment by Terpo** [comment]
I'm not 100% sure but this might be a duplicate of this one: https://github.com/zmaster587/AdvancedRocketry/issues/735

**Comment by zmaster587** [comment]
Should be fixed in on here: http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/MC1.11/

**Comment by Terpo** [comment]
If there us no new release til weekend I test the latest jenkins version, TY

**Comment by sandalle** [comment]
Is there an ETA for when the next official build will be on Curse Forge? They don't allow us to use builds which are not in Curse without special permission.
