### ISSUE TITLE
The End issues

### ISSUE THREAD

**Issue by itsCumcast** [zmaster587/AdvancedRocketry#722]
I entered the End and it acted as if I were in space. I was dying from no oxygen and endermen were dying too, and I spawned no where near the main island. The only thing I edited from the config was edit the space station dimension ID to -11.

**Comment by zmaster587** [comment]
which version of minecraft?

**Comment by itsCumcast** [comment]
I am on version 1.10.2, latest version of FTB Beyond. I made the world before adding the mod, which is version 1.10.2-1.2.1. [Here is the file.](https://www.mediafire.com/?dol5dlu510ific4)

**Comment by itsCumcast** [comment]
[endermen suffocating](https://user-images.githubusercontent.com/24724892/27154836-854d964c-5124-11e7-8966-fb21e3291110.png) and 
[myself dying](https://user-images.githubusercontent.com/24724892/27154852-91bbeb68-5124-11e7-8148-5853896849a3.png)

**Comment by zmaster587** [comment]
alright, try removing the "space" planet from the XML config and see if it occurs again.  Or you can use this modified version of the file where I've already done that.

[planetDefs.xml.zip](https://github.com/zmaster587/AdvancedRocketry/files/1078361/planetDefs.xml.zip)

**Comment by itsCumcast** [comment]
I replaced the file, and the End no longer acts as space. I also picked up a few enderpearl drops on the ground. :p Thank you!

**Comment by zmaster587** [comment]
You're welcome!
