### ISSUE TITLE
[1.7.10] Dupe of a rocket after a warp jump

### ISSUE THREAD

**Issue by fogss** [zmaster587/AdvancedRocketry#724]
Orbital station with a rocket on the landing site. We do a warp jump to any planet. We fly to the planet on a rocket. We return on the same rocket. We do a warp jump to any other place, after that the rocket is doubled on the landing site.

**Comment by denwd** [comment]
it is possible to fix it?

**Comment by zmaster587** [comment]
If I can figure out how to replicate it I can probably fix it, though I've not been able to get this issue to occur in my worlds so far.

**Comment by denwd** [comment]
The player arrives at the station on the rocket. Flies with the station to another planet. Sits in a rocket on this planet. He returns on the same rocket back to the station, but for some reason the player himself is not in the rocket, but under it (visually). The rocket sits down, the player rejoins the server and is in the rocket (as if everything is normal), but under that rocket there is another rocket (a copy).

**Comment by denwd** [comment]
Please test only through the server

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
