### ISSUE TITLE
(1.10.2) Players won't respawn on Earthlike planet with planet respawn enabled

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [zmaster587/AdvancedRocketry#725]
I'm using 1.2.0c AR and LV 0.2.3 on 1.10.2 on a Forge server, and I have an Earthlike habitable planet with the config set to enable respawning on other planets, and a player who I gave the planet to respawned on his old camp on Earth instead of the new spawn on the planet, even after he slept on a bed at the planet.
It has breathable air, close gravity to earth and is in the habitable zone.
To be exact, the gravity is 105, the atmosphere is 100, and the distance is 80. It's also dimmapped to a second overworld I created through the SimpleDimensions mod, if that is what's causing the problem.
On every version of AR I've used, the planet respawn never worked no matter whether it was enabled or not.

**Comment by AGiLE-EaGLE1994** [comment]
Also, I dimmapped a SimpleDimensions dimension to the planet I mentioned in this issue and when I select it with the Warp Ship GUI, the client crashes, but the server doesn't.
I made that dimension a TerrainControl world.

**Comment by AGiLE-EaGLE1994** [comment]
Another problem I had with it is that if you select the Dimmapped SimpleDimension world in the warp controller or planet selector, the game crashes.

**Comment by AGiLE-EaGLE1994** [comment]
[crash-2017-06-18_17.54.47-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1083404/crash-2017-06-18_17.54.47-client.txt)
Here we go. Take a look.
What's going wrong here?

**Comment by zmaster587** [comment]
since you opened #743, it might be easier just to move there for relevancy's sake.
