### ISSUE TITLE
Satellite builder not working as expected

### ISSUE THREAD

**Issue by aaronegger** [zmaster587/AdvancedRocketry#726]
Hi it's me again^^

i have maybe encountered another issue.

I tried build an satellite.
I placed an empty satellite and some items as shown in the screenshot at the bottom.
I clicked on build and it seemed that nothing is happening.
But after some moments i got an satellite with an id ID0.

But i didn't get another chip with the id ID0 for the terminal.

I tried to copy it from the satellite but all attempts failed.

Getting the finished satellite back to the satellite builder was also a bit trickty.
I figured out that i first have to try to insert the satellite (but nothing happens here) and then add a satellite chip (in this case an unprogrammed). Afterwards i click on the satellite (at my inventar again) and then it places itself at the satellite slot of the satellite builder (without doing any drag and drop).

I worked with this documentation about building satellites:
http://65.78.115.159:8000/AdvancedRocketry/blocks/SatelliteAssemblingMachine.php

And here is the screenshot of the current setup:
http://mc.aaronegger.de/sc5.png

Server Infos: https://gist.github.com/aaronegger/02bd341a85a8573076d69e7a8684bb90

Did i miss something or is that a bug?

I missed it to thank you for this mod!
I like it very much how you realized the concept of building individual rockets.
There are a lot of good ideas that should be implemented in vanilla minecraft!
Like multiblock machines and the holo projector!

Keep up the good work :)

**Comment by zmaster587** [comment]
It looks like you placed the main components in the first 2 power slots, the optical sensor/mass sensor/etc should be in the Main Component slot ( you can only have 1 per satellite).  Though you shouldn't have been able to get a satellite with ID 0.  That's likely also why you were unable to copy it.

**Comment by aaronegger** [comment]
I am an idiot.
I now understand how building satellites really work.

At the moment i can't confirm if building satellites now really work in Version 1.2.2, because i downgraded to 1.2.1.

But i can confirm that building satellites work in 1.2.1.

**Comment by aaronegger** [comment]
I think all in all it was my failure. Therefore i close this issue.
