### ISSUE TITLE
[1.10.2] Can't construct space stations

### ISSUE THREAD

**Issue by Tkdmaster** [zmaster587/AdvancedRocketry#727]
Mod Version 1.10.2- 1.0.19
Modpack: Galactic Engineers 1.2.2

hey, so I don't seem to be able to create space station on my multiplayer server for some reason. I bullt a simple platform out of cobblestone as a test on my launchpad, scanned it, then built it in the proper machine and got my station chip and package. I did this 3 times, and sent them up on different types of rockets:
1: Rocket with only satellite bay and payload
2: Rocket with satellite bay and payload, and guidance computer with chip copy.
3: Rocket with satellite bay and payload, and guidance computer with chip copy., and seat.

From my understanding of the wiki, any of these should have worked, but none of them appeared when in the space dimension, either by flying there on another rocket with the ID chip, or by flying with the station building rocket itself, all attempts just fall back down to the planet after not landing on any sort of station platform. Upon examination of the return rocket that had the satellite bay and seat, the payload was no longer onboard.

I have also tried using the teleport command to go to the stations, but once there, there is nothing.

Have I overlooked anything I should be aware of?

**Comment by zmaster587** [comment]
Is this in single player or multiplayer?  Also do you have any mods like sponge, MCPC, or cauldron installed?

**Comment by Tkdmaster** [comment]
This is in multiplayer. The server is a SpongeForge based server as well.

spongeforge-1.10.2-2281-5.2.0-BETA-2353

**Comment by zmaster587** [comment]
I've been getting a lot of reports of really bizzare things happening with sponge, so there very well could be some issue.

**Comment by Tkdmaster** [comment]
It was indeed Sponge, after removal of spongeforge, everything is working perfectly.

**Comment by TheGuyRunningSouth** [comment]
Correct me if I'm wrong, since it's been a while since I've built a
station, but doesn't the guidance computer need a planet ID chip so the
station knows where to orbit?

**Comment by tobiasvdp** [comment]
No, just the station id chip. The "orbiting" of the spaceship around a planet is just an illusion, It's all the same dimension.

**Comment by zmaster587** [comment]
@TheGuyRunningSouth The station is hardcoded to orbit the planet it's initially launched from.  The idea is that they are much heavier than satellites so can't be moved as far.  They can also be moved later with a warp drive though.

**Comment by LXGaming** [comment]
After some testing we found that the issue is due to the chunks not being loaded when the satellite is sent up to space.

**Comment by JoeSGT** [comment]
I'm having the same issue
here is what i am on 
Sponge - 7.0.0-BETA-2729
Forge - 14.23.0.2529
Advanced Rocketry - 1.12.2-1.2.5a
LibVulpes - 0.2.6
here more information

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
