### ISSUE TITLE
[ENHANCEMENT] Dev Builds on Github or Jenkins

### ISSUE THREAD

**Issue by TheAmazingSpy** [zmaster587/AdvancedRocketry#73]
So I was wondering if we could get dev builds because, we might want to test them out. This could possibly help this mod. And I love this mod btw

**Comment by zmaster587** [comment]
As of right now all the dev builds have been going on curse (which is why there's a new release every day or two), but yeah, I am in the process of getting a build server to host dev builds on, setup has just been taking a bit of time.

**Comment by TheAmazingSpy** [comment]
Nice to know :) , but when is the next major release (that adds blocks or items)

**Comment by DarkGuardsman** [comment]
@dmodoomsirius will be working on this issue

**Comment by dmodoomsirius** [comment]
that i will. I need to get everything set up on my end then it will be easy to do.

**Comment by zmaster587** [comment]
http://65.78.115.159:8080/
