### ISSUE TITLE
[1.10.2] Oxygen vent won't turn on.

### ISSUE THREAD

**Issue by Tkdmaster** [zmaster587/AdvancedRocketry#730]
After setting up a space station, I placed down a power source, oxygen vent ontop of it, C02 scrubbers on both sides with cartridges, and gave it a redstone signal to power on, but nothing happens. Am I missing something?

here is a picture of the setup with level set to on.
[http://i.imgur.com/XzPuPtd.png](url)

**Comment by zmaster587** [comment]
Only thing I can think of is that the room may not be sealed for some reason.  Also can you verify that the machine actually has power in the buffer?

**Comment by Tkdmaster** [comment]
The machine definitely has power in the buffer.

Here's some screenshots of the room:
[http://i.imgur.com/PjaDIjS.jpg](url)
[http://i.imgur.com/LADOkrp.jpg](url)
[http://i.imgur.com/NMaxik6.png](url)

The walls are made of structural glass from Mekanism, so it can be a bit hard to see all the edges, but I assure you the walls are solid :)

The airlock area is partly made out of chisel slabs,a s you can see in the picture, would that cause it? Also, the airlock doors should create as seal, yes?

**Comment by tobiasvdp** [comment]
you can always lookup the chisel block registry name (f3 + h I think to enable debug tags, then hover over the item) name and add it to the config. But they would also seal when you leave half the block horizontaly open to air
