### ISSUE TITLE
[Request] Make Oxygen vents quieter

### ISSUE THREAD

**Issue by Tkdmaster** [zmaster587/AdvancedRocketry#731]
Apologies for the post-after-post, but would like to make a small request.

Can we place get a config setting to make oxygen vents quieter? Pretty please? :) Or, at least make them affected my the muffler mod block?

**Comment by zmaster587** [comment]
I may actually just straight up redo the sound tbh, the high pitch hiss doesn't really suit it anyway.  But yeah, I can do that

**Comment by DietmarKrause** [comment]
From my point of view the oxygen vent needs something that tells us, if it is working or not. Until now the one and only thing i found is the sound.

**Comment by zmaster587** [comment]
Definatly not removing the sound, just gonna change it to be less annoying.  But there's two other ways I can think of off the top of my head to check if it's working.  There's the gas detector block, which emits a redstone signal based on the prescence or lack of an atmosphere.  Other option is just to have torches.  The torches will go out if there's no air, but you'd need to relight them manually every time.
