### ISSUE TITLE
Unmanned Vehicle Assembler and Fluid Unloader

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#733]
Hi, 
I have a few problems with the Unmanned Vehicle Assembler and the Rocket Fluid Unloader. I assume that the sole purpose of the Unmanned Vehicle Assembler is for gas mining missions.

1) When a rocket returns and unloaded it cannot be relaunched, if it is disassembled and rebuild then the fuel loads and the rocket can be launched again.

2) When linking the Rocket Fluid Unloader to the Unmanned Vehicle Assembler it does not work, whereas the Fuelling Station does. When the Rocket Fluid Unloader is linked directly to the rocket then it does work and unloads the rocket.

3) The redstone signals emitted from the rocket fluid unloader is odd, When there is no rocket then the redstone is a blob and active, then the rocket has been unloaded the redstone signal is off and the redstone is a line.

4) A cosmetic error is that when the rocket is unloaded the tanks are shown as full, except when looking at tank contents and then it empties both in the window and the tank.

I don't get the coloured buttons in the interface are these supposed to do something?

![image](https://user-images.githubusercontent.com/4198031/27252103-e2d812b4-5355-11e7-8380-1ae4d3edb913.png)

![image](https://user-images.githubusercontent.com/4198031/27252107-0441e448-5356-11e7-8197-d67d87d39472.png)

**Comment by tobiasvdp** [comment]
1. Had same, but its not code related. The entity shifts a bit and gets stuck in de structure blocks. If you leave a gap of 1 around the ship they will be able to relaunch.

**Comment by duncanwebb** [comment]
Many thanks, took me a while to test as the top also needs a block clear, so I add a construction block and remove it before scanning and building. It's a bit difficult to figure this out especially as it works when initially built.

Also when linking the fuelling station and the rocket fluid unloader to the assembler it works first time but they have to be re-linked before it returns. I'm shuttling two rockets from the same assembler so this might be the cause of some problems. I don't think it is with the linking.

**Comment by duncanwebb** [comment]
This is my redstone automation to relaunch the rocket.

![image](https://user-images.githubusercontent.com/4198031/27260129-4d5f952a-5424-11e7-9ecd-a2dc6398bca5.png)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
