### ISSUE TITLE
How is the planet selector ment to be used?

### ISSUE THREAD

**Issue by aaronegger** [zmaster587/AdvancedRocketry#736]
Hi,

i don't understand how i can use the planet selector within a rocket.

I built the rocket with engines (about 30), fuel tanks (about 3 stacks), a seat, a guidance computer and placed a planet id chip after building the rocket in guidance computer.

I clicked on select destination, but i only get the earth and moon for selection:

mc.aaronegger.de/fromRocket1.png
mc.aaronegger.de/fromRocket2.png
mc.aaronegger.de/fromRocket3.png

I tried clicking on planet list and the up button, but they seem to do nothing here.

But i saw that there is a planet selector block.

I built one and got the same view, but now with all planets and the buttons were working too:

mc.aaronegger.de/fromPlanetSelector.png

I built the rocket again with the Planet Selector. But it is not accessible at the finished rocket.

And now here is my question. How can i select another planet, except from the earth and the moon?

**Comment by aaronegger** [comment]
I should mention, that the up button works if I double click the moon.

But then i can only select between the earth and the moon again.

**Comment by DietmarKrause** [comment]
as far as i remember it correctly with a standard moon rocket from overworld you always can only go to moon and earth. For everything else you need to build a space station at first put a warp drive on it and only then you can "warp" your space station (with landed moorn rocket on it) to another planet. Then land on this planet with your moon rocket. 
Sadly the "how to" video on the curse page isnt up-to date anymore. Almost everything has changed....

**Comment by aaronegger** [comment]
Ok now I understand how things work! Thank you for replying :)
It has some positive effects that there is no complete documentation of this mod.
In contrast to other mods, i don't run through the mod to discover all features.

It now takes some time to reveal all the new things this mod brings with it :D

**Comment by zmaster587** [comment]
Sorry for taking so long to reply, thanks for helping out @DietmarKrause!  And glad you got things sorted out @aaronegger.  Sorry for the lack of docs, glad you can put a positive spin on it though.
