### ISSUE TITLE
World is null upon rocket land?

### ISSUE THREAD

**Issue by RussianSanity** [zmaster587/AdvancedRocketry#737]
I just looked over at my console window for my pack using your mod (latest released version) for 1.7.10 mc
and saw this error pop up.
https://gyazo.com/300dfd4689e1eba5e314b2b30d6f70fc
Any idea how to fix this or know what it means?

**Comment by RussianSanity** [comment]
1.7.1.0-1.0.19b.jar is the version I am running.

**Comment by zmaster587** [comment]
There was an issue where the reference to world would be null when the rocket lands, but rather than letting the game crash I printed a debug message with a bit of info. I've not been able to replicate it myself yet though either.   Still no definitive idea of how it happens though my best guess is interaction from something like thermos or sponge.

It's basically saying the tile exists at 0,0,0 and is valid in the world.  I'm regretting not sticking a stack trace printout.

Only negative effect you should see in the world from this directly is the rocket might not link to the pad it landed on when the message shows up.

Also would it be possible to list the mods and version of forge that you're running?  Also does this happen every time a rocket lands on a station or just sometimes?

**Comment by RussianSanity** [comment]
Advanced Rocketry by zmaster587
AE2 Stuff by bdew 
Agricraft by InfinityRaider 
AOBD by ganymedes01
AOBD Singularities by RCXcrafter
Apple Milk and Tea 2 by RazzleberryFox 
Applied Energistics 2 by AlgorithmX2 
Animus by TeamDman and Saerethlb 
Aroma1997's Dimensional World by Aroma1997 
Automagy by Tuhljin 
Avaritia by SpitefulFox 
Avaritia Addons by WanionCane 
Better Questing by FunWayGuy 
Better Questing: Standard Edition by FunWayGuy 
BiblioCraft by JDSinclair 
BiblioWoods (BiomesXL) by JDSinclair 
BiblioWoods (Forestry) by JDSinclair
BiblioWoods (Natura) by JDSinclair 
Big Doors by jaquadro 
Big Reactors by ErogenousBeef 
Binnie Mods by Binnie567 
Birds Nests by cleverpanda714 []
Blood Arsenal by Arcaratus 
Blood Magic by WayofTime 
Botania by Vazkii 
Carpenters Blocks by Syntaxial 
Chisel by tterrag1098, Drullkus, and Minecreatr 
Chisel Tones by TehNut 
ComputerCraft by dantwohundred 
Cooking for Blockheads by BlayTheNinth 
Cosmetic Armor Reworked by ZLainSama 
Custom NPCs by Noppes 
DecoCraft 2 by RazzleberryFox 
Dense Ores by RWTema 
Enchanting Plus by Darkhax 
Enchiridion by joshiejack 
Ender IO by CrazyPands_MC 
Ender IO Addons by Henry_Loenwind 
Ender Storage by chicken_bones 
EnderTech by CarrotCodes 
EnderZoo by CrazyPants_MC 
Eternal Singularity by KingWealthyturtle
EvilCraft by kroeser 
Extra BiomesXL by Annysia 
Extra Cells by DrummerMC 
ExtraTiC by JeanGlassmaker
Extra Utilities 2 by RWTema 
Fairy Lights by pau101 
Forbidden Magic by SpitefulFox 
Forestry by SirSengir 
Gadomancy by makeoo 
Gany's End by ganymedes01 
Gany's Nether by ganymedes01 
Garden Stuff by jaquadro 
Gendustry by bdew 
Grapple Mod by Yyon 
Grimoire of Gaia by Silentine 
Growthcraft Community Edition by Alatyami 
Grue by Shinoow 
Hardcore Ender Expansion by chylex 
Hats by iChun 
Iguana Tinker Tweaks by bonusboni
INpure Core by INpureProjects 
Inventory Pets by Purplicious_Cow 
Inventory Tweaks by Kobata 
Iron Backpacks by gr8pefish 
Iron Chest by progwml6 
Jabba by ProfMobius 
Jaffa Foods (A HarvestCraft Addon) by Murdy007 
Magical Crops by Mark719 
Magical Crops Armoury by Mark719 
Magical Crops Decorative by Mark719 
Magic Bees by MysteriousAges
Malisis Doors by Ordinastie 
Mariculture by joshiejack []
Minecraft Comes Alive by WildBamaBoy
Minefactory Reloaded by skyboy026
Mekanism by aidancbrady 
Mekanism Generators by aidancbrady
Mekanism Tools by aidancbrady 
Minechem by jakimfett 
Modular Powersuits by MachineMuse 
Morpheus by Quetzi 
MrCrayfish Furniture Mod by Mr_Crayfish 
Natura by mDiyo 
NEI Addons by bdew 
NEI Integration by tonius111 
Nether Ores by skyboy026
Nodal Mechanics by Shukaro 
No More Recipe Conflict by Oliv1er 
Not Enough IDs by fewizz 
Not Enough Items by chicken_bones 
Not Enough Resources by Way2muchnoise 
Not Enough Thaumcraft Tabs by fewizz 
OpenBlocks by OpenMods 
Pam's HarvestCraft by MatrexsVigil 
Platforms by ShetiPhian
PortalGun by iChun []
Project Red - Base by Mr_TJP 
Project Red - Compat by Mr_TJP 
Project Red - Integration by Mr_TJP 
Project Red - Lighting by Mr_TJP 
Project Red - Mechanical by Mr_TJP 
Project Red - World by Mr_TJP
RailCraft by CovertJaguar 
Random Things by lumien231 
Recurrent Complex by Ivorforce 
Redstone Armory by TehNut 
Redstone Arsenal by TeamCoFH 
Reliquary v1.3 by P3pp3rF1y 
RFTools by McJty 
Sanguimancy by Tombenpotter 
Secret Rooms Mod by AbrarSyed 
Simple Labels by insaneau
Solar Expansion by TedTheRusSB624 
Soul Shards - The Old Ways by SgtPunishment 
Starminer by あるべ 
Steves Addons by hilburn 
Steves Factory Manager by Vswe 
Storage Drawers by jaquadro 
Storage Drawers (Forestry) by jaquadro 
Storage Drawers (Misc) by jaquadro 
Storage Drawers (Natura) by jaquadro 
Tails by KitsuneKihira 
Tainted Magic by yorkeMC 
ThaumCraft Inventory Scanning by BlayTheNinth 
ThaumCraft Node Tracker by Dyonovan 
Tinkers Construct by mDiyo 
Technomancy by Theflogat 
ThaumCraft by azanor 
ThaumCraft Mob Aspects by Parker8283 
ThaumCraft NEI Plugin by DjGiannuzz 
Thaumic Energistics by Nividica 
Thaumic Exploration by nekosune
Thaumic Horizons by TheKentington 
Thaumic Tinkerer by nekosune
The Spice of Life by squeek502 []
Thermal Dynamics by TeamCoFH
Thermal Expansion by TeamCoFH 
Thermal Foundation by TeamCoFH 
Thermal Singularities by WanionCane
TiC ToolTips by Squeek502
Tinker IO by gkbm2011
Totemic by ljfa 
TrainCraft by Mrbrutal 
Traveller's Gear by BluSunrize
Universal Singularities by KingWealthyturtle 
Waila by ProfMobius 
Waila Plugins by tterrag1098 
Wawla by Darkhax 
Wireless Crafting Terminal by TheRealp455w0rd 
Witchery by Emoniph 
Witching Gadgets by BluSunrize []
ZTones by riciJak 

forge version: forge-10..13.4.1614
