### ISSUE TITLE
Space stations not appearing

### ISSUE THREAD

**Issue by RussianSanity** [zmaster587/AdvancedRocketry#738]
Been having an issue lately where if you make a space station, send it off in the rocket to go to the proper dimension to be created... it will not appear or even place the space station at all. If you go up in a rocket and try to descend it will take you down to the minimum level and spawn you back at the top.

Only way I've gotten this to work without losing your rocket is hopping in creative, hopping out of the rocket as it is descending, making a huge platform to catch the rocket and when the rocket is spawned back up to max height it will descend down onto the platform. 

Any idea on how to fix this?

- On latest release for 1.7.10 mc: 1.7.1.0-1.0.19b.jar

**Comment by zmaster587** [comment]
When it takes you to the space dimension, what are your coordinates?
Also can you send a copy of the advRocketry/temp.dat file?

**Comment by RussianSanity** [comment]
Not modified at all on multiplayer.
I'm not too sure on the ID number of the station.. we've had this error pop up only once that I know of.

This is the crash report (I believe this may or may not be related to this or not) of a player who crashes when tping between dimensions from planet to overworld... might give some insight?
https://pastebin.com/1MSCN4M2

[temp.zip](https://github.com/zmaster587/AdvancedRocketry/files/1116085/temp.zip)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
