### ISSUE TITLE
Crash while going to the moon on a server

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#74]
http://pastebin.com/7HFkJHJZ
Worked fine on ssp but the client crashes when joining the world

**Comment by zmaster587** [comment]
Forgot to set isNativeDimension for true in constructor... applying fix

**Comment by zmaster587** [comment]
see if 0.4.10 fixes?  https://www.dropbox.com/s/nzaqj5irv142sh8/AdvancedRocketry-0.4.10.jar?dl=0

**Comment by wormzjl** [comment]
gonna test this soon

**Comment by wormzjl** [comment]
seems to be fixed
