### ISSUE TITLE
conflict with JumpPad++ Failed to connect to server 1.7.10 + Russian language on the client

### ISSUE THREAD

**Issue by SvEgiiVEteR** [zmaster587/AdvancedRocketry#740]
AdvancedRocketry-1.7.10-1.0.19 (b)
JumpPad++ 2.3.8
Failed to connect to server  
`/ERROR] [FML/]: Failed to connect to server: there are 2 missing blocks and items
/DEBUG] [FML/]: Missing list: [JumpPad++:Launch Pad, JumpPad++:Launch Pad]
`
I can not go on your server
The bug is shown when 2 modes together, on detachment all ok.
log:
server
https://gist.github.com/3e4a407a8d56c3a2b2e4d8bc52accdb7
client
https://gist.github.com/2efa8923b52e0b69d776bf1dbb240ab6

`/ERROR] [FML/]: Failed to connect to server: there are 2 missing blocks and items
/DEBUG] [FML/]: Missing list: [JumpPad++:Launch Pad, JumpPad++:Launch Pad]
`

**Comment by zmaster587** [comment]
Are any blocks set to false in the "JumpPad++.cfg" on either the client or server?

**Comment by SvEgiiVEteR** [comment]
@zmaster587 Yes checked. equal.
the weird thing is that JumpPad++, there is no Launch Pad
looking in NEI
now it will show the configs. maybe they matter....

**Comment by SvEgiiVEteR** [comment]
advancedRocketry
https://gist.github.com/71f57b1794f25c1b3fea0d37ad06cc91
JumpPad++.cfg
https://gist.github.com/12f72cd15079bf7f41a8ee87b4e9e45d

**Comment by zmaster587** [comment]
What if you remove neiintegration, UnicodeFontFixer, and liteloader?

**Comment by SvEgiiVEteR** [comment]
@zmaster587 left the current 3 mod. not what to change, also swears...
win 10 java 8.131

**Comment by zmaster587** [comment]
I just wanted to make sure, because in the logs you gave me before you did have liteloader installed and I was unsure if you tested without it.
(https://gist.github.com/SvEgiiVEteR/3d33e744ec7515797a3fff0cf1fb10d9 line 215)
(https://gist.github.com/SvEgiiVEteR/2efa8923b52e0b69d776bf1dbb240ab6 line 943)
You do appear to be running the same forge version I'm testing with so that seems ok.

Does the issue persist if you reset the world on the server?

**Comment by SvEgiiVEteR** [comment]
@zmaster587 I tried and with LL and without
Now, as I wrote above. Current with 3 modes.
The problem has not disappeared .....

**Comment by zmaster587** [comment]
Does the issue persist if you reset the world on the server? If you go into a single player world do the jump pad blocks show up in the creative menu?

**Comment by SvEgiiVEteR** [comment]
I came across different bugs...even the stupid and illogical... but this conflict won it.....

and Yes forgot to write. map every time I delete at server startup.
and Kaie blocks exactly to look for in a single world?
Launch Pad is definitely not..

**Comment by zmaster587** [comment]
The launch pad is some internal name, it won't show up in world, I'm just curious if any of the launch blocks are showing up in the creative menu?

**Comment by SvEgiiVEteR** [comment]
checked all the blocks are put into the world

hm...
I noticed one strange
dump
block
JumpPad++:Launch Pad,412,true,null,**T145.pads.blocks.BlockPad**
JumpPad++:Light Sensor,413,true,null,**T145.pads.blocks.BlockLightDetector**
item
JumpPad++:Launch Pad,412,true,JumpPad++,**T145.pads.blocks.BlockPadItem**
JumpPad++:Light Sensor,413,true,JumpPad++,**net.minecraft.item.ItemBlock** <<<<<<<<<

**Comment by zmaster587** [comment]
The light sensor doesn't have variations based on metadata, so it can afford to use the default itemblock, so that seems normal.  Can you check to see if a single player world have all 4 of those entries as well?

**Comment by SvEgiiVEteR** [comment]
@zmaster587 
checked they are the same I wrote above about the SP
now checked in MP
all the same
JumpPad++:tile.pad.name,165,true,null,T145.pads.blocks.BlockPad
JumpPad++:Light Sensor,166,true,null,T145.pads.blocks.BlockLightDetector
and
JumpPad++:tile.pad.name,165,true,JumpPad++,T145.pads.blocks.BlockPadItem
JumpPad++:Light Sensor,166,true,JumpPad++,net.minecraft.item.ItemBlock

of course I had to remove your mod. what would go in MP

**Comment by zmaster587** [comment]
So the first entry was from single player with AR and Jumppad in at the same time?

**Comment by SvEgiiVEteR** [comment]
@zmaster587 
Yes
and the second current with the Jumppad without AR. because MP

**Comment by SvEgiiVEteR** [comment]
while I was testing the SP now. I went with MP.
and now noticed that the MP fell with such a failure..

https://gist.github.com/afe14fdb9ef0fd7f543807c9a114720c
like wine around in the JumpPad

**Comment by zmaster587** [comment]
So then the client definatly has the blocks loaded when trying to connect to the server.  Usually if the client has blocks the server does not have, it still lets you join.

Would it be possible to zip an instance of the server and client (mods and config folders should suffice) where this issue occurs?  I tried pulling AR, libvulpes, jumppads++ from curse and had no problems connecting to a server with my setup.

**Comment by zmaster587** [comment]
Can you send it anyway so I can be 100% sure all of the files are identical.  It would also allow me to verify no corruption is involved

**Comment by zmaster587** [comment]
Also that crash appears to be caused by a cow getting on top of a booster pad, but the program does not check to see if it's a player or not and just assumes it's a player anyway

**Comment by zmaster587** [comment]
I suppose if you like I can upload a copy of the instance that I verifed works on my end for you to try if you'd prefer that.

**Comment by SvEgiiVEteR** [comment]
Yes, I can send all. wait)

**Comment by SvEgiiVEteR** [comment]
@zmaster587 
I can't understand. just went to the server.
start close again and AGAIN will NOT LET me.
hmm..I think it's in the RUSSIAN language.

1 Russian language is the gateway to the server.
changed to ENG again will not let me.
closed the game, launched the and go - with ENG joined the server.

checked not once.
blame the Russian translation of the game..... if not difficult to check. BUT the game is required to restart.

**Comment by zmaster587** [comment]
Let me check something... I wonder if it's some locale problem

**Comment by SvEgiiVEteR** [comment]
@zmaster587 I checked сеqчас 10 times with ENG all is well.
I think your mod is probably trying to move the Launch Pad in this fashion.
why?

because when I created a dump file this

JumpPad++:Launch Pad,412,0,false,Acceleration Pad
JumpPad++:Launch Pad,412,1,false,Annihilation Pad
JumpPad++:Launch Pad,412,2,false,Aqua Pad
JumpPad++:Launch Pad,412,3,false,Ballistic Pad
JumpPad++:Launch Pad,412,4,false,Booster Pad
JumpPad++:Launch Pad,412,5,false,End Pad
JumpPad++:Launch Pad,412,6,false,Impact Landing Pad
JumpPad++:Launch Pad,412,7,false,Incineration Pad
JumpPad++:Launch Pad,412,8,false,Jump Pad
JumpPad++:Launch Pad,412,9,false,Jump Pad+
JumpPad++:Launch Pad,412,10,false,Jump Pad++
JumpPad++:Launch Pad,412,11,false,Portal Pad
JumpPad++:Launch Pad,412,12,false,Regeneration Pad
JumpPad++:Launch Pad,412,13,false,Slow Pad
JumpPad++:Launch Pad,412,14,false,Speed Pad
JumpPad++:Light Sensor,413,0,false,Light Sensor

all Launch Pad was translated as "стартовая площадка" BUT no JumpPad perevodu there should be a Launch Pad
and this game will not let me on the server, I think that these things not because of the translation..

**Comment by zmaster587** [comment]
Launch pad is the internal name of the block, if it changes to anything else, the server may not recognise it.  Each mod is also responsible for its own blocks.  AR does not change Jump Pad's block names or vice versa. 
 I can also confirm I can replicate the issue when changing the language though, so now I can see about nailing an exact cause down.

**Comment by SvEgiiVEteR** [comment]
it is strange that without your mod, no problems with the Russian language in this mod is not shown.
I just know that you also have block Launch Pad. I think it's no coincidence.

**Comment by zmaster587** [comment]
I think you may be on to something with that, I have also noticed that with AR removed jumppad++ no longer registers jumppad++:Launch Pad

**Comment by SvEgiiVEteR** [comment]
If it was not difficult to change the name of the block and translate your Launch Pad, then it would be possible to check for the sake of interest what will happen ...

**Comment by zmaster587** [comment]
That's what I'm in the process of doing.  Though I still am trying to figure out how a translated name got used at all.  I'm registering it with a hardcoded constant string.

**Comment by SvEgiiVEteR** [comment]
@zmaster587 Well, maybe the reason is not in your mod.
Maybe the second mod tries to translate itself. Looking for translation Launch Pad finds from you and translates.

**Comment by zmaster587** [comment]
I tried changing the internal name of the Launch Pad in AR from "pad" to "pad2", now i get this when i try to connect:
[22:12:07] [Netty Client IO #2/INFO] [FML]: Found a missing id from the world JumpPad++:tile.pad.name
[22:12:07] [Netty Client IO #2/INFO] [FML]: Found a missing id from the world JumpPad++:tile.pad.name

**Comment by SvEgiiVEteR** [comment]
I think I need to replace the "Launch Pad" myself with something else, for example LauncherPad

**Comment by zmaster587** [comment]
I tried replacing it with "LeWeirdBug" in the lang and I get this:
[22:21:33] [Netty Client IO #2/INFO] [FML]: Found a missing id from the world JumpPad++:LeWeirdBug
[22:21:33] [Netty Client IO #2/INFO] [FML]: Found a missing id from the world JumpPad++:LeWeirdBug

**Comment by zmaster587** [comment]
I went and changed the internal name of the block to match the registry name and updated the lang files.
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/master/20/changes
Appears to fix the issue.

**Comment by SvEgiiVEteR** [comment]
@zmaster587 I confirm the problem has disappeared)
Thank you very much
