### ISSUE TITLE
Titanium Ore Dictionary breaks TechReborn progression

### ISSUE THREAD

**Issue by Stapleton** [zmaster587/AdvancedRocketry#741]
I wouldnt really consider this a bug but more of an enhancement.

If you don't know this, Tech Reborn has Titanium, but the Titanium in TR is supposed to be difficult to get and makes end game TR rather difficult because of how much Bauxite a player needs to get enough Small Piles of Titanium to progress. Advanced Rocketry on the other hand, has Rutile ore which is just Titanium in its ore form. Having AR Titanium be in the same ore dictionary as TR Titanium, kinda ruins Tech Reborn progression in a sense since instead of having to grind out the Bauxite, you can just mine out the Rutile ore and you're done. 

As for my question. Is there any possibility to add in a check for TechReborn and then not register the Advanced Rocketry Titanium Dust/Ingot/Nugget/Block in the Titanium ore dictionary?

In my modpack, I am working on using CraftTweaker to fix this but there are some machines and mods that don't change their recipes when the ore dictionary changes. (Ex: AR Titanium Nuggets cannot be made into TR Ingots unless you do it through the Thermal Expansion Compactor. This is a recipe I cannot remove or fix purely with CraftTweaker and ModTweaker, or until ModTweaker gets compatibility for Thermal Expansion.)

**Comment by zmaster587** [comment]
I'm not really sure that's something that doable unless Tech Reborn also has titanium oredictionaried to something else because most of the recipes in AR are generated from ore dictionary entries.
  If you really wanted to you could disable AR's titanium ore generation, though it may make it hard for players to find enough.

**Comment by OscarXcore** [comment]
Alrighty. I will suggest to the Tech Reborn devs that they put their ores in ore:(form)TR(metalname) or something. Thanks anyways!

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Stapleton** [comment]
This is not from what I can remember. My apologies for not closing this sooner. Granted if this continues to be an issue, it now can be fixed with Late Oredict Removal by CodeTaylor. Thanks anyways!
