### ISSUE TITLE
Terrain Control SimpleDimensions world causes crash when selected

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [zmaster587/AdvancedRocketry#743]
https://github.com/zmaster587/AdvancedRocketry/files/1083404/crash-2017-06-18_17.54.47-client.txt
Here's the crash log.
When I select the world in the Warp Controller or planet selector menu, the game crashes clientside.
It's a SimpleDimensions world with the TerrainControl world type that's been dimmapped to an AR planet in a nearby solar system to Earth.
TerrainControl is a separate mod from SD which has its own, customizable world type.

**Comment by zmaster587** [comment]
would it be at all possible to send a copy of the planetDefs.xml as well as the id of the planet you're trying access?

The odd thing about this is that it's an NPE getting a star, not a planet, that's causing the issue.

**Comment by AGiLE-EaGLE1994** [comment]
Here you go: 
[planetDefs.txt](https://github.com/zmaster587/AdvancedRocketry/files/1096065/planetDefs.txt)
I turned it into a txt file so it would upload.
The planet's dim ID is 30001. SimpleDimensions IDs start at 30000.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
