### ISSUE TITLE
Rockets sent to Docking Pads in the same dimension disappear.

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#744]
Rockets sent to Docking Pads in the same dimension disappear. I have sent a rocket 1 to a docking pad about 20 blocks away and rocket 2 to a docking pad about 430 blocks away and rocket 3 to a docking pad in a difference dimension.

Rocket 1 had an guidance computer, an inventory, 6 tanks and 2 engines, when up and disappeared for ages - landed after about 1 hour or so (human time)
Rocket 2 had a guidance computer, a pressurised tank, 6 tanks and 2 engines, when up and disappeared and has not returned after a couple of days (human time)
Rocket 3 had a guidance computer, 6 tanks and 3 engines and landed on the space station almost immediately.

From what has been discussed in the forum the first two rockets should had landed on their destination docking pads and I guess that they should be quick.

I have recorded the cases and more if you need more information.

Thanks and thanks again for this outstanding mod.

**Comment by zmaster587** [comment]
Rockets 1 and 2 should take the same amount of time as rocket 3, there's no mechanism that does anything different if the destination planet is the same, it's the same code executed.

I was thinking possibly something involving unloaded chunks, but rocket 1 should land in a loaded chunk.  I'll investigate it.

**Comment by duncanwebb** [comment]
Hi,

Then it is strange, if the destination needs to be chunk loaded it could explain it for rocket 2, I don't think it was for rocket 2, however rocket 1 and 3 were always chunk loaded. So from what you have said rocket 1 should have landed fairly quickly after launch.

I have a video that shows what I was doing to explain it to others as it is a bit complex for first timers. [https://youtu.be/1TO1meq9fno](url) I'll redo the video if you think it is not correct.

![image](https://user-images.githubusercontent.com/4198031/27420188-fcd63434-5724-11e7-932c-843a0eafd5cf.png)

The space station was chunk loaded
![image](https://user-images.githubusercontent.com/4198031/27420416-1457831e-5726-11e7-853f-04752324be4b.png)

Thanks

**Comment by IMarvinTPA** [comment]
I have this problem too, 1.12.2-1.2.6-27 on forge 2555.
If you catch a ride on the rocket after you launch it, it goes to y=1k, hovers until it runs out of fuel and falls back to the pad.

IMarv

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
