### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by llloyd4** [zmaster587/AdvancedRocketry#745]
Well, sort of. Refined Storage autocrafting upchucked massively when it came to Mekanism steel and Refined Storage silicone. I had setup my autocrafting furnace to input one sand and get out one silicone. After installing the mod that changed to one sand for one silicone ingot. Same with every other recipe for silicone. Though, through trial and error, I figured out that a silicone ingot can be substituted for the silicone and I changed both the autocrafter pattern on the furnace so Refined Storage would recognize it was finished making silicone, and had to change the autocrafting recipe on the Solderer to accept one silicone ingot in to get one printed silicone. I had to do something similar so that the autocrafter would know that it had gotten the steel from autocrafting it though Mekanism. The final step was one steel dust in and get one steel ingot out and the autocrafter sat there waiting to get the steel and would not complete until I changed the recipe to be one AR steel ingot out then it started to work again.

**Comment by dmodoomsirius** [comment]
if this issue still occurs please comment and reopen the issue.
