### ISSUE TITLE
Observatory not working

### ISSUE THREAD

**Issue by Tronzoid** [zmaster587/AdvancedRocketry#746]
How do I use observatory? it does not seem to be working even after removing and replacing blocks on structure, when I use it, the data page is blank apart from range details and power, how do I fix this?

**Comment by DietmarKrause** [comment]
perhaps i can help: the observatory needs "data" from the satellite mission as does the astrobody thingy.  Upon construction it should have at least one (better all 3) data input blocks. You can select an asteroid (only small ones until now i believe) and write this data to chip. This "writing" only works during the night. If you switch the oberservatory on it will open up in the night and you can see the lense. Then and only then you can write the chip, which reads 0/1000 in all data. that is normal. Put that chip in the astrobody thingy afterwards to analyze the data.

**Comment by dmodoomsirius** [comment]
is this still a issue? if so please comment and reopen it.
