### ISSUE TITLE
Asteroid xml configurations generate negative cobble

### ISSUE THREAD

**Issue by pyure** [zmaster587/AdvancedRocketry#748]
Some configurations may (randomly) generate negative cobble amounts, resulting in an itemstack of -X cobblestone (which promptly vanishes if you try to pick it up)

At a guess, I'm suspecting "richness" values greater than 1.

This configuration can reproduce the problem.

```
   	<asteroid name="High Bothium" distance="100" mass="325" massVariability="0.5" minLevel="0" probability="0.75" richness="1.2" richnessVariability="0.3">
		<ore itemStack="minecraft:iron_ore" chance="25" />
		<ore itemStack="libvulpes:ore0 10" chance="5" />
	</asteroid>
```

**Comment by dmodoomsirius** [comment]
Is this still a issue?
