### ISSUE TITLE
Various terraformer issues (UI + Particles)

### ISSUE THREAD

**Issue by rkane31174** [zmaster587/AdvancedRocketry#749]
mod version 1.2.2 for minecraft 1.7.10
I have the terraformer enabled in the config.

When I access the UI, it is partially buried under my inventory. This makes it hard to see if the machine is running and what the atmosphere level is. This can probably be solved by having the terraformer hide the inventory like other machines.

The other issue is that when the terraformer is active, the normal particles you see when you break a block do not appear. To be more specific, they are clear and ghostly and very hard to see.

Neither of these issues are game breaking and are of relatively low priority.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
