### ISSUE TITLE
[1.7.10]Server Crash when lauching rocket

### ISSUE THREAD

**Issue by Niuttuc** [zmaster587/AdvancedRocketry#751]
On a 1.7.10 server, we got a crash when a player tried to lauch his rocket when he reached space.
On the second try, same thing, except he made the server crash each time he tried to reconnect to the server.
For me, ressembles https://github.com/zmaster587/AdvancedRocketry/issues/720 ?
https://gist.github.com/Niuttuc/f836b31fa1b420525e7d30b4aacb3c07

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
