### ISSUE TITLE
GUI's Are Behind JEI Items

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#752]
Is it possible for the mod to integrate with JEI and either push the JEI items over or appear on top? It becomes a bit difficult to work within some GUI's, mainly the Guidance Block when setting a rocket's destination.

This happens across 1.10 and 1.11

Thank you!
Darkosto

**Comment by dcbartlett** [comment]
Confirmed.  I'm seeing this as well with 1.1.7 Mod Version.  This however happens with other mods, and therefor MAY be something that JEI should fix...

**Comment by dmodoomsirius** [comment]
Darkosto is confirming if this is still a issue on stream as of this post.

**Comment by dmodoomsirius** [comment]
Darkosto confirmed on stream that this issue is fixed so i am closing this issue.
