### ISSUE TITLE
Allowing Thruster Controls or Fuel Usage Based on Gravity

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#753]
Is there a possibility of allowing fuel usage to be connected to gravity? Currently, the amount of fuel used on the moon is the same as the Earth. I believe there's two ways to handle this:

Allow thruster controls so you don't use the same amount of thrust to leave a low gravity planet as you would a higher gravity planet.

Or, allowing us to set the amount of fuel usage per dimension.

Would this be something you would be interested in adding? :)
Darkosto

**Comment by dcbartlett** [comment]
Check the advRocketry.cfg file.  Mine has the below.
```
# If true planets with higher gravity require more fuel and lower gravity would require less
    B:gravityAffectsFuels=true
```
MC Version:  1.10.2
Mod Version:  1.1.7

**Comment by Darkosto** [comment]
Ahh okay! Was helping someone out with this mod and they were asking about these features and did not have the option in their config. That's pretty helpful!

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
