### ISSUE TITLE
Crash on right clicking Warp Core in Space Station

### ISSUE THREAD

**Issue by davqvist** [zmaster587/AdvancedRocketry#755]
AR 1.0.19 in Age of Engineering Modpack
Forge 2316
MC 1.10.2

https://pastebin.com/UCZ3AEdy

Someone built the Warp Core on the Space Station on Earth and send it into space. In the Space Station he continuosly crashed on accessing the Warp Core by right clicking. Even breaking the Warp Core and replacing it, led to this.

**Comment by zmaster587** [comment]
Does this occur in the 1,1.x+ builds?

**Comment by davqvist** [comment]
I haven't heard from anyone having this issue since then, but I also added a note into the guide that you should only form the multiblock in space, just in case. I won't update the pack to the newer AR versions though because so many things changed, including things that break progression and not sure if I want to invest the time figuring out if I can change recipes/configs to counteract that.

Btw, I'm glad you are back as I heard you took a break. Looking forward to 1.12 versions for my upcoming packs. You don't have a discord or something similar if I have questions etc?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
