### ISSUE TITLE
question regarding space suit

### ISSUE THREAD

**Issue by DietmarKrause** [zmaster587/AdvancedRocketry#756]
I understand that the regular space suit has oxygen und hydrogen for the usage and it works well for me. There seems to be a way to use normal armor (as the draconic wyvern armor) it you combine it with a diamond and one piece additionally with a tank. That works in the first place but i found out, that this armor modified in this way does not work against the slowness and mining fatigue buffs on some worlds as does the regular suit. Is there any way to work around that?

**Comment by zmaster587** [comment]
That's a bug on my side I think.  I'll get that fixed
