### ISSUE TITLE
Fluid pipe crash NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Forecaster** [zmaster587/AdvancedRocketry#757]
https://gist.github.com/Forecaster/4b91952f39284e675e02dc21069993e8

Happens randomly when certain peoples bases are loaded

**Comment by Keridos** [comment]
https://github.com/zmaster587/AdvancedRocketry/blob/RoundPlanets1_10/src/main/java/zmaster587/advancedRocketry/cable/LiquidNetwork.java#L68 seems to be the culprit.

**Comment by sandalle** [comment]
This might be related to https://github.com/zmaster587/AdvancedRocketry/issues/721

**Comment by zmaster587** [comment]
See if the latest build here fixes it?  http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/RoundPlanets1_10/
