### ISSUE TITLE
Microwave Transmitter does not work in 1.2.2

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#759]
I've been playing with this and sent up a number of microwave transmitter satellites and plugged the satellite id chip into an input hatch of a Microwave Receiver. Normally this generates power and sine the last version 1.2.2 it has stopped generating power.

I minor problem is that the chip says that the planet is unknown and this can be corrected by putting the chip into a satellite monitoring station.

Build the Satellite
![image](https://user-images.githubusercontent.com/4198031/27684864-0e697b78-5ccc-11e7-8694-18c2d3faf6b1.png)

Satellite 99 in satellite bay
![image](https://user-images.githubusercontent.com/4198031/27684932-5a23f958-5ccc-11e7-8cfe-4b4988e8a1bb.png)

Launch the Satellite 99 into space
![image](https://user-images.githubusercontent.com/4198031/27684984-93b765ec-5ccc-11e7-8eb1-1bad5c5a073a.png)

Put the chip for satellite 99 into the input hatch after the Satellite in in space - Planet unknown.
![image](https://user-images.githubusercontent.com/4198031/27685082-f3122dd8-5ccc-11e7-9165-fd150425e7cd.png)

Put the chip into a satellite terminal and it gets a planet.
![image](https://user-images.githubusercontent.com/4198031/27685287-cd25a0f4-5ccd-11e7-973b-809ba2e4d077.png)

Finally put the chip back into the input hatch and it still doesn't work.
![image](https://user-images.githubusercontent.com/4198031/27685413-5566e4d2-5cce-11e7-9f91-65d13617f981.png)

Put an earlier chip in and it does work
![image](https://user-images.githubusercontent.com/4198031/27685472-961075b6-5cce-11e7-8e80-97f382dff7c1.png)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
