### ISSUE TITLE
[1.11.2] JEI Crashes

### ISSUE THREAD

**Issue by ProxyPlayerHD** [zmaster587/AdvancedRocketry#763]
Whenever viewing Recipes from the Fluid Transposer, the Game Crashed... removing AR fixed it.

soo here ya go

[REPORT](https://pastebin.com/w4yePGRP)

**Comment by vrork** [comment]
Can confirm that is not with that liquids. Its for any liquid Adv. Rocketery messes with.
https://gist.github.com/vrork/1138f7e732689b06b778b593c76f2d04

**Comment by dmodoomsirius** [comment]
here is a silly thought does this happen with just AR and jei and forge?

**Comment by vrork** [comment]
On mine, you can see the item rendered is from adv. Rocktery. Even tough it is a tinkers fluid (aluminum brass)

**Comment by zmaster587** [comment]
Can you try it with the latest build on http://65.78.115.159:8080?

**Comment by TheXWolf** [comment]
Came on here to report the same crash and reason, downloaded latest jenkins build and can confirm no longer crashes. (However lightwood plants texture not showing on inventory or world.)

**Comment by sandalle** [comment]
I think this is a duplicate of https://github.com/zmaster587/AdvancedRocketry/issues/721 and https://github.com/zmaster587/AdvancedRocketry/issues/735 .
