### ISSUE TITLE
Space elevator beacon and capsule appear outside elevator

### ISSUE THREAD

**Issue by IkaMusumee** [zmaster587/AdvancedRocketry#764]
I'm running version 1.2.0c for Minecraft 1.10.2
![2017-07-01_06 53 28](https://user-images.githubusercontent.com/20753395/27761531-872a2da4-5e2b-11e7-917a-38e30b155c52.png)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by IkaMusumee** [comment]
I haven't used the mod in two years out of lazyness, pluss it ran into the same problem I had with Galacticraft in that there's not much to do on other planets that I can't do in the overworld. Then again, that was two years ago. I can't say if I know if this is still a problem or not. It probably still is in that version of the mod.
