### ISSUE TITLE
Crash on Restart

### ISSUE THREAD

**Issue by MrWackers** [zmaster587/AdvancedRocketry#766]
Happens on Servers and Clients.
LibVulpes-1.7.10-0.2.5-universal.jar
AdvancedRocketry-1.7.10-1.2.2.jar

NullPointerException

looks like right here: XMLRecipeLoader.registerRecipes

[crash-2017-07-02_16.31.42-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1120033/crash-2017-07-02_16.31.42-client.txt)

**Comment by zmaster587** [comment]
I hate to ask this after such a long time, but do you still have a copy of the xml recipes you were using?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
