### ISSUE TITLE
Crash on Building Space Station Extension

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#767]
AdvancedRocketry-1.10.2-1.2.2
LibVulpes-1.10.2-0.2.5-universal

I built a large structure on a launch pad and send the first part up in a rocket.

Scanning the second part worked fine but building it caused the game to crash and it crashes every time loading the world.

I've uploaded a video (6 mins) that shows what I'm doing [https://youtu.be/goBGswIsl6g](url)

I've successfully sent extensions to a space station before but I can't remember in which version I did this.

[crash-2017-07-03_13.34.55-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1120282/crash-2017-07-03_13.34.55-server.txt)
[crash-2017-07-03_13.51.34-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1120284/crash-2017-07-03_13.51.34-server.txt)
[crash-2017-07-03_13.06.58-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1120285/crash-2017-07-03_13.06.58-server.txt)
[crash-2017-07-03_13.10.07-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1120283/crash-2017-07-03_13.10.07-server.txt)

**Comment by duncanwebb** [comment]
If I create a simple extension to the space station this builds as expected. So the problem has to do with the larger structure causing a ticking entity.

**Comment by zmaster587** [comment]
The suit work station is acting up it seems
