### ISSUE TITLE
[Cosmetic Bug] Connected texture not working on a single line Launch Pad (1.11.2-1.2.2)

### ISSUE THREAD

**Issue by Liinche** [zmaster587/AdvancedRocketry#768]
As say in the title if we put only one line of Launch Pad there is no connected texture.
![texture bug](https://user-images.githubusercontent.com/25283037/27840470-7fb18754-60f9-11e7-862d-47be0b45baad.png)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
![2019-03-03_19 56 14](https://user-images.githubusercontent.com/9893266/53706138-6bb44d80-3dee-11e9-9cc8-99890deb3653.png)

Can confirm
