### ISSUE TITLE
[Cosmetic Bug] All Single Bloc Machine with power dont connect to Energy Cable (1.11.2-1.2.2)

### ISSUE THREAD

**Issue by Liinche** [zmaster587/AdvancedRocketry#769]
All is in the title ;)
![connection lost](https://user-images.githubusercontent.com/25283037/27875530-c3e15bb0-61b3-11e7-8610-eb441a48903f.png)
List of the machine not connecting :
- Fueling Station
- Rocket Monitoring Station
- Rocket Assembling Machine
- Satellite Terminal
- Space Station Assembler
- Unmanned Vehicle Assembler
- Oxygen Vent

**Comment by Liinche** [comment]
The power input plug also dont connect to the cable

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
