### ISSUE TITLE
Fluid Pipes stop transferring (on chunk load?)

### ISSUE THREAD

**Issue by AlexJ6301** [zmaster587/AdvancedRocketry#771]
Fluid pipes seem to stop transferring fluid after chunk unloads and is reloaded.  MC (RC) server, leave game, come back and most pipes no longer transfering.  Breaking pipe and replacing fixes problem.

**Comment by dmodoomsirius** [comment]
What version of minecraft and what version of Advanced Rocketry and LibVulpes?

**Comment by AlexJ6301** [comment]
Minecraft 1.10

AdvancedRocketry-1.10.2-1.2.2

LibVulpes-1.10.2-0.2.5-universal
