### ISSUE TITLE
Gas Charge Pad Error

### ISSUE THREAD

**Issue by reaper2812** [zmaster587/AdvancedRocketry#773]
I'm trying to fill up a spacesuit with the gas charger on my friend's server running the "All the Mods" pack version 1.10.2 v3.00. For some reason it asks for an Rf input but I know from looking at youtube tutorials for the mod that it doesn't need it. It also will not accept Rf from any wires I use, so I can't actually ever use it. Any idea what we can do to fix this?

**Comment by Liinche** [comment]
i doesnt need rf you just need to fill the gas charger with oxygen and have some tank on your suit

**Comment by reaper2812** [comment]
I realise that and if you actually read my first post I said it there. But the problem is that it shouldn't need Rf but won't work without it

**Comment by Liinche** [comment]
i just try it on the actual pack and it work without rf
try to put your suit back in the workstation to see the amout of oxygen in the tank

**Comment by reaper2812** [comment]
Tried that earlier and it still wasn't working, Jo idea why

**Comment by zmaster587** [comment]
Is this still an issue?
