### ISSUE TITLE
Let station builder check if block is breakable when building

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#774]
So I have some techguns ore clusters generated in the world that is unbreakable, but the station builder is able to remove them from the world.
Could you check the materials before building?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
![2019-03-03_20 01 19](https://user-images.githubusercontent.com/9893266/53706284-22183280-3def-11e9-9231-77f2515d4e54.png)

:thinking:
