### ISSUE TITLE
[1.10.2] Suit Workstation problem

### ISSUE THREAD

**Issue by slava110** [zmaster587/AdvancedRocketry#775]
I can put any item in armor slots of suit workstation.
![2017-07-10_16 33 33](https://user-images.githubusercontent.com/26705162/28020695-f6746350-658d-11e7-857d-09d5ea3f4d69.png)
![2017-07-10_16 33 45](https://user-images.githubusercontent.com/26705162/28020696-f674e0dc-658d-11e7-998b-5824175868ca.png)
![2017-07-10_16 33 56](https://user-images.githubusercontent.com/26705162/28020698-f67cbcd0-658d-11e7-942e-ade253ce2f00.png)
![2017-07-10_16 34 03](https://user-images.githubusercontent.com/26705162/28020697-f676e4ae-658d-11e7-816b-c6a7a24adffb.png)
Fix this please

P.s.: I'm from Russia and don't know English very good. Sorry for my grammatical mistakes. And thanks for fixing space suit color problem :D

About mods:
AdvancedRocketry-1.10.2-1.2.2
LibVulpes-1.10.2-0.2.5

**Comment by zmaster587** [comment]
Confirmed, I meant to fix this a while back but kept forgetting, apololgies.
