### ISSUE TITLE
There was an error when the rocket returned.

### ISSUE THREAD

**Issue by Android-KitKat** [zmaster587/AdvancedRocketry#778]
There was an error when the rocket returned.

Minecraft version: 1.11.2
Mod version: 1.2.2-22
Forge version: 13.20.1.2393

[crash-2017-07-14_01.45.22-server.txt](https://gist.github.com/Android-KitKat/3a063cf1c5026178f7ac0dea575ba14d)

**Comment by zmaster587** [comment]
Fixed in #791
