### ISSUE TITLE
Sattellite Builder and Rocket Assembling Machine cause blank screens

### ISSUE THREAD

**Issue by SplitInfinitive** [zmaster587/AdvancedRocketry#779]
When using either the scan function or the build function for both machines the entire screen goes blank.  The same color as the horizon (black and night and blue during the day).  I can still access the game there's just no screen to interact with as long as I'm looking at the pad in action.

If i close the builder's ui and look away, the screen returns.  If i wait until it finishes, the screen returns.

AR version 1.20.2-1.2.2

when screenshotted: this is what shows up:

![2017-07-15_21 58 15](https://user-images.githubusercontent.com/24683195/28244445-ce8da7a6-69a8-11e7-9c99-923a4cb69455.png)

**Comment by SplitInfinitive** [comment]
Not sure what happened, patching one of my mods seems to have resolved the issue.

Closing issue.

**Comment by Elvarion** [comment]
Having this issue on our Custom Modpack, I got a blank screen while a friend of mine standing at the same location did not get a blank screen.
@SplitInfinitive Could you share a modlist perhaps so we also could fix this?

- AdvancedRocketry-1.10.2-1.2.2
- LibVulpes-1.10.2-0.2.5-universal


List of mods we use: https://gist.github.com/Elvarion/b745b82dcd2687f83ffd7610ae0dae9d
