### ISSUE TITLE
world limiter not working still makes them anyway. 

### ISSUE THREAD

**Issue by jwebba** [zmaster587/AdvancedRocketry#781]
# Dimensions including and after this number are allowed to be made into planets [range: -127 ~ 8000, default: 2]
    I:minDimension=7995

According to what i understand it should only make 5 dimensions. 
In this case it made up to 7995 - 8066

No error file, it's just not working as intended.

**Comment by zmaster587** [comment]
there's a bit of randomness to it, but without the moons you should have 9 + 5 + 7 + 3 + 2 + 1 = 27 (for the different default star systems), then some of those should have moons, so you should have between 40 and 80 planets unless the RNG goes a bit crazy.
