### ISSUE TITLE
ArchitectureCraft Blocks

### ISSUE THREAD

**Issue by dhkatz** [zmaster587/AdvancedRocketry#787]
Blocks from the [ArchitectureCraft Mod](https://mods.curse.com/mc-mods/minecraft/242001-architecturecraft) do not work with the latest 1.10.2-1.2.2 version of Advanced Rocketry (blocks disappear upon building, but reappear if disassembled). Any possibility this could be fixed? The blocks are very great for making good looking rockets. If not, could you please point me to a mod that is supported? Chisels & Bits also appears to not work when building the rocket.

Edit: I should note this is in a multiplayer server. My friends have said this issue does not appear in singleplayer. Possible server issue?

**Comment by DoctorJew** [comment]
Can I close this issue? @dmodoomsirius

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
