### ISSUE TITLE
Broken/crashy fluid pipes

### ISSUE THREAD

**Issue by purpleposeidon** [zmaster587/AdvancedRocketry#790]
This is on a server with AdvancedRocketry-1.10.2-1.2.2-35.

![](https://user-images.githubusercontent.com/150333/28503308-f8ef561e-6fb8-11e7-94cf-623f84a817ff.png)

....sooo: Train -> Fluid Unloader -> U-shaped Red-line up to 15 foundry refractory tanks -> inner Yellow-line up the inside of the silo (powered by levers that I flip when trying to unjam & this causes the crash) -> 8×{IC2 Liquid heat exchangers, creates pahoehoe lava -> Foundry spouts -> Foundry refractory tanks} -> cyan waste-line -> railcraft fluid unloader

The red & cyan pipelines seem totally solid.
However, often (after a server restart?) the yellow line gets stuck. It can be unstuck by turning the levers on the back of the silo on and off, sometimes, or by breaking & replacing the pipes. However, doing this causes this can crash the server: https://gist.github.com/Forecaster/9f23e9d0b2d4bd2904341d98b7b02c4b

https://github.com/Railcraft/RailcraftPatronServer/issues/65

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
