### ISSUE TITLE
[1.11.2] Asteroid mission crash

### ISSUE THREAD

**Issue by ProxyPlayerHD** [zmaster587/AdvancedRocketry#791]
just looking at the Rocket Terminal, seconds go down, timer reaches 0sec... goes down to -1sec. Game crashes.

[Report](https://pastebin.com/ZcBhm1KR)

this is also an issue:

![2017-07-24_10 46 42](https://user-images.githubusercontent.com/13576843/28515778-25b5018e-705f-11e7-8d46-950645cfbfc6.png)

this happens everytime a rocket is being scanned or built... like, how does that go unnoticed?

**Comment by Mocpages** [comment]
Same issue with the mining mission. However, when the mission finishes and the rocket returns, the world crashes on load as well (effectively meaning I can't use it).

**Comment by Bysokar** [comment]
Hi Guys, please test this jar [here](https://deploy.stargatemc.com/AdvancedRocketry-SNAPSHOT.jar) - It is a copy of zmaster587's 1.11 branch with a small fix to hopefully prevent this issue.
Let me know how you go.

**Comment by Bysokar** [comment]
@mocpages @proxypageshd

**Comment by Mocpages** [comment]
It's giving me a ERR_CONNECTION_REFUSED, is the website up right now?

**Comment by Bysokar** [comment]
Oh lol... try replacing stargatemc.com with game.stargatemc.com in the same link.
I moved our site to enjin lastnight. Sorry!

**Comment by zmaster587** [comment]
Fixed random null, and PRs for fixing this kind of stuff would be greatly appriciated if possible in the future

**Comment by zmaster587** [comment]
Rendering should be it's own seperate issue.
