### ISSUE TITLE
Rutile Ore not generating

### ISSUE THREAD

**Issue by InjuredWolf** [zmaster587/AdvancedRocketry#796]
Despite the default configs of rutile ore gen being 6 per chunk (with clump size of 3), mining a chunk (or several) fails to retrieve any of it (using RFTools Builder with Quarry Shape Card). Is the config only for planets (in which case, how do I control overworld ore gen for it - libvulpes does not have any oregen config) or is it bugged? Or am I reading it wrong?

**Comment by zmaster587** [comment]
the advancedRocketry.cfg controls Rutile generation for the overworld and all planets.  Earlier builds I found that the default of 6 was far too low, try changing it to 10 per chunk and 16 per clump.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
