### ISSUE TITLE
Request on License Clarification

### ISSUE THREAD

**Issue by TimTinkers** [zmaster587/AdvancedRocketry#797]
@zmaster587 
I notice that you reissued the license for this repository under default United States copyright. As I understand it, this is "all rights reserved" and only grants us the right to fork per GitHub's TOS. We are not, however, permitted to actually modify or compile this repository in any way.

I just want to stay above-board here before I try and add some of my desired changes into your mod. Is this your desired intent? I notice that you've merged pull requests recently, so is this something I should individually be requesting permission from you to do?

(I realize this might seem like a completely overblown question for Minecraft modding, which is just a hobby to so many of us. But I've accidentally stepped on some developer toes before and don't want to do anything against your wishes here.)

Thanks!

**Comment by zmaster587** [comment]
It was designed to be restrictive during early development (before curse release), however I did plan on moving to a less restrictive licence and have completely forgotten to update it.  I'm trying to see if there's any boiler plate license that allows for everything (redistribution of binary and source, compiling code, modification, etc) except monitization.  Thanks for the notification.

**Comment by zmaster587** [comment]
Moving to MIT license

**Comment by TimTinkers** [comment]
Thank you!
