### ISSUE TITLE
Energy cable is not compatible with ImmersiveEngineering part of the equipment

### ISSUE THREAD

**Issue by Nidero** [zmaster587/AdvancedRocketry#798]
Crash-report link: https://hastebin.com/qiciculusa.http

Problem:Server crash, Client crash

Minecraft version:1.10.2

Forge version:1.10.2-12.18.3.2316

Mod version：
LibVulpes-1.10.2-0.1.19
AdvancedRocketry-1.10.2-1.0.19
ImmersiveEngineering-0.10-61

Steps to reproduce the problem:
Use energy cable to connect ImmersiveEngineering Heater.
Energy cable to connect the bucket wheel mining machine to destroy its multi-block structure.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
This should no longer be a problem anymore since cables are deprecated.
