### ISSUE TITLE
Galaxy Selector Level?

### ISSUE THREAD

**Issue by StargateMC** [zmaster587/AdvancedRocketry#799]
Hi zmaster,

If possible can you add support for multiple galaxies in the planet selectors?
I've got a Stargate themed server and am in the process of adding *config* for 10,000 worlds or so, across several galaxies.... but have found the viewable area in the planet selector is insufficient.... I'm looking for 10,000 planets in total with maybe 2,000 stars.

I'm working on this slowly, but if you were to take this one on board I'm sure you can do it a lot faster.

Regards,
Bysokar

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Bysokar** [comment]
This is still an issue - but we moved to WarpDrive because it has a real space dimension a while ago. Not one for us :)

**Comment by StargateMC** [comment]
This is a feature request @dmodoomsirius not a bug.
