### ISSUE TITLE
(1.10.2) Space Elevator Bug

### ISSUE THREAD

**Issue by StevieBranscum** [zmaster587/AdvancedRocketry#800]
I am playing on Forever Stranded 1.8.9.1 with optifine and have elevators for the moon, earth, and my space station. When I go to the moon, everything is fine, but when I leave the moon, my

**Comment by StevieBranscum** [comment]
Submit button is really close on mobile. Anyhow, the elevator coming from the moon sticks at y=1000, rendering any other uses unusable. Only way I know to fix this is to apply a backup, yet this is extremely inefficient. Advanced Rocketry is 1.2.7 (update as of June 12, 2017)

**Comment by Vordyn** [comment]
I'm having the same issue, I have 2 elevators stuck at y level 999 and 996 which I can't remove. I've broken both the Earth and space station elevator and recreated them without luck.

Also running Forever Stranded but version 1.9.2 (forge 12.18.3.2422) and AR Version 1.2.2.

Will try to move the earth elevator from the x/z location where the elevator is stuck but it breaks the base's design so I'd like to bring it back there.

![2017-09-11_13 43 59](https://user-images.githubusercontent.com/31862328/30289698-00bef2fa-96fb-11e7-973d-e06f1169b614.png)

**Comment by gluff95** [comment]
Can confirm still having this issue in 1.12.2. Appears to be no way to fix except by restoring backup.

**Comment by zmaster587** [comment]
@gluff95  Can you send me a copy of the world and the coordinates?

**Comment by StevieBranscum** [comment]
^ at least in my modpack

**Comment by gluff95** [comment]
@zmaster587 I'm sending you a zip of the backup I took afterwards,. You'll find the bugged capsules at xyz 1434 1000 1813. It's a BIG file however, 2.2 GB. https://mega.nz/#!xAx2zIzR!I42TV0zXv2tmTw1w43gkNtFIkUIb-vp1v1SYhE8IVSk

**Comment by Lemikoo** [comment]
I just got the same issue

**Comment by Lemikoo** [comment]
The capsules are stuck at about level 1000 above the space station. Anytime I try to travel using the space elevator I get stuck in one of these capsules. There are two. I cant mine/break them. Is there any way to remove them? @zmaster587

**Comment by zmaster587** [comment]
right now there's no way to remove them short of WE or the /kill command (not from vanilla or AR to my knowlege).  I'd taken multiple safegaurds to ensure this cannot happen, but as it seems it happens anyway.  I'm currently analysing @gluff95 savefile and hopefully put together a fix.
