### ISSUE TITLE
[1.7.10]Rockets Glitching

### ISSUE THREAD

**Issue by marckusfransson** [zmaster587/AdvancedRocketry#802]
My rocket(s) sometimes glitch to/from planets and wastes all the fuel they have because of this.

**Comment by zmaster587** [comment]
Is there a way to replicate this issue reliably?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
