### ISSUE TITLE
Electrolizer blockage

### ISSUE THREAD

**Issue by GregReeder** [zmaster587/AdvancedRocketry#803]
Not a bug, but issue is useability

The electolizer becomes blocked if (for example) hydrogen tanks are full, but oxygen is being used.  This is an issue on space stations, for example. Either the electrolizer needs to be updated to to void excess liquids, or a block needs to be added to void the gas.

version 1.0.16 for 1.10.2
no fixes found on change log

**Comment by zmaster587** [comment]
requires similar fix as to #835

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
