### ISSUE TITLE
Several things

### ISSUE THREAD

**Issue by Cenbes** [zmaster587/AdvancedRocketry#804]
MC Version - 1. 10. 2
Mod vesion - AdvancedRocketry-1.10.2-1.0.19.jar
Hello, i added your mod on my server and we now testing your and other mods on server, i found some bugs what are not good for game itself and some things what are not good for mod itself.
 
- You can launch rocket remotely what have guidence computer with chip configured to luna and launch it. Rocket will never leave Overworld and it will be stuck in nowhere. Cargo rockets to other planets seems not working :D
https://youtu.be/CG9ORnP1i94
 
- Sometimes rockets not render to player and they bug itself on earth, you can start them, they burn fuel but they will stay on ground without moving until they burn all fuel.
 
- Minning rockets eating chips with asteroid data.
And they get stucked in mid air while landing.
https://youtu.be/eaXZnTXfRpY
 
- Sometimes rockets get stuck while landing in mid air and dont fall down ( i thing it will be good if all rockets will fall down if their engines not working)
 
- You can build 2 or more identical satelites if you will add there 2 or more chasis, if you will launch to satelites with ID 2 they will rewrite data of staelite before.
 
- Sometime when you oppening guidence computer your game can crash: https://pastebin.com/RPi88m4R
At mostly happening on bugged rockets.
Rokets can mostly bug themself after landing on moon.
https://www.youtube.com/watch?v=eEGxFdYDrog
 
- Crusher from mekanism can make your silicon, it mean silicon recipe in your multiblock is not in use.
 
- Stations on multilayer not workin properly.
https://www.youtube.com/watch?v=RnxPgemTFAE
 
- Satelite data in satelite terminal have bigged AI if satelite data extend internal buffer, it will be good incriesse internal buffer to 5000 data and make recipe harder.
https://youtu.be/eaXZnTXfRpY
 
- Dilithium generating on Earth by default - pointless to go on moon.
 
Other bugs:
https://youtu.be/i5eBU10plEQ
 
https://youtu.be/e1tePRgP6vM
 
https://youtu.be/kaAngaO3jpE

**Comment by mcdodge34** [comment]
I can relate to most of theses, so I'm subscribing to see when this will be fixed, I really hope to see theses bugs fixed in 1.10.2 and not only on latest versions like most modders tend to do theses days, I took the time to design an awesome modpack for myself and wanted to enjoy this advanced rocketry mod to the max, have big plans for it, but right now, its not exactly working. I have to disconnect and reconnect from my server every single time I travel on my rocket between destinations, otherwise I'm not loaded properly and I'm stuck in between lands and such. All of this using latest 1.2.2 version of the mod.

**Comment by zmaster587** [comment]
Are both of you using sponge or something similar?

**Comment by mcdodge34** [comment]
Nope, straight Forge latest version, but I've decided to move to 1.12.1 and more than likely will not see your mod on it for quite awhile so it will be something I'll enjoy much later (I don't blame you for this, its quite a task to develop a mod for already 3 versions of Minecraft at the same time) will hopefully see this mod in a future version.

**Comment by TheExmax223** [comment]
Hello everyone, I'm having the same problems as Cenbes describes. I'm using Sponge. Please zmaster587, try your best to fix it, you've already done a lot of good work to make this mod as much awesome as it is, but without this fix I'm unable to use it. Thanks and have a good day :)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by zeldamon** [comment]
Some of these are still issues. I get stuck in transition before landing ~25% of the time, and have to regularly reload my world to get it to work. I'm concerned that on a server a player could get stuck. 1.12.2
