### ISSUE TITLE
[question] hard settings

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#806]
Hello,

Is there a default configuration for hard settings? or some xml templates that i can download? (long research to find planets and asteroids, less ore on asteroids, more expensive rockets or satellites, etc)
(i play with GT6 that add some difficultie but not on this parts héhé)

**Comment by lazerous42** [comment]
I would love something like this, but sadly I haven't come up with anything in my searches.  My pack is 1.7.10 and uses GT5u.  I would love some "hardmode" type recipes.

**Comment by choum33** [comment]
minetweaker can do a part of it but not all ;)
about asteroids i setup some in xml and after some try and fail i found the right way to do it ;)
