### ISSUE TITLE
render distance and satellites

### ISSUE THREAD

**Issue by superon** [zmaster587/AdvancedRocketry#807]
i can't see natural satellites if the render distance is below 7, seems like they're masked out or something

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by superon** [comment]
just got the mail telling me you'd replied, it is and will be unless there's been an update to 1.7.10 or i'm not understanding the issue

**Comment by MrEyeballs29** [comment]
There no back ports from 1.12
