### ISSUE TITLE
Design of warp engine

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#808]
Wouldn't it be cool to have the new Star Trek one on board? Or make an option that you can build the engine vertical and it will get a different texture. An image is [here](https://i.stack.imgur.com/pqhTf.jpg)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
