### ISSUE TITLE
microwave reciver does not work

### ISSUE THREAD

**Issue by maxall4** [zmaster587/AdvancedRocketry#811]
my microwave receiver does not work it builds but it wont take rf from my satellite
i put in the satellite id chip

**Comment by soronthar** [comment]
I can confirm this happening on the 1.10.2 version (Forever Stranded pack). The satellites had a Microwave Transmitter, and I tried with 1, 2 and 3 advanced solar panels with and without batteries. The satelites reached orbit as the Satelite Terminal shows the status as Collecting Energy.

I put the chips in the input hatch for the receved (one at a time, and all at once), turned the multiblock on, and nothing happened.

This was tested in the Overworld.

**Comment by zmaster587** [comment]
Should have been fixed with #998
