### ISSUE TITLE
Performance Issue with tiles

### ISSUE THREAD

**Issue by Sir-Will** [zmaster587/AdvancedRocketry#813]
AdvancedRocketry-1.10.2-1.0.19
![](http://i.imgur.com/jMIAS5k.jpg)
![](http://i.imgur.com/1bVko5G.jpg)

**Comment by zmaster587** [comment]
That appears to be a chunk load loop.  That's not good.

**Comment by dmodoomsirius** [comment]
Duplicate of #1333
