### ISSUE TITLE
Crash due to XML load

### ISSUE THREAD

**Issue by GodMorduk** [zmaster587/AdvancedRocketry#815]
Once the game started, it creates XML files. First launch is fine, but every launch comes after that creation cause crash.

So, basically, the only way to play with AdvRocketry - remove created XML files every time before start. 

Here is crashlog. If nessesary, I can provide the full log. 

[crash-2017-08-10_14.03.41-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1214808/crash-2017-08-10_14.03.41-client.txt)

Version of Minecraft is 1.7.10. 
Version of AdvRocketry - tried 1.2.2, 1.2.1 and even 1.0.19b.

p.s. sorry for my bad English, not my native language

**Comment by zmaster587** [comment]
It looks like it's trying to load a recipe containing a nonexistant item, or at least an item with no name, would it be possible to post the entire forge log and the relevent XML files.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
