### ISSUE TITLE
[1.10.2 - 1.0.19] satellite crash   - age of engineering pack

### ISSUE THREAD

**Issue by audenga** [zmaster587/AdvancedRocketry#817]
launched a satellite now server instant crashes when joined
https://pastebin.com/G2hSwdaM

**Comment by Janrupf** [comment]
You should try to remove the rocket from the entitys, you can find answers how to do this in the internet

**Comment by zmaster587** [comment]
Should already be fixed in 1.1.x and later builds of the mod
