### ISSUE TITLE
Adjust GUI size and scale please ???

### ISSUE THREAD

**Issue by mcdodge34** [zmaster587/AdvancedRocketry#820]
Please, can we get a way to adjust the scale size of the GUI, or scale it down. I have problems with my eyes and I play with Minecraft Large GUI mode since I started playing it back in 2012, I tried real hard to adapt to the Normal GUI scale, but my eyes hurt when I try this (I only have 70% of right eye and 30% vision on left eye) I tested the GUI size and when in normal GUI size in Minecraft, your GUI is perfect for me, but once I choose my large GUI in Minecraft, the GUI for Advanced Rocketry is huge and takes too much of my screen (I'm in 1600*900 resolution if it can help you out)

Oh yeah, very important, I play on 1.10.2, many mods I want aren't in 1.11.2 or 1.12 yet.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by mcdodge34** [comment]
This is indeed still an issue now in 2020 with latest version of Advanced Rocketry in 1.12.2 I know this thread is old and closed but I hope someone will see this, I was expecting it to be fixed since 2017 but nope.

**Comment by mcdodge34** [comment]
I solved this issue partly right now by using airtight seal on all my default armor pieces and having only 1 tank of oxygen in my suit is ok for now, but would love to be able to adjust the scale of the Advanced Rocketry GUI independently from the game GUI, that is the issue I have right now.
