### ISSUE TITLE
some lags

### ISSUE THREAD

**Issue by nailfor** [zmaster587/AdvancedRocketry#821]
mc 1.7.10
ad 1.2.2
I collected an electrolyzer at the orbital station and noticed lags even if the chunk loader does not work (~ 700mc)
A very big load is given by oxygen vent(10,000 ms) if I am outside the station

**Comment by zmaster587** [comment]
What atmosphereCalculationMethod are you using?  Does this occur with atmosphereCalculationMethod set to 2 or 3?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
