### ISSUE TITLE
Updating to AR 1.10.2-1.2.2 beta and LibVulpes -0.2.5 causes crash on startup as Thermal Expansion shows a hashcode error

### ISSUE THREAD

**Issue by jstaff62** [zmaster587/AdvancedRocketry#823]
[2017-08-17-4.log.gz](https://github.com/zmaster587/AdvancedRocketry/files/1230576/2017-08-17-4.log.gz)

The full log for this, even though it literally just happens on startup.

I don't know how much you can do about this because it's mainly TE throwing the error, but as soon as I updated both Advanced Rocketry and LibVulpes this happens every time, then stops and goes back to working perfectly when I go back to the latest release versions; I literally changed nothing else other than updating AR and LV.

**Comment by zmaster587** [comment]
Eerily similar to https://github.com/zmaster587/AdvancedRocketry/issues/456 have you tested with makeMaterialsForOtherMods set to false in the AR config?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
