### ISSUE TITLE
Oxygen vent on Orbit

### ISSUE THREAD

**Issue by edxp** [zmaster587/AdvancedRocketry#824]
Hi.

After upgrading from some ancient version to 1.2.2 on 1.7.10 we encountered  a weird behaviour of oxygen vents:
Note: this is on default configs

1. We have a big Station on orbit (6x4 chunks sealed building 1 Vent per chunk, located on the ceiling). We couldn't get it to fill with air: Oxygen Vents seem to run but do not consume Oxygen and do not fill the atmosphere. Atmospheric analyzer shows Vacuum @0.0 atm.
2. We created an isolated smaller building (4x4x3 internal volume). 
- After adding first Oxygen Vent: no air, no oxygen consumption, energy is consumed; 
- After adding 2nd vent: it immediately consumed all available Oxygen (16 buckets). 
- After providing more Oxygen: no air, no oxygen consumption, energy is consumed, Vent is full of air.
- Adding 3rd Vent: no oxygen consumption, Area is filled with PressurizedAir, Energy is consumed;
- Removing 1st and 2nd Vents: Oxygen is not consumed by 3rd Vent, area is breathable..
- Unsealing the small area; Now it is inside a bigger (6x4 chunks) sealed area. The small area inside is still breathable. Area outside is not breathable. Adding and removing blocks inside the small area makes those blocks non-breathable.
- Unsealing the small area into the space: small area is still breathable, space is not. Oxygen is not consumed, energy is.

Scrubbers are not used at all here.

Please let me know if there is anything I could do to help investigating this.

**Comment by Prodavec** [comment]
We can't reproduce it on our hardware©

**Comment by nickcon26** [comment]
I got same issue and did similar tests.  also on 1.2.2

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
