### ISSUE TITLE
Problem with the operation of cables

### ISSUE THREAD

**Issue by kokos3344** [zmaster587/AdvancedRocketry#829]
Hi, I need to know how to transport the energy from my solar generator to my electric arc furnace. But I do not know how the cables are used. I use version 1.7.10

**Comment by Janrupf** [comment]
You just need to build the cabels and put them under your solar panels but I would recommend to use other cabels if avaible.

**Comment by kokos3344** [comment]
Still not working can you send me an image to see how it is placed?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
