### ISSUE TITLE
Machines not working

### ISSUE THREAD

**Issue by kyguy102** [zmaster587/AdvancedRocketry#830]
All of the machines from advanced rocketry don't work for me, the machines are formed in the multiblock structure form but they do not actually fulfil their function. After pressing the on button nothing happens. The machines also have power.
![2017-08-30_20 21 50](https://user-images.githubusercontent.com/10367758/29868076-f5b58006-8dc0-11e7-86d3-a6ccad08f3ed.png)
![2017-08-30_20 21 55](https://user-images.githubusercontent.com/10367758/29868077-f5b8f1aa-8dc0-11e7-9c7b-fbc0e4ce1d31.png)
![2017-08-30_20 22 10](https://user-images.githubusercontent.com/10367758/29868078-f5bf2dea-8dc0-11e7-895c-1c4ef5b07abe.png)
![2017-08-30_20 22 12](https://user-images.githubusercontent.com/10367758/29868079-f5c3c530-8dc0-11e7-92e5-60e66d4ebb0a.png)
![2017-08-30_20 22 14](https://user-images.githubusercontent.com/10367758/29868081-f5cb7f5a-8dc0-11e7-9525-b73543e9e9ec.png)

**Comment by sandalle** [comment]
I'm having the same problem, first noticed with Lathe (trying to cut Copper Ingots into Copper Rods) and the Electric Arc Furnace (trying to turn Sand into Silicon Ingot as there's no other way to get Silicon Ingots). All machines are assembled (right-clicking opens interface) and have full power. I have left them "running" for hours (real time) to days with no progress.

Modpack: https://minecraft.curseforge.com/projects/nst-unofficial-exploration

Minecraft: 1.11.2
Forge Mod Loader: 1.11.2-13.20.1.2454
LibVulpes: 1.11.2-0.2.5
Advanced Rocketry: 1.11.2-1.2.3

**Comment by matrix07012** [comment]
I'm also having this issue. None of the machine work. They do absolutely nothing.

Minecraft: 1.11.2
Forge Mod Loader: 1.11.2-13.20.1.2454
LibVulpes: 1.11.2-0.2.5
Advanced Rocketry: 1.11.2-1.2.3

**Comment by zmaster587** [comment]
might be related to #851?

**Comment by zmaster587** [comment]
Tested and appears fixed with #851's patches
