### ISSUE TITLE
Infinite Oxygen

### ISSUE THREAD

**Issue by Elvarion** [zmaster587/AdvancedRocketry#832]
So I was setting up a Space Station in Space and was tinkering around with the Oxygen Vent.
First it wasnt working (fault was the 32 block limit) So I reduced the sealed area and it started working and draining a massive amount of oxygen per tick. The bottleneck in my setup seemed to be the EI tank to hold the liquid. I switched the tank for liquid translocators and this is where things got strange.
The oxygen vent was now running with just power, no oxygen needed. Broke the vent and placed back the EI-Tank, everything was fine. 
Then I started moving stuff around and all of a sudden my room got filled with oxygen, and ive not even got the vent placed. Breaking blocks so the seal breaks and then replacing them will re-seal the area giving me back oxygen.

Its now perma filled with oxygen and I cant seem to undo it and actually get a legit setup going.

- AdvancedRocketry-1.10.2-1.2.2.jar
- LibVulpes-1.10.2-0.2.5-universal.jar

- Modlist
https://gist.github.com/Elvarion/b745b82dcd2687f83ffd7610ae0dae9d

**Comment by Elvarion** [comment]
Also ill attach another issue regarding Oxygen here since I can pretty much tell the issue in two sentences.
The Carbon Collection Cartridge wont go below 1/172800 durability in the O2 Scrubber.
The Chemical Reactor NEEDS a CCC with 0/172800 durability to restore it.

**Comment by zmaster587** [comment]
Scrubber should be fixed, looking into the O2 bug.  O2 usage has also been reduced for next build and a multiplier config added.

**Comment by Elvarion** [comment]
Cool, Thanks :)
