### ISSUE TITLE
(1.7.10) Satellite Builder not accepting items in right-most slots

### ISSUE THREAD

**Issue by jstaff62** [zmaster587/AdvancedRocketry#833]
using latest versions of AR and LV (1.2.2 and 0.2.5)
when trying to build a satellite, no data, batteries, main components or solar panels will go into their slots, those 7 slots are completely locked. everything is set up properly and it works perfectly in 1.10.2 but not 1.7.10. versions 1.2.1 and 0.2.4 were used in both MC 1.7 and MC 1.10, then i updated in MC1.7 and the issue remains, only in 1.7.
unless they've been deliberately disabled for whatever reason but this makes the entire block unusable

**Comment by zmaster587** [comment]
It's definatly not deliberate, I'll look into it

**Comment by zmaster587** [comment]
I'm not quite sure what the issue was, but it appears to have been fixed at some point after the 1.2.2 release.  Tested in the build for next release and there's no problem.  So it should work next build

**Comment by jstaff62** [comment]
thank you! :D
