### ISSUE TITLE
What is up with the github wiki?

### ISSUE THREAD

**Issue by Jummit** [zmaster587/AdvancedRocketry#834]
I know there is a advanced rocketry documentation [here](http://65.78.115.159:8000/AdvancedRocketry/), but why is there also the github wiki which seems to be very incomplete and useless?

**Comment by zmaster587** [comment]
The github wiki was made very early on, I had actually forgetten it even existed until you mentioned it.  Though going forward I'm not sure whether I should attempt to copy everything over or just remove the github wiki.  Probably the latter as I don't think the github wiki allows for nice formatting/generic HTML and CSS
