### ISSUE TITLE
[1.7.10] Kills internal Server

### ISSUE THREAD

**Issue by janb14** [zmaster587/AdvancedRocketry#838]
Hey Guys, after just several minutes of playing the mod (everything works as expected),
the internal Server just gives up. This can be noticed by : 
-breaking a block doesnt drop it
-animals not moving
-cant interact with any UI
-shutting down the game stops responding and you need to terminate through taskmanager
-chunkupdated stay at 0 and u can outrun the world load

im running newest versions of both AR and the Lib
1.7.10
latest released forge
and here is my modlist
https://pastebin.com/QkHM9189 (including but missing the AR and the Lib)

the problem occures after playing the mod and building the first structures. But theres nothing in the logs :/

Edit:
i also configured the mod so mystcraft dims and AR not conflict so AR has all dimensions at 2000 and above.

Edit 2:
Im already playing with 6gigs of ram and only 30% is used so no problem there.

**Comment by zmaster587** [comment]
can you paste the log from both the server and client?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
