### ISSUE TITLE
 oxygen recharging platform

### ISSUE THREAD

**Issue by kokos3344** [zmaster587/AdvancedRocketry#839]
I do not work the platform I put on top of it but I do not load the space suit with oxygen and the platform has oxygen

**Comment by zmaster587** [comment]
What version of the mod, what modules do you have in the spacesuit?

**Comment by cap10zeus** [comment]
Hello having same problem playing the latest version of Forever Stranded modpack. It has Advanced Rocketry version 1.2.2 and LibVulpes version 0.2.5. I had to install a tank into the chestplate for it to work. The internal tank will not charge up like it says in the [wiki](http://65.78.115.159:8000/AdvancedRocketry/items/modularSpaceSuit.php). Unless this is intended, then never mind.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
