### ISSUE TITLE
[1.7.10] Observatory not opening up even with station is oriented

### ISSUE THREAD

**Issue by InfornoFire** [zmaster587/AdvancedRocketry#841]
LibVulpes-1.7.10-0.2.5-universal
AdvancedRocketry-1.7.10-1.2.2

For awhile, I have been looking around to find how to use the observatory in space. The problem is I cannot get it to open up and program asteroid chips. I oriented the station to where it is the darkest, didn't work.

Thanks
![2017-09-08_20 41 34](https://user-images.githubusercontent.com/16070849/30235800-4147f8f2-94db-11e7-8994-ec76492e928e.png)

**Comment by Janrupf** [comment]
I think it works only on planets, the space stations are not allowed to be used with obs.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
