### ISSUE TITLE
Arc Furnace will not smelt

### ISSUE THREAD

**Issue by bowmanjd** [zmaster587/AdvancedRocketry#842]
I must be overlooking something. (Sorry, this is probably best for the forums, but I am unsure if there are Advanced Rocketry forums.)

I have tried iron/coal, sand, and now rutile ore, and, even though my arc furnace is powered nicely, and I can open the various GUIs, nothing happens, no matter how many hours I leave the game running.

Am I missing a step, is something misconfigured, or is this possibly a bug?

I am using Forge 1.11.2-13.20.1.2454, LibVulpes-1.11.2-0.2.5, and AdvancedRocketry-1.11.2-1.2.3

Thanks for any help!

![2017-09-09_11 29 38](https://user-images.githubusercontent.com/86415/30241499-a57b4ece-9552-11e7-80cf-2776d06a7254.png)
![2017-09-09_11 30 01](https://user-images.githubusercontent.com/86415/30241490-852f95f8-9552-11e7-991d-ddbc8abe83b1.png)
![2017-09-09_11 35 38](https://user-images.githubusercontent.com/86415/30241527-139843ee-9553-11e7-9406-0ac598e72162.png)

**Comment by bowmanjd** [comment]
Rolling back to LibVulpes 1.11.2-0.2.4 and AdvancedRocketry-1.11.2-1.2.1 seems to have fixed this.

Now on Forge 1.11.2-13.20.1.2476

**Comment by matrix07012** [comment]
I just tried downgrading and it didn't work. I think it might be a mod conflict.

**Comment by bowmanjd** [comment]
matrix07012, are you sure BetterFps is the culprit? I am finding that the machines work intermittently, even with 0.2.4 and 1.2.1. Try destroying a block or two (one of the inputs or outputs seems to work), replacing it, and then seeing if the machine works.

**Comment by zmaster587** [comment]
might be related to #851?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
