### ISSUE TITLE
No planets/moons in guidance computer and planet selector

### ISSUE THREAD

**Issue by HenkNukem** [zmaster587/AdvancedRocketry#843]
Hey, i'm having an issue with selecting planets, only earth shows up in the guidance computer and planet selector.  

The issue is in age of engineering modpack version 1.0.5 and 1.1.0 (haven't tested earlier versions) with AR version 1.0.19.    (i couldn't find in the github for AoE any related issue as well for the FTB forum).

One thing i can say is, i only have the problem in multiplayer and the configs are the same as in mine singleplayer world that is creative though.

**Comment by HenkNukem** [comment]
Fixed, needed to reset the planet in the XML

**Comment by Sir-Will** [comment]
hey @HenkNukem, what exactly did you change to fix it?

**Comment by HenkNukem** [comment]
I looked it up for you ^^ in the advancedRocketry.cfg look for this; resetPlanetsFromXML=false    and change it to true
