### ISSUE TITLE
Can't select destination

### ISSUE THREAD

**Issue by Bircko** [zmaster587/AdvancedRocketry#844]
When I want to select destination it just looks like this here 
![2017-09-10_16 36 03](https://user-images.githubusercontent.com/29576723/30249924-3831bb06-9646-11e7-9120-49023a728d11.png)

**Comment by zmaster587** [comment]
What are you doing and what do you expect to happen.  If you have a space station chip in the rocket and no landing pads on the space station the screen should look like this.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
