### ISSUE TITLE
1.12 Support

### ISSUE THREAD

**Issue by Magi1053** [zmaster587/AdvancedRocketry#845]
I'm making a modpack with Better Questing, and I would love to be able to add this mod into the quest line, forcing players to go to other worlds to get specific ores for other mods. Any update on when this will be available for 1.12.1?

**Comment by Jummit** [comment]
I think there will be no 1.12.1, there is only 1.12 and 1.7.10, and these two are updated separately, so and new version would be to much afford (I think). But i don't know what the developers are doing or wanting.

**Comment by Divineaspect** [comment]
ignore jummit

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by zmaster587** [comment]
I don't know when it'll be updated to 1.12, the main issue right now being the overwhelming number of issues for the existing version and very little time to actually work on it anymore.  I do plan on updating to the latest version of MC, but I have no telling when yet.  If the transition is not hard, perhaps soon(TM).

**Comment by Santana1053** [comment]
Releasing an Alpha version for 1.12 would be much appreciated, so that I can start integrating it into my modpack's progression tree

**Comment by D3nnis3n** [comment]
I agree. Advanced Rocketry is a good solution for modern Access to alternate dimensions to keep the main dimension clear of mining in servers. Would like to use it again, too and prepare with an Alpha.

**Comment by Magi1053** [comment]
Tbh it doesn't even have to work, I just need the items and recipes and the dimensions to get started on the pack.

**Comment by Thutmose** [comment]
I just tested updating to 1.12.1, and got basic functionality in about an hour (mostly find/replacing a few mappings changes for the mappings I use, and fixing up some methods, if you use same mappings will take much less time), I haven't re-implemented recipes yet, and have not added in advancements for the achievements, was mostly wanting to see if mega-rayquaza to the moon still works:

![image](https://user-images.githubusercontent.com/2363472/31051457-cc3c660c-a636-11e7-9801-2a7a9398e239.png)

I can probably do a more proper update later if I have the time

**Comment by D3nnis3n** [comment]
Awesome. :O

**Comment by Divineaspect** [comment]
did you just ride a pokemon to the moon?

**Comment by Thutmose** [comment]
Yep, I had support for AR in pokecube in 1.10.2, where mega rayquaza could fly to the moon in a similar manner to the rockets, I was curious as to whether my AR support would need updating, and it seems it does not need updating, and still works fine.

**Comment by Thutmose** [comment]
I have this forked, I will see about a more "proper" 1.12 update tonight, I think all I didn't get done was the recipes and the achievements in my quick test last night.

**Comment by D3nnis3n** [comment]
Is this just for testing for yourself, or will you maintain the 1.12 branch? Or give it back to the original author? I'm a bit confused now.

**Comment by Thutmose** [comment]
I will probably maintain a 1.12 branch until the original author decides to do a 1.12 port, or wants to take over mine, I probably wouldn't do any new features, and would just do bug fixes/maintanence

**Comment by D3nnis3n** [comment]
That sounds pretty cool. I hope the original author is fine with that. Will you have a maven or something like that? I would like to help testing, like i'm doing for the MMD mods atm. Of Course, only when you want that.

Anyways, i really appreciate that you want to do this work. A big thank you!

**Comment by Thutmose** [comment]
Advanced Rocketry itself should be fine, it has MIT Lisence, the issue I see is with LibVulpes, I will need to see about getting permission to deal with a 1.12 version of it.

**Comment by Thutmose** [comment]
I made this issue asking permission to update LibVulpes: https://github.com/zmaster587/libVulpes/issues/13 if I do get the permission, then I can see about providing a 1.12 port of the mods until the author gets time to handle them.

**Comment by D3nnis3n** [comment]
I cross my fingers. I would be very happy to be able to integrate it into my private modpack. Just fit's the playstyle so good and does multi-dimensioning in a modern, technical way.

**Comment by dmodoomsirius** [comment]
I do plan on setting up a maven for LibVulpes and Advanced rocketry once i get things going with his gradle script. I need to fix a few things before i do so.

**Comment by dmodoomsirius** [comment]
So @zmaster587 and i have spoken about this and we decided if you want to you can do pull requests into the https://github.com/zmaster587/AdvancedRocketry/tree/1.12. There is a 1.12 branch on [LibVulpe](https://github.com/zmaster587/libVulpes/tree/1.12)s. We both will try to review and test them to get builds out.

**Comment by Thutmose** [comment]
Ok, I will probably send in some PRs over the next few days then, currently am looking through to see if I can find why Luna's low gravity isn't working atm

**Comment by zmaster587** [comment]
Alright.  As for luna's low gravity now working, might be the ASM.  Idk what's changed so if there's some code offset that's changed the FSM may be failing to locate the proper insertion location.  If the name mappings changed that may also screw up the ASM.

**Comment by Thutmose** [comment]
ahh right, I don't think I did anything related to ASM, so any of that probably isn't working at all

**Comment by Thutmose** [comment]
Is there any documentation as to what the ASM does? there may be ways to get the same or similar effects now without it, and I will be willing to look for them.

If no documentation exists, I can go look through the ASM stuff and try to figure it out myself, though I have practically 0 experience with core mods.

**Comment by zmaster587** [comment]
There's not too much documentation as of now, I do know there's a hook I added for the O2 system to run on block change in world (running the O2 checks every single tick would bring a powerful server to its knees).  A lot of the commented out stuff was for a 1.7 mod to adjust gravity direction that I considered brining back for a while.

the one with the "RocketInventoryHelper" was a hack to get around not being able to access vanilla chests in the rockets for being to far away.

The item one is for item gravity.

The one for setupTerrain, I don't even remember anymore to be honest and I'm very much regretting not commenting on that.

Either way, I did update the ASM for the latest builds so it should be good to go now.

**Comment by Daihok41** [comment]
Any news on how the 1.12 update is going for Advanced Rocketry and LIbvulpes?

**Comment by zmaster587** [comment]
I've not tested it myself other than some of the basics, but it appears mostly functional.  Thutmose was a lot of help (*cough* did almost all of the work of updating and he deserves a round of applause).  I do plan on pushing a copy to curse today sometime as alpha until I can really get a chance to test the whole thing or get verification from thutmose that things have been tested and are fucntional.

**Comment by D3nnis3n** [comment]
I haven't yet come to test it through as the Elevators seemed bugged and we made heavy use of them on our Server. I'll - in the next days - see how everything works.

**Comment by dmodoomsirius** [comment]
Already updated for 1.12.2 so closing issue
