### ISSUE TITLE
Only 2 Machines Work [1.11.2][Multiplayer]

### ISSUE THREAD

**Issue by JTK222** [zmaster587/AdvancedRocketry#851]
Minecraft version: 1.11.2
Forge version: 13.20.1.23
Mod version: 1.2.3
LibVulpes version: 0.2.5
Type: Multiplayer
Other mods:
Chisel, CTM, funky locomotion, hopperducts, immersive engineering, jei, journeymap, mantle, minecolonies, mysticalagriculture, refinedstorage, tconstruct.
Problem:
Only 2 machines are working and also only partially.
All machines beside the electrolizer and the Chemical reactor don't want to work.
(Crystalizer, Electric Arc Furnace, Precission Assembler, that saw thing (not ingame right now and can't remember the name :P))
(We couldn't test things like rocket assembler and stuff)
And the only way for us to use the fluids from the electrolizer and chemical reactor is trough other mod pipes. But I guess that's due to us making something wrong. (Can't put water with a bucket into the chemical reactor).
And by don't work I mean that they don't craft anything. The multiblock structure work. but they don't want to craft anything.
The log doesn't contain any errors.

**Comment by zmaster587** [comment]
It looks like somehow an itemstack made of air is getting into the output hatches when it's expected to be ItemStack.EMPTY.  Investigating

**Comment by zmaster587** [comment]
Somehow Item.AIR got into the output slot and the machine treated the slot as occupied by an item, should be fixed now
