### ISSUE TITLE
Completed Space Elevator Multiblock causes game to render the skybox background over everything.

### ISSUE THREAD

**Issue by Smtgr14** [zmaster587/AdvancedRocketry#853]
When building the space elevator and right clicking the space elevator block to complete it, the game places the light blue background of the skybox over my FOV. Screenshots show all of the elements of game rendering with some issues (see screenshot)
![2017-09-19_12 27 03](https://user-images.githubusercontent.com/799384/30606108-34faee48-9d36-11e7-9aba-6ec64dcfe91b.png)
The light blue in my overlays is the color that appears over everything.
Upon breaking the multiblock, everything returns to normal. Additionally, I can the world around me if I look away from the multiblock.

I running MC 1.10.2 with Forge 12.18.3.2316 and your mods AdvancedRocketry-1.10.2-1.2.2 and LibVulpes-1.10.2-0.2.5-universal

**Comment by Smtgr14** [comment]
It seems to do this when scanning/building a rocket. Breaking the rocket assembler makes everything fine again.

**Comment by Smtgr14** [comment]
Seems related to #826 but no solution or cause was documented

**Comment by zmaster587** [comment]
Would it be possible to get a complete mod list, and have you checked to see if this occurs with only AR and libvulpes installed?

**Comment by Smtgr14** [comment]
I've checked, vanilla + AR and libvulpes works fine. I'm using the mods from skyfatctory 3 (sans decocraft)
Any idea which mods interfere?

**Comment by Smtgr14** [comment]
It's BetterFPS. Removing it make the issue vanish.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
