### ISSUE TITLE
Planet Template page is down, was up just yesterday.

### ISSUE THREAD

**Issue by ShayminKeldeo421** [zmaster587/AdvancedRocketry#855]
Wanted to create a custom planet, went to the link given in the guide and it just leads to a "Not Found" page. Is there anywhere else I can download the file? https://github.com/zmaster587/blob/master/Template.xml/

**Comment by dmodoomsirius** [comment]
https://github.com/zmaster587/AdvancedRocketry/blob/master/Template.xml
