### ISSUE TITLE
Infinite flying with jetpack

### ISSUE THREAD

**Issue by Janrupf** [zmaster587/AdvancedRocketry#856]
On a 1.7.10 Server (Forge, FTB Infinity) I'm able to fly infinitly. Using the Jetpack, setting it in hover mode, turning it off and there you go. Now you can fly infinitly.

**Comment by zmaster587** [comment]
What version of AR and libvulpes are you using?

**Comment by Janrupf** [comment]
Im not sure about libVulpes (gonna edit this when I have acess to the files) but AR-1.2.2

**Comment by Janrupf** [comment]
Looks like #177

**Comment by Janrupf** [comment]
Closing this, has been to long and its a duplicate, never mind.
