### ISSUE TITLE
[Suggestion] O2 detection block

### ISSUE THREAD

**Issue by DarkGuardsman** [zmaster587/AdvancedRocketry#86]
Could also be a gas detection block in general. Would be useful to detect the level of O2 in an area to sound alarms or lock down areas.  Though this would be done using redstone controlled by GUI settings.

**Comment by zmaster587** [comment]
Oxygen detection block added in 4e1cedf89ec37ef01846b0a15834a9d3f08ac4c2 groundwork for general gas detection block laid
