### ISSUE TITLE
Giving yourself a Data Storage Unit with a DataType higher than 6 crashes the game when mousing over it.

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketry#860]
In Creative mode, I'd rather not build a sattelite and send it into orbit just to get data to test the Observatory or Astrobody Data Processor, so I gave myself a chip using commands. However, giving yourself a chip with a data type over 6 will crash the game with a `java.lang.ArrayIndexOutOfBoundsException` when mousing over it, because it doesn't know what to put in the description.

**Comment by dmodoomsirius** [comment]
Are you able to either gist.github.com or pastebin the crash report that will help Zmaster determine what caused the crash as well as the Minecraft version and LibVulpes version?

**Comment by C1ffisme** [comment]
The issue is pretty obvious, but here's the crash report: https://gist.github.com/C1ffisme/3194c80e07270f4c0861d5cf36e7724e
