### ISSUE TITLE
Commands For Mod Not Showing

### ISSUE THREAD

**Issue by dabestchicken** [zmaster587/AdvancedRocketry#863]
Im using the most recent version of the tommy-tek modpack which has version 1.7.10-1.2.2 of Advanced Rocketry on it. All of the commands listed on the site are showing up as unknown commands. If anyone has any suggestions please  let me know how to get them  working.

**Comment by zmaster587** [comment]
Is this on a server?  If so, are you op?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
