### ISSUE TITLE
NullPointerException in Modpack

### ISSUE THREAD

**Issue by BranTuna** [zmaster587/AdvancedRocketry#866]
Crashes on startup, running Version 1.2.2 for 1.7.10.
[Pastebin](https://pastebin.com/iPRjnzJ1)

**Comment by zmaster587** [comment]
Looks like something broke in one of the XML recipes.  Can you upload the xml for the recipies and/or a copy of the server startup log.  In the meantime I'll work on more graceful handling in the case of a failure to load.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
