### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by KrauzeBartek** [zmaster587/AdvancedRocketry#868]
Can you fix this ?
1.11.2
![2017-10-08_11 50 03](https://user-images.githubusercontent.com/29304275/31315746-df49f35c-ac1e-11e7-8ae6-0e2e7858fb3e.png)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by drhaber** [comment]
I have noticed this issue as well [Mod List for convenience](https://pastebin.com/8YL5z4TM).
