### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by KrauzeBartek** [zmaster587/AdvancedRocketry#869]
1.11.2
13.20.1.2510
Machines doesn't work

**Comment by Janrupf** [comment]
Please provide more Information! What are you trying to do? What exactly fails?

**Comment by KrauzeBartek** [comment]
Machine form holoprojector doesn"t work. They have power, material, they have set on.

**Comment by KrauzeBartek** [comment]
![image](https://user-images.githubusercontent.com/29304275/31462981-c81aa61a-aece-11e7-92bb-712984deab80.png)

**Comment by KrauzeBartek** [comment]
![image](https://user-images.githubusercontent.com/29304275/31462994-d357943e-aece-11e7-985f-be2948213d26.png)

**Comment by zmaster587** [comment]
What item is that?  Is vanilla wood processing disabled?  Did you change any of the recipe configs?  If you take it out and put it in does it work?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
