### ISSUE TITLE
[1.12.2 Maven Build 6] Ticking Crashes after 5 - 10 Minutes uptime of the Server

### ISSUE THREAD

**Issue by D3nnis3n** [zmaster587/AdvancedRocketry#870]
After upgrading from Version 5 / 4 to 6 / 5 we get crashes like These every 5 - 10 minutes. After removal of Advanced Rocketry These are no longer occuring.

> Time: 10/8/17 8:55 PM
> Description: Exception in server tick loop
> 
> java.util.ConcurrentModificationException
> 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
> 	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
> 	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:748)

> Time: 10/8/17 8:35 PM
> Description: Exception in server tick loop
> 
> java.util.ConcurrentModificationException
> 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
> 	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
> 	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
> 	at java.util.HashMap.putMapEntries(HashMap.java:511)
> 	at java.util.HashMap.<init>(HashMap.java:489)
> 	at mekanism.api.transmitters.TransmitterNetworkRegistry.assignOrphans(TransmitterNetworkRegistry.java:136)
> 	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101)
> 	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:93)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_666_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:748)

> Time: 10/8/17 8:30 PM
> Description: Exception in server tick loop
> 
> java.util.ConcurrentModificationException
> 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
> 	at java.util.ArrayList$Itr.next(ArrayList.java:851)
> 	at levelup2.skills.crafting.FurnaceEfficiencyBonus.doFurnaceTicks(FurnaceEfficiencyBonus.java:114)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_957_FurnaceEfficiencyBonus_doFurnaceTicks_WorldTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by Thutmose** [comment]
Hmm, does advanced rocketry make/remove mobs or tile entities asyncronously?  

if it does, then it could be related to this issue, I have not seen this occur on my testing server, though I don't have mechanism or levelup.

**Comment by D3nnis3n** [comment]
Well, the Crash Reports state something else every Crash. It's never the same. Sometimes no mod at all is mentiones, other times it's a different one every time. I'm even still not exactly sure it is AR causing this. I will Keep the Server up for some hours to see if it really does no longer occur with AR uninstalled. For sure, i can only say, that These crashes did no longer occur every 5 - 10 minutes until now. But maybe one Comes by in the next hours. I'll Report back and see what other mods could be the cause. I updated only three mods today. Can't be too hard to find out. Unfortunatley those logs are so short and no real Crash Reports like i usually get. I don't even exactly understand what causes the Problem so i just started removing the last mod i updated and until now, no more crashes. Let's see what happens next.

**Comment by Thutmose** [comment]
ok, if it ever points at an event handler for a known open source mod, post the log section for that, as it might help narrow down the cause, it should at least make it known what list is being interacted with when the crash occurs.

Infact, if you could collect all of the log sections for this, it would be very helpful for figuring out the cause, as it should be something similar between all of them,-

**Comment by D3nnis3n** [comment]
Mekanism is open source: https://github.com/aidancbrady/Mekanism
Levelup is also: https://github.com/BeetoGuy/LevelUp2

**Comment by Thutmose** [comment]
the levelup2 error is a tickable tile entity being added or removed async.
the mekanism error is a TileEntityTransmitter being added or removed async.

This seems to indicate that something is definitely adding tile entities from a seperate thread. maybe @zmaster587  might know where that might be occuring in advanced rocketry or libvulpes?

**Comment by D3nnis3n** [comment]
I just had another Crash like that. Advanced Rocketry was installed again. It had about 26 different mods in it's log with ASM: before. Everytime it had to do something with a tick. Unfortunatley it did not get saved as Crash Report. I hope it occurs again, so i can copy it out of the console.

**Comment by D3nnis3n** [comment]
I have some suspicion that is really weird. I believe it occurs when LevelUp AND Advanced Rocketry is installed. If one of both get's removed the crashes seem to stop. This will take a lot of Investigation tonight as for which mod really is the reason. I still can't really say it definatley is one of both. I also suspect Animania or Ultimate Cars. But removing those did not end the crashes. It's so hard for me to track down, as i'm no developer and can't understand the logs.

**Comment by D3nnis3n** [comment]
I'm pretty confident it's caused by LevelUp2. I had crashed from that before Advanced Rocketry as i saw in my log, but they were very rare. I'll open an issue over there and link it to here. If i'm wrong i get slapped by two developers - but what should i do. Something, somewhere is going terribly wrong and i've got no idea how to find out exactly where.

https://github.com/BeetoGuy/LevelUp2/issues/17

**Comment by Thutmose** [comment]
ok, hopefully they can find somewhere they do async interactions with tile entities, I can see about trying to search through AR and LibVulpes code for it, so far not found anywhere that looks suspicious

**Comment by D3nnis3n** [comment]
Server is still running after LevelUp being removed. I'm confident i found the right cause. Hopefully. I hate that no real Crash Reports are generated. Should i Report that over in forge, too? They're creating the Reports, aren't they?

**Comment by Thutmose** [comment]
not sure, is the server crashing or just hanging? I thought it should produce a report every time it actually crashes...

**Comment by D3nnis3n** [comment]
It crashes out. You get the "Server closed" message and the Server writes "considered crashed" and Ends the script.

**Comment by D3nnis3n** [comment]
Stil no Crash. I consider it not being caused by AR. So either the LevelsUp Update yesterday made the crashes Happening more often or it has some Kind of Problem with AR. I think it's the first Option. But it didn't Crash this night before i had AR installed. I discovered the maven today. Do you mind if i let this issue open until the LevelUp author replies and can confirm it's caused by him?

**Comment by D3nnis3n** [comment]
Oh noes:


> [23:59:57] [Server thread/ERROR]: Encountered an unexpected exception
> java.util.ConcurrentModificationException: null
>         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_131]
>         at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_131]
>         at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290) ~[ol.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777) ~[MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> 

I'm burned out. What the fuck is Happening there?

**Comment by D3nnis3n** [comment]
And another one:

> [00:23:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@408cb32a:
> java.util.ConcurrentModificationException: null
>         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_131]
>         at java.util.HashMap$EntryIterator.next(HashMap.java:1471) ~[?:1.8.0_131]
>         at java.util.HashMap$EntryIterator.next(HashMap.java:1469) ~[?:1.8.0_131]
>         at java.util.HashMap.putMapEntries(HashMap.java:511) ~[?:1.8.0_131]
>         at java.util.HashMap.<init>(HashMap.java:489) ~[?:1.8.0_131]
>         at mekanism.api.transmitters.TransmitterNetworkRegistry.assignOrphans(TransmitterNetworkRegistry.java:136) ~[TransmitterNetworkRegistry.class:?]
>         at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101) ~[TransmitterNetworkRegistry.class:?]
>         at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:93) ~[TransmitterNetworkRegistry.class:?]
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_652_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
>         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
>         at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264) [FMLCommonHandler.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> [00:23:21] [Server thread/ERROR] [FML]: Index: 8 Listeners:
> [00:23:21] [Server thread/ERROR] [FML]: 0: NORMAL
> [00:23:21] [Server thread/ERROR] [FML]: 1: ASM: class blusunrize.immersiveengineering.common.blocks.BlockIETileProvider onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 2: ASM: com.minecolonies.coremod.event.FMLEventHandler@74851d50 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 3: ASM: net.minecraftforge.common.ForgeInternalHandler@1275386f onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 4: ASM: thut.api.entity.ai.AIThreadManager@2c86da3e tickEventServer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 5: ASM: noppes.npcs.ServerTickHandler@455cd393 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 6: ASM: radixcore.core.RadixEvents@200d5304 serverTickEventHandler(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 7: ASM: fi.dy.masa.worldutils.event.TickHandler@422af1da onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 8: ASM: Network Registry:
> [] onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 9: ASM: li.cil.oc.common.EventHandler$@798fe321 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)Ljava/lang/Object;
> [00:23:21] [Server thread/ERROR] [FML]: 10: ASM: li.cil.oc.common.asm.SimpleComponentTickHandler@24147b8f onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 11: ASM: li.cil.oc.common.item.Tablet$@16bec191 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 12: ASM: codechicken.chunkloader.handler.ChunkLoaderEventHandler@15d7bbe3 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 13: ASM: org.blockartistry.DynSurround.server.services.ServiceManager@3eed2255 tickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 14: ASM: org.dynmap.forge.DynmapPlugin$ForgeServer@3856b46a tickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 15: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@1f4a54f2 tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
> [00:23:21] [Server thread/ERROR] [FML]: 16: LOWEST
> [00:23:21] [Server thread/ERROR] [FML]: 17: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [00:23:21] [Server thread/ERROR]: Encountered an unexpected exception
> java.util.ConcurrentModificationException: null
>         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_131]
>         at java.util.HashMap$EntryIterator.next(HashMap.java:1471) ~[?:1.8.0_131]
>         at java.util.HashMap$EntryIterator.next(HashMap.java:1469) ~[?:1.8.0_131]
>         at java.util.HashMap.putMapEntries(HashMap.java:511) ~[?:1.8.0_131]
>         at java.util.HashMap.<init>(HashMap.java:489) ~[?:1.8.0_131]
>         at mekanism.api.transmitters.TransmitterNetworkRegistry.assignOrphans(TransmitterNetworkRegistry.java:136) ~[TransmitterNetworkRegistry.class:?]
>         at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101) ~[TransmitterNetworkRegistry.class:?]
>         at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:93) ~[TransmitterNetworkRegistry.class:?]
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_652_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
>         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
>         at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264) ~[FMLCommonHandler.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) ~[MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> 

Could this even be a forge issue with the newest 2509? I'm through every updated mod. None is causing this alone.

**Comment by Thutmose** [comment]
try reverting to forge 2503, that is what I am testing on and not seen anything like this occur

**Comment by D3nnis3n** [comment]
Yep, that is the last idea i had. I'll do this now.

**Comment by Thutmose** [comment]
hmm, looking at forge changelog, I don't see anything that should cause this... though maybe something did, see if it still happens on 2503

**Comment by D3nnis3n** [comment]
Yeh, but that brought me to another mod, that might be the issue. Because it justed fucked up my world after more testing. I'll Need some more time to see what's Happening here and will then come back to you and the Levels Dev to Close the issues or post my findings.

**Comment by D3nnis3n** [comment]
I hope to have found the mod causing the issue. Downgrading forge didn't do anything. If not, i'll throw my PC out of the Windows. For now, im fucking tired and going to bed. Thanks for the ideas, even though, most likely, this mod is not causing this issue at all. But i still can't come around to say it really happend much more often when both your and Level ups mod was installed. This might be completley random - as the Crash Messages are. :/

**Comment by D3nnis3n** [comment]
@Thutmose 
But i may got another funny bug for you:
When Advanced Rocketry is installed, your Elevator mod bugs out, you can no longer walk into Elevators (invisible wall) and fall through the ground, if you somehow managed to get into it. Remove Advanced Rocketry and it works again. You might want to try yourself, before i even open an issue that is invalid.

**Comment by Thutmose** [comment]
I will try to look into the elevator collision issue tomorrow, I have both AR and my elevators in my testing pack so I should be able to look into it

**Comment by D3nnis3n** [comment]
Alright. The issue i get is, when advanced rocketry is installed and you create an Elevator like usual you are blocked from entry, like a wall of air. You can manage to sneak into it if you try hard or you can get inside, when you were already Standing inside while creating the Elevator. If you stood in the Elevator while creating you will instantly fall through the bottom of the Elevator on which you are usually supposed to be able to stand.

As for the Issue with the Controller Disguise i can confirm removing FoamFix will fix that issue. It seems like foamfix restricts block updates to a lower Count, so it's more performant. As soon as a block is placed beneath it, the Controller changes it's design. Or you can relogin. So this is no bug with your Elevators and i can live with that as foamfix cuts RAM usage in half - which is pretty OP.

**Comment by D3nnis3n** [comment]
As the Server is now running five hours without Crash i consider this not caused by AR (as you sureley did, too) at all and close it, so it's gone from the real issue list. We can talk, anyway.

**Comment by D3nnis3n** [comment]
Seems i got nailed it down. Yeha.

**Comment by D3nnis3n** [comment]
@Thutmose 
Did you have time to check the Elevator issue?

**Comment by Thutmose** [comment]
not yet, might have time to check tomorrow

**Comment by D3nnis3n** [comment]
Seems, you haven’t got time yet, do you? :D

Gesendet von Mail für Windows 10

Von: Thutmose
Gesendet: Mittwoch, 11. Oktober 2017 16:57
An: zmaster587/AdvancedRocketry
Cc: D3nnis3n; State change
Betreff: Re: [zmaster587/AdvancedRocketry] [1.12.2 Maven Build 6] TickingCrashes after 5 - 10 Minutes uptime of the Server (#870)

not yet, might have time to check tomorrow

**Comment by Thutmose** [comment]
Nope not had time to check it yet

**Comment by Thutmose** [comment]
just tried making an elevator, and it works as intended, so not sure what the issue is, if you can get video of it or something, can you post an issue on my issue tracker about it?

**Comment by D3nnis3n** [comment]
Can you recommend me a Software that will make me short Videos that are SMALL to upload? I do not have any experience with making Videos :O

Gesendet von Mail für Windows 10

Von: Thutmose
Gesendet: Sonntag, 15. Oktober 2017 17:08
An: zmaster587/AdvancedRocketry
Cc: D3nnis3n; State change
Betreff: Re: [zmaster587/AdvancedRocketry] [1.12.2 Maven Build 6] TickingCrashes after 5 - 10 Minutes uptime of the Server (#870)

just tried making an elevator, and it works as intended, so not sure what the issue is, if you can get video of it or something, can you post an issue on my issue tracker about it?

**Comment by Thutmose** [comment]
not sure, I usually use OBS or the built in windows video recorder thingy, but neither of them are "small" unless you use a really tiny screen for minecraft
