### ISSUE TITLE
Acceleration is m/s², not m/s.

### ISSUE THREAD

**Issue by purpleposeidon** [zmaster587/AdvancedRocketry#871]
Literally unplayable.

**Comment by C1ffisme** [comment]
Do most of the Minecraft fonts support the Unicode "²"?

**Comment by Thutmose** [comment]
if not, could use m/ss instead :D

**Comment by C1ffisme** [comment]
@Thutmose I suppose you could do m/s^2, but that just looks ugly. m/ss is technically correct, but I feel like "ss" could be interpreted as a different kind of unit, rather than second times second. (I couldn't find any metric prefixes that used an s, though.)

**Comment by zmaster587** [comment]
could do m/s*s as well
