### ISSUE TITLE
Can't get off my rocket when landed and everything is ¨frozen¨ around me.

### ISSUE THREAD

**Issue by MajorLOLGaming** [zmaster587/AdvancedRocketry#872]
the tittle explains it all

![2017-10-09_16 32 45](https://user-images.githubusercontent.com/32457983/31343352-b1582742-ad0f-11e7-9d06-72b15a11604f.png)
So... What did i do wrong? Do you need a log too?

**Comment by zmaster587** [comment]
is this in single player or multiplayer, are there any other mods installed?  And a log might be helpful.  It sounds just like the server or integrated server may be overloaded though.

**Comment by azmicomico** [comment]
This happens to me every time I go to a planet with a rocket. If the landing site is not chunk loaded, the above happens. If you save and quit to the main menu and reload again, you show up inside the rocket on the planet surface.

The logs don't show any error or other message when this happens.

This is on single player, MC 1.10.2 and the integrated server doesn't show any signs of being overloaded.

**Comment by MajorLOLGaming** [comment]
Its single player and i cant acces my log on my phone

**Comment by jrunestone** [comment]
I've only just started with this mod and my first rocket launched fine, but after transitioning to space and about to land on the moon I get the exact same issue. I then launch back to earth (same glitchy/jerky behavior) and when landed, it kills me.

I'm running 1.10.2 with 80 mods, my log DOES however mention the following on each rocket trip:

> [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3984ms behind, skipping 79 tick(s)

TBH not really encountered that before, what would be the solution?

**Comment by zmaster587** [comment]
@jrunestone 3984ms is nearly 4 seconds between ticks, so it definatly looks like a lag issue.  You may want to consider running a tool like visualVM to see what' taking up most of the tick time.  Unfortunatly there's not much I can really say other than that without more info as to what is actually eating all that time.

@azmicomico Is there something in particular you can do to make it occur?  I've not been able to replicate on my end.  Does this occur with only advanced rocketry and libvulpes installed?

@MajorLOLGaming You can still have lag in singleplayer, usually occurs when there's too much going on in the world, and If you can send the log when you get a chance that may help.  And like i said with azmicomico, does it continue to occur without mods?

**Comment by jrunestone** [comment]
@zmaster587 Thanks, yeah after researching a bit more I think this is just a result of too much crap lying around... I'm going to try without BoP and maybe bump up the memory. As far as I'm concerned this issue isn't really about advanced rocketry on its own.

**Comment by azmicomico** [comment]
It happens randomly with a high chance of failure. I've not found a sure way to always happen.

I cannot replicate with just Advanced Rocketry and libVulpes installed. I guess I'll continue saving and quitting when it happens.

**Comment by gdarai** [comment]
First be patient when generating new dimension.
I for exampl have a SkyLands dimension, which is almost entirely generated on entry and it takes Advanced Rocketry good 2 minutes and ful power of all 8 cores before the dimension is generated and the rocket descents to the surface.

So, just don't haste, sit ight and wait. The rocket Should start descending eventually.

**Comment by zmaster587** [comment]
@azmicomico you might be able to make some headway with visualvm, if you run a CPU profile on the world as it's frozen for a minute or two then create a snapshot.  If you browse the server thread and use the hotspot tab, you'll likely find out what's going on I think.

**Comment by azmicomico** [comment]
@gdarai and @zmaster587 The world/game is not frozen when it happens and the dimension is already generated. See the original poster screenshot. You can see the terrain below, but there's no rocket. CPU usage doesn't increase at this time. The message to descend appears and it starts descending if you press space. The altitude changes in the altimeter, but the Y level doesn't and when it lands, the message changes to 'take off'. Pressing left shift to dismount at that time does nothing.

**Comment by zmaster587** [comment]
@azmicomico can you find the minium set of mods to replicate the issue and verify whether or not this occurs in more recent builds?

@azmicomico It's hard to tell, if the server freezes on the first tick, the altimater reads 0 (default state) and the terrain from the world the player was coming from continues to display until the new terrain generates (the image isn't flushed on dim transfer).

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by MajorLOLGaming** [comment]
I don't think this is an issue anymore
