### ISSUE TITLE
Chemical Reactor

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#874]
Version：AR 1.2.3+libvulpes 0.2.5 in MC 1.11
![2017-10-17_12 46 37](https://user-images.githubusercontent.com/23413915/31652392-7eb037b0-b351-11e7-9a39-a677b4ae7d50.png)
I put draconic armor in the chemical reactor and provide RF and opened the reactor，but I can't get airtight enchantment。

**Comment by forestbat** [comment]
![2018-01-05_14 59 24](https://user-images.githubusercontent.com/23413915/34598919-7d83a38c-f22a-11e7-8143-1e88d3c77ea7.png)
I still can't get airtight and it has new mistake，a reaper enchantment of DE。
And upgrades of the draconic legging still disappeared in chemical reactor。

**Comment by zmaster587** [comment]
Can you try changing the AR spacebreathing enchant to a different ID in the config?  I'm suspecting a possible conflict and try this again?

**Comment by zmaster587** [comment]
Cannot replicate in 1.11.2-1.2.5a-63.jar

**Comment by Cryptic318** [comment]
Playing FTB Revelation 1.8 (AR version 1.4.0.-67) and having the same issue - Draconic armor, diamond and tank in the chemical reactor does nothing but wipe my upgrades and enchantments and gives no "Airtight Seal'.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
