### ISSUE TITLE
Client crash on opening Guidance Computer on built rocket ship

### ISSUE THREAD

**Issue by MarkusGordathian** [zmaster587/AdvancedRocketry#877]
Mod Version: 1.2.2
Minecraft Version: 1.10.2
Misc. Info: Added into FTB Beyond along with Integrated Dynamics and Integrated Tunnels

When attempting to access the Guidance Computer by Shift+RClicking the rocket ship, I can see the GC GUI and then my game immediately freezes/crashes. The first 2 times I encountered this bug, my client stopped responding for around 30 seconds until I killed it. The third time, it crashed to the main menu.

The Guidance Computer contained a Planet ID Chip for Luna. After disassembling and rebuilding the rocket, I can open the Guidance Computer just fine.

[Here](https://hastebin.com/ekepivafoy.txt) is Minecraft's log relevant to the crash.

**Comment by dmodoomsirius** [comment]
Does this only happen with Advanced Rocketry and LibVulps? As i do not see anything in the crash report that pertains to Advanced rocketry?

**Comment by doormanorman** [comment]
My game is crashing immediately upon loading. The initial crash happened just as I put a programmed sattelite chip in, then (accidently) sat in the rocket.

Also occasionally disconnecting me when opening the guidance computer menu.

Terrain doesn't load before game crashes, so now I'm stuck restarting over and over hoping I get a split second to hop off the rocket..

This mod is getting on my nerves. 

(1.10.2)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by doormanorman** [comment]
That was so long ago I'm not sure. The main issue I had with advanced
rocketry ended up being the oxygen vents.

Despite being surrounded by solid blocks (in a very small area even), with
a new carbon filter and supplied with plenty of power, they would either
work, then stop working, or they would never start working in the first
place.

Not sure if that's an issue that has been fixed or not as I haven't played
recently, but it was rather problematic.

**Comment by se7enek** [comment]
Still happening apparently so reopen possible?

http://se7en.pl/upload/1597664678.mp4

**Comment by jhardin2121** [comment]
Hello, I am having the exact same issue as the OP. I am currently playing MC Eternal on a server with 2 other poeple. 

Upon clicking on the guidance computer on my built rocket to put in the ID chip, my game immediately crashes and takes me back to the main menu.

**Comment by Logan-Baker63** [comment]
I'm also having this very disappointing problem. I've been playing MC Eternal with a couple friends on a server together and have put in insane effort to get a rocket up and running, only to find that when I open the guidance computer on my rocket, the game crashes. Every time it crashes it blames a different mod for the issue. When I encountered this issue it was a huge bummer and so I gave up and focused on other mods instead. Please fix because otherwise mod unplayable.
![image](https://user-images.githubusercontent.com/71262374/105575592-ac3f5a80-5dbc-11eb-8a7b-1c21aac4a9e5.png)

**Comment by Zafouche** [comment]
Hello, is there any way to fix it now ?

**Comment by Zafouche** [comment]
> Does this only happen with Advanced Rocketry and LibVulps? As i do not see anything in the crash report that pertains to Advanced rocketry.

Is it possible to reopen this issue ? it is still a problem in the modpack

**Comment by linkcool200** [comment]
I have located a temporary solution.  If you have a fuel loader placed down, pick it up and then open the guidance computer.  This at least, worked for me.  It does not matter if the two devices are linked, merely having it placed down seems to be part of the problem.

**Comment by voidsong-dragonfly** [comment]
Two things. # 1, We don't support 1.10.2 anymore. # 2, If this is still happening in 1.12, I would like you to make a new issue and report it for the correct version, with another log.
