### ISSUE TITLE
[1.12.2-1.2.3] Missing model for Lightwood planks

### ISSUE THREAD

**Issue by Lykrast** [zmaster587/AdvancedRocketry#880]
I think this screenshot should speak for itself :
![image](https://user-images.githubusercontent.com/8684850/31892605-c0e763f8-b809-11e7-9b16-1fecd14c541b.png)

Got it from the creative tab, has missing texture for both the item and the block.

**Comment by zmaster587** [comment]
Looks like an issue in 1.11 too
