### ISSUE TITLE
[1.12.2] Precision Assembler gets 0 tick completion time, which prevents it from running properly

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#881]
It seems that some of the recipes on the precision assembler do not output correctly to the output hatches.

I put the required materials in here: 
![image](https://user-images.githubusercontent.com/2363472/31916598-7a99bf14-b821-11e7-9eb9-196a6225207f.png)
The machine runs, the items are consumed, however nothing shows up in output: 
![image](https://user-images.githubusercontent.com/2363472/31916619-9727108c-b821-11e7-82d2-c85f8a57e581.png)
If I use an ingame nbt editor on the precision assmbler block itself however: 
![image](https://user-images.githubusercontent.com/2363472/31916644-b418e076-b821-11e7-825c-668aa6388671.png)
it has the item there, but no way to extract it that I know of.

**Comment by Thutmose** [comment]
here is the assembler setup:
![image](https://user-images.githubusercontent.com/2363472/31916720-19b79062-b822-11e7-96bf-06e6b0022ba6.png)
![image](https://user-images.githubusercontent.com/2363472/31916726-24bc52e0-b822-11e7-91d3-b208a2a19a15.png)

I should also note that it seems to be rather fast when done with titanium coils and motors, it ends up as a 638x speed multiplier:
![image](https://user-images.githubusercontent.com/2363472/31916749-42fdc810-b822-11e7-9eba-592e6c2d9c49.png)

**Comment by Thutmose** [comment]
Looked into it, found where the problem is:

The speed being that high, makes completionTime be 0 ticks (as seen in the nbtedit screenshot), this then means that TileMultiPowerConsumer.isRunning() will return false, which means it never gets to the code which will complete the recipe.

Any idea why the multiplier gets so high for this block? and there should probably be a capped minimum run time of 1 tick for the machines

**Comment by Thutmose** [comment]
The simple fix for this would be to add a max of 1 here:
https://github.com/zmaster587/libVulpes/blob/1.12/src/main/java/zmaster587/libVulpes/tile/multiblock/TileMultiblockMachine.java#L471

however that won't fix the fact that the assembler gets such a high multiplier, is that intended? if so, I will send a PR with the max of 1 there, I will wait for your response though.

**Comment by zmaster587** [comment]
I'll check on the multiplier, it shouldn't be anywhere near that high.  It may have to do with the fact speed is multiplicive, not additive and the prescision assembler has a lot of blocks it takes into account.  But 600x is definately a bit high.

**Comment by zmaster587** [comment]
There's the problem:
![image](https://user-images.githubusercontent.com/3536685/32086543-fdb85a8e-baa3-11e7-87fe-7b1ced226306.png)

where can i get this "Aluiminum" and how many versions of AR back does this go...

**Comment by Thutmose** [comment]
Heh, I had tried looking at that section, but didn't notice anything wrong with "Aluminium"

**Comment by zmaster587** [comment]
Iridium was broken too apparently XD

**Comment by zmaster587** [comment]
Should be fixed now
