### ISSUE TITLE
Crash During Client Startup

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#885]
Hello,

I just installed AR and LV in my 1.12.2 pack and have been getting this crash on load:
https://pastebin.com/BreGwz0V

MC: 1.12.2
Forge: 2515
LibVulpes: 0.2.6
Adv. Rocketry: 1.2.3

Thanks!
Darkosto

**Comment by zmaster587** [comment]
Rolling machine trying to add a recipe where no plate exists for the corresponding ingot in mod compat.
disabling allowMakingItemsForOtherMods should fix it in the meantime.  There'll be a build on the jenkins within the next 24 hours with a patch.
