### ISSUE TITLE
Z-Buffering issue on Observatory Model

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketry#890]
![2017-10-28_15 00 10](https://user-images.githubusercontent.com/9893266/32138036-58834b88-bbf1-11e7-9eef-1187d9887257.png)

(You may need to zoom into the image to see the problem. There are multiple dots on the observatory screen if you look closely. These are a bit more apparent in-game, especially whilst moving.)

Obviously this is a pretty minor issue, but I thought I would bring it to attention.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
Cannot confirm the issue in the latest 1.12.2 :+1:
