### ISSUE TITLE
Glowing Mushroom doesn't look correct in Creative Inventory

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketry#891]
![2017-10-28_15 02 48](https://user-images.githubusercontent.com/9893266/32138067-5c3b0832-bbf2-11e7-8629-952c76277bf8.png)

The Mushroom appears to be rendered in the inventory, rather than using the actual texture.

**Comment by zmaster587** [comment]
Which version of the mod and minecraft?

**Comment by C1ffisme** [comment]
This is 1.10.2, using version 1.2.2.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment]
![2019-03-03_19 06 39](https://user-images.githubusercontent.com/9893266/53705079-81724480-3de7-11e9-9517-c0a7e78a706c.png)

Can confirm
