### ISSUE TITLE
[1.12.2] Fueling Station crashes when inserting Forestry Cans

### ISSUE THREAD

**Issue by Lykrast** [zmaster587/AdvancedRocketry#892]
Minecraft Version: 1.12.2
-
Forge Version: 14.23.0.2515
-
LibVulpes Version: 0.2.6
-
Advanced Rocketry Version: 1.2.3
---------------------
Crash Report: https://pastebin.com/yJG4mLsQ
----------
Putting Forestry Cans filled with Rocket Fuel into the Fueling Station causes the game to crash.

My guess is that it doesn't properly handle the fact that Cans don't give an item when emptied.

**Comment by zmaster587** [comment]
I think your guess is spot on
