### ISSUE TITLE
[1.12.2] Block Shift Issue

### ISSUE THREAD

**Issue by Darkosto** [zmaster587/AdvancedRocketry#899]
Minecraft Version:
1.12.2
Forge Version:
2517
LibVulpes Version:
0.2.6

Advanced Rocketry Version:
1.2.5
*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
Crash Report:
----------
Explain issue in detail:

Hello,

I've added the latest version of Advanced Rocketry to my world (first time the world has been opened with the mod) and got a warning from forge that the level.dat file has been corrupted. I created a backup copy and loaded the world up to find ALL modded blocks had been shifted. I removed A.R. to see if it was the cause and sure enough the blocks were not shifted in another world. This is quite a large issue to ignore on my end since it corrupts any existing world.

What logs would be most helpful for you to take a look at this issue?

Thanks,
Darkosto

**Comment by Thutmose** [comment]
It is related to the Halloween event thing, same error corrupted an entire world of mine last night, a temporary workaround is to disable the seasonal events in configs (I also set the pumpkin biomeid -1 to stop that trying to register as well)

**Comment by Darkosto** [comment]
I tried again with those options disabled and it still corrupted the backup world I tested. I guess I'll have to wait until tomorrow.

**Comment by Thutmose** [comment]
Hmm I hope mine doesn't corrupt anymore then, it had swapped a large number of modded blocks...

**Comment by zmaster587** [comment]
Startup log for when it broke would likely be helpful.  Only real change was a biome was added and it worked no problem when I was testing it over the last 2 days.  I'm not sure it really matters though, I'm probably just going to remove the feature entirely since Halloween is over anyway.

**Comment by Thutmose** [comment]
in my case it was during some other testing things, so there were about 20-30 things wrong at the time, it took me a while to figure out that AR was responsible for some of it, so not sure which of the hundred logs or so it will be in, the only error I saw related to it was an NPE somewhere after here:
https://github.com/zmaster587/AdvancedRocketry/blob/1.12/src/main/java/zmaster587/advancedRocketry/AdvancedRocketry.java#L2050

**Comment by zmaster587** [comment]
Only thing I can possibly think of is that somehow getStar(0) returns null.  Though since stars are registered before that and in order, i don't know

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
