### ISSUE TITLE
[Suggestion]Allow customization of machine recipes via minetweaker

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#9]
Since there are tons of awsome multiblock machines in this mod I'd like to use them to process stuffs from other mods.
Sorry about dumping so much issues in a short time XD

**Comment by zmaster587** [comment]
Rather know about them than not XD
I'll look into minetweaker support, won't be a high priority but when things slow down...

**Comment by Tsyklop** [comment]
@zmaster587 it's a pity. Mod just great. I wanted to put on my modpack but without the support of MT .....

**Comment by zmaster587** [comment]
@Tsyklop I did not say I wasn't adding support for it, I'm just saying I do not have time right now to do so, and other things such as power support for other mods, oxygen systems, and fuel processing is a bit more important.  I would also like to mention that putting it in a modpack now is probably not the best idea as the mod is not really stable, hence why it is listed as alpha.

**Comment by zmaster587** [comment]
Probably actually going to go with an XML system in the future, would be more robust
