### ISSUE TITLE
[question/possible bug] Gasmining mission setting

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#900]
Minecraft Version:
1.10
Forge Version:
12.18.3.2511
LibVulpes Version:
0.2.6

Explain issue in detail:
I tried to make gas mining mission work, but it does not, and I am not sure, what all to set up. Let's say I want to mine AdvancedRocketry Nitrogen. I need to know: If I will do all of the following steps it still does not work. Why and what I did wrongly?

**Partial Answer:** Following steps totally work. What is not working is havig different gases on different planets. Actually **_AdvancedRocketry removes the ```<gas>``` tags from the planets definitions._** Is this bug or expected behaviour? I will test a little bit more, but I am all in for your opinion guys.

1) Set Nitrogen in advancedRocketry.cfg
```
   S:harvestableGasses <
        nitrogen
        cloud_seed
     >
```

2) Set nitrogen as Gas in planetDefs.xml (This step does not work)
```
        <planet name="Red Giant A3 HomeWorld" customIcon="gasgiantred" DIMID="18">
			<artifact>bqmie:icon_item 16</artifact>
            <orbitalDistance>100</orbitalDistance>
			<GasGiant>true</GasGiant>
			<hasRings>true</hasRings>
			<isKnown>true</isKnown>
			<gas>nitrogen</gas>
			<gas>cloud_seed</gas>
            <orbitalTheta>180</orbitalTheta>
            <rotationalPeriod>24000</rotationalPeriod>
            <planet name="Planet A3-1 Home" customIcon="earthlike" DIMID="0" dimMapping="">
                <fogColor>0.5,0.5,0.5</fogColor>
```

3) Build a space station orbiting this gas giant. (This was the first missing bit) It is not enough to be orbitting one of the moons, it has to be the gas giant itself you will have to warp to it even though you built the space station on the orbit of one of the moons.

4) Build a UnmannedVehicle or Drone.... From FuelTanks, Engines, PressurizedTanks and GasIntakes (The builder will not warn you that you don't have tanks or GasIntakes... it is on you to make this right.)

5) Link the Drone with Rocket Monitor and fuel it up.

6) Select wanted gas in the rocket's gui. (Not the launcher, the rocket itself)

7) Press the Launch button.

Well... that does the work. Sort of. Known Issues:
- No Gas Here -  You are not orbitting the giant but some other planet or moon.
- No Gas when the drone returned - You forgetted to add the Gas Intakes
- Extremely long mission time - Not enough Gas Intakes, or too tough setting in the cfg file.

Some illustrative image... This is the first working setting:
![scr01](https://user-images.githubusercontent.com/26735549/32351675-83621128-c01e-11e7-93d7-f14827d413c2.png)

**Comment by gdarai** [comment]
Ok... I have first thing I didn't do... I didn't warped out to be over the gas giant. I was orbitting one of it's moons.

It doesn't seems to be enough.


So new State:
1) Definition of gases in cfg file
2) Adding <gas> tags in planetDefs.cfg
3) Building a space station over the overworld
4) !! Warp to the gas giant even if Overworld was it's moon
5) Build unmanned vehicle from engines, fuelTanks and gasTanks
6) Link to Rocket controller
7) Fuel up...

Observed Problems:
- The planetDefs.cfg inside the save is exact copy of the one in confix EXCEPT it DELETED all the <gas> tags.
- The Drone has correct list of available gases (What is in the cfg file) = in this case only nitrogen
- The drone can be launched (PROGRESS)
- BUT it sreturns empty

So, what am I missing now?

**Comment by azmicomico** [comment]
Do you have Gas Intake blocks on your drone?

**Comment by gdarai** [comment]
Nope... I need some? I'll try and write down the result... thank you.

**Comment by gdarai** [comment]
@zmaster587 I would like to ask for your confirm that you know about this.
**AdvancedRocketry removes the ```<gas>``` tags from the planets definitions.** In the sense that if I have gasses defined in cfg... it is ok, but if I add the ```<gas>``` tag to some planet, and start the game and check in the save folder, the planetDefs there is missing those ```<gas>``` tag.

**Comment by zmaster587** [comment]
The gas tag save handling was broken, sorry about that and the wait, it technically has been keeping proper state in the dat file.
