### ISSUE TITLE
Some systems dosen't work

### ISSUE THREAD

**Issue by JoKangHyeon** [zmaster587/AdvancedRocketry#902]
Minecraft Version:
MC 1.11.2

Forge Version:
-1.11.2-forge1.11.2-13.20.1.2513

LibVulpes Version:
AdvancedRocketry-1.11.2-1.2.4
LibVulpes-1.11.2-0.2.6

Explain issue in detail:
Microwave receiver cannot receive energy.
Unmanned Vehicle collects random gas not selected gas.
Asteroid Mining Rocket not collect anything(with fully charged asteroid chip)

**Comment by Uptobillion** [comment]
1.12as well

**Comment by darkshadow543** [comment]
I am having this issue to, with testing rockets and custom astroids.  I inserted fully researched chip, and the rocket came back with nothing.  I think the rocket might be resetting upon reaching the asteroid.
MC:1.12.2
AR:1.2.5a
Forge: 14.23.0.2538

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
