### ISSUE TITLE
Black Hole System

### ISSUE THREAD

**Issue by bshelden** [zmaster587/AdvancedRocketry#904]
This is a feature request for a non-supermassive black-hole based system.

This should really just come down to a couple mechanics:
- No "day" for any body in the system, since the primary isn't giving off much in the way of light. (Zero if it's not currently accreting).
- A special skybox with a render for the hole.

Something like this: http://rantonels.github.io/starless/ but tuned way down as the only way a system would be inhabitable with a BH in the center is if it's rather quiet.

**Comment by zmaster587** [comment]
Accreting black holes have been added w/ custom render
