### ISSUE TITLE
Custom Planet Configuration 1.12.2

### ISSUE THREAD

**Issue by oliverrook** [zmaster587/AdvancedRocketry#906]
Minecraft Version:
1.12.2
Forge Version:
14.23.0.2512
LibVulpes Version:
0.2.6
*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
Crash Report:
Not Applicable
----------
Explain issue in detail:
Upon adding a new solar system to the config file, the first planet in that new solar system doesn't ever have it's dimension id registered. I've tried multiple dimension ids, including swapping it with ones that worked on a different save. Anything else in the solar system will be fine, including if you add a moon to the first planet, at which point the moon will register, but the planet will not.
I tried using dimension ids 69 ,70, and 100.
Here's my config files:
[planetDefs.txt](https://github.com/zmaster587/AdvancedRocketry/files/1436069/planetDefs.txt)

**Comment by gdarai** [comment]
Very complex issue... can you narrow it down? What is the smallest galaxy you can make which will work wrongly? That is actually something that can tell zmaster a little bit more, little bit faster.

**Comment by zmaster587** [comment]
I know it's been a while, but I do notice that the planet "Liden" has the 'dimMapping=""' tag, this will prevent AR from registering the dimension by design, it's used to compat with dimensions added by other mods such as twilight forest or galacticraft.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
