### ISSUE TITLE
[1.12.2] Satellite Termanal Data display is glitchy

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#907]
Minecraft Version:
- 1.12.2
Forge Version:
- 2517
LibVulpes Version:
- 0.2.6-7
Explain issue in detail:
~~If the sat has more than 1k data, and I press Connect in the satellite terminal, it will fill the 1k buffer for the terminal, and consume all the data in the chip~~
The display for data on the terminal doesn't correctly update to show the actual amount of data in the sat, it seems to glitch starting when the sat is full, and used directly from the full state

**Comment by Thutmose** [comment]
Seems this is actually an error in the gui itself, I put the chip back in, and the data still allowed me to download from connect, and this time it stuck saying 2k data in the sat.

Further clicking connect seems to indicate that the sat is working normally, but the gui isn't
![image](https://user-images.githubusercontent.com/2363472/32305037-5b442526-bf49-11e7-903d-3fb2db7ef6a2.png)
It says 2k, but is currently 0-1 in the sat itself

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
