### ISSUE TITLE
Terraforming process brings TPS down

### ISSUE THREAD

**Issue by azmicomico** [zmaster587/AdvancedRocketry#909]
Minecraft Version:
1.10.2
Forge Version:
1.10.2-12.18.3.2511
LibVulpes Version:
1.10.2-0.26-28
AdvancedRocketry Version:
1.10.2-1.25a

There's no crash.

Once the terraformer reaches 0.26atm, the terraforming process begins. A light show starts with a LOT of lasers coming down from the sky. This brings the TPS down in the corresponding dimension and if let be, it will snowball until the server can no longer do anything else.

The terraforming process seems to be working well, as the biomes and the surface changed. The atmosphere is also breathable now. It's not a slow process as the wiki says though, which I guess is the problem.

I had to set `allowTerraforming=false` in the config to play again, as turning off the terraformer doesn't stop the terraforming process.

This image doesn't bring justice to the live light show. There's a lot of lasers coming down.
![lights](https://user-images.githubusercontent.com/4866301/32307261-89f8f6f2-bf77-11e7-81fd-f0309578486f.png)

The paltry TPS:
![tps](https://user-images.githubusercontent.com/4866301/32307349-fd035408-bf77-11e7-887b-9965d9570481.png)

**Comment by gdarai** [comment]
Ok, good to know... there is a speed modiffier for the terraforming in the config, right? terraformMult, did you tried to play with it a little bit?

**Comment by zmaster587** [comment]
Terraform mult could probably use a better description, it's a multiplier for how fast you can raise/lower the atm, but not the terraforming process itself.  I'll put in a way to limit the speed on that.

**Comment by azmicomico** [comment]
Seems fixed in AdvancedRocketry-1.10.2-1.2.5-51.
