### ISSUE TITLE
prevent other mod's features from generating on the moon

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#91]
If it's possible
Like forestry hive, witchery stuffs...etc

Also lava on the moon is a bit strange I think

**Comment by DarkGuardsman** [comment]
This is planned as far as I understand. 

Also @zmaster587 https://github.com/BuiltBrokenModding/SkyIslandGenerator/blob/master/src/main/java/com/builtbroken/skyislandgenerator/world/WorldGenWrapper.java

**Comment by zmaster587** [comment]
Last commit should prevent oil/buildcraft water/beehives/mod gen in general from spawning on the moon and uninhabitable planets

**Comment by Endag** [comment]
Still happening in 1.0.3 on MC 1.10 - Forestry Hives all over a moon

Also there are a Tinker's Construct's slime islands with slimes constantly suffocating so i think this worldgen  feature should be also blacklisted from moons
