### ISSUE TITLE
Biome ID conflicts with Biomes'O'Plenty

### ISSUE THREAD

**Issue by donqixot** [zmaster587/AdvancedRocketry#910]
Minecraft Version:
-1.12.2
Forge Version:
-1.12.2-14.23.0.2528
LibVulpes Version:
-1.12.2-0.2.6-universal
*is this the latest curseforge build? yes*
----------
Explain issue in detail:
Biomes IDs between Advanced Rocketry and Biomes'O'Plenty seem to collide, example - BoP defines biome 91 as "wetland", while Advanced Rocketry defines biome 91 as "alienForestBiomeId". When I try to create flat world with biome set to 91, BoP wins, it is set to "wetland". I presume I can edit config manually and move them past 110 range, but curious if this can be done automatically for all users.

**Comment by zmaster587** [comment]
Modifed default config to start at 110, doesn't look like either BoP nor vanilla should conflict now

**Comment by donqixot** [comment]
Thank you very much! That was quick!
