### ISSUE TITLE
a little problem on artight seal

### ISSUE THREAD

**Issue by Uptobillion** [zmaster587/AdvancedRocketry#911]
Minecraft Version:
-1.12.2
Forge Version:
-2514
LibVulpes Version:
-0.2.6
*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
Crash Report:
----------
Explain issue in detail:
![2017-11-02_13 21 02](https://user-images.githubusercontent.com/28522459/32310997-1e8eb87a-bfd1-11e7-9fcb-177c126c240d.png)

**Comment by zmaster587** [comment]
What is the enchant ID of multishot?

**Comment by Uptobillion** [comment]
i dont know…… its from thermal foundation



在 2017年11月3日，11:17，zmaster587 <notifications@github.com<mailto:notifications@github.com>> 写道：


What is the enchant ID of multishot?

**Comment by gdarai** [comment]
Actually zmaster has the enchantment ID configurable through the AdvancedRocetry.cfg file... so you may try to just change the enchant ID there.

    # Enchantment ID for the airtight seal effect
    I:AirtightSealEnchantID=128

**Comment by Uptobillion** [comment]
but there is no artightseal id configuration in the cfg file .sould l add this in my cfg file？

在 2017年11月4日，21:11，gdarai <notifications@github.com<mailto:notifications@github.com>> 写道：


Actually zmaster has the enchantment ID configurable through the AdvancedRocetry.cfg file... so you may try to just change the enchant ID there.

# Enchantment ID for the airtight seal effect
I:AirtightSealEnchantID=128

**Comment by ouroborus** [comment]
Getting this same issue.

![image](https://user-images.githubusercontent.com/392047/33207076-27687bb0-d0c1-11e7-8ba3-bb546fae75d4.png)

**Comment by ouroborus** [comment]
It appears that Advanced Rocketry isn't setting up its enchantment IDs correctly. The config file I have says to use 128 but the airtight seal enchantment ended up with a different ID.

**Comment by zmaster587** [comment]
@ouroborus  As far as I can tell, 1.12 did away with setting explicit IDs for enchantments.  Will take a look

**Comment by zmaster587** [comment]
@ouroborus @Uptobillion can you test build 46 of the 1.12 branch on curse when it comes out and report back as to whether or not the issue is fixed?

**Comment by Keaton1188** [comment]
Hey @zmaster587 .. being told by a user on our server thats its still an issue.

Adv Rock version - AdvancedRocketry-1.12.2-1.2.6-50.jar

**Comment by NillerMedDild** [comment]
I had this issue - deleting the ChemicalReactor.xml to let it regenerate fixed it.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
