### ISSUE TITLE
rocket assembly machine does not power up with input plug only with creative plug

### ISSUE THREAD

**Issue by daddy77gaming** [zmaster587/AdvancedRocketry#912]
Minecraft Version:
- 1.10.2
Forge Version:
- 12.18.3.2511
LibVulpes Version:
- 1.10.2-0.2.5
*is this the latest curseforge build?* yes

----------
Explain issue in detail:
Playing forever stranded modpack (without and extra mods like better fps and optifine)
In my test world with a creative plug the rocket assembly machine powers up, with a power input plug it does not.

![2017-11-02_11 52 20](https://user-images.githubusercontent.com/31905330/32323004-c05df96e-bfc6-11e7-8ada-6eab77efe165.png)
![2017-11-02_11 57 31](https://user-images.githubusercontent.com/31905330/32323007-c3b3a942-bfc6-11e7-83db-79a8b9bf9265.png)
![2017-11-02_11 51 29](https://user-images.githubusercontent.com/31905330/32323092-16505164-bfc7-11e7-9412-68ddd277ca9d.png)

**Comment by daddy77gaming** [comment]
I can however power it by directly putting power into the rochet assembly machine, which seeing the whole buildup of the modpack isnt as intentional.
![2017-11-02_12 36 16](https://user-images.githubusercontent.com/31905330/32324098-7845ae16-bfca-11e7-9b42-af969702f285.png)

**Comment by zmaster587** [comment]
The rocket assembling machine is designed to take power directly and isn't part of a larger functional multiblock, other than the launchpad of course.  So it appears to be functioning as intended.

**Comment by zmaster587** [comment]
I forgot to mention this earlier, but the creative plug is also designed as an infinite energy source, where as the input plug normally functions as an energy sink only.  Which is why the creative plug works but the input plug doesn't.
