### ISSUE TITLE
Journeymap shows all planets dimensions as "planet", can they be renamed?

### ISSUE THREAD

**Issue by donqixot** [zmaster587/AdvancedRocketry#913]
Minecraft Version:
1.12.2
Forge Version:
1.12.2-14.23.0.2528
LibVulpes Version:
1.12.2-0.2.6-universal
*is this the latest curseforge build? yes*
---------------------
Explain issue in detail:
Journeymap shows all planets dimensions as "planet", can they be renamed? Ideally automatically like Sol19-Planet0 or something similar?

**Comment by zmaster587** [comment]
Unfortunately that's been requested and due to how MC does dimension registration post 1.7 it's not really feasible 

related to https://github.com/zmaster587/AdvancedRocketry/issues/421
