### ISSUE TITLE
Needle continues to go off the screen.

### ISSUE THREAD

**Issue by dmodoomsirius** [zmaster587/AdvancedRocketry#915]
Minecraft Version:
- 1.12.2
Forge Version:
-
LibVulpes Version:
-
*is this the latest curseforge build?* No latest jenkins
**Please Pastebin crash**
---------------------
Crash Report:
----------
Explain issue in detail:
https://clips.twitch.tv/LightSleepyCamel4Head
needle in monitoring station on ALT continues to go above screen.

**Comment by gdarai** [comment]
Very descriptive... Can you add at least some short comment? You know not everybody want's to decipher or watch a video.
