### ISSUE TITLE
[1.12.2] Issue with Custom asteroids syncing on dedicated servers

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#917]
Minecraft Version:
- 1.12.2
Forge Version:
- 2517
LibVulpes Version:
- 0.2.6-7
Explain issue in detail:

If a server has a customized asteroidConfig.xml, clients will still see asteroid info for the xml on their client in the observatory, rather than what the asteroid the server thinks it has.

I am using this xml to test adding ores to the asteroids:

```XML
<Asteroids>
	<asteroid name="Small Asteroid" distance="10" mass="100" massVariability="0.5" minLevel="0" probability="10" richness="0.2" richnessVariability="0.5">
		<ore itemStack="minecraft:iron_ore" chance="15" />
		<ore itemStack="minecraft:gold_ore" chance="10" />
		<ore itemStack="minecraft:redstone_ore" chance="10" />
		<ore itemStack="libvulpes:ore0 8" chance="10" />
		<ore itemStack="libvulpes:ore0 0" chance="10" />
		<ore itemStack="libvulpes:ore0 10" chance="10" />
	</asteroid>
	<asteroid name="Iridium Enriched asteroid" distance="100" mass="25" massVariability="0.5" minLevel="0" probability="0.75" richness="0.2" richnessVariability="0.3">
		<ore itemStack="minecraft:iron_ore" chance="25" />
		<ore itemStack="libvulpes:ore0 8" chance="10" />
		<ore itemStack="libvulpes:ore0 0" chance="10" />
		<ore itemStack="libvulpes:ore0 10" chance="5" />
	</asteroid>
</Asteroids>
```

and with identical seeds in the observatory: 
![image](https://user-images.githubusercontent.com/2363472/32356167-a831e4ac-c009-11e7-9345-5cd326df683f.png)

I get different results for the asteroids:
![image](https://user-images.githubusercontent.com/2363472/32356173-bc77344e-c009-11e7-91d5-d36dc5a0c6b7.png)

The one that displays correctly is when the config is on both server and client, and the incorrect one is when it is only on the server, and the client has the default xml

**Comment by zmaster587** [comment]
Asteroid configs are not synced over network

**Comment by Thutmose** [comment]
Ya, noticed it was that when I added the same config to my client and suddenly it worked, so I edited the issue to point that out, originally I thought something was wrong in the compiled version, as I had only been testing the config on the server, rather than also putting client side
