### ISSUE TITLE
[Question / Guide] Search for planets in Warp Controller - The Hard Way

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#921]
Minecraft Version:
1.10

Hi Everybody....
Does somebody here have experience with the search for planets? I tried following combination:

Setting: planetsMustBeDiscovered=true
// So from start, I see only my homeworld in the star system and the star itself.

Planet Defs: ```<artifact>some item</artifact>```
// This specifies that you have to put a specified item into Warp controller before you will be allowed to travel to that particular planet.

Now... I am feeding Warp controller with data and pressing 'Search for Planets' like crazy I even put in the correct artefact for one of the planets. But nothing happens... the data disappears and no new planet is visible or available. So, does this functionality work? Did some of you have seen it working?

**Comment by dmodoomsirius** [comment]
in your planetDef.xml do you have the <isKnown>false</isKnown> 
http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/AdvancedPlanetConfiguration.php#isKnown

**Comment by zmaster587** [comment]
It should work at least.  And if the planet has not yet been discovered and a correct artifact is placed in the controller you should get the planet as opposed to any other one.  That being, it's not a 100% chance any discovery will be made.  It should be closer to 1 in 50.  I also meant to add a config for that and apparently forgot.

**Comment by gdarai** [comment]
No hurry...
@dmodoomsirius I don't know... I'll check it. I think the iskown = false is there as default, but I am not sure. You always have to check the planetDefs in your save folder, because the game rewrites the file there with filled wate was missing and removed what was extra. But good point, I will check.

@zmaster587 the 1 in 50 is important information... the config will be nice, thank you. Please write it into changelog if you can. I will test it, it will just need much more sats generating the data in this case.

**Comment by zmaster587** [comment]
http://65.78.115.159:8080/job/Advanced%20Rocketry/job/AdvancedRocketry/job/1.12/13/ there's a copy here with the config if you want to give it a shot

**Comment by gdarai** [comment]
@zmaster587 Is this functionality now out? Is it backported to 1.10?
