### ISSUE TITLE
[Bug] Manual Data Transfer into Warp Controller

### ISSUE THREAD

**Issue by gdarai** [zmaster587/AdvancedRocketry#922]
Minecraft Version:
1.10

- When you have a data Stick with some data on it and you shift-click it into the Warp Controller... the Data Stick will end in the first free slot no matter the data type on the stick.
- When you then press the 'Transfer Data' arrow the data disappears from the stick and the stick became blank. The data does not show up in the Controller
- **When you press the 'Transfer Data' arrow again, this time with blank Random Data stick**, the game crashes.
- When you recover from the crash... the lost data are back in the Warp Controller in the correct progress bar.

**Comment by DevTimur** [comment]
Same goes for 1.7.10
If you insert data stick in any slot, and push "Transfer data" game will crash
Crashlog
https://pastebin.com/DHFh5FXT

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
