### ISSUE TITLE
Electrolyser not accepting water from input pipe?

### ISSUE THREAD

**Issue by azacock** [zmaster587/AdvancedRocketry#926]
Minecraft Version: 1.7.10
Forge Version: 10.13.4.1614
LibVulpes Version: 1.7.10-0.2.6
Advanced Rocketry Version: 1.7.10-1.2.5

Trying to build an Electrolyser. If I use a bucket to place water directly into the Electrolyser's input tank, it works as expected, and produces hydrogen and oxygen, which are output into liquid pipes connected to the output tanks, which lead into pressurized tanks. However, the machine refuses to take water as input from a liquid pipe or pressurized tank. I've even attempted to use pipes and tanks from other mods, but nothing seems to work.

**Comment by dmodoomsirius** [comment]
Does this only happen With LibVulpes and Advanced Rocketry? does kind of pipes are you using from what mod?

**Comment by sjd03271** [comment]
I am having this same problem. It is happening with the LibVulpes and Advanced Rocketry. I also tried the mechanical pipe from mechanism but the electrolyser did not take the water.

**Comment by zmaster587** [comment]
I know for a fact it works with buildcraft pipes since I'm currently using them in my base in my 1.7.10 testworlds.  Have you tried fluid pipes from mods other than mekanism?

**Comment by zmaster587** [comment]
Fixed in next version of libvulpes.

**Comment by sjd03271** [comment]
Ok

**Comment by OboTheHobo** [comment]
I have the exact opposite problem, I can get fluids in but fluids wont come out, and it's the exact same problem with the chemical reactor.
