### ISSUE TITLE
Space Station Assembler bug - Copying ID CHip

### ISSUE THREAD

**Issue by railstar0083** [zmaster587/AdvancedRocketry#929]
Minecraft Version:
- 1.10.2 (Age of Engineering Modpack)
Forge Version:
- 12.18.3
LibVulpes Version:
-

Explain issue in detail:

I successfully created a space station container and then put my chip (ID:1), back in the Assembler with a blank chip in order to make a copy.  When I clicked build, both chips vanished.  Now I have a useless station container.  Is there any way to retrieve a station ID chip when something eats it like this?  If not, there really, REALLY needs to be.

**Comment by azmicomico** [comment]
The command `/advancedRocketry givestation STATIONID` gives you a chip for your space station. Change `STATIONID` to the ID of your space station.

All chips are copied in the Satellite Builder. Insert the source chip on the left chip slot (1), the empty chip on the right chip slot (2) and then press the green button on the top right (3).
![sb](https://user-images.githubusercontent.com/4866301/32424204-c776097e-c2a2-11e7-8df3-35ac11f059e9.png)

**Comment by railstar0083** [comment]
Update:  That command does work with Age of Engineering.  Thank you!  Saved me a lot of trouble.

Now, as to what got me in trouble in the first place.  It might be a good idea to filter the inputs on the Station Assembler.  If it's just going to eat anything that is not a valid recipe, it's bound to catch someone else.

So the bug stands.  I used the wrong machine, but there should probably be a fail safe on the Assembler for dumb dumbs like me.

**Comment by zmaster587** [comment]
Thre should be failsafe in more recent builds.
