### ISSUE TITLE
[1.12.2] Overworld ore generation

### ISSUE THREAD

**Issue by Morpheus1101** [zmaster587/AdvancedRocketry#930]
I've looked through the config for this as its the only mod that uses libvulpes which has ore generation in overworld i want to disable but see no option to do so, unless i am missing something.

**Comment by zmaster587** [comment]
there should be true/false options for each ore in config/advRocketry/advancedRocketry.cfg => ore generation => generate[name of ore]

You can also find options to change the rarity and clump size of each ore individually there as well.

**Comment by Morpheus1101** [comment]
This wont affect mining Asteroids and the likes only overworld generation of ores ?

**Comment by Thutmose** [comment]
Correct, the asteroids are configured via their own XML file, the advancedRocketry.cfg's values shouldn't affect them
