### ISSUE TITLE
1.10.2 The End has no oxygen

### ISSUE THREAD

**Issue by superjeep3** [zmaster587/AdvancedRocketry#933]
Minecraft Version:
1.10.2
-
Forge Version:
1.10.2-forge1.10.2-12.18.3.2422
-
LibVulpes Version:
LibVulpes-1.10.2-0.2.5-universal
-
*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
Crash Report:
----------
Explain issue in detail:

I created a new game with advanced rocketry, and created a space base.  I also used an end portal to go to the end, but died because it said it had no oxygen.  All of the endermen where also dying, and the ender dragon was taking damage.

**Comment by zmaster587** [comment]
Would you be able to upload a copy of the [save location]/advRocketry/planetDefs.xml config file?

**Comment by superjeep3** [comment]
[planetDefs.zip](https://github.com/zmaster587/AdvancedRocketry/files/1456345/planetDefs.zip)

Looking inside of that it does have an entry for DIM 1 (which I understand to be the End).


</planet>
-<planet name="Space" DIMID="1">
<isKnown>false</isKnown>
<fogColor>0.0,0.0,0.0</fogColor>
<skyColor>0.0,0.0,0.0</skyColor>
<gravitationalMultiplier>10</gravitationalMultiplier>
<orbitalDistance>1</orbitalDistance>
<orbitalPhi>0</orbitalPhi>
<rotationalPeriod>24000</rotationalPeriod>
<atmosphereDensity>0</atmosphereDensity>
<biomeIds>106</biomeIds>

**Comment by superjeep3** [comment]
Editing the file and changing the atmospheric Density, and gravity in the file does not seem to do any good.  When minecraft loads up, the changed settings are reverted.

**Comment by donqixot** [comment]
I am not a developer, but what I found there is temp.dat file in ${world}/advRocketry folder. If you edit it using NBTEditor or may be delete it (I did not try it, do it at your own risk), than changes are accepted.

**Comment by superjeep3** [comment]
Awesome.  I will try that tonight.  It will be nice to have an atmosphere and gravity again, although I will miss the constant ender death, and near endless supply of ender pearls.

**Comment by Thutmose** [comment]
your planetDefs.xml has Space listed as DIMID 1, the end is supposed to be DIMID 1, so that is probably what is causing the issue.

**Comment by superjeep3** [comment]
ok, here is what I did...first I deleted temp.dat from the ${world}/advRocketry folder.  The I changed DIM1 from "space" to "planet".  I also changed the atmosphere, and gravity.  Now the end has oxygen, and gravity, but I still am not sure how it got messed up in the first place.

**Comment by zmaster587** [comment]
did you ever change the spacestation dimid in the AR config to 1?

**Comment by superjeep3** [comment]
I did not, would changing it to DIMID = "1" change anything?

**Comment by zmaster587** [comment]
Changing it to DIMID would cause the space dimension to attempt to register as the same ID as the end.  I would also expect it to crash on launch, but the config could have remained after changing it to something else.

**Comment by superjeep3** [comment]
That would make sense.  The game did crash the first time I went to the end.  Would you suggest changing the DIMID for the space station?  If so, what would you recommend changing it to?

**Comment by zmaster587** [comment]
I would only recommend changing it if something else is occupying dimid -2, and then I would say change it to a non occupied dimid.  Also would you be able to send that crash report.  It might help explain how this issue came up in the first place

**Comment by MisterMaow** [comment]
Is there a fix for this issue? I tried just removing the "Planet" from the config file starting at <planet name="Space" DIMID="1"> and ending at </planet> and it just broke the file. Caused the game to not load and blank out the PlanetDefs.xml file to <galaxy> 
</galaxy>

**Comment by MisterMaow** [comment]
Like I can understand the End not having oxygen, It adds a bit of difficulty since you need to wear the spacesuit instead of your OP armor,  But to have everything end the end dying all the time just ruins the end. Since a lot of mods add to the end and this mod pretty much breaks them all.

**Comment by Lyneira** [comment]
I experienced this as well a few weeks ago on my server and most definitely did not change anything about the Space Station's DimID. As mentioned above, the planetdefs.xml had a messed up config and removing the bogus entry for the End did not return the End to normal. I tried removing temp.dat but that destroyed our space station in the process. The only way I managed to fix this with our space station intact was restoring temp.dat from a previous world backup. Will keep in mind an NBT editor for if this ever happens again, fortunately so far it's been good.

**Comment by zmaster587** [comment]
The odd bit about this whole thing is, Advanced Rocketry does not accossiate anything with the end at all by default.  nor have I run into this issue over the 1000+ times I've loaded up worlds while testing.  If there's some way to reliably replicate the issue so I can track it down, it would be very helpful, but without some way to make this issue occur every time, or at least more often than 1 in 1000+ times, there's not really much I can do.

**Comment by superjeep3** [comment]
I did delete the temp file (as was outlined above), and changed the endDimID.  That fixed it for me.
