### ISSUE TITLE
Pipes not pulling from output hatches

### ISSUE THREAD

**Issue by saph12** [zmaster587/AdvancedRocketry#939]
Minecraft Version:
1.12.2 
Forge Version:
14.23.0.2515
Advanced Rocketry Version:
1.2.5a
LibVulpes Version:
0.2.6

Explain issue in detail:
Can not pull from output hatches with any pipe only a hopper will work.

Tried with multiple mods to do this and nothing will pull.

**Comment by zmaster587** [comment]
Did the pipes from AR work?

**Comment by saph12** [comment]
not tested them yet

thermal expansions items ducts is what i mainly tried on each side

**Comment by saph12** [comment]
ok so tested with the AE cables still would not pull from the orbital laser drill

also tested with
extra utilities 2

**Comment by zmaster587** [comment]
I suspect they're only checking for the capability for itemhandling rather than IInventory.
