### ISSUE TITLE
Warp controller select planet crashes game

### ISSUE THREAD

**Issue by Larsz11** [zmaster587/AdvancedRocketry#940]
[crash-2017-11-12_16.26.38-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1464806/crash-2017-11-12_16.26.38-client.txt)
Minecraft Version:
-1.10.2
Forge Version:
-1.10.2-12.18.3.2511
Advanced Rocketry Version:
-1.10.2-1.2.5a
LibVulpes Version:
-1.10.2-0.1.6
*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
Crash Report:
https://gist.github.com/dmodoomsirius/b92f16cb9fe2c05681576c67b49d231c
----------
Explain issue in detail:
Every time i open the warp controller and click on 'Select Planet' the game crashes with this error.

**Comment by dmodoomsirius** [comment]
Moved crash report to a gist as it won't make the issue so long.

**Comment by zmaster587** [comment]
Appears to be with NEI where NEI is trying to draw a tooltip and failing

**Comment by Larsz11** [comment]
i can see if it works with jei.

**Comment by Larsz11** [comment]
with jei it doesn't crash.

**Comment by zmaster587** [comment]
Might have been related to null names?  Either way as far as I can tell this is more of an NEI issue
