### ISSUE TITLE
Space Station Warp Without Core

### ISSUE THREAD

**Issue by dabestchicken** [zmaster587/AdvancedRocketry#942]
Minecraft Version:
-1.7.10
Forge Version:
-7.10.99.99
Advanced Rocketry Version:
-1.2.2
LibVulpes Version:
-0.2.5
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------No Crash
Crash Report:
----------No Crash
Explain issue in detail:
My friend connected a launch pad to his space station using a docking port and went up to it after and everything connected and was working fine. He went back to earth and  tried to fly back up to the space station but it said his station was no longer in solar system. He then tp'd back  to it bc he had a home saved  there and when he got there it was and still is stuck in the warp animation. He did not have a warp core on his space station at the time this happened.  He then added a warp core to try and fix it and he couldn't even see earth on the map. Please if this has been seen  before let me know I didn't see it already posted so I made a new Issue.

**Comment by zmaster587** [comment]
Is it possible to cause the the issue to occur every time?  IE can it be duplicated?

**Comment by dabestchicken** [comment]
@zmaster587 Unknown if we can cause it to happen again atm.  We will do some testing and let you know :)

**Comment by zmaster587** [comment]
Alright thanks!  It's basically impossible for me to fix something I cannot repeat.
