### ISSUE TITLE
Config/ Commands Enhancment

### ISSUE THREAD

**Issue by CTH999** [zmaster587/AdvancedRocketry#943]
So, I think you should be able to do Dim-mapping with plant creation in-world. I also think you should be able to delete stars. 
By being able to delete stars, it will fix the problem where I didn't want a star, and I had to delete the world. Also, I don't know if you can do this, but it would be nice to be able to re-name stars.

I also think a great addition would be /Ar planet (Dim Id) Reset

It would basically keep the planet, but destroy the world save. That way, if you changed a lot of properties that control biomes, It destroys all of them, so it can generate new ones.

Also, A More detailed explanation of the XML Config would be great.

Thanks

**Comment by CTH999** [comment]
Just as I submitted It, I remembered something else. A more detailed explanation of the Config would be very helpful too. Thanks Again

**Comment by dmodoomsirius** [comment]
well we do have http://arwiki.dmodoomsirius.me/AdvancedRocketry/Commands.php and http://arwiki.dmodoomsirius.me/AdvancedRocketry/config/

**Comment by CTH999** [comment]
I know that, but I find the config one confusing (probably just me), but I Do think being able to delete stars and rename them would be nice. I also knew about the wiki. (I Use it a lot) As for the planets, looking at the explanation of another command, I realized it has a save folder, so I can delete that. So, ignore my other message other than the star part. 

Thanks.

**Comment by CTH999** [comment]
You know what, I'll figure out the config, probably easier to use that way (Once I use it). Thanks for you help dmodoomsirius. Closing issue now to de-clutter the issues. Don't want a non-needed on there.
