### ISSUE TITLE
Pressurized Tank is called Fluid Hatch in its GUI

### ISSUE THREAD

**Issue by greenking13** [zmaster587/AdvancedRocketry#947]
Minecraft Version:
-1.10.2 (Latest Curseforge AR version.)

Apologies for removing the rest of the description. It's just what I perceive as a visual issue of the pressurized tank being mislabelled in it's GUI.

**Comment by greenking13** [comment]
Hmm, so I just noticed that in the same AR version stated above, you can place anything you want in the output slot of the fluid hatches and the like. Admittedly, I am unsure if this is a bug, or if the output slot can be used by, for example, the jetpack to fuel itself. I figured I may mention this anyways.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
