### ISSUE TITLE
Incorrect Speeds involving Iridium Coils with Rolling Machine

### ISSUE THREAD

**Issue by greenking13** [zmaster587/AdvancedRocketry#948]
Minecraft Version:
-1.10.2
Forge Version:
-12.18.3.2422
Advanced Rocketry Version:
-1.2.5a
LibVulpes Version:
-0.2.6
**is this the latest curseforge build?**
Latest 1.10.2 version
#Please Pastebin crash
No Crash
Crash Report:
No crash
Explain issue in detail:
Rolling Machine w/ Enhanced Motor + 2 Gold Coils: Speed 5.89x
Rolling Machine w/ Enhanced Motor + 2 Iridium Coils: Speed 4.77x

I am unsure if this is a visual bug concerning the shown values though, since the speed does seem to be much faster than the gold coils.

**Comment by zmaster587** [comment]
There was an issue with there being a typo with iridium where it checks for speed.   I'll look into it

**Comment by greenking13** [comment]
Alright! Now before I create a new issue, I wanted to ask if the carbon collection cartridge not being used and duplicating within the chemical reactor was on purpose. ( I'd get it not being used and just producing charcoal, but the useless dup of the cartridges seems a bit odd.)

**Comment by zmaster587** [comment]
Not it's not on purpose, I believe I solved that a while back though.  Sorry it's taken me so long to get back on this one, but another issue was opened with it.

I swear I've fixed that darn misspelling 6 times now.
