### ISSUE TITLE
Possible Assembler Bug with Already Programmed Chip and Station Deploy in Already Loaded Chunck

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [zmaster587/AdvancedRocketry#951]
Minecraft Version:
1.10.2
Forge Version:
12.18.3.2511
Advanced Rocketry Version:
1.10.2-1.2.2
LibVulpes Version:
1.10.2-0.2.5-universal
**is this the latest curseforge build?**
Don't know...

Explain issue in detail:
Me and my friend have built a station that was 31x31x20. We set up a pad of 31x31 and a Space Station Assembler. Since the maximum size is 16x16, we simply divided the station in 4. After building the first one, with a virgin chip and a Satellite Bay, my friend went with our already build and ready Rocket (with the Space Station Container and the Station 1 Chip) to outer-space. When he got there everything was fine, and the first part of our station was there. He landed there and asked me to send the second part, sending back the Rocket to our base on Earth.

Here all the problems began. First thing we noticed is that after changing the location of the Space Station Assembler and putting a copy or even the original chip (that came back with the Rocket) and a new Satellite Bay in the Assembler, if we would press the Build button, it would ignore the already programmed chip (already inserted), and would create a container with a new chip (from nowhere) named Station 2. After trying to send it, it (correctly) didn't land on our first station, and also got lost in probably a new dimension.

Well, assuming that was a bug, we tried to Scan in the same presets, and it worked. So when rolling back our server and putting again our chip from the Rocket and a new Satellite Bay in the Assembler we Scanned before Building, and it worked very well. So it kept the chip (not creating a new one) and also created our container consuming the Satellite Bay (which didn't happen before).

After that we thought everything was cool and decided to send again our second part of the station. The second problem happened. Since my friend was already in the space station, when I sent the second part the Rocket did reached the right station (and my friend could see it), but the container that was placed inside the rocket was simply gone, and nothing was added to our station, as would be expected.

Finally, after another rollback in the server, my last suggestion was that my friend would logout before I send the second part of the station. This time, I went with the Rocket and, reaching there, the station had the second part, as it was expected.

So I'd say that we faced 2 bugs in total. The first is that if we click Build (without Scanning first) in the Assembler with an already programmed chip, it would take all blocks, save then with some meta-data in the Container create a new chip with Station 2 (although it kept the Station 1 and using either of them, the Station would go to a new Dimension, or location). So to solve that we HAD TO scan with the programmed chip inside the Assembler.

The second one seemed to be: If we send a Rocket to a Dimension (space) that is already loaded, the Rocket won't place the part that it should, simply destroying the Container in the Rocket and everything we Build.

I'd like to turn this in a suggestion to create a Container Copier, or Restorer, that would let you recover the blocks in the Container, since Building the station (with an already programmed chip) simply saved some meta-data on the Container and we could send it to the Station 1 anymore, in anyway, forcing us to rollback the server to recover our blocks (which I should add that were a lot of blocks).

**Comment by Marcelo-Petrucelli** [comment]
Ok, maybe, just maybe, we figured out that the actual reason it didn't work as ALSO that the rocket was not with a player inside in some o the cases where we sent the container of the second part of the station to the space, assuming it would place the blocks... All of this is pretty strange and doesn't make much sense...

**Comment by DVorriose** [comment]
Could the second issue be due to someone being on the station vice in the rocket?  (i.e. if the station chunk/dimension loaded, some function might not be callable correctly).

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
