### ISSUE TITLE
Built rocket crashing game

### ISSUE THREAD

**Issue by adamjones353** [zmaster587/AdvancedRocketry#952]
Minecraft Version:
- 1.10.2
Forge Version:
-forge-1.10.2-12.18.3.2511
Advanced Rocketry Version:
-AdvancedRocketry-1.10.2-1.2.2
LibVulpes Version:
-LibVulpes-1.10.2-0.2.5-universal

#Please Pastebin crash
---------------------
Crash Report: https://pastebin.com/aqPvA56M
----------
Explain issue in detail:
I got this issue when I tried to use another mods block as part of the rocket. The scan was fine but after build client crashed (server unaffected). I had to use mc edit to remove the rocket entity as it crashed everyone in render distance of the rocket. The pack we are using is very large so we have been testing what works but this one was a really bad crash. 

I understand that it is impossible to ask for all mod to work together but maybe a block whitelist for the rocket so when a scan is done it shows invalid blocks.

**Comment by zmaster587** [comment]
Looks like a block from architecturecraft/chisel causing an issue.  Will take a look

**Comment by zmaster587** [comment]
Does this continue to occur without architecurecraft installed with chisel blocks on the rocket?

**Comment by adamjones353** [comment]
No, it is just when they are on.

**Comment by zmaster587** [comment]
Alright, this will at least prevent the crashing.
