### ISSUE TITLE
Crash when entering dimension

### ISSUE THREAD

**Issue by 016Nojr** [zmaster587/AdvancedRocketry#955]
Minecraft Version:
- 1.12.2
Forge Version:
- 14.23.0.2531
Advanced Rocketry Version:
- 1.2.5a-18
LibVulpes Version:
-0.2.6
**is this the latest curseforge build?** It's the latest stable build released, so technichally no.

#Please Pastebin crash
---------------------
Crash Report: https://pastebin.com/JMHjRNJL
----------
Explain issue in detail: When I teleport to a dimension with ID: -2 my screen goes white and I enter a crash-loop. This is done on a server

**Comment by zmaster587** [comment]
how are you teleporting, just a teleport command or a rocket?

**Comment by 016Nojr** [comment]
Teleporting with the Teleporter Probe from RfTools, it's a creative only item that lets you teleport to any(?) dimension

**Comment by zmaster587** [comment]
I addressed this somewhere else, should be fixed now
