### ISSUE TITLE
Rocket Assembler shows wrong stats for Advanced Rocket Engine

### ISSUE THREAD

**Issue by zckss** [zmaster587/AdvancedRocketry#958]
Minecraft Version: 1.10.2
Forge Version: 12.18.3.2511
Advanced Rocketry Version: 1.10.2-1.2.5a
LibVulpes Version: 1.10.2-0.2.5

Explain issue in detail:
When using the rocket assembler to scan build rockets both the basic and advanced rocket engines scan as providing 10N thrust and requiring 1 mb/s of fuel.  Wiki and code indicate the thrust should be 50N and the fuel consumption 2 mb.

To recreate build a rocket assembly multiblock, place a single engine on the launch pad and scan with the rocket assembly machine.

**Comment by Flanks255** [comment]
I've run into this as well in 1.12.2

**Comment by zmaster587** [comment]
I've noticed that in 1.10+ builds the acceleration promised by the engine is also missing, might be related.
