### ISSUE TITLE
Issues trying to compile the mod

### ISSUE THREAD

**Issue by wormzjl** [zmaster587/AdvancedRocketry#96]
I was trying to compile the latest stable branch but failed with some errors
In the log it says something like TileOxygenCharger, TileOxygenVent, TileEntityFuelingStation and TileEntitySatelliteControlCenter are not Abstract, but my log is in chinese and I cannot find a way to let gradle output in english :P
http://pastebin.com/LDe6kCKD
Is there some special requirement to compile the mod?

**Comment by DarkGuardsman** [comment]
My ability to read chinesse sucks but at least google has my back. Looks like its having issues finding ItemStack or something related. Make sure you have everything required to compile. Which includes according to my workspace LibVulpes, GalacitCraft, NEI, CCLib, CCCore, and IC2. 

```
  Symbol: Methods getStackInSlot (int)
  Location: Class TileEntitySatelliteControlCenter
D: \ Minecraft \ Modding \ AdvancedRocketry-stable \ build \ sources \ java \ zmaster587 \ advancedRocketry \ tile \ Satellite \ TileEntitySatelliteControlCenter.java: 230: error: can not find symbol
ItemStack inv = getStackInSlot (1);
```

**Comment by wormzjl** [comment]
actually I got all of them

**Comment by DarkGuardsman** [comment]
Found the issue, looks like zmaster neglected to update LibVulpes with the latest code. Now my local repo has the same issues you stated. Including additional missing references, etc. I'll bug him when he gets on TeamSpeak later today to update.

**Comment by wormzjl** [comment]
And how about these class not abstract problems?

**Comment by DarkGuardsman** [comment]
Most likley the super class is missing an interface. Sometimes when an error happens its not the class with the error that is the problem.

**Comment by wormzjl** [comment]
is there any news ?

**Comment by DarkGuardsman** [comment]
Yes, the lib should be synced now according to @zmaster587

**Comment by wormzjl** [comment]
compiled with the lateset lib but still failed with the same error :P
tried with jdk7 and jdk8, neither would work

http://pastebin.com/6iQ388F9

**Comment by DarkGuardsman** [comment]
I'll bug @zmaster587 first chance I get and see what is going wrongs.

**Comment by wormzjl** [comment]
Ohh I found the trick for compiling, gonna close this for now :3

**Comment by zmaster587** [comment]
What was the trick?

**Comment by wormzjl** [comment]
I was trying to compile AR alone with libvulpes in the libs folder, apparently this won't work like compiling other mods :P

**Comment by zmaster587** [comment]
That should work... did you get libvulpes from curse or did you compile it
first?

**Comment by wormzjl** [comment]
I compiled it from source

**Comment by zmaster587** [comment]
Probably the gradle script, will look into it
