### ISSUE TITLE
Rockets stop rendering when too far above y=256

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#961]
Minecraft Version:
- 1.12.2 (and probably 1.10.2 and 1.11.2)
Forge Version:
- Any for the above versions
Advanced Rocketry Version:
- Any for the above versions
LibVulpes Version:
- Any for the above versions

Explain issue in detail:
You have probably already noticed that the rockets stop rendering once they get above certain heights, and in certain view angles.  This is due to minecraft's chunk culling, and the fact that entities will only render if their chunk is marked for rendering.

In RenderGlobal, the section where it renders entities, only looks for the lists of entities in the chunks marked for rendering, which is populated during the setupTerrain method, during that check it does a frustum check, which only includes chunks with blocks visible from your current view.  This means if you are above y=256, and look any direction other than straight down, the chunk you are in is most likely out of the view, so the rocket won't render.

I am not entirely sure what would be the best solution for this issue, probably something ASM related is needed to be done to the frustum check, or maybe add a seperate section to render mobs with ignoreFrustumCheck set to true, but I am not sure what is the best way to go about it.

**Comment by Thutmose** [comment]
If you wish to confirm the bug, just look at your rocket in any direction besides straight down while above y=256

**Comment by zmaster587** [comment]
setupTerrain method you say?  That's probably why there was an ASM for that in Ar in the first place.  I nuked it in 1.12 because it took me more than 10minutes to get working and I didn't see anything noticable from removing it.  It was probably to solve this issue exactly.
