### ISSUE TITLE
[1.12.2] Rockets don't render in certain locations with certain view angles

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#963]
Minecraft Version:
- 1.12.2 (probably any after 1.8)
Forge Version:
- (probably any for relevant MC versions)
Advanced Rocketry Version:
- (any for given MC version)
LibVulpes Version:
- (same as above)

Explain issue in detail:

This is very closely related to #961 and should probably be fixed by a PR to forge, but I am not sure about the best way to go about fixing it.

What exactly did the fix for #961 do? I don't have much experience with asm, so am not sure from reading the commit to fix it.

It turns out, the same culling issue in #961 occurs when the entity is in a sub-chunk below the current one you are at, the following screenshots illustrate the issue.

Here we have a rocket (and a tall pokemob) standing on y=47, so the top of them is above the sub-chunk boundery (shown as the blue lines in f3+g)
![image](https://user-images.githubusercontent.com/2363472/33289343-3af520d8-d38d-11e7-835e-bb97504f7afa.png)

When I look in such a direction that the subchunk is not in the frustum, they will no longer render:
![image](https://user-images.githubusercontent.com/2363472/33289373-528541f6-d38d-11e7-9d46-3169d658b2d5.png)

Note that the health bar for the pokemob does render, this is because it does it outside if the rendering for the mob itself (the health rendering is done almost identically to the mod "Neat")

**Comment by Thutmose** [comment]
I should also note that this bug affect tile entities as well, it is probably the reason why the rendering for the machines sometimes goes funny.

**Comment by zmaster587** [comment]
A quick hack may just be to expand the frustrum a bit, may look into that

**Comment by DarkGuardsman** [comment]
A pull request to forge was made to solve the issue with Y positive values https://github.com/MinecraftForge/MinecraftForge/pull/4823

**Comment by DarkGuardsman** [comment]
@zmaster587 They merged that PR

**Comment by dmodoomsirius** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1334
