### ISSUE TITLE
[1.12.2] iridium ore generation question

### ISSUE THREAD

**Issue by Morpheus1101** [zmaster587/AdvancedRocketry#964]
I've not been able to find any default generated iridium in my world, is this something i have to manually add into world generation?

**Comment by Thutmose** [comment]
iridium is only found via enriched asteroid mining missions iirc

**Comment by Morpheus1101** [comment]
What machines in space would require the iridium as apposed to the countless machines you could use iridium coils for on the ground before going into space?  I ask as this is my 1st time having used this great mod and atm i've had to enable iridium generation from ThermalFoundation as after quarrying 65 chunks area, i come across no iridium other than what i enabled in TF.  Now admittedly my world generation is LostCities with terrain from BOP of wasteland for the entire overworld

**Comment by Thutmose** [comment]
everything for getting asteroid mining up and running can be done without iridium, so you are supposed to get that done first, then get the iridium and upgrade older machines with them

**Comment by Morpheus1101** [comment]
If thats the case thats good, i found it odd that not even the configs had any mention of iridium for me to determine as you say its only for Asteroids or you have to manually config what is in the asteroids in terms of mining

**Comment by Thutmose** [comment]
it is only found in enriched asteroids by default, iridium coils/motors/etc are used for speeding up machine parts

**Comment by zmaster587** [comment]
Iridium asteroids should be in default conig now.  Can be added to world gen but disabled by default
