### ISSUE TITLE
Screen goes blank when scanning or building a rocket

### ISSUE THREAD

**Issue by Crazygui0601** [zmaster587/AdvancedRocketry#969]
Minecraft Version:
- 1.10.2
Forge Version:
- 12.18.3.2511
Advanced Rocketry Version:
- 1.2.5a
LibVulpes Version:
- 0.2.6
**is this the latest curseforge build?**

#Please Pastebin crash
N/A
Crash Report:
N/A
Explain issue in detail:
When scanning or building the rocket, the screen goes entirely blank as depicted in the attached gif.
The actual scan and building process are unhindered, with accurate stats, and successful building, but every time it performs these actions, the screen goes blank as long as the launch pad is in view during process. If the rocket assembler is not powered, the screen stays blank until the rocket assembler is broken. the assembler can be exited and the issue still occurs.
![ar assembler blank screen](https://user-images.githubusercontent.com/34107258/33395639-c9496360-d50b-11e7-8051-7027ca5a08e6.gif)

**Comment by dmodoomsirius** [comment]
Does this issue occur only with Advanced Rocketry and LibVulpes?

**Comment by zmaster587** [comment]
Do you have optifine installed?

**Comment by Jummit** [comment]
I had this issue too. Sometimes restarting MC helps, sometimes remove a mod like NEI or optifine does the trick.

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
