### ISSUE TITLE
Holo-Projector* Crash

### ISSUE THREAD

**Issue by Fortist** [zmaster587/AdvancedRocketry#97]
The Holo Projector crashes when picking it up (with mouse) while within its GUI.

**Comment by DarkGuardsman** [comment]
If you can, it would be useful to have the crash log.

**Comment by zerotheliger** [comment]
stacktrace plox

**Comment by Darquewolf** [comment]
here is my crash-log from the same instance
[http://pastebin.com/u9VG406Q](url)

I am working on a modpack with your mod so if you need me to try to reproduce this with just AR and the libraries needed I will

I was block selecting the ghosted blocks being dumb but it gave me a block and so i placed it cause why not. 

suggestion for the holo projector would be to do the same thing openblocks does with the building and advance building guide for the holo projector.
[https://github.com/OpenMods/OpenModsLib/blob/5f86b062f2320bb7838927cf8aff936b03fcd545/src/main/java/openmods/utils/render/GeometryUtils.java](url)
don't know if this helps but it **may** be a better method for holograms

**Comment by zmaster587** [comment]
Only way that can possibly happen is if one of the blocks in the structure is air, or has no item associated with it.  Either way, I added a check to prevent it from crashing and the affected blocks should be clearly marked as an error.
