### ISSUE TITLE
Crash on /advRocketry goto <spacedim>

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/AdvancedRocketry#970]
Minecraft Version:
- 1.12.2
Forge Version:
- 2554
Advanced Rocketry Version:
- 1.2.6-1
LibVulpes Version:
- 0.2.6-16
---------------------
Crash Report: https://gist.github.com/Thutmose/12db77f463bd974d20be3869096aa417
----------
Explain issue in detail:
Make a new world, use command /advRocketry goto <spacedim> (default is -2), proceed to crash.

My suggestion is to either include a null check somewhere to account for no space stations, and maybe teleport the player to some default location in space to just be "deep space" or somesuch.

**Comment by dmodoomsirius** [comment]
This has already been fixed. Has not been released yet I believe to curse.

**Comment by Thutmose** [comment]
ahh yes, this claims to fix it: **https://github.com/zmaster587/AdvancedRocketry/commit/f71106e830c016ce3450f598c1f021743ac0436e**

I will close issue when it gets on curse then

**Comment by dmodoomsirius** [comment]
https://minecraft.curseforge.com/projects/advanced-rocketry/files/2504929

**Comment by dmodoomsirius** [comment]
just did a build.
