### ISSUE TITLE
[1.10.2] No Planets in the Guidance Computer

### ISSUE THREAD

**Issue by Aiidoneus** [zmaster587/AdvancedRocketry#971]
Minecraft Version:
- 1.10.2
Forge Version:
- 1.10.2-12.18.3.2477
Advanced Rocketry Version:
- 1.10.2-1.0.19
LibVulpes Version:
- 1.10.2-0.1.19

I saw this post which I have the same issue. https://github.com/zmaster587/AdvancedRocketry/issues/843
I tried deleting the planet.xml and it doesn't regenerate. So I am wondering how to fix this. Just looking for a little guidance. :-)

**Comment by dmodoomsirius** [comment]
did you Delete it inside the world folder? that is where it reads it from.

**Comment by Aiidoneus** [comment]
What file am I deleting in the world folder? Was it not the planet.xml in the config folder?

**Comment by dmodoomsirius** [comment]
Advanced rocketry now copies the planetDef.xml into the saves/<Save name>/advRocketry.

**Comment by Aiidoneus** [comment]
I am on multiplayer server. I assume you are saying the world folder and advRocketry. I only see the other Dimension folders and a temp.dat file

**Comment by zmaster587** [comment]
@dmodoomsirius he's using a 1.0.x build, that was before the xml config was added.

You'd actually probably have to delete the temp.dat file to regernate, or using the solution proposed here https://github.com/zmaster587/AdvancedRocketry/issues/843#issuecomment-348773691

**Comment by Aiidoneus** [comment]
We are good now. Thank you for your help!
