### ISSUE TITLE
Sleeping in Space station isn't working?

### ISSUE THREAD

**Issue by katoumishiyo** [zmaster587/AdvancedRocketry#973]
Minecraft Version: 1.10.2
-
Forge Version: 12.18.3.2185
-
Advanced Rocketry Version: 1.10.2-1.2.2
-
LibVulpes Version: 0.2.5-universal
-
**is this the latest curseforge build?**   

#Please Pastebin crash N/A
---------------------
Crash Report: N/A
----------
Explain issue in detail:
Sleeping in the space station just indicates that it needs to be night. I've researched for a solution which lead me to do the space station rotation away from the sun. which i did, here are some snippets.

![photo1](https://user-images.githubusercontent.com/34169000/33496766-5d1dfe32-d680-11e7-9743-4bec8fd0286f.JPG)

![photo2](https://user-images.githubusercontent.com/34169000/33496774-62d46096-d680-11e7-94fb-4d54e5db1883.JPG)

![photo3](https://user-images.githubusercontent.com/34169000/33496793-704b93a2-d680-11e7-8ebc-35679ad5320b.JPG)

![photo4](https://user-images.githubusercontent.com/34169000/33496798-73166d14-d680-11e7-924a-149200ca72a9.JPG)

What could be causing this?

**Comment by Lyneira** [comment]
Not sure what the bug here is from those screenshots. I'm on 1.12 here and as far as I can tell sleeping on a space station isn't meant to make it day, just to set your spawnpoint if respawning on planets/space stations is enabled. You'll need to make sure the bed is in a breathable atmosphere though.

**Comment by zmaster587** [comment]
@katoumishiyo Do you have allowPlanetRespawn set to true?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
