### ISSUE TITLE
pressure tanks crash client (1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [zmaster587/AdvancedRocketry#974]
Minecraft Version:
1.12.2
Forge Version:
1.12.2-2559
Advanced Rocketry Version:
AdvancedRocketry-1.12.2-1.2.6-27

LibVulpes Version:

LibVulpes-1.12.2-0.2.6-16

**is this the latest curseforge build?**

#Please Pastebin crash
--------------------
Crash Report:
[crash-2017-12-03_18.01.39-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/1524543/crash-2017-12-03_18.01.39-server.txt)

Explain issue in detail:
as soon as the tanks are in inventory it crashes my client even in single and multiplayer

**Comment by zmaster587** [comment]
does this occur without wirelesscharger installed?

**Comment by SDUBZ** [comment]
no if a wireless charger isnt anywhere in the world it doesnt happen

**Comment by SDUBZ** [comment]
seems to be fixed with WC:1.0.5

**Comment by zmaster587** [comment]
Alright, thanks
