### ISSUE TITLE
Biome IDs conflicts with Twilight Forest

### ISSUE THREAD

**Issue by NillerMedDild** [zmaster587/AdvancedRocketry#976]
Minecraft Version:
- 1.12.2
Forge Version:
- 1.12.2-14.23.1.2559
Advanced Rocketry Version:
-1.12.2-1.2.6-27
LibVulpes Version:
-0.2.6-16-universal
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Biome IDs 111-118 are used by Twilight Forest.

**Comment by NillerMedDild** [comment]
In addition to this, it appears the Biome ID configs don't actually change anything.

**Comment by zmaster587** [comment]
The biome ID configs somehow got misplaced in the 1.11 => 1.12 update.  Will be fixed in the next build.  As for moving the biome IDs, I already moved them not to conflict with BOP, there's not much more room to keep moving them up.  I Will have the config fixed for next build though

**Comment by zmaster587** [comment]
After some testing, I'd jammed Advanced rocketry and twilight forest together with default configs and didn't run into any issues.  Space stations use the correct biome, the moons use the correct biome, I don't see anything odd in twilight forest, and planets use arbitrary biomes  What's leading you to think there's a conflict?

**Comment by NillerMedDild** [comment]
I guess the conflict only occurs with multiple biome mods present? I also had BoP, Integrated Dynamics and Wizardry.
The moon was generating as a Dense Twilight Forest, and most planets primarily had Twilight biomes.

But if the config for changing biome IDs now works, I'd call that problem solved :)

**Comment by eduzinnz** [comment]
how to edit erebus biome id? can someone speak?
