### ISSUE TITLE
Creates The Beneath mod as a moon requiring Oxygen

### ISSUE THREAD

**Issue by tjsd** [zmaster587/AdvancedRocketry#978]
Minecraft Version:
1.12.2
Forge Version:
2559
Advanced Rocketry Version:
AdvancedRocketry-1.12.2-1.2.6-27
LibVulpes Version:
LibVulpes-1.12.2-0.2.6-16-universal
**is this the latest curseforge build?** Yes

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Advanced Rocketry claims the Beneath dimension as a moon biome and puts it to require oxygen and world gen does not work.

**Comment by dmodoomsirius** [comment]
Does this only happen with the Beneath mod and Advanced Rocketry and LibVilpes? can you check the planetDef.xml for any dimension that is matching the dimension of the Beneath dimension?  I know that can cause issues. if needed please pastebin your planetDef.xml and the Beneah mod's config and i can take a look.

**Comment by arlyanagi** [comment]
I have similar issue at the end, there is no oxygen.

I'm playing a mod pack 'Modern Skyblock2'. I guess, that mod pack updates Advanced Rocketry versions many times, so dimension IDs are conflicted. The end dimension ID '1' and the space station dimension ID '1'? are assigned same one on planetDefs.xml.

saves/World/advRocketry/planetDefs.xml
https://pastebin.com/Z28gdJdP

Correctly, the end dimension is 1, the space station dimension is -2. I try rewriting from `<planet name="Space" DIMID="1">` to `<planet name="Space" DIMID="-2">`, but it's restored when I start game.
If you know how to rewrite planetDefs.xml, or planetDefs.xml has no problem and I should fix the other files, please tell me.

thank you.

**Comment by zmaster587** [comment]
@arlyanagi It should take if you change the xml config.  Are you writing the file only when the game is completely shutdown and saving it before launch?

**Comment by arlyanagi** [comment]
@zmaster587 Yes, I rewrote that file when the game process was killed. And, it restored when loading world data.

I tried:
- rewriting line:24 from `DIMID="1"` to `DIMID="-2"`, then the end is no oxygen, and the file is restored.
- removing the lines 24-34 to reset data, then the game is crushed when loading world data.

Anyway, the oxygen came back at the end of my world. I did't fix any xml files and not update AdvancedRocketry/LibVulpes jars.

I did:
1. Start the game at over world
2. Go to the end, there is no oxygen and no breathable warning
3. Save and quit the game
4. Delete the end dimension directories, saves/World/DIM1 and saves/World/advRocketry/DIM1
5. Start the game at the end, there is oxygen and breathable

Current saves/World/advRocketry/planetDefs.xml
https://pastebin.com/NQSQdmh7

Now, I have no problem at overworld(breathable), the end(breathable) and space station(not breathable). I don't know why, but existing `saves/World/advRocketry/DIM1` might be a cause. That directory is invalid and not created in my current world data.

**Comment by zmaster587** [comment]
That makes very little sense.  The `saves/World/advRocketry/DIM1` only stores block data, nothing involving the atm and won't be accessed.  What that does indicate though is that AR tried to register the end as its own planet rather than a dimension belonging to vanilla.

All atmosphere data is stored only in saves/World/advRocketry/temp.dat and saves/World/advRocketry/planetDefs.xml

maybe somehow restarting the server had an impact and doing so get AR to clean something up?  I don't know...

Are you able to get it to act up again short of editing the config to for the end to not have air?

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
