### ISSUE TITLE
Crash to desktop when trying to access Guidance Computer

### ISSUE THREAD

**Issue by JCRickards** [zmaster587/AdvancedRocketry#979]
Minecraft Version: 1.11.2
-
Forge Version: 1.11.2
-
Advanced Rocketry Version: 1.2.5a
-
LibVulpes Version:
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail: Whenever I try to access the guidance computer to program the Planet ID Chips it crashes to desktop. The server stays running normally.

**Comment by dmodoomsirius** [comment]
Can you pastebin the crash report and the client log and link them here please? they will allow zmaster to have a easier time tracking it down.

**Comment by JCRickards** [comment]
Sorry about that. Here's the pastebin. 
https://pastebin.com/9LVekSZz

**Comment by dmodoomsirius** [comment]
I am noticing buildcraft in the stacktrace. does this happen with only Advanced Rocketry and LibVulpes?

**Comment by HorizonsMC** [comment]
It's a conflict with Buildcraft.
