### ISSUE TITLE
Conflicting Mods

### ISSUE THREAD

**Issue by Zer0Lyfe** [zmaster587/AdvancedRocketry#981]
so i have testing my custom pack and happen to find a bug. The Bug is making it so i keep defaulting to a difficulty so if i select peaceful in one world it will be peaceful in another world and when you change the difficulty to normal and try reconnecting to the same world it will go to peaceful again even if you have locked the worlds difficulty.

I found out it doesn't do it on its own as it requires astral sorcery (its not caused by libVulpes as well) to start causing this bug for unknown reasons and if i test without Advanced Rocketry it doesn't do the bug so it is the mods conflicting with each other

Mod Versions
Forge 1.12.2 2562
Astral Sorcery 1.12.2-1.8.3
LibVulpes 1.12.2 - 0.2.7-19-universal
Advanced Rocketry 1.12.2-1.2.6-4 (and happened in earlier builds)

**Comment by Zer0Lyfe** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/426

**Comment by zmaster587** [comment]
how are you changing the difficulty?  Can you provide the fml-client-latest log after attempting this?

**Comment by Zer0Lyfe** [comment]
ok ill do that right now

**Comment by Zer0Lyfe** [comment]
https://gist.github.com/Zer0Lyfe/a47e194a8fe766a3d80a76bd4caba76e

**Comment by zmaster587** [comment]
Did you change the difficulty and load up the other world when you get this log file too?

**Comment by Zer0Lyfe** [comment]
sorry forgot about that one sec

**Comment by Zer0Lyfe** [comment]
it seemed like it set the difficultly before i created those world and even when i did it in a instance.

**Comment by zmaster587** [comment]
So the difficulty is getting set to peaceful no matter what you do,  even if you create a new instance with normal or hard?

**Comment by Zer0Lyfe** [comment]
so it when you create a new instance it will default to normal and even when re-entering the same world where you set it to peaceful or hard

**Comment by Zer0Lyfe** [comment]
ill see if i can make video showing this

**Comment by Zer0Lyfe** [comment]
this show what happens 
https://www.youtube.com/watch?v=PUri31n102o&feature=youtu.be
Sorry it is a bit rushed but should explain it

**Comment by zmaster587** [comment]
Alright, I'll take a look

**Comment by Zer0Lyfe** [comment]
Sorry about me making this longer than it should've been.

**Comment by zmaster587** [comment]
No rush, Im a bit busy myself, atm waiting for computer to finsih task so I have enough RAM to launch minecraft

**Comment by zmaster587** [comment]
I tested with Astral Sorcery 1.12.2-1.8.3 and twilightforest 1.12.2-3.5.263 without advanced rocketry or libvulpes installed and the same issue comes up.  So I'm thinking it may an issue with Astral Sorcery + any dimension mod.

**Comment by Zer0Lyfe** [comment]
ok. Thank you zmaster
