### ISSUE TITLE
Crash with fluids from Electrolyzer -> Chemical reactor

### ISSUE THREAD

**Issue by Kazzamkablam** [zmaster587/AdvancedRocketry#982]
Minecraft Version:
1.12.2

Forge Version:
14.23.1.2562

Advanced Rocketry Version:
1.2.6-4

LibVulpes Version:
0.2.7-19

Crash log:
https://www.dropbox.com/s/hlisp0qlp95761i/2017-12-11-1.log?dl=0

Explain issue in detail:
When I tried to hook fluids from electrolyzer to chemical reactor, game crashes and keeps crashing every time I try to log back in.

**Comment by zmaster587** [comment]
should be fixed next build, see #997
