### ISSUE TITLE
Just Enough Resources Profiler cannot do Advanced Rocketry dimensions.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#986]
Minecraft Version: 1.12.2
-
Forge Version:  14.23.1.2555
-
Advanced Rocketry Version: 1.2.6.-27
-
LibVulpes Version: 0.2.6.-16
-
**is this the latest curseforge build?**  Not sure.

#Please Pastebin crash
---------------------
Crash Report:  Not a fatal crash

[03:19:35] [pool-22-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[03:19:35] [pool-22-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.common.DimensionManager.getProvider(DimensionManager.java:153)
[03:19:35] [pool-22-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at jeresources.profiling.ProfilingTimer.getDimensionName(ProfilingTimer.java:84)
[03:19:35] [pool-22-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at jeresources.profiling.ProfilingTimer.startChunk(ProfilingTimer.java:34)

----------
Explain issue in detail:

Just Enough Resources cannot profile AR dimensions.  Seems to be a problem with the dimension manager.

https://github.com/way2muchnoise/JustEnoughResources/issues/134

Thanks,
IMarv

**Comment by zmaster587** [comment]
Only thing I can think of off the top of my head is that it may be trying to profile a dimenion that is registered, but not loaded.  AR does tell forge not to load dimensions unless needed.

**Comment by IMarvinTPA** [comment]
I was in the dimension using the single dimension mode of the profiler and it failed.  It was definitely using the dimension.  However the code may be creating a placeholder copy of the dimension to actually profile it.

**Comment by zmaster587** [comment]
Strange, can't think of what may cause the issue then, all the dimension stuff is handled on forge's end.  the atmosphere and everything is totally seperate.  that being said, the only thing on that line that could NPE is getWorld(id) since the full function is:

    public static WorldProvider getProvider(int dim)
    {
        return getWorld(dim).provider;
    }

**Comment by zmaster587** [comment]
I looks like he's getting a dimension type here https://github.com/way2muchnoise/JustEnoughResources/blob/bf1f3b2af26ca459585f88e3f76f9142aec5497d/src/main/java/jeresources/profiling/ChunkProfiler.java#L45 and assuming it to be the same as the dimension ID.  But b/c AR resuses the same dimension type for multiple dimensions, that may not hold true.

using world.provider.getDimension()  instead may fix the issue

**Comment by IMarvinTPA** [comment]
I see that.  Not AR's fault then.

**Comment by IMarvinTPA** [comment]
I am trying to make JER work with AR but I am having troubles.
After WorldServer world = (WorldServer) this.sender.getEntityWorld();
world.provider.getDimension() returns 2 when on an AR planet.

Additinally,
DimensionManager.getProvider(dimId).getDimensionType().getName()
ends up with an error where the getWorld can't find a world to supply the provider.

Why doesn't AR create a new dimensiontype for each world?

**Comment by IMarvinTPA** [comment]
I have a pull request for JER that allows JER to profile many cross-mod dimension issues, including AR's.
https://github.com/way2muchnoise/JustEnoughResources/pull/138
