### ISSUE TITLE
Use Biome Registry Name in planetDefs.xml vice IDs.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#989]
Minecraft Version: 1.12
-
Forge Version:  Any
-
Advanced Rocketry Version:  Any
-
LibVulpes Version:  Any
-
**is this the latest curseforge build?**  Sure

#Please Pastebin crash
---------------------
Not a crash
----------
Explain issue in detail:
Adding mods with biomes and starting new worlds can shuffle the biome IDs.  Please use the registered biome name in the XML instead of the numeric ID.

Example:
Instead of &lt;biomeIds>23,4,166,147,163 &lt;/biomeIds>
use &lt;biomeIds>minecraft:jungle_edge, minecraft:forest, minecraft:mutated_mesa_rock, advancedrocketry:oceanspires, minecraft:mutated_savanna&lt;/biomeIds>

**Comment by zmaster587** [comment]
Resolved in recent 1.12 builds
