### ISSUE TITLE
Problem with overworld

### ISSUE THREAD

**Issue by Golgatron** [zmaster587/AdvancedRocketry#99]
I have the mod instaled on my server . When I connect to the server I run in the normal world . If I but now re- connect is my world as if I were in outer space .

What can I do about it

**Comment by Golgatron** [comment]
hello anywhere here?

**Comment by zmaster587** [comment]
What exactly do you mean by " If I but now re- connect is my world as if I were in outer space ."

**Comment by Golgatron** [comment]
your german?

**Comment by zmaster587** [comment]
No, I am not, and I do not exactly see how that is relevent.

**Comment by Golgatron** [comment]
i start the server with rocktry join on server and my wordl is normal i disconnect from server and join again and my world is in space all chunks wood gras all in space division and i cant change this i delete  rocketry start the server again join and all is normal

**Comment by zmaster587** [comment]
I have having a very difficult time understanding your english, can you
post a screenshot of what you are seeing when the overworld is in space
with the debug info (F3) on the screen and post a copy of the server logs?

**Comment by Golgatron** [comment]
okay i make this

**Comment by Golgatron** [comment]
so here 
First Time log in on Server with Rocketry all normal 
[Bild]([URL=http://www.directupload.net][IMG]http://fs5.directupload.net/images/160309/57usyws7.png[/IMG][/URL])

**Comment by zmaster587** [comment]
I see what you mean now, I've never seen this happen before so I may need a bit more info.
Can you send me a copy of the advancedRocketry config file as well as the file in "<server directory>/advRocketry/temp.dat" and the server startup log?

**Comment by Golgatron** [comment]
okay i make this

**Comment by Golgatron** [comment]
you need this temp and config data befor this bug or with this bug?

**Comment by zmaster587** [comment]
with the bug

**Comment by Golgatron** [comment]
okay i have found the proplem in world/adrocketry was a duplicatet dat file ......  now is all okay sorry for this

**Comment by zmaster587** [comment]
It's fine, at least if somebody else has the same problem they will see this.
