### ISSUE TITLE
Need a way to define where unmapped dimensions go.

### ISSUE THREAD

**Issue by IMarvinTPA** [zmaster587/AdvancedRocketry#990]
Minecraft Version: 1.12.2
-
Forge Version: 2555
-
Advanced Rocketry Version:  1.12.2-1.2.6-27
-
LibVulpes Version:  1.12.2-0.2.6-16
-
**is this the latest curseforge build?**  Not sure.
----------
Explain issue in detail:

Need a way to define where dimensions created using a mod like RFTools Dimensions end up in the cosmos or other unexpected launches such as from the roof of the Nether.  Perhaps a flag on a star that indicates that launches from an unmapped dimension land in its orbit with a random orbit.  (And maybe a random number of new random moons and/or maybe as a moon to an existing planet.)

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
