### ISSUE TITLE
Crash when placing Solar panel

### ISSUE THREAD

**Issue by ProxyPlayerHD** [zmaster587/AdvancedRocketry#991]
was about to make a Mircowave Receiver... now my world is forever lost.

[LOG](https://pastebin.com/cAKwSvh1)

CrashLog should contain all Information needed.

**Comment by dmodoomsirius** [comment]
It’s not lost. You can use something like mcedit to remove the erroring block until a build is pushed to curseforge.

**Comment by zmaster587** [comment]
Reverting back a build or waiting for the next one should fix the problem

**Comment by zmaster587** [comment]
Fixed for next build
