### ISSUE TITLE
Crash when interacting with Rocket Inventories

### ISSUE THREAD

**Issue by Danickar** [zmaster587/AdvancedRocketry#992]
Minecraft Version:
-1.12.2
Forge Version:
-14.23.1.2566
Advanced Rocketry Version:
-1.2.6-25
LibVulpes Version:
-0.2.6-16
**is this the latest curseforge build?**

#Please Pastebin crash
https://pastebin.com/kaWsHjXd
---------------------
Crash Report:
----------
Explain issue in detail:
Almost every time I try and interact with a rocket's internal inventory (chests, guidance computer, satellite bay) Minecraft crashes to the desktop.

**Comment by Danickar** [comment]
In further testing there is a higher chance of being able to interact with the inventory if it is a brand new rocket, although still crashes a lot. I have been unable to access the inventory on a rocket that has made it into space and returned.

**Comment by zmaster587** [comment]
does this occur without sponge?

**Comment by Danickar** [comment]
Without Sponge it still does occur. We have been using the various hatches/unloaders to access the rockets internal inventories now.

**Comment by zmaster587** [comment]
What about without buildcraft?

**Comment by zmaster587** [comment]
dupe of #972
