### ISSUE TITLE
No moons or planets

### ISSUE THREAD

**Issue by JackOperations** [zmaster587/AdvancedRocketry#994]
Minecraft Version:
-1.11.2
Forge Version:
-13.20.1.2429
Advanced Rocketry Version:
-1.2.5a
LibVulpes Version:
-0.2.6
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
Whenever I chose the planet select option in the rocket, no planet or moon other than Earth shows up

**Comment by dmodoomsirius** [comment]
in the planetDef.xml inside the saves/advRocketry folder if isKnown is false then the planet will now show up by default.

**Comment by TheAwesomeGem** [comment]
Seems fine for me.

**Comment by JackOperations** [comment]
![untitled](https://user-images.githubusercontent.com/30197336/34162254-ef9e5f06-e4ca-11e7-8397-73a54df437b3.png)

I can only see Earth on the planet select screen

**Comment by JackOperations** [comment]
Wait a minute, problem solved. I just deleted the planetDefs.xml and restarted Minecraft. They are here now

**Comment by zmaster587** [comment]
The planet def you have there looks like it should have both the Earth and Mars (if galacticraft is installed).  but because the orbital distance for mars is the same as that of earth, earth will appear to be on top of mars making mars invisible in the planet selector.
