### ISSUE TITLE
Advanced Rocketry Biome IDs

### ISSUE THREAD

**Issue by JackOperations** [zmaster587/AdvancedRocketry#996]
Can someone please tell me what the biomes advanced rocketry adds and their ID's?

**Comment by zmaster587** [comment]
It'll be in the advRocketry/advancedRocketry.cfg in the biomes category, but in the latest builds 110 though 118 are occupied by default

**Comment by thiago1255** [comment]
> It'll be in the advRocketry/advancedRocketry.cfg in the biomes category, but in the latest builds 110 though 118 are occupied by default

I cannot find the IDs in the mod settings. Where can I find ?
