### ISSUE TITLE
Crash in Chemical Reactor

### ISSUE THREAD

**Issue by kungfunick123** [zmaster587/AdvancedRocketry#997]
Minecraft Version:
- 1.12
Forge Version:
- 14.23.1.2562
Advanced Rocketry Version:
- 1.2.6-5
LibVulpes Version:
- 1.12.2-0.2.7-19
**is this the latest curseforge build?**
Yes
#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail: I can't really pastebin anything atm because I'm on a server and 
there's nobody on to start to reset before the issue. But, I have 2 chemical reactors
in my base and the fluid input hatches for some reason turned invisible. This was a day
after I tried to turn them on and the second I clicked the power button I crashed. But,
when I broke one of the input hatches and put it back and went to open the machine
so it would build, it crashed the server and appears to have corrupted the chunk.

**Comment by zmaster587** [comment]
I'm sorry, but i cannot do anything without a crash report, or minimally a method to reproduce the error on my end

**Comment by EarthwormO** [comment]
I am able to reproduce the crash, and have done so a few times.  For me I thought it was crashing using a Server to pull the liquid from the Electrolyzer, but it is apparently on the Chemical Reactor as this paste shows:

https://pastebin.com/iWp2Zt7U

I tried using both thermal expansion Fluiducts and Extra Utilities Pipes to get the fluid in.  Piping 1 of the fluids doesn't seem to crash, only when both fluids are present.  Mine crashes without even turning the Reactor on, just having the Oxygen enter it, crashes the server, and I have to go back to the last backup.

**Comment by zmaster587** [comment]
Ah alright, I actually just finished this issue 20 minutes ago actually since #999 also mentioned the same crash.  So everything should be good in the next build.
