### ISSUE TITLE
Microwave Receiver Producing 0 rf/t

### ISSUE THREAD

**Issue by greenking13** [zmaster587/AdvancedRocketry#998]
Minecraft Version:
-1.12.2
Forge Version:
-I believe it's something like 2565.
Advanced Rocketry Version:
-1.2.6-7
LibVulpes Version:
-0.2.7-19
**is this the latest curseforge build?**
No. A modpack update will occur later today, and I will verify this issue still occurs at that time.

So this isn't a crash, but instead that the Microwave Receiver is producing no rf/t even with the inclusion of 1 satellite with power producing capabilities (aka one with a microwave transmitter) sat chip in a input hatch slot. The only real defining variation than normal is that we renamed the starting planet, but I would assume that the satellite orbits the dimension. I'm honestly unsure what the issue could be, but after watching a few videos and looking into the past issues, this seems to be a recurring issue.
So until such a point in which this can be labelled fully as a bug, what would you like me to post in addition to the above details?

**Comment by zmaster587** [comment]
Would you be able to get items in the satellite or alternatively upload the world/advRocketry/temp.dat and provide the satellite id number so we can rule out lack of power production as a possibility?  

If you build a satellite with the microwave transmitter and fill it with Large Solar Panels does this still occur?

**Comment by greenking13** [comment]
Until such a point that my server manager logs in later today/tomorrow, I won't be able to upload said file. I will now go into an sp world and build the exact same system via creative.,,
![2017-12-21_03 15 42](https://user-images.githubusercontent.com/9355993/34248930-5cfb3b04-e5fd-11e7-9355-3a64df4550db.png)
![2017-12-21_03 15 38](https://user-images.githubusercontent.com/9355993/34248931-5d09197c-e5fd-11e7-9b0e-33bc04efcd02.png)

[temp.zip](https://github.com/zmaster587/AdvancedRocketry/files/1578596/temp.zip)


The satellite should be the only one within that file, ID:0. The satellite was made the same as the mp version, 2 large solar panels, 1 of the T2 batteries, and 3 data chips.

**Comment by zmaster587** [comment]
There should at minimum be a beam of light when turned on.

**Comment by zmaster587** [comment]
for some reason the power storage size on the satellite is 0, that' shouldn't be happening

**Comment by zmaster587** [comment]
Turns out max data was being set for power storage in satellites that accept data.  Fix for next build.

**Comment by greenking13** [comment]
Awesome, nice that that was fixed. :)
