### ISSUE TITLE
Mining Rockets stopping at Build Limit instead of returning

### ISSUE THREAD

**Issue by Danickar** [zmaster587/AdvancedRocketry#999]
Minecraft Version:
-1.12.2
Forge Version:
-Tried under multiple builds of Forge
Advanced Rocketry Version:
-1.2.6-25
LibVulpes Version:
-0.2.6-16
**is this the latest curseforge build?**
No and Yes

Explain issue in detail:
Every mining rocket sent up stops at the build limit (256) on its way back down. I have no idea why this happens. 

Every now and then, the mining rocket doesn't do its mission, just goes up and comes back down. When this happens, the rocket returns all the way to the launchpad. 

I tried the latest build of AR, but it caused an index out of bounds crash every time I opened/interacted with any multiblock machine, so I had to roll that back.

**Comment by zmaster587** [comment]
does the issue occur every time, or some of the time?

can you send the crash report you're getting with the latest build?  All the 1.2.x builds should be compatible

**Comment by Danickar** [comment]
Yes, it happens every time the rocket is on a mining mission. Just to test different things, I have tried different areas, biomes, launch pads at various heights to see if any of that made a difference.

I will reinstall the latest build and try it and get the crash reports.

**Comment by zmaster587** [comment]
I'm not able to replicate this on my end, are you running any other mods?  What's the most recent build of forge you tried with?

**Comment by Danickar** [comment]
https://pastebin.com/r0YLbt6K

This is the index out of bounds I am getting when I updated to the most recent version of AR and its Lib.

I crashed before I could test the rocket to see if it comes back. Still working on testing that piece.

**Comment by Danickar** [comment]
Ok, just sent two rockets up. 1 vanished completely after it finished its mission. No return, just gone and the monitor was no longer tracking it. The other stopped again at build height.

I know there isn't a lot to go on since it isn't giving any kind of crash to look at.

I have tried this with most versions of Forge from 2566 through today's release of 2578.

**Comment by zmaster587** [comment]
I noticed you're running sponge in the crash report you gave me, unfortunately there is a lot of known issues when sponge is used with Advanced rocketry, can you test without sponge installed?

**Comment by Danickar** [comment]
It will be later tonight before I can do that, but yes, I can see what happens when I take Sponge out, not a problem.

**Comment by zmaster587** [comment]
Alright, I also just got a chance to look at the code for the crash report and will have that crash fixed shortly.

**Comment by Danickar** [comment]
Taking Sponge off the server proved to be more difficult than I thought it would be...

That aside, removing Sponge did solve the issue of rockets not returning to the launchpad. I did however have to roll back to the previous version of AR because the IndexOutOfBounds issue was keeping the server from even launching. I know you said you are working on that piece.

Your mod is amazing by the way.  I just wanted to say thank you for all your hard work.

**Comment by zmaster587** [comment]
Alright, unfortunately due to the shear volume of bugs with advanced rocketry itself I cannot get to sponge compat for a while, I hope you understand.

Thanks for the complements, it really means a lot to me that you like the mod.  I've actually got a whole game in development with a similar concept, minecraft unfortunately has a lot of limitations, especially with performance and dimloading.

**Comment by Danickar** [comment]
I run a server for my students and they wanted to keep AR over the few things we used that required Sponge, so Sponge has been removed from my server permanently. I completely understand why don't have time to get to the compat issues right now and honestly don't blame you. Sponge seems very wonky at best.

**Comment by phit** [comment]
you need to disable entity activation for the AR rockets in the Sponge global.conf this is not a bug on either end..

**Comment by fusionmc-evilscoop** [comment]
disable entity activation is only in sponge 1.12 so doesnt help on issue 975

**Comment by phit** [comment]
what? that setting has existed since 1.8.9 at least, [here are the 1.10 docs on it](https://docs.spongepowered.org/5.1.0/en/server/getting-started/configuration/sponge-conf.html?highlight=entity%20activation%20range)

**Comment by fusionmc-evilscoop** [comment]
do you mean entity activation range, otherwise im not seeing it, and if you did, say that not abbreviate

**Comment by phit** [comment]
yes, disable entity activation range for the rocket entity

```
    entity-activation-range {
        # If enabled, newly discovered entities will be added to this config with a default value.
        auto-populate=true
        # Default activation ranges used for all entities unless overridden.
        defaults {
            ambient=32
            aquatic=32
            creature=32
            misc=16
            monster=32
        }
        # Per-mod overrides. Refer to the minecraft default mod for example.
        mods {
            advancedrocketry {
                defaults {
                    misc=0
                }
                # Set to false if you want mod to ignore entity activation rules and always tick.
                enabled=false
                entities {
                    mountdummy=0
                    rocket=0
                }
            }
        }
    }
```

**Comment by fusionmc-evilscoop** [comment]
aha will try that in the morn when i update the mod to latest
fingers crossed, and thx

**Comment by fusionmc-evilscoop** [comment]
helped but now a different issue :D

**Comment by dmodoomsirius** [comment]
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.
